codice/ddf

distribution/ddf-common/src/main/resources/NOTICE
distribution/ddf-common/src/main/resources/etc/custom.properties

- TikaInputTransformer can handle j2k now.
- Add a post query plugin to convert incoming j2k.

DDF-1016 Add support for converting j2k thumbnails.

---

distribution/ddf-common/src/main/resources/etc/certs/CertNew.sh
distribution/ddf-common/src/main/resources/etc/certs/openssl-demo.cnf

- handle index.txt* files better
- handle serial* files better
- fix message type in .cnf

DDF-1047 Fix cert generation.

---

docs/src/main/resources/Managing.adoc

Updated document with content from the 'How-to articals -> Configure DDF with New Certificates' section. Added content form other sources along with some notes/comments.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/34)

DDF-1195 Updated Managing.adoc with 'Configuring DDF with New Certificate' section

---

test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/AbstractIntegrationTest.java
test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestFederation.java

Also updated setFanout() method to accept a boolean so you can turn fanout on and off.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/39)

DDF-1200 - Added positive test case for fanout

---

distribution/install-profiles/src/main/resources/features.xml

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/40)

Ddf 1215 added spatial app to standard ddf install profile

---

docs/src/main/resources/Managing.adoc

@shaundmorris 
Tracy found an issue with the new cert documentation. This pull request is to fix it.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/43)

DDF-1195 Fixed copy/paste error with ws_security config file content

---

test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/AbstractIntegrationTest.java
test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestFederation.java

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/42)

DDF-1200: Initial set of Fanout tests

---

docs/src/main/resources/Extending.adoc
docs/src/main/resources/Managing.adoc

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/48)

DDF-1190 - Updated AsciiDoc for Java 8

---

distribution/test/itests/pom.xml
distribution/test/itests/test-itests-catalog/pom.xml
distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/AbstractIntegrationTest.java
distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestCatalog.java
distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestFederation.java
distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestSecurity.java
distribution/test/itests/test-itests-common/pom.xml
distribution/test/itests/test-itests-common/src/test/java/ddf/common/test/AfterExam.java
distribution/test/itests/test-itests-common/src/test/java/ddf/common/test/BeforeExam.java
distribution/test/itests/test-itests-common/src/test/java/ddf/common/test/PaxExamRule.java
distribution/test/itests/test-itests-common/src/test/java/ddf/common/test/PaxExamRuleTest.java

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/55)

DDF-1289 Added BeforeExam and AfterExam annotations

---

distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestSecurity.java

@pklinef 
@kcwire 
@stustison 
Easiest PR ever.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/62)

DDF-1289 Whitespace change to conform with standards.

---

distribution/test/pom.xml

@figliold: Can you do a quick review and merge to master?
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/63)

Updated ddf-parent version to 3.0.3-SNAPSHOT in distribution/test/pom.xml

---

distribution/docs/src/main/resources/Extending.adoc

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/64)

DDF-1211: fix for ditaa error that breaks in Java 8.

---

pom.xml
sdk/sample-soap-endpoint/pom.xml

Also had a reference to a 2.7.0-SNAPSHOT that needed to be updated.
@pklinef 
@lessarderic 
@mverret 
@stustison
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/67)

DDF-1310 Integration test dependency on sdk, order swap

---

distribution/ddf/pom.xml

This is breaking our builds at the moment.
@AzGoalie 
@pklinef 
@lessarderic 
@tbatieConnexta 
@djblue 
@rzwiefel
@roelens8
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/69)

DDF-1330 Updating from a superseded SNAPSHOT version of opendj.

---

distribution/pom.xml

- Removed ddf-release profile
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/68)

DDF-1329: Remove unused DDF maven profiles

---

distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/AbstractIntegrationTest.java

@shaundmorris
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/72)

DDF-1349: Fixed sdk version in AbstractIntegrationTest to fix failing itests

---

distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/AbstractIntegrationTest.java
distribution/webconsole-branding/pom.xml

- Changed version that contained embedded jars with security vulnerabilities.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/66)

DDF-1305: Address all high severity CLM vulnerabilities

---

distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/Library.java
distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestCatalog.java

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/76)

DDF-1259 - added integration test for CSW Ingest

---

distribution/docs/src/main/resources/ExtContents.adoc

DDF-1360 updated documentation for the simple authz realm to cover the new policy extension interface

---

distribution/ddf-common/src/main/resources/etc/jmx.acl.whitelist.cfg
distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestFederation.java

@mverret will hero
@pklinef 
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/75)

DDF-1343: Updated mbean whitelist

---

distribution/docs/src/main/resources/ExtContents.adoc

@clockard @ricklarsen @djblue
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/86)

DDF-1377 updated security diagrams

---

catalog/catalog-app/src/main/resources/features.xml
catalog/core/catalog-core-app/src/main/resources/features.xml
catalog/core/catalog-core-solrcommands/pom.xml
catalog/core/catalog-core-solrcommands/src/main/java/org/codice/ddf/commands/solr/BackupCommand.java
catalog/core/catalog-core-solrcommands/src/main/java/org/codice/ddf/commands/solr/SolrCommands.java
catalog/core/catalog-core-solrcommands/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/core/pom.xml
distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestSolrCommands.java

@kcwire 
@jlcsmith 
@millerw8 
@beyelerb 
@jrnorth 
@kguerriero
@emanns95
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/88)

DDF-439 added integration test to verify solr:backup command

---

catalog/admin/module/catalog-admin-module-sources/src/main/java/org/codice/ddf/catalog/admin/plugin/AdminSourcePollerServiceBean.java
catalog/docs/src/main/resources/ExtContents.adoc

Allows for factoryPids that don't end in Source or Service
@mverret Will hero
@shaundmorris 
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/92)

DDF-1343: Updated ldap filter to look at the whole string and updated documentation

---

distribution/ddf/src/main/filtered-resources/etc/ddf.platform.config.cfg

- This solves the issue of certain things not working out of the box.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/99)

DDF-1398 Changes default host for installer from 0.0.0.0 to localhost

---

distribution/docs/src/main/resources/ManContents.adoc

@stustison @ricklarsen @clockard @brianfelix @shaundmorris 
Review changes to the documentation.
Build the PDF and HTML files from the ASCII Doc files.
Open the generated PDF or HTML file (ddf/distribution/docs/target/docs).
All changes are within the section titled "Configure DDF with New Certificates".
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/96)

Ddf 1383 certificates documentation update

---

platform/security/policy/security-policy-context/pom.xml
platform/security/policy/security-policy-context/src/main/java/org/codice/ddf/security/policy/context/impl/PolicyManager.java
platform/security/policy/security-policy-context/src/test/java/org/codice/security/policy/context/PolicyManagerTest.java

@pklinef, @stustison, please review.
@figliold, you're my hero :-)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/95)

DDF-1145: Added null check to setPolicies() method to prevent NullPointerException and added extra logging statements.

---

catalog/spatial/spatial-commands/src/main/java/org/codice/ddf/commands/spatial/geonames/GeoNamesUpdateCommand.java

@millerw8 @jlcsmith @kcwire @wmcnalli @beyelerb @emanns95 @kguerriero @shane-voisard
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/93)

DDF-1386: Fix intermittent test failure

---

README.md

Makes changes to the readme file of the DDF's How-to-build section.
@coyotesqrl
@andrewkfiedler is the hero!
@pklinef 
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/110)

DDF-1406 Fixes minor issues in deployment notes in README

---

catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/actions/ActionRegistryImpl.java
catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/controller/SearchController.java

@ricklarsen, @stustison, @djblue, please review this pull request.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/108)

DDF-1410: Update to have a unique list of actions displayed.

---

catalog/ui/search-ui/search-ui-app/src/main/resources/features.xml

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/119)
@millerw8 @jlcsmith @kcwire @wmcnalli @beyelerb @emanns95 @kguerriero @shane-voisard

DDF-1418: Fix search-ui-app install failure

---

distribution/sdk/pom.xml
distribution/sdk/sample-metacard-filter/pom.xml
distribution/sdk/sample-metacard-filter/src/main/java/ddf/sdk/plugin/filter/FilterPostQueryPlugin.java
distribution/sdk/sample-metacard-filter/src/main/resources/OSGI-INF/blueprint/blueprint.xml
distribution/sdk/sample-metacard-filter/src/main/resources/features.xml
distribution/sdk/sdk-app/src/main/resources/features.xml
distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestCatalog.java

@garrettfreibott will hero
@stustison 
@rzwiefel
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/107)

DDF-1399: Added integration test for filter plugin

---

platform/docs/src/main/resources/IntContents.adoc

- Provies users with a way to learn how to configure the Platform UI Settings.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/125)

DDF-1439 Adds documentation for Platform UI Settings

---

catalog/ui/search-ui/standard/src/main/webapp/js/model/Query.js
catalog/ui/search-ui/standard/src/main/webapp/js/view/Query.view.js
catalog/ui/search-ui/standard/src/main/webapp/js/view/SearchControl.view.js
catalog/ui/search-ui/standard/src/main/webapp/js/view/WorkspaceControl.view.js
catalog/ui/search-ui/standard/src/test/js/wd/search.js

Reset the query object's filter when going back to the original search panel and added functional tests.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/121)

DDF-1385: Fixed enhanced search querying

---

catalog/opensearch/catalog-opensearch-source/src/main/resources/META-INF/spring/beans.xml
distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/AbstractIntegrationTest.java
distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestFederation.java
distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestSecurity.java

Added integration tests to verify that BasicAuth is working for DDF clients. The tests set up sources and submit queries to ensure that given proper authentification the query can be completed, and with bad certification, it cannot.
@kcwire @jrnorth @kguerriero @jlcsmith  @millerw8 @beyelerb @wmcnalli 
Champ: @vinamartin
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/131)

DDF-1442: Added BasicAuth iTests

---

pom.xml

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/140)

DDF-1378 Update maven-javadoc-plugin to 2.10.3

---

catalog/spatial/csw/spatial-csw-common/pom.xml
catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/CswConstants.java
catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/transaction/CswAction.java
catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/transaction/CswTransactionRequest.java
catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/transaction/DeleteAction.java
catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/transaction/DeleteTransaction.java
catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/transaction/InsertAction.java
catalog/spatial/csw/spatial-csw-endpoint/pom.xml
catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java
catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/reader/TransactionMessageBodyReader.java
catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/reader/TransactionRequestConverter.java
catalog/spatial/csw/spatial-csw-endpoint/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/TestCswEndpoint.java
catalog/spatial/csw/spatial-csw-endpoint/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/reader/TestTransactionMessageBodyReader.java
catalog/spatial/csw/spatial-csw-transformer/pom.xml
catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/CswRecordConverter.java
catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/CswTransformProvider.java
catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/GetRecordsResponseConverter.java
catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/XStreamAttributeCopier.java
catalog/spatial/csw/spatial-csw-transformer/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/TestXStreamAttributeCopier.java
distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/Library.java
distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestCatalog.java

@millerw8 @jlcsmith @kcwire @wmcnalli @beyelerb @emanns95 @kguerriero @shane-voisard @bdeining
@kguerriero is the hero.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/126)

DDF-1261: Add support for CSW delete transaction

---

distribution/ddf-common/src/main/resources/etc/ws-security/attributeMap.properties
distribution/ddf/src/main/filtered-resources/etc/ddf.security.sts.anonymousclaims.cfg
platform/admin/core/admin-core-api/src/main/java/org/codice/ddf/ui/admin/api/AnonClaimsHandlerExt.java
platform/admin/core/admin-core-api/src/main/java/org/codice/ddf/ui/admin/api/ConfigurationAdmin.java
platform/admin/core/admin-core-api/src/main/java/org/codice/ddf/ui/admin/api/ConfigurationAdminMBean.java
platform/admin/core/admin-core-api/src/main/resources/OSGI-INF/blueprint/blueprint.xml
platform/admin/core/admin-core-api/src/test/java/org/codice/ddf/ui/admin/api/AnonClaimsHandlerExtTest.java
platform/admin/core/admin-core-api/src/test/java/org/codice/ddf/ui/admin/api/ConfigurationAdminTest.java
platform/admin/ui/server-impl.js
platform/admin/ui/src/main/webapp/js/models/Installer.js
platform/admin/ui/src/main/webapp/js/modules/Installer.module.js
platform/admin/ui/src/main/webapp/js/views/installer/AnonClaims.view.js
platform/admin/ui/src/main/webapp/js/views/installer/InstallerMain.view.js
platform/admin/ui/src/main/webapp/less/installer/style.less
platform/admin/ui/src/main/webapp/less/variables.less
platform/admin/ui/src/main/webapp/templates/installer/anonClaimProfiles.handlebars
platform/admin/ui/src/main/webapp/templates/installer/anonClaims.handlebars
platform/admin/ui/src/main/webapp/templates/installer/anonClaimsList.handlebars
platform/admin/ui/src/main/webapp/templates/installer/anonClaimsListHeader.handlebars
platform/admin/ui/src/main/webapp/templates/installer/anonClaimsTable.handlebars
platform/admin/ui/src/main/webapp/templates/installer/anonWarningModal.handlebars
platform/security/sts/security-sts-anonymousclaimshandler/src/main/resources/OSGI-INF/blueprint/blueprint.xml
platform/security/sts/security-sts-anonymousclaimshandler/src/main/resources/OSGI-INF/metatype/metatype.xml

- Added installer page after general configurations for anon claims handler
- Added extension to ConfigurationAdmin to support new functionality
- Removed 'uid' entry
@stustison @andrewkfiedler @djblue
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/124)

DDF-1393 Add anonymous user (base security) configuration to installer

---

README.md
distribution/docs/src/main/resources/ExtContents.adoc

Resolves DDF-1451 (https://codice.atlassian.net/browse/DDF-1451)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/136)

DDF-1451: Bump required maven version to 3.1.0

---

catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/TestSolrProvider.java

@lessarderic
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/162)

DDF-1413 updated solr unit test to verify ID's are correctly in the deleted list

---

catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/event/retrievestatus/DownloadsStatusEventListenerTest.java
catalog/core/catalog-core-urlresourcereader/pom.xml
catalog/core/catalog-core-urlresourcereader/src/main/java/ddf/catalog/resource/impl/URLResourceReader.java
catalog/core/catalog-core-urlresourcereader/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/core/catalog-core-urlresourcereader/src/main/resources/OSGI-INF/metatype/metatype.xml
catalog/core/catalog-core-urlresourcereader/src/test/java/ddf/catalog/resource/impl/ResourceReaderTest.java
catalog/docs/src/main/resources/ExtContents.adoc
catalog/spatial/ogc/spatial-ogc-urlresourcereader/pom.xml
catalog/spatial/ogc/spatial-ogc-urlresourcereader/src/main/java/org/codice/ddf/spatial/ogc/catalog/resource/impl/OgcUrlResourceReader.java
catalog/spatial/ogc/spatial-ogc-urlresourcereader/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/spatial/ogc/spatial-ogc-urlresourcereader/src/test/java/org/codice/ddf/spatial/ogc/catalog/resource/impl/TestResourceReader.java
distribution/ddf-common/pom.xml
distribution/ddf-common/src/main/resources/common-bin.xml
distribution/ddf-common/src/main/resources/data/products/README.txt
distribution/test/itests/test-itests-catalog/pom.xml
distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/AbstractIntegrationTest.java
distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestFederation.java
distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/UrlResourceReaderConfigurator.java

@pklinef @garrettfreibott @lessarderic @andrew-fiedler
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/149)

DDF-1467: Update UrlResourceReader to securely handle file protocol

---

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/CachingFederationStrategy.java

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/166)

DDF-1482: Removed XLoggerWrapper from CachingFederationSytrategyLogger

---

catalog/spatial/csw/spatial-csw-source/src/main/resources/OSGI-INF/metatype/metatype.xml
catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/main/resources/OSGI-INF/metatype/metatype.xml
platform/admin/ui/src/main/resources/OSGI-INF/metatype/metatype.xml
platform/platform-configuration/src/main/resources/OSGI-INF/metatype/metatype.xml
platform/security/handler/security-handler-anonymous/src/main/resources/OSGI-INF/metatype/metatype.xml

(Coordinate Order, Force Spatial Filter Type, Admin UI Style)
Tested on Internet Explorer, FireFox, and Chrome
@kcwire 
@jrnorth is hero
@jlcsmith 
@wmcnalli 
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/164)

DDF-1471 Fixed various default <select> options in the UI 

---

catalog/spatial/csw/spatial-csw-source/src/main/resources/OSGI-INF/metatype/metatype.xml
catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/main/resources/OSGI-INF/metatype/metatype.xml
platform/admin/ui/src/main/resources/OSGI-INF/metatype/metatype.xml
platform/platform-configuration/src/main/resources/OSGI-INF/metatype/metatype.xml
platform/security/handler/security-handler-anonymous/src/main/resources/OSGI-INF/metatype/metatype.xml

Reverts codice/ddf#164
This appears to be causing the integration tests to fail. I haven't figured out the root cause but would like to revert until it can be rectified.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/179)

Revert "DDF-1471 Fixed various default <select> options in the UI "

---

distribution/ddf/src/main/filtered-resources/etc/ddf.security.sts.anonymousclaims.cfg
platform/admin/ui/src/main/webapp/js/views/installer/AnonClaims.view.js

- Added logic to create configuration if none exists
- Removed anon claims config file
@kcwire @jrnorth can one of you guys hero this so we can verify it works with your system.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/178)

DDF-1496 Fixed Anon Claims installation page

---

catalog/spatial/docs/src/main/resources/IntContents.adoc

Added Documentation for CSW Transactions including the Update,Insert
and Delete sub operations with sample requests and responses.
@jrnorth @kguerriero @kcwire
hero is @jrnorth
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/182)

DDF-1480 - Documented CSW Transactions

---

catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/IngestCommand.java

@bdeining 
@jrnorth is hero
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/180)

DDF-1470 - Added a newline following successfull ingestion

---

catalog/spatial/csw/spatial-csw-source/src/main/resources/OSGI-INF/metatype/metatype.xml
catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/main/resources/OSGI-INF/metatype/metatype.xml
distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestFederation.java
platform/admin/ui/src/main/resources/OSGI-INF/metatype/metatype.xml
platform/platform-configuration/src/main/resources/OSGI-INF/metatype/metatype.xml
platform/security/handler/security-handler-anonymous/src/main/resources/OSGI-INF/metatype/metatype.xml

@kcwire 
@EIrwin is hero
@wmcnalli
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/186)

DDF-1471 Fixed various <select> default <option>s in the Admin UI.

---

catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/CswConstants.java
catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java
catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswExceptionMapper.java
catalog/spatial/csw/spatial-csw-endpoint/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/TestCswEndpoint.java
catalog/spatial/csw/spatial-csw-endpoint/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/TestCswExceptionMapper.java

@millerw8 
@jrnorth is hero
@kcwire 
@EIrwin
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/176)

DDF-1488 Errors encountered while processing CSW transaction requests should be handled according to the OGC specification

---

catalog/spatial/geocoding/pom.xml
catalog/spatial/geocoding/spatial-geocoding-api-impl/pom.xml
catalog/spatial/geocoding/spatial-geocoding-api-impl/src/main/java/org/codice/ddf/spatial/geocoding/context/impl/NearbyLocationImpl.java
catalog/spatial/geocoding/spatial-geocoding-api-impl/src/test/java/org/codice/ddf/spatial/geocoding/context/impl/NearbyLocationImplTest.java
catalog/spatial/geocoding/spatial-geocoding-api/pom.xml
catalog/spatial/geocoding/spatial-geocoding-api/src/main/java/org/codice/ddf/spatial/geocoding/GeoEntryQueryable.java
catalog/spatial/geocoding/spatial-geocoding-api/src/main/java/org/codice/ddf/spatial/geocoding/context/NearbyLocation.java
catalog/spatial/geocoding/spatial-geocoding-index/pom.xml
catalog/spatial/geocoding/spatial-geocoding-index/src/main/java/org/codice/ddf/spatial/geocoding/index/GeoNamesLuceneConstants.java
catalog/spatial/geocoding/spatial-geocoding-index/src/main/java/org/codice/ddf/spatial/geocoding/index/GeoNamesLuceneIndexer.java
catalog/spatial/geocoding/spatial-geocoding-query/pom.xml
catalog/spatial/geocoding/spatial-geocoding-query/src/main/java/org/codice/ddf/spatial/geocoding/query/GeoNamesQueryLuceneDirectoryIndex.java
catalog/spatial/geocoding/spatial-geocoding-query/src/main/java/org/codice/ddf/spatial/geocoding/query/GeoNamesQueryLuceneIndex.java
catalog/spatial/geocoding/spatial-geocoding-query/src/test/java/org/codice/ddf/spatial/geocoding/query/TestGeoNamesQueryLuceneIndex.java
catalog/spatial/pom.xml

Added to the GeoNames Query OSGi service.
@kcwire 
@EIrwin is the hero
@bdeining 
@wmcnalli
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/165)

DDF-1481: Add the capability to find the nearest cities to a metacard

---

catalog/spatial/geocoding/spatial-geocoding-geocoder/src/main/java/org/codice/ddf/spatial/geocoder/GeoCoder.java
catalog/spatial/geocoding/spatial-geocoding-geocoder/src/main/java/org/codice/ddf/spatial/geocoder/endpoint/GeoCoderEndpoint.java
catalog/spatial/geocoding/spatial-geocoding-localsearch/src/main/java/org/codice/ddf/spatial/geocoder/geonames/GeoNamesLocalIndex.java
catalog/spatial/geocoding/spatial-geocoding-websearch/src/main/java/org/codice/ddf/spatial/geocoder/geonames/GeoNamesWebService.java

This prevents the gazetteer search box from saying "(error)" if the user searches for a place that doesn't exist. Instead, it will say "(not found)".
@shane-voisard is the hero
@millerw8 
@dcruver
@jlcsmith
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/181)

DDF-1357: Prevent NullPointerException in GeoCoderEndpoint

---

distribution/ddf/pom.xml

- Using move causes issues during clean runs of release:prepare
https://codice.atlassian.net/browse/DDF-1503
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/188)

DDF-1503 Changes move to copy for doc inclusion

---

distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestSolrCommands.java

Refactored the test to make it pass :-)
I've ran the PR build for this change multiple times and the test hasn't failed a single time so I'm hoping this will take care of it.
@shaundmorris, @kcwire, @wmcnalli, please review. I'll merge to master as soon as it's been approved.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/197)

DDF-1491: Fix TestSolrCommands.testSolrBackupNumToKeep()

---

catalog/plugin/catalog-plugin-jpeg2000-thumbnail-converter/pom.xml
catalog/pom.xml

Updated mygrid repository URL in all the pom files that were using the
deprecated one.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/208)

DDF-1535: Update mygrid repository URL

---

distribution/ddf-common/pom.xml
distribution/ddf-common/src/main/resources/etc/system.properties
distribution/ddf/pom.xml
distribution/pom.xml
libs/common-system/pom.xml
libs/common-system/src/main/java/org/codice/ddf/configuration/SystemBaseUrl.java
libs/common-system/src/main/java/org/codice/ddf/configuration/SystemInfo.java
libs/common-system/src/test/java/org/codice/ddf/configuration/SystemBaseUrlTest.java
libs/pom.xml

First part of moving to using system properties in place of ConfigurationWatcher.
@djblue @vinamartin @pklinef
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/200)

DDF-1522 Added platform global config values to system properties.

---

distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestSecurity.java

@lessarderic 
@pklinef 
@coyotesqrl
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/221)

DDF-1442 uncommented commented out test

---

platform/security/sts/security-sts-realm/src/main/java/ddf/security/realm/sts/AbstractStsRealm.java
platform/security/sts/security-sts-realm/src/test/java/ddf/security/realm/sts/TestStsRealm.java

@lessarderic 
@pklinef 
@coyotesqrl
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/224)

DDF-1500 fixed setClaims method that had incorrect string parsing logic and added test

---

catalog/spatial/csw/spatial-csw-endpoint/pom.xml
catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java
catalog/spatial/csw/spatial-csw-endpoint/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/TestCswEndpoint.java
catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/transformer/CswQueryResponseTransformer.java
catalog/spatial/csw/spatial-csw-transformer/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/transformer/TestCswQueryResponseTransformer.java
distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/Library.java
distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestCatalog.java

@wmcnalli is the hero
@kcwire 
@bdeining
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/191)

DDF-1504: Fix NullPointerException in GetRecordById

---

platform/security/core/security-core-impl/src/main/java/ddf/security/common/util/Security.java
platform/security/core/security-core-impl/src/test/java/ddf/security/common/util/SecurityTest.java

@lessarderic 
@coyotesqrl 
@pklinef
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/226)

DDF-1468 changed alias method to pull from system property to avoid potential race condition with config admin

---

distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestFederation.java

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/236)

DDF-1554 Wait for all sources to be available after disabling fanout

---

platform/security/sts/security-sts-ldapclaimshandler/pom.xml
platform/security/sts/security-sts-ldapclaimshandler/src/main/java/ddf/security/sts/claimsHandler/LdapClaimsHandler.java
platform/security/sts/security-sts-ldapclaimshandler/src/test/java/ddf/security/sts/claimsHandler/LdapClaimsHandlerTest.java
platform/security/sts/security-sts-ldaplogin/pom.xml
platform/security/sts/security-sts-ldaplogin/src/main/java/ddf/ldap/ldaplogin/SslLdapLoginModule.java
platform/security/sts/security-sts-ldaplogin/src/test/java/ddf/ldap/ldaplogin/SslLdapLoginModuleTest.java

Added code fix to check bind status after call
and added 2 new test classes to test bind failures
in their corresponding classes.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/198)

DDF-1521 Added code fix and tests

---

README.md
catalog/ui/search-ui/search-endpoint/pom.xml
distribution/ddf-common/src/main/resources/bin/setenv.bat
distribution/docs/src/main/resources/ExtContents.adoc
distribution/docs/src/main/resources/ManContents.adoc
distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/AbstractIntegrationTest.java
distribution/webconsole-branding-plugin/pom.xml
libs/httpproxy/README.md
platform/mime/core/platform-mime-core-impl/src/main/java/ddf/mime/mapper/MimeTypeToTransformerMapperImpl.java
pom.xml

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/199)

DDF-1527 Updated to Java 8 from 7

---

platform/security/cas/security-cas-client/pom.xml
platform/security/cas/security-cas-client/src/test/java/org/codice/ddf/security/handler/cas/CasHandlerTest.java
platform/security/cas/security-cas-impl/pom.xml
platform/security/cas/security-cas-tokenvalidator/pom.xml
platform/security/pom.xml

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/237)

DDF-1500 remove vestigial sts-clientconfig dependencies

---

catalog/opensearch/catalog-opensearch-source/src/main/java/ddf/catalog/source/opensearch/OpenSearchSource.java
distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestSecurity.java
platform/security/rest/security-rest-cxfwrapper/src/main/java/org/codice/ddf/cxf/SecureCxfClientFactory.java

@kcwire 
@mverret  will hero
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/196)

Ddf 1518: Updated SecureCxfClientFactory to inherit headers

---

catalog/ui/search-ui/standard/src/main/webapp/js/widgets/filter.cesium.geometry.group.js

@millerw8 is the hero
@dcruver 
@stustison 
@pklinef
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/209)

DDF-1538: Old geos are cleared when drawing a new geo after a search (in the Cesium map)

---

catalog/ui/search-ui/standard/src/main/webapp/js/controllers/openlayers.controller.js
catalog/ui/search-ui/standard/src/main/webapp/js/view/openlayers.metacard.js

@kcwire is the hero
@EIrwin 
@stustison 
@pklinef
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/193)

DDF-1509: Prevent selecting multiple records when they overlap (in the OpenLayers 2D map)

---

catalog/rest/catalog-rest-endpoint/src/main/java/org/codice/ddf/endpoints/rest/action/MetacardTransformerActionProvider.java

@EIrwin is hero
@wmcnalli
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/228)

DDF-1551 Fixed typo in action description

---

catalog/ui/search-ui/standard/src/main/webapp/js/model/Query.js
catalog/ui/search-ui/standard/src/main/webapp/js/view/Query.view.js
catalog/ui/search-ui/standard/src/main/webapp/js/widgets/cesium.bbox.js
catalog/ui/search-ui/standard/src/main/webapp/js/widgets/openlayers.bbox.js
catalog/ui/search-ui/standard/src/test/js/wd/usng.js

Code changes to UI to accommodate the fixes to the USNG library that are a part of this ticket. 
https://github.com/codice/usng.js/pull/4
@AzGoalie @mverret @shaundmorris @brendan-hofmann 
@andrewkfiedler is hero
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/225)

DDF-1543 UI changes that accompany fix to USNG

---

catalog/transformer/catalog-transformer-service-atom/src/test/java/ddf/catalog/transformer/response/query/atom/TestAtomTransformer.java

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/247)

DDF-1523: Mocked SystemInfo for unit test

---

catalog/ui/search-ui/standard/bower.json

in our most recent changes, we were waiting on USNG to update. this will pull in the most recent changes
@shaundmorris
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/249)

DDF-1543 Update USNG version dependency

---

catalog/spatial/csw/spatial-csw-endpoint/pom.xml
catalog/spatial/csw/spatial-csw-schema-bindings/pom.xml
catalog/spatial/csw/spatial-csw-source/pom.xml
catalog/spatial/csw/spatial-csw-transformer/pom.xml
catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/GetRecordsResponseConverter.java
catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/transformer/CswQueryResponseTransformer.java
catalog/spatial/csw/spatial-csw-transformer/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/TestGetRecordsResponseConverter.java
catalog/spatial/spatial-app/src/main/resources/features.xml
distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestCatalog.java

Additionally had to make some refactorings in order to not use
embeeded classes due to failed equality comparisons with serialized
ResultType class.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/240)

DDF-1507 Added Fix for CSW ResultType query and related iTests

---

distribution/ddf/pom.xml

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/258)

DDF-1556: added docs inclusion in distro part of documentation profile

---

distribution/ddf/src/main/filtered-resources/etc/ddf.platform.config.cfg
platform/admin/ui/src/main/webapp/js/views/installer/Configuration.view.js
platform/admin/ui/src/main/webapp/js/views/installer/InstallerMain.view.js
platform/admin/ui/src/main/webapp/templates/installer/configuration.handlebars
platform/admin/ui/src/main/webapp/templates/installer/navigationButtons.handlebars
platform/platform-configuration/src/main/resources/OSGI-INF/metatype/metatype.xml

@shaundmorris @andrewkfiedler 
This change should only be merged after https://github.com/codice/ddf/pull/248 is merged.
This is a temporary fix until we get the full installation config pages added.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/257)

DDF-1569 Removed configuration page and added a config info page.

---

distribution/docs/src/main/resources/ManContents.adoc

@shaundmorris can you take a quick look at this and let me know if there are any other places that need to be updated as well.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/254)

DDF-1568 Update docs with system property changes

---

catalog/spatial/ogc/spatial-ogc-common/src/test/java/org/codice/ddf/spatial/ogc/catalog/common/TestTrustedRemoteSource.java
distribution/ddf-common/src/main/resources/etc/system.properties
platform/admin/core/admin-core-insecuredefaults/src/main/java/org/codice/ddf/admin/insecure/defaults/service/KeystoreValidator.java
platform/admin/core/admin-core-insecuredefaults/src/test/java/org/codice/ddf/admin/insecure/defaults/service/KeystoreValidatorTest.java
platform/metrics/platform-metrics-webconsole-plugin/src/main/java/ddf/metrics/plugin/webconsole/MetricsWebConsolePlugin.java
platform/security/certificate/security-certificate-generator/pom.xml
platform/security/certificate/security-certificate-generator/src/main/java/org/codice/ddf/security/certificate/generator/KeyStoreFile.java
platform/security/certificate/security-certificate-generator/src/test/java/org/codice/ddf/security/certificate/generator/KeyStoreFileTest.java
platform/security/platform-security-core-api/src/main/java/ddf/security/SecurityConstants.java
platform/security/platform-security-core-api/src/main/java/ddf/security/settings/SecuritySettingsService.java
platform/security/platform-security-settings/src/main/java/ddf/security/settings/impl/SecuritySettingsServiceImpl.java
platform/security/platform-security-settings/src/test/java/ddf/security/settings/impl/KeystoreFormatTest.java
platform/security/platform-security-settings/src/test/java/ddf/security/settings/impl/SecuritySettingsServiceImplTest.java

Add system property for truststore type
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/256)

DDF-1534 p12-keystore-types

---

catalog/ui/search-ui/standard/src/main/doc/help.adoc

@dcruver 
@shane-voisard
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/242)

DDF-1561 Fixed minor typos in the Standard Search UI help.

---

catalog/ui/search-ui/standard/src/main/webapp/js/view/filter/FilterLayout.view.js

@wmcnalli 
@shane-voisard is hero
@dcruver
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/250)

DDF-1562 Fixed geo during searches with multiple filters on the OpenLayers/Cesium maps

---

catalog/ui/search-ui/standard/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/ui/search-ui/standard/src/main/resources/OSGI-INF/metatype/metatype.xml

@kcwire is the hero
@EIrwin
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/268)

DDF-1575: Update default Cesium terrain provider URL

---

platform/security/core/security-core-impl/pom.xml
platform/security/core/security-core-impl/src/main/java/ddf/security/ws/policy/impl/PolicyWSDLGetInterceptor.java
platform/security/core/security-core-impl/src/test/java/ddf/security/ws/policy/impl/PolicyTest.java
platform/security/platform-security-core-api/src/main/java/ddf/security/sts/client/configuration/StsAddressProvider.java
platform/security/sts/security-sts-realm/pom.xml
platform/security/sts/security-sts-realm/src/main/java/ddf/security/realm/sts/StsAddressProviderImpl.java

Changed the issuer address in WSDL's to respect the address in Platform
Global config.
@stustison @coyotesqrl @tbatie @djblue @roelens8
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/154)

DDF-1473 - Issuer address should reflect Platform Global Config

---

platform/security/docs/src/main/resources/IntContents.adoc

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/259)

DDF-1519 Added documentation for IdP support

---

catalog/ui/search-ui/standard/pom.xml
platform/admin/ui/pom.xml

@roelens8 is the hero
@ricklarsen 
just change the pom in /Users/ryanyeats/ddf/ddf/catalog/ui/search-ui/standard so it builds faster when you use the skipTests flag
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/271)

DDF-1579 Fix skipTests flag for search ui unit tests

---

distribution/ddf/pom.xml
distribution/docs/src/main/resources/Managing.adoc

- Update documentation to explain CRL configuration for
web context paths
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/270)

DDF-1506: CRL Documentation Update

---

catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/data/impl/BasicTypes.java
catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/data/impl/MetacardImpl.java
catalog/core/catalog-core-api-impl/src/test/java/ddf/catalog/data/impl/MetacardImplTest.java
catalog/core/catalog-core-api/src/main/java/ddf/catalog/data/Metacard.java
catalog/transformer/catalog-transformer-xml/src/main/java/ddf/catalog/transformer/xml/adapter/AdaptedMetacard.java
catalog/transformer/catalog-transformer-xml/src/main/java/ddf/catalog/transformer/xml/adapter/StringxmlAdapter.java
catalog/transformer/catalog-transformer-xml/src/test/java/ddf/catalog/transform/xml/TestXmlInputTransformer.java
catalog/transformer/catalog-transformer-xml/src/test/resources/metacard1.xml
catalog/transformer/catalog-transformer-xml/src/test/resources/unknownMetacard1.xml

@kcwire 
@wmcnalli 
@shane-voisard is hero
@dcruver
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/241)

DDF-1556 Added description field to basic metacard type

---

distribution/ddf-common/src/main/resources/etc/system.properties
platform/security/common/src/main/java/org/codice/ddf/security/common/jaxrs/RestSecurity.java
platform/security/rest/security-rest-cxfwrapper/pom.xml
platform/security/rest/security-rest-cxfwrapper/src/main/java/org/codice/ddf/cxf/SecureCxfClientFactory.java

@pklinef
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/251)

DDF-1545 - do not require https for basic auth header

---

distribution/docs/src/main/resources/ManContents.adoc

-Adds notes on why and how to configure STS Subject DN constraints
@ricklarsen @stustison @djblue 
Make sure I don't have any typos. 
Also would love some advice on how to word this better.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/273)

DDF-1532: Documentation for Subject DN Constraints

---

pom.xml

Turned off FindBugs and PMD profiles by default.
@figliold: Hero!
@oconnormi: please take a quick look.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/276)

DDF-1582: Disable static analysis tools by default until we're ready to start using them

---

distribution/docs/src/main/resources/ManContents.adoc

Corrected error given in JIRA ticket.
NOTE: I expect this and other section of the documentation will change radically because of the keystore editor and certificate generator. 
In the interest of small and frequent commits, I am creating the pull request now as opposed to waiting for the future changes to be implemented.
@ricklarsen @spearskw
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/277)

DDF-1583-correct-certificate-configuration-documentation

---

platform/security/docs/src/main/resources/IntContents.adoc

@stustison @clockard @vinamartin @djblue
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/294)

DDF-1606: added note to security docs for claims handlers.

---

platform/security/core/security-core-impl/src/main/java/ddf/security/impl/SubjectImpl.java
platform/security/handler/security-handler-anonymous/src/main/java/org/codice/ddf/security/handler/anonymous/AnonymousHandler.java
platform/security/handler/security-handler-anonymous/src/test/java/org/codice/ddf/security/handler/anonymous/AnonymousHandlerTest.java
platform/security/handler/security-handler-api/src/main/java/org/codice/ddf/security/handler/api/AnonymousAuthenticationToken.java
platform/security/handler/security-handler-api/src/test/java/org/codice/ddf/security/handler/api/AnonymousAuthenticationTokenTest.java
platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/server/IdpEndpoint.java
platform/security/interceptor/security-interceptor-anonymous/src/main/java/org/codice/ddf/security/interceptor/AnonymousInterceptor.java
platform/security/platform-security-core-api/src/main/java/ddf/security/principal/AnonymousPrincipal.java
platform/security/sts/security-sts-anonymousclaimshandler/pom.xml
platform/security/sts/security-sts-anonymousclaimshandler/src/main/java/org/codice/ddf/security/claims/anonymous/AnonymousClaimsHandler.java
platform/security/sts/security-sts-anonymousclaimshandler/src/test/java/org/codice/ddf/security/claims/anonymous/AnonymousClaimsHandlerTest.java
platform/security/sts/security-sts-anonymousvalidator/src/main/java/org/codice/ddf/security/validator/anonymous/AnonymousValidator.java
platform/security/sts/security-sts-anonymousvalidator/src/test/java/org/codice/ddf/security/validator/anonymous/AnonymousValidatorTest.java

- Updated AnonymousInterceptor to cache subjects based on ip
- Updated IdpEndpoint, AnonymousValidator and AnonymousHandler to pass in ip address to anon token
@stustison @tbatie
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/278)

DDF-1578 Added ipAddress field to AnonymousAuthenticationToken

---

platform/metrics/platform-metrics-collector/src/test/java/ddf/metrics/collector/rrd4j/RrdJmxCollectorTest.java

- Changed the naming of the rrd files created in the tests to reflect the test running them so they are unique.@pklinef @coyotesqrl @ryeats
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/304)

DDF-1598: RrdJmxCollectorTest fails intermittently

---

platform/security/docs/src/main/resources/IntContents.adoc
platform/security/docs/src/main/resources/ManContents.adoc

@stustison @pklinef
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/291)

DDF-1602: Documentation updates for IdP server and client.

---

platform/admin/core/admin-core-api/src/main/resources/OSGI-INF/metatype/metatype.xml
platform/landing-page/pom.xml
platform/landing-page/src/main/java/org/codice/ddf/landing/LandingPage.java
platform/landing-page/src/main/resources/OSGI-INF/blueprint/blueprint.xml
platform/landing-page/src/main/resources/OSGI-INF/metatype/metatype.xml
platform/landing-page/src/main/resources/index.handlebars
platform/security/core/security-core-impl/src/main/resources/OSGI-INF/metatype/metatype.xml

- change index.html to index.handlebars, since that's how it's being used
- update default description
- work around felix's handling of empty vectors by changing our few negative cardinalities to positive cardinalities
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/298)

DDF-1615 Add color/logo customization to landing page

---

platform/security/encryption/platform-security-encryption-impl/src/main/java/ddf/security/encryption/impl/EncryptionServiceImpl.java
platform/security/encryption/platform-security-encryption-impl/src/test/java/ddf/security/encryption/impl/EncryptionServiceImplTest.java

Fixes up an issue with the way the encryption service was initialized 
@stustison @coyotesqrl
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/317)

DDF-1595: Fixes encryption service initialization

---

distribution/docs/src/main/resources/ManContents.adoc
platform/security/docs/src/main/resources/ManContents.adoc

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/318)

DDF-1617: corrected bug in security docs module causing omnibus failures

---

distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestPlatform.java
distribution/test/itests/test-itests-common/src/test/java/ddf/common/test/config/ConfigurationPropertyMatches.java
platform/platform-configuration-listener/src/main/java/org/codice/ddf/configuration/store/ConfigurationFileDirectory.java
platform/platform-configuration-listener/src/main/java/org/codice/ddf/configuration/store/ConfigurationFileFactory.java

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/320)

DDF-1555: Add back ConfigurationPropertyMatches class that was removed by mistake.

---

catalog/content/core/content-core-filestorageprovider/src/test/java/ddf/content/provider/filesystem/MockMimeTypeResolver.java
catalog/core/catalog-core-commons/src/main/java/ddf/util/XPathHelper.java
catalog/core/catalog-core-impl/pubsub/src/main/java/ddf/catalog/pubsub/criteria/contextual/ContextualEvaluator.java
catalog/core/catalog-core-impl/pubsub/src/main/java/ddf/catalog/pubsub/internal/SubscriptionFilterVisitor.java
catalog/plugin/catalog-plugin-jpeg2000-thumbnail-converter/src/main/java/ddf/catalog/plugin/jpeg2000/thumbnail/converter/Jpeg2000ThumbnailConverter.java
catalog/security/catalog-security-filter/src/main/java/ddf/catalog/security/filter/plugin/FilterPlugin.java
platform/mime/core/platform-mime-core-configurableresolver/src/main/java/ddf/mime/custom/CustomMimeTypeResolver.java
platform/mime/tika/platform-mime-tika-resolver/src/main/java/ddf/mime/tika/TikaMimeTypeResolver.java
pom.xml

@vinamartin @ricklarsen @djblue
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/327)

DDF-1644 Updated checkstyle plugin version for java 8 support and fixed resulting checkstyle errors.

---

platform/security/handler/security-handler-saml/src/main/java/org/codice/ddf/security/handler/saml/SAMLAssertionHandler.java

(cherry picked from commit 2b6ac85)
@roelens8 
@kcwire 
@pklinef 
@shaundmorris
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/306)

DDF-1616 SAMLAssertionHandler now checks session when using basic auth.

---

catalog/core/catalog-core-solr/pom.xml
catalog/core/catalog-core-standardframework/pom.xml
catalog/solr/catalog-solr-embedded-provider/pom.xml
catalog/solr/catalog-solr-external-provider/pom.xml
catalog/solr/catalog-solr-external-provider/src/main/resources/META-INF/services/javax.xml.stream.XMLInputFactory
catalog/ui/search-ui/search-endpoint/pom.xml
catalog/ui/search-ui/search-endpoint/src/main/resources/META-INF/services/javax.xml.stream.XMLInputFactory
platform/solr/platform-solr-server-standalone/pom.xml
pom.xml

This causes an indeterminate version to be selected at runtime, sometimes resulting in errors interacting with Lux.
(cherry picked from commit 7838357)
@pklinef 
@stustison 
@shaundmorris 
@kcwire
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/330)

DDF-1640 Incorrectly configured Woodstox dependency configuration.

---

catalog/ui/docs/src/main/resources/IntContents.adoc
distribution/sdk/pom.xml
distribution/sdk/sample-cometd/.bowerrc
distribution/sdk/sample-cometd/.gitignore
distribution/sdk/sample-cometd/Gruntfile.js
distribution/sdk/sample-cometd/README.md
distribution/sdk/sample-cometd/bower.json
distribution/sdk/sample-cometd/package.json
distribution/sdk/sample-cometd/pom.xml
distribution/sdk/sample-cometd/src/main/webapp/css/site.css
distribution/sdk/sample-cometd/src/main/webapp/index.html
distribution/sdk/sample-cometd/src/main/webapp/js/application.js

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/321)

DDF-1610: Cometd Sample

---

catalog/ui/pom.xml
catalog/ui/search-ui/search-ui-app/src/main/resources/features.xml
platform/platform-app/src/main/resources/features.xml
platform/pom.xml
platform/security/idp/security-idp-client/src/main/java/org/codice/ddf/security/idp/client/IdpMetadata.java
platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/server/IdpEndpoint.java
platform/security/platform-security-core-api/pom.xml
platform/security/platform-security-core-api/src/main/java/ddf/security/samlp/MetadataConfigurationParser.java
platform/security/platform-security-core-api/src/test/java/ddf/security/samlp/MetadataConfigurationParserTest.java

@pklinef 
@vinamartin 
@clockard (will hero)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/322)

DDF-1634 changed the MetadataConfigurationParser to retry HTTP metadata connections with an exponential backoff

---

platform/security/sts/security-sts-server/src/main/java/ddf/security/sts/StsStaticService.java
platform/security/sts/security-sts-server/src/main/resources/OSGI-INF/blueprint/cxf-sts.xml
platform/security/sts/security-sts-server/src/main/resources/OSGI-INF/metatype/metatype.xml

@pklinef @djblue @vinamartin
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/333)

DDF-1649 STS Server Config token issue endpoint list should be configurable

---

platform/platform-app/src/main/resources/features.xml

@ricklarsen @brendan-hofmann @ahoffer
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/340)

DDF-1556: Removed platform-security-settings from features.xml

---

catalog/opensearch/catalog-opensearch-source/src/main/java/ddf/catalog/source/opensearch/OpenSearchSource.java
catalog/opensearch/catalog-opensearch-source/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/opensearch/catalog-opensearch-source/src/test/java/ddf/catalog/source/opensearch/TestOpenSearchSource.java
catalog/ui/search-ui/search-ui-app/src/main/resources/features.xml
distribution/ddf-common/src/main/resources/etc/DDF_Custom_Mime_Type_Resolver.csw.config
distribution/ddf-common/src/main/resources/etc/DDF_Custom_Mime_Type_Resolver.geojson.config
distribution/ddf-common/src/main/resources/etc/DDF_Custom_Mime_Type_Resolver.nitf.config
distribution/ddf-common/src/main/resources/etc/DDF_Custom_Mime_Type_Resolver.xml.config
distribution/ddf-common/src/main/resources/etc/org.codice.ddf.ui.searchui.filter.RedirectServlet.config
distribution/ddf/src/main/filtered-resources/etc/org.codice.ddf.admin.application.service.impl.ApplicationServiceImpl.cfg
distribution/ddf/src/main/filtered-resources/etc/org.codice.ddf.admin.application.service.impl.ApplicationServiceImpl.config
libs/common-system/pom.xml
libs/common-system/src/main/java/org/codice/ddf/configuration/PropertyResolver.java
libs/common-system/src/test/java/org/codice/ddf/configuration/PropertyResolverTest.java
platform/admin/core/admin-core-appservice/src/main/java/org/codice/ddf/admin/application/service/impl/ApplicationServiceImpl.java
platform/admin/core/admin-core-appservice/src/test/java/org/codice/ddf/admin/application/service/impl/ApplicationServiceImplTest.java
platform/mime/core/platform-mime-core-configurableresolver/src/main/resources/OSGI-INF/blueprint/blueprint.xml
platform/platform-app/src/main/resources/features.xml
platform/security/policy/security-policy-context/src/main/java/org/codice/ddf/security/policy/context/impl/PolicyManager.java
platform/security/policy/security-policy-context/src/main/resources/OSGI-INF/blueprint/blueprint.xml
platform/security/policy/security-policy-context/src/test/java/org/codice/security/policy/context/PolicyManagerTest.java
platform/security/sts/security-sts-anonymousclaimshandler/src/main/java/org/codice/ddf/security/claims/anonymous/AnonymousClaimsHandler.java
platform/security/sts/security-sts-anonymousclaimshandler/src/main/resources/OSGI-INF/blueprint/blueprint.xml
platform/security/sts/security-sts-anonymousclaimshandler/src/test/java/org/codice/ddf/security/claims/anonymous/AnonymousClaimsHandlerTest.java
platform/security/sts/security-sts-realm/src/main/java/ddf/security/realm/sts/AbstractStsRealm.java

@andrewkfiedler @garrettfreibott @oconnormi @lessarderic
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/334)

Ddf 1559: Remove Cardinality Workarounds

---

platform/admin/ui/src/main/webapp/js/views/Alerts.view.js
platform/admin/ui/src/main/webapp/js/views/configuration/ConfigurationEdit.view.js
platform/docs/src/main/resources/IntContents.adoc

- also includes some cleanup for pr#314
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/342)

DDF-1612 Update documentation for landing page branding

---

distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/AbstractIntegrationTest.java
distribution/test/itests/test-itests-catalog/src/test/resources/ddf.catalog.solr.external.SolrHttpCatalogProvider.cfg
distribution/test/itests/test-itests-catalog/src/test/resources/ddf.catalog.solr.external.SolrHttpCatalogProvider.config
distribution/test/itests/test-itests-catalog/src/test/resources/ddf.security.sts.client.configuration.config

- Removed ddf.platform.config.cfg files as they are no longer used
- Updated .cfg files in itest to .config
@andrewkfiedler hero
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/324)

DDF-1641: Update .cfg to .config in itests

---

platform/platform-app/src/main/resources/features.xml

@stustison
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/343)

DDF-1618: Updated platform-util in features file

---

pom.xml

@shaundmorris
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/348)

DDF-3500: Set pushChanges to be false

---

catalog/content/core/content-core-api/src/main/java/ddf/content/plugin/PostCreateStoragePlugin.java
catalog/content/core/content-core-api/src/main/java/ddf/content/plugin/PreCreateStoragePlugin.java
catalog/content/core/content-core-catalogerplugin/src/main/java/ddf/content/plugin/cataloger/CatalogContentPlugin.java
catalog/content/core/content-core-catalogerplugin/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/content/core/content-core-checksumplugin/pom.xml
catalog/content/core/content-core-checksumplugin/src/main/java/ddf/content/plugin/checksum/Checksum.java
catalog/content/core/content-core-checksumplugin/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/content/core/content-core-checksumplugin/src/test/java/ddf/content/plugin/checksum/TestChecksum.java
catalog/content/core/content-core-impl/src/main/java/ddf/content/data/impl/ContentMetacardType.java
catalog/content/core/content-core-impl/src/main/java/ddf/content/impl/ContentFrameworkImpl.java
catalog/content/core/content-core-standardframework/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/content/core/pom.xml
libs/checksum/pom.xml
libs/checksum/src/main/java/org/codice/ddf/checksum/AbstractChecksumProvider.java
libs/checksum/src/main/java/org/codice/ddf/checksum/ChecksumProvider.java
libs/checksum/src/main/java/org/codice/ddf/checksum/impl/CRC32ChecksumProvider.java
libs/checksum/src/main/java/org/codice/ddf/checksum/impl/MD5ChecksumProvider.java
libs/checksum/src/main/java/org/codice/ddf/checksum/impl/package-info.java
libs/checksum/src/main/resources/OSGI-INF/blueprint/blueprint.xml
libs/checksum/src/test/java/org/codice/ddf/checksum/SerializableTestObject.java
libs/checksum/src/test/java/org/codice/ddf/checksum/TestCRCChecksumProvider.java
libs/checksum/src/test/java/org/codice/ddf/checksum/TestMD5ChecksumProvider.java
libs/platform-configuration-impl/pom.xml
libs/pom.xml

Implemented Checksum capabilities that can be used by a CheckSumPlugin. CheckSumPlugin is an implementation of a newly created PreCreateStoragePlugin.
@jlcsmith  is hero
@jrnorth
@beyelerb
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/310)

Implemented CRC32 and MD5 CheckSumProvider

---

platform/docs/src/main/resources/IntContents.adoc

- Add instructions for using openssl to base64 encode a logo for the landing page branding
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/346)

DDF-1615 Document base64 encoding

---

distribution/sdk/pom.xml
distribution/sdk/sample-rest-endpoint/pom.xml
distribution/sdk/sample-rest-endpoint/src/main/java/org/codice/ddf/sdk/rest/WhoAmIEndpoint.java
distribution/sdk/sample-rest-endpoint/src/main/resources/OSGI-INF/blueprint/blueprint.xml
distribution/sdk/sdk-app/src/main/resources/features.xml
distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestSingleSignOn.java
distribution/test/itests/test-itests-ddf/src/test/resources/saml-schema-assertion-2.0.xsd
distribution/test/itests/test-itests-ddf/src/test/resources/saml-schema-metadata-2.0.xsd
distribution/test/itests/test-itests-ddf/src/test/resources/xenc-schema.xsd
distribution/test/itests/test-itests-ddf/src/test/resources/xml.xsd
distribution/test/itests/test-itests-ddf/src/test/resources/xmldsig-core-schema.xsd
platform/security/platform-security-core-api/src/main/java/ddf/security/samlp/SamlProtocol.java

@ahoffer @brendan-hofmann @AzGoalie @pklinef @stustison
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/326)

DDF 1609 integration tests for IdP server and client

---

distribution/ddf/pom.xml

@pklinef @AzGoalie
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/354)

DDF-1675 Fix unreliable documentation processing

---

catalog/core/catalog-core-commons/pom.xml
catalog/ui/search-ui/search-htmltransformer/pom.xml
catalog/ui/search-ui/search-htmltransformer/src/main/java/org/codice/ddf/catalog/transformer/html/RecordViewHelpers.java
distribution/sdk/ddf-sso-query-widget/pom.xml
distribution/sdk/ddf-sso-query-widget/src/main/java/org/codice/ddf/ui/Query.java
platform/metrics/platform-metrics-reporting/pom.xml
platform/metrics/platform-metrics-reporting/src/main/java/ddf/metrics/reporting/internal/rrd4j/RrdMetricsRetriever.java
platform/metrics/platform-metrics-reporting/src/test/java/ddf/metrics/reporting/internal/rrd4j/RrdMetricsRetrieverTest.java
platform/metrics/platform-metrics-webconsole-plugin/pom.xml
platform/metrics/platform-metrics-webconsole-plugin/src/test/java/ddf/metrics/plugin/webconsole/MetricsWebConsolePluginTest.java
platform/security/filter/security-filter-login/pom.xml
platform/security/filter/security-filter-login/src/main/java/org/codice/ddf/security/filter/login/LoginFilter.java
platform/security/pep/security-pep-interceptor/pom.xml
platform/security/pep/security-pep-interceptor/src/main/java/ddf/security/pep/interceptor/PEPAuthorizingInterceptor.java
platform/security/platform-security-core-api/src/main/java/ddf/security/samlp/SamlProtocol.java
platform/security/platform-security-core-api/src/test/java/ddf/security/samlp/SamlProtocolTest.java
platform/util/platform-util/src/main/java/org/codice/ddf/platform/util/TransformerProperties.java
platform/util/platform-util/src/main/java/org/codice/ddf/platform/util/XMLUtils.java
platform/util/platform-util/src/test/java/org/codice/ddf/platform/util/XMLUtilsTest.java

-Added AttributeQuery builder to SamlProtocol and a test for creating an AttributeQuery.
-Fixed a bug in the LoginFilter that would print null for the SAML Assertion being returned.
-Added an XMLUtils class for transforming XML
-Refactored old Transformers witihin various places of DDF with new XMLUtils.
@stustison @pklinef @jckilmer is the hero
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/344)

DDF-1659 Add AttributeQuery builder to SamlProtocol

---

catalog/core/catalog-core-resourcesizeplugin/src/main/java/ddf/catalog/plugin/resourcesize/metacard/MetacardResourceSizePlugin.java
catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/ResourceCacheInterface.java
catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/impl/CacheKey.java
catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/impl/ResourceCache.java
catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/CatalogFrameworkImpl.java
catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/resource/download/ReliableResourceDownloader.java
catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/cache/CacheKeyTest.java
catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/cache/impl/ResourceCacheTest.java

@dcruver is hero
@wmcnalli 
@shane-voisard

DDF-1635 Refactored core-catalog-standardframework

---

catalog/admin/module/catalog-admin-module-sources/pom.xml
catalog/admin/module/catalog-admin-module-sources/server.js
catalog/admin/module/catalog-admin-module-sources/src/main/java/org/codice/ddf/catalog/admin/plugin/SourcesPlugin.java
catalog/admin/module/catalog-admin-module-sources/src/main/webapp/main.js
distribution/docs/src/main/resources/ManContents.adoc
platform/admin/ui/src/test/resources/listServices.json
platform/security/pdp/sample-xacml/src/main/resources/access-policy.xml
platform/security/policy/security-policy-context/src/main/resources/OSGI-INF/blueprint/blueprint.xml
platform/security/policy/security-policy-context/src/main/resources/OSGI-INF/metatype/metatype.xml

To simplify security settings, all admin uis should be beneath /admin
@pklinef 
@tbatie 
@jckilmer (hero)

DDF-1674 Move the catalog sources admin ui beneath /admin

---

platform/admin/core/admin-core-api/src/test/java/org/codice/ddf/ui/admin/api/SystemPropertiesAdminTest.java
platform/security/certificate/security-certificate-keystoreeditor/src/test/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditorTest.java

Discovered in scan for ddf-2.8.0-185-g54bc9cb
Some quick try/resources changes and a small bit of refactoring. While I was in there, I also applied the new code formatter.
@rzwiefel
@roelens8
@pklinef

DDF-1684 Fixes resource leaks discovered in unit tests by Coverity.

---

distribution/docs/src/main/resources/ManContents.adoc
distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestPlatform.java
distribution/test/itests/test-itests-ddf/src/test/resources/ddf.test.itests.platform.TestPlatform.invalid.config
platform/platform-configuration-listener/src/main/java/org/codice/ddf/configuration/store/ConfigurationFileDirectory.java
platform/platform-configuration-listener/src/main/java/org/codice/ddf/configuration/store/ConfigurationFileFactory.java
platform/platform-configuration-listener/src/main/java/org/codice/ddf/configuration/store/PersistenceStrategy.java
platform/platform-configuration-listener/src/main/java/org/codice/ddf/configuration/store/felix/FelixPersistenceStrategy.java
platform/platform-configuration-listener/src/main/java/org/codice/ddf/configuration/store/felix/PropertyConverter.java
platform/platform-configuration-listener/src/main/java/org/codice/ddf/configuration/store/felix/PropertyValueConverter.java
platform/platform-configuration-listener/src/test/java/org/codice/ddf/configuration/store/ConfigurationFileDirectoryTest.java
platform/platform-configuration-listener/src/test/java/org/codice/ddf/configuration/store/ConfigurationFileFactoryTest.java
platform/platform-configuration-listener/src/test/java/org/codice/ddf/configuration/store/felix/FelixPersistenceStrategyTest.java

@figliold 
@lessarderic 
@oconnormi 
@bantillo
@andrewkfiedler hero

DDF-1673: Configuration files with invalid values are not being moved to the failed directory

---

catalog/spatial/csw/spatial-csw-source/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/source/CswSource.java

@wmcnalli is hero
@millerw8 
@shane-voisard

DDF-1681 Fixed CSW Source Id Refresh

---

catalog/content/core/content-core-api/pom.xml
catalog/measure/catalog-measure-api/pom.xml
catalog/spatial/csw/spatial-csw-transformer/pom.xml
catalog/spatial/geocoding/spatial-geocoding-extract/pom.xml
catalog/spatial/geocoding/spatial-geocoding-geocoder/pom.xml
catalog/spatial/geocoding/spatial-geocoding-index/pom.xml
catalog/spatial/wcs/spatial-wcs-common/pom.xml
libs/notifications/pom.xml
platform/action/core/platform-action-core-impl/pom.xml
platform/admin/modules/admin-modules-application/pom.xml
platform/admin/modules/admin-modules-configuration/pom.xml
platform/admin/modules/admin-modules-installer/pom.xml
platform/compression/platform-compression-exi/pom.xml
platform/metrics/platform-metrics-ui/pom.xml
platform/mime/core/platform-mime-core-api/pom.xml
platform/security/certificate/security-certificate-generator/pom.xml
platform/security/idp/security-idp-client/pom.xml
platform/security/rest/security-rest-cxfwrapper/pom.xml
pom.xml

@vinamartin @oscaritoro @gordocanchola

DDF-1691  Fixed invalid Jacoco configurations

---

platform/security/pdp/security-pdp-xacmlrealm/pom.xml

DDF-1709 bumped version of Balana to 1.0.2

---

catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/CswRecordMetacardType.java
catalog/spatial/csw/spatial-csw-source/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/source/TestCswSource.java
catalog/spatial/csw/spatial-csw-source/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/source/reader/TestGetRecordsMessageBodyReader.java
catalog/spatial/csw/spatial-csw-source/src/test/resources/getRecordsResponse.xml
catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/DefaultCswRecordMap.java

to the Basic Metacard field Description.
@shane-voisard
@dcruver 
@kcwire is hero
@jrnorth

DDF-1701 Mapped Abstract, Description and Table of Contents 

---

catalog/ui/search-ui/standard/src/main/webapp/js/view/filter/FilterItem.view.js
catalog/ui/search-ui/standard/src/main/webapp/js/widgets/cesium.bbox.js

Revert "DDF-1706 Fixed Advanced search UI BBOX and Geos "

---

distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestSingleSignOn.java
distribution/test/itests/test-itests-ddf/src/test/resources/confluence-sp-authentication-request.xml
distribution/test/itests/test-itests-ddf/src/test/resources/confluence-sp-metadata.xml
distribution/test/itests/test-itests-ddf/src/test/resources/saml-schema-protocol-2.0.xsd

@rzwiefel 
@oscaritoro 
@AzGoalie -Hero

DDF-1647 Added integration tests for non-standard SP's

---

catalog/admin/module/catalog-admin-module-sources/src/main/webapp/templates/configuration/configurationItem.handlebars
platform/admin/ui/src/main/webapp/templates/configuration/configurationItem.handlebars

@kcwire
@millerw8 is hero
Screenshots :  https://codice.atlassian.net/browse/DDF-1702

DDF-1702 Fixed CSS inconsistencies in catalog-admin-module-sources

---

catalog/core/catalog-core-solrcommands/pom.xml
catalog/ui/search-ui/standard/pom.xml
distribution/docs/pom.xml
distribution/test/pom.xml
platform/compression/platform-compression-exi/dependency-check-maven-config.xml
platform/persistence/platform-persistence-core-impl/pom.xml
platform/platform-http-proxy/pom.xml
platform/security/idp/pom.xml
platform/security/pom.xml
platform/security/sts/security-sts-attributequeryclaimshandler/pom.xml
platform/security/sts/security-sts-server/pom.xml
platform/solr/platform-solr-server-standalone/dependency-check-maven-config.xml
platform/solr/platform-solr-server-standalone/pom.xml
platform/solr/pom.xml

@lessarderic @brendan-hofmann 
hero: @spearskw 
To hero: Run a full build with the -Powasp flag
Vulnerabilities fixed:
* nagasena-rta-0000.0002.0049.0.jar: CVE-2014-9389
* commons-fileupload-1.2.1.jar: CVE-2014-0050
* google-http-client-1.21.0.jar: CVE-2010-1807, CVE-2007-3150, CVE-2007-1085
* groovy-2.3.7.jar: CVE-2015-3253
* xalan-2.7.1.jar: CVE-2014-0107
* proxy-camel-servlet-2.9.0-SNAPSHOT.jar: CVE-2014-0003, CVE-2014-0002
* asciidoctorj-1.5.2.jar: jruby_cache_backend.jar: CVE-2011-4838
* jruby-complete-1.7.16.1.jar: readline.jar: CVE-2011-4838

DDF-1714: Fixed OWASP issues

---

platform/security/idp/security-idp-server/pom.xml
platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/cache/CookieCache.java
platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/server/IdpEndpoint.java
platform/security/idp/security-idp-server/src/test/java/org/codice/ddf/security/idp/server/IdpEndpointTest.java

@codice/security @codice/blueteam 
@clockard can hero (just run the build)

DDF-1726 IdP now recognizes the forceauthn attribute on requests

---

distribution/docs/src/main/resources/DDFOmniContents.adoc
distribution/docs/src/main/resources/ExtContents.adoc
distribution/docs/src/main/resources/Extending.adoc
distribution/docs/src/main/resources/IntContents.adoc
distribution/docs/src/main/resources/Integrating.adoc
distribution/docs/src/main/resources/ManContents.adoc
distribution/docs/src/main/resources/Managing.adoc

@clockard @vinamartin @stustison @gordocanchola @oscaritoro

DDF-1279: reorganized documentation

---

platform/security/docs/src/main/resources/IntContents.adoc

DDF-1719 Removed security-pep-redaction from security documentation

---

distribution/ddf-common/src/main/resources/etc/certs/CertNew.cmd
distribution/ddf-common/src/main/resources/etc/certs/CertNew.sh
platform/security/certificate/security-certificate-generator/pom.xml

CertNew.cmd file is analog of CertNew.sh
for Windows OS
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/392)

DDF-1721 certnew-script-for-windows

---

distribution/docs/src/main/resources/ManContents.adoc

Added reference to CertNew scripts.
Removed information that appeared to be redundant with other sectrions of the document.
@stustison @ricklarsen @AzGoalie @spearskw @brendan-hofmann @harrison-tarr

DDF-1720 certificate-generation-documentation

---

platform/platform-configuration-listener/src/test/resources/encryptionCrlAbsPath.properties
platform/platform-configuration-listener/src/test/resources/encryptionCrlInvalidPath.properties
platform/platform-configuration-listener/src/test/resources/encryptionCrlRelPath.properties

Remove these files: platform-configuration-listener/src/test/resources/*.properties and verify all unit tests still pass.
@codice/yellowteam

DDF-1736 Removed property files from platform-configuration-listener

---

platform/security/core/security-core-impl/src/main/java/ddf/security/samlp/impl/LogoutServiceImpl.java
platform/security/core/security-core-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml
platform/security/platform-security-core-api/src/main/java/ddf/security/samlp/SamlProtocol.java
platform/security/platform-security-core-api/src/test/java/ddf/security/samlp/SamlProtocolTest.java

-Moved the LogoutService builder methods into SamlProtocol.
@codice/green 
@ryeats (hero)

DDF-1732 Move LogoutService builder methods into SamlProtocol

---

platform/parser/api/src/main/java/org/codice/ddf/parser/Parser.java
platform/parser/xml/src/main/java/org/codice/ddf/parser/xml/XmlParser.java
platform/parser/xml/src/test/java/org/codice/ddf/parser/xml/TestXmlParser.java

Ddf 1723 Update platform-parser-api to support all marshal/unmarshal paths

---

distribution/ddf-common/src/main/resources/bin/setenv.bat
platform/platform-configuration-listener/src/main/java/org/codice/ddf/configuration/admin/ConfigurationAdminMigration.java
platform/platform-configuration-listener/src/main/resources/OSGI-INF/blueprint/blueprint.xml
platform/platform-configuration-listener/src/test/java/org/codice/ddf/configuration/admin/ConfigurationAdminMigrationTest.java

DDF-1731: Update platform-configuration-listener for windows

---

distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestSecurity.java
platform/security/filter/security-filter-login/pom.xml
platform/security/filter/security-filter-login/src/main/java/org/codice/ddf/security/filter/login/LoginFilter.java

@vinamartin can hero (just run full build)

DDF-1737 added additional validation to the LoginFilter for HoK assertions

---

platform/platform-app/src/main/resources/features.xml

- Fixes display issues with Platform-App in the Admin UI

DDF-1751 update Camel to resolve CVEs

---

distribution/docs/src/main/resources/ManContents.adoc

DDF-1274: fixed incorrect text substitutions in documentation.

---

platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/binding/api/impl/ValidatorImpl.java
platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/binding/redirect/RedirectValidator.java
platform/security/idp/security-idp-server/src/test/java/org/codice/ddf/security/idp/server/IdpEndpointTest.java

DDF-1738 made relaystate optional

---

catalog/docs/src/main/resources/ManContents.adoc

Added some documentation to accompany metacard validation plugin that was worked originally under this ticket number.
@shaundmorris

DDF-1698 Add docs for metacard validation plugin

---

distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestSingleSignOn.java

Added an integration test for single logout. It was added to the TestSingleSignOn class instead of a new one to avoid duplicate code. There are also some other minor changes in the file due to the new code formatter.
@rzwiefel @ryeats @coyotesqrl @tbatie @roelens8 @wbarnie

DDF-1762 Added single logout itest

---

platform/platform-scheduler/src/test/java/ddf/platform/scheduler/TestCommandJob.java

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/432)

DDF-1707 updated unit tests to improve code coverage

---

platform/security/core/security-core-impl/pom.xml
platform/security/core/security-core-impl/src/main/java/ddf/security/assertion/impl/SecurityAssertionImpl.java
platform/security/core/security-core-impl/src/test/java/ddf/security/assertion/impl/SecurityAssertionImplTest.java
platform/security/core/security-core-impl/src/test/resources/saml.xml
platform/security/filter/security-filter-login/pom.xml
platform/security/filter/security-filter-login/src/main/java/org/codice/ddf/security/filter/login/LoginFilter.java
platform/security/handler/security-handler-saml/pom.xml
platform/security/handler/security-handler-saml/src/main/java/org/codice/ddf/security/handler/saml/SAMLAssertionHandler.java
platform/security/idp/security-idp-server/pom.xml
platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/server/IdpEndpoint.java
platform/security/idp/security-idp-server/src/test/java/org/codice/ddf/security/idp/server/IdpEndpointTest.java
platform/security/platform-security-core-api/pom.xml
platform/security/platform-security-core-api/src/main/java/ddf/security/assertion/SecurityAssertion.java

@stustison @ahoffer Please give a quick view make sure I understood the task...
More reviewers and champion to be chosen later.

DDF-1690 Implementation of SAML SSO Time Bounds Check

---

distribution/docs/src/main/resources/ManContents.adoc

DDF-1767 Updated documentation for CRL to cover all properties files

---

platform/security/core/security-core-impl/src/main/java/ddf/security/samlp/impl/LogoutMessageImpl.java
platform/security/idp/security-idp-client/src/main/java/org/codice/ddf/security/idp/client/LogoutRequestService.java
platform/security/idp/security-idp-client/src/test/java/org/codice/ddf/security/idp/client/LogoutRequestServiceTest.java
platform/security/idp/security-idp-server/pom.xml
platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/server/IdpEndpoint.java
platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/server/LogoutState.java

@jckilmer @roelens8 @coyotesqrl @tbatie @wbarnie @rzwiefel

DDF-1740 added inResponseTo validation to SAML logout

---

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/SortedQueryMonitor.java
catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/cache/solr/impl/SortedQueryMonitorTest.java

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/373)

DDF-1692 Add per-source hit count to result properties

---

distribution/docs/src/main/resources/ExtContents.adoc
distribution/docs/src/main/resources/ManContents.adoc
platform/security/docs/src/main/resources/IntContents.adoc
platform/security/sts/security-sts-realm/src/main/resources/OSGI-INF/metatype/metatype.xml

DDF-1775 Updated parts of the DDF documentation to remove old references, duplicate documentation, and old configurations

---

platform/security/core/security-core-impl/pom.xml
platform/security/core/security-core-impl/src/main/java/ddf/security/assertion/impl/SecurityAssertionImpl.java
platform/security/core/security-core-impl/src/main/java/ddf/security/soap/impl/SecureProxyServiceFactoryImpl.java
platform/security/platform-security-core-api/src/main/java/ddf/security/assertion/SecurityAssertion.java

DDF-1756 updated the proxy factory to check assertion against remote policy and updated assertion impl to pull out confirmation methods

---

catalog/spatial/spatial-app/pom.xml

@pklinef 
@kcwire 
@jaymcnallie

DDF-1655 Added spatial-geocoding-admin-module dependency to spatial app

---

catalog/catalog-app/dependency-check-maven-config.xml
catalog/catalog-app/pom.xml
catalog/core/catalog-core-federationstrategy/pom.xml
catalog/core/catalog-core-solr/pom.xml
catalog/pom.xml
catalog/spatial/csw/spatial-csw-transformer/pom.xml
catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/pom.xml
dependency-check-maven-config.xml
distribution/ddf/dependency-check-maven-config.xml
distribution/ddf/pom.xml
distribution/sdk/sample-cometd/java-cli-example/pom.xml
distribution/test/itests/test-itests-ddf/pom.xml
platform/platform-app/dependency-check-maven-config.xml
platform/platform-app/pom.xml
platform/pom.xml
pom.xml

@rzwiefel @coyotesqrl @wbarnie @tbatie @jckilmer @roelens8

DDF-1744 fix owasp findings

---

distribution/ddf-common/src/main/resources/etc/jmx.acl.whitelist.cfg
platform/platform-configuration-migration/src/main/java/org/codice/ddf/configuration/migration/ConfigurationMigrationManager.java
platform/platform-configuration-migration/src/main/java/org/codice/ddf/configuration/migration/ConfigurationMigrationManagerMBean.java
platform/platform-configuration-migration/src/main/resources/OSGI-INF/blueprint/blueprint.xml
platform/platform-configuration-migration/src/test/java/org/codice/ddf/configuration/migration/ConfigurationMigrationManagerTest.java

Reviewers:
@oconnormi 
@bantillo 
@lambeaux
@figliold

DDF-1770: Expose ConfigurationMigrationService as an MBean/Jolokia service

---

catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/plugin/impl/PolicyResponseImpl.java
catalog/core/catalog-core-api/src/main/java/ddf/catalog/plugin/AccessPlugin.java
catalog/core/catalog-core-api/src/main/java/ddf/catalog/plugin/PolicyPlugin.java
catalog/core/catalog-core-api/src/main/java/ddf/catalog/plugin/PolicyResponse.java
catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/CatalogFrameworkImpl.java
catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/FrameworkProperties.java
catalog/core/catalog-core-standardframework/src/main/resources/OSGI-INF/blueprint/blueprint.xml

@pklinef @clockard @vinamartin @coyotesqrl @djblue @lessarderic

DDF-1799 created new api for catalog security plugins

---

catalog/solr/catalog-solr-embedded-provider/pom.xml
catalog/solr/catalog-solr-external-provider/pom.xml
catalog/ui/search-ui/search-endpoint/pom.xml
catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/controller/SearchController.java
catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/model/Search.java
catalog/ui/search-ui/search-endpoint/src/test/java/org/codice/ddf/ui/searchui/query/controller/SearchControllerTest.java
catalog/ui/search-ui/standard/src/main/webapp/js/view/MetacardList.view.js
catalog/ui/search-ui/standard/src/main/webapp/templates/resultlist/counthigh.handlebars
catalog/ui/search-ui/standard/src/main/webapp/templates/resultlist/countlow.handlebars
catalog/ui/search-ui/standard/src/test/js/wd/workspaces.js

Cherry-picked several commits from master into 2.8.x branch
- Search UI exception handling on search responses
- Google collection dependency causing erroneous exceptions in search endpoint
@codice/ui @pklinef @kcwire

DDF-1773: Search UI issues related to return status and exception handling

---

catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/DuplicateCommands.java
catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/MigrateCommand.java
catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/ReplicationCommand.java
catalog/core/catalog-core-commands/src/test/java/org/codice/ddf/commands/catalog/ReplicationCommandTest.java

@millerw8 is hero
@dcruver 
@kcwire

DDF-1777 Added a max option for replicate and migrate catalog-core-commands

---

catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/DuplicateCommands.java
catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/MigrateCommand.java

@millerw8 
@kcwire 
@dcruver 
@shane-voisard

DDF-1784 Updated migrate/duplicate command documentation.

---

distribution/docs/src/main/resources/ManContents.adoc

Flags set for documentation updates regarding migration configuration
Finished simple changes and added issue comments so that big problems can be found quickly. Waiting on one last revision before making a PR.
Finalized changes to docs including the bad hardening paragraph
@lessarderic @ricklarsen @shaundmorris

DDF-1788: Documentation update for .cfg files

---

catalog/catalog-app/pom.xml
distribution/sdk/sdk-app/pom.xml
platform/platform-app/pom.xml
platform/security/security-services-app/pom.xml

@rzwiefel 
@stustison 
@pklinef 

DDF-1722: added missing dependencies.

---

distribution/docs/src/main/resources/ManContents.adoc
distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestConfiguration.java
platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/SystemConfigurationMigration.java
platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/migration/SystemConfigurationMigrationTest.java

Updated files to handle symbolic links. Ignore the previous pull request for DDF-1787.
@lessarderic @figliold @andrewkfiedler @oconnormi @garrettfreibott @Lambeaux

DDF-1787: As an administrator, I want the config-export command to exclude files that are symlinked

---

catalog/docs/src/main/resources/ExtContents.adoc
distribution/docs/src/main/resources/config.adoc
platform/admin/docs/src/main/resources/ExtContents.adoc
platform/admin/docs/src/main/resources/Extending.adoc
platform/admin/docs/src/main/resources/IntContents.adoc
platform/admin/docs/src/main/resources/Integrating.adoc
platform/admin/docs/src/main/resources/ManContents.adoc
platform/admin/docs/src/main/resources/Managing.adoc
platform/admin/docs/src/main/resources/config.adoc

review:
@oscaritoro 
@stustison 
@ahoffer 
@djblue 
@clockard 
@vinamartin 
@gordocanchola

DDF-1273:reorganized Admin docs.

---

catalog/content/docs/src/main/resources/ExtContents.adoc
catalog/content/docs/src/main/resources/Extending.adoc
catalog/content/docs/src/main/resources/IntContents.adoc
catalog/content/docs/src/main/resources/Integrating.adoc
catalog/content/docs/src/main/resources/ManContents.adoc
catalog/content/docs/src/main/resources/Managing.adoc
catalog/content/docs/src/main/resources/config.adoc
catalog/docs/src/main/resources/ExtContents.adoc
catalog/docs/src/main/resources/config.adoc
distribution/docs/src/main/resources/DDFOmniContents.adoc
distribution/docs/src/main/resources/ManContents.adoc
distribution/docs/src/main/resources/config.adoc
platform/admin/docs/src/main/resources/config.adoc

@stustison @clockard @oscaritoro @ahoffer @vinamartin @djblue @gordocanchola

DDF-1275: reorganized DDF Content documentation.

---

catalog/spatial/docs/src/main/resources/ExtContents.adoc
catalog/spatial/docs/src/main/resources/Extending.adoc
catalog/spatial/docs/src/main/resources/IntContents.adoc
catalog/spatial/docs/src/main/resources/Integrating.adoc
catalog/spatial/docs/src/main/resources/ManContents.adoc
catalog/spatial/docs/src/main/resources/Managing.adoc
catalog/spatial/docs/src/main/resources/config.adoc

@stustison @clockard @djblue @vinamartin @gordocanchola @oscaritoro

DDF-1277: reorganized DDF Spatial docs.

---

catalog/ui/docs/src/main/resources/ExtContents.adoc
catalog/ui/docs/src/main/resources/Extending.adoc
catalog/ui/docs/src/main/resources/IntContents.adoc
catalog/ui/docs/src/main/resources/Integrating.adoc
catalog/ui/docs/src/main/resources/ManContents.adoc
catalog/ui/docs/src/main/resources/Managing.adoc
catalog/ui/docs/src/main/resources/config.adoc

@oscaritoro @clockard @gordocanchola @vinamartin @stustison @djblue

DDF-1278: reorganized ui docs.

---

catalog/docs/src/main/resources/ExtContents.adoc
catalog/solr/docs/src/main/resources/ExtContents.adoc
catalog/solr/docs/src/main/resources/Extending.adoc
catalog/solr/docs/src/main/resources/IntContents.adoc
catalog/solr/docs/src/main/resources/Integrating.adoc
catalog/solr/docs/src/main/resources/ManContents.adoc
catalog/solr/docs/src/main/resources/Managing.adoc
catalog/solr/docs/src/main/resources/config.adoc
distribution/docs/pom.xml
distribution/docs/src/main/resources/DDFOmniContents.adoc

@stustison @oscaritoro @vinamartin @djblue @ahoffer @gordocanchola @clockard

DDF-1727: reorganized DDF Solr docs.

---

platform/docs/src/main/resources/ExtContents.adoc
platform/docs/src/main/resources/Extending.adoc
platform/docs/src/main/resources/IntContents.adoc
platform/docs/src/main/resources/Integrating.adoc
platform/docs/src/main/resources/ManContents.adoc
platform/docs/src/main/resources/Managing.adoc
platform/docs/src/main/resources/config.adoc

@oscaritoro @stustison @vinamartin @djblue @clockard @gordocanchola @ahoffer

DDF-1276: reorganized platform documentation.

---

catalog/docs/src/main/resources/ExtContents.adoc
catalog/docs/src/main/resources/Extending.adoc
catalog/docs/src/main/resources/IntContents.adoc
catalog/docs/src/main/resources/Integrating.adoc
catalog/docs/src/main/resources/ManContents.adoc
catalog/docs/src/main/resources/Managing.adoc

@oscaritoro @stustison @vinamartin @clockard @djblue @gordocanchola @ahoffer

DDF-1274: reorganized DDF Catalog documentation.

---

catalog/core/catalog-core-api/src/main/java/ddf/catalog/plugin/AccessPlugin.java
catalog/core/catalog-core-api/src/main/java/ddf/catalog/plugin/PolicyPlugin.java
catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/CatalogFrameworkImpl.java
catalog/plugin/catalog-plugin-metacard-validation/src/main/java/ddf/catalog/metacard/validation/MetacardValidityFilterPlugin.java
catalog/security/catalog-security-filter/pom.xml
catalog/security/catalog-security-filter/src/main/java/ddf/catalog/security/filter/plugin/FilterPlugin.java
catalog/security/catalog-security-filter/src/test/java/ddf/catalog/security/filter/plugin/test/FilterPluginTest.java
catalog/security/catalog-security-operationplugin/pom.xml
catalog/security/catalog-security-operationplugin/src/main/java/ddf/catalog/security/operation/plugin/OperationPlugin.java
catalog/security/catalog-security-plugin/pom.xml
catalog/security/catalog-security-plugin/src/main/java/ddf/catalog/security/plugin/SecurityPlugin.java
distribution/sdk/sample-metacard-filter/src/main/java/ddf/sdk/plugin/filter/FilterPostQueryPlugin.java

DDF-1799 updated catalog access/policy api for resources

---

platform/security/docs/src/main/resources/ExtContents.adoc
platform/security/docs/src/main/resources/Extending.adoc
platform/security/docs/src/main/resources/IntContents.adoc
platform/security/docs/src/main/resources/Integrating.adoc
platform/security/docs/src/main/resources/ManContents.adoc
platform/security/docs/src/main/resources/Managing.adoc
platform/security/docs/src/main/resources/config.adoc

@oscaritoro @clockard @djblue @vinamartin @stustison @gordocanchola

DDF-1766: reorganized DDF Security docs.

---

platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/ConfigurationMigrationManager.java
platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/SystemConfigurationMigration.java
platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/migration/ConfigurationMigrationManagerTest.java

Updated ConfigurationMigrationManager and added unit tests.
Reviewers:
@figliold 
@Lambeaux 
@oconnormi

DDF-1816: Update ConfigurationMigrationManager to call Migratable services

---

catalog/catalog-app/src/main/resources/features.xml
catalog/security/catalog-security-ingestplugin/pom.xml
catalog/security/catalog-security-ingestplugin/src/main/java/ddf/catalog/security/ingest/IngestPlugin.java
catalog/security/catalog-security-ingestplugin/src/test/java/ddf/catalog/security/ingest/IngestPluginTest.java

DDF-1826 updated IngestPlugin to implement AccessPlugin instead of PreIngestPlugin

---

catalog/core/catalog-core-impl/metacard-type-registry/pom.xml
catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/CatalogFrameworkImpl.java
catalog/opensearch/catalog-opensearch-source/src/main/java/ddf/catalog/source/opensearch/OpenSearchFilterVisitor.java
catalog/opensearch/catalog-opensearch-source/src/main/java/ddf/catalog/source/opensearch/RestFilterDelegate.java
catalog/pom.xml
catalog/registry/catalog-registry-metacard-filter/pom.xml
catalog/registry/catalog-registry-metacard-filter/src/main/java/ddf/catalog/registry/metacard/filter/RegistryMetacardFilterPlugin.java
catalog/registry/catalog-registry-metacard-filter/src/main/java/ddf/catalog/registry/metacard/filter/RegistryQueryDelegate.java
catalog/registry/catalog-registry-metacard-filter/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/registry/catalog-registry-metacard-filter/src/test/java/ddf/catalog/registry/metacard/filter/RegistryMetacardFilterPluginTest.java
catalog/registry/pom.xml

Filters out registry metacards in queries that aren't explicitly looking for registry metacards.
@pklinef @djblue @clockard @gordocanchola @mcalcote 
@oscaritoro will hero.

DDF-1749: Pre-query plugin filter for registry metacards

---

platform/platform-app/src/main/resources/features.xml

Added manual install to common-libraries features

---

platform/migration/platform-migratable-util/pom.xml
platform/migration/platform-migratable-util/src/main/java/org/codice/ddf/migration/util/MigratableUtil.java
platform/migration/platform-migratable-util/src/main/java/org/codice/ddf/migration/util/PathMigrationWarning.java
platform/migration/platform-migratable-util/src/test/java/org/codice/ddf/migration/util/MigratableUtilTest.java
platform/migration/pom.xml

Reviewers:
@figliold
@oconnormi 
@Lambeaux

DDF-1827: Create Migratable Utility module

---

catalog/spatial/csw/spatial-csw-source/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/source/CswSource.java
catalog/spatial/csw/spatial-csw-source/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/source/TestCswSource.java
catalog/spatial/csw/spatial-csw-source/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/source/TestCswSourceBase.java

@kcwire 
@dcruver 
@jaymcnallie 
@jrnorth is hero

DDF-1786 Refactored CswSource refresh to use lambdas and consumers

---

catalog/ui/search-ui/standard/src/main/webapp/js/controllers/cesium.layerCollection.controller.js
catalog/ui/search-ui/standard/src/main/webapp/js/controllers/common.layerCollection.controller.js
catalog/ui/search-ui/standard/src/main/webapp/js/controllers/ol.layerCollection.controller.js
catalog/ui/search-ui/standard/src/main/webapp/js/view/preferences/PreferencesModal.view.js

@jrnorth @kcwire @dcruver 
- reindex marionette composite view from jquery sortable.

DDF-1780 Fix map layers not reseting defaults bug.

---

catalog/ui/search-ui/standard/src/main/webapp/css/searchPage.css
catalog/ui/search-ui/standard/src/main/webapp/js/view/preferences/PreferencesModal.view.js

@jlcsmith 
@jaymcnallie 
@bdeining  hero

DDF-1769 Bugfix for preferences modal color picker.

---

platform/platform-app/pom.xml

Working on integrating dependency checking into the build. Should be done soon. But here is a quick fix for now.
@pklinef 
@stustison 
@lessarderic

DDF-1722: fixing implicit dependencies.

---

platform/migration/platform-migratable-api/src/main/java/org/codice/ddf/migration/ExportMigrationException.java
platform/migration/platform-migratable-api/src/main/java/org/codice/ddf/migration/UnexpectedMigrationException.java
platform/migration/platform-migratable-util/src/main/java/org/codice/ddf/migration/util/MigratableUtil.java
platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/admin/ConfigurationAdminMigration.java
platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/ConfigurationMigrationManager.java

Improved the way exceptions are handled and error messages created.
Reviewers:
@figliold 
@oconnormi 
@Lambeaux

DDF-1837: Wrong error message displayed in Admin UI when export fails

---

platform/security/encryption/platform-security-encryption-commands/src/main/resources/OSGI-INF/blueprint/blueprint.xml
platform/security/handler/pom.xml
platform/security/handler/security-handler-basic/pom.xml
platform/security/handler/security-handler-basic/src/main/java/org/codice/ddf/security/handler/basic/WssBasicAuthenticationHandler.java
platform/security/handler/security-handler-basic/src/main/resources/OSGI-INF/blueprint/blueprint.xml
platform/security/handler/security-handler-basic/src/test/java/org/codice/ddf/security/handler/basic/BasicAuthenticationHandlerTest.java
platform/security/pdp/security-pdp-authzrealm/pom.xml
platform/security/pdp/security-pdp-authzrealm/src/main/java/ddf/security/pdp/realm/AuthzRealm.java
platform/security/pdp/security-pdp-authzrealm/src/main/java/ddf/security/pdp/realm/xacml/XacmlPdp.java
platform/security/pdp/security-pdp-authzrealm/src/main/java/ddf/security/pdp/realm/xacml/processor/BalanaClient.java
platform/security/pdp/security-pdp-authzrealm/src/main/resources/OSGI-INF/blueprint/blueprint.xml
platform/security/pdp/security-pdp-authzrealm/src/test/java/ddf/security/pdp/realm/test/AuthzRealmTest.java
platform/security/pdp/security-pdp-authzrealm/src/test/java/ddf/security/pdp/realm/xacml/XacmlPdpTest.java
platform/security/pdp/security-pdp-authzrealm/src/test/java/ddf/security/pdp/realm/xacml/processor/BalanaClientTest.java
platform/security/sts/security-sts-upbstvalidator/pom.xml
platform/security/sts/security-sts-upbstvalidator/src/main/java/org/codice/ddf/security/validator/uname/UPBSTValidator.java
platform/security/sts/security-sts-upbstvalidator/src/main/resources/OSGI-INF/blueprint/blueprint.xml
platform/security/sts/security-sts-upbstvalidator/src/test/java/org/codice/ddf/security/validator/uname/UPBSTValidatorTest.java
platform/security/sts/security-sts-usernametokenvalidator/pom.xml
platform/security/sts/security-sts-usernametokenvalidator/src/main/java/org/codice/ddf/security/validator/username/UsernameTokenValidator.java
platform/security/sts/security-sts-usernametokenvalidator/src/main/resources/OSGI-INF/blueprint/blueprint.xml
platform/security/sts/security-sts-usernametokenvalidator/src/test/java/org/codice/ddf/security/validator/username/TestUsernameTokenValidator.java

DDF-1699 Added Parser marshal/unmarshal.  Also added run time dependencies.

DDF-1699 Added Parser marshal/unmarshal

---

catalog/transformer/catalog-transformer-geojson-input/src/main/java/ddf/catalog/transformer/input/geojson/GeoJsonInputTransformer.java

Fixed threading issues by synchronizing use of the parser
Went with synchronized access over object creation to prevent unecessary object creation on large imports.
@shaundmorris @pklinef @stustison @bcwaters

DDF-1847 - Fixed racy json parser in GeoJsonInputTransformer

---

catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/IngestCommand.java
catalog/core/catalog-core-commands/src/test/java/org/codice/ddf/commands/catalog/TestIngestCommand.java

@pklinef @harrison-tarr @ahoffer

DDF-1850 updated the ingest command to batch and multithread at the same time

---

catalog/catalog-app/pom.xml
libs/libs-pomfix-run/package.json
libs/libs-pomfix-run/pom.xml
libs/libs-pomfix/README.md
libs/libs-pomfix/bin/pom-fix
libs/libs-pomfix/lib/fix.js
libs/libs-pomfix/lib/util.js
libs/libs-pomfix/package.json
libs/libs-pomfix/pom.xml
libs/libs-pomfix/src/assembly/dep.xml
libs/libs-pomfix/test/resources/artifact-items/pom.xml
libs/libs-pomfix/test/resources/descriptors/pom.xml
libs/libs-pomfix/test/resources/features/pom.xml
libs/libs-pomfix/test/resources/features/src/main/resources/features.xml
libs/libs-pomfix/test/test.js
libs/pom.xml

@pklinef 
@stustison 
@lessarderic 
@vinamartin 
@rzwiefel 
@coyotesqrl 

DDF-1848: Integrated maven dependency checker into build process.

---

distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/AbstractIntegrationTest.java
distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalog.java
distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFanout.java
distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFederation.java
distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestRegistry.java
distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestBanana.java
distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestConfiguration.java
distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestSecurity.java
distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestSingleSignOn.java
distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestSolrCommands.java

@pklinef 
@stustison 
@kcwire 
@tbatie 
Could I get a quick review on this, please?

DDF-1648 Resolves potential FindBugs issue with modifiable array.

---

distribution/ddf/src/main/filtered-resources/etc/org.apache.karaf.features.cfg
distribution/kernel/pom.xml
distribution/kernel/src/main/filtered-resources/kernel-features.xml
platform/admin/admin-app/src/main/resources/features.xml
platform/admin/modules/admin-security-ui/pom.xml
platform/platform-app/src/main/resources/features.xml

@tbatie @coyotesqrl @pklinef @stustison

DDF-1648 - removed circular dependency between platform & kernel

---

catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/data/impl/MetacardImpl.java
catalog/core/catalog-core-api-impl/src/test/java/ddf/catalog/data/impl/MetacardImplTest.java
catalog/core/catalog-core-metacardgroomerplugin/src/test/java/ddf/catalog/plugin/groomer/TestMetacardGroomerPlugin.java
catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/TestSolrProvider.java
catalog/spatial/csw/spatial-csw-common/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/common/TestCswRecordMetacardType.java
catalog/spatial/kml/spatial-kml-transformer/src/test/java/org/codice/ddf/spatial/kml/transformer/TestKmlStyleMap.java
catalog/spatial/wfs/1.0.0/spatial-wfs-v1_0_0-endpoint/src/test/java/org/codice/ddf/spatial/ogc/wfs/catalog/endpoint/writer/TestFeatureCollectionMessageBodyWriter.java
catalog/spatial/wfs/1.0.0/spatial-wfs-v1_0_0-endpoint/src/test/resources/wfs.xml
catalog/spatial/wfs/spatial-wfs-converter/src/main/java/org/codice/ddf/spatial/ogc/wfs/catalog/converter/impl/AbstractFeatureConverter.java
catalog/transformer/catalog-transformer-streaming-lib/src/main/java/org/codice/ddf/transformer/xml/streaming/lib/XmlInputTransformer.java

Hero: @brendan-hofmann 
Reviewer: @harrison-tarr

Ddf 899 Type checking and enforcement for AttributeFormats

---

catalog/content/core/content-core-videothumbnailplugin/pom.xml

DDF-1823 Unzip FFmpeg binaries to target folder

---

catalog/ui/search-ui/standard/pom.xml
libs/libs-pomfix-run/pom.xml
libs/libs-pomfix/pom.xml
libs/webapps/lib-webapps-grunt-port-allocator/pom.xml
platform/admin/modules/admin-security-certificate-ui/Gruntfile.js
platform/admin/modules/admin-security-certificate-ui/package.json
platform/admin/modules/admin-security-certificate-ui/pom.xml
platform/admin/modules/admin-security-ui/pom.xml
platform/admin/ui/Gruntfile.js
platform/admin/ui/package.json
platform/admin/ui/pom.xml
platform/error/platform-error-impl/package.json
platform/error/platform-error-impl/pom.xml
platform/security/handler/security-handler-guest/Gruntfile.js
platform/security/handler/security-handler-guest/package.json
platform/security/handler/security-handler-guest/pom.xml
pom.xml

@pklinef @coyotesqrl 
@vinamartin can hero

DDF-1648 fixing compile and runtime issues

---

libs/libs-pomfix/bin/pom-fix

@oscaritoro 
@jckilmer 
@wbarnie 
@NGoss

DDF-1893: updated pom-fix to ignore unknown options.

---

catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/data/impl/MetacardImpl.java
catalog/core/catalog-core-api-impl/src/test/java/ddf/catalog/data/impl/MetacardImplTest.java
catalog/core/catalog-core-metacardgroomerplugin/src/test/java/ddf/catalog/plugin/groomer/TestMetacardGroomerPlugin.java
catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/TestSolrProvider.java
catalog/spatial/csw/spatial-csw-common/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/common/TestCswRecordMetacardType.java
catalog/spatial/kml/spatial-kml-transformer/src/test/java/org/codice/ddf/spatial/kml/transformer/TestKmlStyleMap.java
catalog/spatial/wfs/1.0.0/spatial-wfs-v1_0_0-endpoint/src/test/java/org/codice/ddf/spatial/ogc/wfs/catalog/endpoint/writer/TestFeatureCollectionMessageBodyWriter.java
catalog/spatial/wfs/1.0.0/spatial-wfs-v1_0_0-endpoint/src/test/resources/wfs.xml
catalog/spatial/wfs/spatial-wfs-converter/src/main/java/org/codice/ddf/spatial/ogc/wfs/catalog/converter/impl/AbstractFeatureConverter.java
catalog/transformer/catalog-transformer-streaming-lib/src/main/java/org/codice/ddf/transformer/xml/streaming/lib/XmlInputTransformer.java

Revert "Ddf 899 Type checking and enforcement for AttributeFormats"

---

distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestConfiguration.java

Updated paths and verified that integration tests pass in a windows environment.

DDF-1184: Integration Tests Fail on Windows

---

catalog/spatial/wfs/1.0.0/spatial-wfs-v1_0_0-source/pom.xml
catalog/spatial/wfs/1.0.0/spatial-wfs-v1_0_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v1_0_0/catalog/source/WfsSource.java
catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/pom.xml
catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/source/WfsSource.java

@kcwire @jaymcnallie @shane-voisard anyone else want to put eyes on this?  the hero green-lighted it, no need to wait for the end of the sprint right?

DDF-1872: Added logic to maintain version information inside WFS sources

---

catalog/catalog-app/src/main/resources/features.xml
distribution/test/itests/test-itests-common/src/test/java/ddf/common/test/ServiceManager.java
platform/platform-app/src/main/resources/features.xml
platform/security/platform-security-core-api/src/main/java/ddf/security/SubjectUtils.java
platform/security/platform-security-core-api/src/test/java/ddf/security/SubjectUtilsTest.java
platform/security/security-services-app/src/main/resources/features.xml
platform/security/sts/security-sts-propertyclaimshandler/pom.xml
platform/security/sts/security-sts-propertyclaimshandler/src/main/java/org/codice/ddf/security/sts/claims/property/AttributeFileClaimsHandler.java

- reordered some feature prerequisites
- fixed subject utils get CN method
- added check to attribute file claims handler for x500 principal
- added wait for configurations to service manager for itests
@kcwire @codice/security

DDF-1870 added fixes for filtering ingest

---

distribution/docs/src/main/resources/_contents/securing-contents.adoc

DDF-1870 added documentation for users.attributes file and other areas of security

---

platform/admin/ui/src/main/webapp/templates/application/application.handlebars
platform/admin/ui/src/main/webapp/templates/installer/main.handlebars

DDF-1889 Add "full-height" class to applications div

---

catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/SolrFilterDelegate.java
catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/SolrMetacardClient.java
catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/TestSolrProvider.java
catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/SolrCache.java

Fixes a Solr provider bug when combining nested logical operators and spatial sorting.
@clockard @stustison @codice/solr 
Verify added unit test.
Create a complex filter as described in ticket and pass it to CSW to verify.
https://codice.atlassian.net/browse/DDF-1902

DDF-1902 Fix distance sorting for queries with nested logical operands

---

catalog/catalog-app/src/main/resources/features.xml
catalog/security/catalog-security-filter/src/main/java/ddf/catalog/security/filter/plugin/FilterPlugin.java
catalog/security/catalog-security-filter/src/test/java/ddf/catalog/security/filter/plugin/test/FilterPluginTest.java
catalog/security/catalog-security-metacardattributeplugin/pom.xml
catalog/security/catalog-security-metacardattributeplugin/src/main/java/org/codice/ddf/catalog/security/policy/metacard/MetacardAttributeSecurityPolicyPlugin.java
catalog/security/catalog-security-metacardattributeplugin/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/security/catalog-security-metacardattributeplugin/src/main/resources/OSGI-INF/metatype/metatype.xml
catalog/security/catalog-security-metacardattributeplugin/src/test/java/org/codice/ddf/catalog/security/policy/metacard/MetacardAttributeSecurityPolicyPluginTest.java
catalog/security/catalog-security-xmlattributeplugin/pom.xml
catalog/security/catalog-security-xmlattributeplugin/src/main/java/org/codice/ddf/catalog/security/policy/xml/XmlAttributeSecurityPolicyPlugin.java
catalog/security/catalog-security-xmlattributeplugin/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/security/catalog-security-xmlattributeplugin/src/main/resources/OSGI-INF/metatype/metatype.xml
catalog/security/catalog-security-xmlattributeplugin/src/test/java/org/codice/ddf/catalog/security/policy/xml/XmlAttributeSecurityPolicyPluginTest.java
catalog/security/pom.xml
distribution/docs/src/main/resources/_contents/securing-contents.adoc

Adds implementations for xml metadata and metacard attributes
@pklinef @rzwiefel @clockard @coyotesqrl 
There are no default configurations or itests. Components are entirely unit tested.
DDF-1905

DDF-1905 added policy plugin implementations for xml metadata and metacard attributes

---

catalog/catalog-app/pom.xml

Adds missing dependencies.
@AzGoalie 
@tbatie 
@stustison 
Build `libs-pomfix-run` maven module.
https://codice.atlassian.net/browse/DDF-1848

DDF-1848: added missing dependencies.

---

libs/libs-pomfix/lib/fix.js

Fixes issues with pom-fix on windows
@djblue 
@garrettfreibott will hero!
@lessarderic 
DDF still builds
pom-fix doesn't report false errors on windows
DDF-1906

DDF-1906: fixed issues with pom-fix on windows

---

pom.xml

updated support version to 2.3.6
@stustison 
DDF-1921

DDF-1921: Updated root pom to support 2.3.6

---

catalog/catalog-app/pom.xml
catalog/catalog-app/src/main/resources/features.xml
catalog/core/catalog-core-migratable/pom.xml
catalog/core/catalog-core-migratable/src/main/java/org/codice/ddf/catalog/migratable/impl/CatalogMigratableConfig.java
catalog/core/catalog-core-migratable/src/main/java/org/codice/ddf/catalog/migratable/impl/CatalogMigratableImpl.java
catalog/core/catalog-core-migratable/src/main/java/org/codice/ddf/catalog/migratable/impl/CatalogWriterCallable.java
catalog/core/catalog-core-migratable/src/main/java/org/codice/ddf/catalog/migratable/impl/MigrationFileWriter.java
catalog/core/catalog-core-migratable/src/main/java/org/codice/ddf/catalog/migratable/impl/MigrationTaskManager.java
catalog/core/catalog-core-migratable/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/core/catalog-core-migratable/src/test/java/org/codice/ddf/catalog/migratable/impl/CatalogMigratableConfigTest.java
catalog/core/catalog-core-migratable/src/test/java/org/codice/ddf/catalog/migratable/impl/CatalogMigratableImplTest.java
catalog/core/catalog-core-migratable/src/test/java/org/codice/ddf/catalog/migratable/impl/MigrationFileWriterTest.java
catalog/core/catalog-core-migratable/src/test/java/org/codice/ddf/catalog/migratable/impl/MigrationTaskManagerTest.java
catalog/core/pom.xml
distribution/ddf-common/src/main/resources/etc/ws-security/server/encryption.properties
distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestConfiguration.java
platform/migration/platform-migratable-api/src/main/java/org/codice/ddf/migration/Migratable.java
platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/admin/ConfigurationAdminMigration.java
platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/ConfigurationMigrationManager.java

Catalog export PR: Take 2! Tested it myself and everything works. All comments from the previous PR have been addressed. Please let me know if there are any additional issues.

DDF-1824: Added metacard export to migration

---

catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/Subscribe.java
catalog/spatial/csw/spatial-csw-endpoint/pom.xml
catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java
catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswQueryFactory.java
catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswSubscriptionEndpoint.java
catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/Validator.java
catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/event/CswSubscription.java
catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/event/CswSubscriptionConfigFactory.java
catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/event/SendEvent.java
catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/reader/TransactionRequestConverter.java
catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/writer/CswRecordCollectionMessageBodyWriter.java
catalog/spatial/csw/spatial-csw-endpoint/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/spatial/csw/spatial-csw-endpoint/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswQueryFactoryTest.java
catalog/spatial/csw/spatial-csw-endpoint/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswSubscriptionEndpointTest.java
catalog/spatial/csw/spatial-csw-endpoint/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/TestCswEndpoint.java
catalog/spatial/csw/spatial-csw-endpoint/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/ValidatorTest.java
catalog/spatial/csw/spatial-csw-endpoint/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/event/CswSubscriptionConfigFactoryTest.java
catalog/spatial/csw/spatial-csw-endpoint/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/event/SendEventTest.java
catalog/spatial/csw/spatial-csw-endpoint/src/test/resources/GetRecords.xml
catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/transformer/CswQueryResponseTransformer.java
catalog/spatial/docs/src/main/resources/_contents/intcontents.adoc
distribution/test/itests/test-itests-ddf/pom.xml
distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/AbstractIntegrationTest.java
distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFederation.java
distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/common/Library.java
distribution/test/thirdparty/pom.xml
distribution/test/thirdparty/restito/pom.xml
platform/security/common/src/main/java/ddf/security/common/util/Security.java

Adds an endpoint to subscribe to metacard updates through a webhooks rest api that is similar to CSW
@roelens8 @coyotesqrl @tbatie @bcwaters @jckilmer @pklinef @lessarderic 
Post a CSW query to the services/csw/subscription endpoint with a <csw:ResponseHandler> element added that contains a url to an http server that can log the messages sent to it. (The integration tests do this)

DDF-1858 add pubsub to CSW endpoint

---

catalog/spatial/docs/src/main/resources/_contents/mancontents.adoc
distribution/docs/src/main/resources/_contents/configuring-from-the-command-console-contents.adoc
distribution/docs/src/main/resources/_contents/extending-contents.adoc
distribution/docs/src/main/resources/_contents/running-contents.adoc
distribution/docs/src/main/resources/_contents/securing-contents.adoc
distribution/docs/src/main/resources/ddfomnibus.adoc
distribution/docs/src/main/resources/extending.adoc
distribution/docs/src/main/resources/integrating.adoc
platform/admin/docs/src/main/resources/_contents/mancontents.adoc
platform/docs/src/main/resources/_contents/intcontents.adoc
pom.xml

With upgrade to karaf 4, many console commands changed names. These have been updated to reflect new names.
@pklinef @coyotesqrl @stustison @mcalcote @brianfelix @vinamartin @gordocanchola @clockard @ 
Compare to this table at http://karaf.apache.org/manual/latest-3.0.x/update-notes.html
DDF-1920
n/a

DDF-1920: Updated karaf commands in documentation to karaf v.4 versions.

---

catalog/content/core/content-core-catalogerplugin/pom.xml
catalog/content/core/content-core-catalogerplugin/src/test/java/ddf/content/plugin/cataloger/TestCatalogContentPlugin.java
catalog/content/core/content-core-catalogerplugin/src/test/java/ddf/content/plugin/cataloger/TestContentResourceReader.java

Adds tests for Catalog Content Plugin
@jaymcnallie 
@jlcsmith 
@kcwire 
@jrnorth 
JUnit test cases.
DDF-1912
- [ X ] Update / Add Unit Tests

DDF-1912 Adding tests for Catalog Content Plugin

---

catalog/content/core/content-core-catalogerplugin/src/main/java/ddf/content/plugin/cataloger/CatalogContentPlugin.java
catalog/content/core/content-core-catalogerplugin/src/main/java/ddf/content/plugin/cataloger/Cataloger.java
catalog/content/core/content-core-directorymonitor/pom.xml
catalog/content/core/content-core-directorymonitor/src/main/java/ddf/content/core/directorymonitor/ContentDirectoryMonitor.java
catalog/content/core/content-core-directorymonitor/src/test/java/ddf/content/core/directorymonitor/ContentDirectoryMonitorTest.java
catalog/content/core/content-core-impl/pom.xml
catalog/content/core/content-core-impl/src/main/java/ddf/content/impl/ContentFrameworkImpl.java
platform/security/common/src/main/java/ddf/security/common/util/Security.java

Update content framework to not default all requests to system subject
@codice/security @kcwire @clockard 
run itests
DDF-1936

DDF-1936 Update content framework to not default all requests to system subject

---

platform/admin/core/admin-core-api/pom.xml
platform/admin/core/admin-core-api/src/main/java/org/codice/ddf/ui/admin/api/impl/SystemPropertiesAdmin.java
platform/admin/core/admin-core-api/src/test/java/org/codice/ddf/ui/admin/api/SystemPropertiesAdminTest.java

Updates the user.attributes file during the install
@pklinef @gordocanchola @clockard @coyotesqrl @mcalcote
Run itests @mcalcote can hero

DDF-1870 added the user.attributes file to the system properties update

---

catalog/catalog-app/pom.xml

Removes unused dependency
@stustison @djblue @clockard 
The catalog-registry-metacard-filter was removed but the dependency remained in catalog-app.

DDF-1854: Removing unused dependency

---

catalog/spatial/geocoding/spatial-geocoding-geocoder/src/main/java/org/codice/ddf/spatial/geocoder/endpoint/GeoCoderEndpoint.java
catalog/spatial/geocoding/spatial-geocoding-geocoder/src/main/java/org/codice/ddf/spatial/geocoder/endpoint/JsonpValidator.java
catalog/spatial/geocoding/spatial-geocoding-geocoder/src/test/java/org/codice/ddf/spatial/geocoder/endpoint/TestJsonpValidator.java
platform/security/sts/security-sts-ldapclaimshandler/src/main/java/ddf/security/sts/claimsHandler/ContextSourceDecrypt.java

Cleans up some non logic issues that where brought up during the review of the 2.9.0.Alpha2 backport
@pklinef @jckilmer @mcalcote @shaundmorris @stustison @brianfelix @clockard 
Build ddf
DDF-1865

DDF-1865 Cleanup Based on Review Comments

---

catalog/content/core/content-core-catalogerplugin/pom.xml
catalog/content/core/content-core-directorymonitor/pom.xml
catalog/core/catalog-core-camelcomponent/pom.xml
catalog/core/catalog-core-federationstrategy/pom.xml
catalog/core/catalog-core-federationstrategy/src/test/java/ddf/catalog/federation/impl/FederationStrategyTest.java
catalog/core/catalog-core-impl/metacard-type-registry/pom.xml
catalog/core/catalog-core-migratable/pom.xml
catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/TestSolrProvider.java
catalog/measure/catalog-measure-api/pom.xml
catalog/ui/search-ui/search-endpoint/pom.xml
distribution/ddf-distro-repo/src/main/resources/commons-httpclient-3.1.pom
distribution/sdk/sample-transformers/xslt-identity-input-transformer/pom.xml
distribution/test/itests/pom.xml
distribution/test/pom.xml
distribution/test/thirdparty/rest-assured/pom.xml
libs/notifications/pom.xml
platform/migration/platform-migratable-util/pom.xml
platform/migration/platform-migration-commands/pom.xml
platform/migration/pom.xml
platform/platform-app/pom.xml
platform/platform-migratable/pom.xml
platform/security/common/pom.xml
platform/security/core/security-core-impl/pom.xml
platform/security/idp/security-idp-server/pom.xml
platform/security/sts/security-sts-upbstvalidator/pom.xml
pom.xml

This PR updates several testing tools to current versions. 
- JUnit=4.12
- Mockito=1.10.19
- Powermock=1.6.4
@roelens8 @oconnormi @pklinef 
Full integration build tests. Look for new failures, errors, or warnings.
In a related PR, the version of the testing tool hamcrest was updated.
XMLUnit and potentially other testing tools will be updates in a third and final PR after this PR is merged.
DDF-1450
- XMLUnit and other testing tools will be included after this PR is merged
- Version of PowerMock earlier than 1.6.1 are not compatible with
JUnit 4.12; upgrade PowerMock to 1.6.4
- Remove randomizing running from TestSolrFactory because of compile error
- Use mockito-core instead of mockito all to avoid including hamcrest and to resolve
- Exclude incompatible version of mockito from other …

DDF-1450 JUnit, Mockito, Powermock

---

catalog/spatial/geowebcache/README.md
catalog/spatial/geowebcache/geowebcache-app/pom.xml
catalog/spatial/geowebcache/geowebcache-app/src/main/resources/features.xml
catalog/spatial/geowebcache/pom.xml
catalog/spatial/pom.xml

- Uses the bundled distribution of GeoWebCache (https://github.com/codice/geowebcache-osgi)
- See README.md for example of layer config
@beyelerb @pklinef @millerw8

Ddf 1815: Initial GeoWebCache app 

---

catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/Csw.java
catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/CswConstants.java
catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java
catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/writer/CswRecordCollectionMessageBodyWriter.java
catalog/spatial/csw/spatial-csw-endpoint/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/TestCswEndpoint.java
catalog/spatial/csw/spatial-csw-source/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/source/CswSource.java
catalog/spatial/csw/spatial-csw-source/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/source/TestCswSource.java
catalog/spatial/docs/src/main/resources/_contents/integrating-contents.adoc
distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalog.java
distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFederation.java

Provides support for downloading products with a byte offset.
@ryeats (hero) @tbatie @coyotesqrl @pklinef @kcwire @bcwaters 
Verify that products can still be retrieved and federated.
DDF-1845

DDF-1951 Add support for downloading products with a byte offset over CSW

---

catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java

FIxes a failure in getDescribeRecord
@jlcsmith @kcwire @pklinef @jrnorth @glenhein
build, install, verify you can get describe record
DDF-1954

DDF-1954 - Fixed getDescribeRecord failure

---

catalog/catalog-app/pom.xml
catalog/catalog-app/src/main/resources/features.xml
catalog/registry/catalog-registry-identificationplugin/pom.xml
catalog/registry/catalog-registry-identificationplugin/src/main/java/ddf/catalog/registry/identification/IdentificationPlugin.java
catalog/registry/catalog-registry-identificationplugin/src/main/resources/OSGI-INF/blueprint/blueprint.xml

Adds the PreIngest Registry Identification Plugin to the Catalog-Registry Feature.
@clockard @shaundmorris 
Check for Bamboo build pass
PreIngest IdentificationPlugin was previously merged

DDF-1937 Add PreIngest ID plugin to Registry Feature

---

catalog/plugin/catalog-plugin-querymonitor/pom.xml
catalog/plugin/catalog-plugin-querymonitor/src/main/java/ddf/catalog/querymonitor/ActiveSearch.java
catalog/plugin/catalog-plugin-querymonitor/src/main/java/ddf/catalog/querymonitor/QueryMonitorPlugin.java
catalog/plugin/catalog-plugin-querymonitor/src/main/java/ddf/catalog/querymonitor/QueryMonitorPluginImpl.java
catalog/plugin/catalog-plugin-querymonitor/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/plugin/catalog-plugin-querymonitor/src/test/java/ddf/catalog/querymonitor/QueryMonitorTest.java
catalog/plugin/catalog-plugin-querymonitorcommands/pom.xml
catalog/plugin/catalog-plugin-querymonitorcommands/src/main/java/ddf/catalog/querymonitorcommands/PrintActiveSearchesCommand.java
catalog/plugin/catalog-plugin-querymonitorcommands/src/main/java/ddf/catalog/querymonitorcommands/RemoveSearchAfterCompleteCommand.java
catalog/plugin/catalog-plugin-querymonitorcommands/src/test/java/ddf/catalog/querymonitorcommands/MonitorCommandsTest.java
catalog/plugin/pom.xml

@jlcsmith @jrnorth @kcwire @rzwiefel

DDF-1892 Created a backend plugin/service to track active searches

---

catalog/core/catalog-core-metacardgroomerplugin/src/main/java/ddf/catalog/plugin/groomer/metacard/StandardMetacardGroomerPlugin.java
catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/CatalogFrameworkImpl.java

Fix update/delete for metacards with non default tags
@djblue @stustison 
Bamboo build passes
DDF-1959

DDF-1959 Fixed catalog frameworks queries for delete/update operation

---

catalog/catalog-app/pom.xml
catalog/catalog-app/src/main/resources/features.xml
catalog/content/content-app/pom.xml
catalog/content/content-app/src/main/resources/features.xml
catalog/core/catalog-core-api/pom.xml
catalog/core/catalog-core-api/src/main/java/ddf/catalog/util/Describable.java
platform/platform-api/pom.xml
platform/platform-api/src/main/java/org/codice/ddf/platform/services/common/Describable.java
platform/platform-app/pom.xml
platform/platform-app/src/main/resources/features.xml
platform/pom.xml

Depreciates the two identical yet separate Describable interfaces in catalog and content, and unifies everything under a single Describable interface in platform-util. 
@lessarderic @figliold @coyotesqrl and @stustison 
Run PRBS. Spin-up DDF and make sure nothing fails to come up. 
DDF-1939

DDF-1939: Created a common Describable interface

---

catalog/core/catalog-core-standardframework/pom.xml

Add some missing dependencies to catalog framework.
@stustison @clockard 
In addition to prbs, do some searches from the standard search ui and verify no more exceptions are logged.
@stustison found this while working on the content merge, but it appears to have been introduced in https://github.com/codice/ddf/pull/546 . It wouldn't hurt to reference the changes in that pr in case this same fix is needed elsewhere.
https://codice.atlassian.net/browse/DDF-1977

DDF-1977 Add missing jts imports to catalog framework

---

catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/CswConstants.java
catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/GmdMetacardType.java
catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/converter/DefaultCswRecordMap.java
catalog/spatial/csw/spatial-csw-endpoint/pom.xml
catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java
catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswQueryFactory.java
catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/Validator.java
catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/mappings/CswRecordMapperFilterVisitor.java
catalog/spatial/csw/spatial-csw-endpoint/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/TestCswEndpoint.java
catalog/spatial/csw/spatial-csw-endpoint/src/test/resources/record.xsd
catalog/spatial/csw/spatial-csw-schema-bindings/src/main/resources/gmd/record_gmd.xsd
catalog/spatial/docs/src/main/resources/_contents/integrating-contents.adoc

This PR adds the capability for the CSW Endpoint to Query our Catalog based on the APISO schema
@jlcsmith 
@kcwire 
@jrnorth 
Build and hit the endpoint with APISO requests via postman
https://codice.atlassian.net/browse/DDF-1961

DDF-1961 Added GMD support to CSW Endpoint Queries

---

distribution/ddf/pom.xml

Add geowebcache pom dependency
@jlcsmith 
Run `pom-fix --test` or just try to build.

DDF-1979 Add missing geowebcache pom dependency

---

distribution/ddf/src/main/filtered-resources/etc/org.apache.karaf.features.cfg
distribution/install-profiles/src/main/resources/features.xml

@stustison @bdeining 
Verify the content-app is no longer included in the Admin Console

DDF-1982: Removed content-app from features/install profile

---

catalog/resourcemanagement/resourcemanagement-app/src/main/resources/features.xml

Adds the catalog-app prerequisite to resourcemanagement-app
@jlcsmith 
@kcwire 
Build DDF, build Alliance and install the experimental install profile

DDF-1985 Added catalog-app prerequisite to resourcemanagement-app

---

catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/GmdConverter.java
catalog/spatial/csw/spatial-csw-transformer/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/TestGmdConverter.java
catalog/spatial/csw/spatial-csw-transformer/src/test/resources/gmd/metacard-as-GMD-sparse.xml
catalog/spatial/csw/spatial-csw-transformer/src/test/resources/gmd/metacard-as-GMD.xml

DDF-1989: Fixed GmdConverter test failures

---

catalog/transformer/catalog-transformer-xml/src/main/java/ddf/catalog/transformer/xml/MetacardMarshallerImpl.java
catalog/transformer/catalog-transformer-xml/src/test/java/ddf/catalog/transform/xml/TestXmlMetacardTransformer.java

Updates the MetacardTransformer to serialize multivalued attributes correctly.
How it currently works:
```xml
<metacard>
<string name="tags">
<value>foo</value>
</string>
<string name="tags">
<value>bar</value>
</string>
</metacard>
```
How it should work:
```xml
<metacard>
<string name="tags">
<value>foo</value>
<value>bar</value>
</string>
</metacard>
```
@pklinef 
@rzwiefel 
A full build of ddf.
[DDF-1990](https://codice.atlassian.net/browse/DDF-1990)

DDF-1990: fixed MetacardTransformer multivalued serialization.

---

catalog/catalog-app/pom.xml
catalog/catalog-app/src/main/resources/features.xml
catalog/pom.xml
distribution/docs/pom.xml

removes old / incorrect dependencies from catalog
@stustison @bdeining @rzwiefel

DDF-1988: Removed old dependencies from catalog

---

libs/geospatial/pom.xml
libs/geospatial/src/main/java/org/codice/ddf/libs/geo/GeoFormatException.java
libs/geospatial/src/main/java/org/codice/ddf/libs/geo/util/GeospatialUtil.java
libs/geospatial/src/test/java/org/codice/ddf/libs/geo/GeoUtilTest.java
libs/pom.xml

Adds simple Lat/Lon DMS to decimal degree parsing
@jaymcnallie 
@bdeining 
@kcwire 
Run JUnit tests that verify conversions
https://codice.atlassian.net/browse/DDF-1981

DDF-1981 Add DMS lat/lon parsing to decimal degrees

---

catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/CswSubscribe.java
catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswSubscriptionEndpoint.java
catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/event/CswSubscription.java
catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/event/SendEvent.java
catalog/spatial/csw/spatial-csw-endpoint/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/spatial/csw/spatial-csw-endpoint/src/main/resources/OSGI-INF/metatype/metatype.xml
catalog/spatial/csw/spatial-csw-endpoint/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/event/SendEventTest.java
catalog/spatial/docs/src/main/resources/_contents/integrating-contents.adoc
distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFederation.java
distribution/test/thirdparty/restito/pom.xml
distribution/test/thirdparty/restito/src/main/java/com/xebialabs/restito/server/secure/SecureStubServer.java
platform/security/common/src/main/java/org/codice/ddf/security/common/OutgoingSubjectRetrievalInterceptor.java
platform/security/platform-security-core-api/src/main/java/ddf/security/common/audit/SecurityLogger.java
platform/security/rest/security-rest-cxfwrapper/pom.xml
platform/security/rest/security-rest-cxfwrapper/src/main/java/org/codice/ddf/cxf/SecureCxfClientFactory.java

Runs outgoing events through the AccessPlugins post query processing
@roelens8 @jckilmer @coyotesqrl @bcwaters @codice/security @tbatie 
Run the integration tests
Restito's StubServer didn't offer a way of using your own certificates so we had to extend StubServer to allow it to do so.

DDF-1994 update event publishing to apply AccessPlugins

---

catalog/core/catalog-core-migratable/src/main/java/org/codice/ddf/catalog/migratable/impl/CatalogMigratableImpl.java
catalog/core/catalog-core-migratable/src/main/java/org/codice/ddf/catalog/migratable/impl/MigrationTaskManager.java
catalog/core/catalog-core-migratable/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/core/catalog-core-migratable/src/test/java/org/codice/ddf/catalog/migratable/impl/CatalogMigratableImplTest.java
catalog/core/catalog-core-migratable/src/test/java/org/codice/ddf/catalog/migratable/impl/MigrationFileWriterTest.java
distribution/docs/src/main/resources/_contents/configuring-from-import-contents.adoc
distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestConfiguration.java
platform/migration/platform-migratable-api/pom.xml
platform/migration/platform-migratable-api/src/main/java/org/codice/ddf/migration/AbstractDescribable.java
platform/migration/platform-migratable-api/src/main/java/org/codice/ddf/migration/Migratable.java
platform/migration/platform-migration/pom.xml
platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/ConfigurationMigrationManager.java
platform/migration/platform-migration/src/main/resources/OSGI-INF/blueprint/blueprint.xml
platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/migration/ConfigurationMigrationManagerTest.java
platform/platform-api/pom.xml
platform/platform-api/src/main/java/org/codice/ddf/platform/services/common/Describable.java
platform/platform-migratable/src/main/java/org/codice/ddf/platform/migratable/impl/PlatformMigratable.java
platform/platform-migratable/src/main/resources/OSGI-INF/blueprint/blueprint.xml
platform/platform-migratable/src/test/java/org/codice/ddf/platform/migratable/impl/PlatformMigratableTest.java
platform/security/security-migratable/src/main/java/org/codice/ddf/security/migratable/impl/SecurityMigratable.java
platform/security/security-migratable/src/main/resources/OSGI-INF/blueprint/blueprint.xml
platform/security/security-migratable/src/test/java/org/codice/ddf/security/migratable/impl/SecurityMigratableTest.java

Provides an accessible sub-directory located under the main export directory
@figliold @lessarderic @andrewkfiedler @Lambeaux @bantillo @pklinef @oconnormi
Successful PRBS. Migration commands are working.
None
DIB-4118
None

Ddf 1968 As an integrator, I want to be provided with an accessible sub-directory located under the main export directory

---

catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/RemoveCommand.java

Fixes several bugs with the catalog:remove command
@coyotesqrl @kcwire 
- could not delete with only cql
- could not delete with cql and a list of ids
- deletion count was incorrect

DDF-2012 fixed bugs with remove command

---

distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestSpatial.java
distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/common/Library.java
distribution/test/itests/test-itests-ddf/src/test/resources/TestSpatial/csw/record/CswRecord.xml
distribution/test/itests/test-itests-ddf/src/test/resources/TestSpatial/csw/request/query/CswAfterDateQuery.xml
distribution/test/itests/test-itests-ddf/src/test/resources/TestSpatial/csw/request/query/CswBeforeDateQuery.xml
distribution/test/itests/test-itests-ddf/src/test/resources/TestSpatial/csw/request/query/CswContainingWktLineStringQuery.xml
distribution/test/itests/test-itests-ddf/src/test/resources/TestSpatial/csw/request/query/CswContainingWktPolygonQuery.xml
distribution/test/itests/test-itests-ddf/src/test/resources/TestSpatial/csw/request/query/CswDuringDatesQuery.xml
distribution/test/itests/test-itests-ddf/src/test/resources/TestSpatial/csw/request/query/CswEqualToTextQuery.xml
distribution/test/itests/test-itests-ddf/src/test/resources/TestSpatial/csw/request/query/CswIntersectingWktLineStringQuery.xml
distribution/test/itests/test-itests-ddf/src/test/resources/TestSpatial/csw/request/query/CswIntersectingWktPolygonQuery.xml
distribution/test/itests/test-itests-ddf/src/test/resources/TestSpatial/csw/request/query/CswLikeTextQuery.xml
distribution/test/itests/test-itests-ddf/src/test/resources/TestSpatial/csw/request/query/CswNearestToWktLineStringQuery.xml
distribution/test/itests/test-itests-ddf/src/test/resources/TestSpatial/csw/request/query/CswNearestToWktPolygonQuery.xml
distribution/test/itests/test-itests-ddf/src/test/resources/TestSpatial/csw/request/query/CswOverLappingDatesQuery.xml
distribution/test/itests/test-itests-ddf/src/test/resources/TestSpatial/csw/request/query/CswWithinBufferWktLineStringQuery.xml
distribution/test/itests/test-itests-ddf/src/test/resources/TestSpatial/csw/request/query/CswWithinBufferWktPolygonQuery.xml
distribution/test/itests/test-itests-ddf/src/test/resources/TestSpatial/csw/request/query/CswWithinWktPolygonQuery.xml
distribution/test/itests/test-itests-ddf/src/test/resources/TestSpatial/json/GeoJsonFar.json
distribution/test/itests/test-itests-ddf/src/test/resources/TestSpatial/json/GeoJsonNear.json
distribution/test/itests/test-itests-ddf/src/test/resources/TestSpatial/xml/PlainXmlFar.xml
distribution/test/itests/test-itests-ddf/src/test/resources/TestSpatial/xml/PlainXmlNear.xml

Adds integration tests for testing spatial, temporal and contextual CSW queries.
@ryeats @tbatie @jckilmer @bcwaters @coyotesqrl 
Run TestSpatial and verify all tests pass
N/A
N/A
N/A

DDF-1996 Add integration tests for testing spatial, temporal and contextual CSW queries

---

catalog/transformer/catalog-transformer-streaming-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/transformer/catalog-transformer-streaming-lib/pom.xml
catalog/transformer/catalog-transformer-streaming-lib/src/main/java/org/codice/ddf/transformer/xml/streaming/lib/SaxEventToXmlElementConverter.java
catalog/transformer/catalog-transformer-streaming-lib/src/main/java/org/codice/ddf/transformer/xml/streaming/lib/XmlInputTransformer.java
catalog/transformer/catalog-transformer-streaming-lib/src/test/java/org/codice/ddf/transformer/xml/streaming/lib/TestGenericXmlLib.java
distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/common/CswQueryBuilder.java

Fixes a bug where the metacard type was not always getting updated correctly on the streaming XmlInputTransformer
@brendan-hofmann, @AzGoalie
@lessarderic
@shaundmorris
Use a configuration file to set up a transformer, run an ingest, and ensure that the metacard is properly populated in the Solr Catalog
DDF-1998
DDF-1998 Further fix metacard type

DDF-1998 Fix Metacard Type bug

---

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/CatalogFrameworkImpl.java

Fixes a bug that let invalid metacards be ingested, no matter which enforced validators you have configured.
@bcwaters 
@ahoffer 
@figliold 
@lessarderic 
1) DDF-Catalog -> Features -> catalog-plugin-metacard-validation -> install
2) ingest some metacards
3) DDF-Catalog -> Configuration -> Metacard Validation Marker Plugin -> Enforced Validators -> Add a validator that will throw errors for the metacards in step 2
4) ingest metacards that have validation errors, make sure they don't get ingested
https://codice.atlassian.net/browse/DDF-2030

DDF-2030 Fixed CatalogFrameworkImpl to properly update request

---

catalog/rest/catalog-rest-endpoint/src/main/java/org/codice/ddf/endpoints/rest/RESTEndpoint.java

Fixes bug where you cannot execute Actions when the site name has a space in it.
@jlcsmith @pklinef 
Update the site name to have a space, ingest some data, verify the actions work from the search ui.
DDF-1993
N/A - [ ] Documentation Updated
- [ x ] Update / Add Unit Tests
N/A - [ ] Update / Add Integration Tests

DDF-1993 - updated RestEndpoint to URL decode sourceId & metacardId

---

distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFederation.java

fixes flaky itest
@harrison-tarr @Lambeaux 
@kcwire
@lessarderic
verify bamboo passes

DDF-2026 - updated itest to only query for a single record

---

platform/security/core/security-core-impl/src/main/java/ddf/security/http/impl/HttpSessionFactory.java

adds an audit to new sessions
@roelens8 @tbatie 
@shaundmorris
@stustison
build is sufficient

DDF-2056 added an audit to newly created sessions

---

distribution/ddf/pom.xml

Upgrade opendj-osgi to 1.3.2
@ryeats @roelens8 
@mrmateo
@stustison
Passing build should be sufficient
Only a few minor changes since the 1.3.1 release
see https://github.com/codice/opendj-osgi/commits/master
https://codice.atlassian.net/browse/DDF-2066
https://codice.atlassian.net/browse/LDAP-7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codice/ddf/724)

DDF-2066 upgraded opendj-osgi to 1.3.2

---

catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/data/impl/BasicTypes.java
catalog/core/catalog-core-api/src/main/java/ddf/catalog/data/Metacard.java
catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/CatalogFrameworkImpl.java
catalog/core/catalog-core-versioning/versioning-common/src/main/java/ddf/catalog/core/versioning/HistoryMetacardImpl.java

DDF-2065 - Initial Backend Changes for new UI

---

catalog/opensearch/catalog-opensearch-endpoint/src/main/java/org/codice/ddf/endpoints/OpenSearchEndpoint.java
catalog/rest/catalog-rest-endpoint/src/main/java/org/codice/ddf/endpoints/rest/RESTEndpoint.java
distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFanout.java

Removes unnecessary information from exception messages passed back to clients.
@bcwaters @ryeats @coyotesqrl 
@kcwire
@stustison

DDF-2060 cleaned up exception messages passed back to clients from catalog endpoints

---

distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestSpatial.java
distribution/test/itests/test-itests-ddf/src/test/resources/TestSpatial/csw/request/query/CswCompoundAfterDateAndIntersectingWktPolygon.xml
distribution/test/itests/test-itests-ddf/src/test/resources/TestSpatial/csw/request/query/CswCompoundBeforeDateAndLikeText.xml
distribution/test/itests/test-itests-ddf/src/test/resources/TestSpatial/csw/request/query/CswCompoundLikeTextAndIntersectingWktLineString.xml
distribution/test/itests/test-itests-ddf/src/test/resources/TestSpatial/csw/request/query/CswLogicalOperatorContextualNotQuery.xml
distribution/test/itests/test-itests-ddf/src/test/resources/TestSpatial/csw/request/query/CswLogicalOperatorContextualOrQuery.xml

@roelens8 @tbatie 
@kcwire
@shaundmorris 
Build ddf and run the integration test TestSpatial
N/A
N/A

DDF-2067 Improved TestSpatial to include compound csw queries

---

catalog/plugin/catalog-plugin-versioning/src/main/resources/OSGI-INF/blueprint/blueprint.xml

Fixed blueprint specification of implementing interfaces of History Plugin
@bdeining @djblue 
@jlcsmith
@pklinef
Verify versioning plugin bundle starts successfully.
DDF-1897

DDF-1897: Corrected versioning plugin blueprint

---

platform/security/interceptor/security-interceptor-guest/pom.xml

removes a bad export
@coyotesqrl @pklinef 
@jaymcnallie
@kcwire

DDF-2085 - update security-interceptor-guest to not export it's package

---

platform/security/pdp/security-pdp-authzrealm/src/main/java/ddf/security/pdp/realm/AuthzRealm.java
platform/security/pdp/security-pdp-authzrealm/src/main/java/ddf/security/pdp/realm/xacml/processor/PollingPolicyFinderModule.java

Adds auditing to PDP config changes
@coyotesqrl 
@bcwaters 
@jckilmer 
@shaundmorris 
@stustison
Ensure changes to pdp configs are being logged manually
Added auditing to AuthzRealm and PollingPolicyFinderModule upon config changes

DDF-2078: Audit confguration changes to the PDP

---

platform/security/platform-security-session/src/main/java/org/codice/ddf/security/session/HashSessionIdManager.java
platform/security/sts/security-sts-server/src/main/java/ddf/security/sts/AuthNStatementProvider.java
platform/util/platform-util/src/main/java/org/codice/ddf/platform/util/RandomNumberGenerator.java

Renamed RandomNumberGenerator methods
@coyotesqrl 
@bcwaters 
@pklinef
@shaundmorris

DDF-2076: Rename RNG methods

---

platform/security/core/security-core-impl/pom.xml
platform/security/core/security-core-impl/src/main/java/ddf/security/config/impl/ConfigurationSecurityLogger.java
platform/security/core/security-core-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml
platform/security/platform-security-core-api/pom.xml
platform/security/platform-security-core-api/src/main/java/ddf/security/common/audit/SecurityLogger.java

logs changes made to configuration files
@roelens8 @coyotesqrl @bcwaters @jckilmer @tbatie 
@shaundmorris
@stustison
file system: sed -i 's/gree/blue/g' etc/org.codice.ddf.security.handler.guest.configuration.cfg
karaf console: config:edit org.codice.ddf.security.handler.guest.configuration; config:update
admin page :DDF Security>Configuration>Login Page>Save Changes
verify a log message like the following is logged to the security log.
` [INFO ] 2016-04-28 08:50:28,723 | Thread-16        | securityLogger  |  Subject: admin Configuration updated: {service.pid=org.codice.ddf.security.handler.guest.configuration, style=light-green, textColor=banner-text-black}`

DDF-2081 audit configuration changes.

---

distribution/docs/src/main/resources/_contents/securing-contents.adoc
platform/platform-migratable/src/main/java/org/codice/ddf/platform/migratable/impl/PlatformMigratable.java
platform/security/expansion/security-expansion-metacardattr-map/src/main/resources/OSGI-INF/blueprint/blueprint.xml
platform/security/expansion/security-expansion-metacardattr-map/src/main/resources/OSGI-INF/metatype/metatype.xml
platform/security/expansion/security-expansion-userattr-map/src/main/resources/OSGI-INF/blueprint/blueprint.xml
platform/security/expansion/security-expansion-userattr-map/src/main/resources/OSGI-INF/metatype/metatype.xml

Added empty expansion configuration files and changed their home to /etc
@coyotesqrl 
@jckilmer 
@bcwaters 
@shaundmorris
@stustison
Itests pass

DDF-1829: Create default expansion configuration files

---

catalog/transformer/catalog-transformer-streaming-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml

@AzGoalie @spearskw @bcwaters 
@kcwire
@shaundmorris 
Bamboo should pass
DDF-2089

DDF-2089 Add mimetypes to streaming transformers

---

catalog/transformer/catalog-transformer-streaming-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml

@AzGoalie @spearskw @bcwaters 
@kcwire
@shaundmorris 
Bamboo should pass
DDF-2089

DDF-2089 Add mimetypes to streaming input xformer

---

catalog/core/catalog-core-localstorageprovider/src/test/java/org/codice/ddf/catalog/content/impl/FileSystemStorageProviderTest.java
distribution/test/thirdparty/rest-assured/pom.xml
libs/libs-pomfix-run/pom.xml
platform/admin/core/admin-core-logviewer/package.json
platform/admin/core/admin-core-logviewer/src/test/js/uniq.js

Allows DDF to be, at minimum, quick-built on Windows. Full builds should be possible as well, but are less consistent. 
Mandatory: @figliold @garrettfreibott 
Optional: @oconnormi @bantillo 
@lessarderic
@shaundmorris
Full build on UNIX. 
Quick-build on Windows (must be successful) followed by a full-build on Windows (may take several attempts -- note any consistent failures). 
DDF-2092

DDF-2092: Bulk fixes for Windows builds

---

catalog/spatial/csw/spatial-csw-source-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/CswFilterDelegate.java
catalog/spatial/csw/spatial-csw-source-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/CswFilterFactory.java
catalog/spatial/csw/spatial-csw-source-common/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/TestCswCqlFilter.java
catalog/spatial/csw/spatial-csw-source-common/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/TestCswFilterDelegate.java
catalog/spatial/csw/spatial-csw-source-common/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/TestCswSourceBase.java

@tbatie @roelens8 
@kcwire 
@pklinef
Build ddf and send a case sensitive contextual query to a csw federated source

DDF-2087 Fixed Csw federated queries to set the matchCase field

---

catalog/spatial/registry/registry-federation-admin-service-impl/pom.xml

Fix a dependency in federation admin service pom that was missed in the transition from catalog to spatial. This issue blocks the release.
@jlcsmith @pklinef  
@jlcsmith
@pklinef 
Make sure the build works
DDF-2017

DDF-2017 Fix Federation Admin Service pom dependency

---

catalog/plugin/catalog-plugin-versioning/src/main/java/ddf/catalog/metacard/versioning/HistorianPlugin.java

Removes History metacard from the result list on an ingest
@djblue 
@kcwire
@pklinef

DDF-2131: Removed history metacards from ingest results

---

catalog/spatial/registry/registry-policy-plugin/src/main/java/org/codice/ddf/registry/policy/RegistryPolicyPlugin.java
catalog/spatial/registry/registry-policy-plugin/src/main/resources/OSGI-INF/metatype/metatype.xml

Pulls changes for registry policy plugin from the ddf-registry repo.
@tbatie @ricklarsen 
@figliold
@pklinef
Just needs prbs build 
Some minor changes were made in the ddf-registry repo that need to be merged over to codice/ddf
DDF-2104

DDF-2104 Updated Registry Policy Plugin metatype wording and cleaned up plugin accessors

---

distribution/docs/src/main/resources/_contents/_security-contents/managing-security-contents.adoc
distribution/docs/src/main/resources/_contents/securing-contents.adoc
platform/security/filter/security-filter-login/src/main/resources/OSGI-INF/metatype/metatype.xml
platform/security/policy/security-policy-context/src/main/resources/OSGI-INF/metatype/metatype.xml

Updates documentation for Web Context Policy manager
@coyotesqrl @tbatie @ryeats @roelens8 @bcwaters 
@shaundmorris
@stustison
Docs only. Review compiled documentation.
DDF-2149

Ddf 2149 Update documentation for Web Context Policy manager

---

distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestSpatial.java
distribution/test/itests/test-itests-ddf/src/test/resources/TestSpatial/csw/request/query/CswXPathExpressionQuery.xml
distribution/test/itests/test-itests-ddf/src/test/resources/TestSpatial/csw/request/query/CswXPathExpressionQueryWithAttributeSelector.xml
distribution/test/itests/test-itests-ddf/src/test/resources/TestSpatial/xml/PlainXmlFar.xml

Adds two csw xpath queries to TestSpatial
@tbatie @roelens8 
@figliold
@kcwire 
Run prbs
- [ x ] Update / Add Integration Tests

DDF-2080 Improved TestSpatial to include queries utilizing XPath

---

distribution/docs/src/main/resources/_contents/_catalog-contents/configuring-catalog-contents.adoc
distribution/docs/src/main/resources/_contents/_catalog-contents/extending-catalog-contents.adoc
distribution/docs/src/main/resources/_contents/configuring-contents.adoc
distribution/docs/src/main/resources/_contents/configuring-from-the-admin-console-contents.adoc
distribution/docs/src/main/resources/_contents/configuring-from-the-command-console-contents.adoc
distribution/docs/src/main/resources/_contents/integrating-contents.adoc
distribution/docs/src/main/resources/_contents/running-contents.adoc

Updates documentation for configuring an external LDAP server
@ryeats @roelens8 @coyotesqrl @tbatie @codice/security 
@shaundmorris
@stustison
Documentation only. review changes.
DDF-1796

Ddf 1796 Updates to docs / Configuring an external LDAP

---

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/CatalogFrameworkImpl.java
platform/security/filter/security-filter-authorization/src/main/java/org/codice/ddf/security/filter/authorization/AuthorizationFilter.java
platform/security/filter/security-filter-login/src/main/java/org/codice/ddf/security/filter/login/LoginFilter.java
platform/security/pdp/security-pdp-authzrealm/src/main/java/ddf/security/pdp/realm/AuthzRealm.java
platform/security/platform-security-core-api/pom.xml
platform/security/platform-security-core-api/src/main/java/ddf/security/permission/CollectionPermission.java
platform/security/platform-security-core-api/src/main/java/ddf/security/permission/MatchOneCollectionPermission.java
platform/security/sts/security-sts-attributequerycommon/pom.xml
platform/security/sts/security-sts-attributequerycommon/src/main/java/org/codice/ddf/security/claims/attributequery/common/AttributeQueryClaimsHandler.java
platform/security/sts/security-sts-ldaplogin/src/main/java/ddf/ldap/ldaplogin/SslLdapLoginModule.java

Reduces the overall number of audit logs for performance reasons.
@coyotesqrl @ryeats 
@pklinef
@stustison

DDF-2158 reduced the overall number of audit logs

---

distribution/docs/src/main/resources/_contents/_registry-contents/extending-registry-contents.adoc
distribution/docs/src/main/resources/_contents/_registry-contents/managing-registry-contents.adoc
distribution/docs/src/main/resources/documentation.adoc
distribution/docs/src/main/resources/extending.adoc
distribution/docs/src/main/resources/integrating.adoc
distribution/docs/src/main/resources/managing.adoc
pom.xml

This is a very rough template for the documentation that will be generated by the DDF-Registry. Contents will be filled in and are subject to change. Having the structure will enable work to begin. 
@clockard @gordocanchola @vinamartin @brianfelix @mcalcote @oscaritoro 
@shaundmorris
@stustison
Build only. Verify passes all tests.
Inclusion in the final documentation is currently commented out, so no rendering checks are needed at this time.
Initial template to establish documentation structure and acceptance criteria for future work. This is not the final version of the documentation.
[DDF-2155](https://codice.atlassian.net/browse/DDF-2155)
[DDF-2156](https://codice.atlassian.net/browse/DDF-2156)
[DDF-2157](https://codice.atlassian.net/browse/DDF-2157)

DDF-2155: initial commit for Registry Documentation

---

platform/security/pdp/security-pdp-authzrealm/pom.xml
platform/security/pdp/security-pdp-authzrealm/src/main/java/ddf/security/pdp/realm/xacml/XACMLConstants.java
platform/security/pdp/security-pdp-authzrealm/src/main/java/ddf/security/pdp/realm/xacml/XacmlPdp.java
platform/security/pdp/security-pdp-authzrealm/src/test/java/ddf/security/pdp/realm/xacml/XacmlPdpTest.java
platform/security/security-services-app/src/main/resources/features.xml

Updates the XACML PDP to attempt to determine the value types for resource and subject attributes
@roelens8 @ryeats 
@shaundmorris 
@stustison
Full build on ddf.

DDF-2110 The XACML PDP should attempt to determine the value types

---

catalog/core/catalog-core-standardframework/pom.xml
catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/CatalogFrameworkImpl.java
catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/impl/CatalogFrameworkImplTest.java
distribution/ddf-common/src/main/resources/etc/system.properties
distribution/docs/src/main/resources/_contents/configuring-from-configuration-files-contents.adoc
distribution/docs/src/main/resources/_contents/extending-contents.adoc
platform/util/platform-util/src/main/java/org/codice/ddf/platform/util/InputValidation.java
platform/util/platform-util/src/test/java/org/codice/ddf/platform/util/InputValidationTest.java

Adds input validation for files and mime types.
@ryeats @tbatie 
@shaundmorris
@stustison
…es and check mime types

DDF-2151 added an input validation utility

---

catalog/schematron/catalog-schematron-plugin/src/main/java/ddf/services/schematron/SchematronValidationService.java
catalog/schematron/catalog-schematron-plugin/src/test/java/ddf/services/schematron/SchematronValidationServiceTest.java

This is just a rebased version of https://github.com/codice/ddf/pull/802
@shaundmorris

DDF-2143 SchematronValidationService sanitizes warnings and errors

---

distribution/docs/src/main/resources/_contents/_catalog-contents/extending-catalog-contents.adoc
distribution/docs/src/main/resources/_contents/_catalog-contents/integrating-catalog-contents.adoc
distribution/docs/src/main/resources/_contents/_security-contents/integrating-security-contents.adoc

Removed refs to deprecated DdfConfigurationWatcher from docs.
@bdeining @spearskw @jrnorth @mcalcote @Lambeaux 
@lessarderic
@shaundmorris
Documentation doesn't break build and renders correctly
DDF-2167
https://codice.atlassian.net/browse/DDF-2167

DDF-2167 Removed refs to DdfConfigurationWatcher from docs

---

catalog/catalog-app/src/main/resources/features.xml
catalog/core/catalog-core-commands/pom.xml
catalog/core/catalog-core-commands/src/main/resources/bin/catalog-export
catalog/core/catalog-core-commands/src/main/resources/bin/catalog-export.bat

This PR renames the export scripts in catalog-core-commands and adds some additional status messages.
@dcruver 
@jrnorth 
@jlcsmith
@kcwire
Build DDF and run the catalog-export script
https://codice.atlassian.net/browse/DDF-2135

DDF-2135 Renamed export scripts in catalog-core-commands and added additional status messages

---

platform/admin/core/admin-core-logviewer/package.json
platform/admin/core/admin-core-logviewer/src/main/resources/index.html

Used exact version numbers for NPM dependencies.
@garrettfreibott @djblue 
@lessarderic
@stustison
Updated version numbers in the package.json file.
Removed a reference to a CSS file.

DDF-2166; Log viewer UI should specify only exact versions of NPM dependencies

---

catalog/spatial/registry/registry-federation-admin-service-impl/pom.xml
catalog/spatial/registry/registry-federation-admin-service-impl/src/main/java/org/codice/ddf/registry/federationadmin/service/impl/FederationAdminServiceImpl.java
catalog/spatial/registry/registry-federation-admin-service-impl/src/main/java/org/codice/ddf/registry/federationadmin/service/impl/RefreshRegistrySubscriptions.java
catalog/spatial/registry/registry-federation-admin-service-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/spatial/registry/registry-federation-admin-service-impl/src/main/resources/OSGI-INF/metatype/metatype.xml
catalog/spatial/registry/registry-federation-admin-service-impl/src/test/java/org/codice/ddf/registry/federationadmin/service/impl/FederationAdminServiceImplTest.java
catalog/spatial/registry/registry-federation-admin-service-impl/src/test/java/org/codice/ddf/registry/federationadmin/service/impl/RefreshRegistrySubscriptionsTest.java
catalog/spatial/registry/registry-federation-admin-service/src/main/java/org/codice/ddf/registry/federationadmin/service/FederationAdminService.java
catalog/spatial/registry/registry-identification-plugin/src/main/java/org/codice/ddf/registry/identification/IdentificationPlugin.java

DDF-2102: Updated registry-federation-admin-service-impl and added unit tests

---

catalog/spatial/registry/registry-identification-plugin/pom.xml
catalog/spatial/registry/registry-identification-plugin/src/main/java/org/codice/ddf/registry/identification/IdentificationPlugin.java
catalog/spatial/registry/registry-identification-plugin/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/spatial/registry/registry-identification-plugin/src/test/java/org/codice/ddf/registry/identification/IdentificationPluginTest.java
distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestRegistry.java

The identification plugin has been updated during development on the ddf-registry branch. This pr brings those changes over to the codice ddf code base. Test coverage has been improved and functionality changes have been made to fix bugs and improve performance. 
@spearskw @harrison-tarr 
@figliold 
@shaundmorris 
Build, run itests.
The test coverage took a significant dip during revision has been improved over that ratio, not the ratio from when ddf-registry split from ddf.
DDF-2103 Update unit tests
DDF-2058 Remove dependency on admin service
DDF-2014 Update to preserve local transient attributes
Backend only

DDF-1937 Merge updated identification plugin from ddf-registry to ddf

---

catalog/spatial/registry/registry-ebrim-transformer/src/main/java/org/codice/ddf/registry/converter/RegistryPackageConverter.java
catalog/spatial/registry/registry-ebrim-transformer/src/main/java/org/codice/ddf/registry/transformer/RegistryTransformer.java
catalog/spatial/registry/registry-ebrim-transformer/src/test/java/org/codice/ddf/registry/transformer/RegistryTransformerTest.java

This PR merges in changes that were made to the ebrim transformer during development on the ddf-registry branch. 
@harrison-tarr @spearskw 
@pklinef
@shaundmorris 
Please review the code, build and the run tests.
DDF-2109 - Registry package converter uses Registry Package Utils 
Backend Functionality

DDF-1886 Merge ebrim transformer updates from ddf-registry to ddf

---

distribution/ddf-common/src/main/resources/etc/custom.properties
distribution/ddf/src/main/filtered-resources/etc/org.apache.karaf.features.cfg
distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/AbstractIntegrationTest.java
platform/admin/core/admin-core-api/pom.xml
platform/compression/platform-compression-exi/pom.xml
platform/platform-app/pom.xml
platform/platform-app/src/main/resources/features.xml
platform/platform-configuration/pom.xml
pom.xml

cherry pick the karaf upgrade to back port it to the 2.9.x branch
@shaundmorris
@stustison

DDF-2079 upgrade to karaf 4.0.5

---

platform/security/platform-security-core-api/pom.xml
platform/security/platform-security-core-api/src/main/java/ddf/security/SubjectUtils.java
platform/security/platform-security-core-api/src/test/java/ddf/security/SubjectUtilsTest.java

Adds a new SubjectUtils helper for getting subject roles.
@pklinef 
@rzwiefel 
@kcwire 
@stustison
Build passes.
[DDF-2159](https://codice.atlassian.net/browse/DDF-2159)

DDF-2159: Added a new SubjectUtils helper for getting subject attributes.

---

distribution/docs/src/main/resources/_contents/integrating-contents.adoc

Updates the integration docs with corrections and format fixes. 
@ricklarsen 
@oconnormi 
@jrnorth 
@lessarderic
@shaundmorris
Read it. 
Okay, maybe build DDF docs and ensure HTML/PDF renders fine. 
No. 
DDF-2141

DDF-2141: Update Example Query Response table and Activity Events table

---

catalog/admin/admin-poller-service/pom.xml
catalog/admin/admin-poller-service/src/main/java/org/codice/ddf/catalog/admin/poller/AdminPollerServiceBean.java
catalog/admin/admin-poller-service/src/main/java/org/codice/ddf/catalog/admin/poller/AdminPollerServiceBeanMBean.java
catalog/admin/admin-poller-service/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/admin/admin-poller-service/src/test/java/org/codice/ddf/catalog/admin/poller/AdminPollerTest.java
catalog/admin/module/catalog-admin-module-sources/package.json
catalog/admin/module/catalog-admin-module-sources/src/main/webapp/js/model/Organization.js
catalog/admin/module/catalog-admin-module-sources/src/main/webapp/js/model/Service.js
catalog/admin/module/catalog-admin-module-sources/src/main/webapp/js/model/Source.js
catalog/admin/module/catalog-admin-module-sources/src/main/webapp/js/module.js
catalog/admin/module/catalog-admin-module-sources/src/main/webapp/js/view/Accordion.view.js
catalog/admin/module/catalog-admin-module-sources/src/main/webapp/js/view/AccordionCollectionView.js
catalog/admin/module/catalog-admin-module-sources/src/main/webapp/js/view/ConfigurationEdit.view.js
catalog/admin/module/catalog-admin-module-sources/src/main/webapp/js/view/ModalSource.view.js
catalog/admin/module/catalog-admin-module-sources/src/main/webapp/js/view/Organization.view.js
catalog/admin/module/catalog-admin-module-sources/src/main/webapp/js/view/Source.view.js
catalog/admin/module/catalog-admin-module-sources/src/main/webapp/less/styles.less
catalog/admin/module/catalog-admin-module-sources/src/main/webapp/templates/accordion.hbs
catalog/admin/module/catalog-admin-module-sources/src/main/webapp/templates/bindingTitles.hbs
catalog/admin/module/catalog-admin-module-sources/src/main/webapp/templates/optionLabelType.hbs
catalog/admin/module/catalog-admin-module-sources/src/main/webapp/templates/sourceModal.handlebars
catalog/admin/module/catalog-admin-module-sources/src/main/webapp/templates/sourceOrganization.hbs

This PR updates sources tab to show additional information for registry entries. It also adds accordions to the Binding Configurations.
@ryeats @stustison
@lessarderic
@shaundmorris
Verify the build.
DDF-1964
Adding UI changes
Adding accordion to the Binding Configurations section
Adding action provider link in the sources tab
Adding action providers to the allSourceInfo object
Removing updatePublications that was moved to another class in another ticket

DDF-1964 Update Sources Tab to show additional information for registry entries

---

catalog/spatial/registry/registry-federation-admin-service-impl/pom.xml
catalog/spatial/registry/registry-federation-admin-service-impl/src/main/java/org/codice/ddf/registry/federationadmin/service/impl/RefreshRegistrySubscriptions.java

Add subject to getRegistryMetacardsMap.
@clockard @brianfelix 
@shaundmorris @stustison 
Bamboo and you, check the changed method.
Tested myself 👍 
DDF-2102

DDF-2102 Updated security in getRegistryMetacardsMap from registry-federation-admin-serivce-impl

---

catalog/catalog-app/pom.xml
catalog/pom.xml
catalog/spatial/spatial-app/pom.xml
distribution/docs/pom.xml
distribution/pom.xml
distribution/sdk/pom.xml
distribution/test/pom.xml
libs/activities/pom.xml
libs/checksum/pom.xml
libs/common-system/pom.xml
libs/httpproxy/pom.xml
libs/notifications/pom.xml
libs/platform-configuration-impl/pom.xml
platform/pom.xml
pom.xml

Makes maven downloads go through https instead of http
@ahoffer @spearskw @tbatie 
@jaymcnallie
@stustison 
DDF-2172

DDF-2172 Change repositories to https

---

platform/security/common/src/main/java/ddf/security/service/impl/AbstractAuthorizingRealm.java
platform/security/pdp/security-pdp-authzrealm/src/main/resources/OSGI-INF/blueprint/blueprint.xml

@spearskw @ryeats  
@coyotesqrl
@stustison

DDF-2222 added the metacard attribute expansion to the pdp

---

distribution/docs/src/main/resources/_contents/_registry-contents/managing-registry-contents.adoc
distribution/docs/src/main/resources/_contents/_security-contents/managing-security-contents.adoc
distribution/docs/src/main/resources/_contents/config.adoc
distribution/docs/src/main/resources/_contents/running-contents.adoc
distribution/docs/src/main/resources/documentation.adoc
distribution/docs/src/main/resources/managing.adoc

Initial Draft of managing DDF Registry documentation.
@mcalcote @brianfelix @vinamartin @gordocanchola @clockard @oscaritoro 
@shaundmorris
@stustison
Documentation renders correctly and is free of typos.
Details may change as registry is finalized.
https://codice.atlassian.net/browse/DDF-2155
na

DDF-2155: added documentation for managing DDF-registry.

---

distribution/docs/src/main/resources/_contents/_admin-contents/managing-admin-contents.adoc
distribution/docs/src/main/resources/_contents/_catalog-contents/configuring-catalog-contents.adoc
distribution/docs/src/main/resources/_contents/_catalog-contents/extending-catalog-contents.adoc
distribution/docs/src/main/resources/_contents/_catalog-contents/integrating-catalog-contents.adoc
distribution/docs/src/main/resources/_contents/_security-contents/integrating-security-contents.adoc
distribution/docs/src/main/resources/_contents/_solr-contents/managing-solr-contents.adoc
distribution/docs/src/main/resources/_contents/_spatial-contents/integrating-spatial-contents.adoc
distribution/docs/src/main/resources/_contents/_ui-contents/managing-ui-contents.adoc
distribution/docs/src/main/resources/_contents/configuring-from-configuration-files-contents.adoc
distribution/docs/src/main/resources/_contents/configuring-from-the-admin-console-contents.adoc
distribution/docs/src/main/resources/_contents/extending-contents.adoc
distribution/docs/src/main/resources/_contents/integrating-contents.adoc
distribution/docs/src/main/resources/_contents/quickstart-contents.adoc
distribution/docs/src/main/resources/_contents/running-contents.adoc
distribution/docs/src/main/resources/_contents/securing-contents.adoc
pom.xml

Updates references in the documentation to a maven property that is substituted upon building.
@Lambeaux @mcalcote @jrnorth 
@figliold 
@shaundmorris
documentation renders correctly, substitutions successful, all tests pass
https://codice.atlassian.net/browse/DDF-2174

DDF-2174: set maven properties for 'localhost' references in docs.

---

distribution/docs/src/main/resources/_contents/_catalog-contents/extending-catalog-contents.adoc

Adds documentation 
@jrnorth 
@ricklarsen 
@jaymcnallie
@shaundmorris 
Make sure the documentation looks right. 
DDF-2218

DDF-2218 Add documentation for Metacard Validity Marker plugin

---

distribution/docs/src/main/resources/_contents/_geowebcache-contents/managing-geowebcache-contents.adoc
distribution/docs/src/main/resources/documentation.adoc
distribution/docs/src/main/resources/managing.adoc
pom.xml

Add managing documentation for GeoWebCache application
@spearskw @bdeining 
@jlcsmith 
@jaymcnallie 
Doc only change. Builds successfully, review rendered documentation.
https://codice.atlassian.net/browse/DDF-2163

DDF-2163: documented managing DDF GeoWebCache

---

catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/util/impl/DescribableServiceMap.java
distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFederation.java

Fixes a bug in DescribableServceMap where the internal map was not being updated to reflect changes in the describable id. This has been fixed by making the map listen for service change events and updating its internal map appropriately.
@tbatie @harrison-tarr 
@shaundmorris 
@pklinef
Follow the steps in DDF-2216 and verify there is no longer an error when querying after the source name change
DDF-2216

DDF-2216 Fix describable name change update issue in DescribableServceMap

---

distribution/test/itests/test-itests-common/pom.xml
distribution/test/itests/test-itests-common/src/test/java/ddf/common/test/cometd/CometDClient.java
distribution/test/itests/test-itests-common/src/test/java/ddf/common/test/cometd/CometDMessageValidator.java
distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/AbstractIntegrationTest.java
distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFederation.java

Enhance resource download itests so that they verify the correct notifications and activities are received
@lessarderic
@oconnormi 
@Lambeaux 
@coyotesqrl 
@shaundmorris 
PRBS
DDF-2213

DDF-2213: Enhance resource download itests so that they verify the correct notifications and activities are received

---

platform/admin/admin-app/pom.xml

Fixs a missing dependency for pom-fix under the admin-app
@bcwaters @ryeats 
@coyotesqrl
@shaundmorris

DDF-2196: Separate admin duties via Admin Console

---

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/CatalogFrameworkImpl.java

Streamlines how default values are injected into metacards in the catalog framework.
@rzwiefel 
@glenhein 
@jlcsmith
@kcwire
Create a JSON file that includes some default attribute values as shown in the documentation, ingest some metacards, and verify that the default values were added where appropriate.
[DDF-2125](https://codice.atlassian.net/browse/DDF-2125)

DDF-2125 Streamline default value injection for metacards

---

distribution/docs/src/main/resources/_contents/_geowebcache-contents/managing-geowebcache-contents.adoc
distribution/docs/src/main/resources/documentation.adoc
distribution/docs/src/main/resources/managing.adoc
pom.xml

Adds managing documentation for DDF GeoWebCache
@jlcsmith
@stustison
successful build
DDF-2163

DDF-2163: documented managing DDF GeoWebCache (#836)

---

catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/package.json
catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/model/Association.js
catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/model/Field.js
catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/model/FieldDescriptors.js
catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/model/Node.js
catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/model/Segment.js
catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/view/Association.view.js
catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/view/Field.view.js
catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/view/NodeModal.view.js
catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/view/Registry.view.js
catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/view/Segment.view.js
catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/less/styles.less
catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/templates/associationList.handlebars
catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/templates/associationRow.handlebars
catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/templates/customFieldList.handlebars
catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/templates/field.handlebars
catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/templates/segmentRow.handlebars
catalog/spatial/registry/registry-common/src/main/java/org/codice/ddf/registry/common/RegistryConstants.java
catalog/spatial/registry/registry-schema-bindings/src/main/java/org/codice/ddf/registry/schemabindings/converter/type/SlotTypeConverter.java
catalog/spatial/registry/registry-schema-bindings/src/main/java/org/codice/ddf/registry/schemabindings/converter/web/SlotWebConverter.java
catalog/spatial/registry/registry-schema-bindings/src/test/java/org/codice/ddf/registry/schemabindings/RegistryPackageWebConverterTest.java
catalog/spatial/registry/registry-schema-bindings/src/test/resources/csw-full-registry-package.xml
distribution/ddf-common/src/main/resources/etc/registry/registry-custom-slots.json

Updates the registry local nodes edit tab in the admin ui.
@brendan-hofmann  @mcalcote 
@figliold 
@pklinef
Build and install normally. Install registry and then play around with the local nodes tab in the admin ui to verify functionality of editing/updating/saving of various kinds of fields/configurations
DDF-2190
- Added the concept of 'advanced sections/fields' to simplify the ui
- Moved all fields to the configuration file for fields instead of just having the slots there.
- Added 'bounds' type that lets the user specify an upper and lower geo corners
- Fixed some eventing that was a carry over from previouse pr in this area
- Several other small bug fixes/improvments

DDF-2190 Updates to the registry local node edit page in the admin ui.

---

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/CatalogFrameworkImpl.java

Streamlines how default values are injected into metacards in the catalog framework.
@kcwire
Create a JSON file that includes some default attribute values as shown in the documentation, ingest some metacards, and verify that the default values were added where appropriate.
[DDF-2125](https://codice.atlassian.net/browse/DDF-2125)

DDF-2125 Streamline default value injection (#870)

---

distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestSecurity.java

@jlcsmith
@stustison
Verify TestSecurity itests pass

DDF-2196: Corrected hard-coding of DDF version in TestSecurity (backport)

---

catalog/catalog-app/pom.xml
libs/libs-pomfix-run/package.json
libs/libs-pomfix-run/pom.xml
libs/libs-pomfix/bin/pom-fix
libs/libs-pomfix/lib/util.js

Port of #893 to 2.9.x.
Already been reviewed.
@pklinef
@stustison
Already been verified.
[DDF-2232](https://codice.atlassian.net/browse/DDF-2232)

DDF-2232: updated pom-fix to run correctly on maven build in windows, osx, and linux.

---

distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestSecurity.java

@jlcsmith
@stustison 
Verify TestSecurity itests pass
DDF-2196

DDF-2196: Corrected hard-coding of DDF version in TestSecurity

---

distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalog.java

DDF-2131 - Fixed a hard coded version and switched to system property

---

distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalog.java

DDF-2131: [2.9.x] - Fixed a hard coded version and switched to system property

---

distribution/sdk/sdk-app/src/main/resources/features.xml

Changes the feature order of the sdk-app
@coyotesqrl 
@bcwaters 
@jlcsmith
@kcwire 
Itests pass
TestSecurity was failing due to features in sdk-app uninstalling improperly

DDF-2252: Fix sdk-app features installation

---

platform/security/common/src/main/java/org/codice/ddf/security/common/Security.java

removes the hardcoded admin role
@coyotesqrl
@stustison

DDF-2253 removed the hardcoded admin role

---

catalog/ui/search-ui/standard/src/main/webapp/js/model/Filter.js
catalog/ui/search-ui/standard/src/main/webapp/js/model/Query.js
catalog/ui/search-ui/standard/src/main/webapp/js/view/filter/FacetItem.view.js
catalog/ui/search-ui/standard/src/main/webapp/js/view/filter/FilterCollection.view.js
catalog/ui/search-ui/standard/src/main/webapp/js/view/filter/FilterItem.view.js
catalog/ui/search-ui/standard/src/main/webapp/templates/filter/facet.item.handlebars

Added DDF-2220 to 2.9.x
@pklinef
@shaundmorris
…h is performed (#886)
* DDF-2220: Removed unused code that caused checkboxes to always be checked
* DDF-2220: Fixed metadata-content-type in the filter view
* DDF-2220: Removed dead code
* DDF-2220: changed clone to use toJSON instead

DDF-2220: Additional query parameters are not preserved after a search is performed

---

distribution/docs/src/main/resources/_contents/_admin-contents/extending-admin-contents.adoc
distribution/docs/src/main/resources/_contents/quickstart-contents.adoc
distribution/docs/src/main/resources/_contents/running-contents.adoc
distribution/docs/src/main/resources/_contents/securing-contents.adoc

Update documentation to include description of logviewer.
minor copy edits to documentation.
@lessarderic
@shaundmorris
successful build
https://codice.atlassian.net/browse/DDF-2236

DDF-2236: added logviewer to docs; copy edits

---

catalog/spatial/geocoding/spatial-geocoding-extract/pom.xml

fixes offline gazetteer
@coyotesqrl
@stustison

DDF-2255 - updated embedded dependencies

---

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/CachingFederationStrategy.java
catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/CatalogFrameworkImpl.java

@coyotesqrl
@pklinef
@shaundmorris
@stustison

DDF-2131: removed anytags query from catalogframework

---

catalog/spatial/registry/registry-api-impl/src/main/java/org/codice/ddf/registry/api/impl/RegistryStorePublisher.java
catalog/spatial/registry/registry-identification-plugin/src/main/java/org/codice/ddf/registry/identification/IdentificationPlugin.java
catalog/spatial/registry/registry-identification-plugin/src/test/java/org/codice/ddf/registry/identification/IdentificationPluginTest.java
catalog/spatial/registry/registry-source-configuration-handler/src/main/java/org/codice/ddf/registry/source/configuration/SourceConfigurationHandler.java

Cherry picked from codice master
@shaundmorris
@stustison
https://github.com/codice/ddf/pull/944
DDF-2259

DDF 2259 2.9.x Fixed Registry IdentificationPlugin update method

---

distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestRegistry.java

Fixes registry itest bug
@mcalcote @ani6gup 
@coyotesqrl
@pklinef
DDF-2259

DDF-2259 Fixed registry itest date issue

---

catalog/spatial/registry/registry-federation-admin-service-impl/src/main/java/org/codice/ddf/registry/federationadmin/service/impl/RegistryPublicationServiceImpl.java
catalog/spatial/registry/registry-federation-admin-service-impl/src/test/java/org/codice/ddf/registry/federationadmin/service/impl/RegistryPublicationServiceImplTest.java

Fixes a couple of registry bugs
@mcalcote @clockard @vinamartin
@coyotesqrl 
@shaundmorris 
Build and start up two instances. Have one instance publish to the other. In the instance that published, update the identity node. Verify in the other instance's solr that the change was saved.
DDF-2259
Fixing the update to use registry store ids instead of registry ids
Updating tests

DDF-2259 Registry IdentificationPlugin is not handling updates updates correctly (Updated)

---

catalog/core/catalog-core-federationstrategy/src/test/java/ddf/catalog/federation/impl/FederationStrategyTest.java
catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/history/Historian.java
catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/impl/CatalogFrameworkImplTest.java

@coyotesqrl
@pklinef
@shaundmorris
@jlcsmith
- this was originally supposed to be on by default but there was some discord between the initialized value and metatype default

DDF-2131: Set historian to be on by default

---

platform/admin/core/admin-core-appservice/pom.xml
platform/admin/core/admin-core-appservice/src/main/java/org/codice/ddf/admin/application/service/impl/ApplicationServiceImpl.java

DDF-2196 Runs calls to check subject permissions as current user or elevates

---

platform/admin/core/admin-core-appservice/pom.xml
platform/admin/core/admin-core-appservice/src/main/java/org/codice/ddf/admin/application/service/impl/ApplicationServiceImpl.java

DDF-2196-2.9.X Runs calls to check subject permissions as current user or elevates.

---

platform/admin/core/admin-core-appservice/src/test/java/org/codice/ddf/admin/application/service/impl/ApplicationServiceImplTest.java

This commit fixes a unit test.
@coyotesqrl
@stustison
Full build/test 
N/A
DDF-2196
N/A

DDF-2196 Runs calls to check subject permissions as current user or elevates.

---

pom.xml

Updates the root pom to configure the maven front-end plugin to use the Codice Npm Registry
@coyotesqrl
@stustison
Build DDF to ensure that all npm dependencies required are pulled down

DDF-2261 Transition all npm dependencies to Codice Nexus

---

catalog/transformer/catalog-transformer-streaming-lib/src/main/java/org/codice/ddf/transformer/xml/streaming/lib/SaxEventHandlerDelegate.java
catalog/transformer/catalog-transformer-streaming-lib/src/main/java/org/codice/ddf/transformer/xml/streaming/lib/SaxEventToXmlElementConverter.java
catalog/transformer/catalog-transformer-streaming-lib/src/test/java/org/codice/ddf/transformer/xml/streaming/lib/TestGenericXmlLib.java

Brings master up to date with the PR that went into 2.9.x. More unit tests will be added in a later PR
See: https://github.com/codice/ddf/pull/936
@shaundmorris @coyotesqrl 
DDF-2250

DDF-2250 Make SaxEventToXmlConverter handle edge cases

---

catalog/admin/module/catalog-admin-module-sources/Gruntfile.js
catalog/admin/module/catalog-admin-module-sources/bower.json
catalog/admin/module/catalog-admin-module-sources/package.json
catalog/resourcemanagement/resourcemanagement-querymonitor-ui/Gruntfile.js
catalog/resourcemanagement/resourcemanagement-usage-ui/Gruntfile.js
catalog/spatial/geocoding/spatial-geocoding-admin-module/Gruntfile.js
catalog/spatial/geowebcache/geowebcache-admin-plugin/Gruntfile.js
catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/Gruntfile.js
catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/bower.json
catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/package.json
catalog/spatial/registry/registry-admin-modules/registry-admin-remote-ui/Gruntfile.js
catalog/spatial/registry/registry-admin-modules/registry-admin-remote-ui/package.json
catalog/ui/search-ui/standard/Gruntfile.js
catalog/ui/search-ui/standard/bower.json
platform/admin/core/admin-core-logviewer/src/main/resources/index.html
platform/admin/core/admin-core-logviewer/src/main/webapp/js/components/log-viewer/log-viewer.less
platform/admin/modules/admin-metrics-ui/Gruntfile.js
platform/admin/modules/admin-metrics-ui/bower.json
platform/admin/modules/admin-metrics-ui/package.json
platform/admin/modules/admin-security-certificate-ui/Gruntfile.js
platform/admin/modules/admin-security-certificate-ui/bower.json
platform/admin/modules/admin-security-ui/Gruntfile.js
platform/admin/modules/admin-security-ui/bower.json
platform/admin/ui/Gruntfile.js
platform/admin/ui/bower.json
platform/error/platform-error-impl/bower.json
platform/security/handler/security-handler-guest/Gruntfile.js
platform/security/handler/security-handler-guest/bower.json
platform/security/idp/security-idp-server/Gruntfile.js
platform/security/idp/security-idp-server/bower.json

Points all UIs at the local copy of Lato instead of going out to Google for it.
@codice/ui @ryeats @clockard 
@pklinef
@stustison
ensure that all UIs are reachable and look correct

DDF-2270 pointed all UIs at the local copy of the Lato font

---

distribution/install-profiles/src/main/resources/features.xml

@stustison @pklinef 
Merged to master here: 
https://github.com/codice/ddf/commit/61596d72800892423045422f8f1c3512edd45fc3

DDF-2271- Adds Registry app to install profiles

---

catalog/spatial/registry/registry-schema-bindings/src/main/java/org/codice/ddf/registry/schemabindings/converter/type/ServiceTypeConverter.java
catalog/spatial/registry/registry-schema-bindings/src/test/java/org/codice/ddf/registry/schemabindings/RegistryPackageWebConverterTest.java
catalog/spatial/registry/registry-schema-bindings/src/test/resources/csw-full-registry-package.xml
catalog/spatial/registry/registry-schema-bindings/src/test/resources/csw-registry-package-smaller.xml

@shaundmorris @lessarderic 
Merged to master here https://github.com/codice/ddf/pull/977

DDF-2269: Sets the Service attribute on a registry metacard generated XML

---

catalog/plugin/catalog-plugin-metacard-validation/src/main/resources/OSGI-INF/metatype/metatype.xml

Update the tooltip in the Metacard Validity Marker Plugin to be more descriptive and clear
@emanns95 
@spearskw 
@coyotesqrl 
@stustison
In a DDF, make sure the tooltip is clearer than it used to be.

DDF-2302 Increase clarity of tooltip in MVMP Metatype

---

catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/validation/ValidatePrinter.java

Fixes bad logic which hides validation errors from being printed.
@spearskw 
@coyotesqrl
@jaymcnallie
@shaundmorris
Full Build
DDF-2244

DDF-2244 Updated ValidatePrinter.printEntry to print when errors or warnings occur

---

catalog/ui/search-ui/standard/src/main/webapp/js/model/Metacard.js

This PR fixes MutliPolygon rendering in Cesium.
@codice/ui 
@jlcsmith
@stustison
- Build DDF,
- Ingest a resource that will result in a multipolygon geometry
- Navigate to the Standard Search UI and observe it being rendered correctly
https://codice.atlassian.net/browse/DDF-1804
https://codice.atlassian.net/browse/DDF-1804

DDF-1804 Fixed MultiPolygon rendering in Cesium

---

catalog/plugin/catalog-plugin-videothumbnail/pom.xml
dependency-check-maven-config.xml

@ryeats @adimka @tbatie 
@coyotesqrl 
@shaundmorris
A successful build is sufficient
There is a PR to thirdparty that contains the new binaries.  This PR will not work until that one is merged
DDF-2173

DDF-2235 Update ffmpeg to address related OWASP findings

---

catalog/plugin/catalog-plugin-videothumbnail/pom.xml
dependency-check-maven-config.xml

@coyotesqrl
@shaundmorris 
Once this has been hero'd for the master PR and merged the binaries can be considered tested.

DDF-2235-2.9.x Update ffmpeg to address related OWASP findings

---

catalog/core/catalog-core-localstorageprovider/pom.xml
catalog/core/catalog-core-localstorageprovider/src/main/java/org/codice/ddf/catalog/content/impl/FileSystemStorageProvider.java
catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/CatalogFrameworkImpl.java

Close InputStream objects returned by ContentItem#getInputStream.
@bdeining 
@jrnorth 
@kcwire 
@lcrosenbu 
@beyelerb
@jlcsmith
Build and run under Windows. Configure the content directory monitor. Copy multiple files into the monitored directory. Watch the log file and verify that no errors are thrown. 
DDF-2322

DDF-2322 close InputStream objects returned by ContentItem#getInputStream

---

distribution/docs/src/main/resources/_contents/_spatial-contents/integrating-spatial-contents.adoc

@ricklarsen @bcwaters 
@coyotesqrl
@shaundmorris

DDF-2310: Add example queries to CSW docs

---

catalog/plugin/catalog-plugin-expirationdate/src/main/java/org/codice/ddf/catalog/plugin/expiration/ExpirationDatePlugin.java
catalog/plugin/catalog-plugin-expirationdate/src/test/java/org/codice/ddf/catalog/plugin/expiration/TestExpirationDatePlugin.java

Resolve build failure in Expiration Date Plugin due to taxonomy refactor of Metacard -> Core.
@bdeining 
@coyotesqrl 
@jlcsmith
@kcwire
Successful DDF build. 
https://codice.atlassian.net/browse/DDF-2274

DDF-2274 Resolving build failure in expiration date due to taxonomy change

---

platform/admin/modules/admin-security-certificate-ui/src/main/webapp/js/model/Certificate.js
platform/admin/modules/admin-security-certificate-ui/src/main/webapp/js/model/UrlCertificate.js
platform/admin/modules/admin-security-certificate-ui/src/main/webapp/js/view/UploadModal.view.js
platform/admin/modules/admin-security-certificate-ui/src/main/webapp/less/styles.less
platform/admin/modules/admin-security-certificate-ui/src/main/webapp/templates/certificateDetail.handlebars
platform/admin/modules/admin-security-certificate-ui/src/main/webapp/templates/uploadModal.handlebars
platform/security/certificate/security-certificate-keystoreeditor/pom.xml
platform/security/certificate/security-certificate-keystoreeditor/src/main/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditor.java
platform/security/certificate/security-certificate-keystoreeditor/src/main/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditorMBean.java
platform/security/certificate/security-certificate-keystoreeditor/src/test/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditorTest.java

@coyotesqrl @andrewkfiedler @djblue 
@pklinef
@stustison

DDF-2285 added URL tab to certificate upload to allow adding trusted certificates by URL

---

distribution/test/itests/test-itests-common/src/test/java/ddf/common/test/cometd/CometDClient.java
distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFederation.java

Adds support for download cancellation to the CometDClient used in itests
@bantillo 
@Lambeaux 
@oconnormi 
@cmthom10 
@coyotesqrl
@shaundmorris 
Hero build
PR https://github.com/codice/ddf/pull/1016 needs to be merged before this PR can be merged
DDF-2315

DDF-2315: Add support for download cancellation to the CometDClient

---

catalog/spatial/csw/spatial-csw-source/src/main/resources/OSGI-INF/metatype/metatype.xml

This PR fixes a typo in the CSW Source Metatype
@jlcsmith
@kcwire
Build DDF, look at CSW and GMD source Metacard Mapping tooltip
https://codice.atlassian.net/browse/DDF-2339

DDF-2239 Fixed typo in CSW Metatype

---

platform/security/sts/security-sts-attributequerycommon/src/main/java/org/codice/ddf/security/claims/attributequery/common/AttributeQueryClaimsHandler.java
platform/security/sts/security-sts-ldapclaimshandler/src/main/java/ddf/security/sts/claimsHandler/LdapClaimsHandler.java
platform/security/sts/security-sts-ldapclaimshandler/src/main/java/ddf/security/sts/claimsHandler/RoleClaimsHandler.java
platform/security/sts/security-sts-propertyclaimshandler/src/main/java/org/codice/ddf/security/sts/claims/property/AttributeFileClaimsHandler.java

Makes the LDAP log not be as verbose
@AzGoalie @spearskw 
@kcwire 
@stustison
DDF-2323

DDF-2323 Quiet the LdapClaimsHandler

---

catalog/spatial/registry/registry-app/src/main/resources/features.xml

The DDF Registry-App successfullly uninstalls when stopping it from the DDF Admin UI.
@clockard @gordocanchola @vinamartin @brianfelix @ani6gup 
@kcwire
@shaundmorris
Install Registry-App in Admin UI, then stop it
On a fresh install, attempting to deactivate the DDF Registry-App resulted in the message "An application failed to stop".
The following would be present in the stacktrace:
09:48:33,717 | WARN  | tp1116445361-164 | tion.service.impl.ApplicationServiceBean  336 | dmin-core-appservice | Application registry-app was not successfully stopped.
org.codice.ddf.admin.application.service.ApplicationServiceException: java.lang.IllegalArgumentException: Feature named 'registry-core-api/2.10.0.SNAPSHOT' is not installed
In karaf the issue was traced down to the FeaturesServiceImpl …

DDF-2324 The DDF Registry-App now stops when the user deactivates it

---

catalog/spatial/registry/registry-app/src/main/resources/features.xml

The DDF Registry-App successfullly uninstalls when stopping it from the DDF Admin UI.
@clockard @gordocanchola @vinamartin @brianfelix @ani6gup 
@kcwire
@shaundmorris
Install Registry-App in Admin UI, then stop it
On a fresh install, attempting to deactivate the DDF Registry-App resulted in the message "An application failed to stop".
The following would be present in the stacktrace:
09:48:33,717 | WARN  | tp1116445361-164 | tion.service.impl.ApplicationServiceBean  336 | dmin-core-appservice | Application registry-app was not successfully stopped.
org.codice.ddf.admin.application.service.ApplicationServiceException: java.lang.IllegalArgumentException: Feature named 'registry-core-api/2.10.0.SNAPSHOT' is not installed
In karaf the issue was traced down to the FeaturesServiceImpl …

DDF-2324 2.9.x The DDF Registry-App now stops when the user deactivates it

---

distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFederation.java

Test the download retry situations
@Lambeaux 
@oconnormi 
@cmthom10
@figliold 
@lessarderic 
@coyotesqrl
Run TestFederation tests.
Added integrations tests for multiple users with retry scenarios.

DDF-2305 added integration tests for download with multiple users

---

catalog/spatial/csw/spatial-csw-source/src/main/resources/OSGI-INF/metatype/metatype.xml

This PR fixes some typos in the CSW source configuration.
@jlcsmith
@kcwire
Build and install DDF and observe fixed typos in the CSW Source configuration
This PR was already merged into master

DDF-2239 Fixed typos in CSW Source configuration

---

catalog/security/catalog-security-filter/src/main/java/ddf/catalog/security/filter/plugin/FilterPlugin.java

@coyotesqrl 
@pklinef
@stustison

DDF-2337 changed the filter plugin logs for create to use metacard.getTitle instead of metacard.getId

---

distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFederation.java

* Adds itest coverage for simultaneous downloads of the same product by multiple and single users
@Lambeaux 
@bantillo 
@cmthom10 
@figliold 
@coyotesqrl
@shaundmorris 
Run Hero Build
[DDF-2312](https://codice.atlassian.net/browse/DDF-2312)

DDF-2312: Add coverage for simultaneous downloads of same product

---

catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/data/impl/BasicTypes.java
catalog/core/catalog-core-api/src/main/java/ddf/catalog/data/types/Associations.java
catalog/core/catalog-core-api/src/main/java/ddf/catalog/data/types/Core.java
catalog/core/catalog-core-api/src/main/java/ddf/catalog/data/types/Validation.java
catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/RemoveAllCommand.java
catalog/core/catalog-core-commons/src/main/java/ddf/catalog/filter/delegate/ValidationQueryDelegate.java
catalog/core/catalog-core-commons/src/test/java/ddf/catalog/filter/delegate/ValidationQueryDelegateTest.java
catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/DynamicSchemaResolver.java
catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/TestSolrProvider.java
catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/ValidationQueryFactory.java
catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/cache/solr/impl/ValidationQueryFactoryTest.java
catalog/plugin/catalog-plugin-duplication/src/main/java/ddf/catalog/metacard/duplication/DuplicationValidator.java
catalog/plugin/catalog-plugin-metacard-validation/src/main/java/ddf/catalog/metacard/validation/MetacardValidityFilterPlugin.java
catalog/plugin/catalog-plugin-metacard-validation/src/main/java/ddf/catalog/metacard/validation/MetacardValidityMarkerPlugin.java
catalog/plugin/catalog-plugin-metacard-validation/src/test/java/ddf/catalog/metacard/validation/MetacardValidityFilterPluginTest.java
catalog/plugin/catalog-plugin-metacard-validation/src/test/java/ddf/catalog/metacard/validation/MetacardValidityMarkerPluginTest.java
catalog/transformer/catalog-transformer-streaming-impl/src/main/java/org/codice/ddf/transformer/xml/streaming/impl/GmlHandler.java
catalog/transformer/catalog-transformer-streaming-impl/src/main/java/org/codice/ddf/transformer/xml/streaming/impl/GmlHandlerFactory.java
catalog/transformer/catalog-transformer-streaming-impl/src/test/java/org/codice/ddf/transformer/xml/streaming/impl/TestXmlInputTransformer.java
catalog/transformer/catalog-transformer-streaming-lib/src/main/java/org/codice/ddf/transformer/xml/streaming/lib/SaxEventHandlerDelegate.java
catalog/transformer/catalog-transformer-streaming-lib/src/test/java/org/codice/ddf/transformer/xml/streaming/lib/TestGenericXmlLib.java
distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalog.java

Linked some new taxonomy constants to the old values for backwards compatibility.
@pklinef 
@jrnorth 
@bdeining 
@jlcsmith
@kcwire
Run tests.
DDF-2338

DDF-2338 linked some new taxonomy constants to the old values

---

distribution/docs/src/main/resources/_contents/configuring-from-configuration-files-contents.adoc

Updates documentation regarding formatting of string arrays in configuration files.
@peterhuffer 
@spearskw 
@ricklarsen 
@lessarderic 
@jaymcnallie
@kcwire
- [  ] Update / Add Unit Tests
- [  ] Update / Add Integration Tests

DDF-2179 Update configuration file formatting documentation

---

catalog/ui/search-ui/standard/pom.xml
distribution/docs/pom.xml
platform/security/sts/security-sts-ldapclaimshandler/pom.xml
pom.xml

Upgrades plugins to latest versions
@ricklarsen 
@ryeats 
@coyotesqrl
@shaundmorris 
Docs build

DDF-2355: Docs fail to build using Oracle JDK on Linux

---

catalog/spatial/registry/registry-source-configuration-handler/pom.xml
catalog/spatial/registry/registry-source-configuration-handler/src/main/java/org/codice/ddf/registry/source/configuration/SourceConfigurationHandler.java
catalog/spatial/registry/registry-source-configuration-handler/src/test/java/org/codice/ddf/registry/source/configuration/SourceConfigurationHandlerTest.java

What does this PR
This PR adds null check to config.getProperties
Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged; if a component team is listed, at least one of its members needs to approve)?
@shaundmorris 
Choose 2 committers to review/merge the PR (please choose ONLY two committers from below, delete the rest).
@shaundmorris
Start up DDF with registry. 
Open the DDF Catalog app. 
Open the Node Information tab
Open the identity node and open the Services tab.
Add a service with at least one binding. Save
Open the Sources tab.
Verify a source exists for you identity node, you may have to refresh the list.
Review & hero'd : …

DDF-2313: SourceConfigurationHandler (#1069)

---

distribution/ddf-common/src/main/resources/etc/org.ops4j.pax.web.cfg
distribution/ddf-common/src/main/resources/etc/system.properties
distribution/docs/src/main/resources/_contents/securing-contents.adoc

@beyelerb @coyotesqrl @ahoffer 
@shaundmorris
@stustison

DDF-2358 added new GCM ciphers to list, added some updated java 8 system properties, and updated the pax web config

---

index.html

Adds a bullet to "News and Events" section of codice.org/ddf advising users to upgrade to 8u60 or higher.
@vinamartin @Lambeaux @jrnorth 
@shaundmorris
@stustison
open `index.html` in browser.
[DDF-2365](https://codice.atlassian.net/browse/DDF-2365)
n/a

Update GH Page to reflect new Java version Recommendation

---

catalog/core/catalog-core-solrcommands/pom.xml
catalog/pom.xml
platform/persistence/platform-persistence-core-impl/pom.xml
platform/pom.xml
platform/security/sts/security-sts-attributequerycommon/pom.xml
platform/solr/pom.xml
platform/solr/solr-dependencies/pom.xml

@pklinef 
@coyotesqrl
@stustison

DDF-2364 updated commons-fileupload to the latest version

---

distribution/ddf-common/src/main/resources/etc/system.properties

cherry picks this change back to 2.9.x
@adimka @tbatie 
@coyotesqrl
@shaundmorris

DDF-2359 fix issues ingesting images on a headless server

---

catalog/catalog-app/pom.xml
catalog/catalog-app/src/main/resources/features.xml
catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/operation/impl/UpdateRequestImpl.java
catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/CatalogFrameworkImpl.java
catalog/plugin/catalog-plugin-content-uri/pom.xml
catalog/plugin/catalog-plugin-content-uri/src/main/java/org/codice/ddf/catalog/content/plugin/uri/ContentUriAccessPlugin.java
catalog/plugin/catalog-plugin-content-uri/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/plugin/catalog-plugin-content-uri/src/test/java/org/codice/ddf/catalog/content/plugin/uri/TestContentUriAccessPlugin.java
catalog/plugin/pom.xml
distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalog.java

This is a backport of #1046 
@coyotesqrl

DDF-2327 Add content uri overwrite protection (#1046)

---

catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/data/impl/types/CoreAttributes.java

Corrects the metacard tag attribute definition 
@rzwiefel @bdeining 
@coyotesqrl
@stustison

DDF-2275: Corrected metacard tags attribute definition

---

platform/security/sts/security-sts-server/src/main/java/ddf/security/sts/AuthNStatementProvider.java

@tbatie  @pklinef 
@coyotesqrl
@stustison

DDF-2370 changed AuthNStatementProvider to only create RNG once

---

catalog/spatial/csw/spatial-csw-transformer/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/TestCswUnmarshallHelper.java

This PR adds some additional unit tests to the CswUnmarshallHelper and cleans up the class.
@jrnorth @glenhein 
@jlcsmith
@kcwire 
Build DDF
https://codice.atlassian.net/browse/DDF-2340
…

DDF-2340 Added test cases to CswUnmarshallHelper for xs:gYearMonth and xs:gYear types

---

distribution/test/itests/test-itests-common/src/test/java/ddf/common/test/cometd/CometDClient.java
distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFederation.java

A new findActionUrlBySearchCriterion method in CometDClient.java gets the url of an action in a ClientD message if the message contains a desired string. This is used in a new TestFederation test called findMetacardActionUrlUsingCometDClient to find an action's url from a metacard id and the action's title.
@figliold
@Lambeaux 
@bantillo 
@coyotesqrl
@shaundmorris
run TestFederation

DDF-2357: Added search capability to CometDClient.java for use in TestFederation.java.

---

catalog/plugin/catalog-plugin-metacard-validation/src/main/java/ddf/catalog/metacard/validation/MetacardValidityMarkerPlugin.java
catalog/plugin/catalog-plugin-metacard-validation/src/test/java/ddf/catalog/metacard/validation/MetacardValidityMarkerPluginTest.java

Fixed an issue where federating a metacard it could get multiple validation tags.
@harrison-tarr @ahoffer 
@lessarderic 
@coyotesqrl

DDF-2374: Removed previous validation tags before adding new ones

---

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/CatalogFrameworkImpl.java
catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/impl/FanoutCatalogFrameworkTest.java

Cleans up and clarifies the `validateFixQueryResponse` method in `CatalogFrameworkImpl`.
Also adds a unit test to ensure that in fanout mode, the source id on Metacards in the Results has been updated to the local source.
@adimka @tbatie 
@coyotesqrl
@stustison
Full build/test run
This was discovered during the refactoring/cleanup of the master branch. While the current implementation is not broken, it is inefficient and very unclear.
DDF-2384
N/A

DDF-2384 Cleans up and clarifies the `validateFixQueryResponse` method

---

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/CreateOperations.java

A potential NPE was introduced in the last phase of the refactoring. This resolves that issue.
@rzwiefel @ryeats 
@coyotesqrl
@jlcsmith
Full build/test
N/A
DDF-2362
N/A

DDF-2362 Fixes potential NPE with versioning in CatalogFrameworkImpl create operation

---

catalog/transformer/catalog-transformer-pdf/pom.xml
catalog/transformer/catalog-transformer-pdf/src/main/java/ddf/catalog/transformer/input/pdf/GeoPdfParser.java
catalog/transformer/catalog-transformer-pdf/src/main/java/ddf/catalog/transformer/input/pdf/PdfInputTransformer.java
catalog/transformer/catalog-transformer-pdf/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/transformer/catalog-transformer-pdf/src/main/resources/OSGI-INF/metatype/metatype.xml
catalog/transformer/catalog-transformer-pdf/src/test/groovy/ddf/catalog/transformer/input/pdf/PdfInputTransformerSpecTest.groovy
catalog/transformer/catalog-transformer-pdf/src/test/java/ddf/catalog/transformer/input/pdf/GeoPdfParserTest.java
catalog/transformer/catalog-transformer-pdf/src/test/java/ddf/catalog/transformer/input/pdf/PdfInputTransformerTest.java

Update PdfInputTransformer for new taxonomy.
@bdeining 
@jrnorth 
@rzwiefel 
@jaymcnallie
@jlcsmith
Ingest a PDF and check SOLR for non-new-taxonomy fields.
DDF-2341

DDF-2341 update PdfInputTransformer for new taxonomy

---

catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/util/impl/SourcePoller.java
catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/util/impl/SourcePollerRunner.java
catalog/core/catalog-core-standardframework/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/core/catalog-core-standardframework/src/main/resources/OSGI-INF/metatype/metatype.xml

Changed Source Poller to have a configurable polling interval
@jrnorth @dcruver 
@jlcsmith
@kcwire

DDF-2363: Changed Source Poller to have a configurable polling interval

---

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/UpdateOperations.java

@djblue @jrnorth 
@coyotesqrl
@kcwire

DDF-2409: UpdateOperations method changed to use optional

---

distribution/docs/src/main/resources/_contents/_ui-contents/managing-ui-contents.adoc

This PR adds a WMTS configuration example
@ricklarsen 
@troymohl 
@jlcsmith
@kcwire

DDF-2375 Updated documentation to provide an example WMTS configuration

---

catalog/spatial/registry/registry-federation-admin-service-impl/src/main/java/org/codice/ddf/registry/federationadmin/service/impl/FederationAdminServiceImpl.java

DDF-2423: Code Cleanup in FederationAdminServiceImpl

---

catalog/spatial/registry/registry-api-impl/src/main/java/org/codice/ddf/registry/api/impl/RegistryStoreImpl.java
catalog/spatial/registry/registry-federation-admin-service-impl/src/main/java/org/codice/ddf/registry/federationadmin/service/impl/FederationAdminServiceImpl.java

@clockard @djblue @tbatie @pklinef 
@coyotesqrl 
@kcwire

DDF-2424: Updating registry entries fails when versioning is enabled

---

platform/admin/core/admin-core-appservice/src/main/java/org/codice/ddf/admin/application/service/impl/ApplicationConfigInstaller.java
platform/admin/core/admin-core-appservice/src/test/java/org/codice/ddf/admin/application/service/impl/ApplicationConfigInstallerTest.java

give the ApplicationConfigInstaller the permissions it needs to install apps
@tbatie @adimka 
@coyotesqrl
@shaundmorris
unzip drop this file in and remove the .txt then start the ddf and verify that solr-app, catalog-app, and spatial-app are installed
[org.codice.ddf.admin.applicationlist.properties.txt](https://github.com/codice/ddf/files/425996/org.codice.ddf.admin.applicationlist.properties.txt)

DDF-2407 use system user to install apps through the ApplicationConfigInstaller

---

catalog/core/catalog-core-federationstrategy/src/test/java/ddf/catalog/federation/impl/FederationStrategyTest.java
catalog/core/catalog-core-standardframework/pom.xml
catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/CreateOperations.java
catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/DeleteOperations.java
catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/MetacardFactory.java
catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/OperationsCatalogStoreSupport.java
catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/OperationsMetacardSupport.java
catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/OperationsSecuritySupport.java
catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/OperationsStorageSupport.java
catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/QueryOperations.java
catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/ResourceOperations.java
catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/SourceOperations.java
catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/TransformOperations.java
catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/UpdateOperations.java
catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/resourceretriever/RemoteResourceRetriever.java
catalog/core/catalog-core-standardframework/src/main/resources/OSGI-INF/blueprint/delegate-operators.xml
catalog/core/catalog-core-standardframework/src/test/groovy/ddf/catalog/impl/operations/MetacardFactoryTest.groovy
catalog/core/catalog-core-standardframework/src/test/groovy/ddf/catalog/impl/operations/OperationsCatalogStoreSupportTest.groovy
catalog/core/catalog-core-standardframework/src/test/groovy/ddf/catalog/impl/operations/OperationsMetacardSupportTest.groovy
catalog/core/catalog-core-standardframework/src/test/groovy/ddf/catalog/impl/operations/OperationsSecuritySupportTest.groovy
catalog/core/catalog-core-standardframework/src/test/groovy/ddf/catalog/impl/operations/OperationsStorageSupportTest.groovy
catalog/core/catalog-core-standardframework/src/test/groovy/ddf/catalog/impl/operations/QueryOperationsTest.groovy
catalog/core/catalog-core-standardframework/src/test/groovy/ddf/catalog/impl/operations/ResourceOperationsTest.groovy
catalog/core/catalog-core-standardframework/src/test/groovy/ddf/catalog/impl/operations/SourceOperationsTest.groovy
catalog/core/catalog-core-standardframework/src/test/groovy/ddf/catalog/impl/operations/TransformOperationsTest.groovy
catalog/core/catalog-core-standardframework/src/test/groovy/ddf/catalog/resourceretriever/RemoteResourceRetrieverTest.groovy
catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/impl/CatalogFrameworkImplTest.java
catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/impl/CatalogFrameworkQueryTest.java
catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/impl/FanoutCatalogFrameworkTest.java

Adds spock unit tests, extracts MetacardFactory support class from OperationsMetacardSupport, updates/simplifies QueryOperations, and does some general cleanup.
@ryeats @kcwire  @adimka 
@lessarderic
@stustison
Build/test
N/A
DDF-2362
N/A

DDF-2362 Adds unit tests for CFI delegate operations and support classes

---

catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/ValidateCommand.java
catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/validation/ValidatePrinter.java
catalog/core/catalog-core-commands/src/test/java/org/codice/ddf/commands/catalog/TestValidateCommand.java

Updates ValidateCommand to not print an extra number. Fixed --help message to provide accurate usage examples for CQL queries. Updated unit tests
@spearskw 
@coyotesqrl
@lessarderic 
Full build. Use validate command to verify --help message is accurate and presentation is clear. Attempt with valid and invalid data.

DDF-2411 Improve presentation of Validate Command

---

catalog/spatial/registry/registry-ebrim-transformer/src/main/java/org/codice/ddf/registry/converter/RegistryPackageConverter.java
catalog/spatial/registry/registry-ebrim-transformer/src/test/java/org/codice/ddf/registry/transformer/RegistryTransformerTest.java
catalog/spatial/registry/registry-rest-endpoint/src/test/java/org/codice/ddf/registry/rest/endpoint/report/RegistryReportBuilderTest.java

Updates missing country code and updates extension
Cherrypicks changes that were made on a backport branch https://github.com/codice/ddf/pull/1140
@coyotesqrl
@lessarderic

DDF-2334 Null values displayed in metacard organization attributes

---

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/CreateOperations.java
catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/DeleteOperations.java
catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/QueryOperations.java
catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/UpdateOperations.java

DDF-2390 updated log levels and log messages for catalog framework

---

catalog/ui/search-ui/standard/src/main/webapp/css/searchPage.css

Fix search ui scrolling issue.
@tbatie 
@adimka 
@ryeats 
@vinamartin 
@coyotesqrl
@pklinef
Build search ui and make sure the details view in the workspaces area can scroll.
[DDF-2441](https://codice.atlassian.net/browse/DDF-2441)

DDF-2441: fix search ui scrolling issue.

---

libs/spock-shaded/pom.xml
pom.xml

Upgraded groovy version and changed shaded spock to use the property.
@tbatie @rzwiefel 
@jlcsmith
@kcwire 
Build DDF

DDF-2426 Changed groovy version to 2.4.7 in the root pom and changed spock shaded jar to use the groovy version property

---

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/ResourceOperations.java

@clockard @emanns95 
@lessarderic 
@pklinef

DDF-2444: Fixes anytag queries from being federated in Resource Requests

---

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/CatalogFrameworkImpl.java
catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/impl/CatalogFrameworkImplTest.java

Fixes versioning. 
@jrnorth @djblue @kcwire 
@coyotesqrl
@pklinef
Ingest some non-resource metacard. Ensure in solr that all attributes were versioned. 
There was a bug originally where we were storing only the basic attributes of a metacard in the revisions. Once that was fixed it exposed another problem that was caused when updating by something other than metacard id. (Needed to be unique attribute when we go to search and update/delete it, but with history enabled there was now two of these 'unique' values on metacards)
DDF-2296

[2.9.x] DDF-2296: Fixed bug in Versioning

---

catalog/ui/search-ui/standard/src/main/webapp/js/view/Query.view.js

Backport to 2.9.x
See codice/ddf#1211

DDF-1789 Hide workspace back button in the "Add/Edit Search" view to prevent empty queries from generating in the workspace (2.9.x)

---

catalog/ui/search-ui/standard/src/main/webapp/js/view/Query.view.js
catalog/ui/search-ui/standard/src/main/webapp/templates/search/searchForm.handlebars

This is a backport of https://github.com/codice/ddf/pull/1212
@lessarderic
@pklinef
Follow the instructions in the ticket and verify it no longer misbehaves. Test both Types and Sources.
https://codice.atlassian.net/browse/DDF-2446

DDF-2446 Fix view/model sync in query multiselects

---

catalog/admin/module/catalog-admin-module-sources/src/main/webapp/templates/sourceList.handlebars
catalog/admin/module/catalog-admin-module-sources/src/main/webapp/templates/sourceRow.handlebars
catalog/spatial/registry/registry-source-configuration-handler/src/main/java/org/codice/ddf/registry/source/configuration/SourceConfigurationHandler.java
catalog/spatial/registry/registry-source-configuration-handler/src/test/java/org/codice/ddf/registry/source/configuration/SourceConfigurationHandlerTest.java

Back port for https://github.com/codice/ddf/pull/1166
@stustison
Verify bamboo passes
DDF-2420
(cherry picked from commit 75aaaf4)

DDF-2420 Backport - Removed local node from sources tab table and made disabled sources show no status.

---

platform/admin/core/admin-core-migration-commands/pom.xml
platform/admin/core/admin-core-migration-commands/src/main/java/org/codice/ddf/migration/commands/ExportCommand.java
platform/admin/core/admin-core-migration-commands/src/main/resources/OSGI-INF/blueprint/blueprint.xml
platform/util/platform-util/pom.xml
platform/util/platform-util/src/main/java/org/codice/ddf/platform/util/PathBuilder.java
platform/util/platform-util/src/test/java/org/codice/ddf/platform/util/PathBuilderTest.java

Fully fixes master on Windows (last verification hash 24a9c97). Any commit after that one will require tracking and fixing by the original author. 
@timothytierney
@tbatie 
@lessarderic 
@coyotesqrl
@shaundmorris
Windows and Mac build. Ensure nothing is broken.

DDF-2316: Windows up-to-date master fix

---

catalog/core/catalog-core-tagsfilterplugin/src/main/java/org/codice/ddf/catalog/plugin/tagsfilter/TagsFilterQueryPlugin.java

DDF-2423: added exception to logging statement

---

catalog/admin/module/catalog-admin-module-sources/src/main/webapp/js/view/ModalSource.view.js

Backport for https://github.com/codice/ddf/pull/1162
@coyotesqrl
Verify bamboo build passes
DDF-2415

DDF 2415 Backport - Fixed publish/unpublish status indicators in source modal

---

catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/model/Node.collection.js
catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/view/Registry.view.js

Back-ports DDF-2449; see https://github.com/codice/ddf/commit/2484c4af34b1fa62888053f7a3778f7238839e1b
N/A
@figliold 
@shaundmorris
See https://github.com/codice/ddf/pull/1223

DDF-2449: Registry nodes are now sorted alphabetically (backport).

---

catalog/ui/search-ui/standard/src/main/webapp/js/view/Query.view.js

Fix context of `this` in source/type refreshes
@shaundmorris
Verify no errors in the console when loading the search UI and switching between the source/type tabs.
https://codice.atlassian.net/browse/DDF-2465

DDF-2465 Bind context of this in refeshes

---

catalog/ui/search-ui/standard/src/main/webapp/js/view/Query.view.js

Fix context of `this` in source/type refreshes
@shaundmorris
Verify no errors in the console when loading the search UI and switching between the source/type tabs.
https://codice.atlassian.net/browse/DDF-2465

Ddf 2465 Bind context of this in refeshes

---

README.md

Updates the README.me
@andrewkfiedler @Lambeaux 
@coyotesqrl
@lessarderic

DDF-1406: Updated README with node and windows parallel build

---

catalog/core/catalog-core-standardframework/src/test/groovy/ddf/catalog/impl/operations/SourceOperationsTest.groovy

DDF-2423: Ignore source available test

---

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/CatalogFrameworkImpl.java

backport
@coyotesqrl
@jlcsmith
https://github.com/codice/ddf/pull/1141

[2.9.x] DDF-2368  - Fixed resource usage not counting user's first download

---

distribution/docs/src/main/resources/_contents/_core-concepts/content-intro-contents.adoc
distribution/docs/src/main/resources/_contents/_core-concepts/events-subscriptions-intro-contents.adoc
distribution/docs/src/main/resources/_contents/_core-concepts/federation-intro-contents.adoc
distribution/docs/src/main/resources/_contents/_core-concepts/ingest-intro-contents.adoc
distribution/docs/src/main/resources/_contents/_core-concepts/metadata-intro-contents.adoc
distribution/docs/src/main/resources/_contents/_core-concepts/registry-intro-contents.adoc
distribution/docs/src/main/resources/_contents/_core-concepts/requests-intro-contents.adoc
distribution/docs/src/main/resources/_contents/_core-concepts/search-intro-contents.adoc
distribution/docs/src/main/resources/_contents/_introduction/applications-contents.adoc
distribution/docs/src/main/resources/_contents/_introduction/documentation-notes-contents.adoc
distribution/docs/src/main/resources/_contents/_introduction/introduction-contents.adoc
distribution/docs/src/main/resources/_contents/config.adoc
distribution/docs/src/main/resources/_contents/introduction-contents.adoc
distribution/docs/src/main/resources/draft-documentation.adoc

This PR is the first in a series of documentation rewrites. It includes the _Introduction_ and _Core Concepts_ sections of the documentation. 
@Lambeaux @jrnorth @mcalcote 
@pklinef
@shaundmorris
- Successful Build
- free of typos & errors
- information up to date and complete
The changes here will not yet be visible in the published documentation. To view new version, open `draft-documentation` in either html or pdf in the docs target directory. [pdf version attached to this PR] Once all changes are integrated, the `draft-documentation` will supersede the current version.
https://codice.atlassian.net/browse/DDF-2393
[draft-documentation.pdf](https://github.com/codice/ddf/files/423736/draft-documentation.pdf)

DDF-2393: Added Intro & Core Concepts sections to DRAFT docs

---

catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/CswRecordMetacardType.java
catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/GmdConstants.java
catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/converter/DefaultCswRecordMap.java
catalog/spatial/csw/spatial-csw-endpoint/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/TestCswEndpoint.java
catalog/spatial/csw/spatial-csw-endpoint/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/reader/TestTransactionMessageBodyReader.java
catalog/spatial/csw/spatial-csw-source/src/main/resources/OSGI-INF/metatype/metatype.xml
catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/GmdConverter.java
catalog/spatial/csw/spatial-csw-transformer/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/spatial/csw/spatial-csw-transformer/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/TestGmdConverter.java
catalog/spatial/csw/spatial-csw-transformer/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/transformer/TestGmdTransformer.java
catalog/spatial/csw/spatial-csw-transformer/src/test/resources/gmd/metacard-as-GMD-sparse.xml
catalog/spatial/csw/spatial-csw-transformer/src/test/resources/gmd/metacard-as-GMD.xml

This PR updates GMD Metacard Mappings, and adds additional query-able apiso properties to the CSW Endpoint.
@jlcsmith
@kcwire 
Build and Install DDF, ingest GMD XML and verify endpoint queries and updates via postman
https://codice.atlassian.net/browse/DDF-2388

DDF-2388 Aligned GMD Metacard Mappings and Metacard Transformer with new taxonomy and added additional mappings

---

catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/view/Field.view.js
catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/view/NodeModal.view.js
catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/view/Segment.view.js
catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/less/styles.less
catalog/spatial/registry/registry-federation-admin-service-impl/src/main/java/org/codice/ddf/registry/federationadmin/service/impl/IdentityNodeInitialization.java
catalog/spatial/registry/registry-federation-admin-service-impl/src/test/java/org/codice/ddf/registry/federationadmin/service/impl/IdentityNodeInitializationTest.java

https://github.com/codice/ddf/pull/1261
@figliold @pklinef

DDF-2461 Syncs registry name with site name

---

catalog/spatial/registry/registry-api-impl/src/main/java/org/codice/ddf/registry/api/impl/RegistryStoreImpl.java
catalog/spatial/registry/registry-federation-admin-service-impl/src/main/java/org/codice/ddf/registry/federationadmin/service/impl/FederationAdminServiceImpl.java

@mcalcote @clockard 
@coyotesqrl 
@kcwire
https://github.com/codice/ddf/pull/1169

[2.9.x] DDF-2424: Updating registry entries fails when versioning is enabled

---

platform/platform-app/src/main/resources/features.xml
pom.xml

Adds the ability to install/uninstall the camel-jackson feature - which provides the functionality to marshal and unmarshal Java objects to and from JSON via camel routes.
@dcruver 
@ryeats 
@harrison-tarr
@jaymcnallie 
@pklinef 
Install the camel-jackson feature and verify that no exceptions occur.
DDF-2496

DDF-2496 Add camel-jackson feature to support marshalling and unmarshalling Java objects to and from JSON via camel routes

---

catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/view/Registry.view.js
catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/less/styles.less
catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/templates/regenerateSourcesModal.handlebars
catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/templates/registryPage.handlebars
catalog/spatial/registry/registry-federation-admin-api/src/main/java/org/codice/ddf/registry/federationadmin/internal/FederationAdminMBean.java
catalog/spatial/registry/registry-federation-admin-impl/pom.xml
catalog/spatial/registry/registry-federation-admin-impl/src/main/java/org/codice/ddf/registry/federationadmin/impl/FederationAdmin.java
catalog/spatial/registry/registry-federation-admin-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/spatial/registry/registry-federation-admin-impl/src/test/java/org/codice/ddf/registry/federationadmin/impl/FederationAdminTest.java
catalog/spatial/registry/registry-federation-admin-service/src/main/java/org/codice/ddf/registry/federationadmin/service/internal/RegistrySourceConfiguration.java
catalog/spatial/registry/registry-source-configuration-handler/src/main/java/org/codice/ddf/registry/source/configuration/SourceConfigurationHandler.java
catalog/spatial/registry/registry-source-configuration-handler/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/spatial/registry/registry-source-configuration-handler/src/test/java/org/codice/ddf/registry/source/configuration/SourceConfigurationHandlerTest.java

Backport for https://github.com/codice/ddf/pull/1265
@pklinef 
Verify bamboo build passes
DDF-2454
(cherry picked from commit ac561fe)

DDF-2454 Backport - Added ability to regenerate sources from registry nodes

---

distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFtp.java

-Adds `WaitCondition`s when verifying ingest in TestFtp test methods to allow enough time for file to ingest.
-Increases wait time of configuration update of the `catalog-ftp` feature in TestFtp from 10 to 60 seconds before failing. This will allow more reasonable time in parallel builds for the FtpServer to restart with correct configuration.
@emmberk @bdeining 
@jlcsmith
@lessarderic
Run itests
https://codice.atlassian.net/browse/DDF-2470

DDF-2470: Fix intermittent TestFtp itest failures

---

catalog/spatial/registry/registry-api-impl/src/main/java/org/codice/ddf/registry/api/impl/RegistryStoreImpl.java
catalog/spatial/registry/registry-common/src/main/java/org/codice/ddf/registry/common/RegistryConstants.java
catalog/spatial/registry/registry-publication-action-provider/src/main/java/org/codice/ddf/registry/publication/action/provider/RegistryPublicationActionProvider.java
catalog/spatial/registry/registry-publication-action-provider/src/test/java/org/codice/ddf/registry/publication/action/provider/RegistryPublicationActionProviderTest.java
catalog/spatial/registry/registry-report-action-provider/src/main/java/org/codice/ddf/registry/report/action/provider/RegistryReportActionProvider.java
catalog/spatial/registry/registry-report-action-provider/src/test/java/org/codice/ddf/registry/report/action/provider/TestRegistryReportActionProvider.java
catalog/spatial/registry/registry-source-configuration-handler/src/main/java/org/codice/ddf/registry/source/configuration/SourceConfigurationHandler.java
catalog/spatial/registry/registry-source-configuration-handler/src/test/java/org/codice/ddf/registry/source/configuration/SourceConfigurationHandlerTest.java

Backport for https://github.com/codice/ddf/pull/1290 
@shaundmorris
Verify bamboo passes
DDF-2382
(cherry picked from commit 6cc6c03)

DDF-2382 Backport - Fix registry-id key used in configurations.

---

catalog/core/catalog-core-api-impl/pom.xml
catalog/core/catalog-core-api/pom.xml
catalog/core/catalog-core-camelcomponent/pom.xml
catalog/core/catalog-core-directorymonitor/pom.xml
catalog/core/catalog-core-impl/pubsub/pom.xml
catalog/core/catalog-core-metricsplugin/pom.xml
catalog/core/catalog-core-sourcemetricsplugin/pom.xml
catalog/core/catalog-core-urlresourcereader/pom.xml
catalog/opensearch/catalog-opensearch-endpoint/pom.xml
catalog/opensearch/catalog-opensearch-source/pom.xml
catalog/pom.xml
catalog/spatial/ogc/spatial-ogc-urlresourcereader/pom.xml
distribution/sdk/sample-transformers/xslt-identity-input-transformer/pom.xml
distribution/test/itests/test-itests-common/pom.xml
platform/admin/core/admin-core-appservice/pom.xml
platform/admin/core/admin-core-insecuredefaults/pom.xml
platform/mime/core/platform-mime-core-impl/pom.xml
platform/platform-filter-delegate/pom.xml
platform/security/cas/security-cas-client/pom.xml
platform/security/pom.xml
pom.xml

Updates the logback classic version to 1.1.7
@tbatie @vinamartin 
@lessarderic
@shaundmorris
Full build with tests pass.

DDF-2505: Updated logback classic version

---

catalog/ftp/pom.xml
catalog/ftp/src/main/java/ddf/catalog/ftp/ftplets/FtpRequestHandler.java
catalog/ftp/src/test/java/ddf/catalog/ftp/ftplets/FtpRequestHandlerTest.java
distribution/docs/src/main/resources/_contents/_catalog-contents/integrating-catalog-contents.adoc
distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFtp.java

STOU - Full support is added. The FTP server will return a success message that
includes the metacard id, which the client can interpret as the unique name given
to the object.
SITE - Since the FTP server does not have any site-specific commands, the server
now returns the status code 202, which indicates that SITE is not implemented.
DELE, RETR, RMD, MKD, APPE, RNTO - The FTP server returns a response indicating
success, even though no action was taken. Some clients, for example, always
attempt to make a new directory and then CD to it. This isn't necessary from
the DDF point of view. Previously, the server would return an error that would
cause the client to fail.
Add support for clients that PUT a dot-file and then rename the dot-file to
the final filename. The rename command will …

DDF-2468 Add support for more FTP commands

---

catalog/admin/module/catalog-admin-module-sources/src/main/webapp/WEB-INF/web.xml
catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/WEB-INF/web.xml
catalog/spatial/registry/registry-admin-modules/registry-admin-remote-ui/src/main/webapp/WEB-INF/web.xml
catalog/spatial/wfs/1.0.0/spatial-wfs-v1_0_0-schema-webapp/src/main/resources/WEB-INF/web.xml
catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-schema-bindings/src/main/resources/WEB-INF/web.xml
catalog/ui/search-ui/simple/src/main/webapp/WEB-INF/web.xml
catalog/ui/search-ui/simple/src/main/webapp/resources/WEB-INF/web.xml
platform/admin/modules/admin-metrics-ui/src/main/webapp/WEB-INF/web.xml
platform/platform-filter-delegate/src/main/java/org/codice/ddf/platform/filter/delegate/FilterInjector.java
platform/platform-filter-delegate/src/test/java/org/codice/ddf/platform/filter/delegate/FilterInjectorTest.java
platform/security/filter/security-filter-login/pom.xml
platform/security/filter/security-filter-login/src/main/java/org/codice/ddf/security/filter/login/LoginFilter.java
platform/security/policy/security-policy-context/src/main/resources/OSGI-INF/blueprint/blueprint.xml
platform/security/policy/security-policy-context/src/main/resources/OSGI-INF/metatype/metatype.xml
platform/solr/platform-solr-server-standalone/src/main/webapp/WEB-INF/web.xml

@garrettfreibott @coyotesqrl 
@pklinef
@stustison

DDF-2504 fix issue with getting multiple sessions assigned to a single browser session

---

distribution/kernel/pom.xml
pom.xml

@kcwire 
@millerw8
@pklinef
@stustison

DDF-2511 removed blueprint hack and updated karaf to 4.0.7

---

README.md

Adds a Contributor License Agreement (CLA) badge to the README
@andygoodson 
@kcwire
@lessarderic
This PR does not involve any build/runtime code. To test it should ask on PRs to submit a CLA if one has not been submitted. 
This is a process improvement as opposed to sending emails for CLAs
DDF-2509

DDF-2509: Added Contributor License Agreement (CLA) badge to README

---

catalog/pom.xml
catalog/spatial/geocoding/spatial-geocoding-api-impl/pom.xml
catalog/spatial/geocoding/spatial-geocoding-api-impl/src/main/java/org/codice/ddf/spatial/geocoding/context/impl/NearbyLocationImpl.java
catalog/spatial/geocoding/spatial-geocoding-api-impl/src/test/java/org/codice/ddf/spatial/geocoding/context/impl/NearbyLocationImplTest.java
catalog/spatial/geocoding/spatial-geocoding-lucene/pom.xml
catalog/spatial/geocoding/spatial-geocoding-lucene/src/main/java/org/codice/ddf/spatial/geocoding/index/GeoNamesLuceneIndexer.java
catalog/spatial/geocoding/spatial-geocoding-lucene/src/main/java/org/codice/ddf/spatial/geocoding/query/GeoNamesQueryLuceneDirectoryIndex.java
catalog/spatial/geocoding/spatial-geocoding-lucene/src/main/java/org/codice/ddf/spatial/geocoding/query/GeoNamesQueryLuceneIndex.java
catalog/spatial/geocoding/spatial-geocoding-lucene/src/test/java/org/codice/ddf/spatial/geocoding/query/TestGeoNamesQueryLuceneIndex.java
catalog/spatial/geocoding/spatial-geocoding-websearch/pom.xml
catalog/spatial/geocoding/spatial-geocoding-websearch/src/main/java/org/codice/ddf/spatial/geocoder/geonames/GeoNamesWebService.java
catalog/spatial/geocoding/spatial-geocoding-websearch/src/test/java/org/codice/ddf/spatial/geocoder/geonames/TestGeoNamesWebService.java
catalog/spatial/pom.xml
catalog/spatial/registry/pom.xml
pom.xml

Update usages of lucene-core to 6.0.0.
@kcwire 
@pklinef 
@peterhuffer 
@troymohl 
@beyelerb
@kcwire
Run itests.
There was a desire to reduce the number of lucene versions being used.
DDF-2495

DDF-2495 Update usages of lucene-core to 6.0.0.

---

catalog/spatial/csw/spatial-csw-source/src/main/resources/OSGI-INF/metatype/metatype.xml
catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/main/resources/OSGI-INF/metatype/metatype.xml

This PR updates the wording for the Coordinate Order drop-downs.
@dcruver @glenhein @bdeining @peterhuffer 
@kcwire
@millerw8
Confirm descriptions for Coordinate Order drop-downs display correctly for
- GMD CSW ISO Federated Source
- CSW Specification Profile Federated Source
- WFS 2.0.0 Federated Source

DDF-2514 Updated description for Coordinate Order drop-downs when configuring a source

---

distribution/docs/src/main/resources/_contents/_ui-contents/managing-ui-contents.adoc

This PR updates examples for imagery providers in the Standard Search UI
@ricklarsen
@jlcsmith
@kcwire
https://codice.atlassian.net/browse/DDF-2425
https://codice.atlassian.net/browse/DDF-2425

DDF-2425 Updated Imagery Provider Examples

---

catalog/spatial/geowebcache/geowebcache-admin-plugin/src/main/webapp/js/model/GwcLayers.js

This PR removes an extra tab character and cleans up GWC XML generation
@lcrosenbu @rzwiefel 
@jlcsmith
@kcwire
Build and Install DDF experimental, configure GWC with a tile server and specify WMS Layers

(2.9.x) DDF-2497 Removed extra whitespace in GWC Admin Plugin

---

catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/model/Node.collection.js
catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/view/Registry.view.js
catalog/spatial/registry/registry-source-configuration-handler/src/main/java/org/codice/ddf/registry/source/configuration/SourceConfigurationHandler.java

Backport for https://github.com/codice/ddf/pull/1293
@kcwire 
Verify bamboo run passes
DDF-2454
(cherry picked from commit a4200b3)

DDF-2454 Backport - Sort order of source regeneration entries in dialog and disllow identity node.

---

distribution/docs/src/main/resources/_contents/_resource-management-contents/managing-resource-management-contents.adoc
distribution/docs/src/main/resources/_contents/config.adoc
distribution/docs/src/main/resources/documentation.adoc
distribution/docs/src/main/resources/draft-documentation.adoc
pom.xml

Adds documentation for the Resource Management application to the documentation. 
@bdeining @jlcsmith @Lambeaux @jrnorth @mcalcote 
@jlcsmith
@pklinef
review outline, builds successfully
Added to `draft-documentation` to be included in documentation rewrite. For info on rewrite, see https://github.com/codice/ddf/pull/1036.
https://codice.atlassian.net/browse/DDF-2428

DDF-2428 Add docs for Resource Management apps

---

catalog/transformer/catalog-transformer-streaming-api/pom.xml
catalog/transformer/catalog-transformer-streaming-api/src/main/java/org/codice/ddf/transformer/xml/streaming/AbstractSaxEventHandler.java
catalog/transformer/catalog-transformer-streaming-impl/pom.xml
catalog/transformer/catalog-transformer-streaming-impl/src/main/java/org/codice/ddf/transformer/xml/streaming/impl/GmlHandler.java
catalog/transformer/catalog-transformer-streaming-impl/src/main/java/org/codice/ddf/transformer/xml/streaming/impl/XmlSaxEventHandlerImpl.java

Cleans up redundant code with the SaxEventHandler class and its implementations.
@harrison-tarr @spearskw 
@coyotesqrl
@lessarderic
A full build should pass

DDF-2521: Refactored implementations of SaxEventHandler

---

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/CreateOperations.java
catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/OverrideAttributesSupport.java
catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/UpdateOperations.java
catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/impl/operations/OverrideAttributesSupportTest.java
catalog/rest/catalog-rest-endpoint/pom.xml
catalog/rest/catalog-rest-endpoint/src/main/java/org/codice/ddf/endpoints/rest/RESTEndpoint.java
catalog/rest/catalog-rest-endpoint/src/main/java/org/codice/ddf/endpoints/rest/RESTService.java
catalog/rest/catalog-rest-endpoint/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/rest/catalog-rest-endpoint/src/test/java/org/codice/ddf/endpoints/rest/TestRestEndpoint.java
distribution/docs/src/main/resources/_contents/_catalog-contents/integrating-catalog-contents.adoc

@garrettfreibott @coyotesqrl @rzwiefel 
@pklinef
@stustison
Full build + manual test of resource and parsed metadata
- added option to parse metadata
- fixed bug with derived resources possibly overriding the resource uri of non-derived resources

DDF-2508 added ability to specify individual override attributes in REST request

---

catalog/core/catalog-core-solr/pom.xml
catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/DynamicSchemaResolver.java
catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/SolrFilterDelegate.java
catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/SolrMetacardClient.java
catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/MockMetacard.java
catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/TestSolrFilterDelegate.java
catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/TestSolrProvider.java
platform/solr/platform-solr-server-standalone/src/main/resources/solr/conf/schema.xml

Backport of https://github.com/codice/ddf/pull/1307
@coyotesqrl
@pklinef

(2.9.x) DDF-2506 Use LatLonType for geometry sort keys

---

CHANGES.md
PULL_REQUEST_TEMPLATE

Backport change log (CHANGES.md) 
@pklinef
https://codice.atlassian.net/browse/DDF-2510
n/a

DDF-2510: added a change log at CHANGES.md (#1319)

---

platform/security/sts/security-sts-crlinterceptor/pom.xml

This PR fixes a hard coded version number
@peterhuffer  @lcrosenbu 
@coyotesqrl 
Build DDF

DDF-2530 Changed hard coded version number

---

platform/security/sts/security-sts-crlinterceptor/pom.xml

This PR fixes a hard coded version number
@peterhuffer  @lcrosenbu 
@coyotesqrl 
Build DDF

(2.9.x) DDF-2530 Fixed hardcoded version number

---

distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/cometd/CometDClient.java
distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFederation.java

@Lambeaux 
@lessarderic 
@figliold 
@oconnormi 
@coyotesqrl
@shaundmorris

DDF-2448 Cleanup resource download integration tests

---

distribution/sdk/sample-cometd/java-cli-example/pom.xml

This PR fixes a hard coded version number
@peterhuffer  @lcrosenbu 
@coyotesqrl 
Build DDF

DDF-1700 Fixed hard coded dependency

---

distribution/sdk/sample-cometd/java-cli-example/pom.xml

This PR fixes a hard coded version number
@peterhuffer  @lcrosenbu 
@coyotesqrl 
Build DDF

(2.9.x) DDF-1700 Fixed hardcoded dependency

---

catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/mappings/CswRecordMapperFilterVisitor.java
catalog/spatial/csw/spatial-csw-endpoint/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswQueryFactoryTest.java
catalog/spatial/csw/spatial-csw-endpoint/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/mappings/TestCswRecordMapperFilterVisitor.java

Fixes the temporal check in the CswRecordMapperFilterVisitor
@tbatie @bdeining @AzGoalie 
@coyotesqrl
@pklinef
Verify unit and itests pass
DDF-2413

DDF-2413 Fixed temporal check in CswRecordMapperFilterVisitor.

---

CHANGES.md
PULL_REQUEST_TEMPLATE

Adds version 2.10.0 to change log. 
@pklinef
[DDF-2510](https://codice.atlassian.net/browse/DDF-2510)

DDF-2510-1 updated change log for v. 2.10.0

---

distribution/docs/src/main/resources/_contents/_catalog-frameworks/attribute-injection-definition-contents.adoc
distribution/docs/src/main/resources/_contents/_catalog-frameworks/attribute-type-definition-contents.adoc
distribution/docs/src/main/resources/_contents/_catalog-frameworks/catalog-api-contents.adoc
distribution/docs/src/main/resources/_contents/_catalog-frameworks/catalog-architecture-contents.adoc
distribution/docs/src/main/resources/_contents/_catalog-frameworks/catalog-framework-camel-component-contents.adoc
distribution/docs/src/main/resources/_contents/_catalog-frameworks/catalog-framework-intro-contents.adoc
distribution/docs/src/main/resources/_contents/_catalog-frameworks/catalog-frameworks-contents.adoc
distribution/docs/src/main/resources/_contents/_catalog-frameworks/default-attribute-values-contents.adoc
distribution/docs/src/main/resources/_contents/_catalog-frameworks/developing-catalog-frameworks-contents.adoc
distribution/docs/src/main/resources/_contents/_catalog-frameworks/global-attribute-validators-definition-contents.adoc
distribution/docs/src/main/resources/_contents/_catalog-frameworks/metacard-type-definition-contents.adoc
distribution/docs/src/main/resources/_contents/_catalog-frameworks/standard-catalog-framework-contents.adoc
distribution/docs/src/main/resources/_contents/_core-concepts/metadata-intro-contents.adoc
distribution/docs/src/main/resources/_contents/_core-concepts/search-intro-contents.adoc
distribution/docs/src/main/resources/_contents/_platform-contents/extending-platform-contents.adoc
distribution/docs/src/main/resources/_contents/_tables/ddf.catalog.CatalogFrameworkImpl-table-contents.adoc
distribution/docs/src/main/resources/_contents/config.adoc
distribution/docs/src/main/resources/draft-documentation.adoc

Adds Catalog Framework docs to the Integrating section of the docs
@garrettfreibott @oconnormi @mcalcote @Lambeaux @andrewkfiedler 
@coyotesqrl 
@shaundmorris
Docs render, builds successful, review outline
This is a subtask of https://github.com/codice/ddf/pull/1036. 
https://codice.atlassian.net/browse/DDF-2397
[draft-documentation.pdf](https://github.com/codice/ddf/files/448476/draft-documentation.pdf)

DDF 2397 Updates Catalog Frameworks docs

---

distribution/docs/src/main/resources/_contents/_ui-contents/managing-ui-contents.adoc

This PR updates examples for imagery providers in the Standard Search UI
@ricklarsen
@jlcsmith
@kcwire
https://codice.atlassian.net/browse/DDF-2425
https://codice.atlassian.net/browse/DDF-2425

(2.9.x) DDF-2425 Updated Imagery Provider Examples

---

catalog/spatial/wfs/1.0.0/spatial-wfs-v1_0_0-converter/src/test/java/org/codice/ddf/spatial/ogc/wfs/v1_0_0/catalog/converter/impl/SampleMetacard.java
catalog/spatial/wfs/1.0.0/spatial-wfs-v1_0_0-converter/src/test/java/org/codice/ddf/spatial/ogc/wfs/v1_0_0/catalog/converter/impl/TestGenericFeatureConverter.java
catalog/spatial/wfs/spatial-wfs-converter/src/main/java/org/codice/ddf/spatial/ogc/wfs/catalog/converter/impl/AbstractFeatureConverter.java
catalog/spatial/wfs/spatial-wfs-converter/src/main/java/org/codice/ddf/spatial/ogc/wfs/catalog/converter/impl/GenericFeatureConverter.java
catalog/spatial/wfs/spatial-wfs-mapper/src/main/java/org/codice/ddf/spatial/ogc/wfs/catalog/mapper/impl/MetacardMapperImpl.java

MetacardMapperImpl and Wfs classes updated to DDF taxonomy.
@bdeining 
@coyotesqrl
@lessarderic 
Run junit and itests.
https://codice.atlassian.net/browse/DDF-2501

DDF-2529: Updated MetacardMapperImpl and Wfs classes to new taxonomy.

---

catalog/spatial/geocoding/spatial-geocoding-plugin/src/main/java/org/codice/ddf/spatial/geocoding/plugin/GeoCoderPlugin.java
catalog/spatial/geocoding/spatial-geocoding-plugin/src/test/groovy/org/codice/ddf/spatial/geocoding/plugin/GeoCoderPluginTest.groovy

This PR updates the GeoCoderPlugin to handle UpdateRequests.
@peterhuffer @glenhein @mweser @brjeter
@beyelerb
@kcwire
Confirm unit tests pass.
Relates to https://github.com/codice/ddf/pull/1171.
The spatial-geocoding-plugin in the DDF Spatial app needs to be installed for the plugin to work.
[DDF-2531](https://codice.atlassian.net/browse/DDF-2531)

DDF-2531 Updated GeoCoderPlugin to handle UpdateRequests

---

catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/index.html
catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/view/Field.view.js
catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/less/styles.less
catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/templates/field.handlebars

Backport for https://github.com/codice/ddf/pull/1340
@figliold
Verify bamboo build
DDF-2534
(cherry picked from commit de0acc3)

DDF-2534 Backport - Add autocomplete/suggestion support to the registry node modal fields

---

catalog/ui/search-ui/standard/src/main/webapp/js/view/Menu.view.js
platform/security/handler/security-handler-guest/src/main/webapp/js/view/Login.view.js

Fixes an issue with logging out on of the search ui and admin console on Windows.
@emanns95 @spearskw @brendan-hofmann @tbatie 
@kcwire
@stustison
*TEST ON WINDOWS*
Log out of admin ui, make sure you are signed out of search ui too.
Log into search ui as admin, verify that it worked.
Log out of search ui and verify that you are now guest.

DDF-2539: Fixed log out issue on windows

---

catalog/ui/search-ui/standard/src/main/webapp/js/view/Menu.view.js
platform/security/handler/security-handler-guest/src/main/webapp/js/view/Login.view.js

Fixes an issue with logging out on of the search ui and admin console on Windows.
@brendan-hofmann @spearskw @emanns95 
@shaundmorris
@stustison

DDF-2539: 2.9.x Fixed log out issue on windows

---

platform/security/sts/security-sts-guestvalidator/src/test/java/org/codice/ddf/security/validator/guest/GuestValidatorTest.java

DDF-2537 Remove canValidateBadIp test

---

catalog/core/catalog-core-camelcomponent/pom.xml
distribution/test/itests/pom.xml
distribution/test/itests/test-itests-common/pom.xml
distribution/test/itests/test-itests-ddf/pom.xml
pom.xml

Avoids adding every transitive dependency of DDF to every module that depends on test-itests-common.
@tbatie 
@ahoffer 
@lessarderic
@coyotesqrl 
@pklinef
Building it should be sufficient.
Although this wasn't breaking anything in DDF (yet), upstream projects were more severely impacted. It also noticeably increased the delay to start a build due to the increased project model complexity.
[DDF-2492](https://codice.atlassian.net/browse/DDF-2492)

DDF-2492 Replace distro transitives with explicits

---

catalog/spatial/csw/spatial-csw-source-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/AbstractCswSource.java
platform/security/rest/security-rest-cxfwrapper/src/main/java/org/codice/ddf/cxf/SecureCxfClientFactory.java

@clockard 
@roelens8 
@kcwire
@stustison
This issue does not occur in loopback or locally. To test, stand up DDFs on two machines, making sure to update the cert hostname for both. Ingest a png as the system user on one machine, so that it gets marked with permissions. Retrieve said product as the system user from the other machine.
[DDF-2543](https://codice.atlassian.net/browse/DDF-2543)

DDF-2543 Add user subject to CSW product retrieval

---

catalog/spatial/csw/spatial-csw-source-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/AbstractCswSource.java
platform/security/rest/security-rest-cxfwrapper/src/main/java/org/codice/ddf/cxf/SecureCxfClientFactory.java

Backport 2543
@clockard 
@roelens8 
@kcwire
@stustison
This issue does not occur in loopback or locally. To test, stand up DDFs on two machines, making sure to update the cert hostname for both. Ingest a png as the system user on one machine, so that it gets marked with permissions. Retrieve said product as the system user from the other machine.
[DDF-2543](https://codice.atlassian.net/browse/DDF-2543)

DDF-2543 Add user subject to CSW product retrieval (#1356)

---

catalog/admin/module/catalog-admin-module-sources/src/main/webapp/js/view/ConfigurationEdit.view.js
catalog/admin/module/catalog-admin-module-sources/src/main/webapp/js/view/ModalSource.view.js
catalog/admin/module/catalog-admin-module-sources/src/main/webapp/templates/configuration/checkboxType.handlebars
catalog/admin/module/catalog-admin-module-sources/src/main/webapp/templates/configuration/configurationItem.handlebars

Fixes source tab saving and displaying for dropdown and checkbox menu items.
@vinamartin @djblue @clockard @andrewkfiedler 
[UI](https://github.com/orgs/codice/teams/ui) <--
@coyotesqrl
@stustison
1. Add a source via the sources tab, selecting an option from a dropdown and checkbox menu.
2. Confirm …

DDF-2542 Changing a dropdown or checkbox value on the sources tab will not save the change

---

distribution/sdk/sample-twitter-source/src/main/java/org/codice/ddf/catalog/twitter/source/TwitterSource.java

Fixes the sdk twitter source.
@spearskw @emanns95 
@shaundmorris
@stustison

DDF-2548: Added source id to twitter source results

---

distribution/test/itests/README.md

Document the itest log level flag.
@rzwiefel 
@coyotesqrl
@lessarderic

Add itest logging documentation

---

distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/ServiceManagerProxy.java

Remove a catch that was causing itests to hang indefinitely instead of failing.
@adimka @tbatie 
@coyotesqrl
@shaundmorris 
[DDF-2550](https://codice.atlassian.net/browse/DDF-2550)

DDF-2550 Don't swallow system execution exceptions

---

libs/mpeg-transport-stream/pom.xml
libs/mpeg-transport-stream/src/main/java/org/codice/ddf/libs/mpeg/transport/MTSValidPacketIterator.java
libs/mpeg-transport-stream/src/main/java/org/codice/ddf/libs/mpeg/transport/MpegTransportStreamMetadataExtractor.java
libs/mpeg-transport-stream/src/test/java/org/codice/ddf/libs/mpeg/transport/MTSValidPacketIteratorTest.java

See [PR-1360](https://github.com/codice/ddf/pull/1360)
@bdeining 
@glenhein 
@jlcsmith
@kcwire

DDF-2540: (backport) Added ingest support for mpegts clips with invalid TS packets

---

catalog/core/catalog-core-commands/pom.xml
pom.xml

* The gmavenplus plugin was not being run during the release profile, causing Spock tests not to count for test coverage
* A floating point issue with one coverage number caused a failure when it was off by .01
@coyotesqrl …

DDF-2551 Fixes minor releasability issues with 2.9.3

---

distribution/sdk/sample-twitter-source/src/main/java/org/codice/ddf/catalog/twitter/source/TwitterSource.java

Fixes the twitter sdk source.
@spearskw @emanns95 
@shaundmorris
@stustison

DDF-2548: Added source id to twitter source results (#1364)

---

catalog/plugin/catalog-plugin-videothumbnail/src/main/java/org/codice/ddf/catalog/content/plugin/video/VideoThumbnailPlugin.java

This PR adds  debug logging to VideoThumbnailPlugin
@lcrosenbu @peterhuffer 
@jlcsmith
@coyotesqrl 
Build DDF

DDF-2558 Added some debug logging to VideoThumbnailPlugin

---

catalog/core/catalog-core-urlresourcereader/src/main/java/ddf/catalog/resource/impl/URLResourceReader.java
catalog/core/catalog-core-urlresourcereader/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/core/catalog-core-urlresourcereader/src/test/java/ddf/catalog/resource/impl/ResourceReaderTest.java
catalog/spatial/ogc/spatial-ogc-urlresourcereader/src/test/java/org/codice/ddf/spatial/ogc/catalog/resource/impl/TestResourceReader.java

Updates the URLResourceReader to handle basic auth username/password
@gordocanchola @brianfelix 
@shaundmorris
@stustison
https://codice.atlassian.net/browse/DDF-2547

DDF-2547 Updated URLResourceReader to use basic auth username/password if present.

---

CHANGES.md

Updates release date on Changelog for 2.9.3.
@kcwire @coyotesqrl @shaundmorris 
@coyotesqrl
@kcwire
@shaundmorris
check the date
[DDF-2510](https://codice.atlassian.net/browse/DDF-2510)

DDF-2510 updated changelog with release date

---

catalog/ui/search-ui/search-endpoint/pom.xml
catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/endpoint/CometdEndpoint.java
catalog/ui/search-ui/search-endpoint/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/ui/search-ui/search-endpoint/src/test/java/org/codice/ddf/ui/searchui/query/endpoint/CometdEndpointTest.java

Fixes the cometd endpoint from failing to initialize on install and reboot.
@brendan-hofmann @coyotesqrl
@kcwire
@pklinef
@stustison
Extract DDF and install.
Make sure there are no warnings/errors in logs during install related to the search-endpoint or …

DDF-2564: Updated cometd endpoint to properly startup

---

catalog/ui/search-ui/search-endpoint/pom.xml
catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/endpoint/CometdEndpoint.java
catalog/ui/search-ui/search-endpoint/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/ui/search-ui/search-endpoint/src/test/java/org/codice/ddf/ui/searchui/query/endpoint/CometdEndpointTest.java

Fixes the cometd endpoint from failing to initialize on install and reboot.
@brendan-hofmann @coyotesqrl
@kcwire
@pklinef
Extract DDF and install.
Make sure there are no warnings/errors in logs during install related to the search-endpoint or cometd. …

DDF-2564: Updated cometd endpoint to properly startup (#1395)

---

catalog/core/catalog-core-camelcomponent/pom.xml
catalog/core/catalog-core-solr/pom.xml
catalog/pom.xml
distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/ServiceManagerImpl.java
libs/httpproxy/proxy-camel-servlet/src/main/java/org/codice/proxy/http/HttpProxyCamelHttpTransportServlet.java
platform/platform-app/src/main/resources/features.xml
pom.xml

upgrade artemis to 1.4.0 and upgrades camel to 2.18.0 for some bugfixes and to get the latest camel-spring so we can use the caching connection factory with artemis
@roelens8 @jrnorth @harrison-tarr 
@jaymcnallie
@pklinef
run integratikon tests make sure version changes didnt break anything

DDF-2565 upgrade camel 2.18  and artemis 1.4

---

distribution/docs/src/main/resources/_contents/_installing/installing-intro-contents.adoc
distribution/docs/src/main/resources/_contents/_quickstart/quickstart-configuring-contents.adoc
distribution/docs/src/main/resources/_contents/_quickstart/quickstart-installing-contents.adoc
distribution/docs/src/main/resources/_contents/_running/running-intro-contents.adoc
distribution/docs/src/main/resources/_contents/_running/troubleshooting-contents.adoc
distribution/docs/src/main/resources/_contents/config.adoc
distribution/docs/src/main/resources/_contents/installing-contents.adoc
distribution/docs/src/main/resources/_contents/quickstart-contents.adoc
distribution/docs/src/main/resources/_contents/running-contents.adoc

Updates to `Installing` directions in documentation to replace outdated/incorrect commands for Windows platform. 
@brianfelix @emanns95 @AzGoalie @clockard @spearskw @Lambeaux @djblue 
@figliold
@lessarderic
[DDF-2481](https://codice.atlassian.net/browse/DDF-2481)

DDF-2481 updated Windows commands in installing directions for docs

---

distribution/docs/src/main/resources/_contents/_platform-contents/integrating-platform-contents.adoc
platform/landing-page/pom.xml
platform/landing-page/src/main/java/org/codice/ddf/landing/LandingPage.java
platform/landing-page/src/main/resources/OSGI-INF/blueprint/blueprint.xml
platform/landing-page/src/main/resources/OSGI-INF/metatype/metatype.xml
platform/landing-page/src/main/resources/index.handlebars
platform/landing-page/src/test/groovy/org/codice/ddf/landing/TestLandingPageSpock.groovy

Adds the ability to add custom links to the landing page
@AzGoalie @jckilmer
@kcwire
@shaundmorris
Add links in the landing page configuration and make sure they show up on the landing page
With more prominent buttons:
Bookmarks title configurable, different styling:

DDF-2559 add ability to add custom links to the landing page

---

pom.xml

Upgrades the frontend-maven-plugin to version 1.2.
@Lambeaux @emanns95 
@pklinef
@shaundmorris
Test that parallel builds work by using -T 2C with the mvn command.

DDF-2568: Updated frontend-maven-plugin to 1.2

---

catalog/rest/catalog-rest-endpoint/src/main/java/org/codice/ddf/endpoints/rest/RESTEndpoint.java

Change log level for DataUsageLimitExceededException since it is an expected exception
@lcrosenbu 
@jlcsmith
@lessarderic
Build DDF

DDF-2273 Changed log level for DataUsageLimitExceededException in REST endpoint

---

distribution/docs/src/main/resources/_contents/config.adoc
distribution/docs/src/main/resources/_contents/configuring-contents.adoc
distribution/docs/src/main/resources/_contents/configuring-from-configuration-files-contents.adoc
distribution/docs/src/main/resources/_contents/configuring-from-import-contents.adoc
distribution/docs/src/main/resources/_contents/configuring-from-the-command-console-contents.adoc
distribution/docs/src/main/resources/_contents/installing-contents.adoc
distribution/docs/src/main/resources/_contents/quickstart-contents.adoc
distribution/docs/src/main/resources/ddf-quickstart.adoc

Copy edits to quickstart and installation instructions.
@mcalcote @clockard @tbatie @garrettfreibott @emanns95 @mweser @spearskw 
@pklinef
@shaundmorris
Verify changes to content.
[DDF-2481](https://codice.atlassian.net/browse/DDF-2481)

Ddf 2481 2.9.x Updated Installation & quickstart instructions

---

catalog/ui/search-ui/standard/src/main/doc/_contents/help-contents.adoc

Removes outdated links from Search UI documentation.
Adds changes made to https://github.com/codice/ddf/pull/1420 to master branch.
@mcalcote @Lambeaux @jrnorth
@pklinef
@shaundmorris
[DDF-2593](https://codice.atlassian.net/browse/DDF-2593)

DDF-2593 removed dead image links

---

catalog/ui/search-ui/standard/src/main/webapp/js/HandlebarsHelpers.js
catalog/ui/search-ui/standard/src/main/webapp/templates/metacard.handlebars

Port from the 2.9.x branch
@pklinef
Manually test that multi-valued url fields show up as links
https://github.com/codice/ddf/pull/1427
DDF-2599

DDF-2599 PORT -  Enable multi-valued url attribute links in search ui

---

catalog/schematron/catalog-schematron-plugin/src/main/java/ddf/services/schematron/SchematronValidationService.java
catalog/schematron/catalog-schematron-plugin/src/test/java/ddf/services/schematron/SchematronValidationServiceTest.java

Decouple system startup from schematron compilation.
@spearskw @AzGoalie 
@coyotesqrl
@shaundmorris 
[DDF-2608](https://codice.atlassian.net/browse/DDF-2608)

DDF-2608 Compile schematron asynchronously

---

platform/platform-filter-delegate/src/main/java/org/codice/ddf/platform/filter/delegate/FilterInjector.java

@harrison-tarr @AzGoalie 
@pklinef
@stustison

DDF-2611 ignore exception thrown by setting cookie path

---

catalog/spatial/registry/registry-publication-update-handler/src/main/java/org/codice/ddf/registry/publication/RegistryPublicationHandler.java
catalog/spatial/registry/registry-publication-update-handler/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/spatial/registry/registry-publication-update-handler/src/test/java/org/codice/ddf/registry/publication/RegistryPublicationHandlerTest.java

Port from the 2.9.x branch
@shaundmorris
Verify bamboo build
https://github.com/codice/ddf/pull/1417
DDF-2591

DDF-2591 Added delay to publication updates.

---

catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/content/operation/impl/ReadStorageResponseImpl.java
catalog/core/catalog-core-api/src/main/java/ddf/catalog/content/operation/ReadStorageResponse.java
catalog/core/catalog-core-localstorageprovider/pom.xml
catalog/core/catalog-core-localstorageprovider/src/main/java/org/codice/ddf/catalog/content/impl/FileSystemStorageProvider.java

see title.
@jrnorth 
@peterhuffer 
@lessarderic
@stustison

DDF-2520: Protects FileSystemStorageProvider from null resource URIs

---

libs/webapps/lib-webapps-grunt-port-allocator/npm-shrinkwrap.json
libs/webapps/lib-webapps-grunt-port-allocator/package.json

Removes git sha's with npm registry locations.
@coyotesqrl
@pklinef

DDF-2592: Removed git sha from shrinkwrap

---

catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/content/operation/impl/ReadStorageResponseImpl.java
catalog/core/catalog-core-api/src/main/java/ddf/catalog/content/operation/ReadStorageResponse.java
catalog/core/catalog-core-localstorageprovider/pom.xml
catalog/core/catalog-core-localstorageprovider/src/main/java/org/codice/ddf/catalog/content/impl/FileSystemStorageProvider.java

see title.
@jrnorth 
@peterhuffer 
@lessarderic
@stustison

[2.9.x] DDF-2520: Protects FileSystemStorageProvider from null resource URIs

---

distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/AbstractIntegrationTest.java

Enforces UTF-8 in integration tests as we do in production.
@brendan-hofmann @emanns95 
@coyotesqrl
@shaundmorris
@stustison

DDF-2622: Added UTF-8 to integration tests

---

catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/validation/impl/validator/EnumerationValidator.java

Fixes Enumeration Validator to not mutate the values passed in. 
@troymohl @bdeining @andrewkfiedler 
@coyotesqrl
@jlcsmith
https://codice.atlassian.net/browse/DDF-2625

DDF-2625: Fixes case insensitive enumeration validator

---

catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/content/data/impl/ContentItemImpl.java

DDF-2423: Added toString to ContentItemImpl

---

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/history/Historian.java
catalog/core/catalog-core-standardframework/src/main/resources/OSGI-INF/metatype/metatype.xml

Turns off versioning by default
@pklinef
@shaundmorris

[2.9.x] DDF-2634: Turned versioning off by default

---

distribution/docs/src/main/resources/_contents/_catalog-contents/extending-catalog-contents.adoc
distribution/docs/src/main/resources/_contents/_console-commands/developing-console-commands-contents.adoc
distribution/docs/src/main/resources/_contents/_eventing/eventing-intro-contents.adoc
distribution/docs/src/main/resources/_contents/_eventing/subscriptions-contents.adoc
distribution/docs/src/main/resources/_contents/_operations/operations-intro-contents.adoc
distribution/docs/src/main/resources/_contents/_queries/developing-filter-delegates-contents.adoc
distribution/docs/src/main/resources/_contents/_queries/developing-filters-contents.adoc
distribution/docs/src/main/resources/_contents/_queries/developing-ogc-filters-contents.adoc
distribution/docs/src/main/resources/_contents/_queries/developing-query-options-contents.adoc
distribution/docs/src/main/resources/_contents/_queries/filter-intro-contents.adoc
distribution/docs/src/main/resources/_contents/_queries/queries-intro-contents.adoc
distribution/docs/src/main/resources/_contents/_resources/content-directory-monitor-contents.adoc
distribution/docs/src/main/resources/_contents/_resources/developing-registry-clients-contents.adoc
distribution/docs/src/main/resources/_contents/_resources/developing-resource-readers-contents.adoc
distribution/docs/src/main/resources/_contents/_resources/developing-resource-writers-contents.adoc
distribution/docs/src/main/resources/_contents/_resources/resource-components-intro-contents.adoc
distribution/docs/src/main/resources/_contents/_resources/resource-readers-contents.adoc
distribution/docs/src/main/resources/_contents/_resources/resource-readers-intro-contents.adoc
distribution/docs/src/main/resources/_contents/_resources/resource-writers-contents.adoc
distribution/docs/src/main/resources/_contents/_resources/resource-writers-intro-contents.adoc
distribution/docs/src/main/resources/_contents/_resources/resources-intro-contents.adoc
distribution/docs/src/main/resources/_contents/_resources/retrieving-resources-contents.adoc
distribution/docs/src/main/resources/_contents/_resources/retrieving-resources-options-contents.adoc
distribution/docs/src/main/resources/_contents/_resources/storing-resources-contents.adoc
distribution/docs/src/main/resources/_contents/_resources/url-resource-reader-contents.adoc
distribution/docs/src/main/resources/_contents/_tables/ddf.catalog.resource.impl.URLResourceReader-table-contents.adoc
distribution/docs/src/main/resources/_contents/_tables/org.codice.ddf.catalog.content.monitor.ContentDirectoryMonitor-table-contents.adoc
distribution/docs/src/main/resources/_contents/extending-contents.adoc
distribution/docs/src/main/resources/draft-documentation.adoc

Adds Operations, Eventing, Resources, and Console Commands sections to revised docs. 
@bdeining @clockard @jlcsmith @peterhuffer 
@pklinef
@shaundmorris
docs render correctly, build passes, content complete and up-to-date
Sub task of https://codice.atlassian.net/browse/DDF-2309
https://codice.atlassian.net/browse/DDF-2402
[draft-documentation.pdf](https://github.com/codice/ddf/files/460295/draft-documentation.pdf)

Ddf 2402 added Operations, Eventing, Resources, and Console Commands sections to revised docs.

---

distribution/docs/src/main/resources/_contents/_security-framework/developing-token-validators-contents.adoc
distribution/docs/src/main/resources/_contents/_security-framework/external-ws-s-sts-support-contents.adoc
distribution/docs/src/main/resources/_contents/_security-framework/guest-interceptor-contents.adoc
distribution/docs/src/main/resources/_contents/_security-framework/security-core-api-contents.adoc
distribution/docs/src/main/resources/_contents/_security-framework/security-core-commons-contents.adoc
distribution/docs/src/main/resources/_contents/_security-framework/security-core-implementation-contents.adoc
distribution/docs/src/main/resources/_contents/_security-framework/security-core-intro-contents.adoc
distribution/docs/src/main/resources/_contents/_security-framework/security-encryption-api-contents.adoc
distribution/docs/src/main/resources/_contents/_security-framework/security-encryption-commands-contents.adoc
distribution/docs/src/main/resources/_contents/_security-framework/security-encryption-implementation-contents.adoc
distribution/docs/src/main/resources/_contents/_security-framework/security-encryption-intro-contents.adoc
distribution/docs/src/main/resources/_contents/_security-framework/security-framework-intro-contents.adoc
distribution/docs/src/main/resources/_contents/_security-framework/security-idp-intro-contents.adoc
distribution/docs/src/main/resources/_contents/_security-framework/security-ldap-embedded-server-contents.adoc
distribution/docs/src/main/resources/_contents/_security-framework/security-ldap-intro-contents.adoc
distribution/docs/src/main/resources/_contents/_security-framework/security-pdp-authz-realm-contents.adoc
distribution/docs/src/main/resources/_contents/_security-framework/security-pdp-intro-contents.adoc
distribution/docs/src/main/resources/_contents/_security-framework/security-pep-interceptor-contents.adoc
distribution/docs/src/main/resources/_contents/_security-framework/security-pep-intro-contents.adoc
distribution/docs/src/main/resources/_contents/_security-framework/security-rest-intro-contents.adoc
distribution/docs/src/main/resources/_contents/_security-framework/security-soap-intro-contents.adoc
distribution/docs/src/main/resources/_contents/_security-framework/security-sts-client-config-contents.adoc
distribution/docs/src/main/resources/_contents/_security-framework/security-sts-intro-contents.adoc
distribution/docs/src/main/resources/_contents/_security-framework/security-sts-ldap-claims-handler-contents.adoc
distribution/docs/src/main/resources/_contents/_security-framework/security-sts-ldap-login-contents.adoc
distribution/docs/src/main/resources/_contents/_security-framework/security-sts-server-contents.adoc
distribution/docs/src/main/resources/_contents/_security-framework/security-sts-service-contents.adoc
distribution/docs/src/main/resources/_contents/_security-framework/security-wss-intro-contents.adoc
distribution/docs/src/main/resources/_contents/_tables/ddf.security.sts.client.configuration-table-contents.adoc
distribution/docs/src/main/resources/draft-documentation.adoc

Adds integrator-focused docs on the security framework. 
@ryeats @troymohl @brendan-hofmann @harrison-tarr 
@pklinef
@shaundmorris
@stustison
docs render correctly, build passes, info complete & up-to-date.
sub task of https://codice.atlassian.net/browse/DDF-2309
https://codice.atlassian.net/browse/DDF-2403
[draft-documentation.pdf](https://github.com/codice/ddf/files/460460/draft-documentation.pdf)

Ddf 2403 Added security framework to integrator docs

---

CHANGES.md

- Adds section to CHANGES.md for version 2.9.5 
- updates Release Build Date for 2.9.4
@coyotesqrl
@shaundmorris
preview CHANGES.md file as seen on github

DDF-2309 updated changelog for 2.9.5 version

---

distribution/docs/src/main/resources/_contents/_apis/application-service-api-contents.adoc
distribution/docs/src/main/resources/_contents/_apis/migration-api-contents.adoc
distribution/docs/src/main/resources/_contents/_app-whitelists/admin-whitelist-contents.adoc
distribution/docs/src/main/resources/_contents/_app-whitelists/catalog-whitelist-contents.adoc
distribution/docs/src/main/resources/_contents/_app-whitelists/platform-whitelist-contents.adoc
distribution/docs/src/main/resources/_contents/_app-whitelists/registry-whitelist-contents.adoc
distribution/docs/src/main/resources/_contents/_app-whitelists/security-whitelist-contents.adoc
distribution/docs/src/main/resources/_contents/_app-whitelists/solr-whitelist-contents.adoc
distribution/docs/src/main/resources/_contents/_app-whitelists/spatial-whitelist-contents.adoc
distribution/docs/src/main/resources/_contents/_app-whitelists/ui-whitelist-contents.adoc
distribution/docs/src/main/resources/_contents/_developing/contributing-intro-contents.adoc
distribution/docs/src/main/resources/_contents/_developing/developing-catalog-api-contents.adoc
distribution/docs/src/main/resources/_contents/_developing/developing-intro-contents.adoc
distribution/docs/src/main/resources/_contents/draft-extending-contents.adoc
distribution/docs/src/main/resources/draft-documentation.adoc

Adds development recommendations and API sections to docs, as well as App Whitelists.
@coyotesqrl @Lambeaux @jrnorth 
@pklinef
@shaundmorris
Review outline, Docs render correctly, build passes
sub-task of https://codice.atlassian.net/browse/DDF-2309
https://codice.atlassian.net/browse/DDF-2405
[draft-documentation.pdf](https://github.com/codice/ddf/files/462168/draft-documentation.pdf)

Ddf 2405 added developing and api sections to docs

---

catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/data/impl/MetacardImpl.java

Fixes the MetacardImpl copy constructor from adding null attributes
@mcalcote @Lambeaux 
@lessarderic
@pklinef
- The copy constructor will no longer copy null attributes

DDF-2520: Fixed MetacardImpl copy Constructor

---

catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/MetacardIdEqualityFilterDelegate.java
catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/SolrCatalogProvider.java
catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/TestSolrProvider.java

It takes up to a second for a created, updated, or deleted metacard to become visible in the Solr near real time (NRT) index.  During this time, the catalog framework will not allow updates and deletes due to security checks if the active user has access to the current version of the metacard.  This adds a pending NRT index that is indexed by ID only.  This will allow all catalog operations to pass security checks before the metacards are fully indexed by Solr.  Pending metacards will still not be returned for non-ID queries.
@rzwiefel 
@coyotesqrl
@pklinef
I tested using something similar to the following command.  Make sure to replace the two `<path to ddf clone>` places holders.  Inspect the created metacard and verify …

DDF-2620 Allow updates to metacards that are pending NRT indexing

---

distribution/sdk/sample-cometd/cometd-web-example/pom.xml

Fixes parallel builds on windows
@brendan-hofmann @spearskw 
@coyotesqrl
@pklinef
Removed cleaning of node and npm folders in the cometd-web-example. This breaks parallel builds on windows.

DDF-2592: Removed cleaning of node/npm folders

---

distribution/docs/src/main/resources/_contents/_installing/installing-intro-contents.adoc
distribution/docs/src/main/resources/_contents/installing-contents.adoc

Removes unneeded step to add user on Windows. (master version)
@AzGoalie @Lambeaux @spearskw 
@figliold
@shaundmorris
verify command removed.
[DDF-2481](https://codice.atlassian.net/browse/DDF-2481)

DDF-2481 updated documentation for installing on Windows

---

distribution/docs/src/main/resources/_contents/installing-contents.adoc

Removes unneeded step to add user on Windows. (2.9.x version)
@AzGoalie @Lambeaux @spearskw 
@figliold
@shaundmorris
verify command removed.
[DDF-2481](https://codice.atlassian.net/browse/DDF-2481)

Ddf 2481 2.9.x update Windows installation documentation

---

catalog/ui/search-ui/standard/pom.xml
distribution/docs/pom.xml
pom.xml

Cleans up the documentation profiles in search-ui and docs
@brendan-hofmann @ricklarsen 
@pklinef
@shaundmorris
Building documentation passes on windows/mac/Linux
Documentation is correct

Ddf 2614: Updated documentation profiles

---

catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/validation/impl/validator/EnumerationValidator.java

Fixes Enumeration Validator to not mutate the values passed in. 
@troymohl @bdeining @jrnorth 
@coyotesqrl
@jlcsmith
https://codice.atlassian.net/browse/DDF-2625
#

DDF-2625: Fixed Enumeration Validator issue for null attribute values

---

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/CreateOperations.java
catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/DeleteOperations.java
catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/UpdateOperations.java

- Moves `PostIngestPlugin` processing to occur after (Create|Update|Delete)Requests and (Create|Update|Delete)StorageRequests have been completed and committed.
@emmberk @troymohl 
@coyotesqrl
@pklinef
Full build with integration tests passing.
This is a prerequisite required for the Asynchronous Plugins. Asynchronous Plugins may want to access content, and it must be available. Ensuring content is committed before running the `PostIngestPlugin`s will help ensure that content will be available when needed.
[DDF-2647](https://codice.atlassian.net/browse/DDF-2647)

DDF-2647: Move PostIngestPlugin processing to after content is committed

---

distribution/docs/src/main/resources/_contents/_solr-contents/managing-solr-contents.adoc

Document Solr Cloud setup for High Availability
@lessarderic @figliold @brjeter @Lambeaux @oconnormi 
@ricklarsen 
@figliold
@shaundmorris
Install SolrCloud and Zookeeper using the instructions
https://codice.atlassian.net/browse/DDF-2610

DDF-2610 added documentation to install solrcloud and zookeeper

---

catalog/core/catalog-core-solr/pom.xml
catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/RemoteSolrCatalogProvider.java
catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/UnavailableSolrCatalogProvider.java
catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/AttributeDescriptorImplTest.java
catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/DynamicSchemaResolverTest.java
catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/RemoteSolrCatalogProviderTest.java
catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/SolrFilterBuilderTest.java
catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/SolrFilterDelegateTest.java
catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/SolrProviderTest.java
catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/SolrProviderTestCase.java
distribution/ddf-common/src/main/resources/etc/system.properties
distribution/docs/src/main/resources/_contents/_solr-contents/integrating-solr-contents.adoc
platform/persistence/platform-persistence-core-listeners/pom.xml
platform/platform-app/src/main/resources/features.xml
platform/solr/solr-banana-provisioner/src/main/java/org.codice.banana/BananaSolrProvisioner.java
platform/solr/solr-factory/pom.xml
platform/solr/solr-factory/src/main/java/org/codice/solr/factory/SolrClientFactory.java
platform/solr/solr-factory/src/main/java/org/codice/solr/factory/impl/ConfigurationFileProxy.java
platform/solr/solr-factory/src/main/java/org/codice/solr/factory/impl/EmbeddedSolrFactory.java
platform/solr/solr-factory/src/main/java/org/codice/solr/factory/impl/HttpSolrClientFactory.java
platform/solr/solr-factory/src/main/java/org/codice/solr/factory/impl/SolrClientFactoryImpl.java
platform/solr/solr-factory/src/main/java/org/codice/solr/factory/impl/SolrCloudClientFactory.java
platform/solr/solr-factory/src/test/java/org/codice/solr/factory/impl/ConfigurationFileProxyTest.java
platform/solr/solr-factory/src/test/java/org/codice/solr/factory/impl/ConfigurationStoreTest.java
platform/solr/solr-factory/src/test/java/org/codice/solr/factory/impl/SolrClientFactoryImplTest.java

Addressed unaddressed comments from https://github.com/codice/ddf/pull/1426.
@Lambeaux 
@oconnormi 
@brjeter 
@figliold
@pklinef
Use new solr.* properties in etc/system.properties to verify that all available system properties work as intended. This includes trying the embedded, HTTP, and Cloud modes as well as changing the data directory. You will need to restart DDF after changing the system.properties file. You can also set the system property in the console and restart the Solr Provider bundle.
See https://github.com/codice/ddf/pull/142
[DDF-2467](https://codice.atlassian.net/browse/DDF-2467)
[DDF-2628](https://codice.atlassian.net/browse/DDF-2628)

DDF-2628: Address left over comments from original SolrCloud PR

---

CHANGES.md
catalog/catalog-app/pom.xml
catalog/catalog-app/src/main/resources/features.xml
catalog/confluence/catalog-confluence-common/pom.xml
catalog/confluence/catalog-confluence-common/src/main/java/org/codice/ddf/confluence/common/Confluence.java
catalog/confluence/catalog-confluence-common/src/main/resources/confluence.wadl
catalog/confluence/catalog-confluence-source/pom.xml
catalog/confluence/catalog-confluence-source/src/main/java/org/codice/ddf/confluence/source/ConfluenceFilterDelegate.java
catalog/confluence/catalog-confluence-source/src/main/java/org/codice/ddf/confluence/source/ConfluenceInputTransformer.java
catalog/confluence/catalog-confluence-source/src/main/java/org/codice/ddf/confluence/source/ConfluenceQueryParameter.java
catalog/confluence/catalog-confluence-source/src/main/java/org/codice/ddf/confluence/source/ConfluenceSource.java
catalog/confluence/catalog-confluence-source/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/confluence/catalog-confluence-source/src/main/resources/OSGI-INF/metatype/metatype.xml
catalog/confluence/catalog-confluence-source/src/main/resources/describable.properties
catalog/confluence/catalog-confluence-source/src/test/java/org/codice/ddf/confluence/source/ConfluenceFilterDelegateTest.java
catalog/confluence/catalog-confluence-source/src/test/java/org/codice/ddf/confluence/source/ConfluenceInputTransformerTest.java
catalog/confluence/catalog-confluence-source/src/test/java/org/codice/ddf/confluence/source/ConfluenceSourceTest.java
catalog/confluence/catalog-confluence-source/src/test/resources/confluence_attachment.json
catalog/confluence/catalog-confluence-source/src/test/resources/confluence_page.json
catalog/confluence/catalog-confluence-source/src/test/resources/confluence_page_no_restrictions.json
catalog/confluence/catalog-confluence-source/src/test/resources/full_response.json
catalog/confluence/pom.xml
catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/data/impl/types/AssociationsAttributes.java
catalog/core/catalog-core-api/src/main/java/ddf/catalog/data/types/Associations.java
catalog/pom.xml
distribution/docs/src/main/resources/_contents/_catalog-contents/configuring-catalog-contents.adoc
distribution/docs/src/main/resources/_contents/_catalog-contents/extending-catalog-contents.adoc
distribution/docs/src/main/resources/_contents/_sources/confluence-federated-source-contents.adoc
distribution/docs/src/main/resources/_contents/_tables/Confluence_Federated_Source-table-contents.adoc
distribution/docs/src/main/resources/_contents/_tables/conf-Confluence_Federated_Source-table-contents.adoc

Adds the Confluence federated source to DDF
@brendan-hofmann @jlcsmith @mcalcote @ricklarsen 
@kcwire
@pklinef
- Install DDF and create a Confluence Federated Source using https://codice.atlassian.net/wiki/rest/api/content/ for the url.
- Login to the search ui as the system high user
- Verify that you can get search results back from the confluence source.
- Verify that you can download attachments. 
https://codice.atlassian.net/browse/DDF-2535

DDF-2535 Create Confluence Source

---

catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/SolrFilterDelegate.java
catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/TestSolrFilterDelegate.java
catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/TestSolrProvider.java

Backport of #1474  
@pklinef 
@kcwire

DDF-2636 resolved querying with wildcards on fields containing hyphens

---

distribution/ddf-common/src/main/resources/etc/artemis.xml
distribution/ddf-common/src/main/resources/etc/system.properties
platform/platform-app/src/main/resources/features.xml
pom.xml

Upgrades artemis to 1.5.1 to get some bug fixes we need
@jrnorth 
@roelens8  
@dcruver 
@jaymcnallie
@kcwire
feature:install artemis-amqp
then verify that the artemis starts up in jconsole and it has the correct acceptor …

DDF-2607 upgrade to artemis 1.5.1

---

catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/source/impl/SourceDescriptorImpl.java
catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/SourceOperations.java
catalog/core/catalog-core-standardframework/src/main/resources/OSGI-INF/blueprint/sources.xml
catalog/core/catalog-core-standardframework/src/test/groovy/ddf/catalog/impl/operations/SourceOperationsTest.groovy
catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/impl/CatalogFrameworkImplTest.java
catalog/pom.xml
catalog/rest/catalog-rest-endpoint/pom.xml
catalog/rest/catalog-rest-endpoint/src/test/java/org/codice/ddf/endpoints/rest/TestRestEndpoint.java
catalog/spatial/geocoding/spatial-geocoding-geocoder/pom.xml
catalog/spatial/geocoding/spatial-geocoding-websearch/pom.xml
catalog/transformer/catalog-transformer-geojson-queryresponse/pom.xml
distribution/test/itests/pom.xml
distribution/test/itests/test-itests-common/pom.xml
distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/CatalogBundle.java
distribution/test/itests/test-itests-ddf/pom.xml
distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFanout.java
distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestRegistry.java
distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestSecurity.java
distribution/test/thirdparty/restito/pom.xml
platform/admin/ui/pom.xml
platform/platform-configuration/pom.xml
platform/pom.xml
platform/security/common/pom.xml
platform/security/handler/security-handler-api/pom.xml
platform/security/handler/security-handler-guest/pom.xml
platform/security/platform-security-core-api/pom.xml
platform/security/pom.xml
platform/security/servlet/security-servlet-logout/pom.xml
pom.xml

@emanns95
@lessarderic
@pklinef
@stustison

DDF-2663 fixed issues with sources not being added to descriptors correctly

---

catalog/core/catalog-core-api/src/main/java/ddf/catalog/data/types/constants/core/DataType.java
catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/GmdConverter.java
catalog/spatial/csw/spatial-csw-transformer/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/transformer/TestGmdTransformer.java
catalog/transformer/catalog-transformer-pdf/src/main/java/ddf/catalog/transformer/input/pdf/PdfInputTransformer.java
catalog/transformer/catalog-transformer-video-input/src/main/java/ddf/catalog/transformer/input/video/VideoInputTransformer.java
catalog/transformer/catalog-transformer-video-input/src/test/java/ddf/catalog/transformer/input/video/VideoInputTransformerTest.java

* Create enum CoreDataType, which contains the supported values for Core#DATATYPE.
* Replace existing Core#DATATYPE strings with calls to CoreDataType.
* Update VideoInputTransformer to set Core#DATATYPE to CoreDataType#VIDEO.
@kcwire 
@jlcsmith 
@bdeining 
@beyelerb
@lessarderic
Run unit tests and itests for general changes.
For video, ingest a generic video file that uses the VideoInputTransformer. For example:
```
<value>video/avi</value>
<value>video/msvideo</value>
<value>video/vnd.avi</value>
<value>video/x-msvideo</value>
<value>video/mp4</value>
<value>video/MP2T</value>
<value>video/mpeg</value>
<value>video/quicktime</value>
<value>video/wmv</value> …
```

DDF-2632 Formalize the use of Core#Datatype attribute values

---

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/CachingFederationStrategy.java
catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/SortedQueryMonitor.java
catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/cache/solr/impl/SortedQueryMonitorTest.java

This PR moves the PostFederationQueryPlugin execution into the CallableSourceResponse class so that it Pre and PostFederationQueryPlugins are executed once for every Source.  
@jlcsmith
@pklinef
@kcwire 
Build / Install Development Profile / Configure CSW Sources and Execute Queries / Observe ResourceManagement removes queries once they fail / are completed/
This issue was discovered when using the Resource Management app.  Pre and Post FederationQueryPlugins were no being execute an equal number of times for each source, causing them to linger in QueryMonitor.java
[DDF-2612](https://codice.atlassian.net/browse/DDF-2612)

DDF-2612 Moved PostFederationQueryPlugin execution into CallableSourceResponse

---

CHANGES.md
catalog/catalog-app/pom.xml
catalog/catalog-app/src/main/resources/features.xml
catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/validation/impl/validator/EnumerationValidator.java
catalog/security/catalog-security-resourceplugin/pom.xml
catalog/security/catalog-security-resourceplugin/src/main/java/org/codice/ddf/catalog/security/ResourceUriPolicy.java
catalog/security/catalog-security-resourceplugin/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/security/catalog-security-resourceplugin/src/main/resources/OSGI-INF/metatype/metatype.xml
catalog/security/catalog-security-resourceplugin/src/test/java/org/codice/ddf/catalog/security/ResourceUriPolicyTest.java
catalog/security/pom.xml
catalog/solr/catalog-solr-provider/src/main/resources/OSGI-INF/metatype/metatype.xml
distribution/docs/src/main/resources/_contents/_catalog-contents/configuring-catalog-contents.adoc
distribution/docs/src/main/resources/_contents/_plugins/catalog-policy-plugin-contents.adoc
distribution/docs/src/main/resources/_contents/_plugins/plugin-compatibility-table-contents.adoc
distribution/docs/src/main/resources/_contents/_plugins/policy-plugins-contents.adoc
distribution/docs/src/main/resources/_contents/_plugins/resource-uri-policy-plugin-contents.adoc
distribution/docs/src/main/resources/_contents/_securing/securing-contents.adoc
distribution/docs/src/main/resources/_contents/_tables/conf-org.codice.catalog.security.ResourceUriPolicy-table-contents.adoc
distribution/docs/src/main/resources/_contents/_tables/org.codice.ddf.catalog.security.ResourceUriPolicy-table-contents.adoc
distribution/docs/src/main/resources/_contents/securing-contents.adoc
distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestRegistry.java
pom.xml

Allow administrators to allow privileged users to update metacard resource URI or add a resource URI when creating a metacard. 
@brendan-hofmann @mweser @emanns95 @spearskw
@stustison 
@figliold
@stustison
It has been manually tested. 
No.

DDF-2639 Restrict access to updating or creating resource URIs on metacards

---

catalog/transformer/catalog-transformer-pptx/pom.xml
platform/util/platform-util/pom.xml

Adds a missing dependency 
@glenhein @bdeining 
@jlcsmith
@kcwire
starting and ingesting a powerpoint with thumnails
https://codice.atlassian.net/browse/DDF-2665

DDF-2665: Added missing failsafe dependency

---

distribution/docs/pom.xml
distribution/docs/src/main/resources/_contents/_catalog-contents/integrating-catalog-contents.adoc
distribution/docs/src/main/resources/_contents/_configuring/configuring-from-configuration-files-contents.adoc

- fixes image links for generated diagrams.
- fixes broken diagram
@AzGoalie @calcote @Lambeaux 
@coyotesqrl
@lessarderic
@shaundmorris
@stustison
- docs build successfully
- diagrams included successfully
[DDF-2635](https://codice.atlassian.net/browse/DDF-2635)
n/a

Ddf 2635 POM corrections for documentation profile

---

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/CachingFederationStrategy.java
catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/SortedQueryMonitor.java

Fixes the total hits calculation in SortedQueryMonitor
@emanns95 @vinamartin @bdeining 
@coyotesqrl
@stustison

DDF-2612: Readded hits to SourceResponseImpl

---

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/QueryOperations.java

Ensures the Query Processing details get propagated through catalog framework.
@jrnorth @andrewkfiedler 
@jlcsmith
@kcwire
Bring down a csw source in between isAvailable pings and run a query against that source. Ensure that the response has the processing details that shows the source failed. 
https://codice.atlassian.net/browse/DDF-2667

DDF-2667: Ensure query details get propagated

---

catalog/ui/catalog-ui-search/npm-shrinkwrap.json

Shrinkwrap the catalog ui in a clean environment to avoid OS conflicts.
@djblue @rzwiefel 
@kcwire
@stustison
Do a clean build on windows, mac, and linux. (I already did this on windows but it wouldn't hurt)
Verify that the build succeeded with node v7.1.0 and npm 3.10.9.
Not directly related, but now that we are shrinkwrapping our dependencies, it should be noted that shrinkwrap recommends adding new dependencies using `npm install --save`. https://docs.npmjs.com/cli/shrinkwrap#building-shrinkwrapped-packages This avoids having to delete and regenerate the shrinkwrap file and reduces the chance of accidentally introducing this issue again in the future, e.g. by manually shrinkwrapping from the command line with a different version of npm. …

DDF-2644 Re-shrinkwrap catalog-ui

---

distribution/docs/src/main/resources/_contents/_data/data-intro-contents.adoc

Updates the core and metacard attributes in the "required metacard attributes" section of the docs to match the updated taxonomy.
@brianfelix 
@ricklarsen 
@jlcsmith
@lessarderic

DDF-2624 Updated core and metacard attributes in "required metacard attributes"

---

PULL_REQUEST_TEMPLATE

Added committer
@shaundmorris
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codice/ddf/1547)

DDF-2536 Added Andrew Fiedler to pull request template

---

catalog/async/catalog-async-data-api/pom.xml
catalog/async/catalog-async-data-api/src/main/java/org/codice/ddf/catalog/async/data/api/internal/ProcessCreateItem.java
catalog/async/catalog-async-data-api/src/main/java/org/codice/ddf/catalog/async/data/api/internal/ProcessDeleteItem.java
catalog/async/catalog-async-data-api/src/main/java/org/codice/ddf/catalog/async/data/api/internal/ProcessItem.java
catalog/async/catalog-async-data-api/src/main/java/org/codice/ddf/catalog/async/data/api/internal/ProcessRequest.java
catalog/async/catalog-async-data-api/src/main/java/org/codice/ddf/catalog/async/data/api/internal/ProcessResource.java
catalog/async/catalog-async-data-api/src/main/java/org/codice/ddf/catalog/async/data/api/internal/ProcessResourceItem.java
catalog/async/catalog-async-data-api/src/main/java/org/codice/ddf/catalog/async/data/api/internal/ProcessUpdateItem.java
catalog/async/catalog-async-plugin-api/pom.xml
catalog/async/catalog-async-plugin-api/src/main/java/org/codice/ddf/catalog/async/plugin/api/internal/PostProcessPlugin.java
catalog/async/catalog-async-processingframework-api/pom.xml
catalog/async/catalog-async-processingframework-api/src/main/java/org/codice/ddf/catalog/async/processingframework/api/internal/ProcessingFramework.java
catalog/async/pom.xml
catalog/pom.xml

- Adds an internal experimental API for asynchronous processing plugins.
@troymohl @emmberk @brendan-hofmann
@lessarderic
@pklinef
Full build.
There was a need for long running processes to be done asynchronously in order to decrease the amount of time it takes to process large amounts of data.
This PR is a prerequisite to [DDF-2569](https://github.com/codice/ddf/pull/1495) and was split up to make smaller PRs for easier reviews.
This PR is many tickets in one. [DDF-2576](https://codice.atlassian.net/browse/DDF-2576) is the Epic.
[DDF-2569](https://codice.atlassian.net/browse/DDF-2569)
[DDF-2571](https://codice.atlassian.net/browse/DDF-2571)
[DDF-2573](https://codice.atlassian.net/browse/DDF-2573)

DDF-2571: Add API to support asynchronous plugins

---

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/history/Historian.java

Backports the subject retrievel error fix in historian
anyone
anyone

[2.9.x] DDF-2606: Fixed Subject retrieval error in Historian

---

catalog/catalog-app/src/main/resources/features.xml
catalog/resourcemanagement/resourcemanagement-app/src/main/resources/features.xml
catalog/solr/solr-app/src/main/resources/features.xml
catalog/spatial/geowebcache/geowebcache-app/src/main/resources/features.xml
catalog/spatial/registry/registry-app/src/main/resources/features.xml
catalog/spatial/spatial-app/src/main/resources/features.xml
catalog/ui/search-ui/search-ui-app/src/main/resources/features.xml
platform/admin/admin-app/src/main/resources/features.xml
platform/platform-app/src/main/resources/features.xml
platform/security/security-services-app/src/main/resources/features.xml
pom.xml

Removes DDF from the App Names in the Admin UI.
@gordocanchola @vinamartin @clockard @brianfelix
@shaundmorris
Install DDF and inspect the app names in the admin ui
[DDF-2208](https://codice.atlassian.net/browse/DDF-2208)

DDF-2208 Remove DDF from app names

---

catalog/core/catalog-core-standardframework/pom.xml
catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/CatalogFrameworkImpl.java

Resolve an issue with mimetype resolution in tika's probabilistic detector.
@AzGoalie 
@ahoffer 
@pklinef
@stustison
Verify that a text file with a `.bin` extension gets a mimetype of `text/plain` instead of the default.
This issue was failing silently because we caught the IOException and logged it at `DEBUG`.
[](https://codice.atlassian.net/browse/DDF-2697)

DDF-2697 Fix mark/reset IOException

---

catalog/ui/search-ui/simple/src/main/webapp/SearchHelp.html
distribution/docs/src/main/resources/_contents/_using/using-intro-contents.adoc
distribution/docs/src/main/resources/_contents/_using/using-landing-page-contents.adoc
distribution/docs/src/main/resources/_contents/_using/using-simple-search-ui-contents.adoc
distribution/docs/src/main/resources/draft-documentation.adoc

Adds user-level documentation for the landing page and the simple search UI.
@emanns95 @mweser @AzGoalie @spearskw 
@pklinef
@shaundmorris
review content and formatting.
[DDF-26514](https://codice.atlassian.net/browse/DDF-2651)
[draft-documentation.pdf](https://github.com/codice/ddf/files/674683/draft-documentation.pdf)

DDF-2651 added documentation for using landing page and simple search ui

---

catalog/ui/catalog-ui-search/npm-shrinkwrap.json
catalog/ui/catalog-ui-search/package.json
catalog/ui/catalog-ui-search/server.js
catalog/ui/catalog-ui-search/src/main/webapp/WEB-INF/web.xml
catalog/ui/catalog-ui-search/src/main/webapp/component/component.less
catalog/ui/catalog-ui-search/src/main/webapp/component/lightbox/Lightbox.view.js
catalog/ui/catalog-ui-search/src/main/webapp/component/lightbox/blocking/lightbox.blocking.less
catalog/ui/catalog-ui-search/src/main/webapp/component/lightbox/blocking/lightbox.blocking.view.js
catalog/ui/catalog-ui-search/src/main/webapp/component/lightbox/lightbox.less
catalog/ui/catalog-ui-search/src/main/webapp/component/system-usage/system-usage.hbs
catalog/ui/catalog-ui-search/src/main/webapp/component/system-usage/system-usage.less
catalog/ui/catalog-ui-search/src/main/webapp/component/system-usage/system-usage.view.js
catalog/ui/catalog-ui-search/src/main/webapp/js/SystemUsage.js
catalog/ui/catalog-ui-search/src/main/webapp/js/model/User.js
catalog/ui/catalog-ui-search/src/main/webapp/less/components/iframe.less
catalog/ui/catalog-ui-search/src/main/webapp/less/components/init.less
catalog/ui/catalog-ui-search/src/main/webapp/less/vars.less
catalog/ui/catalog-ui-search/src/main/webapp/main.js

- Adds system usage modal which uses the system message property setting.
- The system usage message can sometimes contain html, so I've quarantined it to an iframe with the sandbox attribute set.  This should keep us secure while allowing admins a degree of freedom when constructing messages.
- Enables limited cors.  At this point it's only allowed for resources in the /css/ directoy, and only for GET and HEAD requests.  I went ahead and updated the grunt server proxy to add the same cors support, so development is easier.
@djblue 
@clockard 
@kcwire
@shaundmorris 
Go to the platform ui configuration in the Admin UI and set a system message.
https://codice.atlassian.net/browse/DDF-2702

DDF-2702 Add system usage modal, enable limited cors

---

distribution/docs/src/main/resources/_contents/_core-concepts/catalog-framework-intro-contents.adoc
distribution/docs/src/main/resources/_contents/_core-concepts/content-intro-contents.adoc
distribution/docs/src/main/resources/_contents/_core-concepts/endpoints-intro-contents.adoc
distribution/docs/src/main/resources/_contents/_core-concepts/ingest-intro-contents.adoc
distribution/docs/src/main/resources/_contents/_core-concepts/metadata-intro-contents.adoc
distribution/docs/src/main/resources/_contents/_core-concepts/requests-intro-contents.adoc
distribution/docs/src/main/resources/_contents/_endpoints/endpoints-intro-contents.adoc
distribution/docs/src/main/resources/_contents/_resources/resources-intro-contents.adoc
distribution/docs/src/main/resources/draft-documentation.adoc

Adds content to the Core Concepts section of the documentation, a high-level overview of important concepts within DDF. 
@mcalcote @Lambeaux @vinamartin @jrnorth
@coyotesqrl
@pklinef
@shaundmorris
@stustison
Review content.
[DDF-2471](https://codice.atlassian.net/browse/DDF-2471)
[draft-documentation.pdf](https://github.com/codice/ddf/files/696983/draft-documentation.pdf)

DDF-2471 updated Core Concept section of docs

---

catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/util/impl/SourcePollerRunner.java
catalog/spatial/registry/registry-api-impl/src/main/java/org/codice/ddf/registry/api/impl/RegistryStoreImpl.java
catalog/spatial/registry/registry-api-impl/src/test/java/org/codice/ddf/registry/api/impl/TestRegistryStore.java
catalog/spatial/registry/registry-federation-admin-service-impl/pom.xml
catalog/spatial/registry/registry-federation-admin-service-impl/src/main/java/org/codice/ddf/registry/federationadmin/service/impl/FederationAdminServiceImpl.java
distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/CatalogBundle.java
distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/csw/mock/FederatedCswMockServer.java
distribution/test/itests/test-itests-common/src/main/resources/default-csw-mock-delete-transaction-response.xml
distribution/test/itests/test-itests-common/src/main/resources/default-csw-mock-get-capabilities-response.xml
distribution/test/itests/test-itests-common/src/main/resources/default-csw-mock-insert-transaction-response.xml
distribution/test/itests/test-itests-common/src/main/resources/default-csw-mock-update-transaction-response.xml
distribution/test/itests/test-itests-common/src/main/resources/default-csw-registry-query-response.xml
distribution/test/itests/test-itests-common/src/main/resources/registry-csw-mock-insert-transaction-response.xml
distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestRegistry.java

Fixs TestRegistry itests
@shaundmorris
@stustison
Verify Jenkins build passes
DDF-2700

DDF-2700 Fix TestRegistry itests.

---

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/history/Historian.java
catalog/core/catalog-core-versioning/versioning-common/src/main/java/ddf/catalog/core/versioning/impl/DeletedMetacardImpl.java

Excludes Deleted Metacard types from versioning
anyone
@coyotesqrl 
anyone
Build, Run, Ensure in solr there are no versioned metacards that have a metacard.version.tags value of `deleted`
https://codice.atlassian.net/browse/DDF-2694

DDF-2694 Exclude Deleted Metacard Types from Versioning

---

distribution/docs/src/main/resources/_contents/_endpoints/csw-endpoint-contents.adoc
distribution/docs/src/main/resources/_contents/_spatial-contents/integrating-spatial-contents.adoc

Corrects the documentation for the Csw Endpoint GetRecords federation example.
@ricklarsen @bdeining  
@kcwire
@shaundmorris 

DDF-2309 fixed CswEndpoint GetRecords federation documentation

---

catalog/plugin/catalog-plugin-videothumbnail/src/main/java/org/codice/ddf/catalog/content/plugin/video/VideoThumbnailPlugin.java

Fixes broken Alliance build.
@jrnorth 
@pklinef
@jlcsmith 
@stustison

DDF-2733 updated stream handler to consume stream and ignore

---

catalog/transformer/catalog-transformer-tika-input/src/main/java/ddf/catalog/transformer/input/tika/TikaInputTransformer.java
catalog/transformer/catalog-transformer-video-input/pom.xml
catalog/transformer/catalog-transformer-video-input/src/main/java/ddf/catalog/transformer/input/video/VideoInputTransformer.java
catalog/transformer/catalog-transformer-xml/src/main/java/ddf/catalog/transformer/xml/MetacardMarshallerImpl.java
catalog/transformer/catalog-transformer-zip/src/main/java/org/codice/ddf/catalog/transformer/zip/ZipCompression.java
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/workspace/WorkspaceTransformer.java

Remediates findings from static analysis tool. The static analysis tool found instances where streams were not closed explicitly. It is believed that none of the findings posed security risks or memory leaks. In the interest of code hygiene , some instances were converted to using Java 8' try-with-resources features to ensure streams are closed explicitly.
@brendan-hofmann @AzGoalie @vinamartin 
@coyotesqrl
@stustison
Pass all unit and integration tests
None.
[DDF-2716](https://github.com/ahoffer/ddf/tree/DDF-2716)

DDF 2716 Close streams

---

catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.config.xml
distribution/docs/src/main/resources/_contents/_catalog-ui-contents/managing-catalog-ui-contents.adoc
distribution/docs/src/main/resources/_contents/_tables/conf-org.codice.ddf.catalog.ui.config-table-contents.adoc
distribution/docs/src/main/resources/_contents/_tables/conf-org.codice.ddf.catalog.ui.query.monitor.email.EmailNotifier-table-contents.adoc
distribution/docs/src/main/resources/_contents/_tables/conf-org.codice.ddf.catalog.ui.query.monitor.impl.WorkspaceQueryService-table-contents.adoc
distribution/docs/src/main/resources/_contents/_tables/conf-org.codice.ddf.catalog.ui.security-table-contents.adoc
distribution/docs/src/main/resources/_contents/_tables/org.codice.ddf.catalog.ui.config-table-contents.adoc
distribution/docs/src/main/resources/_contents/_tables/org.codice.ddf.catalog.ui.query.monitor.email.EmailNotifier-table-contents.adoc
distribution/docs/src/main/resources/_contents/_tables/org.codice.ddf.catalog.ui.query.monitor.impl.WorkspaceQueryService-table-contents.adoc
distribution/docs/src/main/resources/_contents/_tables/org.codice.ddf.catalog.ui.security-table-contents.adoc
distribution/docs/src/main/resources/draft-documentation.adoc
pom.xml

Adds administrator-level documentation for catalog UI
@andrewkfiedler @rzwiefel @clockard @mcalcote @vinamartin 
@jlcsmith
@kcwire
@pklinef
@stustison
verify content
verify build
[DDF-2651](https://codice.atlassian.net/browse/DDF-2651)
[DDF-2644](https://codice.atlassian.net/browse/DDF-2644)
[draft-documentation.pdf](https://github.com/codice/ddf/files/687820/draft-documentation.pdf)

DDF-2651 added admin docs for catalog ui.

---

catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/SolrProviderTest.java
platform/solr/platform-solr-server-standalone/src/main/resources/solr/conf/schema.xml

fixes sorting on textual fields with multiple words.
@mcalcote 
@brianfelix 
@kcwire
@pklinef
Ingest several files with titles of varying length and multiple words.  Post the following query to the CSW Endpoint and verify the results are sorted alphabetically.
```
<csw:GetRecords xmlns:csw="http://www.opengis.net/cat/csw/2.0.2" xmlns:ogc="http://www.opengis.net/ogc" xmlns:gml="http://www.opengis.net/gml" xmlns:ns4="http://www.w3.org/1999/xlink" xmlns:ns5="http://www.w3.org/2001/SMIL20/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:ows="http://www.opengis.net/ows" xmlns:dct="http://purl.org/dc/terms/" xmlns:ns9="http://www.w3.org/2001/SMIL20/Language" resultType="results" outputFormat="application/xml" …
```

DDF-2726: add alphaNumeric Sort field to solr schema.xml

---

catalog/spatial/geocoding/spatial-geocoding-websearch/src/main/java/org/codice/ddf/spatial/geocoder/geonames/GeoNamesWebService.java
catalog/spatial/geocoding/spatial-geocoding-websearch/src/test/java/org/codice/ddf/spatial/geocoder/geonames/TestGeoNamesWebService.java

This PR adds a catch for the exception thrown when the webservice-gazetteer tries to query the `GeoNamesWebService` when there is no internet connection. This caused ingest to fail.
@peterhuffer @kcwire @clockard 
@kcwire
@shaundmorris
1. Install the `webservice-gazetteer` and `spatial-geocoding-plugin` features.
2. With internet connection
a. Ingest a geolocated metacard*.
b. Confirm that the `location.country-code` attribute is set correctly on the metacard.
3. Without internet connection
a. Disconnect from the internet.
b. Ingest a geolocated metacard*.
c. Confirm that the ingest is successful, and `UnknownHostException` is not logged.
d. Notice that the `location.country-code` attribute is not set on this metacard.
*Note: Metacards …

DDF-2325 Added catch for exception in webservice-gazetteer caused by no internet connection

---

platform/admin/core/admin-core-migration-commands/pom.xml
platform/platform-app/src/main/resources/features.xml
platform/pom.xml
platform/security/interceptor/security-interceptor-logger/pom.xml
platform/security/pom.xml
pom.xml

This PR upgrades Apache Shiro to version 1.3.2.
@clockard @vinamartin 
@shaundmorris
@stustison
Confirm full build succeeds.
[DDF-2717](https://codice.atlassian.net/browse/DDF-2717)

DDF-2717 Upgraded Apache Shiro dependency to 1.3.2

---

catalog/spatial/csw/spatial-csw-source-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/AbstractCswStore.java
catalog/spatial/registry/registry-api-impl/src/main/java/org/codice/ddf/registry/api/impl/RegistryStoreImpl.java
catalog/spatial/registry/registry-federation-admin-service-impl/src/main/java/org/codice/ddf/registry/federationadmin/service/impl/FederationAdminServiceImpl.java
distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestRegistry.java

Added some more checks to ensure everything is set up in time for itests execution
@mcalcote @gordocanchola 
@shaundmorris
@stustison
Verify full build. Ideally the build would pass on jenkins
Previous commit fixed several issues in the itests but on very slow builds there still seems to be some issues even after the initial verification of state. This pr aims to verify state before each operation. 
https://codice.atlassian.net/browse/DDF-2700

DDF-2700 Add some check to fix NPE and add more checks to TestRegistry

---

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/CachingFederationStrategy.java
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/cql/CqlResult.java

Clones responses before caching
anyone
@coyotesqrl 
@jlcsmith 
@pklinef
ensure cached responses have thumbnails and metadata
https://codice.atlassian.net/browse/DDF-2723

DDF-2723 Copy SourceResponses before caching

---

catalog/core/catalog-core-localstorageprovider/src/main/java/org/codice/ddf/catalog/content/impl/FileSystemStorageProvider.java
catalog/core/catalog-core-localstorageprovider/src/main/resources/OSGI-INF/metatype/metatype.xml

This PR closes a stream that was left opened.
@jrnorth 
@jlcsmith
@kcwire
ON WINDOWS : Build / Install / Ingest Data / Delete via REST / Verify `data/content/store` deletes the files appropriately /  Verify Archive and Restore throw no errors
Observed on windows 
[DDF-2727](https://codice.atlassian.net/browse/DDF-2727)

DDF-2727 added try-with-resources to directory stream in catalog-core-localstorageprovider

---

distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/ServiceManagerImpl.java

Minor logging change for better debugging when itests fail.
@figliold @lessarderic 
@stustison
[DDF-2742](https://codice.atlassian.net/browse/DDF-2742)

DDF-2742: Making itest logging fix for better debugging.

---

platform/security/sts/security-sts-ldaplogin/src/main/java/ddf/ldap/ldaplogin/SslLdapLoginModule.java
platform/security/sts/security-sts-ldaplogin/src/test/java/ddf/ldap/ldaplogin/SslLdapLoginModuleTest.java

@coyotesqrl
@pklinef
@stustison

DDF-2747 added check for bad characters

---

catalog/transformer/catalog-transformer-common/pom.xml
catalog/transformer/catalog-transformer-common/src/main/java/ddf/catalog/transformer/common/tika/MetacardCreator.java
catalog/transformer/catalog-transformer-common/src/main/java/ddf/catalog/transformer/common/tika/Mp4MetacardType.java

Follows on the previous Tika transformer improvements to include Mp4 specific attributes.
@clockard @brianfelix @gordocanchola 
@coyotesqrl
@figliold
Confirm build/itests pass.
[DDF-2645](https://codice.atlassian.net/browse/DDF-2645)

DDF-2645 Update Tika transformer and metacard attributes for Mp4 files

---

catalog/ui/catalog-ui-search/src/main/webapp/component/location-old/location-old.hbs
catalog/ui/catalog-ui-search/src/main/webapp/component/location-old/location-old.js
catalog/ui/catalog-ui-search/src/main/webapp/component/location-old/location-old.view.js
catalog/ui/catalog-ui-search/src/main/webapp/js/widgets/cesium.bbox.js
catalog/ui/catalog-ui-search/src/main/webapp/js/widgets/openlayers.circle.js

- Falsy comparisons were being performed on numbers, resulting in bad behavior at 0 (which is seen as false).
@djblue 
@bdeining 
@jlcsmith 
@rzwiefel 
Test out the location searches with 0 values for latitude and longitude.  Verify they update the drawing, as well as save correctly. 
https://codice.atlassian.net/browse/DDF-2734

DDF-2734 Remove incorrect falsy comparisons

---

CHANGES.md
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/config/ConfigurationApplication.java
catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.config.xml
catalog/ui/catalog-ui-search/src/main/webapp/js/model/Query.js
distribution/docs/src/main/resources/_contents/_tables/org.codice.ddf.catalog.ui.config-table-contents.adoc

Adds option to disable the cache when using the catalog ui
@mcalcote @brianfelix 
@figliold
Verify build and the presence of the configuration option.
https://codice.atlassian.net/browse/DDF-2729#### Screenshots (if appropriate)

DDF-2729 Added ability for administrators to disable the use of the cache when using the Catalog UI

---

catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/data/impl/MetacardImpl.java

DDF-2723 added source id to metacard clone ctor
- The clone constructor on MetacardImpl(Metacard, MetacardType) will now
copy the SourceID attribute to cloned metacard
anyone
anyone
ensure source id gets cloned

DDF-2723 added source id to metacard clone ctor

---

catalog/admin/module/catalog-admin-module-sources/package.json
catalog/resourcemanagement/resourcemanagement-querymonitor-ui/package.json
catalog/resourcemanagement/resourcemanagement-usage-ui/package.json
catalog/spatial/geocoding/spatial-geocoding-admin-module/package.json
catalog/spatial/geowebcache/geowebcache-admin-plugin/package.json
catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/package.json
catalog/spatial/registry/registry-admin-modules/registry-admin-remote-ui/package.json
catalog/ui/catalog-ui-search/package.json
catalog/ui/search-ui/standard/package.json
platform/admin/modules/admin-metrics-ui/package.json
platform/admin/modules/admin-security-certificate-ui/package.json
platform/admin/modules/admin-security-ui/package.json
platform/error/platform-error-impl/package.json
platform/security/handler/security-handler-guest/package.json

Updates some js library versions to address node security scan findings.
Npm-shrinkwrap files were deleted in projects where the updates occurred since they will no longer be needed one we switch over to yarn and I can't used the npm shrinkwrap files generated from my machine since it will result in a windows build issue.
@mcalcote @AzGoalie 
@pklinef
Verify build. 
https://codice.atlassian.net/browse/DDF-2730

DDF-2730 Addressed node security scan findings

---

catalog/admin/module/catalog-admin-module-sources/yarn.lock
catalog/resourcemanagement/resourcemanagement-querymonitor-ui/yarn.lock
catalog/resourcemanagement/resourcemanagement-usage-ui/yarn.lock
catalog/spatial/geocoding/spatial-geocoding-admin-module/yarn.lock
catalog/spatial/geowebcache/geowebcache-admin-plugin/yarn.lock
catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/yarn.lock
catalog/spatial/registry/registry-admin-modules/registry-admin-remote-ui/yarn.lock
catalog/ui/catalog-ui-search/yarn.lock
catalog/ui/search-ui/standard/yarn.lock
platform/admin/modules/admin-metrics-ui/yarn.lock
platform/admin/modules/admin-security-certificate-ui/yarn.lock
platform/admin/modules/admin-security-ui/yarn.lock
platform/error/platform-error-impl/yarn.lock
platform/security/handler/security-handler-guest/yarn.lock

Updates the yarn.lock files
@AzGoalie 
@pklinef 
https://github.com/codice/ddf/pull/1595 updated the package.json files to address node security issues but the new yarn.lock files were not updated to match. This pr fixes that.
https://codice.atlassian.net/browse/DDF-2730

DDF-2730 Update yarn.lock files to match updated package.json versions.

---

catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/model/Field.js

This PR fixes an issue where the Lat & Lon were not being verified on the Local Node UI modal.
@clockard @mcalcote
@shaundmorris
@stustison
1. Open an `Add Local Node` modal (`Admin Console` -> `Catalog` -> `Node Information` -> `Additional Local Nodes` -> :heavy_plus_sign:).
2. `Show Advanced` and add a `Custom Field` of type `point`.
Confirm that an error message is displayed for invalid values for `Lat` and/or `Lon`:
3. Confirm that the new `Local Node` cannot be saved by pressing the `Add` button. There should be an error message at the bottom:
4. Confirm that error checking for all other fields was not affected and behaves as expected.
[DDF-2753](https://codice.atlassian.net/browse/DDF-2753)

DDF-2753 Fixed issue that the Lat & Lon were not verified on the Local Node UI modal

---

distribution/docs/src/main/resources/_contents/_data/history-attributes-table-contents.adoc

Updated history attributes to reflect current values.
anyone
@pklinef
https://codice.atlassian.net/projects/DDF/issues/DDF-2737?filter=allopenissues

DDF-2737 Updated History Attributes documentation

---

distribution/docs/src/main/resources/_contents/_running/monitoring-contents.adoc

-Adds in information about how it can be found in the admin console
-Adds in information about the PAUSED and LIVE buttons
@garrettfreibott @ahoffer 
@ricklarsen 
@pklinef 
Verify the documentation is now correct.
[](https://codice.atlassian.net/browse/DDF-2766)

DDF-2770 Updates LogViewer documentation

---

catalog/ui/catalog-ui-search/pom.xml
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/cql/CqlResult.java
catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/query/cql/CqlResultTest.java

Fixes the CqlRequest to handle bad distance values.
@rzwiefel
@shaundmorris
[DDF-2644](https://codice.atlassian.net/browse/)

DDF-2644 Update CqlRequest to handle bad distances in results.

---

libs/httpproxy/proxy-camel-route/src/main/java/org/codice/proxy/http/HttpProxyServiceImpl.java

Shuts down the http proxy routes gracefully instead of taking five minutes to time out.
@Lambeaux 
@vinamartin 
@shaundmorris
@stustison
Install DDF. Hit the search UI and do a search to bring up the globe. `shutdown -f` then `log:tail` and verify there's no camel barf and the system shuts down smoothly and quickly.
[DDF-2768](https://codice.atlassian.net/browse/DDF-2768)

DDF-2768 Gracefully shutdown http proxy routes

---

catalog/spatial/geocoding/spatial-geocoding-lucene/pom.xml
catalog/spatial/geocoding/spatial-geocoding-lucene/src/main/java/org/codice/ddf/spatial/geocoding/query/GeoNamesQueryLuceneDirectoryIndex.java
catalog/spatial/geocoding/spatial-geocoding-lucene/src/test/java/org/codice/ddf/spatial/geocoding/query/GeoNamesQueryLuceneDirectoryIndexTest.java
catalog/spatial/geocoding/spatial-geocoding-websearch/src/main/java/org/codice/ddf/spatial/geocoder/geonames/GeoNamesWebService.java
catalog/spatial/geocoding/spatial-geocoding-websearch/src/test/java/org/codice/ddf/spatial/geocoder/geonames/TestGeoNamesWebService.java
catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/controller/search/QueryRunnable.java
catalog/ui/search-ui/search-endpoint/src/test/java/org/codice/ddf/ui/searchui/query/controller/search/QueryRunnableTest.java

Fix parsing of wkts with intersecting polygons.
@kcwire @jlcsmith 
@pklinef
@stustison
Attempt to ingest <details><summary>this metacard</summary>
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<metacard:metacard xmlns:gml="http://www.opengis.net/gml" xmlns:metacard="urn:catalog:metacard" gml:id="GeometryCollection">
<metacard:type>ddf.metacard</metacard:type>
<metacard:source>test</metacard:source>
<metacard:dateTime name="modified">
<metacard:value>2014-06-04T10:07:05.977-04:00</metacard:value>
</metacard:dateTime>
<metacard:string name="title">
<metacard:value>GeometryCollection</metacard:value>
</metacard:string>
<metacard:dateTime name="created">
<metacard:value>2014-06-04T10:07:05.977-04:00</metacard:value> …
```

DDF-2764 Add allowOverlap to wkt parses

---

catalog/admin/module/catalog-admin-module-sources/src/main/webapp/js/view/Source.view.js
catalog/admin/module/catalog-admin-module-sources/src/main/webapp/js/view/Utils.js
catalog/admin/module/catalog-admin-module-sources/src/main/webapp/less/styles.less
catalog/admin/module/catalog-admin-module-sources/src/main/webapp/templates/sourceList.handlebars
catalog/admin/module/catalog-admin-module-sources/src/main/webapp/templates/sourcePage.handlebars
catalog/admin/module/catalog-admin-module-sources/src/main/webapp/templates/sourceRow.handlebars

Limits the size of the bindingUrl column introduced in #1524 
If max size is exceeded overflow is hidden and an ellipsis is displayed.
@lessarderic 
@Lambeaux 
@codice/ui 
@figliold 
@pklinef 
[DDF-2671](https://codice.atlassian.net/browse/DDF-2671)

DDF-2671: Added length limit to source bindingUrl column

---

CHANGES.md

Updates changelog. 
@coyotesqrl
@figliold
@jaymcnallie
@jlcsmith
@kcwire
@lessarderic
@pklinef
@shaundmorris
@stustison
review content
Add any items to add to checklist as comments here. 

DDF-2748 updated changelog for 2.10.0 release.

---

catalog/schematron/catalog-schematron-plugin/src/main/java/ddf/services/schematron/SchematronValidationService.java

Condition causes all schematron validators to run on any metadata. Fixes that.
@ahoffer 
@coyotesqrl
@stustison

DDF-2769 Fixed condition to determine whether to run SchematronValidation in SchematronValidationService

---

catalog/spatial/geocoding/spatial-geocoding-plugin/src/main/java/org/codice/ddf/spatial/geocoding/plugin/GeoCoderPlugin.java

When ingesting large numbers of metacards there was the potential for a thread conflict on the GeoCoder when the country code was being set in the GeoCoderPlugin. This change removes the global GeoCoder instance in favor of a new instance for each operation.
@clockard @emmberk @peterhuffer @vinamartin 
@coyotesqrl
@pklinef
Ingest a large dataset using the ddf console and confirm the process does not encounter any issues.
Please see me for ingest suggestions.
[DDF-2325](https://codice.atlassian.net/browse/DDF-2325)

DDF-2325 Adjust GeoCoderPlugin to avoid thread conflict when evaluating metacard country code

---

catalog/ui/catalog-ui-search/src/main/webapp/js/model/Metacard.js

Backport of https://github.com/codice/ddf/pull/1664
@andrewkfiedler @pklinef

DDF-2787- Updates how thumbnail action url is generated

---

platform/admin/core/admin-core-api/src/main/java/org/codice/ddf/ui/admin/api/GuestClaimsHandlerExt.java
platform/admin/core/admin-core-api/src/test/java/org/codice/ddf/ui/admin/api/GuestClaimsHandlerExtTest.java

See 2nd commit of https://github.com/codice/ddf/pull/1515

DDF-2640 Fix DDF Installer

---

catalog/ui/catalog-ui-search/src/main/webapp/js/ApplicationStart.js

Backport https://github.com/codice/ddf/pull/1649
@pklinef

DDF-2781 Update app to start only after initial user fetch

---

catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/util/impl/CachedSource.java
catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/util/impl/SourcePollerRunner.java
platform/security/pep/security-pep-interceptor/src/main/java/ddf/security/pep/interceptor/PEPAuthorizingInterceptor.java

@coyotesqrl
@pklinef
@stustison

DDF-2788, DDF-2789

---

catalog/core/catalog-core-actions/src/main/java/org/codice/ddf/catalog/actions/AbstractMetacardActionProvider.java
catalog/core/catalog-core-actions/src/test/java/org/codice/ddf/catalog/actions/AbstractMetacardActionProviderTest.java
catalog/rest/catalog-rest-endpoint/src/test/java/org/codice/ddf/endpoints/rest/action/TestMetacardTransformerActionProvider.java
catalog/rest/catalog-rest-endpoint/src/test/java/org/codice/ddf/endpoints/rest/action/TestViewMetacardActionProvider.java
catalog/spatial/registry/registry-ebrim-transformer/src/main/resources/OSGI-INF/blueprint/blueprint.xml

Backport for https://github.com/codice/ddf/pull/1642
@mcalcote @gordocanchola 
@figliold 
@pklinef
[DDF-2775](https://codice.atlassian.net/browse/)

DDF-2775 - Backport - Update to ensure actions displayed in the catalog/search ui are appropriate for the metacards tag

---

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/CacheQueryFactory.java
catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/CacheSolrMetacardClient.java
catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/CachingFederationStrategy.java
catalog/core/catalog-core-standardframework/src/main/resources/OSGI-INF/blueprint/fedstrategy.xml
distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFederation.java

Fix caching in CachingFederationStrategy for real this time without breaking enterprise query.
@pklinef
@shaundmorris
Verify itests pass for ddf and upstream projects
[DDF-2612](https://codice.atlassian.net/browse/)

DDF-2612 Fix caching in CachingFederationStrategy.

---

platform/security/idp/security-idp-client/src/main/java/org/codice/ddf/security/idp/client/IdpHandler.java

	DDF-2798 fixed possible null pointers

---

libs/httpproxy/proxy-camel-route/src/main/java/org/codice/proxy/http/HttpProxyServiceImpl.java

DDF-2797 fixed exception from modifying list inside loop

---

distribution/docs/src/main/resources/_contents/_securing/managing-certificates-contents.adoc
distribution/docs/src/main/resources/_contents/_sources/confluence-federated-source-contents.adoc
distribution/docs/src/main/resources/_contents/_sources/federated-sources-contents.adoc
distribution/docs/src/main/resources/documentation.adoc

updates federated sources to include confluence source docs.
@Lambeaux @vinamartin @mcalcote @jrnorth @ahoffer @clockard 
@coyotesqrl
@pklinef
@shaundmorris
Verify confluence docs present in docs.
[DDF-2802](https://codice.atlassian.net/browse/DDF-2802)
[documentation.pdf](https://github.com/codice/ddf/files/781404/documentation.pdf)

DDF-2802 fix for confluence source docs

---

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/CacheQueryFactory.java
catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/CacheSolrMetacardClient.java
catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/CachingFederationStrategy.java
catalog/core/catalog-core-standardframework/src/main/resources/OSGI-INF/blueprint/fedstrategy.xml
distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFederation.java

Backport for DDF-2612 - Fix caching in CachingFederationStrategy
@pklinef
@shaundmorris
https://github.com/codice/ddf/pull/1653
[DDF-2612](https://codice.atlassian.net/browse/)

DDF-2612 -Backport - Fix caching in CachingFederationStrategy. (#1653)

---

distribution/docs/src/main/resources/_contents/_securing/environment-hardening-contents.adoc

Added a row to the Environment Hardening suggestions that describes how to update the Session Timeout to the recommended 10 minutes.
@ricklarsen @ahoffer 
[Docs](https://github.com/orgs/codice/teams/docs) @Lambeaux 
@shaundmorris
@stustison
Read the changes, observe the generated table.
[DDF-2804](https://codice.atlassian.net/browse/DDF-2804)
(PDF)

DDF-2804 Update hardening guide to recommend 10 minute session timeout

---

platform/security/policy/security-policy-context/src/main/java/org/codice/ddf/security/policy/context/impl/PolicyManager.java
platform/security/policy/security-policy-context/src/main/resources/OSGI-INF/blueprint/blueprint.xml
platform/security/policy/security-policy-context/src/main/resources/OSGI-INF/metatype/metatype.xml
platform/security/policy/security-policy-context/src/test/java/org/codice/security/policy/context/PolicyManagerTest.java

@coyotesqrl @brendan-hofmann 
@pklinef
@stustison

	DDF-2809 fixed issue with extremely long paths or badly formed paths

---

catalog/spatial/geowebcache/geowebcache-app/pom.xml

Updates the geowebcache version
@bdeining 
@jlcsmith
@kcwire
Depends on https://github.com/codice/geowebcache-osgi/pull/2 getting merged first
[DDF-2810](https://codice.atlassian.net/browse/)

DDF-2810 Upgrade GeoWebCache from 0.6 to 0.7.0

---

catalog/spatial/geowebcache/geowebcache-app/pom.xml

Updates the geowebcache version
@bdeining 
@jlcsmith
@kcwire
https://github.com/codice/ddf/pull/1701
[DDF-2810](https://codice.atlassian.net/browse/)

DDF-2810 -Backport- Upgrade GeoWebCache from 0.6 to 0.7.0

---

catalog/ui/catalog-ui-search/src/main/webapp/js/CQLUtils.js
catalog/ui/catalog-ui-search/src/main/webapp/js/widgets/cesium.polygon.js

- Polygons are meant to be a closed shape, so we were adding on the beginning point to the end.  However, we didn't check to see if we had already done so in the past.
@emanns95 
@codymacdonald
@djblue 
@figliold 
Draw a polygon.  Save it.  Check how many points.  Edit, save, edit, save.  Check how many points.  Number of points should not change.  
Add an end or beginning point to an existing polygon.  Save.  Check to make sure we closed the polygon off.  
https://codice.atlassian.net/browse/DDF-2785

DDF-2785 Prevents duplicate points from being added onto the ends of polygons

---

catalog/spatial/csw/spatial-csw-source/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/spatial/wfs/1.0.0/spatial-wfs-v1_0_0-source/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/main/resources/OSGI-INF/blueprint/blueprint.xml

This is a backport of changes here https://github.com/codice/ddf/pull/1630
@bdeining @peterhuffer 
@jlcsmith
@kcwire
[DDF-2765](https://codice.atlassian.net/browse/)

DDF-2765 CSW and WFS forceSpatialFilter should default to NO_FILTER instead of null

---

distribution/docs/src/main/resources/_contents/_running/starting-intro-contents.adoc

Their were some issues when I ran through these steps I ordered them a bit different and fixed the JVM args.
@jrnorth 
@Lambeaux 
@ricklarsen 
@lessarderic 
@shaundmorris

DDF-2360 Fix starting DDF as a service docs

---

catalog/ui/catalog-ui-search/src/main/webapp/component/sort-item/sort-item.view.js
catalog/ui/catalog-ui-search/src/main/webapp/component/visualization/table/thead.view.js
catalog/ui/catalog-ui-search/src/main/webapp/js/model/Metacard.js

backport of https://github.com/codice/ddf/pull/1674

(2.10.x) DDF-2792 Update client side sorting to handle null / blank values more consistently

---

catalog/opensearch/catalog-opensearch-endpoint/src/main/java/org/codice/ddf/endpoints/OpenSearchEndpoint.java

DDF-2824 Fix some typos in a comment in OpenSearchEndpoint

---

catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/SolrFilterDelegate.java
catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/SolrFilterDelegateTest.java

Port for https://github.com/codice/ddf/pull/1729
@lessarderic
@shaundmorris
Verify unit and itests pass
[DDF-2814](https://codice.atlassian.net/browse/DDF-2814)

DDF-2814 -Port- Fix SolrFilterDelegate to not convert polygons into simpler shapes

---

pom.xml

Upgrades to latest version of Yarn to get [this lockfile fix](https://github.com/yarnpkg/yarn/pull/2663).
Also switches to network mutex.
@djblue @AzGoalie 
@shaundmorris
@stustison
This is a build-time issue, not a production issue, so a full build and test run should be sufficient.
N/A
[DDF-2833](https://codice.atlassian.net/browse/DDF-2833)
N/A

DDF-2833 Upgrades to latest version of yarn to get lockfile fix.

---

pom.xml

Upgrades to latest version of Yarn to get [this lockfile fix](https://github.com/yarnpkg/yarn/pull/2663).
Also switches to network mutex.
@djblue @AzGoalie 
@shaundmorris
@stustison
This is a build-time issue, not a production issue, so a full build and test run should be sufficient.
N/A
[DDF-2833](https://codice.atlassian.net/browse/DDF-2833)
N/A

DDF-2833 [2.10.x] Upgrades to latest version of yarn for lockfile fix.

---

catalog/core/catalog-core-directorymonitor/src/main/resources/OSGI-INF/metatype/metatype.xml
distribution/ddf-common/src/main/resources/bin/setenv
distribution/ddf-common/src/main/resources/bin/setenv.bat
distribution/docs/src/main/resources/_contents/_installing/installing-intro-contents.adoc
distribution/docs/src/main/resources/_contents/_quickstart/quickstart-installing-contents.adoc
distribution/docs/src/main/resources/_contents/_running/starting-intro-contents.adoc
distribution/docs/src/main/resources/_contents/_tables/org.codice.ddf.catalog.content.monitor.ContentDirectoryMonitor-table-contents.adoc

Increase default JVM memory to 4096MB
@ricklarsen @emmberk @mcalcote 
@coyotesqrl
@figliold
[DDF-2826](https://codice.atlassian.net/browse/DDF-2826)

DDF-2826 Increase default JVM memory to 4096MB

---

catalog/ui/catalog-ui-search/pom.xml
platform/admin/modules/admin-modules-docs/pom.xml
pom.xml

Upgrade Spark from 2.5 to 2.5.5
@vinamartin @tbatie 
@coyotesqrl
Verify build passes and Catalog UI and Admin Documentation UI work normally
[DDF-2836](https://codice.atlassian.net/browse/DDF-2836)

DDF-2836 Upgrade Spark from 2.5 to 2.5.5

---

catalog/ui/catalog-ui-search/src/main/webapp/component/dropdown/dropdown.hbs
catalog/ui/catalog-ui-search/src/main/webapp/component/dropdown/dropdown.less
catalog/ui/catalog-ui-search/src/main/webapp/component/input/bulk/input-bulk.hbs
catalog/ui/catalog-ui-search/src/main/webapp/component/input/bulk/input-bulk.less
catalog/ui/catalog-ui-search/src/main/webapp/component/input/bulk/input-bulk.view.js
catalog/ui/catalog-ui-search/src/main/webapp/component/input/input.hbs
catalog/ui/catalog-ui-search/src/main/webapp/component/input/input.less
catalog/ui/catalog-ui-search/src/main/webapp/component/property/property.hbs
catalog/ui/catalog-ui-search/src/main/webapp/component/select/select.collection.view.js
catalog/ui/catalog-ui-search/src/main/webapp/component/select/select.hbs
catalog/ui/catalog-ui-search/src/main/webapp/component/select/select.less
catalog/ui/catalog-ui-search/src/main/webapp/component/select/select.view.js
catalog/ui/catalog-ui-search/src/main/webapp/component/visualization/table/row.hbs
catalog/ui/catalog-ui-search/src/main/webapp/component/visualization/table/row.less
catalog/ui/catalog-ui-search/src/main/webapp/component/visualization/table/row.view.js
catalog/ui/catalog-ui-search/src/main/webapp/component/visualization/table/thead.hbs
catalog/ui/catalog-ui-search/src/main/webapp/component/visualization/table/thead.less
catalog/ui/catalog-ui-search/src/main/webapp/css/searchPage.css
catalog/ui/catalog-ui-search/src/main/webapp/js/HandlebarsHelpers.js
catalog/ui/catalog-ui-search/src/main/webapp/less/components/init.less
catalog/ui/catalog-ui-search/src/main/webapp/less/components/links.less
catalog/ui/catalog-ui-search/src/main/webapp/less/vars.less

backport of https://github.com/codice/ddf/pull/1727

DDF-2816 Update attribute views to convert link-like values to links

---

catalog/core/catalog-core-directorymonitor/src/main/resources/OSGI-INF/metatype/metatype.xml
distribution/ddf-common/src/main/resources/bin/setenv
distribution/ddf-common/src/main/resources/bin/setenv.bat
distribution/docs/src/main/resources/_contents/_installing/installing-intro-contents.adoc
distribution/docs/src/main/resources/_contents/_quickstart/quickstart-installing-contents.adoc
distribution/docs/src/main/resources/_contents/_running/starting-intro-contents.adoc
distribution/docs/src/main/resources/_contents/_tables/org.codice.ddf.catalog.content.monitor.ContentDirectoryMonitor-table-contents.adoc

Port of https://github.com/codice/ddf/pull/1718
@coyotesqrl
@figliold
[DDF-2826](https://codice.atlassian.net/browse/DDF-2826)

DDF-2826 -Port- Increase default JVM memory to 4096MB (#1718)

---

distribution/ddf-common/src/main/resources/etc/system.properties
platform/security/platform-security-core-api/pom.xml
platform/security/platform-security-core-api/src/main/java/ddf/security/common/audit/SecurityLogger.java

encode \r and \n by default and encode other characters if system property is set
@ahoffer @clockard 
@coyotesqrl 
@stustison

DDF-2821 encode special characters in audit messages

---

CHANGES.md
catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/solr/FilteringSolrIndex.java
distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestSolrCommands.java
platform/pom.xml
platform/solr/platform-solr-server-standalone/pom.xml
platform/solr/platform-solr-server-standalone/src/main/resources/solr/conf/solrconfig-inmemory.xml
platform/solr/platform-solr-server-standalone/src/main/resources/solr/conf/solrconfig.xml
platform/solr/solr-dependencies/pom.xml
platform/solr/solr-factory/src/main/java/org/codice/solr/factory/impl/EmbeddedSolrFactory.java
platform/solr/solr-factory/src/main/java/org/codice/solr/factory/impl/SolrCoreContainer.java
platform/solr/solr-xpath/pom.xml
platform/solr/solr-xpath/src/main/java/org/codice/solr/xpath/XpathQueryParser.java
pom.xml

Upgrades Solr to version 6.4.1
@lessarderic
@pklinef
@shaundmorris
Hero build and manual test.  For the manual tests, configure DDF the following ways using system.properties:
1) External provider
2) Cloud provider
3) Embedded provider
https://codice.atlassian.net/browse/DDF-2818

DDF-2818: Upgrade Solr to version 6.4.1

---

catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/solr/FilteringSolrIndex.java
distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestSolrCommands.java
platform/pom.xml
platform/solr/platform-solr-server-standalone/pom.xml
platform/solr/platform-solr-server-standalone/src/main/resources/solr/conf/solrconfig-inmemory.xml
platform/solr/platform-solr-server-standalone/src/main/resources/solr/conf/solrconfig.xml
platform/solr/solr-dependencies/pom.xml
platform/solr/solr-factory/src/main/java/org/codice/solr/factory/impl/EmbeddedSolrFactory.java
platform/solr/solr-factory/src/main/java/org/codice/solr/factory/impl/SolrCoreContainer.java
platform/solr/solr-xpath/pom.xml
platform/solr/solr-xpath/src/main/java/org/codice/solr/xpath/XpathQueryParser.java
pom.xml

Upgrades Solr to version 6.4.1 in 2.10.x
@clockard 
@stustison
@pklinef
@shaundmorris
@stustison
Hero build
https://codice.atlassian.net/browse/DDF-2818

DDF-2818: (2.10.x backport) Upgrade Solr to version 6.4.1 

---

platform/metrics/platform-metrics-collector/src/main/java/ddf/metrics/collector/rrd4j/RrdJmxCollector.java
platform/metrics/platform-metrics-reporting/src/main/java/ddf/metrics/reporting/internal/rest/MetricsEndpoint.java

This PR fixes Platform Metrics on Windows
@tbatie @glenhein 
@emanns95 
@jlcsmith
@kcwire
Build / Install on WINDOWS / Verify Metrics file location and Endpoint Behavior
[DDF-2304](https://codice.atlassian.net/browse/DDF-2304)

(2.10.x) DDF-2304 Fixed "data/metrics" paths on Windows

---

platform/metrics/platform-metrics-collector/src/main/java/ddf/metrics/collector/rrd4j/RrdJmxCollector.java
platform/metrics/platform-metrics-reporting/src/main/java/ddf/metrics/reporting/internal/rest/MetricsEndpoint.java

This PR fixes Platform Metrics on Windows
@tbatie @glenhein 
@emanns95 
@jlcsmith
@kcwire
Build / Install on WINDOWS / Verify Metrics file location and Endpoint Behavior
[DDF-2304](https://codice.atlassian.net/browse/DDF-2304)

DDF-2304 Fixed "data/metrics" paths on Windows

---

CHANGES.md
distribution/ddf-common/src/main/resources/etc/system.properties
distribution/docs/src/main/resources/_contents/_configuring/configuring-global-settings-contents.adoc
platform/util/platform-util-unavailableurls/pom.xml
platform/util/platform-util-unavailableurls/src/main/java/org/codice/ddf/platform/util/http/UnavailableUrls.java
platform/util/platform-util-unavailableurls/src/test/java/org/codice/ddf/platform/util/http/UnavailableUrlsTest.java

###What does this PR do?
Port of https://github.com/codice/ddf/pull/1725 to 2.10.x
@coyotesqrl
@stustison
Run unit and integration tests.
Timeout behavior may have been responsible for itest failures and federation problems.
[DDF-2831](https://codice.atlassian.net/browse/DDF-2831)

DDF-2831 Change retry interval for unavailable endpoints

---

CHANGES.md
catalog/spatial/csw/spatial-csw-endpoint/pom.xml
catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java
catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/mappings/CswRecordMapperFilterVisitor.java
catalog/spatial/csw/spatial-csw-endpoint/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/mappings/TestCswRecordMapperFilterVisitor.java
catalog/spatial/wfs/1.0.0/spatial-wfs-v1_0_0-source/pom.xml
catalog/spatial/wfs/1.0.0/spatial-wfs-v1_0_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v1_0_0/catalog/source/WfsFilterDelegate.java
catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-converter/src/main/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/converter/impl/AbstractFeatureConverterWfs20.java
catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-converter/src/test/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/converter/impl/TestGenericFeatureConverter.java
catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/pom.xml
catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/source/WfsFilterDelegate.java
catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/source/WfsSource.java
catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/source/TestWfsFilterDelegate.java
catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/source/TestWfsSource.java
catalog/spatial/wfs/spatial-wfs-common/src/main/java/org/codice/ddf/spatial/ogc/wfs/catalog/common/WfsConstants.java
catalog/spatial/wfs/spatial-wfs-converter/pom.xml
catalog/spatial/wfs/spatial-wfs-converter/src/main/java/org/codice/ddf/spatial/ogc/wfs/catalog/converter/impl/AbstractFeatureConverter.java
catalog/spatial/wfs/spatial-wfs-source/pom.xml
distribution/docs/src/main/resources/_contents/_endpoints/csw-endpoint-contents.adoc
distribution/test/itests/test-itests-common/src/main/resources/csw/request/CswQueryWithUtmIntersect
distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalog.java
libs/geospatial/pom.xml
libs/geospatial/src/main/java/org/codice/ddf/libs/geo/util/GeospatialUtil.java
libs/geospatial/src/test/java/org/codice/ddf/libs/geo/GeoUtilTest.java

Adds UTM coordinate support for OGC Filters in the CSW endpoint.
@bdeining 
@rzwiefel 
@ricklarsen 
@kcwire
@millerw8
Build & Run Unit Tests and Itests
With postman, POST the following to the CSW endpoint and verify no exceptions are returned:
`https://localhost:8993/services/csw`
`<?xml version="1.0" ?>
<GetRecords xmlns="http://www.opengis.net/cat/csw/2.0.2"
xmlns:ogc="http://www.opengis.net/ogc"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xmlns:gml="http://www.opengis.net/gml"
service="CSW"
version="2.0.2"
maxRecords="4"
startPosition="1"
resultType="results"
outputFormat="application/xml"
outputSchema="http://www.opengis.net/cat/csw/2.0.2"
xsi:schemaLocation="http://www.opengis.net/cat/csw/2.0.2 …

DDF-2815: Add UTM coordinate support to CSW endpoint

---

catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswQueryFactory.java
catalog/spatial/csw/spatial-csw-endpoint/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/spatial/csw/spatial-csw-endpoint/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswQueryFactoryTest.java

Allows non standard csw attributes to be sorted on (like effective date).
@clockard @emanns95 @kcwire  
@coyotesqrl
@pklinef

DDF-2835: Fixed CSW sortby
