distribution/docs/src/main/resources/_contents/_installing/controlling-file-system-access-contents.adoc
the /instances directory most likely doesn't exist at this point in the instructions so it needs to be created before it can be chgrp/chmod
@jrnorth 
@clockard 
@ricklarsen 
@jaymcnallie
@shaundmorris
=> DDF-2360 fix directory permissions docs for linux

distribution/docs/src/main/resources/_contents/_running/starting-intro-contents.adoc
Backport of https://github.com/codice/ddf/pull/1749
@bdeining @brendan-hofmann 
@kcwire 
=> (2.10.x) DDF-2360 Corrected instructions for DDF heap setting in windows service wrapper

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/MetacardApplication.java
see title
anyone
@jlcsmith
@kcwire or @andrewkfiedler
manually insert bad data into workspace queries field of metacard. Ensure UI still functions and bad data workspace is filtered out. 
https://codice.atlassian.net/browse/DDF-2811
=> DDF-2811 Workspace fetches now silently hide bad data

catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswQueryFactory.java, catalog/spatial/csw/spatial-csw-endpoint/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/spatial/csw/spatial-csw-endpoint/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswQueryFactoryTest.java
Quick fix to allow csw queries to search when the sortby property isn't defined in the csw output schema.
@ahoffer @emanns95 
@coyotesqrl
@pklinef
Ingest some data and create a CSW endpoint and query it using 'effective' as the sort by property.
Verify that results are returned.
=> DDF-2835: Quick fix for CSW sortby

catalog/transformer/catalog-transformer-xml/src/main/java/ddf/catalog/transformer/xml/MetacardMarshallerImpl.java
Before this change it was possible in edge cases to get an error trying to generate xml output using some of the Catalog UI action providers. This change addresses the potential issue.
@clockard @emmberk @brianfelix @gordocanchola 
@coyotesqrl
@shaundmorris 
Ingest a product into the DDF and use the action providers. Please see me for the specific instance that led to finding this issue.
[DDF-2837](https://codice.atlassian.net/browse/DDF-2837)
=> DDF-2837 Adjusted marshaller logic to account for attributes with null values

distribution/docs/src/main/resources/_contents/_installing/controlling-file-system-access-contents.adoc, distribution/docs/src/main/resources/_contents/_running/starting-intro-contents.adoc
cherry pick dock change from 2.10 
@clockard 
@jrnorth 
@ricklarsen 
@lessarderic
@stustison
=> DDF-2360 Fix starting DDF as a service docs (#1715)

distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/AbstractIntegrationTest.java, distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/security/SecurityPolicyConfigurator.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalog.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalogSearchUi.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestEmbeddedSolr.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFanout.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFederation.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFtp.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestRegistry.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestSpatial.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestConfiguration.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestPlatform.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestSecurity.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestSingleSignOn.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestSolrCommands.java, platform/security/idp/security-idp-client/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/security/idp/security-idp-client/src/main/resources/OSGI-INF/metatype/metatype.xml, platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/server/IdpEndpoint.java, platform/security/idp/security-idp-server/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/security/idp/security-idp-server/src/main/resources/OSGI-INF/metatype/metatype.xml, platform/security/idp/security-idp-server/src/main/resources/templates/login.handlebars, platform/security/platform-security-core-api/pom.xml, platform/security/platform-security-core-api/src/main/java/ddf/security/samlp/MetadataConfigurationParser.java, platform/security/policy/security-policy-context/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/security/policy/security-policy-context/src/main/resources/OSGI-INF/metatype/metatype.xml, platform/security/security-services-app/src/main/resources/features.xml
@tbatie @ahoffer @brendan-hofmann @coyotesqrl 
@pklinef
@stustison
=> DDF-2827 switched the default authentication mechanism to the IdP

catalog/transformer/catalog-transformer-xml/src/main/java/ddf/catalog/transformer/xml/MetacardMarshallerImpl.java
Before this change it was possible in edge cases to get an error trying to generate xml output using some of the Catalog UI action providers. This change addresses the potential issue.
@clockard @emmberk @brianfelix @gordocanchola
@coyotesqrl
@shaundmorris 
Ingest a product into the DDF and use the action providers. Please see me for the specific instance that led to finding this issue.
This changes was previously merged in the 2.10.x branch: https://github.com/codice/ddf/pull/1762
[DDF-2837](https://codice.atlassian.net/browse/DDF-2837)
=> DDF-2837 Adjusted marshaller logic to account for attributes with null values.

catalog/ui/catalog-ui-search/server.js
- Had to remove x-xss-protection header in order to allow logins
@djblue
@coyotesqrl
Start grunt proxy. Ensure you can login through grunt proxy
https://codice.atlassian.net/browse/DDF-2864
=> DDF-2864 Fixed grunt proxy login

distribution/docs/src/main/resources/_contents/_using/using-catalog-search-ui-contents.adoc, platform/security/platform-security-core-api/pom.xml, platform/security/platform-security-core-api/src/main/java/ddf/security/SubjectUtils.java, platform/security/platform-security-core-api/src/test/java/ddf/security/SubjectUtilsTest.java
Adds utility functionality to extract claims from a Subject
Also makes a small, unrelated docs change.
@AzGoalie @garrettfreibott @ricklarsen 
@coyotesqrl
@stustison
CI build sufficient.
N/A
[DDF-2852](https://codice.atlassian.net/browse/DDF-2852)
=> DDF-2852 Add functionality for retrieving a logged-in user's security claims

distribution/docs/src/main/resources/_contents/_using/using-catalog-search-ui-contents.adoc, platform/security/platform-security-core-api/pom.xml, platform/security/platform-security-core-api/src/main/java/ddf/security/SubjectUtils.java, platform/security/platform-security-core-api/src/test/java/ddf/security/SubjectUtilsTest.java
Adds utility functionality to extract claims from a Subject
Also makes a small, unrelated docs change.
@AzGoalie @garrettfreibott @ricklarsen 
@coyotesqrl
@stustison
CI build sufficient.
N/A
[DDF-2852](https://codice.atlassian.net/browse/DDF-2852)
=> DDF-2852 [2.10.x] Add functionality for retrieving a logged-in user's security claims

CHANGES.md
updates changelog for 2.10.1 release
@mcalcote @Lambeaux @jrnorth 
@coyotesqrl
@figliold
@lessarderic
@pklinef
@shaundmorris
@stustison
Preview changes at https://github.com/ricklarsen/ddf/blob/DDF-2748/CHANGES.md
Seeking additional tasks completed/notes to add. Leave as a comment on this PR for inclusion.
=> DDF-2748 updated changelog

Documentation-versions.html
replaces documentation.html and documentation.pdf with latest release version (2.10.1).
@coyotesqrl
@pklinef
@shaundmorris
verify version updated on documentation pages and Documentation-versions.html
n/a
=> DDF-2748 update codice.org/ddf docs to 2.10.1

distribution/docs/src/main/resources/_contents/_installing/installing-intro-contents.adoc
Update the documentation to give users some idea of the hardware requirements for running DDF.
@clockard @emmberk @brianfelix @vinamartin 
[Docs](https://github.com/orgs/codice/teams/docs) @ricklarsen 
@lessarderic
@stustison
Build Docs, Review text in Section 13.1 Installation Prerequisites
These specs are rough estimates, please comment on this PR with your thoughts.
[DDF-2856](https://codice.atlassian.net/browse/DDF-2856)
Updated Screenshot (3/13/17 4:15PM)
=> DDF-2856 Updated Installation Prerequisites to include Hardware Guidelines

catalog/ui/catalog-ui-search/src/main/webapp/component/component.less, catalog/ui/catalog-ui-search/src/main/webapp/component/input/range/input-range.hbs, catalog/ui/catalog-ui-search/src/main/webapp/component/input/range/input-range.less, catalog/ui/catalog-ui-search/src/main/webapp/component/input/range/input-range.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/property/property.js, catalog/ui/catalog-ui-search/src/main/webapp/component/property/property.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/search-settings/search-settings.hbs, catalog/ui/catalog-ui-search/src/main/webapp/component/search-settings/search-settings.less, catalog/ui/catalog-ui-search/src/main/webapp/component/search-settings/search-settings.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/theme-settings/theme-settings.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/user-settings/user-settings.hbs, catalog/ui/catalog-ui-search/src/main/webapp/component/user-settings/user-settings.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/value/value.view.js, catalog/ui/catalog-ui-search/src/main/webapp/js/model/Query.js, catalog/ui/catalog-ui-search/src/main/webapp/js/model/User.js, catalog/ui/catalog-ui-search/src/main/webapp/less/components/input.less, catalog/ui/catalog-ui-search/src/main/webapp/less/components/range-input.less
DDF-2848: Allows the user to control the maximum number of query results that they wish to view.
@bdeining 
@rzwiefel 
@millerw8
Ingest test some test records into the catalog (> the max result count).
1. Launch Admin UI -> Search UI Config -> Change Result Count to 300
2. Launch Catalog UI
3. Click Configuration Gear
4. Click Query
5. Attempt to change result to something more than what was configured in step 1, and verify that it's reset to the max in step 1.
6. Attempt to change the count to < 1, verify that it's reset to 1 as a minimum
7. Configure to some amount less than the max count (e.g. 200).
8. Create a search for everything and view results. Verify that only the amount in step 7 are returned.
9. Click the …
=> DDF-2848: User preference for query results, support 1 to max size configured in the admin UI.

catalog/ui/catalog-ui-search/src/main/webapp/component/result-item/result-item.hbs, catalog/ui/catalog-ui-search/src/main/webapp/js/HandlebarsHelpers.js
- Added a helper to handlebars to resolve attribute aliases.
@clockard 
@pklinef 
Add an alias to the admin config for an attribute in the Catalog UI.  Verify that it gets resolved correctly when using the help view.  In addition, add some attributes to the result preview and verify aliases for those get resolved correctly.
https://codice.atlassian.net/browse/DDF-2845
=> DDF-2845 Update result list help text to reflect attribute aliases

catalog/ui/catalog-ui-search/src/main/webapp/component/result-item/result-item.hbs, catalog/ui/catalog-ui-search/src/main/webapp/js/HandlebarsHelpers.js
backport of https://github.com/codice/ddf/pull/1756
=> (2.10.x) DDF-2845 Update result list help text to reflect attribute aliases

CHANGES.md
backports Changelog updates
@coyotesqrl
@jlcsmith
@pklinef
@shaundmorris
Verify changelog (CHANGES.md)
=> DDF-2748 backport of changelog

catalog/spatial/geocoding/spatial-geocoding-admin-module/package.json, catalog/spatial/geocoding/spatial-geocoding-admin-module/yarn.lock, libs/libs-pomfix/package.json, libs/libs-pomfix/yarn.lock, platform/security/servlet/security-servlet-logout/package.json, platform/security/servlet/security-servlet-logout/yarn.lock
Removes version range markings in package.json files and includes the updated yarn.lock files.
@ahoffer @AzGoalie @emanns95 @djblue 
@pklinef
@stustison
Run full build, then verify that catalog ui and log viewer works.
Important for ensuring control over the version used for each dependency.
[](https://codice.atlassian.net/browse/DDF-2846)
=> DDF-2846 [Backport] Remove version range from package.json for web apps

catalog/pom.xml, platform/platform-app/pom.xml, platform/platform-app/src/main/resources/features.xml, platform/pom.xml, platform/usng4j/platform-usng4j-api/pom.xml, platform/usng4j/platform-usng4j-impl/pom.xml, platform/usng4j/platform-usng4j-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/usng4j/pom.xml, pom.xml
**This PR should not be merged until Codice USNG4J has been officially released.**
-Exports the CoordinateSystemTranslator interface from Codice Usng4j as a an OSGI service.
-This service provides a utility to convert coordinates between various coordinate systems. 
-The service is packaged within an API and Implementation bundle and is accessible via the platform-usng4j feature.
@dcruver 
@stustison 
@jaymcnallie
@pklinef
Run a full clean build.
[DDF-2841](https://codice.atlassian.net/browse/DDF-2841)
=> DDF-2841 Export Usng4j interface as an OSGI service

platform/security/platform-security-core-api/src/main/java/ddf/security/samlp/MetadataConfigurationParser.java
Fixes SP/IdP metadata parsing
@harrison-tarr @vinamartin 
@coyotesqrl 
@stustison
=> DDF-2895 added IOException handler so that exceptions can be backed off just like unsuccessful attempts

catalog/spatial/geocoding/spatial-geocoding-admin-module/package.json, catalog/spatial/geocoding/spatial-geocoding-admin-module/yarn.lock, libs/libs-pomfix/package.json, libs/libs-pomfix/yarn.lock, platform/security/servlet/security-servlet-logout/package.json, platform/security/servlet/security-servlet-logout/yarn.lock
Removes version range markings in package.json files and includes the updated yarn.lock files.
@ahoffer @AzGoalie @emanns95 @djblue 
@pklinef
@stustison
Run full build, then verify that catalog ui and log viewer works.
Important for ensuring control over the version used for each dependency.
[](https://codice.atlassian.net/browse/DDF-2846)
=> DDF 2846 Remove version range from package.json for web apps

README.md
Update the Readme with new quickbuild
@vinamartin @clockard 
@coyotesqrl
@shaundmorris
[DDF-2807](https://codice.atlassian.net/browse/DDF-2807)
=> DDF-2807 Update readme with new quickbuild

catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/model/Node.collection.js, catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/model/Node.js, catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/view/NodeModal.view.js, catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/view/Registry.view.js, catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/less/styles.less, catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/templates/nodeList.handlebars, catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/templates/nodeModal.handlebars, catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/templates/nodeRow.handlebars, catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/templates/registryPage.handlebars, catalog/spatial/registry/registry-common/src/main/java/org/codice/ddf/registry/common/metacard/RegistryUtility.java, catalog/spatial/registry/registry-common/src/test/java/org/codice/ddf/registry/common/metacard/TestRegistryUtility.java, catalog/spatial/registry/registry-federation-admin-api/src/main/java/org/codice/ddf/registry/federationadmin/internal/FederationAdminMBean.java, catalog/spatial/registry/registry-federation-admin-impl/pom.xml, catalog/spatial/registry/registry-federation-admin-impl/src/main/java/org/codice/ddf/registry/federationadmin/impl/FederationAdmin.java, catalog/spatial/registry/registry-federation-admin-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/spatial/registry/registry-federation-admin-impl/src/test/java/org/codice/ddf/registry/federationadmin/impl/FederationAdminTest.java
Improves Node Information tab performance by reducing the amount of data sent to populate the table and caches the data in FederationAdmin. Also made some minor ui usability changes.
The data size and load time for the table information is now a linear function of the number entries independent of the size and complexity of the entries themselves. 
In my test cases the amount of data returned with these change was significantly less than the current version.  The retrieval time was a tenth or less of the current version.
Added spinners to give indication when we are waiting for data as well.
@mcalcote @vinamartin @brianfelix @emmberk 
@figliold
Install DDF with registry. 
Verify that you can add/delete new secondary nodes. …
=> DDF-2855 Reduce amount of data returned in Node Information tab and cache table data in FederationAdmin.

catalog/core/catalog-core-api/src/main/java/ddf/catalog/data/Metacard.java
The metacard interface setAttribute method comment only currently mentions setting an Attribute, not using the method to remove an attribute which is the functionality in our primary metacard implementation. The comment should be updated to include this expectation.
@pklinef @stustison @lessarderic @clockard 
[Core APIs](https://github.com/orgs/codice/teams/core-apis) @ahoffer 
@coyotesqrl 
@lessarderic 
Inspect the text
[DDF-2899](https://codice.atlassian.net/browse/DDF-2899)
=> DDF-2899 Update setAttribute method comments in the metacard interface to reflect the expected contract

distribution/docs/src/main/resources/_contents/_securing/managing-certificates-contents.adoc
copy edits to managing certificates documentation.
@mcalcote @ahoffer @vinamartin @Lambeaux @jrnorth 
@coyotesqrl
@jlcsmith
@pklinef
@shaundmorris
@stustison 
verify content changes.
[DDF-2472](https://codice.atlassian.net/browse/DDF-2472)
=> DDF-2472 edits to managing certificates

catalog/ui/catalog-ui-search/src/main/webapp/js/model/Workspace.js
see https://github.com/codice/ddf/pull/1810
@pklinef 
=> DDF-2874 [2.10.x] Add query change listener for workspace change detection

distribution/docs/src/main/resources/_contents/_securing/managing-certificates-contents.adoc
backport of docs update for managing certificates.
@mcalcote @vinamartin @Lambeaux @ahoffer @jrnorth 
@coyotesqrl
@jlcsmith
@pklinef
@shaundmorris
@stustison
verify edits
[DDF-2472](https://codice.atlassian.net/browse/DDF-2472)
n/a
=> DDF-2472 [backport] edits to managing certificates

distribution/docs/src/main/resources/_contents/_developing/developing-intro-contents.adoc
Updates documentation for OSGi basics
@mcalcote @vinamartin @Lambeaux @jrnorth @tbatie @adimka @garrettfreibott @djblue @peterhuffer 
@coyotesqrl
@lessarderic
@pklinef
@shaundmorris
@kcwire 
review revised content
n/a
[DDF-2652](https://codice.atlassian.net/browse/DDF-2652)
[ddf-2652.zip](https://github.com/codice/ddf/files/862125/ddf-2652.zip)
=> DDF-2652 updated OSGi basics docs

platform/admin/ui/src/main/webapp/js/views/Module.view.js
Updates admin-ui to apply iframeresizer to AdminModule plugins.
@coyotesqrl
@pklinef
To test the new capability, you need to checkout [admin-console-beta](https://github.com/connexta/admin-console-beta/pull/43), and build+deploy it. Then confirm that the `setup-beta` tab correctly resizes the iframe.
=> DDF-2896: Update admin-ui to apply iframeresizer to AdminModule plugins.

catalog/spatial/csw/spatial-csw-source-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/AbstractCswSource.java
@kcwire @brendan-hofmann @clockard 
@coyotesqrl
@stustison
=> DDF-2903 fixed CSW GetCapabilities call to use system subject for ping

distribution/docs/src/main/resources/_contents/_developing/developing-intro-contents.adoc
updates OSGi basics docs for master branch
@mcalcote @vina @Lambeaux @jrnorth 
@coyotesqrl
@kcwire
@pklinef
@shaundmorris
verify updated content
[DDF-2652](https://codice.atlassian.net/browse/DDF-2652)
=> DDF-2652 updated OSGi basics docs [port]

catalog/ui/catalog-ui-search/Gruntfile.js, catalog/ui/catalog-ui-search/pom.xml
Runs webpack in dev mode when `skipStatic` is `true`.
@djblue 
@AzGoalie 
@pklinef
Run `mvn clean install` in `catalog-ui-search`. Verify the `prod` webpack config is used in the command line output.
Run `mvn clean install -DskipStatic` in `catalog-ui-search`. Verify the `dev` webpack config is used in the command line output.
[DDF-2907](https://codice.atlassian.net/browse/DDF-2907)
=> DDF-2907 Add webpack-dev to skipStatic

platform/admin/ui/src/main/webapp/js/views/Module.view.js, platform/admin/ui/src/main/webapp/main.js
Fixs iframe-resizer race conditions.
@coyotesqrl
@pklinef
- build the PR
- open the ui
- add network throttling
- reload the ui several times ensuring there are no exceptions in the console and that iframes are still resizing correctly
=> DDF-2896: fix iframe-resizer race conditions.

catalog/admin/module/catalog-admin-module-sources/src/main/webapp/js/view/ModalSource.view.js, catalog/admin/module/catalog-admin-module-sources/src/main/webapp/templates/sourceModal.handlebars
Fixes the sources tab to not create undesired configs, and fixes the filtering in the main view so only existing configurations are shown.
@emanns95 
@clockard 
@pklinef
Create a source and verify only one config is created. Click in and out of the source modal, click cancel, and verify the dropdown never displays erroneous configs.
[DDF-2901](https://codice.atlassian.net/browse/DDF-2901)
=> DDF-2901 Fix source tab configuration filtering

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/config/ConfigurationApplication.java, catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.config.xml, catalog/ui/search-ui-app/src/main/resources/etc/org.codice.ddf.catalog.ui.config, catalog/ui/search-ui/standard/src/main/java/org/codice/ddf/ui/searchui/standard/properties/ConfigurationStore.java, catalog/ui/search-ui/standard/src/main/resources/OSGI-INF/metatype/metatype.xml, distribution/docs/src/main/resources/_contents/_tables/org.codice.ddf.catalog.ui.config-table-contents.adoc
**This PR was previously merged on the 2.10.x Branch.** https://github.com/codice/ddf/pull/1814
When using default layers with the 2D Map, geometries appear incorrectly positioned. This change utilizes the EPSG:4326 projection for the single image layer so that the metacard locations appear consistent across both the 3D Globe and 2D Map.
@emmberk @clockard @vinamartin
[Docs](https://github.com/orgs/codice/teams/docs) @ricklarsen 
[UI](https://github.com/orgs/codice/teams/ui) @brianfelix 
@pklinef
Install DDF, ingest a product with location information, then confirm the location of the metacard in both the 3D Globe and 2D Map in both the Catalog UI as well as the Standard UI.
To access the 2D Map on the standard UI, navigate to …
=> DDF-2905 Updated single image layer projection coordinate system

platform/security/sts/security-sts-ldaplogin/pom.xml, platform/security/sts/security-sts-ldaplogin/src/main/java/ddf/ldap/ldaplogin/SslLdapLoginModule.java, platform/security/sts/security-sts-ldaplogin/src/test/java/ddf/ldap/ldaplogin/LdapModuleTest.java
Adds unit tests for SslLdaploginModule to test against a running LDAP server.
@brendan-hofmann @codymacdonald 
@pklinef
@stustison
Run the unit tests.
Goal is better coverage of DDF's interfaces to LDAP providers.
[DDF-2860](https://codice.atlassian.net/browse/DDF-2860)
- [N/A] Change Log Updated
=> DDF-2860 Enhance LDAP tests

platform/pom.xml, platform/solr/platform-solr-server-standalone/src/main/resources/solr/conf/solrconfig-inmemory.xml, platform/solr/platform-solr-server-standalone/src/main/resources/solr/conf/solrconfig.xml, pom.xml
Upgrades solr to version 6.4.2 to fix performance issue
@figliold 
@lessarderic
@pklinef
Verify build passes.
Verify sure solr admin ui still function
Verify Ingest/query functions still work
[DDF-2914](https://codice.atlassian.net/browse/DDF-2914)
=> DDF-2914 Upgrade Solr to 6.4.2

platform/admin/ui/src/main/webapp/js/views/Module.view.js, platform/admin/ui/src/main/webapp/main.js
Back port changes from #1801
@coyotesqrl
@pklinef
See #1801 for test instructions.
=> DDF-2896: (2.10.x backport) Update admin-ui to apply iframeresizer to AdminModule plugins.

platform/pom.xml, platform/solr/platform-solr-server-standalone/src/main/resources/solr/conf/solrconfig-inmemory.xml, platform/solr/platform-solr-server-standalone/src/main/resources/solr/conf/solrconfig.xml, pom.xml
Port of https://github.com/codice/ddf/pull/1831 to upgrade solr version
@figliold 
@lessarderic
@pklinef
[DDF-2914](https://codice.atlassian.net/browse/DDF-2914)
=> DDF-2914 -Port- Upgrade Solr to 6.4.2

catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/model/Node.collection.js, catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/model/Node.js, catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/view/NodeModal.view.js, catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/view/Registry.view.js, catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/less/styles.less, catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/templates/nodeList.handlebars, catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/templates/nodeModal.handlebars, catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/templates/nodeRow.handlebars, catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/templates/registryPage.handlebars, catalog/spatial/registry/registry-common/src/main/java/org/codice/ddf/registry/common/metacard/RegistryUtility.java, catalog/spatial/registry/registry-common/src/test/java/org/codice/ddf/registry/common/metacard/TestRegistryUtility.java, catalog/spatial/registry/registry-federation-admin-api/src/main/java/org/codice/ddf/registry/federationadmin/internal/FederationAdminMBean.java, catalog/spatial/registry/registry-federation-admin-impl/pom.xml, catalog/spatial/registry/registry-federation-admin-impl/src/main/java/org/codice/ddf/registry/federationadmin/impl/FederationAdmin.java, catalog/spatial/registry/registry-federation-admin-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/spatial/registry/registry-federation-admin-impl/src/test/java/org/codice/ddf/registry/federationadmin/impl/FederationAdminTest.java
Port of https://github.com/codice/ddf/pull/1784
@brianfelix @emmberk 
@figliold 
See https://github.com/codice/ddf/pull/1784
[DDF-2855](https://codice.atlassian.net/browse/DDF-2855)
=> DDF-2855 -Port- Reduce amount of data returned in Node Information tab and cache table data in FederationAdmin.

distribution/docs/src/main/resources/documentation.adoc
=> DDF-2896: (2.10.x backport) added iframeresizer to documentation to fix scrolling issue.

platform/platform-filter-response/src/main/java/org/codice/ddf/platform/response/filter/ResponseFilter.java
- As of DDF-2893, we're caching everything far too aggressively.
- This update allows apps to perform their own cache busting between versions, see DDF-2916.
- Without this, a user will need to clear their cache (or wait a week) when upgrading to new versions.
@djblue 
@rzwiefel 
@kcwire
@pklinef
Go to the admin application.  Verify that the main app page and any html pages within do not get cached.  Verify that other assets do.
https://codice.atlassian.net/browse/DDF-2917
=> DDF-2917 (2.10.x) Update caching to exclude base app pages and html

platform/security/handler/security-handler-guest/src/main/webapp/WEB-INF/web.xml
Added a security-constraint to the web.xml of the login page to ensure that the connection is using SSL.
@brendan-hofmann @ahoffer 
@coyotesqrl
@stustison
=> DDF-2902 Force SSL on login page

distribution/docs/src/main/resources/_contents/_endpoints/catalog-rest-endpoint-contents.adoc
updates documentation relating to catalog REST endpoint
@mcalcote @vinamartin @Lambeaux @jrnorth @clockard 
@jlcsmith
@stustison
verify content updates
[documentation.pdf](https://github.com/codice/ddf/files/894605/documentation.pdf)
=> DDF-2824 update catalog rest endpoint docs

pom.xml
Allows the download location for Node and Yarn to be overridden.  This will allow CI jobs to proxy downloads to a local server.
@djblue 
@stustison 
@pklinef
Remove the cached version of node from the .m2 directory.  
`rm ~/.m2/repository/com/github/eirslett/node/7.1.0/node-7.1.0-darwin-x64.tar.gz`
Remove the node and node_modules folders from a UI module project like catalog-ui-search.
Build using new variable.
`mvn clean install -Dnode.download.root=http://nexus3rawproxy/repository/nodejs.org/dist`
Verify node is downloaded from proxy.
`[INFO] Downloading http://nexus3rawproxy/repository/nodejs.org/distv7.1.0/node-v7.1.0-darwin-x64.tar.gz to …
=> DDF-2929 Allow overriding download location for node and yarn

CHANGES.md
updates changelog for 2.10.x branch
@mcalcote @vinamartin @Lambeaux @jrnorth @clockard 
@coyotesqrl
@figliold
@kcwire
@lessarderic
@pklinef
@shaundmorris
preview at https://github.com/ricklarsen/ddf/blob/DDF-2748-2.10.x/CHANGES.md
=> DDF-2748 [2.10.x] update changelog for 2.10.2

CHANGES.md
fixes changelog with updated 2.10.2 items
@coyotesqrl
@jlcsmith
@lessarderic
@pklinef
@shaundmorris
- preview at https://github.com/ricklarsen/ddf/blob/DDF-2748-2.10.x/CHANGES.md#2102
=> DDF-2748 updates to change log

pom.xml
Updates the ddf-support version to the released version: 2.3.7
@paouelle 
@coyotesqrl 
@shaundmorris 
Ensure build passes with a clean .m2
https://codice.atlassian.net/browse/DDF-2935
=> DDF-2935 Update DDF-Support version to 2.3.7

distribution/docs/src/main/resources/_contents/_endpoints/catalog-rest-endpoint-contents.adoc
Port of catalog rest endpoint doc edits.
@mcalcote @vinamartin @Lambeaux @jrnorth @clockard 
@coyotesqrl
@figliold
@jlcsmith
@shaundmorris
@stustison
verify content changes.
=> DDF-2824 update catalog rest endpoint docs [2.11.x]

distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalog.java
Cleans up after one of the itests that was leaving behind metacards. 
@coyotesqrl
@shaundmorris
Verify itests pass
[DDF-2928](https://codice.atlassian.net/browse/DDF-2928)
=> DDF-2928 Fix TestCatalog itest to clean up after itself.

catalog/transformer/catalog-transformer-streaming-lib/src/main/java/org/codice/ddf/transformer/xml/streaming/lib/SaxEventHandlerDelegate.java
Fixes issue noted in Coverity scan, CID 161297
@gordocanchola @harrison-tarr 
@shaundmorris
@stustison
Full build and test. For any manual testing, please ask @gordocanchola  for details.
N/A
[DDF-2933](https://codice.atlassian.net/browse/DDF-2933)
N/A
=> DDF-2933 Resolves issue with dereferenced null value and modification of unmod list

distribution/kernel/src/main/filtered-resources/kernel-features.xml
Fixes the karaf version in the kernel-features.xml
@coyotesqrl
@shaundmorris
=> DDF-2224 Use the karaf.version variable in kernel-features.xml

CHANGES.md, catalog/ui/catalog-ui-search/pom.xml, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/config/ConfigurationApplication.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/FeedbackApplication.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/feedback/FeedbackException.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/feedback/FeedbackRequest.java, catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.config.xml, catalog/ui/catalog-ui-search/src/main/webapp/component/component.less, catalog/ui/catalog-ui-search/src/main/webapp/component/input/textarea/input-textarea.hbs, catalog/ui/catalog-ui-search/src/main/webapp/component/input/textarea/input-textarea.less, catalog/ui/catalog-ui-search/src/main/webapp/component/input/textarea/input-textarea.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/property/property.js, catalog/ui/catalog-ui-search/src/main/webapp/component/query-feedback/query-feedback.hbs, catalog/ui/catalog-ui-search/src/main/webapp/component/query-feedback/query-feedback.less, catalog/ui/catalog-ui-search/src/main/webapp/component/query-feedback/query-feedback.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/query-feedback/test.json, catalog/ui/catalog-ui-search/src/main/webapp/component/query-interactions/query-interactions.hbs, catalog/ui/catalog-ui-search/src/main/webapp/component/query-interactions/query-interactions.less, catalog/ui/catalog-ui-search/src/main/webapp/component/query-interactions/query-interactions.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/value/value.view.js, catalog/ui/catalog-ui-search/src/main/webapp/properties.js, catalog/ui/search-ui-app/src/main/resources/etc/org.codice.ddf.catalog.ui.config, distribution/docs/src/main/resources/_contents/_tables/org.codice.ddf.catalog.ui.config-table-contents.adoc
Adds query feedback form to Intrigue. Feedback is sent via Email to the configured email recipient. 
@bdeining 
@rzwiefel 
@glenhein 
@millerw8
1. Configure the email service to point to SMTP server
2. Configure Catalog UI Search, enabling Query Feedback and choosing a destination email that you wish to receive the feedback data at.
3. Perform a search on any workspace and click the 3 dots on the results tab
4. Choose `Submit Feedback` and submit feedback on the query
5. Check the email configured in Step 2 and verify that query feedback has been received.
Admin UI:
Results menu option:
Feedback form:
Example email content:
=> DDF-2820 Query feedback form for Intrigue

distribution/kernel/src/main/filtered-resources/kernel-features.xml
Cherry pick port of https://github.com/codice/ddf/pull/1885
@coyotesqrl
@shaundmorris
@stustison
Verify build passes and distro can be started
[DDF-2224](https://codice.atlassian.net/browse/DDF-2224)
=> DDF-2224 -Port- Use the karaf.version variable in kernel-features.xml

Documentation-versions.html, index.html
updates documentation on codice.org/ddf to reflect version update to 2.10.2.
@mcalcote @vinamartin @Lambeaux @jrnorth @clockard 
@coyotesqrl
@figliold
@kcwire
@lessarderic
@pklinef
@shaundmorris
Verify version updates.
=> DDF-2748 Updated gh-pages for 2.10.2 release

platform/security/policy/security-policy-context/pom.xml, platform/security/policy/security-policy-context/src/test/java/org/codice/security/policy/context/PolicyManagerTest.java
Adds more test coverage to ContextPolicyManager with complex paths.
@emanns95 @ahoffer @codymacdonald 
@coyotesqrl
@stustison
Full build passes
=> DDF-2937 Added more code coverage to ContextPolicyManager

platform/security/platform-security-core-api/src/main/java/ddf/security/SubjectUtils.java, platform/security/platform-security-core-api/src/test/java/ddf/security/SubjectUtilsTest.java, platform/security/security-services-app/pom.xml, platform/security/security-services-app/src/main/resources/features.xml, platform/security/sts/pom.xml, platform/security/sts/security-sts-certificateclaimshandler/pom.xml, platform/security/sts/security-sts-certificateclaimshandler/src/main/java/org/codice/ddf/security/claims/certificate/CertificateClaimsHandler.java, platform/security/sts/security-sts-certificateclaimshandler/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/security/sts/security-sts-certificateclaimshandler/src/main/resources/OSGI-INF/metatype/metatype.xml, platform/security/sts/security-sts-certificateclaimshandler/src/test/java/org/codice/ddf/security/claims/certificate/CertificateClaimsHandlerTest.java, platform/security/sts/security-sts-pkivalidator/src/main/java/org/codice/ddf/security/validator/pki/PKITokenValidator.java, platform/security/sts/security-sts-pkivalidator/src/test/java/org/codice/ddf/security/validator/pki/TestPKITokenValidator.java, platform/security/sts/security-sts-x509validator/src/main/java/org/codice/ddf/security/validator/x509/X509PathTokenValidator.java, platform/security/sts/security-sts-x509validator/src/test/java/org/codice/ddf/security/validator/x509/TestX509PathTokenValidator.java
@coyotesqrl @tbatie @pklinef 
@clockard
@stustison
=> DDF-2949 added email and country claims as cert claims

distribution/docs/src/main/resources/_contents/_configuring/configuring-managed-service-factory-bundles-contents.adoc
fixes formatting for table in documentation
@emanns95 @mcalcote @vinamartin @Lambeaux @jrnorth 
@clockard
@coyotesqrl
@lessarderic
@pklinef
@shaundmorris
verify table formatting (pdf attached)
[documentation.pdf](https://github.com/codice/ddf/files/926913/documentation.pdf)
=> DDF-2824 fixed mgd service table formatting in docs (#1896)

platform/security/sts/security-sts-ldapclaimshandler/pom.xml, platform/security/sts/security-sts-ldapclaimshandler/src/test/java/ddf/security/sts/claimsHandler/RoleClaimsHandlerTest.java
Increases unit test coverage.
@brendan-hofmann @codymacdonald @emmberk @mweser 
@AzGoalie 
@clockard
@coyotesqrl
mvn install -- build success -- 100% unit test pass and meet code coverage.
When the approach taken in this PR is approved, I'll do the same thing for ClaimsHandlerManager to bring up the module's unit test coverage some more. 
[/DDF-2875](https://codice.atlassian.net/browse/DDF-2875/)
- [N/A] Change Log Updated
=> DDF-2875 Increase unit test coverage

catalog/ui/catalog-ui-search/src/main/webapp/js/widgets/openlayers.circle.js
See https://github.com/codice/ddf/pull/1855
=> DDF-2925 - Update openlayers circle drawing to be projection agnostic

catalog/ui/catalog-ui-search/src/main/webapp/component/association/association.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/content/content.view.js, catalog/ui/catalog-ui-search/src/main/webapp/js/HandlebarsHelpers.js
Cherrypick of https://github.com/codice/ddf/pull/1871
Go to a workspace and update the name to include xss.  Verify it doesn't get executed.
This was added in a backport to 2.10.x so it's not out in the wild yet.
https://codice.atlassian.net/browse/DDF-2934
Thanks for finding this one @garrettfreibott !
=> DDF-2934 Remove injection opportunity from bind helper

catalog/core/catalog-core-versioning/versioning-common/pom.xml, pom.xml
Previously spock unit tests would not be ran unless they were suffixed with *Test. 
anyone
@coyotesqrl 
@lessarderic
Ensure spock tests not ending in `Test` are ran and included in coverage
https://codice.atlassian.net/browse/DDF-2943
=> DDF-2943 Fixes Spock tests running

platform/platform-app/src/main/resources/features.xml
Adds commons-lang3 to one of the common dependencies feature in the platform app.
@peterhuffer @adimka @djblue 
@coyotesqrl 
@kcwire
Make sure the feature starts up properly and the commons-lang3 bundle is running
=> DDF-2953: Commons-lang3 should be started at the platform-app level

distribution/docs/src/main/resources/_contents/_endpoints/csw-endpoint-contents.adoc
- Clarified Csw coordinate ordering 
- Corrected documentation for Csw output schema
@bdeining @rzwiefel 
@millerw8
=> DDF-2824: Clarified CSW coord ordering and OutputSchema documentation

catalog/core/catalog-core-standardframework/pom.xml, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/history/Historian.java, catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/history/HistorianTest.java, catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/history/InMemoryStorageProvider.java
Adds unit test coverage to the Historian class.
@rzwiefel @ahoffer @codymacdonald 
@lessarderic [Test](https://github.com/orgs/codice/teams/test)
@coyotesqrl
@pklinef
=> DDF-2945 Added unit tests for Historian

platform/security/idp/security-idp-client/src/main/java/org/codice/ddf/security/idp/client/AssertionConsumerService.java
@coyotesqrl @tbatie 
@pklinef
@stustison
=> 	DDF-2955 fixed infinite redirect loop for assertion consumer service

catalog/ui/catalog-ui-search/src/main/webapp/component/login-form/login-form.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/user/user.view.js, platform/security/filter/security-filter-authorization/src/test/java/org/codice/ddf/security/filter/authorization/AuthorizationFilterTest.java, platform/security/filter/security-filter-web-sso/src/main/java/org/codice/ddf/security/filter/websso/WebSSOFilter.java, platform/security/handler/security-handler-guest/src/main/webapp/WEB-INF/web.xml, platform/security/handler/security-handler-guest/src/main/webapp/js/view/Login.view.js, platform/security/policy/security-policy-context/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/security/policy/security-policy-context/src/main/resources/OSGI-INF/metatype/metatype.xml, platform/security/rest/pom.xml, platform/security/rest/security-rest-authentication/pom.xml, platform/security/rest/security-rest-authentication/src/main/java/org/codice/ddf/security/rest/authentication/AuthenticationEndpoint.java, platform/security/rest/security-rest-authentication/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/security/rest/security-rest-authentication/src/test/java/org/codice/ddf/security/rest/authentication/AuthenticationEndpointTest.java, platform/security/security-services-app/pom.xml, platform/security/security-services-app/src/main/resources/features.xml
Fixed multi-realm authentication for non idp realms.
@brendan-hofmann @ahoffer 
@stustison [Security](https://github.com/orgs/codice/teams/security)
@coyotesqrl 
@stustison
=> Ddf-2902: Fixed multi-realm authentication

distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/SystemStateManager.java
Fix a bug in SystemStateManager that was causing unnecessary config resets.
@emanns95 
@clockard
@coyotesqrl
[DDF-2906](https://codice.atlassian.net/browse/DDF-2906)
=> DDF-2906 Fix array comparison in SystemStateManager

distribution/docs/src/main/resources/_contents/_configuring/configuring-global-settings-contents.adoc
Puts this section back into the docs. It was unintentionally removed.
@figliold @ricklarsen 
@lessarderic 
@shaundmorris 
N/A
[DDF-2628](https://codice.atlassian.net/browse/DDF-2628)
=> DDF-2628 Putting Solr system properties back into the docs.

platform/security/rest/security-rest-authentication/pom.xml
Fixes an issue with the guest handler having the same path from logging in.
@stustison 
@pklinef 
@stustison
=> DDF-2902: Removed Web-ContextPath

catalog/transformer/catalog-transformer-propertyjson-metacard/pom.xml
removes unnecessary version in pom
@bdeining @rzwiefel 
@clockard 
Verify builds cleanly
=> DDF-2874 fixed propertyjson transformer pom version

distribution/test/itests/test-itests-ddf/pom.xml, distribution/test/itests/test-itests-dependencies-app/src/main/filtered-resources/features.xml
Moves the itests to the integration-test phase using the failsafe plugin
@tbatie @brendan-hofmann 
@figliold
@lessarderic
Verify itests don't run with maven clean test
Verify itests pass with maven clean install
[DDF-2857](https://codice.atlassian.net/browse/DDF-2857)
=> DDF-2857 Move itests to integration-test phase

catalog/ui/catalog-ui-search/src/main/webapp/component/login-form/login-form.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/user/user.view.js, catalog/ui/search-ui/standard/src/main/webapp/js/view/Menu.view.js, platform/platform-filter-delegate/src/main/java/org/codice/ddf/platform/filter/delegate/FilterInjector.java, platform/security/handler/security-handler-guest/src/main/webapp/js/view/Login.view.js, platform/security/idp/security-idp-client/src/main/java/org/codice/ddf/security/idp/client/AssertionConsumerService.java, platform/security/idp/security-idp-client/src/test/java/org/codice/ddf/security/idp/client/AssertionConsumerServiceTest.java, platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/server/IdpEndpoint.java, platform/security/policy/security-policy-context/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/security/policy/security-policy-context/src/main/resources/OSGI-INF/metatype/metatype.xml, platform/security/rest/security-rest-authentication/pom.xml, platform/security/rest/security-rest-authentication/src/main/java/org/codice/ddf/security/rest/authentication/AuthenticationEndpoint.java, platform/security/servlet/security-servlet-logout/src/main/java/org/codice/ddf/security/servlet/logout/LocalLogoutServlet.java, platform/security/servlet/security-servlet-logout/src/test/java/org/codice/ddf/security/servlet/logout/TestLogoutServlet.java
@tbatie @garrettfreibott @ahoffer 
@clockard 
@stustison
=> DDF-2959 set session cookie to HTTPOnly

distribution/docs/src/main/resources/_contents/_tables/ddf.catalog.metacard.validation.MetacardValidityFilterPlugin-table-contents.adoc, distribution/docs/src/main/resources/_contents/_tables/ddf.catalog.metacard.validation.MetacardValidityMarkerPlugin-table-contents.adoc
Fixes tables for MetacardValidityMarkerPlugin and MetacardValidityFilterPlugin to have correct values and names for properties, resolve typos, and remove the two tables duplicating each other.
@ricklarsen 
@ahoffer 
@clockard
@shaundmorris
=> DDF-2824 Fixed doc errors in MetacardValidity tables

distribution/test/itests/README.md
Updates the itest readme
@vinamartin @brendan-hofmann 
@clockard
@figliold
[DDF-2857](https://codice.atlassian.net/browse/DDF-2857)
=> DDF-2857 Update itest readme to reflect maven surefire plugin update

Jenkinsfile
Updated the Jenkinsfile to include the nightly build trigger so that we don't have to rely on job configuration. Also added a ticket number to the TODO comment.
@oconnormi
[Build](https://github.com/orgs/codice/teams/build) @brendan-hofmann 
@clockard
@lessarderic
This job can be observed/tested on the local test jenkins.
This trigger is included in the initial Alliance commit: https://github.com/codice/alliance/pull/305
[DDF-2920](https://codice.atlassian.net/browse/DDF-2920)
=> DDF-2920 Included scm cron trigger and updated todo comment

distribution/docs/src/main/resources/_contents/_tables/org.codice.ddf.catalog.ui.config-table-contents.adoc
- Added missing configurations to docs
- Added examples of various imagery provider configurations
- Corrected existing imagery provider configuration
- Clarified projection config
@ricklarsen @bdeining 
@stustison
=> DDF-2425 Updated Catalog UI config documentation

libs/activities/pom.xml
Removes repository definition from `libs/activites` pom file.
@oconnormi 
@shaundmorris 
@clockard
@figliold
Full build
[DDF-1536](https://codice.atlassian.net/browse/DDF-1536)
=> DDF-1536 Consolidate maven repository definitions

Documentation-versions.html
fixes broken link in Documentation versions page of gh-pages site.
@AzGoalie @mcalcote @vinamartin @Lambeaux @jrnorth 
@coyotesqrl
@lessarderic
@pklinef
@shaundmorris
verify link works for anchor.
=> DDF-2824 updated Documentation versions page to fix broken link.

catalog/core/catalog-core-solrcommands/src/test/java/org/codice/ddf/commands/solr/BackupCommandTest.java
Fix path construction in the unit tests to work on all platforms.
@codymacdonald @AzGoalie 
@coyotesqrl
@figliold
Build this module on all platforms.
[DDF-2947](https://codice.atlassian.net/browse/DDF-2947)
=> DDF-2947 Fix test on windows

CHANGES.md, catalog/core/catalog-core-validationparser/src/main/java/ddf/catalog/validation/impl/ValidationParser.java, catalog/core/catalog-core-validationparser/src/test/groovy/ddf/catalog/validation/impl/ValidationParserSpecTest.groovy, distribution/docs/src/main/resources/_contents/_catalog-frameworks/metacard-attribute-validators-definition-contents.adoc, distribution/docs/src/main/resources/documentation.adoc
Adds json configuration of Metacard Validator(s). 
@bdeining 
@glenhein 
@ricklarsen 
@jrnorth 
@rzwiefel 
@lcrosenbu 
@jlcsmith 
@millerw8
@pklinef
Run a full build with tests
=> DDF-2973 JSON configuration for Metacard Validator(s)

platform/security/idp/security-idp-client/pom.xml, platform/security/idp/security-idp-client/src/main/java/org/codice/ddf/security/idp/client/IdpMetadata.java, platform/security/idp/security-idp-server/pom.xml, platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/server/IdpEndpoint.java, platform/security/platform-security-core-api/src/main/java/ddf/security/samlp/MetadataConfigurationParser.java, platform/security/platform-security-core-api/src/test/java/ddf/security/samlp/MetadataConfigurationParserTest.java
Resolves timing issue with idp server and adds callback for idp client.
@brendan-hofmann @bdeining 
@stustison 
@clockard
@lessarderic
Anyone who can successfully duplicate the idp login issue should attempt to login with this update. As we have not found a reproducible way to cause the timing issue, there is no definitive test.
N/A
[DDF-2986](https://codice.atlassian.net/browse/DDF-2986)
N/A
=> DDF-2986 Resolves timing issue with MetadataConfigurationParser callbacks

Jenkinsfile, broker/pom.xml, catalog/core/catalog-core-contentresourcereader/pom.xml, catalog/core/catalog-core-localstorageprovider/pom.xml, catalog/core/catalog-core-urlresourcereader/pom.xml, catalog/spatial/ogc/spatial-ogc-urlresourcereader/pom.xml, catalog/ui/catalog-ui-search/.nsprc, distribution/test/itests/test-itests-common/pom.xml, distribution/test/itests/test-itests-ddf/pom.xml, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalogValidation.java, platform/admin/ui/.nsprc, platform/pom.xml, pom.xml
Adds static analysis steps to jenkins file.
It also includes:
- changes needed to make owas/nsp scans work correctly.
- sends itest output to a log file 
- makes the base builds parallel builds
- updates the surefire plugin version
@oconnormi @mcalcote 
@lessarderic
@shaundmorris
Verify that all static analysis tools run. RIght now we are expecting owas to fail because of real dependency issues
[DDF-2969](https://codice.atlassian.net/browse/DDF-2969)
=> DDF-2969 Add static analysis steps to Jenkins file

catalog/core/catalog-core-standardframework/pom.xml, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/CacheCommitPhaser.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/CachingFederationStrategy.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/SortedQueryMonitor.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/SortedQueryMonitorFactory.java, catalog/core/catalog-core-standardframework/src/main/resources/OSGI-INF/blueprint/fedstrategy.xml, catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/cache/solr/impl/CachingFederationStrategyTest.java
Adds unit tests for CachingFederationStrategy
@ahoffer 
@emanns95 
@mweser 
@AzGoalie 
@lessarderic
@pklinef
Build and run unit tests.
Goal of the ticket was 70% code coverage.
[DDF-2938](https://codice.atlassian.net/browse/DDF-2938)
=> DDF-2938 Add unit test coverage to CachingFederationStrategy

catalog/plugin/catalog-plugin-metacardbackup-filestorage/src/main/java/org/codice/ddf/catalog/plugin/metacard/backup/storage/filestorage/MetacardBackupFileStorage.java
Resolves Sonarqube findings for ambiguous variable names and variable masking in MetacardBackupFileStorage
@troymohl 
@ryeats 
@lessarderic
@shaundmorris
Full build
From Sonarqube findings.
=> DDF-2936 Fix Sonarqube code smells in MetacardBackupFileStorage

catalog/ui/catalog-ui-search/package.json
The `package.json` file in the catalog UI needs to be updated in order for Windows builds to pass.
@AzGoalie 
@djblue 
@mcalcote 
@clockard
Builds on Windows
=> DDF-2956 Fix Windows Catalog UI builds package.json

platform/platform-app/pom.xml, platform/platform-app/src/main/resources/features.xml, pom.xml
COPIED TO MY FORK -> original PR: https://github.com/codice/ddf/pull/1963
Upgrade Camel to the latest version available (2.18.3 as of this PR). 
@brianfelix @vinamartin @emmberk 
[Security](https://github.com/orgs/codice/teams/security) @stustison 
@clockard
@coyotesqrl
Hero Build, Test the Content Directory Monitor
This will fix an outstanding CVE against Camel.
[DDF-2975 Upgrade Camel to 2.18.3](https://codice.atlassian.net/browse/DDF-2975)
=> DDF-2975 Upgrade Camel to 2.18.3

distribution/docs/src/main/resources/_contents/_securing/securing-idp-sp-contents.adoc
Reflect the default installation of the IdP and fix some typos.
@ricklarsen @codymacdonald 
@clockard
@coyotesqrl
=> DDF-2824 Update IdP docs

distribution/docs/src/main/resources/_contents/_catalog-frameworks/catalog-framework-intro-contents.adoc, distribution/docs/src/main/resources/_contents/_plugins/expiration-date-pre-ingest-plugin-contents.adoc, distribution/docs/src/main/resources/_contents/_tables/conf-org.codice.ddf.catalog.plugin.expiration.ExpirationDatePlugin-table-contents.adoc, distribution/docs/src/main/resources/_contents/_tables/org.codice.ddf.catalog.plugin.expiration.ExpirationDatePlugin-table-contents.adoc
- fixes incorrectly formatted diagrams.
- adds configuration info to Expiration Date plugin.
@coyotesqrl
@lessarderic
@pklinef
@shaundmorris
verify content
=> DDF-2824 fix for plugin diagrams and tables.

distribution/docs/src/main/resources/_contents/_core-concepts/search-intro-contents.adoc, distribution/docs/src/main/resources/_contents/_using/using-catalog-search-ui-contents.adoc
REVISION of TEXT search documentation
@mcalcote @vinamartin @Lambeaux @jrnorth @brendan-hofmann 
@jlcsmith
@pklinef
@shaundmorris
review content. 
Additional sections will be added as completed. 
[DDF-2725](https://codice.atlassian.net/browse/DDF-2725)
n/a
=> Ddf 2725 REVISION of updated search docs for Intrigue

catalog/ui/catalog-ui-search/src/main/webapp/component/location-old/location-old.hbs, catalog/ui/catalog-ui-search/src/main/webapp/component/location-old/location-old.js, catalog/ui/catalog-ui-search/src/main/webapp/component/location-old/location-old.less, catalog/ui/catalog-ui-search/src/main/webapp/component/location-old/location-old.view.js, catalog/ui/catalog-ui-search/src/main/webapp/js/widgets/cesium.bbox.js, catalog/ui/catalog-ui-search/src/main/webapp/js/widgets/cesium.circle.js, catalog/ui/catalog-ui-search/src/main/webapp/js/widgets/openlayers.bbox.js, catalog/ui/catalog-ui-search/src/main/webapp/js/widgets/openlayers.circle.js
Add UTM Search support in Intrigue.
@rzwiefel 
@bdeining 
@troymohl  
@stustison
Basic Search Test
1. Build and install
2. Ingest content that contains known geo location data. 
3. Using Intrigue (https://localhost:8993/search/catalog), create search for a specific geographic area using the UTM coordinates. Try with Point Radius and with Bounding Box.
Lat-Lon <=> USNG/MGRS <=> UTM Testing
1. Build and install
2. Using the geographic search fields, enter a point radius for Lat-Lon.
3. Check that the USNG/MGRS and UTM fields contain the correct values. USNG/MGRS is difficult because it does not use exact points, but instead a grid system.
4. Edit the Lat field and check that USNG/MGRS and UTM are updated correctly.
5. Edit the …
=> DDF-2866 Add UTM search support

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/DeleteOperations.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/OperationsSecuritySupport.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/UpdateOperations.java, catalog/core/catalog-core-standardframework/src/test/groovy/ddf/catalog/impl/operations/OperationsSecuritySupportTest.groovy, catalog/spatial/csw/spatial-csw-source-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/AbstractCswStore.java, catalog/spatial/registry/registry-api-impl/src/main/java/org/codice/ddf/registry/api/impl/RegistryStoreImpl.java, catalog/spatial/registry/registry-api-impl/src/test/java/org/codice/ddf/registry/api/impl/TestRegistryStore.java, catalog/spatial/registry/registry-federation-admin-service-impl/src/main/java/org/codice/ddf/registry/federationadmin/service/impl/RefreshRegistryEntries.java, catalog/spatial/registry/registry-federation-admin-service-impl/src/test/java/org/codice/ddf/registry/federationadmin/service/impl/RefreshRegistryEntriesTest.java
Updates the registry such that its requests include a subject. 
Also fixed issues in UpdateOperation, DeleteOperation and AbstractCswStore where the subject wasn't getting passed along with generated requests
@emmberk @mcalcote 
@coyotesqrl
@stustison
Test the following registry functions
-Publish
-Unpublish
-Publication update
-Subscription
[DDF-3001](https://codice.atlassian.net/browse/DDF-3001)
=> DDF-3001 Update registry to insert subject information into requests.

platform/platform-filter-delegate/pom.xml, platform/platform-filter-delegate/src/main/java/org/codice/ddf/platform/filter/delegate/FilterInjector.java, platform/platform-filter-delegate/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/security/command/pom.xml, platform/security/command/security-command-listener/pom.xml, platform/security/command/security-command-listener/src/main/java/org/codice/ddf/security/command/listener/CommandAuditer.java, platform/security/command/security-command-listener/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/security/command/security-command-listener/src/test/java/org/codice/ddf/security/command/listener/CommandAuditerTest.java, platform/security/core/security-core-impl/pom.xml, platform/security/core/security-core-impl/src/main/java/ddf/security/listener/AuditingHttpSessionListener.java, platform/security/core/security-core-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/security/filter/security-filter-authorization/src/main/java/org/codice/ddf/security/filter/authorization/AuthorizationFilter.java, platform/security/filter/security-filter-login/src/main/java/org/codice/ddf/security/filter/login/LoginFilter.java, platform/security/pom.xml, platform/security/rest/security-rest-cxfwrapper/src/main/java/org/codice/ddf/cxf/SecureCxfClientFactory.java, platform/security/security-services-app/pom.xml, platform/security/security-services-app/src/main/resources/features.xml, platform/security/sts/security-sts-attributequerycommon/src/main/java/org/codice/ddf/security/claims/attributequery/common/AttributeQueryClaimsHandler.java, platform/security/sts/security-sts-ldapclaimshandler/src/main/java/ddf/security/sts/claimsHandler/ClaimsHandlerManager.java, platform/security/sts/security-sts-ldaplogin/src/main/java/ddf/ldap/ldaplogin/SslLdapLoginModule.java
- session creation
- session destruction
- source connections
- attribute store connections
- karaf command line commands
@ahoffer @AzGoalie @Lambeaux 
@coyotesqrl
@stustison
=> DDF-2980 added additional audits

distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestSingleSignOn.java, platform/security/idp/security-idp-client/src/main/java/org/codice/ddf/security/idp/client/AssertionConsumerService.java, platform/security/idp/security-idp-client/src/test/java/org/codice/ddf/security/idp/client/AssertionConsumerServiceTest.java, platform/security/rest/security-rest-cxfwrapper/pom.xml, platform/security/rest/security-rest-cxfwrapper/src/main/java/org/codice/ddf/cxf/paos/BodyWriter.java, platform/security/rest/security-rest-cxfwrapper/src/main/java/org/codice/ddf/cxf/paos/PaosInInterceptor.java, platform/security/rest/security-rest-cxfwrapper/src/test/java/org/codice/ddf/cxf/paos/PaosInInterceptorTest.java
@pklinef @clockard 
@coyotesqrl
@stustison
=> DDF-3005 added ability for SAML ECP to initiate conversation with a POST request

catalog/spatial/registry/registry-api-impl/src/main/java/org/codice/ddf/registry/api/impl/RegistryMetacardHandler.java, catalog/spatial/registry/registry-api-impl/src/main/java/org/codice/ddf/registry/api/impl/RegistryStoreCleanupHandler.java, catalog/spatial/registry/registry-api-impl/src/test/java/org/codice/ddf/registry/api/impl/RegistryMetacardHandlerTest.java, catalog/spatial/registry/registry-api-impl/src/test/java/org/codice/ddf/registry/api/impl/RegistryStoreCleanupHandlerTest.java, catalog/spatial/registry/registry-federation-admin-service-impl/src/main/java/org/codice/ddf/registry/federationadmin/service/impl/IdentityNodeInitialization.java, catalog/spatial/registry/registry-federation-admin-service-impl/src/main/java/org/codice/ddf/registry/federationadmin/service/impl/RefreshRegistryEntries.java, catalog/spatial/registry/registry-federation-admin-service-impl/src/main/java/org/codice/ddf/registry/federationadmin/service/impl/RegistryPublicationServiceImpl.java, catalog/spatial/registry/registry-publication-update-handler/src/main/java/org/codice/ddf/registry/publication/RegistryPublicationHandler.java, catalog/spatial/registry/registry-source-configuration-handler/src/main/java/org/codice/ddf/registry/source/configuration/SourceConfigurationHandler.java
Adds more logging to the registry
@ricklarsen 
@beyelerb
@stustison
[DDF-2988](https://codice.atlassian.net/browse/DDF-2988)
=> DDF-2988 Add more logging to registry.

catalog/ui/catalog-ui-search/package.json, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/cql/CqlRequest.java, catalog/ui/catalog-ui-search/src/main/webapp/component/query-basic/query-basic.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/query-settings/query-settings.hbs, catalog/ui/catalog-ui-search/src/main/webapp/component/query-settings/query-settings.less, catalog/ui/catalog-ui-search/src/main/webapp/component/query-settings/query-settings.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/result-sort/result-sort.less, catalog/ui/catalog-ui-search/src/main/webapp/component/sort-item/sort-item.less, catalog/ui/catalog-ui-search/src/main/webapp/component/sort-item/sort-item.view.js, catalog/ui/catalog-ui-search/src/main/webapp/js/model/Query.js
- Now in Intrigue you can choose to sort by any attribute
instead of just the hardcoded 9 that exist now
@bdeining @djblue 
@millerw8
Ensure dropdown is populated, saves, etc. Confirm search results come back in the specified sort order.
https://codice.atlassian.net/browse/DDF-2894
http://ddf.slackexception.com/images/SortByAttribute.mp4
=> DDF-2894 Added sort by any attribute

broker/broker-app/src/main/resources/features.xml, catalog/ui/catalog-ui-search/yarn.lock, platform/platform-app/pom.xml, platform/platform-app/src/main/resources/features.xml, pom.xml
Fix bug introduced in camel-amqp that prevents it from starting
@ryeats 
@emmberk 
@vinamartin 
@roelens8 
@jaymcnallie
@kcwire
ensure that you can `feature:install camel-amqp` _and_ `feature:install artemis-amqp`. The order matters.
https://codice.atlassian.net/browse/DDF-3006
=> DDF-3006 Fix bug introduced in camel-amqp that prevents it from starting

distribution/docs/src/main/jdocs/content/_endpoints/cometd-endpoint-contents.adoc, distribution/docs/src/main/resources/_contents/_endpoints/cometd-endpoint-contents.adoc
updated reference to broken link in documentation. 
@clockard
@coyotesqrl
@lessarderic
@pklinef
@shaundmorris
verify link working in updated section.
[documentation.pdf](https://github.com/codice/ddf/files/1020545/documentation.pdf)
=> DDF-2824 fixed broken link in cometD docs

distribution/docs/src/main/resources/_contents/_security-framework/security-sts-ldap-claims-handler-contents.adoc, distribution/docs/src/main/resources/_contents/_security-framework/security-sts-ldap-login-contents.adoc
Quick docs fix for typos
@ricklarsen @figliold @paouelle 
[DDF-2403](https://codice.atlassian.net/browse/DDF-2403)
=> DDF-2403 Fixing small issues in the STS Ldap Login docs

distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestSpatial.java
The initial changes from this pr came from an attempt to remove flakiness in the itest regarding catalog operations. There seem to be some additional issues with reliability in terms of the underlying webservice. The test has been marked unstable to address the underlying issue. 
@bdeining @peterhuffer @jrnorth 
[Test](https://github.com/orgs/codice/teams/test) @brendan-hofmann 
@clockard
@lessarderic
Inspect the changes.
A ticket has been created to fix the underlying issues and remove the unstable flag (DDF-3032).
[DDF-3032](https://codice.atlassian.net/browse/DDF-3032)
[DDF-3000](https://codice.atlassian.net/browse/DDF-3000)
=> DDF-3000 Reducing catalog operation flakiness in itest and marking unstable

distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestSecurity.java
Adds additional security tests for TLS and Cipher Suites. Currently a WIP-PR. Will be adding similar tests for federating sources.
@brendan-hofmann @ahoffer @emanns95 
@stustison [Security](https://github.com/orgs/codice/teams/security)
@lessarderic [Test](https://github.com/orgs/codice/teams/test)
@coyotesqrl
@pklinef
=> DDF-2966 Added tls/cipher suite security tests

catalog/spatial/geocoding/spatial-geocoding-plugin/pom.xml, catalog/spatial/geocoding/spatial-geocoding-plugin/src/main/java/org/codice/ddf/spatial/geocoding/plugin/GeoCoderPlugin.java, catalog/spatial/geocoding/spatial-geocoding-plugin/src/test/groovy/org/codice/ddf/spatial/geocoding/plugin/GeoCoderPluginTest.groovy
Updated GeoCoderPlugin to correctly protect agianst null configuration updates
@rzwiefel @peterhuffer @bdeining 
@beyelerb
[DDF-3031](https://codice.atlassian.net/browse/DDF-3031)
=> (2.10.x) DDF-3031 Protect against null configuration updates in GeoCoderPlugin

platform/admin/core/admin-core-appservice/pom.xml, platform/admin/core/admin-core-appservice/src/main/java/org/codice/ddf/admin/application/service/command/AbstractProfileCommand.java, platform/admin/core/admin-core-appservice/src/main/java/org/codice/ddf/admin/application/service/command/ProfileInstallCommand.java, platform/admin/core/admin-core-appservice/src/main/java/org/codice/ddf/admin/application/service/command/ProfileListCommand.java, platform/admin/core/admin-core-appservice/src/test/java/org/codice/ddf/admin/application/service/command/AbstractProfileCommandTest.java, platform/admin/core/admin-core-appservice/src/test/java/org/codice/ddf/admin/application/service/command/ProfileInstallCommandTest.java, platform/admin/core/admin-core-appservice/src/test/java/org/codice/ddf/admin/application/service/command/ProfileListCommandTest.java, platform/admin/core/admin-core-appservice/src/test/resources/profiles/devProfile.json, platform/admin/core/admin-core-appservice/src/test/resources/profiles/invalidApp.json, platform/admin/core/admin-core-appservice/src/test/resources/profiles/invalidFeatureInstall.json, platform/admin/core/admin-core-appservice/src/test/resources/profiles/invalidFeatureUninstall.json, platform/admin/core/admin-core-appservice/src/test/resources/profiles/invalidStopBundles.json, platform/admin/core/admin-core-appservice/src/test/resources/profiles/profileWithDuplicates.json
* Adds admin:profile:list command
Adds several commands for dealing with install profiles
@brjeter @paouelle @Lambeaux 
@coyotesqrl
@lessarderic
[DDF-2823](https://codice.atlassian.net/browse/DDF-2823)
=> DDF-2823 Added profile:install command

catalog/ui/catalog-ui-search/src/main/webapp/component/input/geometry/input-geometry.view.js
Updates the wkt validator to correctly handle multipoint.
@millerw8
@bdeining 
@adimka 
Enter a location of `GEOMETRYCOLLECTION (MULTIPOINT ((-113 32), (-112 33)), MULTIPOLYGON (((10 10, 15 10, 15 15, 10 15, 10 10)), ((20 20, 25 20, 25 25, 20 25, 20 20))), POLYGON ((-20 5, -15 5, -15 -5, -20 -5, -20 5)))` and verify that no issues are found.
https://codice.atlassian.net/browse/DDF-3027
=> DDF-3027 Update wkt validator to correctly handle MultiPoint

catalog/spatial/geocoding/spatial-geocoding-plugin/pom.xml, catalog/spatial/geocoding/spatial-geocoding-plugin/src/main/java/org/codice/ddf/spatial/geocoding/plugin/GeoCoderPlugin.java, catalog/spatial/geocoding/spatial-geocoding-plugin/src/test/groovy/org/codice/ddf/spatial/geocoding/plugin/GeoCoderPluginTest.groovy
Updated GeoCoderPlugin to correctly protect agianst null configuration updates
@rzwiefel @peterhuffer @bdeining 
@beyelerb
[DDF-3031](https://codice.atlassian.net/browse/DDF-3031)
=> DDF-3031 Protect against null configuration updates in GeoCoderPlugin

broker/broker-undelivered-messages-ui/src/main/resources/WEB-INF/web.xml, catalog/admin/module/catalog-admin-module-sources/src/main/webapp/WEB-INF/web.xml, catalog/resourcemanagement/resourcemanagement-querymonitor-ui/src/main/webapp/WEB-INF/web.xml, catalog/resourcemanagement/resourcemanagement-usage-ui/src/main/webapp/WEB-INF/web.xml, catalog/spatial/geocoding/spatial-geocoding-admin-module/src/main/webapp/WEB-INF/web.xml, catalog/spatial/geowebcache/geowebcache-admin-plugin/src/main/webapp/WEB-INF/web.xml, catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/WEB-INF/web.xml, catalog/spatial/registry/registry-admin-modules/registry-admin-remote-ui/src/main/webapp/WEB-INF/web.xml, catalog/ui/catalog-ui-search/src/main/webapp/WEB-INF/web.xml, catalog/ui/search-ui/simple/src/main/webapp/WEB-INF/web.xml, catalog/ui/search-ui/simple/src/main/webapp/resources/WEB-INF/web.xml, catalog/ui/search-ui/standard/src/main/webapp/WEB-INF/web.xml, platform/admin/core/admin-core-logviewer/src/main/webapp/WEB-INF/web.xml, platform/admin/modules/admin-metrics-ui/src/main/webapp/WEB-INF/web.xml, platform/admin/modules/admin-security-certificate-ui/src/main/webapp/WEB-INF/web.xml, platform/admin/modules/admin-security-ui/src/main/webapp/WEB-INF/web.xml, platform/admin/ui/src/main/webapp/WEB-INF/web.xml, platform/error/platform-error-impl/src/main/webapp/WEB-INF/web.xml, platform/security/idp/security-idp-server/src/main/webapp/WEB-INF/web.xml, platform/solr/platform-solr-server-standalone/src/main/webapp/WEB-INF/web.xml
@garrettfreibott @ahoffer @ryeats @djblue 
@coyotesqrl
=> DDF-3015 added HTTPS enforcement to all web apps

index.html
@kcwire
@lessarderic
@pklinef
@shaundmorris
@coyotesqrl 
@clockard
=> DDF-2824 update 'latest build' link on project site.

catalog/core/catalog-core-eventcommands/pom.xml, platform/admin/core/admin-core-migration-commands/pom.xml, platform/persistence/platform-persistence-commands/src/main/java/org/codice/ddf/persistence/commands/StoreDeleteCommand.java
-Reads from command line correctly
-Adds in missing dependency that was getting pulled in through another dependency that will need to be removed with the karaf upgrade
@emmberk @clockard 
@clockard
@lessarderic
=> DDF-2132 Cleans up console commands

pom.xml
Removes the obr repository
@coyotesqrl @lessarderic 
@pklinef
@stustison
=> DDF-3058 Removed the obr repository

distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestRegistry.java
Remove unused annotation references in TestRegistry
@josephthweatt @emmberk @vinamartin 
@clockard
@lessarderic
Run TestRegistry
[DDF-2639](https://codice.atlassian.net/browse/DDF-2639)
=> DDF-2639 Remove unused annotation references in TestRegistry

catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/validation/impl/validator/SizeValidator.java, catalog/core/catalog-core-api-impl/src/test/java/ddf/catalog/validation/impl/SizeValidatorTest.java, distribution/docs/src/main/resources/_contents/_catalog-frameworks/global-attribute-validators-definition-contents.adoc
Allow size validator to be configured with the same value for min and max.
@jrnorth 
@rzwiefel 
@troymohl 
@millerw8
@shaundmorris
Run tests and itests.
[DDF-3056](https://codice.atlassian.net/browse/DDF-3056)
=> DDF-3056 allow size validator to be configured with the same value for min and max

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/event/retrievestatus/DownloadsStatusEventPublisher.java
Address a few SonarQube findings: https://sonarqube.com/project/issues?fileUuids=AVspKMhzJo2FoAtkflkY&id=ddf&resolved=false
@djblue 
@oconnormi 
@Lambeaux 
https://github.com/orgs/codice/teams/continuous-integration
@figliold 
@clockard 
Build passes
I just re-used an initial SonarQube ticket 
https://codice.atlassian.net/browse/DDF-398
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codice/ddf/2018)
=> DDF-398 Resolved SonarQube findings in DownloadsStatusEventPublisher

.gitignore
Removes erroneous pattern matching `bin`.
@brendan-hofmann @AzGoalie 
@clockard
@shaundmorris
Pull down branch and confirm that git does not show any untracked files in `bin` folders.
N/A
[DDF-3063](https://codice.atlassian.net/browse/DDF-3063)
N/A
=> DDF-3063 Removes incorrect ignore pattern from .gitignore

platform/platform-paxweb-jettyconfig/src/main/java/org/codice/ddf/security/session/AttributeSharingHashSessionIdManager.java, platform/platform-paxweb-jettyconfig/src/main/resources/jetty.xml, platform/platform-paxweb-jettyconfig/src/test/java/org/codice/ddf/security/session/TestAttributeSharingHashSessionIdManager.java
… to avoid a hack in pax web
@jlcsmith @beyelerb @millerw8 
@coyotesqrl
@stustison
=> DDF-3060 changed to extend jetty's impl instead of the abstract class to avoid a hack in pax web

platform/security/sts/security-sts-realm/src/main/java/ddf/security/realm/sts/AbstractStsRealm.java
@jlcsmith @beyelerb @millerw8 
@coyotesqrl
@stustison
=> DDF-3061 synchronized the session renewal and added a cache to return the last returned token

platform/admin/ui/src/main/webapp/less/configuration/style.less
@mcalcote 
@djblue 
@clockard 
@lessarderic 
1. Build ddf.
2. Open Admin Console, select System.
3. Click on various configuration names. In the modal, the checkboxes should be aligned as shown in the picture below.
4. Repeat steps 2-3 for Firefox, Chrome, and IE10
[DDF-3066](https://codice.atlassian.net/browse/)
=> DDF-3066 Align Checkboxes in System Section of Admin Console

catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/view/Registry.view.js, catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/less/styles.less, catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/templates/deleteNodeModal.handlebars, catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/templates/nodeList.handlebars, catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/templates/regenerateSourcesModal.handlebars
Creates "delete all" and "select all" options in the admin's Registry Application.
* The "Regenerate Sources" modal now has a **Select All** checkbox.
* Added a small trashcan for local and remote nodes to delete all nodes in their respective table.
* "deleteNodeModal" gives specific messages for whether it is deleting a single node or multiple nodes.
@mcalcote 
@vinamartin 
@clockard
@coyotesqrl 
1. Build DDF
2. Launch admin console, add Registry Application to the admin's Active Applications.
3. Enter Registry, populate the Additional Local Nodes table and Remote Nodes table with nodes.
4. Verify that the **Select All** checkbox in Regenerate Sources will select all nodes and regenerate them.
5. Try to delete all nodes for both Local Nodes …
=> DDF-3055 "Select All" options on the Registry Remote Nodes & Regenerate Sources screens

distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFtp.java
Fixes minor TechDebt in TestFtp.
@emmberk @vinamartin @josephthweatt @ricklarsen
[Test](https://github.com/orgs/codice/teams/test) @clockard 
@clockard
@lessarderic
Build iTests successfully
[DDF-3085](https://codice.atlassian.net/browse/DDF-3085)
=> DDF-3085 Fixed minor techDebt in TestFtp

PULL_REQUEST_TEMPLATE
Adds an emoji legend to the PR template so that PR creators + reviewers can use these emojis when reviewing PRs. **Looking for feedback on wording/phrasing in the legend.** 
In addition, removed the section on component teams as it is currently unclear and frequently deleted.
@rzwiefel @dcruver @Lambeaux @josephthweatt @brendan-hofmann @tbatie @garrettfreibott 
@clockard
@coyotesqrl
@lessarderic
@kcwire
=> DDF-3037 Adds emoji legend to PR template

distribution/docs/src/main/jdocs/content/_endpoints/catalog-rest-endpoint-contents.adoc, distribution/docs/src/main/jdocs/content/_endpoints/csw-endpoint-contents.adoc, distribution/docs/src/main/resources/_contents/_endpoints/catalog-rest-endpoint-contents.adoc, distribution/docs/src/main/resources/_contents/_endpoints/csw-endpoint-contents.adoc
Adds documentation to CSW and ReST endpoints on various error conditions.
@ricklarsen 
@brianfelix 
@kcwire
@millerw8
Build the distribution/docs and validate the CSW Endpoint and ReST endpoint documentation in the `documentation.pdf` and `jdocumentation.pdf`
https://codice.atlassian.net/browse/DDF-3086
=> DDF-3086 Error examples added to CSW and ReST endpoint documentation

platform/security/sts/security-sts-ldaplogin/src/main/java/ddf/ldap/ldaplogin/SslLdapLoginModule.java
@lessarderic 
@coyotesqrl
@stustison
=> DDF-3087 improved trace and debug logging in LDAP login module

catalog/core/catalog-core-camelcomponent/pom.xml, catalog/pom.xml, catalog/transformer/catalog-transformer-pptx/pom.xml, catalog/transformer/catalog-transformer-tika-input/src/test/java/ddf/catalog/transformer/input/tika/TikaInputTransformerTest.java, catalog/ui/catalog-ui-search/pom.xml, dependency-check-maven-config.xml, distribution/docs/src/main/resources/_contents/_dependency-list/ddf-dependency-list.adoc, distribution/sdk/artemis-sandbox/pom.xml, distribution/sdk/pom.xml, distribution/test/itests/test-itests-common/pom.xml, gitsetup/pom.xml, libs/mpeg-transport-stream/pom.xml, libs/owasp-diff-runner/pom.xml, platform/admin/core/admin-core-appservice/pom.xml, platform/admin/core/admin-core-migration-commands/pom.xml, platform/metrics/platform-metrics-reporting/pom.xml, platform/mime/core/platform-mime-core-impl/pom.xml, platform/platform-paxweb-jettyconfig/pom.xml, platform/pom.xml, platform/security/pdp/security-pdp-authzrealm/pom.xml, platform/security/security-services-app/src/main/resources/features.xml, pom.xml
@emmberk @ryeats 
@coyotesqrl
@lessarderic
Verify build passes and basic ddf functionality
[DDF-3054](https://codice.atlassian.net/browse/DDF-3054)
=> DDF-3054 Fix owasp dependency issues.

PULL_REQUEST_TEMPLATE
Add Rick Larsen to PR template
@codice/docs 
@ricklarsen 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codice/ddf/2069)
=> DDF-3037 Added Rick Larsen as docs committer

catalog/ui/catalog-ui-search/package.json, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/QueryApplication.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/geofeature/BoundingBoxFeature.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/geofeature/Coordinate.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/geofeature/Feature.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/geofeature/FeatureService.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/geofeature/PointRadiusFeature.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/geofeature/PolygonFeature.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/geofeature/StubFeatureService.java, catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/ui/catalog-ui-search/src/main/webapp/component/component.less, catalog/ui/catalog-ui-search/src/main/webapp/component/input/autocomplete/input-autocomplete.hbs, catalog/ui/catalog-ui-search/src/main/webapp/component/input/autocomplete/input-autocomplete.less, catalog/ui/catalog-ui-search/src/main/webapp/component/input/autocomplete/input-autocomplete.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/location-old/location-old.hbs, catalog/ui/catalog-ui-search/src/main/webapp/component/location-old/location-old.js, catalog/ui/catalog-ui-search/src/main/webapp/component/location-old/location-old.less, catalog/ui/catalog-ui-search/src/main/webapp/component/location-old/location-old.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/property/property.js, catalog/ui/catalog-ui-search/src/main/webapp/component/value/value.view.js, catalog/ui/catalog-ui-search/src/main/webapp/js/widgets/cesium.bbox.js, catalog/ui/catalog-ui-search/src/main/webapp/js/widgets/openlayers.bbox.js, catalog/ui/catalog-ui-search/src/main/webapp/styles/styles.less, catalog/ui/catalog-ui-search/webpack/config/base.js, catalog/ui/catalog-ui-search/yarn.lock
- Adds a "Keyword" button to the search UI that queries a service for geographic place names. Upon choosing a name from the list, the corresponding shape (polygon, bounding box, etc.) will be loaded into the form.
- Adds the interface for the keyword search service, and provides a stub implementation that always returns one each of a polygon, bounding box, and point/radius location. The real implementation will be in a forthcoming PR.
Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged)?
@rzwiefel 
@millerw8
1. Open search UI and edit an existing search
2. Choose "Somewhere Specific" for the "Located" filed and select the "Keyword" tab.
3. Type 2 or …
=> DDF-3069 Geospatial search by named location (keyword)

catalog/admin/module/catalog-admin-module-maplayers/pom.xml, catalog/admin/module/catalog-admin-module-maplayers/src/main/resources/WEB-INF/web.xml
Updates web.xml for map-layers to prevent unnecessary exceptions in logs.
@tbatie 
@peterhuffer 
@clockard
@coyotesqrl
Build bundle, clear logs, hot deploy, make sure there are no exceptions in the logs.
[DDF-3038](https://codice.atlassian.net/browse/DDF-3038)
=> DDF-3038 Updated web.xml to prevent unnecessary exceptions in logs.

platform/security/idp/security-idp-client/src/main/java/org/codice/ddf/security/idp/client/IdpLogoutActionProvider.java, platform/security/platform-security-core-api/src/main/java/ddf/security/SubjectUtils.java, platform/security/platform-security-core-api/src/test/java/ddf/security/SubjectUtilsTest.java, platform/security/servlet/security-servlet-logout/src/main/java/org/codice/ddf/security/servlet/logout/LogoutService.java, platform/security/servlet/security-servlet-logout/src/main/webapp/js/logout-response.js
Backport of #2051 
@lessarderic
@stustison
=> (2.10.x) DDF-3070 Allow the ability to logout if currently guest.

distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestSecurity.java
Fixes a race condition in TestSecurity.testCertificateGeneratorService when the system subject expires before calling stopService
@brendan-hofmann @emanns95 @jhunzik
@stustison
=> DDF-3097 Fixed race condition in TestSecurity.testCertificateGeneratorService

distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/opensearch/OpenSearchTestCommons.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalog.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalogValidation.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFederation.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFtp.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestSpatial.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestConfiguration.java
Refactor itests open search query code to make it re-usable
@tbatie @brendan-hofmann
@figliold
@lessarderic
Verify itests pass with maven clean install
[](https://jira.di2e.net/browse/DIB-3317)
=> DDF-3022 Refactor itests open search query code to make it re-usable

distribution/docs/src/main/resources/_contents/_resources/content-directory-monitor-contents.adoc
Update the documentation for the content directory monitor to accurately reflect the process adding for multi-valued attribute overrides.
@ahoffer 
@shaundmorris
If the current docs are followed, the multiple values will not all get stored on the metacard.
[](https://codice.atlassian.net/browse/DDF-2710) …
=> DDF-2710 Update CDM multi-value overrides docs

catalog/core/catalog-core-directorymonitor/pom.xml, catalog/core/catalog-core-directorymonitor/src/test/java/org/codice/ddf/catalog/content/monitor/AbstractComponentTest.java, catalog/core/catalog-core-directorymonitor/src/test/java/org/codice/ddf/catalog/content/monitor/ContentDirectoryMonitorIT.java
Allows component tests to use the module that they're testing without having them pre-compiled.
@clockard @brendan-hofmann 
@clockard
@lessarderic
=> DDF-3050 Fixed dependency issue for directory monitor

Jenkinsfile
Update the maven settings config file used during the deploy stage.
@codice/build 
@clockard @lessarderic
Inspect
The current .xml file is indeed the name of the config, but the ID is used to find the proper settings during the build stages.
[DDF-2920](https://codice.atlassian.net/browse/DDF-2920)
=> DDF-2920 Updated Deploy step settings config

catalog/ui/catalog-ui-search/src/main/webapp/index.html, catalog/ui/catalog-ui-search/src/main/webapp/js/CustomElements.js, catalog/ui/catalog-ui-search/src/main/webapp/js/application.js, catalog/ui/catalog-ui-search/src/main/webapp/properties.js, catalog/ui/catalog-ui-search/src/main/webapp/styles/vars.less, distribution/docs/src/main/resources/_contents/_tables/org.codice.ddf.catalog.ui.config-table-contents.adoc, distribution/docs/src/main/resources/_contents/_using/using-catalog-search-ui-contents.adoc, pom.xml
- Updates product name from Catalog to Intrigue.
- Updates namespace from ddf- to intrigue-.
- Updates .html to be .text in application.js to remove injection opportunity.
@pklinef 
@rzwiefel 
@djblue 
Go to the UI and verify that the name has been updated.  Verify that the namespace change had no adverse effects.
https://codice.atlassian.net/browse/DDF-2822
=> DDF-2822 Update product name from Catalog to Intrigue

catalog/catalog-app/pom.xml, catalog/spatial/csw/spatial-csw-schema-bindings/pom.xml, catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-schema-bindings/pom.xml, pom.xml
Updates pom files to not deploy duplicate source jars when running a release. This caused a failure in nexus repositories that did not allow updates. Also updates the artifactId from catalog-plugin-metacardbackup to catalog-plugin-metacardbackup-storage-common based on changes in https://github.com/codice/ddf/pull/2012.
@vinamartin 
@emmberk 
@taz77 
@clockard
@shaundmorris
Download and unzip nexus: https://www.sonatype.com/download-oss-sonatype
Run nexus: ./\<nexus location\>/bin/nexus start
Update .m2/settings.xml to include:
```
<server>
<id>releases</id>
<username>admin</username>
<password>admin123</password>
</server>
```
Prepare the release `mvn release:prepare -Prelease -DlocalCheckout=true -DignoreSnapshots=true` and accept all the defaults …
=> DDF-3080 Updates pom files to not deploy duplicate source jars during release

Documentation-versions.html, index.html
updates codice.org/ddf & documentation for latest release version.
@mcalcote @vinamartin @Lambeaux @jrnorth @ahoffer 
@clockard
@coyotesqrl
@lessarderic
@pklinef
@shaundmorris
verify version numbers updated & links point to correct versions.
=> DDF-2748 updated gh-page for 2.10.3 release

distribution/docs/src/main/jdocs/content/_quickstart/quickstart-ingesting-contents.adoc, distribution/docs/src/main/jdocs/content/_running/ingesting-contents.adoc, distribution/docs/src/main/jdocs/content/_using/using-catalog-search-ui-contents.adoc, distribution/docs/src/main/resources/_contents/_quickstart/quickstart-ingesting-contents.adoc, distribution/docs/src/main/resources/_contents/_running/ingesting-contents.adoc, distribution/docs/src/main/resources/_contents/_using/using-catalog-search-ui-contents.adoc
updates documentation about ingest to include ingest from Intrigue UI.
@mcalcote @vinamartin @Lambeaux @jrnorth @ahoffer 
@clockard
@coyotesqrl
@lessarderic
@pklinef
@shaundmorris
verify new content is accurate
builds successfully
[DDF-3078](https://codice.atlassian.net/browse/DDF-3078)
=> DDF-3078 updated UI ingest documentation.

catalog/core/catalog-core-standardframework/pom.xml
Update coverage numbers causing build failures in standard framework
@adimka 
@ryeats 
@coyotesqrl
@lessarderic
CI Build
Originates from https://github.com/codice/ddf/pull/2115
=> DDF-3127 Update coverage numbers for standard framework

broker/broker-app/src/main/resources/features.xml, broker/broker-route-manager/src/test/resources/test-route.xml, broker/broker-topic-logger/src/main/resources/OSGI-INF/blueprint/blueprint.xml, broker/broker-undelivered-messages-ui/src/main/java/org/codice/ddf/broker/ui/UndeliveredMessages.java, broker/broker-undelivered-messages-ui/src/main/java/org/codice/ddf/broker/ui/UndeliveredMessagesMBean.java, broker/broker-undelivered-messages-ui/src/main/webapp/index.js, broker/broker-undelivered-messages-ui/src/test/java/org/codice/ddf/broker/ui/UndeliveredMessagesTest.java, distribution/ddf-common/src/main/resources/etc/artemis-backup.xml, distribution/ddf-common/src/main/resources/etc/artemis.xml, distribution/docs/src/main/resources/_contents/_broker/configure-ha.adoc, distribution/sdk/artemis-sandbox/src/main/java/sdk.example.route/AmqpProducerConsumerExample.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestMessageBroker.java, platform/platform-app/pom.xml, platform/platform-app/src/main/resources/features.xml, pom.xml
Upgrades Artemis to 2.1.0. 
-Artemis fixed a glitch that required appending JMS prefixes: "jms.queue" or "jms.topic" to queue/topic names when brokering messages via AMQP, now it's not necessary to append the JMS prefixes. Removed the JMS prefixes for the DLQ and Expiry queues defined in the artemis.xml.
-Uncommented the password-codec and mask-password elements in the artemis.xml to allow password encryption within the file. (There was a bug in the previous version of artemis that prevented us from doing this)
@ryeats 
@jrnorth 
@derekwilhelm 
@jaymcnallie
@kcwire
@pklinef
-Run a full build. Make sure itests pass. 
-Start DDF, and install all artemis features to verify they can start up.
-Manually test that failover works.
[DDF-3029](https://codice.atlassian.net/browse/) …
=> DDF-3029 Upgrade Artemis to 2.1.0

catalog/ui/search-ui-app/src/main/resources/features.xml
Allows search ui configuration to be overridden in the /etc directory
@brendan-hofmann @vinamartin @emmberk 
@coyotesqrl …
=> DDF-3131 Update Search-Ui-App to allow overrides

catalog/admin/module/catalog-admin-module-maplayers/pom.xml, catalog/admin/module/catalog-admin-module-maplayers/src/main/java/org/codice/ddf/catalog/admin/plugin/MaplayersPlugin.java, catalog/admin/module/catalog-admin-module-maplayers/src/main/webapp/map-layers/index.js, catalog/admin/module/catalog-admin-module-maplayers/src/main/webapp/map-layers/reducer.js, catalog/admin/module/catalog-admin-module-maplayers/src/main/webapp/map-layers/validate.spec.js
- rename `May Layers ` to `Map Layers`
- display valid alpha values in label
- detect invalid map layers configuration and allow users to fix or
discard
- added yarn ignore proxy setting on build
@tbatie 
@lessarderic
- Full build of `catalog-admin-module-maplayers` module
- Insert invalid map layers config through config admin and make sure map layers ui allows users to fix or discard those configs
[DDF-3038](https://codice.atlassian.net/browse/DDF-3038) …
=> DDF-3038 several map-layer configuration ui improvements

distribution/ddf-common/src/main/resources/etc/system.properties, platform/security/sts/security-sts-server/src/main/java/ddf/security/sts/SubjectDNConstraintsInterceptor.java, platform/security/sts/security-sts-server/src/test/java/ddf/security/sts/SubjectDNConstraintsInterceptorTest.java
@ahoffer @lessarderic @brendan-hofmann 
@clockard
@stustison
=> DDF-3101 changed regex to check for hostname only connection to STS, added test for constraint interceptor

distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/callables/GetConfigurationProperties.java, platform/admin/admin-app/pom.xml, platform/admin/admin-app/src/main/resources/features.xml, platform/admin/admin-configuration-passwordencryption/pom.xml, platform/admin/admin-configuration-passwordencryption/src/main/java/org/codice/ddf/admin/configuration/password/encryption/PasswordEncryptingPersistenceManager.java, platform/admin/admin-configuration-passwordencryption/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/admin/admin-configuration-passwordencryption/src/test/java/org/codice/ddf/admin/configuration/password/encryption/PasswordEncryptingPersistenceManagerTest.java, platform/admin/pom.xml, platform/pom.xml
@pklinef @lessarderic @beyelerb  @brendan-hofmann 
https://github.com/orgs/codice/teams/security/members
@coyotesqrl
@stustison
[DDF-3088](https://codice.atlassian.net/browse/DDF-3088)
=> DDF-3088 added password encryption/decryption to configuration files that are stored on disk

platform/security/security-services-app/pom.xml, platform/security/security-services-app/src/main/resources/features.xml, platform/security/servlet/pom.xml, platform/security/servlet/security-servlet-whoami/pom.xml, platform/security/servlet/security-servlet-whoami/src/main/java/org/codice/ddf/security/servlet/whoami/WhoAmI.java, platform/security/servlet/security-servlet-whoami/src/main/java/org/codice/ddf/security/servlet/whoami/WhoAmIServlet.java, platform/security/servlet/security-servlet-whoami/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/security/servlet/security-servlet-whoami/src/test/groovy/org/codice/ddf/security/servlet/whoami/SubjectSpecification.groovy, platform/security/servlet/security-servlet-whoami/src/test/groovy/org/codice/ddf/security/servlet/whoami/WhoAmIServletSpec.groovy, platform/security/servlet/security-servlet-whoami/src/test/groovy/org/codice/ddf/security/servlet/whoami/WhoAmISpec.groovy
Adds `/whoami` context to be able to see information about subjects for all realms that are logged into the current session.
@tbatie 
@brjeter 
@coyotesqrl
@stustison
Goto [https://localhost:8993/whoami](https://localhost:8993/whoami) and verify information matches details for currently logged in user.  Test with guest, local account, and LDAP user.
[DDF-3138](https://codice.atlassian.net/browse/DDF-3138)
```
{
"idp": {
"name": "tstark",
"displayName": "tstark",
"email": "tstark@example.com",
"notOnOrAfter": "2017-07-07T10:22:40.935Z",
"notBefore": "2017-07-07T09:52:40.935Z",
"expiresIn": "27 minutes 54 seconds",
"issuer": "localhost",
"isGuest": false,
"authnContextClasses": [
"urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport"
],
"claims": { …
```
=> DDF-3138 Create a service to see user session information.

PULL_REQUEST_TEMPLATE
Add Ben as committer to PR template
@bdeining
[](https://codice.atlassian.net/browse/DDF-3037)
=> DDF-3037 Added Ben Deininger as committer to PR template

CODEOWNERS
=> added stustison to codeowners

catalog/spatial/geocoding/spatial-geocoding-plugin/pom.xml
Adds missing embedded dependencies in spatial-geocoding-plugin bundle.
@paouelle 
@coyotesqrl
Full build with integration tests.
[DDF-3158](https://codice.atlassian.net/browse/DDF-3158)
=> DDF-3158 Missing import in Spatial Geocoding plugin causes integration test failure

catalog/spatial/registry/registry-api-impl/src/main/java/org/codice/ddf/registry/api/impl/RegistryStorePublisher.java
Changing the remote registry url will publish to the new url.
@mcalcote @vinamartin @emmberk 
@clockard
@lessarderic 
To Test:
* Build the DDF
* Setup three DDFs, one as a registry (registry), the others as remote DDFs (ddf1, ddf2).
* Configure the first remote DDF's Remote Registry CSW endpoint to point at itself, e.g., https://ddf1:8993/services/csw
* Update the first remote DDF's Remote Registry CSW endpoint to point at the registry, e.g, https://registry:8993/services/csw
* Update the second remote DDF's Remote Registry CSW endpoint to point at the registry, e.g., https://registry:8993/services/csw
* Refresh the Catalog App's Node information tab on all the DDFs.
* Notice ddf1 should …
=> DDF-3141 Publish to remote registry when registry url is updated

distribution/ddf-common/src/main/resources/bin/setenv, distribution/ddf-common/src/main/resources/bin/setenv.bat, distribution/docs/src/main/jdocs/content/_configuring/environment-hardening-contents.adoc, distribution/docs/src/main/jdocs/content/_running/starting-intro-contents.adoc, distribution/docs/src/main/resources/_contents/_running/starting-intro-contents.adoc, distribution/docs/src/main/resources/_contents/_securing/environment-hardening-contents.adoc
Prevents connections to DDF's JMX 
@emmberk
@vinamartin
@josephthweatt
@mcalcote
@clockard
@coyotesqrl 
1. Build & run DDF
3. In another Terminal, run `jconsole`
4. In JConsole, attempt to connect with the _Local Process_  by double clicking on org.apache.karaf.main.Main
5. See that you are **not** able to connect
6. In JConsole, attempt to connect with the _Remote Process_ using:
- service:jmx:rmi:///jndi/rmi://localhost:1099/karaf-root
- credentials are admin/admin
7. See that you are **not** able to connect
8. In the terminal run `ps -ax | grep org.apache.karaf.main.Main`
9. See that arg `-Dcom.sun.management.jmxremote` is no longer used when starting DDF and that `-XX:+DisableAttachMechanism` is used to prevent connections
The initial documentation and ticket information to disable …
=> DDF-3111 Prevent connections to JMX

distribution/docs/src/main/jdocs/content/_endpoints/csw-endpoint-contents.adoc, distribution/docs/src/main/resources/_contents/_endpoints/csw-endpoint-contents.adoc
Updated CSW Transaction Update request examples to include the ogc namespace when using a constraint
@bdeining 
@troymohl 
@ricklarsen 
@jlcsmith 
[DDF-3113](https://codice.atlassian.net/browse/DDF-3113)
=> DDF-3113 Updated CSW Transaction Update request examples to include ogc namespace

catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswExceptionMapper.java
Adds additional information for CSW errors. Example:
`<ows:Exception exceptionCode="MissingParameterValue">
<ows:ExceptionText>Error handling Request: Unable to locate a transformer for id = blahblah
---- Debugging information ----
message             : Unable to locate a transformer for id = blahblah
class               : ddf.catalog.data.impl.MetacardImpl
required-type       : ddf.catalog.data.impl.MetacardImpl
converter-type      : Proxy9bad5553_915d_45e1_ae8f_4ef3c04ea4fa
path                : /csw:Transaction/csw:Insert/DOCUMENT
line number         : 7
class[1]            : org.codice.ddf.spatial.ogc.csw.catalog.common.transaction.CswTransactionRequest
converter-type[1]   : org.codice.ddf.spatial.ogc.csw.catalog.converter.TransactionRequestConverter
version             : not …
=> DDF-3157 Improve CSW error reporting

distribution/docs/src/main/jdocs/content/_configuring/managing-certificates-contents.adoc, distribution/docs/src/main/jdocs/content/_quickstart/quickstart-certificates.adoc, distribution/docs/src/main/jdocs/content/_quickstart/quickstart-configuring-contents.adoc
- updates certificate-configuration documentation. 
- relocates all instructions for self-signed certificates to the quick start guide.
@mcalcote @vinamartin @Lambeaux @jrnorth @ahoffer 
@clockard
@coyotesqrl
@lessarderic
@pklinef
@shaundmorris
@stustison
review certificate documentation for accuracy/completeness. Generated PDF attached.
[DDF-3083](https://codice.atlassian.net/browse/DDF-3083)
[jdocumentation.pdf](https://github.com/codice/ddf/files/1106850/jdocumentation.pdf) …
=> DDF-3083 updated documentation on certificates.

distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/AbstractIntegrationTest.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/ContainerPerSuiteItestSuite.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestSecurityAuditPlugin.java
@clockard @blen-desta 
@coyotesqrl
@stustison
=> DDF-2906 fixed ordering of integration tests and HTTP endpoint wait conditions

distribution/docs/src/main/jdocs/content/_configuring/catalog-filtering-contents.adoc, distribution/docs/src/main/jdocs/content/_configuring/configuring-web-context-policy-manager-contents.adoc, distribution/docs/src/main/jdocs/content/_configuring/environment-hardening-contents.adoc, distribution/docs/src/main/jdocs/content/_configuring/hardening-user-access-contents.adoc, distribution/docs/src/main/jdocs/content/_configuring/managing-certificates-contents.adoc, distribution/docs/src/main/jdocs/content/_installing/controlling-file-system-access-contents.adoc, distribution/docs/src/main/resources/_contents/_installing/controlling-file-system-access-contents.adoc, distribution/docs/src/main/resources/_contents/_securing/catalog-filtering-contents.adoc, distribution/docs/src/main/resources/_contents/_securing/configuring-web-context-policy-manager-contents.adoc, distribution/docs/src/main/resources/_contents/_securing/environment-hardening-contents.adoc, distribution/docs/src/main/resources/_contents/_securing/hardening-user-access-contents.adoc, distribution/docs/src/main/resources/_contents/_securing/managing-certificates-contents.adoc, distribution/docs/src/main/resources/_contents/_security-framework/security-pdp-authz-realm-contents.adoc
@paouelle @figliold 
@stustison
[DDF-3155](https://codice.atlassian.net/browse/DDF-3155)
=> DDF-3155 Fixing a few minor issues in the hardening guide

catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/model/Node.js, catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/view/Registry.view.js, catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/less/styles.less, catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/templates/clientServerModal.handlebars, catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/templates/nodeList.handlebars, catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/templates/nodeRow.handlebars, catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/templates/registryPage.handlebars, catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/templates/subscriptionFilterModal.handlebars, catalog/spatial/registry/registry-common/src/main/java/org/codice/ddf/registry/common/RegistryConstants.java, catalog/spatial/registry/registry-federation-admin-api/src/main/java/org/codice/ddf/registry/federationadmin/internal/FederationAdminMBean.java, catalog/spatial/registry/registry-federation-admin-impl/src/main/java/org/codice/ddf/registry/federationadmin/impl/AdminHelper.java, catalog/spatial/registry/registry-federation-admin-impl/src/main/java/org/codice/ddf/registry/federationadmin/impl/FederationAdmin.java, catalog/spatial/registry/registry-federation-admin-impl/src/test/java/org/codice/ddf/registry/federationadmin/impl/AdminHelperTest.java, catalog/spatial/registry/registry-federation-admin-impl/src/test/java/org/codice/ddf/registry/federationadmin/impl/FederationAdminTest.java, catalog/spatial/registry/registry-federation-admin-service-impl/src/main/java/org/codice/ddf/registry/federationadmin/service/impl/IdentityNodeInitialization.java, catalog/spatial/registry/registry-policy-plugin/src/main/java/org/codice/ddf/registry/policy/RegistryPolicyPlugin.java, catalog/spatial/registry/registry-policy-plugin/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/spatial/registry/registry-policy-plugin/src/test/java/org/codice/ddf/registry/policy/RegistryPolicyPluginTest.java, distribution/ddf-common/src/main/resources/etc/system.properties
Add ability to set filtering/policy configurations from the admin ui node tab
@mcalcote @emmberk @vinamartin 
@coyotesqrl
@figliold
Verify filtering/client mode work between to registries. 
[DDF-3124](https://codice.atlassian.net/browse/DDF-3124)
Changed buttons in upper right to be icons. Added filter icon to rows that are filtered from subscriptions
New dropdown when settings gear is clicked
Dialog for filtering subscription nodes
Dialog for changing registry modes …
=> DDF-3124 Add ability to set filtering/policy configurations from the admin ui node tab

catalog/transformer/catalog-transformer-pdf/src/main/java/ddf/catalog/transformer/input/pdf/PdfInputTransformer.java, catalog/transformer/catalog-transformer-tika-input/src/main/java/ddf/catalog/transformer/input/tika/TikaInputTransformer.java
@clockard @spearskw  @brendan-hofmann @pklinef 
@coyotesqrl
@jlcsmith
@stustison
=> DDF-3178 reduced the number of redundant memory copies that the tika input transformer was doing

platform/security/cas/security-cas-client/pom.xml, platform/security/cas/security-cas-client/src/main/java/org/codice/ddf/security/handler/cas/CasHandler.java, platform/security/core/security-core-impl/src/main/java/ddf/security/http/impl/HttpSessionFactory.java, platform/security/core/security-core-impl/src/main/java/ddf/security/listener/AuditingHttpSessionListener.java, platform/security/filter/security-filter-login/src/main/java/org/codice/ddf/security/filter/login/LoginFilter.java, platform/security/filter/security-filter-login/src/test/java/org/codice/ddf/security/filter/login/LoginFilterTest.java
@SmithJosh @pklinef @ahoffer 
@coyotesqrl
@stustison
=> DDF-3168 hashed some inputs to the audit logs

catalog/transformer/catalog-transformer-pdf/pom.xml, catalog/transformer/catalog-transformer-pdf/src/main/java/ddf/catalog/transformer/input/pdf/PdfInputTransformer.java
Fixes a plaintext parsing issue
@glenhein
@jlcsmith
@stustison
This had broken one itest in the downstream Alliance project. A build/run of that would confirm that it is resolved.
N/A
[DDF-3177](https://codice.atlassian.net/browse/DDF-3177)
N/A
- ❗ …
=> DDF-3177 Fixes a problem where a bytesource on a closed FBOS was being passed around

catalog/core/catalog-core-api/src/main/java/ddf/catalog/transform/QueryFilterTransformer.java
This PR adds a QueryFilterTransformer interface.
@troymohl 
@kcwire 
@millerw8
A full build should suffice
https://codice.atlassian.net/wiki/display/DDF/QueryFilterTransformer+Design
[DDF-3190](https://codice.atlassian.net/browse/DDF-3190) …
=> DDF-3190 Added QueryFilterTransformer Interface

catalog/transformer/catalog-transformer-zip/src/main/java/org/codice/ddf/catalog/transformer/zip/ZipValidator.java, distribution/ddf-common/src/main/resources/etc/ws-security/issuer/encryption.properties, distribution/ddf-common/src/main/resources/etc/ws-security/issuer/signature.properties, distribution/ddf-common/src/main/resources/etc/ws-security/server/encryption.properties, distribution/ddf-common/src/main/resources/etc/ws-security/server/signature.properties, platform/platform-app/pom.xml, platform/platform-app/src/main/resources/features.xml, platform/platform-crypto-provider/pom.xml, platform/platform-crypto-provider/src/main/java/org/apache/wss4j/common/crypto/MerlinExtension.java, platform/pom.xml, platform/security/filter/security-filter-login/pom.xml, platform/security/filter/security-filter-login/src/main/java/org/codice/ddf/security/filter/login/LoginFilter.java, platform/security/sts/security-sts-realm/pom.xml, platform/security/sts/security-sts-realm/src/main/java/ddf/security/realm/sts/AbstractStsRealm.java
@jlcsmith @beyelerb @SmithJosh 
@coyotesqrl
@stustison
=> DDF-3187 added a new Merlin class that handles name constraints properly

pom.xml
@mcalcote @emmberk @josephthweatt @alexaabrd @tbatie @Lambeaux @emanns95 
@clockard
@shaundmorris 
=> DDF-2824: Fixes typographical error

platform/admin/admin-configuration-configinstaller/src/test/java/org/codice/ddf/admin/configuration/FelixConfigTest.java
Fixes a minor pathing issue in unit tests. 
@mcalcote 
@brjeter 
@paouelle 
@figliold 
@shaundmorris
Windows build required. 
Stuff broke. 
=> DDF-3148 Fix windows build

platform/security/platform-security-core-api/src/main/java/ddf/security/samlp/SimpleSign.java
Fixes a possible nullpointer in Signature Validtation
@coyotesqrl
@stustison
https://codice.atlassian.net/browse/DDF-3183
=> DDF-3183 - Fix possible nullpointer in signature validation

distribution/test/itests/README.md
Added the command for testing multiple classes.
Updates the README.md for itests to include the command for executing multiple test classes.
@AzGoalie 
@emanns95 
@shaundmorris
=> DDF-2857 Update itest README.md to include executing multiple test classes

Jenkinsfile
Specifying JAVA_HOME for windows builds, adjusting cron statement to avoid overlapping deployments, adding retry to all scm operations.
@codice/build 
@clockard @shaundmorris
Run the pipeline build in a test jenkins environment and confirm the changes compile/operate as expected. Inspect the java_home change and make sure the windows path is updated correctly.
See recent jenkins failures for origin of these changes.
=> DDF-2969 Updating Jenkinsfile for various build improvements

platform/solr/platform-solr-server-standalone/src/main/webapp/css/angular/stream.css, platform/solr/platform-solr-server-standalone/src/main/webapp/js/angular/controllers/stream.js, platform/solr/platform-solr-server-standalone/src/main/webapp/partials/stream.html
Adds missing streams files (missed untracked files from previous commit) from the Solr 6.6.0 web application
@adimka 
@codice/solr 
@bdeining
@pklinef
[DDF-3195](https://codice.atlassian.net/browse/DDF-3195)
=> DDF-3195 Added stream files for the Solr 6.6.0 web application

broker/broker-undelivered-messages-ui/yarn.lock, catalog/admin/module/catalog-admin-module-sources/yarn.lock, catalog/resourcemanagement/resourcemanagement-querymonitor-ui/yarn.lock, catalog/resourcemanagement/resourcemanagement-usage-ui/yarn.lock, catalog/spatial/geocoding/spatial-geocoding-admin-module/yarn.lock, catalog/spatial/geowebcache/geowebcache-admin-plugin/yarn.lock, catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/yarn.lock, catalog/spatial/registry/registry-admin-modules/registry-admin-remote-ui/yarn.lock, catalog/ui/search-ui/standard/yarn.lock, platform/admin/core/admin-core-logviewer/yarn.lock, platform/admin/modules/admin-metrics-ui/yarn.lock, platform/admin/modules/admin-security-certificate-ui/yarn.lock, platform/admin/modules/admin-security-ui/yarn.lock, platform/admin/ui/yarn.lock, platform/error/platform-error-impl/yarn.lock, platform/security/handler/security-handler-guest/yarn.lock, platform/security/idp/security-idp-server/yarn.lock
Updates yarn.lock files that are out of sync with their corresponding package.json.
@emanns95 
@djblue 
@pklinef 
@stustison
A full build of DDF should succeed and not cause any yarn.lock files to be flagged as changed by git.
https://codice.atlassian.net/browse/DDF-3214
=> DDF-3214 Update yarn.lock files

catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/model/Node.js, catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/view/NodeModal.view.js
Fixes a couple of 'success' callbacks that were removed with the latest version of jquery.
@mcalcote @emmberk @vinamartin 
@bdeining 
@coyotesqrl
Install DDF with the registry and add a secondary node. Verify that after clicking the 'Add' button that the add dialog closes. Now delete that same secondary node and verify that the delete dialog closes after clicking 'Delete'
[DDF-3103](https://codice.atlassian.net/browse/DDF-3103) …
=> DDF-3103 Fix registry ajax callbacks after jquery version upgrade.

catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/util/impl/ResultIterable.java
@AzGoalie 
@rzwiefel 
@bdeining
@coyotesqrl
[DDF-3034](https://codice.atlassian.net/browse/DDF-3034)
=> DDF-3034 Updated ResultIterable log message to exclude 0

platform/admin/ui/src/main/webapp/js/views/configuration/ConfigurationEdit.view.js, platform/admin/ui/src/main/webapp/templates/configuration/textTypeList.handlebars, platform/security/idp/security-idp-client/src/main/java/org/codice/ddf/security/idp/client/IdpHandler.java, platform/security/idp/security-idp-client/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/security/idp/security-idp-client/src/main/resources/OSGI-INF/metatype/metatype.xml, platform/security/idp/security-idp-client/src/test/java/org/codice/ddf/security/idp/client/IdpHandlerTest.java
- fixed cardinality display of types other than text
- added config drop down options for cardinality display in idp handler config
@SmithJosh @garrettfreibott @tbatie 
@coyotesqrl
@stustison …
=> DDF-3224 added configurable list of context classes to idp handler

catalog/ui/search-ui/simple/pom.xml
Simple Search UI was missing an import package causing the webapp to fail to come up despite the bundle coming up fine.
@mweser @emmberk @mackncheesiest 
@bdeining 
@lessarderic 
Build and install DDF. Verify the Simple Search UI loads.
[DDF-2803](https://codice.atlassian.net/browse/DDF-2803) …
=> DDF-2803 Fixing the simple search UI by adding an import package

catalog/spatial/csw/spatial-csw-endpoint/pom.xml, catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java, catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswQueryFactory.java, catalog/spatial/csw/spatial-csw-endpoint/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/TestCswEndpoint.java, distribution/test/itests/test-itests-common/src/main/resources/TestSpatial/csw/record/CswPagingRecord.xml, distribution/test/itests/test-itests-common/src/main/resources/TestSpatial/csw/request/query/CswPagingTestLikeQuery.xml, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestSpatial.java
Uses paging internally for get, update, and delete operations to avoid failing or producing incorrect and unexpected results.
@rzwiefel @AzGoalie @kcwire 
@codice/io
@clockard
@lessarderic
Full build and test. Then a larger number of records should be ingested - at minimum, more than 20 - and then queried, updated, and deleted through CSW queries. All records should be correctly processed.
N/A
[DDF-3207](https://codice.atlassian.net/browse/DDF-3207)
N/A
- ❓ …
=> DDF-3207 Updates CswEndpoint to support paging

platform/admin/ui/src/main/webapp/less/configuration/style.less
See attached pictures for visualization
@vinamartin @emmberk @mcalcote 
@clockard
Run DDF, open admin console, click System, click Admin Configuration Policy. See buttons without underline.
[DDF-3238](https://codice.atlassian.net/browse/DDF-3238)
Before:
After:
=> DDF-3238 Removed underline from buttons in Admin configuration modals

distribution/sdk/sample-twitter-source/src/main/java/org/codice/ddf/catalog/twitter/source/TwitterSource.java
Updates Twitter source to implement ConfiguredService interface so it will work when deployed. Currently even though the availability check works, the source will not show up as available without this change.
@ahoffer 
@clockard
@coyotesqrl
Build and deploy the twitter source into any running DDF instance. 
Configure the source via the sources tab with an API key and secret, these can be obtained from Twitter's website.  …
=> DDF-3242 Updates Twitter source to work out of the box

CODEOWNERS
Adds comments and an example to the codeowners file and expands a little coverage.
@rzwiefel 
@pklinef
@stustison
To test correctly, we'd want to create a variety of PRs touching these patterns. More likely, we'll test as we go since it will be added to much more. …
=> Cleanup and expansion of CODEOWNERS

Jenkinsfile
Updates the version of Maven used for building and performing static analysis stages.
@vinamartin @LinkMJB  @rzwiefel
@codice/build 
@clockard @shaundmorris
[DDF-2969](https://codice.atlassian.net/browse/DDF-2969)
=> DDF-2969 Upgrade Maven version used during build and analysis stages

platform/landing-page/src/main/resources/index.handlebars
Sanitizes css color values before applying them to the landing page.
@peterhuffer 
@stustison
- Build
- Configure landing page with invalid/escaped css configuration
- Ensure that the configuration is ignored/harmless
[DDF-3252](https://codice.atlassian.net/browse/DDF-3252)
=> DDF-3252 Sanitized css color values before applying them to the landing page

catalog/ui/catalog-ui-search/src/main/webapp/component/paging/paging.hbs, catalog/ui/catalog-ui-search/src/main/webapp/component/paging/paging.less, catalog/ui/catalog-ui-search/src/main/webapp/component/paging/paging.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/query-feed/query-feed.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/result-selector/result-selector.view.js, catalog/ui/catalog-ui-search/src/main/webapp/js/model/Metacard.js, catalog/ui/catalog-ui-search/src/main/webapp/js/model/Query.js
This allows the user to step through pages of results on the server (in addition to the existing paging controls, which only step through results client-side).
When the user navigates to the last client-side page, and there are still more results on the server to view, the paging controls are replaced with a "More.." button to fetch the next page of results from the server. Similarly, when viewing the 2nd to nth server page, a "More.." button replaces the previous page controls to navigate back.
The status display for the results has been updated to reflect server-side paging (e.g. "51 to 100 of 200 results").
@djblue 
@millerw8 
@bdeining
- Create a search that returns _n_ results.
- Change the user preference Query->Number of Search Results to a number …
=> DDF-3233 Add server-side paging to search results

distribution/docs/src/main/jdocs/templates/documentation.ftl, distribution/docs/src/main/resources/_contents/config.adoc
Improves navigation of documentation by collapsing sections in the table of contents and adding icons to expand/collapse.
@mcalcote @vinamartin @emmberk @Lambeaux @jrnorth @ahoffer 
@clockard
@coyotesqrl
@lessarderic
@pklinef
@shaundmorris
- build documentation
- open jdocumentation.html in browser and check that collapse/expand navigation works as expected.
- open jdocumentation.pdf and make sure navigation is not broken (expand/collapse is not expected to work, but should not affect regular navigation
[DDF-3239](https://codice.atlassian.net/browse/DDF-3239)
[jdocumentation.zip](https://github.com/codice/ddf/files/1249769/jdocumentation.zip) …
=> DDF-3239 Added collapsing to documentation TOC html

Jenkinsfile
Updates Jenkinsfile to support using multi-branch pipeline in jenkins.
Various steps were updated to detect when a pull request is being built vs a regular branch
Several settings were tweaked to bring build closer to the legacy jobs in configuration.
* Updated maven memory options
* Added property to override random device on linux
* Made deploy step conditional
* Made coverity step conditional on master branch
* Made Incremental vs Full build conditional
* Set git longpath support on windows
* Added stage to run pomfix before actual build steps
@mcalcote @LinkMJB @clockard 
@codice/build 
@lessarderic 
@shaundmorris 
[DDF-3261](https://codice.atlassian.net/browse/DDF-3261)
PR Build
Branch Build
Tasks: …
=> DDF-3261 Updating pipeline to support multi-branch jobs

dependency-check-maven-config.xml
@mcalcote 
@clockard 
@shaundmorris
=> DDF-3054 Adds owasp suppression for CVE-2016-8739

catalog/solr/catalog-solr-solrclient/pom.xml, catalog/solr/catalog-solr-solrclient/src/main/java/ddf/catalog/source/solr/rest/SolrRest.java, catalog/solr/catalog-solr-solrclient/src/main/java/ddf/catalog/source/solr/rest/SolrRestClient.java, catalog/solr/catalog-solr-solrclient/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/solr/catalog-solr-solrclient/src/main/resources/OSGI-INF/metatype/metatype.xml, catalog/solr/catalog-solr-solrclient/src/test/java/ddf/catalog/source/solr/rest/SolrRestTest.java, catalog/solr/pom.xml, catalog/solr/solr-app/pom.xml, catalog/solr/solr-app/src/main/resources/features.xml, distribution/test/itests/test-itests-ddf/pom.xml, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalog.java
Adds the ability to configure Solr similarity algorithm settings.
@adimka 
@glenhein 
@bdeining
@millerw8
Run full build with itests
Launch Admin UI
Select Solr Catalog
Select Catalog Solr Relevancy Ranking
Change k1 and b values.
Verify they have been changed at https://localhost:8993/solr/catalog/schema (search for similarity section).
https://codice.atlassian.net/browse/DDF-3263 …
=> DDF-3263 Solr similarity configuration

distribution/ddf-common/src/main/resources/etc/org.ops4j.pax.web.cfg
@SmithJosh @garrettfreibott 
@lessarderic
@stustison
=> DDF-3274 added truststore properties to pax web config

platform/admin/ui/src/main/webapp/js/models/Installer.js, platform/admin/ui/src/main/webapp/js/views/installer/Navigation.view.js, platform/admin/ui/src/main/webapp/templates/installer/finish.handlebars, platform/admin/ui/src/main/webapp/templates/installer/navigationButtons.handlebars
Enable system restart from installer
* There is an issue with the karaf.bat file such that restart doesn’t work on windows. We submitted a fix for it and it will be in karaf 4.1.2. Hold off on merging until we upgrade to karaf 4.1.2 
@mcalcote @coyotesqrl 
@pklinef
@shaundmorris
Verify that after install the system comes back up without the need to manually restart it.
[DDF-3047](https://codice.atlassian.net/browse/DDF-3047)
=> DDF-3047 Enable system restart from installer

CODEOWNERS
=> Added entries to CODEOWNERS

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/security/UserApplication.java
fixes log level
anyone
?
anyone
https://codice.atlassian.net/browse/DDF-3286
=> DDF-3286 Fixes overly verbose log

catalog/core/catalog-core-camelcomponent/pom.xml, catalog/core/catalog-core-camelcomponent/src/main/java/ddf/camel/component/catalog/content/FileSystemDataAccessObject.java, catalog/core/catalog-core-camelcomponent/src/main/java/ddf/camel/component/catalog/content/FileSystemPersistenceProvider.java, catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/IngestCommand.java, catalog/core/catalog-core-directorymonitor/pom.xml, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/FileSystemPersistenceProvider.java, catalog/core/catalog-core-impl/pubsub/src/main/java/ddf/catalog/pubsub/criteria/contextual/ContextualEvaluator.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/impl/FileSystemPersistenceProvider.java, catalog/spatial/wfs/1.0.0/spatial-wfs-v1_0_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v1_0_0/catalog/source/WfsFilterDelegate.java, catalog/transformer/catalog-transformer-pptx/pom.xml, catalog/transformer/catalog-transformer-pptx/src/main/java/ddf/catalog/transformer/input/pptx/PptxInputTransformer.java, platform/admin/core/admin-core-appservice/src/main/java/org/codice/ddf/admin/application/service/command/ProfileListCommand.java, platform/metrics/platform-metrics-reporting/pom.xml, platform/metrics/platform-metrics-reporting/src/main/java/ddf/metrics/reporting/internal/rest/MetricsEndpoint.java, platform/metrics/platform-metrics-reporting/src/main/java/ddf/metrics/reporting/internal/rrd4j/RrdMetricsRetriever.java, platform/notifications/core/platform-core-notifications/pom.xml, platform/notifications/core/platform-core-notifications/src/main/java/org/codice/ddf/notifications/impl/FileSystemPersistenceProvider.java
Changes include using try-with-resources where resources are not being closed and adjusting switch statement conditionals.
@rzwiefel @shaundmorris @clockard @emmberk @vinamartin 
Full build, Manual testing of any areas suspected to be affected.
This changes were made under the recommendation of sonarqube findings: https://sonarcloud.io/project/issues?id=ddf&resolved=false&severities=BLOCKER&types=BUG
[DDF-3277](https://codice.atlassian.net/browse/DDF-3277) …
=> DDF-3277 Resolve sonarqube identified blocker severity bugs

catalog/spatial/csw/spatial-csw-endpoint/pom.xml
This PR exports the mapping package so that it can be used by those extending DDF
@AzGoalie @troymohl 
@kcwire
@millerw8
Build.  No functionality has changed
[DDF-3198](https://codice.atlassian.net/browse/DDF-3198) …
=> DDF-3198 Exported mappings package

catalog/ui/catalog-ui-search/src/main/webapp/component/component.less, catalog/ui/catalog-ui-search/src/main/webapp/component/input/bulk/input-bulk.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/input/date/input-date.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/input/enum/input-enum.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/location-old/location-old.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/query-altitude/query-altitude.hbs, catalog/ui/catalog-ui-search/src/main/webapp/component/query-altitude/query-altitude.less, catalog/ui/catalog-ui-search/src/main/webapp/component/query-altitude/query-altitude.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/query-basic/query-basic.hbs, catalog/ui/catalog-ui-search/src/main/webapp/component/query-basic/query-basic.less, catalog/ui/catalog-ui-search/src/main/webapp/component/query-basic/query-basic.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/query-time/query-time.hbs, catalog/ui/catalog-ui-search/src/main/webapp/component/query-time/query-time.less, catalog/ui/catalog-ui-search/src/main/webapp/component/query-time/query-time.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/time-settings/time-settings.hbs, catalog/ui/catalog-ui-search/src/main/webapp/component/time-settings/time-settings.less, catalog/ui/catalog-ui-search/src/main/webapp/component/time-settings/time-settings.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/user-settings/user-settings.hbs, catalog/ui/catalog-ui-search/src/main/webapp/component/user-settings/user-settings.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/visualization/table/row.view.js, catalog/ui/catalog-ui-search/src/main/webapp/js/Common.js, catalog/ui/catalog-ui-search/src/main/webapp/js/DistanceUtils.js, catalog/ui/catalog-ui-search/src/main/webapp/js/model/User.js
-Adds altitude to basic query, adds user pref for time format
-Adds user preference for time format.
-Splits time part of basic query into query-time component.
@jlcsmith
@kcwire
@pklinef
=> DDF-3293 - Adds altitude search to basic query, adds user pref for time format

platform/security/rest/security-rest-cxfwrapper/src/main/java/org/codice/ddf/cxf/paos/BodyWriter.java
Fixes a nullpointer
@garrettfreibott @djblue 
@stustison
@clockard 
Was originally encountered by creating a Transactional CSW source and running a query
https://codice.atlassian.net/browse/DDF-3289
=> DDF-3289 Fixes NullPointer in BodyWriter

catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java, catalog/spatial/csw/spatial-csw-endpoint/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/TestCswEndpoint.java
Collects all IDs matching the filter and holds them in memory before batching out delete requests. The reason for this is because if we send a batch for deletion and then iterate on the query request, the resultIterable will update the index to the next set even though the deletion will result in the results left-shifting. This will result in records that should be deleted being skipped when batching is used.
@jhunzik 
@rzwiefel 
@ahoffer 
@coyotesqrl
@lessarderic …
=> DDF-3207 Updated CSW delete to collect all IDs before batching

platform/migration/platform-migration/pom.xml, platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/migration/AbstractMigrationTest.java
Fixes the build
@paouelle @mcalcote 
@figliold 
@stustison
Run the unit tests
[DDF-3142](https://codice.atlassian.net/browse/DDF-3142) …
=> DDF-3142 Skipping unit tests if symlinks cannot be created

catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/DumpCommand.java
Adds pagination to dump command queries
anyone
@clockard
@coyotesqrl
Running dump command with  > 1000 results
https://codice.atlassian.net/browse/DDF-3272
=> DDF-3272 fixed dump command by adding pagination

pom.xml
Updates ddf support version
@clockard 
@coyotesqrl
@kcwire
@shaundmorris
[DDF-3219](https://codice.atlassian.net/browse/DDF-3219)
=> DDF-3219 Updated to latest ddf-support version

catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/LatestCommand.java, catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/SearchCommand.java
updates latest & search command to use resultIterable so it is not capped at 1000 results
anyone
@clockard
@coyotesqrl
running commands
[](https://codice.atlassian.net/browse/DDF-3162)
=> DDF-3162 Updated Latest/Search command with ResultIterable

Jenkinsfile
Adds a few optimizations to the multi-branch pipeline support
* Blocks concurrent builds on the same branch
* Adds timestamps
* Incremental owasp for prs
* Incremental sonar for prs
@mcalcote @LinkMJB 
@codice/build 
@shaundmorris 
@clockard 
[DDF-3261](https://codice.atlassian.net/browse/DDF-3261)
=> DDF-3261 optimizations for multi-branch pipeline

platform/security/rest/security-rest-cxfwrapper/src/main/java/org/codice/ddf/cxf/paos/BodyWriter.java
Slightly modifies the logic in the BodyWriter class.
@tbatie @peterhuffer 
@coyotesqrl 
@stustison 
Make sure everything builds and all the current tests pass.
[DDF-3303](https://codice.atlassian.net/browse/DDF-3303)
=> DDF-3303 Modified the logic in the BodyWriter class

catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/operation/faceting/FacetProperties.java
This change publicizes some constants in `FacetProperties` for faceted queries. (See [DDF-3301](https://codice.atlassian.net/browse/DDF-3301)).
@adimka 
@glenhein 
@bdeining 
@millerw8 
Build the DDF module `catalog/core/catalog-core-api-impl`. (A full DDF build works, too.)
[DDF-3301](https://codice.atlassian.net/browse/DDF-3301) …
=> DDF-3301 Publicize constants in FacetProperties.

pom.xml
Moving checkstyle to the `validate` phase will fail builds much faster.
@vinamartin @blen-desta @oconnormi 
@clockard
@shaundmorris
Full build/test. Break something in a file - remove a line from the header or some other semantic change that checkstyle checks - and ensure it fails the build quickly.
[DDF-3310](https://codice.atlassian.net/browse/DDF-3310) …
=> DDF-3310 Move checkstyle checks to the validate lifecycle phase.

platform/security/handler/security-handler-saml/src/main/java/org/codice/ddf/security/handler/saml/SAMLAssertionHandler.java
Implements the changes that @gradygit made in #2219 to the master (2.11.0) DDF code base. Please see that PR for full description of the changes. That commit was already approved but was made on the older baseline.
N/A
@coyotesqrl 
@stustison
Testing was performed using the same steps as described in #2219 with a little less work because IDP is enabled out of the box now.
> Preconditions:
Keycloak has been deployed and a security realm has been created. Can use the official docker image if desired.
DDF has been built using these changes and deployed.
> Steps:
> 1. Set up a Keycloak client using DDF's metadata as input ( …
=> DDF-3311: Merged changes from gradygit to the main baseline.

distribution/docs/src/main/resources/content/_architectures/migration-api-contents.adoc, distribution/docs/src/main/resources/content/_configuring/configuring-from-import-intro-contents.adoc, distribution/docs/src/main/resources/content/_configuring/exporting-existing-configurations-contents.adoc, distribution/docs/src/main/resources/content/_configuring/importing-exported-configurations-contents.adoc
Updates documentation with latest findings with respect to export/import commands.
@Lambeaux 
@brjeter 
@figliold
Doc PR, so simply checkout the documentation related to export/import.
[DDF-3290](https://codice.atlassian.net/browse/DDF-3290) …
=> DDF-3290 - updated migration export/import documentation

platform/admin/core/admin-core-migration-commands/src/main/java/org/codice/ddf/migration/commands/MigrationCommand.java, platform/admin/core/admin-core-migration-commands/src/test/java/org/codice/ddf/migration/commands/AbstractMigrationCommandTest.java, platform/migration/platform-migratable-api/src/main/java/org/codice/ddf/migration/MigrationException.java, platform/migration/platform-migration/pom.xml, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/admin/ConfigurationAdminMigratable.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/admin/ImportMigrationConfigurationAdminContext.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/ConfigurationMigrationManager.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/ExportMigrationContextImpl.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/ExportMigrationEntryImpl.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/ExportMigrationJavaPropertyReferencedEntryImpl.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/ExportMigrationPropertyReferencedEntryImpl.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/ExportMigrationReportImpl.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/ImportMigrationContextImpl.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/ImportMigrationEntryImpl.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/ImportMigrationExternalEntryImpl.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/ImportMigrationJavaPropertyReferencedEntryImpl.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/ImportMigrationPropertyReferencedEntryImpl.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/JsonUtils.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/MigrationContextImpl.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/MigrationReportImpl.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/PathUtils.java, platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/migration/AbstractMigrationReportTest.java, platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/migration/AbstractMigrationTest.java, platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/migration/ExportMigrationEntryImplTest.java, platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/migration/ExportMigrationJavaPropertyReferencedEntryImplTest.java, platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/migration/ExportMigrationSystemPropertyReferencedEntryImplTest.java, platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/migration/ImportMigrationEntryImplTest.java, platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/migration/ImportMigrationJavaPropertyReferencedEntryImplTest.java, platform/migration/platform-migration/src/test/java/org/codice/ddf/test/matchers/ThrowableMatchers.java, platform/security/security-migratable/src/test/java/org/codice/ddf/security/migratable/impl/SecurityMigratableTest.java
This PR adds security auditing to the export/import commands and framework.
@brjeter 
@Lambeaux 
@figliold
@stustison
Run the migration:export and migration:import command and verify the security logs. All files exported and imported should be audited.
[DDF-3288](https://codice.atlassian.net/browse/DDF-3288) …
=> DDF-3288 - Implement security auditing in the export and import processes

platform/solr/platform-solr-server-standalone/src/main/resources/solr/conf/solrconfig-inmemory.xml, platform/solr/platform-solr-server-standalone/src/main/resources/solr/conf/solrconfig.xml, platform/solr/platform-solr-server-standalone/src/main/webapp/WEB-INF/web.xml, pom.xml
Upgrades to Solr 6.6.1 (http://lucene.apache.org/solr/6_6_1/changes/Changes.html) 
@figliold @emmberk @rzwiefel @lessarderic
@clockard 
@millerw8 
(Instructions from the last upgrade)
Full build.
Configure it to use stand-alone solr, embedded solr, and solr cloud. In all three scenarios, confirm ability to ingest metacards, save workspaces, and query.
[DDF-3279](https://codice.atlassian.net/browse/DDF-3279) …
=> DDF-3279 Upgrade to Solr 6.6.1

distribution/ddf-common/src/main/resources/common-bin.xml, distribution/ddf-common/src/main/resources/etc/startup.properties, distribution/ddf/pom.xml, distribution/ddf/src/main/descriptors/bin.xml, platform/osgi/platform-osgi-configadmin/pom.xml, platform/osgi/platform-osgi-configadmin/src/main/java/org/apache/felix/cm/impl/ConfigurationManager.java, platform/osgi/platform-osgi-configadmin/src/main/java/org/codice/felix/cm/file/EncryptingPersistenceManager.java, platform/osgi/platform-osgi-configadmin/src/main/java/org/codice/felix/cm/file/WrappedPersistenceManager.java, platform/osgi/platform-osgi-configadmin/src/test/java/org/codice/felix/cm/file/EncryptingPersistenceManagerTest.java, platform/osgi/platform-osgi-configadmin/src/test/java/org/codice/felix/cm/file/WrappedPersistenceManagerTest.java, platform/osgi/pom.xml, platform/pom.xml, platform/security/encryption/platform-security-encryption-impl/pom.xml, pom.xml
**Please do not squash the two commits when it comes time to merge**
**Only the 2nd commit needs review**
---
- Provisions our own felix-backed config admin implementation by changing `startup.properties`
- Encrypts all string-valued properties in the bundle cache
_Important_: Only the 2nd commit needs review. The first commit is a straight copy-paste of a class needed from Felix itself. Changes to this class can be viewed on the 2nd commit. The class in its original form can be found both on the first commit of this PR and here: http://svn.apache.org/viewvc/felix/releases/org.apache.felix.configadmin-1.8.14/src/main/java/org/apache/felix/cm/impl/ConfigurationManager.java?view=co
@brjeter 
@paouelle 
@figliold 
@shaundmorris 
@pklinef 
@SmithJosh 
@emmberk 
@vinamartin 
(please choose …
=> DDF-3249 Implemented bundle cache encryption within a custom config admin impl

distribution/ddf-common/src/main/resources/common-bin.xml, distribution/ddf/src/main/descriptors/bin.xml, distribution/kernel/pom.xml, platform/osgi/platform-osgi-configadmin/pom.xml, platform/osgi/platform-osgi-configadmin/src/main/java/org/codice/felix/cm/file/EncryptingPersistenceManager.java
Addresses Sonarqube with either a fix or suppression. 
@stustison 
@rzwiefel 
@clockard 
@oconnormi 
Build is sufficient. 
=> DDF-3249 Address build dependency and Sonarqube issues

catalog/core/catalog-core-subscriptionstore/subscriptionstore-impl/src/main/java/org/codice/ddf/catalog/subscriptionstore/common/SubscriptionPersistor.java, catalog/core/catalog-core-subscriptionstore/subscriptionstore-impl/src/test/java/org/codice/ddf/catalog/subscriptionstore/common/SubscriptionPersistorTest.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/security/UserApplication.java, catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/controller/ActivityController.java, catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/controller/NotificationController.java, catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/service/UserService.java, catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/service/WorkspaceService.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalog.java, platform/notifications/core/platform-core-notificationcommands/src/main/java/org/codice/ddf/notifications/commands/DeleteCommand.java, platform/notifications/core/platform-core-notificationcommands/src/main/java/org/codice/ddf/notifications/commands/ListCommand.java, platform/persistence/platform-persistence-commands/src/main/java/org/codice/ddf/persistence/commands/AbstractStoreCommand.java, platform/persistence/platform-persistence-core-api/src/main/java/org/codice/ddf/persistence/PersistentStore.java, platform/persistence/platform-persistence-core-attributes-impl/src/main/java/org/codice/ddf/persistence/attributes/internal/AttributesStoreImpl.java, platform/persistence/platform-persistence-core-attributes-impl/src/test/java/org/codice/ddf/persistence/attributes/internal/TestAttributesStoreImpl.java, platform/persistence/platform-persistence-core-listeners/src/main/java/org/codice/ddf/persistence/events/ActivityListener.java, platform/persistence/platform-persistence-core-listeners/src/main/java/org/codice/ddf/persistence/events/NotificationListener.java
Resolves a vulnerability found by SonarQube
@emmberk  @mcalcote 
@clockard
@coyotesqrl 
[DDF-3298](https://codice.atlassian.net/browse/)
=> DDF-3298 Made string values in PersistentStore into an enum

catalog/opensearch/catalog-opensearch-source/src/main/java/ddf/catalog/source/opensearch/impl/OpenSearchSource.java
Fixed URL updated in OpenSearch source
@mackncheesiest @adimka 
@millerw8
@rzwiefel 
Build / Install / Configure an OpenSearch source / Change URL and verify change takes effect by issuing a query
[DDF-3329](https://codice.atlassian.net/browse/DDF-3329)
- ❗ …
=> DDF-3329 Fixed URL updated in OpenSearch source

catalog/opensearch/catalog-opensearch-source/src/main/java/ddf/catalog/source/opensearch/impl/OpenSearchSource.java, catalog/opensearch/catalog-opensearch-source/src/test/java/ddf/catalog/source/opensearch/impl/TestOpenSearchSource.java
Add ability to pass foreign markup data to caller of OpenSearchSource.
@bdeining 
@coyotesqrl 
@lessarderic
@millerw8
Run unit tests.
[DDF-3287](https://codice.atlassian.net/browse/DDF-3287) …
=> DDF-3287 add ability to pass foreign markup data to caller of OpenSearchSource

Jenkinsfile
Several of the stages were also formatted which makes the changes a little harder to read. Sorry in advance.
@codice/build 
@clockard @rzwiefel @shaundmorris
Run a multibranch pipeline build with this jenkinsfile
The quality analysis stage contains items that should inform the development team without failing the build. However the security analysis stage must still be passed for the build to deploy.
[DDF-3322](https://codice.atlassian.net/browse/DDF-3322)
=> DDF-3322 Move non-failure state static analysis builds after the deploy step in the jenkinsfile and add Codecov

distribution/docs/src/main/resources/content/_metadataAttributes/core-attributes-table.adoc
Fix documentation change missed in docs transition
This was already approved and merged in https://github.com/codice/ddf/pull/2298
@emmberk 
[DDF-3210](https://codice.atlassian.net/browse/DDF-3210)
=> DDF-3210 Fix documentation change missed in docs transition

Jenkinsfile
Several of the stages were also formatted which makes the changes a little harder to read. Sorry in advance.
@codice/build 
@clockard @rzwiefel @shaundmorris
Run a multibranch pipeline build with this jenkinsfile
The quality analysis stage contains items that should inform the development team without failing the build. However the security analysis stage must still be passed for the build to deploy.
[DDF-3322](https://codice.atlassian.net/browse/DDF-3322)
=> (2.11.x) DDF-3322 Move non-failure state static analysis builds after the deploy step in the jenkinsfile and add Codecov

catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/RemoveCommand.java, catalog/core/catalog-core-commands/src/test/java/org/codice/ddf/commands/catalog/RemoveCommandTest.java
Refactors RemoveCommand.java to utilize ResultIterable from the generic utility found in DDF-3034
@Joy603 
@johnsliao
@mweser
@emanns95 
@coyotesqrl 
@clockard
@shaundmorris
1. Build DDF
2. Ingest metacards into the DDF (more than the default batch size of 250). 
3. Attempt to delete all metacards using `catalog:remove --cql "title like '*'" …
=> DDF-3165 catalog:remove command now uses ResultIterable to batch query responses for metacard deletion

catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/RemoveCommand.java, catalog/core/catalog-core-commands/src/test/java/org/codice/ddf/commands/catalog/RemoveCommandTest.java
=> DDF-3165 changed catalog:remove command to utilize ResultIterable

distribution/docs/pom.xml, distribution/docs/src/main/resources/content/_dependencyList/ddf-dependency-list.adoc, pom.xml
Newer versions of the asciidoctorj plugins have been released and this change points our build at them.
@AzGoalie @vinamartin 
@codice/docs 
@ricklarsen @rzwiefel 
Build, look for errors during the build process. Open the built documentation and confirm it appears as expected.
There may be conflicts between our version of jbake and the older asciidoctorj plugins …
=> DDF-2824 Updated asciidoctorj and jbake mvn plugin versions

catalog/security/catalog-security-metacardattributeplugin/src/main/resources/OSGI-INF/metatype/metatype.xml, distribution/docs/src/main/resources/content/_plugins/metacard-attribute-plugin.adoc, distribution/docs/src/main/resources/content/_tables/MetacardAttributePlugin.adoc
Updates Metacard Attribute Security Policy Plugin documentation
@ricklarsen @brendan-hofmann 
@coyotesqrl
@shaundmorris
@stustison
Render and view the documentation.
No.
[DDF-3325](https://codice.atlassian.net/browse/DDF-3325)
- [N/A ] Update / Add Unit Tests …
=> DDF-3325 Update Metacard Attribute Security Policy Plugin documentation

platform/admin/ui/src/main/webapp/js/models/Installer.js, platform/admin/ui/src/main/webapp/js/views/installer/Navigation.view.js, platform/admin/ui/src/main/webapp/templates/installer/finish.handlebars, platform/admin/ui/src/main/webapp/templates/installer/navigationButtons.handlebars
Updates installer UI to suggest the admin to restart even though no changes have been made.
@garrettfreibott @clockard @djblue @tbatie 
@figliold
@lessarderic
Run through the installer without making any changes.
Verify the shutdown button shuts down the system.
Verify the restart button restarts the system. 
This is related to a potential issue with lock files in Solr.
[DDF-3279](https://codice.atlassian.net/browse/DDF-3279) …
=> [2.11.x] DDF-3279 Updates installer to force restart even if no changes are made

catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/DynamicSchemaResolver.java, catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/SchemaFields.java, catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/SolrMetacardClientImpl.java, catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/DynamicSchemaResolverTest.java, catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/SolrProviderTest.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/CacheSolrMetacardClient.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/cql/CqlRequest.java, catalog/ui/catalog-ui-search/src/main/webapp/js/model/Query.js, catalog/ui/catalog-ui-search/src/main/webapp/js/model/Workspace.js, catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/solr/FilteringDynamicSchemaResolver.java, catalog/ui/search-ui/search-endpoint/src/test/groovy/org/codice/ddf/ui/searchui/query/solr/FilteringDynamicSchemaResolverTest.groovy, platform/solr/platform-solr-server-standalone/src/main/resources/solr/conf/schema.xml
Backport of https://github.com/codice/ddf/pull/2355
@jlcsmith
@rzwiefel
=> [2.11.x] DDF-3262 Increase Solr string indexing size and exclude attributes

platform/security/servlet/security-servlet-logout/src/main/java/org/codice/ddf/security/servlet/logout/LocalLogoutServlet.java, platform/security/servlet/security-servlet-logout/src/test/java/org/codice/ddf/security/servlet/logout/TestLogoutServlet.java
Fixes possible NullPointerExceptions in `LocalLogoutServlet`
anyone
@clockard 
@stustison
https://codice.atlassian.net/browse/DDF-3331
=> DDF-3331 Fix possible nullpointers in LocalLogoutServlet

dependency-check-maven-config.xml, distribution/docs/pom.xml, distribution/docs/src/main/resources/content/_dependencyList/ddf-dependency-list.adoc, pom.xml
Newer versions of the asciidoctorj plugins have been released and this change points our build at them.
@AzGoalie @vinamartin 
@codice/docs 
@ricklarsen @rzwiefel 
Build, look for errors during the build process. Open the built documentation and confirm it appears as expected.
There may be conflicts between our version of jbake and the older asciidoctorj plugins …
=> (2.11.x) DDF-2824 Updated asciidoctorj and jbake mvn plugin versions

platform/security/servlet/security-servlet-logout/src/main/java/org/codice/ddf/security/servlet/logout/LocalLogoutServlet.java, platform/security/servlet/security-servlet-logout/src/test/java/org/codice/ddf/security/servlet/logout/TestLogoutServlet.java
Fixes possible NullPointerExceptions in `LocalLogoutServlet`
anyone
@clockard 
@stustison
https://codice.atlassian.net/browse/DDF-3331
=> [2.11.x] DDF-3331 Fix possible nullpointers in LocalLogoutServlet

platform/admin/ui/src/main/webapp/js/models/Installer.js, platform/admin/ui/src/main/webapp/js/views/installer/Navigation.view.js, platform/admin/ui/src/main/webapp/templates/installer/finish.handlebars, platform/admin/ui/src/main/webapp/templates/installer/navigationButtons.handlebars
Port: https://github.com/codice/ddf/pull/2400
@lessarderic
@rzwiefel
=> DDF-3279 Updates installer to force restart even if no changes are made

catalog/ui/catalog-ui-search/.nsprc
Adds a suppression for several issues from transitive dependencies
@mcalcote @djblue 
@clockard 
@stustison 
run `nsp check` under `catalog/ui/catalog-ui-search`
[DDF-3345](https://codice.atlassian.net/browse/DDF-3345)
=> DDF-3345 Address node security platform vulnerabilities in catalog-ui-search

catalog/ui/catalog-ui-search/.nsprc
Adds a suppression for several issues from transitive dependencies
@clockard 
[DDF-3345](https://codice.atlassian.net/browse/DDF-3345)
=> DDF-3345 (Backport) Address node security platform vulnerabilities in catalog-ui-search

platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/admin/ExportMigrationConfigurationAdminEntry.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/admin/ImportMigrationConfigurationAdminContext.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/admin/ImportMigrationConfigurationAdminEntry.java
Currently the export/import process for config admin objects relies on the pid and the factory pid properties to be properly defined. However, they can easily get out of sync in config admin if they do not get updated properly by client code. We actually seen in some weird cases these not set properly. As such, we should make sure to protect the code by ensuring to store the right pid and factory pid in the properties set we export and at import time, we should also protect ourselves against missing pid.
@emanns95 
@Lambeaux 
@brjeter 
@coyotesqrl
@figliold
The only way to test the export would be to modify a config object directly at run-time. For the import, it would require tweaking the …
=> DDF-3315 - Add protection code for invalid config admin objects during migration export/import

distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/AbstractIntegrationTest.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalog.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestSolrCommands.java
Port https://github.com/codice/ddf/pull/2405
@clockard 
@lessarderic
=> DDF-3279 Updates itests to use embedded solr

platform/admin/core/admin-core-appservice/src/main/java/org/codice/ddf/admin/application/service/command/ProfileInstallCommand.java, platform/admin/core/admin-core-appservice/src/test/java/org/codice/ddf/admin/application/service/command/ProfileInstallCommandTest.java
Backports #2367 to 2.11.x
@clockard 
[DDF-3316](https://codice.atlassian.net/browse/DDF-3316)
=> DDF-3316 (Backport) Implement security audit logging in profile install command

distribution/ddf-common/src/main/resources/bin/setenv, distribution/ddf-common/src/main/resources/bin/setenv.bat, distribution/ddf-common/src/main/resources/etc/startup.properties, distribution/ddf-common/src/main/resources/etc/system.properties, distribution/ddf-common/src/main/resources/security/default.policy, distribution/kernel/pom.xml, distribution/test/itests/README.md, distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/AbstractIntegrationTest.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFederation.java, platform/admin/admin-configuration-configinstaller/src/main/java/org/codice/ddf/admin/configuration/ConfigurationInstaller.java, platform/osgi/platform-osgi-configadmin/pom.xml, platform/osgi/platform-osgi-configadmin/src/main/resources/OSGI-INF/permissions.perm, platform/security/core/security-core-impl/pom.xml, platform/security/core/security-core-impl/src/main/java/ddf/security/config/impl/ConfigurationSecurityLogger.java, platform/security/pdp/security-pdp-authzrealm/src/main/java/ddf/security/pdp/realm/xacml/processor/PollingPolicyFinderModule.java
Backport of #2373 
@paouelle @oconnormi @tbatie 
@clockard
@rzwiefel 
@stustison 
=> DDF-3297 [2.11.x] Adds security manager to container #2373

catalog/core/catalog-core-urlresourcereader/pom.xml, catalog/core/catalog-core-urlresourcereader/src/main/java/ddf/catalog/resource/impl/URLResourceReader.java, catalog/core/catalog-core-urlresourcereader/src/test/java/ddf/catalog/resource/impl/URLResourceReaderTest.java
This PR is a port of https://github.com/codice/ddf/pull/2423.
@clockard
[DDF-3342](https://codice.atlassian.net/browse/DDF-3342)
=> DDF-3342 Fixed downloading qualified resources from a federated source

platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/admin/ExportMigrationConfigurationAdminEntry.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/admin/ImportMigrationConfigurationAdminContext.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/admin/ImportMigrationConfigurationAdminEntry.java
Master [PR 2362](https://github.com/codice/ddf/pull/2362)
Currently the export/import process for config admin objects relies on the pid and the factory pid properties to be properly defined. However, they can easily get out of sync in config admin if they do not get updated properly by client code. We actually seen in some weird cases these not set properly. As such, we should make sure to protect the code by ensuring to store the right pid and factory pid in the properties set we export and at import time, we should also protect ourselves against missing pid.
@figliold
The only way to test the export would be to modify a config object directly at run-time. For the import, it would …
=> [2.11.x] DDF-3315 - Add protection code for invalid config admin objects during migration export/import

catalog/transformer/catalog-transformer-streaming-api/src/main/java/org/codice/ddf/transformer/xml/streaming/Gml3ToWkt.java, catalog/transformer/catalog-transformer-streaming-impl/pom.xml, catalog/transformer/catalog-transformer-streaming-impl/src/main/java/org/codice/ddf/transformer/xml/streaming/impl/Gml3ToWktImpl.java, catalog/transformer/catalog-transformer-streaming-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/transformer/catalog-transformer-streaming-impl/src/test/java/org/codice/ddf/transformer/xml/streaming/impl/TestGml3ToWktImpl.java, catalog/transformer/catalog-transformer-streaming-impl/src/test/java/org/codice/ddf/transformer/xml/streaming/impl/TestXmlInputTransformer.java
Adapted Gml3ToWkt to us Geotools for conversion.
https://github.com/orgs/codice/teams/ogc
@clockard
@coyotesqrl
We currently are manually using JTS to convert and parse the XML. We should instead allow Geotools to do this for us.
[DDF-3334](https://codice.atlassian.net/browse/DDF-3334)
=> DDF-3334 Converted Gml3ToWkt to use Geotools

catalog/ui/catalog-ui-search/src/main/webapp/component/singletons/logout-actions.js, catalog/ui/catalog-ui-search/src/main/webapp/component/user/user.hbs, catalog/ui/catalog-ui-search/src/main/webapp/component/user/user.less, catalog/ui/catalog-ui-search/src/main/webapp/component/user/user.view.js
Updates Intrigue to be aware of IDP.
If IDP is active, then the user component will act as if a user is always logged in (it will show the guest details and a logout button).
@djblue 
@clockard 
Verify that when you are logged into Intrigue as Guest that you can login as another user.
https://codice.atlassian.net/browse/DDF-3355 …
=> DDF-3355: (2.11.x) Updates Intrigue to be aware of IDP

catalog/ui/catalog-ui-search/src/main/webapp/component/singletons/logout-actions.js, catalog/ui/catalog-ui-search/src/main/webapp/component/user/user.hbs, catalog/ui/catalog-ui-search/src/main/webapp/component/user/user.less, catalog/ui/catalog-ui-search/src/main/webapp/component/user/user.view.js
Updates Intrigue to be aware of IDP.
If IDP is active, then the user component will act as if a user is always logged in (it will show the guest details and a logout button).
Port to master of PR:  https://github.com/codice/ddf/pull/2433
CI build
https://codice.atlassian.net/browse/DDF-3355 …
=> DDF-3355: Updates Intrigue to be aware of IDP

libs/klv/pom.xml, libs/klv/src/main/java/org/codice/ddf/libs/klv/data/text/KlvEncodingDetectedString.java, libs/klv/src/test/java/org/codice/ddf/libs/klv/KlvEncodingDetectedStringTest.java
Port https://github.com/codice/ddf/pull/2426
@lessarderic 
@rzwiefel
=> DDF-3344 Adds KlvEncodingDetectedString

distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/AbstractIntegrationTest.java
Wraps stream access in try-with-resources.
@blen-desta @vinamartin 
@clockard
@figliold
CI build is sufficient as it only impacts itests.
[DDF-3365](https://codice.atlassian.net/browse/DDF-3365) …
=> DDF-3365 [2.11.x] Cleans up an unclosed io stream issue in itests.

distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/AbstractIntegrationTest.java
Wraps stream access in try-with-resources.
(cherry picked from commit 88cf761)
@clockard
@shaundmorris
[DDF-3365](https://codice.atlassian.net/browse/DDF-3365) …
=> DDF-3365 Cleans up an unclosed io stream issue in itests.

catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/DuplicateCommands.java, catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/MigrateCommand.java, catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/ReplicateCommand.java, catalog/core/catalog-core-commands/src/test/java/org/codice/ddf/commands/catalog/ReplicateCommandTest.java
fixes replicate and migrate commands
~~Note that the changes will need to be rebased with the these https://github.com/codice/ddf/pull/2316 before being merged~~
@emmberk @tbatie 
@clockard
@coyotesqrl
The commands should be run and verified they work correctly
[DDF-3232](https://codice.atlassian.net/browse/DDF-3232) …
=> DDF-3232 Fixed duplicate commands so they now page results

catalog/ui/catalog-ui-search/src/main/webapp/component/component.less, catalog/ui/catalog-ui-search/src/main/webapp/component/metacard-preview/metacard-preview.hbs, catalog/ui/catalog-ui-search/src/main/webapp/component/metacard-preview/metacard-preview.less, catalog/ui/catalog-ui-search/src/main/webapp/component/metacard-preview/metacard-preview.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/tabs/metacard/tabs-metacard.js, catalog/ui/catalog-ui-search/src/main/webapp/component/tabs/metacard/tabs-metacard.less, catalog/ui/catalog-ui-search/src/main/webapp/component/tabs/metacard/tabs-metacard.view.js, catalog/ui/catalog-ui-search/src/main/webapp/js/model/Metacard.js, catalog/ui/catalog-ui-search/src/main/webapp/styles/components/links.less, catalog/ui/catalog-ui-search/src/main/webapp/styles/vars.less, catalog/ui/catalog-ui-search/yarn.lock
Backport of https://github.com/codice/ddf/pull/2335
Depends on #2303 for testing. No issues on which goes in first though, the tab just won't appear without it.
@jlcsmith
@kcwire
@pklinef
=> [2.11.x] DDF-3276 Adds preview tab for results with previews available

catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/DuplicateCommands.java, catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/MigrateCommand.java, catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/ReplicateCommand.java, catalog/core/catalog-core-commands/src/test/java/org/codice/ddf/commands/catalog/ReplicateCommandTest.java
fixes replicate and migrate commands
~~Note that the changes will need to be rebased with the these https://github.com/codice/ddf/pull/2316 before being merged~~
@emmberk @tbatie 
@clockard
@coyotesqrl
The commands should be run and verified they work correctly
[DDF-3232](https://codice.atlassian.net/browse/DDF-3232) …
=> [2.11.x] DDF-3232 Fixed duplicate commands so they now page results

distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/AbstractIntegrationTest.java
Provides an overloaded means of adding content.
@blen-desta @mcalcote 
@clockard
@rzwiefel
CI run.
[DDF-3365](https://codice.atlassian.net/browse/DDF-3365)
=> [2.11.x] DDF-3365 Cleans up an unclosed io stream issue in itests.

catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/view/NodeModal.view.js, catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/templates/field.handlebars
Port: https://github.com/codice/ddf/commit/f6650aa00b7019749376c02023a0cdd467d5c256
@clockard 
=> DDF-3367 Fixes registry multivalued fields

catalog/async/catalog-async-processingframework/pom.xml, catalog/async/catalog-async-processingframework/src/main/java/org/codice/ddf/catalog/async/processingframework/impl/InMemoryProcessingFramework.java
Resolves a static analysis finding.
(cherry picked from commit 434ac7b)
@peterhuffer @ahoffer 
@clockard
@rzwiefel
Full CI build.
[DDF-3377](https://codice.atlassian.net/browse/DDF-3377) …
=> DDF-3377 Closes resource stream potentially left open in InMemoryProcessingFramework

distribution/docs/src/main/resources/content/_installing/installing-intro.adoc
Updates the minimum system requirements to Windows 10 and recommended to Windows Server 2012. Removes macOS from table. Adds WebGL to recommended requirements to match minimum requirements.
@ricklarsen 
@oconnormi 
@beyelerb
Build documentation and review.
[DDF-3358](https://codice.atlassian.net/browse/DDF-3358)
=> [2.11.x] DDF-3358 Update Minimum and Recommended System Requirements

platform/security/idp/security-idp-client/src/main/resources/post-binding.html, platform/security/idp/security-idp-client/src/main/resources/templates/redirect.handlebars, platform/security/idp/security-idp-client/src/main/resources/templates/soapfault.handlebars, platform/security/idp/security-idp-client/src/main/resources/templates/submitForm.handlebars, platform/security/idp/security-idp-server/pom.xml, platform/security/idp/security-idp-server/src/main/resources/html/index.html, platform/security/idp/security-idp-server/src/main/resources/templates/redirect.handlebars, platform/security/idp/security-idp-server/src/main/resources/templates/submitForm.handlebars, platform/security/idp/security-idp-server/src/test/java/org/codice/ddf/security/idp/server/IdpEndpointTest.java
2.11.x port of https://github.com/codice/ddf/pull/2350
@mcalcote @josephthweatt @stustison @tbatie  
@clockard
@coyotesqrl
@figliold 
Build DDF or downstream project. 
Try logging in and out of search UI and admin UI on a Mac.
Try logging in and out of search UI and admin UI with IE11 on Windows.
[DDF-3309](https://codice.atlassian.net/browse/DDF-3309) …
=> [2.11.x] DDF-3309 Convert templates to HTML 5

catalog/core/catalog-core-directorymonitor/pom.xml, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/AbstractDurableFileConsumer.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/DavAlterationObserver.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/DurableFileAlterationListener.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/DurableFileComponent.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/DurableFileEndpoint.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/DurableFileSystemFileConsumer.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/DurableWebDavFileConsumer.java, catalog/core/catalog-core-directorymonitor/src/test/java/org/codice/ddf/catalog/content/monitor/DurableFileAlterationListenerTest.java, catalog/core/catalog-core-localstorageprovider/src/main/java/org/codice/ddf/catalog/content/impl/FileSystemStorageProvider.java
Backport of https://github.com/codice/ddf/pull/2441
@rzwiefel
[DDF-3354](https://codice.atlassian.net/browse/DDF-3354)
=> [Backport] DDF-3354 CDM verify file size stable before ingesting

distribution/docs/src/main/resources/content/_whitelists/admin-whitelist.adoc, distribution/docs/src/main/resources/content/_whitelists/catalog-whitelist.adoc, distribution/docs/src/main/resources/content/_whitelists/platform-whitelist.adoc, distribution/docs/src/main/resources/content/_whitelists/registry-whitelist.adoc, distribution/docs/src/main/resources/content/_whitelists/removed-whitelist.adoc, distribution/docs/src/main/resources/content/_whitelists/security-whitelist.adoc, distribution/docs/src/main/resources/content/_whitelists/solr-whitelist.adoc, distribution/docs/src/main/resources/content/_whitelists/spatial-whitelist.adoc, distribution/docs/src/main/resources/content/_whitelists/ui-whitelist.adoc, platform/security/platform-security-core-api/src/main/java/ddf/security/policy/extension/PolicyExtension.java
Updates the whitelist to correct previous errors.
@coyotesqrl
@kcwire
@lessarderic
@pklinef
@rzwiefel
@shaundmorris
@stustison
In recent changes to an internal interface it was discovered that it had been leaked into the whitelist. Upon further examination it appears this may have happened for several packages.
[documentation.pdf](https://github.com/codice/ddf/files/1360351/documentation.pdf)
=> [2.11.x] DDF-3320 Fix errors in whitelist.

catalog/async/catalog-async-processingframework/pom.xml, catalog/async/catalog-async-processingframework/src/main/java/org/codice/ddf/catalog/async/processingframework/impl/InMemoryProcessingFramework.java
Resolves a static analysis finding.
@peterhuffer @ahoffer 
@clockard
@rzwiefel
Full CI build.
[DDF-3377](https://codice.atlassian.net/browse/DDF-3377)
=> [2.11.x] DDF-3377 Closes resource stream potentially left open in InMemoryProcessingFramework

catalog/transformer/catalog-transformer-tika-input/src/main/java/ddf/catalog/transformer/input/tika/TikaInputTransformer.java, catalog/transformer/catalog-transformer-tika-input/src/test/java/ddf/catalog/transformer/input/tika/TikaInputTransformerTest.java
(cherry picked from commit 30145ce)
Backport of https://github.com/codice/ddf/pull/2492
@coyotesqrl
@figliold
Passing CI build
[DDF-3210](https://codice.atlassian.net/browse/DDF-3210)
=> [Backport] DDF-3210 Update tika data types that were missed in the original PR

distribution/ddf-common/src/main/resources/etc/system.properties
Adds `disable.configEdit=true` to `system.properties` file and adds blank lines back to make file readable again.
Forward port of https://github.com/codice/ddf/pull/2509.
@paouelle 
@clockard
Build DDF with Solr configured as `HttpSolrClient`, and make sure the HTTP POST to `https://localhost:8993/solr/catalog/config/requestHandler` with the following data:
```
{
"add-updateprocessor" : {
"name" : "firstFld",
"class": "solr.FirstFieldValueUpdateProcessorFactory",
"fieldName":"test_s"
}
}
```
fails with the following error:
```
{
"responseHeader":{
"status":403,
"QTime":13625},
"error":{
"metadata":[ …
```
=> DDF-3384 Disable Solr Config API

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/security/WorkspacePolicyExtension.java, catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/security/WorkspacePolicyExtensionTest.java, distribution/docs/src/main/resources/content/_securityFramework/realms.adoc, distribution/docs/src/main/resources/content/_whitelists/admin-whitelist.adoc, distribution/docs/src/main/resources/content/_whitelists/catalog-whitelist.adoc, distribution/docs/src/main/resources/content/_whitelists/platform-whitelist.adoc, distribution/docs/src/main/resources/content/_whitelists/registry-whitelist.adoc, distribution/docs/src/main/resources/content/_whitelists/removed-whitelist.adoc, distribution/docs/src/main/resources/content/_whitelists/security-whitelist.adoc, distribution/docs/src/main/resources/content/_whitelists/solr-whitelist.adoc, distribution/docs/src/main/resources/content/_whitelists/spatial-whitelist.adoc, distribution/docs/src/main/resources/content/_whitelists/ui-whitelist.adoc, platform/admin/core/admin-core-configpolicy/src/main/java/org/codice/ddf/admin/config/policy/AdminConfigPolicy.java, platform/admin/core/admin-core-configpolicy/src/test/java/org/codice/ddf/admin/config/policy/AdminConfigPolicyTest.java, platform/security/pdp/security-pdp-authzrealm/src/main/java/ddf/security/pdp/realm/AuthzRealm.java, platform/security/pdp/security-pdp-authzrealm/src/test/java/ddf/security/pdp/realm/test/AuthzRealmTest.java, platform/security/platform-security-core-api/src/main/java/ddf/security/policy/extension/PolicyExtension.java
Port of https://github.com/codice/ddf/pull/2383
and https://github.com/codice/ddf/pull/2419
@bdeining
@stustison
CI build
[DDF-3320](https://codice.atlassian.net/browse/DDF-3320)
=> DDF-3320 Update PolicyExtension interface methods and implementing classes

Documentation-versions.html, index.html
updates gh-pages branch (codice.org/ddf) for the 2.11.0 release.
@clockard
@shaundmorris
check valid links and updated version of documentation.html and documentation.pdf
=> DDF-2748 updated website for 2.11.0 release

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/workspace/QueryMetacardTypeImpl.java
Port of https://github.com/codice/ddf/pull/2517
@clockard
[DDF-3380](https://codice.atlassian.net/browse/DDF-3380)
=> DDF-3380 Fixed needing to save a workspace twice after saving a search in Intrigue

Jenkinsfile
Updates the regex used for determining deployable branches
@mcalcote @LinkMJB 
@codice/build 
@clockard @shaundmorris 
[DDF-3387](https://codice.atlassian.net/browse/DDF-3387)
=> DDF-3387 Updating deployable branches regex expression to handle multiple digits

Jenkinsfile
Backports #2515 
@clockard 
@codice/build 
=> [2.11.x] DDF-3387 Updating deployable branches regex expression to handle multiple digits

pom.xml
Removes an unnecessary build extension
@LinkMJB @mcalcote 
@codice/build 
@shaundmorris 
@clockard 
=> DDF-3264 Removing wagon-webdav-jackrabbit build extension

platform/platform-filter-delegate/src/main/java/org/codice/ddf/platform/filter/delegate/FilterInjector.java, platform/platform-filter-delegate/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/platform-filter-delegate/src/test/java/org/codice/ddf/platform/filter/delegate/FilterInjectorTest.java
Apply pklinef fix for filter injector servlet context race condition.
@pklinef @shaundmorris 
@lessarderic 
@rzwiefel 
Install and verify there are no errors related to injecting the DelegateServletFilter
[DDF-3385](https://codice.atlassian.net/browse/DDF-3385)
=> [2.11.x] DDF-3385 Apply pklinef fix for filter injector servlet context race condition.

platform/security/idp/security-idp-client/src/main/resources/post-binding.html, platform/security/idp/security-idp-client/src/main/resources/templates/redirect.handlebars, platform/security/idp/security-idp-client/src/main/resources/templates/soapfault.handlebars, platform/security/idp/security-idp-client/src/main/resources/templates/submitForm.handlebars, platform/security/idp/security-idp-server/pom.xml, platform/security/idp/security-idp-server/src/main/resources/html/index.html, platform/security/idp/security-idp-server/src/main/resources/templates/redirect.handlebars, platform/security/idp/security-idp-server/src/main/resources/templates/submitForm.handlebars, platform/security/idp/security-idp-server/src/test/java/org/codice/ddf/security/idp/server/IdpEndpointTest.java
Converts the IDP template and .html files from XHTML to HTML 5.
@stustison 
@djblue 
@pklinef 
@rzwiefel
@stustison
Build DDF branch.
Run DDF.
Login and logout. This should cause the web browser to interact with the IDP applications.
1. Ensure that login and logout works as it does on the maste branch.
2. Open the developer  …
=> DDF-3309 Convert templates to HTML 5

platform/platform-filter-delegate/src/main/java/org/codice/ddf/platform/filter/delegate/FilterInjector.java, platform/platform-filter-delegate/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/platform-filter-delegate/src/test/java/org/codice/ddf/platform/filter/delegate/FilterInjectorTest.java
Apply pklinef fix for filter injector servlet context race condition.
@emmberk @AzGoalie @vinamartin @clockard 
@lessarderic
@pklinef 
Install and verify there are no errors related to injecting the DelegateServletFilter
[DDF-3385](https://codice.atlassian.net/browse/DDF-3385)
=> DDF-3385 Apply pklinef fix for filter injector servlet context race condition. (#2531)

catalog/opensearch/catalog-opensearch-source/src/main/java/ddf/catalog/source/opensearch/impl/OpenSearchSource.java, catalog/opensearch/catalog-opensearch-source/src/test/java/ddf/catalog/source/opensearch/impl/TestOpenSearchSource.java, catalog/ui/catalog-ui-search/yarn.lock
Ensure that all metacards returned by Open Search Source have the correct source-id.
@bdeining 
@troymohl 
@coyotesqrl 
@peterhuffer 
https://github.com/orgs/codice/teams/IO
@lessarderic
@rzwiefel
Run unit tests.
[DDF-3381](https://codice.atlassian.net/browse/DDF-3381) …
=> DDF-3381 ensure that all metacards returned by Open Search Source have the correct source-id

catalog/transformer/catalog-transformer-tika-input/src/main/java/ddf/catalog/transformer/input/tika/TikaInputTransformer.java, catalog/transformer/catalog-transformer-tika-input/src/test/java/ddf/catalog/transformer/input/tika/TikaInputTransformerTest.java
Forward port of DDF-3317 on 2.11.x
@gordocanchola @peterhuffer 
@clockard
@lessarderic
=> DDF-3317 Fixed TikaInputTransformer parsing wrong metadata 

distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/ContainerPerClassItestSuite.java
This was a backport for https://github.com/codice/ddf/pull/2475
but ended up using a less invasive solution incase we want to turn the test back on in the future.
@coyotesqrl 
[DDF-3279](https://codice.atlassian.net/browse/DDF-3279)
=> DDF-3279 Remove TestEmbeddedSolr since we are testing that case elsewhere

README.md
Fix broken README links
anyone
@clockard
@coyotesqrl
[DDF-3390](https://codice.atlassian.net/browse/DDF-3390)
=> DDF-3390 Fix broken README links

catalog/core/catalog-core-directorymonitor/pom.xml, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/DurableFileAlterationListener.java, catalog/transformer/catalog-transformer-tika-input/src/main/java/ddf/catalog/transformer/input/tika/TikaInputTransformer.java, catalog/transformer/catalog-transformer-tika-input/src/test/java/ddf/catalog/transformer/input/tika/TikaInputTransformerTest.java
DDF-3007 Ensure metacards have the extracted text attribute defined.
DDF-3354 Remove javafx.util.Pair and replace with apache commons Pair class (#2511)
- OpenJDK installs don't have the javafx class so replacing with apache commons Pair class.
Verify CI build passes
[DDF-3007](https://codice.atlassian.net/browse/DDF-3007)
[DDF-3354](https://codice.atlassian.net/browse/DDF-3354)
=> DDF-3007 and DDF-3354 Ports from 2.11.x

catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/SearchCommand.java
This PR fixes the `catalog:search` command from always displaying `?` hits in the console message.
@AzGoalie @peterhuffer
@clockard
@rzwiefel
Verify the hits count in the message printed to the console for some edge cases of the `catalog:search` command:
- No records in catalog
- Many records in catalog (over page size)
- Specifying `SEARCH_PHRASE`
- Specifying `NUMBER_OF_ITEMS`
[DDF-3403](https://codice.atlassian.net/browse/DDF-3403)
- ❗ …
=> DDF-3403 Fixed hit count console message in catalog:search command

catalog/ui/catalog-ui-search/webpack/config/base.js
Update `git st` to `git status` for linux compatibility
@clockard 
@lessarderic 
Wait for PR to go through the CI Pipeline
=> DDF-3357 Update `git st` to `git status` for linux compatibility

catalog/ui/catalog-ui-search/src/main/webapp/component/query-item/query-item.hbs
Fixes typo in tooltip for notifications
@adimka @mackncheesiest 
@bdeining
@millerw8 
[DDF-3406](https://codice.atlassian.net/browse/DDF-3406)
=> DDF-3406 Fixed typo in tooltip for notifications

catalog/core/catalog-core-commons/src/main/java/ddf/util/XPathHelper.java, catalog/core/catalog-core-solrcommands/src/main/java/org/codice/ddf/commands/solr/BackupCommand.java, catalog/schematron/catalog-schematron-plugin/src/main/java/ddf/services/schematron/SvrlReport.java, catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-converter/src/main/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/converter/impl/AbstractFeatureConverterWfs20.java, catalog/transformer/catalog-transformer-service-xslt/src/main/java/ddf/catalog/services/xsltlistener/AbstractXsltTransformer.java, catalog/transformer/catalog-transformer-tika-input/pom.xml, catalog/transformer/catalog-transformer-tika-input/src/main/java/ddf/catalog/transformer/input/tika/TikaInputTransformer.java, catalog/transformer/catalog-transformer-xml/pom.xml, catalog/transformer/catalog-transformer-xml/src/main/java/ddf/catalog/transformer/xml/adapter/StringxmlAdapter.java, catalog/transformer/catalog-transformer-xml/src/main/resources/stringxml.xslt, distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/XmlDocument.java, platform/metrics/platform-metrics-reporting/src/main/java/ddf/metrics/reporting/internal/rest/MetricsEndpoint.java, platform/parser/xml/pom.xml, platform/security/common/src/main/java/org/codice/ddf/security/common/HttpUtils.java, platform/security/handler/security-handler-api/src/main/java/org/codice/ddf/security/handler/api/BSTAuthenticationToken.java, platform/security/idp/security-idp-server/pom.xml, platform/security/pdp/security-pdp-authzrealm/src/main/java/ddf/security/pdp/realm/xacml/processor/XacmlClient.java, platform/util/platform-util/pom.xml, platform/util/platform-util/src/main/java/org/codice/ddf/platform/util/XMLUtils.java, platform/util/platform-util/src/test/java/org/codice/ddf/platform/util/XMLUtilsParameterizedTests.java, platform/util/platform-util/src/test/java/org/codice/ddf/platform/util/XMLUtilsTest.java, platform/util/platform-util/src/test/resources/xxe_injection.txt
Makes improvements based on results found through static analysis of the codebase. Improves XMLUtils, removes dead code, etc.
@bdeining @troymohl 
@coyotesqrl
@millerw8 
Full build to ensure no regressions
[DDF-3360](https://codice.atlassian.net/browse/DDF-3360)
- ❗ …
=> DDF 3360 Improve DDF based on static analysis results

platform/security/core/security-core-impl/src/main/java/ddf/security/config/impl/ConfigurationSecurityLogger.java, platform/security/core/security-core-impl/src/main/java/ddf/security/impl/SubjectImpl.java, platform/security/core/security-core-impl/src/main/java/ddf/security/liberty/paos/impl/RequestMarshaller.java, platform/security/core/security-core-impl/src/main/java/ddf/security/liberty/paos/impl/RequestUnmarshaller.java, platform/security/core/security-core-impl/src/main/java/ddf/security/liberty/paos/impl/ResponseMarshaller.java, platform/security/core/security-core-impl/src/main/java/ddf/security/liberty/paos/impl/ResponseUnmarshaller.java, platform/security/core/security-core-impl/src/main/java/ddf/security/samlp/impl/LogoutMessageImpl.java, platform/security/core/security-core-impl/src/main/java/ddf/security/service/impl/SecurityManagerImpl.java
Resolves SonarQube findings from the `security-core-impl` bundle.
@SmithJosh @emanns95 
@rzwiefel
@stustison
Full CI build and manual sanity test.
[DDF-3420](https://codice.atlassian.net/browse/DDF-3420) …
=> DDF-3420 Resolves static analysis findings for the security-core-impl bundle

catalog/admin/module/catalog-admin-module-sources/src/main/resources/index.html
Adds missing iframe-resizer script to sources ui.
@jefchng
@rzwiefel
- Quick build
- Go to Sources UI
- Add ~15 dummy sources
- Ensure that the iframe increases in size to accommodate all the sources
[DDF-3414](https://codice.atlassian.net/browse/DDF-3414)
=> DDF-3414 Adds missing iframe-resizer script to sources ui.

libs/httpproxy/proxy-camel-route/src/main/java/org/codice/proxy/http/HttpProxyServiceImpl.java
Protects against potential (though unlikely) NPE and cleans up a few SonarQube findings.
@Lambeaux @AzGoalie 
@clockard
@rzwiefel
Full build and CI and quick manual regression test.
[DDF-3409](https://codice.atlassian.net/browse/DDF-3409) …
=> [2.11.x] DDF-3409 Protects against potential NPE in HttpProxyServiceImpl ctor

libs/httpproxy/proxy-camel-route/src/main/java/org/codice/proxy/http/HttpProxyServiceImpl.java
Protects against potential (though unlikely) NPE and cleans up a few SonarQube findings.
(cherry picked from commit 292d944)
@Lambeaux @AzGoalie 
@clockard
@rzwiefel
Full build and CI and quick manual regression test.
[DDF-3409](https://codice.atlassian.net/browse/DDF-3409) …
=> DDF-3409 Protects against potential NPE in HttpProxyServiceImpl ctor

distribution/docs/src/main/resources/content/_installing/ddf-setup-types.adoc, distribution/docs/src/main/resources/content/_installing/firewall-config.adoc, distribution/docs/src/main/resources/content/_installing/high-availability-initial-setup.adoc, distribution/docs/src/main/resources/content/_installing/initial-startup.adoc, distribution/docs/src/main/resources/content/_installing/installing-from-admin-console.adoc, distribution/docs/src/main/resources/content/_installing/installing-from-the-command-line.adoc, distribution/docs/src/main/resources/content/_installing/system-configuration-settings.adoc
Documents the new profile:install command.
@oconnormi @figliold 
@lessarderic 
[DDF-3397](https://codice.atlassian.net/browse/DDF-3397)
=> DDF-3397 Documenting the profile:install command

catalog/core/catalog-core-camelcomponent/src/main/java/ddf/camel/component/catalog/content/FileSystemDataAccessObject.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/impl/FileSystemPersistenceProvider.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/cql/CqlRequest.java
Resolves issues found by a static analysis tool where locale is ignored which could lead to unintended behavior.
@blen-desta @emmberk 
@coyotesqrl
@figliold 
[DDF-3400](https://codice.atlassian.net/browse/DDF-3400) …
=> [2.11.x]DDF-3400 Resolving incorrect String comparisons ignoring locale

catalog/admin/module/catalog-admin-module-sources/src/main/resources/index.html
=> [2.11.x] DDF-3414 Adds missing iframe-resizer script to sources ui.

distribution/docs/src/main/resources/content/_installing/ddf-setup-types.adoc, distribution/docs/src/main/resources/content/_installing/firewall-config.adoc, distribution/docs/src/main/resources/content/_installing/high-availability-initial-setup.adoc, distribution/docs/src/main/resources/content/_installing/initial-startup.adoc, distribution/docs/src/main/resources/content/_installing/installing-from-admin-console.adoc, distribution/docs/src/main/resources/content/_installing/installing-from-the-command-line.adoc, distribution/docs/src/main/resources/content/_installing/system-configuration-settings.adoc
Documents the new profile:install command.
@oconnormi @figliold 
@lessarderic 
[DDF-3397](https://codice.atlassian.net/browse/DDF-3397)
=> [2.11.x]DDF-3397 Documenting the profile:install command

catalog/core/catalog-core-commons/src/main/java/ddf/util/XPathHelper.java, catalog/core/catalog-core-solrcommands/src/main/java/org/codice/ddf/commands/solr/BackupCommand.java, catalog/schematron/catalog-schematron-plugin/src/main/java/ddf/services/schematron/SvrlReport.java, catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-converter/src/main/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/converter/impl/AbstractFeatureConverterWfs20.java, catalog/transformer/catalog-transformer-service-xslt/src/main/java/ddf/catalog/services/xsltlistener/AbstractXsltTransformer.java, catalog/transformer/catalog-transformer-tika-input/pom.xml, catalog/transformer/catalog-transformer-tika-input/src/main/java/ddf/catalog/transformer/input/tika/TikaInputTransformer.java, catalog/transformer/catalog-transformer-xml/pom.xml, catalog/transformer/catalog-transformer-xml/src/main/java/ddf/catalog/transformer/xml/adapter/StringxmlAdapter.java, catalog/transformer/catalog-transformer-xml/src/main/resources/stringxml.xslt, distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/XmlDocument.java, platform/metrics/platform-metrics-reporting/src/main/java/ddf/metrics/reporting/internal/rest/MetricsEndpoint.java, platform/parser/xml/pom.xml, platform/security/common/src/main/java/org/codice/ddf/security/common/HttpUtils.java, platform/security/handler/security-handler-api/src/main/java/org/codice/ddf/security/handler/api/BSTAuthenticationToken.java, platform/security/idp/security-idp-server/pom.xml, platform/security/pdp/security-pdp-authzrealm/src/main/java/ddf/security/pdp/realm/xacml/processor/XacmlClient.java, platform/util/platform-util/pom.xml, platform/util/platform-util/src/main/java/org/codice/ddf/platform/util/XMLUtils.java, platform/util/platform-util/src/test/java/org/codice/ddf/platform/util/XMLUtilsParameterizedTests.java, platform/util/platform-util/src/test/java/org/codice/ddf/platform/util/XMLUtilsTest.java, platform/util/platform-util/src/test/resources/xxe_injection.txt
Makes improvements based on results found through static analysis of the codebase. Improves XMLUtils, removes dead code, etc.
(Cherry pick of https://github.com/codice/ddf/commit/2950ff7f1ecb48e9f4518d158347fcc4376ac853)
@bdeining @troymohl 
@coyotesqrl
@millerw8
Full build to ensure no regressions
[DDF-3360](https://codice.atlassian.net/browse/DDF-3360) …
=> [2.11.x] DDF-3360 Improve DDF based on static analysis results

platform/security/servlet/security-servlet-logout/src/main/java/org/codice/ddf/security/servlet/logout/LogoutService.java
Forward port of DDF-3402 from 2.11.x
https://github.com/codice/ddf/pull/2549
@clockard
@coyotesqrl
=> DDF-3402 Added cache control headers to LogoutService

catalog/core/catalog-core-camelcomponent/src/main/java/ddf/camel/component/catalog/content/FileSystemDataAccessObject.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/impl/FileSystemPersistenceProvider.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/cql/CqlRequest.java
Resolves issues found by a static analysis tool where locale is ignored which could lead to unintended behavior.
@blen-desta @emmberk 
@coyotesqrl
@figliold 
[DDF-3400](https://codice.atlassian.net/browse/DDF-3400) …
=> DDF-3400 Resolving incorrect String comparisons ignoring locale

catalog/core/catalog-core-solrcommands/src/main/java/org/codice/ddf/commands/solr/BackupCommand.java
Fixes an invalid URL that was introduced as a part of #2468 
@clockard 
@bdeining 
@coyotesqrl
CI build
[DDF-3360](https://codice.atlassian.net/browse/DDF-3360) …
=> DDF-3360 Fixed invalid URL in BackupCommand

distribution/docs/src/main/resources/content/_installing/installing-intro.adoc, distribution/docs/src/main/resources/content/_running/starting-intro.adoc
Update the requirements section of the docs as well as correct a few typos in the automatic start section.
@ryeats @djblue @clockard @lessarderic @vinamartin @shaundmorris
@codice/docs 
Read through the changes.
[DDF-3358](https://codice.atlassian.net/browse/DDF-3358)
=> DDF-3358 Updated Requirements table details and auto install notes

catalog/spatial/geocoding/spatial-geocoding-api-impl/src/test/java/org/codice/ddf/spatial/geocoding/context/impl/NearbyLocationImplTest.java, catalog/spatial/geocoding/spatial-geocoding-lucene/src/test/java/org/codice/ddf/spatial/geocoding/query/TestGeoNamesQueryLuceneIndex.java, platform/security/pdp/security-pdp-authzrealm/src/main/java/ddf/security/pdp/realm/xacml/XacmlPdp.java, platform/security/pdp/security-pdp-authzrealm/src/test/java/ddf/security/pdp/realm/xacml/XacmlPdpTest.java
Updates unit tests to build on locales with comma-separated decimals
@garrettfreibott @rzwiefel @mcalcote @josephthweatt 
@clockard
@rzwiefel
Set system language/locale to Swedish and run a full build. 
=> DDF-3415 Updates unit tests to build on locales with comma-separated decimals

catalog/solr/catalog-solr-solrclient/src/main/java/ddf/catalog/source/solr/rest/SolrRest.java, catalog/solr/catalog-solr-solrclient/src/main/java/ddf/catalog/source/solr/rest/SolrUpdateClient.java, catalog/solr/catalog-solr-solrclient/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/solr/catalog-solr-solrclient/src/main/resources/OSGI-INF/metatype/metatype.xml, catalog/solr/catalog-solr-solrclient/src/test/java/ddf/catalog/source/solr/rest/SolrRestTest.java
Updates the metacard_cache solr core with the same values as catalog core. Also requests Solr optimize after settings are changed.
@glenhein 
@millerw8  
@bdeining
@pklinef
Full build. 
Manually change Solr Relevancy settings within the Solr admin tile.
Verify relevancy is updated for each core:
https://localhost:8993/solr/catalog/schema
https://localhost:8993/solr/metacard_cache/schema
[DDF3421](https://codice.atlassian.net/browse/DDF-3421) …
=> DDF-3421 Add call to Solr update to re-optimize index after setting change

catalog/spatial/csw/spatial-csw-source/src/main/resources/OSGI-INF/metatype/metatype.xml, distribution/docs/src/main/resources/content/_tables/Csw_Federation_Profile_Source.adoc
Port of https://github.com/codice/ddf/pull/2577
@figliold
[DDF-3419](https://codice.atlassian.net/browse/DDF-3419)
=> DDF-3419 Add timeout parameters to CSW federation source metatype (#2577)

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/UpdateOperations.java
Port of https://github.com/codice/ddf/pull/2600
@coyotesqrl
@rzwiefel
[DDF-3425](https://codice.atlassian.net/browse/DDF-3425)
=> DDF-3425 Fix UpdateOperations page size (#2600)

catalog/spatial/registry/registry-admin-modules/registry-admin-remote-ui/src/main/webapp/js/model/Registry.js
Port of https://github.com/codice/ddf/pull/2576
@bdeining
@rzwiefel
Passing CI build
[DDF-3417](https://codice.atlassian.net/browse/DDF-3417)
=> DDF-3417 Fix remote registry delete modal closing issue (#2576)

catalog/ui/catalog-ui-search/src/main/webapp/js/store.js
Fixed capitalization issue in store.js
@Variadicism @mojogitoverhere 
@bdeining
Full build, install, make sure you can access Intrigue.
[DDF-3429](https://codice.atlassian.net/browse/DDF-3429)
=> DDF-3429 Fixed capitalization issue in store.js

distribution/docs/src/main/resources/content/_installing/installing-intro.adoc, distribution/docs/src/main/resources/content/_running/starting-intro.adoc
Update the requirements section of the docs as well as correct a few typos in the automatic start section.
@ryeats @djblue @clockard @lessarderic @ricklarsen @vinamartin @shaundmorris 
=> [2.11.x] DDF-3358 Updated Requirements docs detail and auto install notes

platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/migration/ImportMigrationContextImplTest.java
It fixed an unstable test case which showed up in Jenkins.
@tbatie 
@emanns95 
@clockard
@figliold
Build the platform-migration project with test cases and make sure it passes which the Jenkins build will be doing.
[DDF-3383](https://codice.atlassian.net/browse/DDF-3383) …
=> DDF-3383 fixed unstable test case

distribution/docs/src/main/resources/content/_installing/ie11-configuration.adoc, distribution/docs/src/main/resources/content/_installing/installing-intro.adoc, distribution/docs/src/main/resources/content/_quickstart/quickstart-installing.adoc
Adds information about configuring IE11 for use with the latest release.
@ricklarsen @clockard @lessarderic @shaundmorris 
@codice/docs 
View rich diff to ensure content is accurate.
=> [2.11.x] DDF-2881 Update IE11 security configuration documentation

distribution/docs/src/main/resources/content/_architectures/migration-api.adoc, distribution/docs/src/main/resources/content/_installing/installing-intro.adoc
- fixes table caption for Installation Prerequisites
- fixes title ordering in migration API docs
@clockard
@coyotesqrl
@lessarderic
@pklinef
@rzwiefel
@shaundmorris
- builds are successful. 
- content updated.
=> [2.11.x] DDF-2824 fixed install prereq caption & migration api titles

catalog/pom.xml, catalog/transformer/pom.xml, libs/klv/pom.xml, platform/pom.xml, pom.xml
Updates DDF to use latest thirdparty tika-bundle.  
**This PR depends on https://github.com/codice/thirdparty/pull/17**
@derekwilhelm 
@codice/build 
@bdeining
@clockard
[](https://codice.atlassian.net/browse/DDF-3442) …
=> DDF-3442 updates tika-bundle version

catalog/pom.xml, catalog/transformer/pom.xml, libs/klv/pom.xml, platform/pom.xml, pom.xml
backport of https://github.com/codice/ddf/pull/2633
Updates DDF to use latest thirdparty tika-bundle.  
**This PR depends on https://github.com/codice/thirdparty/pull/17**
@derekwilhelm 
@codice/build 
@bdeining
@clockard
[](https://codice.atlassian.net/browse/DDF-3442)
- ❗ …
=> [2.11.x] DDF-3442 update tika-bundle version to resolve OWASP finding

platform/solr/platform-solr-server-standalone/dependency-check-maven-config.xml
Adds Suppression for Solr 6.6.1 CVE-2017-12629.
@clockard
@lessarderic
@coyotesqrl
Run OWASP
https://codice.atlassian.net/browse/DDF-3279
Screenshots (if appropriate)
Checklist:
Review Comment Legend:
✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist.
❓ (Question Mark) This comment is …
=> [2.11.x] DDF-3279: Added Suppression for Solr 6.6.1 CVE-2017-12629

distribution/docs/src/main/resources/content/_installing/ie11-configuration.adoc, distribution/docs/src/main/resources/content/_installing/installing-intro.adoc, distribution/docs/src/main/resources/content/_quickstart/quickstart-installing.adoc
Adds information about configuring IE11 for use with the latest release.
@ricklarsen @clockard @lessarderic @shaundmorris 
@codice/docs 
View rich diff to ensure content is accurate.
=> DDF-2881 Update IE11 security configuration documentation

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/config/ConfigurationApplication.java, catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.config.xml, catalog/ui/catalog-ui-search/src/main/webapp/component/navigation-left/navigation-left.hbs, catalog/ui/catalog-ui-search/src/main/webapp/component/navigation-left/navigation-left.less, catalog/ui/catalog-ui-search/src/main/webapp/component/navigation-left/navigation-left.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/navigation/navigation.hbs, catalog/ui/catalog-ui-search/src/main/webapp/component/navigation/navigation.less, catalog/ui/catalog-ui-search/src/main/webapp/component/navigation/navigation.view.js, catalog/ui/catalog-ui-search/src/main/webapp/index.html, catalog/ui/catalog-ui-search/src/main/webapp/js/application.js, catalog/ui/catalog-ui-search/src/main/webapp/styles/mixins.less, catalog/ui/search-ui-app/src/main/resources/etc/org.codice.ddf.catalog.ui.config.config, distribution/docs/src/main/resources/content/_tables/ui.config 2.adoc, platform/platform-configuration/src/main/java/org/codice/ddf/configuration/PlatformUiConfiguration.java, platform/platform-configuration/src/test/java/org/codice/ddf/configuration/PlatformUiConfigurationTest.java
Adds a logo in the title bar that can be toggled in the admin UI. It is hidden by default. The product image from the branding plugin is used as the logo.
@djblue @adimka @bdeining @glenhein @Variadicism @brianfelix @mackncheesiest 
@millerw8 
Go to the admin UI and verify the "Show Logo in Title Bar" setting is unchecked by default in the Catalog UI Search settings. Verify no logo is shown. Toggle the checkbox and verify the product image from the branding plugin is added in the top right corner of all Intrigue pages.
[DDF-1983](https://codice.atlassian.net/browse/DDF-1983)
- ✏️ …
=> DDF-1983 Optionally add a logo to the title bar

catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/RemoveAllCommand.java, distribution/docs/src/main/resources/content/_running/command-scheduler.adoc, platform/platform-scheduler/pom.xml, platform/platform-scheduler/src/main/java/ddf/platform/scheduler/CommandJob.java, platform/platform-scheduler/src/main/java/ddf/platform/scheduler/ScheduledCommandTask.java, platform/platform-scheduler/src/main/java/ddf/platform/scheduler/ScheduledTask.java, platform/platform-scheduler/src/main/java/ddf/platform/scheduler/ServiceStore.java, platform/platform-scheduler/src/main/resources/OSGI-INF/metatype/metatype.xml, platform/platform-scheduler/src/main/resources/quartz.properties, platform/platform-scheduler/src/test/java/ddf/platform/scheduler/CommandJobTest.java, platform/security/common/src/main/java/org/codice/ddf/security/common/Security.java
Port of https://github.com/codice/ddf/pull/2559
@clockard
[DDF-3335](https://codice.atlassian.net/browse/DDF-3335)
=> DDF-3335 Added delayed start to Platform Command Scheduler jobs

distribution/docs/src/main/resources/content/_appReferences/mg-broker-app.adoc
Fixes docs to give a working example, since we upgraded to Artemis 2.1
@ryeats @jrnorth @roelens8 
@codice/docs 
@jaymcnallie
Could try to set up two DDFs in a HA Artemis cluster 
Artemis changed some of the mbeans in the transition from 1.X to 2.X, this bring us up to date.
N/A …
=> DDF-3029 Update broker docs to match Artemis 2.1 Jolokia call

distribution/ddf-common/.gitattributes, distribution/ddf-common/src/main/resources/bin/ddf, distribution/ddf-common/src/main/resources/bin/ddf.bat, distribution/ddf-common/src/main/resources/bin/ddf_on_error.bat, distribution/ddf-common/src/main/resources/bin/ddf_on_error.sh, distribution/ddf-common/src/main/resources/bin/setenv-windows-wrapper.conf, distribution/ddf-common/src/main/resources/bin/setenv.bat, distribution/ddf-common/src/main/resources/bin/start, distribution/ddf-common/src/main/resources/bin/start.bat, distribution/ddf-common/src/main/resources/common-bin.xml, distribution/docs/src/main/resources/content/_running/starting-intro.adoc, pom.xml
This PR adds support to Windows for automatically restarting ddf when a fatal error is detected and when an out of memory error is detected. It also fixes the restart when ddf is started via the service wrapper.
@tbatie 
@emanns95 
@figliold 
@clockard
@coyotesqrl
@lessarderic
1. Unzip and install the distribution on Windows
2. Go through the installation and make sure that the restart step at the end still works
3. Force an out of memory (see below). The process should restart
4. run a migration:export followed by a migration:import, the process should restart automatically
5. Go through the documentation to install the service wrapper
6. re-do step #2 and #4 via the client.bat tool
The …
=> DDF-3416 Added OutOfMemory and VM error support on Windows

platform/solr/solr-factory/src/main/java/org/codice/solr/factory/impl/HttpSolrClientFactory.java
Backport of https://github.com/codice/ddf/pull/2602
Closes client sockets in HttpSolrClientFactory
@brjeter @Lambeaux 
@coyotesqrl
@lessarderic
@pklinef 
Full build.
Install, ingest, queries, and save/read a workspace.
[DDF-3426](https://codice.atlassian.net/browse/DDF-3426)
=> [2.11.x] DDF-3426 Close client sockets in HttpSolrClientFactory

pom.xml
Update gitflow incremental builder to latest version
@codice/build @lessarderic @LinkMJB @oconnormi @clockard 
Make a trival change on top of this version bump and then use gib maven command to confirm the incremental build works.
`mvn clean install -B -T 1C -pl -Dgib.enabled=true -Dgib.referenceBranch=/refs/remotes/origin/$CHANGE_TARGET`
https://github.com/vackosar/gitflow-incremental-builder …
=> DDF-3374 Updated gitflow incremental builder to latest version

Documentation-versions.html
updates ddf.codice.org for 2.11.1 release
@lessarderic
@rzwiefel
verify versions have updated.
=> DDF-2748 updated website for 2.11.1 release

catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java, catalog/spatial/csw/spatial-csw-endpoint/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/TestCswEndpoint.java
Make CswEndpoint extendable so that 3rd-party QueryFilterTransformers can supply a list of type names that get dynamically merged into the type names used for GetCapabilities GetRecords and DescribeRecord.
@bdeining 
@troymohl 
@coyotesqrl 
@lessarderic
@millerw8
Run unit tests.
[DDF-3435](https://codice.atlassian.net/browse/DDF-3435) …
=> DDF-3435 make the list of type names in GetCapabilities extendable

PULL_REQUEST_TEMPLATE
Adds a section on how our process _temporarily_ changes after branching.
@mcalcote @vinamartin @lessarderic 
@clockard
@pklinef
N/A
This will better centralize documentation of the temporary process change following branching. …
=> [2.11.x] Updates PR Template with notes for how to handle porting between branches

PULL_REQUEST_TEMPLATE
Adds a section on how our process _temporarily_ changes after branching.
@mcalcote @vinamartin @lessarderic 
@clockard
@pklinef
N/A
This will better centralize documentation of the temporary process change following branching. …
=> Updates PR Template with notes for how to handle porting between branches

catalog/ui/catalog-ui-search/src/main/webapp/component/query-basic/query-basic.view.js
Ports #2645 from 2.11.x into master
@clockard 
=> DDF-3444 fixing doubled anyText filter in Intrigue basic query (#2645)

platform/admin/ui/src/main/webapp/js/views/configuration/Service.view.js, platform/admin/ui/src/main/webapp/templates/configuration/configurationRow.handlebars
Port: https://github.com/codice/ddf/pull/2621
@pklinef @rzwiefel
=> DDF-3436 Removes the ability to delete non factory configurations

platform/solr/solr-factory/src/main/java/org/codice/solr/factory/impl/HttpSolrClientFactory.java
Closes client sockets in HttpSolrClientFactory
@brjeter @Lambeaux 
@coyotesqrl
@lessarderic
@pklinef 
Full build
Install, ingest, queries, and save/read a workspace.
[DDF-3426](https://codice.atlassian.net/browse/DDF-3426)
=> DDF-3426 Close client sockets in HttpSolrClientFactory

catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/operation/impl/TermFacetPropertiesImpl.java
Changes the default value to be counted as a facet result to 1 from 0.
There should be at least one occurrence of a value to be returned as a facet result.
@mackncheesiest @Variadicism 
@bdeining
@rzwiefel
Unit and itests should be sufficient.
[DDF-3456](https://codice.atlassian.net/browse/DDF-3456)
Certain exceptions may occur. For example, if there is a problem with the CI environment then a manually performed full build and static analysis …
=> DDF-3456 Set default minimum facet count to 1 for faceted queries

distribution/docs/src/main/resources/content/_architectures/migration-api.adoc, distribution/docs/src/main/resources/content/_installing/installing-intro.adoc
**PORT of PR https://github.com/codice/ddf/pull/2626**
- fixes table caption for Installation Prerequisites
- fixes title ordering in migration API docs
@clockard
@coyotesqrl
@lessarderic
@pklinef
@rzwiefel
@shaundmorris
- builds are successful. 
- content updated. …
=> DDF-2824 fixed install prereq caption & migration api titles

catalog/ui/catalog-ui-search/src/main/webapp/component/query-altitude/query-altitude.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/query-settings/query-settings.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/sort-item/sort-item.view.js
This PR fixes the issues that Intrigue searches do not save the Sort Attribute any time that both the Sort Attribute and selected Sources are modified.
@peterhuffer @AzGoalie @oconnormi 
@codice/ui 
@clockard
@rzwiefel
Modify both the `Sort Attribute` and selected `Sources` in a search in Intrigue, and confirm that the fields are saved (even after refreshing) and that the search results are correct. Confirm that the query settings still work on basic search, advanced search, and result filtering view.
[DDF-3458](https://codice.atlassian.net/browse/DDF-3458)
Certain exceptions may occur. For example, if there is a problem with the CI environment then a manually performed full build and static analysis check may be substituted _at the …
=> [2.11.x] DDF-3458 Fixed an issue where the Sort Attribute was not being saved in Intrigue searches

distribution/docs/src/main/resources/content/_installing/ddf-setup-types.adoc
Fixes typo in installing docs -> Setup types; links and app list
@lessarderic
@rzwiefel
verify list accuracy; verify links;
[documentation.pdf](https://github.com/codice/ddf/files/1471976/documentation.pdf)
Certain exceptions may occur. For example, if there is a problem with the CI environment then a manually performed full build and static analysis check may be substituted _at the discretion of the repository maintainers_. Additionally, …
=> DDF-2824 fixed links in Setup Type docs

catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/XstreamPathConverter.java, catalog/spatial/csw/spatial-csw-transformer/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/TestXstreamPathConverter.java
Fixes a case where the text after nested element data wasn't being returned.
Previous PR: https://github.com/codice/ddf/pull/2658
@adimka
@glenhein
@bdeining
@millerw8
Full build.
[DDF-3451](https://codice.atlassian.net/browse/DDF-3451)
Certain exceptions may occur. For example, if there is a problem with the CI environment then a manually performed full build and static analysis check may be substituted _at the discretion of the repository …
=> DDF-3451 Add handling for END_ELEMENT data in XstreamPathConverter

catalog/ui/catalog-ui-search/src/main/webapp/component/query-altitude/query-altitude.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/query-settings/query-settings.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/sort-item/sort-item.view.js
____
Port of https://github.com/codice/ddf/pull/2672
@clockard
[DDF-3458](https://codice.atlassian.net/browse/DDF-3458)
=> DDF-3458 Fixed an issue where the Sort Attribute was not being saved in Intrigue searches

Documentation-versions.html, index.html
updates ddf.codice.org for release of 2.11.2 version
@clockard
@lessarderic
@shaundmorris
verify versions updated on Index and Documentation-versions pages
Certain exceptions may occur. For example, if there is a problem with the CI environment then a manually performed full build and static analysis check may be substituted _at the discretion of the repository maintainers_. Additionally, repository metadata such as this `PULL_REQUEST_TEMPLATE`, the repository …
=> DDF-2748 updated website for 2.11.2 version

catalog/transformer/catalog-transformer-tika-input/src/main/java/ddf/catalog/transformer/input/tika/TikaInputTransformer.java, distribution/docs/src/main/resources/content/_metadataAttributes/complete-list-file-types.adoc
Browsers on windows will interpret some visio files as having a mime type of "application/vnd.ms-visio.viewer".  Adding this registration to the tika transformer.
@brendan-hofmann @gordocanchola 
@bdeining
@clockard
On windows - using any browser - ensure visio files ingest successfully via Intrigue.
[](https://codice.atlassian.net/browse/DDF-3459)
Certain …
=> [2.11.x] DDF-3459 adds tika support for application/vnd.ms-visio.viewer

dependency-check-maven-config.xml, platform/solr/platform-solr-server-standalone/dependency-check-maven-config.xml
Suppresses a CVE that does not apply to DDF. **NOTE: This is blocking builds.**
@mackncheesiest @ryeats 
@clockard
@coyotesqrl 
[DDF-3472](https://codice.atlassian.net/browse/DDF-3472)
Certain exceptions may occur. For example, if there is a problem with the CI environment then a manually performed full build and static analysis check may be substituted _at the discretion of the repository …
=> [2.11.x]DDF-3472 Suppressing warning for Xerces OWASP finding

dependency-check-maven-config.xml, platform/solr/platform-solr-server-standalone/dependency-check-maven-config.xml
Master port for https://github.com/codice/ddf/pull/2703
Suppresses a CVE that does not apply to DDF. **NOTE: This is blocking builds.**
@mackncheesiest @ryeats @vinamartin 
@clockard
@coyotesqrl 
[DDF-3472](https://codice.atlassian.net/browse/DDF-3472)
Certain exceptions may occur. For example, if there is a problem with the CI environment then a manually performed full build and static …
=> DDF-3472 Suppressing warning for Xerces OWASP finding

distribution/docs/src/main/resources/content/_metadataAttributes/complete-list-file-types.adoc
Fixed error in appendix resulting from uneven table rows. 
Added a comment for future editing and maintenance.
@rzwiefel
No missing cells in rendered documentation.
asciidoctor quirk. need to have empty cells to fill out number of columns.
[documentation.pdf](https://github.com/codice/ddf/files/1489333/documentation.pdf)
Certain exceptions may occur. For example, if there is a problem with the CI environment then a …
=> DDF-2824 fixed error in appendix table

platform/email/platform-email-api/src/main/java/org/codice/ddf/platform/email/SmtpClient.java, platform/email/platform-email-impl/pom.xml, platform/email/platform-email-impl/src/main/java/org/codice/ddf/platform/email/impl/SmtpClientImpl.java
Fixed logging and API for email service
Fixed logging and API for email service
@glenhein @troymohl 
@millerw8
@rzwiefel
Build
The current implementation does nothing to help diagnose an error when the message fails to send.  The current implementation of the API does not throw a MessageException
[DDF-2494](https://codice.atlassian.net/browse/DDF-2494) …
=> DDF-2494 Fixed logging and API for email service

dependency-check-maven-config.xml
- Suppressing several CVEs (these are all below our build failing threshold). Most of them were incorrectly reported by the `dependency-check-maven` plugin. Some just do not apply to DDF.
- ~Upgraded the version of poi to address CVE-2016-5000~
@vinamartin @mcalcote 
@clockard 
@lessarderic 
@shaundmorris
@stustison
- In the root pom, change `failBuildOnCVSS` configuration for `dependency-check-maven` to 0 instead of 7
- Run `mvn clean install -fn -Powasp -DskipStatic=true -DwebBuildEnv=dev -DskipTests=true`. This will run the OWASP plugin and continue the whole build on failures.
- Verify there are no additional CVEs reported …
=> DDF-3472 Suppressing a long list of CVEs

platform/admin/configurator/admin-configurator-actions-api/src/main/java/org/codice/ddf/internal/admin/configurator/actions/ConfiguratorSuite.java, platform/admin/configurator/admin-configurator-impl/src/main/java/org/codice/ddf/admin/configurator/impl/ConfiguratorSuiteImpl.java, platform/admin/configurator/admin-configurator-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml
The ConfiguratorSuite service is used to group the ConfiguratorFactory and Actions under one service.
@paouelle @peterhuffer 
none
@coyotesqrl
@figliold 
@clockard 
CI passes
Certain exceptions may occur. For example, if there is a problem with the CI environment then a manually performed full build and static analysis check may be substituted _at the …
=> DDF-2825: Move ConfiguratorSuite to DDF

platform/admin/configurator/admin-configurator-actions-api/src/main/java/org/codice/ddf/internal/admin/configurator/actions/ConfiguratorSuite.java, platform/admin/configurator/admin-configurator-impl/src/main/java/org/codice/ddf/admin/configurator/impl/ConfiguratorSuiteImpl.java, platform/admin/configurator/admin-configurator-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml
The ConfiguratorSuite service is used to group the ConfiguratorFactory and Actions under one service.
@paouelle @peterhuffer 
none
@coyotesqrl
@figliold 
@clockard 
Certain exceptions may occur. For example, if there is a problem with the CI environment then a manually performed full build and static analysis check may be substituted _at the discretion …
=> [2.11.x] DDF-2825: Move ConfiguratorSuite to DDF

distribution/docs/src/main/resources/content/_configuring/solr-synonyms.adoc, platform/solr/platform-solr-server-standalone/src/main/resources/solr/conf/schema.xml
Configures synonym support on the text indexes used for keyword/anyText searches.
@ahoffer 
@ricklarsen 
@pklinef
Verify that synonym matching works for keyword queries from Intrigue.  Synonyms are configured in data/solr/catalog/conf/synonyms.txt
[](https://codice.atlassian.net/browse/DDF-3476)
Certain exceptions may occur. For example, if there is a problem with the CI environment then a manually performed full build and static analysis check may be substituted _at the …
=> DDF-3476 adds synonym matching on all text indexes

dependency-check-maven-config.xml, distribution/ddf-common/src/main/resources-filtered/etc/system.properties, platform/solr/platform-solr-server-standalone/dependency-check-maven-config.xml, platform/solr/platform-solr-server-standalone/src/main/resources/solr/conf/solrconfig-inmemory.xml, platform/solr/platform-solr-server-standalone/src/main/resources/solr/conf/solrconfig.xml, pom.xml
- Upgrades to Solr 6.6.2
- Removes Solr 6.6.1 owasp suppressions 
- Reverts change that disabled Solr Config API (https://github.com/codice/ddf/pull/2509/files)
Solr 6.6.2 Release Notes: https://lucene.apache.org/solr/6_6_2/changes/Changes.html#v6.6.2
Previous Solr Upgrade 6.6.1: https://github.com/codice/ddf/pull/2305
I've manually verified there have been no webapp changes or dependencies that need to be changed.
@mcalcote @ahoffer @emanns95 @clockard @millerw8 @stustison 
@coyotesqrl @brjeter 
@figliold
@lessarderic
(Instructions from the last upgrade)
Full build.
Configure it to use stand-alone solr, embedded solr, and solr cloud. In all three scenarios, confirm ability to ingest metacards, save workspaces, and query.
[DDF-3440](https://codice.atlassian.net/browse/DDF-3440)
For the …
=> [2.11.x]DDF-3440 Upgrades to Solr 6.6.2

catalog/transformer/catalog-transformer-geojson-queryresponse/pom.xml, catalog/transformer/catalog-transformer-geojson-queryresponse/src/main/java/ddf/catalog/transformer/queryresponse/geojson/GeoJsonQueryResponseTransformer.java, catalog/transformer/catalog-transformer-geojson-queryresponse/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/transformer/catalog-transformer-geojson-queryresponse/src/test/java/ddf/catalog/transformer/queryresponse/geojson/TestGeoJsonQueryResponseTransformer.java
Refactors the `GeoJsonQueryResonseTransformer` by making the metacard transformer used to generate the `properties` JSON blob configurable.
@adimka @mackncheesiest @Variadicism @brianfelix @dcruver @glenhein @troymohl 
@bdeining 
@millerw8
Full build. Manually verify https://localhost:8993/services/catalog/query?q=*&format=geojson can still be reached and metacard attributes can be viewed under the `properties` field.
[DDF-3474](https://codice.atlassian.net/browse/DDF-3474)
* Review by at least two …
=> DDF-3474 Made the metacard transformer in the geojson OS response configurable

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/monitor/impl/SubscriptionsPersistentStoreImpl.java
Fixes workspace subscriptions
@glenhein @adimka 
@clockard
@lessarderic
Certain exceptions may occur. For example, if there is a problem with the CI environment then a manually performed full build and static analysis check may be substituted _at the discretion of the repository maintainers_. Additionally, repository …
=> DDF-3465 Fixed workspace subscriptions

Jenkinsfile
Removed scripted parallel stage syntax and TODOs related to the DSL.
@oconnormi @mackncheesiest @vinamartin @blen-desta @LinkMJB 
@codice/build 
@clockard @shaundmorris
These changes were run in the local test jenkins under "matt test multibranch".
[DDF-2971](https://codice.atlassian.net/browse/DDF-2971)
Certain exceptions may occur. For example, if there is a problem with the CI environment then a manually performed full build and static analysis check may be substituted _at the discretion of the repository maintainers_. Additionally, repository …
=> DDF-2971 Refactor the Jenkinsfile to match updated Jenkins DSL

catalog/core/catalog-core-standardframework/pom.xml, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/SortedQueryMonitor.java, catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/cache/solr/impl/SortedQueryMonitorTest.java
Adds attribute sorting to SortedQueryMonitor
@adimka 
@mackncheesiest  
@bdeining
@millerw8
@pklinef 
Currently sorting is only done by relevance, temporal, or distance. This adds the ability to sort by other attributes when aggregating results from multiple sources.
[DDF-3477](https://codice.atlassian.net/browse/DDF-3477)
Certain exceptions may occur. For example, if there is a problem with the CI environment then a manually performed full build and static analysis check may be substituted _at the discretion …
=> DDF-3477 Add attribute sorting to SortedQueryMonitor

distribution/console-branding/src/main/resources/org/apache/karaf/branding/branding.properties
Removes hardcoded admin console link on console.
@emanns95 
@tbatie 
@djblue 
@clockard
@figliold
Unzip distro and check console, it should no longer show `Open a browser to https://localhost:8993/admin to access the Admin Console.`
[DDF-3481](https://codice.atlassian.net/browse/DDF-3481)
Certain exceptions may occur. For example, if there is a problem with the CI environment then a manually performed full build …
=> [2.11.x] DDF-3481 Removed hardcoded admin console link in branding.properties

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/monitor/impl/SubscriptionsPersistentStoreImpl.java
Fixes workspace subscriptions
@glenhein @adimka 
@clockard
@lessarderic
Certain exceptions may occur. For example, if there is a problem with the CI environment then a manually performed full build and static analysis check may be substituted _at the discretion of the repository maintainers_. Additionally, repository …
=> [2.11.X] DDF-3465 Fixed workspace subscriptions

distribution/docs/src/main/resources/content/_configuring/configuring-guest-access.adoc, distribution/docs/src/main/resources/content/_quickstart/quickstart-configuring.adoc, distribution/docs/src/main/resources/content/_quickstart/quickstart-ingesting.adoc, distribution/docs/src/main/resources/content/_running/ingesting.adoc, distribution/docs/src/main/resources/content/_securityFramework/guest-interceptor.adoc
updates configuration and ingest docs to highlight the guest claims handler configuration.
@clockard
@lessarderic
@rzwiefel
@shaundmorris
@stustison
review revised content.
[DDF-3482](https://codice.atlassian.net/browse/DDF-3482)
[documentation.pdf](https://github.com/codice/ddf/files/1528950/documentation.pdf)
Certain exceptions may occur. For example, if there is a problem with the CI environment then a manually performed full build and static analysis check may be …
=> DDF-3482 updated guest claims documentation.

distribution/docs/src/main/resources/content/_metadataAttributes/complete-list-file-types.adoc, distribution/docs/src/main/resources/content/_running/supported-file-formats.adoc
updates data management section of docs to fix links to appendix sections
@mcalcote @AzGoalie @vinamartin @ahoffer @garrettfreibott 
@clockard
@coyotesqrl
@lessarderic
@rzwiefel
builds successfully, links have been corrected.
[documentation.pdf](https://github.com/codice/ddf/files/1535932/documentation.pdf)
Certain exceptions may occur. For example, if there is a problem with the CI environment then a manually performed full build and static analysis check may be …
=> DDF-2824 fixed broken link in docs

platform/security/core/security-core-impl/src/main/java/ddf/security/config/impl/ConfigurationSecurityLogger.java, platform/security/core/security-core-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/security/platform-security-core-api/src/main/java/ddf/security/common/audit/SecurityLogger.java
Auditing the action of a configuration (created, updated ...) with the pid instead of the entire configuration.
@brjeter @tbatie 
@coyotesqrl
@rzwiefel
Verify that passwords are not printed in plain text in the security log by
* Creating and updating sources from the Admin Console and the Sources Wizard
* Connecting to LDAP through the Admin Console and the LDAP Wizard
- Login and LDAP Claims Handler from the Admin Console 
- Authentication and Attribute store from the LDAP Wizard
[DDF-3469](https://codice.atlassian.net/browse/DDF-3469)
Certain …
=> DDF-3469 Sanitize passwords from the security log

platform/security/core/security-core-impl/src/main/java/ddf/security/config/impl/ConfigurationSecurityLogger.java, platform/security/core/security-core-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/security/platform-security-core-api/src/main/java/ddf/security/common/audit/SecurityLogger.java
Backport of https://github.com/codice/ddf/pull/2702
Auditing the action of a configuration (created, updated ...) with the pid instead of the entire configuration.
@brjeter @tbatie 
@coyotesqrl
@rzwiefel
Verify that passwords are not printed in plain text in the security log by
* Creating and updating sources from the Admin Console and the Sources Wizard
* Connecting to LDAP through the Admin Console and the LDAP Wizard
- Login and LDAP Claims Handler from the Admin Console 
- Authentication and Attribute store from the LDAP Wizard
[DDF-3469](https://codice.atlassian.net/browse/DDF-3469)
* …
=> [2.11.x] DDF-3469 Sanitize passwords in the security log

distribution/docs/src/main/resources/content/_quickstart/quickstart-installing.adoc
Adds a step to quickstart installation instructions to use `waitForReady` command.
@mcalcote @vinamartin @ahoffer @rzwiefel @garrettfreibott 
@clockard
@lessarderic
@rzwiefel
[DDF-3483](https://codice.atlassian.net/browse/DDF-3483)
Certain exceptions may occur. For example, if there is a problem with the CI environment then a manually performed full build and static analysis check may be substituted _at the discretion of the repository maintainers_. Additionally, repository metadata such as this …
=> DDF-3483 added note about waitForReady command to docs

catalog/core/catalog-core-camelcomponent/src/main/java/ddf/camel/component/catalog/ingest/PostIngestConsumer.java, catalog/plugin/catalog-plugin-metacardbackup-filestorage/pom.xml, catalog/plugin/catalog-plugin-metacardbackup-filestorage/src/main/java/org/codice/ddf/catalog/plugin/metacard/backup/storage/filestorage/MetacardFileStorageRoute.java, catalog/plugin/catalog-plugin-metacardbackup-s3storage/pom.xml, catalog/plugin/catalog-plugin-metacardbackup-s3storage/src/main/java/org/codice/ddf/catalog/plugin/metacard/backup/storage/s3storage/MetacardS3StorageRoute.java, catalog/plugin/catalog-plugin-metacardbackup-s3storage/src/main/resources/OSGI-INF/metatype/metatype.xml, catalog/plugin/catalog-plugin-metacardbackup-storage-common/pom.xml, catalog/plugin/catalog-plugin-metacardbackup-storage-common/src/main/java/org/codice/ddf/catalog/plugin/metacard/backup/common/MetacardStorageRoute.java
Fixes errors where the Camel storage routes:
1. Updated PostIngestConsumer to start more threads and not constrain backlog.
2. Fixed camel creation errors when updating route definitions via metatype.
3. Updated Amazon S3 Secret Key field to be text. This avoids encoding empty strings as passwords for systems using roles on EC2 containers.
@adimka  
@glenhein 
@bdeining
@millerw8
Configure multiple Storage routes. 
Add/Remove/Update them
Ingest data and verify it is stored in the correct location(s).
[DDF-3470](https://codice.atlassian.net/browse/DDF-3470)
* Successful static …
=> DDF-3470 Fix error with camel storage routes

libs/httpproxy/proxy-camel-servlet/src/main/java/org/codice/proxy/http/HttpProxyCamelHttpTransportServlet.java, platform/platform-app/pom.xml, platform/platform-app/src/main/resources/features.xml, pom.xml
Upgrade Camel to 2.19.4 and CXF to 3.1.13
@ryeats 
@derekwilhelm 
@emmberk 
@jaymcnallie 
@stustison
Run a full build, verify all unit and integration tests pass. Start up DDF and verify that all apps start and no exceptions occur.
[DDF-3471](https://codice.atlassian.net/browse/DDF-3471)
Certain exceptions may occur. For example, if there is …
=> DDF-3471 Upgrade Camel to 2.19.4 and CXF to 3.1.13

platform/security/idp/security-idp-plugin/pom.xml, platform/security/idp/security-idp-plugin/security-idp-plugin-api/pom.xml, platform/security/idp/security-idp-plugin/security-idp-plugin-api/src/main/java/org/codice/ddf/security/idp/plugin/SamlPresignPlugin.java, platform/security/idp/security-idp-plugin/security-idp-plugin-subjectconfirmation/pom.xml, platform/security/idp/security-idp-plugin/security-idp-plugin-subjectconfirmation/src/main/java/org/codice/ddf/security/idp/plugin/subjectconfirmation/SubjectConfirmationPresignPlugin.java, platform/security/idp/security-idp-plugin/security-idp-plugin-subjectconfirmation/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/security/idp/security-idp-plugin/security-idp-plugin-subjectconfirmation/src/test/groovy/org/codice/ddf/security/idp/plugin/subjectconfirmation/SubjectConfirmationPresignPluginSpec.groovy, platform/security/idp/security-idp-plugin/security-idp-plugin-subjectconfirmation/src/test/resources/SAMLResponse.xml, platform/security/idp/security-idp-plugin/security-idp-plugin-subjectconfirmation/src/test/resources/ssometadata.xml, platform/security/idp/security-idp-server/pom.xml, platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/binding/api/impl/ResponseCreatorImpl.java, platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/binding/post/PostBinding.java, platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/binding/post/PostResponseCreator.java, platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/binding/redirect/RedirectBinding.java, platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/binding/redirect/RedirectResponseCreator.java, platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/binding/soap/SoapBinding.java, platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/binding/soap/SoapResponseCreator.java, platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/server/IdpEndpoint.java, platform/security/idp/security-idp-server/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/security/platform-security-core-api/pom.xml, platform/security/platform-security-core-api/src/main/java/ddf/security/samlp/SimpleSign.java, platform/security/platform-security-core-api/src/test/java/ddf/security/samlp/SimpleSignTest.java, platform/security/security-services-app/pom.xml, platform/security/security-services-app/src/main/resources/features.xml, platform/security/sts/security-sts-realm/src/main/java/ddf/security/realm/sts/AbstractStsRealm.java
- Adds a new plugin point to the IdP server to update responses prior to being re-signed and returned
- Creates new plugin api
- Creates initial implementor to add/update `SubjectConfirmationData` with `NotOnOrAfter` and `Recipient` values
- Ensuring that Each bearer assertion(s) MUST contain an `<AudienceRestriction>` including the service provider's unique identifier as an `<Audience>` **Will be done in a separate PR.**
- Full CI build
- *Test Redirect Binding*: Install and setup DDF
- *Test Post Binding*: Update the IdP client metadata, removing the redirect binding (following is the easiest way I can think to do this):
- Point your browser to the [IdP login endpoint](https://localhost:8993/services/idp/login/metadata) of your running server (that link assumes `localhost:8993`)
- Copy …
=> [2.11.x] DDF-3463 Adds new plugin point to update SAML assertions prior to re-sign

platform/security/idp/security-idp-plugin/pom.xml, platform/security/idp/security-idp-plugin/security-idp-plugin-api/pom.xml, platform/security/idp/security-idp-plugin/security-idp-plugin-api/src/main/java/org/codice/ddf/security/idp/plugin/SamlPresignPlugin.java, platform/security/idp/security-idp-plugin/security-idp-plugin-subjectconfirmation/pom.xml, platform/security/idp/security-idp-plugin/security-idp-plugin-subjectconfirmation/src/main/java/org/codice/ddf/security/idp/plugin/subjectconfirmation/SubjectConfirmationPresignPlugin.java, platform/security/idp/security-idp-plugin/security-idp-plugin-subjectconfirmation/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/security/idp/security-idp-plugin/security-idp-plugin-subjectconfirmation/src/test/groovy/org/codice/ddf/security/idp/plugin/subjectconfirmation/SubjectConfirmationPresignPluginSpec.groovy, platform/security/idp/security-idp-plugin/security-idp-plugin-subjectconfirmation/src/test/resources/SAMLResponse.xml, platform/security/idp/security-idp-plugin/security-idp-plugin-subjectconfirmation/src/test/resources/ssometadata.xml, platform/security/idp/security-idp-server/pom.xml, platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/binding/api/impl/ResponseCreatorImpl.java, platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/binding/post/PostBinding.java, platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/binding/post/PostResponseCreator.java, platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/binding/redirect/RedirectBinding.java, platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/binding/redirect/RedirectResponseCreator.java, platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/binding/soap/SoapBinding.java, platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/binding/soap/SoapResponseCreator.java, platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/server/IdpEndpoint.java, platform/security/idp/security-idp-server/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/security/platform-security-core-api/pom.xml, platform/security/platform-security-core-api/src/main/java/ddf/security/samlp/SimpleSign.java, platform/security/platform-security-core-api/src/test/java/ddf/security/samlp/SimpleSignTest.java, platform/security/security-services-app/pom.xml, platform/security/security-services-app/src/main/resources/features.xml, platform/security/sts/security-sts-realm/src/main/java/ddf/security/realm/sts/AbstractStsRealm.java
(cherry picked from commit b7b9e4b) #2738 
@bdeining
@beyelerb
@clockard
@coyotesqrl
@figliold
@jaymcnallie
@jlcsmith
@kcwire
@lessarderic
@millerw8
@mrmateo
@pklinef
@rzwiefel
@shaundmorris
@stustison
Certain exceptions may occur. For …
=> DDF-3463 Adds new plugin point to update SAML assertions prior to re-sign

PULL_REQUEST_TEMPLATE
moved the Notes on Review process to the confluence page and linked
anyone
=> Modified PULL_REQUEST_TEMPLATE

catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswQueryFactory.java, catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/QueryFilterTransformerProvider.java, catalog/spatial/csw/spatial-csw-endpoint/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswQueryFactoryTest.java, catalog/spatial/csw/spatial-csw-endpoint/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/QueryFilterTransformerProviderTest.java, catalog/spatial/csw/spatial-csw-endpoint/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/ValidatorTest.java
Fixed transaction translations for custom typeNames so custom typeNames can be added to the CSW Endpoint.
@adimka @troymohl @Variadicism 
@jlcsmith
@millerw8
Build and verify no regressions via itests.  At this moment, there are no custom typeNames that exist in the DDF baseline.
[DDF-3487](https://codice.atlassian.net/browse/DDF-3487)
Certain exceptions …
=> DDF-3487 Fixed transaction translations for custom typeNames

dependency-check-maven-config.xml, distribution/ddf-common/src/main/resources-filtered/etc/system.properties, platform/solr/platform-solr-server-standalone/dependency-check-maven-config.xml, platform/solr/platform-solr-server-standalone/src/main/resources/solr/conf/solrconfig-inmemory.xml, platform/solr/platform-solr-server-standalone/src/main/resources/solr/conf/solrconfig.xml, pom.xml
____
https://github.com/codice/ddf/pull/2698
@clockard @lessarderic
=> DDF-3440 Upgrades to Solr 6.6.2

platform/platform-app/src/main/resources/features.xml
This PR adds `io` feature as a feature prereq in the `platform-migration` feature.
@brjeter @Lambeaux @paouelle 
@coyotesqrl
@figliold
- Itests.
- Confirm that the `unknown persistence strategy extension: config` error does not occur during startup (see the ticket Description).
[DDF-3501](https://codice.atlassian.net/browse/DDF-3501) …
=> [2.11.x] DDF-3501 Added io feature prereq to the platform-migration feature

Documentation-versions.html, index.html
updates site for 2.11.3 release
@peterhuffer 
@clockard
@coyotesqrl
@lessarderic
@rzwiefel
@shaundmorris
No build required. …
=> DDF-2748 updated site for 2.11.3 release

platform/platform-app/src/main/resources/features.xml
____
This PR is a port of https://github.com/codice/ddf/pull/2767.
@brjeter @Lambeaux @paouelle
@bdeining 
@kcwire 
[DDF-3501](https://codice.atlassian.net/browse/DDF-3501)
=> DDF-3501 Added io feature prereq to the platform-migration feature

platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/migration/ImportMigrationEntryImplTest.java
Removes unnecessary mock in ImportMigrationEntryImplTest
@peterhuffer @paouelle 
@coyotesqrl
@lessarderic
Certain exceptions may occur. For example, if there is a problem with the CI environment then a manually performed full build and static analysis check may be substituted _at the discretion of the repository maintainers_. Additionally, repository metadata such as this `PULL_REQUEST_TEMPLATE`, the repository `README`, and other …
=> [2.11.x] DDF-3495 Removed unnecessary mock

platform/migration/platform-migration/pom.xml, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/CipherUtils.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/ConfigurationMigrationManager.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/ExportMigrationContextImpl.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/ExportMigrationManagerImpl.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/ImportMigrationContextImpl.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/ImportMigrationManagerImpl.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/Messages.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/MigrationZipConstants.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/MigrationZipFile.java, platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/admin/ConfigurationAdminMigratableTest.java, platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/migration/AbstractMigrationSupport.java, platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/migration/CipherUtilsTest.java, platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/migration/ConfigurationMigrationManagerTest.java, platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/migration/ExportMigrationContextImplTest.java, platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/migration/ExportMigrationManagerImplTest.java, platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/migration/ImportMigrationContextImplTest.java, platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/migration/ImportMigrationManagerImplTest.java, platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/migration/MigrationZipFileTest.java
Backport of #2486 to 2.11.x
@clockard @coyotesqrl
=> [2.11.x] DDF-3376 Add encryption support to the migration framework

distribution/docs/src/main/resources/content/_securityFramework/security-ldap-embedded-server.adoc
Fixes some links to external resources in the security framework documentation
@emmberk @peterhuffer @AzGoalie 
@codice/docs 
@shaundmorris @figliold 
[DDF-3507](https://codice.atlassian.net/browse/DDF-3507) …
=> DDF-3507 Fixed broken links in documentation for OpenDJ docs

distribution/docs/src/main/resources/content/_securityFramework/security-ldap-embedded-server.adoc
backports #2777 
@shaundmorris 
[DDF-3507](https://codice.atlassian.net/browse/DDF-3507)
=> [2.11.x] DDF-3507 Fixed broken links in documentation for OpenDJ docs

distribution/docs/src/main/resources/content/_coreConcepts/service-standards.adoc
Adds WPS to standards supported in Core Concepts docs. (Was previously commented out)
@ryeats @mcalcote @ahoffer @vinamartin @garrettfreibott 
@clockard
@coyotesqrl
@lessarderic
@pklinef
@rzwiefel
@shaundmorris …
=> DDF-2824 added WPS to list of standards in docs

platform/security/common/pom.xml, platform/security/common/src/main/java/ddf/security/assertion/impl/SecurityAssertionImpl.java, platform/security/common/src/main/java/ddf/security/samlp/impl/SamlValidator.java, platform/security/common/src/test/java/ddf/security/assertion/impl/SecurityAssertionImplTest.java, platform/security/common/src/test/resources/saml.xml, platform/security/core/security-core-impl/pom.xml, platform/security/core/security-core-impl/src/main/java/ddf/security/samlp/impl/LogoutMessageImpl.java, platform/security/core/security-core-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/security/core/security-core-impl/src/test/groovy/ddf/security/samlp/impl/LogoutMessageSpecTest.groovy, platform/security/handler/security-handler-api/pom.xml, platform/security/handler/security-handler-api/src/main/java/org/codice/ddf/security/handler/api/HandlerResult.java, platform/security/idp/security-idp-client/pom.xml, platform/security/idp/security-idp-client/src/main/java/org/codice/ddf/security/idp/client/LogoutRequestService.java, platform/security/idp/security-idp-client/src/test/java/org/codice/ddf/security/idp/client/LogoutRequestServiceTest.java, platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/server/IdpEndpoint.java, platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/server/LogoutState.java, platform/security/idp/security-idp-server/src/test/groovy/org/codice/ddf/security/idp/server/IdpEndpointSpecTest.groovy, platform/security/idp/security-idp-server/src/test/java/org/codice/ddf/security/idp/server/IdpEndpointTest.java, platform/security/idp/security-idp-server/src/test/resources/saml.xml, platform/security/platform-security-core-api/src/main/java/ddf/security/samlp/LogoutMessage.java, platform/security/platform-security-core-api/src/main/java/ddf/security/samlp/SamlProtocol.java, platform/security/platform-security-core-api/src/test/java/ddf/security/samlp/SamlProtocolTest.java, platform/security/security-services-app/pom.xml, platform/security/security-services-app/src/main/resources/features.xml, platform/security/sts/security-sts-server/src/main/java/ddf/security/sts/AuthNStatementProvider.java
#What does this PR do?
Implements SessionIndex for SAML. Specifically:
SecurityAssertionImpl parses a SecurityToken, it copies the SessionIndex from the Security token into its own copy of the AuthnStatement
The SessionIndex is extracted from an incoming SAML logout request by the LogoutMessage
The Saml Protocol class copies the SessionIndex from the LogoutRequest it creates
The SamlValidator checks for the presence of a SessionIndex when it validates a SAML request.
Added SessionIndex attribute to XML file used in testing
Changed how SessionIndex is generated in AuthnStatementProvider. SessionIndex can be any string, but standard recommends small-ish integer. It now generates only positive session indexes and reduces the upper size of a session index
Added unit test to …
=> DDF-3422 SSO logout SessionIndex

catalog/transformer/catalog-transformer-streaming-lib/src/main/java/org/codice/ddf/transformer/xml/streaming/lib/SaxEventHandlerDelegate.java, platform/admin/core/admin-core-appservice/src/main/java/org/codice/ddf/admin/application/service/command/ProfileListCommand.java, platform/security/handler/security-handler-saml/src/main/java/org/codice/ddf/security/handler/saml/SAMLAssertionHandler.java, platform/solr/platform-solr-server-standalone/src/main/webapp/js/require.js
Updated past tense version of occur to `occurred` from `occured`
@vinamartin @ricklarsen @clockard @rzwiefel @shaundmorris
=> DDF-3518 Corrected typo to 'occurred'

platform/admin/core/admin-core-impl/src/main/java/org/codice/ddf/admin/core/impl/AdminConsoleService.java
This is  MASTER PORT of https://github.com/codice/ddf/pull/2760. I am including the same reviewers and approvers who approved the 2.11.x PR.
Purpose: 
Guest claims set during the install process were not always reflective of what was presented in the UI. This PR changes the installer to use the guest claims shown by the admin UI.
@peterhuffer 
@mcalcote 
@kcrowe01 
@figliold
@clockard
@rzwiefel
1. Build distro.
2. Unzip distro on Mac and start the application (NOTE:  Must be a configuration that offers installation profiles and the installation profiles must offer choices that affect the guest claims.)
3. Go to Admin UI and start the installation.
4. Pick a profile and observe the change to the default guest claims. …
=> DDF-3496 Guest claims installation

catalog/ui/catalog-ui-search/src/main/webapp/component/visualization/maps/openlayers/map.openlayers.js
Converted coordinates from map projection to EPSG:4326 to display lat/lng to use
@Variadicism 
@bdeining
Try out the UI when the projection is set to EPSG:4326, confirm the 2D map shows correct lat/lng values in the lower left as the user moves around the cursor.  Repeat for EPSG:3857
[DDF-3516](https://codice.atlassian.net/browse/DDF-3516) …
=> DDF-3516 Converted coordinates to display in OpenLayers

distribution/ddf/pom.xml
Removed zero width character from pom
anyone
https://codice.atlassian.net/browse/DDF-3527
=> DDF-3527 Removed zero width character from pom

distribution/docs/src/main/resources/content/_installing/high-availability-initial-setup-exceptions.adoc, distribution/docs/src/main/resources/content/_sources/solr-catalog-provider.adoc
Adds clarification for certain HA setup steps. 
@brjeter 
@blen-desta 
@oconnormi 
@coyotesqrl
@shaundmorris
Verify documentation. 
Feedback was generated from third party review and attempted setup of an HA cluster. 
[DDF-3502](https://codice.atlassian.net/browse/DDF-3502) …
=> [2.11.x] DDF-3502 Clarify documentation for setting up a highly available cluster

distribution/docs/src/main/resources/content/_configuring/configuring-access-plugins.adoc, distribution/docs/src/main/resources/content/_configuring/configuring-data-management.adoc, distribution/docs/src/main/resources/content/_configuring/configuring-data-policy-plugins.adoc, distribution/docs/src/main/resources/content/_configuring/configuring-platform-ui.adoc, distribution/docs/src/main/resources/content/_configuring/configuring-solr.adoc, distribution/docs/src/main/resources/content/_plugins/metacard-attribute-plugin.adoc, distribution/docs/src/main/resources/content/_plugins/metacard-validity-filter.adoc, distribution/docs/src/main/resources/content/_plugins/metacard-validity-marker.adoc, distribution/docs/src/main/resources/content/_plugins/security-audit-plugin.adoc, distribution/docs/src/main/resources/content/_plugins/xml-attribute-plugin.adoc, distribution/docs/src/main/resources/content/_tables/MetacardValidityMarkerPlugin.adoc
Updates to the configuring section of the documentation; specifically configurations involving data management. 
@clockard
@coyotesqrl
@lessarderic
@pklinef
@rzwiefel
@shaundmorris
Review content. Most changes are just moving content, but some new material added.
[DDF-3352](https://codice.atlassian.net/browse/DDF-3352)
[documentation.pdf](https://github.com/codice/ddf/files/1580990/documentation.pdf) …
=> [2.11.x] DDF-3352 updated configuring data management docs

catalog/admin/admin-poller-service/src/main/java/org/codice/ddf/catalog/admin/poller/AdminPollerServiceBean.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/DurableWebDavFileConsumer.java, catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/DynamicSchemaResolver.java, catalog/solr/catalog-solr-solrclient/pom.xml, catalog/solr/catalog-solr-solrclient/src/main/java/ddf/catalog/source/solr/rest/SolrRest.java, catalog/spatial/csw/spatial-csw-source-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/AbstractCswSource.java, catalog/spatial/csw/spatial-csw-source-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/AbstractCswStore.java, catalog/spatial/geocoding/spatial-geocoding-admin-module/src/main/java/org/codice/ddf/spatial/admin/module/service/Geocoding.java, catalog/spatial/geocoding/spatial-geocoding-offline-catalog/src/main/java/org/codice/ddf/spatial/geocoding/query/GeoNamesQueryLuceneDirectoryIndex.java, catalog/spatial/registry/registry-federation-admin-impl/src/main/java/org/codice/ddf/registry/federationadmin/impl/AdminHelper.java, catalog/transformer/catalog-transformer-pdf/src/main/java/ddf/catalog/transformer/input/pdf/GeoPdfParserImpl.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/FeedbackApplication.java, distribution/sdk/artemis-sandbox/src/main/java/sdk.example.route/CoreProducerConsumerExample.java, libs/httpproxy/proxy-camel-route/pom.xml, libs/httpproxy/proxy-camel-route/src/main/java/org/apache/commons/httpclient/contrib/ssl/AuthSSLX509TrustManager.java, libs/klv/src/main/java/org/codice/ddf/libs/klv/data/text/KlvEncodingDetectedString.java, platform/admin/core/admin-core-appservice/src/main/java/org/codice/ddf/admin/application/service/command/ProfileListCommand.java, platform/admin/core/admin-core-appservice/src/main/java/org/codice/ddf/admin/application/service/impl/ApplicationServiceBean.java, platform/admin/core/admin-core-appservice/src/main/java/org/codice/ddf/admin/application/service/impl/ApplicationServiceImpl.java, platform/admin/core/admin-core-appservice/src/test/java/org/codice/ddf/admin/application/service/command/ProfileListCommandTest.java, platform/admin/core/admin-core-appservice/src/test/java/org/codice/ddf/admin/application/service/impl/ApplicationServiceBeanTest.java, platform/admin/core/admin-core-impl/src/main/java/org/codice/ddf/admin/core/impl/SystemPropertiesAdmin.java, platform/persistence/platform-persistence-core-impl/pom.xml, platform/persistence/platform-persistence-core-impl/src/main/java/org/codice/ddf/persistence/internal/PersistentStoreImpl.java, platform/security/certificate/security-certificate-keystoreeditor/src/main/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditor.java, platform/security/common/src/main/java/ddf/security/ws/policy/impl/PolicyWSDLGetInterceptor.java, platform/solr/solr-factory/src/main/java/org/codice/solr/factory/impl/EmbeddedSolrFactory.java
Improves code quality, security, reliability, and maintainability
@vinamartin @mcalcote @rzwiefel @paouelle @clockard @figliold @shaundmorris 
@clockard
@rzwiefel
Run unit and integration tests
If you have access, you can see the original issues here: https://scan8.coverity.com/reports.htm#v32842/p10941
[DDF-3480](https://codice.atlassian.net/browse/DDF-3480)
- [ N/A] Documentation Updated …
=> DDF-3480 Address Coverity findings

distribution/docs/src/main/resources/content/_installing/high-availability-initial-setup-exceptions.adoc, distribution/docs/src/main/resources/content/_sources/solr-catalog-provider.adoc
Forward port of https://github.com/codice/ddf/pull/2773
@brjeter 
@coyotesqrl 
=> DDF-3502 Clarify documentation for setting up a highly available cluster

Jenkinsfile
Backport of https://github.com/codice/ddf/pull/2775
Suppresses lines of the form 
```
18:43:23 [INFO] Downloading: http://NEXUS/PATH/TO/ARTIFACT
18:43:23 [INFO] Downloaded: http://NEXUS/PATH/TO/ARTIFACT (27 KB at 985.4 KB/sec)
```
from the Jenkins Pipeline build logs
@vinamartin @blen-desta @oconnormi @mcalcote @LinkMJB 
@bdeining
@clockard
It has been verified on a downstream project that only the desired logs are suppressed.
[DDF-3506](https://codice.atlassian.net/browse/DDF-3506) …
=> [2.11.x] DDF-3506 Suppress 'Downloading/Downloaded' status lines in logs

catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/CswTransformProvider.java
Closed input stream in CswTransformProvider
@blen-desta 
@brjeter 
@coyotesqrl
@shaundmorris 
[](https://codice.atlassian.net/browse/DDF-3520)
=> DDF-3520 Closed input stream in CswTransformProvider

platform/security/idp/security-idp-plugin/security-idp-plugin-subjectconfirmation/src/main/java/org/codice/ddf/security/idp/plugin/subjectconfirmation/SubjectConfirmationPresignPlugin.java
Changes the Audience in a SAML response to the unique identifier of the Service Provider.
@brjeter @Lambeaux 
@coyotesqrl 
@stustison 
Full build.
Will add further testing instructions.
I am pulling the SP's entity ID from the request because in the SAML spec under section 4.1.4.1 it says:
```
The <Issuer> element MUST be present and MUST
contain the unique identifier of the requesting service provider
```
https://www.oasis-open.org/committees/download.php/56782/sstc-saml-profiles-errata-2.0-wd-07.pdf
[DDF-3526](https://codice.atlassian.net/browse/DDF-3526) …
=> [2.11.x] DDF-3526 Changed the Audience in a SAML response to the unique identifier of the Service Provider

catalog/spatial/csw/spatial-csw-source-common/pom.xml, catalog/spatial/csw/spatial-csw-source-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/AbstractCswSource.java
Restore missing method
Remove dupliced dependency
Fixes an error introduced in an earlier merge.
@anyone 
@bdeining
@millerw8
@mrmateo
CI build
DDF-3480
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an inline code snippet or a gist. 
- …
=> DDF-3480 Coverity Findings - restore missing method

catalog/core/catalog-core-solr/pom.xml, catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/DynamicSchemaResolver.java
- Doing null check before returning the center point **(first commit)**
- Addressed several SonarQube findings **in separate commits**
@coyotesqrl 
@lessarderic 
- Verify metacards with Geometry attribute but no center point can be ingested (see me for details)
- Verify basic ingest and query work
[DDF-3499](https://codice.atlassian.net/browse/DDF-3499) …
=> [2.11.x]DDF 3499 Handle possible NPE for the center point in DynamicSchemaResolver

distribution/docs/src/main/resources/content/_configuring/configuring-access-plugins.adoc, distribution/docs/src/main/resources/content/_configuring/configuring-data-management.adoc, distribution/docs/src/main/resources/content/_configuring/configuring-data-policy-plugins.adoc, distribution/docs/src/main/resources/content/_configuring/configuring-platform-ui.adoc, distribution/docs/src/main/resources/content/_configuring/configuring-solr.adoc, distribution/docs/src/main/resources/content/_plugins/metacard-attribute-plugin.adoc, distribution/docs/src/main/resources/content/_plugins/metacard-validity-filter.adoc, distribution/docs/src/main/resources/content/_plugins/metacard-validity-marker.adoc, distribution/docs/src/main/resources/content/_plugins/security-audit-plugin.adoc, distribution/docs/src/main/resources/content/_plugins/xml-attribute-plugin.adoc, distribution/docs/src/main/resources/content/_tables/MetacardValidityMarkerPlugin.adoc
**Port to `master` of PR https://github.com/codice/ddf/pull/2788**
Updates to the configuring section of the documentation; specifically configurations involving data management. 
@clockard
@coyotesqrl
@lessarderic
@pklinef
@rzwiefel
@shaundmorris
Review content. Most changes are just moving content, but some new material added.
[DDF-3352](https://codice.atlassian.net/browse/DDF-3352)
[documentation.pdf](https://github.com/codice/ddf/files/1604527/documentation.pdf) …
=> DDF-3352 updated configuring data management docs

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/CreateOperations.java
Fixed storage not being properly rolled back on ingest via content directory monitor. 
@brjeter 
@blen-desta  
@bdeining
@coyotesqrl
TBD
TBD
[DDF-3530](https://codice.atlassian.net/browse/DDF-3530) …
=> [2.11.x] DDF-3530 Fixed storage not being properly rolled back on ingest via content directory monitor

catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/SolrMetacardClientImpl.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/QueryOperations.java, catalog/core/catalog-core-standardframework/src/test/groovy/ddf/catalog/impl/operations/QueryOperationsSpec.groovy, catalog/transformer/catalog-transformer-service-atom/src/main/java/ddf/catalog/transformer/response/query/atom/AtomTransformer.java, catalog/transformer/catalog-transformer-service-atom/src/test/java/ddf/catalog/transformer/response/query/atom/TestAtomTransformer.java
Modifies AtomTransformer to remove any returned entries when the 'count' parameter on the request is 0.
@Variadicism 
@bdeining
@jlcsmith
1) ingest a few products
2) execute an opensearch query normally (`https://localhost:8993/services/catalog/query?q=*`)
- all of the items ingested should be shown
3) execute the same search with `&count=0` (`https://localhost:8993/services/catalog/query?q=*&count=0`)
- no items will be returned, but the `totalResults` element should show the number of items ingested in step 1.
[DDF-3484](https://codice.atlassian.net/browse/DDF-3484)
* Review by …
=> DDF-3484 HitCount-only Queries

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/CreateOperations.java
Forward port of https://github.com/codice/ddf/pull/2811
@brjeter 
@blen-desta 
@bdeining 
@clockard
Ensure content is not stored after an ingest failure. 
[DDF-3530](https://codice.atlassian.net/browse/DDF-3530) …
=> DDF-3530 Fixed storage not being properly rolled back on ingest via content directory monitor

catalog/catalog-app/pom.xml, catalog/catalog-app/src/main/resources/features.xml, catalog/validator/catalog-validator-metacardframecenter/pom.xml, catalog/validator/catalog-validator-metacardframecenter/src/main/java/org/codice/ddf/validator/metacard/framecenter/MetacardFrameCenterValidator.java, catalog/validator/catalog-validator-metacardframecenter/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/validator/catalog-validator-metacardwkt/pom.xml, catalog/validator/catalog-validator-metacardwkt/src/main/java/org/codice/ddf/validator/metacard/wkt/MetacardWktValidator.java, catalog/validator/catalog-validator-metacardwkt/src/test/java/org/codice/ddf/validator/metacard/wkt/MetacardWktValidatorTest.java, catalog/validator/catalog-validator-wkt/pom.xml, catalog/validator/catalog-validator-wkt/src/main/java/org/codice/ddf/validator/wkt/WktValidator.java, catalog/validator/catalog-validator-wkt/src/main/java/org/codice/ddf/validator/wkt/WktValidatorImpl.java, catalog/validator/catalog-validator-wkt/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/validator/catalog-validator-wkt/src/test/java/org/codice/ddf/validator/wkt/WktValidatorImplTest.java, catalog/validator/pom.xml
Forward-port for https://github.com/codice/ddf/pull/2786
Adds validator for the frame center attribute on metacards. This validator will remove the value from the metacard if it's invalid (same behavior as current Location validation).
Without this validation, invalid WKT values are allowed through and Solr fails to store.
@coyotesqrl 
@rzwiefel 
- Full build
- Ingest a resource with an invalid location and verify the validation errors can be seen in the UI (see `MetacardValidityMarkerPlugin` in the Catalog app in the AdminUI)
- Ingest a resource with a valid location and verify it does not have validation errors …
=> DDF-3508 Added validation for Frame Center attribute

platform/security/platform-security-core-api/src/main/java/ddf/security/samlp/MetadataConfigurationParser.java
Modifies a logging statement from info -> debug since if a system is triggering this notification, every single request/login was spamming the log
@ahoffer 
anyone
https://codice.atlassian.net/browse/DDF-3473 …
=> [2.11.x] DDF-3473 fixed logging

catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/DynamicSchemaResolver.java
Forward-port for https://github.com/codice/ddf/pull/2764 (except for sonarqube fixes since the classes have diverged)
- Doing null check before returning the center point
@coyotesqrl 
@lessarderic 
- Full build
[DDF-3499](https://codice.atlassian.net/browse/DDF-3499) …
=> DDF-3499 Handle possible NPE for the center point in DynamicSchemaResolver

catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/event/CswSubscriptionConfigFactory.java
Updates `CswSubscriptionConfigFactory` to use OWASP best practices when unmarshalling
@ryeats @adimka 
@coyotesqrl
Full build
[DDF-3536](https://codice.atlassian.net/browse/DDF-3536) …
=> [2.11.x] DDF-3536 Updated CswSubscriptionConfigFactory unmarshalling based on OWASP Recommendations

catalog/admin/module/catalog-admin-module-maplayers/src/main/webapp/map-layers/reducer.js
____
Port of https://github.com/codice/ddf/pull/2823
@clockard
[DDF-3449](https://codice.atlassian.net/browse/DDF-3449)
=> DDF-3449 Fixed deleting non-bottom Map Layers

catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/event/CswSubscriptionConfigFactory.java
Forward-port of #2822 
Updates `CswSubscriptionConfigFactory` to use OWASP best practices when unmarshalling
@ryeats @adimka 
@coyotesqrl
Full build
[DDF-3536](https://codice.atlassian.net/browse/DDF-3536) …
=> DDF-3536 Updated CswSubscriptionConfigFactory unmarshalling based on OWASP Recommendations

catalog/transformer/catalog-transformer-common/pom.xml, catalog/transformer/catalog-transformer-common/src/main/java/ddf/catalog/transformer/common/tika/MetacardCreator.java, catalog/transformer/catalog-transformer-common/src/test/java/ddf/catalog/transformer/common/tika/MetacardCreatorTest.java
=> DDF-3521 Removes redundant mapping for Creator and Contributor

catalog/ui/catalog-ui-search/src/main/webapp/component/content/content.js
Deselects metacards on a new search as they are now stale
@GabrielFabian @mackncheesiest @mojogitoverhere 
@millerw8
@jlcsmith 
Build / Install / Ingest Data / Execute Search / Inspect records / Execute new Search and verify proper behaviors
[DDF-3540](https://codice.atlassian.net/browse/DDF-3540) …
=> DDF-3540 Deselects metacards on a new search as they are now stale

catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/cache/solr/impl/CachingFederationStrategyTest.java
Adds unit tests to CachingFederationStrategy federate method and cleans up current unit test implementation.
@brjeter 
@Lambeaux 
@AzGoalie 
@blen-desta 
@coyotesqrl 
https://codice.atlassian.net/browse/DDF-3519 …
=> DDF-3519 Add unit tests to CachingFederationStrategy federate method

pom.xml
Upgrade the node version to comply with yarn
@LinkMJB @vinamartin 
@clockard 
This upgrade is to get rid of the errors we get from yarn:
`[ERROR] warning You are using Node "7.1.0" which is not supported and may encounter bugs or unexpected behavior. Yarn supports the following semver range: "^4.8.0 || ^5.7.0 || ^6.2.2 || ^8.0.0"`
[DDF-3537](https://codice.atlassian.net/browse/DDF-3537)
- ❓ (Question …
=> DDF-3537 Upgrade node version to comply with yarn

catalog/ui/catalog-ui-search/src/main/webapp/component/workspaces-templates/workspaces-templates.hbs, catalog/ui/catalog-ui-search/src/main/webapp/component/workspaces-templates/workspaces-templates.less, catalog/ui/catalog-ui-search/src/main/webapp/component/workspaces-templates/workspaces-templates.view.js
Rewords the "More templates" button to better meet user expectations and improves usability of the button. The wording of "Template Gallery" doesn't have the same implication that more templates will be shown.
@mojogitoverhere @glenhein 
@bdeining
@millerw8
Full build
Verification across platforms/browsers and user theme preferences
Background contained in ticket
[DDF-3533](https://codice.atlassian.net/browse/DDF-3533)
`Drawer closed` with up/down arrows as of https://github.com/codice/ddf/pull/2820/commits/bb3af04abdeacd4559cc0cbea4a9f075668c8ec9
`Drawer open` with up/down arrows as of …
=> DDF-3533 Improve usability of "More templates" button

catalog/ui/catalog-ui-search/src/main/webapp/component/golden-layout/golden-layout.hbs
Updates "Add Visual" tooltip to be slightly more descriptive.
I'm open to different wording here. 
@emanns95 @ricklarsen @andrewkfiedler @Lambeaux @blen-desta @peterhuffer 
@coyotesqrl 
@rzwiefel
Go to Intrigue and open up a workspace.
Click the Question Mark icon in the upper right corner of the workspace.
Click on the Add Visual button and verify the tooltip is more descriptive.  …
=> DDF-3543 Updates "Add Visual" tooltip

catalog/spatial/geocoding/spatial-geocoding-api/src/main/java/org/codice/ddf/spatial/geocoding/GeoCodingConstants.java
Resolved SonarQube finding
@adimka @GabrielFabian 
@jlcsmith
@shaundmorris
Full Build
[DDF-3337](https://codice.atlassian.net/browse/DDF-3337) …
=> DDF-3337 Resolved SonarQube finding

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/config/ConfigurationApplication.java, catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.config.xml, catalog/ui/catalog-ui-search/src/main/webapp/js/ApplicationSetup.js
Added configuration to disable unknown errors dialogue
@mackncheesiest @mojogitoverhere 
@jlcsmith
@millerw8
Build / Install / Check `Disable Unknown Error Box` in the Catalog UI Config / Navigate to Intrigue and enter a workspace / turn DDF off / the source poller should eventually return an `unknown error` and it should not show on Intrigue
[DDF-3548](https://codice.atlassian.net/browse/DDF-3548) …
=> DDF-3548 Added configuration to disable unknown errors dialogue

platform/security/common/src/main/java/ddf/security/samlp/impl/SamlValidator.java
This PR cleans up repeated fields in ddf.security.samlp.impl.SamlValidator to prevent any misunderstanding/clash with corresponding fields in inner classes.
@ahoffer @AzGoalie  
@clockard 
@coyotesqrl 
@rzwiefel 
Full build.
[DDF-3544](https://codice.atlassian.net/browse/DDF-3544) …
=> DDF-3544 Cleaned up repeated fields in ddf.security.samlp.impl.SamlValidator to fix code smell

catalog/ui/catalog-ui-search/src/main/webapp/component/golden-layout/golden-layout.hbs
https://github.com/codice/ddf/pull/2833
@coyotesqrl 
@clockard
=> DDF-3543 Updates "Add Visual" tooltip (#2833)

distribution/docs/src/main/resources/content/_configuring/configuring-security-policies.adoc, distribution/docs/src/main/resources/content/_configuring/no-idp.adoc, distribution/docs/src/main/resources/content/_configuring/sts-no-idp.adoc
Fixes typos in the Configuring Security Policies section of the documentation.
@mcalcote @vinamartin @ahoffer @garrettfreibott @rzwiefel 
@clockard
@coyotesqrl
@lessarderic
@shaundmorris
@stustison
builds successfully, properties resolve correctly
[DDF-3356](https://codice.atlassian.net/browse/DDF-3356)
[documentation.pdf](https://github.com/codice/ddf/files/1636799/documentation.pdf)
- ❓ …
=> DDF-3356 updated security policies docs

distribution/docs/src/main/resources/content/_configuring/reusing-configurations.adoc, platform/admin/core/admin-core-migration-commands/src/main/java/org/codice/ddf/migration/commands/DecryptCommand.java, platform/admin/core/admin-core-migration-commands/src/test/java/org/codice/ddf/migration/commands/DecryptCommandTest.java, platform/migration/platform-migratable-api/pom.xml, platform/migration/platform-migratable-api/src/main/java/org/codice/ddf/migration/MigrationOperation.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/ConfigurationMigrationManager.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/ConfigurationMigrationService.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/DecryptMigrationManagerImpl.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/ExportMigrationManagerImpl.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/ImportMigrationManagerImpl.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/Messages.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/MigrationReportImpl.java, platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/migration/AbstractMigrationSupport.java, platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/migration/ConfigurationMigrationManagerTest.java, platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/migration/DecryptMigrationManagerImplTest.java
Provides a decrypt command for the exported migration file and updates documentation with respect to the export file being encrypted.
@tbatie 
@emanns95 
@oconnormi 
@Lambeaux 
@figliold
@lessarderic
@millerw8
@stustison
Execute a migrate:export from the command line and then execute migrate:decrypt, A .zip file should be generated and contain all exported decrypted files.
Now that we are encrypting the exported file, it is now much harder to troubleshoot or debug enhancements to the migration framework. The new migrate:decrypt command  can be used to peek at the content of an exported file. …
=> [2.11.x] DDF-3376 Added migration decrypt command (#2824)

catalog/core/catalog-core-api/src/main/java/ddf/catalog/Constants.java, catalog/core/catalog-core-solr/pom.xml, catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/SolrMetacardClientImpl.java, catalog/spatial/geocoding/spatial-geocoding-api/src/main/java/org/codice/ddf/spatial/geocoding/GeoCodingConstants.java, catalog/spatial/geocoding/spatial-geocoding-api/src/main/java/org/codice/ddf/spatial/geocoding/GeoEntryQueryable.java, catalog/spatial/geocoding/spatial-geocoding-feature/src/main/java/org/codice/ddf/spatial/geocoding/feature/CatalogFeatureIndexer.java, catalog/spatial/geocoding/spatial-geocoding-feature/src/main/java/org/codice/ddf/spatial/geocoding/feature/CatalogHelper.java, catalog/spatial/geocoding/spatial-geocoding-feature/src/test/java/org/codice/ddf/spatial/geocoding/feature/TestCatalogFeatureIndexer.java, catalog/spatial/geocoding/spatial-geocoding-feature/src/test/java/org/codice/ddf/spatial/geocoding/feature/TestCatalogFeatureQueryable.java, catalog/spatial/geocoding/spatial-geocoding-offline-catalog/pom.xml, catalog/spatial/geocoding/spatial-geocoding-offline-catalog/src/main/java/org/codice/ddf/spatial/geocoding/index/GeoNamesCatalogIndexer.java, catalog/spatial/geocoding/spatial-geocoding-offline-catalog/src/main/java/org/codice/ddf/spatial/geocoding/query/GazetteerQueryCatalog.java, catalog/spatial/geocoding/spatial-geocoding-offline-catalog/src/main/java/org/codice/ddf/spatial/geocoding/query/GeoNamesQueryLuceneDirectoryIndex.java, catalog/spatial/geocoding/spatial-geocoding-offline-catalog/src/test/java/org/codice/ddf/spatial/geocoding/query/GazetteerQueryCatalogTest.java, catalog/spatial/geocoding/spatial-geocoding-websearch/src/main/java/org/codice/ddf/spatial/geocoder/geonames/GeoNamesWebService.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/geofeature/GazetteerFeatureService.java, catalog/ui/catalog-ui-search/src/main/webapp/component/input/autocomplete/input-autocomplete.view.js, catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/query/geofeature/GazetteerFeatureServiceTest.java, platform/solr/platform-solr-server-standalone/src/main/resources/solr/conf/solrconfig-inmemory.xml, platform/solr/platform-solr-server-standalone/src/main/resources/solr/conf/solrconfig.xml
Improves the suggestions provided for anyGeo searches.
@brianfelix @mackncheesiest @mojogitoverhere 
@codice/solr
@bdeining
@millerw8
[DDF-3485](https://codice.atlassian.net/browse/DDF-3485)
Certain exceptions may occur. For example, if there is a problem with the CI environment then a manually performed full build and static analysis check may be …
=> DDF-3485 Improve geo keyword auto-complete

catalog/ui/catalog-ui-search/src/main/webapp/js/ApplicationSetup.js
Adds more informative error messages in Intrigue for specific situations where "Unknown Error" appeared otherwise.
@andrewkfiedler @adimka @mojogitoverhere @Variadicism @brianfelix 
@bdeining
@millerw8
Build and install DDF, navigate to Intrigue, create a query to put the workspace in a "modified" state, turn off DDF, and
(i) attempt to save that query. You should receive an "Error Saving Workspace" message
(ii) wait for source polling to occur. You should receive an "Error Polling Sources" message
[DDF-3550](https://codice.atlassian.net/browse/DDF-3550) …
=> DDF-3550 Improved error messages for ambiguous unknown errors

distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/ServiceManagerImpl.java, distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/SystemStateManager.java
Fixes downstream (and potential DDF) itest issue.
@blen-desta @bakejeyner @Lambeaux 
@bdeining
@clockard
CI build and running any broken downstream itests.
[DDF-3560](https://codice.atlassian.net/browse/DDF-3560)
- ❓ (Question …
=> DDF-3560 Restart the registry bundles necessary to re-initialize the registry metacard for itests.

catalog/ui/catalog-ui-search/src/main/webapp/component/table/results/table-results.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/table/table.less, catalog/ui/catalog-ui-search/src/main/webapp/component/visualization/table/row.less, catalog/ui/catalog-ui-search/src/main/webapp/component/visualization/table/thead.hbs, catalog/ui/catalog-ui-search/src/main/webapp/component/visualization/table/thead.less, catalog/ui/catalog-ui-search/src/main/webapp/component/visualization/table/thead.view.js
Allows for columns to be resized in the Table visualization in Intrigue so that users can view long metacard attributes with ease.
@djblue 
@mcalcote 
@garrettfreibott (Try and break this, please)
@rzwiefel
Build and start up Intrigue. Ingest a few files and if needed, give them an attribute with a very long value (ex. title = "A very long title, so long that it overflows outside of the cell"). 
Verify that when hovering over the header you see the cursor change to an East/West arrow. Verify that when clicking and dragging the column can be resized. Verify that you can still click the outer part of the header to sort on that value. Verify that resizing won't allow you to accidentally sort the column. …
=> [2.11.x] DDF-3562 Allows columns to be resized in Intrigue

distribution/docs/src/main/resources/content/_securityServices/sts-server.adoc, distribution/docs/src/main/resources/content/_tables/sts.adoc, platform/security/sts/security-sts-server/src/main/resources/OSGI-INF/blueprint/cxf-sts.xml, platform/security/sts/security-sts-server/src/main/resources/OSGI-INF/metatype/metatype.xml
Updates the STS issuer to align with the SAML spec:
[SAML Profiles, Section 4.1.4.2](https://www.oasis-open.org/committees/download.php/56782/sstc-saml-profiles-errata-2.0-wd-07.pdf)
> Each assertion's `<Issuer>` element MUST contain the unique identifier of the [E26]responding identity provider; the `Format` attribute MUST be omitted or have a value of `urn:oasis:names:tc:SAML:2.0:nameid-format:entity`. Note that this profile assumes a single responding identity provider, and all assertions in a response MUST be issued by the same entity.
@blen-desta @ricklarsen 
@clockard
@stustison
- Full CI build.
- Interop with …
=> [2.11.x] DDF-3556 Updates default value for STS issuer to IdP login URI.

distribution/docs/src/main/resources/content/_securityServices/sts-server.adoc, distribution/docs/src/main/resources/content/_tables/sts.adoc, platform/security/sts/security-sts-server/src/main/resources/OSGI-INF/blueprint/cxf-sts.xml, platform/security/sts/security-sts-server/src/main/resources/OSGI-INF/metatype/metatype.xml
(Port of #2874)
Updates the STS issuer to align with the SAML spec:
[SAML Profiles, Section 4.1.4.2](https://www.oasis-open.org/committees/download.php/56782/sstc-saml-profiles-errata-2.0-wd-07.pdf)
> Each assertion's `<Issuer>` element MUST contain the unique identifier of the [E26]responding identity provider; the `Format` attribute MUST be omitted or have a value of `urn:oasis:names:tc:SAML:2.0:nameid-format:entity`. Note that this profile assumes a single responding identity provider, and all assertions in a response MUST be issued by the same entity.
@blen-desta @ricklarsen 
@clockard
@stustison
- Full CI build. …
=> DDF-3556 Updates default value for STS issuer to IdP login URI.

distribution/docs/src/main/resources/content/_configuring/http-port.adoc, distribution/docs/src/main/resources/content/_installing/initial-startup.adoc
Updates instructions for changing the HTTP and/or HTTPS port numbers.
@lessarderic
@rzwiefel
@shaundmorris
review revised content.
[DDF-3347](https://codice.atlassian.net/browse/DDF-3347) …
=> DDF-3347 updated instructions for changing port number

catalog/ui/catalog-ui-search/src/main/webapp/component/table/results/table-results.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/table/table.less, catalog/ui/catalog-ui-search/src/main/webapp/component/visualization/table/row.less, catalog/ui/catalog-ui-search/src/main/webapp/component/visualization/table/thead.hbs, catalog/ui/catalog-ui-search/src/main/webapp/component/visualization/table/thead.less, catalog/ui/catalog-ui-search/src/main/webapp/component/visualization/table/thead.view.js
backport: https://github.com/codice/ddf/commit/fad63794e33e55f267f80cc3e31d53d6e1f90035
@brendan-hofmann @andrewkfiedler @clockard
=> DDF-3562 Allows columns to be resized in Intrigue

catalog/core/catalog-core-directorymonitor/pom.xml, catalog/core/catalog-core-directorymonitor/src/test/java/org/codice/ddf/catalog/content/monitor/ContentDirectoryMonitorIT.java, distribution/test/itests/pom.xml, distribution/test/itests/test-itests-common/pom.xml, distribution/test/itests/test-itests-ddf/pom.xml, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFederation.java, distribution/test/itests/test-itests-dependencies-app/pom.xml, distribution/test/itests/test-itests-dependencies-app/src/main/filtered-resources/features.xml, distribution/test/pom.xml, pom.xml, thirdparty/pom.xml, thirdparty/rest-assured/pom.xml, thirdparty/restito/pom.xml, thirdparty/restito/src/main/java/com/xebialabs/restito/server/secure/SecureStubServer.java
Back-port of https://github.com/codice/ddf/pull/2349.
@tbatie 
@rzwiefel
Successful build.
Back-port of https://github.com/codice/ddf/pull/2349.
[DDF-3307](https://codice.atlassian.net/browse/DDF-3307) …
=> [2.11.x] DDF-3307 Move test third-party libraries so they can be re-used outside integration tests

catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/util/impl/SourceDescriptorComparator.java, catalog/core/catalog-core-downloadaction/src/main/java/org/codice/ddf/catalog/download/action/ResourceDownloadActionProvider.java, catalog/core/catalog-core-resourcestatusplugin/src/main/java/ddf/catalog/core/resourcestatus/metacard/MetacardResourceStatus.java, catalog/resourcemanagement/resourcemanagement-querymonitor-commands/src/main/java/org/codice/ddf/resourcemanagement/query/commands/RemoveSearchAfterCompleteCommand.java, catalog/spatial/spatial-commands/src/main/java/org/codice/ddf/commands/spatial/gazetteer/GazetteerUpdateCommand.java, catalog/spatial/wfs/1.0.0/spatial-wfs-v1_0_0-common/src/main/java/org/codice/ddf/spatial/ogc/wfs/v1_0_0/catalog/common/Wfs10JTStoGML200Converter.java, platform/admin/core/admin-core-impl/src/main/java/org/codice/ddf/admin/core/impl/AdminConsoleService.java, platform/security/pdp/security-pdp-authzrealm/src/main/java/ddf/security/pdp/realm/xacml/processor/PollingPolicyFinderModule.java
Resolve locale-dependent string comparisons
@blen-desta @Lambeaux @brjeter @bakejeyner 
@clockard
@coyotesqrl
[DDF-3553](https://codice.atlassian.net/browse/) …
=> DDF-3553 Resolved locale-dependent string comparisons

catalog/transformer/catalog-transformer-xml/pom.xml, catalog/transformer/catalog-transformer-xml/src/main/java/ddf/catalog/transformer/xml/adapter/AdaptedMetacard.java, catalog/transformer/catalog-transformer-xml/src/test/java/ddf/catalog/transform/xml/TestAdaptedMetacard.java, catalog/transformer/catalog-transformer-xml/src/test/java/ddf/catalog/transform/xml/TestXmlInputTransformer.java
Abbreviated review in effect. 
Forward port of https://github.com/codice/ddf/pull/2844
@brjeter 
@blen-desta 
@coyotesqrl 
=> DDF-3549 Download links for federated products in Intrigue should point to the local DDF instead of the remote one

catalog/rest/catalog-rest-endpoint/pom.xml
Removed common-system from list of embedded dependencies in catalog-rest-endpoint pom file.
@clockard
Successful build.
The `common-system` was changed from a jar to a bundle (see #2727) between the time the original PR (#2090) was created and merged. This PR simply removes `common-system` from the REST Endpoint's list of embedded dependencies.
[DDF-3105](https://codice.atlassian.net/browse/DDF-3105)
- ✏️ …
=> DDF-3105 Create Component test for REST endpoint (#2090)

Jenkinsfile
Pipelines build was failing with an unexpected token in the Jenkinsfile. This PR corrects the issue 🙏.
@oconnormi @vinamartin @blen-desta @LinkMJB @emanns95 @mackncheesiest @clockard @rzwiefel 
Wait to merge until the file can be evaluated in Jenkins.
=> DDF-3506 Replaced additional missing tokens in Jenkinsfile

catalog/spatial/wfs/1.0.0/spatial-wfs-v1_0_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v1_0_0/catalog/source/WfsSource.java, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/pom.xml, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsSource.java, catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/source/WfsSource.java, catalog/spatial/wfs/spatial-wfs-common/src/main/java/org/codice/ddf/spatial/ogc/wfs/catalog/common/AbstractWfsSource.java
Adds the ability to specify a client certificate alias to use with the WFS source.
@adimka 
@troymohl 
@glenhein 
@millerw8
@bdeining 
Verify full build
[DDF-3570](https://codice.atlassian.net/browse/DDF-3570)
- ❓ (Question …
=>  DDF-3570 adds client certificate support for WFS sources

catalog/ui/search-ui/search-endpoint/pom.xml, dependency-check-maven-config.xml, distribution/docs/src/main/resources/content/_dependencyList/ddf-dependency-list.adoc, platform/platform-app/pom.xml, platform/solr/platform-solr-server-standalone/dependency-check-maven-config.xml, pom.xml
Upgrates the jackson libraries to 2.9.4
@bdeining
@shaundmorris
CI Build passes
[DDF-3590](https://codice.atlassian.net/browse/DDF-3590)
=> [2.11.x] DDF-3590 Update jackson libraries to 2.9.4

catalog/ui/catalog-ui-search/src/main/webapp/component/singletons/session-timeout.js, distribution/docs/src/main/resources/content/_configuring/environment-hardening.adoc, platform/security/servlet/security-servlet-session-expiry/src/main/java/org/codice/ddf/security/servlet/expiry/SessionManagementService.java, platform/security/servlet/security-servlet-session-expiry/src/test/java/org/codice/ddf/security/servlet/expiry/SessionManagementServiceTest.java
Backport of https://github.com/codice/ddf/pull/2831 .
@AzGoalie @troymohl @emmberk 
@clockard
See https://github.com/codice/ddf/pull/2831 steps.
[DDF-3529](https://codice.atlassian.net/browse/DDF-3529) …
=> [2.11.x] DDF-3529 Fix UI session timeout redirect

catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/pom.xml
Fixed coverage
@glenhein 
@jlcsmith
@millerw8
Build
[DDF-3552](https://codice.atlassian.net/browse/DDF-3552) …
=> DDF-3552 Fixed coverage

platform/admin/core/admin-core-appservice/src/main/java/org/codice/ddf/admin/application/service/command/StatusApplicationCommand.java, platform/admin/core/admin-core-appservice/src/test/java/org/codice/ddf/admin/application/service/command/StatusApplicationCommandTest.java
Resolves cognitive complexity sonarqube finding in StatusApplicationCommand and adds a unit test
@blen-desta @Lambeaux 
@coyotesqrl
@shaundmorris 
[3538](https://codice.atlassian.net/browse/3538) …
=> DDF-3538 Resolve cognitive complexity finding in status application command

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/workspace/WorkspaceTransformer.java
Fixes Workspace Queries attributes Overwriting
Anyone
@emmberk 
@codice/io 
anyone
Ensure multiple queries with different sources don't get overwritten with the first queries sources
https://codice.atlassian.net/browse/DDF-3601 …
=> DDF-3601 Fix Workspace Queries attributes Overwriting

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/workspace/WorkspaceTransformer.java
Fixes Workspace Queries attributes Overwriting
Anyone
@emmberk 
@codice/io 
anyone
Ensure multiple queries with different sources don't get overwritten with the first queries sources
https://codice.atlassian.net/browse/DDF-3601 …
=> [2.11.x] DDF-3601 2.11.x workspace queries fix

distribution/docs/src/main/resources/content/_quickstart/quickstart-certificates.adoc, distribution/docs/src/main/resources/content/_quickstart/quickstart-installing.adoc
Backport of #2870 
@clockard @figliold 
[DDF-3559](https://codice.atlassian.net/browse/DDF-3559)
=> [2.11.x] DDF-3559 Added instructions for installing on a headless server

platform/admin/core/admin-core-appservice/src/main/java/org/codice/ddf/admin/application/service/impl/ApplicationConfigInstaller.java, platform/admin/core/admin-core-appservice/src/test/java/org/codice/ddf/admin/application/service/impl/ApplicationConfigInstallerTest.java
Resolves cognitive complexity finding in ApplicationConfigInstaller
@Lambeaux 
@blen-desta 
@coyotesqrl 
@shaundmorris
[3538](https://codice.atlassian.net/browse/3538) …
=> DDF-3538 Resolve cognitive complexity finding in Application Config Installer

platform/admin/core/admin-core-appservice/src/main/java/org/codice/ddf/admin/application/service/impl/ApplicationServiceBean.java
Resolves cognitive complexity findings in application service bean. 
@blen-desta 
@brjeter 
@bakejeyner 
@coyotesqrl 
@shaundmorris
Test installation and verify the admin UI is rendering correctly. 
[DDF-3538](https://codice.atlassian.net/browse/DDF-3538) …
=> DDF-3538 Resolve cognitive complexity findings in application service bean

platform/admin/core/admin-core-appservice/src/main/java/org/codice/ddf/admin/application/rest/ApplicationUploadEndpoint.java, platform/admin/core/admin-core-appservice/src/test/java/org/codice/ddf/admin/application/rest/ApplicationUploadEndpointTest.java
Resolves a cognitive complexity finding in the app upload endpoint.
✏️  When reviewing, commits have been separated logically to assist with evaluation: 
1. Complexity reduction using pure logic rules
2. Complexity reduction that extends to semantic changes with minimal to no impact
3. Fixes an outstanding TODO in the code
@brjeter 
@blen-desta 
@bakejeyner 
@coyotesqrl 
@shaundmorris
Need test case for the app upload endpoint. 
[DDF-3538](https://codice.atlassian.net/browse/DDF-3538) …
=> DDF-3538 Resolve cognitive complexity finding in app upload endpoint

distribution/docs/src/main/resources/content/_appReferences/mg-admin.adoc, distribution/docs/src/main/resources/content/_appReferences/mg-broker-app.adoc, distribution/docs/src/main/resources/content/_appReferences/mg-catalog.adoc, distribution/docs/src/main/resources/content/_appReferences/mg-geowebcache.adoc, distribution/docs/src/main/resources/content/_appReferences/mg-intrigue.adoc, distribution/docs/src/main/resources/content/_appReferences/mg-platform.adoc, distribution/docs/src/main/resources/content/_appReferences/mg-registry.adoc, distribution/docs/src/main/resources/content/_appReferences/mg-resource-mgmt.adoc, distribution/docs/src/main/resources/content/_appReferences/mg-security.adoc, distribution/docs/src/main/resources/content/_appReferences/mg-solr.adoc, distribution/docs/src/main/resources/content/_appReferences/mg-spatial.adoc, distribution/docs/src/main/resources/content/_appReferences/mg-ui.adoc, distribution/docs/src/main/resources/templates/application-reference.ftl
updates template for documentation Appendix for future maintainability.
@clockard
@coyotesqrl
@lessarderic
@rzwiefel
@shaundmorris
verify correct formatting on Appendix section headers
[DDF-3554](https://codice.atlassian.net/browse/DDF-3554) …
=> DDF-3554 refactored appendix template

platform/admin/core/admin-core-appservice/src/main/java/org/codice/ddf/admin/application/service/impl/ApplicationServiceImpl.java, platform/admin/core/admin-core-appservice/src/test/java/org/codice/ddf/admin/application/service/impl/ApplicationServiceImplTest.java
Resolves cognitive complexity findings in app service impl. 
@blen-desta 
@brjeter 
@bakejeyner 
@coyotesqrl 
@shaundmorris
Testing installation and app commands should be sufficient. 
[DDF-3538](https://codice.atlassian.net/browse/DDF-3538)
- ❗ …
=> DDF-3538 Resolve cognitive complexity findings in app service impl

platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/binding/api/impl/ValidatorImpl.java
Disallows angle brackets - `<` and `>` - in `RelayState`.
(Port of #2939)
@rzwiefel
@stustison
Attaching a third-party SP in which the `RelayState` can be specified (Spring Security works well for this) and setting the `RelayState` to any value with any number of angle brackets should disallow authentication.
N/A
[DDF-3606](https://codice.atlassian.net/browse/DDF-3606) …
=> [2.11.x] DDF-3606 Prevents low-risk XSS reflection attack from a remote SP by validating RelayState.

catalog/rest/catalog-rest-endpoint/pom.xml, catalog/rest/catalog-rest-endpoint/src/main/java/org/codice/ddf/endpoints/rest/RESTEndpoint.java, pom.xml
Addressed the potential reflected cross-site scripting vulnerability in RESTEndpoint.
@brjeter 
@blen-desta 
@bakejeyner 
@Lambeaux 
@clockard
@coyotesqrl 
[DDF-3587](https://codice.atlassian.net/browse/DDF-3587) …
=> DDF-3587 Resolved Reflected XSS vulnerability in RestEndpoint

platform/security/security-services-app/src/main/resources/features.xml, platform/security/sts/security-sts-ldaplogin/pom.xml, platform/security/sts/security-sts-ldaplogin/src/main/java/ddf/ldap/ldaplogin/LdapConnectionPooledObjectFactory.java, platform/security/sts/security-sts-ldaplogin/src/main/java/ddf/ldap/ldaplogin/LdapLoginConfig.java, platform/security/sts/security-sts-ldaplogin/src/main/java/ddf/ldap/ldaplogin/SslLdapLoginModule.java, platform/security/sts/security-sts-ldaplogin/src/main/resources/OSGI-INF/blueprint/karaf_ldap_config.xml, platform/security/sts/security-sts-ldaplogin/src/test/java/ddf/ldap/ldaplogin/LdapLoginConfigTest.java, platform/security/sts/security-sts-ldaplogin/src/test/java/ddf/ldap/ldaplogin/LdapModuleTest.java, platform/security/sts/security-sts-ldaplogin/src/test/java/ddf/ldap/ldaplogin/SslLdapLoginModuleTest.java
cherry pick to master the ldap fix
@jlcsmith
@derekwilhelm 
@rzwiefel
@stustison
- [ x] Update / Add Unit Tests …
=> DDF-3594 improve performance of ldap login

catalog/ui/catalog-ui-search/src/main/webapp/component/location-old/location-old.hbs, catalog/ui/catalog-ui-search/src/main/webapp/component/location-old/location-old.less, catalog/ui/catalog-ui-search/src/main/webapp/css/searchPage.css, catalog/ui/catalog-ui-search/src/main/webapp/js/DistanceUtils.js, catalog/ui/catalog-ui-search/src/main/webapp/styles/components/jquery-ui.less
Adds support for nautical miles as units of measure for point-radii and line geospatial searches. The width of the dropdown box was also increase to accommodate the length of the new option and the text/background color of the dropdown was fixed.
@adimka @mackncheesiest
@jlcsmith
Manually verify the nautical units are able to be used in line and point-radii queries, the nautical units are correctly converted to meters in the queries, and the css looks ok in all themes and spacing levels.
[DDF-3607](https://codice.atlassian.net/browse/DDF-3607) …
=> DDF-3607 Added support for nautical miles

platform/landing-page/src/main/resources/assets/js/index.js
Sanitizes the header and footer text values on the landing page
@blen-desta 
@brjeter 
@bakejeyner 
@coyotesqrl 
Start Admin UI
In Admin Console click Platform
Click Configuration
Click Platform UI Configuration
Edit the header and footer values to contain view corrupting html (<script> alert() </script>)
Verify on the landing page the view is consistent to other pages
[DDF-3617](https://codice.atlassian.net/browse/) …
=> DDF-3617 Sanitized header and footer text on landing page

catalog/core/catalog-core-api/src/main/resources/feature.xml, catalog/rest/catalog-rest-endpoint/pom.xml, catalog/rest/catalog-rest-endpoint/src/test/java/org/codice/ddf/endpoints/rest/RestEndpointIT.java, libs/test-common/src/main/filtered-resources/features.xml, libs/test-common/src/main/java/org/codice/ddf/test/common/AbstractComponentTest.java, libs/test-common/src/main/java/org/codice/ddf/test/common/configurators/ApplicationOptions.java, libs/test-common/src/main/java/org/codice/ddf/test/common/configurators/PortFinder.java, platform/mime/core/platform-mime-core-api/src/main/resources/feature.xml
Changed how the PortFinder is being passed around in the AbstractComponentTest class.
Renamed the catalog core API and mime type API features to avoid conflict with those defined in the platform-app and catalog-app features files, which was causing tests to fail in some circumstances.
Improved some of the comments and removed unneeded dependencies in pom files.
Forward port of https://github.com/codice/ddf/pull/2950.
@tbatie 
@paouelle 
@clockard
@coyotesqrl
CI build successful.
[DDF-3105](https://codice.atlassian.net/browse/DDF-3105)
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+R …
=> DDF-3105 Create Component test for REST endpoint

Documentation-versions.html, index.html
Updates website for 2.11.5 release
@ricklarsen 
[DDF-3610](https://codice.atlassian.net/browse/DDF-3610)
=> DDF-3610 Updated website for 2.11.5 release

catalog/ui/catalog-ui-search/src/main/webapp/js/ApplicationStart.js, catalog/ui/catalog-ui-search/src/main/webapp/js/model/User.js
- Updates the UI to auto-redirect to a new workspace if a User comes in to the start page (no hash -> /search/catalog/) without any existing workspaces.
- Updates the UI to auto-redirect to a workspace if the User comes in to the start page (no hash -> /search/catalog/) and only has one workspace.
- No redirects / creates will happen if there is a hash (#workspaces, #upload, etc.).
@bdeining
@jlcsmith
@millerw8 
@adimka 
@mackncheesiest
=> DDF-3582 Adds auto-redirect / workspace creation

broker/broker-route-manager/pom.xml, broker/broker-route-manager/src/test/java/org/codice/ddf/broker/route/manager/DynamicRouteDeployerTest.java, catalog/measure/catalog-measure-api/pom.xml, pom.xml
Upgrade to Jacoco 0.8.0
@paouelle 
@oconnormi 
@peterhuffer 
@codice/build 
@codice/test 
@lessarderic 
@clockard 
Windows build passes 
https://codice.atlassian.net/browse/DDF-3596 …
=> DDF-3596 Upgraded to Jacoco 0.8.0

distribution/docs/src/main/resources/content/_installing/installing-intro.adoc, distribution/docs/src/main/resources/content/_quickstart/quickstart-installing.adoc
Remove `/m` from startup guide PATH suggested code
@clockard @ricklarsen @shaundmorris @vinamartin
=> DDF-2824 Fixed startup guide typo

broker/broker-route-manager/src/main/java/org/codice/ddf/broker/route/manager/DynamicRouteDeployer.java, broker/broker-route-manager/src/test/java/org/codice/ddf/broker/route/manager/DynamicRouteDeployerTest.java
When restarting the route manager bundle, none of the routes from the routes directory were getting restarted properly. This PR properly restarts the routes when restarting that bundle.
@ryeats 
@derekwilhelm 
@coyotesqrl
@jaymcnallie 
1. Run a full build, with all tests passing.
2. Insert a routes file inside <INSTALL_DIR>/etc/routes, verify the route(s) are running. Restart the route manager bundle, verify the route(s) from the routes file are still running.
[DDF-3608](https://codice.atlassian.net/browse/)
- ✏️ …
=> DDF-3608 Restarting the route manager bundle now properly restarts routes

distribution/docs/src/main/resources/content/_configuring/configuring-guest-access.adoc, distribution/docs/src/main/resources/content/_configuring/configuring-idp.adoc, distribution/docs/src/main/resources/content/_configuring/configuring-sts.adoc
Updates some of the security hardening documentation.
@brjeter 
@blen-desta 
@coyotesqrl
@stustison 
=> DDF-2824-Security-Hardening

catalog/opensearch/catalog-opensearch-source/pom.xml, catalog/opensearch/catalog-opensearch-source/src/main/java/ddf/catalog/source/opensearch/impl/OpenSearchParserImpl.java, catalog/opensearch/catalog-opensearch-source/src/test/groovy/ddf/catalog/source/opensearch/impl/OpenSearchParserImplCreateBBoxSpec.groovy, catalog/opensearch/catalog-opensearch-source/src/test/java/ddf/catalog/source/opensearch/impl/OpenSearchParserImplTest.java, catalog/schematron/catalog-schematron-plugin/src/main/resources/iso-schematron/iso_schematron_skeleton_for_saxon.xsl, catalog/schematron/catalog-schematron-plugin/src/main/resources/iso-schematron/iso_svrl_for_xslt2.xsl, catalog/ui/search-ui/simple/src/main/resources/RecordView.html, catalog/ui/search-ui/simple/src/main/webapp/lib/jquery/js/plugin/purl.js, distribution/docs/src/main/resources/content/_tables/OpenSearchSource.adoc, platform/admin/modules/admin-modules-application/src/test/resources/services.json, platform/admin/modules/admin-modules-configuration/src/test/resources/services.json, platform/admin/modules/admin-modules-installer/src/test/resources/services.json
____
Port of https://github.com/codice/ddf/pull/2933
@bdeining 
@clockard  
[DDF-3604](https://codice.atlassian.net/browse/DDF-3604)
=> DDF-3604 Fixed OpenSearch bounding box

platform/landing-page/src/main/resources/assets/js/index.js
Back-port https://github.com/codice/ddf/pull/2954
@blen-desta 
@bakejeyner 
@brjeter 
@coyotesqrl
=> [2.11.x] DDF-3617 Sanitized header and footer text on landing page

platform/security/servlet/security-servlet-logout/src/main/webapp/js/logout-response.js
Sanitizes a URL parameter on the logout page
@brjeter 
@blen-desta 
@bakejeyner 
@coyotesqrl 
Go to: https://localhost:8993/logout/logout-response.html?msg=%3Cscript%3Ealert(1);%3C/script%3E
Verify the view is not corrupted.
[DDF-3625](https://codice.atlassian.net/browse/) …
=> DDF-3625 Sanitized Logout Page URL Parameters

platform/security/servlet/security-servlet-logout/src/main/webapp/js/logout-response.js
Back-port https://github.com/codice/ddf/pull/2965
@brjeter 
@bakejeyner 
@blen-desta 
@coyotesqrl 
=> [2.11.x] DDF-3625 Sanitized Logout Page URL Parameters

catalog/core/catalog-core-federationstrategy/pom.xml, catalog/core/catalog-core-solr/pom.xml, catalog/core/catalog-core-standardframework/pom.xml, catalog/core/pom.xml, catalog/pom.xml, catalog/solr/catalog-solr-provider/pom.xml, catalog/spatial/geocoding/spatial-geocoding-create/pom.xml, catalog/spatial/geocoding/spatial-geocoding-extract/pom.xml, catalog/spatial/geocoding/spatial-geocoding-offline-catalog/pom.xml, catalog/ui/search-ui/search-endpoint/pom.xml, distribution/test/itests/test-itests-common/pom.xml, pom.xml
Upgrades maven-dependency-plugin to 3.0.2
@mcalcote @LinkMJB 
@codice/build 
@lessarderic 
@shaundmorris 
[DDF-3338](https://codice.atlassian.net/browse/DDF-3338)
=> DDF-3338 upgrade maven-dependency-plugin to 3.0.2

catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/TransformersCommand.java, catalog/core/catalog-core-commands/src/test/java/org/codice/ddf/commands/catalog/TransformersCommandTest.java
The 'catalog:transformer' command now lists metacard transformers as well (it used to only list input transformers). You can also indicate if you
want just input transformers or just metacard transformers with the
-i and -m options.
@peterhuffer @emmberk @clockard 
@clockard
@figliold
Run TransformersCommandTest.java
https://codice.atlassian.net/browse/DDF-3202 …
=> DDF-3202 Extended catalog:transformer command

platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/binding/redirect/RedirectValidator.java, platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/server/IdpEndpoint.java
Took out the @encoded for relay state and encoded relay state in the signature verification instead
@coyotesqrl 
@stustison
Using the SAML conformance test kit at https://github.com/connexta/saml-conformance
[DDF-3571](https://codice.atlassian.net/browse/DDF-3571) …
=> DDF-3571 Took out the @encoded for relay state and encoded relay state in the signature verification instead

libs/test-common/src/main/java/org/codice/ddf/test/common/rules/TestFailureLogger.java
Filters out Fragment bundles from the log messages that are displayed for bundles that are not ACTIVE when component tests fail to start.
Related to #2992 
@emanns95 @tbatie 
@lessarderic
@rzwiefel
This is a component test change and will only show up on a failure to start. CI should be sufficient, but could be more thoroughly heroed by making a feature/bundle un-deployable for a component test (by depending on something unavailable, for example) and then confirming that the log contains none of the Fragment bundles after the Listing inactive bundles log message. …
=> DDF-3642 Filters out Fragment bundles from logging component test failures

pom.xml
Upgrades bouncy castle from 1.55 to 1.59
@clockard @figliold 
[DDF-3648](https://codice.atlassian.net/browse/DDF-3648) …
=> DDF-3648 Upgraded bouncy castle to 1.59

pom.xml
backports #3001 
@clockard @coyotesqrl 
[DDF-3648](https://codice.atlassian.net/browse/DDF-3648)
=> [2.11.x] DDF-3648 Upgraded bouncy castle to 1.59

distribution/docs/src/main/resources/content/_installing/installing-intro.adoc
Updates the minimum system requirements and moves the tested operating systems and browsers to a separate table.
@ricklarsen 
@oconnormi 
@mcalcote 
@shaundmorris 
Build documentation and review.
[DDF-3358](https://codice.atlassian.net/browse/DDF-3358)
=> DDF-3358 Update Minimum and Recommended System Requirements

catalog/ui/catalog-ui-search/src/main/webapp/component/query-settings/query-settings.hbs
Changes button label to be consistent with others.
@bdeining @lcrosenbu @andrewkfiedler 
@bdeining
Build, verify change
[DDF-3654](https://codice.atlassian.net/browse/DDF-3654) …
=> DDF-3654 fixed button verb consistency

catalog/ui/catalog-ui-search/src/main/webapp/component/user-settings/user-settings.hbs, catalog/ui/catalog-ui-search/src/main/webapp/component/user-settings/user-settings.less
Resolves DDF-3638, minor UI change
@lcrosenbu  @bdeining @AzGoalie  
@bdeining
Full build, look at UI to verify changes.
[DDF-3638](https://codice.atlassian.net/browse/DDF-3638) …
=> DDF-3638 provide intuitive description of Search Settings

distribution/docs/src/main/resources/content/_dependencyList/ddf-dependency-list.adoc, distribution/test/itests/test-itests-dependencies-app/pom.xml, platform/platform-app/pom.xml, platform/platform-app/src/main/resources/features.xml, pom.xml
Backport of this fix: https://github.com/codice/ddf/pull/2969
@brjeter
@coyotesqrl
@lessarderic
@shaundmorris …
=> DDF-3627 Updates httpclient to v4.5.4 resolve TLS SAN issue (#2969)

platform/admin/ui/src/main/webapp/templates/installer/finish.handlebars
=> [2.11.x] DDF-2824 Fixes a small typo on the installer finish page

platform/admin/ui/src/main/webapp/templates/installer/finish.handlebars
Port https://github.com/codice/ddf/pull/3017
@andrewkfiedler @rzwiefel @shaundmorris
=> DDF-2824 Fixes a small typo on the installer finish page

dependency-check-maven-config.xml
Port of https://github.com/codice/ddf/pull/3021
@bdeining @clockard
=> DDF-3590 Adds suppression for CVE-2017-7525

platform/admin/ui/src/main/webapp/templates/installer/finish.handlebars
Just fixes a typo for the /keystores directory
@Lambeaux 
@tbatie 
@codice/ui 
@figliold 
Could be through inspection or pull up the new version with the change in it.
[DDF-3639](https://codice.atlassian.net/browse/DDF-3639) …
=> DDF-3639 fixed install page typo

distribution/docs/src/main/resources/content/_architectures/migration-api.adoc, platform/migration/platform-migratable-api/src/main/java/org/codice/ddf/migration/ExportMigrationContext.java, platform/migration/platform-migratable-api/src/test/java/org/codice/ddf/migration/ExportMigrationContextTest.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/admin/ConfigurationAdminMigratable.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/admin/ExportMigrationConfigurationAdminContext.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/admin/ImportMigrationConfigurationAdminContext.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/ExportMigrationContextImpl.java, platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/admin/ConfigurationAdminMigratableTest.java, platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/migration/ExportMigrationContextImplTest.java
____
It modifies the config admin migratable to export the config files under etc in addition to the config objects. Although the import phase will not re-import those files, it eventually might re-import them. Since in order to support it later, we need to make sure the files are available as part of the export DAR file.
@emanns95 
@tbatie 
@clockard
@lessarderic 
@figliold
- Install DDF and make changes to config
- Perform a `migration:export` 
- Preserve the 3 files exported
- Re-unzip DDF
- Perform `migration:import --profile` 
- Verify that the system is reconfigured as it was
[DDF-3614](https://codice.atlassian.net/browseDDF-3614/) …
=> DDF-3614 Modified config admin migratable to export config files in addition to objects

broker/broker-undelivered-messages-ui/package.json, broker/broker-undelivered-messages-ui/yarn.lock, catalog/admin/module/catalog-admin-module-sources/pom.xml, catalog/resourcemanagement/resourcemanagement-querymonitor-ui/pom.xml, catalog/resourcemanagement/resourcemanagement-querymonitor-ui/src/main/webapp/main.js, catalog/resourcemanagement/resourcemanagement-usage-ui/pom.xml, catalog/resourcemanagement/resourcemanagement-usage-ui/src/main/webapp/main.js, catalog/spatial/geocoding/spatial-geocoding-admin-module/pom.xml, catalog/spatial/geocoding/spatial-geocoding-admin-module/src/main/webapp/main.js, catalog/spatial/geowebcache/geowebcache-admin-plugin/pom.xml, catalog/spatial/geowebcache/geowebcache-admin-plugin/src/main/webapp/main.js, catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/pom.xml, catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/main.js, catalog/ui/catalog-ui-search/package.json, catalog/ui/catalog-ui-search/yarn.lock, catalog/ui/search-ui/standard/pom.xml, catalog/ui/search-ui/standard/src/main/webapp/main.js, distribution/docs/src/main/resources/content/_dependencyList/ddf-dependency-list.adoc, platform/admin/core/admin-core-logviewer/package.json, platform/admin/core/admin-core-logviewer/yarn.lock, platform/admin/modules/admin-metrics-ui/pom.xml, platform/admin/modules/admin-metrics-ui/src/main/webapp/main.js, platform/admin/modules/admin-security-certificate-ui/pom.xml, platform/admin/modules/admin-security-certificate-ui/src/main/webapp/main.js, platform/admin/ui/pom.xml, platform/admin/ui/src/main/webapp/main.js, pom.xml
Upgrade the moment library to 2.20.1
@emmberk @peterhuffer @kcover @djblue 
@rzwiefel
Install ddf and verify that date/time functions in Intrigue and the admin ui still work.
[DDF-3646](https://codice.atlassian.net/browse/DDF-3646)
=> DDF-3646 Update moment to 2.20.1

dependency-check-maven-config.xml, platform/solr/platform-solr-server-standalone/dependency-check-maven-config.xml
@emanns95 @oconnormi 
@bdeining
@clockard
=> [2.11.x] DDF-3590 Adds suppression for CVE-2017-7525

distribution/docs/src/main/resources/content/_configuring/enforcing-errors.adoc, distribution/docs/src/main/resources/content/_configuring/errors-and-warnings.adoc, distribution/docs/src/main/resources/content/_configuring/hiding-errors-by-role.adoc, distribution/docs/src/main/resources/content/_configuring/hiding-errors.adoc, distribution/docs/src/main/resources/content/_devComponents/attribute-injection.adoc, distribution/docs/src/main/resources/content/_running/correcting-errors.adoc, distribution/docs/src/main/resources/content/_running/editing-attributes.adoc, distribution/docs/src/main/resources/content/_running/injecting-attributes.adoc, distribution/docs/src/main/resources/content/_running/overriding-attributes.adoc, distribution/docs/src/main/resources/content/_running/viewing-invalid.adoc, distribution/docs/src/main/resources/content/_tables/MetacardValidityMarkerPlugin.adoc
Updates documentation in these areas:
- Configuring: showing hiding metacards with data validation errors from users.
- Data management: editing and overriding metacards
- Developing: edits to creating an attribute injection file.
@brendan-hofmann @ahoffer @mcalcote @vinamartin 
https://github.com/orgs/codice/teams/data/members
@beyelerb
@clockard
@coyotesqrl
@lessarderic
@shaundmorris
review content additions and edits.
[DDF-3633](https://codice.atlassian.net/browse/DDF-3633) …
=> DDF-3633 updated docs for metacard attribute editing

catalog/plugin/catalog-plugin-jpeg2000-thumbnail-converter/pom.xml, catalog/transformer/catalog-transformer-tika-input/pom.xml, distribution/docs/src/main/resources/content/_dependencyList/ddf-dependency-list.adoc
Update jpeg2000 library to latest codice version which has a fix for an infinite loop problem
Depends on https://github.com/codice/jai-imageio-jpeg2000/pull/3
@bdeining
@lessarderic
[DDF-3656](https://codice.atlassian.net/browse/DDF-3656)
=> DDF-3656 Update jpeg2000 library to latest codice version

distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/ServiceManager.java, distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/ServiceManagerImpl.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalog.java
Prevents the a test from starting up a feature that doesn't start up independently. Made it start/stop the bundle instead.
@emanns95 
@oconnormi 
@figliold
@rzwiefel …
=> DDF-3636: Fixed TestCatalog#testMetacardIngestNetworkPlugin test

platform/admin/ui/src/main/webapp/templates/installer/finish.handlebars
Fix typo  in the installation page. Backport of https://github.com/codice/ddf/pull/2989
@vinamartin 
@Lambeaux 
@tbatie 
@codice/ui 
@clockard
@figliold 
[DDF-3639](https://codice.atlassian.net/browse/DDF-3639) …
=> DDF-3639 fixed install page typo (#2989)

catalog/ui/catalog-ui-search/src/main/webapp/component/query-interactions/query-interactions.hbs, catalog/ui/catalog-ui-search/src/main/webapp/component/query-interactions/query-interactions.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/result-selector/result-selector.view.js, catalog/ui/catalog-ui-search/src/main/webapp/js/model/Query.js
Enables issuing and display of result count only queries via Intrigue.
@rzwiefel @mackncheesiest @Lambeaux 
@bdeining
Ingest data, create a query. Issuing the query normally should return results.
Selecting the result count option from the overflow menu should return the same result count, but not display any results.
[DDF-3641](https://codice.atlassian.net/browse/DDF-3641)
Regular Query
Result Count Button
Hit Count Result …
=> DDF-3641 Adds result count only query support to Intrigue

catalog/ui/catalog-ui-search/src/main/webapp/component/navigation-right/navigation-right.hbs, catalog/ui/catalog-ui-search/src/main/webapp/component/navigation-right/navigation-right.less
Updates the sign-in icon and removes the previously visible guest icon. 
@bdeining 
@adimka 
View the sign in button in the top toolbar. 
[DDF-3644](https://codice.atlassian.net/browse/DDF-3644) …
=> DDF-3644 Updating Sign In Icon

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/QueryApplication.java
Intrigue queries will now enumerate all results for a query up to the page size parameter instead of being limited to the internal catalog maxPageSize
@pklinef 
anyone
See ticket for reproduction steps
This was simply a missed case when we added the internal catalog maxPageSize to limit the results of an individual query and so the fix was using the ResultIterable to page through all needed results for a query
https://codice.atlassian.net/browse/DDF-3509 …
=> DDF-3509 Fixed page size bug with Intrigue queries

catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswSubscriptionEndpoint.java, catalog/spatial/geocoding/spatial-geocoding-offline-catalog/src/main/java/org/codice/ddf/spatial/geocoding/index/IndexInitializer.java
Resolves SonarQube Blocker Bug findings. I only updated the log statements with the findings. The whole log level usage may need to re-examined for consistency in the future.
@mcalcote 
@idperez 
@kcover 
@ryeats 
@bdeining 
@rzwiefel   
Passing build
[DDF-3277](https://codice.atlassian.net/browse/DDF-3277) …
=> DDF-3277 Fixed not enough arguments issues

distribution/docs/src/main/resources/content/_appendixIntros/metadata-attributes-intro.adoc, distribution/docs/src/main/resources/content/_configuring/environment-hardening.adoc, distribution/docs/src/main/resources/content/_coreConcepts/data-standards.adoc, distribution/docs/src/main/resources/content/_data/data-intro.adoc, distribution/docs/src/main/resources/content/_installing/system-configuration-settings.adoc, distribution/docs/src/main/resources/content/_metadataAttributes/associations-attributes-table.adoc, distribution/docs/src/main/resources/content/_metadataAttributes/catalog-taxonomy-intro.adoc, distribution/docs/src/main/resources/content/_metadataAttributes/complete-list-file-types.adoc, distribution/docs/src/main/resources/content/_metadataAttributes/contact-attributes-table.adoc, distribution/docs/src/main/resources/content/_metadataAttributes/core-attributes-table.adoc, distribution/docs/src/main/resources/content/_metadataAttributes/datetime-attributes-table.adoc, distribution/docs/src/main/resources/content/_metadataAttributes/format-specific-attributes.adoc, distribution/docs/src/main/resources/content/_metadataAttributes/history-attributes-table.adoc, distribution/docs/src/main/resources/content/_metadataAttributes/location-attributes-table.adoc, distribution/docs/src/main/resources/content/_metadataAttributes/media-attributes-table.adoc, distribution/docs/src/main/resources/content/_metadataAttributes/metacard-attributes-table.adoc, distribution/docs/src/main/resources/content/_metadataAttributes/mp4-attributes.adoc, distribution/docs/src/main/resources/content/_metadataAttributes/security-attributes-table.adoc, distribution/docs/src/main/resources/content/_metadataAttributes/supported-file-formats.adoc, distribution/docs/src/main/resources/content/_metadataAttributes/topic-attributes-table.adoc, distribution/docs/src/main/resources/content/_metadataAttributes/validation-attributes-table.adoc, distribution/docs/src/main/resources/content/_transformers/tika-input-xformer.adoc
- creates anchors for attribute definitions in the appendix to facilitate linking directly to the attributes.
@beyelerb
@clockard
@lessarderic
@shaundmorris
- build is successful. 
[DDF-3633](https://codice.atlassian.net/browse/DDF-3633) …
=> DDF-3633 updated appendix for catalog taxonomy attributes

README.md
@mcalcote 
@clockard
DDF logo appears on README
[DDF-3390](https://codice.atlassian.net/browse/DDF-3390) …
=> DDF-3390 Fixed logo link

catalog/plugin/catalog-plugin-jpeg2000-thumbnail-converter/pom.xml, catalog/transformer/catalog-transformer-tika-input/pom.xml, distribution/docs/src/main/resources/content/_dependencyList/ddf-dependency-list.adoc
Port of https://github.com/codice/ddf/pull/3014
@bdeining
@lessarderic
CI Build
[DDF-3565](https://codice.atlassian.net/browse/DDF-3565)
=> DDF-3656 Update jpeg2000 library to latest codice version (#3014)

catalog/spatial/geocoding/spatial-geocoding-offline-catalog/src/main/resources/OSGI-INF/blueprint/blueprint.xml
Fix geocoding-offline-catalog blueprint to resolve ddf.home variable
@troymohl @peterhuffer @oconnormi 
@figliold
@stustison
@bdeining 
CI Build
[DDF-3568](https://codice.atlassian.net/browse/DDF-3568)
=> DDF-3568 Fix geocoding-offline-catalog blueprint to resolve ddf.home variable

distribution/docs/src/main/resources/content/_tables/CachingFederationStrategy.adoc
Updates Caching Federation Strategy configuration documentation is accurately define the default value for cache everything. 
https://github.com/codice/ddf/blob/master/catalog/core/catalog-core-standardframework/src/main/resources/OSGI-INF/metatype/sortedFederationStrategy.xml#L64
@ahoffer 
@peterhuffer 
@pklinef …
=> DDF-2824 Update Caching Federation Strategy docs

broker/broker-undelivered-messages-ui/package.json, broker/broker-undelivered-messages-ui/yarn.lock, catalog/admin/module/catalog-admin-module-sources/pom.xml, catalog/resourcemanagement/resourcemanagement-querymonitor-ui/pom.xml, catalog/resourcemanagement/resourcemanagement-querymonitor-ui/src/main/webapp/main.js, catalog/resourcemanagement/resourcemanagement-usage-ui/pom.xml, catalog/resourcemanagement/resourcemanagement-usage-ui/src/main/webapp/main.js, catalog/spatial/geocoding/spatial-geocoding-admin-module/pom.xml, catalog/spatial/geocoding/spatial-geocoding-admin-module/src/main/webapp/main.js, catalog/spatial/geowebcache/geowebcache-admin-plugin/pom.xml, catalog/spatial/geowebcache/geowebcache-admin-plugin/src/main/webapp/main.js, catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/pom.xml, catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/main.js, catalog/ui/catalog-ui-search/package.json, catalog/ui/catalog-ui-search/yarn.lock, catalog/ui/search-ui/standard/pom.xml, catalog/ui/search-ui/standard/src/main/webapp/main.js, distribution/docs/src/main/resources/content/_dependencyList/ddf-dependency-list.adoc, platform/admin/core/admin-core-logviewer/package.json, platform/admin/core/admin-core-logviewer/yarn.lock, platform/admin/modules/admin-metrics-ui/pom.xml, platform/admin/modules/admin-metrics-ui/src/main/webapp/main.js, platform/admin/modules/admin-security-certificate-ui/pom.xml, platform/admin/modules/admin-security-certificate-ui/src/main/webapp/main.js, platform/admin/ui/pom.xml, platform/admin/ui/src/main/webapp/main.js, pom.xml
Port of https://github.com/codice/ddf/pull/3000
@rzwiefel
@shaundmorris
CI Build
[DDF-3646](https://codice.atlassian.net/browse/DDF-3646)
=> DDF-3646 Update moment to 2.20.1 (#3000)

pom.xml
See title.
@emanns95 
@AzGoalie 
@codice/ui
@codice/build 
@kcwire
- `mvn clean install` ui directory on windows should be enough
[DDF-3584](https://codice.atlassian.net/browse/DDF-3584) …
=> DDF-3584 Bumps yarn version to fix windows build issue

ui/packages/ui/src/main/webapp/templates/installer/finish.handlebars
Updates some file typos in the installation page, systemKeystore -> serverKeystore
@codice/docs 
@clockard
Could verify the files are correct
[DDF-3639](https://codice.atlassian.net/browse/DDF-3639) …
=> DDF-3639 Fixed typos in install finish page

dependency-check-maven-config.xml, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestSecurity.java, platform/platform-http-proxy/pom.xml, platform/security/pom.xml, platform/solr/platform-solr-server-standalone/dependency-check-maven-config.xml, platform/solr/platform-solr-server-standalone/pom.xml, pom.xml
- Reduce unnecessary OWASP checks for CI
- Update the dependency check plugin version to 3.1.1
- Use maven plugin management to set default properties for dependency check plugin
@mcalcote
@vinamartin
@brianfelix
@LinkMJB
@oconnormi
@clockard
@rzwiefel
`mvn install -P owasp -DskipStatic=true -DskipTests=true`
No.
DDF-3506
- [ N/A] Documentation Updated
- [N/A ] Update / Add Unit Tests
- [N/A ] Update / Add Integration Tests …
=> DDF-3506 Improve OWASP scanning

catalog/transformer/catalog-transformer-streaming-lib/src/main/java/org/codice/ddf/transformer/xml/streaming/lib/SaxEventHandlerDelegate.java
Revert duplicate removal logic from SaxEventHandlerDelegate
Breaking pr https://github.com/codice/ddf/commit/cad9b595434358d66f2fbb7de981999c9a6cbe5e#diff-10699b7d5591be1bb81f1bcc754b8552R170
@emanns95 @mcalcote 
@rzwiefel
@shaundmorris
Passing CI build
[DDF-3674](https://codice.atlassian.net/browse/DDF-3674)
=> DDF-3674 Revert duplicate removal logic from SaxEventHandlerDelegate

catalog/core/catalog-core-directorymonitor/pom.xml, catalog/core/catalog-core-metricsplugin/pom.xml, catalog/core/catalog-core-standardframework/pom.xml, catalog/rest/catalog-rest-endpoint/pom.xml, catalog/solr/solr-app/pom.xml, catalog/spatial/csw/spatial-csw-schema-bindings/pom.xml, catalog/spatial/geocoding/spatial-geocoding-offline-catalog/pom.xml, catalog/spatial/kml/spatial-kml-transformer/pom.xml, catalog/spatial/registry/registry-source-configuration-handler/pom.xml, catalog/spatial/spatial-app/pom.xml, catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-schema-bindings/pom.xml, catalog/ui/search-ui/search-endpoint/pom.xml, catalog/ui/search-ui/standard/pom.xml, distribution/sdk/ddf-sso-query-widget/pom.xml, distribution/sdk/ddf-sso-widget/pom.xml, distribution/test/itests/test-itests-ddf/pom.xml, distribution/test/pom.xml, gitsetup/pom.xml, libs/owasp-diff-runner/pom.xml, platform/compression/platform-compression-exi/pom.xml, platform/email/platform-email-impl/pom.xml, platform/error/platform-error-servlet/pom.xml, platform/osgi/platform-osgi-condpermadmin/pom.xml, platform/osgi/platform-osgi-configadmin/pom.xml, platform/security/cas/security-cas-client/pom.xml, platform/security/sts/security-sts-realm/pom.xml, platform/solr/platform-solr-server-standalone/pom.xml, platform/solr/solr-banana/pom.xml, pom.xml
The current nightly builds of DDF contain various warnings. These warnings may lead to build instability. This PR addresses them.
All of the warnings are either dependencies with missing versions or duplications in the same pom.
@brjeter @bakejeyner @blen-desta 
@coyotesqrl
@shaundmorris 
Maven warnings can be seen in the latest DDF nightly builds https://jenkins.phx.connexta.com/job/DDF-Jobs/job/master/job/Linux/
[DDF-3668](https://codice.atlassian.net/browse/) …
=> DDF-3668 Resolved maven build warnings

ui/packages/catalog-ui-search/src/main/webapp/component/workspace-interactions/workspace-interactions.hbs
Changes "Move to trash" to "Delete Workspace".
@michaelmenousek @lcrosenbu @andrewkfiedler 
@bdeining
Full build, launch UI, verify that "Move to trash" is now "Delete Workspace"
[DDF-3703](https://codice.atlassian.net/browse/DDF-3703)  …
=> DDF-3703 changed Move to trash to Delete Workspace

platform/compression/platform-compression-exi/pom.xml, platform/solr/platform-solr-server-standalone/pom.xml
Fixes the owasp configuration for a couple of modules
@ahoffer @emanns95 
@bdeining
@shaundmorris
Local build without running the owas profile
[DDF-3506](https://codice.atlassian.net/browse/DDF-3506)
=> DDF-3506 Move owasp configuration in sub modules to the owasp profile

pom.xml
Exactly what it says in the summary 😄 
@ahoffer @LinkMJB 
@codice/build 
@shaundmorris @clockard 
[DDF-3709](https://codice.atlassian.net/browse/DDF-3709) …
=> DDF-3709 add properties for overriding dependency-check NVD download location

platform/security/idp/security-idp-client/src/main/java/org/codice/ddf/security/idp/client/LogoutRequestService.java
Resolves a NPE exception that occurred during a logout using POST binding
@brjeter @blen-desta @bakejeyner @SmithJosh 
@clockard
@coyotesqrl 
* Paste [idp metadata](https://github.com/codice/ddf/files/1827168/idp.txt) in: AdminConsole -> Security -> Configuration -> IdP Client
* Paste [sp metadata](https://github.com/codice/ddf/files/1827167/sp.txt) in: AdminConsole -> Security -> Configuration -> IdP Server
Verify proper logout and login
[DDF-3684](https://codice.atlassian.net/browse/DDF-3684) …
=> DDF-3684 Resolved NPE during logout when using POST binding

ui/packages/catalog-ui-search/src/main/webapp/component/map-context-menu/map-context-menu.hbs, ui/packages/catalog-ui-search/src/main/webapp/component/map-context-menu/map-context-menu.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/map.model.js
Adds "Copy DMS Coordinates" option to map context-menu.
@Schachte 
@Variadicism 
@codice/ui 
@bdeining
1. Right click map.
2. Copy DMS coordinates (verify value in popup matches DMS coordinates in bottom left-hand corner).
[DDF-3693](https://codice.atlassian.net/browse/DDF-3693) …
=> DDF-3693 Adding DMS coordinates

distribution/docs/src/main/resources/content/_installing/ddf-setup-types.adoc, distribution/docs/src/main/resources/content/_installing/guest-claims-attributes.adoc, ui/packages/ui/src/main/webapp/js/views/installer/Configuration.view.js, ui/packages/ui/src/main/webapp/js/views/installer/GuestClaims.view.js, ui/packages/ui/src/main/webapp/js/views/installer/InstallerMain.view.js
Reorder installer pages to Welcome -> Setup Type -> Claims -> Settings -> Finish
@kcover @peterhuffer @emmberk 
@shaundmorris
@stustison
Install DDF and verify there are no issues going through the installer.
[DDF-3704](https://codice.atlassian.net/browse/DDF-3704)
=> DDF-3704 Reorder installer pages

platform/osgi/platform-osgi-conditions/src/main/java/org/codice/ddf/condition/BundleNameCondition.java, platform/osgi/platform-osgi-conditions/src/main/java/org/codice/ddf/condition/SignerCondition.java
Adds doPrivileged blocks that will be needed for the next version of Equinox
@tbatie @rzwiefel @SmithJosh 
@coyotesqrl
@stustison …
=> DDF-3297 added doPrivileged blocks for protected operations within the conditions

pom.xml, ui/packages/catalog-ui-search/.nsprc, ui/packages/catalog-ui-search/package.json, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/map.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/openlayers/map.openlayers.js, ui/yarn.lock
Upgrades Openlayers to 4.6.5 
https://github.com/openlayers/openlayers/blob/ca3e11a10b47ba0323b3fbc477ce1d39eb06b26e/changelog/v4.6.0.md
Should help with migrating to OL 5.0 in the future.
I did a search and replace where the old version (3.20.1) and "openlayers" was being used. Could use feedback on if other places need to be upgraded/tested. I didn't change the webjar since that seems to be related to the Standard Search UI and this is focused on Intrigue. I'm not sure if keeping the webjar will still cause an NSP failure.
@djblue @mojogitoverhere  @ricklarsen 
@codice/ui 
@codice/ui 
@pklinef
I did a build and …
=> DDF-3699 Upgraded Openlayers to 4.6.5

platform/osgi/platform-osgi-conditions/src/main/java/org/codice/ddf/condition/BundleNameCondition.java, platform/osgi/platform-osgi-conditions/src/main/java/org/codice/ddf/condition/PrincipalCondition.java, platform/osgi/platform-osgi-conditions/src/main/java/org/codice/ddf/condition/SignerCondition.java, platform/persistence/platform-persistence-core-impl/pom.xml, platform/persistence/platform-persistence-core-impl/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker, platform/solr/solr-factory/src/main/java/org/codice/solr/factory/impl/HttpSolrClientFactory.java, platform/solr/solr-factory/src/main/java/org/codice/solr/factory/impl/SolrClientFactoryImpl.java
Makes classes final so that they cannot be overridden when invoking doPrivileged blocks.
@SmithJosh @blen-desta @paouelle 
@bdeining
@stustison
A full CI run will confirm that unit tests are not impacted (due to mocking) and that no runtime functionality is impacted.
N/A
[DDF-3724](https://codice.atlassian.net/browse/DDF-3724) …
=> DDF-3724 Methods invoking SecurityManager should be final

platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/CipherUtils.java, platform/osgi/platform-osgi-configadmin/src/main/java/org/codice/felix/cm/file/DelegatingPersistenceManager.java, platform/security/common/src/main/java/org/codice/ddf/security/common/Security.java, platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/server/IdpEndpoint.java
Address Cat 1 Fortify Scan findings.
@mackncheesiest @Schachte 
@coyotesqrl
@stustison
Full Build
[DDF-3723](https://codice.atlassian.net/browse/DDF-3723) …
=> DDF-3723 Address Cat 1 Fortify Scan findings

ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-old.hbs, ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-old.less, ui/packages/standard/src/main/webapp/css/searchPage.css
Display coordinate format options after criteria are selected
@BernardIgiri 
@clockard
@jlcsmith
Open the basic search ui and ensure that the coordinate format buttons only appear when appropriate
[DDF-3721](https://codice.atlassian.net/browse/DDF-3721)
=> DDF-3721 Display coordinate format options after criteria are selected

ui/packages/catalog-ui-search/src/main/webapp/js/model/QueryResult.collection.js
Fix sorting when some values are undefined.
@adimka 
@millerw8
Build and install. Ingest some metacards and add a new field (e.g. topic.keyword) to some of them. Sort by keyword, then by title. Verify that when no keyword is defined, the metacards are still sorted by title.
[DDF-3733](https://codice.atlassian.net/browse/DDF-3733)
- ✏️ (Pencil) This comment is a nitpick …
=> DDF-3733 Check if both sort keys are undefined

ui/packages/ace/lib/package.js
Follow on to https://github.com/codice/ddf/pull/3111 to fix build issues
=> DDF-3719 Fixes building on windows

distribution/ddf-common/src/main/resources/security/default.policy
@bakejeyner @blen-desta @brjeter @idperez 
@coyotesqrl
@stustison
[DDF-3713](https://codice.atlassian.net/browse/DDF-3713) …
=> DDF-3713 Add security exceptions for paths retrieved via System.getProperty

ui/packages/catalog-ui-search/src/main/webapp/component/editor/editor.view.js
- The dropdown was receiving the wrong model, causing adding and removing attributes to fail.
@adimka 
@rzwiefel 
Try to add and remove attributes from a metacard and verify it works.
[DDF-3734](https://codice.atlassian.net/browse/DDF-3734)
=> DDF-3734 Fixes issue with adding attributes to metacards

ui/packages/catalog-ui-search/src/main/webapp/component/query-adhoc/query-adhoc.less
Fix for IE Text Scroll Bar in Text View
@adimka @mackncheesiest 
@codice/ui 
@jlcsmith
Build / Install / Inspect Text Template in IE11
[DDF-3736](https://codice.atlassian.net/browse/DDF-3736)
Resolves this ☝️ 
- …
=> DDF-3736 Fix for IE Text Scroll Bar in Text View

catalog/spatial/geocoding/spatial-geocoding-api/src/main/java/org/codice/ddf/spatial/geocoding/GeoEntry.java, catalog/spatial/geocoding/spatial-geocoding-api/src/main/java/org/codice/ddf/spatial/geocoding/GeoEntryAttributes.java, catalog/spatial/geocoding/spatial-geocoding-api/src/main/java/org/codice/ddf/spatial/geocoding/GeoEntryCreator.java, catalog/spatial/geocoding/spatial-geocoding-api/src/main/java/org/codice/ddf/spatial/geocoding/GeoEntryIndexer.java, catalog/spatial/geocoding/spatial-geocoding-create/pom.xml, catalog/spatial/geocoding/spatial-geocoding-create/src/main/java/org/codice/ddf/spatial/geocoding/create/GeoNamesCreator.java, catalog/spatial/geocoding/spatial-geocoding-create/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/spatial/geocoding/spatial-geocoding-create/src/test/java/org/codice/ddf/spatial/geocoding/create/GeoNamesCreatorTest.java, catalog/spatial/geocoding/spatial-geocoding-extract/src/main/java/org/codice/ddf/spatial/geocoding/extract/GeoNamesFileExtractor.java, catalog/spatial/geocoding/spatial-geocoding-extract/src/test/java/org/codice/ddf/spatial/geocoding/extract/GeoNamesFileExtractorTest.java, catalog/spatial/geocoding/spatial-geocoding-offline-catalog/src/main/java/org/codice/ddf/spatial/geocoding/index/GeoNamesCatalogIndexer.java, catalog/spatial/geocoding/spatial-geocoding-offline-catalog/src/main/java/org/codice/ddf/spatial/geocoding/index/GeoNamesLuceneIndexer.java, catalog/spatial/geocoding/spatial-geocoding-offline-catalog/src/test/java/org/codice/ddf/spatial/geocoding/index/GeoNamesCatalogIndexerTest.java, catalog/spatial/geocoding/spatial-geocoding-offline-catalog/src/test/java/org/codice/ddf/spatial/geocoding/index/GeoNamesLuceneIndexerExceptionsTest.java, catalog/spatial/geocoding/spatial-geocoding-offline-catalog/src/test/java/org/codice/ddf/spatial/geocoding/index/GeoNamesLuceneIndexerTest.java, catalog/spatial/spatial-app/pom.xml, catalog/spatial/spatial-app/src/main/resources/features.xml, catalog/spatial/spatial-commands/src/test/java/org/codice/ddf/commands/spatial/gazetteer/GazetteerUpdateCommandTest.java, pom.xml
Fixes the GeoNames file indexer from running on each restart of DDF. Corrects GeoNames to set Country to use 3 character ISO country code instead of 2 to prevent the data from being marked INVALID. Updates to use Codice Country Code converter. Added logic to track which input file the data was imported from. 
@adimka 
@GabrielFabian  
@bdeining
@jlcsmith
Install DDF. 
Enable trace logging for GeoNames indexer: log:set TRACE org.codice.ddf.spatial.geocoding.index
Once GeoNames data import has completed verify that the records in Solr are not marked INVALID.
Restart DDF.
Check Solr to ensure that no additional records have been imported after restart
Remove the …
=> DDF-3716 Fixes for GeoNames indexer running on each start.

distribution/docs/src/main/resources/content/_configuring/default-layout-intrigue.adoc
Adds documentation for Administrators to use the Default Layout UI.
@mcalcote @ahoffer @vinamartin @djblue 
@clockard
@lessarderic
@rzwiefel
@shaundmorris
review content
[DDF-3725](https://codice.atlassian.net/browse/DDF-3725) …
=> DDF-3725 added docs for Default Layout UI

ui/packages/catalog-ui-search/src/main/webapp/component/workspace-interactions/workspace-interactions.hbs
Made the hamburger menu option names more descriptive
@alexaabrd 
@Schachte 
@bdeining
[DDF-3737](https://codice.atlassian.net/browse/DDF-3737) …
=> DDF-3737 Added additional descriptions to hamburger menu on workspace

ui/packages/ace/lib/webpack.config.js
- Fixes issue with Promise being undefined in older browsers
@jlcsmith
@djblue 
@Variadicism 
Verify IE11 works with the changes.
https://github.com/webpack/webpack/issues/4254
=> DDF-3719 Adds babel-polyfill to entry for production

ui/packages/catalog-ui-search/package.json, ui/packages/catalog-ui-search/src/main/webapp/styles/components/jquery-ui.less, ui/yarn.lock
Replaces napa dependency with one from the npm registry and updates jquery-ui-multiselect-widget
@djblue @mojogitoverhere 
@jlcsmith …
=> DDF-3751 Removed napa and updated jquery-ui-multiselect-widget

catalog/spatial/csw/spatial-csw-connectedsource/src/main/resources/OSGI-INF/metatype/metatype.xml, distribution/docs/src/main/resources/content/_tables/Csw_Connected_Source.adoc
fixed misspelled word "metacad" in docs and in metatype.xml file
@clockard
@coyotesqrl
@lessarderic
@rzwiefel
@shaundmorris
check the spelling …
=> Ddf 2824 fixed typo in csw connected source

catalog/core/catalog-core-urlresourcereader/src/main/java/ddf/catalog/resource/impl/URLResourceReader.java, distribution/ddf-common/src/main/resources/security/default.policy
@tbatie @SmithJosh @blen-desta 
@coyotesqrl
@stustison …
=> DDF-3297 updated policy for downstream project compatibility and fixed issue with URL resource reader throwing an exception

ui/packages/catalog-ui-search/src/main/webapp/component/query-time/query-time.view.js
Changed the After and Before labels to From and To within the Between option
@lcrosenbu 
@bakejeyner 
@bdeining
Verify labels are displaying From and To in Between for modify date time
[DDF-3722](https://codice.atlassian.net/browse/DDF-3722) …
=> DDF-3722 Changed labels for Between in modify date range

distribution/docs/src/main/resources/content/_endpoints/csw-endpoint.adoc
Adds missing attribute to table for CSW endpoint.
@clockard
@lessarderic
@rzwiefel
@shaundmorris
content review
- ❗ …
=> DDF-2824 adding missing attribute to table

ui/packages/catalog-ui-search/src/main/webapp/styles/vars.less
Changes default colors of the sea theme
@lcrosenbu 
@alexaabrd 
@bdeining
[DDF-3762](https://codice.atlassian.net/browse/ddf-3762)
old colors: …
=> DDF-3762 Improved color scheme of sea theme

pom.xml
Allow RHEL Jenkins using Maven 3.5.0 to successfully build DDF.  But we will need to verify that it doesn't break in other environment (especially Windows since I don't have Windows)
@jlcsmith @AzGoalie @ricklarsen 
https://github.com/orgs/codice/teams/build
https://github.com/orgs/codice/teams/continuous-integration
@millerw8
Verified that it build in Windows / Mac / Linux
It failed in RHEL when the version is at 1.7.26
Source of reference: https://github.com/asciidoctor/asciidoctorj/issues/586
[]https://codice.atlassian.net/browse/DDF-3764 …
=> DDF-3764 Upgrade jruby version for doc build for RHEL

features/apps/pom.xml, features/branding/pom.xml, features/camel/pom.xml, features/karaf/pom.xml, features/security/pom.xml, features/utilities/pom.xml, libs/test-common/src/main/java/org/codice/ddf/test/common/features/FeatureUtilities.java
Completes the pom dependencies from #2896.
@oconnormi 
@tbatie 
@Lambeaux
@ryeats
@codice/test
@rzwiefel 
@figliold
@pklinef
All tests pass and the install profiles work …
=> DDF-3739 Updated poms to include ddf feature dependencies

platform/security/handler/security-handler-saml/src/main/java/org/codice/ddf/security/handler/saml/SAMLAssertionHandler.java
@troymohl 
@bdeining
@millerw8
@pklinef
@stustison …
=> DDF-3757 audit any unsolicited session ID requests

distribution/docs/src/main/resources/content/_configuring/configuring-fanout-proxy.adoc
Updates content on Configuring a Fanout Proxy
@clockard
@coyotesqrl
@lessarderic
@rzwiefel
@shaundmorris …
=> DDF-2824 Corrections to fanout proxy docs

distribution/docs/src/main/resources/content/_configuring/uploading-and-editing.adoc
Adds a section to the docs explaining how to allow or revoke ingesting
and editing metadata in intrigue.
@clockard
[DDF-3727](https://codice.atlassian.net/browse/DDF-3727)
=> DDF-3727 Add ingest/editing configuration to docs

ui/packages/catalog-ui-search/src/main/webapp/component/query-advanced/query-custom/query-custom.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/query-settings/query-settings.hbs, ui/packages/catalog-ui-search/src/main/webapp/component/query-settings/query-settings.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/result-form/result-form.js, ui/packages/catalog-ui-search/src/main/webapp/component/search-form-interactions/search-form-interactions.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/search-form/search-form-tab-container.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/search-form/search-form.collection.js, ui/packages/catalog-ui-search/src/main/webapp/component/search-form/search-form.js, ui/packages/catalog-ui-search/src/main/webapp/component/search-form/search-form.view.js, ui/packages/catalog-ui-search/src/main/webapp/js/model/Query.js, ui/packages/catalog-ui-search/src/main/webapp/js/model/QueryResponse.js
This PR adds support for Query Result Forms to be selected inside of the Query Forms, and tailors the result views to only show attributes specified on the Query Result Form.  Also fixes a bug when there is no template specified in user preferences.
~~STILL TODO:  Tailor the Inspector View to only show Query Result Form attributes~~
@adimka @mackncheesiest 
@jlcsmith
Build / Install / Set up `etc/forms` and verify result forms are shown and can be selected / Verify Table 
View changes based on Query Form
[DDF-3747](https://codice.atlassian.net/browse/DDF-3747) …
=> DDF-3747 Adds Result Form Support to Search Forms 

distribution/docs/src/main/resources/content/_endpoints/csw-endpoint.adoc
Adds a note to the CSW endpoint docs to clarify that responses are samples that may differ from what is seen on a running system. 
@mcalcote @vinamartin @ahoffer @emanns95 
@clockard
@kcwire
@rzwiefel
@shaundmorris
content change only …
=> DDF-2824 added note for sample responses to endpoint docs

ui/packages/catalog-ui-search/src/main/webapp/component/alert-settings/alert-settings.hbs, ui/packages/catalog-ui-search/src/main/webapp/component/alert-settings/alert-settings.less, ui/packages/catalog-ui-search/src/main/webapp/component/theme-settings/theme-settings.less
Rework verbiage and styling for user's Notifications Setting
@lcrosenbu 
@idperez 
@djblue 
@Lambeaux 
@bdeining
N/A
*Note: that the other settings are styled this way (aligned to the left with smaller text)*
[DDF-3779](https://codice.atlassian.net/browse/DDF-3779)
*Old:*
*New:* …
=> DDF-3779 Rework verbiage and styling for user's Notifications Setting

ui/packages/catalog-ui-search/src/main/webapp/component/dropdown/layers/dropdown.layers.hbs, ui/packages/catalog-ui-search/src/main/webapp/component/dropdown/map-settings/dropdown.map-settings.hbs, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/cesium/cesium.less, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/map.less, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/map.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/openlayers/openlayers.less
Updated Cesium toolbar buttons to be consistent with other buttons across the ui
@lcrosenbu 
@idperez 
@Lambeaux 
@adimka 
@djblue 
@Schachte 
@bdeining
[DDF-3778](https://codice.atlassian.net/browse/DDF-3778)
*Old:*
*New:* …
=> DDF-3778 Update Map toolbar buttons to be consistent with other buttons across the ui

ui/packages/ace/.nsprc, ui/packages/ace/package.json, ui/packages/admin-metrics-ui/package.json, ui/packages/admin-security-certificate-ui/package.json, ui/packages/admin-security-ui/package.json, ui/packages/catalog-admin-module-sources/package.json, ui/packages/geowebcache-admin-plugin/package.json, ui/packages/platform-error-impl/package.json, ui/packages/registry-admin-local-ui/package.json, ui/packages/registry-admin-remote-ui/package.json, ui/packages/resourcemanagement-querymonitor-ui/package.json, ui/packages/resourcemanagement-usage-ui/package.json, ui/packages/security-handler-guest/package.json, ui/packages/security-servlet-logout/package.json, ui/packages/spatial-geocoding-admin-module/package.json, ui/packages/standard/package.json, ui/packages/ui/package.json, ui/yarn.lock
Upgrade Express from 4.14.0 to 4.16.3 
Upgrade Request from 2.79.0 to 2.85.0
Upgrade Phantomjs-prebuilt from 2.1.14 to 2.1.16
@djblue @andrewkfiedler 
@codice/ui
@clockard 
@bdeining
Manual test of UIs upgraded
NSP check will pass after upgrades are merged
[DDF-3707](https://codice.atlassian.net/browse/DDF-3707) …
=> DDF-3707 npm upgrades Express, Request, Phantomjs-prebuilt

distribution/docs/src/main/resources/content/_running/subscription-commands.adoc
Corrected console command docs to remove typo
@mcalcote @ahoffer @garrettfreibott 
@clockard
@coyotesqrl
@lessarderic
@rzwiefel
@shaundmorris
- ❗ …
=> DDF-2824 updated typo in commands docs

distribution/ddf-common/src/main/resources/bin/setenv, distribution/ddf-common/src/main/resources/bin/setenv.bat, distribution/docs/src/main/resources/content/_installing/installing-intro.adoc, distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/AbstractIntegrationTest.java
@rzwiefel @coyotesqrl @lessarderic @oconnormi 
@pklinef
@stustison …
=>  DDF-3796 increases DDFs default memory settings to 6 gb for standard runtime and also itests

catalog/core/catalog-core-directorymonitor/pom.xml, catalog/core/catalog-core-directorymonitor/src/test/java/org/codice/ddf/catalog/content/monitor/ContentDirectoryMonitorIT.java
Added missing depdency and addressed other race conditions.
@oconnormi 
@coyotesqrl
Full build on Docker swarm.
https://github.com/codice/ddf/pull/3148
[DDF-3753](https://codice.atlassian.net/browse/DDF-3753) …
=> DDF-3753 Re-enable CDM component tests

distribution/docs/src/main/resources/content/_appReferences/mg-admin.adoc, distribution/docs/src/main/resources/content/_appReferences/mg-broker-app.adoc, distribution/docs/src/main/resources/content/_appReferences/mg-catalog.adoc, distribution/docs/src/main/resources/content/_appReferences/mg-geowebcache.adoc, distribution/docs/src/main/resources/content/_appReferences/mg-platform.adoc, distribution/docs/src/main/resources/content/_appReferences/mg-registry.adoc, distribution/docs/src/main/resources/content/_appReferences/mg-resource-mgmt.adoc, distribution/docs/src/main/resources/content/_appReferences/mg-security.adoc, distribution/docs/src/main/resources/content/_appReferences/mg-solr.adoc, distribution/docs/src/main/resources/content/_appReferences/mg-spatial.adoc, distribution/docs/src/main/resources/content/_appReferences/mg-ui.adoc, distribution/docs/src/main/resources/content/_transformers/registry-xformer.adoc
Updates documentation for application reference sections.
@mcalcote @ahoffer @garrettfreibott 
@lessarderic
@rzwiefel
@shaundmorris …
=> DDF-2824 updates to feature installation docs

ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/map.view.js
Uses the [SVGInjector](https://github.com/iconic/SVGInjector) dependency to inject the map-marker.svg
@lcrosenbu 
@idperez 
[DDF-3760](https://codice.atlassian.net/browse/DDF-3760) …
=> DDF-3760 Changed 2D/3D maps' Home icon

platform/security/sts/security-sts-realm/src/main/java/ddf/security/realm/sts/AbstractStsRealm.java
Ensures the claim types we request from claims handlers are all unique.
@stustison
1. Install DDF using the minimal profile
2. Login to /admin. In the Web Context Policy Manager, change the auth type for /admin to SAML|BASIC:
```
/admin=SAML|BASIC
```
3. From the Karaf console, turn up the log level for the Login Filter to TRACE:
```
> log:set TRACE org.codice.ddf.security.filter.login
```
4. Logout
5. Log back into /admin. Find the SAML assertion in the log and verify that there are no duplicate Attribute elements in the AttributeStatement, as shown in the image below.
NOTE: Attributes with the same Name and NameFormat but different values are expected.
The …
=> DDF-3797 Filter duplicate claim types from SAML assertions

distribution/docs/src/main/resources/content/_configuring/configuring-idp.adoc, platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/binding/api/Validator.java, platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/binding/api/impl/ValidatorImpl.java, platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/binding/redirect/RedirectValidator.java, platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/binding/soap/SoapValidator.java, platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/server/IdpEndpoint.java, platform/security/idp/security-idp-server/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/security/idp/security-idp-server/src/main/resources/OSGI-INF/metatype/metatype.xml, platform/security/idp/security-idp-server/src/test/java/org/codice/ddf/security/idp/server/IdpEndpointTest.java
Adds a configuration option to the admin console (`Admin Console -> Security -> Configuration -> IdP Server -> Limit RelayStates to 80 Bytes`) to deny SAML messages with a RelayState greater than 80 bytes. From SAML Core Section 3.4.3, 3.5.3, 3.6.3:
```
The [RelayState] value MUST NOT exceed 80 bytes in length
```
@blen-desta 
@brjeter 
@SmithJosh 
@coyotesqrl
@stustison
> "Valid Request" and "Invalid Request" refer to the contents in [requests.txt](https://github.com/codice/ddf/files/1948762/requests.txt)
1. Install DDF, minimum profile recommended.
2. Log into the Admin Console.
3. Confirm that `Limit RelayStates to 80 Bytes` is enabled by default: `Admin Console -> Security -> Configuration -> IdP Server -> Limit RelayStates to 80 Bytes`.
4. In the same configuration window, disable …
=> DDF-3795 Add an Option to Prevent Relay States Greater Than 80 Bytes

distribution/ddf-common/src/main/resources/security/default.policy
Added permissions needed to start and use the Felix Web Console.
@rymach 
@SmithJosh 
@bdeining
@stustison
Start the `webconsole` feature.  Verify that https://localhost:8993/system/console/ works and that all pages in the menu work. …
=> DDF-3297 Update policy for Felix Webconsole

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/forms/SearchFormsApplication.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/MetacardApplication.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/security/Constants.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/security/ShareableMetacardImpl.java, ui/packages/catalog-ui-search/src/main/webapp/component/search-form-interactions/search-form-interactions.less, ui/packages/catalog-ui-search/src/main/webapp/component/search-form-interactions/search-form-interactions.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/search-form/search-form.collection.js, ui/packages/catalog-ui-search/src/main/webapp/component/search-form/search-form.view.js
- Disables sharing capabilities on system loaded templates on the UI
- Adds validation on the backend to ensure system templates cannot be shared
- Improves validation on the DELETE endpoint for deleting templates to only those who created the template originally
@bdeining 
@middlets719 
@adimka 
@bdeining 
- Build DDF
- Ensure that ellipses don't show up on frontend for modifying system templates
- Ensure that system templates cannot be deleted in any way
[DDF-3801](https://codice.atlassian.net/browse/DDF-3801) …
=> DDF-3801 Disable Sharing Capabilities of System Loaded Templates (Result and Search)

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/ws/SecureWebSocketServlet.java, catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/blueprint/blueprint.xml
@SmithJosh @djblue @pklinef 
@rzwiefel
@stustison …
=> DDF-3628 changed websocket servlet to pull subject off request instead of initial handler result

platform/landing-page/src/main/resources/index.handlebars, ui/README.md, ui/packages/catalog-admin-module-sources/src/main/webapp/less/styles.less, ui/packages/catalog-admin-module-sources/src/main/webapp/templates/sourceList.handlebars, ui/packages/catalog-admin-module-sources/src/main/webapp/templates/sourceRow.handlebars, ui/packages/catalog-ui-search/src/main/webapp/component/dropdown/dropdown.companion.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/dropdown/query-src/dropdown.query-src.less, ui/packages/catalog-ui-search/src/main/webapp/component/dropdown/query-src/dropdown.query-src.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/query-src/query-src.hbs, ui/packages/catalog-ui-search/src/main/webapp/component/query-src/query-src.less, ui/packages/catalog-ui-search/src/main/webapp/component/source-item/source-item.less, ui/packages/ui/src/main/webapp/components/configuration-item/configuration-item.less, ui/packages/ui/src/main/webapp/less/common/tables.less, ui/packages/ui/src/main/webapp/less/configuration/style.less
DDF-3770 Handling long source names in UI
Handles long source names on landing page, Admin Console Sources tab, Admin Console Configurations, Catalog Search queries and sources endpoint
@emanns95 @tbatie @emmberk 
@bdeining 
Add source with long source name and ensure text is properly handled on landing page, Admin Console Sources Tab (including edit and delete modals), Admin Console Configurations, Catalog Search UI queries and sources endpoint
[DDF-3770](https://codice.atlassian.net/browse/DDF-3770)
[screenshots.zip](https://github.com/codice/ddf/files/1925196/screenshots.zip)
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/ …
=> DDF-3770 Handling long source names in UI

distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalog.java
@AzGoalie 
@emanns95 
@rzwiefel
[DDF-3827](https://codice.atlassian.net/browse/DDF-3827)
=> DDF-3827 Mark testDefaultValuesCreate itest as unstable

Documentation-versions.html
- adds 2.11.6 to Previous Versions table
- fixed dates on previous versions to be formatted YYYY-MM-DD
=> DDF-2824 added 2.11.6 to previous version table

catalog/rest/catalog-rest-endpoint/pom.xml, catalog/rest/catalog-rest-endpoint/src/test/java/org/codice/ddf/endpoints/rest/RestEndpointIT.java, libs/libs-pomfix/test/resources/descriptors/pom.xml, libs/libs-pomfix/test/test.js
Removes dependencies on old feature files that have been moved or rewritten
@emanns95 
@figliold 
@lessarderic
@pklinef
Full CI build passes …
=> DDF-3739: Remove references to stale feature files

CODEOWNERS
Adds whitelist files under @codice/whitelist 
=> Added whitelist files

catalog/catalog-app/src/main/resources/features.xml, catalog/confluence/catalog-confluence-source/pom.xml, catalog/core/catalog-core-validationparser/pom.xml, catalog/transformer/catalog-transformer-geojson-input/pom.xml, catalog/transformer/catalog-transformer-propertyjson-metacard/pom.xml, catalog/ui/catalog-ui-search/pom.xml, catalog/ui/search-ui-app/src/main/resources/features.xml, catalog/ui/search-ui/standard/pom.xml, distribution/test/itests/test-itests-ddf/pom.xml, distribution/test/itests/test-itests-dependencies-app/src/main/filtered-resources/features.xml, features/migration/src/main/feature/feature.xml, features/security/src/main/feature/feature.xml, features/utilities/src/main/feature/feature.xml, platform/admin/admin-app/src/main/resources/features.xml, platform/admin/core/admin-core-appservice/pom.xml, platform/admin/core/admin-core-impl/pom.xml, platform/error/platform-error-impl/pom.xml, platform/migration/platform-migration/pom.xml, platform/security/idp/security-idp-server/pom.xml, platform/security/servlet/security-servlet-logout/pom.xml, pom.xml
Changes boon version to use ${boon.version} instead of hard coding version number (currently on version 0.34). Removes embedded boon dependencies and instead starts the boon bundle.
@mcalcote 
@ahoffer 
@emanns95 
@rzwiefel
@figliold 
CI build
[DDF-3814](https://codice.atlassian.net/browse/DDF-3814) …
=> DDF-3814 Upgrade all projects to use latest 0.34 boon library

distribution/ddf-common/src/main/resources/security/default.policy, distribution/test/itests/test-itests-common/pom.xml, distribution/test/itests/test-itests-common/src/main/resources/TestSpatial/xml/WFS_11_GetCapabilities.xml, distribution/test/itests/test-itests-common/src/main/resources/TestSpatial/xml/WFS_11_sfRoads.xml, distribution/test/itests/test-itests-common/src/main/resources/TestSpatial/xml/WFS_11_sfRoadsFeatureType.xsd, distribution/test/itests/test-itests-common/src/main/resources/TestSpatial/xml/sfRoad1.xml, distribution/test/itests/test-itests-common/src/main/resources/TestSpatial/xml/sfRoad2.xml, distribution/test/itests/test-itests-common/src/main/resources/TestSpatial/xml/sfRoad3.xml, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestSpatial.java
Adds WFS 1.1.0 Source ITests
@mojogitoverhere @gordocanchola @GabrielFabian @dcruver 
https://github.com/orgs/codice/teams/test
@jlcsmith  …
=> DDF-3839 Added WFS 1.1.0 Source ITests

distribution/ddf/pom.xml, distribution/ddf/src/main/filtered-resources/etc/org.apache.karaf.features.cfg, features/apps/pom.xml, features/apps/src/main/feature/feature.xml, ui/packages/ace/lib/webpack.config.js, ui/packages/catalog-ui-search/src/main/webapp/component/input/number/input-number.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/input/radio/input-radio.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/layer-item/layer-item.hbs, ui/packages/catalog-ui-search/src/main/webapp/component/layer-item/layer-item.less, ui/packages/catalog-ui-search/src/main/webapp/component/layer-item/layer-item.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/metacard-interactions/metacard-interactions.hbs, ui/packages/catalog-ui-search/src/main/webapp/component/metacard-interactions/metacard-interactions.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/property/property.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/query-settings/query-settings.hbs, ui/packages/catalog-ui-search/src/main/webapp/component/query-settings/query-settings.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/radio/radio.hbs, ui/packages/catalog-ui-search/src/main/webapp/component/user-settings/user-settings.hbs, ui/packages/catalog-ui-search/src/main/webapp/component/user-settings/user-settings.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/cesium/map.cesium.js, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/openlayers/map.openlayers.js, ui/packages/catalog-ui-search/src/main/webapp/js/controllers/common.layerCollection.controller.js, ui/packages/catalog-ui-search/src/main/webapp/js/controllers/ol.layerCollection.controller.js, ui/packages/catalog-ui-search/src/main/webapp/js/model/User.js, ui/packages/catalog-ui-search/src/main/webapp/plugins/metacard-interactions.js, ui/packages/catalog-ui-search/src/main/webapp/plugins/query-settings.js, ui/packages/catalog-ui-search/src/main/webapp/plugins/user-settings.js
- Fixes ace relative module resolution when using symlinks
- Adds remove button to layer-item component if a layer is removable
- Updates map component to listen to mapLayer collection on add/remove
- Updates WMT layer type to use the first available layer if none is provided
- Warns in the console if not provided
- Warns in the console if provided but not found
- Prevents removal of user removable layers when syncing with admin imagery providers
- Adds UI as a distribution boot feature
@Schachte
@adimka 
@codice/ui 
@bdeining
- Full build of the ui directory
- Quick build of everything else
To test user removable map layers:
- In the admin console, add two map layers one with the `userRemovable` key and another without
- Open Intrigue and verify that the …
=> DDF-3719 Various UI extensibility changes

Jenkinsfile
Multithreaded builds have proven to be inconsistent and unstable. This change will improve stability by reverting to single-threaded builds.
@oconnormi @LinkMJB @clockard @mackncheesiest @shaundmorris 
@codice/build 
[DDF-3847](https://codice.atlassian.net/browse/DDF-3847) …
=> DDF-3847 Jenkinsfile single-threaded build update

Jenkinsfile
Multithreaded builds have proven to be inconsistent and unstable. This change will improve stability by reverting to single-threaded builds.
@oconnormi @LinkMJB @clockard @mackncheesiest @shaundmorris @brendan-hofmann @vinamartin 
@codice/build 
[DDF-3847](https://codice.atlassian.net/browse/DDF-3847) …
=> 2.11.X DDF-3847 Jenkinsfile single-threaded build update

ui/packages/catalog-ui-search/src/main/webapp/component/workspace-lists/workspace-lists.view.js
Fixes a bug introduced by #3112 where lists with elements in them do not render.
@codice/ui 
@bdeining
[DDF-3706](https://codice.atlassian.net/browse/DDF-3706)
- ❓ (Question …
=> DDF-3706 Fix list render bug

catalog/spatial/geowebcache/README.md, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/util/EndpointUtil.java, catalog/ui/search-ui-app/src/main/resources/features.xml, distribution/ddf-common/src/main/resources-filtered/etc/application-definitions/search-ui.json, distribution/docs/src/main/resources/content/_appReferences/mg-ui.adoc, distribution/docs/src/main/resources/content/_running/troubleshooting-ui.adoc, platform/admin/modules/admin-modules-application/src/test/resources/application-service-array.json, pom.xml
Adjust the name of the Standard Search UI App to more accurately reflect the features it contains.
@vinamartin 
@djblue 
@tbatie …
=> DDF-2824 Clean up Search UI terminology

platform/security/common/src/main/java/ddf/security/samlp/impl/SamlValidator.java, platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/server/IdpEndpoint.java
- Added URL encoding to relay state when validating and creating logout request signatures
- Made sure the destination on the response is the correct binding URL
@bakejeyner 
@brjeter 
@coyotesqrl 
@stustison 
- Successful login and logout 
- Running the SAML Conformance Test Kit against it
The Relay State has to be URL encoded when creating and validating signatures according to the Binding Spec.
> To construct the signature, a string consisting of the concatenation of the RelayState 
> (if present), SigAlg, and SAMLRequest (or SAMLResponse) query string parameters 
> (**each one URLencoded**)
> is constructed in one of the following ways (ordered as below):
> `SAMLRequest=value&RelayState=value&SigAlg=value`
> …
=> DDF-3696: Minor Logout Fixes

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/history/Historian.java, catalog/core/catalog-core-standardframework/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/core/catalog-core-standardframework/src/main/resources/OSGI-INF/blueprint/delegate-operators.xml, catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/history/HistorianTest.java, catalog/security/catalog-security-plugin/src/main/java/ddf/catalog/security/plugin/SecurityPlugin.java, catalog/security/catalog-security-plugin/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/security/catalog-security-plugin/src/test/java/ddf/catalog/security/plugin/SecurityPluginTest.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/MetacardApplication.java, catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/blueprint/blueprint.xml
Removes dependency on user accounts having email addresses.
@middlets719 
@jlcsmith 
@stustison
User accounts may not always have an associated email address. This removes the dependency on email address and also cleans up some error reporting in the UI.
[DDF-3840](https://codice.atlassian.net/browse/DDF-3840) …
=> DDF-3840 Remove dependency on email address for user accounts

catalog/core/catalog-core-urlresourcereader/pom.xml
Removed the ddf.catalog.resource.impl export from the catalog-core-urlresourcereader bundle.
@ahoffer 
@blen-desta 
@figliold
@shaundmorris
Full build, start DDF and make sure products can be downloaded.
[DDF-3854](https://codice.atlassian.net/browse/DDF-3854) …
=> DDF-3854 Removed ddf.catalog.resource.impl from exported package list

distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestSingleSignOn.java
Fixes issue with missing rule in this commit: https://github.com/codice/ddf/pull/3261
@lessarderic @rzwiefel 
@Bdthomson @LinkMJB
=> DDF-3848 Adds missing rule annotation to skip tests

ui/packages/catalog-ui-search/src/main/webapp/component/search-form/search-form.collection.js
Fixed UI bug with templates
@Lambeaux @adimka @mackncheesiest 
@jlcsmith
Build / Unzip / Copy some forms into `etc/form` / Install / Verify System Forms are shown
[DDF-3672](https://codice.atlassian.net/browse/DDF-3672) …
=> DDF-3672 Fixed UI bug with templates

ui/packages/catalog-ui-search/package.json, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/openlayers/map.openlayers.js, ui/packages/catalog-ui-search/src/main/webapp/js/Common.js, ui/packages/catalog-ui-search/src/main/webapp/js/Common.spec.js, ui/packages/catalog-ui-search/src/main/webapp/js/OpenLayersGeometryUtils.js, ui/packages/catalog-ui-search/src/main/webapp/js/OpenLayersGeometryUtils.spec.js, ui/packages/catalog-ui-search/src/main/webapp/js/widgets/openlayers.bbox.js, ui/packages/catalog-ui-search/src/main/webapp/js/widgets/openlayers.circle.js, ui/packages/catalog-ui-search/src/main/webapp/js/widgets/openlayers.line.js, ui/packages/catalog-ui-search/src/main/webapp/js/widgets/openlayers.polygon.js, ui/yarn.lock
For the 2D map I made the following changes:
1. Limited zoom out.
2. Wrapped coodinates to valid ranges from all search geometery on the draw:end event.
@rymach @AzGoalie @gordocanchola @GabrielFabian 
@bdeining 
@jlcsmith
The user should:
1. Zoom out and scroll far to the left or the right.
2. Draw a search geo of type line, polygon, bounding box, or point radius.
3. Run the search.
4. Edit the search and verify that none of the longitude coordinates are out of the range
of -180 to 180 and none of the latitude coordinates are out of the range of -90 to 90.
5. Repeat steps 1-4 for each of the search geometry types.
[DDFUI-50](https://codice.atlassian.net/browse/DDFUI-50)
Please see [Notes …
=> DDF-50 Fixing bug where search geos on 2D map can return invalid coordinates

catalog/opensearch/catalog-opensearch-source/src/main/java/org/codice/ddf/opensearch/source/OpenSearchSource.java, catalog/opensearch/catalog-opensearch-source/src/test/groovy/org/codice/ddf/opensearch/source/OpenSearchSourceSpec.groovy
Fixes automatic injection of wild card. Wild card will now only be injected if there are no other parameters 
@Schachte @mojogitoverhere 
@bdeining
@jlcsmith
1. Run a quick build 
2. once installed, run  <log:set DEBUG org.apache.cxf>
3. Configure an opensearch source 
4. Run a search with no parameters 
5. Ensure the output still has the wild card parameter in the outputted URL
6. Add parameters to the search, Verify wild card is not in the outputted URL and the query is still performed correctly. 
DDF-3856 …
=> DDF-3856 Fix automatic injection of wild card

catalog/opensearch/catalog-opensearch-source/src/test/java/org/codice/ddf/opensearch/source/OpenSearchSourceTest.java, catalog/spatial/kml/spatial-kml-util/src/test/java/org/codice/ddf/spatial/kml/util/KmlMarshallerTest.java, catalog/spatial/kml/spatial-kml-util/src/test/java/org/codice/ddf/spatial/kml/util/KmlTransformationsTest.java, catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/forms/api/FlatFilterBuilderTest.java, catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/metacard/workspace/transformations/EmbeddedListMetacardsHandlerTest.java, catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/metacard/workspace/transformer/WorkspaceTransformerTest.java, catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/security/ShareableMetacardImplTest.java, catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/security/ShareableMetacardSharingPolicyPluginTest.java, features/install-profiles/src/test/java/org/codice/ddf/features/profiles/test/ITInstallProfilesFeatures.java, pom.xml
Re-enables scans across test directories.
@Variadicism 
@ahoffer 
@bdeining
@rzwiefel
This is build-time only. A successful CI run (not even including integration tests) will suffice.
For manual testing, breaking something in a test source file, e.g. removing the file header from a JUnit class, and verifying that the compilation fails is sufficient.
N/A
[DDF-3868](https://codice.atlassian.net/browse/DDF-3868) …
=> DDF-3868 Include test directories in checkstyle scans.

distribution/docs/src/main/resources/content/_installing/initial-startup.adoc, distribution/docs/src/main/resources/content/_quickstart/quickstart-ingesting.adoc
makes minor fixes to quick start installation and standard installation instruction steps.
@mcalcote @ahoffer @austinsteffes @rzwiefel @garrettfreibott @lessarderic @shaundmorris 
@lessarderic
@rzwiefel
@shaundmorris
- builds successfully …
=> DDF-2824 fixes for quickstart and installing docs

dependency-check-maven-config.xml
Temporarily suppresses CVE-2018-1335 until geotools has been upgraded.
@coyotesqrl
@stustison
Successful OWASP scan.
[DDF-3871](https://codice.atlassian.net/browse/DDF-3871) …
=> DDF-3871 - Update Geotools to latest version

ui/packages/ace/package.json, ui/packages/catalog-ui-search/package.json, ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-old.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/map.view.js, ui/packages/catalog-ui-search/src/main/webapp/js/CQLUtils.js, ui/packages/catalog-ui-search/src/main/webapp/js/CQLUtils.spec.js, ui/yarn.lock
See title. Also did some minor file cleanup by using the `require` syntax for imports instead of `define` and adds unit tests for CQLUtils.
@AzGoalie  @djblue @BernardIgiri @GabrielFabian 
@jlcsmith
Run a keyword search using a location that contains a multipolygon like the US. Verify the outgoing CQL contains the correct multipolygon (each polygon within it should be surrounded by two sets of parenthesis)
[DDF-3852](https://codice.atlassian.net/browse/DDF-3852) …
=>  DDF-3852 Fix multipolygon CQL serialization
