codice/ddf

catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/ContentDirectoryMonitor.java, catalog/core/catalog-core-directorymonitor/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/core/catalog-core-directorymonitor/src/main/resources/OSGI-INF/metatype/metatype.xml, catalog/core/catalog-core-directorymonitor/src/test/java/org/codice/ddf/catalog/content/monitor/ContentDirectoryMonitorTest.java, distribution/docs/src/main/resources/_contents/_resources/content-directory-monitor-contents.adoc
This PR fixes an issue where files were being ingested prematurely by the CDM during slow copies, and increases the CDM readLockInterval to a more reasonable number due to user feedback.  Additionally, a readLockTimeout was added that is 2 * the readLockCheckInterval as per Apache Camel guidelines. 
@Lambeaux 
@jlcsmith
@kcwire
Build / Install / Configure CDM / Copy Files to directory (large and small) / Observe proper behavior
[DDF-2865](https://codice.atlassian.net/browse/DDF-2865)
=> DDF-2865 Fixed CDM handling of empty files and increased the default interval to a more reasonable number

catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/ContentDirectoryMonitor.java, catalog/core/catalog-core-directorymonitor/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/core/catalog-core-directorymonitor/src/main/resources/OSGI-INF/metatype/metatype.xml, catalog/core/catalog-core-directorymonitor/src/test/java/org/codice/ddf/catalog/content/monitor/ContentDirectoryMonitorTest.java, distribution/docs/src/main/resources/_contents/_resources/content-directory-monitor-contents.adoc
This PR fixes an issue where files were being ingested prematurely by the CDM during slow copies, and increases the CDM readLockInterval to a more reasonable number due to user feedback.  Additionally, a readLockTimeout was added that is 2 * the readLockCheckInterval as per Apache Camel guidelines. 
@Lambeaux 
@jlcsmith
@kcwire
Build / Install / Configure CDM / Copy Files to directory (large and small) / Observe proper behavior
[DDF-2865](https://codice.atlassian.net/browse/DDF-2865)
=> (2.10.x) DDF-2865 Fixed CDM handling of empty files and increased the default interval to a more reasonable number

catalog/ui/catalog-ui-search/src/main/webapp/js/controllers/cesium.layerCollection.controller.js, catalog/ui/catalog-ui-search/src/main/webapp/js/controllers/ol.layerCollection.controller.js
This PR adds WMTS support for OpenLayers.  It uses the `optionsFromCapabilities` functionality provided by OpenLayers to dynamically create the proper options and TileGrid for the layer.
@djblue 
@jlcsmith
Build / Install / Configure Catalog UI Imagery Provider with a WMTS layer / Verify layer is positioned properly in both OpenLayers and Cesium.
Sample layer : http://suite.opengeo.org/geoserver/gwc/service/wmts
`[{"type": "WMT","url": "http://suite.opengeo.org/geoserver/gwc/service/wmts", "layer" : "opengeo:countries", "style" : "", "format" : "image/jpeg", "tileMatrixSetID": "EPSG:4326", "tileMatrixLabels" : ['EPSG:4326:0', 'EPSG:4326:1', 'EPSG:4326:2', 'EPSG:4326:3', 'EPSG:4326:4', 'EPSG:4326:5', 'EPSG:4326:6', 'EPSG:4326:7', 'EPSG:4326:8', …
=> DDF-2512 Added WMTS support to OpenLayers

distribution/ddf-common/src/main/resources/common-bin.xml
Combined Doc and Documentation folders into a single folder
Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged)?
@clockard @mcalcote @vinamartin @emmberk
Select at least one member from relevant component team(s) from below (at least one component team member needs to approve the PR).
@ricklarsen
Choose 2 committers to review/merge the PR (please choose ONLY two committers from below, delete the rest).
@figliold
@pklinef
Build the distro using a build profile that includes documentation (mvn -P release) and ensure that all documentation and javadocs are in the documentation folder.
What are …
=> DDF-2829 Combined Doc and Documentation folders into a single folder

pom.xml
Adds the `gitflow-incremental-builder` build extension to the root `pom.xml` to support local and PR incremental builds.
@oconnormi 
@LinkMJB 
@coyotesqrl
@shaundmorris
1. Run `mvn clean install` and make sure a normal build is executed.
1. Make a local change to a source file, run `mvn -Dgib.enaled=true clean install` and make sure only the module that was changed and all its dependent modules are built
Back-port of https://github.com/codice/ddf/pull/1748
[DDF-2843](https://codice.atlassian.net/browse/DDF-2843)
=> DDF-2843 [2.10.x]: Add incremental builder extension to speed up PR builds

distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/annotations/PaxExamRule.java, distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/utils/LoggingUtils.java, distribution/test/itests/test-itests-common/src/test/java/ddf/common/test/PaxExamRuleTest.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalog.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalogSearchUi.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestEmbeddedSolr.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFanout.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFederation.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFtp.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestRegistry.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestSpatial.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestApplicationService.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestConfiguration.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestPlatform.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestSecurity.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestSingleSignOn.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestSolrCommands.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/admin/ConfigurationFilesPoller.java, platform/migration/platform-migration/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/admin/ConfigurationFilesPollerTest.java
Replace nio with commons-io's file watcher, and replace the one second sleep with a poll for the file size to become stable.
These changes should mitigate itest stability problems in CI environments that are prone to IOWait spikes.
Also includes some improvements to itest logging that were needed to debug this solution anyways.
@ahoffer @clockard 
@coyotesqrl
@lessarderic
[DDF-2869](https://codice.atlassian.net/browse/DDF-2869)
=> DDF-2869 Rework ConfigurationFilesPoller to be more reliable

catalog/ui/catalog-ui-search/src/main/webapp/js/model/Workspace.js
- This listener got dropped at some point, so query changes won't be properly detected without this.  The logic to ignore query changes to results is already in though.
@rzwiefel 
@djblue 
@pklinef
Make a change to a query and verify the workspace change icon appears.  Run the query and verify it does not appear.  
The logic to ignore results changes was already in, but at some point the listener got accidentally removed.
https://codice.atlassian.net/browse/DDF-2847
=> DDF-2874 Add query change listener for workspace change detection

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/config/ConfigurationApplication.java, catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.config.xml, catalog/ui/search-ui-app/src/main/resources/etc/org.codice.ddf.catalog.ui.config, catalog/ui/search-ui/standard/src/main/java/org/codice/ddf/ui/searchui/standard/properties/ConfigurationStore.java, catalog/ui/search-ui/standard/src/main/resources/OSGI-INF/metatype/metatype.xml, distribution/docs/src/main/resources/_contents/_tables/org.codice.ddf.catalog.ui.config-table-contents.adoc
When using default layers with the 2D Map, geometries appear incorrectly positioned. This change utilizes the EPSG:4326 projection for the single image layer so that the metacard locations appear consistent across both the 3D Globe and 2D Map.
@emmberk @clockard @vinamartin
[Docs](https://github.com/orgs/codice/teams/docs) @ricklarsen 
[UI](https://github.com/orgs/codice/teams/ui) @brianfelix 
@pklinef
Install DDF, ingest a product with location information, then confirm the location of the metacard in both the 3D Globe and 2D Map in both the Catalog UI as well as the Standard UI.
To access the 2D Map on the standard UI, navigate to `https://localhost:8993/search/standard/?map=2d`
To access the 2D Map in the catalog UI, select the cog in the upper right corner of the …
=> DDF-2905 Updated single image layer projection coordinate system

catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/content/data/impl/ContentItemImpl.java, catalog/core/catalog-core-api-impl/src/test/java/ddf/catalog/content/data/impl/ContentItemValidatorTest.java, catalog/core/catalog-core-api/src/main/java/ddf/catalog/content/data/ContentItem.java, catalog/core/catalog-core-localstorageprovider/src/main/java/org/codice/ddf/catalog/content/impl/FileSystemStorageProvider.java, catalog/core/catalog-core-localstorageprovider/src/test/java/org/codice/ddf/catalog/content/impl/FileSystemStorageProviderTest.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/UpdateOperations.java, catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/impl/CatalogFrameworkImplTest.java, catalog/security/catalog-security-filter/src/main/java/ddf/catalog/security/filter/plugin/FilterPlugin.java
The PR adds a check to see if the the update content item has a qualifier before setting the `resource-size` attribute on the metacard. I also added to the javadoc for ContentItem#Qualifier.
@peterhuffer @troymohl @bdeining @brendan-hofmann
@pklinef 
@kcwire
1. Full build.
2. Full build with https://github.com/codice/alliance/pull/225. Especially, confirm that `ImagingTest` succeeds.
This PR is required for https://github.com/codice/alliance/pull/225.
[DDF-2871](https://codice.atlassian.net/browse/DDF-2871)
=> DDF-2871 Modified Update to not set resource-size when the item has a qualifier

platform/usng4j/platform-usng4j-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml
Modified blueprint.xml to remove the '.api' portion of the service interface package name.
This PR fixes a bug that we preventing the usng4j services from starting up.
@roelens8 
@jaymcnallie
@pklinef
1) build DDF
2) extract the ddf-2.11.0.zip
3) start DDF
4) in the Karaf shell, enter the command `feature:install platform-usng4j`
5) verify that the usng4j-api and usng4j-impl bundles have started.
DDF-2090
- [N/A] Change Log Updated
=> DDF-2909 usng4j services fail to start

catalog/admin/module/catalog-admin-module-sources/src/main/webapp/js/view/ModalSource.view.js, catalog/admin/module/catalog-admin-module-sources/src/main/webapp/templates/sourceModal.handlebars
Cherrypick of #1815 
Fixes the sources tab to not create undesired configs, and fixes the filtering in the main view so only existing configurations are shown.
@emanns95 
@clockard 
@pklinef
Create a source and verify only one config is created. Click in and out of the source modal, click cancel, and verify the dropdown never displays erroneous configs.
[DDF-2901](https://codice.atlassian.net/browse/DDF-2901)
=> DDF-2901 Only create the selected config (#1815)

distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/AbstractIntegrationTest.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalog.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalogSearchUi.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestEmbeddedSolr.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFanout.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFederation.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFtp.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestRegistry.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestSpatial.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestApplicationService.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestConfiguration.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestSolrCommands.java
All itests reset catalog contents in an @after with the karaf command "catalog:removeall -f -p". Previous cleanup logic has been removed from relevant itests. Additonally, data used by itests are now ingested in @before.
@emanns95 @ahoffer @brendan-hofmann @mweser 
@coyotesqrl
@shaundmorris
DDF can be built and all itests run.
[DDF-2868](https://codice.atlassian.net/browse/DDF-2868)
=> DDF-2868 Reset catalog contents after every itest

catalog/core/catalog-core-camelcomponent/src/main/java/ddf/camel/component/catalog/content/FileSystemPersistenceProvider.java, catalog/core/catalog-core-camelcomponent/src/test/java/ddf/camel/component/catalog/content/FileSystemPersistenceProviderTest.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/FileSystemPersistenceProvider.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/impl/FileSystemPersistenceProvider.java, platform/notifications/core/platform-core-notifications/src/main/java/org/codice/ddf/notifications/impl/FileSystemPersistenceProvider.java
Replaced String concatenation with calls to Paths.get when constructing the path to the persistence store to prevent extra DurableFileConsumer directories from being mistakenly created.
@emanns95 @ahoffer @brendan-hofmann @AzGoalie @mweser 
@coyotesqrl
@shaundmorris
1. Start and install a DDF instance
2. From the admin console, navigate to Catalog -> Configuration -> Catalog Content Directory Monitor
3. In the Directory Path field, add a local path to a directory from your machine for testing
4. Navigate to the `DDF_HOME/data` directory on your machine 
5. In the data directory, make sure there is only one `DurableFileConsumer` directory and one `processed` directory.
6. The `DurableFileConsumer` directory should contain only one .ser …
=> DDF-2911 Prevent directory monitor from creating extra DurableFileConsumer directory 

distribution/docs/src/main/resources/documentation.adoc
When the iframe-resizer was added for admin modules, it caused usability issues for documentation. This PR fixes those issues by adding the iframe-resizer script to documentation.
@coyotesqrl
@pklinef
- quick build, but include documentation
- open admin ui
- ensure the docs are usable
=> DDF-2896: added iframeresizer to documentation to fix scrolling issue.

distribution/docs/src/main/resources/documentation.adoc
Updates the link to the script in 2.10 to reflect its correct location.
@djblue @garrettfreibott 
@lessarderic
@shaundmorris
- Full build including documentation.
- Install and run
- Check `Documentation` link in Admin Console to ensure that it displays correctly and scrolls.
N/A
=> DDF-2896 Changes script link to iframe resizer in documentation.

platform/admin/core/admin-core-api/pom.xml, platform/admin/core/admin-core-api/src/main/java/org/codice/ddf/ui/admin/api/GuestClaimsHandlerExt.java, platform/admin/core/admin-core-api/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/admin/core/admin-core-api/src/test/java/org/codice/ddf/ui/admin/api/GuestClaimsHandlerExtTest.java, platform/platform-app/src/main/resources/features.xml, platform/security/platform-security-core-api/pom.xml, platform/security/platform-security-core-api/src/main/java/ddf/security/PropertiesLoader.java, platform/util/platform-util/pom.xml, platform/util/platform-util/src/main/java/org/codice/ddf/platform/util/properties/PropertiesFileReader.java, platform/util/platform-util/src/main/java/org/codice/ddf/platform/util/properties/PropertiesLoader.java, platform/util/platform-util/src/test/java/org/codice/ddf/platform/util/properties/PropertiesFileReaderTest.java
Addresses minor technical debt from previous sprint. 
@oconnormi 
@brjeter 
@lessarderic 
@figliold 
This technical debt has no specific testing steps. 
Yes. Similar functionality to `PropertiesFileReader` already exists in `security-core-api` within the `PropertiesLoader` class. Since `admin-core-api` already depends on `security-core-api` it made sense to just move the property manipulation logic there. 
[DDF-2731](https://codice.atlassian.net/browse/DDF-2731)
=> DDF-2731: Move property logic to platform-util where it can be reused

pom.xml
Enables a ddf-support maven plugin which scans the project at build for any package.json files which incorrectly use version ranges for dependencies.
@ahoffer @emanns95 @AzGoalie @vinamartin 
@coyotesqrl
@pklinef
Will need to pull in ddf-support PR as well (https://github.com/codice/ddf-support/pull/38) for the actual plugin, and then run `mvn verify` in DDF. Successful if verify errors out with a MojoException due to incorrect version range symbols. 
Version ranges expose the codebase to potential vulnerabilities, unlike sticking to exact, known versions of dependencies. 
[](https://codice.atlassian.net/browse/DDF-2819)
=> DDF-2819 Add maven-version-validation-plugin to root pom.xml

platform/admin/ui/src/main/webapp/js/views/Module.view.js
- In order to reduce the initial network cost, each tab's content (Applications, Documentation, etc.) is now loaded on demand when the user clicks the tab for the first time.
@djblue 
@rzwiefel 
@pklinef
Go to the admin UI and verify that the documentation does not load until you go to the documentation tab.
https://codice.atlassian.net/browse/DDF-2915
=> DDF-2915 (2.10.x) Update the Admin UI loading scheme to reduce initial network cost

platform/security/rest/security-rest-cxfwrapper/src/main/java/org/codice/ddf/cxf/SecureCxfClientFactory.java, platform/security/rest/security-rest-cxfwrapper/src/test/java/org/codice/ddf/cxf/SecureCxfClientFactoryTest.java
This allows for the creation of unstructured, generic, security aware WebClients. Instead of being required to define an interface class, we can pass the WebClient class in to create a general purpose client as supported by the JAXRSClientFactory.
@tbatie @peterhuffer
@coyotesqrl
@kcwire
Full build with tests is sufficient.
[DDF-2919](https://codice.atlassian.net/browse/)
=> DDF-2919 [2.10.x] Create generic WebClients with SecureCxfClientFactory

catalog/pom.xml, catalog/ui/catalog-ui-search/pom.xml, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/monitor/email/EmailNotifier.java, catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.email.xml, distribution/docs/src/main/resources/_contents/_platform-contents/managing-platform-contents.adoc, distribution/docs/src/main/resources/_contents/_tables/conf-org.codice.ddf.platform.email.impl.SmtpClientImpl-table-contents.adoc, distribution/docs/src/main/resources/_contents/_tables/org.codice.ddf.platform.email.impl.SmtpClientImpl-table-contents.adoc, platform/email/platform-email-api/pom.xml, platform/email/platform-email-api/src/main/java/org/codice/ddf/platform/email/SmtpClient.java, platform/email/platform-email-impl/pom.xml, platform/email/platform-email-impl/src/main/java/org/codice/ddf/platform/email/impl/SmtpClientImpl.java, platform/email/platform-email-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/email/platform-email-impl/src/main/resources/OSGI-INF/metatype/metatype.xml, platform/email/platform-email-impl/src/test/java/org/codice/ddf/platform/email/impl/SmtpClientImplITCase.java, platform/email/pom.xml, platform/platform-app/pom.xml, platform/platform-app/src/main/resources/features.xml, platform/pom.xml, pom.xml
Create a centralized email service that handles the configuration details for connecting to an email server.
@bdeining 
@rzwiefel 
@michaelmenousek  [optional]
[Core APIs](https://github.com/orgs/codice/teams/core-apis) @brendan-hofmann 
@pklinef 
@lessarderic
For testing, you will need to know the hostname of your email server. If you don't know what it is, you can try asking your system administrator or run the un*x command "dig mx DOMAINNAME", where DOMAINNAME is the domain name portion of your email address.
There are two areas that need to be tested: non-authenticating and authenticating. A non-authenticating email server does not require a username/password. For the authenticating test, the only email server that I know of that uses authentication w/ TLS is gmail.
If you have a …
=> DDF-2494 create an email service

catalog/ui/catalog-ui-search/src/main/webapp/js/widgets/openlayers.circle.js
- The units of the radius for circles in openlayers depends upon the map projection.  As a result, we need to convert back and forth as needed using getMetersPerUnit.
@clockard 
@mcalcote 
@pklinef
Verify that drawing circles works with openlayers.  Update the projection and switch back and forth from EPSG:3857 and EPSG:4326.  Verify old drawings work as they should, and new drawings as well.
https://codice.atlassian.net/browse/DDF-2925
=> DDF-2925 (2.10.x) - Update openlayers circle drawing to be projection agnostic

catalog/plugin/catalog-plugin-videothumbnail/src/main/java/org/codice/ddf/catalog/content/plugin/video/VideoThumbnailPlugin.java, catalog/plugin/catalog-plugin-videothumbnail/src/test/java/org/codice/ddf/catalog/content/plugin/video/TestVideoThumbnailPlugin.java
The ContentItem documentation states that null should be used as the qualifier for the original content. The video thumbnail plugin was assuming the qualifier is the empty string. 
@troymohl 
@peterhuffer 
@emmberk 
@jlcsmith 
@kcwire
@lessarderic
Ingest a video and verify that the thumbnail is created.
[DDF-2921](https://codice.atlassian.net/browse/DDF-2921)
=> DDF-2921 update VideoThumbnailPlugin and test code to use null for qualifier strings that represent the original content

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/CacheQueryFactory.java
When the `CacheQueryFactory` wraps and modifies queries to hit the cache, it was neglecting to include the timeout for the query. This PR resolves that.
@emanns95 @AzGoalie 
@pklinef
@stustison
On a slow or resource constrained machine, run the `TestFederation.testMetacardCache` integration test several times. It should pass successfully.
N/A
[DDF-2862](https://codice.atlassian.net/browse/DDF-2862)
N/A
=> DDF-2862 Fixes cache queries to carry over the query timeout passed to them

catalog/ui/catalog-ui-search/src/main/webapp/component/association/association.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/content/content.view.js, catalog/ui/catalog-ui-search/src/main/webapp/js/HandlebarsHelpers.js
- Removed possible injection opportunity from bind helper.
- Updated two other areas to be safe from possible injection.
@rzwiefel 
@pklinef
Go to a workspace and update the name to include xss.  Verify it doesn't get executed.
This was added in a backport to 2.10.x so it's not out in the wild yet.
https://codice.atlassian.net/browse/DDF-2934
Thanks for finding this one @garrettfreibott !
=> DDF-2934 (2.10.x) Remove injection opportunity from bind helper

catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/SolrCatalogProvider.java, distribution/test/itests/test-itests-common/src/main/resources/csw/request/CswUpdateAllByFilterRequest, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalog.java
This PR fixes an issue where UpdateRequests were only updating the first 10 metacards.
@jlcsmith
@pklinef 
Build / Install / Ingest 20-25 Records / Bulk Edit All 25 Records / Verify all are updated
[DDF-2928](https://codice.atlassian.net/browse/DDF-2928)
=> DDF-2928 Fixed SolrCatalogProvider row size

catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/operation/impl/QueryResponseImpl.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/CacheQueryFactory.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/QueryOperations.java, catalog/core/catalog-core-standardframework/src/main/resources/OSGI-INF/blueprint/delegate-operators.xml, catalog/core/catalog-core-standardframework/src/main/resources/OSGI-INF/metatype/metatype.xml, catalog/core/catalog-core-standardframework/src/test/groovy/ddf/catalog/impl/operations/QueryOperationsTest.groovy, catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/impl/CatalogFrameworkImplTest.java, distribution/docs/src/main/resources/_contents/_queries/developing-query-options-contents.adoc
This timeout will be applied in cases where the timeout is set
to a negative value or to 0 in the query.
* Added documentation for configuring query timeout
* Added unit tests for query timeout setting
@rzwiefel
@pklinef
@stustison 
A solr update seems to have resolved us being able to replicate the system freezing, but the timeout is still being added.
[DDF-2862](https://codice.atlassian.net/browse/DDF-2862)
=> DDF-2862 Added configurable default QueryResponse queue timeout

catalog/core/catalog-core-commons/src/main/java/ddf/catalog/impl/filter/FuzzyFunctionFactory.java, catalog/core/catalog-core-commons/src/test/java/ddf/catalog/impl/filter/FuzzyFunctionTest.java, distribution/docs/src/main/resources/_contents/_app-whitelists/catalog-whitelist-contents.adoc
This PR undoes the removal of the FuzzyFunctionFactory and deprecates it.
It also removes `ddf.catalog.filter.impl` from the whitelist.
@coyotesqrl  
@millerw8
@pklinef
Build / Install / Verify that the CqlEndpoint still recognizes proximity searches.  Since this functionality was already hero'd in the main PR, this should be sufficient.
[DDF-2900](https://codice.atlassian.net/browse/DDF-2900)
=> DDF-2900 Undid removal of FuzzyFunctionFactory.java

catalog/plugin/catalog-plugin-metacardbackup/pom.xml, catalog/plugin/catalog-plugin-metacardbackup/src/main/java/org/codice/ddf/catalog/plugin/metacard/backup/MetacardBackupPlugin.java, catalog/plugin/catalog-plugin-metacardbackup/src/test/java/org/codice/ddf/catalog/plugin/metacard/backup/MetacardBackupPluginTest.java
Resolves a Coverity finding to ensure an InputStream is not left open.
@bdeining @rzwiefel 
@shaundmorris
@stustison
Full build and test. For any manual testing, please ask @bdeining for details.
N/A
[DDF-2931](https://codice.atlassian.net/browse/DDF-2931)
N/A
=> DDF-2931 Fixes issue with unclosed InputStream

platform/security/rest/security-rest-cxfwrapper/src/main/java/org/codice/ddf/cxf/SecureCxfClientFactory.java, platform/security/rest/security-rest-cxfwrapper/src/test/java/org/codice/ddf/cxf/SecureCxfClientFactoryTest.java
This allows for the creation of unstructured, generic, security aware WebClients. Instead of being required to define an interface class, we can pass the WebClient class in to create a general purpose client as supported by the JAXRSClientFactory.
@tbatie @peterhuffer 
@stustison
@kcwire
Full build with tests is sufficient.
[DDF-2919](https://codice.atlassian.net/browse/)
=> DDF-2919 Create generic WebClients with SecureCxfClientFactory

gitsetup/pom.xml
Fix to the gitsetup module. A maven build (normal or quick) is not actually skipping execution of these plugins on the gitsetup module, as intended. 
@Lambeaux @figliold 
@coyotesqrl 
@lessarderic 
Run both a `mvn clean install` and `quickbuild` from the root. The build can be stopped after the Gitsetup module is built (it's only the second one). Verify in the maven output that `maven-dependency-plugin`, `findbugs-maven-plugin`, and `maven-checkstyle` plugins are not executed under the Gitsetup module.
[DDF-2918](https://codice.atlassian.net/browse/DDF-2918)
=> DDF-2918 Fixing gitsetup to truly not run plugins from the parent pom

catalog/spatial/csw/spatial-csw-common/pom.xml, catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/BoundingBoxReader.java, catalog/spatial/csw/spatial-csw-common/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/common/TestBoundingBoxReader.java, catalog/spatial/csw/spatial-csw-common/src/test/resources/BoundingBoxBadCoordinates.xml, catalog/spatial/csw/spatial-csw-common/src/test/resources/BoundingBoxBadCrs.xml, catalog/spatial/csw/spatial-csw-common/src/test/resources/BoundingBoxEPSG32636.xml, catalog/spatial/csw/spatial-csw-common/src/test/resources/BoundingBoxInLatLonEPSG4326.xml, catalog/spatial/csw/spatial-csw-common/src/test/resources/BoundingBoxInLonLatEPSG4326.xml, catalog/spatial/csw/spatial-csw-endpoint/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/reader/TestTransactionMessageBodyReader.java, catalog/spatial/csw/spatial-csw-source/pom.xml, catalog/spatial/csw/spatial-csw-transformer/pom.xml, catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/CswTransformProvider.java, catalog/spatial/csw/spatial-csw-transformer/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/TestCswTransformProvider.java, catalog/spatial/csw/spatial-csw-transformer/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/TestCswUnmarshallHelper.java, catalog/spatial/csw/spatial-csw-transformer/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/TestGetRecordsResponseConverter.java, catalog/spatial/registry/registry-api-impl/pom.xml, catalog/spatial/registry/registry-schema-bindings/pom.xml
This PR fixes an issue with passing context information (coordinateOrder) to the CswRecordConverter and adds a unit test to prevent regression.  Additionally it adds more robust support for CRS conversions when parsing CSW responses.
@clockard @glenhein 
@troymohl 
@jlcsmith
@kcwire
Build / Install/ Configure various CSW sources ( some with LAT / LON vs LON / LAT) and verify results.
This PR relies on this PR for GeospatialUtils : https://github.com/codice/ddf/pull/1712
[DDF-2842](https://codice.atlassian.net/browse/DDF-2842)
=> DDF-2842 Fixed coordinate order for CSW Federated Sources

platform/admin/ui/src/main/webapp/js/views/Module.view.js
- In order to reduce the initial network cost, each tab's content (Applications, Documentation, etc.) is now loaded on demand when the user clicks the tab for the first time.
@djblue 
@rzwiefel 
@pklinef
Go to the admin UI and verify that the documentation does not load until you go to the documentation tab.
https://codice.atlassian.net/browse/DDF-2915
=> DDF-2915 Update the Admin UI loading scheme to reduce initial network cost

distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestApplicationService.java
Marks `TestApplicationService.cTestAppStartStop()` as unstable.
@emanns95 
@clockard
@figliold
Full build including integration tests and make sure `TestApplicationService.cTestAppStartStop()` isn't run.
[DDF-2954](https://codice.atlassian.net/browse/DDF-2954)
=> DDF-2954 TestApplicationService.cTestAppStartStop() is unstable

distribution/docs/src/main/resources/_contents/_configuring/updating-system-users.adoc, distribution/docs/src/main/resources/documentation.adoc
added section to configuring documentation for updating system user
@clockard
@lessarderic
@pklinef
@shaundmorris
@stustison
verify section updated successfully
[documentation.pdf](https://github.com/codice/ddf/files/931127/documentation.pdf)
=> DDF-2824 fixed missing include for Updating users in docs

catalog/spatial/csw/spatial-csw-source/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/source/TransactionalCswStoreImpl.java, catalog/spatial/csw/spatial-csw-source/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/spatial/csw/spatial-csw-source/src/main/resources/OSGI-INF/metatype/metatype.xml, distribution/docs/src/main/resources/_contents/_sources/csw-transactional-federated-source-contents.adoc, distribution/docs/src/main/resources/_contents/_sources/federated-sources-contents.adoc, distribution/docs/src/main/resources/_contents/_spatial-contents/managing-spatial-contents.adoc, distribution/docs/src/main/resources/_contents/_tables/Csw_Transactional_Federated_Source-table-contents.adoc, distribution/docs/src/main/resources/_contents/_tables/conf-Csw_Transactional_Federated_Source-table-contents.adoc, distribution/docs/src/main/resources/documentation.adoc
This PR creates a transactional CSW Source that implements the AbstractCswStore which will ultimately support sending CSW transactions (create, update, delete) to federated CSW sources. 
@clockard 
@jlcsmith
@pklinef
There currently is no mechanism for sending out transactions to the CSW Source.  There already exists unit and integration tests for the AbstractCswStore, so no additional tests need to be created.  To hero, build and install DDF and verify that the CSW Transactional Source functions as as a normal source would.
[DDF-2942](https://codice.atlassian.net/browse/DDF-2942)
=> DDF-2942 Create a CSW Transactional Source

distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalogValidation.java
Marked an itest that regularly fails on the windows jenkins build unstable to improved automated build results.
@brendan-hofmann @emanns95 @AzGoalie @emmberk @vinamartin 
[Test](https://github.com/orgs/codice/teams/test) @Lambeaux 
@clockard
@lessarderic
Run the itests
This test did not have any issues on the linux nightly, but was the source of over half the windows itest failures tracked while developing the ddf jenkinsfile.
DDF-2958 is also the ticket to improve this itest and remove the unstable annotation.
[DDF-2958](https://codice.atlassian.net/browse/DDF-2958)
=> DDF-2958 Marked TestCatalogValidation's testNoEnforceValidityErrorsOrWarnings unstable to improve windows itest success rate

CHANGES.md, catalog/catalog-app/pom.xml, catalog/catalog-app/src/main/resources/features.xml, catalog/plugin/catalog-plugin-metacardbackup-api/pom.xml, catalog/plugin/catalog-plugin-metacardbackup-api/src/main/java/org/codice/ddf/catalog/plugin/metacard/backup/storage/api/MetacardBackupException.java, catalog/plugin/catalog-plugin-metacardbackup-api/src/main/java/org/codice/ddf/catalog/plugin/metacard/backup/storage/api/MetacardBackupStorageProvider.java, catalog/plugin/catalog-plugin-metacardbackup-api/src/main/java/org/codice/ddf/catalog/plugin/metacard/backup/storage/internal/MetacardBackupException.java, catalog/plugin/catalog-plugin-metacardbackup-api/src/main/java/org/codice/ddf/catalog/plugin/metacard/backup/storage/internal/MetacardBackupStorageProvider.java, catalog/plugin/catalog-plugin-metacardbackup-filestorage/pom.xml, catalog/plugin/catalog-plugin-metacardbackup-filestorage/src/main/java/org/codice/ddf/catalog/plugin/metacard/backup/storage/filestorage/MetacardBackupFileStorage.java, catalog/plugin/catalog-plugin-metacardbackup-filestorage/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/plugin/catalog-plugin-metacardbackup-filestorage/src/main/resources/OSGI-INF/metatype/metatype.xml, catalog/plugin/catalog-plugin-metacardbackup-filestorage/src/main/resources/describable.properties, catalog/plugin/catalog-plugin-metacardbackup-filestorage/src/test/java/org/codice/ddf/catalog/plugin/metacard/backup/storage/filestorage/MetacardBackupFileStorageTest.java, catalog/plugin/catalog-plugin-metacardbackup/pom.xml, catalog/plugin/catalog-plugin-metacardbackup/src/main/java/org/codice/ddf/catalog/plugin/metacard/backup/MetacardBackupPlugin.java, catalog/plugin/catalog-plugin-metacardbackup/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/plugin/catalog-plugin-metacardbackup/src/main/resources/OSGI-INF/metatype/metatype.xml, catalog/plugin/catalog-plugin-metacardbackup/src/test/java/org/codice/ddf/catalog/plugin/metacard/backup/MetacardBackupPluginTest.java, catalog/plugin/pom.xml, distribution/docs/src/main/resources/_contents/_plugins/metacard-backup-filestorage-contents.adoc, distribution/docs/src/main/resources/_contents/_plugins/metacard-backup-plugin-contents.adoc, distribution/docs/src/main/resources/_contents/_plugins/plugin-compatibility-table-contents.adoc, distribution/docs/src/main/resources/_contents/_plugins/post-ingest-plugins-contents.adoc, distribution/docs/src/main/resources/_contents/_tables/plugin.metacard-backup-filestorage-table-contents.adoc, distribution/docs/src/main/resources/_contents/_tables/plugin.metacard-backup-table-contents.adoc, distribution/docs/src/main/resources/documentation.adoc, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalog.java
Separates the storage for the Metacard Backup Plugin from the plugin itself.
@bdeining 
@glenhein 
@ricklarsen 
@millerw8 
@coyotesqrl 
1. Install DDF
2. Catalog:Features and install `catalog-metacard-backup-filestorage` and `catalog-metacard-backup`
3. Refresh Admin UI
4. Catalog:Configuration -> Backup Post-Ingest Plugin, disable this.
5. Catalog:Configuration -> Metacard Backup File Storage Provider, select directory. By default it is $DDF_HOME/data/backup/metacard. Click Save changes to create an instance.
6. Catalog:Configuration -> Metacard Backup Plugin. Click Save changes to create an instance.
7. Upload data to the catalog.
8. Ensure that a copy of the metacards is created in the directory specified in step 4.
Broke out …
=> DDF-2936 Separating Metacard backup storage from backup configuration

Jenkinsfile
The goal of this change is to add the initial Jenkinsfile to the project repo and establish the format for follow-on work. 
@oconnormi @LinkMJB @emmberk
[Build](https://github.com/orgs/codice/teams/build) @brendan-hofmann 
@lessarderic 
@clockard 
This job is currently running in the test Jenkins environment. After this ticket is merged we can set up a job for it on the standard jenkins to eventually migrate our nightly (and beyond) to.
This jenkinsfile utilizes the declarative syntax. This is currently in its 1.0 state and will likely have refinements and improvements rolling out in the near future.
[DDF-2920](https://codice.atlassian.net/browse/DDF-2920)
=> DDF-2920 Added initial jenkinsfile for pipelines build

distribution/ddf-common/src/main/resources/etc/org.ops4j.pax.web.cfg, distribution/ddf-common/src/main/resources/etc/system.properties, distribution/docs/src/main/resources/_contents/_configuring/configuring-global-settings-contents.adoc, platform/platform-commands/src/main/java/org/codice/ddf/commands/platform/DescribeCommand.java
- Also modifying the pax-web config to run jetty on the new internal ports.
This provides new system properties to allow an admin to run the DDF on a specific port, but advertise a different, external port. This is needed for certain features to work when DDF is behind a proxy or running in a container.
@Lambeaux @oconnormi
@figliold
@lessarderic 
- Run a full build.
- Change the `org.codice.ddf.system.httpsPort` property (external port) to be different than 8993. Run a proxy on that "external" port and put DDF behind it.
- Verify a resource can be downloaded (i.e. that the resource url uses the external port)
- Verify you can logout through the UI
- Verify the describe command prints out the correct ports (`platform:describe`)
[DDF-2932](https://codice.atlassian.net/browse/DDF-2932)
=> DDF-2932 Adding new system properties for internal ports.

catalog/plugin/catalog-plugin-metacardbackup-filestorage/src/test/java/org/codice/ddf/catalog/plugin/metacard/backup/storage/filestorage/MetacardBackupFileStorageTest.java, catalog/plugin/catalog-plugin-metacardbackup/src/test/java/org/codice/ddf/catalog/plugin/metacard/backup/MetacardBackupPluginTest.java
Fixes Windows build errors caused by the DDF-2936 changes.
@mcalcote 
@bdeining 
@kcwire
@millerw8
Full build on Windows.
Unit tests for Metacard Backup Plugin and Metacard Backup File Storage were coded for unix pathing instead of using File.separator. 
https://codice.atlassian.net/browse/DDF-2936
=> DDF-2936 Windows build fix for separating Metacard backup storage from backup configuration

distribution/ddf/pom.xml
removed documentation profile from distribution/ddf module.
@clockard
@lessarderic
@pklinef
@shaundmorris
builds successfully
[DDF-2867](https://codice.atlassian.net/browse/DDF-2867)
=> DDF-2867 removed skipDocs profile from distribution/ddf pom

CHANGES.md, catalog/plugin/catalog-plugin-metacardbackup/pom.xml, catalog/plugin/catalog-plugin-metacardbackup/src/main/java/org/codice/ddf/catalog/plugin/metacard/backup/MetacardBackupPlugin.java, catalog/plugin/catalog-plugin-metacardbackup/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/plugin/catalog-plugin-metacardbackup/src/main/resources/OSGI-INF/metatype/metatype.xml, catalog/plugin/catalog-plugin-metacardbackup/src/test/java/org/codice/ddf/catalog/plugin/metacard/backup/MetacardBackupPluginTest.java, distribution/docs/src/main/resources/_contents/_tables/plugin.metacard-backup-table-contents.adoc
Adds the ability to disable the backup of invalid metacards, such that only metacards that pass validation are backed up. 
@bdeining 
@glenhein 
@ricklarsen 
@kcwire
@millerw8
**Automated Tests:**
Run full build with Unit Tests.
**Manual Testing:**
1. Install DDF. Go into the Admin UI -> Catalog -> Features
a. Install catalog-metacard-backup-filestorage
b. Install catalog-metacard-backup
2. Refresh Admin UI
3. Go into Admin UI -> Catalog -> Configuration
a. Select Metacard Backup File Storage Provider and Save Changes for the default configuration
b. Select Metacard Backup Plugin and Save Changes for default configuration with the `Backup Invalid Metacards` option selected
4. Upload anything into DDF (e.g. .png image)
5. Click …
=> DDF-2961 Add option to skip invalid metacards when backing up.

catalog/core/catalog-core-federationstrategy/src/test/java/ddf/catalog/federation/impl/FederationStrategyTest.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/DeleteOperations.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/RemoteDeleteOperations.java, catalog/core/catalog-core-standardframework/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/core/catalog-core-standardframework/src/main/resources/OSGI-INF/blueprint/delegate-operators.xml, catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/impl/CatalogFrameworkImplTest.java, catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/impl/CatalogFrameworkQueryTest.java, catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/impl/FanoutCatalogFrameworkTest.java, catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/impl/operations/RemoteDeleteOperationsTest.java
Adds test coverage to DeleteOperations (ddf/catalog/impl/operations) by separating out the RemoteDeleteOperations into their own class.
@ahoffer @rzwiefel  @emanns95 @jrnorth  
@coyotesqrl 
@clockard 
Running test coverage on all tests in `ddf/catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog` should cover all of RemoteDeleteOperations and DeleteOperations.
Follows a string of goals to increase unit test coverage throughout DDF.
[](https://codice.atlassian.net/browse/DDF-2940)
=> DDF-2940 Improve unit test coverage for DeleteOperations

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/QueryOperations.java
Fixes cache queries when a source is unavailable
@bdeining 
@jlcsmith 
@kcwire 
Setup Source, Query and ensure cache is primed. Take down source, wait for sources to show source as unavailable. Run query and ensure cache results are still returned
https://codice.atlassian.net/browse/DDF-2967
=> DDF-2967 Fixed cache queries when source is unavailable

catalog/ui/catalog-ui-search/src/main/webapp/component/visualization/maps/cesium/map.cesium.js, catalog/ui/catalog-ui-search/src/main/webapp/component/visualization/maps/openlayers/map.openlayers.js
- The overlay actions have been updated to take into account recent changes to how geos are represented in results.
@jlcsmith
@rzwiefel 
@bdeining 
Use an overlay action on both cesium and openlayers and verify they work correctly.
https://codice.atlassian.net/browse/DDF-2972
=> DDF-2972 Fix overlay actions on cesium and openlayers

platform/security/sts/security-sts-ldapclaimshandler/pom.xml, platform/security/sts/security-sts-ldapclaimshandler/src/main/java/ddf/security/sts/claimsHandler/ClaimsHandlerManager.java, platform/security/sts/security-sts-ldapclaimshandler/src/test/java/ddf/security/sts/claimsHandler/LdapClaimsHandlerTest.java
1. Improves unit coverage of LdapClaimsHandler from 28% method coverage to 57% method coverage.
2.Improves unit coverage of LdapClaimsHandler from 11% line coverage to 77% line coverage.
3. Cleans up checkstyle warnings about ClaimsHandlerManager
@clockard
@clockard
@coyotesqrl 
Full build of DDF w/ integration tests
Part of red team's "war on test coverage"
[DDF-2875](https://codice.atlassian.net/browse/DDF-2875)
- [ N/A] Documentation Updated
- [ N/A] Change Log Updated
- [X ] Update / Add Unit Tests
- [ N/A] Update / Add Integration Tests
=> DDF-2875 Unit tests for LdapClaimsHandler

distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/annotations/SkipUnstableTest.java
Add a note on `@Rule ConditionalIgnoreRule` to the javadoc for `SkipUnstableTest`.
@ricklarsen @codymacdonald 
@clockard
@coyotesqrl
=> DDF-2824 Update javadoc to include rule

platform/solr/solr-factory/src/main/java/org/codice/solr/factory/impl/SolrCloudClientFactory.java
Added missing System.getProperty() calls.
@pklinef 
@brjeter 
@millerw8
@figliold 
Configure DDF to use SolrCloud and verify that the `solr.cloud.shardCount`, `solr.cloud.replicationFactor`, `solr.cloud.maxShardPerNode` and `org.codice.ddf.system.threadPoolSize` system properties can be used to change how SolrCloud gets configured at startup.
[DDF-2977](https://codice.atlassian.net/browse/DDF-02977)
=> DDF-2977 SolrCloud system properties are not properly processed

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/DeleteOperations.java
Removing the call to doPostIngest in DeleteOperations delete method. It was removed here because delete calls doDelete which is calling doPostIngest.
This PR removes the duplicate processing of post ingest plugins on a delete operation.
@peterhuffer @dcruver 
@clockard 
@pklinef 
DDF-2987
=> DDF-2987 Remove duplicate call to doPostIngest

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/resource/download/ReliableResourceDownloader.java, catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/resource/download/ReliableResourceDownloaderTest.java
Protects against an unlikely but possible NPE. From a Coverity finding, CID-108051.
@Lambeaux @rzwiefel 
@clockard
@stustison
Full build/test should be sufficient.
N/A
[DDF-2990](https://codice.atlassian.net/browse/DDF-2990)
N/A
=> DDF-2990 Protects against NPE in ReliableResourceDownloader

catalog/ui/catalog-ui-search/src/main/webapp/component/system-usage/system-usage.view.js
- The url for the css is a moving target with the new cache busting, so this updates the system usage view to get whatever the latest style sheet is dynamically rather than statically.
@clockard
@djblue 
@Lambeaux 
Add a system usage message.  Verify the correct css is fetched for the view.
https://codice.atlassian.net/browse/DDF-2981#### Screenshots (if appropriate)
=> DDF-2981 Update System Usage view to take cache busting into account

catalog/spatial/registry/registry-federation-admin-impl/src/main/java/org/codice/ddf/registry/federationadmin/impl/FederationAdmin.java, catalog/spatial/registry/registry-federation-admin-impl/src/test/java/org/codice/ddf/registry/federationadmin/impl/FederationAdminTest.java, catalog/spatial/registry/registry-federation-admin-service-impl/src/main/java/org/codice/ddf/registry/federationadmin/service/impl/FederationAdminServiceImpl.java, catalog/spatial/registry/registry-federation-admin-service-impl/src/test/java/org/codice/ddf/registry/federationadmin/service/impl/FederationAdminServiceImplTest.java, catalog/spatial/registry/registry-federation-admin-service/src/main/java/org/codice/ddf/registry/federationadmin/service/internal/FederationAdminService.java
Updates the registry delete logic so that the internal remote-registry metacards can be removed.
@coyotesqrl 
@shaundmorris
Install two instances and have registry 1 publish to registry 2. 
From the Node Information tab on registry 2 delete registry 1.
Go to solr on registry 2 and verify that there is only one entry that matches metacar-tags_txt:registry*
[DDF-2991](https://codice.atlassian.net/browse/DDF-2991)
=> DDF-2991 Updated registry delete operation to removes backing registry-remote metacards.

catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/ContentDirectoryMonitor.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/history/Historian.java, catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/history/HistorianTest.java, catalog/security/catalog-security-filter/src/main/java/ddf/catalog/security/filter/plugin/FilterPlugin.java, catalog/spatial/csw/spatial-csw-source-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/AbstractCswSource.java, catalog/spatial/registry/registry-api-impl/src/main/java/org/codice/ddf/registry/api/impl/RegistryMetacardHandler.java, catalog/spatial/registry/registry-api-impl/src/main/java/org/codice/ddf/registry/api/impl/RegistryStoreCleanupHandler.java, catalog/spatial/registry/registry-api-impl/src/main/java/org/codice/ddf/registry/api/impl/RegistryStorePublisher.java, catalog/spatial/registry/registry-federation-admin-service-impl/src/main/java/org/codice/ddf/registry/federationadmin/service/impl/IdentityNodeInitialization.java, catalog/spatial/registry/registry-federation-admin-service-impl/src/main/java/org/codice/ddf/registry/federationadmin/service/impl/RefreshRegistryEntries.java, catalog/spatial/registry/registry-identification-plugin/src/main/java/org/codice/ddf/registry/identification/RegistryIdPostIngestPlugin.java, catalog/spatial/registry/registry-identification-plugin/src/test/java/org/codice/ddf/registry/identification/RegistryIdPostIngestPluginTest.java, catalog/spatial/registry/registry-publication-action-provider/src/main/java/org/codice/ddf/registry/publication/manager/RegistryPublicationManager.java, catalog/spatial/registry/registry-publication-update-handler/src/main/java/org/codice/ddf/registry/publication/RegistryPublicationHandler.java, catalog/spatial/registry/registry-source-configuration-handler/src/main/java/org/codice/ddf/registry/source/configuration/SourceConfigurationHandler.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/MetacardApplication.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/monitor/impl/WorkspaceQueryServiceImpl.java, distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/ServiceManagerProxy.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestRegistry.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestApplicationService.java, platform/admin/core/admin-core-appservice/src/main/java/org/codice/ddf/admin/application/service/impl/ApplicationConfigInstaller.java, platform/platform-scheduler/src/main/java/ddf/platform/scheduler/CommandJob.java, platform/security/common/src/main/java/org/codice/ddf/security/common/Security.java, platform/security/common/src/test/java/org/codice/ddf/security/SecurityTest.java
Changes the `Security.runAsAdmin()` and `Security.runAsAdminWithException()` to be non-static
and updates all the usages of those methods in the code.
@rzwiefel 
@clockard 
@stustison
Full build, install and make sure the following areas are working properly:
* Directory monitor
* Historian
* Redaction and filtering
* Registry
* Catalog UI workspaces
* Command scheduler
[DDF-2992](https://codice.atlassian.net/browse/DDF-2992)
=> DDF-2992 Security utility class contains static methods which cannot mocked

catalog/core/catalog-core-metacardgroomerplugin/src/main/java/ddf/catalog/plugin/groomer/metacard/StandardMetacardGroomerPlugin.java, distribution/ddf-common/src/main/resources/etc/definitions/core-attribute-injectors.json, distribution/test/itests/test-itests-common/src/main/resources/modified-metacard-2.xml, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalog.java
This PR removes the logic to set default tags from the StandardMetacardGroomerPlugin and adds a JSON configuration instead.
@rzwiefel @troymohl 
@Lambeaux 
@pklinef
@clockard 
@stustison
Build / Install / Ingest and verify tags are set
[DDF-3004](https://codice.atlassian.net/browse/DDF-3004)
=> DDF-3004 Moved Default Tag behavior to JSON

catalog/core/catalog-core-api/src/main/java/ddf/catalog/operation/Query.java, catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/SolrMetacardClientImpl.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/QueryOperations.java, catalog/core/catalog-core-standardframework/src/test/groovy/ddf/catalog/impl/operations/QueryOperationsTest.groovy
- Enforces a maximum pageSize that defaults to `1000`, but can be overridden with a system property. This protects against overloading the system with too many records.
- With the current implementation, NegativeArraySizeExceptions occur in Solr Cloud. In order to avoid defaulting the number of rows for a query to a large number that could cause OutOfMemory errors in Solr Cloud, it will instead do a query for the number of records then set the number of rows for the actual query to that number.
@Lambeaux @figliold 
@lessarderic 
@pklinef 
- Full build
- Run DDF while connected to Solr Cloud.
- Ensure basic functionality of the Intrigue UI (i.e. workspaces get saved, are preserved between accounts, etc).
- Hit CSW Endpoint with …
=> DDF-2872 Enforce maximum pageSize for queries in the Catalog Framework

catalog/transformer/catalog-transformer-geojson-input/pom.xml, catalog/transformer/catalog-transformer-geojson-input/src/main/java/ddf/catalog/transformer/input/geojson/GeoJsonInputTransformer.java
GeoJsonInputTransformer explicitly sets the value of the metacard location field with the value of the GeoJson's geometry field.
@ryeats 
@kcwire
@pklinef 
@jaymcnallie 
-Run a full build clean build. 
-Ingest geojson containing geometry data and verify the metacard location field is populated.
When using the GeoJsonInputTransfomer to convert from GeoJson to a metacard, if the metacard's metacard type had multiple attribute descriptors with their types equal to "GEO", the old transformer logic would put the value of the geojson's geometry field into the last field it finds that has a type equal to "GEO" instead of immediately putting it into the metacard's location field.
[DDF-2964](https://codice.atlassian.net/browse/DDF-2964) …
=> DDF-2964 Fix GeoJsonInputTransformer to explicitly set the metacard location with the geojson geometry

catalog/spatial/csw/spatial-csw-transformer/src/main/resources/OSGI-INF/blueprint/blueprint.xml, distribution/test/itests/test-itests-common/src/main/resources/csw/record/CswRecord2, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestSpatial.java
This PR adds an integration test for the GeoCoderPlugin and asserts that a metacard's location.country-code is correctly derived from its location attribute.
@adimka @glenhein 
@brianfelix 
@jlcsmith
@millerw8
Build DDF
[DDF-3000](https://codice.atlassian.net/browse/DDF-3000)
=> DDF-3000 Added itest for GeoCoderPlugin

catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/ExportCommand.java
- When delete is enabled, we now remove items from the cache so cached items don't get returned in results
@vinamartin @peterhuffer 
@jlcsmith
@kcwire
Run search of archived items to populate cache, Export with delete enabled `--delete=true`, ensure that no items get returned from UI search.
https://codice.atlassian.net/browse/DDF-2698
=> DDF-2698 Now remove exported items from cache

catalog/core/catalog-core-subscriptionstore/pom.xml, catalog/core/catalog-core-subscriptionstore/subscriptionstore-impl/pom.xml, catalog/core/catalog-core-subscriptionstore/subscriptionstore-impl/src/main/java/org/codice/ddf/catalog/subscriptionstore/common/SubscriptionMetadata.java, catalog/core/catalog-core-subscriptionstore/subscriptionstore-impl/src/main/java/org/codice/ddf/catalog/subscriptionstore/common/SubscriptionPersistor.java, catalog/core/catalog-core-subscriptionstore/subscriptionstore-impl/src/test/java/org/codice/ddf/catalog/subscriptionstore/common/SubscriptionPersistorTest.java, catalog/core/catalog-core-subscriptionstore/subscriptionstore-internal-api/pom.xml, catalog/core/catalog-core-subscriptionstore/subscriptionstore-internal-api/src/main/java/org/codice/ddf/catalog/subscriptionstore/internal/MarshalledSubscription.java, catalog/core/catalog-core-subscriptionstore/subscriptionstore-internal-api/src/main/java/org/codice/ddf/catalog/subscriptionstore/internal/SubscriptionIdentifier.java, catalog/core/catalog-core-subscriptionstore/subscriptionstore-internal-api/src/main/java/org/codice/ddf/catalog/subscriptionstore/internal/SubscriptionStoreException.java, catalog/core/catalog-core-subscriptionstore/subscriptionstore-internal-api/src/main/java/org/codice/ddf/catalog/subscriptionstore/internal/SubscriptionType.java, catalog/core/pom.xml, platform/persistence/platform-persistence-core-api/src/main/java/org/codice/ddf/persistence/PersistentStore.java
_DDF-2927 PR 1 out of 4._ 
The SubscriptionPersistor will be used within the cache loader and writer. It talks to the Persistent Store, specifically the `event_subscriptions` core. It operates on SubscriptionMetadata, which contains the serializable parts of a complete Subscription object. 
@brjeter 
@paouelle 
@lessarderic 
@shaundmorris 
@ryeats 
@rzwiefel 
@figliold 
@pklinef
Part 1 of 4 is not testable by the end user, as it exposes no functionality. Please refer to the unit tests. 
This is part of an effort to centralize durable subscriptions to Solr. Later on, there are high availability implications and benefits. 
[DDF-2927](https://codice.atlassian.net/browse/DDF-2927)
=> DDF-2927 Started the subscription service by adding a persistor and its data model

distribution/docs/pom.xml, distribution/docs/src/main/jdocs/content/_core-concepts/catalog-framework-intro-contents.adoc, distribution/docs/src/main/jdocs/content/_core-concepts/content-intro-contents.adoc, distribution/docs/src/main/jdocs/content/_core-concepts/endpoints-intro-contents.adoc, distribution/docs/src/main/jdocs/content/_core-concepts/events-subscriptions-intro-contents.adoc, distribution/docs/src/main/jdocs/content/_core-concepts/federation-intro-contents.adoc, distribution/docs/src/main/jdocs/content/_core-concepts/ingest-intro-contents.adoc, distribution/docs/src/main/jdocs/content/_core-concepts/metadata-intro-contents.adoc, distribution/docs/src/main/jdocs/content/_core-concepts/registry-intro-contents.adoc, distribution/docs/src/main/jdocs/content/_core-concepts/resources-intro-contents.adoc, distribution/docs/src/main/jdocs/content/_core-concepts/search-intro-contents.adoc, distribution/docs/src/main/jdocs/content/_introduction/applications-contents.adoc, distribution/docs/src/main/jdocs/content/_introduction/core-concepts-intro-contents.adoc, distribution/docs/src/main/jdocs/content/_introduction/developing-intro-contents.adoc, distribution/docs/src/main/jdocs/content/_introduction/documentation-notes-contents.adoc, distribution/docs/src/main/jdocs/content/_introduction/integrating-intro-contents.adoc, distribution/docs/src/main/jdocs/content/_introduction/introduction-contents.adoc, distribution/docs/src/main/jdocs/content/_introduction/managing-intro-contents.adoc, distribution/docs/src/main/jdocs/jbake.properties, distribution/docs/src/main/jdocs/templates/documentation.ftl, distribution/docs/src/main/jdocs/templates/eventing.ftl, distribution/docs/src/main/jdocs/templates/introduction.ftl, distribution/docs/src/main/resources/_contents/_tables/ddf.catalog.transformer.input.pdf.PdfInputTransformer-table-contents.adoc, distribution/docs/src/main/resources/_contents/_tables/ddf.catalog.transformer.input.pptx.PptxInputTransformer-table-contents.adoc, distribution/docs/src/main/resources/_contents/config.adoc
- Adds the introduction and core-concepts sections of the documentation to the jbake templates. 
- Simplified/reduced the outline/TOC for these sections
@clockard
@coyotesqrl
@lessarderic
@pklinef
@shaundmorris
Verify sections are being included from old format.
`-contents.adoc` files unchanged except for adding headers. Content review optional.
[DDF-2880](https://codice.atlassian.net/browse/DDF-2880)
[jdocumentation.pdf](https://github.com/codice/ddf/files/1006135/jdocumentation.pdf)
=> Ddf 2880 add Introductory sections to templated docs

catalog/spatial/registry/registry-schema-bindings/src/main/java/org/codice/ddf/registry/schemabindings/helper/InternationalStringTypeHelper.java, catalog/spatial/registry/registry-schema-bindings/src/test/java/org/codice/ddf/registry/schemabindings/helper/InternationalStringTypeHelperTest.java
The InternationalStringTypeHelper class has a method to get a string from the InternationStringType. In this method, the list of LocalizedStringTypes is iterated until one with a language matching the default locale's is found.
Adding a check so if a match isn't found it will default to the first string in the list.
Updating itest
cherry pick commit (d02cb0a4fb49155afa82a5cf655fbaa422656f22)
This PR fixes the build errors seen by systems whose locale's language is not 'en-US'
#[Core APIs](https://github.com/orgs/codice/teams/core-apis)
@clockard
@shaundmorris
Set machine's region to something other than US.
Build ddf/catalog/spatial/registy
Verify tests pass
[DDF-3026](https://codice.atlassian.net/browse/DDF-3026)
=> backport DDF-3026: Registy unit tests failing for locales outside of 'en-US'

catalog/spatial/registry/registry-schema-bindings/src/main/java/org/codice/ddf/registry/schemabindings/helper/InternationalStringTypeHelper.java, catalog/spatial/registry/registry-schema-bindings/src/test/java/org/codice/ddf/registry/schemabindings/helper/InternationalStringTypeHelperTest.java
The InternationalStringTypeHelper class has a method to get a string from the InternationStringType. In this method, the list of LocalizedStringTypes is iterated until one with a language matching the default locale's is found.
Adding a check so if a match isn't found it will default to the first string in the list.
Updating itest
This PR fixes the build errors seen by systems whose locale's language is not 'en-US'
@clockard
@shaundmorris
Set machine's region to something other than US.
Build ddf/catalog/spatial/registy
Verify tests pass
[DDF-3026](https://codice.atlassian.net/browse/DDF-3026)
=> DDF-3026: Registy unit tests failing for locales outside of 'en-US'

distribution/test/itests/test-itests-common/pom.xml, distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/ServiceManagerProxy.java, distribution/test/itests/test-itests-ddf/pom.xml, distribution/test/itests/test-itests-dependencies-app/src/main/filtered-resources/features.xml, pom.xml
The issue of the ServiceManagerProxy getting a NPE when trying to get the system subject became very apparent when working on the karaf upgrade ticket. We did find that it is also occasionally happening right now on master as well though. This pr should protect against this.
@mcalcote @emmberk 
@lessarderic
@shaundmorris
[DDF-3033](https://codice.atlassian.net/browse/DDF-3033)
=> DDF-3033 Ensure SecurityManager service is available before trying to use it in ServiceManagerProxy

catalog/catalog-app/src/main/resources/features.xml, distribution/test/itests/pom.xml, distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/AbstractIntegrationTest.java
Pax Exam 4.11.0 Release notes: https://ops4j1.jira.com/wiki/display/PAXEXAM4/2017/05/16/Pax+Exam+4.11.0+released
Changes by file: 
_catalog-app/src/main/resources/features.xml_
Rearranges bundles in catalog-core to prevent a timing issue
_distribution/test/itests/pom.xml_
Updates the pax exam version to 4.11.0, added a comment
_test-itests-common/src/main/java/org/codice/ddf/itests/common/AbstractIntegrationTest.java_
Fixes an issue with a configuration that gets set using pax exam that used to be in quotations but no longer needs to be.
_test-itests-common/src/main/java/org/codice/ddf/itests/common/ServiceManagerProxy.java_
Creates a retry for getting the SecurityManager in the ServiceManagerProxy to prevent a potential timing issue that was occurring in the itests. This issue currently …
=> DDF-3025 Upgrade to Pax Exam 4.11.0

distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/AbstractIntegrationTest.java, distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/catalog/CatalogTestCommons.java, distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/opensearch/OpenSearchTestCommons.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalog.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalogValidation.java
Fixes flaky tests in TestCatalogValidation
Fix was to ensure stable base state in setup and make sure ingest/query operations waited long enough for configurations/metacards to be ready. 
@mcalcote @emmberk 
@figliold
@lessarderic
Verify itests pass. This has been tested already on the jenkins server and passed 22 itest runs in a row
[DDF-2958](https://codice.atlassian.net/browse/DDF-2958)
=> DDF-2958 Fix unstable itests in TestCatalogValidation

catalog/core/catalog-core-commands/pom.xml, catalog/core/catalog-core-solrcommands/pom.xml, catalog/resourcemanagement/resourcemanagement-app/pom.xml, catalog/ui/catalog-ui-search/pom.xml, libs/libs-pomfix/test/resources/descriptors/pom.xml, platform/admin/core/admin-core-appservice/pom.xml, platform/platform-scheduler/pom.xml, platform/security/common/pom.xml, platform/security/platform-security-core-api/pom.xml, platform/security/sts/security-sts-ldaplogin/pom.xml
This PR adds `${karaf.version}` to karaf dependencies so that the version does not rely on dependency management (see [DDF-2985](https://codice.atlassian.net/browse/DDF-2985)). This PR shouldn't affect any versions. It just cleans up the dependency management before the Karaf upgrade to 4.1.1.
@vinamartin @mcalcote @josephthweatt 
@beyelerb
@clockard
Full build.
[DDF-2132](https://codice.atlassian.net/browse/DDF-2132)
=> DDF-2132 Added version properties for karaf dependencies

catalog/core/catalog-core-subscriptionstore/subscriptionstore-impl/pom.xml, catalog/core/catalog-core-subscriptionstore/subscriptionstore-impl/src/main/java/org/codice/ddf/catalog/subscriptionstore/SubscriptionCacheLoader.java, catalog/core/catalog-core-subscriptionstore/subscriptionstore-impl/src/main/java/org/codice/ddf/catalog/subscriptionstore/SubscriptionCacheWriter.java, catalog/core/catalog-core-subscriptionstore/subscriptionstore-impl/src/main/java/org/codice/ddf/catalog/subscriptionstore/common/CachedSubscription.java, catalog/core/catalog-core-subscriptionstore/subscriptionstore-impl/src/main/java/org/codice/ddf/catalog/subscriptionstore/common/SubscriptionMetadata.java, catalog/core/catalog-core-subscriptionstore/subscriptionstore-impl/src/main/java/org/codice/ddf/catalog/subscriptionstore/common/SubscriptionPersistor.java, catalog/core/catalog-core-subscriptionstore/subscriptionstore-impl/src/test/java/org/codice/ddf/catalog/subscriptionstore/CacheEntryTestImpl.java, catalog/core/catalog-core-subscriptionstore/subscriptionstore-impl/src/test/java/org/codice/ddf/catalog/subscriptionstore/SubscriptionCacheLoaderTest.java, catalog/core/catalog-core-subscriptionstore/subscriptionstore-impl/src/test/java/org/codice/ddf/catalog/subscriptionstore/SubscriptionCacheWriterTest.java, catalog/core/catalog-core-subscriptionstore/subscriptionstore-impl/src/test/java/org/codice/ddf/catalog/subscriptionstore/common/CachedSubscriptionTest.java, catalog/core/catalog-core-subscriptionstore/subscriptionstore-internal-api/src/main/java/org/codice/ddf/catalog/subscriptionstore/internal/SubscriptionFactory.java, catalog/core/catalog-core-subscriptionstore/subscriptionstore-internal-api/src/main/java/org/codice/ddf/catalog/subscriptionstore/internal/SubscriptionRegistrationException.java
_DDF-2927 PR 2 out of 4._ 
The cache loader and writer implementations use the SubscriptionPersistor to read, write, and delete subscriptions from the persistent store. The container impl itself (PR 3/4) does not interact with the persistor directly; only through cache operations. 
Instances of `CachedSubscription` will be stored in the cache. While DDF is starting up, it is possible to have unregistered and uninitialized `CachedSubscription`s in the cache. This should be resolved after DDF has finished booting and is necessary because:
1. An instance of `SubscriptionFactory` is required to regenerate the original, non-serializable subscription for each subscription type. 
2. Consumers of the subscription store register their factory impl with osgi, but the subscription store loads the …
=> DDF-2927 Added a self-registering cached subscription, cache loader, and cache writer

catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java
Adds debug log messages for failures during CSW transactions.
@bdeining 
@brianfelix 
@kcwire
@millerw8
1. Set debug logging for the CSW endpoint: 
log:set DEBUG org.codice.ddf.spatial.ogc.csw.catalog.endpoint
2. Tail the log (log:tail)
3. Ingest invalid data:
POST invalid data to endpoint: https://localhost:8993/services/csw
`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<csw:Transaction service="CSW" verboseResponse="true" version="2.0.2" xmlns:csw="http://www.opengis.net/cat/csw/2.0.2">
<csw:Insert typeName="invalid-data">
<root>
<id>abcd16df29413796b388b02ee017a315</id>
</document>
</csw:Insert>
</csw:Transaction>`
https://codice.atlassian.net/browse/DDF-3049
=> DDF-3049 Add logging for CSW transaction exceptions

CHANGES.md, catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/validation/impl/report/AttributeValidationReportImpl.java, catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/validation/impl/validator/MatchAnyValidator.java, catalog/core/catalog-core-api-impl/src/test/java/ddf/catalog/validation/impl/MatchAnyValidatorTest.java, catalog/core/catalog-core-validationparser/src/main/java/ddf/catalog/validation/impl/ValidationParser.java, catalog/core/catalog-core-validationparser/src/test/groovy/ddf/catalog/validation/impl/ValidationParserSpecTest.groovy, distribution/docs/src/main/resources/_contents/_catalog-frameworks/global-attribute-validators-definition-contents.adoc
This PR adds a MatchOneValidator to support the ability to or validators together in a JSON file.
@rzwiefel @troymohl 
@jrnorth 
@jlcsmith
@millerw8
Build / Install / Configure a MatchOneValidator / Verify Proper behavior
Example:
`
{
"validators": {
"title": [
{
"validator": "size",
"arguments": ["0", "128"]
},
{
"validator": "match_one",
"validators": [
{ 
"validator": "enumeration", 
"arguments": ["abe", "lincoln"] 
},
{
"validator": "pattern",
"arguments": ["sc-[0-9]\+"] 
}
]
}
]
}
}
`
[DDF-3030](https://codice.atlassian.net/browse/DDF-3030)
=> DDF-3030 Added support for match any validator

catalog/core/catalog-core-api/src/main/java/ddf/catalog/content/operation/MetadataExtractor.java, catalog/transformer/catalog-transformer-tika-input/pom.xml, catalog/transformer/catalog-transformer-tika-input/src/main/java/ddf/catalog/transformer/input/tika/TikaInputTransformer.java, catalog/transformer/catalog-transformer-tika-input/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/transformer/catalog-transformer-tika-input/src/test/java/ddf/catalog/transformer/input/tika/TikaInputTransformerTest.java
1. Add a new interface, MetadataExtractor to catalog operations. Modified TikaInputTransformer to use the new interface. Services that implement the MetadataExtractor interface are called with the Tika transformer ingests a document. The transformer will call the service twice. Once to get a list of attribute descriptors to add to the metacard type. The second time, the transformer passes the tika-extracted metadata and the new metacard to the extractor. The extractor has the opportunity to enrich the metacard by adding new attributes derived from the tika-extracted metadata.
2. Light cleanup of TikaInputTransformer.transform() method. Some of the functionality was moved into helper methods. Complexity of the method was reduced.
3. Additional unit tests.
@brendan-hofmann @emanns95 …
=> DDF-3007 Metadata Extractor

platform/admin/ui/src/main/webapp/js/models/Applications.js
Adds in a null check for the application name regex in the case where an application neither has a version or a version in its name. The `.match` method returns null when the regex isn't matched. 
This isn't currently an issue with any of our apps, but it could become an issue in the future. 
@djblue @andrewkfiedler 
@clockard
@lessarderic
Run through the installer and make sure everything installs properly
This is related to work being done for the Karaf 4.1.1 upgrade.
=> DDF-3062 Adds null check for application name regex

catalog/spatial/wfs/1.0.0/spatial-wfs-v1_0_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v1_0_0/catalog/source/TestWfsFilterDelegate.java
Effectively restored all the commented code in TestWfsFilterDelegate for **wfs v1_0_0**.
Imported necessary packages and restored commented out variables.
@vinamartin 
@stustison 
@kcwire 
@clockard
@lessarderic 
Build the DDF, test this file, TestWfsFilterDelegate for **wfs v1_0_0** with `mvn clean verify -Dit.test=TestWfsFilterDelegate`
I found this file while refactoring the DDF (see [PR 2017](https://github.com/codice/ddf/pull/2017)), and am not entirely certain why this code was removed in the first place. If anyone knows why, please let us know.
[DDF-3042](https://codice.atlassian.net/browse/)
=> DDF-3042 Fix unused tests in TestWfsFilterDelegate

distribution/docs/src/main/jdocs/content/_installing/installing-intro-contents.adoc, distribution/docs/src/main/jdocs/content/_quickstart/quickstart-configuring-contents.adoc, distribution/docs/src/main/jdocs/content/_quickstart/quickstart-ingesting-contents.adoc, distribution/docs/src/main/jdocs/content/_quickstart/quickstart-installing-contents.adoc, distribution/docs/src/main/jdocs/jbake.properties, distribution/docs/src/main/jdocs/templates/documentation.ftl, distribution/docs/src/main/jdocs/templates/quickstart.ftl, distribution/docs/src/main/resources/_contents/_installing/installing-intro-contents.adoc, distribution/docs/src/main/resources/_contents/_quickstart/quickstart-configuring-contents.adoc, distribution/docs/src/main/resources/_contents/_quickstart/quickstart-installing-contents.adoc
- Adds Quick Start tutorial to jbake/freemarker templates for documentation.
@vinamartin @Lambeaux @ahoffer @jrnorth 
@clockard
@coyotesqrl
@lessarderic
@pklinef
@shaundmorris
- compare attached pdf to current documentation for completeness.
- "New" `-contents.adoc` files are existing material with headers added. Content review is OPTIONAL.
Moved Quick Start section closer to beginning of documentation, to before the complete installation/configuration instructions.
[DDF-2881](https://codice.atlassian.net/browse/DDF-2881)
[jdocumentation.pdf](https://github.com/codice/ddf/files/1068995/jdocumentation.pdf)
=> DDF-2881  added quick start tutorial to templated documentation

catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/XstreamTreeWriter.java
Fixed bug where child xml elements that ended with their parents
node name caused incorrect output
@adimka 
@bdeining 
@kcwire 
@millerw8
Full build
[DDF-3068](https://codice.atlassian.net/browse/DDF-3068)
=> DDF-3068 Fixed bug in XstreamTreeWriter

broker/broker-app/src/main/resources/features.xml, catalog/catalog-app/src/main/resources/features.xml, platform/security/security-services-app/src/main/resources/features.xml
Fixed typo on project version variable in feature files that was causing some features to have invalid version information
@brianfelix 
@bdeining 
@coyotesqrl 
@kcwire
@pklinef
Build it, run it, type feature:list on the CLI and confirm all feature versions (2nd column) make sense.  In particular, there should be nothing in the form of 0.0.0.__project_version
There was a typo omitting the trailing } on the project.version variable in multiple feature files.  The result was the variable was not recognized as a variable, but as the actual version, the version was set to 0.0.0.<text> where the text was the an underscore-escaped version of what was supposed to be the variable.  
https://codice.atlassian.net/browse/DDF-3081
=> DDF-3081 Fixed typo on project version variable in feature files

catalog/catalog-app/pom.xml, catalog/catalog-app/src/main/resources/features.xml, catalog/spatial/geocoding/spatial-geocoding-plugin/src/main/java/org/codice/ddf/spatial/geocoding/plugin/GeoCoderPlugin.java, catalog/spatial/geocoding/spatial-geocoding-plugin/src/test/groovy/org/codice/ddf/spatial/geocoding/plugin/GeoCoderPluginTest.groovy, catalog/validator/catalog-validator-metacardlocation/pom.xml, catalog/validator/catalog-validator-metacardlocation/src/main/java/org/codice/ddf/validator/metacard/location/MetacardLocationValidator.java, catalog/validator/catalog-validator-metacardlocation/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/validator/catalog-validator-metacardlocation/src/test/java/org/codice/ddf/validator/metacard/location/MetacardLocationValidatorTest.java, catalog/validator/pom.xml
Updates GeoCoder so that bad location data will generate a plugin exception that is caught above. Added a location validator for to mark invalid locations as well as clear the location field such that the metacard can be stored.
@bdeining 
@glenhein 
@clockard
@millerw8
1. Post the following CSW transaction with invalid location information:
```<csw:Transaction service="CSW" version="2.0.2" verboseResponse="true" xmlns:csw="http://www.opengis.net/cat/csw/2.0.2">
<csw:Insert typeName="csw:Record">
<csw:Record
xmlns:ows="http://www.opengis.net/ows"
xmlns:csw="http://www.opengis.net/cat/csw/2.0.2"
xmlns:dc="http://purl.org/dc/elements/1.1/"
xmlns:dct="http://purl.org/dc/terms/"
xmlns:xsd="http://www.w3.org/2001/XMLSchema"> …
```
=> DDF-3052 Update GeoCoder to handle bad locations. Add location validator to flag invalid location data.

catalog/ui/search-ui-app/src/main/resources/etc/org.codice.ddf.catalog.ui.config
Fixes the default org.codice.ddf.catalog.ui.config file to match defaults in the metatype.xml. This adds correct pattern matching for read-only fields on the UI.
@glenhein 
@adimka 
@dannythk 
@clockard
@millerw8
Verify that fields containing the names, but not exactly matching can be edited. For instance an `ext.point-of-contact-name` would no longer be read-only and allow editing.
https://codice.atlassian.net/browse/DDF-3090 …
=> DDF-3090 Fixed ui.config regex to match default metatype configuration.

distribution/docs/src/main/jdocs/content/_endpoints/catalog-rest-endpoint-contents.adoc, distribution/docs/src/main/resources/_contents/_endpoints/catalog-rest-endpoint-contents.adoc
Fixes (removes) duplicated lines in Catalog Rest Endpoint docs breaking formatting. 
@vinamartin @Lambeaux @jrnorth @ahoffer 
@ricklarsen
@clockard
@coyotesqrl
@lessarderic
@pklinef
@shaundmorris
- Verify the table in section `22.1.3(documentation.pdf)/7.1.2(jdocumentation.pdf) Using the Catalog REST Endpoint` is formatted correctly.
- Verify formatting for section headers following.
[jdocumentation.pdf](https://github.com/codice/ddf/files/1086321/jdocumentation.pdf) …
=> DDF-2824 fixed broken table in ReST endpoint docs

platform/security/idp/security-idp-client/src/main/java/org/codice/ddf/security/idp/client/IdpLogoutActionProvider.java, platform/security/platform-security-core-api/src/test/java/ddf/security/SubjectUtilsTest.java, platform/security/servlet/security-servlet-logout/src/main/java/org/codice/ddf/security/servlet/logout/LogoutService.java, platform/security/servlet/security-servlet-logout/src/main/webapp/js/logout-response.js
- Fixed bug that would not allow logging out if guest.
- Fixed IdP logout action provider to use the user’s display name
instead of their full name id.
- Fixed logout confirmation to URI decode the response message.
@brjeter 
@lessarderic
@stustison
Login as guest.  Go to `https://localhost:8993/logout` and verify that you can logout as guest and log in as a different user.
[DDF-3070](https://codice.atlassian.net/browse/DDF-3070)
- [ n/a ] Change Log Updated
=> DDF-3070 Allow the ability to logout if currently guest.

catalog/core/catalog-core-impl/pubsub/src/main/java/ddf/catalog/pubsub/EventProcessorImpl.java, catalog/core/catalog-core-impl/pubsub/src/main/java/ddf/catalog/pubsub/internal/SubscriptionFilterVisitor.java, catalog/core/catalog-core-impl/pubsub/src/main/java/ddf/catalog/pubsub/predicate/TemporalPredicate.java, catalog/core/catalog-core-impl/pubsub/src/test/java/ddf/catalog/pubsub/MockQuery.java, catalog/core/catalog-core-impl/pubsub/src/test/java/ddf/catalog/pubsub/PredicateTest.java, catalog/core/catalog-core-impl/pubsub/src/test/java/ddf/catalog/pubsub/TestEventProcessorImpl.java
Adds handling of metacard.created and metacard.modified as temporal fields for pubsub.
@ahoffer 
@mweser 
TBD
Full test build
This is to help support possible programs that build on the DDF that relied on "modified" or "created" referring to the metacard instead of the resource.
[DDF-3089](https://codice.atlassian.net/browse/DDF-3089)
=> DDF-3089 Added pubsub support for metacard.created/modified

CHANGES.md, catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/XstreamTreeWriter.java, catalog/spatial/csw/spatial-csw-transformer/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/TestXstreamTreeWriter.java
Fix XstreamTreeWriter to correctly handle the case when a parent and child element contain the same attribute.
@bdeining 
@jlcsmith 
IO - @coyotesqrl 
@lessarderic
@millerw8
Run unit tests and itests.
[DDF-3098](https://codice.atlassian.net/browse/DDF-3098)
=> DDF-3098 fix XstreamTreeWriter to correctly handle parent/child attributes

catalog/spatial/csw/spatial-csw-connectedsource/src/main/resources/OSGI-INF/metatype/metatype.xml, catalog/spatial/csw/spatial-csw-source/src/main/resources/OSGI-INF/metatype/metatype.xml, catalog/spatial/wfs/1.0.0/spatial-wfs-v1_0_0-connectedsource/src/main/resources/OSGI-INF/metatype/metatype.xml, catalog/spatial/wfs/1.0.0/spatial-wfs-v1_0_0-source/src/main/resources/OSGI-INF/metatype/metatype.xml, catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-connectedsource/src/main/resources/OSGI-INF/metatype/metatype.xml, catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/main/resources/OSGI-INF/metatype/metatype.xml, platform/admin/core/admin-core-impl/src/main/java/org/codice/ddf/admin/core/impl/ConfigurationAdminImpl.java, platform/admin/ui/src/main/webapp/js/views/configuration/ConfigurationEdit.view.js
Makes the password fields consistent in the UI so that if no password is set then the field is left blank
@emmberk
@vinamartin
@clockard
@josephthweatt
@ricklarsen
@clockard
@shaundmorris
1. Build and run ddf
2. In the Admin Console, Go to Applications Catalog > Sources
3. Add 2 sources, one with a password and one without a password
4. Click on the sources you just added to see that the one without a password is left blank, and the one with a password is masked with "password"
[DDF-2523](https://codice.atlassian.net/browse/) …
=> DDF-2523 Made password fields consistent in the UI (revised)

catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/ValidateCommand.java
Changes the usage message of catalog:validate to reflect the correct option
@emmberk 
@vinamartin 
@clockard
@shaundmorris
1. Build & run DDF
2. go through the setup process in the admin console
3. run `catalog:validate` 
4. see _correct_ usage message
5. verify correctness by seeing the difference between running `catalog:validate --cql *` & `catalog:validate --cqlQuery *`:
[DDF-3100](https://codice.atlassian.net/browse/)
- ❗ …
=> DDF-3100 Corrected catalog:validate usage message

catalog/ui/catalog-ui-search/src/main/webapp/js/view/preferences/PreferencesModal.view.js, catalog/ui/catalog-ui-search/src/main/webapp/templates/preferences/layerPicker.handlebars
Map layer transparency values were being stored in the model with a range of 1-100.  However, the map expects a range of 0-1.  This resulted incorrect layer transparencies.  Updated the transparency value stored in the model accordingly.
@spearskw 
@bdeining 
@codice/ui 
1) Configure 1 or more map layers in the Intrigue UI configuration.
2) Verify that transparencies can be changed appropriately via map preferences
[DDF-3059](https://codice.atlassian.net/browse/DDF-3059) …
=> DDF-3059 corrected map layer transparency logic

catalog/core/catalog-core-commands/pom.xml, catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/CatalogCommands.java, catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/ExportCommand.java, catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/SubjectCommands.java, catalog/core/catalog-core-commands/src/test/groovy/org/codice/ddf/commands/catalog/ExportCommandSpec.groovy
- Removes `-d` delete alias from export command
- Short circuits trying to sign zip if nothing was exported
- Added unit tests for Export Command
@adimka @bdeining 
@coyotesqrl
@lessarderic
1. Ensure -d command has no conflicts
2. Ensure on an export with no metacards or content there are no errors in the log
https://codice.atlassian.net/browse/DDF-2698
=> DDF-2698 Remove -d alias from Export Command

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/ResourceOperations.java, catalog/core/catalog-core-standardframework/src/test/groovy/ddf/catalog/impl/operations/ResourceOperationsSpec.groovy, catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/impl/operations/ResourceOperationsTest.java
Fixes resource retrieval by uri when the uri has a fragment. 
Also refactored getResourceInfo method to address sonarqube findings
@coyotesqrl @mcalcote 
@kcwire
@shaundmorris
[DDF-3118](https://codice.atlassian.net/browse/DDF-3118)
=> DDF-3118 Fix resource retrieval by uri.

catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/TransformersCommand.java, catalog/core/catalog-core-commands/src/test/java/org/codice/ddf/commands/catalog/TransformersCommandTest.java, distribution/docs/src/main/jdocs/content/_running/console-commands-contents.adoc, distribution/docs/src/main/resources/_contents/_running/console-commands-contents.adoc
This is a new feature to assist the user in finding available transformers. It is called with `catalog:transformers`, and displays three details about each transformer:
- id
- schema
- mime-type (multiple values)
Schema & mime-type can have no values ("N/A"), but id must be included.
@vinamartin 
@emmberk 
@coyotesqrl 
@clockard
@coyotesqrl 
1. Build and run DDF
2. Load the catalog commands by setting up the Admin Console
3. In DDF, type in `catalog:transformers`
4. Review the output. Verify that the formatting is correct and that all of your available transformers are shown in the output.
5. Go to the Admin Console and select Catalog. In the features tab, uninstall some transformers and execute `catalog:transformers` again to see if the number of …
=> DDF-2486 Created a command to list active transformers (catalog:transformers)

distribution/ddf/src/main/filtered-resources/etc/org.apache.karaf.features.cfg
This PR removed the extra comma that was added to the end of the `featuresBoot` list in the `org.apache.karaf.feature.cfg` file because it is no longer needed.
@mcalcote @vinamartin @alexaabrd @josephthweatt 
@clockard
@lessarderic
- itests
- `/bin/ddf` script
[DDF-2132](https://codice.atlassian.net/browse/DDF-2132)
=> DDF-2132 Fixed tech debt in featuresBoot in org.apache.karaf.feature.cfg

catalog/catalog-app/pom.xml, catalog/catalog-app/src/main/resources/features.xml, catalog/plugin/catalog-plugin-security-audit/pom.xml, catalog/plugin/catalog-plugin-security-audit/src/main/java/org/codice/ddf/catalog/plugin/security/audit/SecurityAuditPlugin.java, catalog/plugin/catalog-plugin-security-audit/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/plugin/catalog-plugin-security-audit/src/main/resources/OSGI-INF/metatype/metatype.xml, catalog/plugin/catalog-plugin-security-audit/src/test/java/org/codice/ddf/catalog/security/audit/SecurityAuditPluginTest.java, catalog/plugin/pom.xml, distribution/docs/src/main/resources/_contents/_plugins/security-audit-plugin-contents.adoc, distribution/docs/src/main/resources/documentation.adoc, distribution/test/itests/test-itests-common/src/main/resources/metacard1.xml, distribution/test/itests/test-itests-common/src/main/resources/metacard2.xml, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/ContainerPerSuiteItestSuite.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestSecurityAuditPlugin.java
It migrates the security audit plugin from Alliance to DDF.
@tbatie @vinamartin @peterhuffer 
@coyotesqrl
@stustison
Ingest anything into the catalog and then change a security attribute (this is easier with the Catalog UI in DDF). Verify the change was audited.
https://codice.atlassian.net/browse/CAL-215
https://codice.atlassian.net/browse/CAL-315
https://codice.atlassian.net/browse/DDF-3096
=> DDF-3096 Migrates the security audit plugin from Alliance to DDF

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/QueryOperations.java, catalog/core/catalog-core-standardframework/src/test/groovy/ddf/catalog/impl/operations/QueryOperationsSpec.groovy
`QueryOperations.getNonVersionTagsFilter` did not include the "deleted" metacard-tag used by versioning metacards for deletions. This resulted in consecutive delete requests on a resource removing the versioning metacard. Adding the "deleted" metacard-tag to the filter should prevent those metacards from being included in the DeleteOperation's query request and getting deleted.
@rzwiefel 
@AzGoalie 
@mweser 
@jhunzik 
https://github.com/orgs/codice/teams/data
@clockard
@coyotesqrl 
Full build
[DDF-3119](https://codice.atlassian.net/browse/DDF-3119) …
=> DDF-3119 Add deleted tag for exclude version cards filter

distribution/test/itests/README.md, distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/AbstractIntegrationTest.java, distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/AdminConfig.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestEmbeddedSolr.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestSolrCommands.java
This PR fixes a regression from the Karaf upgrade to 4.1.1 that caused the `itestLogLevel` itest property to no longer work.
@mackncheesiest @Lambeaux @alexaabrd @josephthweatt @idperez 
@coyotesqrl
@clockard
- Confirm that the `itestLogLevel` and `securityLogLevel` itest properties work as expected. See `distribution/test/itest/README.md`.
- Test itests on downstream projects.
[DDF-2132](https://codice.atlassian.net/browse/DDF-2132) …
=> DDF-2132 Updated logging configuration in itests to work with log4j2

distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestSecurityAuditPlugin.java
Update the TestSecurityAuditPlugin wait conditions that were causing intermittent failures, noticed on several Windows builds.
@mcalcote 
@blen-desta 
@clockard
@coyotesqrl 
Run tests
Was causing build failures on local Windows machines and in Jenkins.
[DDF-3096](https://codice.atlassian.net/browse/DDF-3096)
=> DDF-3096 Update TestSecurityAuditPlugin wait conditions

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/UpdateOperations.java
Maps metacard IDs to metacards in the metacardMap in UpdateOperations in order to match with the UpdateRequest that gets rewritten in order to accomodate historian.
@rzwiefel 
@jhunzik 
@AzGoalie 
@coyotesqrl
@lessarderic
Full build
[DDF-3127](https://codice.atlassian.net/browse/DDF-3127)
=> DDF-3127 UpdateOperations metacardMap maps ids to metacards

distribution/test/itests/test-itests-ddf/pom.xml, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestPlatform.java, platform/platform-logging/src/main/java/org/codice/ddf/platform/logging/LogEvent.java, platform/platform-logging/src/test/java/org/codice/ddf/platform/logging/LogEventTest.java
This PR fixes the regression introduced by DDF-2132 that caused log entries levels to all appear as `UNKNOWN` in the logviewer.
@vinamartin @mcalcote @alexaabrd @josephthweatt @garrettfreibott 
@clockard
@figliold
Confirm that log levels show up correctly at the `/admin/logviewer/index.html` endpoint and under `System` >> `Logs` in the Admin Console.
`pax-logging` was upgraded to 1.9.1 in Karaf 4.1.1
[DDF-3117](https://codice.atlassian.net/browse/DDF-3117) …
=> DDF-3117 Fixed the logviewer log levels from all appearing as UNKNOWN

catalog/async/catalog-async-processingframework/src/main/resources/OSGI-INF/blueprint/blueprint.xml
This PR fixes a typo that set the threadpool size in the InMemoryProcessingFramework to 1 instead of `${org.codice.ddf.system.threadPoolSize}`.
@peterhuffer @troymohl 
@clockard
@kcwire
Confirm that the `catalog-async-inmemory` feature can be installed without any issues.
[DDF-3136](https://codice.atlassian.net/browse/DDF-3136)
=> DDF-3136 Fixed default threadpool size in the ProcessingFramework

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/history/Historian.java, catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/history/HistorianTest.java
This PR fixes an issue that was causing `UpdateStorageRequest`s to fail when the request contains only qualified content items.
@rzwiefel @peterhuffer @troymohl 
@codice/data 
@kcwire 
@clockard
Confirm build succeeds.
The asynchronous plugin API (https://github.com/codice/ddf/pull/1495) introduced motivation to submit an `UpdateStorageRequest` with only qualified content items.
[DDF-3135](https://codice.atlassian.net/browse/DDF-3135)
- ❗ …
=> DDF-3135 Fixed error when updating storage with only qualified content items

catalog/catalog-app/pom.xml, catalog/catalog-app/src/main/resources/features.xml, catalog/transformer/catalog-transformer-csv/pom.xml, catalog/transformer/catalog-transformer-csv/src/main/java/ddf/catalog/transformer/csv/ColumnHeaderIterator.java, catalog/transformer/catalog-transformer-csv/src/main/java/ddf/catalog/transformer/csv/CsvAttributeDescriptorComparator.java, catalog/transformer/catalog-transformer-csv/src/main/java/ddf/catalog/transformer/csv/CsvQueryResponseTransformer.java, catalog/transformer/catalog-transformer-csv/src/main/java/ddf/catalog/transformer/csv/MetacardIterator.java, catalog/transformer/catalog-transformer-csv/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/transformer/catalog-transformer-csv/src/test/java/ddf/catalog/transformer/csv/ColumnHeaderIteratorTest.java, catalog/transformer/catalog-transformer-csv/src/test/java/ddf/catalog/transformer/csv/CsvAttributeDescriptorComparatorTest.java, catalog/transformer/catalog-transformer-csv/src/test/java/ddf/catalog/transformer/csv/CsvQueryResponseTransformerTest.java, catalog/transformer/catalog-transformer-csv/src/test/java/ddf/catalog/transformer/csv/MetacardIteratorTest.java, catalog/transformer/pom.xml, distribution/docs/src/main/resources/_contents/_transformers/csv-query-response-transformer-contents.adoc, distribution/docs/src/main/resources/documentation.adoc, pom.xml
This change creates an implementation of QueryResponseTransformer that translates the results from metacards to CSV format. Front-end support for this
will be added in a separate story.
@gordocanchola (hero)
@brianfelix 
[UI](https://github.com/orgs/codice/teams/ui) (@andrewfielder)
[Data](https://github.com/orgs/codice/teams/data) (@brianfelix)
@jlcsmith
1) ingest some number of products.
2) perform an OpenSearch query and specify 'csv' as the output format 
Example: curl --basic --user admin:admin --insecure "https://localhost:8993/services/catalog/query?q=*&format=csv"
[DDF-3024](https://codice.atlassian.net/browse/DDF-3024)
=> DDF-3024 CSV Query Response Transformer

catalog/admin/admin-poller-service/src/main/java/org/codice/ddf/catalog/admin/poller/AdminPollerServiceBean.java, catalog/spatial/registry/registry-federation-admin-impl/src/main/java/org/codice/ddf/registry/federationadmin/impl/AdminHelper.java, platform/admin/core/admin-core-api/src/main/java/org/codice/ddf/admin/core/api/ConfigurationAdmin.java, platform/admin/core/admin-core-impl/src/main/java/org/codice/ddf/admin/core/impl/ConfigurationAdminImpl.java, platform/admin/core/admin-core-impl/src/test/java/org/codice/ddf/admin/core/impl/ConfigurationAdminImplTest.java
When creating a new source from the sources tab, other options showed up that were not sources (see attached screenshot). This PR keeps only the sources from appearing
@vinamartin 
@emmberk 
@clockard 
@stustison
1. Build DDF and go to the Admin UI
2. Open the Catalog application, then select the Sources tab
3. Select Add Source, verify that the only options in the **Source Type** dropdown box are sources. 
[DDF-3112](https://codice.atlassian.net/browse/) …
=> DDF-3112 When creating a new source from the sources UI, other options show up that are not sources

distribution/ddf-common/src/main/resources/etc/log4j2.config.xml, distribution/ddf-common/src/main/resources/etc/org.ops4j.pax.logging.cfg, distribution/docs/src/main/jdocs/content/_configuring/auditing-contents.adoc, distribution/docs/src/main/resources/_contents/_securing/auditing-contents.adoc
Adds failover log back to logging configuration.
With the Karaf upgrade, there is an issue with the pax logging configuration that makes it unavailable to use through our default configuration, however, when using the log4j2.config.xml file failover seems to be functional (though errors populate the log). 
@emmberk 
@Lambeaux 
@pklinef 
@coyotesqrl 
@clockard
@lessarderic
- Create a disk image and mount it (Here's an example of how to do so on a mac: https://support.apple.com/kb/PH22247?locale=en_US&viewlocale=en_US)
- Unzip the DDF
- Configure the DDF's logging configuration per the documentation and setup the `securityMain` appender to write to a log file inside of the disk image
- Start up the DDF 
- Verify …
=> DDF-3073 Adds failover log back to logging config

catalog/core/catalog-core-directorymonitor/pom.xml
Disables the directory monitor component tests until #2090 adds port randomization.
@mcalcote @AzGoalie 
@clockard
@lessarderic 
Build catalog-core-directorymonitor and verify the component tests do not run.
This issue was causing the tests to fail to startup on the nightlies, rendering them unstable in jenkins.
[DDF-3105](https://codice.atlassian.net/browse/DDF-3105) …
=> DDF-3105 Temporarily disable CDMIT

catalog/core/catalog-core-api-impl/pom.xml, catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/util/impl/CatalogQueryException.java, catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/util/impl/QueryFunction.java, catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/util/impl/ResultIterable.java, catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/util/impl/ResultListIterable.java, catalog/core/catalog-core-api-impl/src/test/groovy/ddf/catalog/util/impl/ResultIterableSpec.groovy, catalog/core/catalog-core-api-impl/src/test/groovy/ddf/catalog/util/impl/ResultListIterableSpec.groovy, catalog/core/catalog-core-api/src/main/java/ddf/catalog/CatalogFramework.java, catalog/core/catalog-core-commands/pom.xml, catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/ExportCommand.java, catalog/core/catalog-core-commands/src/test/groovy/org/codice/ddf/commands/catalog/ExportCommandSpec.groovy
Provides two generic `Iterable` classes that can be used to iterate over all the results returned by the catalog framework regardless of any page size limitations enforced. The iterations can be done one `Result` at a time or in batches.
@mweser 
@rzwiefel 
@ahoffer 
@coyotesqrl
@pklinef
These classes are not currently used so a simple passing build is sufficient.
These utilities are needed to address many potential paging problems that currently exist in the application.
[DDF-3034](https://codice.atlassian.net/browse/DDF-3034) …
=> DDF-3034 Provide a generic utility class to page through catalog framework query results

catalog/catalog-app/src/main/resources/features.xml, catalog/core/catalog-core-backupplugin/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/core/catalog-core-backupplugin/src/main/resources/OSGI-INF/metatype/metatype.xml, distribution/docs/src/main/jdocs/content/_configuring/managing-certificates-contents.adoc, distribution/docs/src/main/jdocs/content/_running/ingesting-contents.adoc, distribution/docs/src/main/resources/_contents/_catalog-contents/managing-catalog-contents.adoc, distribution/docs/src/main/resources/_contents/_plugins/catalog-backup-plugin-contents.adoc, distribution/docs/src/main/resources/_contents/_running/ingesting-contents.adoc, distribution/docs/src/main/resources/_contents/_securing/managing-certificates-contents.adoc, distribution/docs/src/main/resources/_contents/_tables/conf-ddf.catalog.backup.CatalogBackupPlugin-table-contents.adoc, distribution/docs/src/main/resources/_contents/_tables/conf-plugin.backup-table-contents.adoc, distribution/docs/src/main/resources/_contents/_tables/ddf.catalog.backup.CatalogBackupPlugin-table-contents.adoc, distribution/docs/src/main/resources/_contents/_tables/plugin.backup-table-contents.adoc, distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/AbstractIntegrationTest.java
Removes the `enableBackupPlugin` configuration option and leaves the catalog backup plugin uninstalled by default. Renames references to the plugin in the documentation to "Catalog Backup Plugin".
@ahoffer 
@ryeats 
@idperez 
@ricklarsen 
@clockard 
@jaymcnallie
Build DDF, start it up, and verify that the catalog backup plugin is not installed.
Our documentation states that the plugin is not installed for performance reasons but in reality it is installed by default.
[DDF-2995](https://codice.atlassian.net/browse/DDF-2995) …
=> DDF-2995 Make the catalog backup plugin uninstalled by default

dependency-check-maven-config.xml
Adds in new suppression for geowebcache which breaks the build.
A similar change was made here: https://github.com/codice/alliance/commit/6253941a70c5809a635cba12dd624d253fb86fb7
@mcalcote @clockard @josephthweatt 
@clockard 
@coyotesqrl 
=> DDF-3054 Updates geowebcache owasp suppresions

distribution/ddf-common/src/main/resources/etc/org.ops4j.pax.web.cfg, distribution/docs/src/main/jdocs/content/_configuring/configuring-jetty-threadpool-from-admin-console.contents.adoc, distribution/docs/src/main/jdocs/content/_configuring/configuring-jetty-threadpool-from-command-console.contents.adoc, distribution/docs/src/main/jdocs/content/_configuring/configuring-jetty-threadpool-settings-config-contents.adoc, distribution/docs/src/main/resources/_contents/_configuring/configuring-jetty-threadpool-from-admin-console.contents.adoc, distribution/docs/src/main/resources/_contents/_configuring/configuring-jetty-threadpool-from-command-console.contents.adoc, distribution/docs/src/main/resources/_contents/_configuring/configuring-jetty-threadpool-settings-config-contents.adoc, distribution/docs/src/main/resources/_contents/_configuring/configuring-threadpool-from-admin-console.contents.adoc, distribution/docs/src/main/resources/_contents/_configuring/configuring-threadpool-from-command-console.contents.adoc, distribution/docs/src/main/resources/_contents/_configuring/configuring-threadpool-settings-config-contents.adoc, distribution/docs/src/main/resources/documentation.adoc, platform/platform-paxweb-jettyconfig/src/main/resources/jetty.xml, pom.xml
DDF-3146 Updated the version of Jetty in the root pom
**platform-paxweb-jettyconfig** should have a threadpool to handle multiple concurrent updates without causing a resource shortage. Currently, concurrent updates can cause user applications to function slowly or not at all.
This PR changes the ThreadPool's minimum & maximum threads as well as the idle timeout time (see org.ops4j.pax.web.cfg).
@ricklarsen 
@emmberk 
@rzwiefel 
@clockard 
@stustison 
The issue can be tested by running the **concurrent_updates_test.py** script [provided here](https://codice.atlassian.net/secure/attachment/18000/concurrent_updates_test.py). Before running you will need to run `pip3 install urllib3`. Run the script with python3 and note the output. The output should be: …
=> DDF-3146 Add Threadpool to Jetty Configuration

catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/XstreamPathConverter.java, catalog/spatial/csw/spatial-csw-transformer/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/TestXstreamPathConverter.java
Fix bug that prevented multiple repeated xml elements from being returned to the caller.
@bdeining 
@troymohl 
@coyotesqrl 
@lessarderic
@millerw8
Run tests and itests. A unit test was added to reproduce the bug.
[DDF-3154](https://codice.atlassian.net/browse/DDF-3154)
=> DDF-3154 Fix bug related to multiple repeated xml elements

catalog/ui/catalog-ui-search/webpack/config/dev.js
Bring back the ability to log in while using the webpack dev proxy.
@djblue @SmithJosh 
@bdeining
Install DDF. Run `npm start`. In a fresh session, go to `http://localhost:8080` and verify you can login.
[DDF-3159](https://codice.atlassian.net/browse/DDF-3159) …
=> DDF-3159 Add proxy http login

catalog/ui/search-ui-app/src/main/resources/features.xml
Catalog-search-ui has an implicit dependency on the spatial-app, which can cause it to fail during installation if it is initialized first. 
This change declares the spatial-app feature as a dependency of the catalog-ui feature.
@bdeining 
@millerw8
@pklinef
Installation with standard profile should complete successfully - both spatial-app and catalog search ui should be installed.
https://codice.atlassian.net/browse/DDF-3069
=> DDF-3069 Fix loading issues for catalog-ui-search

catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/util/impl/ResultIterable.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/MetacardApplication.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/associations/Associated.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/util/EndpointUtil.java, catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/util/EndpointUtilTest.java
Uses ResultIterable to retrieve Metacards from the catalog. After DDF-2782, there was a possibility of a user only receiving a subset of the actual results.
@mweser 
@emmberk 
@clockard 
@coyotesqrl 
1. Build DDF and unzip
2. Before running DDF, edit the **setenv** inside **ddf-2.11.0-SNAPSHOT/bin** so that the last line reads: `export JAVA_OPTS=-"server -Dcatalog.maxPageSize=3 .......`
3. Run DDF
4. In DDF's terminal, install the Catalog UI using `feature:install catalog-ui`
5. Ingest a metacard through Catalog UI
6. Using the Catalog UI, select the metacard and expand it. In the details tab, make four changes to the title. Save after every change
7. Select the History tab, verify that there are four changes to the metacard …
=> DDF-3161 Results displayed by Intrigue can be incomplete because the Catalog UI endpoint doesn't handle paging

catalog/ui/catalog-ui-search/src/main/webapp/component/location-old/location-old.view.js
Disables shape editing in Intrigue when query editing is disabled
@albany551 
@bdeining 
@millerw8
@pklinef 
Create a query with a shape and save.
Attempt to edit the shape definition. Switch types. Shape editing should be disabled.
https://codice.atlassian.net/browse/DDF-3176 …
=> DDF-3176 Disable shape editing when query editing is disabled.

platform/admin/ui/src/main/webapp/js/views/Modal.js
Forces users to click OK to dismiss System Usage modal
@vinamartin 
@emmberk 
@mcalcote 
@clockard
When System Usage modal appears in the ADMIN console, attempt to click everywhere besides OK and see that you can only click OK to dismiss the Modal. 
[DDF-3170](https://codice.atlassian.net/browse/) …
=> DDF-3170 Require users to push OK button on System Usage Modal to exit

distribution/ddf-common/src/main/resources/etc/log4j2.config.xml, distribution/ddf-common/src/main/resources/etc/org.ops4j.pax.logging.cfg, platform/security/platform-security-core-api/pom.xml, platform/security/platform-security-core-api/src/main/java/ddf/security/common/audit/LogFailoverAlertAppender.java, platform/security/platform-security-core-api/src/main/resources/OSGI-INF/blueprint/blueprint.xml
Alerts admins when failover logging fails. 
_Original PR_ : 
[DDF-2912 Implemented System Administrator Alerts](https://github.com/codice/ddf/pull/1829) by @emmberk 
_Changes_: 
Log4j2 formatting is different from Log4j
Had to add in a time check to the appender because of how fast the logs come in
_Must be built using_ : 
[DDF 3128 Add Decanter and alert/solr appenders base for future expansion](https://github.com/codice/ddf/pull/2130) by @clockard 
[DDF 3143 Update alerting in the admin UI](https://github.com/codice/ddf/pull/2141) by @clockard 
@emmberk @clockard @ahoffer @josephthweatt 
@clockard
@figliold 
Follow the directions here: https://github.com/codice/ddf/pull/2131
but while configuring the log4j2.config.xml config, also configure the failover appender look like the following: …
=> DDF-3169 Adds alerts for failover log failure

catalog/core/catalog-core-api/src/main/java/ddf/catalog/content/operation/ContentMetadataExtractor.java, catalog/transformer/catalog-transformer-pdf/pom.xml, catalog/transformer/catalog-transformer-pdf/src/main/java/ddf/catalog/transformer/input/pdf/PdfInputTransformer.java, catalog/transformer/catalog-transformer-tika-input/pom.xml, catalog/transformer/catalog-transformer-tika-input/src/main/java/ddf/catalog/transformer/input/tika/TikaInputTransformer.java, catalog/transformer/catalog-transformer-tika-input/src/test/java/ddf/catalog/transformer/input/tika/TikaInputTransformerTest.java
Updates the `ContentMetadataExtractor` with a new `process` method that can work directly with `InputStream`s.
Also updates the `TikaInputTransformer` to use this new method instead of generating Strings.  
This PR is based off the changes for DDF-3178 in #2164
@ahoffer @rzwiefel 
@clockard
@jlcsmith
@stustison
Ingest of large text files should be determined to require less heap and GC less frequently.
N/A
[DDF-3177](https://codice.atlassian.net/browse/DDF-3177)
[DDF-3178](https://codice.atlassian.net/browse/DDF-3178)
N/A …
=> DDF-3177 Adds a process method for content metadata that takes a stream.

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/CreateOperations.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/OverrideAttributesSupport.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/UpdateOperations.java, catalog/core/catalog-core-standardframework/src/test/groovy/ddf/catalog/impl/operations/CreateOperationsSpec.groovy, catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/impl/operations/OverrideAttributesSupportTest.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalog.java
Fixes attribute overrides to make them applied on content directory monitor file monitored file updates.
@AzGoalie 
@clockard 
@stustison
1. Ingest a file with an attribute override set. (ie contact.creator-name)
2. Modify the file, including a value that will change the overridden attribute (ie a metacard with contact.creator-name set to something else)
3. Let the CDM update the metacard and verify that the attribute is still overridden
Original PR: https://github.com/codice/ddf/pull/1953
[DDF-2979](https://codice.atlassian.net/browse/DDF-2979) …
=> DDF-2979 Apply attribute overrides in CDM updates

broker/broker-undelivered-messages-ui/src/main/java/org/codice/ddf/broker/ui/UndeliveredMessages.java, broker/broker-undelivered-messages-ui/src/test/java/org/codice/ddf/broker/ui/UndeliveredMessagesTest.java, distribution/ddf-common/src/main/resources/etc/artemis-backup.xml, distribution/ddf-common/src/main/resources/etc/artemis.xml, distribution/sdk/artemis-sandbox/pom.xml
This PR fixes a bug that would prevent the UndeliveredMessagesMbean from being registered if the system hostname was not localhost. For more Information see: https://codice.atlassian.net/browse/DDF-3179
-Changed the Artemis broker name to "artemis"
-The Artemis ObjectName created in the UndeliveredMessagesMbean now uses "artemis" as the broker name instead of the system hostname
-Added missing dependencies to fix sdk example routes
@ryeats 
@jrnorth 
@clockard
@jaymcnallie
-Run a full build, all itests should pass.
-Change the system hostname to something other than "localhost", verify the UndeliveredMessagesMbean is …
=> DDF-3179 UndeliveredMessagesMbean operations can be executed regardless of the system hostname value

catalog/spatial/geocoding/spatial-geocoding-geocoder/src/main/resources/OSGI-INF/blueprint/blueprint.xml
I left out a service reference on the GeoCoder bean when I rearranged its underlying interfaces for the keyword search feature.
Currently this causes an NPE when you import a document and the GeoCoder plugin gets used to find the country code based on the document's location data.
@bdeining 
@troymohl 
@bdeining
@millerw8
Ingest document(s) with location data and check that they are properly geo-located.
Ensure that there aren't any NPEs in the Karaf log.
https://codice.atlassian.net/browse/DDF-3069
=> DDF-3069 Fix service reference in geocoder plugin

catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/DumpCommand.java, catalog/core/catalog-core-commands/src/test/java/org/codice/ddf/commands/catalog/DumpCommandTest.java
-Prevents DDF from shutting down when transform fails
-Changes counter to correctly display the results that were dumped (Prints out 0 file(s) dumped in 0 seconds when a failure happens)
-Does not create a blank file when transform fails
@emmberk @bdeining @kcrowe01 
@clockard
@coyotesqrl
Ingest some data that is known not to be transformable using one of the transformers. 
Run the `catalog:dump` command with the transformer option and give it a transformer that will fail. Verify that the DDF doesn't shut down, no files are written to the dump location, and a message saying 0 files were dumped is printed to the console. 
[DDF-3116](https://codice.atlassian.net/browse/DDF-3116) …
=> DDF-3116 Fixes bugs with catalog:dump when transform fails

distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestSingleSignOn.java, platform/security/idp/security-idp-client/src/main/java/org/codice/ddf/security/idp/client/IdpMetadata.java, platform/security/idp/security-idp-server/pom.xml, platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/server/IdpEndpoint.java, platform/security/platform-security-core-api/src/main/java/ddf/security/samlp/MetadataConfigurationParser.java, platform/security/platform-security-core-api/src/test/java/ddf/security/samlp/MetadataConfigurationParserTest.java
Previously, these operations occurred on injection of the metadata locators. That led to an intermittent timing issue, as the two bundles cross-query HTTP endpoints. Now, they execute the queries and parse the data once, on initial access. This allows both services to be fully initialized before any queries are executed.
This change also includes some minor cleanup to the `MetadataConfigurationParser` class. That cleanup had been associated with an earlier approach to resolving the timing issue and is not necessary; however, it does make for smaller, more concise methods.
@rzwiefel @tbatie @oconnormi 
@pklinef
@stustison
As this …
=> DDF-3167 Changes the timing for the IdP server & client initialization of metadata.

catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/RemoveAllCommand.java, catalog/core/catalog-core-commands/src/test/java/org/codice/ddf/commands/catalog/RemoveAllCommandTest.java
Fixes issue with RemoveAll command where not all metacards are deleted when the batchSize is greater than the page size the catalog framework uses. 
@ahoffer @emanns95 @emmberk @jhunzik  @josephthweatt 
@bdeining
@coyotesqrl
Running a build with itests and unit tests ought to be sufficient to verify correctness.
Catalog Framework maintains an internal page size, but not all commands function with an awareness of this. Therefore, paging has to be accounted for.
[](https://codice.atlassian.net/browse/3144) …
=> DDF-3144 Fix removeAll command not deleting all metacards when batchSize exceeds catalog page size

catalog/admin/module/catalog-admin-module-maplayers/src/main/webapp/map-layers/index.js, catalog/admin/module/catalog-admin-module-maplayers/src/main/webapp/map-layers/reducer.js
- Allowed empty string `imageryProviders` configuration to be processed
without error.
- Typo fix.
@tbatie 
@bdeining 
@clockard
Set `imageryProviders` intrigue configuration to empty string. Verify the an error modal does not pop up.
[DDF-3189](https://codice.atlassian.net/browse/DDF-3189)
=> DDF-3189 minor map-layers fixes

distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/csw/CswTestCommons.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalog.java
Adds support for files with XML header declarations to CswTestCommons.getCswInsertRequest
@brianfelix @glenhein @emanns95 
https://github.com/orgs/codice/teams/test
@bdeining
@millerw8
Full build for verification that no regressions were introduced
In its current state, an XML file with the header gets substituted into the CSW insert request along with the header, and the parsing logic throws an exception because an XML header occurs somewhere other than at the start of the file.
[DDF-3173](https://codice.atlassian.net/browse/DDF-3173) …
=> DDF-3173 Added support for cleaning up XML declarations in getCswInsertRequest iTest utility

Jenkinsfile
Added `-DretryFailedDeploymentCount=10` to the deploy command
@oconnormi @clockard @shaundmorris @LinkMJB 
@codice/build 
This change matches the command used in the legacy jenkins deploy jobs.
=> DDF-2969 Update deploy command to retry failed deployments

platform/platform-filter-delegate/pom.xml, platform/platform-filter-delegate/src/main/java/org/codice/ddf/platform/filter/delegate/DelegateServletFilter.java, platform/platform-filter-delegate/src/main/java/org/codice/ddf/platform/filter/delegate/FilterInjector.java, platform/platform-filter-delegate/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/platform-filter-delegate/src/test/java/org/codice/ddf/platform/filter/delegate/DelegateServletFilterTest.java
This PR fixes the issue that restarting DDF caused some servlets to be missing the `SecurityFilter`s added in https://github.com/codice/ddf/commit/8c330bab9cf7c5e247b020beba115b60b6f66129.
@mcalcote @Lambeaux @vinamartin 
@clockard
@coyotesqrl
1. Install DDF. You shouldn't see any log messages like, 
```
Bundle platform-filter-delegate/2.11.0.SNAPSHOT is waiting for dependencies...
```
or
```
Could not inject DelegateServletFilter into xxxxx because the servlet was already initialized.
```
2. Restart DDF. Again, you shouldn't see any of those log messages.
3. Confirm that ingesting from Intrigue works.
[DDF-2863](https://codice.atlassian.net/browse/DDF-2863) …
=> DDF-2863 Added optional flag to the SecurityFilters list in the DelegateServletFilter

distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestSingleSignOn.java, platform/security/idp/security-idp-client/src/main/java/org/codice/ddf/security/idp/client/IdpMetadata.java, platform/security/idp/security-idp-server/pom.xml, platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/server/IdpEndpoint.java, platform/security/idp/security-idp-server/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/security/idp/security-idp-server/src/main/resources/OSGI-INF/metatype/metatype.xml, platform/security/idp/security-idp-server/src/main/resources/templates/login.handlebars, platform/security/platform-security-core-api/src/main/java/ddf/security/samlp/MetadataConfigurationParser.java, platform/security/platform-security-core-api/src/test/java/ddf/security/samlp/MetadataConfigurationParserTest.java
**Backport**
Previously, these operations occurred on injection of the metadata locators. That led to an intermittent timing issue, as the two bundles cross-query HTTP endpoints. Now, they execute the queries and parse the data once, on initial access. This allows both services to be fully initialized before any queries are executed.
This change also includes some minor cleanup to the `MetadataConfigurationParser` class. That cleanup had been associated with an earlier approach to resolving the timing issue and is not necessary; however, it does make for smaller, more concise methods.
@rzwiefel @tbatie @oconnormi 
@pklinef
@stustison …
=> DDF-3167 [2.10.x] Changes the timing for the IdP server & client initialization of metadata.

platform/admin/admin-app/pom.xml, platform/admin/admin-app/src/main/resources/features.xml, platform/admin/admin-configuration-configinstaller/pom.xml, platform/admin/admin-configuration-configinstaller/src/main/java/org/codice/ddf/admin/configuration/ConfigurationInstaller.java, platform/admin/admin-configuration-configinstaller/src/main/java/org/codice/ddf/admin/configuration/FelixConfig.java, platform/admin/admin-configuration-configinstaller/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/admin/admin-configuration-configinstaller/src/test/java/org/codice/ddf/admin/configuration/ConfigurationInstallerTest.java, platform/admin/admin-configuration-configinstaller/src/test/java/org/codice/ddf/admin/configuration/FelixConfigTest.java, platform/admin/configurator/admin-configurator-actions-api/src/main/java/org/codice/ddf/internal/admin/configurator/actions/ConfigActions.java, platform/admin/configurator/admin-configurator-impl/src/main/java/org/codice/ddf/admin/configurator/impl/ConfigOperation.java, platform/admin/configurator/admin-configurator-impl/src/main/java/org/codice/ddf/admin/configurator/impl/ConfigValidator.java, platform/admin/configurator/admin-configurator-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/admin/pom.xml
Provides a SynchronousConfigurationListener that will delete config files in etc if the config in config admin was deleted as well. Also takes into consideration inconsistent management of the felix file install property. Should that property fail to be tracked, the file in etc is removed as well. 
@paouelle @brjeter @oconnormi 
@coyotesqrl (for configurator changes)
@beyelerb (for admin team)
Admin Team (not yet created on GH)
@figliold 
@shaundmorris
Delete some configurations from the admin UI that have corresponding files in etc and ensure the files are deleting along with them. 
Known issue: In the admin UI you may  need to delete a configuration twice for it to truly be gone. 
This change is a necessary fix to support …
=> DDF-3148 Deleting configs in ConfigAdmin also deletes the corresponding files in etc

catalog/core/catalog-core-commands/src/test/java/org/codice/ddf/commands/catalog/SeedCommandTest.java, catalog/ui/catalog-ui-search/pom.xml
The current implementation of the catalog:seed command takes a maximum number of resources to download and uses that number to page through the results:
https://github.com/codice/ddf/blob/088e81f76c19291ba3a6e953b25700b08bb217db/catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/SeedCommand.java#L115-L119
Now that   DDF-2872  has been added to address potential Solr and security problems, the number of results returned is limited to a maximum, which means that the command could skip some resources when it needs to page because of some download failures or already cached resources.
This PR added a unit test to verify that results would not be skipped.
@mweser 
@vinamartin 
@jhunzik 
@clockard 
@bdeining 
1. Build DDF & …
=> DDF-3166 Add Unit Test to Ensure catalog:seed Does Not Skip Resources

catalog/ui/catalog-ui-search/src/main/webapp/component/query-basic/query-basic.view.js
The intrigue UI always adds a wildcard contextual parameter. There does not appear to be any way to perform a strictly temporal or location-based search.
This PR makes it so that the wildcard is only in the query when no other specifications have been given.
@djblue 
@emmberk 
@rzwiefel 
@vinamartin 
@clockard
@coyotesqrl 
1. Build & run DDF. Install the catalog commands through admin.
2. Go to intrigue and create the following searches:
- An empty search with no parameters specified. When you save this search, you should see the text field with a wildcard (*) in its place
- A temporal search. Only specify the time range of the search. Here, the text field should be blank.
- A type search. Only specify the type of information you are …
=> DDF-3191 Intrigue incorrectly adds wildcards to all queries by default

catalog/admin/admin-poller-service/src/main/java/org/codice/ddf/catalog/admin/poller/AdminPollerServiceBean.java, catalog/admin/admin-poller-service/src/test/java/org/codice/ddf/catalog/admin/poller/AdminPollerTest.java
Fixes a npe by checking if the service or factory pid contains _disabled
@vinamartin @josephthweatt @mcalcote 
@coyotesqrl
@figliold
Startup DDF and add a secondary local node with a federation service and a couple of endpoints. 
Verify that it shows up in the sources tab with the endpoint types you added. Check the log and verify that there isn't any log message that look like `10:53:56,144 | INFO  | tp1725158859-118 | admin-poller-service | Error getting source info: null`
[DDF-3036](https://codice.atlassian.net/browse/DDF-3036) …
=> DDF-3036 Fix NPE caused by looking up properties on disabled configurations

platform/io/platform-io-impl/pom.xml, platform/io/platform-io-impl/src/main/java/org/codice/ddf/platform/io/CfgStrategy.java, platform/io/platform-io-impl/src/main/java/org/codice/ddf/platform/io/ConfigStrategy.java, platform/io/platform-io-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/io/platform-io-impl/src/test/java/org/codice/ddf/platform/io/CfgStrategyTest.java, platform/io/platform-io-impl/src/test/java/org/codice/ddf/platform/io/ConfigStrategyTest.java, platform/io/platform-io-internal-api/pom.xml, platform/io/platform-io-internal-api/src/main/java/org/codice/ddf/platform/io/internal/PersistenceStrategy.java, platform/io/pom.xml, platform/pom.xml
Provides a lightweight, internal API for writing to config files. Each service implementation supports a different format. 
Both the configurator service and import / export operations can leverage these services. Other areas in the admin app could eventually leverage these as well. 
Moved PersistenceStrategy from migration to platform io where it can be reused
**WIP**: Made the platform io module, but still need to get rid of the leftovers in platform-migration. Also need to consider other test cases. 
Publish strategies will use the file extension supported by each impl as a service property. 
@paouelle 
@brjeter 
@oconnormi 
@coyotesqrl 
Admin Team (not yet listed) - @beyelerb
@figliold 
@shaundmorris
TBD
TBD
https://codice.atlassian.net/browse/DDF-3186 …
=> DDF-3186 Created internal api for reading and writing configs in various formats

platform/admin/ui/src/main/webapp/js/views/Alerts.view.js, platform/admin/ui/src/main/webapp/templates/alerts.handlebars
Fixes alerting for configurations dialogs in admin ui
@emmberk @mcalcote  
@bdeining
@shaundmorris
Install DDF and enter and save an invalid configuration (Platform->Configuration->Metrics Reporting->Metrics Max Threshold = asdf). Verify that the alert you receive doesn't show the dismiss button or the host name. It should look something like
Export error should look something like
Verify that the admin-ui level alerting still works as before. See testing steps on https://github.com/codice/ddf/pull/2141
Alerting was updated a few weeks ago but the invalid configuration aspect wasn't handled.
[DDF-3143](https://codice.atlassian.net/browse/DDF-3143) …
=> DDF-3143 Fix alerting for configuration dialogs.

catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/util/impl/SourcePollerRunner.java, catalog/spatial/csw/spatial-csw-source-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/AbstractCswSource.java, catalog/spatial/registry/registry-api-impl/src/main/java/org/codice/ddf/registry/api/impl/RegistryStoreImpl.java, catalog/spatial/registry/registry-api-impl/src/test/java/org/codice/ddf/registry/api/impl/TestRegistryStore.java
Update RegistryStore to ensure availability only when connected to a registry.
Also updated SourcePollerRunner.unbind() method to protect against NPEs.
@mcalcote @emmberk @vinamartin 
@bdeining
@figliold
@shaundmorris
Install two DDF and install the registry app. For DDF A create a secondary node and then delete the identity node using the command `catalog:remove -p --cql "title like 'DDF-A'"` where DDF-A is the name of DDF A's identity node. On DDF B create a remote registry connection to DDF A and verify that the remote registry never shows up as available. Using bundle start/stop from the console, stop and restart the bundle registry-federation-admin-service-impl on DDF A. This should recreate the identity node. DDF B remote registry connection …
=> DDF 3199 Update RegistryStore to ensure availability only when connected to a registry

catalog/ui/catalog-ui-search/src/main/webapp/component/visualization/maps/cesium/geocoder.js, catalog/ui/catalog-ui-search/src/main/webapp/component/visualization/maps/cesium/map.cesium.js
This PR ports over a fix for the gazetteer search bar in Intrigue. 
@clockard @djblue @vinamartin @alexaabrd 
@jlcsmith
_Out-of-the-box DDF_
- Search for some known locations, and confirm that the search box offers suggestions and auto-completes the full location.
- Search for some random/unknown locations, and confirm that the gazetteer tries to find the best match for the search terms or shows a `(not found)` message. The box should not show `Searching ...` indefinitely.
- Confirm using the search box offline works as well.
_DDF using the `offline-gazetteer`_
- Follow the documentation to enable and configure the `offline-gazetteer`.
- Repeat test steps above to confirm …
=> DDF-2850 Fixed Intrigue gazetteer search

catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/ECQLMapperVisitor.java, catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/PropertyMapperVisitor.java, catalog/spatial/csw/spatial-csw-common/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/common/PropertyMapperVisitorTest.java, catalog/spatial/csw/spatial-csw-source-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/CswCqlTextFilter.java
Update CswCqlTextFilter to work with ECQL keyword restrictions. The PropertyMapperVisitor/ECQLMapperVisitor were added to accomplish this.
@kcrowe01 @emmberk @vinamartin @AzGoalie 
@coyotesqrl
@figliold
Install two DDF with registry with certs (dev=true). Create a connection from one to the other via the remote registry tab using all the default options. Verify that the node you are connecting to gets the sending node entry in the Node Information tab. Once this is verified go back to the remote registries tab and open up the registry connection. Turn off the auto push option. Verify that the node you are connected to no longer has the sending node in the Node Information tab (It could take a few seconds for it to be …
=> DDF-3071 Update CswCqlTextFilter to work with ECQL keyword restrictions

distribution/ddf-common/src/main/resources/etc/shell.init.script
Fixes the number of bundle fragments `waitForReady` waits for to account for the newly added `platform-crypto-provider` fragment
@clockard
@coyotesqrl
=> DDF-3187 Fixes waitForReady to account for new fragment

catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/content/operation/impl/CreateStorageResponseImpl.java, catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/CatalogCommands.java, catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/ImportCommand.java, catalog/core/catalog-core-commands/src/test/groovy/org/codice/ddf/commands/catalog/ExportCommandSpec.groovy, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/history/Historian.java, catalog/core/catalog-core-versioning/versioning-common/src/main/java/ddf/catalog/core/versioning/impl/MetacardVersionImpl.java, catalog/ui/catalog-ui-enumeration/src/main/java/org/codice/ddf/catalog/ui/enumeration/ExperimentalEnumerationExtractor.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/cql/CqlQueryResponse.java, catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/ui/catalog-ui-search/src/main/webapp/js/model/Metacard.js
- Updated logging in Historian
- Updated logging in CqlQueryResponse
- Fixed missing implicit dependencies on Injected Attributes
- Added to string to CreateStorageResponseImpl
- Fixed CatalogCommands getUserInputModifiable
- Accounts for Windows Systems now. 
- Removed changed assumptions in MetacardVersionImpl
- Previously we relied on MetacardTypes not changing. However they can and do 
change now. So we have opted to always serialize the MetacardType (but did
add caching to prevent the serialization overhead).
- Fixed model/Metacard.js re-query on archive/restore
anyone
@coyotesqrl
@bdeining 
https://codice.atlassian.net/browse/DDF-3188 …
=> DDF-3188,3123 Improved logging in Intrigue and Historian + misc. fixes

catalog/resourcemanagement/resourcemanagement-querymonitor-ui/pom.xml, catalog/resourcemanagement/resourcemanagement-querymonitor-ui/src/main/webapp/main.js, catalog/resourcemanagement/resourcemanagement-usage-ui/pom.xml, catalog/resourcemanagement/resourcemanagement-usage-ui/src/main/webapp/main.js, catalog/spatial/geocoding/spatial-geocoding-admin-module/pom.xml, catalog/spatial/geocoding/spatial-geocoding-admin-module/src/main/webapp/main.js, catalog/spatial/geowebcache/geowebcache-admin-plugin/pom.xml, catalog/spatial/geowebcache/geowebcache-admin-plugin/src/main/webapp/main.js, catalog/ui/search-ui/standard/pom.xml, catalog/ui/search-ui/standard/src/main/webapp/main.js, platform/admin/modules/admin-security-certificate-ui/pom.xml, platform/admin/modules/admin-security-certificate-ui/src/main/webapp/main.js
The 2.4.7 Marionette webjar added a wildcard to its pom.xml for its backbone dependency, which breaks windows builds. This downgrades all Marionette webjars to 2.4.5, which doesn't have a wildcard.
@djblue 
@emanns95 
@pklinef
Build should succeed.
https://codice.atlassian.net/browse/DDF-3103
=> DDF-3103 Downgrade Marionette to 2.4.5 to avoid Windows build issue

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/OperationsMetacardSupport.java, catalog/core/catalog-core-standardframework/src/test/groovy/ddf/catalog/impl/operations/OperationsMetacardSupportSpec.groovy, catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/impl/CatalogFrameworkImplTest.java, catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/impl/FanoutCatalogFrameworkTest.java, distribution/ddf-common/src/main/resources/etc/system.properties, distribution/docs/src/main/jdocs/content/_configuring/configuring-global-settings-contents.adoc, distribution/docs/src/main/resources/_contents/_configuring/configuring-global-settings-contents.adoc, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalog.java, platform/util/platform-util/pom.xml, platform/util/platform-util/src/main/java/org/codice/ddf/platform/util/InputValidation.java, platform/util/platform-util/src/test/java/org/codice/ddf/platform/util/InputValidationTest.java
- Fix the issue where mime type improperly used the original filename and overwrote the sanitized filename.
- Fix a bug where if `files.bad`, `files.bad.extension` in `system.properties` contained any capitalization, to-be sanitized files would not be properly identified
- Minor refactoring of `generateMetacardAndContentItems()`
- Add ability to ignore files (`ignore.files` in `system.properties`)
- Update documentation as needed
@ahoffer 
@emanns95 
@AzGoalie 
@jhunzik 
@mweser 
@coyotesqrl
@stustison
1. Build ddf
2. Add a  dummy filename to `ignore.files` in `etc/system.properties`
3. Stand up ddf
4. Ingest the attached test files
5. `crossdomain.xml` and `thUmbs.db` …
=> DDF-3172 bad.files and bad.file.extensions in system.properties is not being respected

platform/security/handler/security-handler-pki/pom.xml, platform/security/handler/security-handler-pki/src/main/java/org/codice/ddf/security/handler/pki/CrlChecker.java, platform/security/handler/security-handler-pki/src/test/java/org/codice/ddf/security/handler/pki/CrlCheckerTest.java
Updates the CrlChecker to attempt to refresh the CRL when the nextUpdate time has passed.
@rzwiefel 
@beyelerb
@jlcsmith
System configured with a valid CRL. After start up login with a specific user's PKI. Add that certificate to the CRL and verify the CRL is refreshed on the correct interval.
Currently the CRL will only be refreshed on system restart (or bundle restart of the security-handler-pki)
[DDF-3139](https://codice.atlassian.net/browse/ddf-3139) …
=> DDF-3139 Update CrlChecker to refresh CRL on nextUpdate

catalog/ui/catalog-ui-search/src/main/webapp/component/system-usage/system-usage.view.js, catalog/ui/catalog-ui-search/src/main/webapp/js/SystemUsage.js
- Makes System Usage Modal display every time for non-user login
- Makes System Usage Modal display every time for users if "once per session" is set to false
- Makes System Usage Modal display only once per browser session for users when "once per session" is set to true
@josephthweatt @djblue @mcalcote @vinamartin @emmberk
@clockard
2. After building DDF, 
- Add system usage properties in ddf.platform.ui.config.config:
```
systemUsageEnabled=B"true"
systemUsageOncePerSession=B"false"
systemUsageMessage="Click\ acknowledge\ to\ continue"
systemUsageTitle="CONSENT\ BANNER"
```      
- OR build downstream project that already has a system usage message 
**_NOTE: the modal content will not display if quick built_**
3. Run & setup your …
=> DDF-3171 Changed SystemUsage storage logic to make modal display appropriately

distribution/test/itests/README.md, distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/AbstractIntegrationTest.java
Enables downstream projects to use custom configurations for `AbstractStsRealm` that are then properly respected during integration testing.
@brjeter @AzGoalie 
@bdeining
@lessarderic
Manually verify that 
- If no `ddf.security.sts.client.configuration.config` file is placed in `distribution/ddf-common/src/main/resources`, then a file is automatically created inside the Pax Exam runtime folder with an `address` configuration
- If a  `ddf.security.sts.client.configuration.config` file is placed in `distribution/ddf-common/src/main/resources`, then the values used in that file, other than `address`, …
=> DDF-3221 Improved support for downstream configuration of AbstractStsRealm in integration tests

catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/util/impl/CollectionResultComparator.java, catalog/core/catalog-core-api-impl/src/test/java/ddf/catalog/util/impl/CollectionResultComparatorTest.java, catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/SolrFilterDelegate.java, catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/SolrMetacardClientImpl.java, catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/SolrFilterDelegateTest.java, catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/SolrProviderTest.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/SortedQueryMonitor.java, catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswQueryFactory.java, catalog/spatial/csw/spatial-csw-source-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/AbstractCswSource.java, catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/solr/FilteringDynamicSchemaResolver.java, distribution/test/itests/test-itests-common/src/main/resources/csw-multi-sort-asc.xml, distribution/test/itests/test-itests-common/src/main/resources/csw-multi-sort-desc.xml, distribution/test/itests/test-itests-common/src/main/resources/sorttestcard1.xml, distribution/test/itests/test-itests-common/src/main/resources/sorttestcard2.xml, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalog.java
Adds support for multiple sort attributes in CSW queries.
@bdeining  
@kcwire 
https://github.com/orgs/codice/teams/core-apis/
@pklinef 
@millerw8
Run full build with itests.
Insert similar metacards with only a few attributes that differ.
Specify a CSW query that defines multiple SortBy using similar attributes first. 
Ensure that results are returned in the correct sort order.
Extended SortBys were added in the QueryRequest properties to avoid changing whitelisted APIs.
Sources that only support single SortBy will continue to get the sort attributes from the single SortBy in the Query.
https://codice.atlassian.net/browse/DDF-3201 …
=> DDF-3201 Add multi-attribute sorting for CSW

catalog/core/catalog-core-impl/filter-proxy/src/main/java/ddf/catalog/filter/proxy/adapter/GeotoolsFilterAdapterImpl.java, catalog/core/catalog-core-impl/filter-proxy/src/test/java/ddf/catalog/filter/proxy/adapter/test/FilterAdapterTest.java, catalog/ui/catalog-ui-search/src/main/webapp/component/property/property.js, catalog/ui/catalog-ui-search/src/main/webapp/component/query-basic/query-basic.hbs, catalog/ui/catalog-ui-search/src/main/webapp/component/query-basic/query-basic.less, catalog/ui/catalog-ui-search/src/main/webapp/component/query-basic/query-basic.view.js, catalog/ui/catalog-ui-search/src/main/webapp/js/CQLUtils.js, catalog/ui/catalog-ui-search/src/main/webapp/js/cql.js, catalog/ui/catalog-ui-search/src/main/webapp/js/cql.spec.js, catalog/ui/catalog-ui-search/webpack/config/ci.js, catalog/ui/catalog-ui-search/webpack/config/test.js
Adds support to Intrigue for creating relative temporal queries that can be saved and will always perform the temporal search relative to the time of the search execution.
@AzGoalie 
@jhunzik 
@ahoffer 
@mweser 
@djblue 
@rzwiefel 
@ryeats 
@pklinef
Start up a DDF and ingest a product. Perform a relative temporal query that will both include and exclude the product and verify the metacard is present or not. Try waiting 3-4 minutes after ingesting and perform a `last 1 minute` query to verify no results and a `last 1 hour` query to verify results.
[DDF-3180](https://codice.atlassian.net/browse/DDF-3180) …
=> DDF-3180 Add temporal query support to Intrigue

platform/admin/core/admin-core-insecuredefaults/src/main/java/org/codice/ddf/admin/insecure/defaults/service/InsecureDefaultsCollector.java
Fix InsecureDefaultsCollector.getTruststorePath
@tbatie @vinamartin 
@bdeining
@figliold
Install DDF and verify that the insecure defaults alert doesn't contain any detail message about not being able to load a keystore/truststore.
[DDF-2304](https://codice.atlassian.net/browse/DDF-2304)
=> DDF-2304 Fix InsecureDefaultsCollector.getTruststorePath

catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/XstreamPathConverter.java, catalog/spatial/csw/spatial-csw-transformer/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/TestXstreamPathConverter.java
Migrates the path matching done in XStreamPathMatcher away from using regular expression matching, in favor of considerably more performant character array processing. This change has resulted in about a 5x increase in performance, with ingest taking around 18.5% of the time previously recorded. I've also added a few unit test assertions to ensure the path matching is behaving as expected in edge cases.
The old code was considerably more readable, but I've done my best to keep this code relatively maintainable, despite its lower-level, by adding explanatory javadoc, and extracting the more complicated portions of the comparison to helper methods. I'm definitely open to any suggestions that would improve readability.
(please choose AT LEAST two reviewers that need to approve the PR before …
=> DDF-3225 Improve performance of XStreamPathConverter

catalog/admin/module/catalog-admin-module-maplayers/src/main/webapp/map-layers/index.js, catalog/admin/module/catalog-admin-module-maplayers/src/main/webapp/map-layers/reducer.js, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/config/ConfigurationApplication.java, catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/config/ConfigurationApplicationTest.java, distribution/docs/src/main/resources/_contents/_tables/org.codice.ddf.catalog.ui.config-table-contents.adoc
Adds a configuration option to Intrigue for map layers to be directly retrieved instead of proxied through the DDF server.
@albany551  
@andrewkfiedler  
@bdeining
@millerw8
Full build and install
Configure a map layer such that the proxy is disabled for the layer and verify in Chrome developer tools or similar tool that tile requests are made directly to the configured tile server.
Example:
[{
"alpha": 1,
"parameters": {},
"type": "OSM",
"url": "http://c.tile.openstreetmap.org",
"proxyEnabled": "false"
}]
[DDF-3211](https://codice.atlassian.net/browse/DDF-3211) …
=> DDF-3211 Add configuration for Intrigue to directly retrieve map tiles.

catalog/confluence/catalog-confluence-source/pom.xml, catalog/confluence/catalog-confluence-source/src/main/java/org/codice/ddf/confluence/source/ConfluenceFilterDelegate.java, catalog/confluence/catalog-confluence-source/src/main/java/org/codice/ddf/confluence/source/ConfluenceSource.java, catalog/confluence/catalog-confluence-source/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/confluence/catalog-confluence-source/src/main/resources/OSGI-INF/metatype/metatype.xml, catalog/confluence/catalog-confluence-source/src/test/java/org/codice/ddf/confluence/source/ConfluenceFilterDelegateTest.java, catalog/confluence/catalog-confluence-source/src/test/java/org/codice/ddf/confluence/source/ConfluenceSourceTest.java, catalog/core/catalog-core-tagsfilterplugin/src/main/java/org/codice/ddf/catalog/plugin/tagsfilter/TagsFilterQueryPlugin.java, catalog/core/catalog-core-tagsfilterplugin/src/test/java/org/codice/ddf/catalog/plugin/tagsfilter/TagsFilterQueryPluginTest.java, distribution/docs/src/main/jdocs/content/_tables/ddf.catalog.transformer.xml.XmlResponseQueueTransformer-table-contents.adoc, distribution/docs/src/main/jdocs/content/_tables/org.codice.ddf.catalog.ui.config-table-contents.adoc, distribution/docs/src/main/resources/_contents/_tables/Confluence_Federated_Source-table-contents.adoc, distribution/docs/src/main/resources/_contents/_tables/org.codice.ddf.platform.email.impl.SmtpClientImpl-table-contents.adoc
Make ConfluenceSource more configurable. 
- Fix connected source implementation
- Fix username/password update issue
- Fix how we determine catalog provider in TagsFilterQueryPlugin
@mcalcote @emmberk @vinamartin 
@figliold
@shaundmorris
Install ddf and create a federated confluence source to a confluence server version 6.2.3.
Verify that you can get results back as an anonymous user.
Turn off anonymous access in confluence and verify you can get results back still as a specific user.
I have a trial confluence instances installed that you can hit for testing. 
[DDF-3218](https://codice.atlassian.net/browse/DDF-3218) …
=> DDF-3218 Make ConfluenceSource more configurable.

platform/admin/core/admin-core-logviewer/src/main/webapp/js/components/log-panel/log-panel.js
Removes the link in **Admin UI -> System -> Logs** that allows the log viewer to be seen in a new tab.
@djblue 
@vinamartin 
@clockard 
@stustison
1. Build and run DDF
2. Go to the Admin UI -> System -> Logs
3. Verify there is no link to open the logs in a new tab, and no issues related to these changes
[DDF-3226](https://codice.atlassian.net/browse/) …
=> DDF-3226 Removed 'Open View in New Tab' link in System->Logs in Admin UI

catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/controller/SearchController.java, catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/controller/search/QueryRunnable.java, catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/service/SearchService.java, catalog/ui/search-ui/search-endpoint/src/test/java/org/codice/ddf/ui/searchui/query/controller/SearchControllerTest.java, catalog/ui/search-ui/standard/src/main/resources/OSGI-INF/metatype/metatype.xml, distribution/docs/src/main/jdocs/content/_tables/org.codice.ddf.ui.search.standard.properties-table-contents.adoc
The search endpoint has been changed to enforce its own maximum page size, the user is able to configure this value. It has also been updated to make sure it properly pages if the number of results returned by the catalog framework doesn't match its own maximum page size.
@mweser @emmberk @josephthweatt @vinamartin @alexaabrd 
@clockard @lessarderic 
Install a DDF, then configure the Standard Search Endpoint max results to be lower than the number of results in the catalog. Confirm the configured max is returned using the standard search ui.
Configure the max standard search results to be higher than the catalog.maxPageSize, but both …
=> DDF-3182 Added paging to search endpoint and config for max page size

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/config/ConfigurationApplication.java, catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.config.xml, catalog/ui/catalog-ui-search/src/main/webapp/js/model/Sources.js, catalog/ui/catalog-ui-search/src/main/webapp/properties.js, distribution/docs/src/main/resources/_contents/_tables/org.codice.ddf.catalog.ui.config-table-contents.adoc
Disables searching the local catalog from Intrigue. 
@adimka  
@albany551  
@bdeining
Install DDF
Configure Catalog UI Search and check `Disable Local Catalog`
Configure a local source (e.g. CSW)
Ingest some data via CSW
Launch Intrigue and create a new search. Select providers. 
Verify that `ddf.distribution` or similar is not present but the CSW source is.
This allows integrators to use Intrigue while providing separate middleware for query.
[DDF-3220](https://codice.atlassian.net/browse/DDF-3220) …
=> DDF-3220 Disable local catalog searching from Intrigue.

distribution/docs/src/main/jdocs/content/_quickstart/quickstart-certificates.adoc, distribution/docs/src/main/jdocs/content/_running/starting-intro-contents.adoc, distribution/docs/src/main/resources/_contents/_running/starting-intro-contents.adoc, distribution/docs/src/main/resources/_contents/_securing/managing-certificates-contents.adoc, platform/platform-app/src/main/resources/features.xml
Fix installing DDF with broker-app while offline.
@emmberk 
@jrnorth 
@vinamartin 
@clockard
@jaymcnallie
Install broker-app on a DDF while not connected to the internet and without an .m2/repository …
=> DDF-2132 offline install issue missing org.apache.felix.coordinator

catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/XstreamPathConverter.java, catalog/spatial/csw/spatial-csw-transformer/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/TestXstreamPathConverter.java
Fixes an edge case causing indexed fields to not be considered equal in cases where they should be, and adds a unit test covering this edge case.
@glenhein @mackncheesiest 
@bdeining
@millerw8
Full build should suffice.
Fixes and adds test coverage for a previously untested edge case.
[DDF-2335](https://codice.atlassian.net/browse/DDF-2335) …
=> DDF-3225 Fix edge case handling in XStreamPathConverter

catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/IngestCommand.java
@spearskw 
@AzGoalie 
@mweser 
@ahoffer
@rzwiefel  
@bdeining
@coyotesqrl
Build and attempt to do tab-filepath completion using the ingest command.
This was already supported using this same feature for the validate command.
[DDF-3236](https://codice.atlassian.net/browse/DDF-3236)
=> DDF-3236 Added file path completion for ingest command

catalog/opensearch/catalog-opensearch-source/src/main/java/ddf/catalog/source/opensearch/impl/OpenSearchSource.java, catalog/opensearch/catalog-opensearch-source/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/opensearch/catalog-opensearch-source/src/main/resources/OSGI-INF/metatype/metatype.xml, catalog/opensearch/catalog-opensearch-source/src/test/java/ddf/catalog/source/opensearch/impl/TestOpenSearchSource.java
This PR makes the Entry XML configurable to allow for more robust atom response parsing and transformation into a metacard.
@adimka 
@clockard
@millerw8
Build / Install.  This functionality is covered in unit tests.
[DDF-3184](https://codice.atlassian.net/browse/DDF-3184) …
=> DDF-3184 Added a configurable option to the OpenSearchSource for parsing the response

catalog/rest/catalog-rest-endpoint/src/main/java/org/codice/ddf/endpoints/rest/InternalServerErrorException.java, catalog/rest/catalog-rest-endpoint/src/main/java/org/codice/ddf/endpoints/rest/RESTEndpoint.java, catalog/rest/catalog-rest-endpoint/src/main/java/org/codice/ddf/endpoints/rest/RESTService.java, catalog/rest/catalog-rest-endpoint/src/test/java/org/codice/ddf/endpoints/rest/TestRestEndpoint.java
Catalog REST endpoint should return 404 when a Metacard is not found, but returns 500
* Changed the server error exception that was thrown to return a 404 instead
* Changed `ServerErrorException` (now `InternalServerException`) to only throw Internal Server Errors (500)
* Created a private method (`createBadRequestResponse`) which creates a 400 instead of having `ServerErrorException` handle it
@Lambeaux 
@rzwiefel  
@coyotesqrl 
@kcwire 
1- Successful build and making sure all tests pass
2- Making sure that a 404 is returned instead of a 500 when a Metacard is not found
[DDF-3234](https://codice.atlassian.net/browse/DDF-3234)
- ✏️ …
=> DDF-3234 Catalog REST endpoint should return 404 when a Metacard is not found, but returns 500

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/config/ConfigurationApplication.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/EntityTooLargeException.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/MetacardApplication.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/FeedbackApplication.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/QueryApplication.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/security/UserApplication.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/util/EndpointUtil.java, catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.config.xml, catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/util/EndpointUtilTest.java
Fixes intrigue endpoints from reading data indefinitely.
anyone
@clockard
@coyotesqrl
Ensure you cannot upload to any Intrigue post/patch/put endpoint with a blob greater than 1MB in size
https://codice.atlassian.net/browse/DDF-3229
=> DDF-3229 Fix intrigue endpoints from reading data infinitely

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/CachingFederationStrategy.java, catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/cache/solr/impl/CachingFederationStrategyTest.java
Fixes CachingFederationStrategy so connected sources aren't filtered out as duplicates.
@bdeining
@coyotesqrl
@pklinef
Install DDF and add a confluence connected source. 
Upload a product to the local DDF.
Perform a search and verify you get results back from both the local catalog and the confluence source. (Note: The results will all show as from the local source so you will need to look at some other attribute on the results to verify where they came from)
[DDF-3231](https://codice.atlassian.net/browse/DDF-3231) …
=> DDF-3231 Fix ConnectedSources in CachingFederationStrategy

CODEOWNERS
Confirming that codeowners files works with non-committers
=> Quick testing edit to CODEOWNERS

platform/admin/configurator/admin-configurator-impl/pom.xml, platform/admin/configurator/admin-configurator-impl/src/main/java/org/codice/ddf/admin/configurator/impl/BundleOperation.java, platform/admin/configurator/admin-configurator-impl/src/main/java/org/codice/ddf/admin/configurator/impl/FeatureOperation.java, platform/admin/configurator/admin-configurator-impl/src/test/groovy/org/codice/ddf/admin/configurator/impl/BundleConfigHandlerTest.groovy, platform/admin/configurator/admin-configurator-impl/src/test/groovy/org/codice/ddf/admin/configurator/impl/FeatureConfigHandlerTest.groovy
Adds granular checks before allowing a user to make feature/bundle changes.
@tbatie @Lambeaux 
@clockard
@stustison
1. Full build and test. 
2. Install of the downstream Admin Console Beta kar and run through its operations. 
3. Attempt to use the Configurator to perform feature/bundle operations with an unauthorized user.
N/A
[DDF-3247](https://codice.atlassian.net/browse/DDF-3247)
N/A …
=> DDF-3247 Adds granular permissions checking to Configurator operations.

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/resource/download/ReliableResourceDownloader.java, platform/security/handler/security-handler-pki/pom.xml, platform/security/handler/security-handler-pki/src/main/java/org/codice/ddf/security/handler/pki/CrlChecker.java, platform/security/handler/security-handler-pki/src/test/java/org/codice/ddf/security/handler/pki/CrlCheckerTest.java
`CrlChecker` now uses a single static pool for its scheduled checks for CRL lists. A better solution would be to convert the checker into a service; however, this should be sufficient for now.
This PR also resolves a small, related, issue with a thread pool that was constructed and never used for the `ReliableResourceDownloader`.
When running this evening, I found that while the issue at hand was resolved, I had three itest failures on my local development box. I do not believe these are related to this change, and in fact might be a misleading result of the development branch upon which I had done my development (I based off of #2255 because of the improved ability to track down the culprit branches/pools). However, it is possible there is a bug introduced that caused these tests to …
=> DDF-3139 Resolves issue where CrlChecker opened a new pool on every construction

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/util/EndpointUtil.java
Fixes a duplicate key exception for a `Collectors.toMap`
@garrettfreibott @josephthweatt 
@codice/io 
@coyotesqrl
@pklinef
https://codice.atlassian.net/browse/DDF-3161
=> DDF-3161 Fixed a duplicate key exception

platform/security/sts/security-sts-ldapclaimshandler/src/main/java/ddf/security/sts/claimsHandler/LdapClaimsHandler.java, platform/security/sts/security-sts-ldapclaimshandler/src/main/java/ddf/security/sts/claimsHandler/RoleClaimsHandler.java, platform/security/sts/security-sts-ldapclaimshandler/src/test/java/ddf/security/sts/claimsHandler/LdapClaimsHandlerTest.java, platform/security/sts/security-sts-ldapclaimshandler/src/test/java/ddf/security/sts/claimsHandler/RoleClaimsHandlerTest.java, platform/security/sts/security-sts-ldaplogin/pom.xml, platform/security/sts/security-sts-ldaplogin/src/main/java/ddf/ldap/ldaplogin/SslLdapLoginModule.java
Temporary code to ignore LDAP referrals in login and claims handler code. Initial take to keep exceptions from aborting login process. As a result of the spike, additional logic may be implemented to conditionally follow referrals, etc.
If merged, this doesn't close DDF-3147, an updated is expected from the result of the spike.
@ahoffer  
@coyotesqrl  
@jlcsmith
@stustison …
=> DDF-3147 Ignore LDAP referrals in login and claims handlers

platform/admin/ui/src/main/webapp/js/views/SystemUsageModal.view.js, platform/admin/ui/src/main/webapp/templates/systemUsage.layout.handlebars
Limits HTML rendering capabilities in the Admin-UI Usage Modal to formatting only.
@blen-desta 
@stustison
- Build distribution
- Enable and set system usage modal to contain a script tag `<script>alert(1)</script>`
- Refresh admin ui and ensure that js didn't execute but that any other content shows up correctly formatted
[DDF-3248 ](https://codice.atlassian.net/browse/DDF-3248) …
=> DDF-3248 Limited HTML rendering capabilities in the Admin-UI Usage Modal to formatting only.

distribution/docs/src/main/jdocs/content/_tables/org.codice.ddf.security.sts.claims.property.PropertyFileClaimsHandler-table-contents.adoc, platform/security/sts/security-sts-propertyclaimshandler/pom.xml, platform/security/sts/security-sts-propertyclaimshandler/src/main/java/org/codice/ddf/security/sts/claims/property/PropertyFileClaimsHandler.java, platform/security/sts/security-sts-propertyclaimshandler/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/security/sts/security-sts-propertyclaimshandler/src/main/resources/OSGI-INF/metatype/metatype.xml, platform/security/sts/security-sts-propertyclaimshandler/src/test/java/org/codice/ddf/security/sts/claims/property/TestPropertyFileClaimsHandler.java
Add ID claim to PropertyFileClaimsHandler
@vinamartin @emmberk  @mcalcote @ricklarsen 
@shaundmorris
@stustison
Install DDF and login as admin.
Go to https:/localhost:8993/whoami and verify the admin has the claim http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier= [admin, guest]
[DDF-3237](https://codice.atlassian.net/browse/DDF-3237) …
=> DDF-3237 Add ID claim to PropertyFileClaimsHandler

catalog/transformer/catalog-transformer-pptx/pom.xml, catalog/transformer/catalog-transformer-pptx/src/main/java/ddf/catalog/transformer/input/pptx/PptxInputTransformer.java, catalog/transformer/catalog-transformer-pptx/src/test/java/ddf/catalog/transformer/input/pptx/PptxInputTransformerTest.java
Allows a PowerPoint presentation to be ingested and its metacard added to the catalog, even if a thumbnail cannot be generated for the PowerPoint.
@AzGoalie @emanns95 @mweser @jhunzik 
@bdeining
@clockard 
Unfortunately, the PowerPoint file that exposed this issue is not available for testing. We have been unable to create another PowerPoint file with the same behavior. 
No.
[DDF-3245](https://codice.atlassian.net/browse/DDF-3245) …
=> DDF-3245 Ingest PowerPoint

catalog/opensearch/catalog-opensearch-source/pom.xml, catalog/opensearch/catalog-opensearch-source/src/main/java/ddf/catalog/source/opensearch/impl/OpenSearchFilterVisitor.java, catalog/opensearch/catalog-opensearch-source/src/test/java/ddf/catalog/source/opensearch/impl/TestOpenSearchFilterVisitor.java
This PR adds support for vividsolution geometries in OpenSearchFilterVisitor. ECQL.toFilter creates filters with geometries of this type which were previously unhandled. This would result in failed spatial queries over the OpenSearch endpoint.
@mcalcote @vinamartin @emmberk 
@clockard
@shaundmorris
* Spin up and install with system defaults
* Federate with another DDF over the OpenSearch endpoint
* Using Intrigue, perform spatial queries using Point-Radius, Polygon and BBox and confirm that the expected results are returned
[DDF-3208](https://codice.atlassian.net/browse/DDF-3208) …
=> DDF-3208 Fixes Geospatial searches over OpenSearch endpoint

platform/platform-filter-response/src/main/java/org/codice/ddf/platform/response/filter/ResponseFilter.java
- As of DDF-2893, we're caching everything far too aggressively.
- This update allows apps to perform their own cache busting between versions, see DDF-2916.
- Without this, a user will need to clear their cache (or wait a week) when upgrading to new versions.
@djblue 
@rzwiefel 
@kcwire
@pklinef
Go to the admin application.  Verify that the main app page and any html pages within do not get cached.  Verify that other assets do.
https://codice.atlassian.net/browse/DDF-2917
=> DDF-2917 Update caching to exclude base app pages and html

catalog/rest/catalog-rest-endpoint/src/main/java/org/codice/ddf/endpoints/rest/RESTEndpoint.java, catalog/rest/catalog-rest-endpoint/src/test/java/org/codice/ddf/endpoints/rest/TestRestEndpoint.java, distribution/docs/src/main/jdocs/content/_tables/org.codice.ddf.catalog.content.monitor.ContentDirectoryMonitor-table-contents.adoc
- Maximum attribute data size is capped to 65,535 bytes
@anyone
@clockard
@stustison
1. Ensure you cannot override an attribute with data greater than 65,535 in size.
https://codice.atlassian.net/browse/DDF-3223
=> DDF-3223 Adds limit to attribute override size

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/config/ConfigurationApplication.java, catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.config.xml, catalog/ui/catalog-ui-search/src/main/webapp/component/filter/filter.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/select/select.hbs, catalog/ui/catalog-ui-search/src/main/webapp/component/select/select.view.js
Lets descriptions for metacard attributes be edited and stored in system configuration, to be shown as tooltips in the attribute selector dropdown (in advanced search).
@bdeining 
@millerw8 
@bdeining 
@millerw8
In admin console, navigate to Standard Search UI -> Configuration -> Catalog UI Search and add an entry to the new `Attribute Descriptions` section.
For example, `title=Descriptive title for metacard`
In Intrigue, navigate to the advanced search editor. Choose the attribute you created a description for and verify that a tooltip appears over it with the description text.
https://codice.atlassian.net/browse/DDF-3251
=> DDF-3251 Allow descriptive tooltips when selecting an attribute in advanced search

catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswQueryFactory.java, catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/mappings/MetacardCswRecordMap.java, catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/transformer/CswRecordMap.java, catalog/spatial/csw/spatial-csw-endpoint/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/spatial/csw/spatial-csw-endpoint/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswQueryFactoryTest.java
Moves the SortBy normalization logic after the QueryFilterTransformers have run. This makes it possible to update invalid SortBy parameters in the QueryFilterTransformer.
@adimka @brianfelix @mackncheesiest @brendan-hofmann 
@bdeining
@millerw8
Full build with unit and itests.
Previously, the SortBy parameters were normalized before the QueryRequest object was created and passed to the QueryFilterTransformers. If a SortBy parameter was an invalid CSW attribute, then it was stripped out completely. This change allows the QueryFilterTransformers to update the SortBy before it is normalized like usual. …
=> DDF-3259 Moved SortBy normalization logic after the query filter transforms

distribution/ddf-common/src/main/resources/common-bin.xml, distribution/ddf-common/src/main/resources/etc/org.apache.karaf.shell.cfg, distribution/docs/src/main/jdocs/content/_configuring/environment-hardening-contents.adoc, distribution/docs/src/main/resources/_contents/_securing/environment-hardening-contents.adoc
- Disables SSH by default
- Updates documentation to explain how to re-enable it and why it is disabled
@garrettfreibott @rzwiefel @ricklarsen 
@clockard
@stustison
- Install and confirm that the SSH server is not available.
- Following the documentation, enable SSH and ensure that it works.
N/A
N/A …
=> DDF-3273 Disable SSH by default

catalog/core/catalog-core-api/src/main/java/ddf/catalog/data/types/constants/core/DataType.java, catalog/transformer/catalog-transformer-pdf/src/main/java/ddf/catalog/transformer/input/pdf/PdfInputTransformer.java, catalog/transformer/catalog-transformer-video-input/src/main/java/ddf/catalog/transformer/input/video/VideoInputTransformer.java, catalog/transformer/catalog-transformer-video-input/src/test/java/ddf/catalog/transformer/input/video/VideoInputTransformerTest.java, distribution/ddf-common/src/main/resources/etc/definitions/core-attributes-validator.json, distribution/docs/src/main/resources/_contents/_data/core-attributes-table-contents.adoc, distribution/test/itests/test-itests-common/src/main/resources/xml/record/testNumerical.xml
Updates the DDF DataTypes to conform to the DCMI types.
@emmberk @brendan-hofmann 
@bdeining
@figliold
Install ddf and ingest a pdf and video file through Intrigue. Verify that they have the updated datatypes of Text and Moving Image.
[DDF-3210](https://codice.atlassian.net/browse/DDF-3210) …
=> DDF-3210 Updated catalog taxonomy to support new DCMI-defined types

platform/platform-scheduler/pom.xml, platform/platform-scheduler/src/main/java/ddf/platform/scheduler/CommandJob.java, platform/platform-scheduler/src/test/java/ddf/platform/scheduler/CommandJobTest.java
This PR adds a work-around that fixes a NPE when scheduling a command from the `Platform Command Scheduler`.
@vinamartin @mcalcote @glenhein 
@clockard
@figliold 
Add a `Platform Command Scheduler` configuration, and confirm that there is no `java.lang.NullPointerException: "in" is null!` entry in the log. Confirm that the command is executed and that the scheduler behaves as expected.
[KARAF-5362](https://issues.apache.org/jira/browse/KARAF-5362) NPE Creating Session with a null "in" parameter from a SessionFactory
[DDF-3121](https://codice.atlassian.net/browse/DDF-3121) …
=> DDF-3121 Fixed NPE in the Platform Scheduler

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/config/ConfigurationApplication.java, catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.config.xml, catalog/ui/catalog-ui-search/src/main/webapp/component/visualization/maps/cesium/geocoder.js, catalog/ui/search-ui-app/src/main/resources/etc/org.codice.ddf.catalog.ui.config.config, distribution/docs/src/main/jdocs/content/_tables/org.codice.ddf.catalog.ui.config-table-contents.adoc
Makes gazetteer configurable in Intrigue.
@emmberk @mcalcote @vinamartin 
@rzwiefel
Install DDF, go to Intrigue and select Local for a workspace.
Once the globe loads open up the dev tools network tab and search for location name
You should see a request to https://nominatim.openstreetmap.org/search
Now go to the admin ui -> Standard Search UI -> Catalog UI Search -> org.codice.ddf.catalog.ui.config and uncheck Use Online Gazetteer
Reload Intrigue and perform the same search. 
Verify that the search request is now sent to https://localhost:8993/services/REST/v1/Locations …
=> DDF-2850 Make gazetteer configurable in Intrigue.

catalog/core/catalog-core-commands/pom.xml, catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/RemoveAllCommand.java, catalog/core/catalog-core-commands/src/test/java/org/codice/ddf/commands/catalog/RemoveAllCommandTest.java
This PR fixes an issue with the removeall command warning prompt on Windows.
@AzGoalie @mcalcote 
@clockard
@rzwiefel
Execute the removeall command with different options, and confirm that the behavior is correct and that the warning prompt appears correctly.
The issue was that the response to the warning prompt only appears on the console after hitting enter on Windows.
[DDF-3121](https://codice.atlassian.net/browse/DDF-3121) …
=> DDF-3121 Fixed removeall yes/no prompt on Windows

catalog/core/catalog-core-commands/pom.xml, catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/CatalogCommands.java, catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/DuplicateCommands.java, catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/ExportCommand.java, catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/ImportCommand.java, catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/MigrateCommand.java, catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/ReplicateCommand.java, catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/SubjectCommands.java, catalog/core/catalog-core-commands/src/test/groovy/org/codice/ddf/commands/catalog/ExportCommandSpec.groovy, catalog/core/catalog-core-commands/src/test/java/org/codice/ddf/commands/catalog/ReplicateCommandTest.java, catalog/core/catalog-core-commands/src/test/java/org/codice/ddf/commands/catalog/SubjectCommandsTest.java
This PR refactors the catalog commands to use the Karaf `session.readLine` method when reading console input.
@AzGoalie @mcalcote 
@clockard
@rzwiefel
| Command  | Test Step |
| ------------- | ------------- |
| `catalog:export --delete` (without `--force`) | Check that the warning prompt works. |
| `catalog:import --skip-signature-verification` (without `--force`) | Check that the warning prompt works. |
| `catalog:migrate` (without `--from` nor `--to`) | Check that the provider prompts work. |
| `atalog:replicate` (without `[ID]` argument) | Check that the `ID` prompt works. |
| `catalog:<any subject command> --user` | Check that the password prompt works and that the user input is masked. |
This is a follow-on PR to …
=> DDF-3121 Refactored catalog commands to use Karaf readLine

catalog/ui/catalog-ui-search/src/main/webapp/js/CQLUtils.js
Change the sanitizeGeometry function in CQLUtils.js to use regex instead of replacing matches that break other queries, such as the relative temporal query.
@ryeats 
@albany551 
@rzwiefel
Manually verify that geometry queries all sanitize as expected and no other queries will be pulled in. …
=> DDF-3180 Fix sanitizeGeometry to use regex

catalog/ui/catalog-ui-search/pom.xml, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/security/Constants.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/security/README.md, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/security/WorkspacePolicyExtension.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/security/WorkspacePreIngestPlugin.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/security/WorkspaceSecurityConfiguration.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/security/WorkspaceSharingPolicyPlugin.java, catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.security.xml, catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/security/WorkspacePolicyExtensionTest.java, catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/security/WorkspacePreIngestPluginTest.java, catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/security/WorkspaceSharingPolicyPluginTest.java
- Updates workspace security to allow owner attribute to be configurable.
- Adds admin alerting on failure to create workspace.
- Simplifies policy extension.
- Increases unit test code coverage.
- General code cleanup.
@tbatie 
@peterhuffer 
@rzwiefel
@stustison
- Full build with itests.
- Edit `user.properties` and `user.attributes` to add a new user with no email but with a nameidentifier.
- Ensure that the new user cannot use workspaces but that the admin is notified.
- Update the workspace security configuration to use nameidentifier for the owner attribute.
- Ensure the new user can use workspaces in intrigue.
[DDF-3283](https://codice.atlassian.net/browse/DDF-3283) …
=> DDF-3283 Workspace security updates.

Jenkinsfile
Builds on #2281 with the following changes
* Downgrades maven on linux build to work around some build issues
* Falling back to system java on linux builds to work around some build issues
* No longer redirecting itest log output to file
* Updated the deploy stage conditions to stop from breaking in jenkins when not using the github-branch-source plugin
* Added restriction to cron trigger to only apply to master branch. **NOTE:** This will require using multi-branch job type and the github-branch-source
@LinkMJB @mcalcote 
@codice/build 
@shaundmorris 
@clockard 
[DDF-3261](https://codice.atlassian.net/browse/DDF-3261) …
=> DDF-3261 Additional pipeline updates to support multi-branch builds

catalog/spatial/geocoding/spatial-geocoding-lucene/pom.xml, catalog/spatial/geocoding/spatial-geocoding-lucene/src/main/java/org/codice/ddf/spatial/geocoding/index/IndexInitializer.java, catalog/spatial/geocoding/spatial-geocoding-lucene/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/spatial/geocoding/spatial-geocoding-lucene/src/test/java/org/codice/ddf/spatial/geocoding/index/IndexInitializerTest.java, catalog/spatial/spatial-app/src/main/resources/features.xml, catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.config.xml, distribution/docs/src/main/resources/content/_application-references/managing-spatial-contents.adoc, distribution/docs/src/main/resources/content/_tables/org.codice.ddf.catalog.ui.config-table-contents.adoc
Switches the default gazetteer from the online version to the offline. Adds a default dataset for the offline gazetteer.
@emmberk @mcalcote 
@bdeining
@rzwiefel
Install DDF and turn off the option Standard Search UI -> Catalog UI Search-> Use Online Gazetteer.
Go to the Intrigue ui and
Search for a location like "Arizona" in the search map search bar in the upper right and verify that the location is found.
[DDF-3281](https://codice.atlassian.net/browse/DDF-3281) …
=> DDF-3281 Add default geoname data and default to offline gazetteer.

catalog/catalog-app/pom.xml
Removes an old dependency from the catalog-app pom that no longer exists.
This leftover dependence prevents the project from being released.
@paouelle @brjeter 
@figliold
@shaundmorris
Successful build and maven release:prepare doesn't find any snapshot dependencies
[DDF-3142](https://codice.atlassian.net/browse/DDF-3142) …
=> DDF-3142 Remove catalog-core-migratable dependency in catalog-app

catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/CommandSupport.java, catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/IngestCommand.java
This PR fixes the progress bar for a few catalog commands.
@ahoffer @johnsliao @vinamartin @mcalcote 
@clockard
@rzwiefel 
The modified progress bar is used in a few situations:
- `catalog:ingest`
- `--batchsize`
- `--multithreaded`
- `catalog:seed`
- `catalog:migrate`
- `--batchsize`
- `--multithreaded`
- `catalog:replicate`
- `--batchsize`
- `--multithreaded`
Check that the progress bar looks correct for processing different edge cases with the commands:
- small/large batch sizes
- small/large number of records to process
- no records to process
- multithreaded/not multithreaded
This PR doesn't change anything about the behavior before the regression except:
- There is no longer an arrow when the progress bar is at 100%.
- The progress bar width matches that of the Karaf start-up …
=> DDF-3121 Fixed catalog commands progress bar

catalog/ui/catalog-ui-search/src/main/webapp/component/alert/alert.js, catalog/ui/catalog-ui-search/src/main/webapp/component/content/content.js, catalog/ui/catalog-ui-search/src/main/webapp/component/golden-layout/golden-layout.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/metacard/metacard.js, catalog/ui/catalog-ui-search/src/main/webapp/component/paging/paging.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/tabs/workspace-content/tabs-workspace-content.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/upload/upload.js, catalog/ui/catalog-ui-search/src/main/webapp/component/visualization/histogram/histogram.hbs, catalog/ui/catalog-ui-search/src/main/webapp/component/visualization/histogram/histogram.less, catalog/ui/catalog-ui-search/src/main/webapp/component/visualization/histogram/histogram.view.js, catalog/ui/catalog-ui-search/src/main/webapp/js/store.js
- Added new method to calculate categories for date type histograms.
- Updated single click methods to utilize the getCategories methods instead of trying to calculate the single bin.  This is more reliable.
- Do note that plotly uses a special convention sometimes for date bin sizes.  Instead of a number, they give a string like so: 'M3'.  Where M means months, and the number following M means the number of months.
- Updates histogram to use full result set rather than page
- Adds guard for attributes that have no matching data.
- Updates new selection interface attribute to be cleared when going back to searches from results.
- Updates metacard.js to account for new selection interface attribute
- Updates the histogram tooltips to be more consistent with the rest of the UI, and …
=> DDF-3094 Updates histogram to bin dates by ranges instead of categories, and to show the entire result set

distribution/docs/src/main/resources/content/_developingComponents/assuring-authenticity-of-bundles-and-applications-contents.adoc, distribution/docs/src/main/resources/content/config.adoc
Adjust section heading levels in docs to follow asciidoctor outline. 
Also added a "status" property to config.adoc
@mcalcote @vinamartin @emmberk @Lambeaux @jrnorth 
@clockard
@coyotesqrl
@lessarderic
@pklinef
@rzwiefel
@shaundmorris
builds successfully.
This will remove instances of 'Section header out of order...' warnings in build logs.
`:status: published` gives the config.adoc file a valid header in regards to the templates and clears up noise in build logs. …
=> DDF-2824 fixed typo in docs section heading

pom.xml
* Upgrades maven-deploy-plugin from 2.6 to 2.8.2
* Upgrades maven-releaes-plugin from 2.5.1 to 2.5.3
Upgrading to a newer version will allow for retrying on failed deploys
The previous version of the maven-release plugin did not work correctly on windows
@LinkMJB @emanns95 
@codice/build 
@shaundmorris 
@clockard 
The build pipeline specifies ` -DretryFailedDeploymentCount=10` during the deploy stage, however this was being ignored due to it not being supported in the version of the deploy plugin in use.
[DDF-3304](https://codice.atlassian.net/browse/DDF-3304) …
=> DDF-3304 Upgraded maven-deploy-plugin and maven-release-plugin

platform/admin/core/admin-core-insecuredefaults/src/main/java/org/codice/ddf/admin/insecure/defaults/service/UsersPropertiesFileValidator.java, platform/admin/core/admin-core-insecuredefaults/src/test/java/org/codice/ddf/admin/insecure/defaults/service/UsersPropertiesFileValidatorTest.java
Adds another insecure default detail to the insecure defaults alert and logs a security audit message.
@rzwiefel
@stustison
Install DDF and wait for the insecure defaults alert to appear in the admin ui (could take up to 5 min).
Verify that the insecure defaults alert details contains an line for the existence of the users.properties file (see screenshot below). 
Verify that the security.log in data/logs contains an entry `System is running with the users.properties file.`
[DDF-3306](https://codice.atlassian.net/browse/DDF-3306)
=> DDF-3306 Display an alert in the Admin Console if the users.properties file exists

catalog/ui/catalog-ui-search/src/main/webapp/component/map-actions/map-actions.view.js
Fixes bug where the metacard actions page content did not display in IE11
@gordocanchola @dcruver @millerw8 
@codice/ui 
@pklinef 
@kcwire 
Verify metacard actions display properly in IE11, Chrome and Firefox
[DDF-3300](https://codice.atlassian.net/browse/DDF-3300)
=> DDF-3300 Metacard actions do not display in IE 11

catalog/ui/catalog-ui-search/src/main/webapp/js/model/Query.js
Fixes paging status display when there are 0 results. Currently displays "1-0 of 0 results", will now show "0 results". See screenshots.
@bdeining 
@millerw8
Run a search that returns 0 results and check that the paging status indicates "0 results".
https://codice.atlassian.net/browse/DDF-3233
=> DDF-3233 Fix paging status when there are no results

platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/ImportMigrationManagerImpl.java, platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/migration/ImportMigrationManagerImplTest.java
Adds directory filtering when processing a zip file during migration import.
@brjeter 
@Lambeaux 
@tbatie 
@figliold
@lessarderic
Run the migration:export command. Then unzip it the content. Re-zip the content from the command line:
- first cd to the exported-XXXX directory created
- zip -r -X ../exported-XXXX *
Finally, run the migration:import command using the newly created zip file.
[DDF-3314](https://codice.atlassian.net/browse/DDF-3314) …
=> DDF-3314 - Adding directory filtering when processing a zip file during migration import

platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/ImportMigrationManagerImpl.java, platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/migration/ImportMigrationManagerImplTest.java
Adds directory filtering when processing a zip file during migration import.
[Original Master PR](https://github.com/codice/ddf/pull/2359)
@figliold
Run the migration:export command. Then unzip it the content. Re-zip the content from the command line:
- delete exported-XXXX.zip
- first cd to the exported-XXXX directory created
- zip -r -X ../exported-XXXX.zip *
Finally, run the migration:import command using the newly created zip file.
[DDF-3314](https://codice.atlassian.net/browse/DDF-3314) …
=> (2.11.x) DDF-3314 - Adding directory filtering when processing a zip file during migration import

catalog/catalog-app/pom.xml, catalog/catalog-app/src/main/resources/features.xml, catalog/transformer/catalog-transformer-preview/pom.xml, catalog/transformer/catalog-transformer-preview/src/main/java/org/codice/ddf/transformer/preview/PreviewMetacardTransformer.java, catalog/transformer/catalog-transformer-preview/src/main/java/org/codice/ddf/transformer/preview/actions/PreviewActionProvider.java, catalog/transformer/catalog-transformer-preview/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/transformer/catalog-transformer-preview/src/test/java/org/codice/ddf/transformer/preview/PreviewMetacardTransformerTest.java, catalog/transformer/catalog-transformer-preview/src/test/java/org/codice/ddf/transformer/preview/actions/PreviewActionProviderTest.java, catalog/transformer/pom.xml
Adding a metacard transformer and action provider for text preview
This PR adds a metacard transformer and action provider to expose the ext.extracted.text to be used as a text preview.
@dcruver @spearskw 
@jlcsmith 
@pklinef 
Ingest a document (pdf, doc/x, ppt/x, xls/x, mhtml)
Search for the document
Open the Inspector and select the Actions tab.
Click the 'Text Preview' action.
Verify a new browser tab is opened with a preview of the document's text.
[DDF-3276](https://codice.atlassian.net/browse/DDF-3276)
- ❓ …
=> DDF-3276 Text Preview

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/config/ConfigurationApplication.java, catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.config.xml, catalog/ui/catalog-ui-search/src/main/webapp/component/visualization/maps/cesium/map.cesium.js, catalog/ui/catalog-ui-search/src/main/webapp/component/visualization/maps/map.less, catalog/ui/catalog-ui-search/src/main/webapp/component/visualization/maps/map.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/visualization/maps/openlayers/map.openlayers.js, catalog/ui/catalog-ui-search/src/main/webapp/templates/geocoder.handlebars
- Adds configuration for map home to Intrigue, allowing admins to customize it.
- Adds map home button to openlayers, removes the default map home button from cesium and replaces it with our own for consistency.
- Default map home is a rough bounding box of the USA.
- The help for map home specifies it needs to be in a particular order, but really it works so long as a series of coordinates in lon, lat order are supplied.
@djblue 
@jlcsmith
@clockard
=> [2.11.x] DDF-3323 - Adds ability for admin to configure the map home in Intrigue

distribution/ddf-common/src/main/resources/etc/org.ops4j.pax.logging.cfg
Suppresses WARN logs with exceptions printed by Pax Web's org.ops4j.pax.web.extender.war.internal.UnregisterWebAppVisitorWC.java.
@tbatie 
@emanns95 
@clockard
@lessarderic 
Hero Build
https://codice.atlassian.net/browse/DDF-3321 …
=> DDF-3321: Investigate warnings logged on startup

catalog/transformer/catalog-transformer-pptx/src/main/java/ddf/catalog/transformer/input/pptx/PptxInputTransformer.java, catalog/transformer/catalog-transformer-pptx/src/test/java/ddf/catalog/transformer/input/pptx/PptxInputTransformerTest.java, catalog/transformer/catalog-transformer-tika-input/src/main/java/ddf/catalog/transformer/input/tika/TikaInputTransformer.java, catalog/transformer/catalog-transformer-tika-input/src/test/java/ddf/catalog/transformer/input/tika/TikaInputTransformerTest.java
Adding a catch throwable around the Tika metadata extraction that logs the error
Changing the flow so that the transform will continue given a Tika extraction failure
This PR provides better Tika exception handling. 
A catch throwable is used to wrap the Tika extraction because it's hard to capture all of the possible Tika exceptions.
The flow was changed so that an exception in the Tika extraction will not prevent the transform.
@dcruver @beyelerb @kcwire 
@jlcsmith
@pklinef
[DDF-3317](https://codice.atlassian.net/browse/DDF-3317) …
=> DDF-3317 Add better handling of Tika extraction errors

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/security/WorkspacePolicyExtension.java, catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/security/WorkspacePolicyExtensionTest.java, distribution/docs/src/main/resources/content/_securityFramework/realms.adoc, platform/admin/core/admin-core-configpolicy/src/main/java/org/codice/ddf/admin/config/policy/AdminConfigPolicy.java, platform/admin/core/admin-core-configpolicy/src/test/java/org/codice/ddf/admin/config/policy/AdminConfigPolicyTest.java, platform/security/pdp/security-pdp-authzrealm/src/main/java/ddf/security/pdp/realm/AuthzRealm.java, platform/security/pdp/security-pdp-authzrealm/src/test/java/ddf/security/pdp/realm/test/AuthzRealmTest.java, platform/security/platform-security-core-api/src/main/java/ddf/security/policy/extension/PolicyExtension.java
Update PolicyExtension interface methods and implementing classes. 
This changed fixes an issue where users without system high attributes could not save workspaces.
@djblue @emmberk 
@bdeining
@stustison
See me for testing details
[DDF-3320](https://codice.atlassian.net/browse/DDF-3320)
=> DDF-3320 Update PolicyExtension interface methods and implementing classes

catalog/core/catalog-core-api-impl/pom.xml, catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/util/impl/ResultIterable.java, catalog/core/catalog-core-api-impl/src/test/groovy/ddf/catalog/util/impl/ResultIterableSpec.groovy, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/QueryOperations.java, catalog/core/catalog-core-standardframework/src/test/groovy/ddf/catalog/impl/operations/QueryOperationsSpec.groovy
Because we simulate a cursor by executing sequential queries with an incremented start index position, it is possible that ingests can occur, interleaved within subsequent queries. This could result in duplicate results appearing in multiple pages of the results. This will remove those duplicates.
This will also correctly page when there are filtered results, handling the case where a single page's worth of results is blanked out because all N results are filtered.
@rzwiefel @emanns95 
@clockard
@lessarderic
Full build and test run should be sufficient. Rerunning some of the manual heroing steps from recent pagination-related command PRs would be good as well.
N/A …
=> [2.11.x] DDF-3034 Prevent duplicate results during result pagination and handle filtered results.

catalog/core/catalog-core-api-impl/pom.xml, catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/util/impl/ResultIterable.java, catalog/core/catalog-core-api-impl/src/test/groovy/ddf/catalog/util/impl/ResultIterableSpec.groovy, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/QueryOperations.java, catalog/core/catalog-core-standardframework/src/test/groovy/ddf/catalog/impl/operations/QueryOperationsSpec.groovy
Because we simulate a cursor by executing sequential queries with an incremented start index position, it is possible that ingests can occur, interleaved within subsequent queries. This could result in duplicate results appearing in multiple pages of the results. This will remove those duplicates.
@rzwiefel @emanns95 
@clockard
@lessarderic
Full build and test run should be sufficient. Rerunning some of the manual heroing steps from recent pagination-related command PRs would be good as well.
N/A
[DDF-3034](https://codice.atlassian.net/browse/DDF-3034)
N/A …
=> DDF-3034 Prevent duplicate results during result pagination.

catalog/transformer/catalog-transformer-pptx/src/main/java/ddf/catalog/transformer/input/pptx/PptxInputTransformer.java, catalog/transformer/catalog-transformer-pptx/src/test/java/ddf/catalog/transformer/input/pptx/PptxInputTransformerTest.java, catalog/transformer/catalog-transformer-tika-input/src/main/java/ddf/catalog/transformer/input/tika/TikaInputTransformer.java, catalog/transformer/catalog-transformer-tika-input/src/test/java/ddf/catalog/transformer/input/tika/TikaInputTransformerTest.java
2.11.x backport of PR https://github.com/codice/ddf/pull/2363
Adding a catch throwable around the Tika metadata extraction that logs the error
Changing the flow so that the transform will continue given a Tika extraction failure
Changing the PPTX input transformer to not fail ingest on an exception when generating the thumbnail
@dcruver 
@pklinef 
@jlcsmith
=> [2.11.x] DDF-3317 Add better handling of Tika extraction errors

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/config/ConfigurationApplication.java, catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.config.xml, catalog/ui/catalog-ui-search/src/main/webapp/component/visualization/maps/cesium/map.cesium.js, catalog/ui/catalog-ui-search/src/main/webapp/component/visualization/maps/map.less, catalog/ui/catalog-ui-search/src/main/webapp/component/visualization/maps/map.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/visualization/maps/openlayers/map.openlayers.js, catalog/ui/catalog-ui-search/src/main/webapp/templates/geocoder.handlebars
- Adds configuration for map home to Intrigue, allowing admins to customize it.
- Adds map home button to openlayers, removes the default map home button from cesium and replaces it with our own for consistency.
- Default map home is a rough bounding box of the USA.
- The help for map home specifies it needs to be in a particular order, but really it works so long as a series of coordinates in lon, lat order are supplied.
@jlcsmith 
@djblue 
@kcwire
=> DDF-3323 - Adds ability for admin to configure the map home in Intrigue

distribution/docs/src/main/resources/content/_installing/ddf-setup-types.adoc, distribution/install-profiles/src/main/resources/features.xml
Adds a new install profile to install only the applications required for a minimum viable profile.
The name of the profile is subject to change.
@derekwilhelm 
@jaymcnallie
@pklinef 
Verify the install profile shows up in the Admin UI when installing DDF for the first time.
Install the profile and make sure no exceptions occur.
[DDF-3333](https://codice.atlassian.net/browse/DDF-3333) …
=> DDF-3333 Add a new install profile that contains minimum dependencies

catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/DynamicSchemaResolver.java, catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/SchemaFields.java, catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/SolrMetacardClientImpl.java, catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/DynamicSchemaResolverTest.java, catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/SolrProviderTest.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/CacheSolrMetacardClient.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/cql/CqlRequest.java, catalog/ui/catalog-ui-search/src/main/webapp/js/model/Query.js, catalog/ui/catalog-ui-search/src/main/webapp/js/model/Workspace.js, catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/solr/FilteringDynamicSchemaResolver.java, catalog/ui/search-ui/search-endpoint/src/test/groovy/org/codice/ddf/ui/searchui/query/solr/FilteringDynamicSchemaResolverTest.groovy, platform/solr/platform-solr-server-standalone/src/main/resources/solr/conf/schema.xml
Allow Solr tokenized txt field to index more data than txt string field.
Support excluding attributes from Solr response.
@bdeining 
@codice/solr 
@jlcsmith
@rzwiefel
Create or modify a record with a string field (e.g. title, description) that contains over 32k of text.  At the end of the text (past 32k) include a unique word.  Verify that the record ingests, the unique word past the 32k is searchable, and the first 32k of the string is returned.
This provides the ability to search more than 32k of text that is extracted by the Tika transformer after the DDF-3268 changes to the Tika transformer.
https://github.com/codice/ddf/pull/2302
[DDF-3262](https://codice.atlassian.net/browse/DDF-3262)
- ✏️ …
=> DDF-3262 Increase Solr string indexing size and exclude attributes

distribution/ddf-common/src/main/resources/etc/org.ops4j.pax.logging.cfg
Suppresses WARN logs with exceptions printed by Pax Web's org.ops4j.pax.web.extender.war.internal.UnregisterWebAppVisitorWC.java.
Backport to 2.11.x of PR https://github.com/codice/ddf/pull/2372
@clockard 
@clockard 
CI Build
https://codice.atlassian.net/browse/DDF-3321 …
=> DDF-3321: (2.11.x backport) Investigate warnings logged on startup

Jenkinsfile
Changes the node security scan to only scan projects that are actually packaging dependencies
@mcalcote  @djblue 
@codice/build 
@clockard @shaundmorris 
=> DDF-3261 Updated nsp Static Analysis stage to only scan projects using browserify or webpack

dependency-check-maven-config.xml
Updates the owasp suppressions from doc plugin update. This includes suppressions for jruby and asciidocs used during the build process, but not runtime.
@ricklarsen @garrettfreibott @vinamartin 
@clockard @ricklarsen @rzwiefel 
Run OWASP against the changeset
=> DDF-2824 Updated owasp suppressions from doc plugin update

distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/AbstractIntegrationTest.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalog.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestSolrCommands.java
Updates itests to use embedded solr + disables tests that require http solr client. 
@clockard @tbatie @emanns95 @Lambeaux 
@figliold 
@lessarderic
Full build with all itests passing 
[DDF-3279](https://codice.atlassian.net/browse/DDF-3279)
=> [2.11.x] DDF-3279 Updates itests to use embedded solr

platform/admin/core/admin-core-appservice/src/main/java/org/codice/ddf/admin/application/service/command/ProfileInstallCommand.java, platform/admin/core/admin-core-appservice/src/test/java/org/codice/ddf/admin/application/service/command/ProfileInstallCommandTest.java
Updates profile:install command to include security auditing
Removes usage of systemSubject
@peterhuffer @emmberk @paouelle @stustison 
@clockard 
@figliold 
Run `profile:install <profile>` as an administrative user and verify that the security logs contain an audit for the actions performed by the command
[DDF-3316](https://codice.atlassian.net/browse/DDF-3316) …
=> DDF-3316 Implement security audit logging in profile install command

catalog/security/catalog-security-metacardattributeplugin/src/main/resources/OSGI-INF/metatype/metatype.xml, distribution/docs/src/main/resources/content/_plugins/metacard-attribute-plugin.adoc, distribution/docs/src/main/resources/content/_tables/MetacardAttributePlugin.adoc
Backport of DDF-3325 master to 2.11.x
@clockard
@ricklarsen 
Build docs. Search for "Intersection of Source Attribute Values" and make sure it is there.
[DDF-3325](https://codice.atlassian.net/browse/DDF-3325)
=> BACK PORT DDF-3325 Update Metacard Attribute Security Policy Plugin documentation

Jenkinsfile
Backports #2408 to 2.11.x
@clockard @mcalcote 
@codice/build 
[DDF-3261](https://codice.atlassian.net/browse/DDF-3261)
=> DDF-3261 (Backport) Updated nsp Static Analysis stage to only scan projects using browserify or webpack

catalog/core/catalog-core-urlresourcereader/pom.xml, catalog/core/catalog-core-urlresourcereader/src/main/java/ddf/catalog/resource/impl/URLResourceReader.java, catalog/core/catalog-core-urlresourcereader/src/test/java/ddf/catalog/resource/impl/URLResourceReaderTest.java
This PR fixes an issue which caused the main resource would be retrieved instead of the qualified resource from a federated source.
@peterhuffer @AzGoalie @oconnormi 
@clockard
@rzwiefel
Because there are no content types in DDF that get qualified resources, the easiest way to test this is to set up two instances of Alliance and look at the qualified resources for a NITF record.
1. Setup Alliance A with a OpenSearch Federated Source connected to Alliance B.
2. Ingest a NITF in Alliance B.
3. In Intrigue on Alliance A, find the NITF result from Alliance B.
4. The `View overview` and `View original` `Actions` should return images (jpeg or jpeg200), not the original NITF file. Downloading the original NITF should still work as well. …
=> DDF-3342 Fixed downloading qualified resources from a federated source

distribution/ddf-common/src/main/resources/etc/artemis-backup.xml, distribution/ddf-common/src/main/resources/etc/artemis.xml, distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/AbstractIntegrationTest.java
disable broker disk usage checks during itests
@jrnorth @roelens8 
@clockard
@rzwiefel
you can look at the MaxDiskUsage attribute on org.apache.activemq.artemis mbean and verify it is 100. …
=> DDF-3341 disable broker disk usage checks during itests

distribution/ddf-common/src/main/resources/bin/setenv, distribution/ddf-common/src/main/resources/bin/setenv.bat, distribution/ddf-common/src/main/resources/etc/startup.properties, distribution/ddf-common/src/main/resources/etc/system.properties, distribution/ddf-common/src/main/resources/security/default.policy, distribution/kernel/pom.xml, distribution/test/itests/README.md, distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/AbstractIntegrationTest.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFederation.java, platform/admin/admin-configuration-configinstaller/src/main/java/org/codice/ddf/admin/configuration/ConfigurationInstaller.java, platform/osgi/platform-osgi-configadmin/pom.xml, platform/osgi/platform-osgi-configadmin/src/main/resources/OSGI-INF/permissions.perm, platform/security/core/security-core-impl/pom.xml, platform/security/core/security-core-impl/src/main/java/ddf/security/config/impl/ConfigurationSecurityLogger.java, platform/security/pdp/security-pdp-authzrealm/src/main/java/ddf/security/pdp/realm/xacml/processor/PollingPolicyFinderModule.java
Adds ProGrade security manager and policy file to container.
@paouelle @Lambeaux @SmithJosh @garrettfreibott @ryeats 
@clockard
@lessarderic
@stustison
Full regression test of DDF. This will potentially impact downstream projects; they will need to add/update policy files and `setenv` scripts accordingly.
N/A …
=> DDF-3297 Adds security manager to container

distribution/ddf-common/src/main/resources/common-bin.xml, distribution/ddf-common/src/main/resources/etc/org.apache.karaf.command.acl.shell.cfg, distribution/ddf-common/src/main/resources/etc/org.apache.karaf.command.acl.ssh.cfg, distribution/ddf-common/src/main/resources/etc/org.apache.karaf.shell.cfg, distribution/ddf-common/src/main/resources/security/default.policy, distribution/docs/src/main/resources/content/_configuring/environment-hardening.adoc, distribution/docs/src/main/resources/content/_configuring/hardening-user-access.adoc, pom.xml
Turns on local access to SSH into running DDF.
Also shuts down access to all but a specific subset of Karaf shell commands.
@tbatie @Lambeaux @vinamartin @paouelle @ricklarsen 
@clockard
@rzwiefel
@stustison
Install and SSH into running DDF. It should work from the same host as the instance and not from anywhere else.
Also check that access to Karaf commands is restricted to only the subset now specified in `etc/org.apache.karaf.command.acl.shell.cfg` and that they work correctly. Confirm that necessary/common functionality is not blocked from the shell.
This is now safe because of the introduction of the Java security manager. …
=> DDF-3273 [2.11.x] Turns SSH back on, only accessible from localhost.

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/CacheBulkProcessor.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/CachingFederationStrategy.java, distribution/sdk/sample-cometd/java-cli-example/src/main/java/org/codice/ddf/cli/CommandExecutor.java, platform/security/core/security-core-impl/src/main/java/ddf/security/config/impl/ConfigurationSecurityLogger.java
Fix dangerous condition where Throwable is caught by catching VirtualMachineErrors beforehand and rethrowing them so that important JVM errors that require action are not hidden
@coyotesqrl
@figliold  …
=> DDF-3324 Catch VirtualMachineError before Throwable

catalog/opensearch/catalog-opensearch-source/src/main/java/ddf/catalog/source/opensearch/impl/OpenSearchSource.java, catalog/opensearch/catalog-opensearch-source/src/test/java/ddf/catalog/source/opensearch/impl/TestOpenSearchSource.java, catalog/spatial/csw/spatial-csw-source-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/AbstractCswSource.java, catalog/spatial/csw/spatial-csw-source-common/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/TestCswSource.java
Update CSW and OpenSearch sources to include basic auth info in the retrieveResource properties map.
@vinamartin @mcalcote 
@clockard
@rzwiefel
Install DDF and setup federation to query over OpenSearch and CSW endpoints. The DDF being queried should be setup to only allow basic authentication for the OpenSearch and CSW endpoints. Verify that a resource can be downloaded over both of these endpoints only when a valid user/pass is provided in the source setup. 
[DDF-3318](https://codice.atlassian.net/browse/DDF-3318) …
=> DDF-3318 Update URLResourceReader usages to include basic auth info

platform/admin/ui/src/main/webapp/less/application/app-card.less, platform/admin/ui/src/main/webapp/less/utils.less
Fixes a problem where the description of an application would overflow the box it was held in depending on the size of the user's window.
@clockard 
@rzwiefel 
Install DDF and navigate to the admin console. Verify that resizing your browser does not cause the description text for applications to overflow the application boxes. This should be tested on IE10, chrome and firefox.
[DDF-3327](https://codice.atlassian.net/browse/DDF-3327) …
=> DDF-3327 Fix description overflow in Admin UI Application boxes

distribution/ddf-common/src/main/resources/common-bin.xml, distribution/ddf-common/src/main/resources/etc/org.apache.karaf.command.acl.shell.cfg, distribution/ddf-common/src/main/resources/etc/org.apache.karaf.command.acl.ssh.cfg, distribution/ddf-common/src/main/resources/etc/org.apache.karaf.shell.cfg, distribution/ddf-common/src/main/resources/security/default.policy, distribution/docs/src/main/resources/content/_configuring/environment-hardening.adoc, distribution/docs/src/main/resources/content/_configuring/hardening-user-access.adoc, pom.xml
Shuts down access to all but a specific subset of Karaf shell commands.
Also moves the Google code formatter check to the validate maven phase for fast-fail.
(cherry picked from commit 242930e)
@clockard
@rzwiefel
=> DDF-3273 Turns SSH back on, only accessible from localhost. (#2438)

catalog/admin/module/catalog-admin-module-maplayers/src/main/webapp/map-layers/index.js
The trash can icon in Map Layers is now the "error" color in the chosen theme. This is to make the icon stand out and be consistent with the admin-console-beta trash icon.
@djblue  @garrettfreibott 
@clockard 
@shaundmorris
Build DDF and make sure that the map layers trash icon is red and is aligned correctly. Observe that its correct in Chrome, Firefox and IE
[DDF-3353](https://codice.atlassian.net/browse/) …
=> DDF-3353 Made delete button in Map Layers red

libs/klv/pom.xml, libs/klv/src/main/java/org/codice/ddf/libs/klv/data/text/KlvEncodingDetectedString.java, libs/klv/src/test/java/org/codice/ddf/libs/klv/KlvEncodingDetectedStringTest.java
Adds KlvEncodingDetectedString which detects the encoding of the string in order to set the value properly.
@brendan-hofmann @glenhein @mcalcote  @ahoffer 
@lessarderic 
@rzwiefel
[DDF-3344](https://codice.atlassian.net/browse/DDF-3344)
=> [2.11.x] DDF-3344 Adds KlvEncodingDetectedString

distribution/ddf-common/src/main/resources/security/default.policy, distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/AbstractIntegrationTest.java
Updated `AbstractIntegrationTest` to add a leading slash for Windows OSs to fix itest permissions issues with the security manager.
@brianfelix 
@AzGoalie 
@tbatie 
@coyotesqrl
@rzwiefel
Run all itests on Windows machine and verify that the tests are able to be run instead of hanging on permissions issues. …
=> DDF-3297 Update itests to fix ddf.home.policy on Windows

distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestSecurity.java, platform/security/certificate/security-certificate-generator/src/main/java/org/codice/ddf/security/certificate/generator/CertificateGenerator.java
Changes the test to wait for the CertificateGenerator service to come up.
@ahoffer 
@clockard
CI Build
[DDF-3368](https://codice.atlassian.net/browse/DDF-3368)
=> DDF-3368 [2.11.x] TestSecurity.testCertificateGeneratorService() fails intermittently

catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/reader/TransactionMessageBodyReader.java
This PR add a NoNameCoder to the CSW Endpoint so elements with double underscores can be handled appropriately.
@adimka @mojogitoverhere 
@codice/data 
@millerw8
@rzwiefel
A full build should suffice
[DDF-3366](https://codice.atlassian.net/browse/DDF-3366) …
=> DDF-3366 Added NoNameCoder to CSW Endpoint

distribution/ddf-common/src/main/resources/security/default.policy, distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/AbstractIntegrationTest.java
Updated `AbstractIntegrationTest` to add a leading slash for Windows OSs to fix itest permissions issues with the security manager.
@brianfelix 
@AzGoalie 
@tbatie 
@coyotesqrl
@rzwiefel
Run all itests on Windows machine and verify that the tests are able to be run instead of hanging on permissions issues. …
=> DDF-3297 Update itests to fix ddf.home.policy on Windows (#2453)

catalog/core/catalog-core-directorymonitor/pom.xml, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/AbstractDurableFileConsumer.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/DavAlterationObserver.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/DurableFileAlterationListener.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/DurableFileComponent.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/DurableFileEndpoint.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/DurableFileSystemFileConsumer.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/DurableWebDavFileConsumer.java, catalog/core/catalog-core-directorymonitor/src/test/java/org/codice/ddf/catalog/content/monitor/DurableFileAlterationListenerTest.java, catalog/core/catalog-core-localstorageprovider/src/main/java/org/codice/ddf/catalog/content/impl/FileSystemStorageProvider.java
Makes sure a file has finished copying before trying to ingest it with the CDM.
Also fixed a potential NPE in FileSystemStorageProvider
Also fix multiple monitored directory issue.
@brendan-hofmann @emmberk 
@figliold
@rzwiefel
Install DDF and create a CDM for an empty directory.
Copy this script to a file and make it executable and changing 'cdm-dir' to the monitored directory configured for the CDM. The script simulates a slowly copying file. 
```
#!/bin/bash
for i in {1..60}
do
echo "Line $i" >> cdm-dir/cdm-changing-file.txt
sleep 1
done
```
Start the script and verify that the cdm-changing-file.txt doesn't show up in the catalog until after the script has finished. 
Run the script again and verify that the …
=> [2.11.x] DDF-3354 CDM verify file size is stable before ingesting

catalog/transformer/catalog-transformer-tika-input/src/main/java/ddf/catalog/transformer/input/tika/TikaInputTransformer.java, catalog/transformer/catalog-transformer-tika-input/src/test/java/ddf/catalog/transformer/input/tika/TikaInputTransformerTest.java
Fixes the TikaInputTransformer parsing bodyText instead of metadataText.
@gordocanchola @emmberk 
@clockard
@lessarderic
=> [2.11.x] DDF-3317 Fixed TikaInputTransformer parsing wrong metadata

catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/view/NodeModal.view.js, catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/templates/field.handlebars
Fixes registry multivalued fields so they are editable again. 
Fixes a related issue where the system name appeared editable.
@djblue @ahoffer @mcalcote 
@clockard
Verify that multivalued fields can be edited by adding new custom fields
Verify that when adding remote registries that all the fields are uneditable
Verify that the system name cannot be modified
[DDF-3367](https://codice.atlassian.net/browse/DDF-3367) …
=> [2.11.x] DDF-3367 Fixes registry multivalued fields

catalog/transformer/catalog-transformer-tika-input/src/main/java/ddf/catalog/transformer/input/tika/TikaInputTransformer.java, catalog/transformer/catalog-transformer-tika-input/src/test/java/ddf/catalog/transformer/input/tika/TikaInputTransformerTest.java
Updates the tika data types to use the correct types defined in the DataType enum
@emmberk 
@bdeining
@coyotesqrl
@figliold
@lessarderic
Install DDF and ingest some office documents. Verify that you can search for and find them.
[DDF-3210](https://codice.atlassian.net/browse/DDF-3210)
=> [2.11.x] DDF-3210 Update tika data types that were missed in the original PR

platform/admin/ui/src/main/webapp/less/application/app-card.less, platform/admin/ui/src/main/webapp/less/utils.less
Fixes a problem where the description of an application would overflow the box it was held in depending on the size of the user's window.
@clockard
Install DDF and navigate to the admin console. Verify that resizing your browser does not cause the description text for applications to overflow the application boxes. This should be tested on IE10, chrome and firefox.
[DDF-3327](https://codice.atlassian.net/browse/DDF-3327) …
=> [2.11.x] DDF-3327 Fix description overflow in Admin UI Application boxes (#2392)

distribution/ddf-common/src/main/resources/bin/setenv, distribution/ddf-common/src/main/resources/bin/setenv.bat, distribution/ddf-common/src/main/resources/common-bin.xml, distribution/docs/src/main/resources/content/_configuring/environment-hardening.adoc, distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/AbstractIntegrationTest.java
Turns off security manager.
@tbatie @paouelle 
@clockard
@lessarderic
@stustison
Full CI build. Full regression pass. …
=> [2.11.x] DDF-3273 Disable Java Security Manager & update hardening guide re: SSH

distribution/ddf-common/src/main/resources/bin/setenv, distribution/ddf-common/src/main/resources/bin/setenv.bat, distribution/ddf-common/src/main/resources/common-bin.xml, distribution/docs/src/main/resources/content/_configuring/environment-hardening.adoc, distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/AbstractIntegrationTest.java
Turns off security manager.
(cherry picked from commit bbe5f30)
@tbatie @paouelle 
@clockard
@lessarderic
@stustison
Full CI build. Full regression pass. …
=> DDF-3273 Disable Java Security Manager & update hardening guide re: SSH

catalog/core/catalog-core-standardframework/pom.xml, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/DeleteOperations.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/QueryOperations.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/UpdateOperations.java, catalog/core/catalog-core-standardframework/src/test/groovy/ddf/catalog/impl/operations/QueryOperationsSpec.groovy, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/MetacardApplication.java
Fixed ability to delete DeletedMetacards and also fixes SecurityLogger in the standardframework bundle
anyone
anyone
ensure you can restore metacards and the DeletedMetacard marker gets deleted on restore
https://codice.atlassian.net/browse/DDF-3369
=> [2.11.x] DDF-3369 Fixed ability to delete DeletedMetacards

distribution/ddf-common/src/main/resources/etc/system.properties
Adds `disable.configEdit=true` to `system.properties` file.
@paouelle 
@oconnormi 
@clockard
@pklinef
Build DDF with Solr configured as `HttpSolrClient`, and make sure the HTTP POST to `https://localhost:8993/solr/catalog/config/requestHandler` with the following data:
```
{
"add-updateprocessor" : {
"name" : "firstFld",
"class": "solr.FirstFieldValueUpdateProcessorFactory",
"fieldName":"test_s"
}
}
```
fails with the following error:
```
{
"responseHeader":{
"status":403,
"QTime":13625},
"error":{
"metadata":[
"error-class","org.apache.solr.common.SolrException",
"root-error-class","org.apache.solr.common.SolrException"],
"msg":" …
```
=> [2.11.x] DDF-3384 Disable Solr Config API

distribution/ddf-common/src/main/resources/bin/setenv-windows-wrapper.conf, distribution/ddf-common/src/main/resources/bin/setenv-wrapper.conf
Disables the security manager when running using the service wrapper.
@figliold @tbatie  
@clockard
@lessarderic
@stustison
@coyotesqrl …
=> DDF-3297 disable security manager when running using the service wrapper

distribution/ddf-common/src/main/resources/bin/ddf.bat, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/ImportMigrationContextImpl.java, platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/migration/ImportMigrationContextImplTest.java
It temporarily modifies import's clean directory feature to only delete files and not directories in order to workaround a delete handle still opened issue on Windows which renders us incapable of re-creating a directory we just deleted at import time.
A change in the migration API will be coming up with the same ticket that replace the need for this workaround.
@tbatie @emanns95 
@figliold
@lessarderic
Perform an export followed by an import on a Windows 2000 server machine.
[DDF-3383](https://codice.atlassian.net/browse/DDF-3383) …
=> [2.11.x] DDF-3383 temporarily modified clean directory() not to delete directories

libs/libs-pomfix-run/yarn.lock, pom.xml
- Upgrades frontend-maven-plugin to https://github.com/codice/frontend-maven-plugin/tree/frontend-plugins-1.6
- Upgrade necessary to upgrade yarn.
@lessarderic 
@oconnormi 
@figliold 
@clockard 
Just build and verify it works.
It was necessary to upgrade the frontend plugin to accommodate the latest yarn.
https://codice.atlassian.net/browse/DDF-3386 …
=> DDF-3386 Upgrades yarn and frontend-maven-plugin

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/workspace/QueryMetacardTypeImpl.java
It's no longer required to save a workspace twice after saving a search in Intrigue.
@emanns95 @AzGoalie 
@codice/ui 
@jlcsmith
1. Save a search in Intrigue.
2. Save the workspace.
3. Notice that the workspace appears saved the first time.
[DDF-3380](https://codice.atlassian.net/browse/DDF-3380)
=> [2.11.x] DDF-3380 Fixed needing to save a workspace twice after saving a search in Intrigue

catalog/core/catalog-core-directorymonitor/pom.xml, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/DurableFileAlterationListener.java
OpenJDK installs don't have the javafx class so replacing with an internal implementation.
@bdeining 
@lessarderic
CI build should be enough. If you want to get crazy you could try installing using OpenJDK and make sure the directory monitor works.
[DDF-3354](https://codice.atlassian.net/browse/DDF-3354)
=> [2.11.x] DDF-3354 Remove javafx.util.Pair and replace with internal class

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/MetacardApplication.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/notes/NoteAttributes.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/notes/NoteConstants.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/notes/NoteMetacard.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/notes/NoteMetacardType.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/notes/NoteUtil.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/util/EndpointUtil.java, catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/ui/catalog-ui-search/src/main/webapp/component/annotation/annotation.collection.js, catalog/ui/catalog-ui-search/src/main/webapp/component/annotation/annotation.collection.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/annotation/annotation.hbs, catalog/ui/catalog-ui-search/src/main/webapp/component/annotation/annotation.js, catalog/ui/catalog-ui-search/src/main/webapp/component/annotation/annotation.less, catalog/ui/catalog-ui-search/src/main/webapp/component/annotation/annotation.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/component.less, catalog/ui/catalog-ui-search/src/main/webapp/component/input/textarea/input-textarea.less, catalog/ui/catalog-ui-search/src/main/webapp/component/input/textarea/input-textarea.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/query-annotations/query-annotations.hbs, catalog/ui/catalog-ui-search/src/main/webapp/component/query-annotations/query-annotations.less, catalog/ui/catalog-ui-search/src/main/webapp/component/query-annotations/query-annotations.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/tabs/query/tabs-query.js, catalog/ui/catalog-ui-search/src/main/webapp/component/tabs/query/tabs-query.less, catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/util/EndpointUtilTest.java, catalog/ui/catalog-ui-search/yarn.lock
ATTN: DO NOT MERGE UNTIL 2.11 IS FORKED FROM MASTER. WAIT FOR 2.12-SNAPSHOT!
Add the ability to attach notes to workspace queries.
@bdeining 
@troymohl 
@bdeining
1) build and install
2) Create a workspace query. After the initial query has been created, there will be a new tab on the query called 'Notes'. You can add, edit and delete notes. You must be logged in as a non-guest user.
[DDF-3216](https://codice.atlassian.net/browse/DDF-3216) …
=> DDF-3216 add the ability to attach notes to workspace queries

distribution/ddf-common/src/main/resources/etc/startup.properties, platform/osgi/platform-osgi-configadmin/pom.xml, platform/osgi/platform-osgi-configadmin/src/main/resources/OSGI-INF/permissions.perm
Turns bundle cache encryption back on. It was turned off for Security Manager work.
@coyotesqrl 
@lessarderic  …
=> [2.11.x]DDF-3249 Turning bundle cache encryption back on

platform/error/platform-error-impl/src/main/resources/index.html, platform/security/common/src/main/resources/templates/redirectTemplate.html, platform/security/common/src/main/resources/templates/submitFormTemplate.html, platform/security/handler/security-handler-guest/src/main/resources/index.html
Removes the remaining xml tags from html pages. 
@djblue @ahoffer @rzwiefel @emanns95 
@clockard @lessarderic 
Install DDF and then update `org.codice.ddf.security.policy.context.impl.PolicyManager.config` such that IDP in the authenticationTypes is replaced with `basic|SAML`. I should look like this:  `"/\=basic|SAML|GUEST", \`
Attempt to log into DDF using IE11. The tags would cause an error when IE11 tried to render the page previously. No browser errors should occur with this changeset.
The other tags were removed in this pr: https://github.com/codice/ddf/pull/2488
[DDF-3309](https://codice.atlassian.net/browse/DDF-3309) …
=> [2.11.x] DDF-3309 Removed xml tags from html pages

catalog/transformer/catalog-transformer-tika-input/src/main/java/ddf/catalog/transformer/input/tika/TikaInputTransformer.java, catalog/transformer/catalog-transformer-tika-input/src/test/java/ddf/catalog/transformer/input/tika/TikaInputTransformerTest.java
Ensure tika metacards have the extracted text attribute defined.
@mcalcote @ahoffer @gordocanchola 
@lessarderic
@rzwiefel
@shaundmorris
Ingest office documents and ensure that they have the ext.extracted.txt attribute defined.
[DDF-3007](https://codice.atlassian.net/browse/DDF-3007)
=> DDF-3007 Ensure tika metacards have the extracted text attribute defined.

catalog/core/catalog-core-contentresourcereader/src/main/java/org/codice/ddf/catalog/content/resource/reader/DerivedContentActionProvider.java, catalog/core/catalog-core-contentresourcereader/src/test/java/org/codice/ddf/catalog/content/resource/reader/DerivedContentActionProviderTest.java, catalog/spatial/registry/registry-publication-action-provider/src/main/java/org/codice/ddf/registry/publication/action/provider/RegistryPublicationActionProvider.java, catalog/spatial/registry/registry-report-action-provider/pom.xml, catalog/spatial/registry/registry-report-action-provider/src/main/java/org/codice/ddf/registry/report/action/provider/RegistryReportActionProvider.java, catalog/spatial/registry/registry-report-action-provider/src/test/java/org/codice/ddf/registry/report/action/provider/TestRegistryReportActionProvider.java, platform/action/core/platform-action-core-api/src/main/java/ddf/action/MultiActionProvider.java
This PR updates the javadoc in `MultiActionProvider` to clarify that `canHandle` should be called before `getActions`.
Most of the implementations of `getActions` were duplicating checking `canHandle`.
@AzGoalie @peterhuffer @gordocanchola
@clockard
@rzwiefel
Full build.
[DDF-3373](https://codice.atlassian.net/browse/DDF-3373)
=> DDF-3373 Updated the javadoc in MultiActionProvider to clarify that canHandle should be called before getActions

catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/InspectCommand.java, catalog/core/catalog-core-commands/src/test/java/org/codice/ddf/commands/catalog/InspectCommandTest.java
Adds displaying of multi-valued attributes to the `catalog:inspect` command.
@vinamartin 
@ahoffer 
@coyotesqrl
@figliold 
Inspect a metacard that has a multi-valued attribute and see that all the values are listed.
[DDF-3308](https://codice.atlassian.net/browse/DDF-3308)
- ❗ …
=> DDF-3308 Added multi-valued attr suppport for inspect command

distribution/docs/src/main/resources/content/_metadataAttributes/associations-attributes-table.adoc, distribution/docs/src/main/resources/content/_metadataAttributes/contact-attributes-table.adoc, distribution/docs/src/main/resources/content/_metadataAttributes/core-attributes-table.adoc, distribution/docs/src/main/resources/content/_metadataAttributes/datetime-attributes-table.adoc, distribution/docs/src/main/resources/content/_metadataAttributes/history-attributes-table.adoc, distribution/docs/src/main/resources/content/_metadataAttributes/location-attributes-table.adoc, distribution/docs/src/main/resources/content/_metadataAttributes/media-attributes-table.adoc, distribution/docs/src/main/resources/content/_metadataAttributes/metacard-attributes-table.adoc, distribution/docs/src/main/resources/content/_metadataAttributes/mp4-attributes.adoc, distribution/docs/src/main/resources/content/_metadataAttributes/security-attributes-table.adoc, distribution/docs/src/main/resources/content/_metadataAttributes/topic-attributes-table.adoc, distribution/docs/src/main/resources/content/_metadataAttributes/validation-attributes-table.adoc, distribution/docs/src/main/resources/jbake.properties, distribution/docs/src/main/resources/templates/appendices.ftl
- fixes jbake type declaration that was not following convention. All type names should be camel case.
@mcalcote @oconnormi 
@clockard
@coyotesqrl
@lessarderic
@pklinef
@rzwiefel
@shaundmorris
- build logs were showing a null pointer exception. Docs still rendered as expected. Error should be gone now. …
=> [2.11.x] DDF-2824 corrected typo in docs template and jbake.properties file

catalog/async/catalog-async-data-api/src/main/java/org/codice/ddf/catalog/async/data/api/internal/InaccessibleResourceException.java, catalog/async/catalog-async-data-api/src/main/java/org/codice/ddf/catalog/async/data/api/internal/ProcessResource.java, catalog/async/catalog-async-data-api/src/main/java/org/codice/ddf/catalog/async/data/api/internal/ProcessResourceItem.java, catalog/async/catalog-async-data/pom.xml, catalog/async/catalog-async-data/src/main/java/org/codice/ddf/catalog/async/data/impl/LazyProcessResourceImpl.java, catalog/async/catalog-async-data/src/main/java/org/codice/ddf/catalog/async/data/impl/ProcessCreateItemImpl.java, catalog/async/catalog-async-data/src/main/java/org/codice/ddf/catalog/async/data/impl/ProcessResourceImpl.java, catalog/async/catalog-async-data/src/test/groovy/org/codice/ddf/catalog/async/data/LazyProcessResourceImplTest.groovy, catalog/async/catalog-async-data/src/test/groovy/org/codice/ddf/catalog/async/data/ProcessResourceImplTest.groovy, catalog/async/catalog-async-postingestplugin/pom.xml, catalog/async/catalog-async-postingestplugin/src/main/java/org/codice/ddf/catalog/async/processingplugin/ProcessingPostIngestPlugin.java, catalog/async/catalog-async-postingestplugin/src/test/groovy/org/codice/ddf/catalog/async/processingplugin/ProcessingPostIngestPluginTest.groovy, catalog/async/catalog-async-processingframework/src/main/java/org/codice/ddf/catalog/async/processingframework/impl/InMemoryProcessingFramework.java, catalog/async/catalog-async-processingframework/src/test/groovy/org/codice/ddf/catalog/async/processingframework/impl/InMemoryProcessingFrameworkTest.groovy
Adding markMetacardAsModified to the ProcessResourceItem interface.
Changing InMemoryProcessingFramework's storeProcessRequest to handle the case where a resource exist but only the metacard was modified.
Changing the way we close ProcessResource input streams in InMemoryProcessingFramework to use the ProcessResource's new close method
The original way of getting the input stream and closing it directly was causing the lazy loaded process resource to load the resource, just to close the stream.
Adding a LazyProcessResource that will only load the resource when it is accessed
the LazyProcessResources is passed a Supplier that will be used to load the resource
Changing the ProcessingPostIngestPlugin to use the LazyProcessResource instead of ProcessResource that is loading all resources …
=> DDF-3278 Updating Async Processing Framework with LazyProcessResource

platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/ImportMigrationContextImpl.java, platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/migration/ImportMigrationContextImplTest.java
**2.11.x PR: [2507](https://github.com/codice/ddf/pull/2507)**
It temporarily modifies import's clean directory feature to only delete files and not directories in order to workaround a delete handle still opened issue on Windows which renders us incapable of re-creating a directory we just deleted at import time.
A change in the migration API will be coming up with the same ticket that replace the need for this workaround.
@lessarderic
Perform an export followed by an import on a Windows 2000 server machine.
[DDF-3383](https://codice.atlassian.net/browse/DDF-3383) …
=> DDF-3383 temporarily modified clean directory() not to delete directories

catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/IngestCommand.java
This PR updates the `catalog:ingest` command so that it no longers logs duplicate warnings to the ingest log and also stops warnings from being printed on the console that interrupt the progress bar.
_Before:_
console
```
admin@root()> catalog:ingest -t xml path/to/some/records
0% [>                                                                       ]     0 records/secFailed to ingest file [path/to/some/records/someImage.png].
80% [=========================================================>              ]    21 records/sec
4 file(s) ingested in 0 seconds
1 file(s) failed to be ingested.  See the ingest log for more details.
```
ingest log:
```
10:09:07,522 | WARN  | tCommandThread 0 | ingestLogger                     | f.commands.catalog.IngestCommand  447 | 359 - …
```
=> DDF-3401 Fixed catalog:ingest command from printing duplicate error messages

platform/security/servlet/security-servlet-logout/src/main/java/org/codice/ddf/security/servlet/logout/LogoutService.java
Adds `no-cache` and `no-store` to the responses from LogoutService.
@peterhuffer @emmberk @emanns95 
@clockard
1. Install DDF normally
2. Clear browser cache, cookies, sessions or use an incognito/private window.
3. Login as Guest
4. Visit https://localhost:8993/logout and verify that you are logged in as Guest
5. Logout of Guest
6. Login as Admin
7. Visit https://localhost:8993/logout and verify that you are logged in as Admin
[DDF-3402](https://codice.atlassian.net/browse/3402)
- ❓ (Question …
=> DDF-3402 Added cache control headers to LogoutService

distribution/ddf-common/src/main/resources/etc/startup.properties, platform/osgi/platform-osgi-configadmin/pom.xml, platform/osgi/platform-osgi-configadmin/src/main/resources/OSGI-INF/permissions.perm
Turns bundle cache encryption back on. It was turned off for Security Manager work.
@coyotesqrl 
@lessarderic 
[DDF-3249](https://codice.atlassian.net/browse/DDF-3249)
- ❗ …
=> DDF-3249 Turning bundle cache encryption back on

catalog/core/catalog-core-standardframework/pom.xml, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/DeleteOperations.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/QueryOperations.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/UpdateOperations.java, catalog/core/catalog-core-standardframework/src/test/groovy/ddf/catalog/impl/operations/QueryOperationsSpec.groovy, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/MetacardApplication.java
Fixed ability to delete DeletedMetacards and also fixes SecurityLogger in the standardframework bundle
anyone
anyone
ensure you can restore metacards and the DeletedMetacard marker gets deleted on restore
https://codice.atlassian.net/browse/DDF-3369
=> DDF-3369 Fixed ability to delete DeletedMetacards

libs/libs-pomfix-run/yarn.lock, pom.xml
- Upgrades frontend-maven-plugin to https://github.com/codice/frontend-maven-plugin/tree/frontend-plugins-1.6
- Upgrade necessary to upgrade yarn.
backports #2513 
@clockard @shaundmorris 
=> [2.11.x] DDF-3386 Upgrades yarn and frontend-maven-plugin

catalog/admin/module/catalog-admin-module-maplayers/src/main/webapp/map-layers/index.js, catalog/admin/module/catalog-admin-module-maplayers/src/main/webapp/map-layers/reducer.js, catalog/admin/module/catalog-admin-module-maplayers/src/main/webapp/map-layers/validate.spec.js, catalog/ui/catalog-ui-search/src/main/webapp/js/controllers/cesium.layerCollection.controller.js
Adds a `withCredentials` field to the imagery providers json so each provider can optionally be added as a trusted server in Cesium. Also adds a new option in the Map Layers Configuration UI and changes the Show and Transparent toggle to checkboxes for consistency.
@djblue @bdeining
@millerw8
Add a new imagery provider using the Map Layers Configuration UI. Give it a name, set the url to `http://c.tile.openstreetmap.org`, set alpha to 1, set provider type to "Open Street Map", and only check "show" (leave all the other boxes unchecked). Go to `/search/catalog/` and you should see the …
=> DDF-3379 Add support for adding imagery providers as trusted servers

platform/error/platform-error-impl/src/main/resources/index.html, platform/security/common/src/main/resources/templates/redirectTemplate.html, platform/security/common/src/main/resources/templates/submitFormTemplate.html, platform/security/handler/security-handler-guest/src/main/resources/index.html
Removes the remaining xml tags from html pages. 
Port of https://github.com/codice/ddf/pull/2530
@djblue @ahoffer @rzwiefel @emanns95 
@clockard @lessarderic 
Install DDF and then update `org.codice.ddf.security.policy.context.impl.PolicyManager.config` such that IDP in the authenticationTypes is replaced with `basic|SAML`. I should look like this:  `"/\=basic|SAML|GUEST", \`
Attempt to log into DDF using IE11. The tags would cause an error when IE11 tried to render the page previously. No browser errors should occur with this changeset.
The other tags were removed in this pr: https://github.com/codice/ddf/pull/2350
[DDF-3309](https://codice.atlassian.net/browse/DDF-3309) …
=> DDF-3309 Removed remaining xml tags from html pages

catalog/async/catalog-async-data-api/src/main/java/org/codice/ddf/catalog/async/data/api/internal/InaccessibleResourceException.java, catalog/async/catalog-async-data-api/src/main/java/org/codice/ddf/catalog/async/data/api/internal/ProcessResource.java, catalog/async/catalog-async-data-api/src/main/java/org/codice/ddf/catalog/async/data/api/internal/ProcessResourceItem.java, catalog/async/catalog-async-data/pom.xml, catalog/async/catalog-async-data/src/main/java/org/codice/ddf/catalog/async/data/impl/LazyProcessResourceImpl.java, catalog/async/catalog-async-data/src/main/java/org/codice/ddf/catalog/async/data/impl/ProcessCreateItemImpl.java, catalog/async/catalog-async-data/src/main/java/org/codice/ddf/catalog/async/data/impl/ProcessResourceImpl.java, catalog/async/catalog-async-data/src/test/groovy/org/codice/ddf/catalog/async/data/LazyProcessResourceImplTest.groovy, catalog/async/catalog-async-data/src/test/groovy/org/codice/ddf/catalog/async/data/ProcessResourceImplTest.groovy, catalog/async/catalog-async-postingestplugin/pom.xml, catalog/async/catalog-async-postingestplugin/src/main/java/org/codice/ddf/catalog/async/processingplugin/ProcessingPostIngestPlugin.java, catalog/async/catalog-async-postingestplugin/src/test/groovy/org/codice/ddf/catalog/async/processingplugin/ProcessingPostIngestPluginTest.groovy, catalog/async/catalog-async-processingframework/src/main/java/org/codice/ddf/catalog/async/processingframework/impl/InMemoryProcessingFramework.java, catalog/async/catalog-async-processingframework/src/test/groovy/org/codice/ddf/catalog/async/processingframework/impl/InMemoryProcessingFrameworkTest.groovy
2.11.x backport of PR #2310 
Adding markMetacardAsModified to the ProcessResourceItem interface.
Changing InMemoryProcessingFramework's storeProcessRequest to handle the case where a resource exist but only the metacard was modified.
Changing the way we close ProcessResource input streams in InMemoryProcessingFramework to use the ProcessResource's new close method
The original way of getting the input stream and closing it directly was causing the lazy loaded process resource to load the resource, just to close the stream.
LazyProcessResourceImpl:
Adding a LazyProcessResource that will only load the resource when it is accessed
the LazyProcessResources is passed a Supplier that will be used to load the resource
Changing the ProcessingPostIngestPlugin to use the LazyProcessResource instead …
=> [2.11.x] DDF-3278 Async Processing Framework

catalog/ui/catalog-ui-search/.nsprc
Adds an exception for a dependency of plotly.js to the catalog-ui-search bundle.
@oconnormi @vinamartin @djblue 
@andrewkfiedler @rzwiefel
Observe the changes, run nsp check script to confirm the exception.
This was causing the Node Js Security phase of the build to fail.
[DDF-3345](https://codice.atlassian.net/browse/DDF-3345)
=> [2.11.x] DDF-3345 Update node security vulnerabilities for plotly.js

distribution/docs/src/main/resources/content/_appendixIntros/dependency-list-intro.adoc, distribution/docs/src/main/resources/content/_appendixIntros/metadata-attributes-intro.adoc, distribution/docs/src/main/resources/content/_appendixIntros/whitelist-intro.adoc, distribution/docs/src/main/resources/content/_dependencyList/ddf-dependency-list.adoc, distribution/docs/src/main/resources/content/_metadataAttributes/associations-attributes-table.adoc, distribution/docs/src/main/resources/content/_metadataAttributes/catalog-taxonomy-intro.adoc, distribution/docs/src/main/resources/content/_metadataAttributes/complete-list-file-types.adoc, distribution/docs/src/main/resources/content/_metadataAttributes/contact-attributes-table.adoc, distribution/docs/src/main/resources/content/_metadataAttributes/core-attributes-table.adoc, distribution/docs/src/main/resources/content/_metadataAttributes/datetime-attributes-table.adoc, distribution/docs/src/main/resources/content/_metadataAttributes/format-specific-attributes.adoc, distribution/docs/src/main/resources/content/_metadataAttributes/history-attributes-table.adoc, distribution/docs/src/main/resources/content/_metadataAttributes/location-attributes-table.adoc, distribution/docs/src/main/resources/content/_metadataAttributes/media-attributes-table.adoc, distribution/docs/src/main/resources/content/_metadataAttributes/metacard-attributes-table.adoc, distribution/docs/src/main/resources/content/_metadataAttributes/mp4-attributes.adoc, distribution/docs/src/main/resources/content/_metadataAttributes/security-attributes-table.adoc, distribution/docs/src/main/resources/content/_metadataAttributes/topic-attributes-table.adoc, distribution/docs/src/main/resources/content/_metadataAttributes/validation-attributes-table.adoc, distribution/docs/src/main/resources/content/_whitelists/admin-whitelist.adoc, distribution/docs/src/main/resources/content/_whitelists/catalog-whitelist.adoc, distribution/docs/src/main/resources/content/_whitelists/platform-whitelist.adoc, distribution/docs/src/main/resources/content/_whitelists/registry-whitelist.adoc, distribution/docs/src/main/resources/content/_whitelists/removed-whitelist.adoc, distribution/docs/src/main/resources/content/_whitelists/security-whitelist.adoc, distribution/docs/src/main/resources/content/_whitelists/solr-whitelist.adoc, distribution/docs/src/main/resources/content/_whitelists/spatial-whitelist.adoc, distribution/docs/src/main/resources/content/_whitelists/ui-whitelist.adoc, distribution/docs/src/main/resources/templates/appendices.ftl
Fixes appendix template in docs to allow specifying defined order to sections.
@emmberk @mcalcote @vinamartin @ahoffer @garrettfreibott 
@clockard
@coyotesqrl
@lessarderic
@pklinef
@rzwiefel
@shaundmorris
-appendix builds successfully. No content changes made.
=> DDF-2824 fixed appendix docs template

platform/security/servlet/security-servlet-whoami/src/test/groovy/org/codice/ddf/security/servlet/whoami/SubjectSpecification.groovy
Fixes failing tests in WhoAmI unit tests. Ensure that there will be days, hours, minutes, and seconds differences in time while testing.
@oconnormi 
@adimka 
@bdeining
@pklinef
Full build.
Corrects the error that occurred in WhoAmI tests:
[ERROR] formats expiration duration of assertion(org.codice.ddf.security.servlet.whoami.WhoAmISpec)  Time elapsed: 0.16 s  <<< FAILURE!
org.spockframework.runtime.ConditionNotSatisfiedError:
Condition not satisfied:
duration.contains('days')
|        |
|        false
59 minutes 59 seconds
at org.codice.ddf.security.servlet.whoami.WhoAmISpec.formats expiration duration of assertion(WhoAmISpec.groovy:104) …
=> DDF-3138 Fix for WhoAmI groovy test failure

distribution/docs/src/main/resources/content/_appendixIntros/dependency-list-intro.adoc, distribution/docs/src/main/resources/content/_appendixIntros/metadata-attributes-intro.adoc, distribution/docs/src/main/resources/content/_appendixIntros/whitelist-intro.adoc, distribution/docs/src/main/resources/content/_dependencyList/ddf-dependency-list.adoc, distribution/docs/src/main/resources/content/_metadataAttributes/associations-attributes-table.adoc, distribution/docs/src/main/resources/content/_metadataAttributes/catalog-taxonomy-intro.adoc, distribution/docs/src/main/resources/content/_metadataAttributes/complete-list-file-types.adoc, distribution/docs/src/main/resources/content/_metadataAttributes/contact-attributes-table.adoc, distribution/docs/src/main/resources/content/_metadataAttributes/core-attributes-table.adoc, distribution/docs/src/main/resources/content/_metadataAttributes/datetime-attributes-table.adoc, distribution/docs/src/main/resources/content/_metadataAttributes/format-specific-attributes.adoc, distribution/docs/src/main/resources/content/_metadataAttributes/history-attributes-table.adoc, distribution/docs/src/main/resources/content/_metadataAttributes/location-attributes-table.adoc, distribution/docs/src/main/resources/content/_metadataAttributes/media-attributes-table.adoc, distribution/docs/src/main/resources/content/_metadataAttributes/metacard-attributes-table.adoc, distribution/docs/src/main/resources/content/_metadataAttributes/mp4-attributes.adoc, distribution/docs/src/main/resources/content/_metadataAttributes/security-attributes-table.adoc, distribution/docs/src/main/resources/content/_metadataAttributes/topic-attributes-table.adoc, distribution/docs/src/main/resources/content/_metadataAttributes/validation-attributes-table.adoc, distribution/docs/src/main/resources/content/_whitelists/admin-whitelist.adoc, distribution/docs/src/main/resources/content/_whitelists/catalog-whitelist.adoc, distribution/docs/src/main/resources/content/_whitelists/platform-whitelist.adoc, distribution/docs/src/main/resources/content/_whitelists/registry-whitelist.adoc, distribution/docs/src/main/resources/content/_whitelists/removed-whitelist.adoc, distribution/docs/src/main/resources/content/_whitelists/security-whitelist.adoc, distribution/docs/src/main/resources/content/_whitelists/solr-whitelist.adoc, distribution/docs/src/main/resources/content/_whitelists/spatial-whitelist.adoc, distribution/docs/src/main/resources/content/_whitelists/ui-whitelist.adoc, distribution/docs/src/main/resources/templates/appendices.ftl
**BACKPORT of PR https://github.com/codice/ddf/pull/2586**
Fixes appendix template in docs to allow specifying defined order to sections.
@emmberk @mcalcote @vinamartin @ahoffer @garrettfreibott 
@clockard
@coyotesqrl
@lessarderic
@pklinef
@rzwiefel
@shaundmorris
-appendix builds successfully. No content changes made. …
=> DDF-2824 fixed appendix docs template (#2586)

catalog/ui/catalog-ui-search/.nsprc
Adds an exception for a dependency of plotly.js to the catalog-ui-search bundle.
@oconnormi @vinamartin @djblue 
@andrewkfiedler @rzwiefel
Observe the changes, run nsp check script to confirm the exception.
This was causing the Node Js Security phase of the build to fail.
2.11.x PR - https://github.com/codice/ddf/pull/2547
[DDF-3345](https://codice.atlassian.net/browse/DDF-3345)
=> DDF-3345 Update node security vulnerabilities for plotly.js

catalog/spatial/registry/registry-admin-modules/registry-admin-remote-ui/src/main/webapp/js/model/Registry.js
Fix remote registry modal closing issue when deleting
@vinamartin @mcalcote @peterhuffer 
@bdeining
@rzwiefel
Install DDF and install the registry
Navigate to the Remote Registries tab 
Add some remote registry
Click the trash can icon to see the "Delete Registry Configuration" window
Select some remote registry to delete and click delete
See that the modal does disappears 
[DDF-3417](https://codice.atlassian.net/browse/DDF-3417)
=> [2.11.x] DDF-3417 Fix remote registry modal closing issue when deleting

catalog/spatial/csw/spatial-csw-source/src/main/resources/OSGI-INF/metatype/metatype.xml, distribution/docs/src/main/resources/content/_tables/Csw_Federation_Profile_Source.adoc
Add timeout parameters to CSW federation source metatype
@peterhuffer @emmberk @AzGoalie 
@coyotesqrl
@figliold
Install DDF
Go to Catalog->Sources and add CSW Federation Profile Source
Verify that you can set the two timeout parameters
[DDF-3419](https://codice.atlassian.net/browse/DDF-3419)
=> [2.11.x] DDF-3419 Add timeout parameters to CSW federation source metatype

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/UpdateOperations.java
Updates the page size in UpdateOperations that was missed in the ResultsIterator updates
@emmberk @peterhuffer @AzGoalie 
@coyotesqrl
@rzwiefel
Easiest way to test is to setup to DDFs with registries. 
Publish/Subscribe ddf1 to ddf2. 
Update ddf1 identity node by adding a description and save.
Verify that ddf2 has the updated description in its remote nodes.
[DDF-3425](https://codice.atlassian.net/browse/DDF-3425)
=> [2.11.x] DDF-3425 Fix UpdateOperations page size

catalog/spatial/csw/spatial-csw-source-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/AbstractCswSource.java
In the event that alignStream throws an IOException,  the InputStream passed in will be orphaned and become a resource leak. This change closes the stream when the IOException is caught, before it is re-thrown. 
@rzwiefel @idperez @stustison @garrettfreibott @shaundmorris 
Review changes
This was identified by a coverity scan.
[DDF-3362](https://codice.atlassian.net/browse/DDF-3362)
=> DDF-3362 Update AbstractCswSource.alignStream to close resource for IOException

Jenkinsfile
Updating the sonar coverage exclusion helps improve coverage by avoiding files that should not be analyzed by sonarqube. This includes .adoc .js .xml as well as JAXB and WSDL directories. 
@oconnormi @vinamartin 
@codice/build 
@clockard @lessarderic
This exclusion pattern can be seen in the locally running/succeeding DDF sonar job.
This pattern helped improve the coverage from 48% to 63%. …
=> DDF-3261 Update sonar exclusion pattern to improve coverage

platform/security/handler/security-handler-pki/src/main/java/org/codice/ddf/security/handler/pki/AbstractPKIHandler.java, platform/security/handler/security-handler-pki/src/test/java/org/codice/ddf/security/handler/pki/PKIHandlerTest.java, platform/security/policy/security-policy-context/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/security/policy/security-policy-context/src/main/resources/OSGI-INF/metatype/metatype.xml
Error Messages reporting a revoked certificate used to return 500, now returns 403.
@rzwiefel @vinamartin @garrettfreibott
@shaundmorris
@stustison
1. Build DDF
2. Talk to @josephthweatt or @garrettfreibott 
[DDF-3394](https://codice.atlassian.net/browse/DDF-3394)
=> DDF-3394 Revoked Certificate now returns 403 instead of 500

platform/security/handler/security-handler-pki/src/main/java/org/codice/ddf/security/handler/pki/AbstractPKIHandler.java, platform/security/handler/security-handler-pki/src/test/java/org/codice/ddf/security/handler/pki/PKIHandlerTest.java, platform/security/policy/security-policy-context/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/security/policy/security-policy-context/src/main/resources/OSGI-INF/metatype/metatype.xml
Error Messages reporting a revoked certificate used to return 500, now returns 403.
@rzwiefel @vinamartin @garrettfreibott
@clockard 
@stustison
1. Build DDF
2. Talk to @josephthweatt or @garrettfreibott 
[DDF-3394](https://codice.atlassian.net/browse/DDF-3394)
=> [2.11.x] DDF-3394 Revoked Certificate now returns 403 instead of 500

platform/security/servlet/security-servlet-whoami/src/test/groovy/org/codice/ddf/security/servlet/whoami/SubjectSpecification.groovy
#Backport for @troymohl's commit: https://github.com/codice/ddf/pull/2592
Fixes failing tests in WhoAmI unit tests. Ensure that there will be days, hours, minutes, and seconds differences in time while testing.
@mcalcote @blen-desta 
@clockard
@coyotesqrl 
`mvn clean install` inside platform/security/servlet/security-servlet-whoami
[DDF-3138](https://codice.atlassian.net/browse/DDF-3138) …
=> [2.11.x] DDF-3138 Fix for groovy test failure (#2592)

platform/security/sts/security-sts-server/README.md, platform/security/sts/security-sts-server/pom.xml, platform/security/sts/security-sts-server/src/main/java/ddf/security/sts/DefaultInMemoryTokenStore.java, platform/security/sts/security-sts-server/src/main/java/ddf/security/sts/EHCacheManagerHolder.java, platform/security/sts/security-sts-server/src/main/java/ddf/security/sts/EHCacheTokenStore.java, platform/security/sts/security-sts-server/src/main/java/ddf/security/sts/EHCacheUtils.java, platform/security/sts/security-sts-server/src/main/resources/OSGI-INF/blueprint/tokenstore.xml
-Copies classes directly from the `cxf-rt-ws-security`and `wss4j` bundles that depend on classes from the `net.sf.ehcache` package into DDF's `security-sts-server` bundle. There seemed to be a timing issue where the ehcache dependency brought in by `cxf-rt-ws-security` and `wss4j` wasn’t available at the time `security-sts-server` needed it, causing NoClassDefFoundError exceptions to occur. This fix will prevent the need for `cxf-rt-ws-security` and `wss4j` to bring in the ehcache dependency as the classes that depend on ehcache are contained in `security-sts-server` instead.
@ryeats 
@jaymcnallie
@stustison
1. Run a …
=> DDF-3364 Fix the security-sts-server to successfully start up after restarting DDF when the broker-app is installed

platform/security/sts/security-sts-server/README.md, platform/security/sts/security-sts-server/pom.xml, platform/security/sts/security-sts-server/src/main/java/ddf/security/sts/DefaultInMemoryTokenStore.java, platform/security/sts/security-sts-server/src/main/java/ddf/security/sts/EHCacheManagerHolder.java, platform/security/sts/security-sts-server/src/main/java/ddf/security/sts/EHCacheTokenStore.java, platform/security/sts/security-sts-server/src/main/java/ddf/security/sts/EHCacheUtils.java, platform/security/sts/security-sts-server/src/main/resources/OSGI-INF/blueprint/tokenstore.xml
Backport of https://github.com/codice/ddf/pull/2490
@ryeats 
@jaymcnallie
@stustison
1. Run a full build. 
2. Install DDF, install the broker-app. Restart DDF. Make sure the `security-sts-server` bundle has successfully started.
[DDF-3364](https://codice.atlassian.net/browse/DDF-3364) …
=> [2.11.x] DDF-3364 Fix the security-sts-server to successfully start up after restarting DDF when the broker-app is installed

platform/admin/ui/src/main/webapp/js/views/configuration/Service.view.js, platform/admin/ui/src/main/webapp/templates/configuration/configurationRow.handlebars
Removes the ability to delete non factory configurations as these configurations can't really be deleted so even when removing the configuration the configuration will persist. 
@tbatie @djblue @Lambeaux @lessarderic 
@pklinef
@rzwiefel
Navigate to the Platform app in the UI and click the Configuration tab.
Configure "Platform UI Configuration".
Verify it can't be deleted. 
Verify the Custom Mime Types _can_ be deleted
[DDF-3436](https://codice.atlassian.net/browse/DDF-3436) …
=> [2.11.x] DDF-3436 Removes the ability to delete non factory configurations

catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/RemoveAllCommand.java, distribution/docs/src/main/resources/content/_running/command-scheduler.adoc, platform/platform-scheduler/pom.xml, platform/platform-scheduler/src/main/java/ddf/platform/scheduler/CommandJob.java, platform/platform-scheduler/src/main/java/ddf/platform/scheduler/ScheduledCommandTask.java, platform/platform-scheduler/src/main/java/ddf/platform/scheduler/ScheduledTask.java, platform/platform-scheduler/src/main/java/ddf/platform/scheduler/ServiceStore.java, platform/platform-scheduler/src/main/resources/OSGI-INF/metatype/metatype.xml, platform/platform-scheduler/src/main/resources/quartz.properties, platform/platform-scheduler/src/test/java/ddf/platform/scheduler/CommandJobTest.java, platform/security/common/src/main/java/org/codice/ddf/security/common/Security.java
This PR fixes an issue where platform-scheduler fails on the first attempt(s) to run command jobs after a restart. There is now a 1 minute delay before `Platform Command Scheduler` jobs are started.
@peterhuffer @AzGoalie @oconnormi 
@clockard
@lessarderic
1. Before starting up for the first time, add a `ddf.platform.scheduler.Command` configuration file to `/etc`. When I tested, I used
_`ddf.platform.scheduler.Command-removeExpiredRecords.config`_
```
command="removeall\ -f\ --expired"
intervalString="10"
intervalType="secondInterval"
```
I made the interval small so I could see it execute multiple times. I also used a command that will only work after installation to make sure that everything works as expected.
2. Start up DDF.
3. Search for `platform-scheduler` in the ddf log, and …
=> [2.11.x] DDF-3335 Added delayed start to Platform Command Scheduler jobs

catalog/ui/catalog-ui-search/src/main/webapp/js/controllers/cesium.layerCollection.controller.js, catalog/ui/catalog-ui-search/src/main/webapp/js/controllers/common.layerCollection.controller.js, catalog/ui/catalog-ui-search/src/main/webapp/js/controllers/ol.layerCollection.controller.js, catalog/ui/catalog-ui-search/src/main/webapp/js/model/User.js
Configures Cesium and Open Layers to only fetch tiles if `show=true` and `alpha > 0`.
@adimka @mackncheesiest @Variadicism @glenhein @brianfelix 
@codice/ui
@bdeining
Configure a map layer in the Admin UI under `Applications` -> `Catalog` -> `Map Layers Configuration`.  Enter a name, set URL to `http://c.tile.openstreetmap.org`, set alpha to 1, and ensure only show is checked. Open a workspace in Intrigue (3D map) and open the dev tools. Verify image tiles are being fetched. Open the map layers configuration in the top right and set transparency to 0 (drag to the right). Repeat the procedure for a 2D map. …
=> DDF-3432 Only fetch imagery tiles if alpha > 0

catalog/ui/catalog-ui-search/src/main/webapp/component/query-basic/query-basic.view.js
Fixes an issue where the Basic query in Intrigue results in a cql filter being generated with a doubled anyText parameter
@peterhuffer @emmberk @AzGoalie 
@codice/ui 
@andrewkfiedler @clockard 
Create a basic query and observe the cql contents being sent out to ensure that the anyText term is only present once
[DDF-3444](https://codice.atlassian.net/browse/DDF-3444) …
=> [2.11.x] DDF-3444 Fixing doubled anyText filter in Intrigue basic query

catalog/core/catalog-core-camelcomponent/src/main/java/ddf/camel/component/catalog/content/ContentProducer.java, catalog/core/catalog-core-camelcomponent/src/main/java/ddf/camel/component/catalog/content/ContentProducerDataAccessObject.java, catalog/core/catalog-core-camelcomponent/src/test/java/ddf/camel/component/catalog/content/ContentProducerDataAccessObjectTest.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/AbstractDurableFileConsumer.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/DurableWebDavFileConsumer.java, catalog/core/catalog-core-localstorageprovider/src/main/java/org/codice/ddf/catalog/content/impl/FileSystemStorageProvider.java, catalog/core/catalog-core-localstorageprovider/src/test/java/org/codice/ddf/catalog/content/impl/FileSystemStorageProviderTest.java, distribution/ddf-common/src/main/resources/etc/log4j2.config.xml, distribution/ddf-common/src/main/resources/etc/org.ops4j.pax.logging.cfg
Back port of https://github.com/codice/ddf/pull/2604
@AzGoalie @emmberk @brendan-hofmann
@clockard 
@lessarderic
Follow instructions in description of https://codice.atlassian.net/browse/DDF-3372, except verify the exception does not occur.
Also verify that there is no Camel NPE warning when deleting a monitored item.
[DDF-3372](https://codice.atlassian.net/browse/DDF-3372) …
=> [2.11.x] DDF-3372 Update WebDav to not get file when deleting

platform/admin/core/admin-core-appservice/src/main/java/org/codice/ddf/admin/application/service/impl/ApplicationImpl.java, platform/admin/core/admin-core-appservice/src/test/java/org/codice/ddf/admin/application/service/impl/ApplicationImplTest.java, platform/admin/core/admin-core-appservice/src/test/resources/test-features-with-main-feature3.xml
The code changes for this PR have already been reviewed and approved.  See [PR 2620](https://github.com/codice/ddf/pull/2620) for details.
This PR fixes a bug where apps are displayed as active despite not having their features installed.
@emanns95 @tbatie @Lambeaux @emmberk
@clockard
@coyotesqrl
Start up DDF, but do not perform any installation.
Use app:list to verify default apps are installed
Perform a standard install.
Verify that all of the appropriate apps are still installed. …
=> DDF-3430 Search whole features list for matching feature and repo name

platform/admin/core/admin-core-impl/src/main/java/org/codice/ddf/admin/core/impl/AdminConsoleService.java, platform/admin/core/admin-core-impl/src/test/java/org/codice/ddf/admin/core/impl/AdminConsoleServiceTest.java
The color values for the header and footer configurations in the Admin UI are escaped to limit only the color being affected.
@Lambeaux 
@coyotesqrl  
@brjeter 
Start Admin UI
In Admin Console click Platform
Click Configuration
Click Platform UI Configuration
Edit Text Color and Background Color fields with any form of extraneous CSS
Check if only the color is affected
Before this change if you change the text color to:
white; height: 210px; z-index: 999999; background-image: url(https://gifimage.net/wp-content/uploads/2017/06/troll-face-gif-8.gif); background-repeat: no-repeat; background-attachment: fixed; background-position-x: center
And changed the background color to: 
white
You would affect more than …
=> DDF-3382 Usage Header and Footer Configurations are Sanitized

catalog/ui/catalog-ui-search/src/main/webapp/js/CQLUtils.js
Restricts the regex used in sanitizeGeometryCql to be more restrictive so it doesn't modify parts of the query that shouldn't be.
@djblue 
@tbatie 
@mcalcote 
@bdeining
1. Set up DDF
2. Ingest data with spatial data
3. Construct a query using Intrigue that includes both a relative temporal criteria and a point-radius spatial criteria
4. Workspace does not become unresponsive …
=> [DDF-2.11.x] DDF-3448 Restrict sanitizeGeometryCql regex more

catalog/ui/catalog-ui-search/src/main/webapp/component/input/autocomplete/input-autocomplete.less, catalog/ui/catalog-ui-search/src/main/webapp/component/location-old/location-old.less
Updates the CSS used by the Geographic Keyword Search bar so that it renders properly in IE11 (forward port of #2648)
@mojogitoverhere @Variadicism @adimka @brianfelix 
@codice/ui 
@bdeining
[DDF-3445](https://codice.atlassian.net/browse/DDF-3445) …
=> DDF-3445 Update CSS for Geographic Keyword Search

catalog/ui/catalog-ui-search/src/main/webapp/component/input/autocomplete/input-autocomplete.less, catalog/ui/catalog-ui-search/src/main/webapp/component/location-old/location-old.less
Updates the CSS used by the Geographic Keyword Search bar so that it renders properly in IE11
@mojogitoverhere @Variadicism @adimka @brianfelix 
@codice/ui 
@bdeining
Verify that the Geographic Keyword Search box renders properly across browsers
[DDF-3445](https://codice.atlassian.net/browse/DDF-3445)
Before
After …
=> [2.11.x] DDF-3445 Update CSS for Geographic Keyword Search

catalog/transformer/catalog-transformer-xml/pom.xml, catalog/transformer/catalog-transformer-xml/src/main/java/ddf/catalog/transformer/xml/EscapingPrintWriter.java, catalog/transformer/catalog-transformer-xml/src/test/java/ddf/catalog/transform/xml/TestEscapingPrintWriter.java
- Previously the XML transformer would allow invalid characters to be
serialized into the XML (via the Escaping print writer). It is now
changed to use the Apache commons escaper which will produce valid XML.
@stustison @brendan-hofmann @jlcsmith @coyotesqrl @shaundmorris 
@codice/data
Anyone
Contact @rzwiefel for test data that previously broke this and confirm that it no longer produces invalid XML
https://codice.atlassian.net/browse/DDF-3453
- …
=> [2.11.x] DDF-3453 Fixed XML Transformer Issue

catalog/ui/catalog-ui-search/src/main/webapp/js/CQLUtils.js
Restricts the regex used in sanitizeGeometryCql to be more restrictive so it doesn't modify parts of the query that shouldn't be.
@djblue 
@tbatie 
@mcalcote 
@bdeining
1. Set up DDF
2. Ingest data with spatial data
3. Construct a query using Intrigue that includes both a relative temporal criteria and a point-radius spatial criteria
4. Workspace does not become unresponsive …
=> DDF-3448 Restrict sanitizeGeomeryCql regex more (#2657)

catalog/core/catalog-core-camelcomponent/src/main/java/ddf/camel/component/catalog/content/ContentProducer.java, catalog/core/catalog-core-camelcomponent/src/main/java/ddf/camel/component/catalog/content/ContentProducerDataAccessObject.java, catalog/core/catalog-core-camelcomponent/src/test/java/ddf/camel/component/catalog/content/ContentProducerDataAccessObjectTest.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/AbstractDurableFileConsumer.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/DurableWebDavFileConsumer.java, catalog/core/catalog-core-localstorageprovider/src/main/java/org/codice/ddf/catalog/content/impl/FileSystemStorageProvider.java, catalog/core/catalog-core-localstorageprovider/src/test/java/org/codice/ddf/catalog/content/impl/FileSystemStorageProviderTest.java, distribution/ddf-common/src/main/resources/etc/log4j2.config.xml, distribution/ddf-common/src/main/resources/etc/org.ops4j.pax.logging.cfg
- Update WebDav CDM to no longer attempt to fetch a file when a delete event is received
- Update FileSystemStorageProvider to catch IOException when failing to open inputStream to external reference
@dcruver @brendan-hofmann @clockard @emmberk @AzGoalie 
@codice/io 
@lessarderic
@pklinef
Follow instructions in description of https://codice.atlassian.net/browse/DDF-3372, except verify the exception does not occur.
Also verify that there is no Camel NPE warning when deleting a monitored item.
When monitoring a WebDav server In Place with the CDM, the remote file would attempt to be downloaded even though it had already been deleted.
[DDF-3372](https://codice.atlassian.net/browse/DDF-3372) …
=> DDF-3372 Update WebDav to not get file when deleting

Jenkinsfile
Several maven commands in the Jenkinsfile were not being run in batch-mode. This change updates them all for consistency. This also should reduce log output and size.
@mackncheesiest @LinkMJB @oconnormi 
@codice/build 
@clockard @shaundmorris
Adding this `-B` to the other maven commands initially reduced log size from 65MB to 30MB.
=> DDF-3261 Update maven commands to all run in batch-mode

catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/XstreamPathConverter.java, catalog/spatial/csw/spatial-csw-transformer/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/TestXstreamPathConverter.java
Adds support for wildcard matching a path to the XstreamPathConverter
@adimka 
@glenhein 
@bdeining
@rzwiefel
This adds support to wildcard match paths and append all children under the wildcard node as a value.
[DDF-3451](https://codice.atlassian.net/browse/DDF-3451) …
=> DDF-3451 Add wildcard everything matching support to XstreamPathConverter

catalog/ui/catalog-ui-search/src/main/webapp/component/visualization/maps/cesium/map.cesium.js
- Updates cesium component to destroy itself when closed
- Without destruction, cpu percentages never return to normal levels.  With destruction, the cpu returns to 0% over time.
@millerw8 
@bdeining 
@pklinef 
@kcwire 
Use firefox for this one.  Open the browser to `about:performance` and have another window side by side with the Intrigue UI.  Watch the cpu levels in the `about:performance` tab.  Go to the view with golden layout and open up Cesium if it isn't already open (the 3d map).  Once open, close it.  Verify that over time the cpu levels in `about:performance` return to 0% for that tab.
If you have an old instance running, you can verify the old behavior, where closing cesium didn't let the cpu return to 0%.  Instead, it would continue to burn cycles.  
This appears to mainly be …
=> DDF-3438 Updates cesium component to destroy itself when closed

catalog/ui/catalog-ui-search/src/main/webapp/component/dropdown/query-src/dropdown.query-src.hbs, catalog/ui/catalog-ui-search/src/main/webapp/component/dropdown/query-src/dropdown.query-src.view.js, catalog/ui/catalog-ui-search/src/main/webapp/js/model/Query.js
when local catalog is disabled, do not let the local catalog be used as a default
@bdeining 
@troymohl 
@lessarderic
@millerw8
1) build and install
2) In the Catalog UI Search admin config, check the box "Disable Local Catalog".
3) In the UI, create an advanced query and de-select the 'All Sources'.
4) Click Search. Should see an error message about no sources being selected.
5) Edit the query and select the local source.
6) Click Search. Should see an error message about no sources being selected.
7)  In the Catalog UI Search admin config, uncheck the box "Disable Local …
=> DDF-3455 when local catalog is disabled, do not let the local catalog be used as a default

catalog/ui/catalog-ui-search/src/main/webapp/component/query-interactions/query-interactions.hbs, catalog/ui/catalog-ui-search/src/main/webapp/component/query-interactions/query-interactions.less, catalog/ui/catalog-ui-search/src/main/webapp/component/query-interactions/query-interactions.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/query-schedule/query-schedule.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/workspace-details/workspace-details.hbs, catalog/ui/catalog-ui-search/src/main/webapp/component/workspace-interactions/workspace-interactions.less, catalog/ui/catalog-ui-search/src/main/webapp/component/workspace-interactions/workspace-interactions.view.js, catalog/ui/catalog-ui-search/src/main/webapp/js/model/Query.js, catalog/ui/catalog-ui-search/src/main/webapp/js/model/Workspace.collection.js, catalog/ui/catalog-ui-search/src/main/webapp/js/model/Workspace.js
- Makes the notes view for queries visible (under query interactions)
- Adds distinguishment between guest workspaces and all others (cloud)
- Uses distinguishment to hide / show certain actions, like notes and sharing
- Fixes issues with duplicating workspaces, where things like owners and sharing were carried over.  Also fixes the issue of queries having the same id, which meant the notes on the query could be shared across workspaces when duplicating.
@bdeining
@glenhein 
@adimka 
[DDF-3216](https://codice.atlassian.net/browse/DDF-3216)
=> DDF-3216 Makes notes view for queries visible

distribution/ddf-common/src/main/resources/common-bin.xml, distribution/docs/src/main/resources/content/_configuring/exporting-configurations.adoc, distribution/docs/src/main/resources/content/_configuring/reusing-configurations.adoc, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/ConfigurationMigrationManager.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/ExportMigrationManagerImpl.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/ImportMigrationManagerImpl.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/Messages.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/MigrationContextImpl.java, platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/admin/ConfigurationAdminMigratableTest.java, platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/migration/AbstractMigrationSupport.java, platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/migration/ConfigurationMigrationManagerTest.java, platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/migration/ExportMigrationManagerImplTest.java, platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/migration/ImportMigrationManagerImplTest.java, platform/platform-migratable/src/test/java/org/codice/ddf/platform/migratable/impl/PlatformMigratableTest.java, platform/security/security-migratable/src/test/java/org/codice/ddf/security/migratable/impl/SecurityMigratableTest.java
This PR changes the filename format for exported file to include the brand name and to use the upcoming extension from [DDF-3376](https://codice.atlassian.net/browse/DDF-3376). It also pre-creates an empty exported dir at unzip time.
@emanns95 
@oconnormi 
@tbatie 
@Lambeaux 
@rzwiefel 
@figliold
Unzip distro and verify the exported directory is created with no files in it. Perform a migration export and verify the file created is ddf-<version>.dar. Perform a migration import and verify it finds the same file.
[DDF-3447](https://codice.atlassian.net/browse/DDF-3447) …
=> [2.11.x] DDF-3447 Add product name to file exported from migration:export

distribution/ddf-common/src/main/resources/common-bin.xml, distribution/docs/src/main/resources/content/_configuring/exporting-configurations.adoc, distribution/docs/src/main/resources/content/_configuring/reusing-configurations.adoc, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/ConfigurationMigrationManager.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/ExportMigrationManagerImpl.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/ImportMigrationManagerImpl.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/Messages.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/MigrationContextImpl.java, platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/admin/ConfigurationAdminMigratableTest.java, platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/migration/AbstractMigrationSupport.java, platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/migration/ConfigurationMigrationManagerTest.java, platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/migration/ExportMigrationManagerImplTest.java, platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/migration/ImportMigrationManagerImplTest.java, platform/platform-migratable/src/test/java/org/codice/ddf/platform/migratable/impl/PlatformMigratableTest.java, platform/security/security-migratable/src/test/java/org/codice/ddf/security/migratable/impl/SecurityMigratableTest.java
This PR changes the filename format for exported file to include the brand name and to use the upcoming extension from [DDF-3376](https://codice.atlassian.net/browse/DDF-3376). It also pre-creates an empty exported dir at unzip time.
@emanns95 
@oconnormi 
@tbatie 
@Lambeaux 
@rzwiefel 
@figliold
Unzip distro and verify the exported directory is created with no files in it. Perform a migration export and verify the file created is ddf-<version>.dar. Perform a migration import and verify it finds the same file.
[DDF-3447](https://codice.atlassian.net/browse/DDF-3447) …
=> DDF-3447 Add product name to file exported from migration:export

platform/admin/core/admin-core-insecuredefaults/pom.xml, platform/admin/core/admin-core-insecuredefaults/src/main/java/org/codice/ddf/admin/insecure/defaults/service/DefaultUsersDeletionScheduler.java, platform/admin/core/admin-core-insecuredefaults/src/test/java/org/codice/ddf/admin/insecure/defaults/service/DefaultUsersDeletionSchedulerTest.java, platform/admin/core/admin-core-insecuredefaults/src/test/java/org/codice/ddf/admin/insecure/defaults/service/UsersPropertiesCollectorTest.java
Fix failing unit test on windows and changes the use of object streams in DefaultUsersDeletionScheduler.
@brjeter 
@clockard
@coyotesqrl
@rzwiefel 
Full build of module on windows + run tests 
and
Manual verification
* This feature isn't on by default in DDF so after starting DDF go to `Admin Console → Admin → Users.properties Deletion Scheduler → Enable user.properties automatic deletion` to turn it on
* Set the following log:
`log:set DEBUG org.codice.ddf.admin.insecure.defaults.service`
`log:set DEBUG org.apache.camel.impl`
`log:set DEBUG org.apache.karaf.jaas.modules.properties`
* Along with insecure defaults (which takes about 5 minutes to appear), you should be able to see a notice in the admin console that a `users.properties` file exists with a deletion date and time.
* Verify …
=> [2.11.x] DDF-3363 Windows Test Fix

distribution/ddf-common/src/main/resources-filtered/etc/system.properties, distribution/ddf-common/src/main/resources/etc/log4j2.config.xml, distribution/ddf-common/src/main/resources/etc/org.ops4j.pax.logging.cfg, distribution/docs/src/main/resources/content/_configuring/auditing.adoc
This PR fixed some discrepancies between `org.ops4j.pax.logging.cfg` and `log4j2.config.xml`.
@gordocanchola @peterhuffer 
@bdeining
@clockard
- Confirm that both log configuration files include the same suppressions.
- Confirm that logging still works when DDF is running.
- Follow the Documentation (`Enabling Fallback Audit Logging`) to switch to use the `log4j2.config.xml`, and confirm that logging still works when DDF is running.
Is is a required hardening step to use the `log4j2.config.xml` configuration file, so it should match `org.ops4j.pax.logging.cfg`.
[DDF-3427](https://codice.atlassian.net/browse/DDF-3427) …
=> DDF-3427 Aligned org.ops4j.pax.logging.cfg and log4j2.config.xml configurations

platform/security/idp/security-idp-client/src/main/java/org/codice/ddf/security/idp/client/AssertionConsumerService.java, platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/server/IdpEndpoint.java, platform/security/idp/security-idp-server/src/test/groovy/org/codice/ddf/security/idp/server/IdpEndpointSpecTest.groovy, platform/security/platform-security-core-api/src/main/java/ddf/security/samlp/SamlProtocol.java, platform/security/platform-security-core-api/src/test/java/ddf/security/samlp/SamlProtocolTest.java
-------
- /services/idp/login/metadata now has a SingleSignOnService with a SOAP
Binding and /services/idp/login Location
- /services/saml/sso/metadata now has a AssertionConsumerService with a PAOS
Binding and /services/saml/sso Location
Adds SOAP and PAOS bindings to the SAML metadata.
@vinamartin 
@ahoffer 
@rzwiefel
@stustison
Hit `services/idp/login/metadata` and `/services/saml/sso/metadata` endpoints and make sure that the new bindings are present.
[DDF-3443](https://codice.atlassian.net/browse/DDF-3443) …
=> [2.11.x] DDF-3443: SAML ECP SOAP and PAOS Bindings Added to SAML Metadata

catalog/ui/catalog-ui-search/src/main/webapp/component/add-attribute/add-attribute.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/attributes-rearrange/attributes-rearrange.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/hide-attribute/hide-attribute.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/property/property.collection.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/property/property.hbs, catalog/ui/catalog-ui-search/src/main/webapp/component/property/property.js, catalog/ui/catalog-ui-search/src/main/webapp/component/property/property.less, catalog/ui/catalog-ui-search/src/main/webapp/component/property/property.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/remove-attribute/remove-attribute.view.js
Follow on to: https://github.com/codice/ddf/pull/2542
- Conflicting definitions are no longer warned about in announcements, they are now warned only when the user is in edit mode.  It's similar to read only attributes, except it shows 'Conflicting Definition'.  The help prompts them to contact the admin.  We do have to disallow editing, since it will appear to succeed but not actually change the attribute correctly.
- Fixes a few places where we weren't intersecting metacard types.
@mcalcote @djblue
@rzwiefel
@shaundmorris
@clockard 
Install and ingest a product that has known issues with attribute definitions and verify no warning …
=> DDF-3410 Updates conflicting definition warning tactic

catalog/ui/catalog-ui-search/src/main/webapp/component/add-attribute/add-attribute.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/attributes-rearrange/attributes-rearrange.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/hide-attribute/hide-attribute.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/property/property.collection.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/property/property.hbs, catalog/ui/catalog-ui-search/src/main/webapp/component/property/property.js, catalog/ui/catalog-ui-search/src/main/webapp/component/property/property.less, catalog/ui/catalog-ui-search/src/main/webapp/component/property/property.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/remove-attribute/remove-attribute.view.js
Follow on to: https://github.com/codice/ddf/pull/2542
- Conflicting definitions are no longer warned about in announcements, they are now warned only when the user is in edit mode.  It's similar to read only attributes, except it shows 'Conflicting Definition'.  The help prompts them to contact the admin.  We do have to disallow editing, since it will appear to succeed but not actually change the attribute correctly.
- Fixes a few places where we weren't intersecting metacard types.
@mcalcote @djblue
@lessarderic
@shaundmorris
@clockard 
Install and ingest a product that has known issues with attribute definitions and verify no warning …
=> [2.11.x] DDF-3410 Updates conflicting definition warning tactic

platform/admin/core/admin-core-insecuredefaults/src/main/java/org/codice/ddf/admin/insecure/defaults/service/DefaultUsersDeletionScheduler.java, platform/admin/core/admin-core-insecuredefaults/src/test/java/org/codice/ddf/admin/insecure/defaults/service/DefaultUsersDeletionSchedulerTest.java
Changes the use of object streams in DefaultUsersDeletionScheduler.
Note: These changes are also added in https://github.com/codice/ddf/pull/2673 fot the 2.11.x branch
@brjeter 
@clockard
@rzwiefel
Full build on both mac and windows
and
Manual verification
* This feature isn't on by default in DDF so after starting DDF go to `Admin Console → Admin → Default Users Deletion Scheduler → Enable user.properties automatic deletion` to turn it on
* Set the following log:
`log:set DEBUG org.codice.ddf.admin.insecure.defaults.service`
`log:set DEBUG org.apache.camel.impl`
`log:set DEBUG org.apache.karaf.jaas.modules.properties`
* Along with insecure defaults (which takes about 5 minutes to appear), you should be able to see a notice in the admin console that a `users.properties` file exists with a …
=> DDF-3363 Changed the use of object streams in DefaultUsersDeletionScheduler

catalog/plugin/catalog-plugin-metacard-validation/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/plugin/catalog-plugin-metacard-validation/src/main/resources/OSGI-INF/metatype/metatype.xml, distribution/docs/src/main/resources/content/_tables/MetacardValidityFilterPlugin.adoc
Updates the blueprint and metatype so the Validity Filter Plugin will not filter on warnings by default.
@AzGoalie 
@bdeining
@figliold
Full build. Verify the filter warnings checkbox is off in the admin ui.
Certain exceptions may occur. For example, if there is a problem with the CI environment then a manually performed full build and …
=> [2.11.x] DDF-3464 Update FilterPlugin to not filter warnings

catalog/plugin/catalog-plugin-metacard-validation/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/plugin/catalog-plugin-metacard-validation/src/main/resources/OSGI-INF/metatype/metatype.xml, distribution/docs/src/main/resources/content/_tables/MetacardValidityFilterPlugin.adoc
Updates the blueprint and metatype so the Validity Filter Plugin will not filter on warnings by default.
@AzGoalie 
@bdeining
@figliold
Full build. Verify the filter warnings checkbox is off in the admin ui.
Certain exceptions may occur. For example, if there is a problem with the CI environment then a manually performed full build and …
=> DDF-3464 Update FilterPlugin to not filter warnings (#2685)

catalog/transformer/catalog-transformer-xml/pom.xml, catalog/transformer/catalog-transformer-xml/src/main/java/ddf/catalog/transformer/xml/EscapingPrintWriter.java, catalog/transformer/catalog-transformer-xml/src/test/java/ddf/catalog/transform/xml/TestEscapingPrintWriter.java
- Previously the XML transformer would allow invalid characters to be
serialized into the XML (via the Escaping print writer). It is now
changed to use the Apache commons escaper which will produce valid XML.
@stustison @brendan-hofmann @jlcsmith @coyotesqrl @shaundmorris 
@codice/data
Anyone
Contact @rzwiefel for test data that previously broke this and confirm that it no longer produces invalid XML
https://codice.atlassian.net/browse/DDF-3453
- …
=> DDF-3453 Fixed xml transformer issue

dependency-check-maven-config.xml
Suppress camel cve that does not apply to DDF
These issues found are with camel-hessian and camel-castor in apache-camel and DDF only uses apache-camel for testing.
Issues found by owasp
https://nvd.nist.gov/vuln/detail/CVE-2017-12633#vulnDescriptionTitle
https://nvd.nist.gov/vuln/detail/CVE-2017-12634#vulnDescriptionTitle
@brjeter @peterhuffer 
@bdeining
@jlcsmith
CI build
[DDF-3472](https://codice.atlassian.net/browse/DDF-3472)
=> DDF-3472 Suppress camel cve that does not apply to DDF

dependency-check-maven-config.xml
Port of https://github.com/codice/ddf/pull/2728
Suppress camel cve that does not apply to DDF
These issues found are with camel-hessian and camel-castor in apache-camel and DDF only uses apache-camel for testing.
Issues found by owasp
https://nvd.nist.gov/vuln/detail/CVE-2017-12633#vulnDescriptionTitle
https://nvd.nist.gov/vuln/detail/CVE-2017-12634#vulnDescriptionTitle
@brjeter @peterhuffer
@bdeining
@jlcsmith
CI build
DDF-3472
=> [2.11.x] DDF-3472 Suppress camel cve that does not apply to DDF

catalog/core/catalog-core-api/pom.xml, catalog/core/catalog-core-metricsplugin/pom.xml, catalog/core/catalog-core-resourcestatusplugin/pom.xml, catalog/opensearch/catalog-opensearch-endpoint/pom.xml, catalog/rest/catalog-rest-endpoint/pom.xml, catalog/spatial/kml/spatial-kml-networklinkendpoint/pom.xml, catalog/spatial/registry/registry-policy-plugin/pom.xml, catalog/spatial/registry/registry-publication-action-provider/pom.xml, catalog/transformer/catalog-transformer-service-atom/pom.xml, libs/common-system/pom.xml, libs/platform-configuration-impl/pom.xml, platform/admin/core/admin-core-impl/pom.xml, platform/admin/core/admin-core-insecuredefaults/pom.xml, platform/admin/core/admin-core-migration-commands/pom.xml, platform/metrics/platform-metrics-reporting/pom.xml, platform/platform-app/pom.xml, platform/platform-app/src/main/resources/features.xml, platform/platform-configuration/pom.xml, platform/security/cas/security-cas-client/pom.xml, platform/security/cas/security-cas-cxfservletfilter/pom.xml, platform/security/filter/security-filter-login/pom.xml, platform/security/idp/security-idp-client/pom.xml, platform/security/idp/security-idp-server/pom.xml, platform/security/platform-security-core-api/pom.xml, platform/security/policy/security-policy-context/pom.xml, platform/security/servlet/security-servlet-logout/pom.xml, platform/security/sts/security-sts-server/pom.xml
Makes the common-system module it's own bundle and removes common-system from bundle embed sections. This was pulled out of https://github.com/codice/ddf/pull/2713 to be it's own pr
@emmberk @AzGoalie @peterhuffer 
@bdeining
@coyotesqrl
@rzwiefel
CI build and verify installs successfully
[DDF-3460](https://codice.atlassian.net/browse/DDF-3460)
=> DDF-3460 Make commons-system its own bundle

platform/migration/platform-migration/pom.xml, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/CipherUtils.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/ConfigurationMigrationManager.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/ExportMigrationContextImpl.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/ExportMigrationManagerImpl.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/ImportMigrationContextImpl.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/ImportMigrationManagerImpl.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/Messages.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/MigrationZipConstants.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/MigrationZipFile.java, platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/admin/ConfigurationAdminMigratableTest.java, platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/migration/AbstractMigrationSupport.java, platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/migration/CipherUtilsTest.java, platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/migration/ConfigurationMigrationManagerTest.java, platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/migration/ExportMigrationContextImplTest.java, platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/migration/ExportMigrationManagerImplTest.java, platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/migration/ImportMigrationContextImplTest.java, platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/migration/ImportMigrationManagerImplTest.java, platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/migration/MigrationZipFileTest.java
Encrypts/Decrypts the export created by the migration framework
@paouelle @peterhuffer @emmberk @AzGoalie  
@clockard @coyotesqrl 
1. Install DDF
2. run `migration:export`
3. confirm that `<ddf_home>/exported/<ddf-export-file-name>.dar` and `<ddf_home>/exported/<ddf-export-file-name>.dar.key` and `<ddf_home>/exported/<ddf-export-file-name>.dar.sha256` exist
4. manually unzip the file and verify that files have encrypted contents
5. copy the zip and the key to a new system
6. run `migration:import` and confirm success
Each entry in the migration zip is individually encrypted. The zip can be unzipped with any zip utility, however the contents of each file will be unreadable unless decrypted using the correct key
[DDF-3376](https://codice.atlassian.net/browse/DDF-3376) …
=> DDF-3376 Add encryption support to the migration framework

catalog/plugin/catalog-plugin-videothumbnail/src/test/java/org/codice/ddf/catalog/content/plugin/video/VideoThumbnailPluginTest.java
This PR ignores failing unit tests on Windows until the failures can be investigated in [DDF-3503](https://codice.atlassian.net/browse/DDF-3503).
@oconnormi @mcalcote @LinkMJB @jrnorth 
@codice/test 
@codice/build 
@coyotesqrl
@lessarderic
CI build on Windows Server 2016.
[DDF-3503](https://codice.atlassian.net/browse/DDF-3503) …
=> DDF-3503 Ignored failing unit tests in catalog-plugin-videothumbnail

catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/ImportCommand.java
- Now when A single metacard fails to process, the import command will continue with the rest of the metacards instead of failing the rest of the transaction
Anyone
Anyone
Ensure that when a single invalid metacard among a batch is imported, the rest of the valid metacards are imported.
https://codice.atlassian.net/browse/DDF-3452
=> DDF-3452 Fixes import command to continue processing

catalog/plugin/catalog-plugin-metacardbackup-filestorage/src/main/java/org/codice/ddf/catalog/plugin/metacard/backup/storage/filestorage/MetacardFileStorageRoute.java, catalog/plugin/catalog-plugin-metacardbackup-filestorage/src/test/java/org/codice/ddf/catalog/plugin/metacard/backup/storage/filestorage/MetacardBackupFileStorageTest.java
Implemented delete capability in the MetacardFileStorageRoute
@troymohl @mojogitoverhere 
@jlcsmith
@millerw8
Build / Install / Configure MetacardFileStorageRoute / Execute CRUD on metacards and verify the backup behaves as expected.  Also verify the `KeepDeletedMetacards` is honored.
[DDF-3488](https://codice.atlassian.net/browse/DDF-3488)
Certain …
=> DDF-3488 Implemented delete capability in the MetacardFileStorageRoute

catalog/ui/catalog-ui-search/src/main/webapp/component/dropdown/dropdown.companion.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/dropdown/dropdown.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/filter-builder/filter-builder.less, catalog/ui/catalog-ui-search/src/main/webapp/component/filter/filter.js, catalog/ui/catalog-ui-search/src/main/webapp/component/filter/filter.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/input/enum/input-enum.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/input/with-param/input-with-param.less, catalog/ui/catalog-ui-search/src/main/webapp/component/input/with-param/input-with-param.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/location-old/location-old.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/property/property.js, catalog/ui/catalog-ui-search/src/main/webapp/component/select/select.collection.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/select/select.less, catalog/ui/catalog-ui-search/src/main/webapp/component/select/select.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/value/value.view.js
- Adds custom value support to dropdowns.  You can specify whether case should match or not.
- Adds enums to the advanced search view that allow custom values.
@jlcsmith
@rzwiefel 
@djblue 
Add an enumeration for an attribute and verify that you see a dropdown for it on the advanced search view.  Verify that it still allows entering custom values, and if using = or matchcase that it takes casing into account.
https://codice.atlassian.net/browse/DDF-3404
=> DDF-3404 Adds custom value support to dropdowns, add enums to advanced search view

platform/security/common/pom.xml, platform/security/common/src/main/java/ddf/security/assertion/impl/SecurityAssertionImpl.java, platform/security/common/src/main/java/ddf/security/samlp/impl/SamlValidator.java, platform/security/common/src/test/java/ddf/security/assertion/impl/SecurityAssertionImplTest.java, platform/security/common/src/test/resources/saml.xml, platform/security/core/security-core-impl/pom.xml, platform/security/core/security-core-impl/src/main/java/ddf/security/samlp/impl/LogoutMessageImpl.java, platform/security/core/security-core-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/security/core/security-core-impl/src/test/groovy/ddf/security/samlp/impl/LogoutMessageSpecTest.groovy, platform/security/handler/security-handler-api/pom.xml, platform/security/handler/security-handler-api/src/main/java/org/codice/ddf/security/handler/api/HandlerResult.java, platform/security/idp/security-idp-client/pom.xml, platform/security/idp/security-idp-client/src/main/java/org/codice/ddf/security/idp/client/LogoutRequestService.java, platform/security/idp/security-idp-client/src/test/java/org/codice/ddf/security/idp/client/LogoutRequestServiceTest.java, platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/server/IdpEndpoint.java, platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/server/LogoutState.java, platform/security/idp/security-idp-server/src/test/groovy/org/codice/ddf/security/idp/server/IdpEndpointSpecTest.groovy, platform/security/idp/security-idp-server/src/test/java/org/codice/ddf/security/idp/server/IdpEndpointTest.java, platform/security/idp/security-idp-server/src/test/resources/saml.xml, platform/security/platform-security-core-api/src/main/java/ddf/security/samlp/LogoutMessage.java, platform/security/platform-security-core-api/src/main/java/ddf/security/samlp/SamlProtocol.java, platform/security/platform-security-core-api/src/test/java/ddf/security/samlp/SamlProtocolTest.java, platform/security/security-services-app/pom.xml, platform/security/security-services-app/src/main/resources/features.xml, platform/security/sts/security-sts-server/src/main/java/ddf/security/sts/AuthNStatementProvider.java
Implements SessionIndex for SAML. Specifically:
- SecurityAssertionImpl parses a SecurityToken, it copies the SessionIndex from the Security token into its own copy of the AuthnStatement
- The SessionIndex is extracted from an incoming SAML logout request by the LogoutMessage
- The SamlProtocol class copies the SessionIndex from the LogoutRequest it creates
- The SamlValidator checks for the presence of a SessionIndex when it validates a SAML request.
- Added SessionIndex attribute to XML file used in testing
- Changed how SessionIndex is generated in AuthnStatementProvider. SessionIndex can be any string, but standard recommends small-ish integer. It now generate only positive session indexes and reduces the upper size of a session index
- Added unit test to …
=> [2.11.x] DDF-3422 Add SessionIndex to SAML LogoutRequest

Jenkinsfile
Suppresses lines of the form 
```
18:43:23 [INFO] Downloading: http://NEXUS/PATH/TO/ARTIFACT
18:43:23 [INFO] Downloaded: http://NEXUS/PATH/TO/ARTIFACT (27 KB at 985.4 KB/sec)
```
from the Jenkins Pipeline build logs
@vinamartin @blen-desta @oconnormi @mcalcote @LinkMJB 
@bdeining
@clockard
It has been verified both in legacy DDF jobs and on a downstream project that only the desired logs are suppressed.
[DDF-3506](https://codice.atlassian.net/browse/DDF-3506) …
=> DDF-3506 Suppress 'Downloading/Downloaded' status lines in logs

distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/ServiceManagerImpl.java
Suppresses itest logs that aren't gated by a `LOGGER` in `ServiceManagerImpl`
@tbatie @rzwiefel @adimka 
@bdeining
@millerw8
Full build
This print statement causes roughly 14000 lines to be printed into build logs regardless of root logger level during itest setup.
[DDF-3517](https://codice.atlassian.net/browse/DDF-3517) …
=> DDF-3517 Suppress extraneous logs in ServiceManagerImpl

catalog/pom.xml, dependency-check-maven-config.xml, platform/security/pom.xml, pom.xml
- Upgrades the beanutils version which was using the vulnerable artifact as a transitive dependency.
- Suppressing the CVE still because OWASP is looking at the DDF version instead of the actual artifact's version.
@blen-desta @emmberk 
@coyotesqrl 
@shaundmorris 
Full build
[DDF-3523](https://codice.atlassian.net/browse/DDF-3523) …
=> [2.11.x]DDF-3523 Upgrading beanutils version and suppressing CVE

catalog/pom.xml, dependency-check-maven-config.xml, platform/security/pom.xml, pom.xml
Forward-port for: https://github.com/codice/ddf/pull/2797
- Upgrades the beanutils version which was using the vulnerable artifact as a transitive dependency.
- Suppressing the CVE still because OWASP is looking at the DDF version instead of the actual artifact's version.
@blen-desta @emmberk 
@coyotesqrl 
@shaundmorris 
Full build
[DDF-3523](https://codice.atlassian.net/browse/DDF-3523) …
=> DDF-3523 Upgrading beanutils version and suppressing CVE

catalog/transformer/catalog-transformer-service-atom/src/main/java/ddf/catalog/transformer/response/query/atom/AtomTransformer.java
Moved WKTReader in AtomTransformer to be a member variable for thread safety
@troymohl 
@dcruver 
@bdeining
@coyotesqrl
Set up several OpenSearch self-federation, and trick to to do an infinite loop via doing an enterprise search (each loop will call itself and federate).  Add data with a Geospatial component and kick off the infinite loop.  Confirm the atom transformer is called dozens of times a second, with no parse exceptions.
[DDF-3511](https://codice.atlassian.net/browse/DDF-3511) …
=> DDF-3511 Moved WKTReader in AtomTransformer to be a member variable

catalog/ui/catalog-ui-search/src/main/webapp/component/component.less, catalog/ui/catalog-ui-search/src/main/webapp/component/golden-layout/golden-layout.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/visualization/low-bandwidth-map/low-bandwidth-map.hbs, catalog/ui/catalog-ui-search/src/main/webapp/component/visualization/low-bandwidth-map/low-bandwidth-map.less, catalog/ui/catalog-ui-search/src/main/webapp/component/visualization/low-bandwidth-map/low-bandwidth-map.view.js, catalog/ui/catalog-ui-search/src/main/webapp/js/router.js, distribution/docs/src/main/resources/content/_using/using-catalog-search-ui.adoc
Adds a `?lowBandwidth` parameter for use in Intrigue to allow for better UX in bandwidth-restricted environments
@mojogitoverhere @Variadicism @rzwiefel @djblue 
@codice/ui 
@bdeining
Verify functionality of `?lowBandwidth` param across various browsers
At the moment, passing in the `?lowBandwidth` URL parameter to any URL targeting Intrigue simply causes the UI to prompt the user for confirmation before loading either the openlayers or cesium maps. Future changes can be made with respect to other "low bandwidth" improvements. 
[DDF-3504](https://codice.atlassian.net/browse/DDF-3504)
3D Map
2D Map …
=> DDF-3504 Implemented lowBandwidth param for Intrigue

catalog/transformer/catalog-transformer-common/pom.xml, catalog/transformer/catalog-transformer-common/src/main/java/ddf/catalog/transformer/common/tika/MetacardCreator.java, catalog/transformer/catalog-transformer-common/src/test/java/ddf/catalog/transformer/common/tika/MetacardCreatorTest.java
The mapping for Contributor and Creator in Tika is redundant if both fields have the same value (e.g. the last person to edit the file **is** the creator of the file).
This change checks if they are different before setting contributor.
@emanns95 @brianfelix @ahoffer @garrettfreibott 
@rzwiefel
Create a document where creator and last author are the same.
Ingest the document and verify contributor is not set. 
[DDF-3521](https://codice.atlassian.net/browse/DDF-3521) …
=> [2.11.x] DDF-3521 Removes redundant mapping for Creator and Contributor

catalog/ui/catalog-ui-search/src/main/webapp/js/widgets/openlayers.line.js, catalog/ui/catalog-ui-search/src/main/webapp/js/widgets/openlayers.polygon.js
Removed logic to checking 'y' value to be between -90 and 90 prior to transforming from the native projection.
This logic fails on my degree based projections such as EPSG:3857.  This check should not be done, instead relying on the library to check and normalize values.
https://github.com/orgs/codice/teams/UI
@bdeining
First, to witness the bug:
Set the UI projection to EPSG:3857
Open up the UI and 2D Map
Draw a lineString or a Polygon in a query on the 2D map.
Observe that all latitude values end up being very small.  The shapes end up on the equator, and the values in the text boxes are very small
Repeating the steps …
=> DDF-3531 Moved logic to checking latitudes to after  projection transformation

catalog/admin/module/catalog-admin-module-sources/src/main/webapp/js/view/ModalSource.view.js, catalog/admin/module/catalog-admin-module-sources/src/main/webapp/js/view/Source.view.js, catalog/admin/module/catalog-admin-module-sources/src/main/webapp/js/view/Utils.js, platform/admin/ui/src/main/webapp/templates/configuration/configurationRow.handlebars, platform/admin/ui/src/main/webapp/templates/configuration/serviceRow.handlebars, platform/security/servlet/security-servlet-logout/src/main/webapp/js/main.js, platform/security/servlet/security-servlet-logout/src/main/webapp/less/style.less
DDF-3510 Modals no longer be dismissible by clicking outside or pressing the ESC key
Removes the ability for modals to be dismissed by clicking outside or pressing the ESC key. Modals affected are configuration, sources and logout.
@vinamartin @mcalcote @djblue @peterhuffer 
@figliold
@shaundmorris 
- Add/Edit Configuration modals
- Add/Edit/Delete Sources modals
- Logout IFrame
should not be dismissible by clicking outside or my pressing the ESC key and function as expected.
Accidental modal dismissals caused loss of work and incomplete logouts.
[DDF-3510](https://codice.atlassian.net/browse/DDF-3510) …
=> [2.11.x]DDF-3510 Modals to no longer be dismissible by clicking outside or pressing the ESC key

pom.xml
See: https://github.com/vackosar/gitflow-incremental-builder/issues/15#issuecomment-318679437
Updates default GIB behavior to perform a full build if it loses git context
@oconnormi @lessarderic @shaundmorris @vinamartin 
@lessarderic
@shaundmorris
Perform PR build on CI environment
Perform manual GIB enabled build (use options: `-Dgib.enabled=true -Dgib.referenceBranch=refs/remotes/origin/2.11.x`)
See: https://trello.com/c/7iBsxkdi
- https://codice.atlassian.net/projects/DDF/issues/DDF-3525 …
=> [2.11.x] DDF-3525 Set gib.failOnError=false

pom.xml
See: https://github.com/vackosar/gitflow-incremental-builder/issues/15#issuecomment-318679437
Updates default GIB behavior to perform a full build if it loses git context
@oconnormi @lessarderic @shaundmorris @vinamartin 
@lessarderic
@shaundmorris
Perform PR build on CI environment
Perform manual GIB enabled build (use options: `-Dgib.enabled=true -Dgib.referenceBranch=refs/remotes/origin/master`)
See: https://trello.com/c/7iBsxkdi
- https://codice.atlassian.net/projects/DDF/issues/DDF-3525 …
=> DDF-3525 Set gib.failOnError=false

catalog/admin/module/catalog-admin-module-maplayers/src/main/webapp/map-layers/reducer.js
This PR fixes an issue where the map layers could not immediately be saved after deleting a layer.
@djblue @peterhuffer 
@codice/ui 
@clockard
@millerw8
1. In the `Admin Console` -> `Catalog` -> `Map Layers` tab, add some map layers (the details don't need to be filled in to test this PR).
2. Run through some edge cases of deleting the top, bottom, and middle map layers. Also, confirm that moving layers up and down still works before and after deleting layers.
3. Confirm that
- The order of the map layers is updated correctly in the json in the `Advanced Configuration`
- There isn't an error message, like `Order should be between 0 and 2`, that blocks saving.
[DDF-3449](https://codice.atlassian.net/browse/DDF-3449) …
=> [2.11.x] DDF-3449 Fixed deleting non-bottom Map Layers

catalog/admin/module/catalog-admin-module-sources/src/main/webapp/js/view/ModalSource.view.js, catalog/admin/module/catalog-admin-module-sources/src/main/webapp/js/view/Source.view.js, catalog/admin/module/catalog-admin-module-sources/src/main/webapp/js/view/Utils.js, platform/admin/ui/src/main/webapp/templates/configuration/configurationRow.handlebars, platform/admin/ui/src/main/webapp/templates/configuration/serviceRow.handlebars, platform/security/servlet/security-servlet-logout/src/main/webapp/js/main.js, platform/security/servlet/security-servlet-logout/src/main/webapp/less/style.less
DDF-3510 Modals no longer be dismissible by clicking outside or pressing the ESC key
Removes the ability for modals to be dismissed by clicking outside or pressing the ESC key. Modals affected are configuration, sources and logout.
@djblue @peterhuffer 
@figliold
@clockard  
- Add/Edit Configuration modals
- Add/Edit/Delete Sources modals
- Logout IFrame
should not be dismissible by clicking outside or my pressing the ESC key and function as expected.
Accidental modal dismissals caused loss of work and incomplete logouts.
[DDF-3510](https://codice.atlassian.net/browse/DDF-3510)
- ✏️ (Pencil) …
=> DDF-3510 Explicit Modal Dismissal

catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/cache/solr/impl/SortedQueryMonitorTest.java
Increased the atMost wait time and added pollInterval in `SortedQueryMonitorTest`'s `interruptThirdFuture` test
@mackncheesiest @LinkMJB 
@coyotesqrl
@rzwiefel
Full build. Make sure test doesn't fail when run repeatedly (use run until failure on IntelliJ).
[DDF-3539](https://codice.atlassian.net/browse/DDF-3539) …
=> DDF-3539 Added to the wait in SortedQueryMonitorTest's interruptThirdFuture

catalog/transformer/catalog-transformer-csv/src/main/java/ddf/catalog/transformer/csv/MetacardIterator.java, catalog/transformer/catalog-transformer-csv/src/test/java/ddf/catalog/transformer/csv/MetacardIteratorTest.java
Fixes a bug in the MetacardIterator where the `next()` method would only output the first value of multivalued attributes. This caused some values to be missing when search results were exported as CSV from the Table viewer in Intrigue.
@adimka @brianfelix @glenhein @dcruver @mackncheesiest @Variadicism @troymohl
@bdeining
@millerw8 
Manually ingest some data that has some multivalued attributes and export it as CSV in the Table viewer in Intrigue. Verify that all values are shown in the CSV.
[DDF-3534](https://codice.atlassian.net/browse/DDF-3534) …
=> DDF-3534 MetacardIterator now correctly handles multivalued attributes

catalog/ui/catalog-ui-search/src/main/webapp/component/singletons/session-timeout.js, distribution/docs/src/main/resources/content/_configuring/environment-hardening.adoc, platform/security/servlet/security-servlet-session-expiry/src/main/java/org/codice/ddf/security/servlet/expiry/SessionManagementService.java, platform/security/servlet/security-servlet-session-expiry/src/test/java/org/codice/ddf/security/servlet/expiry/SessionManagementServiceTest.java
Fixes the session timeout redirect in the UI.
Changes the UI to respect the timeout specified.
Changes the redirect type (HTTP 303 instead of 307). 
Fixes the UI such that non-saved workspaces don't prevent the redirect. 
@adimka 
@brjeter 
@bdeining
1. Install DDF
2. Update the catalog timeout to 120000 (or something reasonable for testing) in 
3. Navigate to /search/catalog
4. Create a new workspace or edit existing workspace. Wait for the time configured in step 2.
5. Verify that the redirect to logout occurs after that time.
[DDF-3529](https://codice.atlassian.net/browse/DDF-3529) …
=> DDF-3529 Fix UI session timeout redirect

catalog/ui/catalog-ui-search/src/main/webapp/component/query-title/query-title.hbs, catalog/ui/catalog-ui-search/src/main/webapp/component/query-title/query-title.view.js
Normalizes the display of the search title to show `Search Name`
@Variadicism  
@bdeining
Edit searches in the UI. Verify all places, the default is displayed as `Search Name` and `Search Title` doesn't appear.
[DDF-3541](https://codice.atlassian.net/browse/DDF-3541)
- ❓ (Question …
=> DDF-3541 Normalize search title to display Search Name

catalog/ui/catalog-ui-search/src/main/webapp/js/jquery.whenAll.js
- Previously if only 1 argument was supplied the resolve ended up being called differently (it used the deferred / promise passed in directly).  This could cause issues in areas of the code that rely on the resolution of the whenAll.  Developers would need to check whether or not they passed in an array of size 1 in order to know how to handle the resolution of the whenAll.  Now developers can depend on it returning an array of responses.
@adimka 
@troymohl 
@millerw8 
Turn off the cache in the Admin UI and make sure you don't have any extra sources (just local).  
Update the notifications enum in the Admin UI to allow a shorter notification period (maybe 10 seconds?).
Go to the UI (or refresh if you already have it open).
Create a query and turn on notifications (bell …
=> DDF-3468 Updates $.whenAll to have a consistent resolve

distribution/docs/src/main/resources/content/_configuring/reusing-configurations.adoc, platform/admin/core/admin-core-migration-commands/src/main/java/org/codice/ddf/migration/commands/DecryptCommand.java, platform/admin/core/admin-core-migration-commands/src/test/java/org/codice/ddf/migration/commands/DecryptCommandTest.java, platform/migration/platform-migratable-api/pom.xml, platform/migration/platform-migratable-api/src/main/java/org/codice/ddf/migration/MigrationOperation.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/ConfigurationMigrationManager.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/ConfigurationMigrationService.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/DecryptMigrationManagerImpl.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/ExportMigrationManagerImpl.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/ImportMigrationManagerImpl.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/Messages.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/MigrationReportImpl.java, platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/migration/AbstractMigrationSupport.java, platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/migration/ConfigurationMigrationManagerTest.java, platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/migration/DecryptMigrationManagerImplTest.java
Provides a decrypt command for the exported migration file.
@tbatie 
@emanns95 
@oconnormi 
@Lambeaux 
@figliold
@lessarderic
@millerw8
@stustison
Execute a migrate:export from the command line and then execute migrate:decrypt, A .zip file should be generated and contain all exported decrypted files.
Now that we are encrypting the exported file, it is now much harder to troubleshoot or debug enhancements to the migration framework. The new migrate:decrypt command  can be used to peek at the content of an exported file.
[DDF-3376](https://codice.atlassian.net/browse/DDF-3376) …
=> DDF-3376 Added migration decrypt command

catalog/ui/catalog-ui-search/src/main/webapp/component/workspaces-templates/workspaces-templates.less
Fixes a CSS issue from #2820 with certain styles not being consistently applied depending on if a header/footer is present. 
@mojogitoverhere @glenhein @Variadicism @brianfelix  
@codice/ui 
@bdeining
Verify that the template gallery drawer functions properly regardless of whether or not a header/footer are configured in Admin UI -> Platform -> Platform UI Configuration.
#2820 reworked the `More Templates` button to now hide all templates by default and expand to expose templates when pressed. Since templates are hardcoded at the moment, the idea was to expand to show just the 5 templates that we have and still leave …
=> DDF-3533 Fixed show/hide template CSS when header/footer not present

catalog/admin/catalog-admin-downloadmanager/src/main/java/org/codice/ddf/catalog/admin/downloadmanager/DownloadManagerServiceMBean.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/event/retrievestatus/DownloadStatusInfo.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/event/retrievestatus/DownloadStatusInfoImpl.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/resource/download/DownloadInfo.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/resource/download/DownloadStatus.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/resource/download/ReliableResourceCallable.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/resource/download/ReliableResourceDownloader.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/resource/download/ReliableResourceStatus.java, catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/event/retrievestatus/DownloadsStatusEventListenerTest.java, catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/resource/download/ReliableResourceDownloaderTest.java
This PR refactors download status fields in `ddf.catalog.resource.download.DownloadInfo` to a new class to prevent any misunderstanding/clash with corresponding fields.
This PR also fixes some javadoc links.
@AzGoalie @peterhuffer @harrison-tarr 
@clockard 
@coyotesqrl 
Full build.
[DDF-3544](https://codice.atlassian.net/browse/DDF-3544) …
=> DDF-3544 Refactored download status constants in catalog-core-standardframework to new class to fix code smell

catalog/core/catalog-core-api/src/main/java/ddf/catalog/content/data/ContentItem.java, catalog/core/catalog-core-contentresourcereader/src/main/java/org/codice/ddf/catalog/content/resource/reader/ContentResourceReader.java, catalog/core/catalog-core-contentresourcereader/src/main/java/org/codice/ddf/catalog/content/resource/reader/DerivedContentActionProvider.java, catalog/core/catalog-core-contentresourcereader/src/test/java/org/codice/ddf/catalog/content/resource/reader/DerivedContentActionProviderTest.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/impl/CacheKey.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/ResourceOperations.java, catalog/core/catalog-core-urlresourcereader/src/main/java/ddf/catalog/resource/impl/URLResourceReader.java, catalog/core/catalog-core-urlresourcereader/src/test/java/ddf/catalog/resource/impl/URLResourceReaderTest.java
This PR renames field `ddf.catalog.content.data.ContentItem#QUALIFIER` to prevent any misunderstanding/clash with field `ddf.catalog.content.data.impl.ContentItemImpl#qualifer`.
@AzGoalie @peterhuffer 
@clockard 
@coyotesqrl 
Full build.
[DDF-3544](https://codice.atlassian.net/browse/DDF-3544) …
=> DDF-3544 Renamed QUALIFIER constant in ddf.catalog.content.data.ContentItem to fix code smell

catalog/core/catalog-core-commons/src/main/java/ddf/catalog/filter/delegate/FilterToTextDelegate.java, catalog/core/catalog-core-commons/src/main/java/ddf/catalog/impl/filter/DivisibleByFunction.java, catalog/core/catalog-core-commons/src/main/java/ddf/catalog/impl/filter/FuzzyFunction.java, catalog/core/catalog-core-commons/src/main/java/ddf/catalog/impl/filter/GeoToolsFunctionFactory.java, catalog/core/catalog-core-commons/src/main/java/ddf/catalog/impl/filter/ProximityFunction.java, catalog/core/catalog-core-commons/src/main/java/ddf/catalog/impl/filter/TemporalFilter.java, catalog/core/catalog-core-commons/src/test/java/ddf/catalog/impl/filter/FuzzyFunctionTest.java, catalog/core/catalog-core-commons/src/test/java/ddf/catalog/impl/filter/GeoToolsFunctionFactoryTest.java, catalog/core/catalog-core-commons/src/test/java/ddf/catalog/impl/filter/ProximityFunctionTest.java, catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/SolrFilterDelegate.java, catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/TestSolrFilterBuilder.java, catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/ExtendedGeotoolsFunctionFactory.java, catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/PropertyIsFuzzyFunction.java
This PR renames fields in 
- `ddf.catalog.impl.filter.DivisibleByFunction`
- `ddf.catalog.impl.filter.FuzzyFunction`
- `ddf.catalog.impl.filter.ProximityFunction`
to prevent any misunderstanding/clash with field `org.geotools.filter.FunctionExpressionImpl#name`.
This PR also renames fields in `org.codice.ddf.spatial.ogc.csw.catalog.common.PropertyIsFuzzyFunction` to prevent any misunderstanding/clash with field `org.geotools.filter.FunctionImpl#name`.
@AzGoalie @peterhuffer 
@clockard 
@coyotesqrl 
Full build.
[DDF-3544](https://codice.atlassian.net/browse/DDF-3544)
- ✏️ …
=> DDF-3544 Renamed constants in geotools function impls to fix code smell

catalog/ui/catalog-ui-search/src/main/webapp/component/component.less, catalog/ui/catalog-ui-search/src/main/webapp/component/dropdown/hover-preview/dropdown.hover-preview.hbs, catalog/ui/catalog-ui-search/src/main/webapp/component/dropdown/hover-preview/dropdown.hover-preview.less, catalog/ui/catalog-ui-search/src/main/webapp/component/dropdown/hover-preview/dropdown.hover-preview.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/hover-preview/hover-preview.hbs, catalog/ui/catalog-ui-search/src/main/webapp/component/hover-preview/hover-preview.less, catalog/ui/catalog-ui-search/src/main/webapp/component/hover-preview/hover-preview.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/result-item/result-item.hbs, catalog/ui/catalog-ui-search/src/main/webapp/component/result-item/result-item.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/theme-settings/theme-settings.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/visualization/table/row.hbs, catalog/ui/catalog-ui-search/src/main/webapp/component/visualization/table/row.less, catalog/ui/catalog-ui-search/src/main/webapp/component/visualization/table/row.view.js, catalog/ui/catalog-ui-search/src/main/webapp/js/model/User.js
- Adds user preference to preview images by hovering.
@bdeining
@jlcsmith
Turn on full image preview on hover.  Then go to the result previews and hover over an image and hover over the zoom icon.  This will pop open a full view of the image.  Click to see the image in a new window.
Turn off full image preview on hover.  Then go to the result previews and hover over an image and hover over the zoom icon.  Verify nothing pops up.  Verify you can still click the icon to see the image in a new window.
https://codice.atlassian.net/browse/DDF-3513
=> DDF-3513 Adds user pref for previewing images by hover

catalog/ui/catalog-ui-search/src/main/webapp/component/visualization/low-bandwidth-map/low-bandwidth-map.less
Fixes a CSS issue introduced in #2774 that was causing the background to be transparent on the map toolbar 
@mojogitoverhere @adimka @brianfelix @GabrielFabian 
@bdeining
Install and verify that the toolbar is no longer transparent
[DDF-3504](https://codice.atlassian.net/browse/DDF-3504)
Broken:
Fixed: …
=> DDF-3504 Fixed CSS for map toolbar in lowBandwidthMap view

catalog/ui/catalog-ui-search/src/main/webapp/component/input/date/input-date.view.js
- Previously the datepicker would not appear if it was forced to open upwards.
- https://github.com/Eonasdan/bootstrap-datetimepicker/issues/790 details some of the methods people have found for correcting the position when attaching to the body.  The positioning method now takes this into account.
@bdeining 
@millerw8 
@jlcsmith
@adimka 
Open a datepicker that only has room to open upwards and verify it's visible.
https://github.com/Eonasdan/bootstrap-datetimepicker/issues/790 details others who have ran into this issue.
https://codice.atlassian.net/browse/DDF-3418#### Screenshots (if appropriate)
=> DDF-3418 Fixes datepicker issue with opening upwards

platform/security/common/src/main/java/org/codice/ddf/security/common/jaxrs/RestSecurity.java, platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/binding/post/PostRequestDecoder.java, platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/server/IdpEndpoint.java, platform/security/idp/security-idp-server/src/test/groovy/org/codice/ddf/security/idp/server/IdpEndpointSpecTest.groovy
- Adds the destination in `LogoutResponse`s sent through HTTP-POST
- Fixes not being able to read long `LogoutRequest`s though HTTP-POST 
@Lambeaux @brjeter @bakejeyner 
@coyotesqrl
@stustison 
Try using different SP's and verify that the destination is present in the `LogoutResponse`.
Test using Spring's SP. Contact me for how to do that.
When trying to use Spring's SP with DDF's IdP, we get a `org.opensaml.xml.security.SecurityException` with the message `SAML message intended destination (required by binding) was not present`
In https://docs.oasis-open.org/security/saml/v2.0/saml-bindings-2.0-os.pdf, section 3.5.5.2, we have:
```
If the message is signed, the Destination XML attribute in the root SAML element 
of the protocol message MUST contain the URL to which the sender has …
```
=> [2.11.x] DDF-3555 Add the destination in LogoutResponse sent through HTTP-POST and fix not being able to read long LogoutRequest

platform/security/common/src/main/java/org/codice/ddf/security/common/jaxrs/RestSecurity.java, platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/binding/post/PostRequestDecoder.java, platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/server/IdpEndpoint.java, platform/security/idp/security-idp-server/src/test/groovy/org/codice/ddf/security/idp/server/IdpEndpointSpecTest.groovy
Forward port of https://github.com/codice/ddf/pull/2863
- Adds the destination in `LogoutResponse`s sent through HTTP-POST
- Fixes not being able to read long `LogoutRequest`s though HTTP-POST 
@Lambeaux @brjeter @bakejeyner 
@coyotesqrl
@stustison 
Try using different SP's and verify that the destination is present in the `LogoutResponse`.
Test using Spring's SP. Contact me for how to do that.
When trying to use Spring's SP with DDF's IdP, we get a `org.opensaml.xml.security.SecurityException` with the message `SAML message intended destination (required by binding) was not present`
In https://docs.oasis-open.org/security/saml/v2.0/saml-bindings-2.0-os.pdf, section 3.5.5.2, we have:
```
If the message is signed, the Destination XML attribute in the root SAML element 
of the protocol …
```
=> DDF-3555 Add the destination in LogoutResponse sent through HTTP-POST and fix not being able to read long LogoutRequest

libs/common-system/pom.xml, libs/common-system/src/main/java/org/codice/ddf/configuration/AbsolutePathResolver.java, libs/common-system/src/test/java/org/codice/ddf/configuration/AbsolutePathResolverTest.java, platform/util/platform-util/pom.xml, platform/util/platform-util/src/main/java/org/codice/ddf/platform/util/properties/PropertiesLoader.java, platform/util/platform-util/src/test/java/org/codice/ddf/platform/util/properties/PropertiesLoaderTest.java, platform/util/platform-util/src/test/resources/test.properties
Cleans up PropertiesLoader by making the code cleaner and reducing cognitive complexity. Adds unit testing.
@Lambeaux 
@blen-desta 
@clockard
@coyotesqrl 
Should have no change in functionality.
[DDF-2879](https://codice.atlassian.net/browse/DDF-2879) …
=> DDF-2879 Refactor PropertiesLoader and add unit tests

catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/CswSourceConfiguration.java, catalog/spatial/csw/spatial-csw-source-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/AbstractCswSource.java, catalog/spatial/csw/spatial-csw-source-common/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/TestCswSource.java, catalog/spatial/csw/spatial-csw-source-common/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/TestCswSourceBase.java
Adds the ability to specify a client certificate alias to use with the CSW source.
Depends on: https://github.com/codice/ddf/pull/2866
@adimka 
@jlcsmith 
@bdeining 
@millerw8 
Adds the ability to specify alias and keystore as part of the CSW base classes.
[DDF-3564](https://codice.atlassian.net/browse/DDF-3564) …
=> DDF-3564 Added client certification configuration for CSW source.

catalog/transformer/catalog-transformer-xml/pom.xml, catalog/transformer/catalog-transformer-xml/src/main/java/ddf/catalog/transformer/xml/adapter/AdaptedMetacard.java, catalog/transformer/catalog-transformer-xml/src/test/java/ddf/catalog/transform/xml/TestAdaptedMetacard.java, catalog/transformer/catalog-transformer-xml/src/test/java/ddf/catalog/transform/xml/TestXmlInputTransformer.java
Fixes a bug where AdaptedMetacard was not cleaning out stale attribute values when new ones were set. 
@beyelerb 
@coyotesqrl
TBD
TBD
https://codice.atlassian.net/browse/DDF-3549 …
=> [2.11.x] DDF-3549 Download links for federated products in Intrigue should point to the local DDF instead of the remote one

catalog/ui/catalog-ui-search/pom.xml, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/security/UserApplication.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/security/WorkspacePolicyExtension.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/security/WorkspacePreIngestPlugin.java, catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.security.xml, catalog/ui/catalog-ui-search/src/main/webapp/js/model/User.js, catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/security/WorkspacePolicyExtensionTest.java, catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/security/WorkspacePreIngestPluginTest.java, catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/endpoint/CometdEndpoint.java, catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/service/UserService.java, catalog/ui/search-ui/search-endpoint/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/ui/search-ui/search-endpoint/src/test/java/org/codice/ddf/ui/searchui/query/endpoint/CometdEndpointTest.java, catalog/ui/search-ui/standard/src/main/webapp/js/model/user.js, catalog/ui/search-ui/standard/test.js, platform/security/core/security-core-impl/src/main/java/ddf/security/impl/SubjectIdentityImpl.java, platform/security/core/security-core-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/security/core/security-core-impl/src/main/resources/OSGI-INF/metatype/metatype.xml, platform/security/core/security-core-impl/src/test/java/ddf/security/impl/SubjectIdentityTest.java, platform/security/platform-security-core-api/src/main/java/ddf/security/SubjectIdentity.java
Updates UI to store user preferences by Unique ID instead of username. The unique ID method has been added to SecurityUtils and will first attempt to return an email address and then the username. 
@mojogitoverhere  
@bdeining 
@djblue 
@stustison
1. Launch UI as a user
2. Make a preference change
3. Navigate to https://localhost:8993/solr/#/preferences/query and query.
4. Ensure that the `id_txt` field is the correct email address for that user.
[DDF-3569](https://codice.atlassian.net/browse/DDF-3569) …
=> DDF-3569 Update UI to use unique ID for user preferences

Jenkinsfile
Mike O'Connor takes the blame for this.
Pipelines build was failing with an unexpected token in the Jenkinsfile. This PR corrects the issue.
@oconnormi @vinamartin @blen-desta @LinkMJB @emanns95 
@clockard
@rzwiefel 
Inspect Visually
=> DDF-3506 Fixed unexpected token from DSL Update

catalog/transformer/catalog-transformer-streaming-lib/src/main/java/org/codice/ddf/transformer/xml/streaming/lib/SaxEventHandlerDelegate.java
Adds support to org.codice.ddf.transformer.xml.streaming.lib.SaxEventHandlerDelegate for endDocument()
Adds support to org.codice.ddf.transformer.xml.streaming.lib.SaxEventHandlerDelegate for endDocument()
@emanns95 
@peterhuffer 
@clockard
@rzwiefel
Full build.
https://codice.atlassian.net/browse/DDF-3572
- ❓ …
=> DDF-3572: Add support to org.codice.ddf.transformer.xml.streaming.lib.SaxEventHandlerDelegate for endDocument()

catalog/ui/catalog-ui-search/src/main/webapp/component/visualization/maps/openlayers/map.openlayers.js
Lat/Lon show up as degrees when they are actually meters from 0 when using certain projections (EPSG:3857) in the lower corner of the map.  This cleans that up.  
Backport from master
@beyelerb
@rzwiefel
[DDF-3516](https://codice.atlassian.net/browse/DDF-3516) …
=> (2.11.x) DDF-3516 Converted coordinates from map projection to EPSG:4326 to display lat/lng to user

catalog/spatial/registry/registry-federation-admin-service-impl/src/main/java/org/codice/ddf/registry/federationadmin/service/impl/IdentityNodeInitialization.java, catalog/spatial/registry/registry-federation-admin-service-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/spatial/registry/registry-federation-admin-service-impl/src/test/java/org/codice/ddf/registry/federationadmin/service/impl/IdentityNodeInitializationTest.java, distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/SystemStateManager.java
DDF-3561 Make registry identity node initialization required for bundle startup
- Update SystemStateManger to ignore geoname metacards
- Remove SystemStateManager todo comment and code
@Lambeaux @mcalcote 
@coyotesqrl 
@shaundmorris
Verify ci build passes. Build downstream projects and verify their itests pass as well.
[DDF-3561](https://codice.atlassian.net/browse/DDF-3561)
=> DDF-3561 Make registry identity node initialization required for bundle startup

catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/pom.xml, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsSource.java, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/resources/OSGI-INF/metatype/metatype.xml
Adds configurability of allowing redirects to be followed from the WFS 1.1.0 source
@bdeining @adimka @mojogitoverhere
@bdeining @millerw8
Full build, config WFS 1.1.0 source and allow for redirects. Verify allowRedirects is set and followed.
[DDF-3585](https://codice.atlassian.net/browse/DDF-3585) …
=> DDF-3585 Add ability to follow redirects on the WFS 1.1.0 source

catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/transformer/CswQueryFilterTransformer.java, catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/transformer/CswRecordMapperFilterVisitor.java, catalog/spatial/csw/spatial-csw-endpoint/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/spatial/csw/spatial-csw-endpoint/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswQueryFactoryTest.java, catalog/spatial/csw/spatial-csw-endpoint/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswQueryFilterTransformerTest.java, catalog/spatial/csw/spatial-csw-endpoint/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/transformer/CswRecordMapperFilterVisitorTest.java
- Includes all registered attribute descriptors to determine the datatype of filter literal expressions. Without this, some expressions were being left as String instead of their actual data type and the query fails in Solr.
- No longer passing in the CSW metacard type into the `CswQueryFilterTransformer` and `CswRecordMapperFilterVisitor` since we are using all metacard types instead (already passed in).
@emmberk @emanns95 @blen-desta 
@bdeining 
@clockard 
- Setup a loopback CSW Federation Profile source
- Query the CSW source by several different types of attributes and verify they work as expected (specifically query by `effective` …
=> [2.11.x]DDF-3600 Use all registered attribute desciptors to build filters in the CSW Endpoint

catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/validation/impl/validator/MatchAnyValidator.java, catalog/core/catalog-core-api-impl/src/test/java/ddf/catalog/validation/impl/MatchAnyValidatorTest.java
Updated MatchAny validator to validate on a per value basis instead of a per attribute basis
@Variadicism @glenhein @GabrielFabian 
@jlcsmith
@millerw8
Build / Install / Add validators describe in ticket / Ingest Data / Verify validation
[DDF-3576](https://codice.atlassian.net/browse/DDF-3576) …
=> DDF-3576 Updated MatchAny validator to validate on a per value basis instead of a per attribute basis

catalog/ui/catalog-ui-search/src/main/webapp/component/search-interactions/search-interactions.hbs, catalog/ui/catalog-ui-search/src/main/webapp/component/search-interactions/search-interactions.less, catalog/ui/catalog-ui-search/src/main/webapp/component/search-interactions/search-interactions.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/search-settings/search-settings.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/search-type/search-type.view.js, catalog/ui/catalog-ui-search/src/main/webapp/js/model/QuerySettings.js
Incorporates some feedback from https://github.com/codice/ddf/pull/2845
Adds quick switch actions for the basic form types, and stores the type as a preference.
@bdeining 
@millerw8
@adimka 
Verify the quick switch options work for switching forms.  Verify that after running a search, the form you switched to is the form that appears when searching.
[DDF-3512](https://codice.atlassian.net/browse/3512)
=> DDF 3512 Add quick switch actions for forms, user preference for form type

platform/security/common/src/main/java/ddf/security/samlp/impl/SamlValidator.java, platform/security/idp/security-idp-client/src/main/java/org/codice/ddf/security/idp/client/IdpHandler.java, platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/binding/api/impl/ValidatorImpl.java, platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/binding/post/PostResponseCreator.java, platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/binding/redirect/RedirectResponseCreator.java, platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/binding/redirect/RedirectValidator.java, platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/binding/soap/SoapResponseCreator.java, platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/server/IdpEndpoint.java, platform/security/idp/security-idp-server/src/test/java/org/codice/ddf/security/idp/server/IdpEndpointTest.java
1. DDF-3571 Changed DDF so it doesn't require a relayState but if one is provided it should include it in its response
2. DDF-3556 Changed LogoutResponse issuer for post and redirect binding
3. DDF-3574 Check the accepted binding and send a correctly formatted response - adding template type
@brjeter @Lambeaux @bakejeyner 
@coyotesqrl 
@stustison
Test by connecting DDF to Spring (which doesn't provide a relay state by default). This should be done without changing DDF's metadata.
[DDF-3571](https://codice.atlassian.net/browse/DDF-3571)
[DDF-3556](https://codice.atlassian.net/browse/DDF-3556)
[DDF-3574](https://codice.atlassian.net/browse/DDF-3574)
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance …
=> [2.11.x] Minor SAML Spec compliance fixes

distribution/docs/src/main/resources/content/_quickstart/quickstart-certificates.adoc, distribution/docs/src/main/resources/content/_quickstart/quickstart-installing.adoc
Adds an authentication type for `/admin=BASIC` that gets removed after install
Updates documentation to explain how to generate certs that are valid for IP addresses
@clockard @figliold 
1. Follow the added section in the quickstart guide.
2. Start the system.
3. Access admin ui installer via `https://<FQDN>:8993/admin`
4. Confirm that login works via idp
5. Starting with a clean system, repeat using IP instead of FQDN in all steps.
[DDF-3559](https://codice.atlassian.net/browse/DDF-3559) …
=> DDF-3559 Bypassing IdP during initial install

catalog/transformer/catalog-transformer-service-atom/src/main/java/ddf/catalog/transformer/response/query/atom/AtomTransformer.java
Backported from master
@jlcsmith
@shaundmorris
[DDF-3511](https://codice.atlassian.net/browse/DDF-3511) …
=> (2.11.x) DDF-3511 Moved WKTReader in AtomTransformer to be a member variable for thread safety

catalog/ui/catalog-ui-search/src/main/webapp/component/workspace-details/workspace-details.hbs, catalog/ui/catalog-ui-search/src/main/webapp/component/workspace-details/workspace-details.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/workspace-item/workspace-item.collection.view.js, catalog/ui/catalog-ui-search/src/main/webapp/js/model/Workspace.js
- Previously the workspace collection wouldn't rerender on sync, so newly created workspaces that lacked an owner (till the server returned) would be hidden if the filtering was set to "owned by me".
- Sorting by modified previously used the static "modified" field.  Now it uses the "metacard.modified" field.  Also, the sorting is reversed to sort newly modified things to the top.
@adimka 
@bdeining 
=> DDF-3580, DDF-3581 Updates workspace collection to appropriately rerender and sort

catalog/ui/catalog-ui-search/src/main/webapp/js/cql.js, catalog/ui/catalog-ui-search/src/main/webapp/js/cql.spec.js, catalog/ui/catalog-ui-search/src/main/webapp/js/model/Workspace.collection.js
Intrigue now exclusively uses the characters `* ? \` to represent wildcard, single character wildcard, and escape respectively. These characters are translated to their CQL-equivalent syntax before querying the CQL endpoint and workspaces are saved with their queries in CQL format. Any user-inputted CQL special characters are escaped before sending. If a user wants to utilize these CQL characters, they must the `* ? \` syntax mentioned above.
@djblue 
@vinamartin 
@rzwiefel
@codice/ui 
@codice/io 
@pklinef 
Install DDF, create a workspace with a query that uses CQL and Intrigue special characters, and ensure that when the query is run and the workspace is created, all outgoing requests have the following character transformations:
`* `=> `%`
`?` => `_`
`%` =>`\%`
`_` => …
=> DDF-3566: Update Intrigue to use CQL query syntax with the CQL endpoint

catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/transformer/CswQueryFilterTransformer.java, catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/transformer/CswRecordMapperFilterVisitor.java, catalog/spatial/csw/spatial-csw-endpoint/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/spatial/csw/spatial-csw-endpoint/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswQueryFactoryTest.java, catalog/spatial/csw/spatial-csw-endpoint/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswQueryFilterTransformerTest.java, catalog/spatial/csw/spatial-csw-endpoint/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/transformer/CswRecordMapperFilterVisitorTest.java
Forward-port for https://github.com/codice/ddf/pull/2921
- Includes all registered attribute descriptors to determine the datatype of filter literal expressions. Without this, some expressions were being left as String instead of their actual data type and the query fails in Solr.
- No longer passing in the CSW metacard type into the `CswQueryFilterTransformer` and `CswRecordMapperFilterVisitor` since we are using all metacard types instead (already passed in).
@emmberk @emanns95 @blen-desta 
@bdeining 
@clockard 
- Setup a loopback CSW Federation Profile source
- Query the CSW source by several different types of attributes and verify …
=> DDF-3600 Use all registered attribute desciptors to build filters in the CSW Endpoint (#2921)

platform/security/common/src/main/java/ddf/security/samlp/impl/SamlValidator.java, platform/security/idp/security-idp-client/src/main/java/org/codice/ddf/security/idp/client/IdpHandler.java, platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/binding/api/impl/ValidatorImpl.java, platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/binding/post/PostResponseCreator.java, platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/binding/redirect/RedirectResponseCreator.java, platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/binding/redirect/RedirectValidator.java, platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/binding/soap/SoapResponseCreator.java, platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/server/IdpEndpoint.java, platform/security/idp/security-idp-server/src/test/java/org/codice/ddf/security/idp/server/IdpEndpointTest.java
Forward port of https://github.com/codice/ddf/pull/2889
1. DDF-3571 Changed DDF so it doesn't require a relayState but if one is provided it should include it in its response
2. DDF-3556 Changed LogoutResponse issuer for post and redirect binding
3. DDF-3574 Check the accepted binding and send a correctly formatted response - adding template type
@brjeter @Lambeaux @bakejeyner 
@coyotesqrl 
@stustison
Test by connecting DDF to Spring (which doesn't provide a relay state by default). This should be done without changing DDF's metadata.
[DDF-3571](https://codice.atlassian.net/browse/DDF-3571)
[DDF-3556](https://codice.atlassian.net/browse/DDF-3556)
[DDF-3574](https://codice.atlassian.net/browse/DDF-3574) …
=> DDF-3571 Minor SAML Spec compliance fixes

catalog/ui/catalog-ui-search/src/main/webapp/js/cql.js, catalog/ui/catalog-ui-search/src/main/webapp/js/cql.spec.js, catalog/ui/catalog-ui-search/src/main/webapp/js/model/Workspace.js
**Backport of [DDF-3566](https://github.com/codice/ddf/pull/2887)**
Intrigue now exclusively uses the characters `* ? \` to represent wildcard, single character wildcard, and escape respectively. These characters are translated to their CQL-equivalent syntax before querying the CQL endpoint and workspaces are saved with their queries in CQL format. Any user-inputted CQL special characters are escaped before sending. If a user wants to utilize these CQL characters, they must the `* ? \` syntax mentioned above.
@djblue 
@vinamartin 
@rzwiefel
@codice/ui 
@codice/io 
@pklinef 
Install DDF, create a workspace with a query that uses CQL and Intrigue special characters, and ensure that when the query is run and the workspace is created, all outgoing requests have the following …
=> [2.11.x] DDF-3566: Update Intrigue to use CQL query syntax

platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/binding/api/impl/ValidatorImpl.java
Disallows angle brackets - `<` and `>` - in `RelayState`.
@rzwiefel
@stustison
Attaching a third-party SP in which the `RelayState` can be specified (Spring Security works well for this) and setting the `RelayState` to any value with any number of angle brackets should disallow authentication.
N/A
[DDF-3606](https://codice.atlassian.net/browse/DDF-3606) …
=> DDF-3606 Prevents low-risk XSS reflection attack from a remote SP by validating RelayState.

platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/server/IdpEndpoint.java, platform/security/idp/security-idp-server/src/test/java/org/codice/ddf/security/idp/server/IdpEndpointTest.java
Backport of https://github.com/codice/ddf/pull/2936
Check bindings supported by SP when sending passive pki login responses
@brjeter @Lambeaux @bakejeyner
@coyotesqrl
@rzwiefel
@stustison 
Connecting to Spring security.
We check the supported bindings when we do initial login but not through this path.
[DDF-3574](https://codice.atlassian.net/browse/DDF-3574) …
=> [2.11.x] DDF-3574 Check bindings supported by SP when sending passive pki login responses

platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/server/IdpEndpoint.java, platform/security/idp/security-idp-server/src/test/java/org/codice/ddf/security/idp/server/IdpEndpointTest.java
Forward port of https://github.com/codice/ddf/pull/2937
Check bindings supported by SP when sending passive pki login responses
@brjeter @Lambeaux @bakejeyner
@coyotesqrl
@rzwiefel
@stustison 
Connecting to Spring security. Note: Changes from https://github.com/codice/ddf/pull/2930 are required.
We check the supported bindings when we do initial login but not through this path.
[DDF-3574](https://codice.atlassian.net/browse/DDF-3574) …
=> DDF-3574 Check bindings supported by SP when sending passive pki login responses

catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsSource.java
Made WFS 1.1 support redirect configuration when configured with certificate authentication.
Currently, WFS 1.1 allows the user to specify username/pass, or certificate, or neither.  It also allows the user to specify allowRedirects, but that variable was not used when configured with certificates.  This adds that to the configuration
@troymohl  
@glenhein 
@bdeining
@jlcsmith
Likely just an oversight as different parts came together.  Unfortunately also overlaps with the specific configuration for a current use-case.
[DDF-3570](https://codice.atlassian.net/browse/DDF-3570)
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guide …
=> DDF-3570 Made WFS 1.1 support redirect configuration when using certificates

catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/Csw.java
Removed javax.ws.rs.Consumes from CSW GET actions so that the requests don't expect an explicit content type
@jrnorth 
@bdeining
@jlcsmith
Hook up to wiremock or any other service that will accept CSW connections.  Confirm the outbound request for getCapabilities (or any GET request) does not include the Content-Type header
CSW JAX-RS Interface shouldn't impose a Content-Type header on GET methods.
Requiring application/xml or text/xml (as it currently does) implies a payload being sent along the GET requests.  These requests do not include a payload, and it is typically recommended that get requests do not include payloads.  Further, tables 52 and 54 of the CSW 2.0.2 …
=> DDF-3615 Removed Consumes from Csw javax RS interface

platform/security/idp/security-idp-client/src/main/java/org/codice/ddf/security/idp/client/AssertionConsumerService.java
Improves the error message that is displayed when the user sits idle at the idp for too long then attempts to log in.
@blen-desta 
@brjeter 
@idperez 
@clockard
@coyotesqrl
1. Start up and install DDF
2. Wait at the login screen for >10 minutes
3. When attempting to log in after 10 minutes the message "AuthN response returned unknown or expired relay state. Please refresh the page or resend the request to continue the login process." Should be displayed.
4. Refreshing the page should log you into DDF.
[3609](https://codice.atlassian.net/browse/3609) …
=> DDF-3609 Idle during login on DDF displays non-helpful error message

catalog/core/catalog-core-api/src/main/resources/feature.xml, catalog/rest/catalog-rest-endpoint/pom.xml, catalog/rest/catalog-rest-endpoint/src/test/java/org/codice/ddf/endpoints/rest/RestEndpointIT.java, libs/test-common/src/main/filtered-resources/features.xml, libs/test-common/src/main/java/org/codice/ddf/test/common/AbstractComponentTest.java, libs/test-common/src/main/java/org/codice/ddf/test/common/configurators/ApplicationOptions.java, libs/test-common/src/main/java/org/codice/ddf/test/common/configurators/PortFinder.java, platform/mime/core/platform-mime-core-api/src/main/resources/feature.xml
Changed how the PortFinder is being passed around in the AbstractComponentTest class.
Renamed the catalog core API and mime type API features to avoid conflict with those defined in the platform-app and catalog-app features files, which was causing tests to fail in some circumstances.
Improved some of the comments and removed unneeded dependencies in pom files.
Back-port of https://github.com/codice/ddf/pull/2951.
@tbatie 
@paouelle 
@clockard
@coyotesqrl
CI build successful.
[DDF-3105](https://codice.atlassian.net/browse/DDF-3105)
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Requ …
=> [2.11.x] DDF-3105 Create Component test for REST endpoint

catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/pom.xml, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsFilterDelegate.java, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsSource.java, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/resources/OSGI-INF/metatype/metatype.xml, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsFilterDelegateTest.java, distribution/docs/src/main/resources/content/_tables/Wfs_v1_1_0_Federated_Source.adoc, libs/geospatial/src/main/java/org/codice/ddf/libs/geo/util/GeospatialUtil.java
It was discovered that since the WFS 1.1 code is able to set the desired SRS in the query, that the code no longer needs to restrict geo queries to features that report a 4326 SRS.  The SRS value used in the query is now admin configurable. 
@bdeining 
@jlcsmith 
https://github.com/orgs/codice/teams/IO
@bdeining
@millerw8
Test against GeoServer. When configuring  the source, use "urn:x-ogc:def:crs:EPSG:4326" for the SRS.  …
=> DDF-3552 bug fix related to srs in queries

catalog/ui/catalog-ui-search/src/main/webapp/component/component.less, catalog/ui/catalog-ui-search/src/main/webapp/component/navigation/navigation.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/navigator/navigator.less, catalog/ui/catalog-ui-search/src/main/webapp/component/notfound/notfound.hbs, catalog/ui/catalog-ui-search/src/main/webapp/component/notfound/notfound.less, catalog/ui/catalog-ui-search/src/main/webapp/component/notfound/notfound.view.js, catalog/ui/catalog-ui-search/src/main/webapp/index.html, catalog/ui/catalog-ui-search/src/main/webapp/js/application.js, catalog/ui/catalog-ui-search/src/main/webapp/js/router.js, catalog/ui/catalog-ui-search/src/main/webapp/properties.js, catalog/ui/catalog-ui-search/src/main/webapp/styles/components/content.less, catalog/ui/catalog-ui-search/src/main/webapp/styles/fonts.less
- Adds ability to hide the upload page on Intrigue
- Adds a "not found" page to handle when routing to something that
doesn't exist.
@bdeining 
@jlcsmith 
@adimka 
@millerw8
Go to Intrigue with upload disabled in the configuration.  Verify you cannot reach the upload page (/#ingest).  
The  configuration already existed for this, it wasn't hooked in however.
[3611](https://codice.atlassian.net/browse/3611)
- ❓ …
=> DDF-3611 Adds ability to hide upload page on Intrigue

platform/security/rest/security-rest-cxfwrapper/src/main/java/org/codice/ddf/cxf/SecureCxfClientFactory.java
Changes SecureCxfClientFactory to only set setUseHttpsURLConnectionDefaultHostnameVerifier to true when disableCNChecks is false.
@bdeining 
@stustison
Per the javadoc we shouldn't have been setting that parameter to true when we were setting disableCNChecks to true: https://github.com/apache/cxf/blob/master/core/src/main/java/org/apache/cxf/configuration/jsse/TLSClientParameters.java#L127-L132
[DDF-3623](https://codice.atlassian.net/browse/DDF-3623) …
=> DDF-3623 Set setUseHttpsURLConnectionDefaultHostnameVerifier to false if disabling CN checks

distribution/docs/src/main/resources/content/_appReferences/mg-broker-app.adoc, distribution/docs/src/main/resources/content/_appReferences/mg-geowebcache.adoc, distribution/docs/src/main/resources/content/_architectures/metrics-reporting.adoc, distribution/docs/src/main/resources/content/_configuring/admin-console-tutorial.adoc, distribution/docs/src/main/resources/content/_configuring/global-settings.adoc, distribution/docs/src/main/resources/content/_configuring/securing-idp-sp.adoc, distribution/docs/src/main/resources/content/_devComponents/custom-applications.adoc, distribution/docs/src/main/resources/content/_endpoints/application-endpoint.adoc, distribution/docs/src/main/resources/content/_endpoints/catalog-rest-endpoint.adoc, distribution/docs/src/main/resources/content/_endpoints/cometd-endpoint.adoc, distribution/docs/src/main/resources/content/_endpoints/csw-endpoint.adoc, distribution/docs/src/main/resources/content/_endpoints/metrics-endpoint.adoc, distribution/docs/src/main/resources/content/_installing/installing-from-admin-console.adoc, distribution/docs/src/main/resources/content/_installing/system-configuration-settings.adoc, distribution/docs/src/main/resources/content/_quickstart/quickstart-configuring.adoc, distribution/docs/src/main/resources/content/_quickstart/quickstart-ingesting.adoc, distribution/docs/src/main/resources/content/_running/command-scheduler.adoc, distribution/docs/src/main/resources/content/_running/monitoring.adoc, distribution/docs/src/main/resources/content/_securityFramework/guest-interceptor.adoc, distribution/docs/src/main/resources/content/_tables/Confluence_Federated_Source.adoc, distribution/docs/src/main/resources/content/_tables/EmailNotifier.adoc, distribution/docs/src/main/resources/content/_tables/OpenSearchSource.adoc, distribution/docs/src/main/resources/content/_using/using-catalog-search-ui.adoc, distribution/docs/src/main/resources/content/_using/using-landing-page.adoc, pom.xml
Fixes sample default/url formatting for documentation. It has been overgeneralizing the formatting caused pre-formatted code sections to display an unnecessary leading `\` character.
@clockard
@coyotesqrl
@lessarderic
@rzwiefel
@shaundmorris
These default urls should not be displayed as links, but they should not have the escape slash at the beginning either …
=> [2.11.x] DDF-2824 fixed formatting for sample DDF urls in docs

distribution/ddf-common/src/main/resources-filtered/etc/startup.properties, distribution/ddf-common/src/main/resources/common-bin.xml, distribution/kernel/pom.xml, distribution/kernel/src/main/descriptors/bin.xml, platform/admin/core/admin-core-appservice/src/main/java/org/codice/ddf/admin/application/service/impl/ApplicationServiceBean.java, platform/osgi/platform-osgi-configadmin/src/main/java/org/codice/felix/cm/file/ConfigurationContextImpl.java, pom.xml
Upgrades Felix Fileinstall to 3.6.4 and removes the hack to stay on 3.6.0
@paouelle 
@brjeter 
@clockard 
@shaundmorris
Ensure that config files in etc do not have strange / unnecessary values. 
Ensure all config fields show up on the admin ui. 
Fileinstall was upgraded from 3.6.0 to 3.6.4 as part of the Karaf upgrade. Due to some issues (config file pollution, configs missing from ui, etc) we implemented a temporary hack to continue using Fileinstall 3.6.0 in case the issue could not be resolved in time. This PR is to resolve said issues. 
[DDF-3558](https://codice.atlassian.net/browse/DDF-3558) …
=> [2.11.x] DDF-3558 Upgrade Felix Fileinstall to 3.6.4

platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/admin/ExportMigrationConfigurationAdminContext.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/admin/ImportMigrationConfigurationAdminContext.java
It modifies the config admin migratable to export the config objects into a different folder from etc to prevent collision if actual config files from etc are exported.
@emanns95 
@tbatie 
@clockard
@figliold
- Install DDF and make changes to config
- Perform a `migration:export` 
- Preserve the 3 files exported
- Re-install DDF
- Perform `migration:import` 
- Verify that the system is reconfigured as it was
[DDF-3614](https://codice.atlassian.net/browseDDF-3614/) …
=> [2.11.x] DDF-3614 Modified config admin migratable to export config objects to a separate folder

distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/AbstractIntegrationTest.java, distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/KarafConsole.java, distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/SystemStateManager.java
Increases the timeout for the catalog:removeall commad in itests
@tbatie 
@emanns95 
@paouelle 
@clockard
@rzwiefel 
CI build
https://codice.atlassian.net/browse/DDF-3626
- ❗ …
=> DDF-3626: Add timeout to catalog:removeall command in itests

platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/admin/ExportMigrationConfigurationAdminContext.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/admin/ImportMigrationConfigurationAdminContext.java
It modifies the config admin migratable to export the config objects into a different folder from etc to prevent collision if actual config files from etc are exported.
@emanns95 
@tbatie 
@clockard
@figliold
- Install DDF and make changes to config
- Perform a `migration:export` 
- Preserve the 3 files exported
- Unzip DDF distribution
- Perform `migration:import --profile` 
- Verify that the system is reconfigured as it was
[DDF-3614](https://codice.atlassian.net/browseDDF-3614/)
- ✏️ (Pencil) …
=> DDF-3614 Modified config admin migratable to export config objects to a separate folder

catalog/opensearch/catalog-opensearch-source/pom.xml, catalog/opensearch/catalog-opensearch-source/src/main/java/ddf/catalog/source/opensearch/impl/OpenSearchParserImpl.java, catalog/opensearch/catalog-opensearch-source/src/test/groovy/ddf/catalog/source/opensearch/impl/OpenSearchParserImplCreateBBoxSpec.groovy, catalog/opensearch/catalog-opensearch-source/src/test/java/ddf/catalog/source/opensearch/impl/OpenSearchFilterVisitorTest.java, catalog/opensearch/catalog-opensearch-source/src/test/java/ddf/catalog/source/opensearch/impl/OpenSearchParserImplTest.java, catalog/opensearch/catalog-opensearch-source/src/test/java/ddf/catalog/source/opensearch/impl/OpenSearchSourceTest.java, catalog/schematron/catalog-schematron-plugin/src/main/resources/iso-schematron/iso_schematron_skeleton_for_saxon.xsl, catalog/schematron/catalog-schematron-plugin/src/main/resources/iso-schematron/iso_svrl_for_xslt2.xsl, catalog/ui/search-ui/simple/src/main/resources/RecordView.html, catalog/ui/search-ui/simple/src/main/webapp/lib/jquery/js/plugin/purl.js, distribution/docs/src/main/resources/content/_tables/OpenSearchSource.adoc, platform/admin/modules/admin-modules-application/src/test/resources/services.json, platform/admin/modules/admin-modules-configuration/src/test/resources/services.json, platform/admin/modules/admin-modules-installer/src/test/resources/services.json
This PR fixes the OpenSearch `Convert to BBox` option.
@AzGoalie @peterhuffer 
@codice/io 
@bdeining
@clockard
Execute point radius searches to an OpenSearch source in Intrigue, and confirm that the expected results are returned.
Specifically, the issue was observed with a record with `location`=`POLYGON ((-122 37.33, -122.05 37.33, -122.05 37.22, -122 37.22, -122 37.33))` and the search "`Latitude`=`33`, `Longitude`=`-122`, `Radius`=`500 miles`" from Intrigue. The `OpenSearchSource`, with `Convert to BBox`=`true`, was incorrectly transforming the spatial search to `bbox=422.42053621382615,25.77186615764653,-666.4205362138262,40.22813384235347`.
[DDF-3604](https://codice.atlassian.net/browse/DDF-3604)
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/7 …
=> [2.11.x] DDF-3604 Fixed OpenSearch bounding box

distribution/docs/src/main/resources/content/_appReferences/mg-broker-app.adoc, distribution/docs/src/main/resources/content/_appReferences/mg-geowebcache.adoc, distribution/docs/src/main/resources/content/_architectures/metrics-reporting.adoc, distribution/docs/src/main/resources/content/_configuring/admin-console-tutorial.adoc, distribution/docs/src/main/resources/content/_configuring/global-settings.adoc, distribution/docs/src/main/resources/content/_configuring/securing-idp-sp.adoc, distribution/docs/src/main/resources/content/_devComponents/custom-applications.adoc, distribution/docs/src/main/resources/content/_endpoints/application-endpoint.adoc, distribution/docs/src/main/resources/content/_endpoints/catalog-rest-endpoint.adoc, distribution/docs/src/main/resources/content/_endpoints/cometd-endpoint.adoc, distribution/docs/src/main/resources/content/_endpoints/csw-endpoint.adoc, distribution/docs/src/main/resources/content/_endpoints/metrics-endpoint.adoc, distribution/docs/src/main/resources/content/_installing/installing-from-admin-console.adoc, distribution/docs/src/main/resources/content/_installing/system-configuration-settings.adoc, distribution/docs/src/main/resources/content/_quickstart/quickstart-configuring.adoc, distribution/docs/src/main/resources/content/_quickstart/quickstart-ingesting.adoc, distribution/docs/src/main/resources/content/_running/command-scheduler.adoc, distribution/docs/src/main/resources/content/_running/monitoring.adoc, distribution/docs/src/main/resources/content/_securityFramework/guest-interceptor.adoc, distribution/docs/src/main/resources/content/_tables/Confluence_Federated_Source.adoc, distribution/docs/src/main/resources/content/_tables/EmailNotifier.adoc, distribution/docs/src/main/resources/content/_tables/OpenSearchSource.adoc, distribution/docs/src/main/resources/content/_using/using-catalog-search-ui.adoc, distribution/docs/src/main/resources/content/_using/using-landing-page.adoc, pom.xml
**Port to `master` of PR https://github.com/codice/ddf/pulls**
Fixes sample default/url formatting for documentation. It has been overgeneralizing the formatting caused pre-formatted code sections to display an unnecessary leading `\` character.
@clockard
@coyotesqrl
@lessarderic
@rzwiefel
@shaundmorris
These default urls should not be displayed as links, but they should not have the escape slash at the beginning either …
=> DDF-2824 fixed formatting for sample DDF urls in docs

distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/ServiceManagerImpl.java
Filters out Fragment bundles from the log messages that are displayed for bundles that are not ACTIVE when itests fail to start.
@emanns95 @tbatie 
@lessarderic
@rzwiefel
This is an itest change and will only show up on a failure to start. CI should be sufficient, but could be more thoroughly heroed by making a feature/bundle un-deployable for an itest (by depending on something unavailable, for example) and then confirming that the log contains none of the Fragment bundles after the `Listing inactive bundles` log message.
N/A
[DDF-3642](https://codice.atlassian.net/browse/DDF-3642)
Please see …
=> DDF-3642 Filters out Fragment bundles from logging on itest failures

catalog/spatial/kml/spatial-kml-transformer/pom.xml, catalog/transformer/catalog-transformer-xml/pom.xml, catalog/transformer/catalog-transformer-xml/src/main/java/ddf/catalog/transformer/xml/GeometryTransformer.java, catalog/transformer/catalog-transformer-xml/src/main/java/ddf/catalog/transformer/xml/XmlInputTransformer.java, catalog/transformer/catalog-transformer-xml/src/main/java/ddf/catalog/transformer/xml/XmlValidationEventHandler.java, catalog/transformer/catalog-transformer-xml/src/test/java/ddf/catalog/transform/xml/TestXmlValidationEventHandler.java
The DefaultValidationEventHandler may print to the system when an exception occurs. By extending it and overwriting the methods we can send these messages to the log instead of polluting the karaf console. 
This change also updates the KML dependency used for similar reasons.
@vinamartin @ahoffer @garrettfreibott @gordocanchola 
@clockard @rzwiefel
build the project, Inspect the changes. I can provide a test file to confirm the karaf console doesn't have the same stack trace as before.
[DDF-3647](https://codice.atlassian.net/browse/DDF-3647) …
=> DDF-3647 Add Custom XmlValidationEventHandler, update KML dependency to use Codice fork

distribution/docs/src/main/resources/content/_architectures/migration-api.adoc, platform/migration/platform-migratable-api/src/main/java/org/codice/ddf/migration/ExportMigrationContext.java, platform/migration/platform-migratable-api/src/test/java/org/codice/ddf/migration/ExportMigrationContextTest.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/admin/ConfigurationAdminMigratable.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/admin/ExportMigrationConfigurationAdminContext.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/admin/ImportMigrationConfigurationAdminContext.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/ExportMigrationContextImpl.java, platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/admin/ConfigurationAdminMigratableTest.java, platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/migration/ExportMigrationContextImplTest.java
It modifies the config admin migratable to export the config files under etc in addition to the config objects. Although the import phase will not re-import those files, it eventually might re-import them. Since in order to support it later, we need to make sure the files are available as part of the export DAR file.
@emanns95 
@tbatie 
@clockard
@lessarderic 
@figliold
- Install DDF and make changes to config
- Perform a `migration:export` 
- Preserve the 3 files exported
- Re-install DDF
- Perform `migration:import` 
- Verify that the system is reconfigured as it was
[DDF-3614](https://codice.atlassian.net/browseDDF-3614/) …
=> [2.11.x] DDF-3614 Modified config admin migratable to export config files in addition to objects

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/RemoteDeleteOperations.java, catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/impl/operations/RemoteDeleteOperationsTest.java
- Previously the framework would overwrite the return collection instead of accumulating them into a set of results. Now the proper accumulation occurs
anyone
remotely delete across two separate sources
https://codice.atlassian.net/browse/DDF-2970 …
=> [2.11.x] DDF-2970 Fixed remote delete result collection

platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/binding/redirect/RedirectResponseCreator.java
Encodes the RelayState before creating the signature, according to the [SAML Specification Section 3.4.4.1](https://www.oasis-open.org/committees/download.php/56780/sstc-saml-bindings-errata-2.0-wd-06-diff.pdf):
"To construct the signature, a string consisting of the concatenation of the RelayState (if present), SigAlg, and SAMLRequest (or SAMLResponse) query string parameters (each one URLencoded) is constructed"
@blen-desta 
@kcover
@clockard
@stustison
Log into DDF
[DDF-3571](https://codice.atlassian.net/browse/DDF-3571) …
=> DDF-3571 Encode relay state when creating SAML signature

distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/AbstractIntegrationTest.java
In a downstream project that extends `AbstractIntegrationTest`, we want the Security Manager turned off for itests. Overriding the `configureVmOptions` method should turn off the Security Manager in the itests, but the `homeXxxOption` methods are not visible outside of the AbstractIntegrationTest class:
```java
@Override
protected Option[] configureVmOptions() {
return options(
vmOption("-Xmx2048M"),
// avoid integration tests stealing focus on OS X
vmOption("-Djava.awt.headless=true"),
vmOption("-Dfile.encoding=UTF8"),
HomeAwareVmOption.homeAwareVmOption("-Dddf.home={karaf.home}"),
HomePermVmOption.homePermVmOption("-Dddf.home.perm={karaf.home}"),
HomePolicyVmOption.homePolicyVmOption("-Dddf.home.policy={karaf.home}"));
}
```
@peterhuffer @kcover @figliold @mcalcote @coyotesqrl …
=> DDF-3297 Updated some Security Manager-related methods in AbstractIntegrationTest to be protected

catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/IngestCommand.java, catalog/schematron/catalog-schematron-plugin/src/main/resources/OSGI-INF/metatype/metatype.xml, dependency-check-maven-config.xml, distribution/docs/src/main/resources/content/_securityServices/expansion-service.adoc, distribution/docs/src/main/resources/content/_tables/SchematronValidationService.adoc, platform/security/expansion/security-expansion-metacardattr-map/src/main/resources/OSGI-INF/metatype/metatype.xml, platform/security/expansion/security-expansion-userattr-map/src/main/resources/OSGI-INF/metatype/metatype.xml, platform/solr/platform-solr-server-standalone/dependency-check-maven-config.xml
- Fixes some typos in `IngestCommand`
- Fixes some typos in the `Expansion Service` metatypes and docs
- Adds a note about relative file paths to the `Schematron File Names` field in the `Schematron Validators` configuration
@kcover @peterhuffer
@codice/docs 
@clockard
@ricklarsen
Full build. Check that tooltips and docs are formatted correctly.
- ❓ (Question …
=> DDF-2824 Fixed some typos in IngestCommand and some configurations

catalog/ui/catalog-ui-search/src/main/webapp/component/confirmation/query/confirmation.query.hbs, catalog/ui/catalog-ui-search/src/main/webapp/component/content/content.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/dropdown/query-select/dropdown.query-select.hbs, catalog/ui/catalog-ui-search/src/main/webapp/component/dropdown/result-filter/dropdown.result-filter.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/query-interactions/query-interactions.hbs, catalog/ui/catalog-ui-search/src/main/webapp/component/query-item/query-item.hbs
Changes all literal uses of the word query to the word search in order to keep verbiage consistent throughout the UI.
@jrnorth 
@Variadicism 
@brianfelix 
@codice/ui
@bdeining 
Could be through inspection or pull up the new version with the change in it.
[DDF-3657](https://codice.atlassian.net/browse/DDF-3657) …
=> DDF-3657 Use common language for Search and selecting a saved search

platform/security/rest/security-rest-cxfwrapper/src/main/java/org/codice/ddf/cxf/SecureCxfClientFactory.java
Allows a SecureCXFClient supporting redirects the ability to go through the same URL multiple times
[DDF-3570](https://codice.atlassian.net/browse/DDF-3570) …
=> DDF-3570 Allows a SecureCXFClient supporting redirects to the same URL multiple times

distribution/ddf-common/src/main/resources/etc/org.ops4j.pax.url.mvn.cfg
Updates pax mvn settings to only look for a maven settings file under the users home directory
@peterhuffer @blen-desta @coyotesqrl 
@clockard @pklinef 
[DDF-3681](https://codice.atlassian.net/browse/DDF-3681) …
=> DDF-3681 updated pax maven settings

broker/broker-security-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml
Previously the update-strategy was "component-managed" with update-method="update" but there is no such method in `SubjectInjectorPlugin`. This change ensures the `setConfiguredAddresses()` method will be called on configuration updates.
@roelens8 
@clockard
@jaymcnallie
Install `broker-app` and the `broker-security` feature. Set a breakpoint inside `setConfiguredAddresses()` in `SubjectInjectorPlugin` and verify that it is hit when you update the `Subject Injector Plugin Configuration` in the Admin UI.
[DDF-3524](https://codice.atlassian.net/browse/DDF-3524) …
=> DDF-3524 Change SubjectInjectorPlugin update-strategy to "container-managed"

catalog/ui/catalog-ui-search/src/main/webapp/component/search-interactions/search-interactions.view.js, catalog/ui/catalog-ui-search/src/main/webapp/component/search-settings/search-settings.hbs, catalog/ui/catalog-ui-search/src/main/webapp/component/search-settings/search-settings.less, catalog/ui/catalog-ui-search/src/main/webapp/component/search-settings/search-settings.view.js
Adds ability to cancel out of search settings configuration window.
@bdeining 
@lcrosenbu 
@bdeining
[DDF-3649](https://codice.atlassian.net/browse/DDF-3649) …
=> DDF-3649 Adding Cancel Button in Query Settings Configuration Window

catalog/ui/catalog-ui-search/src/main/webapp/js/model/List.js, catalog/ui/catalog-ui-search/src/main/webapp/js/model/Workspace.collection.js, catalog/ui/catalog-ui-search/src/main/webapp/js/router.js
- Previously these areas would get the defaults for the unspecified attributes.  This could possibly cause issues with attributes like federation being left blank.  Whether or not we should do so for the "create search from geo" is hard to determine.
- It might be worth exploring doing this in alternative ways.  We could go back and make it so user defaults need to be explicitly mixed in rather than having them as part of the Query defaults for all new queries.  Or we could make a method to apply user defaults and use that where we need it.  Or we could have two different query models, with one that extends the other and simply mixes in the user defaults.  There are a lot of options.
@djblue 
@rzwiefel 
@birda 
@pklinef
[3629](https://codice.atlassian.net/browse/DDF-3629)
- ✏️ (Pencil) …
=> DDF-3629 Updates instantiations of new Searches to be more specific

catalog/ui/catalog-ui-search/src/main/webapp/js/ColorGenerator.js
- Removes colors that typically indicate warnings or errors.
- Uses the 10 best colors from this palette (https://ux.stackexchange.com/questions/94696/color-palette-for-all-types-of-color-blindness).  These were chosen to avoid warning colors for color blindness as well, so colors that appear fine to normal vision don't appear alarming in others.
@lcrosenbu 
@jlcsmith 
@pklinef 
Make ten different searches and examine the colors.
Users had confusion around thinking certain colors meant the search had issues (red, orange).  This should remove confusion and provide a better color palette for colorblind users.
[DDF-3643](https://codice.atlassian.net/browse/DDF-3643) …
=> DDF-3643 Updates search color palette

catalog/resourcemanagement/resourcemanagement-querymonitor-ui/pom.xml, catalog/resourcemanagement/resourcemanagement-usage-ui/pom.xml, catalog/spatial/csw/spatial-csw-schema-bindings/pom.xml, catalog/spatial/geocoding/spatial-geocoding-admin-module/pom.xml, catalog/spatial/geowebcache/geowebcache-admin-plugin/pom.xml, catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-schema-bindings/pom.xml, catalog/transformer/catalog-transformer-xml-binding/pom.xml, platform/admin/modules/admin-security-ui/pom.xml, platform/osgi/platform-osgi-configadmin/pom.xml, pom.xml
Upgrades the following plugins
* maven-surefire-plugin
* maven-failsafe-plugin
* maven-compiler-plugin
* maven-jar-plugin
* build-helper-maven-plugin
* maven-jaxb2-plugin
* maven-javadoc-plugin
* fmt-maven-plugin
* maven-project-info-reports-plugin
* maven-checkstyle-plugin
Removes the following plugins from pluginManagement
* maven-deploy-plugin
* maven-clean-plugin
* maven-install-plugin
* cobertura-maven-plugin
Additional
* removes maven-antrun-plugin usages
* removes old/unnecessary gem-maven-plugin usages
@codice/build 
@shaundmorris @clockard 
Run a full build
[DDF-3677](https://codice.atlassian.net/browse/DDF-3677) …
=> DDF-3677 Upgraded several maven plugins

ui/packages/ui/src/main/webapp/js/views/installer/Certificate.view.js
Fixes typo in the keystore description during installation.
@brjeter 
@blen-desta 
@idperez 
@coyotesqrl 
@bakejeyner 
UI
@shaundmorris
Unzip new dib and on the System Configuration Settings installation page, the Add Keystore description should be updated to "... system's private key ..." in order to use the possessive form instead of the plural form of the word systems.
https://codice.atlassian.net/browse/DDF-3680
- ✏️ …
=> DDF-3680 Missing apostrophe in the Add KeyStore description

catalog/transformer/catalog-transformer-csv/src/main/java/ddf/catalog/transformer/csv/CsvQueryResponseTransformer.java, catalog/transformer/catalog-transformer-csv/src/test/java/ddf/catalog/transformer/csv/CsvQueryResponseTransformerTest.java
Currently from the UI, if a user select a list of items and chooses the "export visible" only option, those attributes along with a whole series of other attributes were added to the output CSV. 
This PR ensures that only the selected attributes from the UI will appear in the output CSV and updates a unit test to reflect this logic adjustment accordingly. 
This is the desired outcome as the UI will only populate columns where data exists and is not null, therefore, the output CSV will not be populated with a series of empty columns with no data. 
@Bdthomson  …
=> DDF-3655 Ensuring Backend Exports Only Visibly Selected Attributes

distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestSecurity.java
Remove unnecessary itest.
@vinamartin @mcalcote @shaundmorris @rzwiefel @garrettfreibott 
@clockard
@rzwiefel
@shaundmorris
CI build with tests.
The CertificateGenerator is created by blueprint in one thread, In this thread, the CertificateGenerator is being registered with the MBean server. In another thread, the test is attempting to use the CertificateGenerator. The CertificateGenerator is not being registered fast enough and the Jolokia call return null.
The unit test coverage is solid. The only thing the itest really does is to make sure that MBeans can be registered and exposed via JMX. Is that worth testing? No, because if that doesn’t it means the JVM itself is broken.
Conclusion: Remove unnecessary itest.
DDF-3687
- [ N/A] Documentation Updated
- [N/A ] Update / Add Unit Tests
- …
=> DDF-3687 Remove unnecessary itest

catalog/opensearch/catalog-opensearch-source/src/main/java/ddf/catalog/source/opensearch/impl/OpenSearchSource.java, catalog/opensearch/catalog-opensearch-source/src/test/java/ddf/catalog/source/opensearch/impl/OpenSearchSourceTest.java
Adds a check for if `transformerReference` is an empty collection before attempting to call `transformerReference.iterator().next()`. Otherwise, we can throw a `NoSuchElementException` if no service ref is found.
@troymohl @mojogitoverhere @brianfelix @adimka 
@bdeining
[DDF-3634](https://codice.atlassian.net/browse/DDF-3634) …
=> DDF-3634 Added empty collection check before access in OpenSearchSource

ui/lerna.json, ui/pom.xml
The `--no-optional` flag seems not to work for everyone as it's causing
build failures. Switching to `--ignore-optional` seems to have a higer
success rate.
@oconnormi 
@adimka 
@codice/build 
@codice/ui 
@pklinef
`rm -rf ui/{node,node_modules} && cd ui/ && mvn clean install`
We need two people to build this PR. One who has had no issues building with the old flag and one who has.
[DDF-3584](https://codice.atlassian.net/browse/DDF-3584) …
=> DDF-3584 Updates yarn install command

catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/data/impl/MetacardTypeImpl.java, catalog/transformer/catalog-transformer-streaming-lib/src/main/java/org/codice/ddf/transformer/xml/streaming/lib/SaxEventHandlerDelegate.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/notes/NoteAttributes.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/workspace/ListMetacardTypeImpl.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/workspace/QueryMetacardTypeImpl.java
Fix conflicting attribute descriptor definitions. 
Also adds a check that will log a warning every time a MetacardType is created that has conflicting definitions to help prevent new redefinitions.
@emmberk @peterhuffer @kcover 
@figliold
@rzwiefel
Install DDF and go to Intrigue. 
Verify there are no warnings in the log for `Conflicting attribute definitions`
[DDF-3674](https://codice.atlassian.net/browse/DDF-3674)
=> DDF-3674 Fix conflicting attribute descriptor definitions

Jenkinsfile
Remove 1 thread/CPU on full builds only which haven't been able to pass. These can run slower to get to full analysis.
@oconnormi @LinkMJB @mcalcote @mackncheesiest 
@codice/build 
@clockard
@lessarderic 
Only affects full builds and this is attempt to improve it.
[DDF-2971](https://codice.atlassian.net/browse/DDF-2971) …
=> DDF-2971 removed 1 thread/CPU from full build

ui/packages/catalog-ui-search/src/main/webapp/component/visualization-selector/visualization-selector.hbs, ui/packages/catalog-ui-search/src/main/webapp/component/visualization-selector/visualization-selector.less, ui/packages/catalog-ui-search/src/main/webapp/styles/mixins.less
Adjusts the "Add Visual" menu to provide a consistent feel.
@mackncheesiest @Variadicism @lcrosenbu 
@bdeining
Full build, manually verify menu functionality for adding visuals as well as improved aesthetics.
[DDF-3666](https://codice.atlassian.net/browse/DDF-3666)
Old Menu:
New Menu:
=> DDF-3666 Add consistent size and alignment to 'Add Visual' menu

catalog/core/catalog-core-commands/pom.xml, platform/admin/core/admin-core-appservice/pom.xml, platform/error/platform-error-servlet/pom.xml
The karaf-services-maven-plugin takes much longer to generate the karaf command manifest info than the maven-bundle-plugin does. This causes bottlenecks in certain points in our build process.
@paouelle 
@emanns95 
@figliold
@rzwiefel
Ensure the karaf commands in catalog-core-commands and admin-core-appservice still work …
=> DDF-3685: Use maven-bundle-plugin instead of karaf-services-maven-plugin for karaf commands

platform/security/common/src/main/resources/templates/submitFormTemplate.html, platform/security/idp/security-idp-client/src/main/resources/post-binding.html, platform/security/idp/security-idp-client/src/main/resources/templates/submitForm.handlebars, platform/security/idp/security-idp-server/src/main/resources/templates/submitForm.handlebars, platform/solr/platform-solr-server-standalone/src/main/webapp/tpl/documents.html, ui/packages/security-idp-server/src/main/resources/templates/submitForm.handlebars
Changes SAML redirect form submission from "post" to "POST" as stated by section 3.5.4 of the SAML Binding spec:
`The action attribute of the form MUST be the recipient's HTTP endpoint for the protocol or profile using this binding to which the SAML message is to be delivered. The method attribute MUST be "POST".`
@blen-desta 
@brjeter 
@djblue 
@clockard 
@coyotesqrl 
Sign in to DDF.
[DDF-3701](https://codice.atlassian.net/browse/DDF-3701) …
=> DDF-3701 Change SAML redirect form submission from "post" to "POST"

distribution/ddf-common/src/main/resources/bin/setenv-windows-wrapper.conf, distribution/ddf-common/src/main/resources/bin/setenv-wrapper.conf, distribution/ddf-common/src/main/resources/etc/org.apache.karaf.command.acl.wrapper.cfg, distribution/ddf-common/src/main/resources/security/default.policy
Adds permissions necessary to run the profile:install and wrapper:install commands, adds a Karaf ACL so that only admin users can run wrapper:install, and fixes the default service wrapper configuration.
@bakejeyner @blen-desta @brjeter @idperez 
@coyotesqrl
@stustison
[DDF-3697](https://codice.atlassian.net/browse/DDF-3697)
- ❓ …
=> DDF-3697 Add security manager exceptions for profile:install & wrapper:install commands

ui/packages/ace/handlebars/index.js, ui/packages/ace/handlebars/runtime.js, ui/packages/ace/lib/webpack.config.js, ui/packages/ace/package.json, ui/packages/catalog-ui-search/package.json, ui/packages/catalog-ui-search/src/main/webapp/js/ApplicationSetup.js, ui/packages/catalog-ui-search/src/main/webapp/js/HandlebarsHelpers.js
Ace has a dependency on handlebars at build time to compile templates
while catalog-ui-search has one at runtime. If they don't resolve the
exact same version of handlebars, it can cause issues with missing
helpers at runtime. This can be fixed by ace exposing its version so
`catalog-ui-search` can use it directly.
@adimka 
@glenhein 
@codice/ui 
@bdeining
- `mvn clean install` ui directory
- ensure no ui regressions in `/search/catalog` …
=> DDF-3719 Explicitly shares handlebars dependency

ui/packages/catalog-ui-search/src/main/webapp/component/filter/filter.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/filter/search-form/filter.search-form.view.js
Implements the default values for templates on the UI
@Schachte @adimka 
@bdeining
@jlcsmith
Reinstall DDF instance.  
Prior to initial startup add the etc/forms directory to the DDF instance
Edit the XML files to include a default value
Default values are loaded into the first Literal Tag after the function Tag.  Ex:
<fes:Function name="template.value.v1">
<fes:Literal>Connexta</fes:Literal> (DefaultValue)
Start DDF
Open the template that was modified to include a default
Verify default value is displayed in the valid fields
https://codice.atlassian.net/browse/DDF-3702 …
=> DDF 3702 - Pre-populated Query Templates in the UI

ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/cesium/map.cesium.js, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/openlayers/map.openlayers.js, ui/packages/catalog-ui-search/src/main/webapp/js/widgets/cesium.bbox.js, ui/packages/catalog-ui-search/src/main/webapp/js/widgets/cesium.circle.js, ui/packages/catalog-ui-search/src/main/webapp/js/widgets/cesium.line.js, ui/packages/catalog-ui-search/src/main/webapp/js/widgets/cesium.polygon.js, ui/packages/catalog-ui-search/src/main/webapp/js/widgets/drawing.controller.js, ui/packages/catalog-ui-search/src/main/webapp/js/widgets/openlayers.bbox.js, ui/packages/catalog-ui-search/src/main/webapp/js/widgets/openlayers.circle.js, ui/packages/catalog-ui-search/src/main/webapp/js/widgets/openlayers.line.js, ui/packages/catalog-ui-search/src/main/webapp/js/widgets/openlayers.polygon.js
- Updates the map views to properly clean up their drawing tools when destroyed.
- Starts the process of pulling out common drawing tool functionality, starting with the controllers.  Now there is a base drawing controller that each can extend as necessary.
@adimka 
@jlcsmith
@rzwiefel 
Test out each of the drawing methods and verify they work as expected.  Make sure to have both types of map open (2d and 3d), and test closing each and reopening each and then drawing with each type.  Verify no errors are thrown.
It looks like this started being an issue when we updated cesium to destroy itself properly, but regardless both maps should be disposing of their drawing tools when they get destroyed.
[DDF-3715](https://codice.atlassian.net/browse/DDF-3715)
=> DDF-3715 Updates map views to properly clean up their drawing tools when destroyed, refactors the drawing tools by pulling out common methods

libs/spock-shaded/pom.xml, libs/spock-shaded/src/main/groovy/org/codice/spock/extension/Supplemental.groovy, libs/spock-shaded/src/main/groovy/org/codice/spock/extension/builtin/ClearInterruptions.groovy, libs/spock-shaded/src/main/groovy/org/codice/spock/extension/builtin/ClearInterruptionsExtension.groovy, libs/spock-shaded/src/main/groovy/org/codice/spock/extension/builtin/SupplementalExtension.groovy, libs/spock-shaded/src/main/java/org/codice/spock/extension/DeFinalize.java, libs/spock-shaded/src/main/java/org/codice/spock/extension/DeFinalizeWith.java, libs/spock-shaded/src/main/java/org/codice/spock/extension/builtin/DeFinalizeClassLoader.java, libs/spock-shaded/src/main/java/org/codice/spock/extension/builtin/DeFinalizeSputnik.java, libs/spock-shaded/src/main/java/org/codice/spock/extension/builtin/DeFinalizer.java
- Upgrades Spock to the latest version.
- Fixes the spock-shaded project which not properly shading cglib-nodep, objenesis, and groovy-all
- Adds an extension to Spock's test runner that can properly definalize 3rd party classes to allow mocking them. This new test runner works much like the Kotlin test runner without the quirks
- Adds a Spock extension capable of clearing any left over interruptions on the test thread after a test case
- Adds a Spock extension which supplements some classes with new methods to simplify building test cases
@jhunzik 
@emanns95 
@figliold 
@coyotesqrl
@rzwiefel …
=> DDF-3621 Upgraded and added new extensions to Spock

ui/packages/catalog-ui-search/src/main/webapp/component/filter/filter.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/filter/search-form/filter.search-form.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/query-add/query-add.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/query-advanced/query-custom/query-custom.hbs, ui/packages/catalog-ui-search/src/main/webapp/component/query-advanced/query-custom/query-custom.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/search-form-interactions/search-form-interactions.hbs, ui/packages/catalog-ui-search/src/main/webapp/component/search-form-interactions/search-form-interactions.less, ui/packages/catalog-ui-search/src/main/webapp/component/search-form-interactions/search-form-interactions.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/search-form/search-form.collection.js, ui/packages/catalog-ui-search/src/main/webapp/js/model/QuerySettings.js
This tickets adds the preference options to the user to save default query templates when a new search is performed. 
The user is able to do the following:
- Save custom query templates as default templates
- Clear custom query templates
- Persists into user settings
@adimka 
@bdeining  
@bdeining
- Load different templates and ensure saving will load the saved template when a new query is performed.
- Likewise, ensure that clearing the saved template doesn't always load the saved template when a new query is performed
- Also ensure the buttons toggle …
=> DDF-3678 Enable Functionality for Saving Default Query Templates

ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/cesium/map.cesium.js
- The previous method did not work in IE11.
- Based on https://groups.google.com/forum/#!topic/cesium-dev/p-Rcg0JeH7Y it would
appear using pickEllipsoid is better and will result in more accurate
positions.
@jlcsmith
@adimka 
Verify that coordinates are displayed when mousing over the map in IE11.
[DDF-3748](https://codice.atlassian.net/browse/DDF-3748)
=> DDF-3748 Updates how cesium coordinates are retrieved

ui/packages/ui/src/main/webapp/components/configuration-item/configuration-item.hbs, ui/packages/ui/src/main/webapp/components/configuration-item/configuration-item.view.js, ui/packages/ui/src/main/webapp/components/service-item/service-item.hbs, ui/packages/ui/src/main/webapp/components/service-item/service-item.view.js
Fixes an issue where configuration edit modals could display in the wrong tab after clicking between them, causing the UI to become unusable until a user refreshes. 
Notes on how to reproduce this issue here: https://codice.atlassian.net/browse/DDF-3758
@djblue 
@adimka 
@rzwiefel
For factory and non-factory configurations: 
1. Open any application's menu.
2. Navigate to that app's Configuration tab.
3. Choose (don't click, just make a mental note) any name from the list.
4. Click the System tab.
5. Click the name you chose on this tab.
6. Observe the modal pops up and is editable and able to be saved. 
[DDF-3758](https://codice.atlassian.net/browse/DDF-3758)
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidel …
=> DDF-3758 Prevents configuration edit modals from displaying in the wrong tab

ui/packages/catalog-ui-search/package.json, ui/packages/cesium-assets/package.json, ui/yarn.lock
- Cesium was having issues maintaining the correct coordinate frame of reference during certain zooms, particularly when the user zoomed too far out.  It appears to be fixed in the latest version.
@jlcsmith 
@djblue 
@Variadicism 
@bdeining 
Before using the version with upgraded cesium, verify that on the old cesium zooming far out will cause results to become unclickable.  Then use the upgraded cesium and verify that this behavior disappears.
[DDF-3735](https://codice.atlassian.net/browse/DDF-3735)
=> DDF-3735 Upgrades Cesium to fix zoom issue

ui/packages/ace/lib/ls-packages.js
Sometimes when switching branches, the `ui/packages` directory can
contain empty directories which cause ace to fail. By not assuming that
all directories in `ui/packages` are valid packages (have a
`package.json`), we can prevent build failures.
@bdeining
- Ensure `ui/packages` contains an empty directory
- `mvn clean install` the ui directory …
=> DDF-3719 Updates ace to be more resilient

distribution/docs/src/main/resources/content/_endpoints/csw-endpoint.adoc
Automated line numbering can drift when lines are too long and text wrapping occurs. As a workaround these line numbers are being disabled for the time being. 
@clockard
@lessarderic
@rzwiefel
@shaundmorris
content review only  …
=> DDF-2824 removed line numbers from sample xml in docs

ui/packages/ace/bin.js, ui/packages/ace/lib/start.js, ui/packages/ace/lib/webpack.config.js, ui/packages/ace/package.json, ui/yarn.lock
- The websockets were failing in certain browsers (Firefox, Edge, not Chrome though) when auth wasn't passed.
@djblue 
@Variadicism 
Run the dev server and verify it defaults to admin:admin for the basic auth.  Verify you can also pass your own auth through the auth variable.
Looks like this issue was introduced when we upgraded to the latest webpack, so it's possible it's a bug in one of the newer versions of the webpack dev server or the http-proxy-middleware, etc.  Or they've simply updated how they expect it to be used.
[DDF-3743](https://codice.atlassian.net/browse/DDF-3743)
=> DDF-3743 Updates dev server to handle ws

platform/platform-configuration/src/main/java/org/codice/ddf/configuration/PlatformUiConfiguration.java, platform/platform-configuration/src/test/java/org/codice/ddf/configuration/PlatformUiConfigurationTest.java, ui/packages/catalog-ui-search/src/main/webapp/component/singletons/session-timeout.js
Fixes previous commit that incorrectly used properties.timeout which was a UI Connection Timeout for the UI session timeout logic. Now it correctly populates and uses the Platform UI Session Timeout property as intended. 
@adimka 
@bdeining 
@millerw8 
@stustison
1. Install DDF
2. Update the Platform UI timeout to 120000 (or something reasonable for testing) in
3. Navigate to /search/catalog
4. Wait for the amount of time specified in step 2
5. Verify that the popup for session timeout appears and session logs out if it's not continued. …
=> DDF-3529 Use Platform Config UI Timeout for UI session timeout

ui/packages/ace/lib/set-env.js, ui/packages/ace/lib/webpack.config.js
Disables the SimpleProgressWebpackPlugin when `webBuildEnv` is set to prod to reduce CI logging noise.
Also improves `set-env.js` so that it returns the exit code of the process that it invokes to fail faster in the build.
@Bdthomson @djblue @Schachte 
@andrewkfiedler @bdeining
Verify build and look at CI logs …
=> DDF-3719 Reduced CI logs & improved set-env.js

distribution/docs/src/main/resources/content/_configuring/search-options.adoc
Adds a section to the docs that explains how to disable searching for
historical and archived metacards, and searching of the local catalog.
@clockard
[DDF-3728](https://codice.atlassian.net/browse/DDF-3728) …
=> DDF-3728 Add search options configuration to docs

ui/packages/catalog-ui-search/src/main/webapp/component/filter-builder/filter-builder.less, ui/packages/catalog-ui-search/src/main/webapp/component/filter/filter.less
Updates the CSS used by `filter-builder` and `filter` to properly size the filter operation (i.e. `AND`, `OR`, `NOT AND`, `NOT OR`) and filter attribute (i.e. `anyText`, `anyGeo`, ...) buttons so that the text doesn't overflow the width of those components. 
@adimka @alexaabrd @djblue @Variadicism 
Verify that the CSS looks like how the screenshots look
[DDF-3786](https://codice.atlassian.net/browse/DDF-3786)
Before:
After: …
=> DDF-3786 Updated filter-builder.less & filter.less

distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestSecurity.java, platform/admin/core/admin-core-appservice/src/main/java/org/codice/ddf/admin/application/service/impl/ApplicationImpl.java, platform/admin/core/admin-core-appservice/src/main/java/org/codice/ddf/admin/application/service/impl/ApplicationServiceBean.java, platform/admin/core/admin-core-appservice/src/main/java/org/codice/ddf/admin/application/service/impl/ApplicationServiceImpl.java, platform/admin/core/admin-core-impl/src/main/java/org/codice/ddf/admin/core/impl/ConfigurationAdminImpl.java, ui/packages/ui/src/main/webapp/js/models/ApplicationsLayout.js
Admin UI operations have slowed down with the security manager due to permission checks related to different OSGi operations such as looking up the bundle location and getting metatype information.  Caching this information improves Admin UI responsiveness. 
@tbatie 
@vinamartin 
@coyotesqrl
@stustison
Verify the response type to show applications in the Admin UI drops from about 2 seconds to about half a second which is close to pre-security manager response times. …
=> DDF-3297 Admin UI permission check performance

catalog/core/catalog-core-directorymonitor/pom.xml, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/ContentDirectoryMonitor.java, catalog/core/catalog-core-directorymonitor/src/test/java/org/codice/ddf/catalog/content/monitor/AbstractComponentTest.java, catalog/core/catalog-core-directorymonitor/src/test/java/org/codice/ddf/catalog/content/monitor/ContentDirectoryMonitorIT.java, catalog/rest/catalog-rest-endpoint/pom.xml
Updated CDM component tests to use PortFinder class and re-enabled.
Also changed how the ContentDirectoryMonitor detroy() method cleaned
up routes.
@peterhuffer 
@tbatie 
https://github.com/orgs/codice/teams/test
@clockard
1. Configure multiple CDMs, shut down DDF, restart and make sure CDMs are still working as expected.
2. Configure multiple CDMs, delete one, shut down DDF, restart and make sure only the ones that were not deleted are still there and working as expected.
3. Run a full parallel build and make sure there are no port conflicts.
[DDF-3753](https://codice.atlassian.net/browse/DDF-3753) …
=> DDF-3753 Re-enable CDM component tests

features/apps/src/main/feature/feature.xml
Removes the dependency in `ddf-boot-features` on `admin-modules-installer` that was disallowing the uninstall of `admin-modules-installer`.
@tbatie @garrettfreibott 
@codice/ui 
@bdeining
Full build, run through installer, verify that installer module is uninstalled following reboot after install.
This was causing some inconsistent and funky install behavior, including directing the user to run the installer again following a successful install as the result of a race condition with the `post-install` module.
[DDF-3788](https://codice.atlassian.net/browse/DDF-3788)
- ✏️ (Pencil) …
=> DDF-3788 Allows Admin UI installer to uninstall

catalog/spatial/csw/spatial-csw-source-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/AbstractCswSource.java
Makes the `initClientFactory()` method of `AbstractCswSource` protected instead of private so child classes can override the CXF client factory creation.
Also fixes a type error in `initSubscribeClientFactory()` that was hidden because we weren't using the diamond operator when instantiating `SecureCxfClientFactory`.
@Bdthomson 
@glenhein 
@troymohl 
@codice/ogc 
@codice/io
@bdeining
@jlcsmith
Run a full build.
[DDF-3802](https://codice.atlassian.net/browse/DDF-3802) …
=> DDF-3802 Make AbstractCswSource CXF client factory overridable

ui/packages/catalog-ui-search/src/main/webapp/component/map-context-menu/map-context-menu.less, ui/packages/catalog-ui-search/src/main/webapp/component/map-context-menu/map-context-menu.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/map.model.js, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/openlayers/map.openlayers.js
- Updates openlayers to not show coordinates when off the main map.
- Updates map context menu to hide coordinate copying options when coordinates are not available.
@jlcsmith
@adimka 
Verify that the coordinate copy options aren't displayed when off the maps.  Verify that the coordinates are now hidden in openlayers when off the main map.  
[DDF-3752](https://codice.atlassian.net/browse/DDF-3752)
=> DDF-3752 Updates map-context-menu to not show coordinate options when off map, updates openlayers to not show coordinates when off map

platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/admin/ConfigurationAdminMigratable.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/admin/ExportMigrationConfigurationAdminContext.java, platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/admin/ConfigurationAdminMigratableTest.java
Fixes a race condition that occurs because the config admin migratable has a dependency on the persistence strategy services at init time. This problem surfaces now because of the platform-app split which requires the features to be completely independent from one another or at least to not require each other at initialization time.
@tbatie 
@oconnormi 
@emanns95 
@clockard
@figliold
- Unzip and install the distribution.
- Perform a migration export
- Unzip the distribution but do not install it
- Perform a migration import with the --profile option
- Verify the system is restored to …
=> DDF-3739 Removed the hard dependencies on persistence strategies at initialization time for the config admin migratable

ui/.gitignore, ui/packages.xml, ui/packages/catalog-ui-search/src/main/webapp/js/ApplicationSetup.js, ui/packages/codice-icons/package.json, ui/packages/codice-icons/webpack.config.js, ui/pom.xml
Updates the codice-webfonts package to better support downstream modifications of the `catalog-ui-search` package using the sources artifacts.
This PR:
- Adds the `codice-icons` files to our configuration in `ui/packages.xml` that is then used as [our maven-assembly-plugin](https://github.com/codice/ddf/blob/3d3703bab8972b41a9ace67658d96bc829777fa2/ui/pom.xml#L279-L282) configuration on what things to include for downstream modification and reuse.
- Changes the output directory of the finalized font from `target` to `icons` to avoid tricky issues with build tooling clearing `target` directories at inopportune times
- Removes the `ace package` build step for `codice-icons` since I don't believe we actually need the `codice-icons.jar` artifact when we bundle things with the …
=> DDF-3785 Improve codice-icons compatibility with downstream Intrigue modifications

distribution/docs/src/main/resources/content/_installing/installing-intro.adoc, distribution/docs/src/main/resources/content/_quickstart/quickstart-installing.adoc, features/apps/pom.xml, features/apps/src/main/feature/feature.xml, features/security/pom.xml, features/security/src/main/feature/feature.xml, platform/security/pom.xml, platform/security/secure-boot/pom.xml, platform/security/secure-boot/src/main/java/org/codice/ddf/security/boot/SecureBoot.java, platform/security/secure-boot/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/security/secure-boot/src/test/groovy/org/codice/ddf/security/boot/SecureBootSpec.groovy
Prevents users from running DDF under specific directories when security manager is enabled
@tbatie 
@emanns95 
@paouelle 
@clockard
@lessarderic 
1) Unzip DDF in your user.home directory and verify that it shutsdown automatically with an error message stating that DDF cannot be installed in user.home.
2) Unzip DDF in another directory outside of user.home, and verify that it starts up and runs with no problems.
https://codice.atlassian.net/browse/DDF-3798 …
=> DDF-3798: Users should be prevented from running DDF under specific when security manager is enabled

distribution/docs/pom.xml
Ensure that PDF generation only occurs when using the release profile. HTML docs will still be generated when building the docs module. 
@ahoffer @austinsteffes @sblackmore 
@codice/docs 
@clockard @ricklarsen @rzwiefel
`mvn clean install` in \distribution\docs to confirm HTML docs are still generated
`mvn clean install -P release` in \distribution\docs to confirm both HTML and PDF docs are generated 
This change reduced the standard build of the docs module by 3.5 minutes on my machine.
[DDF-3820](https://codice.atlassian.net/browse/DDF-3820) …
=> DDF-3820 Moved PDF generation to the release profile

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/forms/filter/FilterReader.java, platform/parser/api/src/main/java/org/codice/ddf/parser/Parser.java
Improves sanitation for filter 2.0 XML parsing. 
@adimka 
@bdeining 
@coyotesqrl
Drop templates in `etc/forms` and ensure they are usable. 
https://www.owasp.org/index.php/XML_External_Entity_(XXE)_Prevention_Cheat_Sheet#JAXB_Unmarshaller
[DDF-3720](https://codice.atlassian.net/browse/DDF-3720) …
=> DDF-3720 Improve XML parsing in FilterReader for templates

distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalog.java
Fixes unstable `testDefaultValuesCreate` iTest in `TestCatalog`.
@blen-desta 
@brjeter 
@clockard
@rzwiefel
Build and run the TestCatalog iTests: `mvn clean verify -D it.test=TestCatalog`, and verify that `testDefaultValuesCreate` passed.
[3824](https://codice.atlassian.net/browse/3824) …
=> Fix unstable testDefaultValuesCreate itest in TestCatalog

ui/packages/catalog-ui-search/src/main/webapp/js/model/MetacardAction.js
Removing the call to decode the url
Changing it to do a string replace 'decoding' of the {&queryId} template
This PR undoes the url decode of the urls returned by action providers.
@BernardIgiri @dcruver @GabrielFabian @mojogitoverhere @AzGoalie @rymach @djblue @andrewkfiedler 
@jlcsmith
@pklinef 
Using Intrigue, perform a search
Open Inspector for a selected result
Select Actions
Hover cursor over metacard actions or Right click -> Copy link address
Verify there is a query param for query id only for actions with the queryId parameter
Verify that the Overlay On the Map action does that (if …
=> DDF-3808 Appending queryId to the action provided urls

dependency-check-maven-config.xml
Suppress new OWASP Finding https://nvd.nist.gov/vuln/detail/CVE-2018-1270
DDF is not exposing STOMP over WebSocket endpoints, so CVE-2012-1270 is not a critical issue.
@austinsteffes @oconnormi @ahoffer 
@rzwiefel @stustison
OWASP build …
=> DDF-3695 Update OWASP findings in Query Monitor Commands

catalog/core/catalog-core-camelcomponent/src/main/java/ddf/camel/component/catalog/inputtransformer/InputTransformerProducer.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/DurableWebDavFileConsumer.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/synchronizations/FileDeletionSynchonization.java
For WebDav CDM, deletes the cached WebDav file after creates or updates.
Also resolves blocker Sonar findings from the original PR.
@roelens8 @emmberk @brendan-hofmann 
@clockard
@lessarderic 
- Setup a CDM to monitor a WebDav server.
- Drop files on the WebDav server for ingest.
- Verify no `dav*` files are in `<INSTALL_DIR>/data/tmp`
- Update the ingested file
- Verify no `dav*` files again.
An oversight in the original PR.
[DDF-3660](https://codice.atlassian.net/browse/DDF-3660) …
=> DDF-3660 [2.11.x] Fix cached WebDav files being left behind

ui/packages/ui/src/main/webapp/js/MetatypeRegistry.js, ui/packages/ui/src/main/webapp/js/ServiceFactoryNameRegistry.js, ui/packages/ui/src/main/webapp/js/models/Service.js
- Adds method to determine display name for a service based on its
fpid and properties.
- Updates the content directory monitor service to use monitored directory as its display
name.
@Lambeaux 
@pklinef
@clockard 
@tbatie 
Create a content directory monitor and verify that it uses the monitored directory as the name.
[DDF-3682](https://codice.atlassian.net/browse/DDF-3682)
=> DDF-3682 Updates display name for content directory monitors

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/config/ConfigurationApplication.java, catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.config.xml, ui/packages/catalog-ui-search/src/main/webapp/component/list-create/list-create.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/list-editor/list-editor.hbs, ui/packages/catalog-ui-search/src/main/webapp/component/list-editor/list-editor.less, ui/packages/catalog-ui-search/src/main/webapp/component/list-editor/list-editor.view.js, ui/packages/catalog-ui-search/src/main/webapp/js/properties.js
Update of https://github.com/codice/ddf/pull/2960 since it was way out of date.
- Allows the admin to specify commonly created lists for users to utilize.
@bdeining
@millerw8
@djblue 
Go to the admin UI and add a new template like:
`{"id":"Pizza Deliveries", "list.icon": "tasks", "list.cql": "(\"anyText\" ILIKE 'pizza')"}`
[3622](https://codice.atlassian.net/browse/DDF-3622)
=> DDF-3622 Adds admin config for list templates

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/config/ConfigurationApplication.java, catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.config.xml, catalog/ui/search-ui-app/src/main/resources/etc/org.codice.ddf.catalog.ui.config.config, ui/packages/catalog-ui-search/src/main/webapp/js/model/QueryResponse.js
DDF-3826 Added configuration option to turn on/off websockets in Intrigue
Adds configuration option to turn on/off websockets in Intrigue
@Bdthomson 
@glenhein 
@codice/ui 
@bdeining
Disable websockets in the admin UI and confirm that no websocket connections are attempted in Intrigue and that searches behave as expected. Reenable websockets in the admin UI and confirm that websocket connections are attempted in Intrigue and that searches behave as expected.
[DDF-3826](https://codice.atlassian.net/browse/DDF-3826)
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Reques …
=> DDF-3826 Added configuration option to turn on/off websockets in Intrigue

platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/server/IdpEndpoint.java, platform/security/idp/security-idp-server/src/test/groovy/org/codice/ddf/security/idp/server/IdpEndpointSpec.groovy
Fixes a SAML compliance issue where DDF is manually redirecting using javascript code instead of responding with an HTTP status code of 303 and putting the URL in the Location header.
From the SAML Bindings document:
>The SAML response is returned in the same fashion as described for the SAML request in step 2.
and
>The SAML request is returned encoded into the HTTP response's Location header, and the HTTP status MUST be either 303 or 302.
Note: 303 was chosen over 302 based on the definition for 303 according to the HTTP spec. See https://github.com/codice/ddf/pull/3084#issuecomment-377244473.
@blen-desta @bakejeyner 
(please choose ONLY two committers from …
=> DDF-3696 IdP logout does 303 redirect instead of manual javascript redirect

distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestSingleSignOn.java
Marks flaky tests as unstable. 
These three tests have been failing frequently on CI. 
@emanns95 
@emmberk 
@bakejeyner 
@blen-desta 
@coyotesqrl
@lessarderic
All itests pass
[DDF-3848](https://codice.atlassian.net/browse/DDF-3848) …
=> DDF-3848 Disable TestSingleSignOn unstable tests

catalog/ui/catalog-ui-search/src/main/webapp/component/input/date/input-date.view.js
[2.11.x] DDF-3831 Removes all key bindings from catalog search ui date time picker
Key bindings in Catalog Search UI date picker were causing issues with users, especially those who prefer to manually edit/input dates and times. For example, arrow keys could only be used to navigate the calendar, not the input field and pressing the ENTER or ESC key will hide the date picker but disable all key bindings in the process even upon the re-rendering of the date picker. 
The solution is to remove [all key bindings](https://eonasdan.github.io/bootstrap-datetimepicker/Options/#keybinds). Users would no longer be able to interact with the date picker calendar via keyboard but be able to manually edit/input dates and times. 
@emanns95 @vinamartin  
@tbatie @brendan-hofmann 
Check that the default …
=> [2.11.x] DDF-3831 Removes all key bindings from catalog search ui date time picker

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/cql/CqlRequest.java
This PR adds the notion of a QueryType to eventually be used to distinguish between Ad Hoc, Standing and Scheduled queries within the system.  This is added to the QueryRequest properties map.
@mackncheesiest @middlets719 
@rzwiefel
@jlcsmith 
Full Build / This property is not used anywhere currently
[DDF-3843](https://codice.atlassian.net/browse/DDF-3843) …
=> DDF-3843 Added queryType to CqlRequests

catalog/opensearch/catalog-opensearch-source/src/main/java/org/codice/ddf/opensearch/source/OpenSearchParserImpl.java, catalog/opensearch/catalog-opensearch-source/src/test/java/org/codice/ddf/opensearch/source/OpenSearchParserImplTest.java
When Geometry object is encountered. Construct a WKT geometry parameters for web client.
@millerw8 
@bdeining 
@bdeining
@jlcsmith
@millerw8
Ingest any record with a geolocation information
Using curl or postman to query using geometry search argument based on Open Search extension Geo Draft 2.0
http://www.opensearch.org/Specifications/OpenSearch/Extensions/Geo/1.0/Draft_2#The_.22geometry.22_parameter
Example:
https://localhost:8993/services/catalog/query?q=*&geometry=POLYGON((15%2011%2C15%2045%2C-20%2038%2C-15%20-20%2C15%2011)) …
=> DDF-3836 OpenSearch source to support Geometry search criteria.

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/history/Historian.java, catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/history/HistorianTest.java
There was a possibility previously that we would version the wrong metacard
when versioning a product overwrite. However it did not appear to impact us
because when quering for the already updated metacard we got returned a
cached version that hid the issue. Now we are using the already included
metacard (in the updateRequest) which we should have been doing all along.
`@anyone`
overwrite a product/resource in intrigue and ensure the correct metadata is stored in the revision that is created of the original metacard.
https://codice.atlassian.net/browse/DDF-3844 …
=> DDF-3844 Fixes Product overwrite versioning bug

catalog/spatial/geocoding/spatial-geocoding-api/src/main/java/org/codice/ddf/spatial/geocoding/GeoEntryQueryable.java, catalog/spatial/geocoding/spatial-geocoding-geocoder/src/main/java/org/codice/ddf/spatial/geocoder/GazetteerGeoCoder.java, catalog/spatial/geocoding/spatial-geocoding-geocoder/src/test/java/org/codice/ddf/spatial/geocoder/GazetteerGeoCoderTest.java
GeoEntryQueryable getCountryCode javadoc update to match functionality of returning iso3 country code
Update usage in GazetteerGeoCoder getCountryCode method to return ISO3 without attempting convert
@millerw8 
@bdeining 
@bdeining
@jlcsmith
@millerw8
Upload any geotagged image or one provided below
Query for the image, use inspector view to verify location.country-code is populated with the correct iso3 character country code (USA for the image provided) …
=> DDF-3825 GeoCoder preingest plugin country code derivation

ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-old.view.js, ui/packages/catalog-ui-search/src/main/webapp/js/CQLUtils.js
Remove "smart" rescaling of units from Point Radius and Line. No conversion is executed when switching between unit
Don’t want to convert in units. If user types 1000 with meter selected, then select unit then they want 1000 NM, not 1000 meters converted to NM
@BernardIgiri 
@AzGoalie 
@bdeining   
@millerw8  
Open a basic search diaglog
Located -> Some where specific -> Point Radius
Enter a value, change unit. The value shouldn't be converted
https://codice.atlassian.net/browse/DDF-3710
https://jira.di2e.net/browse/GSR-1661 …
=> DDF-3710 remove smart unit conversion for line and radius point search

catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-common/src/main/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/common/Wfs20Constants.java, catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/source/reader/FeatureCollectionMessageBodyReaderWfs20.java
Fix bug in WFS20 where no results were returned. The WFS20 source wasn't expecting the mime type "application/gml+xml"
@Bdthomson 
@bdeining 
@jlcsmith 
- build and install 
- [download GeoServer](http://geoserver.org/release/stable/) and run the installer
- run the Start GeoServer desktop app
- configure WFS20 source
- execute a wild card query from the UI
- verify 825 results
[DDF-3865](https://codice.atlassian.net/browse/DDF-3865) …
=> DDF-3865 Fix bug in WFS20 where no results were returned

distribution/ddf-common/src/main/resources/security/default.policy, features/kernel/src/main/feature/feature.xml, platform/security/policy/security-policy-context/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/security/policy/security-policy-context/src/main/resources/OSGI-INF/metatype/metatype.xml, pom.xml
Adds the health and readiness endpoints from fabric8 to the ddf boot features
* supports more intelligent load balancing via health monitoring
* supports readiness checks that help determine when it is ok to interact with the system
* extensible to support additional health and readiness checks if needed
Not sure if the way I'm adding it is the best way to do this, open to suggestions.
@tbatie @Lambeaux 
@lessarderic @pklinef 
* Start the system, 
ping https://localhost:8993/readiness-check and https://localhost:8993/health-check until they return `200`
https://fabric8.io/guide/karaf.html#fabric8-karaf-health-checks
[DDF-3763](https://codice.atlassian.net/browse/DDF-3763)
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guideline …
=> DDF-3763 Added fabric-karaf-checks to boot features

platform/security/core/security-core-impl/src/main/java/ddf/security/samlp/impl/LogoutMessageImpl.java, platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/server/IdpEndpoint.java, platform/security/platform-security-core-api/src/main/java/ddf/security/samlp/LogoutMessage.java, platform/security/platform-security-core-api/src/main/java/ddf/security/samlp/SamlProtocol.java
- Allows sending multiple status codes in saml logout response
- Added the NotOnOrAfter attribute on LogoutRequests
@clockard 
@coyotesqrl 
@stustison
- Able to log in and log out of DDF correctly
- Use the SAML Conformance Test Kit for further testing
Core 3.2.2. explains why we can't just return a partial status code. We have to return success with partial as a secondary status code.
```
The value of the topmost <StatusCode> element MUST be from the top-level list provided 
in this section.
```
Core 3.7.3.2 explains why we need to return a `NotOnOeAfter` attribute.
```
When constructing a logout request message, the session authority MUST set the value of 
the NotOnOrAfter attribute of the message to a …
```
=> DDF-3696 Allows sending multiple status codes in saml logout response

features/kernel/src/main/feature/feature.xml
After #3155 was merged some inconsistencies were soon during startup of the system. This change will leave the `fabric8-karaf-features` repo in ddf but will remove the `fabric8-karaf-checks` feature from the boot features. The feature can be turned on manually in the future until the underlying issue is found
@peterhuffer @roelens8 
@coyotesqrl @clockard 
Verify that things are back to normal after starting up the system. Check Intrigue and ingest through Intrigue
[DDF-3763](https://codice.atlassian.net/browse/DDF-3763) …
=> DDF-3763 removed fabric8-karaf-checks from default boot features

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/forms/SearchFormsApplication.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/forms/TemplateTransformer.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/forms/model/pojo/CommonTemplate.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/forms/model/pojo/FieldFilter.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/forms/model/pojo/FormTemplate.java, catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/blueprint/blueprint.xml, ui/packages/catalog-ui-search/src/main/webapp/component/query-add/query-add.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/query-editor/query-editor.less, ui/packages/catalog-ui-search/src/main/webapp/component/query-template-sharing/query-template-sharing.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/result-form/result-form.collection.js, ui/packages/catalog-ui-search/src/main/webapp/component/result-form/result-form.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/result-form/result-forms.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/search-form-interactions/search-form-interactions.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/search-form/forms-sharing/search-form-sharing-tab-container.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/search-form/forms-sharing/search-form-sharing.collection.js, ui/packages/catalog-ui-search/src/main/webapp/component/search-form/forms-sharing/search-form-sharing.collection.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/search-form/search-form.collection.js, ui/packages/catalog-ui-search/src/main/webapp/component/search-form/search-form.collection.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/search-form/search-form.js, ui/packages/catalog-ui-search/src/main/webapp/component/search-form/search-form.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/search-interactions/search-interactions.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/tabs/search-form/tabs.search-form.js
Enables sharing on result-set templates:
- Populate shared result-set templates onto users search form in the result-set linker dropdown
- Enable ability to share custom result-set templates from new tab view to other:
- users
- groups
@middlets719 
@bdeining 
@bdeining 
@millerw8 
- Quickbuild after pulling down PR
- Unzip distributon and navigate to `/etc` directory `/ddf/distribution/ddf/target/ddf-2.12.0-SNAPSHOT/etc`
- Also ensure that some forms are loaded in the `forms directory`
- Modify the `user.properties` file to have the following contents:
```
admin=admin,group,admin,manager,viewer,system-admin,systembundles …
```
=> DDF-3784 Enabling Sharing on Result-Set Templates on UI & Backend

catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/ContentDirectoryMonitor.java, catalog/spatial/csw/spatial-csw-source-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/AbstractCswSource.java, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsSource.java, catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/source/WfsSource.java
Reverts a recent change to destroy method in AbstractCswSource and adds suppression in other areas.
@vinamartin @emmberk 
@coyotesqrl
@stustison
See https://issues.apache.org/jira/browse/ARIES-1436. Bug fixed in 1.2.0, DDF is on 1.1.0. This causes the destroy method to not be called.
[DDF-3817](https://codice.atlassian.net/browse/DDF-3817) …
=> DDF-3817 Revert destroy argument

catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/ContentDirectoryMonitor.java, catalog/spatial/csw/spatial-csw-source-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/AbstractCswSource.java, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsSource.java, catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/source/WfsSource.java
Reverts a recent change to destroy method in AbstractCswSource and adds suppression in other areas.
@vinamartin @emmberk
@coyotesqrl
@stustison
See https://issues.apache.org/jira/browse/ARIES-1436. Bug fixed in 1.2.0, DDF is on 1.1.0. This causes the destroy method to not be called.
[DDF-3817](https://codice.atlassian.net/browse/DDF-3817) …
=> DDF-3817 [2.12.x] Revert destroy argument in AbstractCswSource

distribution/ddf-common/src/main/resources/security/default.policy
Adds recursive ws-security permission to source poller and jolokia.
@SmithJosh 
@peterhuffer 
@oconnormi 
@coyotesqrl
@stustison
[DDF-3866](https://codice.atlassian.net/browse/DDF-3866) …
=> DDF-3866 Added ws-security for poller and jolokia to default policy

catalog/opensearch/catalog-opensearch-source/src/main/resources/OSGI-INF/metatype/metatype.xml, distribution/docs/src/main/resources/content/_tables/Csw_Federated_Source.adoc, distribution/docs/src/main/resources/content/_tables/Csw_Federation_Profile_Source.adoc
Fixes a typo from https://github.com/codice/ddf/commit/51bd06b1e7b4b8113722c08d5ff3759870b40dd5
Root context was never meant to be an external property. 
@Bdthomson @emanns95 
@rzwiefel …
=> DDF-3817 Fixes typo in metatypes and documentation

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/CreateOperations.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/OverrideAttributesSupport.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/UpdateOperations.java, catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/impl/CatalogFrameworkImplTest.java, catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/impl/operations/OverrideAttributesSupportTest.java, catalog/rest/catalog-rest-endpoint/src/main/java/org/codice/ddf/endpoints/rest/RESTEndpoint.java, catalog/rest/catalog-rest-endpoint/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/rest/catalog-rest-endpoint/src/test/java/org/codice/ddf/endpoints/rest/RestEndpointIT.java, catalog/rest/catalog-rest-endpoint/src/test/java/org/codice/ddf/endpoints/rest/RestEndpointTest.java
Updates the rest endpoint and the catalog standard framework to respect attribute/metacard overrides
@emmberk @peterhuffer @glenhein 
@lessarderic
@rzwiefel
Ingest a metacard with an id via the rest endpoint and verify it has the same id after ingest.
Ingest a metacard with id and product together and verify the metacard has the same id after ingest
To test general attribute override run the command `curl -k -X POST -i -H "Content-Type: multipart/mixed" -F parse.resource=@/path/to/txt/file -F parse.media.duration=5.0 https://localhost:8993/services/catalog` and verify that the ingested text file has the media.duration attribute set.
[DDF-3863](https://codice.atlassian.net/browse/DDF-3863)
=> DDF-3863 Update RESTEndpoint respect attribute/metacard overrides

catalog/opensearch/catalog-opensearch-source/src/main/resources/OSGI-INF/metatype/metatype.xml, distribution/docs/src/main/resources/content/_tables/Csw_Federated_Source.adoc, distribution/docs/src/main/resources/content/_tables/Csw_Federation_Profile_Source.adoc
Port of https://github.com/codice/ddf/pull/3316
@clockard @brendan-hofmann
=> [2.12.x] DDF-3817 Fixes typo in metatypes and documentation

platform/security/platform-security-core-api/pom.xml, platform/security/platform-security-core-api/src/main/java/ddf/security/samlp/MetadataConfigurationParser.java
This moves the code that reads local files for IdP metadata into privileged blocks. During testing of the fabric8 feature that was added (but is currently not enabled) in DDF-3763, it was discovered that its bundle required permissions to read the metadata as it attempted to connect. As there is nothing confidential in the IdP metadata, it is safe to privilege the calls to read the file within the `MetadataConfigurationParser` so permission checks won't go up the chain from there.
This is not a high-priority change and is not targeting 2.12.0.
@peterhuffer @oconnormi @brjeter 
@rzwiefel
@stustison
A full install and …
=> DDF-3763 Moving SAML metadata reads into privileged blocks.

platform/osgi/platform-osgi-condpermadmin/pom.xml, platform/osgi/platform-osgi-condpermadmin/src/main/java/org/codice/ddf/condpermadmin/PermissionActivator.java, platform/osgi/platform-osgi-condpermadmin/src/test/java/org/codice/ddf/condpermadmin/PermissionActivatorTest.java, platform/osgi/platform-osgi-condpermadmin/src/test/resources/badformat.policy
Prints the name of the failing policy file to the command line and executes a hard system exit.
This prevents the system from initializing in an unsecured state.
@brjeter @blen-desta 
@rzwiefel
@stustison
Edit any policy file in the `security` directory to make it badly formatted. Attempt to start the server. It should exit immediately, printing the name of the invalid file to the command line.
Will fail fast on the first badly formatted file it encounters.
[DDF-3884](https://codice.atlassian.net/browse/DDF-3884)
- …
=> DDF-3884 Terminates DDF if any security policy file is malformed.

catalog/core/catalog-core-camelcomponent/src/main/java/ddf/camel/component/catalog/inputtransformer/InputTransformerProducer.java
- Closes file handle that remained open in InputTransformerProducer.
- Adds a default mime type to InputTransformerProducer.
- Removes a suppression.
@brendan-hofmann @kcover @emanns95 
@clockard
@coyotesqrl
CDM Unit and Component tests, and TestCatalog itests on Windows.
Having this file handle open would cause a cached file, from monitoring a WebDav server, to fail to be deleted after the file had been ingested.
[DDF-3660](https://codice.atlassian.net/browse/DDF-3660)
- ✏️ (Pencil) This comment …
=> DDF-3660 [2.12.x] Properly close file handle in InputTransformerProducer

distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/AbstractIntegrationTest.java, distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/config/UrlResourceReaderConfigurator.java
Changes URLResourceReaderConfigurator to only update the root resource directory if it has changed to reduce the impact of waiting for the configuration changes to complete.
Also adds the Stopwatch JUnit Rule to the AbstractIntegrationTest class to log the time it takes to execute each test method.
@Lambeaux 
@paouelle  
https://github.com/orgs/codice/teams/test
@stustison
@figliold
Successful CI/CD and local builds, including downstream projects.
The following test performance improvements were observed when building on local laptop:
TestCatalog
- Original: 34:51 min
- With changes: 13:51 min
All itests
- Original: 01:16 h
- With …
=> DDF-3882 Integration Tests running slowly and timing out

platform/security/rest/security-rest-cxfwrapper/src/main/java/org/codice/ddf/cxf/paos/PaosInInterceptor.java, platform/security/rest/security-rest-cxfwrapper/src/test/java/org/codice/ddf/cxf/paos/PaosInInterceptorTest.java
Ensure that cxf receives all headers in the interceptor are a list of strings. 
Anyone
@clockard 
Ensure that an update over CSW (using IdP as auth method) still works correctly.
The translation of the headers from the rest client to the cxf interceptor requires a slightly different format. 
https://codice.atlassian.net/browse/DDF-3860 …
=> DDF-3860 Change header copying to ensure all lists are strings

distribution/docs/src/main/resources/content/_appReferences/mg-broker-app.adoc, distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/ServiceManagerImpl.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalogSearchUi.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFederation.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestMessageBroker.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestPlatform.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestSecurity.java, features/security/pom.xml, features/security/src/main/feature/feature.xml, platform/security/filter/pom.xml, platform/security/filter/security-filter-csrf/pom.xml, platform/security/filter/security-filter-csrf/src/main/java/org/codice/ddf/security/filter/csrf/CsrfFilter.java, platform/security/filter/security-filter-csrf/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/security/filter/security-filter-csrf/src/test/groovy/org/codice/ddf/security/filter/csrf/CsrfFilterSpec.groovy, ui/packages/admin-core-logviewer/src/main/webapp/js/backend/index.js, ui/packages/admin-core-logviewer/src/main/webapp/js/components/log-entry/log-entry.js, ui/packages/admin-core-logviewer/src/test/js/actions.js, ui/packages/admin-security-certificate-ui/src/main/webapp/main.js, ui/packages/broker-undelivered-messages-ui/src/main/webapp/index.js, ui/packages/catalog-admin-module-layout/src/main/webapp/default-layout/reducer.js, ui/packages/catalog-admin-module-layout/src/main/webapp/lib/react-mount/index.js, ui/packages/catalog-admin-module-maplayers/src/main/webapp/map-layers/index.js, ui/packages/catalog-admin-module-maplayers/src/main/webapp/map-layers/reducer.js, ui/packages/catalog-ui-search/src/main/webapp/js/ApplicationSetup.js, ui/packages/ui/src/main/webapp/main.js
Adds the header "X-Requested-With" as a required header on the backend so that all incoming requests to anything under `/admin/jolokia` or `/search/catalog/internal` must contain this header or a 403 will be returned. Value of this header can be anything, only it's presence is checked. The incoming request must also have either an origin or referer header that matches the target origin or a 403 will be returned. Also adds this header to any necessary UI packages.
@djblue 
@rzwiefel 
@tbatie 
@codice/ui 
@stustison
Make sure the admin UI and Intrigue still work. Watch network requests and make sure no 403s are returned. Try accessing jolokia & intrigue internal URLs directly and ensure that they cannot be accessed - a 403 should be returned. See below for …
=> DDF-3855: Add CSRF Protections to Jolokia and Intrigue Endpoints

catalog/common/catalog-common-geo-formatter/src/main/java/ddf/geo/formatter/CompositeGeometry.java, catalog/common/catalog-common-geo-formatter/src/main/java/ddf/geo/formatter/Polygon.java, catalog/opensearch/catalog-opensearch-api/src/main/java/org/codice/ddf/opensearch/source/BoundingBox.java, catalog/opensearch/catalog-opensearch-endpoint/src/main/java/org/codice/ddf/opensearch/endpoint/OpenSearchEndpoint.java, catalog/opensearch/catalog-opensearch-endpoint/src/test/java/org/codice/ddf/opensearch/endpoint/query/OpenSearchQueryTest.java, catalog/opensearch/catalog-opensearch-source/pom.xml, catalog/opensearch/catalog-opensearch-source/src/main/java/org/codice/ddf/opensearch/source/BoundingBoxUtils.java, catalog/opensearch/catalog-opensearch-source/src/main/java/org/codice/ddf/opensearch/source/OpenSearchFilterVisitor.java, catalog/opensearch/catalog-opensearch-source/src/main/java/org/codice/ddf/opensearch/source/OpenSearchParserImpl.java, catalog/opensearch/catalog-opensearch-source/src/main/java/org/codice/ddf/opensearch/source/OpenSearchSource.java, catalog/opensearch/catalog-opensearch-source/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/opensearch/catalog-opensearch-source/src/main/resources/OSGI-INF/metatype/metatype.xml, catalog/opensearch/catalog-opensearch-source/src/test/groovy/org/codice/ddf/opensearch/source/BoundingBoxUtilsSpec.groovy, catalog/opensearch/catalog-opensearch-source/src/test/groovy/org/codice/ddf/opensearch/source/OpenSearchSourceSpec.groovy, catalog/opensearch/catalog-opensearch-source/src/test/java/org/codice/ddf/opensearch/source/OpenSearchFilterVisitorTest.java, catalog/opensearch/catalog-opensearch-source/src/test/java/org/codice/ddf/opensearch/source/OpenSearchParserImplTest.java, catalog/opensearch/catalog-opensearch-source/src/test/java/org/codice/ddf/opensearch/source/OpenSearchSourceTest.java, distribution/docs/src/main/resources/content/_endpoints/opensearch-endpoint.adoc, distribution/docs/src/main/resources/content/_sources/opensearch-source.adoc, distribution/docs/src/main/resources/content/_tables/OpenSearchSource.adoc
OpenSearch capabilities (Search/Endpoint) to OpenSearch geo Draft 2 by allowing geometries instead of polygons
OpenSearch endpoints are both upgraded to accept geometries and polygons.
OpenSearch endpoint support multiple spatial criteria at the same time (geometry, polygon, bounding box, point radius).
OpenSearch Sources generate a GeometryCollection to put in the geometry field when user defines multiple geospatial criteria in the UI.
OpenSearch Sources generate a polygon to put in the geometry field when user defines a polygon geospatial criteria in the UI.
With convertToBoundingBox as false, if OpenSearch Source encounters multiple point radius search, an approximate polygon (square) is formulated and add to a geometry collection.
With convertToBoundingBox as true, if OpenSearch …
=> DDF-3836 Extend query abilities to support multiple geometries

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/OperationsMetacardSupport.java, catalog/core/catalog-core-standardframework/src/test/groovy/ddf/catalog/impl/operations/OperationsMetacardSupportSpec.groovy, catalog/plugin/catalog-plugin-checksum/pom.xml, catalog/plugin/catalog-plugin-checksum/src/main/java/org/codice/ddf/catalog/content/plugin/checksum/Checksum.java, catalog/plugin/catalog-plugin-checksum/src/test/java/org/codice/ddf/catalog/content/plugin/checksum/ChecksumTest.java
If an incoming content item is qualified (derived product), accept its metacard and don't generate a metacard for the qualified content item.
Update checksum plugin to ignore qualified (derived) content.
@roelens8 @emmberk @clockard
@coyotesqrl
@pklinef
Unit tests
The Chipping action provider in Alliance not generate actions since the original products metacard's type was modified to be the derived content's metacard type.
[DDF-3899](https://codice.atlassian.net/browse/DDF-3899) …
=> DDF-3889 Accept qualified content item's metacard

ui/packages/catalog-ui-search/src/main/webapp/component/system-usage/system-usage.view.js
Fixes `Uncaught TypeError: Cannot read property 'href' of null
at HTMLDocument.<anonymous> (system-usage.view.js:26)` that prevented System Usage Message from populating. 
@emanns95 @bantillo @djblue 
@tbatie 
Configure System Usage Message and confirm that it is populated on Intrigue.
Systme Usage Message did not populate on Intrigue.
[DDF-3885](https://codice.atlassian.net/browse/DDF-3885) …
=> DDF-3885 Fixes System Usage Message on Intrigue

ui/packages/catalog-ui-search/src/main/webapp/component/system-usage/system-usage.view.js
--
Backport of https://github.com/codice/ddf/pull/3324.
Fixes Uncaught TypeError: Cannot read property 'href' of null at HTMLDocument.<anonymous> (system-usage.view.js:26) that prevented System Usage Message from populating.
@bantillo @djblue @jhunzik @paouelle @figliold 
@tbatie 
Configure System Usage Message and confirm that it is populated on Intrigue.
System Usage Message did not populate on Intrigue.
[DDF-3885](https://codice.atlassian.net/browse/DDF-3885) …
=> DDF-3885 System Usage Message does not populate on Intrigue (#3324)

catalog/spatial/registry/registry-federation-admin-service-impl/src/main/java/org/codice/ddf/registry/federationadmin/service/impl/IdentityNodeInitialization.java, catalog/spatial/registry/registry-federation-admin-service-impl/src/test/java/org/codice/ddf/registry/federationadmin/service/impl/IdentityNodeInitializationTest.java
Fixes an issue where local identity node wasn't populated correctly when
using a custom sitename. This was likely introduced when changes were made
to security manager and the solr client causing bundles to start at different times. 
@peterhuffer @emmberk @JGatley 
@bdeining
@clockard
message me for details
[DDF-3900](https://codice.atlassian.net/browse/DDF-3900) …
=> DDF-3900 Fix registry local identity node population

ui/packages/ace/lib/webpack.config.js
Resolves ticket: DDF-3916
Updates the UI Dev Server's proxy configuration to be compatible with the recent CSRF changes.
@adimka 
@djblue 
@codice/ui 
@rzwiefel
Run the dev server with the CSRF Filter running (enabled by default) and ensure that no 403s are returned when requests to /search/catalog/internal are made.
The CSRF Filter enforces that requests to protected contexts that an Origin or Referer header that matches the hostname & port of the request's target.
[DDF-3855](https://codice.atlassian.net/browse/DDF-3855)
[DDF-3916](https://codice.atlassian.net/browse/DDF-3916)
- …
=> DDF-3855, DDF-3916: UI Dev Server Proxy CSRF Compatibility

distribution/ddf-common/src/main/resources-filtered/etc/system.properties, distribution/docs/src/main/resources/content/_plugins/security-logging-plugin.adoc, platform/security/platform-security-core-api/src/main/java/ddf/security/common/audit/SecurityLogger.java
Allows a user to define custom attributes in the system properties file to be logged by the security logger.
@bdeining @middlets719 @Schachte @mojogitoverhere @troymohl  
@millerw8
@stustison 
Add property to system properties under security.logger.extra_attributes, (ensure that the additional attribute can be accessed through the `Subject` object. "Clearance" for example), build DDF, check log for added attribute.
[DDF-3895](https://codice.atlassian.net/browse/DDF-3895)
For this screenshot, an additional attribute `CountryOfAffilitaion` was added to the Subject attributes. The log will look …
=> DDF-3895 modified SecurityLogger to allow for custom attributes

catalog/plugin/catalog-plugin-videothumbnail/pom.xml, catalog/plugin/catalog-plugin-videothumbnail/src/main/java/org/codice/ddf/catalog/content/plugin/video/VideoThumbnailPlugin.java, catalog/plugin/catalog-plugin-videothumbnail/src/test/java/org/codice/ddf/catalog/content/plugin/video/VideoThumbnailPluginTest.java
Renames ffmpeg binary Strings based on change in https://github.com/codice/thirdparty/pull/19
@blen-desta @brjeter @bakejeyner 
@stustison
Verify the unit/itests involving this bundle still function built on top of https://github.com/codice/thirdparty/pull/19
The upstream codice/thirdparty changes rename the ffmpeg binaries so that downstream projects that utilize dependency-check-maven have less false positive CVE detections. CVE detections increased in some cases after https://github.com/codice/thirdparty/pull/18 due to dependency-check-maven using filename as evidence for version …
=> DDF-3842 Renames ffmpeg binaries based on codice/thirdparty change

platform/admin/core/admin-core-appservice/src/main/java/org/codice/ddf/admin/application/service/impl/ApplicationServiceBean.java, platform/admin/core/admin-core-appservice/src/main/java/org/codice/ddf/admin/application/service/impl/ApplicationServiceBeanMBean.java, platform/admin/core/admin-core-appservice/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/admin/core/admin-core-appservice/src/test/java/org/codice/ddf/admin/application/service/impl/ApplicationServiceBeanTest.java, ui/packages/ui/src/main/webapp/js/models/Installer.js, ui/packages/ui/src/main/webapp/js/models/features/feature.js, ui/packages/ui/src/main/webapp/js/views/installer/Profile.view.js
Adds error logging for the Jolokia servlet. 
This addresses lack of logging when feature resolution has an error. 
@tbatie 
@stustison 
@lessarderic
Install DDF. Ensure everything works as expected for a correct case. 
Remove the `!com.sun.management` statement from the pom of `catalog-ui-search` and ensure that the install process fails with an exception in the backend error logs. The stacktrace returned by Jolokia to the frontend should be redacted (use network tab in Chrome dev tools). 
App decoupling has hid the Karaf features service from being exposed. Starting features is now done through Karaf's MBean directly, but it does not log the info we need, and this leaves no location in our code to catch exceptions that might occur. …
=> DDF-3636 Fix logging regression where no error is logged when features fail to start

ui/packages/catalog-ui-search/src/main/webapp/component/filter/filter.collection.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/filter/filter.hbs
Fixes Firefox bug observed when attempting to re-order (drag-and-drop) filters in search form
@Lambeaux 
@brianfelix 
@bdeining
https://codice.atlassian.net/browse/DDF-3918 …
=> DDF-3918: Allow search field ordering (dragging) in Firefox

platform/solr/solr-factory/src/main/java/org/codice/solr/factory/impl/ConfigurationFileProxy.java, platform/solr/solr-factory/src/main/java/org/codice/solr/factory/impl/EmbeddedSolrFiles.java
Adds @Deprecates to ConfigurationFileProxy and EmbeddedSolrFiles to account for deprecation of their usage based on solr.data.dir.
@mcalcote 
@ahoffer 
@coyotesqrl 
build ddf
[DDF-3930](https://codice.atlassian.net/browse/DDF-3930) …
=> DDF-3930 Deprecating ConfigurationFileProxy and EmbeddedSolrFiles

platform/security/cas/security-cas-client/src/main/java/org/codice/ddf/security/handler/cas/CasLogoutService.java, platform/security/cas/security-cas-client/src/main/resources/OSGI-INF/blueprint/casfilters.xml, platform/security/cas/security-cas-client/src/main/resources/OSGI-INF/metatype/metatype.xml
*  Sets the encodeServiceUrl to false because if true, the CAS client will include the user's session id in the service URL after authentication.
* updates the default configuration values to be more accurate
@vinamartin 
@SmithJosh 
@beyelerb
@stustison
[DDF-3921](https://codice.atlassian.net/browse/DDF-3921)
- ✏️ (Pencil) This comment is a nitpick or style suggestion, …
=> DDF-3921 Minor CAS updates

platform/security/idp/security-idp-client/src/main/java/org/codice/ddf/security/idp/client/AssertionConsumerService.java, platform/security/platform-security-core-api/src/main/java/ddf/security/samlp/SamlProtocol.java, platform/security/platform-security-core-api/src/test/java/ddf/security/samlp/SamlProtocolTest.java
Adds all supported NameIdFormats to the SP metadata so it is clear which formats we do and do not support.
@bakejeyner @vinamartin @alexaabrd 
@stustison
Verify that the SP metadata contains the three supported NameIdFormats:
```
urn:oasis:names:tc:SAML:2.0:nameid-format:persistent
urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified
urn:oasis:names:tc:SAML:1.1:nameid-format:X509SubjectName
```
The SP metadata can be found at https://localhost:8993/services/saml/sso/metadata
CAS 5 can be used as an IdP, but fails authentication if the requested NameIdFormat is not listed as supported by the SP. Being more explicit about the formats we support will increase interoperability with external …
=> DDF-3946 Add supported NameIdFormats to SP metadata

ui/packages/catalog-ui-search/src/main/webapp/js/widgets/cesium.circle.js, ui/packages/catalog-ui-search/src/main/webapp/js/widgets/cesium.line.js, ui/packages/catalog-ui-search/src/main/webapp/js/widgets/openlayers.circle.js, ui/packages/catalog-ui-search/src/main/webapp/js/widgets/openlayers.line.js
- Previously everything in the location model got normalized to meters, but that is no longer the case.  As such the drawing tools needed to be updated to convert things to meters when using the model value, and to convert to the proper units when updating the model value.
@bdeining
@millerw8 
@djblue 
Open both the 2d and 3d map side by side.  Use the drawing tools to draw a point radius.  Update the units and verify that drawing changes accordingly.  Do the same with the line drawing.  
[DDF-3710](https://codice.atlassian.net/browse/DDF-3710)
=> DDF-3710 Updates drawing tools to take into account units

ui/packages/catalog-ui-search/src/main/webapp/js/widgets/cesium.circle.js, ui/packages/catalog-ui-search/src/main/webapp/js/widgets/cesium.line.js, ui/packages/catalog-ui-search/src/main/webapp/js/widgets/openlayers.circle.js, ui/packages/catalog-ui-search/src/main/webapp/js/widgets/openlayers.line.js
Backport of https://github.com/codice/ddf/pull/3351
- Previously everything in the location model got normalized to meters, but that is no longer the case.  As such the drawing tools needed to be updated to convert things to meters when using the model value, and to convert to the proper units when updating the model value.
@bdeining
@millerw8 
@djblue 
Open both the 2d and 3d map side by side.  Use the drawing tools to draw a point radius.  Update the units and verify that drawing changes accordingly.  Do the same with the line drawing.  
[DDF-3710](https://codice.atlassian.net/browse/DDF-3710)
=> [2.12.x] DDF-3710 Updates drawing tools to take into account units

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/workspace/transformer/impl/EmbeddedListMetacardsHandler.java, catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/metacard/workspace/transformer/impl/EmbeddedListMetacardsHandlerTest.java, ui/packages/catalog-ui-search/src/main/webapp/component/list-interactions/list-interactions.hbs
This PR changes the way list actions are obtained. Currently we are passing only the workspace metacard to the `ActionProvider`s to obtain the list actions. This PR updates the list action retrieval code so that it passes a map containing both the workspace metacard _and_ the list metacard to the `ActionProvider`s instead.
This change will make it easier for `ActionProvider` implementors to write simple and correct code. For example, prior to this change, writing an `ActionProvider` for lists that returns actions only when the list is not empty would require the implementor to deal with the list metacard XML. Now that the list is being provided to each `ActionProvider` as a `Metacard`, writing code that deals with the details of the list is easier.
Removes the hostname fix now that …
=> DDF-3669 Use list and workspace metacards to determine list actions

ui/packages/ace/lib/webpack.config.js, ui/packages/ace/package.json, ui/packages/catalog-ui-search/src/main/webapp/js/router/routes-loader.js, ui/yarn.lock
The code the `routes-loader` generates doesn't get passed through babel,
so we cannot use ES6 features. We could figure out a way to pass the
code through babel, but it is sufficient to simply not use the features
for now.
The fetch api is unavailable in IE10, we can address this issue by using
a polyfill.
@Schachte 
@rzwiefel
- Full build of the ui directory
- Load catalog-ui-search module in IE10 browser
- Ensure functionality is restored
[DDF-3962](https://codice.atlassian.net/browse/DDF-3962) …
=> DDF-3962 Resolve IE10 compatibility issue

ui/packages/ace/lib/default-wcpm-config.json, ui/packages/ace/lib/disable-idp.js
Previously, the `disable-idp` command would:
- fetch the existing web context policy configuration
- apply a minimal change to the policy (remove IDP from authentication types)
- save the altered policy back into configuration admin
An issue would occur if there was no existing configuration, but this is
easily fixed by embedding the default config into the script.
@tbatie  …
=> DDF-3719 Adds defaultConfig to `disable-idp` command

catalog/security/catalog-security-plugin/src/main/java/ddf/catalog/security/plugin/SecurityPlugin.java, catalog/security/catalog-security-plugin/src/test/java/ddf/catalog/security/plugin/SecurityPluginTest.java, distribution/test/itests/test-itests-common/src/main/resources/json/record/UpdatedSimpleGeoJsonRecord, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalog.java
- Don't override POC attribute in SecurityPlugin if it is already present.
@emmberk @kcover @brjeter 
@clockard
@stustison
Unit tests.
When a Metacard created on one system is sent over to another system, it rewrites the POC. Then if the original system sends an update, the PointOfContactPolicyPlugin sees 2 different POCs and rejects the update.
[DDF-3960](https://codice.atlassian.net/browse/DDF-3960)
- ✏️ …
=> DDF-3960 Update SecurityPlugin to not override POC attribute

distribution/docs/src/main/resources/content/_configuring/global-settings.adoc, distribution/docs/src/main/resources/content/_tables/CatalogBackupPlugin.adoc, distribution/docs/src/main/resources/content/_tables/URLResourceReader.adoc, distribution/docs/src/main/resources/content/_tables/sts.client.configuration.adoc, distribution/docs/src/main/resources/content/_tables/sts.wss.configuration.adoc
- Replaces usages of ddf.home with home_directory
@kcover @clockard @emmberk 
@shaundmorris 
Build docs and verify ddf.home is now DDF_HOME.
- …
=> DDF-2824 Cleanup usages of ddf.home in docs

platform/security/filter/security-filter-csrf/pom.xml, platform/security/filter/security-filter-csrf/src/main/java/org/codice/ddf/security/filter/csrf/CsrfFilter.java, platform/security/filter/security-filter-csrf/src/test/groovy/org/codice/ddf/security/filter/csrf/CsrfFilterSpec.groovy
CSRF filter now compares the origin or referer header for incoming requests to the hostname and port specified in system.properties for local and external authorities. This allows the CSRF to operate properly when behind a proxy that does not modify origin or referer headers so long as the system.properties is correctly configured to include the proxy's hostname + port.
@adimka 
The main addition is the ability to run DDF behind a proxy without CSRF Filter violations, so set up DDF with a proxy with proper settings in system.properties and ensure everything still works. Also see testing section of previous PR here: https://github.com/codice/ddf/pull/3297 for a more detailed list of contexts to test. …
=> DDF-3855: External Hostname Support for CSRF Filter

catalog/opensearch/catalog-opensearch-endpoint/src/main/java/org/codice/ddf/opensearch/endpoint/query/OpenSearchQuery.java, catalog/opensearch/catalog-opensearch-endpoint/src/test/java/org/codice/ddf/opensearch/endpoint/query/OpenSearchQueryTest.java, catalog/opensearch/catalog-opensearch-source/src/main/java/org/codice/ddf/opensearch/source/OpenSearchFilterVisitor.java, catalog/opensearch/catalog-opensearch-source/src/test/groovy/org/codice/ddf/opensearch/source/OpenSearchSourceSpec.groovy, catalog/opensearch/catalog-opensearch-source/src/test/java/org/codice/ddf/opensearch/source/OpenSearchFilterVisitorTest.java, distribution/docs/src/main/resources/content/_endpoints/opensearch-endpoint.adoc
spatial criteria are always joined as an OR operation for OpenSearch Endpoint.
To be consistent with OpenSearch geo extension Draft 2 which support WKT GeometryCollection
Please choose AT LEAST four reviewers.
@bdeining
@millerw8
@mackncheesiest
@emmberk 
At least one reviewer should be a code owner.
How should this be tested? Justify why only a full build is sufficient for testing.
Configure a Open Search federated source with bounding box as OFF
Ingest 3 records somewhat close together ( for easy testing)
Draw a polygon around the left record only
Draw a bounding box around the right record only
Draw a point radius anywhere not on any of the record
Search should find the left and right records
Turn Source Bounding Box as ON
Search should find all 3 records
Try again …
=> DDF-3857 grouping spatial critera using logical OR

distribution/docs/src/main/resources/content/_tables/platform.ui.config.adoc, platform/platform-configuration/src/main/java/org/codice/ddf/configuration/PlatformUiConfiguration.java, platform/platform-configuration/src/main/resources/OSGI-INF/metatype/metatype.xml, platform/platform-configuration/src/test/java/org/codice/ddf/configuration/PlatformUiConfigurationTest.java
- Disallows setting platform UI configuration timeout to below 2
@emmberk @SmithJosh @mackncheesiest 
@clockard
@rzwiefel
Unit tests.
Manually test setting timeout below 2 defaults to 15.
Even though the bean will have the correct timeout value, the actual value saved in the configuration file will be whatever the admin puts in the UI. For example, if the admin set a timeout of 1, the configuration will have a value of 1, but the platform ui configuration endpoint will return 15. …
=> DDF-3943 Default timeout option in platform UI config

ui/packages/catalog-ui-search/src/main/webapp/js/model/Workspace.js
Fixes workspace being set into unsaved state when paging through the results, specifically when attempting to get a new serve page.
@millerw8 
@millerw8 
https://codice.atlassian.net/browse/DDF-3925
- ❓ (Question …
=> DDF-3925 Fixed workspace state being modified by paging

ui/packages/ui/src/main/webapp/components/tab-content/tab-content.view.js, ui/packages/ui/src/main/webapp/components/tab-item/tab-item.less, ui/packages/ui/src/main/webapp/components/tab-item/tab-item.view.js, ui/packages/ui/src/main/webapp/js/views/Module.view.js, ui/packages/ui/src/main/webapp/templates/moduleTab.handlebars
Prevents the possibility of more than one tab being shown at once in the even that multiple shown events get generated at the same time.
@roelens8 
@mcalcote 
@djblue 
@clockard 
Go to the admin UI and run either manually attempt to click tabs fast, or use this in the web console.
```$('[data-toggle=tab]').click()```
Verify only one tab gets shown at once.
[DDF-3924](https://codice.atlassian.net/browse/DDF-3924)
=> DDF-3924 Prevents more than one tab from showing at once

catalog/ui/catalog-ui-search/pom.xml, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/security/LogoutApplication.java, catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/blueprint/blueprint.xml, features/security/pom.xml, features/security/src/main/feature/feature.xml, platform/security/servlet/pom.xml, platform/security/servlet/security-servlet-logout-endpoint/pom.xml, platform/security/servlet/security-servlet-logout-endpoint/src/main/java/org/codice/ddf/security/logout/endpoint/LogoutEndpoint.java, platform/security/servlet/security-servlet-logout-endpoint/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/security/servlet/security-servlet-logout-service/pom.xml, platform/security/servlet/security-servlet-logout-service/src/main/java/org/codice/ddf/security/logout/service/LogoutService.java, platform/security/servlet/security-servlet-logout/pom.xml, platform/security/servlet/security-servlet-logout/src/main/java/org/codice/ddf/security/servlet/logout/LogoutServiceImpl.java, platform/security/servlet/security-servlet-logout/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/security/servlet/security-servlet-logout/src/test/java/org/codice/ddf/security/servlet/logout/LogoutServiceImplTest.java, ui/packages/catalog-ui-search/src/main/webapp/component/singletons/logout-actions.js
**This is PR 5/7**
- Moved endpoint for the LogoutService into a new module
- Added new endpoint under /search/catalog/internal
- Changed Intrigue code to use new endpoint
@coyotesqrl
@rzwiefel
- Look at the network activity in intrigue and verify that `/search/catalog/internal/logout/action` is called and that the response is a 200 with a json body …
=> DDF-3941 - Moved intrigue from using the LogoutService endpoint under /services

distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestPlatform.java, platform/metrics/platform-metrics-reporting/pom.xml
The metrics report download button was throwing an error into the admin ui due to a ClassNotFoundException. The missing jar was embedded in the metrics reporting bundle and an itest was added to ensure the download button will return a 200 in the future. 
@austinsteffes @ahoffer 
@brendan-hofmann @rzwiefel @shaundmorris 
Go to the Admin Console in a browser
Select the Platform App (the metrics tab will appear)
Click the download button in the bottom left corner
The error shown in the screenshot will *NOT* appear!
[DDF-3968](https://codice.atlassian.net/browse/DDF-3968)
- ✏️ (Pencil) This comment …
=> DDF-3968 Fix metrics report download and add itest to prevent regression

catalog/confluence/catalog-confluence-source/pom.xml, catalog/confluence/catalog-confluence-source/src/main/java/org/codice/ddf/confluence/source/ConfluenceInputTransformer.java, catalog/confluence/catalog-confluence-source/src/main/java/org/codice/ddf/confluence/source/ConfluenceSource.java, catalog/confluence/catalog-confluence-source/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/confluence/catalog-confluence-source/src/test/java/org/codice/ddf/confluence/source/ConfluenceInputTransformerTest.java, catalog/confluence/catalog-confluence-source/src/test/java/org/codice/ddf/confluence/source/ConfluenceSourceTest.java, catalog/confluence/catalog-confluence-source/src/test/resources/confluence_attachment.json, catalog/confluence/catalog-confluence-source/src/test/resources/confluence_page.json, catalog/confluence/catalog-confluence-source/src/test/resources/confluence_page_no_restrictions.json, catalog/confluence/catalog-confluence-source/src/test/resources/full_response.json
Injects attribute descriptors into confluence metacards and fixes attribute overrides so they are the correct type. Address some sonarqube findings as well.
@shaundmorris 
@figliold
Install DDF and create a confluence source.
Add overrides that are in the common taxonomy but not in the confluence type. (I used `datetime.start=2018-06-28`)
Perform a query via Intrigue using the confluence source and verify the overrides show up as expected.
[DDF-3933](https://codice.atlassian.net/browse/DDF-3933)
=> DDF-3933 Fix attribute overrides in confluence source

catalog/ui/search-ui-app/src/main/resources/features.xml
The Simple Search UI was deprecated in 8ab5e702fa73f64e5bb3b5176737e387828e845e. This PR moves the `search-redirect` bundle under the `search-ui-app` feature so that it is started by default regardless of what search UI is installed.
@peterhuffer
@austinsteffes
@clockard
@vinamartin
- Confirm that /search redirects to /search/catalog.
- Confirm that the redirect can be configured in the Admin Console.
[DDF-3929](https://codice.atlassian.net/browse/DDF-3929) …
=> DDF-3929 Updated search-redirect to be installed with search-ui-app

distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/AbstractIntegrationTest.java
Fixes path separator character
@stustison 
`@anyone`
https://codice.atlassian.net/browse/DDF-3915
=> DDF-3915 Add os agnostic path separator to solr itest policy

distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/AbstractIntegrationTest.java
Fixes path separator character
@stustison 
`@anyone`
https://codice.atlassian.net/browse/DDF-3915
=> [2.13.x] DDF-3915  Add os agnostic path separator to solr itest policy

features/security/pom.xml, features/security/src/main/feature/feature.xml, platform/security/idp/security-idp-plugin/pom.xml, platform/security/idp/security-idp-plugin/security-idp-plugin-nameidpolicy/pom.xml, platform/security/idp/security-idp-plugin/security-idp-plugin-nameidpolicy/src/main/java/org/codice/ddf/security/idp/plugin/nameidpolicy/NameIdPolicyPresignPlugin.java, platform/security/idp/security-idp-plugin/security-idp-plugin-nameidpolicy/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/security/idp/security-idp-plugin/security-idp-plugin-nameidpolicy/src/test/groovy/org/codice/ddf/security/idp/plugin/nameidpolicy/NameIdPolicyPresignPluginSpec.groovy, platform/security/idp/security-idp-plugin/security-idp-plugin-nameidpolicy/src/test/resources/sampleResponse.xml
Adds support for `NameIDPolicy`s on the `AuthnRequest` in DDF's IdP.
@blen-desta
@brjeter
@coyotesqrl
@stustison
1. Build and install DDF
2. Run [this branch of the SAML CTK](https://github.com/bakejeyner/saml-conformance/tree/DDF-3893), and verify that there are no errors.
[DDF-3893](https://codice.atlassian.net/browse/DDF-3893) …
=> DDF-3893 The IdP should account for the NameIDPolicy in AuthnRequests

platform/admin/core/admin-core-impl/src/main/java/org/codice/ddf/admin/core/impl/AdminAlertImpl.java, platform/admin/core/admin-core-impl/src/test/java/org/codice/ddf/admin/core/impl/AdminAlertImplTest.java
Adds an alert if solr is not reachable. The alert will appear in the admin console. This PR also updates a unit test to expect an alert if solr is down. This PR relies on the new separate solr process.
@mcalcote 
@rzwiefel 
@ahoffer 
@clockard 
@rzwiefel
Manually steps to test:
1) Start the DDF
2) Log in to the admin console
3) Manually stop solr using {DDF_HOME}/solr/bin/solr stop -p 8994
4) Wait for at least 30 seconds
5) The solr connectivity alert should eventually display in the admin console (can try refreshing)
6) Manually start solr using {DDF_HOME}/solr/bin/solr start -p 8994
7) Wait at least 30 seconds
8) Dismiss the solr alert, refresh the admin console page, and you should …
=> DDF-3919 Solr connectivity alert

catalog/spatial/spatial-app/src/main/resources/features.xml
The `gazetteer` commands were not starting for default because they were waiting on services started by the `spatial-geocoding-feature`. The `spatial-geocoding-feature` should be started with the `offline-gazetteer` because it only contains services that are used by the offline gazetteer.
@peterhuffer @vinamartin @kcover 
@bdeining
@clockard
Confirm that the `gazetteer` commands are available after a default install.
[DDF-3982](https://codice.atlassian.net/browse/DDF-3982) …
=> [2.13.x] DDF-3982 Updated the spatial-geocoding-feature bundle to start with the offline-gazetteer feature

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/catalog/CatalogApplication.java
Fixes Metacard ID not being set as a header in the CatalogApplication.
@garrettfreibott  @brjeter 
@rzwiefel
Ingest data from Intrigue with the network tab open and verify that a location header is returned in the response. …
=> [2.13.x] DDF-3941 Fix Metacard ID not being set in CatalogApplication

distribution/ddf-common/src/main/resources/bin/ddf, distribution/ddf-common/src/main/resources/bin/ddf.bat
Won't start local solr if not configured as HttpSolrClient
Parse solr port and client properly even with spaces between = 
@ahoffer 
@millerw8 
@bdeining 
@codice/solr 
@bdeining
@millerw8
Test in both Linux and Windows
by default. start up DDF should start solr
`Started Solr server on port 8994 (pid=46296). Happy searching!`
Modify etc/system.properties `solr.client` value any else but `HttpSolrClient`
Verify solr is not started
https://codice.atlassian.net/browse/DDF-3992 …
=> DDF-3992 won't start local solr if not configured as HttpSolrClient

distribution/ddf-common/src/main/resources/security/default.policy
Gives `catalog-ui-search` permissions to read, write, and execute the Codice Third Party executables.
@Kjames5269 
@emmberk 
@clockard
@coyotesqrl 
1. Install DDF
2. Ingest a video file (message me if you need one)
3. Verify that the DDF logs don't throw any exceptions and that there is a thumbnail on the ingested resource.
[DDF-3988](https://codice.atlassian.net/browse/DDF-3988) …
=> DDF-3988 Give the third-party FFmpeg library permissions to create thumbnails

distribution/ddf-common/src/main/resources/security/default.policy, platform/platform-migratable/src/main/java/org/codice/ddf/platform/migratable/impl/PlatformMigratable.java, platform/platform-migratable/src/test/java/org/codice/ddf/platform/migratable/impl/PlatformMigratableTest.java, platform/security/security-migratable/src/main/java/org/codice/ddf/security/migratable/impl/SecurityMigratable.java, platform/security/security-migratable/src/test/java/org/codice/ddf/security/migratable/impl/SecurityMigratableTest.java
- Teams tagged
____
It moves the policy files migration from the platform migratable to the security migratable and ensures to migrate the whole security directory and not just the default.policy file. It also fixes a permission issue where default interface methods from the API are called and thus require the same privileges as the implementation.
@ethantmanns 
@jhunzik 
@tbatie
@figliold
@stustison
@tbatie
Please see …
=> DDF-3979 Modified to migrate all policy files

ui/packages/catalog-ui-search/src/main/webapp/component/filter/filter.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/input/date/input-date.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/input/enum/input-enum.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/input/input.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/input/location/input-location.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/input/number/input-number.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-old.view.js
Search templates fail to search if date or anyGeo fields are left unfilled
Note: this change impacts all search filters (not just templates). Any filter containing an input where isValid() returns false will be removed from the search. 
* modify isValid implementation for several input views
* remove all invalid filters at search time
@djblue 
@bdeining
@millerw8 
Create searches (advanced, basic, and template) with invalid fields and confirm that the fields are removed.
[DDF-3939](https://codice.atlassian.net/browse/DDF-3939)
(if this behavior is accepted I will update the documentation and add unit tests)
Please see …
=> DDF-3939 Search templates fail to search if date or anyGeo fields are left unfilled

ui/packages/catalog-ui-search/src/main/webapp/component/search-interactions/search-interactions.view.js, ui/packages/catalog-ui-search/src/main/webapp/js/model/Query.js
Link to 2.13.x PR: #3453
____
Fixes the issue of when resetting a search form it clears the values instead of defaulting to anyText.
@djblue @mackncheesiest
@bdeining
1. Extract built DDF
2. Create a /etc/forms directory
3. Start DDF
4. Enable experimental features in the catalog-ui-search config
5. Create a search form in the catalog search ui and save it.
6. Click the reset button from the three button dropdown and verify your form is the same.
[DDF-3984](https://codice.atlassian.net/browse/DDF-3984) …
=> DDF-3984 Fixed resetting search forms

distribution/ddf-common/src/main/resources/common-bin.xml
Excludes unused libraries from the distribution to reduce Sonatype findings.
@peterhuffer @emmberk @oconnormi 
@bdeining
@clockard
The excluded files should not be included in the distribution after building the ddf-common and ddf modules.
[DDF-3989](https://codice.atlassian.net/browse/DDF-3989) …
=> DDF-3989 Exclude unused libraries from distribution

distribution/ddf-common/src/main/resources/security/configurations.policy, distribution/ddf-common/src/main/resources/security/default.policy, distribution/docs/src/main/resources/content/_securing/auditing.adoc
Fixing a minor security-manager bug that occurs when setting up security hardening for DDF.
@bakejeyner 
@blen-desta 
@ricklarsen 
@paouelle
@clockard
@coyotesqrl 
Step 1:
Install and build DDF
Step 2:
```
edit <DDF_HOME>/etc/org.ops4j.pax.logging.cfg
uncomment the line (remove the # from the beginning of the line) for log4j2 (org.ops4j.pax.logging.log4j2.config.file = ${karaf.etc}/log4j2.config.xml)
delete all other lines
```
Run DDF and there should be no security-manager errors.
Step 3:
* edit `<DDF_HOME>/security/configurations.policy`
* find `//  permission java.io.FilePermission "/path/to/directory/", "read,write";` under Security-Hardening
* uncomment both lines and change the value …
=> DDF-3974 Updating security hardening documentation and default.policy to include securityBackup

Jenkinsfile
Removes the javadoc:aggregate step from the pipeline. This step is no longer needed.
@LinkMJB @oconnormi 
@lessarderic
@shaundmorris
The Jenkins pipeline is not used in CI at the moment
There has been recent CI instability in this maven execution. It is believed to no longer be needed, so we're removing it.
[DDF-3981](https://codice.atlassian.net/browse/DDF-3981) …
=> DDF-3981 Removed javadoc:aggregate step from pipeline

distribution/ddf-common/src/main/resources/security/configurations.policy, distribution/docs/src/main/resources/content/_architectures/url-resource-reader.adoc, distribution/docs/src/main/resources/content/_running/ingest-command.adoc
Document how an administrator can add permissions for the URL Resource Reader to retrieve resources from directories
@jhunzik @peterhuffer @ricklarsen 
@lessarderic
@stustison
1) Ingest a metacard with a link to a resource located in an external directory
2) Read the docs to update the configurations.policy
3) restart DDF
4) Retrieve the resource the external directory (via URL Resource Reader)
[DDF-3985](https://codice.atlassian.net/browse/DDF-3985) …
=> DDF-3985 Updated URL Resource Reader permissions/docs

distribution/ddf-common/src/main/resources/common-bin.xml
Port of https://github.com/codice/ddf/pull/3461
Excludes unused libraries from the distribution to reduce Sonatype findings.
@peterhuffer @emmberk @oconnormi
@bdeining
@clockard
The excluded files should not be included in the distribution after building the ddf-common and ddf modules.
[DDF-3989](https://codice.atlassian.net/browse/DDF-3989) …
=> [2.13.x] DDF-3989 Exclude unused libraries from the distribution

distribution/ddf-common/src/main/resources-filtered/etc/system.properties, distribution/docs/src/main/resources/content/_quickstart/quickstart-installing.adoc
This PR fixes the `Quick Install of DDF on a remote headless server` section of the documentation. Changing the solr.http.url from `http://localhost:_DO_NOT_EXPAND_${solr.http.port}/solr` to `http://<hostname>:_DO_NOT_EXPAND_${solr.http.port}/solr` causes issues.
@ahoffer @mcalcote @peterhuffer @oconnormi 
@rzwiefel
There are no testable changes for this PR.
[DDF-3915](https://codice.atlassian.net/browse/DDF-3915) …
=> [2.13.x] DDF-3915 Added a note in the documentation to not update the solr.http.url in system.properties

ui/packages/catalog-ui-search/src/main/webapp/component/search-interactions/search-interactions.view.js, ui/packages/catalog-ui-search/src/main/webapp/js/model/Query.js
Fixes the issue of when resetting a search form it clears the values instead of defaulting to anyText.
@djblue @mackncheesiest 
@bdeining
1. Extract built DDF
2. Create a `/etc/forms` directory
3. Start DDF
4. Enable experimental features in the catalog-ui-search config
5. Create a search form in the catalog search ui and save it.
6. Click the reset button from the three button dropdown and verify your form is the same.
[DDF-3984](https://codice.atlassian.net/browse/DDF-3984) …
=> [2.13.x] DDF-3984 Fixed resetting search forms

distribution/test/itests/test-itests-ddf/pom.xml
Fix for Windows itests. Itest POM executes chmod, which causes an error on Windows. Sam Chu created a fix by moved the chmod execution to the unix-only profile.
UPDATE: Moved from 2.13.x to mater per conversation with Chris
@samuelechu 
@mcalcote  
@vinamartin 
@rzwiefel 
@clockard
@pklinef
Build and run an itest on windows.
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an inline code snippet or a gist.  …
=> DDF-3915 Fix for itest on Windows

ui/packages/catalog-ui-search/src/main/webapp/behaviors/dropdown.behavior.js, ui/packages/catalog-ui-search/src/main/webapp/component/query-schedule/query-schedule.less, ui/packages/catalog-ui-search/src/main/webapp/component/query-settings/query-settings.less
- Updates these components to have a minimum size.
- Updates dropdown behavior to allow having a minimum size without using the !important keyword.
@mcalcote 
@clockard 
@tbatie 
@rzwiefel 
@blen-desta 
Open the settings dropdown and the schedule dropdown and verify they aren't being sized super small.
=> DDF-4011 Adds minimum sizes to query-schedule and query-settings components

platform/security/filter/security-filter-csrf/src/main/java/org/codice/ddf/security/filter/csrf/CsrfFilter.java, platform/security/filter/security-filter-csrf/src/test/groovy/org/codice/ddf/security/filter/csrf/CsrfFilterSpec.groovy
This PR fixes an issue that was introduced by the CSRF support in which `503 (Forbidden)` responses were returned when loading the Admin Console when DDF was installed with a hostname than is not lowercase. This PR updates the method that grabs the hostname property to always return lowercase so that the CSRF check does not fail.
@garrettfreibott @peterhuffer @kcover 
@clockard
@vinamartin
Using a hostname that is not lowercase:
- Install DDF using the `Quick Install of DDF on a remote headless server` section of the documentation. Confirm that the Admin Console is functional after install.
- Install DDF with ?dev=true. Confirm that the Admin Console is functional after install.
[DDF-3855](https://codice.atlassian.net/browse/DDF-3855) …
=> [2.13.x] DDF-3855 Updated SystemBaseUrl to return the hostname in lowercase

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/catalog/CatalogApplication.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/configuration/PlatformUiConfigurationApplication.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/security/AuthenticationApplication.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/security/LogoutApplication.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/session/SessionManagementApplication.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/spatial/GeoCoderApplication.java, ui/packages/catalog-ui-search/src/main/webapp/component/builder/builder.view.js
Changed the new Spark endpoints to return Strings instead of Spark Responses.
@Bdthomson @adimka 
@coyotesqrl
@rzwiefel 
1. `CatalogApplication`
- Verify ingest works
- Verify in the metacard id is returned as a header on the response
- Verify querying works
2. `PlatformUiConfigurationApplication`
- Verify that configurations like the header, footer, color etc.. work on intrigue
- Change the platform configurations in the Admin Console under 
`Platform -> Configuration -> Platform UI Configuration` and make 
sure they take effect in both the Admin Console and Intrigue
3. `AuthenticationApplication`
- Set the authentication method for /search to GUEST
- Go to Intrigue
- Login from Intrigue
4. `LogoutApplication`
- Verify that when from Intrigue that endpoint is called and that the response …
=> [2.13.x] DDF-3941 Changed the new Spark endpoints to return Strings instead of Spark Responses

platform/security/filter/security-filter-csrf/src/main/java/org/codice/ddf/security/filter/csrf/CsrfFilter.java, platform/security/filter/security-filter-csrf/src/test/groovy/org/codice/ddf/security/filter/csrf/CsrfFilterSpec.groovy
____
Master port of https://github.com/codice/ddf/pull/3448
Updates the CSRF Filter to match hostnames without case sensitivity to account for non-lowercased hostnames in system.properties
@emmberk  @peterhuffer @kcover
@clockard
@vinamartin
Using a hostname that is not lowercase:
Install DDF using the Quick Install of DDF on a remote headless server section of the documentation. Confirm that the Admin Console is functional after install.
Install DDF with ?dev=true. Confirm that the Admin Console is functional after install.
[DDF-3855](https://codice.atlassian.net/browse/DDF-3855)
- ✏️ (Pencil) …
=> DDF-3855: Update CSRF filter to be case insensitive for hostnames

distribution/ddf-common/src/main/resources/security/configurations.policy, distribution/ddf-common/src/main/resources/security/default.policy, distribution/docs/src/main/resources/content/_securing/auditing.adoc
[Link to master PR: #3419](https://github.com/codice/ddf/pull/3419)
____
@bakejeyner
@blen-desta
@ricklarsen
@clockard
@coyotesqrl …
=> [2.13.x] DDF-3974 Updating security hardening documentation and default.policy to include securityBackup

catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/SolrFilterDelegate.java, catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/SolrFilterDelegateTest.java
Replaces `anyText:*` queries with `*:*` Solr queries.  This avoids `anyText` being expanded to all attributes when the query value is only a wildcard.  Instead a Solr `MatchAllDocsQuery` is used which is optimized for this use case.
@paouelle 
@troymohl 
@clockard
@rzwiefel
Install and ingest data into DDF.  From Intrigue, do an advance search and search for "*" on `anyText`.  A default basic search on "*" should have the same result.
Verify in the Solr log files that the `q` parameter looks like `q=+(++(*:*+-validation-errors_txt:[*+TO+*])++AND++(++(+metacard-tags_txt_tokenized:%22resource%22+OR++(*:*+-metacard-tags_txt:[*+TO+*])++)++AND+*:*+)++)+`
[DDF-3938](https://codice.atlassian.net/browse/DDF-3938)
- [ n/a ] …
=> [2.13.x] DDF-3938 Replace anyText:* with *:* to use optimized MatchAllDocsQuery

ui/packages/catalog-ui-search/src/main/webapp/component/component.less, ui/packages/catalog-ui-search/src/main/webapp/component/result-item/result-item.hbs, ui/packages/catalog-ui-search/src/main/webapp/component/result-item/result-item.less, ui/packages/catalog-ui-search/src/main/webapp/component/result-item/result-item.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/result-link/result-link.hbs, ui/packages/catalog-ui-search/src/main/webapp/component/result-link/result-link.less, ui/packages/catalog-ui-search/src/main/webapp/component/result-link/result-link.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/table/row.view.js
This PR adds a dropdown menu displaying all `associations.external` URL's for metacards in Intrigue that have any `associations.external` attributes. 
@clockard 
@kcover 
@emmberk 
@peterhuffer 
@oconnormi 
@codice/ui 
@clockard
- Ingest a metacard.
- In the inspector's details tab, add an associations.external attribute. 
- Edit the associations.external attribute, add URL(s) with a valid protocol.
- In the Intrigue search, verify that the new external links button appears and is usable. Verify that other buttons attached to the metacard were not negatively impacted. 
[DDF-3933](https://codice.atlassian.net/browse/DDF-3933) …
=> [2.13.x] DDF-3933 Add external links dropdown to Intrigue

platform/security/cas/security-cas-client/pom.xml, platform/security/cas/security-cas-client/src/main/java/org/codice/ddf/security/handler/cas/filter/FilteredRequest.java, platform/security/cas/security-cas-client/src/main/java/org/codice/ddf/security/handler/cas/filter/ProxyFilter.java, platform/security/cas/security-cas-client/src/main/java/org/codice/ddf/security/handler/cas/filter/ProxyFilterChain.java, platform/security/cas/security-cas-client/src/main/resources/OSGI-INF/blueprint/casfilters.xml, platform/security/cas/security-cas-client/src/test/java/org/codice/ddf/security/handler/cas/CasHandlerTest.java, platform/security/cas/security-cas-client/src/test/java/org/codice/ddf/security/handler/cas/FilteredRequestTest.java
Wraps incoming ServletRequests so they use the correct context paths behind a proxy. 
@vinamartin 
* Checkout this repo and follow the ReadMe to deploy a reverse proxy: https://github.com/brendan-hofmann/nginx-reverse-proxy/tree/context
* Install DDF with ?dev=true to generate certs for your ip/hostname
* Install the public key of the reverse proxy in the keystore and truststore under the alias localhost by running this command in `etc/keystores`: `openssl s_client -showcerts -connect localhost:YOUR_PORT_80_PORT_ASSIGNED_BY_DOCKER< /dev/null | openssl x509 -outform DER > derp.der; keytool -delete -alias localhost -keystore serverKeystore.jks -storepass changeit; keytool -import -alias localhost -keystore serverKeystore.jks -file derp.der -storepass …
=> DDF-3998 Fix CAS client redirects

catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/blueprint/blueprint.xml
Refactors out unnecessary service registration in favor of using the bean here instead.
Exporting it as a service can cause classloader issues when developing and integrating with bundles that need `org.codice.ddf.catalog.ui.query.monitor.impl.SubscriptionsPersistentStore`.
@glenhein @djblue 
@rzwiefel
Build and run Intrigue, verify everything is working as expected (particularly initial load, managing workspaces)
https://codice.atlassian.net/browse/DDF-4014 …
=> DDF-4014 Refactor catalog-ui-search blueprint to not register unnecessary service

distribution/ddf-common/src/main/resources/security/default.policy
Addes permission needed for downloading resources from confluence
@peterhuffer @kcover @JGatley 
@coyotesqrl
@shaundmorris
Install DDF and add a confluence federated source (https://codice.atlassian.net/wiki/rest/api/content) 
Enable Catalog->Configuration->URL Resource Reader->Follow Server Redirects
In intrigue search the confluence source for "security_manager_tech_codice.pptx"
Verify the ppt can be downloaded via the download button
[DDF-3933](https://codice.atlassian.net/browse/DDF-3933)
=> DDF-3933 Add permission for catalog-core-resourcereader used by confluence

features/apps/src/main/feature/feature.xml
Ensures the filter delegate is running in jetty before any contexts paths are registered.
@ryeats 
@clockard 
@figliold
@stustison
@coyotesqrl 
Distribution successfully starts up. …
=> [2.13.x] DDF-3739: Ensure filter delegate runs before any context paths are registered with Jetty

distribution/solr-distro/assembly.xml, distribution/solr-distro/src/main/resources/solrFiles/bin/solr.cmd
- Teams tagged
Link to 2.13.x PR: #3532 
____
Replace Solr provided cmd file with one that addresses the stack-traces that appear on boot. 
@pklinef @oconnormi @rzwiefel @ahoffer @ethantmanns @kcover @bakejeyner @tyler30clemens @figliold 
Install and run DDF, ensure that there aren't any log4j stack traces in the karaf console.
=> DDF-3915 Updated Windows Solr CMD file to avoid logger stack traces

distribution/docs/src/main/resources/content/_using/using-catalog-search-ui.adoc
Improves documentation of operators that can be used while creating an Advanced Search in Intrigue. Primary focus was on the `NEAR` operator since it has no equivalent operator in the already-documented Basic search.
@BernardIgiri @rymach @rzwiefel
@codice/docs 
@vinamartin
Build & verify added documentation
[DDF-4029](https://codice.atlassian.net/browse/DDF-4029) …
=> DDF-4029 Documented Advanced Search operators

distribution/ddf-common/src/main/resources/security/default.policy
Link to 2.13.x PR: #3554 
____
Adds missing permissions that were causing itests to fail
@bakejeyner @peterhuffer @kcover @mcalcote 
@coyotesqrl
@rzwiefel
@shaundmorris
@tbatie
@vinamartin
CI Build
=> DDF-3945 Add missing jetty.websocket permissions to policy file (#3554)

catalog/catalog-app/pom.xml, catalog/catalog-app/src/main/resources/features.xml, catalog/core/catalog-core-api/src/main/java/ddf/catalog/Constants.java, catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/SolrMetacardClientImpl.java, catalog/plugin/catalog-plugin-gazetteer/pom.xml, catalog/plugin/catalog-plugin-gazetteer/src/main/java/org/codice/ddf/catalog/plugin/gazetteer/BuildSuggesterIndex.java, catalog/plugin/catalog-plugin-gazetteer/src/main/java/org/codice/ddf/catalog/plugin/gazetteer/BuildSuggesterIndexPlugin.java, catalog/plugin/catalog-plugin-gazetteer/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/plugin/catalog-plugin-gazetteer/src/test/groovy/org/codice/ddf/catalog/plugin/gazetteer/BuildSuggesterIndexPluginSpec.groovy, catalog/plugin/catalog-plugin-gazetteer/src/test/groovy/org/codice/ddf/catalog/plugin/gazetteer/BuildSuggesterIndexSpec.groovy, catalog/plugin/pom.xml, catalog/spatial/spatial-commands/pom.xml, catalog/spatial/spatial-commands/src/main/java/org/codice/ddf/commands/spatial/gazetteer/GazetteerBuildSuggesterIndexCommand.java, catalog/spatial/spatial-commands/src/test/java/org/codice/ddf/commands/spatial/gazetteer/GazetteerBuildSuggesterIndexCommandTest.java, distribution/docs/src/main/resources/content/_appReferences/mg-spatial.adoc, platform/solr/platform-solr-server-standalone/src/main/resources/solr/conf/solrconfig-inmemory.xml, platform/solr/platform-solr-server-standalone/src/main/resources/solr/conf/solrconfig.xml
- Changes when the Solr gazetteer suggester index is built. Currently the index is built on every Solr restart and `catalog ` core reload, regardless of whether the gazetteer entries have changed. This PR sets `buildOnStartup=false` and adds a new `PostIngestPlugin` that builds the suggester index when new gazetteer metacards are created, updated, or deleted.
- Adds a `gazetteer:build-suggester-index` command for manually issuing requests to build the suggester index (useful if the request submitted after the gazetteer update fails).
- Changes `storeDir` to `indexPath` in the suggest component in `solrconfig.xml`. `BlendedInfixLookupFactory` uses `indexPath` to store the suggester index. This change prevents Solr from printing a bogus failure message in its log and ensures the suggester …
=> DDF-3987 Build offline gazetteer suggester index whenever gazetteer metacards are created, updated, or deleted

platform/security/pdp/security-pdp-authzrealm/src/main/java/ddf/security/pdp/realm/xacml/processor/PollingPolicyFinderModule.java
Switches the FileAlterationObserver used in PollingPolicyFinderModule to a custom one that override and wraps method in an AccessController.doPrivileged to fix an access control exception.
@stustison
@tbatie
See me for instructions.
[DDF-4046](https://codice.atlassian.net/browse/DDF-4046)
=> DDF-4046 Update PollingPolicyFinderModule to use custom file observer

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/config/ConfigurationApplication.java, catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.xml, catalog/ui/search-ui-app/src/main/resources/etc/org.codice.ddf.catalog.ui.config, distribution/docs/src/main/resources/content/_tables/catalog.ui.config.adoc, ui/packages/catalog-ui-search/src/main/webapp/component/query-basic/query-basic.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/query-time/query-time.hbs, ui/packages/catalog-ui-search/src/main/webapp/component/query-time/query-time.less, ui/packages/catalog-ui-search/src/main/webapp/component/query-time/query-time.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/singletons/metacard-definitions.js
As a user I would like to choose the time fields basic search searches against.
Currently, the basic search expands against 5 time fields. Ideally, the basic search should allow for a drop-down of visible time fields which should be searched, and the default selection should be an admin-configurable mechanism.
For example: Date Revised and Created could be the default fields, all visible date-time fields are shown in the multi-select dropdown.  The user can uncheck Date Revised to just do created, or change the selection however they choose when building the dropdown.  
This will give the user much better granularity to control what fields they search against.
* configurable default for basic temporal search
* User selectable dropdown for basic temporal search fields
* Consultation with …
=> DDF-4039 Add time fields to basic search

platform/platform-filter-delegate/pom.xml, platform/platform-filter-delegate/src/main/java/org/codice/ddf/platform/filter/delegate/FilterInjector.java, platform/platform-filter-delegate/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/platform-filter-delegate/src/test/java/org/codice/ddf/platform/filter/delegate/FilterInjectorTest.java
Restarts ServletContext bundles if they came up before the platform-filter-deleage bundle. Add logging around this so it is clear when this happens.
@coyotesqrl
@lessarderic
Good CI build.
I manually tested this by artificially adding delays but during a normal install it can't be replicated consistently.
Some times the platform filter delegate bundle would come up after other ServletContext bundle. When this would happen the needed filters would not be injected into the change but there was no indication of this anywhere. Users would find out when they tried an operation and it would fail. Most often it would fail with something like "No user subject".
[DDF-4053](https://codice.atlassian.net/browse/DDF-4053)
=> [2.13.x] DDF-4053 Add retry logic to platform filter delegate

distribution/ddf-common/src/main/resources-filtered/etc/system.properties, distribution/ddf-common/src/main/resources/bin/ddf.bat, distribution/ddf-common/src/main/resources/bin/ddfsolr, distribution/docs/src/main/resources/content/_configuring/global-settings.adoc, distribution/docs/src/main/resources/content/_running/starting-intro.adoc, distribution/docs/src/main/resources/content/_sources/solr-catalog-provider.adoc
Update the docs and start scripts to reference a non-default heap max for Solr that is configurable.
@clockard @lessarderic @kcrowe01 @taz77 @austinsteffes @garrettfreibott @ahoffer @ricklarsen 
Ensure Solr starts and operates as expected. Try ingesting a large dataset (like a million records) through the command line with `ingest -t format path/to/records` and make sure the ingest is successful.
Read through the docs changes and make sure they are adequate.  …
=> 2.13.X DDF-3915 Updating Solr Memory Default and Docs

platform/admin/core/admin-core-appservice/src/main/java/org/codice/ddf/admin/application/service/impl/ApplicationServiceBean.java, platform/admin/core/admin-core-appservice/src/test/java/org/codice/ddf/admin/application/service/impl/ApplicationServiceBeanTest.java, platform/security/platform-security-core-api/src/main/java/ddf/security/samlp/SimpleSign.java
Adds AccessController.doPrivilegedAction() call to ApplicationServiceBean's installFeature() method to grant same feature install permissions to other bundles.
@brjeter 
@clockard
@coyotesqrl
@stustison
Unzip the distribution (or any downstream distribution), start karaf and make sure that the installer UI works as expected, especially when the profile selected contains a feature that needs to install a file or files under `/etc`.
Since this is an intermittent problem, the test should be repeated multiple times on both Windows and Linux.
[DDF-4051](https://codice.atlassian.net/browse/DDF-4051) …
=> [2.13.x] DDF-4051 Permissions granted to ApplicationService to install new features should be granted to other bundles

Jenkinsfile
This PR removes the "skipDocs" from quickbuild step on PR builds. The docs module does not build the PDF during normal builds, so it is quick to build. Skipping building the docs module causes the quickbuild step to fail on PR builds right after a release because the docs module has not yet been deployed.
@LinkMJB @mcalcote @oconnormi
@clockard 
CI build
[DDF-4065](https://codice.atlassian.net/browse/DDF-4065) …
=> [2.13.x] DDF-4065 Removed "skipDocs" from quickbuild step on PR builds prior to GIB

platform/admin/core/admin-core-appservice/src/main/java/org/codice/ddf/admin/application/service/impl/ApplicationServiceImpl.java, platform/admin/core/admin-core-appservice/src/main/resources/OSGI-INF/blueprint/blueprint.xml
This PR removes a leftover managed-properties section in a blueprint for a config that was removed in https://github.com/codice/ddf/pull/2986 (https://github.com/codice/ddf/commit/5b30f47b61db9df4372c3b8b658c4bb5b20798a1#diff-3e2a721ab8acfb851595af59df747ee9 and https://github.com/codice/ddf/commit/5b30f47b61db9df4372c3b8b658c4bb5b20798a1#diff-6fde67309bea545bb05f0addffbc2d1eL258).
@peterhuffer @kcover 
@clockard
@vinamartin
CI build
[DDF-4068](https://codice.atlassian.net/browse/DDF-4068) …
=> DDF-4068 Removed unused ApplicationServiceImpl managed-properties

catalog/opensearch/catalog-opensearch-source/src/main/java/org/codice/ddf/opensearch/source/OpenSearchFilterVisitor.java, catalog/opensearch/catalog-opensearch-source/src/test/java/org/codice/ddf/opensearch/source/OpenSearchFilterVisitorTest.java
OpenSearch to support multipolygon intersect filter
@bdeining 
@millerw8 
@troymohl 
@bdeining 
@millerw8 
Create a loopback Opensearch federated source
Use Advance Search UI. Search for anyGeo with the following polygon 
[[[-113.95256342767334,38.09997616271079],[-112.82951580761528,41.640015299716595],[-111.92619609116173,38.124390299716595],[-112.58537577866173,38.17321857372821],[-112.85393061517334,39.85778866271079],[-113.29338374017334,38.1488044367224],[-113.95256342767334,38.09997616271079]],[[-111.04728897451434,41.61315988205996],[-107.84904708503757,41.68640229307738],[-109.92424269556079,38.90319872104254],[-107.87346189259563,38.92761285804835],[-107.92228882550273,38.24401903354254],[-111.02287550806079,38.31726144455996] …
=> DDF-4021 OpenSearch to support multipolygon intersect filter

ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/map.view.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/location/location.less
Adds a field indicating if the map in a MapView has loaded.
Also fixes a CSS issue causing unreadable text.
@Schachte @middlets719 @djblue
@codice/ui 
@bdeining
CI + build the UI and make sure it loads.
[DDF-4064](https://codice.atlassian.net/browse/DDF-4064) …
=> DDF-4064 Add indicator that map has loaded to MapView

distribution/solr-distro/assembly.xml, distribution/solr-distro/pom.xml, distribution/solr-distro/src/main/resources/bin/solr, distribution/solr-distro/src/main/resources/bin/solr.cmd, distribution/solr-distro/src/main/resources/security/solr-default.policy
Master port: https://github.com/codice/ddf/pull/3556
Enables the Pro-Grade security manager on the JVM running the standalone Solr instance.
@mcalcote 
@ahoffer 
@coyotesqrl 
@stustison
Run itests and verify that all Solr functionality such and ingest, query, and retrieval still work as expected.
[DDF-4053](https://codice.atlassian.net/browse/DDF-4035) …
=> [2.13.x] DDF-4035: Add Policies and Enable Sec Manager for Standalone Solr

distribution/solr-distro/assembly.xml, distribution/solr-distro/pom.xml, distribution/solr-distro/src/main/resources/bin/solr, distribution/solr-distro/src/main/resources/bin/solr.cmd, distribution/solr-distro/src/main/resources/security/solr-default.policy
2.13.x port: https://github.com/codice/ddf/pull/3626
Enables the Pro-Grade security manager on the JVM running the standalone Solr instance.
@mcalcote 
@ahoffer 
@coyotesqrl 
@stustison
Run itests and verify that all Solr functionality such and ingest, query, and retrieval still work as expected.
[DDF-4053](https://codice.atlassian.net/browse/DDF-4035) …
=> DDF-4035: Add Policies and Enable Sec Manager for Standalone Solr

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/catalog/CatalogApplication.java
I closed a stream that shouldn't have been closed and it was caught in the forward port #3588 
Closes input streams in Catalog Application
@bakejeyner @blen-desta @brjeter 
@coyotesqrl
@stustison 
@rzwiefel 
1) Install DDF
2) hit https://localhost:8993/search/catalog/internal/catalog/:id
I did this through postman with the following headers: 
``` 
Host: localhost:8993
Referer: https://localhost:8993/admin/
X-Requested-With: XMLHttpRequest
```
You can get an id by navigating to details in intrigue:
Nothing should break. 👍 
3) hit https://localhost:8993/search/catalog/internal/catalog/:sourceid/:id with the same postman headers
Nothing should break. 👍 
[DDF-4016](https://codice.atlassian.net/browse/DDF-4016) …
=> [2.13.x] DDF-4016 the response will close the output stream when it's ready

distribution/ddf-common/src/main/resources-filtered/etc/system.properties, distribution/ddf-common/src/main/resources/bin/ddf.bat, distribution/docs/src/main/resources/content/_configuring/global-settings.adoc
reverts a small portion of https://github.com/codice/ddf/pull/3612
@bdeining @ahoffer 
No hero necessary since its reverting it to what it was previously (a known working state).
=> DDF-2824 revert start.solr variable name

dependency-check-maven-config.xml
Suppresses two CVEs.
Getting OWASP failures on CVE-2017-7658 and CVE-2017-7657, but these don't actually apply to the version of Jetty that DDF is using.
@bdeining 
@stustison 
[DDF-4087](https://codice.atlassian.net/browse/DDF-4087) …
=> DDF-4087 Suppressing jetty CVEs that don't apply to DDF

ui/packages/catalog-ui-search/src/main/webapp/component/visualization/low-bandwidth-map/low-bandwidth-map.hbs, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/low-bandwidth-map/low-bandwidth-map.view.js
Currently low bandwidth mode brings up the map visuals with a large green continue button.  This is a little vague in purpose, (does it continue low band-width?  does it continue to the map?) Perhaps a "continue to map anyway" and "close map" options would be better so it is clear to what the user wants to do.
https://localhost:8993/search/catalog/?lowBandwidth
@GabrielFabian  
@gjvera 
@bdeining
[DDF-4098](https://codice.atlassian.net/browse/DDF-4098) …
=> DDF-4098 Low bandwidth map buttons should be more clear

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/cql/CqlQueryResponse.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/ws/JsonRpc.java
This is a bug fix for intrigue failing to find results when websockets are enabled. In a previous commit a `@JsonIgnore` annotation was added to the CqlQueryResponse class. Several classes use Boon to deserialize the response, but they need to specify that they include annotations. Since the JsonRpc mapper didn't include annotations the json failed to deserialize causing the `/wc` endpoint to fail.
@bellcc 
@leo-sakh 
@peterhuffer 
@Schachte 
@bdeining
@millerw8
- Make sure websockets are enabled (System > Catalog Search UI)
- Inject one or more metacards and run a search query through intrigue, confirming that the metacards are found.
[DDF-4048](https://codice.atlassian.net/browse/DDF-4084) …
=> DDF-4084 Intrigue fails to find results with Websockets enabled

distribution/ddf-common/src/main/resources-filtered/etc/application-definitions/admin.json, features/apps/src/main/feature/feature.xml, platform/admin/modules/admin-modules-application/src/test/resources/application-service-array.json
Fixes typo in Admin UI which read "Admin UI **provides contains** modules allowing the administrator to access ..."
@ethantmanns @tbatie 
@shaundmorris 
Verify hovering over the Admin description box in the UI shows the typo is no longer there …
=> DDF-2824 Fixes typo "provides contains" in Admin UI

distribution/docs/src/main/resources/content/_running/ui-ingest.adoc, distribution/docs/src/main/resources/content/_using/using-catalog-search-ui.adoc
Link to 2.13.x PR: #3622
____
Updates docs to mention limitations to uploading metadata to Intrigue.
@jhunzik @tyler30clemens @paouelle @figliold 
@rzwiefel
@tbatie
Build and verify docs
=> DDF-4073 Document Intrigue metadata upload limitations (#3622)

ui/packages/catalog-ui-search/package.json, ui/yarn.lock
=> Backport usng version fix

platform/security/filter/security-filter-csrf/src/main/java/org/codice/ddf/security/filter/csrf/CsrfFilter.java
Link to 2.13.x PR: [DDF-4060 2.13.x PR](https://github.com/codice/ddf/pull/3673)
Updates the CSRF filter to allow any hostnames set since last restart. This will allow requests with localhost origin to work until the system is restarted, allowing the installer to finish without errors.
@blen-desta 
@mcalcote 
@stustison
@tbatie
Install with `?dev=true`, change the hostname during setup, ensure that the restart now button at the end of the installer actually restarts the system instead of the jolokia request returning a 403. After install, check that the hostname was updated to the new hostname.
Error was caused by the CSRF filter updating to the new hostname and enforcing the same-origin requirement before the installer was finished installing. Since the browser was still …
=> DDF-4060: Fixes restart button for dev=true

catalog/core/catalog-core-impl/filter-proxy/src/main/java/ddf/catalog/filter/proxy/adapter/GeotoolsFilterAdapterImpl.java, catalog/core/catalog-core-impl/filter-proxy/src/main/java/ddf/catalog/filter/proxy/adapter/PeriodParser.java, catalog/core/catalog-core-impl/filter-proxy/src/test/java/ddf/catalog/filter/proxy/adapter/test/FilterAdapterTest.java
Gives GeotoolsFilterAdapterImpl the ability to process relative time
filters that contain decimal values and adds a test for the new
functionality. Also corrects some static analysis findings involving repeated strings.
Note: searches can be inexact when given a year or month decimal value due to the difficulty of accounting for a leap day and varying month lengths in a decimal unit. The actual period parsed
will be longer than the given value by a maximum of 6 hours (when given X.9999.. years)
@peterhuffer @emmberk @oconnormi 
@clockard
@tbatie 
Unit tests. Verify that relative time search works as it did before and works when given decimal values. This isn't how we usually test but I also highly suggest putting a break point in GeotoolsFilterAdapterImpl to check that the …
=> DDF-3952 Fix backend to allow relative time queries with decimals

catalog/transformer/catalog-transformer-html/src/main/resources/OSGI-INF/metatype/metatype.xml, catalog/transformer/catalog-transformer-html/src/main/resources/templates/template.hbs
- Addresses comments that came up while performing further testing
- When hiding empty attributes row colors update to alternate
- Updates default html category title
@jrnorth 
@djblue 
@willwill96 
@bdeining 
@rzwiefel 
1. Full Build
2. Export a single metacard and a result set as HTML
3. Verify that when hiding empty attributes the row colors alternate
[DDF-4043](https://codice.atlassian.net/browse/DDF-4043) …
=> DDF-4043 HTML Export Quality of Life Changes

features/security/pom.xml, features/security/src/main/feature/feature.xml, platform/security/idp/security-idp-plugin/pom.xml, platform/security/idp/security-idp-plugin/security-idp-plugin-namequalifier/pom.xml, platform/security/idp/security-idp-plugin/security-idp-plugin-namequalifier/src/main/java/org/codice/ddf/security/idp/plugin/namequalifier/NameQualifierPresignPlugin.java, platform/security/idp/security-idp-plugin/security-idp-plugin-namequalifier/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/security/idp/security-idp-plugin/security-idp-plugin-namequalifier/src/test/groovy/org/codice/ddf/security/idp/plugin/namequalifier/NameQualifierPresignPluginSpec.groovy
Backport of https://github.com/codice/ddf/pull/3354
The IdP should add its entity ID in the NameQualifier field of all Persistent Identifiers
@bantillo @brjeter @bakejeyner 
@coyotesqrl
@shaundmorris
Run the [SAML-CTK](https://github.com/codice/saml-conformance) tests against it.
[DDF-3903](https://codice.atlassian.net/browse/DDF-3903) …
=> [2.13.x] DDF-3903 The IdP should add its entity ID in the NameQualifier field of all Persistent Identifiers

catalog/ui/catalog-ui-search/pom.xml, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/handlers/CqlTransformHandler.java, catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/query/handlers/CqlTransformHandlerTest.java
The queryResponseTransformer for csv export was utilized in `/transform/csv` and is being replaced by `cql/transform/{transformerId}`.
With the new endpoint, adding arguments and requesting a csv file results in an empty file (a valid file returns when only null arguments are in the json payload).
The argument structure for the csv transformer is different than other queryResponseTransformers, this includes an adapter for the arguments, incorporating some of the logic of the old endpoint to the new one allowing for these arguments to be sent to the csv transformer.
Update: this PR also adds updates in the endpoint to allow the CSW transformer to export properly with a cql request
@brianfelix 
@bellcc 
@leo-sakh 
@bdeining
@rzwiefel 
use …
=> DDF-4120 Modify Cql Transform Handler to adapt to existing CSV and CSW Transformers
