codice/ddf

platform/solr/solr-factory/src/test/groovy/org/codice/solr/factory/impl/EmbeddedSolrFilesSpec.groovy

Fixes a test case that fails on Windows.
@emanns95 
@peterhuffer 
@jhunzik 
@figliold
run the tests on windows
[DDF-3621](https://codice.atlassian.net/browse/DDF-3621) …

DDF-3621 Fixed test case to work on Windows

---

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/SolrCache.java

It changes the logging of Solr failures while trying to expire the cache such that if it occurs because Solr is unavailable, only debug traces are generated such as not to pollute logs. 
It also changes the normal INFO log in all other cases to move the stack trace to DEBUG instead.
In addition, it addresses 2 SonarQube issue reported in that file.
@tbatie 
@jhunzik 
@emanns95 
@figliold
@lessarderic
Startup DDF and verify that the following log not longer shows up at INFO level
```
... | SolrCache                        | ... | ... - catalog-core-standardframework - 2.12.0.SNAPSHOT | Unable to …
```

DDF-3621 Downgraded logs during caching expiration when the failure is due to Solr being unavailable

---

distribution/docs/src/main/resources/content/_running/directory-monitor-ingest.adoc
distribution/docs/src/main/resources/content/_running/external-ingest.adoc
distribution/docs/src/main/resources/content/_running/ingest-command.adoc
distribution/docs/src/main/resources/content/_using/using-catalog-search-ui.adoc

Describe how each ingest method notifies user/admin of failure to ingest.
@ahoffer @austinsteffes @garrettfreibott 
@codice/docs 
@ricklarsen - Documentation @rzwiefel
Read the changes. Build the docs module and view the formatting 
[DDF-3873](https://codice.atlassian.net/browse/DDF-3873) …

DDF-3873 Update ingest instructions to help with failed operations

---

catalog/core/catalog-core-directorymonitor/pom.xml
catalog/spatial/csw/spatial-csw-transformer/pom.xml
catalog/spatial/kml/spatial-kml-networklinkendpoint/pom.xml
catalog/spatial/registry/registry-publication-action-provider/pom.xml
catalog/ui/catalog-ui-search/pom.xml
distribution/kernel/pom.xml
features/security/pom.xml
pom.xml

Fixes build issues printed out at the top of build concerning misconfigured pom files
(like duplicate dependencies, missing versions, etc).
anyone
build
https://codice.atlassian.net/browse/DDF-3880
**FROM THIS:**
**TO THIS:** …

DDF-3880 Resolve mvn build warnings

---

platform/security/rest/security-rest-cxfwrapper/src/main/java/org/codice/ddf/cxf/paos/PaosInInterceptor.java
platform/security/rest/security-rest-cxfwrapper/src/test/java/org/codice/ddf/cxf/paos/PaosInInterceptorTest.java

Previously, the PaosInInterceptor would not forward the original headers
which would cause things to break. Now we add the original headers back in
as would be expected of a request that was not intercepted at all.
anyone @clockard @stustison 
Setup Two DDFs via CSW with IDP enabled as the authentication mechanism, ensure you can download a product from DDF B where the product was ingested into DDF A. Also it may not hurt to enable fanout proxy on  DDF B and ensure you can still download the product from there. 
the `PaosInInterceptor` was not forwarding the correct headers causing things like ECP to not function correctly. 
https://codice.atlassian.net/browse/DDF-3860
- [na] Documentation Updated
- [na] Update / Add Integration Tests …

DDF-3860 PaosInInterceptor now forwards headers

---

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/forms/filter/FilterWriter.java
catalog/ui/catalog-ui-search/src/main/resources/schemas/ows19115subset.xsd
catalog/ui/catalog-ui-search/src/main/resources/schemas/owsAll.xsd
catalog/ui/catalog-ui-search/src/main/resources/schemas/owsCommon.xsd
catalog/ui/catalog-ui-search/src/main/resources/schemas/owsContents.xsd
catalog/ui/catalog-ui-search/src/main/resources/schemas/owsDataIdentification.xsd
catalog/ui/catalog-ui-search/src/main/resources/schemas/owsDomainType.xsd
catalog/ui/catalog-ui-search/src/main/resources/schemas/owsExceptionReport.xsd
catalog/ui/catalog-ui-search/src/main/resources/schemas/owsGetCapabilities.xsd
catalog/ui/catalog-ui-search/src/main/resources/schemas/owsGetResourceByID.xsd
catalog/ui/catalog-ui-search/src/main/resources/schemas/owsInputOutputData.xsd
catalog/ui/catalog-ui-search/src/main/resources/schemas/owsManifest.xsd
catalog/ui/catalog-ui-search/src/main/resources/schemas/owsOperationsMetadata.xsd
catalog/ui/catalog-ui-search/src/main/resources/schemas/owsServiceIdentification.xsd
catalog/ui/catalog-ui-search/src/main/resources/schemas/owsServiceProvider.xsd
catalog/ui/catalog-ui-search/src/main/resources/schemas/xlink.xsd
catalog/ui/catalog-ui-search/src/main/resources/schemas/xml.xsd

**Important!** Look at the commits. The first one is just schema files. The 2nd one has meaningful code changes. 
Fixes an issue where, on bundle start, `catalog-ui-search` will make web requests for schema document `<import>` dependencies that were missed the first time. The remaining schemas have been added as JAR resources and the `FilterWriter` will transform `schemaLocation` URIs to point to the local copy. 
As a direct consequence of this, `catalog-ui-search` starts up significantly faster now. And no errors should occur when an internet connection is not available. 
@dannythk 
@Schachte 
@rzwiefel  
@coyotesqrl 
Build the DDF zip. Disconnect from all networks before deploying. Validate this first by trying to load a web page and ensure the browser-specific "No …

DDF-3872 Installation cannot successfully complete in an isolated, offline environment due to remote schema loading

---

distribution/ddf-common/src/main/resources/security/default.policy

Adds permissions that are needed to run Catalog commands via the `bin/client` script. See the ticket for details.
@coyotesqrl 
@stustison
- Build DDF
- Run `bin/ddf` and, once it's ready, install using `profile:install standard`
- In a separate window, use the `bin/client` script to ssh in.
- On the new window, run any catalog command (`latest` is an easy one). There should be no `AccessControlException`s printed out.
[DDF-3897](https://codice.atlassian.net/browse/DDF-3897)
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+R …

DDF-3897 Add permissions for Catalog commands via SSH

---

catalog/core/catalog-core-camelcomponent/pom.xml
catalog/core/catalog-core-camelcomponent/src/main/java/ddf/camel/component/catalog/inputtransformer/InputTransformerProducer.java
catalog/core/catalog-core-camelcomponent/src/test/java/ddf/camel/component/catalog/inputtransformer/InputTransformerProducerTest.java
catalog/core/catalog-core-camelcomponent/src/test/resources/file.txt

- Cherry pick of https://github.com/codice/ddf/pull/3313
- Adds some unit tests for InputTransformerProducer
@paouelle @ethantmanns 
@coyotesqrl 
CDM unit + component tests and TestCatalog itests, preferably on Windows.
CatalogCamelComponent unit tests. 
[DDF-3660](https://codice.atlassian.net/browse/DDF-3660) …

DDF-3660 Properly close file handle in InputTransformerProducer

---

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/OperationsMetacardSupport.java
catalog/core/catalog-core-standardframework/src/test/groovy/ddf/catalog/impl/operations/OperationsMetacardSupportSpec.groovy
catalog/plugin/catalog-plugin-checksum/pom.xml
catalog/plugin/catalog-plugin-checksum/src/main/java/org/codice/ddf/catalog/content/plugin/checksum/Checksum.java
catalog/plugin/catalog-plugin-checksum/src/test/java/org/codice/ddf/catalog/content/plugin/checksum/ChecksumTest.java

Port of https://github.com/codice/ddf/commit/005905ea0129c67ada72a9d6aca1e789419f6c08
@emmberk @clockard @kcover 
@coyotesqrl
Unit tests
[DDF-3889](https://codice.atlassian.net/browse/DDF-3889)
- ❓ (Question …

DDF-3889 Accept qualified content item's metacard

---

ui/packages/catalog-ui-search/src/main/webapp/component/paging/paging.hbs
ui/packages/catalog-ui-search/src/main/webapp/component/paging/paging.less
ui/packages/catalog-ui-search/src/main/webapp/component/result-selector/result-selector.less

See title.
@adimka 
@bdeining
- quick build
- open Intrigue 
- ensue more button doesn't overflow
[DDF-3909](https://codice.atlassian.net/browse/DDF-3909) …

[2.12.x] DDF-3909 Updates paging buttons to use less vars

---

ui/packages/catalog-ui-search/src/main/webapp/component/paging/paging.hbs
ui/packages/catalog-ui-search/src/main/webapp/component/paging/paging.less
ui/packages/catalog-ui-search/src/main/webapp/component/result-selector/result-selector.less

DDF-3909 Updates paging buttons to use less vars

---

distribution/ddf-common/src/main/resources-filtered/etc/custom.properties
platform/admin/admin-app/src/main/resources/features.xml
platform/admin/modules/admin-modules-docs/pom.xml

Currently downstream projects rely on sun.reflect, which is not currently exported from bundle 0. sun.reflect is used explicitly in libraries like Spark Core. In DDF, we embed Spark Core, which explains why we haven't added this change yet, however, downstream, we actually use Spark as a bundle. 
@middlets719 
@bdeining 
@tbatie 
@Bdthomson  …

DDF-3910 Removed spark-core embed from admin-docs-ui and started spark-core as a bundle

---

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/config/ConfigurationApplication.java
catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.config.xml
catalog/ui/search-ui-app/src/main/resources/etc/org.codice.ddf.catalog.ui.config.config
distribution/docs/src/main/resources/content/_tables/catalog.ui.config.adoc

Fixes wording in Catalog UI configuration to eliminate inconsistent uses of Disable/Enable and groups all Boolean values together
@Bdthomson 
@bdeining 
@jlcsmith 
- build
- install
- verify default Boolean values in catalog ui config
- verify that ui doesn't have any regressions
[DDF-3867](https://codice.atlassian.net/browse/DDF-3867) …

DDF-3867 made Booleans in Catalog UI config consistent

---

ui/packages/catalog-ui-search/package.json
ui/packages/catalog-ui-search/src/main/webapp/js/router/routes-loader.js
ui/yarn.lock

- This allows downstream distributions to utilize a mix of upstream components and downstream components.
@clockard
@djblue 
Verify that Intrigue still works properly in plain DDF.  
[DDF-3838](https://codice.atlassian.net/browse/DDF-3838)

DDF-3838 Updates router loader to add dynamic path resolution

---

ui/README.md
ui/package.json
ui/packages/ace/bin.js
ui/packages/ace/lib/disable-idp.js

- Updates `ui/README.md` with more getting started information
- Adds new `ace disable-idp` command
@tbatie 
@codice/ui 
@bdeining  
- Review documentation changes
- Quick build
- Start DDF
- Run `yarn disable-idp`
- Run `yarn start` for any ui
- Ensure ui works without any idp issues …

DDF-3719 Improves UI developer documentation

---

distribution/ddf-common/src/main/resources/security/default.policy

gets rid of permission denied when starting up resourcemanagment-app
@ahoffer 
@brjeter 
@coyotesqrl
@stustison 
build DDF
Go to Admin UI
Go to System tab
Go to Feature tab
Install feature: resourcemanagement-app 
No AccessControlException should come up in the logs
[DDF-3927](https://codice.atlassian.net/browse/DDF-3927) …

DDF-3927 Adding resourcemanagement-usage-ui to createClassLoader

---

pom.xml

Upgrades fabric8
@mackncheesiest @mcalcote 
@stustison @coyotesqrl 
[DDF-3923](https://codice.atlassian.net/browse/DDF-3923)

DDF-3923 Upgraded fabric8 to 3.0.12

---

catalog/core/catalog-core-urlresourcereader/src/main/java/ddf/catalog/resource/impl/URLResourceReader.java
distribution/ddf-common/src/main/resources/security/configurations.policy

- Add Privileged Actions to URLResourceReader
- Update CDM configurations.policy section
- Fixes a few SonarQube findings
@clockard @emmberk @kcover 
@coyotesqrl
@stustison
Follow documentation to configure a CDM for in place directory and verify the ingested products can be downloaded via Intrigue.
This change makes it so when downloading products ingested via the CDM  configured for a in place directory, that permissions do not need to be added for every type of endpoint that the product can be downloaded through. Originally, each endpoint would need to permissions to read from the configured …

DDF-3660 Add Privileged Actions to URLResourceReader

---

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/forms/SearchFormsLoader.java

Increases the wait time for the SearchFormsLoader to see updates from the Source Poller.
@Lambeaux @Bdthomson 
@bdeining
@jlcsmith …

DDF-3937 Increased polling time for SearchFormsLoader

---

distribution/docs/src/main/resources/content/_installing/installing-intro.adoc

Increased minimum and recommended disk space requirements to 40GB and 80GB respectively.
@johnsliao  
@beyelerb 
@ricklarsen
@shaundmorris
Full build.
[DDF-3935](https://codice.atlassian.net/browse/DDF-3935)
- ❓ (Question …

DDF-3935 Increase Minimum and Recommended Disk Space Requirements

---

catalog/spatial/kml/spatial-kml-transformer/src/main/java/org/codice/ddf/spatial/kml/transformer/KMLTransformerImpl.java
catalog/spatial/kml/spatial-kml-util/pom.xml
catalog/spatial/kml/spatial-kml-util/src/main/java/org/codice/ddf/spatial/kml/converter/MetacardToKml.java
catalog/spatial/kml/spatial-kml-util/src/test/java/org/codice/ddf/spatial/kml/converter/MetacardToKmlTest.java

Refactors MetacardToKml's `createKmlGeoFromWkt` method to do only what it's name implies and pull some inner logic into another method.
@glenhein 
@brianfelix 
@bdeining
@coyotesqrl
Full build should suffice, refactored a couple methods without changing functionality.
Currently the `createKmlGeoFromWkt` method has side effects that are unclear until digging into the function.
[DDF-3837](https://codice.atlassian.net/browse/DDF-3837)
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging …

DDF-3837 Refactoring MetacardToKml to multiple methods

---

ui/packages/catalog-ui-search/src/main/webapp/js/controllers/ol.layerCollection.controller.js

Modified the AGM source to include a function to map tile position to URL correctly.
This fix adds a tiling function to the AGM source
@djblue 
@AzGoalie 
@millerw8
1) build and deploy the catalog-ui-search bundle
2) In the admin console (Search UI -> Configuration -> org.codice.ddf.catalog.ui.config) under Imagery Providers insert the following:
[ 
{"parameters":{"transparent":false,"format":""},
"name":"ArcGIS",
"order":0,
"url":"https://services.arcgisonline.com/arcgis/rest/services/ESRI_Imagery_World_2D/MapServer/",
"proxyEnabled":false,
"withCredentials":true,
"type":"AGM",
"show":true,
"projection":"EPSG:4326",
"alpha":1}
]
3) In the admin console (Search UI -> …

DDF-3942: ArcGIS Tile Layer Not Rendering Correctly

---

catalog/rest/catalog-rest-endpoint/src/main/java/org/codice/ddf/endpoints/rest/RESTEndpoint.java
catalog/rest/catalog-rest-endpoint/src/test/java/org/codice/ddf/endpoints/rest/RestEndpointTest.java
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/config/ConfigurationApplication.java
catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.config.xml
catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/config/ConfigurationApplicationTest.java
distribution/docs/src/main/resources/content/_configuring/upload-editor-intrigue.adoc
distribution/docs/src/main/resources/content/_tables/catalog.ui.config.adoc
distribution/docs/src/main/resources/content/_using/using-catalog-search-ui.adoc
ui/packages/catalog-ui-search/src/main/webapp/component/component.less
ui/packages/catalog-ui-search/src/main/webapp/component/ingest-details/ingest-details.view.js
ui/packages/catalog-ui-search/src/main/webapp/component/ingest-editor/ingest-editor.hbs
ui/packages/catalog-ui-search/src/main/webapp/component/ingest-editor/ingest-editor.less
ui/packages/catalog-ui-search/src/main/webapp/component/ingest-editor/ingest-editor.view.js
ui/packages/catalog-ui-search/src/main/webapp/component/ingest/ingest.less
ui/packages/catalog-ui-search/src/main/webapp/component/ingest/ingest.view.js
ui/packages/catalog-ui-search/src/main/webapp/component/input/enum/input-enum.view.js
ui/packages/catalog-ui-search/src/main/webapp/component/input/geometry/input-geometry.view.js
ui/packages/catalog-ui-search/src/main/webapp/component/input/input.view.js
ui/packages/catalog-ui-search/src/main/webapp/component/list-item/list-item.view.js
ui/packages/catalog-ui-search/src/main/webapp/component/property/property.collection.view.js
ui/packages/catalog-ui-search/src/main/webapp/component/property/property.hbs
ui/packages/catalog-ui-search/src/main/webapp/component/property/property.js
ui/packages/catalog-ui-search/src/main/webapp/component/property/property.less
ui/packages/catalog-ui-search/src/main/webapp/component/property/property.view.js
ui/packages/catalog-ui-search/src/main/webapp/component/singletons/metacard-definitions.js
ui/packages/catalog-ui-search/src/main/webapp/component/tabs/list-add/tabs-list-add.js
ui/packages/catalog-ui-search/src/main/webapp/component/value/value.js
ui/packages/catalog-ui-search/src/main/webapp/js/ApplicationSetup.js
ui/packages/catalog-ui-search/src/main/webapp/js/Marionette.Region.js

This PR adds an attribute editor to the Intrigue uploader that allows users to set attribute values that will be applied on upload. It's similar to the existing metacard edit capability, but users can set attributes and upload in one step now. Administrators can configure which attributes users can set, and can require that users set certain attributes before uploading.
If the editor is configured without any attributes, the uploader reverts to its existing behavior.
@alexaabrd @vinamartin @djblue 
@codice/ui 
Build and verify that:
* The editor is not shown if no attributes are configured (attributes …

DDF-3896 Add Intrigue upload editor

---

distribution/ddf-common/src/main/resources/security/default.policy
platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/ImportMigrationEntryImpl.java
platform/security/common/src/main/java/org/codice/ddf/security/common/Security.java

Added new auth permissions for the Security class which will become useful when we stop embedding that project.
It fixes the security policy and one issue in migration to work with the security manager.
It also extends privileges in the Security class whenever using the system subject. However, this will only start being useful when we stop embedding the corresponding jar.
@tbatie 
@jhunzik 
@ethantmanns 
@figliold
@stustison
**This should be tested with a downstream distribution**
- Unzip and perform a migration:export
- Copy the 3 generated files somewhere safe
- Go through the installation
- …

DDF-3932 Fixed security for migration import/export

---

ui/packages/catalog-ui-search/src/main/webapp/component/query-settings/query-settings.view.js

Adds extensibility plugin support to query-settings.
@djblue @GabrielFabian @mackncheesiest 
@bdeining
CI build, verify UI loads properly, and you can view query settings. …

DDF-3719 Add query-settings extensibility

---

libs/libs-pomfix/package.json
libs/libs-pomfix/yarn.lock

Upgrade Cheerio version
@djblue @mackncheesiest 
@jlcsmith
Full Build
[DDF-3949 ](https://codice.atlassian.net/browse/DDF-3949 ) …

DDF-3949 Cheerio version

---

ui/packages/catalog-admin-module-maplayers/src/main/webapp/map-layers/reducer.js

Fixes a bug in adding/saving map layers in the catalog  
Servlet is expecting 'X-Requested-With' header from the client in [CsrfFilter.java](https://github.com/codice/ddf/blob/826e07f8ec132d6102e35c4977aa93f5fb2e0295/platform/security/filter/security-filter-csrf/src/main/java/org/codice/ddf/security/filter/csrf/CsrfFilter.java#L106), which wasn't present before  
@dcruver 
@bdeining
@jlcsmith
1. Launch DDF and login to the admin console  
2. Click on Catalog  
3. You should be in a tab labeled "Map Layers Configuration". Click the + button to add a new layer
4. Enter a name and a valid provider (e.g: https://server.arcgisonline.com/arcgis/rest/services/World_Imagery/MapServer) and the respective provider type (e.g. ArcGIS Map Server)
5. …

DDF-3948 Fixed Map Layer Configuration

---

catalog/transformer/catalog-transformer-propertyjson-metacard/src/main/java/ddf/catalog/transformer/metacard/propertyjson/PropertyJsonMetacardTransformer.java
catalog/transformer/catalog-transformer-propertyjson-metacard/src/test/groovy/ddf/catalog/transformer/metacard/propertyjson/PropertyJsonMetacardTransformerSpec.groovy

Adds a simple check to make sure we don't get a class cast exception when transforming metacards to json
@rzwiefel
CI build should be sufficient
[DDF-3934](https://codice.atlassian.net/browse/DDF-3934)

DDF-3934 Protect against class cast exception in PropertyJsonMetacardTransformer

---

platform/solr/solr-factory/src/main/java/org/codice/solr/factory/impl/HttpSolrClientFactory.java

Ensure that the temporary http client would be closed no mater what.
@jhunzik 
@ethantmanns 
@figliold
@coyotesqrl
@rzwiefel 
Build pass. 
It will be almost impossible to reproduce this particular error scenario as it would require a runtime exception to happen in the constructor of a 3rd party class.
[DDF-3959](https://codice.atlassian.net/browse/DDF-3959) …

DDF-3959 Ensure socket is closed in HttpSolrClientFactory 

---

distribution/docs/src/main/resources/content/_appReferences/mg-ui.adoc
distribution/docs/src/main/resources/content/_catalogFrameworks/.asciidoctor/diagram/catalog_architecture_framework.png.cache
distribution/docs/src/main/resources/content/_catalogFrameworks/.asciidoctor/diagram/ingest_request.png.cache
distribution/docs/src/main/resources/content/_catalogFrameworks/.asciidoctor/diagram/product_retrieval_request.png.cache
distribution/docs/src/main/resources/content/_catalogFrameworks/.asciidoctor/diagram/query_request.png.cache
distribution/docs/src/main/resources/content/_endpoints/cometd-endpoint.adoc
pom.xml

adds `deprecated` notation to sections deprecated in next release. 
@mcalcote @rzwiefel @austinsteffes @garrettfreibott 
@lessarderic
@shaundmorris
- builds successfully
- deprecation warning appears and is formatted correctly.
[DDF-3954](https://codice.atlassian.net/browse/DDF-3954) …

DDF-3954 added deprecation label to deprecated features

---

distribution/ddf-common/src/main/resources/security/default.policy
features/migration/src/main/feature/feature.xml
features/security/src/main/feature/feature.xml

Fixed a permission mistake where the etc directory was duplicated.
Also modified the security feature to ensure that the security migratable would be started.
@brjeter 
@jhunzik 
@ethantmanns 
@figliold
@coyotesqrl 
**This should be tested with a downstream distribution**
- Unzip and perform a migration:export
- Copy the 3 generated files somewhere safe
- Go through the installation
- Perform a migration:export
- Copy the 3 generated files somewhere safe
- Copy back the files exported the first time around and perform a migration:import --profile
- Verify through the UI that the system is back to …

DDF-3932 Fixed security-migratable permissions and made sure it would be started

---

libs/test-common/pom.xml
libs/test-common/src/main/java/org/codice/ddf/test/common/features/FeatureUtilities.java

Addresses DDF-related security issues that came up in Fortify. 
@mackncheesiest @mojogitoverhere 
@bdeining
@millerw8 
Make sure it passes a full build
[DDF-3953](https://codice.atlassian.net/browse/DDF-3953) …

DDF-3953 Improve DDF based on static analysis results

---

ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/cesium/map.cesium.js

- Previously if cesium hit an issue with a terrain provider (bad url, offline, etc.) it would not fail gracefully (fail to load imagery providers, etc.).  Now it will fallback to the default cesium terrain provider.
@mcalcote 
@rzwiefel 
@djblue 
@ethantmanns 
@clockard 
Configure a bad terrain provider (either with a bad url or a bad type, or without a type) and verify that the UI loads correctly.  There should be warnings in the console that indicate what has gone wrong.
[DDF-3966](https://codice.atlassian.net/browse/DDF-3966)

DDF-3966 Updates cesium map to handle terrain provider issues

---

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/util/EndpointUtil.java

fixed result sorting with modified date as primary and id as secondary
NATURAL_ORDER is omitted by SolrClient, hence results are not sorted
When SolrClient return unsorted result combining with paging, duplicate results are returned on the second page. Resulting in missing result set.
replacing with SortByImpl to specify property to sort by.
@millerw8
@bdeining
@rzwiefel
Ask 2 committers to review/merge the PR and tag them here. If you don't know who to ask, you can request reviews in https://groups.google.com/forum/#!forum/ddf-developers .
@millerw8
@bdeining
@rzwiefel
Navigate with workspace or use this link …

DDF-3894 fixed result sorting with modified date as primary and id as secondary

---

libs/libs-pomfix-run/pom.xml
libs/libs-pomfix/pom.xml

@LinkMJB 
@Schachte 
@bdeining
- mvn clean install

DDF-3719 Adds type to pom-fix artifact to fix build issues

---

catalog/ui/catalog-ui-search/catalog-ui-search.xml
catalog/ui/catalog-ui-search/pom.xml

Attach catalog-ui-search src code zip so that it can be extensible
@SmithJosh @vinamartin @Variadicism 
@rzwiefel
[DDF-3957](https://codice.atlassian.net/browse/DDF-3957) …

DDF-3957 Attach catalog-ui-search src code zip

---

dependency-check-maven-config.xml

Suppresses CVE-2018-1275.
@brjeter 
@ryeats 
@clockard
@shaundmorris
Full build with no OWASP failures.
[DDF-3970](https://codice.atlassian.net/browse/DDF-3970) …

DDF-3970 Address OWASP finding related to Spring Framework's spring-messaging module

---

catalog/spatial/geocoding/pom.xml
catalog/spatial/geocoding/spatial-geocoding-api/src/main/java/org/codice/ddf/spatial/geocoding/GeoCoderService.java
catalog/spatial/geocoding/spatial-geocoding-endpoint/pom.xml
catalog/spatial/geocoding/spatial-geocoding-endpoint/src/main/java/org/codice/ddf/spatial/geocoder/endpoint/GeoCoderEndpoint.java
catalog/spatial/geocoding/spatial-geocoding-endpoint/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/spatial/geocoding/spatial-geocoding-geocoder/src/main/java/org/codice/ddf/spatial/geocoder/impl/GeoCoderServiceImpl.java
catalog/spatial/geocoding/spatial-geocoding-geocoder/src/main/java/org/codice/ddf/spatial/geocoder/impl/JsonpValidator.java
catalog/spatial/geocoding/spatial-geocoding-geocoder/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/spatial/geocoding/spatial-geocoding-geocoder/src/test/java/org/codice/ddf/spatial/geocoder/impl/GeoCoderServiceImplTest.java
catalog/spatial/geocoding/spatial-geocoding-geocoder/src/test/java/org/codice/ddf/spatial/geocoder/impl/JsonpValidatorTest.java
catalog/spatial/spatial-app/pom.xml
catalog/spatial/spatial-app/src/main/resources/features.xml
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/spatial/GeoCoderApplication.java
catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/blueprint/blueprint.xml
ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/cesium/geocoder.js
ui/packages/catalog-ui-search/src/main/webapp/js/view/openlayers.geocoder.js

**This is PR 4/7**
- Moved GeoCoderEndpoint to new module
- Created new endpoint under /search/catalog/internal
- Changed urls in catalog-search-ui to use new endpoints
@brjeter @peterhuffer  
@clockard
@coyotesqrl
TBD …

DDF-3941 - Moved intrigue from using the GeoCoderEndpoint under /services

---

catalog/ui/catalog-ui-search/pom.xml
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/configuration/PlatformUiConfigurationApplication.java
catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/blueprint/blueprint.xml
features/admin/pom.xml
features/admin/src/main/feature/feature.xml
platform/platform-configuration-endpoint/pom.xml
platform/platform-configuration-endpoint/src/main/java/org/codice/ddf/configuration/endpoint/PlatformUiConfigurationEndpoint.java
platform/platform-configuration-endpoint/src/main/resources/OSGI-INF/blueprint/blueprint.xml
platform/platform-configuration-service/pom.xml
platform/platform-configuration-service/src/main/java/org/codice/ddf/configuration/service/PlatformUiConfigurationService.java
platform/platform-configuration/pom.xml
platform/platform-configuration/src/main/java/org/codice/ddf/configuration/PlatformUiConfiguration.java
platform/platform-configuration/src/main/resources/OSGI-INF/blueprint/blueprint.xml
platform/platform-configuration/src/test/java/org/codice/ddf/configuration/PlatformUiConfigurationTest.java
platform/pom.xml
ui/packages/catalog-ui-search/src/main/webapp/js/properties.js

**This is PR 2/7**
- Moved the `/services/platform/config/ui` endpoint to PlatformUiConfigurationEndpoint
- Implementation of endpoint remains at PlatformUiConfiguration
- Created new endpoint under `/search/catalog/internal/platform/config/ui` using the same implementation
- Changed `catalog-search-ui` code to use new endpoint
@garrettfreibott @brjeter @bakejeyner 
@coyotesqrl
- Make sure the configurations like the header, footer, color etc.. work on intrigue
- Make sure from the network tab that the call is made to the `/search/catalog/internal/platform/config/ui` endpoint
- Change the platform configurations in the Admin Console under `Platform -> Configuration -> Platform UI Configuration` and make sure …

DDF-3941 - Moved intrigue from using the PlatformUiConfiguration Endpoint under /services

---

PULL_REQUEST_TEMPLATE

Add Tracy Batie and vina Martin as committers in the PR Template
Anybody 
@tbatie 
@vinamartin …

DDF-3037 added tbatie and vinamartin as committers

---

catalog/transformer/catalog-transformer-service-atom/pom.xml

Export Atom package for downstream dependencies
@GabrielFabian @mackncheesiest 
@jlcsmith
@millerw8
Full build should suffice
[DDF-3511](https://codice.atlassian.net/browse/DDF-3511) …

DDF-3511 Export Atom package for downstream dependencies

---

catalog/spatial/registry/registry-api-impl/src/main/java/org/codice/ddf/registry/api/impl/RegistryStoreImpl.java

Fixes duplicate nodes when first publishing node information
@emmberk @peterhuffer @kcover 
@figliold
@shaundmorris
Stand up 2 DDFs and install the registry on both of them.
On DDF1 add a remote registry connection to DDF2 with all the default values
On DDF2 use the admin ui Node Information tab to verify DDF1 was published
On DDF2 NodeInformation tab view the DDF1 node information and verify it is populated.
[DDF-3967](https://codice.atlassian.net/browse/DDF-3967)

DDF-3967 Fix duplicate registry leaf nodes

---

ui/packages/catalog-ui-search/src/main/webapp/component/router/router.js
ui/packages/catalog-ui-search/src/main/webapp/js/router.js

Somewhere along the line, either #3326 or #3357 made it so that attempting to use Intrigue with the `?lowBandwidth` URL param caused it to fail to load because of a listener that was firing due to the `router.set({lowBandwidth: ...})` event happening before router initialization was complete.
Rather than move this assignment to [the updateRoute](https://github.com/codice/ddf/blob/995e80b248a0f0369720dd1bcc27482aeb0db780/ui/packages/catalog-ui-search/src/main/webapp/js/router.js#L93-L97) method which is presumably called after all the necessary router information is extracted, this PR sets the parameter in the `defaults` object of the `router.js`.
I did this because, once set, that parameter will never change without triggering a full page refresh and/or navigation. It's not intended to be …

DDF-3838 Updates lowBandwidth param for router changes

---

distribution/ddf-common/src/main/resources/security/default.policy

Updates rest endpoint policy
@peterhuffer @emmberk @rzwiefel 
@shaundmorris 
@lessarderic 
CI build with itest should be sufficient 
[DDF-3975](https://codice.atlassian.net/browse/DDF-3975)

DDF-3975 Update default policy for rest endpoint

---

ui/packages/catalog-ui-search/src/main/webapp/dev/component/input-guide/input-guide.view.js

DDF-3686 Made a uri relative

---

PULL_REQUEST_TEMPLATE

Adds a commented-out note at the top of the PR template on master while abbreviated review of forward-ports from 2.13.x to master are in effect. Developers should uncomment and include the PR number of their 2.13.x PR when that is the source of the change to master.
@emmberk @peterhuffer @bakejeyner 
@clockard
@vinamartin …

DDF-XXXX Adding PR template note regarding abbreviated review for 2.13.x

---

ui/packages.xml

Adds the new codice linter in UI to packages.xml for downstream extensibility.
@djblue  
@bdeining
Full build.  …

DDF-3686 Add linter to packages.xml

---

ui/packages/catalog-ui-search/src/main/webapp/dev/component/input-guide/input-guide.view.js

Backport of https://github.com/codice/ddf/pull/3425
Changed uri path. …

[2.13.x] DDF-3686 Made a uri relative

---

ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-old.view.js
ui/packages/catalog-ui-search/src/main/webapp/js/CQLUtils.js

Search template edit does not display anyGeo point radius filters correctly
@djblue 
@bdeining
@jlcsmith
See ticket
[DDF-3940](https://codice.atlassian.net/browse/DDF-3940) …

DDF-3940 Search template edit does not display anyGeo point radius filters correctly

---

PULL_REQUEST_TEMPLATE

Comments out extra instructions that  that shouldn't appear in PR description.
@emmberk @blen-desta 
@clockard
@vinamartin …

Comments out extra instructions in PR template intended for submitters

---

PULL_REQUEST_TEMPLATE

Comments out extra instructions that  that shouldn't appear in PR description.
@emmberk @blen-desta 
@clockard
@vinamartin …

[2.13.x] Comments out extra instructions in PR template intended for submitters

---

distribution/docs/src/main/resources/content/_installing/installing-intro.adoc
distribution/docs/src/main/resources/content/_running/starting-intro.adoc
distribution/docs/src/main/resources/content/_sources/solr-catalog-provider.adoc

Update Solr version reference links in docs
@ricklarsen @ahoffer @rzwiefel @garrettfreibott @austinsteffes

2.13.X DDF-3915 Update Solr version reference links in docs

---

distribution/docs/src/main/resources/content/_installing/installing-intro.adoc
distribution/docs/src/main/resources/content/_running/starting-intro.adoc
distribution/docs/src/main/resources/content/_sources/solr-catalog-provider.adoc

Link to 2.13.x PR: #3437
____
Update Solr version reference links in docs
@ricklarsen @ahoffer @rzwiefel @garrettfreibott @austinsteffes

DDF-3915 Update Solr version reference links in docs

---

platform/solr/solr-query/src/main/java/org/codice/solr/query/SolrQueryFilterVisitor.java
platform/solr/solr-query/src/test/java/org/codice/solr/query/SolrQueryFilterVisitorTest.java

- Only cache non-null schema values in the SolrQueryFilterVisitor
@emmberk @pklinef @kcover 
@clockard
@coyotesqrl
Unit and integration tests.
When there were no existing entries in SOLR and the SolrQueryFilterVisitor cache was empty, the SolrQueryFilterVisitor would try to query SOLR for the field to get its schema. A `null` schema would be returned and cached. Since the default AttributeFormat is text, this could cause some fields to be incorrectly identified as text until a system restart.
By not caching a null value, it will cause the SolrQueryFilterVisitor to query SOLR to try to get the …

DDF-3977 Only cache non-null schema values

---

catalog/schematron/catalog-schematron-plugin/src/main/java/ddf/services/schematron/SchematronValidationService.java

Addresses DDF-related security issues that came up in Fortify. 
@mackncheesiest @shaundmorris 
@bdeining
@millerw8 
Make sure it passes a full build
[DDF-3953](https://codice.atlassian.net/browse/DDF-3953) …

DDF-3953 Security improvements based on static code analysis results

---

features/security/pom.xml
features/security/src/main/feature/feature.xml
platform/security/idp/security-idp-plugin/pom.xml
platform/security/idp/security-idp-plugin/security-idp-plugin-nameidpolicy/pom.xml
platform/security/idp/security-idp-plugin/security-idp-plugin-nameidpolicy/src/main/java/org/codice/ddf/security/idp/plugin/nameidpolicy/NameIdPolicyPresignPlugin.java
platform/security/idp/security-idp-plugin/security-idp-plugin-nameidpolicy/src/main/resources/OSGI-INF/blueprint/blueprint.xml
platform/security/idp/security-idp-plugin/security-idp-plugin-nameidpolicy/src/test/groovy/org/codice/ddf/security/idp/plugin/nameidpolicy/NameIdPolicyPresignPluginSpec.groovy
platform/security/idp/security-idp-plugin/security-idp-plugin-nameidpolicy/src/test/resources/sampleResponse.xml

[Master PR](https://github.com/codice/ddf/pull/3412)
@blen-desta 
@brjeter 
@clockard
@coyotesqrl

[2.13.x] DDF-3893 The IdP should account for the NameIDPolicy in AuthnRequests

---

distribution/ddf-common/src/main/resources/security/default.policy

Added permissions for deleting default users and to executing jaas commands
@vinamartin @brjeter 
@coyotesqrl 
@stustison 
1. Make sure the default users are deleted by the scheduler: ask me if you have questions on how to get that done
2. Make sure jaas commands work:
- Encrypting password
- In the `etc/org.apache.karaf.jaas.cfg` file, change `encryption.enabled` to true
- Make sure passwords in the `users.properties` file are encrypted
- Adding users:
- `jaas:realm-manage --index 1`
- `jaas:user-add foo bar`
- `jaas:update`
- `jaas:realm-manage --index 1`
- `jaas:user-list` - see foo as a user
- Deleting users:
- `jaas:realm-manage --index 1`
- `jaas:user-delete foo`
- `jaas:update`
- `jaas:realm-manage --index 1`
- …

DDF-3945 Added permissions for deleting default users and to executing jaas commands

---

catalog/spatial/spatial-app/src/main/resources/features.xml

Link to 2.13.x PR: https://github.com/codice/ddf/pull/3449
@bdeining @millerw8 
[DDF-3982](https://codice.atlassian.net/browse/DDF-3982)

DDF-3982 Updated the spatial-geocoding-feature bundle to start with the offline-gazetteer feature

---

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/catalog/CatalogApplication.java

Link to 2.13.x PR: https://github.com/codice/ddf/pull/3457
____
@garrettfreibott  @brjeter 
@rzwiefel

DDF-3941 Fix Metacard ID not being set in CatalogApplication

---

ui/packages/catalog-ui-search/src/main/webapp/js/cql.js

Fixes a bug where going form a search form -> basic was failing.
@Schachte @Lambeaux 
@millerw8
Build / Install / Turn on Experimental UI Features / Create `etc/forms` / Create Search Form / Switch between basic, advanced, custom forms and verify that it works correctly
[DDF-3774](https://codice.atlassian.net/browse/DDF-3774) …

DDF-3774 Fixed switching between search form -> basic

---

distribution/docs/src/main/resources/content/_running/starting-intro.adoc

Link to 2.13.x PR: #3450 
____
Revise steps in Automatically Starting Solr to account for the file structure in the distribution.
@ricklarsen @rzwiefel @ahoffer @austinsteffes @garrettfreibott @JGatley @kcover 
Read through the changes.
These steps were updated by following them to test automatic starting of the solr process. …

DDF-3915 Updated Automatically Starting Solr as a Process Documentation

---

distribution/docs/src/main/resources/content/_running/starting-intro.adoc

Revise steps in Automatically Starting Solr to account for the file structure in the distribution.
@ricklarsen @rzwiefel @ahoffer @austinsteffes @garrettfreibott @JGatley @kcover 
Read through the changes.
These steps were updated by following them to test automatic starting of the solr process. …

2.13.X DDF-3915 Updated Automatically Starting Solr as a Process Documentation

---

distribution/ddf-common/src/main/resources/security/configurations.policy
distribution/docs/src/main/resources/content/_configuring/content-directory-monitor.adoc

- Update CDM permissions. 
- Update docs
@emmberk @bakejeyner @jefchng 
@clockard
@vinamartin
Setup Move, Delete, and In Place configurations of CDM on directories outside of the user home directory according to the docs. Verify for each method that the products ingested are downloadable via Intrigue.
[DDF-3660](https://codice.atlassian.net/browse/DDF-3660) …

DDF-3660 Update CDM permissions and docs

---

catalog/spatial/registry/registry-federation-admin-service-impl/src/main/java/org/codice/ddf/registry/federationadmin/service/impl/IdentityNodeInitialization.java
catalog/spatial/registry/registry-federation-admin-service-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/spatial/registry/registry-federation-admin-service-impl/src/test/java/org/codice/ddf/registry/federationadmin/service/impl/IdentityNodeInitializationTest.java
distribution/ddf-common/src/main/resources/security/default.policy

Makes some updates to IdentityNodeInitialization to hopefully make it play nicer with the rest of the system on startup.
@emmberk @peterhuffer @kcover 
@coyotesqrl
@figliold
@rzwiefel
@shaundmorris
CI Build
[DDF-3995](https://codice.atlassian.net/browse/DDF-3995) …

DDF-3995 Update IdentityNodeInitialization to be more fault tolorant

---

distribution/ddf-common/src/main/resources/security/default.policy

Link to 2.13.x PR: [3466](https://github.com/codice/ddf/pull/3466)
____
@emmberk 
@Kjames5269 
@clockard
@coyotesqrl 

DDF-3988 Give the third-party FFmpeg library permissions to create thumbnails

---

catalog/ui/catalog-ui-search/pom.xml
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/MetacardApplication.java
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/monitor/api/SubscriptionsPersistentStore.java
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/monitor/impl/SubscriptionsPersistentStoreImpl.java
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/monitor/impl/TrivialSubscriptionsPersistentStore.java
catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/query/monitor/impl/SubscriptionsPersistentStoreImplTest.java
platform/persistence/platform-persistence-core-api/src/main/java/org/codice/ddf/persistence/PersistentStore.java
platform/persistence/platform-persistence-core-impl/src/main/java/org/codice/ddf/persistence/internal/PersistentStoreImpl.java
platform/persistence/platform-persistence-core-impl/src/test/java/org/codice/ddf/persistence/internal/PersistentStoreImplTest.java

- Adds `removeSubscriptions` method to `SubscriptionsPersistentStore.java` interface
- Calls `removeSubscriptions` method on workspace deletion
- Adds `get` method with start index and page size to `PersistentStore.java` interface.
- Changes `SubscriptionsPersistentStore.java` to call `get` with a start of 0 and a page size of 1000 when retrieving workspace subscriptions.
@jrnorth 
@glenhein 
@ryeats 
@bdeining
@rzwiefel
1. Create 20 workspaces
2. Subscribe to all of them and get all workspaces again, they should all be marked with `subscribed: true`.
I've included a postman script to help.
[DDF.postman_collection.json.zip](https://github.com/codice/ddf/files/2207484/DDF.postman_collection.json.zip) …

DDF-3983 Add paging to PersistentStore

---

distribution/docs/src/main/resources/content/scripts.html

Link to 2.13.x PR: https://github.com/codice/ddf/pull/3477
____
@codice/ui 
@clockard
@vinamartin 

DDF-3686 Fix scrolling in the Admin UI documentation tab

---

distribution/docs/src/main/resources/content/_endpoints/csw-endpoint.adoc
distribution/docs/src/main/resources/templates/build/endpoints.ftl

add formatting fix to docs template (whitespace)
@clockard
@lessarderic
@rzwiefel
@shaundmorris
builds successfully
- …

DDF-2824 add formatting fix to docs templates

---

distribution/ddf-common/src/main/resources-filtered/etc/system.properties
distribution/docs/src/main/resources/content/_quickstart/quickstart-installing.adoc

Link to 2.13.x PR: https://github.com/codice/ddf/pull/3487
____
@clockard
@rzwiefel 
[DDF-3915](https://codice.atlassian.net/browse/DDF-3915)

DDF-3915 Added a note in the documentation to not update the solr.http.url in system.properties

---

catalog/transformer/catalog-transformer-pdf/pom.xml
catalog/transformer/catalog-transformer-pptx/pom.xml
features/pom.xml
pom.xml

Updates the following libraries:
* pdfbox to 2.0.11
* hibernate to 5.3.6.Final
* org.apache.servicemix.bundles.jasypt to 1.9.2_1
* org.apache.servicemix.bundles.aws-java-sdk to 1.11.344_1
@emmberk @peterhuffer @oconnormi 
@clockard 
@vinamartin
Not sure of the best ways to test the upgrades but here's what I did.
* pdfbox seems be part of the ingest process for pdfs and pptxs so ingested one of each and made sure it ingested correctly.
* hibernate execute "feature:info cxf-bean-validation-core" and make sure the proper version of the hibernate bundle is being used
* org.apache.servicemix.bundles.jasypt execute "feature:info wss4j" and make sure the proper version is being used. I know cxf is used in our web clients so in an attempt to test it out I connected to a confluence source and did …

[2.13.x] DDF-4003 Update libraries to fix sonatype findings

---

distribution/ddf-common/src/main/resources/common-bin.xml
distribution/ddf-common/src/main/resources/etc/blacklisted.properties
distribution/ddf-common/src/main/resources/security/default.policy
features/kernel/src/main/feature/feature.xml
pom.xml

Updates jetty to 9.3.24.v20180605
@peterhuffer @emmberk @oconnormi @brjeter
@clockard
@stustison
install ddf and execute "feature:info pax-jetty" in the console and verify the bundles are using the 9.3.24.v20180605 version. Make sure that you can log in and travel to the admin and intrigue UIs.
[DDF-4008](https://codice.atlassian.net/browse/DDF-4008) …

[2.13.x] DDF-4008 Update jetty to 9.3.24.v20180605

---

distribution/docs/src/main/resources/content/_sources/solr-catalog-provider.adoc

Updates jts to the latest version
@coyotesqrl
Download the jar. 👍 
[DDF4010](https://codice.atlassian.net/browse/DDF-4010)
- [ 👍] Documentation Updated …

[2.13.x] DDF-4010 Updating a documentation hyperlink to point to the most recent version of jts

---

platform/solr/solr-factory/src/main/java/org/codice/solr/factory/impl/SolrCloudClientFactory.java

Corrects the Solr Cloud Solrj client building to use the uploaded collection configuration.  The default configuration will be used otherwise which will cause ingest to fail.
@bakejeyner 
@Kjames5269 
@clockard
@rzwiefel
Follow documentation to setup DDF with Solr Cloud.  Verify that data can be ingested and searched.
Check http://localhost:8983/solr/#/~cloud?view=tree and verify under `/configs` that there are no `<collection name>.AUTOCREATED` configurations.
[DDF-3964](https://codice.atlassian.net/browse/DDF-3964)
`catalog` is correct but `catalog.AUTOCREATED` is incorrect. …

[2.13.x] DDF-3964 Use correct collection config in Zookeeper

---

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/catalog/CatalogApplication.java
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/configuration/PlatformUiConfigurationApplication.java
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/security/AuthenticationApplication.java
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/security/LogoutApplication.java
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/session/SessionManagementApplication.java
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/spatial/GeoCoderApplication.java
ui/packages/catalog-ui-search/src/main/webapp/component/builder/builder.view.js

Link to 2.13.x PR: https://github.com/codice/ddf/pull/3510
____
@Bdthomson @adimka 
@coyotesqrl
@rzwiefel

 DDF-3941 Changed the new Spark endpoints to return Strings instead of Spark Responses

---

distribution/ddf-common/src/main/resources-filtered/etc/system.properties
distribution/ddf-common/src/main/resources/bin/ddf
distribution/ddf-common/src/main/resources/bin/ddfsolr
distribution/ddf-common/src/main/resources/bin/get_property

Add two new properties to system.properties: START_SOLR; START_KARAF
Add Jason L.'s fix for managing Solr
Split ddf script into 3 scripts
Start Solr with two-way TLS by default
@mcalcote 
@rzwiefel 
@lamhuy 
@oconnormi 
@JGatley 
@pklinef 
@clockard 
1. Secure loclahost.
- Install DDF. 
- After installation, the admin console should show a warning about insecure defaults (this mean it has a good connection to Solr).
- Visit https://localhost:8994/solr in a browser.
- The browser should display a certification error
1. Secure, certs
- Install DDF with ?dev=true.
- After installation, the admin console should show a warning about insecure defaults.
- Visit https://localhost:8994/solr in a browser.
- The browser should display a certification error
1. Unsecure, localhost
- Edit …

[2.13.x] DDF-3915 Solr script fixes for *nix

---

distribution/ddf-common/src/main/resources/bin/ddf.bat
distribution/ddf-common/src/main/resources/bin/get_property.bat

Update the DDF Windows scripts to pull extra Solr properties when starting Solr. 
@pklinef @oconnormi @rzwiefel @ahoffer @ethantmanns @kcover @bakejeyner @tyler30clemens @figliold 
Inspect changes, run start scripts
These should "just work" for the default developer use case, so please check that your normal routine is unaffected. 
[DDF-3915](https://codice.atlassian.net/browse/DDF-3915) …

2.13.X DDF-3915 Update ddf and solr scripts for Windows

---

catalog/transformer/catalog-transformer-pdf/pom.xml
catalog/transformer/catalog-transformer-pptx/pom.xml
features/pom.xml
pom.xml

https://github.com/codice/ddf/pull/3494
@emmberk @peterhuffer @oconnormi 
@clockard 
@vinamartin

DDF-4003 Update libraries to fix sonatype findings

---

distribution/ddf-common/src/main/resources/security/configurations.policy
distribution/docs/src/main/resources/content/_architectures/url-resource-reader.adoc
distribution/docs/src/main/resources/content/_running/ingest-command.adoc

Link to 2.13.x PR: #https://github.com/codice/ddf/pull/3456
@peterhuffer 
@jhunzik 
@Kjames5269 
@clockard 
@ricklarsen 
---
This …

DDF-3985 Updated URL Resource Reader permissions/docs (#3456)

---

catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/SolrFilterDelegate.java
catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/SolrFilterDelegateTest.java

Link to 2.13.x PR: #3504
____
@paouelle 
@troymohl 
@clockard
@rzwiefel

DDF-3938 Replace anyText:* with *:* to use optimized MatchAllDocsQuery

---

platform/solr/solr-factory/src/main/java/org/codice/solr/factory/impl/SolrCloudClientFactory.java

Link to 2.13.x PR: #3503
____
@bakejeyner 
@Kjames5269 
@clockard
@rzwiefel

DDF-3964 Use correct collection config in Zookeeper

---

ui/packages/catalog-ui-search/src/main/webapp/component/ingest/ingest.view.js

Fixes a bug that prevents uploading to lists because a url wasn't passed to a component.
@glenhein 
@jlcsmith 
@djblue 
@vinamartin
Upload a zip of images, you should see "x.zip uploaded successfully. y items found."
[DDF-3896](https://codice.atlassian.net/browse/DDF-3896) …

[2.13.x] DDF-3896 Fix list upload by passing url to component

---

pom.xml

Update countrycode library version to 0.1.3
https://github.com/codice/countrycode
@leo-sakh 
@Bdthomson 
@bdeining
@vinamartin
build, install 
https://codice.atlassian.net/browse/DDF-4020

DDF-4020 Update countrycode library version to 0.1.3

---

ui/packages/catalog-ui-search/src/main/webapp/component/ingest/ingest.view.js

Link to 2.13.x PR: #3511 
____
Fixes a bug that prevents uploading to lists because a url and reference to a function wasn't passed to a component.
@jlcsmith
@djblue
@vinamartin …

DDF-3896 Fix list upload by passing url to component

---

ui/packages/catalog-admin-module-sources/src/main/webapp/js/view/ModalSource.view.js

Allows editing of disabled sources
@ethantmanns @emmberk  @jhunzik 
@clockard 
@tbatie
Edit a disabled source through the Admin Console. Clicking the save button should close the modal and successfully save the changes.
[DDF-3591](https://codice.atlassian.net/browse/DDF-3591) …

[2.13.x] DDF-3591 Allows editing of disabled sources

---

ui/packages/catalog-admin-module-sources/src/main/webapp/js/view/ModalSource.view.js

Link to 2.13.x PR: #3526 
____
@ethantmanns @jhunzik @emmberk 
@clockard 
@tbatie

DDF-3591 Allows editing of disabled sources

---

distribution/docs/src/main/resources/content/_configuring/global-settings.adoc
distribution/docs/src/main/resources/content/_configuring/hardening-solr-index.adoc
distribution/docs/src/main/resources/content/_configuring/solr-admin-ui.adoc
distribution/docs/src/main/resources/content/_devComponents/managed-service-factories.adoc
distribution/docs/src/main/resources/content/_installing/firewall-config.adoc
distribution/docs/src/main/resources/content/_sources/solr-catalog-provider.adoc

- Doc changes based on code changes in PR 3476
- Remove extraneous or incorrect information
@ricklarsen @mcalcote @rzwiefel @austinsteffes 
@clockard
@rzwiefel
@shaundmorris
Build docs. Read. 
DDF-3915 and PR 3476 …

[2.13.x] DDF-3915 Solr documentation updates

---

ui/packages.xml

Adds the new codice linter in UI to packages.xml for downstream extensibility.
@djblue  
@bdeining
Full build.  …

[2.13.x] DDF-3686 Add linter to packages.xml

---

catalog/ui/catalog-ui-metacard-sharing-impl/pom.xml
catalog/ui/catalog-ui-metacard-sharing-impl/src/main/java/org/codice/ddf/catalog/ui/sharing/ShareableMetacardImpl.java
catalog/ui/catalog-ui-search/pom.xml
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/forms/data/AttributeGroupMetacard.java
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/forms/data/AttributeGroupType.java
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/forms/data/QueryTemplateMetacard.java
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/MetacardApplication.java
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/workspace/WorkspaceMetacardImpl.java
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/security/ShareableMetacardAccessPlugin.java
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/security/ShareableMetacardPolicyExtension.java
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/security/ShareableMetacardPreIngestPlugin.java
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/security/ShareableMetacardSharingPolicyPlugin.java
catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/security/ShareableMetacardAccessPluginTest.java
catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/security/ShareableMetacardImplTest.java
catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/security/ShareableMetacardPreIngestPluginTest.java
catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/security/ShareableMetacardSharingPolicyPluginTest.java
catalog/ui/pom.xml

Extracts shareable implementation to a separate module and packages it as a jar. This facilitates usage in downstream projects without the need of embedding the entire `catalog-ui-search` module. 
@djblue 
@bdeining 
@adimka 
@bdeining
**full build**
Share a search form from user 1 to user 2, verify that works
Share a workspace from user 1 to user 2, verify that works …

DDF-3649 Extracting Shareability Implementation To Separate Module 

---

catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/blueprint/blueprint.xml

Link to 2.13.x PR: https://github.com/codice/ddf/pull/3506
@rzwiefel @brendan-hofmann @djblue

DDF-4014 Refactor catalog-ui-search blueprint to not register unnecessary SubscriptionsPersistentStore service

---

distribution/ddf-common/src/main/resources/security/default.policy

Addresses access control exception when clicking the gmd:MD_Metadata action in the Inspector in Intrigue.
@peterhuffer @Kjames5269 @bdeining 
@clockard
@rzwiefel 
@stustison 
1) Ingest a file/metacard
2) Go into the Inspector tab in Intrigue
3) Go to the Action tab
4) Select the gmd:md_metadata action …

DDF-3945 Permission entry for the gmd:MD action

---

distribution/ddf-common/src/main/resources/common-bin.xml
distribution/ddf-common/src/main/resources/etc/blacklisted.properties
distribution/ddf-common/src/main/resources/security/default.policy
features/kernel/src/main/feature/feature.xml
pom.xml

Link to 2.13.x PR: #3497 
@peterhuffer @emmberk @oconnormi @brjeter
@clockard
@stustison

DDF-4008 Update jetty to 9.3.24.v20180605

---

ui/packages/catalog-ui-search/src/main/webapp/component/query-add/query-add.view.js
ui/packages/catalog-ui-search/src/main/webapp/component/search-form-interactions/search-form-interactions.view.js
ui/packages/catalog-ui-search/src/main/webapp/js/model/Query.js

Link to 2.13.x PR: #3534
____
Fixes the UI when deleting a search form, it resets to the default search form or basic text search.
@Bdthomson @lamhuy @mackncheesiest @hayleynorton 
@bdeining 
1. Extract built DDF
2. Create a /etc/forms directory
3. Start DDF
4. Enable experimental features in the catalog-ui-search config
5. Create a search form in the catalog search ui and save it.
6. Select the search form.
7. Delete the search form.
8. Verify that when you open a new search, it is a basic text search.
[DDF-4019](https://codice.atlassian.net/browse/DDF-4019) …

DDF-4019 Fixed deleting search forms

---

catalog/ui/catalog-ui-search/pom.xml
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/MetacardApplication.java
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/monitor/api/SubscriptionsPersistentStore.java
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/monitor/impl/SubscriptionsPersistentStoreImpl.java
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/monitor/impl/TrivialSubscriptionsPersistentStore.java
catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/query/monitor/impl/SubscriptionsPersistentStoreImplTest.java
platform/persistence/platform-persistence-core-api/src/main/java/org/codice/ddf/persistence/PersistentStore.java
platform/persistence/platform-persistence-core-impl/src/main/java/org/codice/ddf/persistence/internal/PersistentStoreImpl.java
platform/persistence/platform-persistence-core-impl/src/test/java/org/codice/ddf/persistence/internal/PersistentStoreImplTest.java

- Adds `removeSubscriptions` method to `SubscriptionsPersistentStore.java` interface
- Calls `removeSubscriptions` method on workspace deletion
- Adds `get` method with start index and page size to `PersistentStore.java` interface.
- Changes `SubscriptionsPersistentStore.java` to call `get` with a start of 0 and a page size of 1000 when retrieving workspace subscriptions.
@jrnorth 
@glenhein 
@ryeats 
@bdeining
@rzwiefel
1. Create 20 workspaces
2. Subscribe to all of them and get all workspaces again, they should all be marked with `subscribed: true`.
I've included a postman script to help.
[DDF.postman_collection.json.zip](https://github.com/codice/ddf/files/2207484/DDF.postman_collection.json.zip) …

[2.13.x] DDF-3983 Add paging to PersistentStore

---

distribution/ddf-common/src/main/resources/security/default.policy

Link to 2.13.x PR: https://github.com/codice/ddf/pull/3512
____
allow GMD action in Intrigue
@peterhuffer 
@Kjames5269 
@bakejeyner 
@ahoffer 
@clockard
Change the policy and use the GMD action …

DDF-3945 Permission entry for the gmd:MD action (#3512)

---

distribution/docs/src/main/resources/content/_configuring/global-settings.adoc
distribution/docs/src/main/resources/content/_configuring/hardening-solr-index.adoc
distribution/docs/src/main/resources/content/_configuring/solr-admin-ui.adoc
distribution/docs/src/main/resources/content/_devComponents/managed-service-factories.adoc
distribution/docs/src/main/resources/content/_installing/firewall-config.adoc
distribution/docs/src/main/resources/content/_sources/solr-catalog-provider.adoc

Link to 2.13.x PR: https://github.com/codice/ddf/pull/3518
Updates documentation related to standalone Solr server epic
@mcalcote 
@shaundmorris 
@emmberk 
@figliold
@rzwiefel
Checkout the branch and perform a clean build of the distribution/docs module. 
Inspect the output, `target/docs/html/documentation.html` for proper formatting, spelling, grammar. …

DDF-3915 Solr documentation updates

---

Jenkinsfile

The Full Build stage has now been split into two separate stages. The first stage runs all tests and analysis except the itests. The second stage just runs the itests. In the case of windows where the agent must be secured, a quick build precedes the itest run.
@oconnormi @clockard @shaundmorris @mackncheesiest @LinkMJB

DDF-3847 Adjust Jenkinsfile pipeline stages to separate full build stages

---

distribution/ddf-common/src/main/resources/security/default.policy

Adds missing permissions that were causing itests to fail
@bakejeyner @peterhuffer @kcover @mcalcote 
@coyotesqrl
@rzwiefel
@shaundmorris
@tbatie
@vinamartin
CI Build

DDF-3945 Add missing jetty.websocket permissions to policy file

---

distribution/ddf-common/src/main/resources-filtered/etc/system.properties
distribution/ddf-common/src/main/resources/bin/ddf
distribution/ddf-common/src/main/resources/bin/ddf.bat
distribution/ddf-common/src/main/resources/bin/ddfsolr
distribution/ddf-common/src/main/resources/bin/get_property
distribution/ddf-common/src/main/resources/bin/get_property.bat

Foward port of PR 3518 and PR 3476 
@rzwiefel 
@ricklarsen 
@mcalcote 
@clockard 
@clockard
@rzwiefel
1. Build documentation and check output for correct formatting.
2. Build and start. Upload something to ensure connectivity with Solr …

DDFD-3915 Updated Solr start script & documentation

---

pom.xml

Updates version of geotools-suite
@GabrielFabian @middlets719 
@jlcsmith
@pklinef
Full Build
[DDF-4022](https://codice.atlassian.net/browse/DDF-4022) …

DDF-4022 Updated geotools-suite version

---

Documentation-versions.html
index.html

updates the gh-pages branch (ddf.codice.org) with latest release documentation.
@clockard
@lessarderic
@rzwiefel
@shaundmorris …

DDF-2824 updated project site for 2.13.0 release

---

distribution/docs/pom.xml

renames executions of the build-helper-maven-plugin to ensure both are run during builds.
@mcalcote @ahoffer @garrettfreibott @austinsteffes @oconnormi 
@clockard
@coyotesqrl
@lessarderic
@rzwiefel
@shaundmorris …

DDF-2824 fixed duplicate execution IDs in docs pom

---

distribution/docs/src/main/resources/content/_quickstart/quickstart-ingesting.adoc

Fixes quickstart docs to point to Intrigue UI.
@ricklarsen  
Documentation
Inspection, regenerate docs.

Point quickstart docs to Intrigue UI

---

distribution/docs/src/main/resources/content/_sources/solr-catalog-provider.adoc

- Teams tagged
[Link to 2.13.x PR: #3498](https://github.com/codice/ddf/pull/3498)
@bakejeyner @brjeter
@coyotesqrl
- ✏️ …

DDF-4010 Updating a documentation hyperlink to point to the most recent version of jts

---

ui/packages/catalog-ui-search/src/main/webapp/js/model/List.js

Allows Intrigue Lists to search enterprise sources
@glenhein @mackncheesiest 
@bdeining
- Create a CSW source (or any remote source). I used `https://catalogue-imos.aodn.org.au/geonetwork/srv/eng/csw` for my CSW source.
- Ingest a local product
- Query the CSW source and add it to a list
- Add the local product to the same list
- Verify both the local and enterprise product are in the new list
[DDF-4013](https://codice.atlassian.net/browse/DDF-4013) …

DDF-4013 Change List search to enterprise from local

---

ui/packages/catalog-ui-search/package.json
ui/yarn.lock

Updates catalog-ui-search to use npm usng.js artifact
@blen-desta 
@adimka 
@codice/ui 
@coyotesqrl
@stustison
- `cd ui && mvn clean install`
- ensure location input has no regressions 
[DDF-4025](https://codice.atlassian.net/browse/DDF-4025) …

DDF-4025 Updates catalog-ui-search to use npm usng.js artifact

---

distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/AbstractIntegrationTest.java
distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/SystemStateManager.java

Fix stability issues in itests
@ethantmanns 
@clockard
@tbatie
CI build …

[2.13.x] DDF-8324: Fix stability issues in itests

---

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/catalog/CatalogApplication.java

Closes input streams in Catalog Application
@coyotesqrl
@stustison 
1) Install DDF
2) hit https://localhost:8993/search/catalog/internal/catalog/:id
I did this through postman with the following headers: 
``` 
Host: localhost:8993
Referer: https://localhost:8993/admin/
X-Requested-With: XMLHttpRequest
```
You can get an id by navigating to details in intrigue:
Nothing should break. 👍 
3) hit https://localhost:8993/search/catalog/internal/catalog/:sourceid/:id with the same postman headers
Nothing should break. 👍 
[DDF-4016](https://codice.atlassian.net/browse/DDF-4016) …

[2.13.x] DDF-4016 Closing input streams in CatalogApplication

---

distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/AbstractIntegrationTest.java
distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/SystemStateManager.java

Link to 2.13.x PR:https://github.com/codice/ddf/pull/3557
____
@ethantmanns
@emmberk 
@clockard
@tbatie
CI build
https://codice.atlassian.net/browse/DDF-3824 …

DDF-3824: Fix stability issues in itests

---

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/forms/SearchFormsLoader.java

Made Failsafe Asynchronous which fixes downstream itest failures
@GabrielFabian @Bdthomson 
@pklinef
@millerw8 
Build / Unzip / make etc forms directory / Install / turn on experimental features / verify search form crud
[DDF-4036](https://codice.atlassian.net/browse/DDF-4036) …

DDF-4036 Made Failsafe Asynchronous

---

ui/packages/catalog-ui-search/src/main/webapp/component/search-form-interactions/search-form-interactions.hbs

Closes the edit div for search form tempaltes
@Bdthomson @hayleynorton @lamhuy
@bdeining
1. Extract built DDF
2. Create a /etc/forms directory
3. Start DDF
4. Enable experimental features in the catalog-ui-search config
5. Create a search form in the catalog search ui and save it.
6. Verify that the delete button is on the search form in the search form browser …

DDF-4058 Closed off edit button for search form templates

---

distribution/ddf-common/src/main/resources/common-bin.xml
distribution/ddf-common/src/main/resources/etc/blacklisted.properties
features/kernel/src/main/feature/feature.xml
libs/test-common/src/main/java/org/codice/ddf/test/common/configurators/DdfBaseOptions.java
libs/test-common/src/main/resources/blacklisted.properties
pom.xml

Updates pax web version to better work with the jetty version
@kcover @emmberk @peterhuffer 
@bdeining
@lessarderic
@shaundmorris
Install DDF and do a basic smoke test on webapps
[DDF-4008](https://codice.atlassian.net/browse/DDF-4008)

[2.13.x] DDF-4008 Update pax web to 6.0.11 to match jetty version

---

catalog/rest/catalog-rest-impl/src/main/java/org/codice/ddf/rest/impl/CatalogServiceImpl.java

Closes an input stream in CatalogServiceImpl
@bakejeyner 
@blen-desta 
@coyotesqrl
@stustison 
1) Install DDF
2) Import a file into DDF hitting `https://localhost:8993/services/catalog/metacard`
Nothing should break 👍 
[DDF-4018](https://codice.atlassian.net/browse/DDF-4018) …

[2.13.x] DDF-4018 closing input streams in catalogServiceImpl

---

Jenkinsfile

Link to 2.13.x PR: https://github.com/codice/ddf/pull/3597
____
@clockard @ricklarsen 
[DDF-4065](https://codice.atlassian.net/browse/DDF-4065)

DDF-4065 Removed "skipDocs" from quickbuild step on PR builds prior to GIB

---

distribution/ddf-common/src/main/resources/common-bin.xml
distribution/ddf-common/src/main/resources/etc/blacklisted.properties
features/kernel/src/main/feature/feature.xml
libs/test-common/src/main/java/org/codice/ddf/test/common/configurators/DdfBaseOptions.java
libs/test-common/src/main/resources/blacklisted.properties
pom.xml

Updates pax web version to better work with the jetty version
@kcover @emmberk @peterhuffer 
@bdeining
@lessarderic
@shaundmorris
Install DDF and do a basic smoke test on webapps
[DDF-4008](https://codice.atlassian.net/browse/DDF-4008)

DDF-4008 Update pax web to 6.0.11 to match jetty version

---

distribution/docs/src/main/resources/content/_dependencyList/ddf-dependency-list.adoc
features/security/src/main/feature/feature.xml
platform/email/platform-email-impl/pom.xml

@troymohl @GabrielFabian 
@jlcsmith
@stustison
Build

DDF-2494 Fixed javax mail version

---

Documentation-versions.html
index.html

updates project website (gh-pages branch) to include latest (2.13.1) release.
@mcalcote @ahoffer @austinsteffes @garrettfreibott 
@clockard
@coyotesqrl
@lessarderic
@shaundmorris
verify content: dates, versions. (documentation.html and .pdf are auto-generated) …

DDF-2824 updated project website for 2.13.1 release

---

catalog/spatial/registry/registry-ebrim-transformer/pom.xml
platform/security/platform-security-core-api/pom.xml
platform/security/rest/security-rest-clientapi/pom.xml
platform/security/rest/security-rest-cxfwrapper/pom.xml
pom.xml

Made version property for Google HTTP client
@troymohl @GabrielFabian 
@jlcsmith
@millerw8
Full build …

DDF-4076 Made version property for Google HTTP client

---

catalog/ui/search-ui-app/pom.xml
catalog/ui/search-ui-app/src/main/resources/features.xml

- Adds new config files to features and pom file to enable them on startup. This was missed in https://github.com/codice/ddf/pull/3467
@Schachte 
@brianfelix 
@bdeining 
Ensure that on startup in Admin UI > Search UI you see all the new configs filled out (have a config section filled out that you can delete). Before the values would be filled out but you would have to hit save for them to trigger. …

DDF-3986 Adding config to features and pom

---

catalog/catalog-app/src/main/resources/features.xml

Link to 2.13.x PR: #3623 
____
@lamhuy @brjeter
@stustison
@tbatie

DDF-4075 Adds requirement on catalog-core-api to catalog-security-filter

---

platform/admin/core/admin-core-appservice/src/main/java/org/codice/ddf/admin/application/service/command/ProfileInstallCommand.java

Link to 2.13.x PR: #3583 
Adds AccessController.doPrivilegedAction() call to doExecute().
@clockard
@coyotesqrl 
[DDF-4054](https://codice.atlassian.net/browse/DDF-4054) …

DDF-4054 Permissions granted to profile:install command should be granted to other bundles

---

distribution/test/performance/jmeter/catalog-transformer-xml/pom.xml
distribution/test/performance/jmeter/catalog-transformer-xml/src/test/jmeter/XMLTransformerPerf-json.jmx
distribution/test/performance/jmeter/csw/pom.xml
distribution/test/performance/jmeter/csw/src/test/jmeter/CSW-GetRecords.jmx

updates jmeter performance tests in order to get useful outputs of graphs and more information within those
@ahoffer @mcalcote @garrettfreibott 
@coyotesqrl
@rzwiefel
@clockard 
go into /ddf/distribution/test/performance/jmeter 
run mvn clean install to clear out
run mvn install -Pjmeter
outputted graphs will be in 2 respective directories for the 2 jmeter tests
/ddf/distribution/test/performance/jmeter/catalog-transformer-xml/target/jmeter/results
/ddf/distribution/test/performance/jmeter/csw/target/jmeter/results
[DDF-4056](https://codice.atlassian.net/browse/DDF-4056) …

Ddf 4056 - Update jmeter performance tests

---

platform/security/cas/security-cas-client/pom.xml
platform/security/cas/security-cas-client/src/main/java/org/codice/ddf/security/handler/cas/filter/FilteredRequest.java
platform/security/cas/security-cas-client/src/main/java/org/codice/ddf/security/handler/cas/filter/ProxyFilter.java
platform/security/cas/security-cas-client/src/main/java/org/codice/ddf/security/handler/cas/filter/ProxyFilterChain.java
platform/security/cas/security-cas-client/src/main/resources/OSGI-INF/blueprint/casfilters.xml
platform/security/cas/security-cas-client/src/test/java/org/codice/ddf/security/handler/cas/CasHandlerTest.java
platform/security/cas/security-cas-client/src/test/java/org/codice/ddf/security/handler/cas/FilteredRequestTest.java

Link to 2.13.x PR: #3481
____
@vinamartin @ahoffer 
@stustison 
[DDF-3998](https://codice.atlassian.net/browse/DDF-3998)

DDF-3998 Fix CAS client redirects

---

dependency-check-maven-config.xml

Backport for https://github.com/codice/ddf/pull/3653
@clockard  
@stustison 

[2.13.x]DDF-4087 Suppressing jetty CVEs that don't apply to DDF

---

catalog/rest/catalog-rest-impl/src/main/java/org/codice/ddf/rest/impl/CatalogServiceImpl.java

- Teams tagged
Link to 2.13.x PR: #3536 
____
@bakejeyner @blen-desta @coyotesqrl @stustison @rzwiefel  …

DDF-4018 closing input streams in catalogServiceImpl

---

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/catalog/CatalogApplication.java

- Teams tagged
Link to 2.13.x PR: #3535
____
@rzwiefel 
@coyotesqrl 
@stustison  …

DDF-4016 Closing input streams in CatalogApplication

---

ui/packages/catalog-ui-search/src/main/webapp/js/controllers/ol.layerCollection.controller.js

Fix AGM imagery provider
@SmithJosh 
@vinamartin 
Build / Install / Configure AGM and verify on both maps …

DDF-3686 Fix AGM imagery provider

---

catalog/spatial/spatial-app/src/main/resources/features.xml
catalog/spatial/wfs/1.0.0/spatial-wfs-v1_0_0-schema-webapp/pom.xml
catalog/ui/search-ui/search-redirect/pom.xml

There is no need to embed these jars since the artifact is a bundle that is already running by default. Several other bundles are already importing the packages exported by the jetty-servlets bundle.
@jhunzik 
@ethantmanns 
@paouelle 
@tbatie 
@figliold 
1. Build and install DDF through Admin UI.
2. Open "Inspect" to "Network" tab.
3. Navigate to search-redirect by hitting https://localhost:8993/search (which will redirect you)
- check for "Content Encoding: gzip" to make sure and verify GzipFilter is occurring. 
4. Navigate to https://localhost:8993/ogc/gml/2.1.2/feature.xsd 
- check for "Content Encoding: gzip" to make sure and verify GzipFilter is occurring.
[DDF-4071](https://codice.atlassian.net/browse/DDF-4071) …

DDF-4071 Removed embedded jetty-servlets

---

ui/packages/catalog-ui-search/src/main/webapp/component/component.less
ui/packages/catalog-ui-search/src/main/webapp/component/input/bulk/input-bulk.view.js
ui/packages/catalog-ui-search/src/main/webapp/component/input/date/input-date.view.js
ui/packages/catalog-ui-search/src/main/webapp/component/input/enum/input-enum.view.js
ui/packages/catalog-ui-search/src/main/webapp/component/input/time/input-time.less
ui/packages/catalog-ui-search/src/main/webapp/component/input/time/input-time.view.js
ui/packages/catalog-ui-search/src/main/webapp/component/property/property.js
ui/packages/catalog-ui-search/src/main/webapp/component/property/property.view.js
ui/packages/catalog-ui-search/src/main/webapp/component/result-form/result-form.collection.js
ui/packages/catalog-ui-search/src/main/webapp/component/search-form/search-form.collection.js
ui/packages/catalog-ui-search/src/main/webapp/component/time-settings/time-settings.view.js
ui/packages/catalog-ui-search/src/main/webapp/component/value/value.view.js
ui/packages/catalog-ui-search/src/main/webapp/component/visualization/table/row.view.js
ui/packages/catalog-ui-search/src/main/webapp/dev/component/input-guide/input-guide.hbs
ui/packages/catalog-ui-search/src/main/webapp/dev/component/input-guide/input-guide.view.js
ui/packages/catalog-ui-search/src/main/webapp/js/Common.js
ui/packages/catalog-ui-search/src/main/webapp/js/model/User.js

Adds a separate time input (doesn't have a date component) to Intrigue that is accessible through a PropertyView with type: 'TIME'
First commit is base component functionality
Second commit is refactoring overall usages of timeFormat to dateTimeFormat and refactoring code out of input-time.view
Third commit is adding a demonstration usage in the Intrigue /#dev route
@adimka 
@troymohl 
@bdeining 
This is a rebase of https://github.com/codice/ddf/pull/3574 …

DDF-4037 Added input-time.view to Intrigue (Rebase)

---

distribution/docs/src/main/resources/content/_running/ui-ingest.adoc
distribution/docs/src/main/resources/content/_using/using-catalog-search-ui.adoc

Adds a warning in the docs to warn users that Intrigue uploads will be considered as products instead of metadata.
@jhunzik 
@paouelle 
@figliold
@tbatie
@shaundmorris 
Build and view docs.
[DDF-4073](https://codice.atlassian.net/browse/DDF-4073) …

DDF-4073 Document Intrigue metadata upload limitations

---

catalog/spatial/registry/registry-federation-admin-service-impl/pom.xml
catalog/spatial/registry/registry-federation-admin-service-impl/src/test/java/org/codice/ddf/registry/federationadmin/service/impl/FederationAdminServiceImplTest.java
catalog/spatial/registry/registry-federation-admin-service-impl/src/test/java/org/codice/ddf/registry/federationadmin/service/impl/RefreshRegistryEntriesTest.java
catalog/spatial/registry/registry-federation-admin-service-impl/src/test/java/org/codice/ddf/registry/federationadmin/service/impl/RegistryPublicationServiceImplTest.java
catalog/spatial/registry/registry-federation-admin-service-impl/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
platform/security/common/src/main/java/org/codice/ddf/security/common/Security.java

Prevents overriding of the Security.getSystemSubject method to prevent malicious persons from replacing secured versions with unsecured versions of classes/services.
@ethantmanns 
@jhunzik 
@paouelle 
@tbatie 
@figliold 
@coyotesqrl 
1. Get changes (make sure you have changes from CAL-460 or else some tests in CAL will break due to not being able to mock final methods) and test respective unit tests.
2. Install then run DDF and hit Security.getSystemSubject method and make sure nothing breaks.
In reality, any user who could replace a secured piece of code would already have full access to the system and could do much more. That is why this issue is of low-priority.
[DDF-4055](https://codice.atlassian.net/browse/DDF-4055) …

[2.13.x]DDF-4055 Changed Security.getSystemSubject method to be final and fixed unit tests

---

ui/packages/catalog-admin-module-layout/package.json
ui/packages/catalog-admin-module-layout/src/main/webapp/default-layout/reducer.js
ui/packages/catalog-admin-module-layout/src/main/webapp/default-layout/test-data/config.json
ui/packages/catalog-admin-module-maplayers/package.json
ui/packages/catalog-admin-module-maplayers/src/main/webapp/map-layers/reducer.js

- Fixes the path that the `admin-module` reducer gives when updating configuration for map layer calls.
- Adds `m2` script to package.json for installing module into `m2` for hot deploys.
- Fixes `GoldenLayout` require statement that was preventing `admin-layout` from loading.
@AzGoalie 
@alanchampion 
@djblue 
@jlcsmith 
- Verify that you see the map layers configuration in `Admin UI > Catalog > Map Layers` and you can update the configuration without getting an error.
[DDF-3986](https://codice.atlassian.net/browse/DDF-3986) …

DDF-3986 Fixing map-layers metatype path

---

distribution/docs/src/main/resources/content/_appendixIntros/hardening-checklist.adoc
distribution/docs/src/main/resources/content/_configuring/configuring-guest-access.adoc
distribution/docs/src/main/resources/content/_configuring/reusing-configurations.adoc
distribution/docs/src/main/resources/content/_installing/file-system-access.adoc
distribution/docs/src/main/resources/content/_installing/installing-intro.adoc
distribution/docs/src/main/resources/content/_securing/auditing.adoc
distribution/docs/src/main/resources/content/_securing/disallowing-login-wo-certs.adoc
distribution/docs/src/main/resources/content/_securing/hardening-intro.adoc
distribution/docs/src/main/resources/content/_securing/managing-certificates.adoc
distribution/docs/src/main/resources/content/_securing/managing-crl.adoc
distribution/docs/src/main/resources/content/_securing/managing-keystores.adoc
distribution/docs/src/main/resources/templates/build/application-reference.ftl
distribution/docs/src/main/resources/templates/build/metadata-reference.ftl
distribution/docs/src/main/resources/templates/build/reference.ftl
distribution/docs/src/main/resources/templates/documentation.ftl

Several sections of the hardening guide were moved to make the process of installing a hardened system more clear. Several typos were found during this process and will be addressed as part of this ticket.
@austinsteffes @garrettfreibott @ahoffer @ricklarsen @shaundmorris 
Inspect changes for suggestions and improvements.
[DDF-4086](https://codice.atlassian.net/browse/DDF-4086) …

DDF-4086 Update organization and address typos in hardening guide

---

catalog/ui/search-ui/standard/src/main/doc/_contents/help-contents.adoc
platform/landing-page/src/main/resources/assets/js/index.js
platform/security/filter/security-filter-csrf/pom.xml
platform/security/filter/security-filter-csrf/src/main/java/org/codice/ddf/security/filter/csrf/CsrfFilter.java
platform/security/filter/security-filter-csrf/src/main/resources/OSGI-INF/blueprint/blueprint.xml
platform/security/filter/security-filter-csrf/src/test/groovy/org/codice/ddf/security/filter/csrf/CsrfFilterSpec.groovy
platform/security/idp/security-idp-client/src/main/java/org/codice/ddf/security/idp/client/IdpLogoutActionProvider.java

- Changed thumbnail and download urls
- Locked down /services for system to system communications
@brjeter @djblue @garrettfreibott
@clockard
@coyotesqrl
@stustison
Test everything with the network tab open to make sure there are no `403`s
- Verify Ingest and query works
- Verify that all action providers work
- Verify that thumbnails urls and resources download urls are correct
- Verify list creation and other features like history still work
- Verify that simple search works 
**NOTE**: Standard search will be broken (verify that it works without the csrf feature)
- Verify that all sources work
- Verify that downstream projects work as expected
- Verify session invalidation/expiry and renewal work …

[2.13.x] DDF-3941 - Locked down /services for system to system communications

---

catalog/catalog-app/src/main/resources/features.xml

Put Async Framework API into its own feature
@clockard @kcover @emmberk 
@lessarderic
@vinamartin
Build, install, and verify the In memory async framework implementation can still start.
[DDF-4085](https://codice.atlassian.net/browse/DDF-4085) …

DDF-4085 Put Async Framework API into its own feature

---

distribution/ddf-common/src/main/resources-filtered/etc/application-definitions/admin.json
features/apps/src/main/feature/feature.xml
platform/admin/modules/admin-modules-application/src/test/resources/application-service-array.json

Link to 2.13.x PR: https://github.com/codice/ddf/pull/3657
@rzwiefel @bdeining @shaundmorris @tbatie

DDF-2824 Fixes typo "provides contains" in Admin UI

---

distribution/docs/src/main/resources/content/_configuring/configuring-idp.adoc
distribution/docs/src/main/resources/content/_configuring/configuring-rest-for-users.adoc
distribution/docs/src/main/resources/content/_configuring/connecting-to-external-idp.adoc
distribution/docs/src/main/resources/content/_configuring/no-idp.adoc
distribution/docs/src/main/resources/content/_securityServices/security-idp-intro.adoc

Updates the IdP documentation
@brjeter @bakejeyner @Kjames5269 
@coyotesqrl
@stustison
Make sure the links work.
[DDF-4048](https://codice.atlassian.net/browse/DDF-4048)
Diagram: …

[2.13.x] DDF-4048 Updated IdP documentation

---

distribution/docs/src/main/resources/content/_configuring/configuring-idp.adoc
distribution/docs/src/main/resources/content/_configuring/configuring-rest-for-users.adoc
distribution/docs/src/main/resources/content/_configuring/connecting-to-external-idp.adoc
distribution/docs/src/main/resources/content/_configuring/no-idp.adoc
distribution/docs/src/main/resources/content/_securityServices/security-idp-intro.adoc

Link to 2.13.x PR: https://github.com/codice/ddf/pull/3610
____
@brjeter @bakejeyner @Kjames5269
@coyotesqrl
@stustison

DDF-4048 Updated IdP documentation and added a reference to the SAML-CTK

---

catalog/ui/search-ui/standard/src/main/doc/_contents/help-contents.adoc
platform/landing-page/src/main/resources/assets/js/index.js
platform/security/filter/security-filter-csrf/pom.xml
platform/security/filter/security-filter-csrf/src/main/java/org/codice/ddf/security/filter/csrf/CsrfFilter.java
platform/security/filter/security-filter-csrf/src/main/resources/OSGI-INF/blueprint/blueprint.xml
platform/security/filter/security-filter-csrf/src/test/groovy/org/codice/ddf/security/filter/csrf/CsrfFilterSpec.groovy
platform/security/idp/security-idp-client/src/main/java/org/codice/ddf/security/idp/client/IdpLogoutActionProvider.java

Link to 2.13.x PR: https://github.com/codice/ddf/pull/3558
____
@brjeter @garrettfreibott
@clockard
@coyotesqrl
@stustison 

DDF-3941 - Locked down /services for system to system communications

---

ui/packages/catalog-ui-search/src/main/webapp/component/filter/filter.less
ui/packages/catalog-ui-search/src/main/webapp/component/input/with-param/input-with-param.less
ui/packages/catalog-ui-search/src/main/webapp/component/input/with-param/input-with-param.view.js
ui/packages/catalog-ui-search/src/main/webapp/dev/component/component.less
ui/packages/catalog-ui-search/src/main/webapp/dev/component/dev/dev.js
ui/packages/catalog-ui-search/src/main/webapp/dev/component/input-guide/input-guide.view.js
ui/packages/catalog-ui-search/src/main/webapp/dev/component/videos/videos.hbs
ui/packages/catalog-ui-search/src/main/webapp/dev/component/videos/videos.less
ui/packages/catalog-ui-search/src/main/webapp/dev/component/videos/videos.view.js

- Fixes the css for the input with param component.
- Previously it would spill outside it's container, now it sizes it's children correctly.
@shaundmorris 
@bdeining 
@djblue 
@adimka 
@andrewzimmer
Test out the near input in the advanced search.
[DDF-3828](https://codice.atlassian.net/browse/ddf-3828)
[Video](https://www.youtube.com/watch?v=cg3Gh6DVF5k&feature=youtu.be)

DDF-3828 Fixes the css for the input with param component

---

distribution/docs/src/main/resources/content/_appReferences/mg-broker-app.adoc

Fixes some of the message broker documentation to be more accurate.
@ryeats 
@jaymcnallie 
@ricklarsen 
[DDF-4100](https://codice.atlassian.net/browse/) …

DDF-4100 Fix incorrect statement in broker app documentation

---

ui/packages/ace/lib/format.js

Ignores failing css files after formatting changes
@bdeining
- `mvn clean install` ui directory
[DDF-4107](https://codice.atlassian.net/browse/DDF-4107) …

DDF-4107 Ignores failing css files after formatting changes

---

distribution/docs/src/main/resources/content/_using/using-catalog-search-ui.adoc

Fix typo from https://github.com/codice/ddf/pull/3691/files#diff-b7f0fbe68f662c37a11f59b4ec36aa3a. …

DDF-4114 Fix docs typo

---

distribution/docs/src/main/resources/content/_dependencyList/ddf-dependency-list.adoc
pom.xml

Upgrades bouncy castle to 1.60
@emmberk @kcover @stustison 
@clockard
@coyotesqrl
Build
Basic ingest and search of resource
Verify no bouncy castle related errors/warnings in logs 
Bouncy castle needs to be upgraded to address SonaType findings.
[DDF-4110](https://codice.atlassian.net/browse/DDF-4110) …

DDF-4110 Upgrade bouncy castle to 1.60

---

catalog/transformer/catalog-transformer-streaming-impl/src/main/java/org/codice/ddf/transformer/xml/streaming/impl/Gml3ToWktImpl.java

Adds a ThreadLocal XML parser in `Gml3ToWktImpl` so multi-threaded ingests don't run into race conditions.
@figliold 
@paouelle 
@jhunzik 
@rzwiefel
@tbatie
Ingest multiple XML files containing GML at the same time in Intrigue and verify the XML input transformer doesn't fail.
[DDF-4109](https://codice.atlassian.net/browse/DDF-4109) …

DDF-4109 Add a ThreadLocal parser for Gml3ToWktImpl

---

platform/security/idp/security-idp-client/pom.xml
platform/security/idp/security-idp-client/src/main/java/org/codice/ddf/security/idp/client/AssertionConsumerService.java
platform/security/idp/security-idp-client/src/test/java/org/codice/ddf/security/idp/client/AssertionConsumerServiceTest.java

Adds null checks to AssertionConsumerService in case the system gets in a bad state.
@ahoffer @blen-desta @brjeter 
@rzwiefel
@tbatie
[DDF-4059](https://codice.atlassian.net/browse/DDF-4059) …

[2.13.x] DDF-4059 Added a null check in AssertionConsumerService:getSamlResponse()

---

ui/packages/catalog-ui-search/src/main/webapp/component/metacard-archive/metacard-archive.view.js

This PR fixes a typo:
@kcover @peterhuffer 
@clockard
@vinamartin
CI build
This PR is so simple that it does not need to be manually tested. …

DDF-2824 Fixed typo in archive message

---

platform/security/filter/security-filter-csrf/pom.xml
platform/security/filter/security-filter-csrf/src/main/java/org/codice/ddf/security/filter/csrf/CsrfFilter.java
platform/security/filter/security-filter-csrf/src/main/resources/OSGI-INF/blueprint/blueprint.xml
platform/security/filter/security-filter-csrf/src/test/groovy/org/codice/ddf/security/filter/csrf/CsrfFilterSpec.groovy

Link to 2.13.x PR: https://github.com/codice/ddf/pull/3698
____
@ethantmanns 
@peterhuffer 
@coyotesqrl
@figliold

DDF-3941 Add Jetty User Agent to CSRF Filter

---

catalog/transformer/catalog-transformer-streaming-impl/src/main/java/org/codice/ddf/transformer/xml/streaming/impl/Gml3ToWktImpl.java

Link to 2.13.x PR: #3681 
____
Adds a ThreadLocal XML parser in Gml3ToWktImpl so multi-threaded ingests don't run into race conditions (since the parser is not thread safe).
@figliold
@paouelle
@jhunzik
@rzwiefel
@tbatie
Ingest multiple XML files containing GML at the same time in Intrigue and verify the XML input transformer doesn't fail.
[DDF-4109](https://codice.atlassian.net/browse/DDF-4109) …

DDF-4109 Creates ThreadLocal parser in Gml3ToWktImpl (#3681)

---

ui/packages/catalog-ui-search/src/main/webapp/component/alert-settings/alert-settings.hbs
ui/packages/catalog-ui-search/src/main/webapp/component/alert-settings/alert-settings.view.js
ui/packages/catalog-ui-search/src/main/webapp/component/slideout/slideout.less
ui/packages/catalog-ui-search/src/main/webapp/js/model/User.js

Enables persistent notifications by default and changes expiration date from 1 day to 1 month.
@Bdthomson @hayleynorton @lamhuy 
@bdeining
@djblue 
1. Build and install DDF
2. Click on the gear icon in top right of the search ui
3. Click on Notifications
4. Verify that persistent notifications are enabled and that the expiration date is 1 month.
[DDF-4101](https://codice.atlassian.net/browse/DDF-4101) …

DDF-4101 Enabled persistent notifications by default

---

ui/packages/catalog-ui-search/src/main/webapp/component/query-interactions/query-interactions.view.js
ui/packages/catalog-ui-search/src/main/webapp/component/query-item/query-item.view.js
ui/packages/catalog-ui-search/src/main/webapp/js/model/Query.js

Link to 2.13.x PR: #3705 
____
When rerunning a query from the search ui it will reset the pagnation to show the first result.
@Bdthomson @hayleynorton 
@djblue
@figliold
1. Build and install DDF
2. Ingest a large amount of data (250+). Ex reuters xml data set.
3. Create a query and search.
4. Click the >> button to go to the end of the current result set.
5. Click the more button to get to the next page.
6. Rerun the query and verify that the results start off at 1-25.
[DDF-4118](https://codice.atlassian.net/browse/DDF-4118)
- ✏️ (Pencil) …

DDF-4118 When rerunning a query from the search ui, it will reset the pagnation

---

libs/pom.xml
libs/tlmatcher/pom.xml
libs/tlmatcher/src/main/java/org/codice/util/tlmatcher/TimeLimitedMatcher.java
libs/tlmatcher/src/test/java/org/codice/util/tlmatcher/TimeLimitedMatcherTest.java

Creates a customized, reduced-scope RegEx matcher for time-limited searches. These matches may be used in place of standard `Matcher` instances to ensure timely responses are returned to the caller or, in those cases where the input regex is too complex, to protect the caller from over-long response times.
@brjeter 
@paouelle 
@pklinef 
@rzwiefel
@stustison
This is new low-level functionality that has not been utilized anywhere in DDF yet. For now, testing can be performed by calling this factory manually, or by relying on the provided unit tests.
[DDF-4113](https://codice.atlassian.net/browse/DDF-4113) …

DDF-4113 Adds time-limited RegEx matcher

---

.github/CODEOWNERS

Modified Codeowners

---

catalog/core/catalog-core-validationparser/src/main/java/ddf/catalog/validation/impl/ValidationParser.java
catalog/core/catalog-core-validationparser/src/test/groovy/ddf/catalog/validation/impl/ValidationParserSpec.groovy
catalog/core/catalog-core-validator/pom.xml
catalog/core/catalog-core-validator/src/main/java/ddf/catalog/validation/impl/validator/RelationshipValidator.java
catalog/core/catalog-core-validator/src/test/groovy/ddf/catalog/validation/impl/RelationshipValidatorSpec.groovy
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/MetacardApplication.java
distribution/docs/src/main/resources/content/_devComponents/global-attribute-validators.adoc
ui/packages/catalog-ui-search/src/main/webapp/component/ingest-details/ingest-details.view.js
ui/packages/catalog-ui-search/src/main/webapp/component/ingest/ingest.view.js
ui/packages/catalog-ui-search/src/main/webapp/component/input/geometry/input-geometry.view.js
ui/packages/catalog-ui-search/src/main/webapp/component/location-new/location-new.view.js
ui/packages/catalog-ui-search/src/main/webapp/component/property/property.hbs
ui/packages/catalog-ui-search/src/main/webapp/component/property/property.less
ui/packages/catalog-ui-search/src/main/webapp/component/property/property.view.js
ui/packages/catalog-ui-search/src/main/webapp/styles/mixins.less

Add relational validators to the ingest editor.
@SmithJosh 
@jrnorth 
@vina
Use the definitions files to create relational constraints. Add those attributes to the ingest editor configuration in intrigue. Try to upload files with attributes that violate those constraints and verify that the correct messages are displayed. Also configure some attribute aliases and verify that the messages use the aliased terms.
[DDF-4082](https://codice.atlassian.net/browse/DDF-4082) …

DDF-4082 Add relational validators to the ingest editor

---

catalog/opensearch/catalog-opensearch-source/src/main/java/org/codice/ddf/opensearch/source/OpenSearchParserImpl.java
catalog/opensearch/catalog-opensearch-source/src/test/groovy/org/codice/ddf/opensearch/source/OpenSearchParserImplSpec.groovy
catalog/opensearch/catalog-opensearch-source/src/test/groovy/org/codice/ddf/opensearch/source/OpenSearchSourceSpec.groovy
catalog/opensearch/catalog-opensearch-source/src/test/java/org/codice/ddf/opensearch/source/OpenSearchParserImplTest.java

Link to 2.13.x PR: https://github.com/codice/ddf/pull/3715
____
@bdeining
@clockard
[DDF-4130](https://codice.atlassian.net/browse/DDF-4130)

DDF-4130 Fixed searching an OpenSearchSource by a keyword that contains a space

---

catalog/spatial/registry/registry-federation-admin-service-impl/pom.xml
catalog/spatial/registry/registry-federation-admin-service-impl/src/test/java/org/codice/ddf/registry/federationadmin/service/impl/FederationAdminServiceImplTest.java
catalog/spatial/registry/registry-federation-admin-service-impl/src/test/java/org/codice/ddf/registry/federationadmin/service/impl/RefreshRegistryEntriesTest.java
catalog/spatial/registry/registry-federation-admin-service-impl/src/test/java/org/codice/ddf/registry/federationadmin/service/impl/RegistryPublicationServiceImplTest.java
catalog/spatial/registry/registry-federation-admin-service-impl/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
platform/security/common/src/main/java/org/codice/ddf/security/common/Security.java

Link to 2.13.x PR: #3584 
____
Prevents overriding of the Security.getSystemSubject method to prevent malicious persons from replacing secured versions with unsecured versions of classes/services.
forward port of #3584
@jhunzik @ethantmanns 
@tbatie @figliold 
1. Get changes (make sure you have changes from CAL-460 or else some tests in CAL will break due to not being able to mock final methods) and test respective unit tests.
2. Install then run DDF and hit Security.getSystemSubject method and make sure nothing breaks. …

DDF-4055 Changed method to be final and fixed unit tests

---

distribution/docs/src/main/resources/content/_appReferences/mg-admin.adoc
distribution/docs/src/main/resources/content/_appReferences/mg-broker-app.adoc
distribution/docs/src/main/resources/content/_appReferences/mg-catalog.adoc
distribution/docs/src/main/resources/content/_appReferences/mg-geowebcache.adoc
distribution/docs/src/main/resources/content/_appReferences/mg-platform.adoc
distribution/docs/src/main/resources/content/_appReferences/mg-registry.adoc
distribution/docs/src/main/resources/content/_appReferences/mg-resource-mgmt.adoc
distribution/docs/src/main/resources/content/_appReferences/mg-security.adoc
distribution/docs/src/main/resources/content/_appReferences/mg-solr.adoc
distribution/docs/src/main/resources/content/_appReferences/mg-spatial.adoc
distribution/docs/src/main/resources/content/_appReferences/mg-ui.adoc
distribution/docs/src/main/resources/content/_configuring/jetty-threadpool-settings.adoc

Copy edits to documentation sections on sources and application references.
@mcalcote @ahoffer @austinsteffes @garrettfreibott 
@clockard
@lessarderic
@shaundmorris
content changes only  …

DDF-2824 updated app ref docs

---

broker/broker-app/src/main/resources/features.xml
broker/broker-connection-factory/pom.xml
broker/broker-route-manager/pom.xml
broker/broker-route-manager/src/main/resources/OSGI-INF/blueprint/blueprint.xml
broker/broker-topic-logger/pom.xml
broker/broker-topic-logger/src/main/java/org/codice/ddf/broker/logger/TopicLogger.java
broker/broker-topic-logger/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/AbstractDurableFileConsumer.java
catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/DurableFileEndpoint.java
catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/DurableFileSystemFileConsumer.java
catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/DurableWebDavFileConsumer.java
distribution/ddf-common/src/main/resources/etc/artemis-backup.xml
distribution/ddf-common/src/main/resources/etc/artemis.xml
distribution/ddf-common/src/main/resources/security/default.policy
distribution/docs/src/main/resources/content/_reference/_appReferences/mg-broker-app.adoc
distribution/sdk/artemis-sandbox/pom.xml
distribution/sdk/artemis-sandbox/src/main/java/sdk.example.route/CoreProducerConsumerExample.java
distribution/sdk/artemis-sandbox/src/main/resources/OSGI-INF/blueprint/blueprint.xml
distribution/sdk/artemis-sandbox/src/main/resources/sdk-example-route.xml
distribution/test/itests/test-itests-common/src/main/resources/sdk-example-route.xml
distribution/test/itests/test-itests-ddf/pom.xml
distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestMessageBroker.java
distribution/test/itests/test-itests-dependencies-app/src/main/filtered-resources/features.xml
features/camel/src/main/feature/feature.xml
features/pom.xml
pom.xml
thirdparty/restito/pom.xml

Link to 2.13.x PR: #3651 
____
@harrison-tarr @roelens8 @KalCramer @derekwilhelm
https://github.com/orgs/codice/teams/core-apis
@clockard
[DDF-3973](https://codice.atlassian.net/browse/DDF-3973) …

DDF-3973 upgrade to camel 2.22.0 and artemis 2.6.2 (#3651)

---

platform/security/filter/security-filter-csrf/pom.xml
platform/security/filter/security-filter-csrf/src/main/java/org/codice/ddf/security/filter/csrf/CsrfFilter.java
platform/security/filter/security-filter-csrf/src/main/resources/OSGI-INF/blueprint/blueprint.xml
platform/security/filter/security-filter-csrf/src/test/groovy/org/codice/ddf/security/filter/csrf/CsrfFilterSpec.groovy

- Whitelisted WSDL URLs
- Whitelisted POST to `/services/login`
@garrettfreibott @brjeter 
@coyotesqrl
@stustison
- Able to access the wsdl urls listed under `/services` 
- Able to log in by going to `/login` …

[2.13.x] DDF-3941 Whitelisted WSDL URLs

---

platform/security/filter/security-filter-csrf/pom.xml
platform/security/filter/security-filter-csrf/src/main/java/org/codice/ddf/security/filter/csrf/CsrfFilter.java
platform/security/filter/security-filter-csrf/src/main/resources/OSGI-INF/blueprint/blueprint.xml
platform/security/filter/security-filter-csrf/src/test/groovy/org/codice/ddf/security/filter/csrf/CsrfFilterSpec.groovy

Link to 2.13.x PR: https://github.com/codice/ddf/pull/3717
@garrettfreibott @brjeter
@coyotesqrl
@stustison

DDF-3941 Whitelisted WSDL URLs

---

platform/security/filter/security-filter-csrf/pom.xml
platform/security/filter/security-filter-csrf/src/main/java/org/codice/ddf/security/filter/csrf/CsrfFilter.java
platform/security/filter/security-filter-csrf/src/main/resources/OSGI-INF/blueprint/blueprint.xml
platform/security/filter/security-filter-csrf/src/test/groovy/org/codice/ddf/security/filter/csrf/CsrfFilterSpec.groovy

Changed the user agent whitelist to a user agent blacklist
@garrettfreibott @brjeter 
@rzwiefel
@stustison
- Verify that endpoints under /services that are not whitelisted cannot be accessed from a browser (eg. https://localhost:8993/services/csw?service=CSW&version=2.0.2&request=GetCapabilities)
- Verify that the endpoint can be accessed from postman or curl.
- verify that basic DDF functionalities still work (ingest, query, download, action providers) …

[2.13.x] DDF-3941 Changed the user agent whitelist to a user agent blacklist in the CSRF filer

---

ui/packages/catalog-ui-search/src/main/webapp/react-component/text-field/text-field.js

Link to 2.13.x PR: https://github.com/codice/ddf/pull/3723
____
@tbatie
@ethantmanns
@djblue
1. Open Intrigue basic search form
2. Enter 0 for the latitude and 20 for the longitude
3. Verify latitude and longitude values do not disappear
https://codice.atlassian.net/browse/DDF-4137 …

DDF-4137: Intrigue basic search form - "0" latitude and longitude values disappear

---

platform/security/filter/security-filter-csrf/pom.xml
platform/security/filter/security-filter-csrf/src/main/java/org/codice/ddf/security/filter/csrf/CsrfFilter.java
platform/security/filter/security-filter-csrf/src/main/resources/OSGI-INF/blueprint/blueprint.xml
platform/security/filter/security-filter-csrf/src/test/groovy/org/codice/ddf/security/filter/csrf/CsrfFilterSpec.groovy

Link to 2.13.x PR: https://github.com/codice/ddf/pull/3727
@garrettfreibott @brjeter
@rzwiefel
@stustison

DDF-3941 Changed the user agent whitelist to a user agent blacklist

---

distribution/docs/src/main/resources/content/_configuring/configuring-guest-access.adoc
platform/security/handler/security-handler-api/pom.xml
platform/security/handler/security-handler-api/src/main/java/org/codice/ddf/security/handler/api/GuestAuthenticationToken.java
platform/security/platform-security-core-api/pom.xml
platform/security/platform-security-core-api/src/main/java/ddf/security/principal/GuestPrincipal.java
platform/security/sts/security-sts-guestclaimshandler/pom.xml
platform/security/sts/security-sts-guestclaimshandler/src/main/java/org/codice/ddf/security/claims/guest/GuestClaimsHandler.java
platform/security/sts/security-sts-guestclaimshandler/src/test/java/org/codice/ddf/security/claims/guest/GuestClaimsHandlerTest.java
platform/security/sts/security-sts-guestvalidator/pom.xml
platform/security/sts/security-sts-guestvalidator/src/main/java/org/codice/ddf/security/validator/guest/GuestValidator.java
platform/security/sts/security-sts-guestvalidator/src/test/java/org/codice/ddf/security/validator/guest/GuestValidatorTest.java

- Replaces IP Address suffix on `Guest@....` Principal name with a randomly generated value
- Adds a security audit indicating the mapping from the incoming IP Address to the generated internal ID
- Caches the internal IDs for 30 minutes so they can be reused for Guest access from the same IP
@brjeter @garrettfreibott @bakejeyner
@clockard
@stustison
1. Log in as guest and ensure a security message of the form `Mapping IP Addr [[0:0:0:0:0:0:0:1]] to Internal ID [200f7e55Xda24X4ec3X8e9fX2bad7393fd53]` appears
2. Ingest a record and check that its PoC field indicates `Guest@[RANDOM]` where the random value matches that in the audit log
3. Using a new browser or incognito window, log in as guest again (within 30 minutes) and ensure that 
a. No new audit log is written
b. …

[2.13.x] DDF-4144 Changes name format of Guest Principal so it no longer includes IP Address

---

features/security/pom.xml
features/security/src/main/feature/feature.xml
platform/security/idp/security-idp-plugin/pom.xml
platform/security/idp/security-idp-plugin/security-idp-plugin-requestsubjectvalidator/pom.xml
platform/security/idp/security-idp-plugin/security-idp-plugin-requestsubjectvalidator/src/main/java/org/codice/ddf/security/idp/plugin/requestsubjectvalidator/RequestSubjectValidatorPresignPlugin.java
platform/security/idp/security-idp-plugin/security-idp-plugin-requestsubjectvalidator/src/main/resources/OSGI-INF/blueprint/blueprint.xml
platform/security/idp/security-idp-plugin/security-idp-plugin-requestsubjectvalidator/src/test/groovy/org/codice/ddf/security/idp/plugin/requestsubjectvalidator/RequestSubjectValidatorPresignPluginSpec.groovy
platform/security/idp/security-idp-plugin/security-idp-plugin-requestsubjectvalidator/src/test/resources/SAMLResponse.xml
platform/security/idp/security-idp-plugin/security-idp-plugin-requestsubjectvalidator/src/test/resources/ssometadata.xml
platform/security/idp/security-idp-plugin/security-idp-plugin-subjectconfirmation/src/test/groovy/org/codice/ddf/security/idp/plugin/subjectconfirmation/SubjectConfirmationPresignPluginSpec.groovy
platform/security/pom.xml

Verifies that the Subject in the received AuthnRequest refers to the same principle (user) as the Subject in the created Response.
@blen-desta 
@brjeter 
@clockard
@coyotesqrl
Run [this branch of the SAML CTK](https://github.com/codice/saml-conformance/pull/200) against the built & installed DDF. The invalid subject error tests should pass.
[DDF-4139](https://codice.atlassian.net/browse/DDF-4139) …

DDF-4139 DDF should validate the Subject sent in the AuthnRequest

---

distribution/ddf-common/src/main/resources/common-bin.xml
distribution/ddf-common/src/main/resources/etc/blacklisted.properties
features/pom.xml

Upgrades Netty 3.9.2 and 4.0.33.
Since v4.0.33 is a transitive dependency used by the karaf-decanter-cassandra I looked into upgrading that. However the newest version 2.0.0 still had the dependency on 4.0.33. Because of this karaf-decanter-cassandra is added to the blacklisted.properties file and Netty v4.0.33 has been added to the list of exclusions. 
@blen-desta @brjeter 
@clockard
@tbatie
> Install DDF
> Run ```find . | egrep -i "netty.*(3\.9\.2|4\.\0\.33)```
> Start DDF
> Run ```feature:list | grep cassandra```
> Both of these should produce no results
> Ingest change some settings, make sure nothing breaks 👍 
[DDF-4129](https://codice.atlassian.net/browse/DDF-4129) …

[2.13.x] DDF-4129 Updating netty versions and blacklisting features that use outdated versions

---

distribution/docs/src/main/resources/content/_managing/_configuring/jetty-threadpool-settings.adoc
distribution/docs/src/main/resources/content/_reference/_appReferences/mg-admin.adoc
distribution/docs/src/main/resources/content/_reference/_appReferences/mg-broker-app.adoc
distribution/docs/src/main/resources/content/_reference/_appReferences/mg-catalog.adoc
distribution/docs/src/main/resources/content/_reference/_appReferences/mg-geowebcache.adoc
distribution/docs/src/main/resources/content/_reference/_appReferences/mg-platform.adoc
distribution/docs/src/main/resources/content/_reference/_appReferences/mg-registry.adoc
distribution/docs/src/main/resources/content/_reference/_appReferences/mg-resource-mgmt.adoc
distribution/docs/src/main/resources/content/_reference/_appReferences/mg-security.adoc
distribution/docs/src/main/resources/content/_reference/_appReferences/mg-solr.adoc
distribution/docs/src/main/resources/content/_reference/_appReferences/mg-spatial.adoc
distribution/docs/src/main/resources/content/_reference/_appReferences/mg-ui.adoc

**Port to `master` of PR [3706](https://github.com/codice/ddf/pull/3706)**
Copy edits to documentation sections on sources and application references.
@mcalcote @ahoffer @austinsteffes @garrettfreibott 
@clockard
@lessarderic
@shaundmorris
content changes only  …

DDF-2824 updated app ref docs (#3706)

---

ui/packages/ace/lib/webpack.config.js
ui/packages/catalog-ui-search/src/main/webapp/component/result-item/result-item.view.js
ui/packages/catalog-ui-search/src/main/webapp/plugins/result-item.js

Makes query result item extensible
@gjvera 
@millerw8 
@willwill96 
@codice/ui 
@bdeining
- `mvn clean install` ui directory
- ingest data with stereo pair
- replicate demo
[DDF-4121](https://codice.atlassian.net/browse/DDF-4121)
[demo](https://youtu.be/Jv2TeIyJyQE) …

DDF-4121 Makes query result item extensible

---

.github/CODE_OF_CONDUCT.md

Adds CoC.
@ahoffer @blen-desta 
N/A
@rzwiefel
@shaundmorris
@vinamartin
N/A
No Jira ticket created.
Fixes: #3764 

Adds Code of Conduct for DDF contributors.

---

catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/DynamicSchemaResolver.java
catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/DynamicSchemaResolverTest.java

Protect against a vulnerability in tinybinary when attempting to generate xpath support for metacard metadata.
@SmithJosh 
@vinamartin 
[DDF-4152](https://codice.atlassian.net/browse/DDF-4152) …

DDF-4152 Handle unchecked exceptions

---

distribution/docs/src/main/resources/content/_managing/_configuring/configuring-guest-access.adoc
platform/security/handler/security-handler-api/pom.xml
platform/security/handler/security-handler-api/src/main/java/org/codice/ddf/security/handler/api/GuestAuthenticationToken.java
platform/security/platform-security-core-api/pom.xml
platform/security/platform-security-core-api/src/main/java/ddf/security/principal/GuestPrincipal.java
platform/security/sts/security-sts-guestclaimshandler/pom.xml
platform/security/sts/security-sts-guestclaimshandler/src/main/java/org/codice/ddf/security/claims/guest/GuestClaimsHandler.java
platform/security/sts/security-sts-guestclaimshandler/src/test/java/org/codice/ddf/security/claims/guest/GuestClaimsHandlerTest.java
platform/security/sts/security-sts-guestvalidator/pom.xml
platform/security/sts/security-sts-guestvalidator/src/main/java/org/codice/ddf/security/validator/guest/GuestValidator.java
platform/security/sts/security-sts-guestvalidator/src/test/java/org/codice/ddf/security/validator/guest/GuestValidatorTest.java

Link to 2.13.x PR: #3744 
____
@brjeter @garrettfreibott @bakejeyner
@stustison
@tbatie
_N.B. The following line is present to test GitHub Issues and Projects w/triggers_
Fixes: #3743 …

DDF-4144 Changes name format of Guest Principal so it no longer includes IP Address

---

ui/packages/catalog-ui-search/src/main/webapp/js/CQLUtils.js
ui/packages/catalog-ui-search/src/main/webapp/js/widgets/openlayers.polygon.js

Fixed Multipolygon handling on the 2d map.
@leo-sakh @djblue 
@millerw8
Build / Install / Construct and `anyGeo` query with a 3d array (multipolygon) / verify it is drawn correctly and the query is sent to the backend with a buffer correctly
before
after …

DDF-3999 Fixed Multipolygon handling on the 2d map

---

ui/packages/catalog-ui-search/src/main/webapp/react-component/location/point-radius.js

Prevents users from entering other text into the lat/lon and radius fields that can cause issues deserializing a saved search.
@Variadicism 
@SmithJosh 
@djblue
@figliold
@tbatie
* Build UI
* Attempt to enter non-numbers into basic search point-radius lat/lon
* Verify you can't
Entering non-numbers resulted in them being saved in saved searches and caused errors to be thrown during deserialization.
[DDF-4154](https://codice.atlassian.net/browse/DDF-4154) …

DDF-4154 Only allow number input for Intrigue point-radius latlon

---

ui/packages/catalog-ui-search/src/main/webapp/react-component/location/point-radius.js

Link to 2.13.x PR: #3768
____
Prevents users from entering other text into the lat/lon and radius fields that can cause issues deserializing a saved search.
@willwill96 
@SmithJosh 
@djblue
@figliold
@tbatie
* Build UI
* Attempt to enter non-numbers into basic search point-radius lat/lon
* Verify you can't
Entering non-numbers resulted in them being saved in saved searches and caused errors to be thrown during deserialization.
[DDF-4154](https://codice.atlassian.net/browse/DDF-4154) …

[FORWARDPORT] DDF-4154 Only allow number input for Intrigue point-radius latlon

---

catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/DynamicSchemaResolver.java
catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/DynamicSchemaResolverTest.java

Protect against a vulnerability in tinybinary when attempting to generate xpath support for metacard metadata.
Link to 2.13.x PR: #3752 
@SmithJosh 
@vinamartin …

DDF-4152 Handle unchecked exceptions (#3752)

---

catalog/spatial/wps/pom.xml

DDF-4103 Add name to WPS pom

---

distribution/solr-distro/pom.xml

Changes solr 7.4.0 download to codice hosting
@ahoffer 
@mcalcote 
@clockard
@coyotesqrl
@pklinef
build 
[DDF-4167](https://codice.atlassian.net/browse/DDF-4167)
- ❗ …

[2.13.x] DDF-4167 Changing solr 7.4 download to codice hosting

---

distribution/solr-distro/pom.xml

Forward port of https://github.com/codice/ddf/pull/3785
Changes solr 7.4.0 download to codice hosting
@ahoffer
@mcalcote
@clockard
@coyotesqrl
@pklinef
build it
[DDF-4167](https://codice.atlassian.net/browse/DDF-4167)
Screenshots
Checklist:
Please see Notes on Review Process for further guidance on requirements for merging and abbreviated reviews.
Review Comment Legend:
✏️ …

DDF-4167 Changing solr 7.4 download to codice hosting

---

platform/admin/core/admin-core-impl/src/main/java/org/codice/ddf/admin/core/impl/SystemPropertiesAdmin.java
platform/admin/core/admin-core-impl/src/test/java/org/codice/ddf/admin/core/impl/SystemPropertiesAdminTest.java

Link to 2.13.x PR: #3728 
@clockard
@vinamartin 

DDF-4135 Don't overwite internal ports with external ports

---

platform/security/idp/security-idp-client/src/main/java/org/codice/ddf/security/idp/client/AssertionConsumerService.java
platform/security/idp/security-idp-client/src/main/java/org/codice/ddf/security/idp/client/AuthnResponseValidator.java
platform/security/idp/security-idp-client/src/main/java/org/codice/ddf/security/idp/client/IdpHandler.java
platform/security/idp/security-idp-client/src/main/java/org/codice/ddf/security/idp/client/IdpLogoutActionProvider.java
platform/security/idp/security-idp-client/src/main/java/org/codice/ddf/security/idp/client/LogoutRequestService.java
platform/security/idp/security-idp-plugin/security-idp-plugin-namequalifier/src/main/java/org/codice/ddf/security/idp/plugin/namequalifier/NameQualifierPresignPlugin.java
platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/binding/api/impl/ValidatorImpl.java
platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/server/IdpEndpoint.java
platform/security/servlet/security-servlet-logout/src/main/java/org/codice/ddf/security/servlet/logout/LocalLogoutServlet.java
ui/packages/security-servlet-logout/src/main/resources/index.html
ui/packages/security-servlet-logout/src/main/resources/logout-response.html
ui/packages/security-servlet-logout/src/main/webapp/js/logout-response.js
ui/packages/security-servlet-logout/src/main/webapp/js/main.js

Changed internal URL references in the IdP code to use the external URL
@brjeter @SmithJosh
@djblue 
@coyotesqrl
@stustison 
1- Verify DDF still works without a proxy
- Verify log in and log out
- Change the AuthnType in the WebContextPolicyManager to `/=BASIC`
- Verify login/logout works with BASIC
- Run the SamlConf tests. Will get the following two failures since the fix was not backported
- Profiles 4.1.4.1: POST AuthnRequest With Subject Containing an Invalid Name ID Test FAILED
- Profiles 4.1.4.1: Redirect AuthnRequest With Subject Containing an Invalid Name ID Test FAILED
2- Verify DDF works behind a proxy
Use [nginx-reverse-proxy](https://github.com/LinkMJB/nginx-reverse-proxy/pull/3) or another reverse proxy
- Testing access …

[2.13.x] DDF-4111 Changed internal url references in the IdP code to use the external url

---

.gitignore
distribution/docs/src/main/resources/content/_architectures/url-resource-reader.adoc
distribution/docs/src/test/java/ddf/docs/DocumentationTest.java

Fixes documentation unit test to be platform-independent.
@clockard
@lessarderic
@shaundmorris
builds successfully and test passes …

DDF-2824 improvement to docs unit test

---

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/cql/CqlRequest.java
ui/packages/catalog-ui-search/src/main/webapp/js/model/Query.js

- Adds batchId to queries generated from the frontend.
- Pull batchId off of request and place on request properties.
- Pull requestId off of request and place on request properties.
@andrewzimmer
@Schachte 
@djblue 
View the outbound network traffic on the WS request and observe that each new request has a new batch id.
[DDF-4164](https://codice.atlassian.net/browse/DDF-4164)
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet …

DDF-4164 Adding batchId to queries

---

catalog/opensearch/catalog-opensearch-source/src/main/java/org/codice/ddf/opensearch/source/OpenSearchSource.java

This PR updates the OpenSearchSoure to not cache it's availability because all source caching should be handled in the CatalogFramework. This is one part of fixing the issue described in [DDF-1366](https://codice.atlassian.net/browse/DDF-1366).
The OpenSearchSource#isAvailable method is not used anywhere inside catalog-opensearch-source. No unit test were updated because there were no unit tests that tested the caching.
@kcover @peterhuffer @pvargas @lamhuy @ethantmanns 
@codice/io 
@clockard
@bdeining 
- CI build
- Confirm that OpenSearch sources can be queried and that their availabilities appear correct in the Admin UI->Catalog->Sources tab and in Intrigue.
https://github.com/codice/ddf/blob/3efc289a995afbddf1170c716233a34ee82eaab8/catalog/core/catalog-core-api/src/main/java/ddf/catalog …

[2.13.x] DDF-1366 Updated OpenSearchSource to not cache availability

---

pom.xml

Quick fix to update from snapshot to production release version of ddf-support libraries.

DDF-4168 Updates ddf-support version to production release.

---

pom.xml

Replace the dependency of a Codice-Parent snapshot with the released DDF-Parent.
@garrettfreibott @austinsteffes @bdeining @brjeter @shaundmorris @clockard @ahoffer @paouelle @stustison 
Build
[DDF-3705](https://codice.atlassian.net/browse/DDF-3705)
- ❗ …

DDF-3705 Set DDF-Parent as the parent pom

---

distribution/docs/src/main/resources/content/_configuring/content-directory-monitor.adoc

This PR adds a note in the CDM documentation to account for when a metacard points to a resource outside of CDM. 
@emmberk 
@peterhuffer 
@clockard
@ricklarsen 
Builds successfully. 
[DDF-4162](https://codice.atlassian.net/browse/DDF-4162) …

[2.13.x] DDF-4162 Updated CDM documentation

---

catalog/opensearch/catalog-opensearch-endpoint/src/main/java/org/codice/ddf/opensearch/endpoint/KeywordTextParser.java
catalog/opensearch/catalog-opensearch-endpoint/src/main/java/org/codice/ddf/opensearch/endpoint/OpenSearchEndpoint.java
catalog/opensearch/catalog-opensearch-endpoint/src/test/groovy/org/codice/ddf/opensearch/endpoint/OpenSearchEndpointSpec.groovy

This PR addresses some static analysis findings in catalog-opensearch-endpoint and updates some logging to match [DDF guidelines](https://codice.atlassian.net/wiki/spaces/DDF/pages/7045131/Log+Levels).
@kcover @peterhuffer 
@clockard
@vinamartin
- CI build
- Confirm that the OpenSource endpoint still works.
[DDF-4130](https://codice.atlassian.net/browse/DDF-4130) …

DDF-4130 Addressed some static analysis findings in catalog-opensearch-endpoint

---

distribution/docs/src/main/resources/content/_configuring/remove-default-users-cont.adoc

Rearranges the default users deletion documentation so it's in one place.
@emmberk @brjeter 
@stustison
Make sure the docs order is similar to the screenshot below.
[DDF-4181](https://codice.atlassian.net/browse/DDF-4181) …

[2.13.x] DDF-4181 Rearrange the default users deletion documentation so it's in one place.

---

distribution/docs/src/main/resources/content/_managing/_configuring/content-directory-monitor.adoc

Link to 2.13.x PR: #3777 
____
This PR adds a note in the CDM documentation to account for when a metacard points to a resource outside of CDM. 
@emmberk 
@peterhuffer 
@clockard
@ricklarsen 
Builds successfully. 
[DDF-4162](https://codice.atlassian.net/browse/DDF-4162) …

DDF-4162 Updated CDM documentation

---

distribution/ddf-common/src/main/resources/security/default.policy

Link to 2.13.x PR: #3797 
@peterhuffer @emmberk
@clockard

DDF-4175 Give SSH bundles read/write access to all files

---

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/util/EndpointUtil.java
catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/util/EndpointUtilTest.java

Fixed refresh result count
@Corey-Collins @GabrielFabian 
@djblue
Build / Install / Verify normal and hit count only queries …

DDF-4120 Fixed refresh result count

---

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/forms/SearchFormsLoader.java

Made Failsafe Asynchronous which fixes downstream itest failures
Master PR https://github.com/codice/ddf/pull/3566
@GabrielFabian @Bdthomson 
@pklinef
@millerw8 
Build / Unzip / make etc forms directory / Install / turn on experimental features / verify search form crud
[DDF-4036](https://codice.atlassian.net/browse/DDF-4036) …

[2.13.x] Made Failsafe Asynchronous

---

catalog/confluence/catalog-confluence-source/src/main/java/org/codice/ddf/confluence/source/ConfluenceFilterDelegate.java
catalog/confluence/catalog-confluence-source/src/test/java/org/codice/ddf/confluence/source/ConfluenceFilterDelegateTest.java
catalog/core/catalog-core-commons/src/main/java/ddf/catalog/filter/delegate/TagsFilterDelegate.java
catalog/core/catalog-core-impl/filter-proxy/src/test/java/ddf/catalog/filter/delegate/TagsFilterDelegateTest.java
catalog/spatial/registry/registry-federation-admin-service-impl/src/main/java/org/codice/ddf/registry/federationadmin/service/impl/FederationAdminServiceImpl.java
distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestRegistry.java

Update ConfluenceFilterDelegate to handle propertyIsGreaterThan
- Also fix and issue with the TagsFilterDelegate 'not' implementation
@coyotesqrl
@rzwiefel
@tbatie
See me for test steps
[DDF-4176](https://codice.atlassian.net/browse/DDF-4176)

DDF-4176 Update ConfluenceFilterDelegate to handle propertyIsGreaterThan

---

distribution/solr-distro/src/main/resources/bin/solr
distribution/solr-distro/src/main/resources/bin/solr.cmd

Link to 2.13.x PR: #3814 
@gordocanchola @garrettfreibott 
@coyotesqrl 
@stustison 

DDF-4035 Constraining java.ext.dirs to java home in external Solr

---

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/security/AccessControlAccessPlugin.java
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/security/AccessControlPolicyPlugin.java
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/security/AccessControlUtil.java

Addresses ACL vulnerabilities reported in SonarCloud 
https://sonarcloud.io/project/issues?id=ddf&resolved=false&types=VULNERABILITY
@troymohl 
@shaundmorris 
@bdeining 
@djblue 
@shaundmorris 
@bdeining  …

DDF-4184 - Resolve SonarQube Vulnerability Warnings

---

ui/packages/ui/src/main/webapp/less/common/banner.less
ui/packages/ui/src/main/webapp/less/installer/style.less

Fixes problem where input boxes would end up on top of header and footer banners.
@emmberk @peterhuffer @oconnormi @kcover 
@codice/ui 
@clockard @rzwiefel 
[DDF-4189](https://codice.atlassian.net/browse/DDF-4189) …

DDF-4189 Fix banner z-index.

---

ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/cesium/geocoder.js
ui/packages/catalog-ui-search/src/main/webapp/js/view/openlayers.geocoder.js

Fixes the pan & zoom capabilities of both maps. 
@Variadicism 	
@samuelechu 	
@codice/ui 
@djblue 
@millerw8
Using both the 3D and 2D maps, type various queries into the pan / zoom search box, such as "par", "tempe", etc and ensure either hitting ENTER or picking from autocomplete moves the camera to the intended target. 
[DDF-4179](https://codice.atlassian.net/browse/DDF-4179) …

DDF-4179 Map pan & zoom by geographic place name appears to search forever and does not reorient the camera

---

Documentation-versions.html
index.html

updates the gh-pages branch (ddf.codice.org) page to reflect 2.13.2 release.
@codice/docs 
@clockard
@coyotesqrl
@lessarderic
@shaundmorris
verify version numbers …

DDF-2824 updated project website for 2.13.2 release

---

catalog/confluence/catalog-confluence-source/src/main/java/org/codice/ddf/confluence/source/ConfluenceFilterDelegate.java
catalog/confluence/catalog-confluence-source/src/test/java/org/codice/ddf/confluence/source/ConfluenceFilterDelegateTest.java
catalog/core/catalog-core-commons/src/main/java/ddf/catalog/filter/delegate/TagsFilterDelegate.java
catalog/core/catalog-core-impl/filter-proxy/src/test/java/ddf/catalog/filter/delegate/TagsFilterDelegateTest.java
catalog/spatial/registry/registry-federation-admin-service-impl/src/main/java/org/codice/ddf/registry/federationadmin/service/impl/FederationAdminServiceImpl.java
distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestRegistry.java
ui/packages/registry-admin-local-ui/src/main/webapp/js/model/Field.js

Link to 2.13.x PR: #3802 #3771 
____
DDF-4161 Fix registry date field validation error
DDF-4176 Update ConfluenceFilterDelegate to handle propertyIsGreaterThan
@coyotesqrl
@shaundmorris
@tbatie
CI Build
[DDF-4161](https://codice.atlassian.net/browse/4161)
[DDF-4176](https://codice.atlassian.net/browse/4176)

DDF-4161 DDF-4176 Master ports

---

ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/openlayers/map.openlayers.js

Missing `this` context preprended to the create vector layers calls were causing failures downstream when rendering multi-geos. 
@codice/ui 
@bdeining
@djblue 
@willwill96 
@adimka 
- ❗ …

DDF-4205 Fixing missing this context in open layers for multi-geos

---

ui/packages/catalog-ui-search/src/main/webapp/component/announcement/CommonMessages.tsx
ui/packages/catalog-ui-search/src/main/webapp/component/query-add/query-add.view.js
ui/packages/catalog-ui-search/src/main/webapp/component/query-adhoc/query-adhoc.view.js
ui/packages/catalog-ui-search/src/main/webapp/component/query-advanced/query-advanced.view.js
ui/packages/catalog-ui-search/src/main/webapp/component/query-basic/query-basic.view.js
ui/packages/catalog-ui-search/src/main/webapp/component/query-editor/query-editor.view.js
ui/packages/catalog-ui-search/src/main/webapp/component/query-settings/query-settings.view.js

Validate search forms (adhoc, basic, advanced) before a search/save is run
@Bdthomson @hayleynorton @alanchampion 
@codice/ui 
@bdeining @andrewkfiedler 
- build/run
- currently validation should always be true, so verify that functionality of all search forms (adhoc, advanced, basic) remains the same.
[DDF-4192](https://codice.atlassian.net/browse/DDF-4192) …

DDF-4192 Add validation to search forms

---

ui/packages/catalog-ui-search/src/main/webapp/component/query-editor/query-editor.view.js

Currently, when editing a search, the original search criteria is not displayed.
Modified the edit text field in Intrigue to show the original criteria.
@brjeter @garrettfreibott 
@codice/ui 
@djblue
Edit a search and make sure that the first key word you searched for is displayed.
[DDF-4196](https://codice.atlassian.net/browse/DDF-4196) …

[2.13.x] DDF-4196 Modified the edit text field in Intrigue to show the original criteria

---

distribution/ddf-common/src/main/resources/security/default.policy
pom.xml

Link to 2.13.x PR: #3856 
____
It updates the reference to the AC debugger to the latest 1.5 version.
@ethantmanns 
@jhunzik 
@kcover 
@codice/test 
@figliold
@tbatie
1. Build DDF
2. Unzip DDF
3. Replace the `<<ALL FILES>>` for the ssh bundles:
```
grant codeBase "file:/org.apache.karaf.shell.ssh/org.apache.sshd.core" {
permission java.io.FilePermission "<<ALL FILES>>", "read,write";
}
```
with
```
grant codeBase "file:/org.apache.karaf.shell.ssh/org.apache.sshd.core" {
permission java.io.FilePermission "${ddf.home.perm}etc${/}keystores${/}-", "read";
permission java.io.FilePermission "${ddf.home.perm}etc${/}ws-security${/}server${/}-", "read";
permission java.io.FilePermission "${ddf.home.perm}etc${/}host.key", "read,write";
permission …
```

[FORWARD PORT] DDF-4199 Updated AC debugger to 1.5

---

ui/packages/catalog-ui-search/src/main/webapp/component/query-adhoc/query-adhoc.view.js
ui/packages/catalog-ui-search/src/main/webapp/component/query-basic/query-basic.view.js

Link to 2.13.x PR: #3844 
@garrettfreibott @blen-desta 
@rzwiefel 
[DDF-4023](https://codice.atlassian.net/browse/DDF-4023)

DDF-4203 Fixes "%" wildcard discrepancies in Intrigue

---

distribution/ddf-common/src/main/resources/bin/ddf
distribution/ddf-common/src/main/resources/bin/ddf.bat
distribution/ddf-common/src/main/resources/security/default.policy
platform/admin/core/admin-core-appservice/pom.xml
platform/admin/core/admin-core-appservice/src/main/java/org/codice/ddf/admin/application/service/impl/ApplicationServiceBean.java
platform/admin/core/admin-core-appservice/src/main/java/org/codice/ddf/admin/application/service/impl/ApplicationServiceBeanMBean.java
platform/admin/core/admin-core-appservice/src/main/resources/OSGI-INF/blueprint/blueprint.xml
platform/admin/core/admin-core-appservice/src/test/java/org/codice/ddf/admin/application/service/impl/ApplicationServiceBeanTest.java
platform/migration/platform-migration/pom.xml
platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/ConfigurationMigrationManager.java
platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/migration/AbstractMigrationSupport.java
platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/migration/ConfigurationMigrationManagerTest.java
ui/packages/ui/src/main/webapp/js/models/Installer.js

Link to 2.13.x PR: #3853 
____
It modified the installer UI such that when comes time to restart DDF, it actually does it not through karaf reboot behavior but takes advantage of the restart logic defined inside the `ddf` and `ddf.bat` scripts. This has the advantages that the ddf scripts will actually restart Solr as well if it needs to.
It also modified migration:import to do the same thing.
@ethantmanns 
@jhunzik 
@figliold
@lessarderic 
1- Unzip DDF and proceed through the UI installer
2- Click restart
3- Verify that Solr is being shutdown and then restarted in addition to DDF
4- Perform a migration:export
5- Perform a migration:import
6- Same as step 3
[DDF-4147](https://codice.atlassian.net/browse/DDF-4147) …

[FORWARD PORT] DDF-4147 Modified UI installer and migration:import to restart Solr as well as DDF

---

catalog/ui/catalog-ui-search-api/pom.xml
catalog/ui/catalog-ui-search-api/src/main/java/org/codice/ddf/catalog/ui/subscription/SubscriptionsPersistentStore.java
catalog/ui/catalog-ui-search/pom.xml
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/MetacardApplication.java
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/monitor/email/EmailNotifier.java
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/monitor/impl/SubscriptionsPersistentStoreImpl.java
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/monitor/impl/TrivialSubscriptionsPersistentStore.java
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/monitor/impl/WorkspaceServiceImpl.java
catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.querymonitor.xml
catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/query/monitor/impl/WorkspaceServiceImplTest.java
platform/email/platform-email-impl/pom.xml
platform/email/platform-email-impl/src/main/java/org/codice/ddf/platform/email/impl/SmtpClientImpl.java
platform/email/platform-email-impl/src/test/java/org/codice/ddf/platform/email/impl/SmtpClientImplITCaseTest.java

- Moves SubscriptionPersistentStore interface into `catalog-ui-search-api` bundle and exports it.
- Publishes the `WorkspacePersistentStore` as a service.
- Removes the cron string config for the `WorkspaceQueryService`.
- Adds new detailed exception to instantiation of an SMTP client session instead of allowing a NPE to get thrown.
- Removes `platform-util-unavailableurls` from `catalog-ui-search` pom because it no longer has to be embedded.
@rzwiefel 
@Schachte 
@bdeining
@millerw8
Full build and installation of `profile-standard` as well as making sure the UI still loads should be enough.
[DDF-4180](https://codice.atlassian.net/browse/DDF-4180)
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Reque …

DDF-4180 Move subscription interface into catalog-ui-search-api bundle

---

ui/packages/admin-security-certificate-ui/src/main/webapp/js/HandlebarsHelpers.js
ui/packages/admin-security-certificate-ui/src/main/webapp/js/model/UrlCertificate.js
ui/packages/admin-security-certificate-ui/src/main/webapp/js/view/UploadModal.view.js
ui/packages/admin-security-certificate-ui/src/main/webapp/templates/certificateDetail.handlebars
ui/packages/admin-security-certificate-ui/src/main/webapp/templates/uploadModal.handlebars

Allows users to upload certificates to the system's trust store.
@tbatie 
@paouelle 
@ethantmanns 
@jhunzik 
@codice/ui 
@djblue
1) Navigate to 'Security' -> 'Certificates'
2) Click on the '+' under System Trust Store
3) Click on the HTTPS Import tab
4) Enter https://www.google.com:443
5) Click Show Certificates
* You will see 2 certificates
6) Click Save
7) Verify certifcates were imported. 
* You will see 'Done!' for each of the two certificates.
7) Click Cancel to close the modal
8) Verify that 'google internet authority g3' and 'www.google.com' are now listed under System Trust Store
9) Navigate to <ddf.home>/etc/keystores
10) Verify the two new certificates are in serverTruststore.jks
* keytool -list -v -keystore serverTruststore.jks …

[2.13.x] DDF-4206: Adding a Certificate/Key via https import fails

---

catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/ExportCommand.java
catalog/core/catalog-core-directorymonitor/pom.xml
catalog/core/catalog-core-directorymonitor/src/test/java/org/codice/ddf/catalog/content/monitor/ContentDirectoryMonitorIT.java
catalog/pom.xml
catalog/spatial/csw/spatial-csw-transformer/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/GetRecordsResponseConverterTest.java
catalog/spatial/registry/registry-federation-admin-service-impl/src/test/java/org/codice/ddf/registry/federationadmin/service/impl/IdentityNodeInitializationTest.java
catalog/transformer/catalog-transformer-common/pom.xml
catalog/transformer/catalog-transformer-rtf/src/test/java/ddf/catalog/transformer/output/rtf/RtfQueryResponseAndMetacardTransformerTest.java
distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFederation.java
features/camel/src/main/feature/feature.xml
features/pom.xml
features/security/src/main/feature/feature.xml
features/test-utilities/src/main/feature/feature.xml
platform/admin/core/admin-core-appservice/src/test/java/org/codice/ddf/admin/application/service/migratable/JsonFeatureTest.java
pom.xml
ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/user/user.tsx

Update dependencies. Fixes a bug or two as well.
@mcalcote @blen-desta @brjeter
@clockard
@coyotesqrl
@stustison …

DDF-4178 updated cxf, camel, http, and shiro

---

ui/packages/admin-security-certificate-ui/src/main/webapp/js/HandlebarsHelpers.js
ui/packages/admin-security-certificate-ui/src/main/webapp/js/model/UrlCertificate.js
ui/packages/admin-security-certificate-ui/src/main/webapp/js/view/UploadModal.view.js
ui/packages/admin-security-certificate-ui/src/main/webapp/templates/certificateDetail.handlebars
ui/packages/admin-security-certificate-ui/src/main/webapp/templates/uploadModal.handlebars

Link to 2.13.x PR: https://github.com/codice/ddf/pull/3854
____
Allows users to upload certificates to the system's trust store.
@paouelle
@ethantmanns
@jhunzik
@codice/ui 
@tbatie
1) Navigate to 'Security' -> 'Certificates'
2) Click on the '+' under System Trust Store
3) Click on the HTTPS Import tab
4) Enter https://www.google.com:443
5) Click Show Certificates
* You will see 2 certificates
6) Click Save
7) Verify certifcates were imported. 
* You will see 'Done!' for each of the two certificates.
7) Click Cancel to close the modal
8) Verify that 'google internet authority g3' and 'www.google.com' are now listed under System Trust Store
9) Navigate to <ddf.home>/etc/keystores
10) Verify the two new certificates are in serverTruststore.jks
* keytool -list …

DDF-4206: Adding a Certificate/Key via https import fails

---

ui/packages/catalog-ui-search/src/main/webapp/component/ingest/ingest.view.js

The third commit in #3729 tried to reduce callback nesting but broke the ingest editor. This PR reverts those changes.
@peterhuffer 
@vinamartin
1. Configure the upload editor with some attributes (under Search UI > Config > Catalog UI Search)
2. Verify you can upload via the Intrigue uploader
[DDF-4082](https://codice.atlassian.net/browse/DDF-4082) …

DDF-4082 Fix upload editor pre-ingest validation

---

catalog/spatial/wfs/1.0.0/spatial-wfs-v1_0_0-source/src/main/resources/OSGI-INF/blueprint/blueprint.xml

- Teams tagged
Link to 2.13.x PR: #3888 
____
@brjeter @Kjames5269 
@clockard
@stustison …

DDF-4047 Adds constructor arg to blueprint for WFS 1.0 Source

---

catalog/spatial/wfs/1.0.0/spatial-wfs-v1_0_0-source/src/main/resources/OSGI-INF/blueprint/blueprint.xml

Adds a ctor arg to blueprint to match updated class ctor.
@brjeter @Kjames5269 
@clockard
@stustison
Build and create a WFS Federated source; ensure it connects. 
This public server should work - http://geothermal.isgs.illinois.edu/ArcGIS/services/OneGeology/ILGS_MODGLS_Geology_WFS/MapServer/WFSServer
[DDF-4047](https://codice.atlassian.net/browse/DDF-4047) …

[2.13.x] DDF-4047 Adds constructor arg to blueprint for WFS 1.0 Source

---

distribution/docs/src/main/resources/content/_catalogFrameworks/standard-catalog-framework.adoc
distribution/docs/src/main/resources/content/_devComponents/editing-docs.adoc
distribution/docs/src/main/resources/templates/build/developing-components.ftl
distribution/docs/src/test/java/ddf/docs/DocumentationTest.java

adds a section to developer documentation to describe process for updating documentation.
@mcalcote @ahoffer @austinsteffes @garrettfreibott 
@codice/docs 
@clockard
@lessarderic
@shaundmorris
- builds successfully with content included
- review content
[DDF-4194](https://codice.atlassian.net/browse/DDF-4194) …

DDF-4194 add section on contributing documentation to docs

---

dependency-check-maven-config.xml

Suppress geowebcache reported OWASP vulnerability. Geowebcache is off by default, and not recommended to be used in a production environment.
@paouelle @kcover @mdang8 @tbatie 
@codice/build 
@clockard
@coyotesqrl
CI build.
[DDF-4231](https://codice.atlassian.net/browse/DDF-4231) …

[2.13.x] DDF-4231 Fix OWASP scan for geowebcache

---

features/admin/src/main/feature/feature.xml
features/migration/src/main/feature/feature.xml
platform/admin/core/admin-core-appservice/pom.xml
platform/admin/core/admin-core-appservice/src/main/java/org/codice/ddf/admin/application/service/command/ProfileInstallCommand.java
platform/admin/core/admin-core-appservice/src/main/java/org/codice/ddf/admin/application/service/impl/ApplicationServiceImpl.java
platform/admin/core/admin-core-appservice/src/main/java/org/codice/ddf/admin/application/service/migratable/JsonBundle.java
platform/admin/core/admin-core-appservice/src/main/java/org/codice/ddf/admin/application/service/migratable/JsonFeature.java
platform/admin/core/admin-core-appservice/src/main/java/org/codice/ddf/admin/application/service/migratable/JsonProfile.java
platform/admin/core/admin-core-appservice/src/main/java/org/codice/ddf/admin/application/service/migratable/JsonUtils.java
platform/admin/core/admin-core-appservice/src/main/java/org/codice/ddf/admin/application/service/migratable/JsonValidatable.java
platform/migration/platform-migration/pom.xml
platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/JsonUtils.java
platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/migration/ExportMigrationManagerImplTest.java
platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/migration/ImportMigrationManagerImplTest.java

This is a Java 11 upgrade PR
It replaces Boon with Gson in platform-migration and admin-core-appservice.
@blen-desta 
@brjeter 
@jhunzik 
@ethantmanns 
@coyotesqrl
@figliold
@tbatie
- Unzip and start DDF (do not run installer)
- execute migration:export
- execute migration:decrypt
- install DDF via profile:install command
- after restart, execute migration:import which will bring you back to pre-install state
- re-install DDF via the UI
This is a Java11 upgrade PR.
[DDF-4210](https://codice.atlassian.net/browse/DDF-4210) …

[J11] DDF-4210 Replace Boon in platform-migration and admin-core-appservice

---

catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/query/handlers/CqlTransformHandlerTest.java

Fix regex issue I saw on my CI build failing:
https://jenkins.codice.org/job/DDF-Jobs/job/pr/job/Linux/5487/
@willwill96 
@bdeining
@millerw8  …

DDF-3997 Modify regex to allow for the milliseconds placeholder to be optional

---

ui/packages/ace/lib/webpack.config.js

Improves ui dev server CPU utilization
@glenhein 
@rymach 
@rzwiefel
- yarn start
[DDF-4232](https://codice.atlassian.net/browse/DDF-4232)

DDF-4232 Improves ui dev server CPU utilization

---

ui/packages/catalog-ui-search/src/main/webapp/react-component/auto-complete/auto-complete.spec.js

Updates failing unit tests
@Lambeaux 
@gjvera 
@bdeining
@rzwiefel
- `mvn clean install` ui directory
[DDF-4200](https://codice.atlassian.net/browse/DDF-4200)

DDF-4200 Updates failing unit tests

---

libs/libs-pomfix/lib/fix.js

Allows users to include src/ in their path to DDF
@glenhein 
@oconnormi 
@Variadicism 
@tbatie
- full build of libs/libs-pomfix and libs-pomfix-run
[DDF-4229](https://codice.atlassian.net/browse/DDF-4229) …

DDF-4229 Allows users to include src/ in their path to DDF

---

ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/openlayers/map.openlayers.js
ui/packages/catalog-ui-search/src/main/webapp/js/widgets/openlayers.bbox.js
ui/packages/catalog-ui-search/src/main/webapp/js/widgets/openlayers.circle.js
ui/packages/catalog-ui-search/src/main/webapp/js/widgets/openlayers.line.js
ui/packages/catalog-ui-search/src/main/webapp/js/widgets/openlayers.polygon.js

- Persisting proper ID to OL feature objects
- Adding OL API extension to retrieve map instance
Adds cid's to each geo-type for open layers features.
Also adds the ability to return the open layers map instance.
@Schachte 
@adimka
@middlets719  
@bdeining
@djblue 
@bdeining
@djblue 
Load the map and make sure it loads on intrigue.
[DDF-4234](https://codice.atlassian.net/browse/DDF-4234) …

DDF-4234 Updating Open Layers to Persist IDs onto Map

---

platform/admin/core/admin-core-impl/src/main/java/org/codice/ddf/admin/core/impl/ConfigurationAdminImpl.java

Decrease amount of time it takes to load the Admin UI by using a populated map of ObjectClassDefinitions instead of fetching it per config in a loop.
@Bdthomson @kcover @brjeter @stustison 
@codice/ui 
@clockard
@pklinef 
Ensure the Admin UI loads within a second or 2 by inspecting the Admin UI network request in your browsers dev tools.
Admin UI was taking 5-30 seconds to load.
[DDF-4244](https://codice.atlassian.net/browse/DDF-4244) …

[2.13.x] DDF-4244 Decrease time to load Admin UI

---

catalog/ui/catalog-ui-search/pom.xml
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/QueryApplication.java
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/suggestion/LatLon.java
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/suggestion/LatLonCoordinateProcessor.java
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/suggestion/LiteralSuggestion.java
catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/query/suggestion/LatLonCoordinateProcessorTest.java
ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/openlayers/map.openlayers.js
ui/packages/catalog-ui-search/src/main/webapp/react-component/location/gazetteer.js
ui/packages/catalog-ui-search/src/main/webapp/react-component/location/keyword.js

Gives the suggestion service the ability to parse latitude/longitude coordinates from a search string
@Lambeaux @alanchampion @Bdthomson
@bdeining 
If testing before [DDF-4200](https://github.com/codice/ddf/pull/3847) is merged, use the anyGeo Keyword search. 
If testing after, use the gazetteer search box and disable online gazetteer.
Test a variety of latitude/longitude coordinates, including
- invalid numbers 
- latitude w/o longitude and vice versa 
- letters and other symbols intermixed
- negative/non-negative
- decimals
and verify that the correct coordinates are suggested
Depends on [DDF-4200](https://github.com/codice/ddf/pull/3847)
[DDF-4222](https://codice.atlassian.net/browse/DDF-4222)
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/719469 …

DDF-4222 Allow user to enter lat/lon coordinates into the gazetteer search box

---

platform/admin/core/admin-core-impl/src/main/java/org/codice/ddf/admin/core/impl/ConfigurationAdminImpl.java

Link to 2.13.x PR: #3907 
@Bdthomson @kcover @brjeter @stustison
@codice/ui
@clockard
@pklinef

DDF-4244 Decrease time to load Admin UI

---

catalog/core/catalog-core-metricsplugin/pom.xml
catalog/core/catalog-core-sourcemetricsplugin/pom.xml
distribution/sdk/sample-metrics/pom.xml
platform/metrics/platform-metrics-interceptor/pom.xml
platform/metrics/platform-metrics-reporting/pom.xml
platform/metrics/platform-metrics-reporting/src/main/java/ddf/metrics/reporting/internal/rest/MetricsEndpoint.java
platform/solr/solr-dependencies/pom.xml
pom.xml

Upgrades to latest RRD4J version.
@brjeter @pklinef @Kjames5269 
@codice/data 
@clockard
@shaundmorris
- Full CI build
- Metrics should be verified
[DDF-1397](https://codice.atlassian.net/browse/DDF-1397) …

DDF-1397 Upgrades RRD4J

---

ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/cesium/geocoder.js
ui/packages/catalog-ui-search/src/main/webapp/js/view/openlayers.geocoder.js

Port of https://github.com/codice/ddf/commit/4c2eedb2e7c163e4ce190e07ba18aa6c56a119b2
@Lambeaux @djblue 
@codice/ui 
@clockard
See #3805 
[DDF-4179](https://codice.atlassian.net/browse/DDF-4179) …

[2.13.x] DDF-4179 Fix geocoder camera reorientation

---

ui/packages/catalog-ui-search/src/main/webapp/component/paging/paging.hbs

Fixes font of the Back button when paging through results
@GabrielFabian 	@gjvera 	@djblue 	@willwill96 	
@codice/ui 
@bdeining
1. Ingest n documents
2. Set the `Number of Search Results` to a number less than n (settings -> Search Options)
3. Verify the Back button looks good
[DDF-4050](https://codice.atlassian.net/browse/DDF-4050) …

DDF-4050 Fix Back button font

---

catalog/core/catalog-core-metricsplugin/pom.xml
catalog/core/catalog-core-sourcemetricsplugin/pom.xml
distribution/sdk/sample-metrics/pom.xml
platform/metrics/platform-metrics-interceptor/pom.xml
platform/metrics/platform-metrics-reporting/pom.xml
platform/metrics/platform-metrics-reporting/src/main/java/ddf/metrics/reporting/internal/rest/MetricsEndpoint.java
platform/solr/solr-dependencies/pom.xml
pom.xml

Upgrades RRD4J and resolves an issue discovered where incorrect paths were set for the admin console.
*Work inadvertently performed on master branch prior to this backport rather than initially on this release branch. This change should be manually re-verified on this branch.*
@brjeter @pklinef @blen-desta 
@clockard
@shaundmorris
- Full CI build
- Metrics should be verified
[DDF-1397](https://codice.atlassian.net/browse/DDF-1397) …

[2.13.x] DDF-1397 Upgrades RRD4J and resolves path issue discovered during upgrade

---

distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/AbstractIntegrationTest.java
distribution/test/itests/test-itests-ddf/pom.xml

Attaches the acdebugger during itests
@paouelle @coyotesqrl 
@codice/test 
@lessarderic 
@tbatie
1. Make a change in distribution/ddf-common/src/main/resources/security/default.policy that removes a permission. Ex: removing all the permissions for cxf
2. Quickbuild DDF
3. Run the ITests and see the output from the acdebugger.
Security permission exceptions are hard to debug, especially if they are not consistent. Adding the acdebugger will printout a nice stacktrace and helpful suggestions on how to fix any security permission that appears.
[DDF-4213](https://codice.atlassian.net/browse/DDF-4213) …

DDF-4213 Added acedebugger to itests

---

ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/openlayers/map.openlayers.js

Adds feature styles for Multiline and MultiPolygon types
@andrewkfiedler @bdeining @adimka @Schachte @djblue 
@codice/ui 
Build UI and ensure Intrigue loads
[DDF-4240](https://codice.atlassian.net/browse/DDF-4240) …

DDF-4240 Add Color styles to Multiline and MultiPolygon types

---

catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/data/impl/BasicTypes.java
catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/DynamicSchemaResolver.java
catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/json/MetacardTypeMapperFactory.java
catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/DynamicSchemaResolverTest.java
catalog/core/catalog-core-validationparser/src/main/java/ddf/catalog/validation/impl/ValidationParser.java

Replaces Java serialization with JSON serialization for storing `MetacardType` to Solr.  Java serialization is slow, insecure if mishandled, and brittle.
@paouelle 
@mcalcote 
@codice/solr 
@clockard
@rzwiefel
Install standard profile, ingest any data set into the system, and query.  Create, save, and reload workspaces in Intrigue.
[DDF-3938](https://codice.atlassian.net/browse/ddf-3938) …

DDF-3938 Use JSON for MetacardType stored in Solr

---

pom.xml

Updates the third-party tika-bundle to the newest version that removes vulnerabilities found in `org.apache.pdfbox` v `2.0.9` and `bcprov-jdk15on-1.54.jar`
@blen-desta @brjeter @stustison
@coyotesqrl 
@clockard 
CI
[Companion PR](https://github.com/codice/thirdparty/pull/26)
[DDF-4197](https://codice.atlassian.net/browse/DDF-4197) …

[2.13.x] DDF-4197 Updating the version of the third-party tika-bundle to 1.18.0_3

---

ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-old.js

This fixes manual input of UTM / UPS coordinates for bounding boxes + point radius in the anyGeo component
@BernardIgiri 
@Lambeaux 
@Variadicism 
@dimitry-sherman
@codice/ui 
@millerw8 
1. Verify that manual entry of UTM / UPS coordinates works for both the bounding box and point radius tab of the anyGeo field. You can do this by drawing a shape, then manually entering the resulting fields populated in the anyGeo field again to see if the same shape is drawn. Note: it is expected behavior for some of the fields to be cleared when the user enters invalid input. However, the anyGeo component should remain and should not disappear in any case.
2. Verify that records show correctly in search queries made from manually entered shapes. …

DDF-4258 AnyGeo Component is Removed when User Inputs UPS Coordinates Manually

---

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/security/AccessControlPolicyExtension.java

Updates logic that checks workspace owner to ignore case on checks.
@djblue 
@codice/ui 
@bdeining 
1. Install and Login to UI as admin
2. Create a workspace 
3. Shutdown system
4. Update <ddf.home>/etc/users.attributes and change the user part of the emailaddress to something like Admin instead of admin
5. Restart system, Login to UI, verify you see previously created workspace.
[DDF-4221](https://codice.atlassian.net/browse/DDF-4221) …

DDF-4221 Workspace owner checks case insensitive

---

platform/platform-paxweb-jettyconfig/src/main/java/org/codice/ddf/pax/web/jetty/FilterInjector.java
platform/platform-paxweb-jettyconfig/src/main/resources/OSGI-INF/blueprint/blueprint.xml
platform/platform-paxweb-jettyconfig/src/test/java/org/codice/ddf/pax/web/jetty/FilterInjectorTest.java

@KalCramer @jhunzik 
@clockard
@stustison

DDF-4241 made servlet filters pluggable

---

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/util/EndpointUtil.java
catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.whitelist.xml
catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/util/EndpointUtilTest.java

The UI now will allow an optional whitelist of metatypes understood. If the list is empty, it could support all metacard types, but when populated, only returns the ones allowed.
The advantages of this is that we will not need to track upstream changes for downstream projects for new attributes and continue to blacklist them on an attribute by attribute basis.
It should also help the performance of the UI by not processing all 680kb of json data for all the metacard types and using that information when populating search lists, etc.
@middlets719 
@bdeining 
@millerw8 
@zta6 
@bdeining
@millerw8 
Build, go to advanced query search and ensure all attributes are populated in the dropdown.
Drop a config file in etc with a non-existent metacard type and watch that same list …

DDF-4262 Enabling Configurable Metacard Type Filtering in Catalog UI

---

catalog/core/catalog-core-solr/pom.xml
catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/DynamicSchemaResolver.java
catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/DynamicSchemaResolverTest.java

Link to 2.13.x PR: https://github.com/codice/ddf/pull/3919
Adds standard metadata size limit and ability to configure limit if needed to adding metadata to solr input documents
@ahoffer 
@mcalcote 
@clockard
@lessarderic
@pklinef
Forward Port
[DDF-4248](https://codice.atlassian.net/browse/DDF-4248) …

DDF-4248 Metacard caching does not guard against large binary fields 

---

ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-old.js

Lets user draw bounding boxes in UPS space on the 3d map
@BernardIgiri 
@Lambeaux 
@Variadicism 
@dimitry-sherman
@codice/ui 
@millerw8
1. Verify that bounding boxes can be drawn in the 3d map in UPS space (latitudes above 84 degrees N and under 80 degrees S) 
2. Check that previous functionality has not been broken. In both the 2d and 3d maps:
-Using the text fields in the anyGeo search component, manually input bboxes in ups, utm, both utm/ups space
-draw bboxes in ups, utm, both utm/ups space 
[demo](https://gfycat.com/ConsiderateOblongDipper) …

DDF-4271 Drawing bounding boxes on the 3D map does not work in UPS space

---

distribution/ddf-common/src/main/resources/etc/org.apache.karaf.features.xml
features/security/pom.xml
features/security/src/main/feature/feature.xml

**Note:** Exception being made for this going into the release during the code freeze.
JSP package imports/exports were mismatched due to the new custom pax-web version "7.2.4.CODICE", making JSP support not properly enabled.
@KalCramer @ryeats @Kjames5269 @bakejeyner 
@clockard
@coyotesqrl 
Install and verify Simple Search comes up normally.
[DDF-4123](https://codice.atlassian.net/browse/DDF-4123) …

[2.13.x]DDF-4123 Fix simple search with new, custom pax-web bundles

---

distribution/ddf-common/src/main/resources/security/default.policy

`/login` page does not work due to an AccessControlException
@clockard
@coyotesqrl
- Install DDF (just minimum profile is fine)
- Go to `/login`
- Login to the IDP login page
- Enter admin/admin for the `/login` page
- It should redirect to the landing page
[DDF-4279](https://codice.atlassian.net/browse/DDF-4279) …

[2.13.x]DDF-4279 Add permissions to fix the /login page

---

catalog/validator/catalog-validator-metacardduplication/pom.xml
catalog/validator/catalog-validator-metacardduplication/src/main/java/org/codice/ddf/validator/metacard/duplication/DuplicationValidator.java
distribution/ddf-common/src/main/resources-filtered/etc/application-definitions/catalog.json

Link to 2.13.x PR: #3954
@kcover @pklinef @bakejeyner @emmberk 
@codice/data 
@clockard
@figliold 

DDF-4217 Fix DuplicationValidator catalog query not returning results

---

ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-old.js

Preserves the tab state that the user was on before drawing in both the 2d and 3d maps
@BernardIgiri 
@dimitry-sherman
@Variadicism 
@Lambeaux 
@codice/ui 
@millerw8 
Verify that tab state is preserved on the anyGeo component when drawing in the 2d and 3d maps
Test on all tabs (lat/lon, usng, utm/ups, etc.) for point radius and bounding box. Note: The tab state will not be preserved after a search is performed. This is pre-existing behavior
[DDF-4282](https://codice.atlassian.net/browse/DDF-4282)
[2D demo](https://drive.google.com/open?id=1N14eUj9wcXIof8BcyY-kSjVeKPra38qY)
[3D demo](https://drive.google.com/open?id=1VID8jHhvsK4Fiw5RwATRvUrYJUL3ZQOf) …

DDF-4282 Preserve anyGeo Tab State when Drawing Shapes

---

ui/packages/catalog-ui-search/src/main/webapp/component/query-add/query-add.view.js
ui/packages/catalog-ui-search/src/main/webapp/js/model/Query.js

Removes the default title from the query model, in favor of placeholder behavior in new query views.
@Schachte @cantstoptheunk 
@djblue
Create a new query, the placeholder value of "Search Name" should appear. Save the query, edit the query, ensure the saved name displays in the editor.
[DDF-4276](https://codice.atlassian.net/browse/4276) …

DDF-4276 Remove default query title in favor of placeholder

---

platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/server/IdpEndpoint.java
platform/security/sts/security-sts-server/src/main/resources/OSGI-INF/blueprint/cxf-sts.xml
platform/security/sts/security-sts-server/src/main/resources/OSGI-INF/metatype/metatype.xml

Link to 2.13.x PR: https://github.com/codice/ddf/pull/3801
____
@coyotesqrl
@stustison 

DDF-4171 - Resolved SAML compliance issues when DDF is configured behind a proxy

---

pom.xml

- Teams tagged
Link to 2.13.x PR: #3923
____
@blen-desta @brjeter @stustison
@coyotesqrl
@clockard …

DDF-4197 Tika-third-party bundle upgrade.

---

catalog/rest/catalog-rest-impl/src/main/java/org/codice/ddf/rest/impl/CatalogServiceImpl.java
catalog/rest/catalog-rest-impl/src/test/java/org/codice/ddf/rest/impl/CatalogServiceImplTest.java
catalog/rest/catalog-rest-service/pom.xml
catalog/rest/catalog-rest-service/src/main/java/org/codice/ddf/rest/service/CatalogService.java
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/ListApplication.java
catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/blueprint/blueprint.xml

Link to 2.13.x PR: #3953 
____
@SmithJosh @alexaabrd 
@vinamartin 
@beyelerb 

Ddf 4267 fix list upload attribute overrides (#3953)

---

ui/packages/catalog-ui-search/src/main/webapp/component/filter/filter.view.js
ui/packages/catalog-ui-search/src/main/webapp/component/multivalue/multivalue.view.js
ui/packages/catalog-ui-search/src/main/webapp/component/relative-time/relative-time.view.js

Fixes bug that was preventing searches using relative time filters from being saved and ran.
@djblue 	@GabrielFabian 	@rymach 	@GabrielFabian 	
@bdeining
[DDF-4289](https://codice.atlassian.net/browse/DDF-4289) …

DDF-4289 Fix relative time searches

---

distribution/docs/src/main/resources/content/_dependencyList/ddf-dependency-list.adoc
features/security/src/main/feature/feature.xml
platform/security/sts/security-sts-ldapclaimshandler/pom.xml

Upgrades spring-ldap-core to address vulnerabilities.
@peterhuffer @emmberk @oconnormi 
@clockard
@rzwiefel
@tbatie
[DDF-4209](https://codice.atlassian.net/browse/DDF-4209)
Install DDF and test logging in through LDAP …

[2.13.x] DDF-4209 Upgrade spring-ldap-core to address vulnerabilities

---

catalog/core/catalog-core-solr/pom.xml
catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/SolrMetacardClientImpl.java
catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/SolrProviderRealTimeQueryTest.java
distribution/ddf-common/src/main/resources-filtered/etc/custom.system.properties

Adds a system property for metacard types to commit within a second of ingest.  This simulates the previous behavior for Intrigue metacard types but not other types in the system for performance.
@bellcc 
@paouelle 
@codice/solr 
@lessarderic
@rzwiefel
Create a workspace and go back to the workspace view and refresh.  Workspace should be available.
[DDF-3938](https://codice.atlassian.net/browse/DDF-3938) …

DDF-3938 Simulate previous NRT commit with Intrigue specific metacards

---

ui/packages/catalog-ui-search/src/main/webapp/component/editor/editor.view.js

Fixes regression in editor.view.js
@Bdthomson
@rzwiefel
- Successful CI build
- Yarn start catalog-ui-search
- Ensure users can add / edit attributes
[DDF-4251](https://codice.atlassian.net/browse/DDF-4251)

DDF-4251 Fixes regression in editor.view.js

---

distribution/docs/src/main/resources/content/_plugins/metacard-groomer.adoc
distribution/docs/src/main/resources/templates/build/plugins.ftl

- updates documentation for installation of metacard groomer.
- updates documentation template to alphabetize catalog plugins.  
@codice/docs 
@clockard
@lessarderic
@shaundmorris
- review content.
- builds successfully
[DDF-4280](https://codice.atlassian.net/browse/DDF-4280) …

DDF-4280 updated docs for metacard groomer

---

ui/packages/ui/src/main/webapp/js/views/installer/Configuration.view.js

Before the installer would save the system properties entered into it, then
check if the entered certs were valid. This could result in ddf running
on a different hostname than what was in the certs and make the
installer inaccessable. This commit will have the installer validate and save the certs
first, then save the system properties.
@emmberk @peterhuffer @pvargas @mdang8 
@codice/ui 
@clockard
Start by performing the steps listed in the ticket to make sure that the original bug can't be reproduced. Then, confirm the page works as it did before by going through the following scenarios:
- clicking next without any changes should allow you to proceed.
- changing the hostname with dev=true should allow you to proceed.
- changing the hostname without entering certs should …

[2.13.x] DDF-4285 Validate certs before saving system properties

---

distribution/docs/src/main/resources/content/_reference/_dependencyList/ddf-dependency-list.adoc
features/security/src/main/feature/feature.xml
platform/security/sts/security-sts-ldapclaimshandler/pom.xml

Link to 2.13.x PR: #3871 
@peterhuffer @emmberk @oconnormi
@clockard
@rzwiefel
@tbatie

DDF-4209 Update spring-ldap-core to version 2.3.2

---

ui/packages/ui/src/main/webapp/js/views/installer/Configuration.view.js

Link to 2.13.x PR: #3971 
@emmberk @peterhuffer @pvargas @mdang8
@codice/ui 
@clockard

DDF-4285 Validate certs before saving system properties

---

distribution/kernel/pom.xml
features/kernel/pom.xml

Fixes the feature itests
@paouelle @peterhuffer 
@codice/build 
@codice/test 
@lessarderic
@tbatie

DDF-4265 Fix feature itests

---

distribution/ddf-common/src/main/resources/etc/org.apache.karaf.features.xml
distribution/ddf-common/src/main/resources/security/default.policy
features/security/pom.xml
features/security/src/main/feature/feature.xml
platform/error/platform-error-impl/src/main/resources/codeMessages.properties
platform/error/platform-error-servlet/src/main/java/org/codice/ddf/platform/error/servlet/ErrorServlet.java

Link to 2.13.x PR: #3948, #3962, #3968
@clockard  
@coyotesqrl 

DDF-4123/4279/4284 Minor forward ports

---

distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/AbstractIntegrationTest.java
distribution/test/itests/test-itests-ddf/pom.xml

Updates itests to use kernel
@Lambeaux 
@lessarderic 
@LinkMJB 
@tbatie 
@codice/build 
- Successful CI Build
[DDF-4298](https://codice.atlassian.net/browse/DDF-4298) …

DDF-4298 Improve UI CI Incremental Build

---

catalog/spatial/kml/spatial-kml-transformer/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/transformer/catalog-transformer-csv-queryresponse/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/transformer/catalog-transformer-geojson-queryresponse/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/transformer/catalog-transformer-html/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/transformer/catalog-transformer-rtf/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/transformer/catalog-transformer-service-atom/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/transformer/catalog-transformer-xml/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/handlers/CqlTransformHandler.java
catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/blueprint/blueprint.xml
distribution/docs/src/main/resources/content/_developing/_devComponents/transformers-query-response.adoc

Adds support for whitelisting which QueryResponseTransformers would populate the table-view's export dropdown menu. This prevents us from using / testing data transformers that aren't supported for resultset exports.
@bellcc 
@brianfelix 
@leo-sakh 
@jrnorth 
@bdeining
@millerw8
Verify that the export dropdown menu only includes the transformers marked in this PR with the `<entry key="export-resultset" value="true"/>` indicator. …

DDF-4309 whitelist the queryResponseTransformers that populate the export dropdown

---

ui/packages/catalog-ui-search/src/main/webapp/component/input/password/input-password.tsx
ui/packages/catalog-ui-search/src/main/webapp/component/input/password/input-password.view.js
ui/packages/catalog-ui-search/src/main/webapp/component/property/property.js
ui/packages/catalog-ui-search/src/main/webapp/component/slideout/slideout.view.js
ui/packages/catalog-ui-search/src/main/webapp/component/value/value.view.js
ui/packages/catalog-ui-search/src/main/webapp/dev/component/guide/guide.view.js
ui/packages/catalog-ui-search/src/main/webapp/dev/component/password/index.tsx
ui/packages/catalog-ui-search/src/main/webapp/dev/component/password/password.tsx
ui/packages/catalog-ui-search/src/main/webapp/react-component/container/input-wrappers/base/base.tsx
ui/packages/catalog-ui-search/src/main/webapp/react-component/container/input-wrappers/password/index.tsx
ui/packages/catalog-ui-search/src/main/webapp/react-component/container/input-wrappers/password/password.tsx
ui/packages/catalog-ui-search/src/main/webapp/react-component/container/user/user.tsx
ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/navigation-left/navigation-left.tsx
ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/navigation-right/navigation-right.tsx
ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/user/user.tsx

- Adds a password component.
- Fixes slideout bug where going between notifications and the user panel caused the user panel to no longer show up.
@djblue
@millerw8
@glenhein 
Test logging in and out.
[DDF-4263](https://codice.atlassian.net/browse/DDF-4263)

DDF-4263 Adds password component, fixes slideout bug

---

features/pom.xml
pom.xml

Replace properties that had been moved to the parent pom.
@tbatie @ryeats @derekwilhelm @coyotesqrl @oconnormi @lessarderic @paouelle @Kjames5269 
Build DDF and ensure no dependency version are undefined. It my be easiest to confirm if ddf-parent is build locally with all the properties removed and then update the root pom to look at that snapshot.  …

DDF-3705 Replace pom properties previously removed

---

distribution/ddf-common/src/main/resources/security/default.policy

Allows geonames to be ingested by updated security policy 
@bdeining 
@middlets719 
@millerw8 
@troymohl 
@paouelle 
@bdeining
@millerw8 
@paouelle 
Ingest geonames data from ddf data dir:
`gazetteer:update "$ddf.data/countries.geo.json"`
[DDF-4314](https://codice.atlassian.net/browse/DDF-4314) …

DDF-4314 Adding new security policy to allow geonames ingest

---

ui/packages/catalog-admin-module-layout/src/main/webapp/default-layout/index.js
ui/packages/catalog-admin-module-layout/src/main/webapp/default-layout/reducer.js

The default layout config is editable by dragging and dropping the UI "visualizations" around (see first screen shot below). There is also a panel for the underlying json configuration for the current layout at the bottom (second screenshot). This makes the JSON panel editable.
@codice/ui 
@djblue 
- Install DDF
- Go to the AdminUI -> Search UI
- Do a combination of the below in different orders:
- Modify the JSON configuration in the bottom panel (must be valid JSON) and verify it's reflected in the top panel
- Hit the Save button, refresh the page, and make sure it saved
- Hit the Reset button and verify both panels go back to the state of the last save.
- Create, drag, and drop visualizations around in the top panel.
- Put in invalid JSON in …

[2.13.x]DDF-4310 Make the Default Layout config editable

---

distribution/kernel/pom.xml

Link to master PR: #3961
@paouelle @peterhuffer 
@lessarderic @tbatie 

DDF-4265 Fix feature itests 

---

features/security/pom.xml

Fixes pom dependency which is breaking the CI job that builds it without a settings file and with a clean m2.
(https://jenkins.codice.org/job/DDF-Jobs/job/2.13.x/job/Linux/177/)
@blen-desta @Kjames5269 
@clockard
@coyotesqrl 
- Remove `org.codice.thirdparty:cas-client-core:3.5.0_1` from the local m2.
- Temporarily rename your local `settings.xml` file
- Run `mvn clean install` under `features/security`
[DDF-4286](https://codice.atlassian.net/browse/DDF-4286) …

DDF-4286 Fixing cas-client pom dependency to fix CI

---

ui/packages/catalog-admin-module-layout/src/main/webapp/default-layout/index.js
ui/packages/catalog-admin-module-layout/src/main/webapp/default-layout/reducer.js

Link to 2.13.x PR: #4002
@djblue 
@rzwiefel 

DDF-4310 Make the Default Layout config editable

---

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/workspace/transformer/impl/WorkspaceTransformerImpl.java
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/util/EndpointUtil.java
catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/util/EndpointUtilTest.java

Makes reading dates more forgive in endpointUtils parseToDate.  Also makes it consistently return Instant.
Also catches exceptions when writing attributes in WorkspaceTransformerImpl so that it will not automatically fail to save a workspace when it has a bad attribute.
@Variadicism 
@troymohl 
@bdeining
Create workspaces, Confirm with various queries they can be saved, modified, saved, refreshed and return again.  Also consider downstream products that may inject additional attributes into workspaces.
[DDF-4127](https://codice.atlassian.net/browse/DDF-4127) …

DDF-4127 Made workspace and endpointUtil a little more forgiven when parsing attributes

---

platform/security/sts/security-sts-attributequerycommon/src/main/java/org/codice/ddf/security/claims/attributequery/common/AttributeQueryClaimsHandler.java

DDF-4328 adding a doPrivileged block around Service.create
@blen-desta @bakejeyner 
@brjeter 
@coyotesqrl
@stustison
CI
[DDF-4328](https://codice.atlassian.net/browse/DDF-4328) …

DDF-4328 adding a doPrivileged block around Service.create

---

catalog/catalog-app/src/main/resources/features.xml
catalog/spatial/spatial-app/src/main/resources/features.xml
distribution/ddf-common/src/main/resources/etc/profiles/ha.json

- Fix the features themselves to declare their dependencies
- Include the additional dependencies in the ha profile for maintenance purposes
- Removes some features/bundles that no longer exist
@Kjames5269  @paouelle 
@coyotesqrl 
@figliold 
- Install with the HA profile: `profile:install ha`
- Install with the standard profile via both the UI or CLI
[DDF-4322](https://codice.atlassian.net/browse/DDF-4322)
- ❓ …

[2.13.x]DDF-4322 Fix the HA installation profile

---

platform/security/sts/security-sts-attributequerycommon/src/main/java/org/codice/ddf/security/claims/attributequery/common/AttributeQueryClaimsHandler.java

Backport of #4025 
- Teams tagged
Link to MASTER PR: #4025 
____
@blen-desta @bakejeyner
@brjeter
@coyotesqrl
@stustison
CI
- ✏️ …

[2.13.x] DDF-4328 adding a doPrivileged block around Service.create

---

ui/README.md
ui/package.json

Updates UI README.md
@pklinef 
@codice/ui 
- CI build
[DDF-3584](https://codice.atlassian.net/browse/DDF-3584)

DDF-3584 Updates UI README.md

---

broker/pom.xml
catalog/core/catalog-core-contentresourcereader/pom.xml
catalog/core/catalog-core-federationstrategy/pom.xml
catalog/core/catalog-core-localstorageprovider/pom.xml
catalog/core/catalog-core-solr/pom.xml
catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/SolrProviderTest.java
catalog/core/catalog-core-solr/src/test/resources/simplelogger.properties
catalog/core/catalog-core-standardframework/pom.xml
catalog/core/catalog-core-urlresourcereader/pom.xml
catalog/opensearch/catalog-opensearch-source/pom.xml
catalog/plugin/catalog-plugin-security-audit/pom.xml
catalog/pom.xml
catalog/spatial/csw/spatial-csw-action/pom.xml
catalog/spatial/ogc/spatial-ogc-urlresourcereader/pom.xml
catalog/spatial/wfs/spatial-wfs-featuretransformer/src/test/logback-test.xml
distribution/docs/pom.xml
distribution/test/itests/test-itests-common/pom.xml
distribution/test/itests/test-itests-ddf/pom.xml
platform/admin/core/admin-core-configpolicy/pom.xml
platform/admin/pom.xml
platform/pom.xml
platform/security/common/pom.xml
platform/security/core/security-core-services/pom.xml
platform/security/pep/security-pep-interceptor/pom.xml
platform/security/platform-security-core-api/src/test/java/ddf/security/samlp/MetadataConfigurationParserTest.java
pom.xml

Refactors the maven-surefire-plugin to use the `argLine` property instead of the `argLine` configuration.
@blen-desta 
@brjeter 
@Kjames5269 
@clockard
@coyotesqrl
**This should be hero'd on both Windows and Mac**
1. Perform a quickbuild.
2. Run `mvn clean install -pl !distribution/test/itests` from the DDF source root.
3. All tests should pass.
[DDF-4260](https://codice.atlassian.net/browse/DDF-4260)
- ❓ (Question …

DDF-4260 Refactor surefire argLine property

---

catalog/spatial/kml/spatial-kml-transformer/pom.xml
catalog/spatial/kml/spatial-kml-transformer/src/main/java/org/codice/ddf/spatial/kml/transformer/DescriptionTemplateHelper.java
platform/metrics/platform-metrics-reporting/src/main/java/ddf/metrics/reporting/internal/rest/MetricsEndpoint.java

This PR fixes some SimpleDateFormatter race conditions.
@paouelle @Bdthomson 
@coyotesqrl
@pklinef
Since the change is 1:1 with SimpleDateFormat, this should be covered by unit tests.
[DDF-4293](https://codice.atlassian.net/browse/DDF-4293)
- ❗ …

DDF-4293 Fixed race conditions with SimpleDateFormatter

---

Documentation-versions.html
index.html

updates DDF website documentation for 2.13.3 release
@codice/docs 
@clockard
@lessarderic
@shaundmorris …

DDF-2824 updated DDF website for 2.13.3 release

---

distribution/docs/src/main/resources/content/_architectures/_plugins/metacard-groomer.adoc
distribution/docs/src/main/resources/templates/build/plugins.ftl

Link to 2.13.x PR: #[3973](https://github.com/codice/ddf/pull/3973)
- updates documentation for installation of metacard groomer.
- updates documentation template to alphabetize catalog plugins.  
@codice/docs 
@clockard
@lessarderic
@shaundmorris
- review content.
- builds successfully
[DDF-4280](https://codice.atlassian.net/browse/DDF-4280) …

DDF-4280 updated docs for metacard groomer (#3973)

---

catalog/confluence/catalog-confluence-source/src/main/resources/OSGI-INF/metatype/metatype.xml
catalog/opensearch/catalog-opensearch-source/src/main/resources/OSGI-INF/metatype/metatype.xml
catalog/spatial/csw/spatial-csw-source/src/main/resources/OSGI-INF/metatype/metatype.xml
catalog/spatial/wfs/1.0.0/spatial-wfs-v1_0_0-source/src/main/resources/OSGI-INF/metatype/metatype.xml
catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/resources/OSGI-INF/metatype/metatype.xml
catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/main/resources/OSGI-INF/metatype/metatype.xml
platform/admin/core/admin-core-api/src/main/java/org/codice/ddf/admin/core/api/Service.java
platform/admin/core/admin-core-impl/src/main/java/org/codice/ddf/admin/core/impl/ConfigurationAdminImpl.java
ui/packages/catalog-admin-module-sources/src/main/webapp/js/view/ModalSource.view.js
ui/packages/catalog-admin-module-sources/src/main/webapp/templates/sourceModal.handlebars

@ethantmanns 
@figliold 
@paouelle 
@brjeter 
@codice/ui 
@tbatie 
Test in multiple browsers
- Go to Admin UI -> Catalog -> Sources tab 
- Add a source
- Verify that a description appears below the Source Type field
- Change the Source Type and verify the description changes
[DDF-4319](https://codice.atlassian.net/browse/DDF-4319) …

[2.13.x] DDF-4319 Add catalog source descriptions to the Admin UI when configuring/editing sources

---

catalog/catalog-app/src/main/resources/features.xml
catalog/spatial/spatial-app/src/main/resources/features.xml
distribution/ddf-common/src/main/resources/etc/profiles/ha.json

Link to 2.13.x PR: #4015 
@Kjames5269 @paouelle 
@coyotesqrl
@figliold 
[DDF-4322](https://codice.atlassian.net/browse/DDF-4322)

DDF-4322 Fix the HA installation profile

---

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/MetacardApplication.java
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/workspace/QueryMetacardTypeImpl.java
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/workspace/transformer/impl/AssociatedQueryMetacardsHandler.java
catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/metacard/workspace/transformer/impl/AssociatedQueryMetacardsHandlerTest.java

@bdeining
@clockard
@coyotesqrl
@djblue
@figliold
@jlcsmith
@lessarderic
@millerw8
@pklinef
@rzwiefel
@shaundmorris
@stustison
@tbatie
@vinamartin
- ❗ …

Backend changes to partial collab

---

ui/packages/catalog-ui-search/src/main/webapp/component/search-settings/search-settings.view.js

Updates search-settings view to pass in an option to the query-settings view letting it know the context of where it is created from
@Bdthomson @hayleynorton @alanchampion 
@codice/ui 
@bdeining 
[DDF-4340](https://codice.atlassian.net/browse/DDF-4340) …

DDF-4340 Add additional context to query-settings component

---

ui/packages/catalog-ui-search/src/main/webapp/react-component/location/keyword.js
ui/packages/catalog-ui-search/src/main/webapp/react-component/location/multipoly.js

Adds support to render buffer/units of measurement into keyword piece of the location component
@djblue 
@bdeining 
@middlets719 
@adimka 
@codice/ui 
@bdeining
- …

DDF-4315 Incorporating Buffer/Units Into Keyword Location

---

catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/ExportCommand.java
catalog/core/catalog-core-directorymonitor/pom.xml
catalog/core/catalog-core-directorymonitor/src/test/java/org/codice/ddf/catalog/content/monitor/ContentDirectoryMonitorIT.java
catalog/pom.xml
catalog/spatial/csw/spatial-csw-transformer/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/GetRecordsResponseConverterTest.java
catalog/spatial/registry/registry-federation-admin-service-impl/src/test/java/org/codice/ddf/registry/federationadmin/service/impl/IdentityNodeInitializationTest.java
catalog/transformer/catalog-transformer-common/pom.xml
distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFederation.java
features/camel/src/main/feature/feature.xml
features/pom.xml
features/security/src/main/feature/feature.xml
features/test-utilities/src/main/feature/feature.xml
platform/admin/core/admin-core-appservice/src/test/java/org/codice/ddf/admin/application/service/migratable/JsonFeatureTest.java
pom.xml

Link to master PR: #3807 
Updates various dependencies. There are some minor incompatibilities between CXF 3.2.5 and Karaf 4.2.1 in downstream projects that this fixes.
@emmberk @blen-desta 
@clockard
@coyotesqrl 
[DDF-4178](https://codice.atlassian.net/browse/DDF-4178) …

[2.13.x]DDF-4178 updated cxf, camel, http, and shiro

---

distribution/ddf-common/src/main/resources/etc/hazelcast.xml

Link to 2.13.x PR: #4044
@rzwiefel 
@tbatie 
@clockard
@shaundmorris 
@stustison

DDF-4337: Disable Hazelcast Port 5701 by Default

---

ui/packages/catalog-ui-search/src/main/webapp/component/announcement/actions.js
ui/packages/catalog-ui-search/src/main/webapp/component/announcement/announcement.less
ui/packages/catalog-ui-search/src/main/webapp/component/announcement/announcements.jsx
ui/packages/catalog-ui-search/src/main/webapp/component/result-form/result-form.collection.less
ui/packages/catalog-ui-search/src/main/webapp/component/result-form/result-form.view.js
ui/packages/catalog-ui-search/src/main/webapp/component/search-form-editor/search-form-editor.view.js

- Adds a confirmation message for successful save and an error message for unsuccessful save of a Result Form to match the behavior of Search Forms
- Wraps the `message` of the `announcement.announce` method with a `<pre>` tag (this makes the announcements more formatting-friendly i.e. printing a new line for `\n`)
- Adds the ability to scroll on the Results Forms page if necessary
@djblue @andrewzimmer @Bdthomson 
@codice/ui 
@bdeining 
- Go to the Result Forms page and click the new form button
- Attempt to save an empty form 
- Verify that a red warning symbol appears next to `Title` and `Attributes` and that you are unable to save the form
- Fill in the required fields and save
- Verify that a success announcement pops up (and that the styling of the message matches …

DDF-4294 Added confirmation/error message when saving a new Result Form

---

catalog/ui/catalog-ui-search/pom.xml
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/cql/CqlRequest.java
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/util/EndpointUtil.java
catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/query/cql/CqlRequestTest.java
ui/packages/catalog-ui-search/src/main/webapp/react-component/container/table-export/table-export.tsx

1. Adds ability for Cql Requests to query against multiple sources
2. Enables Table Export to Query against federated sources
@rymach 
@gjvera 
@codice/ui 
@bdeining
@djblue
1. Set up both local catalog and at least one federated source (each with multiple resources)
2. Run searches against multiple combinations of sources
- Ensure that results are the ones expected
- Export results using table export and ensure that all metacards in the table are exported
3. Spot test search functionality for regressions
[DDF-4334](https://codice.atlassian.net/browse/DDF-4334) …

DDF-4334 Add Support for Federated Sources in Table Export

---

distribution/docs/src/main/resources/content/_configuring/hiding-errors-by-role.adoc
distribution/docs/src/main/resources/content/_introduction/documentation-notes.adoc

Updates documentation to clarify instructions for filtering errors and warnings. 
@ethantmanns @austinsteffes @ahoffer @mcalcote @garrettfreibott @vinamartin @alexaabrd 
@codice/docs 
@clockard
@lessarderic
@shaundmorris
@vinamartin
review content
[DDF-4345](https://codice.atlassian.net/browse/DDF-4345) …

DDF-4345 updated documentation for filtering errors and warnings

---

distribution/ddf-common/src/main/resources/security/default.policy
platform/sync-installer/sync-installer-impl/pom.xml
pom.xml

Upgrade Jacoco, codice-maven, codice-test, ac debugger versions in support of Java 11	
@ethantmanns 
@jhunzik 
@AzGoalie 
@coyotesqrl
@figliold
@tbatie
- The PR build should be sufficient
[DDF-4223](https://codice.atlassian.net/browse/DDF-4223) …

[Java11] DDF-4223 Upgrade Jacoco, codice-maven, codice-test, ac debugger versions in support of Java 11	

---

catalog/spatial/wfs/1.0.0/spatial-wfs-v1_0_0-schema-webapp/src/main/resources/WEB-INF/web.xml
catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/ui/search-ui/search-redirect/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/ui/search-ui/simple/src/main/webapp/WEB-INF/web.xml
platform/admin/core/admin-core-jolokia/src/main/resources/OSGI-INF/blueprint/blueprint.xml
platform/admin/modules/admin-modules-docs/src/main/resources/OSGI-INF/blueprint/blueprint.xml
platform/security/idp/security-idp-server/src/main/webapp/WEB-INF/web.xml
platform/security/servlet/security-servlet-logout/src/main/resources/OSGI-INF/blueprint/blueprint.xml
platform/security/servlet/security-servlet-whoami/src/main/resources/OSGI-INF/blueprint/blueprint.xml
platform/solr/platform-solr-server-standalone/src/main/webapp/WEB-INF/web.xml
ui/packages/ace/lib/package.js
ui/packages/security-idp-server/src/main/webapp/WEB-INF/web.xml
ui/src/main/resources/WEB-INF/web.xml

Adds async-support=true to GzipFilter so that the UI works.
@KalCramer 
@clockard 
@codice/ui 
@coyotesqrl
@djblue
unzip and run if the admin UI loads then it worked
https://stackoverflow.com/questions/20643970/asyncsupported-exception-when-switch-from-jetty-7-to-jetty-9/20644532#20644532
[DDF-4352](https://codice.atlassian.net/browse/DDF-4352) …

[2.13.x] DDF-4352 fix GzipFilter add async-supported=true

---

catalog/confluence/catalog-confluence-source/src/main/java/org/codice/ddf/confluence/source/ConfluenceInputTransformer.java
catalog/confluence/catalog-confluence-source/src/test/java/org/codice/ddf/confluence/source/ConfluenceInputTransformerTest.java
catalog/confluence/catalog-confluence-source/src/test/resources/anonymous_user_response.json

Link to 2.13.x PR: #4063 
@emmberk @kcover @pvargas @mdang8
@codice/io 
@coyotesqrl
@vinamartin
[DDF-4347](https://codice.atlassian.net/browse/DDF-4347)

DDF-4347 Allow Confluence to query anonymous content

---

catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/ui/search-ui/search-redirect/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/ui/search-ui/simple/src/main/webapp/WEB-INF/web.xml
platform/admin/core/admin-core-jolokia/src/main/resources/OSGI-INF/blueprint/blueprint.xml
platform/admin/modules/admin-modules-docs/src/main/resources/OSGI-INF/blueprint/blueprint.xml
platform/security/idp/security-idp-server/src/main/webapp/WEB-INF/web.xml
platform/security/servlet/security-servlet-logout/src/main/resources/OSGI-INF/blueprint/blueprint.xml
platform/security/servlet/security-servlet-whoami/src/main/resources/OSGI-INF/blueprint/blueprint.xml
ui/packages/ace/lib/package.js
ui/packages/security-idp-server/src/main/webapp/WEB-INF/web.xml
ui/src/main/resources/WEB-INF/web.xml

- Teams tagged
Link to 2.13.x PR: #4066 
____
@KalCramer 
@codice/ui 
-->
@clockard 
@coyotesqrl …

DDF-4352 fix GzipFilter issue add async-support=true param

---

ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/workspaces-items/workspaces-items.tsx

Previous PR of DDF-4346 had the term `New Workspace` misplaced. This PR fixes it so that `New Workspaces` is now below the button.
@Schachte 
@bdeining 
@zta6 
@bdeining 
- ❗ …

DDF-4346 Fixing misplacement of text in workspaces

---

distribution/test/itests/test-itests-ddf/pom.xml
pom.xml

Replaces starting the AC Debugger with the exec maven plugin with the new AC Debugger maven plugin.
Should be merged after https://github.com/codice/ddf/pull/4060
@Kjames5269  @paouelle 
@codice/test 
@lessarderic 
@tbatie 
1. Verify that the AC Debugger starts when running an ITest
2. Verify that the AC Debugger doesn't start when passed -DskipTests
3. Verify that the AC Debugger doesn't start when passed -DisDebugEnabled …

DDF-4213 Added AC Debugger maven plugin

---

distribution/ddf-common/src/main/resources/security/default.policy
pom.xml

It updates the AC debugger's backdoor to the latest version such that it would be compatible with the latest debugger.
@jhunzik 
@ethantmanns 
@codice/test 
@figliold
@tbatie
- unzip DDF
- comment out the `"file:/platform-migration/platform-migratable-api"` section in the  default.policy file
- start DDF
- attach the latest version of the debugger with the `--debug --continuous --wait` options
- perform a migration:export from the command shell
- verify that the debugger is able to analyze the security issues and that the migration export succeeded
[DDF-4223](https://codice.atlassian.net/browse/DDF-4223)
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging …

[2.13.x] DDF-4223 Updated AC debugger to the latest version

---

Jenkinsfile

- Simplifies CI workspace name
- Performs post-build cleanup to mitigate container reuse issues, like disk capacity
@oconnormi 
@mcalcote 
@codice/build 
@clockard
@shaundmorris
Tested on jenkins-test. Ask for URL if needed.
[DDF-4343](https://codice.atlassian.net/browse/DDF-4343?atlOrigin=eyJpIjoiYmMzMjUzNTdjOThkNDU1NjljY2YzMTY4MzdmMWE0ZGYiLCJwIjoiaiJ9) …

DDF-4343 Simplify CI workspace name and perform post-build cleanup

---

pom.xml

Updates the Country Code Converter Version to the most recent release
@gjvera 
@rymach 
@bdeining 
@djblue 
Just needs a build and a successful install. 
[DDF-4364](https://codice.atlassian.net/browse/DDF-4364)
- ❗ …

DDF-4364 Update Country Converter Version

---

ui/packages/catalog-ui-search/src/main/webapp/component/between-time/between-time.hbs
ui/packages/catalog-ui-search/src/main/webapp/component/between-time/between-time.less
ui/packages/catalog-ui-search/src/main/webapp/component/between-time/between-time.view.js
ui/packages/catalog-ui-search/src/main/webapp/component/filter-comparator/filter-comparator.view.js
ui/packages/catalog-ui-search/src/main/webapp/component/filter/filter.view.js
ui/packages/catalog-ui-search/src/main/webapp/component/query-basic/query-basic.view.js
ui/packages/catalog-ui-search/src/main/webapp/component/query-time/query-time.hbs
ui/packages/catalog-ui-search/src/main/webapp/component/query-time/query-time.view.js
ui/packages/catalog-ui-search/src/main/webapp/js/CQLUtils.js
ui/packages/catalog-ui-search/src/main/webapp/js/CQLUtils.spec.js
ui/packages/catalog-ui-search/src/main/webapp/js/filter.js
ui/packages/catalog-ui-search/src/main/webapp/react-component/container/input-wrappers/date/date.tsx

- Adds a 'Between' temporal option to the advanced search builder that allows a user to specify a 'From' date and a 'To' date.
- Refactors the 'Between' portion of the 'Basic Search' form to use the same component as the advanced search builder.
- All 'Between' queries in Intrigue now use a CQL DURING query rather than an AND of a BEFORE and an AFTER query.
@bellcc 
@leo-sakh 
@glenhein 
@codice/ui 
@djblue
1. Ingest some test data or configure a federated source.
2. Create searches on various temporal fields using the new 'Between' option in the advanced search builder and verify that you get the correct results.
a. You can disable WebSockets and check in your browser's developer tools that the CQL in the requests to the `/cql` endpoint has the correct …

DDF-4342 Add 'Between' temporal option to the advanced search builder

---

.github/PULL_REQUEST_TEMPLATE

Anybody
@coyotesqrl 
@shaundmorris 
[DDF-3976](https://codice.atlassian.net/browse/DDF-3976)

[2.13.x]DDF-3976 Adding brjeter as a committer to the PR template

---

.github/PULL_REQUEST_TEMPLATE

Anybody
@coyotesqrl 
@shaundmorris 
[DDF-3976](https://codice.atlassian.net/browse/DDF-3976)

DDF-3976 Adding brjeter as a committer to the PR template

---

catalog/transformer/catalog-transformer-preview/pom.xml
catalog/transformer/catalog-transformer-preview/src/main/java/org/codice/ddf/transformer/preview/PreviewMetacardTransformer.java
features/cxf/src/main/feature/feature.xml
pom.xml

Makes the text preview action display html text rather than rendering them in the browser
Before:
After:
@mcalcote 
@ricklarsen 
@ahoffer 
@clockard
@vinamartin
[DDF-4355](https://codice.atlassian.net/browse/DDF-4355)
- …

[2.13.x] DDF-4355 Sanitize Text Preview Action

---

catalog/transformer/catalog-transformer-preview/pom.xml
catalog/transformer/catalog-transformer-preview/src/main/java/org/codice/ddf/transformer/preview/PreviewMetacardTransformer.java
features/cxf/src/main/feature/feature.xml
pom.xml

Makes the text preview action display html text rather than rendering them in the browser
Before:
After:
@mcalcote 
@ricklarsen 
@ahoffer 
@clockard
@vinamartin
[DDF-4355](https://codice.atlassian.net/browse/DDF-4355)
- …

DDF-4355 Sanitize Text Preview Action

---

distribution/docs/src/main/resources/content/_developing/_devComponents/global-attribute-validators.adoc

Adds a missing comma to the sample validators section.
anyone
@codice/docs 
@vinamartin
Build the docs and make sure the example has correct json syntax.
- ❗ …

DDF-2824 Add missing comma in validators doc

---

ui/packages/catalog-ui-search/src/main/webapp/react-component/container/theme-container/theme-container.tsx
ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/user-settings/user-settings.tsx
ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/workspaces-templates/workspaces-templates.tsx
ui/packages/catalog-ui-search/src/main/webapp/styles/vars.less

- Updates the dark theme.
@djblue 
@TeresaHudson 
@jrnorth 
@brianfelix 
Go to the UI and verify the colors are applied appropriately.  Update the user theme to another choice (sea?) and verify it still works as expected.
[DDF-3762](https://codice.atlassian.net/browse/DDF-3762)

DDF-3762 Updates color scheme

---

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/forms/SearchFormsLoader.java

When the catalog ui search bundle gets reloaded, system-templates duplicated. Things become an issue in operations as we hot deploy the UI jar or restart the bundle (mass template duplication). This blocks this from happening by treating the titles of _system templates_ as a primary key to block against duplication. 
@Bdthomson 
@adimka 
@millerw8 
@bdeining 
@djblue 
[DDF-4380](https://codice.atlassian.net/browse/DDF-4380) …

DDF-4380 Block System Template Duplication in Forms Bootstrapper

---

.github/PULL_REQUEST_TEMPLATE

Adds Joe North to Pull Request Template
@jrnorth

Added Joe North to Pull Request Template

---

ui/packages/catalog-ui-search/src/main/webapp/react-component/menu/menu.js

Fixes dropdown error 
@mojogitoverhere @willwill96 @GabrielFabian  
@codice/ui 
@djblue
[DDF-4385](https://codice.atlassian.net/browse/DDF-4385) …

DDF-4385 Fixing Dropdown error

---

ui/packages/catalog-ui-search/src/main/webapp/component/filter/filter.less
ui/packages/catalog-ui-search/src/main/webapp/component/filter/filter.view.js
ui/packages/catalog-ui-search/src/main/webapp/component/input/date/input-date.view.js

Link to 2.13.x PR: #4089 
____
Changes the placeholder text for a date filter in the advanced search form to use ISO 8601 format. This PR also makes the the date filter text field larger to accommodate all of the placeholder text.
@tbatie 
@mcalcote 
@codice/ui 
@figliold 
The two placeholders that were moved are "Use * for wildcard" and "YYYY-MM-DD[T]HH:mm:ss.SSSZ"
- Verify the date placeholder in the Advanced Search Form has the new value.
- Verify the anyText placeholder is still "Use * for wildcard"
- The date placeholders in the Basic Search Form should be unchanged.
- The search bar on the workspaces page should say "Search DDF Intrigue".
- Verify any other placeholders in Intrigue remain unchanged.
N/A …

DDF-4359 Update date input field placeholder text to use ISO 8601 format

---

index.html

Fixes the release order in the News & Events list on the DDF website.
@bellcc 
@codice/docs 
@shaundmorris
Verify the releases in the News & Events page are in chronological order. …

DDF-2824 Fix release order in News & Events list on DDF website

---

catalog/core/catalog-core-commons/src/main/java/ddf/util/XPathHelper.java
catalog/core/catalog-core-commons/src/test/java/ddf/catalog/impl/XPathHelperTest.java

This PR allows XPathhelper print to analyze and print xml attributes 
@ahoffer @mcalcote @garrettfreibott 
@clockard
@vinamartin
[DDF-4382](https://codice.atlassian.net/browse/DDF-4382) …

DDF-4382 XPathHelper print removes the tags and attributes from the results

---

platform/security/idp/security-idp-client/pom.xml
platform/security/idp/security-idp-client/src/main/java/org/codice/ddf/security/idp/client/IdpHandler.java
platform/security/idp/security-idp-client/src/test/java/org/codice/ddf/security/idp/client/IdpHandlerTest.java
platform/security/rest/security-rest-cxfwrapper/src/main/java/org/codice/ddf/cxf/client/impl/SecureCxfClientFactoryImpl.java
platform/security/rest/security-rest-cxfwrapper/src/test/java/org/codice/ddf/cxf/SecureCxfClientFactoryTest.java
platform/security/rest/security-rest-cxfwrapper/src/test/resources/SAMLAssertion.xml

Link to 2.13.x PR: #4122 
@blen-desta @Kjames5269 
@clockard 
@stustison
[DDF-4389](https://codice.atlassian.net/browse/DDF-4389)

DDF-4389 Disable ECP when not using HTTPS (#4122)

---

catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/SolrFilterDelegate.java
catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/SolrFilterDelegateTest.java
catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/provider/SolrProviderQuery.java

Fix bug that caused the DivisibleBy query not to work 
@KalCramer 
@a-asaad 
@codice/solr 
@jrnorth
@pklinef
[](https://codice.atlassian.net/browse/DDF-4391)
- [ x] Update / Add Unit Tests …

[2.13.x] DDF-4391 DivisibleBy query does not work on multivalued fields

---

platform/security/rest/security-rest-cxfwrapper/src/main/java/org/codice/ddf/cxf/paos/PaosInInterceptor.java
platform/security/rest/security-rest-cxfwrapper/src/test/java/org/codice/ddf/cxf/paos/PaosInInterceptorTest.java

Copies the message headers from the given message to the created request in the `PaosInInterceptor`. This will make sure the message headers are not lost while doing ECP. 
@garrettfreibott @Kjames5269 
@brjeter
@stustison
Verify that headers are not dropped during federation over HTTP.
[DDF-4398](https://codice.atlassian.net/browse/DDF-4398) …

[2.13.x] DDF-4398 The PaosInInterceptor drops headers when doing ECP

---

catalog/ui/search-ui-app/src/main/resources/etc/IntrigueBundle.properties
ui/packages/catalog-ui-search/src/main/webapp/js/ApplicationSetup.js
ui/packages/catalog-ui-search/src/main/webapp/js/model/Query.js

- Localized error polling sources message
- Fixed undefined attribute
@leo-sakh 
@brianfelix 
@codice/ui 
@djblue
- Do not enable local search
- Perform a search with no sources selected
[DDF-4394](https://codice.atlassian.net/browse/DDF-4394)

DDF-4394 Localized polling sources error message

---

dependency-check-maven-config.xml

Forward-port: #4147 
@ahoffer @blen-desta 
@codice/build
@coyotesqrl 
@stustison 
[DDF-4407](https://codice.atlassian.net/browse/DDF-4407) …

[2.13.x]DDF-4407 Suppress CVE-2018-8088, a slf4j vulnerability that doesn't affect DDF

---

dependency-check-maven-config.xml

Backport: #4148
@ahoffer @blen-desta 
@codice/build
@coyotesqrl 
@stustison 
[DDF-4407](https://codice.atlassian.net/browse/DDF-4407)

DDF-4407 Suppress CVE-2018-8088, a slf4j vulnerability that doesn't affect DDF

---

ui/packages/catalog-ui-search/src/main/webapp/component/builder/builder.less
ui/packages/catalog-ui-search/src/main/webapp/component/builder/builder.view.js
ui/packages/catalog-ui-search/src/main/webapp/component/property/property.collection.view.js

Updates the manual metacard builder so that it can handle missing metacard definitions.
@Schachte 
@glenhein 
@brianfelix 
@bellcc 
@codice/ui 
@bdeining
1. Make sure the `Metacard Type Whitelist` is empty in admin console
2. Check that manual metacard builder is working
3. Add a filter to `Metacard Type Whitelist` in admin console
4. Check that manual opening the manual metacard builder displays a warning message
[DDF-4386](https://codice.atlassian.net/browse/DDF-4386) …

DDF-4386: Missing metacard definition handling and feedback

---

platform/security/rest/security-rest-cxfwrapper/src/main/java/org/codice/ddf/cxf/paos/PaosInInterceptor.java
platform/security/rest/security-rest-cxfwrapper/src/test/java/org/codice/ddf/cxf/paos/PaosInInterceptorTest.java

Link to 2.13.x PR: https://github.com/codice/ddf/pull/4138
____
@garrettfreibott @Kjames5269 
@brjeter
@stustison

DDF-4398 The PaosInInterceptor drops headers when doing ECP

---

pom.xml

Upgraded CountryCode
@Bdthomson @Schachte @GabrielFabian @willwill96 
@codice/build 
@jrnorth
@djblue 
Full Build Should Suffice …

DDF-4399 Upgraded CountryCode

---

platform/persistence/platform-persistence-core-impl/src/main/java/org/codice/ddf/persistence/internal/PersistentStoreImpl.java
platform/persistence/platform-persistence-core-impl/src/test/java/org/codice/ddf/persistence/internal/PersistentStoreImplTest.java

Reduce soft commit timings for persistent store to reduce lag for user preferences.
@Schachte 
@djblue
@codice/solr
@bdeining 
@pklinef
Change your theme and see if it's immediately persisted on page refresh.
[DDF-4397](https://codice.atlassian.net/browse/DDF-4397) …

DDF-4397 Reduce soft commit timings for persistent store

---

distribution/ddf-common/src/main/resources/etc/log4j2.config.xml
distribution/ddf-common/src/main/resources/etc/org.ops4j.pax.logging.cfg

Backport of https://github.com/codice/ddf/pull/4146
@clockard @tbatie @austinsteffes @mcalcote 

DDF-4406 Removes references to unused solr.log file (#4146)

---

ui/packages/catalog-ui-search/src/main/webapp/component/search-form/search-form.view.js

This PR fixes some styling issues with the result forms that resulted in the text being centered.
@codice/ui 
@jrnorth
Build / Install / Add search form and verify it is not centered
[DDF-4235](https://codice.atlassian.net/browse/DDF-4235)
Before
After …

DDF-4235 Fixed styling for system result forms

---

.github/PULL_REQUEST_TEMPLATE

Adds threat dragon models to checklist in PR template
@stustison 
@rzwiefel 
@shaundmorris 
@coyotesqrl 
[DDF-3976](https://codice.atlassian.net/browse/DDF-3976) …

DDF-3976 Add threat dragon to checklist

---

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/forms/api/FilterNode.java
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/forms/api/FilterVisitor2.java
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/forms/api/FlatFilterBuilder.java
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/forms/builder/JsonModelBuilder.java
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/forms/builder/XmlModelBuilder.java
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/forms/filter/AbstractFilterVisitor2.java
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/forms/filter/TransformVisitor.java
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/forms/filter/VisitableJsonElementImpl.java
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/forms/filter/VisitableXmlElementImpl.java
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/forms/model/FilterNodeImpl.java
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/forms/model/FilterNodeMapImpl.java
catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/forms/FilterNodeAssertionSupport.java
catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/forms/builder/JsonModelBuilderTest.java
catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/forms/builder/XmlModelBuilderTest.java
catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/forms/filter/TransformVisitorJsonTest.java
catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/forms/filter/TransformVisitorXmlTest.java
catalog/ui/catalog-ui-search/src/test/resources/forms/filter-json/spatial-distance-ops/DWithin.json
catalog/ui/catalog-ui-search/src/test/resources/forms/filter2/spatial-distance-ops/DWithin.xml

Enable users to create and use search forms with point radii
@GabrielFabian 	@gjvera 	@willwill96 	@rymach 	
@bdeining
@djblue
Create search forms with point radii. Verify they save successfully and their values are correct when they are editted and used to search.
[DDF-4373](https://codice.atlassian.net/browse/DDF-4373) …

DDF-4373 Add support for search forms with point radii

---

ui/packages/catalog-ui-search/src/main/webapp/component/confirmation/confirmation.less
ui/packages/catalog-ui-search/src/main/webapp/component/confirmation/query/confirmation.query.hbs
ui/packages/catalog-ui-search/src/main/webapp/component/confirmation/query/confirmation.query.less
ui/packages/catalog-ui-search/src/main/webapp/component/confirmation/query/confirmation.query.view.js
ui/packages/catalog-ui-search/src/main/webapp/component/dropdown/query-select/dropdown.query-select.hbs

Refactor and clarify max query per workspace notification.
@codice/ui 
@bdeining
- build, install, boot up UI. 
- create 11 queries on 1 workspace.
- the 11th query should trigger this warning.
- verify new style/verbage is correct.
- verify ability to replace a query with the new query.
- verify ability to create a new workspace with the new query.
**Mockups provided by @TeresaHudson**
**Old View:**
**New View:**
[DDF-4400](https://codice.atlassian.net/browse/DDF-4400) …

DDF-4400 refactored max query notification

---

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/forms/SearchFormsApplication.java
ui/packages/catalog-ui-search/src/main/webapp/component/announcement/announcements.jsx
ui/packages/catalog-ui-search/src/main/webapp/component/query-advanced/query-advanced.view.js
ui/packages/catalog-ui-search/src/main/webapp/component/result-form/result-form-collection-instance.js
ui/packages/catalog-ui-search/src/main/webapp/component/result-form/result-form.collection.js
ui/packages/catalog-ui-search/src/main/webapp/component/result-form/result-form.js
ui/packages/catalog-ui-search/src/main/webapp/component/result-form/result-form.view.js
ui/packages/catalog-ui-search/src/main/webapp/component/result-form/result-forms.view.js
ui/packages/catalog-ui-search/src/main/webapp/component/search-form-editor/search-form-editor.view.js
ui/packages/catalog-ui-search/src/main/webapp/component/search-form-interactions/search-form-interactions.view.js
ui/packages/catalog-ui-search/src/main/webapp/component/search-form/forms-sharing/search-form-sharing.collection.js
ui/packages/catalog-ui-search/src/main/webapp/component/search-form/forms-system/search-form-system.collection.js
ui/packages/catalog-ui-search/src/main/webapp/component/search-form/search-form.collection.js
ui/packages/catalog-ui-search/src/main/webapp/component/search-form/search-form.hbs
ui/packages/catalog-ui-search/src/main/webapp/component/search-form/search-form.js
ui/packages/catalog-ui-search/src/main/webapp/component/search-form/search-form.view.js
ui/packages/catalog-ui-search/src/main/webapp/js/model/Query.js

Allows you to see new search and result forms in the grid without refreshing the page
@bdeining
@djblue
- Search Forms
- Navigate to the Search Forms page
- Create a new form
- Verify that a success message appears saying the form was successfully saved
- Ensure that you can see the new form in the grid without refreshing the page
- Click the interactions drop-down
- Verify that you see _all_ of the following options:
- Make Default Form
- Share Form
- Edit Form
- Delete Form
- Make sure you can successfully complete all these actions
- When editing, change the title and search term
- After editing and saving, ensure that you see a success message saying the form was successfully saved
- Refresh the page and verify that all your edits persisted
- …

DDF-4368 Updating search and result forms without page refresh

---

catalog/ui/catalog-ui-search/pom.xml
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/forms/SearchFormsApplication.java
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/forms/SearchFormsLoader.java
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/forms/SearchFormsUtil.java
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/forms/commands/SearchFormsLoaderCommand.java
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/forms/commands/SearchFormsManageCommand.java
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/util/EndpointUtil.java
catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/forms/SearchFormsLoaderTest.java
catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/forms/commands/SearchFormsLoaderCommandTest.java
catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/forms/commands/SearchFormsManageCommandTest.java
distribution/ddf-common/src/main/resources/etc/forms/readme.md
distribution/docs/src/main/resources/content/_managing/_running/forms-commands.adoc

Adds Karaf command to manage system templates.
@Bdthomson 
@middlets719 
@zta6 
@bdeining 
@millerw8 
@djblue 
Run the command `forms:load` to invoke the ingestion of the system templates. Ensure that system templates are placed in the proper directory or else nothing will be ingested.
Run `forms:manage -l / forms:manage --list` to view all ingested forms.
Run `forms:manage -s / forms:manage --remove-single "ID"` to remove a single metacard.
Run `forms:manage -r / forms:manage --remove-all` to remove all system templates.
[DDF-4401](https://codice.atlassian.net/browse/DDF-4401)
- [ x ] Update / Add Unit Tests …

DDF-4401 Adding System Templates Karaf Command

---

catalog/confluence/catalog-confluence-source/src/main/java/org/codice/ddf/confluence/source/ConfluenceInputTransformer.java
catalog/confluence/catalog-confluence-source/src/main/java/org/codice/ddf/confluence/source/ConfluenceSource.java
catalog/confluence/catalog-confluence-source/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/confluence/catalog-confluence-source/src/main/resources/OSGI-INF/metatype/metatype.xml
catalog/confluence/catalog-confluence-source/src/test/java/org/codice/ddf/confluence/source/ConfluenceInputTransformerTest.java
catalog/confluence/catalog-confluence-source/src/test/resources/confluence_page_storage_body.json

Link to 2.13.x PR: https://github.com/codice/ddf/pull/4145
____
Fix confluence body expansion 
@brjeter
@vinamartin
CI build
[DDF-4404](https://codice.atlassian.net/browse/DDF-4404)

DDF-4404 Fix confluence body expansion (#4145)

---

distribution/ddf-common/src/main/resources-filtered/etc/custom.system.properties
platform/platform-paxweb-jettyconfig/pom.xml
platform/platform-paxweb-jettyconfig/src/main/java/org/codice/ddf/pax/web/jetty/CsrfFilter.java
platform/platform-paxweb-jettyconfig/src/test/groovy/org/codice/ddf/security/filter/csrf/CsrfFilterSpec.groovy

Link to master PR: https://github.com/codice/ddf/pull/4150
____
Adds a whitelist for trusted host and port combinations for the CSRF filter
@Bdthomson 
@rzwiefel
@tbatie
@vinamartin
1. Ensure `csrf.enabled` is set to `true` in `custom.system.properties`.
2. Verify that CSRF is enabled
- Login, then attempt to hit https://localhost:8993/admin/jolokia/ from your browser.
- Verify that you get a 403 response.
3. Test the trusted authorities list
- Set `csrf.trustedAuthorities` to `localhost:5000`
- Attempt to hit https://localhost:8993/admin/jolokia/ from postman or cURL with the following headers:
- `X-Requested-With: XMLHttpRequest`
- `Origin: https://localhost:5000`
- Verify that you get a json response.
4. Test disabling CSRF
- Set `csrf.enabled` to …

[2.13.x] DDF-4408 Adding whitelist for trusted host and port combinations for the CSRF filter

---

platform/security/sts/security-sts-ldaplogin/src/main/java/ddf/ldap/ldaplogin/SslLdapLoginModule.java

Improves logging when there is an LDAP authentication issue.
@blen-desta @bakejeyner  
@tbatie @brjeter 
1. Configure LDAP for Auth and a data store as shown below:
2. Login with the ldap credentials
3. The data store should be incorrectly setup so you'll see an error that the user failed to login, and the attributes were not found.
[DDF-4422](https://codice.atlassian.net/browse/DDF-4422) …

[2.13.x] DDF-4422 Making LDAP logging more verbose

---

platform/security/core/security-core-services/src/main/java/ddf/security/samlp/impl/LogoutMessageImpl.java

Changes the ID attribute on a LogoutRequest to comply with the SAML Specification
@bakejeyner @Kjames5269 
@brjeter
@coyotesqrl
Run the [SAML Conformance Test Kit](https://github.com/codice/saml-conformance) and make sure it passes.
[DDF-4434](https://codice.atlassian.net/browse/DDF-4434) …

[2.13.x] DDF-4434 Changed the ID attribute on a LogoutRequest to comply with the SAML Specification

---

platform/security/core/security-core-services/src/main/java/ddf/security/samlp/impl/LogoutMessageImpl.java

Link to 2.13.x PR: https://github.com/codice/ddf/pull/4186
____
@bakejeyner @Kjames5269 
@brjeter
@coyotesqrl

DDF-4434 Changed the ID attribute on a LogoutRequest to comply with the SAML Specification

---

ui/packages/catalog-ui-search/src/main/webapp/component/ingest-editor/ingest-editor.view.js
ui/packages/catalog-ui-search/src/main/webapp/component/property/property.collection.view.js

Link to 2.13.x PR: https://github.com/codice/ddf/pull/4164
@andrewkfiedler @brendan-hofmann @rzwiefel @mcalcote 

DDF-4415 Initializes upload editor to not show validation issues on load

---

catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/SolrFilterDelegate.java
catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/SolrFilterDelegateTest.java
catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/provider/SolrProviderQuery.java

- Teams tagged
Link to 2.13.x PR: #4123
____
@KalCramer  
@a-asaad
@codice/solr 
@jrnorth
@pklinef
- ❓ (Question …

DDF-4391 fix DivisibleBy query function

---

ui/packages/catalog-ui-search/src/main/webapp/js/store.js
ui/packages/catalog-ui-search/src/main/webapp/react-component/container/sharing/sharing.tsx
ui/packages/catalog-ui-search/src/main/webapp/react-component/container/workspace-interactions/workspace-interactions.tsx
ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/workspace-interactions/workspace-interactions.tsx
ui/packages/catalog-ui-search/src/main/webapp/react-component/utils/security/security.tsx

- When a user attempts to delete a workspace that has been shared with others it reminds the user and asks whether they want to `Cancel` or `Continue`
@rymach 
@codice/ui 
@djblue
- Create a shared workspace and refresh
- Verify that the user is prompted when deleting this workspace
- Create a non-shared workspace and refresh
- Verify that the user is not prompted when deleting this workspace
- Prior to this workspaces that have been shared could be deleted without any reminder. 
[DDF-4429](https://codice.atlassian.net/browse/DDF-4429)
- ✏️ (Pencil) This comment …

DDF-4429 Reminder when deleting shared workspaces

---

ui/packages/catalog-ui-search/package.json
ui/yarn.lock

Upgraded to newer usng.js library with fixed northing values in lat long to utm conversions.
Updates the USNG.js library to the latest version which fixes the northing values of UTM coordinates when converted from lat lon coordinates in the southern hemisphere. This fixes the display of UTM coordinates on the 2D and 3D maps when you choose UTM coordinate display from the config menu in the southern hemisphere. This also fixes the display of UTM coordinates when copying UTM coordinates from the 2D and 3D maps in the southern hemisphere.
@rymach @dimitry-sherman @samuelechu 
@andrewkfiedler @bdeining 
Build DDF on the 2D and 3D maps change the coordinate display to UTM/UPS and move to the southern hemisphere any where between the equator and 80 degrees south. Verify that the northing value …

DDF-4437 Bumps usng.js version to the latest

---

dependency-check-maven-config.xml
distribution/docs/src/main/resources/content/_reference/_dependencyList/ddf-dependency-list.adoc
platform/solr/solr-dependencies/pom.xml
pom.xml

- Upgrades jackson to version 2.9.8
@codice/build 
@bdeining
@tbatie 
- Version upgrade so full build is sufficient
[DDF-4439](https://codice.atlassian.net/browse/DDF-4439) …

DDF-4439 Upgrade jackson databind to version 2.9.8

---

dependency-check-maven-config.xml
distribution/docs/src/main/resources/content/_dependencyList/ddf-dependency-list.adoc
pom.xml
ui/yarn.lock

- Upgrades jackson to version 2.9.8
- Suppresses a number of false positives
- Suppresses additional CVE for karaf
@brjeter 
@paouelle 
@codice/build 
@bdeining
@paouelle
- Full build is sufficient since this is just a version upgrade
- None
[DDF-4439](https://codice.atlassian.net/browse/DDF-4439) …

[2.13.x] DDF-4439 Upgrade jackson to version 2.9.8

---

catalog/core/catalog-core-eventcommands/pom.xml
catalog/core/catalog-core-eventcommands/src/main/java/org/codice/ddf/catalog/pubsub/command/ListCommand.java
catalog/core/catalog-core-eventcommands/src/test/java/org/codice/ddf/catalog/pubsub/command/ListCommandTest.java
distribution/ddf-common/src/main/resources/security/default.policy
platform/security/rest/security-rest-cxfwrapper/src/main/java/org/codice/ddf/cxf/paos/PaosInInterceptor.java
ui/packages/catalog-admin-module-sources/src/main/webapp/js/model/Source.js
ui/packages/catalog-admin-module-sources/src/main/webapp/js/model/Status.js

Link to 2.13.x PR: #4082
____
This is a forward port of some bugfixes related to source and subscription management. It also improves the output of the `subscriptions:list` command
@bakejeyner @blen-desta @Kjames5269 
@codice/ui
TEST 1: Sources UI
1. Create a new source in the sources UI, and open the browser dev tools to view the network tab.
2. Select and close the source edit modal a few times, and disable/re-enable the source a few times.
3. Verify there is still just a single request to the backend every 30 seconds.
4. Disable the source. Verify that the requests to the backend stop
TEST 2: subscriptions:list AccessControlException
1. Create a subscription pointing to a site that DDF does not trust, e.g. example.com
2. Run the subscriptions:list command and verify …

DDF-{4365, 4370, 4372, 4374} Bugfixes for source and subscription management

---

ui/packages/catalog-ui-search/src/main/webapp/component/input/enum/input-enum.less
ui/packages/catalog-ui-search/src/main/webapp/component/lightbox/result/lightbox.result.less
ui/packages/catalog-ui-search/src/main/webapp/component/result-form/result-form-tab-container.view.js
ui/packages/catalog-ui-search/src/main/webapp/component/result-form/result-form.collection.js
ui/packages/catalog-ui-search/src/main/webapp/component/result-form/result-form.less
ui/packages/catalog-ui-search/src/main/webapp/component/search-form-interactions/search-form-interactions.view.js
ui/packages/catalog-ui-search/src/main/webapp/component/search-form/search-form.js

- Fixes the way selected attributes are rendered in the result form editor once saved
- Refactors result form code to more closely resemble its search form counterpart
- Fixes saved result forms re-routing to the search forms page
- Adds a scrollbar for fields that overflow the lightbox when the screen is not maximized
- Create and save a result form with all attributes selected
- Re-open the saved result form
- Verify that you see the attributes dropdown (similar to the second screenshot below)
- Experiment with the window size and make sure that a scrollbar appears on the result form editor, allowing you to scroll to see all fields when the screen is too small to display them all at once
- Close the result form
- Refresh the page
- Make sure the result form you saved is …

DDF-4420 Fixed rendering of large number of attributes on result forms

---

.github/PULL_REQUEST_TEMPLATE

Update DDF pull request template to add Ethan Manns as a committer
@coyotesqrl
@vinamartin

Add Ethan Manns to PR template

---

platform/admin/core/admin-core-migration-commands/pom.xml
platform/admin/core/admin-core-migration-commands/src/main/java/org/codice/ddf/migration/commands/ImportCommand.java
platform/admin/core/admin-core-migration-commands/src/test/java/org/codice/ddf/migration/commands/ImportCommandTest.java

Other DDF commands have warnings that protect against actions that might have irreversible consequences on the system (removing all records from the catalog, restarting the system, etc.). 
The migration:import command can potentially reconfigure the entire system and also restarts the system. An admin running the command should be warned before running it. 
@Kjames5269 @josephthweatt @emmberk 
@brjeter
@ethantmanns 
Build and run DDF.
Run `migration:export`. 
Attempt to run `migration:import` and notice that a warning message appears explaining what possible consequences will come after running the command.
Try using yes, no, and text that isn't yes or no. Verify the expected result occurs. 
Run `migration:import --force` and `migration:import -f` and verify the command runs without the …

[2.13.x] DDF-4468 Adds migration:import warning message and force option

---

ui/packages/admin-metrics-ui/src/main/resources/index.html
ui/packages/admin-metrics-ui/src/main/webapp/main.js
ui/packages/admin-security-certificate-ui/src/main/resources/index.html
ui/packages/admin-security-certificate-ui/src/main/webapp/main.js
ui/pom.xml

Updated blueimp dependency to fix owasp
@Schachte @Bdthomson 
@ethantmanns
@jrnorth
Build / verify upload for certs on admin ui security tab
[DDF-4464](https://codice.atlassian.net/browse/DDF-4464) …

DDF-4464 blue imp dependency

---

ui/packages/catalog-ui-search/src/main/webapp/component/navigator/navigator.view.js

Adds a link to the system root context from the Intrigue navigation slideout to allow users to easily return to the system home from the search UI.
@Schachte @gordocanchola @middlets719 @zta6 
@codice/ui 
@bdeining
@djblue
From Intrigue, use the hamburger icon to open the navigation slideout, select the "DDF Home" option, and ensure that you're redirected to the system root context.
[DDF-4455](https://codice.atlassian.net/browse/DDF-4455)
- ❗ …

DDF-4455 Adds a link to the system root context from the Intrigue navigation slideout

---

catalog/ui/catalog-ui-search/pom.xml

Remove dependency that's no longer available
This is breaking mvn release process. 
@bdeining 
@troymohl 
Full CI build
This dependency was introduced in 
https://codice.atlassian.net/browse/DDF-4120 …

DDF-4120 remove unused dependency

---

platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/server/IdpEndpoint.java
platform/security/idp/security-idp-server/src/test/java/org/codice/ddf/security/idp/server/IdpEndpointTest.java
platform/security/sts/security-sts-realm/src/main/java/ddf/security/realm/sts/AbstractStsRealm.java

@blen-desta @garrettfreibott 
@coyotesqrl
@stustison
@tbatie

DDF-4430 updated the IdP to allow it to renew expired assertions

---

ui/packages/catalog-ui-search/src/main/webapp/js/model/UploadBatch.js

Prevents the Upload Editor from reaching 100% until all files are finished uploading
@rymach 
@bdeining
1. Upload several items in one click via the upload tab and by creating a list
2. Ensure that the percentage does not reach 100% until all uploads are resolved
[DDF-4423](https://codice.atlassian.net/browse/DDF-4423)
Example of Issue: …

DDF-4423 Upload Editor Reads 100% Before All Files Uploaded

---

distribution/ddf-common/src/main/resources/security/default.policy

adds permissions to default.policy to stop accesscontrolexception
@brjeter
1. Perform a standard install of DDF. I used the standard profile from the Karaf shell.
2. Log into the Admin UI.
3. Navigate to the session renew endpoint: https://localhost:8993/services/internal/session/renew. The request should succeed and you should see a page containing only a number indicating the number of milliseconds until the session expires.
4. Now, from the Karaf shell, reinstall the security-sts-server feature (Note: don't disable bundle refreshing)
admin@root()> feature:install security-sts-server
5. In a fresh browser session (e.g. new Incognito window), again log into the Admin UI.
6. Once again, navigate to the session renew endpoint: …

DDF-4453 AccessControlException after refreshing security-sts-server feature

---

index.html

updates documentation on [ddf.codice.org](http://codice.org/ddf/) for 2.13.5 release.
@codice/docs 
@brjeter
@clockard
@lessarderic
@mcalcote
@shaundmorris …

DDF-2824 updated product site for 2.13.5 release

---

ui/packages/catalog-ui-search/src/main/webapp/component/list-interactions/list-interactions.view.js
ui/packages/catalog-ui-search/src/main/webapp/react-component/container/table-export/table-export.tsx
ui/packages/catalog-ui-search/src/main/webapp/react-component/utils/save-file/index.tsx
ui/packages/catalog-ui-search/src/main/webapp/react-component/utils/save-file/save-file.tsx

Enables list actions to be called using `fetch`, and adds a check for `content-disposition` to download files.
@codice/ui
@bdeining
@djblue
a. Register a list action that downloads a file
b. Register a list action that provides a json payload with a success and a failure case.
[DDF-4341 ](https://codice.atlassian.net/browse/DDF-4341) …

DDF-4341 Enable list actions to be called with fetch

---

catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/LatestCommand.java
distribution/docs/src/main/resources/content/_managing/_running/catalog-commands.adoc

Link to 2.13.x PR: https://github.com/codice/ddf/pull/4242
____
@ethantmanns @emmberk 

DDF-4473 Changes Latest Command to use Metacard.Modifed instead of Modified

---

distribution/docs/src/main/resources/content/_appReferences/mg-geowebcache.adoc

Fills in missing values for the `Adding GeoWebCache layers` table in the documentation.
@bakejeyner @austinsteffes @ahoffer 
@codice/docs 
@brjeter
@clockard
@lessarderic
@mcalcote
@shaundmorris
verify content additions …

DDF-2824 filled in missing table information for GeoWebCache docs

---

ui/packages/catalog-ui-search/src/main/webapp/component/result-selector/result-selector.view.js

Removes throttle from result selector view
@mojogitoverhere @Bdthomson @willwill96 
@codice/ui 
@bdeining 
@djblue 
ingest some data 
run a while card search 
click the play button several times 
ensure all results are returned and there is no flickering
create a list with some of the results 
ensure results are returned in the list with no flickering or delay
[DDF-4476](https://codice.atlassian.net/browse/DDF-4476)
- …

DDF-4476 removing throttle from result selector view

---

ui/packages/catalog-ui-search/src/main/webapp/component/location-new/inputs/masked-text-field.js
ui/packages/catalog-ui-search/src/main/webapp/component/location-new/utils/dms-utils.js
ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-old.js
ui/packages/catalog-ui-search/src/main/webapp/react-component/location/base.line.js
ui/packages/catalog-ui-search/src/main/webapp/react-component/location/location.js
ui/packages/catalog-ui-search/src/main/webapp/react-component/text-field/text-field.js
ui/packages/catalog-ui-search/src/main/webapp/react-component/text-field/text-field.spec.js

Adds validation that the user can see before executing a query. If a user tries to input a lat/lon coordinate that is invalid, then the UI will not let them do so.
@willwill96 
@rymach 
@codice/ui 
@bdeining 
@djblue 
Create an advanced or basic query
create an anyGeo filter, with `point radius` and `bounding box` filters
enter invalid coordinates and ensure the UI will not let you 
ensure no regressions in the geospatial search
[DDF-4467](https://codice.atlassian.net/browse/DDF-4467) …

DDF-4467 Validating lat/lon coords

---

distribution/docs/src/main/resources/content/_using/using-catalog-search-ui.adoc

Link to master PR: #3548 
*Note* : This was not a clean cherry-pick.
This is back port for a docs change that clarifies how to query in Intrigue.
@vinamartin 
@Kjames5269 
@codice/docs 
@emmberk 
Build DDF and verify that the docs render correctly.
While working on #4205 it was clear that we needed to be more verbose with our instructions on how to query in Intrigue.
[DDF-4029](https://codice.atlassian.net/browse/4029)
[documentation.html.zip](https://github.com/codice/ddf/files/2774169/documentation.html.zip) …

[2.13.x] DDF-4029 Updated documentation for advanced search operators

---

.github/ISSUE_TEMPLATE.md

Adds GH Issue template for pilot program
@ryeats
@vinamartin

DDF-0000 Adds GH Issue template

---

.github/PULL_REQUEST_TEMPLATE

@ryeats
@vinamartin
Fixes: #4258 

DDF-04258 Updates PR Template to support GH Issues Pilot

---

ui/packages/catalog-ui-search/src/main/webapp/component/location-new/geo-components/lat-long-dd.js
ui/packages/catalog-ui-search/src/main/webapp/component/location-new/geo-components/wkt.js
ui/packages/catalog-ui-search/src/main/webapp/component/location-new/location-new.js
ui/packages/catalog-ui-search/src/main/webapp/component/location-new/utils/index.js
ui/packages/catalog-ui-search/src/main/webapp/component/location-new/utils/wkt-utils.js
ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-old.js
ui/packages/catalog-ui-search/src/main/webapp/js/DistanceUtils.js
ui/packages/catalog-ui-search/src/main/webapp/js/widgets/cesium.bbox.js
ui/packages/catalog-ui-search/src/main/webapp/js/widgets/cesium.circle.js
ui/packages/catalog-ui-search/src/main/webapp/js/widgets/cesium.line.js
ui/packages/catalog-ui-search/src/main/webapp/js/widgets/cesium.polygon.js
ui/packages/catalog-ui-search/src/main/webapp/js/widgets/openlayers.bbox.js
ui/packages/catalog-ui-search/src/main/webapp/js/widgets/openlayers.circle.js
ui/packages/catalog-ui-search/src/main/webapp/js/widgets/openlayers.line.js
ui/packages/catalog-ui-search/src/main/webapp/js/widgets/openlayers.polygon.js

Changes the drawing tools for both 2D and 3D maps to create points with 6 digits of precision, rather than 14 digits. 14 digits of precision makes things hard to read in the UI, and is more precision than is necessary. You can read about the physical precision of various amounts of decimal precision [here](https://en.wikipedia.org/wiki/Decimal_degrees). 6 digits of decimal precision gives about 0.1m of physical precision. 
❗️ ❗️ ❗️ **This PR depends on changes in this PR: https://github.com/codice/ddf/pull/4229**
@middlets719 
@Schachte 
@bdeining 
@adimka 
codice/ui 
@millerw8
Perform anyGeo searches with each shape (bbox, line, polygon, point radius)
verify that the coordinates of the drawn shape only display 6 digits of precision in the …

DDF-4418 As a user I would like lat/lon values to only have at most 6 points to the right of the decimal so that my locations are easier to read

---

distribution/docs/src/main/resources/content/_sources/wfs-sources-services.adoc

Fixes typo that caused formatting issue with numbered list in WFS sources docs.
@bakejeyner @austinsteffes @ahoffer 
@codice/docs 
@clockard
@lessarderic
@mcalcote
@shaundmorris
verify formatting fix. …

DDF-2824 fixed typo in wfs sources docs

---

distribution/ddf-common/src/main/resources/security/default.policy

Link to 2.13.x PR: #4259 
@coyotesqrl 
@emmberk 
For Jira:
[DDF-4480](https://codice.atlassian.net/browse/DDF-4480)

DDF-4480 Add permission for feature install command

---

distribution/docs/src/main/resources/content/_integrating/_endpoints/metrics-endpoint.adoc
distribution/docs/src/main/resources/content/_managing/_configuring/_sources/wfs-sources-services.adoc
distribution/docs/src/main/resources/content/_reference/_appReferences/mg-broker-app.adoc

Link to 2.13.x PR: [#4257](https://github.com/codice/ddf/pull/4257)
____
Fixes typos that caused formatting issue with numbered list in WFS sources and message broker docs.
@bakejeyner @austinsteffes @ahoffer 
@codice/docs 
@clockard
@lessarderic
@mcalcote
@shaundmorris
verify formatting fix. …

DDF-2824 fixed typos in wfs sources and message broker docs

---

ui/packages/catalog-ui-search/src/main/webapp/js/model/Workspace.collection.js

Replaces the name of the ahoc workspace with `New Workspace` rather than the search query text.
@willwill96 
@hayleynorton 
@andrewzimmer 
@bdeining
@jrnorth 
- Navigate to Workspaces
- Under the `start a new workspace` label search using a query
- Verify that the new workspace is titled `New Workspace` instead of the query you entered
For Jira:
[DDF-4485](https://codice.atlassian.net/browse/DDF-4485)
For GH Issues:
Fixes: #____ …

DDF-4485 Adhoc workspace title is the search query text

---

ui/packages/catalog-ui-search/src/main/webapp/react-component/location/location.js

Currently, as we extend the location component to support more items, BBOX, polygon etc. As the number of items in this section grows, the UI starts to look strange. 
Given that this plugin is extensible and used downstream, the numbers of items has already started to grow and makes for a poor user experience. 
This **UI enhancement** seeks to remediate this problem by placing everything in a scrollable dropdown. 
**Current** 
**Inevitable Issues (Mockup)** 
**Proposed Change**
@bdeining 
@middlets719 
@zta6 
@adimka 
@codice/ui 
@bdeining 
@djblue 
@gjvera 
@middlets719 
For Jira:
For GH Issues:
Fixes: #4297 
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request …

DDF-04297 Refactoring location dropdown

---

.github/ISSUE_TEMPLATE.md
.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/improvement.md
.github/ISSUE_TEMPLATE/task.md

Adds a better description for bugs,
Comments out Any Additional Information
Adds a new Task issue as a catchall. (even though this really only changes the description)
@peterhuffer @vinamartin @ricklarsen @coyotesqrl 
Use the issue templates
For Jira:
For GH Issues:
#4286  …

DDF-04286 Improving the issue templates

---

.github/ISSUE_TEMPLATE/task.md

@AzGoalie
@bdeining
@blen-desta
@brjeter
@clockard
@coyotesqrl
@djblue
@emmberk
@ethantmanns
@figliold
@jlcsmith
@jrnorth
@lessarderic
@mcalcote
@millerw8
@oconnormi
@paouelle
@pklinef
@ryeats
@rzwiefel
@shaundmorris
@stustison
@tbatie
@troymohl
@vinamartin
For Jira:
For GH Issues:
Fixes: #____
- ❓ …

DDF-04286 Removes an unescaped single quote that was breaking the markdown

---

ui/packages/catalog-ui-search/src/main/webapp/react-component/menu/menu.js
ui/packages/catalog-ui-search/src/main/webapp/react-component/menu/menu.less

Fixes the overlap that was found in the location dropdown in Intrigue. It also adds a tooltip to each MenuItem so the user can still read the full location without having to select it.
@Kjames5269 
@emmberk 
@codice/ui 
@djblue 
@vinamartin
- Verify that long location names no longer overflow to the next line in Intrigue's location dropdown.
- Make sure that hovering over each suggestion displays a tooltip with the full location name.
Fixes: #4288 
Before:
After: …

DDF-04288 Fix MenuItem overlap in the Intrigue location dropdown

---

ui/packages/catalog-ui-search/src/main/webapp/plugins/navigation-right.tsx
ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/navigation-right/navigation-right.tsx

Makes `navigation-right` extensible
@bdeining
@djblue
Verify no regression has occurred on the right navigation bar
[DDF-4474](https://codice.atlassian.net/browse/DDF-4474) …

DDF-4474 Made right navigation bar extensible

---

ui/packages/catalog-ui-search/src/main/webapp/component/result-item/result-item.less
ui/packages/catalog-ui-search/src/main/webapp/component/result-item/result-item.view.js

Add additional extensibility to item-result buttons for use in downstream projects
@hayleynorton @Bdthomson 
@codice/ui 
@bdeining
@djblue
- build/run
- ingest data
- verify no regression for result items (mostly buttons) …

DDF-4475 Add additional extensibility to result item

---

features/camel/src/main/feature/feature.xml
features/pom.xml
platform/admin/core/admin-core-insecuredefaults/pom.xml

See: https://github.com/codice/ddf/pull/4322
@emmberk 
@brjeter 
@clockard 
@stustison
See: https://github.com/codice/ddf/pull/2512
Fixes: https://github.com/codice/ddf/issues/4320 …

[2.13.x] DDF-04320 Force Camel's quartz component to use newer version of c3p0

---

ui/packages/catalog-ui-search/src/main/webapp/js/QueryPolling.js
ui/packages/catalog-ui-search/src/main/webapp/js/model/Query.js

Adds support for preQueryPlugin to be an async function. This will give more flexibility to what the plugin can do
@gjvera 
@rymach 
@bdeining
@djblue
Spot test search functionality: 
- try creating (from both the search bar and a blank workspace), editing, running and saving queries and look for regressions
For GH Issues:
Fixes: #4301  …

DDF-04301 Add support for preQueryPlugin to be async

---

ui/packages/catalog-ui-search/src/main/webapp/react-component/menu/menu.js

Removes title from menu.js
@jhunzik 
@Kjames5269 
@vinamartin
@codice/ui 
- CI build
Fixes: #4288

DDF-04288 Removes title from menu.js

---

distribution/ddf-common/src/main/resources/etc/org.apache.karaf.features.xml

Overrides `org.apache.aries.proxy/org.apache.aries.proxy` to a newer version to fix a bug where default methods within interfaces would throw an exception. 
This will be fixed when we upgrade to Karaf 4.2.3.
Karaf issue: https://issues.apache.org/jira/browse/KARAF-5086
Aries issue: https://issues.apache.org/jira/browse/ARIES-1849
https://github.com/codice/ddf/pull/4250 depends upon this change.
@KalCramer @kcover 
@clockard @brjeter @pklinef 
Successful CI
For Jira: …

[2.13.x] DDF-4472 Overriding blueprint aries version to fix an implementation default bug

---

catalog/confluence/catalog-confluence-source/src/main/resources/OSGI-INF/blueprint/blueprint.xml

Ports a confluence fix to master
@brjeter
@vinamartin
For Jira:
[DDF-4452](https://codice.atlassian.net/browse/4452)

DDF-4452 Fix Confluence connected source blueprint constructor args 

---

dependency-check-maven-config.xml

See the issue description for more background context.
@bakejeyner @tyler30clemens 
@stustison
@emmberk 
N/A
For GH Issues:
Fixes: #4351  …

[2.13.x]DDF-04351 Suppress Karaf's XXE vulnerability

---

distribution/ddf-common/src/main/resources-filtered/etc/org.apache.karaf.features.xml

Link to 2.13.x PR: #4341
____
@kcover @KalCramer 
@clockard 
@brjeter 
@pklinef 
Successful CI
This would be a temporary fix until Karaf gets upgraded to 4.2.3 …

DDF-4472 Overriding apache.aries.proxy to fix an issue with default methods within interfaces

---

distribution/kernel/pom.xml

2.13.x PR: #4359 
The system fails to startup without this. Caused by https://github.com/codice/ddf/pull/4341
@Kjames5269 @vinamartin @Bdthomson @pklinef 
Build and install DDF
For Jira:
- ❗ …

DDF-4472 Fix aries.proxy startup issue

---

distribution/kernel/pom.xml

The system fails to startup without this. Caused by https://github.com/codice/ddf/pull/4341
@Kjames5269 @vinamartin @Bdthomson @pklinef 
Build and install DDF
For Jira: …

[2.13.x]DDF-4472 Fix aries.proxy startup issue

---

ui/packages/catalog-ui-search/src/main/webapp/component/query-settings/query-settings.view.js

Empties the query extensions region when no extension is returned
@codice/ui 
@djblue
Click on the search button to create a new query. Verify that the dropdown still functions normally.
For GH Issues:
Fixes: #4361  …

DDF-04361 Empty the query extensions region when no extension is returned

---

ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/cesium/map.cesium.js
ui/packages/catalog-ui-search/src/main/webapp/js/controllers/cesium.layer-ordering.js
ui/packages/catalog-ui-search/src/main/webapp/js/controllers/cesium.layer-ordering.spec.js
ui/packages/catalog-ui-search/src/main/webapp/js/controllers/cesium.layerCollection.controller.js
ui/packages/catalog-ui-search/src/main/webapp/js/controllers/cesium.layerOrdering.spec.js

Fetch only visible layers on 3D map initialization.
@BernardIgiri 
@Lambeaux 
@codice/ui 
@jrnorth 
Do these on the 3D map:
3. Verify that the order of the layers is as expected when hidden/shown or rearranged.
[DDF-4451](https://codice.atlassian.net/browse/DDF-4451) …

DDF-4451 3D Map Attempts to Fetch Hidden Layers on Initialization

---

ui/packages/catalog-ui-search/src/main/webapp/component/select/filterHelper.js
ui/packages/catalog-ui-search/src/main/webapp/component/select/filterHelper.spec.js
ui/packages/catalog-ui-search/src/main/webapp/component/select/select.collection.view.js

Improves filtering logic for dropdowns in Intrigue.
Previously, filtering through a dropdown would match if any part of the filter was found in the word. This would lead to weird behavior like returning "validation" and "width" when the filter was "id".
The new behavior splits the words on camelcase, dashes, dots, and spaces then checks to see if any of the resulting words start with the filter value. This results in a slightly more intuitive behavior as shown here:
@emmberk @ethantmanns @Kjames5269 @jhunzik 
@TeresaHudson (**UX**)
@AzGoalie
@djblue
Try using a few of the dropdowns in Intrigue as found in Advanced Search, Upload Editor, Metacard editing, etc.
I'm not sure if I chose good delimiters here so make sure to test with as many dropdowns as possible.
[DDF-4478 …

DDF-4478 Improves filtering logic for dropdowns

---

ui/packages/catalog-ui-search/src/main/webapp/js/controllers/ol.layerCollection.controller.js

We have been getting complaints about inconsistencies within our error messages, specifically referring to WMTS as WMT. This has caused confusion in our downstream projects as we refer to the same types of layers as WMTS elsewhere and WMT here.
This is a very small improvement to update these messages by making them read as "WMTS" instead of "WMT".
Example:
https://github.com/codice/ddf/blob/15f20494516fa01613593c0b4055c99bcf020a8e/ui/packages/catalog-ui-search/src/main/webapp/js/controllers/ol.layerCollection.controller.js#L68
https://en.wikipedia.org/wiki/Web_Map_Tile_Service
@djblue 
@bdeining 
@zta6 
@adimka 
@codice/docs 
@codice/ui 
@djblue 
@bdeining
For Jira:
For GH Issues:
Fixes: #4313  …

DDF-04313 Renaming inconsistent WMTS references

---

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/QueryApplication.java
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/ws/JsonRpc.java
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/ws/SecureWebSocketServlet.java
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/ws/WebSocketAuthenticationException.java
ui/packages/catalog-ui-search/src/main/webapp/js/model/QueryResponse.js

Link to 2.13.x PR: #4325
Note: This was not a clean cherry-pick from 2.13.x. I'll note the places where the code is different.
@coyotesqrl
@djblue 
@stustison
For GH Issues:
Fixes: #4318 …

DDF-04318 Check that the user is logged in for every Intrigue WebSocket request

---

ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/map.less
ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/map.view.js
ui/packages/catalog-ui-search/src/main/webapp/react-component/button/split-button/index.spec.js
ui/packages/catalog-ui-search/src/main/webapp/react-component/button/split-button/index.tsx
ui/packages/catalog-ui-search/src/main/webapp/react-component/button/split-button/zoomToHome.tsx
ui/packages/catalog-ui-search/src/main/webapp/styles/mixins.less

Adding split button dropdown react component, zoomToHome implementation component, and replacing the old set home and zoom to home buttons with the new split button.
@samuelechu @Lambeaux @dimitry-sherman 
@djblue 
1. Pan and zoom the map to a recognizable geographic feature.
2. Click the down arrow by the Home button.
3. Click the save option.
4. Pan and zoom anywhere else on the map.
5. Click the Home button and verify that it pans and zooms back to where it was,
For GH Issues:
Fixes: #4307  …

DDF-04307 Migrating home and save home buttons to react

---

ui/packages/security-idp-server/src/main/webapp/js/view/Login.view.js

- Previously the focus wasn't placed on the form, so it made it
slightly frustrating to login.  Now focus is sent to the username
field, resulting in a better experience.
@glenhein 
@tbatie 
@TeresaHudson 
@samuelechu 
@jhunzik 
Go to the login page and verify that focus is placed on the username field.
Fixes: #4375 
Old Behavior on Page Load:
New Behavior on Page load:

DDF-04375 Updates login page to autofocus

---

distribution/docs/src/main/resources/content/_managing/_running/solr-service.adoc

Correctly spells the word "stop"
@emmberk @brjeter @tyler30clemens @austinsteffes @ricklarsen 
@codice/docs 
@brjeter 
@vinamartin 
Build docs, inspect output.
Fixes: #4379 
- [NA] Update / Add Threat Dragon models …

DDF-04379 Correct Typo in Documentation

---

catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/filter/impl/SortByImpl.java
catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/operation/impl/QueryImpl.java
catalog/rest/catalog-rest-impl/src/main/java/org/codice/ddf/rest/impl/action/MetacardTransformerActionProvider.java
catalog/rest/catalog-rest-impl/src/test/java/org/codice/ddf/rest/impl/action/MetacardTransformerActionProviderTest.java
libs/common-system/src/main/java/org/codice/ddf/configuration/SystemBaseUrl.java

Fixes various performance hot spots discovered while testing CSW ingest and query.
Removes reflection for an often used toString and builds with StringBuilder instead.
Caches System.getProperty lookups that are used often, but are now slower due to Java Security Manager.
@leo-sakh 
@Bdthomson  
@bdeining
@coyotesqrl
@stustison 
Full build with tests
Fixes: #4349  …

DDF-04349 Various CSW ingest and query performance updates

---

distribution/ddf-common/src/main/resources/common-bin.xml

Fixes A bug where DDF fails to start if the user has an empty M2
@lamhuy @jhunzik 
@millerw8 @brjeter @pklinef @vinamartin 
See steps [here](#4385)
Spawned from:
For GH Issues:
Fixes: #4385 
- ❗ …

[2.13.x] DDF-04385 Fixing a bug where DDF fails to start if the user has an empty m2

---

Faq.html

Fixes dead link to building instructions on Faq page. 
@codice/docs 
@ethantmanns
@lessarderic
@mcalcote
@shaundmorris
follow the link
For Jira: …

DDF-2824 updated the link on FAQ page

---

catalog/plugin/catalog-plugin-metacard-validation/src/main/resources/OSGI-INF/metatype/metatype.xml
distribution/ddf-common/src/main/resources/etc/ddf.catalog.metacard.validation.MetacardValidityFilterPlugin.config
distribution/ddf-common/src/main/resources/etc/users.properties
distribution/docs/src/main/resources/content/_configuring/hiding-errors-by-role.adoc
distribution/docs/src/main/resources/content/_securing/hardening-checklist.adoc
distribution/docs/src/main/resources/content/_tables/MetacardValidityFilterPlugin.adoc
distribution/test/itests/test-itests-common/src/main/resources/etc/test-users.properties
platform/admin/core/admin-core-impl/src/main/java/org/codice/ddf/admin/core/impl/SystemPropertiesAdmin.java
platform/security/sts/security-sts-propertyclaimshandler/src/test/resources/users.properties

At installation, a role including the hostname is added and used in the MetacardValidityFilterPlugin
@brjeter 
@lessarderic
@mcalcote
- Install with dev=true
- Navigate to admin ui -> catalog -> configuration -> Metacard Validation Filter Plugin
- Make sure Attribute Map's value contains ${your host name}-data-manager
- Upload invalid metacard in catalog. Ensure you can see the result in the search
- Sign out and sign in as admin. Ensure you can NOT see the result in the search
For GH Issues:
Fixes: #4321  …

DDF-4321 adding new role with hostname to control validation filtering

---

ui/packages/catalog-ui-search/src/main/webapp/component/result-form/result-form.view.js

Adds a filter to ensure that hidden attributes are not displayed in the attribute drop-down for adding or editing a result form.
@Bdthomson 
@andrewzimmer 
@hayleynorton 
@codice/ui
@bdeining
1. In the Admin Console, add an attribute to "Catalog UI Search Hidden Attributes"
2. Go to the Result Form page in the Catalog UI and add or edit a Result Form.
3. When viewing the drop-down for attributes, ensure that the hidden attribute is not shown.
For GH Issues:
Fixes: #4399  …

DDF-04399 Filtering out hidden attributes from Result Form

---

distribution/ddf-common/src/main/resources/common-bin.xml

Link to 2.13.x PR: #4386
____
@lamhuy @jhunzik 
@millerw8 @brjeter @pklinef @vinamartin @emmberk 
#4385  …

DDF-4472 Fixing a bug where DDF fails to start if the user has an empty M2

---

catalog/catalog-app/src/main/resources/features.xml
catalog/core/catalog-core-camelcomponent/src/main/java/ddf/camel/component/catalog/inputtransformer/InputTransformerProducer.java
catalog/core/catalog-core-directorymonitor/pom.xml
catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/AbstractDurableFileConsumer.java
catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/AsyncFileAlterationListener.java
catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/AsyncFileAlterationObserver.java
catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/AsyncFileEntry.java
catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/DurableFileAlterationListener.java
catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/DurableFileSystemFileConsumer.java
catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/DurableWebDavFileConsumer.java
catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/FileSystemPersistenceProvider.java
catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/JsonPersistantStore.java
catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/ObjectPersistentStore.java
catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/synchronizations/CompletionSynchronization.java
catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/synchronizations/LoggingSynchronization.java
catalog/core/catalog-core-directorymonitor/src/test/java/org/codice/ddf/catalog/content/monitor/AsyncFileAlterationObserverTest.java

Fixes a problem where the CDM would update it's internal state regardless of if the process completed
successfully or not. This could lead to the CDM and catalog getting out of sync when a network disconnect or ingest failure occurred.
@peterhuffer 
@kcover 
@lessarderic 
@clockard 
@vinamartin 
1. Install DDF
2. Install the standard profile and turn logs up on the CDM. 
3. `log:set TRACE org.codice.ddf.catalog.content.monitor`
** I found it easier to test the disconnect with a breakpoint in the code but It's not required with a big enough directory.
4. start the CDM (in-place) monitoring a network file system. /admin -> catalog -> configurations -> cdm
5. disconnect from the network file system and check that things failed ingesting.
6. Reconnect to the network file system.
7. ensure …

[2.13.x] DDF-4424 Updating the CDM File Directory (in-place) to update the observer state only on a successful ingest to the catalog framework

---

platform/solr/solr-password/pom.xml

Fixes the deployment issue 
```
Can't release project due to non released dependencies :
[ERROR] ddf.lib:spock-shaded:jar:2.13.6-SNAPSHOT:test
[ERROR] in project 'DDF :: Platform :: Solr :: Password' (ddf.platform.solr:solr-password:bundle:2.13.6-SNAPSHOT)
```
@brjeter  @clockard  …

[2.13.x] Remove ref to spock library

---

Documentation-versions.html
index.html

Updates product website for 2.13.6 release.
@codice/docs 
@brjeter
@clockard
@lessarderic
@shaundmorris
For Jira: …

DDF-2824 updated product website for 2.13.6 release

---

platform/security/encryption/platform-security-encryption-crypter/pom.xml

Bumps the version of the `security-encryption-crypter` module.
@blen-desta 
@brjeter 
@coyotesqrl 
Fixes: #4427 

DDF-04427 Bump crypter version

---

catalog/core/catalog-core-standardframework/src/main/resources/OSGI-INF/metatype/metatype.xml
ui/packages/catalog-ui-search/src/main/webapp/component/source-app/source-app.hbs

Fix for #4355 
Adds  allow-same-origin to iframe sandbox
@leo-sakh 
@codice/ui 
@bdeining
rerun steps - webapp should work now …

DDF-04355 Add allow-same-origin to source-app iframe

---

distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/AbstractIntegrationTest.java
distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalogValidation.java

Temporarily fixes the failing tests in TestCatalogValidation by resetting the state after each test. The long term fix should be having each test clean up after themselves. This also changes the timeout from 20 minutes to 2 minutes as it is only used when ingesting and changing properties. 
@austinsteffes @brjeter @ethantmanns 
@codice/test 
@brjeter 
@ethantmanns
For Jira:
For GH Issues:
Fixes: #04321 …

DDF-04321 Temporary fix for TestCatalogValidation and timeout changed to 2 mins

---

catalog/core/catalog-core-commands/src/test/java/org/codice/ddf/commands/catalog/DumpCommandTest.java
catalog/transformer/catalog-transformer-zip/src/test/java/org/codice/ddf/catalog/transformer/zip/ZipCompressionTest.java

- Fixes unit tests on windows by using the proper file separator. 
@willwill96 
@codice/build 
@tbatie
- Build the changed modules on windows
- None
For GH Issues:
Fixes: #4459 
- N/A …

DDF-04459 Fixes zip compression and dump command unit tests on windows

---

distribution/ddf-common/pom.xml
distribution/ddf-common/src/main/resources-filtered/etc/custom.properties
distribution/ddf-common/src/main/resources-filtered/etc/custom.system.properties
distribution/ddf-common/src/main/resources/security/default.policy
distribution/docs/src/main/resources/content/_architectures/_securityFramework/security-encryption-intro.adoc
distribution/docs/src/main/resources/content/_reference/_dependencyList/ddf-dependency-list.adoc
distribution/kernel/pom.xml
platform/osgi/platform-osgi-configadmin/pom.xml
platform/osgi/platform-osgi-configadmin/src/main/java/org/codice/felix/cm/file/EncryptingPersistenceManager.java
platform/osgi/platform-osgi-configadmin/src/test/java/org/codice/felix/cm/file/EncryptingPersistenceManagerTest.java
platform/security/encryption/platform-security-encryption-api/pom.xml
platform/security/encryption/platform-security-encryption-commands/src/test/java/ddf/security/command/EncryptCommandTest.java
platform/security/encryption/platform-security-encryption-crypter/pom.xml
platform/security/encryption/platform-security-encryption-crypter/src/main/java/ddf/security/encryption/crypter/Crypter.java
platform/security/encryption/platform-security-encryption-crypter/src/test/java/ddf/security/encryption/crypter/CrypterTest.java
platform/security/encryption/platform-security-encryption-impl/pom.xml
platform/security/encryption/platform-security-encryption-impl/src/main/java/ddf/security/encryption/impl/EncryptionServiceImpl.java
platform/security/encryption/platform-security-encryption-impl/src/test/java/ddf/security/encryption/impl/EncryptionServiceImplTest.java
platform/security/encryption/pom.xml
platform/security/idp/security-idp-client/src/main/java/org/codice/ddf/security/idp/client/IdpLogoutActionProvider.java
platform/security/idp/security-idp-client/src/test/java/org/codice/ddf/security/idp/client/IdpLogoutActionProviderTest.java
platform/security/platform-security-core-api/src/main/java/ddf/security/SecurityConstants.java
pom.xml

```
pom.xml
distribution\docs\src\main\resources\content\_dependencyList\ddf-dependency-list.adoc
distribution\docs\src\main\resources\content\_securityFramework\security-encryption-intro.adoc
```
- Teams tagged
Link to 2.13.x PR: https://github.com/codice/ddf/pull/4339
Replaces keyczar with tink.
@blen-desta 
@brjeter 
@coyotesqrl 
@stustison 
See test steps on 2.13.x PR.
Fixes: #4275 …

DDF-04275 Replace keyczar with tink

---

Jenkinsfile

Adds a step to start a docker daemon to the Setup stage of the pipeline
@mcalcote @LinkMJB 
@codice/build 
@clockard @vinamartin 
[DDF-4331](https://codice.atlassian.net/browse/DDF-4331) …

DDF-4331 Add dockerd to pipepline

---

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/config/ConfigurationApplication.java
catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.xml
catalog/ui/search-ui-app/src/main/resources/etc/org.codice.ddf.catalog.ui.config
distribution/docs/src/main/resources/content/_reference/_tables/catalog.ui.config.adoc
ui/packages/catalog-ui-search/src/main/webapp/react-component/container/table-export/table-export.tsx
ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/table-export/table-export.tsx

Adding `Export Result Limit` to the `Catalog Search UI` config.
Updating table-export.tsx to add a third option to the `Export Results` drop down menus, `Exact Number`
An input box will be displayed when this option is selected.
The user can enter a number of records to export. This value will be checked against the new `Export Result Limit` as well as the total number of results returned by the query.
A warning message will be displayed if the user tries to export a number greater than the `Export Result Limit` and the download button will be disabled.
This PR adds the ability to export a custom number of results from the `Export Results` dialog.
An `Export Result Limit` is being added to the `Catalog Search UI` config page in `Admin UI`
@jrnorth @djblue @adimka @zta6 @middlets719 …

DDF-04397 Allow user to specify number or results to export

---

ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-old.view.js
ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-serialization.js
ui/packages/catalog-ui-search/src/main/webapp/plugins/location-serialization.js

Adding Plugin support to the serializing and deserializing of the location model to allow new search types to be added and still preserve user query selects on reloads
@Schachte @zta6 @gordocanchola @adimka 
@codice/ui 
@bdeining
@djblue
Ingest Gazetteer information with `gazetteer:update "$ddf.data/countries.geo.json"`
Regression test Query Preservation:
Create and save separate location search with each of the following types, Lines, Polygon, Point, BBox, and Keyword.  
Reopen each search and verify the location information is the same as when it was saved.
For Jira:
For GH Issues:
Fixes: #4445 ____ …

DDF-4445 Add Plugin support for location serialization

---

catalog/transformer/catalog-transformer-csv-queryresponse/src/main/java/ddf/catalog/transformer/csv/CsvMetacardTransformer.java
catalog/transformer/catalog-transformer-csv-queryresponse/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/transformer/catalog-transformer-csv-queryresponse/src/test/java/ddf/catalog/transformer/csv/CsvMetacardTransformerTest.java

Takes a single result metacard from a search and allows it to be exported as a .csv file.
@bellcc 
@derekwilhelm 
@jlcsmith 
Upload any file and then export result as CSV. You should receive a .csv file and open the file to check that the attribute names and values were processed correctly.
Fixes: #4398  …

DDF-04398 Add backend support for CSV export to DDF

---

ui/packages/catalog-ui-search/src/main/webapp/react-component/container/sharing/sharing.tsx

Prevents users from overriding the workspace sharing settings if another user has made changes since the page was loaded. When workspace settings are saved, a request is made to fetch the latest workspace state. If the state is the same, then we allow the changes. Otherwise, we tell the user they must refresh the page and to fetch the latest changes.
@codice/ui 
@djblue @willwill96 @gjvera @rymach 
@bdeining
Create a new workspace and open the workspace sharing settings. Open another tab and open the workspace sharing settings for the same workspace. Change the permissions in the first tab and click `Apply`. The settings should be saved successfully. Now change the settings in the second tab and click `Apply'. The settings should fail to be saved and you should see the …

DDF-04383 Prevent users from overriding the workspace sharing settings if another user has made changes

---

ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/map.less
ui/packages/catalog-ui-search/src/main/webapp/react-component/button/split-button/index.tsx
ui/packages/catalog-ui-search/src/main/webapp/react-component/button/split-button/zoomToHome.tsx

- Updates the Home button to look more like an actual button paired with its dropdown.
- Other miscellaneous CSS fixes 
@BernardIgiri 
@willwill96 
@gjvera 
@djblue 
@rymach 
@codice/ui 
@bdeining
Verify toolbar functionality works as expected and looks good with different zoom levels, screen sizes, spacing, and themes
For Jira:
For GH Issues:
Fixes: #4448 
Old
New …

DDF-04448 Gazetteer Home button cleanup

---

ui/packages/catalog-ui-search/src/main/webapp/component/ingest-details/ingest-details.view.js

Fixes the fractions that would sometimes show up incorrectly when uploading files.
@bellcc 
@jlcsmith 
* First upload any number of files in the uploader (ie. 2 files)
* Hit the clear button
* Then upload any number of files again (ie. 1 file)
* Hit the start button
* Ensure that the fraction displayed when uploading never exceeds 100%
For Jira:
For GH Issues:
Fixes: #4395 ____ …

DDF-04395 Fixes fraction displayed when uploading

---

ui/README.md
ui/path.sh

@adimka 
@bdeining
- Uninstall node and yarn
- Pull down PR
- Source path.sh
- Ensure node and yarn versions are correct
For GH Issues:
Fixes: #4441

DDF-04441 Adds ui/path.sh to easily use maven's yarn / node

---

catalog/ui/catalog-ui-search/pom.xml
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/forms/SearchFormsApplication.java
catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/forms/SearchFormsApplicationTest.java
catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/forms/SearchFormsSymbolsIT.java
catalog/ui/catalog-ui-search/src/test/resources/forms/app/form-filter-simple.xml
catalog/ui/catalog-ui-search/src/test/resources/forms/app/form-simple-response.json
catalog/ui/catalog-ui-search/src/test/resources/forms/app/form-simple.json
catalog/ui/catalog-ui-search/src/test/resources/forms/app/inline-xml.xslt
catalog/ui/catalog-ui-search/src/test/resources/log4j.properties

Adds regression tests for search forms. The boundaries are REST (HTTP/network) <--> Catalog Framework. 
@middlets719 
@Schachte 
@samuelechu 
@BernardIgiri 
@codice/test 
@bdeining 
@troymohl
Full build should be sufficient. Only new tests are added. 
Users would build forms with search terms that included JSON symbols. Creation would succeed but retrieving the forms resulted in bad JSON being returned. This issue has since been fixed but this set of tests should ensure all symbols are supported going forward. 
[DDF-4402](https://codice.atlassian.net/browse/DDF-4402)
- ✏️ …

DDF-4402 Adds JSON regression tests for search forms

---

catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.facetwhitelist.xml
distribution/docs/src/main/resources/content/_reference/_tables/AttributeSuggestionsWhitelist.adoc

Adds documentation for the [faceting autocomplete PR](https://github.com/codice/ddf/pull/4409)
@gjvera 
@djblue 
@bdeining 
Build / Install / Make sure documentation regarding `Attribute Suggestion Whitelist` is present in the documentation that gets generated (can be viewed for admin console)
For Jira:
For GH Issues:
Fixes: #4408 
What the docs look like: 
Screenshot of the feature in question (autocomplete):  …

DDF-04408 Add Documentation for Faceting Autocomplete

---

distribution/docs/src/main/resources/content/_integrating/_endpoints/catalog-rest-endpoint.adoc

Revised Draft of the integrator's documentation for the Catalog REST endpoint. 
@bakejeyner @austinsteffes @garrettfreibott 
@codice/docs 
@brjeter
@clockard
@lessarderic
@shaundmorris
- review content.
- builds successfully 
This will set an example for style, ordering, and content in documenting future endpoints. 
For GH Issues:
Improves: #4374 
[catalog-rest-ep.zip](https://github.com/codice/ddf/files/2886664/catalog-rest-ep.zip) …

DDF-04374 updated docs for catalog rest endpoint

---

README.md

@shaundmorris @rzwiefel @bdeining @coyotesqrl

DDF-0000 Removes Gitter badge from README.md

---

catalog/spatial/wfs/1.0.0/spatial-wfs-v1_0_0-source/pom.xml
catalog/spatial/wfs/1.0.0/spatial-wfs-v1_0_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v1_0_0/catalog/source/WfsSource.java
catalog/spatial/wfs/1.0.0/spatial-wfs-v1_0_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v1_0_0/catalog/source/WfsSourceTest.java
catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/pom.xml
catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsSource.java
catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsSourceTest.java
catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/pom.xml
catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/source/WfsSource.java
catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/source/WfsSourceTest.java

Link to 2.13.x PR: #4490 
@leo-sakh 
@codice/io 
@bdeining
@troymohl
For GH Issues:
Fixes: #4486

DDF-04486 Enforce the WFS sources' configured connect and receive timeouts

---

catalog/core/catalog-core-directorymonitor/pom.xml
catalog/core/catalog-core-directorymonitor/src/test/java/org/codice/ddf/catalog/content/monitor/ContentDirectoryMonitorIT.java
catalog/core/catalog-core-directorymonitor/src/test/java/org/codice/ddf/catalog/content/monitor/features/TinkFeatures.java
catalog/core/catalog-core-localstorageprovider/pom.xml
catalog/core/catalog-core-localstorageprovider/src/main/java/org/codice/ddf/catalog/content/impl/FileSystemStorageProvider.java
catalog/core/catalog-core-localstorageprovider/src/test/java/org/codice/ddf/catalog/content/impl/FileSystemStorageProviderTest.java
catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/DeleteOperations.java
distribution/ddf-common/src/main/resources-filtered/etc/custom.properties
distribution/ddf-common/src/main/resources/security/default.policy
features/security/pom.xml
features/security/src/main/feature/feature.xml
features/test-utilities/src/main/feature/feature.xml
platform/osgi/platform-osgi-configadmin/src/main/java/org/codice/felix/cm/file/EncryptingPersistenceManager.java
platform/security/encryption/platform-security-encryption-crypter/pom.xml
platform/security/encryption/platform-security-encryption-crypter/src/main/java/ddf/security/encryption/crypter/Crypter.java
platform/security/encryption/platform-security-encryption-crypter/src/test/java/ddf/security/encryption/crypter/CrypterTest.java

Updates the `FileSystemStorageProvider` to encrypt the content it writes to disk.
@blen-desta 
@stustison 
1. Build DDF and install the standard profile.
1. Ingest a resource using Intrigue.
1. Query for that resource using Intrigue.
1. Verify that the result looks normal
1. Check for a thumbnail (if applicable)
1. Verify all of the `Actions` in the `Inspector` tab work, especially the `resource` action.
1. Verify that the content is encrypted on disk
1. Navigate to `<DDF_HOME>/data/content/store/{first 3 characters of id}/{next three characters of id}/{id}`, and verify that you cannot open the resource.
1. Verify that the new keysets have been generated.
1. Navigate to the keyset directory under `<DDF_HOME>/etc/keysets`
1. Verify that there are 6 total …

[2.13.x] DDF-4457 Encrypt file system storage

---

catalog/catalog-app/src/main/resources/features.xml
catalog/core/catalog-core-directorymonitor/pom.xml
catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/AbstractDurableFileConsumer.java
catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/AsyncFileAlterationListener.java
catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/AsyncFileAlterationObserver.java
catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/AsyncFileEntry.java
catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/DurableFileAlterationListener.java
catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/DurableFileSystemFileConsumer.java
catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/DurableWebDavFileConsumer.java
catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/FileSystemPersistenceProvider.java
catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/JsonPersistantStore.java
catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/ObjectPersistentStore.java
catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/synchronizations/CompletionSynchronization.java
catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/synchronizations/LoggingSynchronization.java
catalog/core/catalog-core-directorymonitor/src/test/java/org/codice/ddf/catalog/content/monitor/AsyncFileAlterationObserverTest.java

Link to 2.13.x PR: #4223 
____
@vinamartin @lessarderic @clockard @kcover @peterhuffer 

DDF-4424 Updating the CDM (in-place) to update the observer state only on a successful ingest to the catalog framework

---

distribution/docs/pom.xml
distribution/docs/src/main/resources/content/_integrating/_endpoints/csw-endpoint.adoc

Revision of integrator's documentation for CSW endpoint. 
@bakejeyner @garrettfreibott @blen-desta @austinsteffes 
@codice/docs 
@brjeter
@clockard
@lessarderic
@shaundmorris
review content, verify build is successful, & tests pass
For GH Issues:
contributes to: #4374
[csw-docs.zip](https://github.com/codice/ddf/files/2957843/csw-docs.zip) …

DDF-04374 updated docs for CSW endpoint

---

ui/packages/catalog-ui-search/src/main/webapp/component/search-form/search-form.view.js
ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/workspace-item/workspace-item.tsx

Fixes an issue where e-mails were overflowing off of search/result forms.
Also, changes workspaces' e-mails overflow to use ellipses instead of ending abruptly at the end of the card
Adds a title property to the containing DOM elements so that the full e-mail can be viewed by hovering over it if needed.
See screenshots for more details.
@gjvera 
@rymach 
@bdeining
@djblue
1. Quickbuild and unzip
2. Before starting up DDF, go to the etc/users.attributes file and change the e-mail to be longer
3. Start up DDF and verify nothing looks strange on the workspaces/search forms/result forms pages
For Jira:
For GH Issues:
Fixes: #4515 
Workspaces:
Search/Result Forms: …

DDF-04515 Fix Search Form Email Overflow Issue

---

distribution/docs/src/main/resources/content/_integrating/_endpoints/opensearch-endpoint.adoc

updates the integrator's documentation for the OpenSearch endpoint. 
@bakejeyner @austinsteffes @garrettfreibott @blen-desta 
@codice/docs 
@brjeter
@clockard
@lessarderic
@ryeats
@rzwiefel
@shaundmorris
review content changes, builds successfully, and tests pass
For GH Issues:
Contributes to : #4374  …

DDF-04374 updated integrator documentation for the OpenSearch endpoint

---

catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/AsyncFileAlterationObserver.java
catalog/core/catalog-core-directorymonitor/src/test/java/org/codice/ddf/catalog/content/monitor/AsyncFileAlterationObserverTest.java

Fixes a unit tests with the CDM that was flakey on slower machines.
@peterhuffer @kcover 
@codice/io 
@codice/test 
@lessarderic @clockard @vinamartin 
CI should cover all these changes
For Jira:
[DDF-4424](https://codice.atlassian.net/browse/DDF-4424)
For GH Issues:
Fixes: #____ …

[2.13.x] DDF-4424 Increasing CDM unit test reliability on slower machines.

---

Jenkinsfile

Bypasses the windows stages in the Jenkinsfile to avoid current pipeline issue.
@codice/build 
@LinkMJB 
@clockard 
@brjeter 
@blen-desta 
@shaundmorris  …

DDF-4005 Commenting out Windows build path until pipeline issues can be resolved.

---

Jenkinsfile

Bypasses the windows stages in the Jenkinsfile to avoid current pipeline issue.
@codice/build 
@LinkMJB 
@clockard 
@brjeter 
@blen-desta 
@shaundmorris  …

(2.14.X) DDF-4005 Commenting out Windows build path until pipeline issues can be resolved

---

Jenkinsfile

Bypasses the windows stages in the Jenkinsfile to avoid current pipeline issue.
@codice/build 
@LinkMJB 
@clockard 
@brjeter 
@blen-desta 
@shaundmorris  …

(2.13.X) DDF-4005 Commenting out Windows build path until pipeline issues can be resolved.

---

catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/AsyncFileAlterationObserver.java

- Teams tagged
Link to 2.13.x PR: #4514
____
This is a port of a change that Patrick blocked #4514 on. It's a straight 3 line cherry-pick
@jhunzik @kcover @peterhuffer 
@codice/io 
@clockard @lessarderic @paouelle  …

DDF-4424 CDM ensuring variables modified within locks are always modified within locks

---

pom.xml

**NOTE: This change should go into master only**
Upgrades the version of bouncy castle in order to mitigate the CVE's mentioned [here](https://www.cvedetails.com/vulnerability-list/vendor_id-7637/Bouncycastle.html).
@blen-desta 
@Kjames5269 
@stustison 
Since `BouncyCastle` is used almost everywhere there is security, a general security smoke test should be performed. And since a "general security smoke test" isn't a thing, here are some steps you can try out:
1. Build and install DDF.
1. Log into the admin console.
1. Logout.
1. Log into Intrigue.
1. Ingest a resource.
1. Query for that resource.
1. Verify the resource looks correct.
1. In the Karaf console, run `security:encrypt <value>` where `<value>` is an arbitrary string of your choice. Verify that the value is …

DDF-4555 Upgrade bouncy castle

---

platform/admin/core/admin-core-impl/src/main/java/org/codice/ddf/admin/core/impl/SystemPropertiesAdmin.java
platform/admin/core/admin-core-impl/src/test/java/org/codice/ddf/admin/core/impl/SystemPropertiesAdminTest.java
platform/admin/core/admin-core-impl/src/test/resources/custom.system.properties

Fixes an issue where the installer would overwrite the solr password after it had already been set earlier on in the install process. 
@ahoffer @Kjames5269 @jhunzik 
@emmberk
Run through the installer and hit restart now at the end.
Open DDF and verify that Intrigue starts up. 
Look at custom.system.properties and verify that the solr.password is some encrypted password.
This PR (https://github.com/codice/ddf/pull/4429) introduced the issue by frontloading the read of the system properties file which makes it fall out of sync after the solr properties are updated.
I've refactored it to read every time these methods are called to ensure it doesn't fall out of sync.
Fixes: #4570
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/P …

[2.14.x] Fixes bug where installer would overwrite the solr password

---

ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/visualization-selector/visualization-selector.js

Fix styling regression that was a result of #4503 
@codice/ui 
For Jira:
For GH Issues:
Fixes: #4485 
regression
fix …

DDF-04485 fixing styling regression

---

platform/admin/core/admin-core-impl/src/main/java/org/codice/ddf/admin/core/impl/SystemPropertiesAdmin.java
platform/admin/core/admin-core-impl/src/test/java/org/codice/ddf/admin/core/impl/SystemPropertiesAdminTest.java
platform/admin/core/admin-core-impl/src/test/resources/custom.system.properties

Fixes an issue where the installer would overwrite the solr password after it had already been set earlier on in the install process. 
@ahoffer @Kjames5269 @jhunzik 
@emmberk
Run through the installer and hit restart now at the end.
Open DDF and verify that Intrigue starts up. 
Look at custom.system.properties and verify that the solr.password is some encrypted password.
This PR (https://github.com/codice/ddf/pull/4429) introduced the issue by frontloading the read of the system properties file which makes it fall out of sync after the solr properties are updated.
I've refactored it to read every time these methods are called to ensure it doesn't fall out of sync.
Fixes: #4570
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/P …

DDF-4570 Fixes installer overriding solr password

---

platform/admin/core/admin-core-impl/src/main/java/org/codice/ddf/admin/core/impl/SystemPropertiesAdmin.java
platform/admin/core/admin-core-impl/src/test/java/org/codice/ddf/admin/core/impl/SystemPropertiesAdminTest.java
platform/admin/core/admin-core-impl/src/test/resources/custom.system.properties

Fixes an issue where the installer would overwrite the solr password after it had already been set earlier on in the install process. 
@ahoffer @Kjames5269 @jhunzik 
@emmberk
Run through the installer and hit restart now at the end.
Open DDF and verify that Intrigue starts up. 
Look at custom.system.properties and verify that the solr.password is some encrypted password.
This PR (https://github.com/codice/ddf/pull/4429) introduced the issue by frontloading the read of the system properties file which makes it fall out of sync after the solr properties are updated.
I've refactored it to read every time these methods are called to ensure it doesn't fall out of sync.
Fixes: #4570
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/P …

[2.13.x] DDF-4570 Fixes installer overriding solr password

---

catalog/core/catalog-core-directorymonitor/pom.xml
catalog/core/catalog-core-directorymonitor/src/test/java/org/codice/ddf/catalog/content/monitor/ContentDirectoryMonitorIT.java
catalog/core/catalog-core-directorymonitor/src/test/java/org/codice/ddf/catalog/content/monitor/features/TinkFeatures.java
catalog/core/catalog-core-localstorageprovider/pom.xml
catalog/core/catalog-core-localstorageprovider/src/main/java/org/codice/ddf/catalog/content/impl/FileSystemStorageProvider.java
catalog/core/catalog-core-localstorageprovider/src/test/java/org/codice/ddf/catalog/content/impl/FileSystemStorageProviderTest.java
catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/DeleteOperations.java
distribution/ddf-common/src/main/resources-filtered/etc/custom.properties
distribution/ddf-common/src/main/resources/security/default.policy
features/security/pom.xml
features/test-utilities/pom.xml
features/test-utilities/src/main/feature/feature.xml
platform/osgi/platform-osgi-configadmin/src/main/java/org/codice/felix/cm/file/EncryptingPersistenceManager.java
platform/security/encryption/platform-security-encryption-crypter/pom.xml
platform/security/encryption/platform-security-encryption-crypter/src/main/java/ddf/security/encryption/crypter/Crypter.java
platform/security/encryption/platform-security-encryption-crypter/src/test/java/ddf/security/encryption/crypter/CrypterTest.java

**NOTE: This is a straight cherry-pick of [the 2.13.x PR](https://github.com/codice/ddf/pull/4502)**
- Teams tagged
Link to 2.13.x PR: #4502
____
Updates the `FileSystemStorageProvider` to encrypt the content it writes to disk.
@blen-desta 
@coyotesqrl 
@stustison 
For Jira:
[DDF-4457](https://codice.atlassian.net/browse/DDF-4457) …

DDF-4457 Encrypt file system storage

---

ui/packages/catalog-ui-search/src/main/webapp/component/input/date/input-date.view.js

Sets the time value to 00:00:00 when the user changes the date in the date picker.
@Bdthomson 
@hayleynorton 
@andrewzimmer 
@codice/ui 
@bdeining 
@djblue
1. In the catalog UI, create a query 
2. Choose a date attribute to search on (ex: created), and click the calendar button to open the date picker
3. Verify that the date and time are set to the current time before selecting a date
4. Choose a date in the date picker calendar, and verify that the time is changed to 00:00:00
For GH Issues:
Fixes: #4559  …

DDF-04559 Defaulting time to 00:00:00 when changing date in date picker

---

pom.xml

Upgrades the version of the third party tika bundle to avoid Jackson CVEs.
@blen-desta
@stustison
@vinamartin
1. [Build this branch of `third-party`](https://github.com/codice/thirdparty/pull/30)
1. Build this branch of DDF.
1. Build + standard install Alliance `1.1.x`, making sure that the `ddf.version` in Alliance's root pom is `2.13.7-SNAPSHOT`.
1. In `Admin Console -> All -> Features`, install `MpegtsInputTransformer` and `MpegtsStreaming`.
1. On the karaf command line, run `catalog:ingest -t mpegts <path_to_ts_file>`, where `<path_to_ts_file>` is a path to an `mpegts` file. Message me if an mpegts file is needed. The resource should ingest without error.
1. Through Intrigue, ingest a PDF. It should ingest without error.
Fixes: #4543 …

DDF-04543 Upgrade tika bundle version

---

ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/user-notifications/user-notifications.js

As a result of #4484, user notifications flicker upon deletion. 
@codice/ui 
@djblue 
perform some actions that create notifications (e.g upload data)
ensure no abnormalities or regressions in the user-notification component
For Jira:
For GH Issues:
Fixes: #4483  …

DDF-04483 fixing flickering user-notifications

---

ui/packages/catalog-ui-search/src/main/webapp/react-component/container/loading-companion/loading-companion.tsx
ui/packages/catalog-ui-search/src/main/webapp/react-component/container/metacard-archive/metacard-archive.tsx

Fixes bug in metacard-archive tab that prevented the loading view from displaying after the archive button is clicked.
Also adds an error message to restore
@adimka 
@Bdthomson 
@hayleynorton 
@codice/ui 
@bdeining
@djblue
- Ingest some data
- in the inspector, archive the result
- verify that the loading view displays
- verify an error message appears when attempting to restore
For Jira:
For GH Issues:
Fixes: #4498  …

DDF-04498 Migrate metacard-archive to react, loading bug fix

---

ui/packages/catalog-ui-search/src/main/webapp/component/input/date/input-date.view.js

Fixes bug introduced in https://github.com/codice/ddf/pull/4560 causing queries on date attributes to fail due to CQL parsing issues
@willwill96 @gjvera @adimka @nsuvarna 
@bdeining
@djblue
1. Ingest some data
2. Run a query with a date attribute like `Date Created`
3. Verify the outgoing CQL is correct and results are returned as expected
For Jira:
For GH Issues:
Fixes: #4586  …

DDF-4586 Fix date queries

---

ui/packages/catalog-ui-search/src/main/webapp/styles/components/list.less

Adds a right border to result items to avoid the appearance of results being cut off by the edge of the results pane
@andrewzimmer @Bdthomson 
@djblue
Verify that there's a border on the right side of each result that matches the styling of the top and bottom borders
Fixes: #4604  …

DDF-4604 Added right border to result items

---

ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/card/card.tsx

@samuelechu @zta6 @brianfelix 
@djblue
@vinamartin
For GH Issues:
Fixes: #4598 

DDF-4598 Add onClick support to card.tsx

---

catalog/core/catalog-core-camelcomponent/src/main/java/ddf/camel/component/catalog/framework/FrameworkProducer.java
catalog/core/catalog-core-camelcomponent/src/test/java/ddf/camel/component/catalog/CatalogComponentFrameworkTest.java
catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/AsyncFileEntry.java
catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/FileTypeAdapter.java
catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/JsonPersistantStore.java
distribution/docs/src/main/resources/content/_catalogFrameworks/catalog-framework-camel-component.adoc

Fixes a bug in CDM in which files fail to be ingested after the system restarts.
@peterhuffer @brjeter @kcover @clockard @lessarderic @jhunzik 
@codice/io 
Start CDM
Ingest a couple products.
Shutdown DDF
Create, update and delete a file from the monitored directory.
Start DDF.
Ensure all files are successfully ingested after CDM starts.
For Jira:
[DDF-4424](https://codice.atlassian.net/browse/DDF-4424)
For GH Issues:
Fixes: #____ …

[2.13.x]DDF-4424 CDM fixing an issue with json deserialization and updating state when the catalog is not up.

---

dependency-check-maven-config.xml

This PR suppresses a false positive [CVE reported against hadoop](https://nvd.nist.gov/vuln/detail/CVE-2018-11766). The `solr-core` artifact was pulling in this dependency, however we do not use hadoop in our solr use case. Hence the suppression of the CVE.
Passes CI.
@ahoffer 
@blen-desta 
@brjeter 
@pklinef 
@stustison 
Fixes: #4612  …

[2.13.x] DDF-4612 Suppress solr hadoop cve

---

.github/PULL_REQUEST_TEMPLATE

This reverts commit 45437f3606fb28c27aad9aa6bea7b4a9226e00f6.
For GH Issues:
Fixes: #____
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codice/ddf/4632)

Revert "Updated PULL_REQUEST_TEMPLATE"

---

catalog/core/catalog-core-localstorageprovider/src/main/java/org/codice/ddf/catalog/content/impl/FileSystemStorageProvider.java
platform/security/encryption/platform-security-encryption-crypter/src/main/java/ddf/security/encryption/crypter/Crypter.java

Fixes a bug introduced by #4502.
The file system encryption PR changed what was getting returned on ingest. Originally, the response would contain an input stream + size containing the plaintext content. However, due to the file system encryption changes, the response contains the **encrypted** input stream + size. This was breaking downstream tests that were expecting the plaintext input stream + size to be returned.
The PR also had an issue with writing encrypted resources. The chunk size was 128 and **every** write would result in 128 bytes being written, even if the original resource didn't have 128 bytes left.
@ahoffer 
@blen-desta 
@brjeter 
@stustison 
1. Build this DDF branch
1. Build Alliance `1.1.x` (make sure the DDF version in Alliance `1.1.X` is …

[2.13.x hotfix] DDF-4457-hotfix Fix file system encryption issues

---

dependency-check-maven-config.xml

- Teams tagged
Link to 2.13.x PR: #4618
____
This PR suppresses a false positive [CVE reported against hadoop](https://nvd.nist.gov/vuln/detail/CVE-2018-11766). The `solr-core` artifact was pulling in this dependency, however we do not use hadoop in our solr use case. Hence the suppression of the CVE.
Passes CI.
@ahoffer 
@blen-desta 
@brjeter 
@pklinef 
@stustison 
Fixes: #4612 
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71 …

DDF-4612 Suppress solr hadoop cve

---

catalog/rest/catalog-rest-impl/pom.xml

Exposed REST service to be used downstream
@jrnorth
@troymohl
CI
For Jira:
For GH Issues:
Fixes: #4627 

DDF-04627 Exposed REST service to be used downstream

---

catalog/core/catalog-core-solr/pom.xml
catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/SolrMetacardClientImpl.java
catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/SolrMetacardClientImplTest.java

This allows for the solrconfigs that enable spellcheck and it's suggestions to take effect. Therefore, if you have the spellcheck solr configurations, you will now get results back even if you misspell data. This feature is useful for downstream projects that have a spellcheck requirement.
@derekwilhelm 
@bellcc 
@rececoffin 
@glenhein 
@ethantmanns 
@rzwiefel 
@ethantmanns
@rzwiefel
Contact @cantstoptheunk to provide you the necessary config files for solr.
Ingest data and then misspell searches on different fields in Intrigue and you should get results back unless the search term is completely different from what is in the data.
`https://github.com/codice/ddf/issues/4597` …

DDF-4597 Added backend capability to re-query off spellcheck suggestions

---

catalog/core/catalog-core-localstorageprovider/src/main/java/org/codice/ddf/catalog/content/impl/FileSystemStorageProvider.java
platform/security/encryption/platform-security-encryption-crypter/src/main/java/ddf/security/encryption/crypter/Crypter.java

- Fixes issues with encrypted input stream breaking downstream tests
- Fixes issues with writing encrypted resources
- Teams tagged
Link to 2.13.x PR: #4607 
____
Fixes a bug introduced by #4502.
The file system encryption PR changed what was getting returned on ingest. Originally, the response would contain an input stream + size containing the plaintext content. However, due to the file system encryption changes, the response contains the **encrypted** input stream + size. This was …

[hotfix] DDF-4457-hotfix Fixes file system encryption issues introduced by #4502 (#4633)

---

distribution/docs/src/main/resources/content/_running/editing-attributes.adoc
distribution/docs/src/main/resources/content/_running/injecting-attributes.adoc
distribution/docs/src/main/resources/content/_running/overriding-attributes.adoc
distribution/docs/src/main/resources/content/_running/validator-plugins.adoc
distribution/docs/src/main/resources/content/_running/viewing-invalid.adoc

Updates doc order for downstream 
@jhunzik 
@brjeter
Build successful 
Updates doc ordering for downstream
Fixes: #4548  …

[2.13.x]DDF-4548 Update docs for enforced validator plugin 

---

ui/packages/catalog-ui-search/src/main/webapp/js/model/Workspace.collection.js
ui/packages/catalog-ui-search/src/main/webapp/react-component/container/workspaces-templates-container/workspaces-templates-container.tsx

Removes parsing for user-entered cql in the Workspaces homepage search bar. This functionality was not needed, and removing it fixes an issue where running a query with parsing errors from the Workspaces page creates a workspace that can't be opened.
@Bdthomson @andrewzimmer @hayleynorton @Schachte
@codice/ui 
@bdeining 
@djblue 
@rzwiefel 
1. Go to the Workspaces page in the ui
2. Enter a query like: `"anyText" ILIKE 'Q'` in the search bar (the quote mixing leads to a parsing error)
3. Ensure that the workspace is created and can be opened normally. A query for the text entered in step 2 should be in the workspace (not parsed as actual cql)
For GH Issues:
Fixes: #4623 
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Re …

DDF-4623 Preventing workspaces from being created from unparsable queries

---

catalog/ui/catalog-ui-search/README.md
catalog/ui/catalog-ui-search/pom.xml
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/config/ConfigurationApplication.java
catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/blueprint/consumes.xml
catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/blueprint/endpoints.xml
catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/blueprint/provides.xml

Arranges the Catalog UI Search wiring to be organized by (1) coupling levels to DDF mapped to files, and (2) files arranged by app or feature. 
Future changes will now clearly reveal if the UI's coupling to DDF is increasing or decreasing. 
@rymach 
@gjvera 
@codice/ui 
@djblue 
@rzwiefel 
Verify the system starts up, there are no errors in the logs, there are no errors on bundle refresh, and Intrigue is working as expected:
1. Verify the ability to create, edit, and delete workspaces. 
1. Verify the ability to query the system (if one query succeeds, the app is wired together correctly).
1. Verify the ability to create, edit, and delete search forms.
1. Verify the ability to share a workspace or search form. 
1. Verify the ability to use Intrigue's uploader: upload any …

DDF-4606 Clean up blueprint definitions for Catalog UI Search

---

ui/packages/catalog-ui-search/src/main/webapp/component/query-add/query-add.view.js
ui/packages/catalog-ui-search/src/main/webapp/component/query-advanced/query-advanced.view.js
ui/packages/catalog-ui-search/src/main/webapp/component/search-form-list/search-form-list.view.js

Fixes bug where users could not switch to another search form if they have a default configured
@willwill96 @gjvera @rymach @Lambeaux 
@bdeining
@djblue
- Click "Search DDF Intrigue"
- Verify text search is selected by default
- Create some new search forms
- Verify you can switch between the different search forms
- Make one of the search forms your default
- Refresh the page
- Verify the default form is now shown after clicking "Search DDF Intrigue"
- Switch to another form
- Verify the new form is correctly populated
- Run and save the search. Click the edit button (pencil) on the search and verify it is correct
- Refresh the page
- Find a search in the dropdown list and click the edit button (pencil). Verify it is still correct.
- Ensure all other search form functionality still works …

DDF-04647 Fix bug preventing users from changing search forms

---

catalog/plugin/catalog-plugin-metacardbackup-s3storage/pom.xml
catalog/plugin/catalog-plugin-metacardbackup-s3storage/src/main/java/org/codice/ddf/catalog/plugin/metacard/backup/storage/s3storage/DeleteBean.java
catalog/plugin/catalog-plugin-metacardbackup-s3storage/src/main/java/org/codice/ddf/catalog/plugin/metacard/backup/storage/s3storage/MetacardS3StorageRoute.java
catalog/plugin/catalog-plugin-metacardbackup-storage-common/src/main/java/org/codice/ddf/catalog/plugin/metacard/backup/common/MetacardStorageRoute.java
catalog/plugin/catalog-plugin-metacardbackup-storage-common/src/test/java/org/codice/ddf/catalog/plugin/metacard/backup/common/MetacardStorageRouteTest.java

Implements deleting metadata from S3.
@Corey-Collins  
@brianfelix  
@codice/io 
@bdeining
@jrnorth
Test on system with S3. 
Ingest metadata.
Verify metadata is in S3.
Delete metadata.
Verify metadata has been removed from S3.
[DDF-3492](https://codice.atlassian.net/browse/DDF-3492) …

DDF-3492 Support for deleting metacards from S3

---

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/QueryMetacardApplication.java
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/query/data/metacard/QueryMetacardTypeImpl.java
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/query/data/model/QueryBasic.java
catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/metacard/QueryMetacardApplicationTest.java

- Adds owner, created, and modified attributes to searches
@rececoffin 
@codice/data 
@rzwiefel
- Create a couple of searches through the REST API interface. 
- Verify that they have a created, modified, and owner attribute on them.
None
For GH Issues:
Fixes: #4667  …

DDF-4667 Adds owner, created, and modified attributes to searches

---

catalog/core/catalog-core-camelcomponent/src/main/java/ddf/camel/component/catalog/framework/FrameworkProducer.java
catalog/core/catalog-core-camelcomponent/src/test/java/ddf/camel/component/catalog/CatalogComponentFrameworkTest.java
catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/AsyncFileEntry.java
catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/FileTypeAdapter.java
catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/JsonPersistantStore.java
catalog/core/catalog-core-directorymonitor/src/test/java/org/codice/ddf/catalog/content/monitor/AsyncFileAlterationObserverTest.java
distribution/docs/src/main/resources/content/_architectures/_catalogFrameworks/catalog-framework-camel-component.adoc

- Teams tagged
Link to 2.13.x PRs: #4630 #4617
____
@clockard @peterhuffer @kcover @lessarderic @brjeter @jhunzik 
@codice/io  …

DDF-4424 Fixing CDM issues with GSON deserialization and ingesting when the local catalog is unavailable

---

distribution/docs/src/main/resources/content/_managing/_datamanagement/editing-attributes.adoc
distribution/docs/src/main/resources/content/_managing/_datamanagement/injecting-attributes.adoc
distribution/docs/src/main/resources/content/_managing/_datamanagement/overriding-attributes.adoc
distribution/docs/src/main/resources/content/_managing/_datamanagement/schematron-validation.adoc
distribution/docs/src/main/resources/content/_managing/_datamanagement/viewing-invalid.adoc
distribution/docs/src/main/resources/content/_managing/_running/forms-commands.adoc
distribution/docs/src/main/resources/content/_managing/_running/other-ingest.adoc
distribution/docs/src/main/resources/content/_managing/_running/validator-plugins.adoc

Link to 2.13.x PR: #4564 
@jhunzik 
@codice/docs 
@brjeter
@vinamartin
Build successful
For GH Issues:
Fixes: #4548  …

DDF-4548 Update docs for enforced validator plugin

---

ui/packages/catalog-ui-search/src/main/webapp/react-component/container/loading-companion/loading-companion.tsx

Fixes the loading companion for some components downstream.
Makes it so no functions are called if the component is updated twice in a row
and the loading state is unchanged
@mojogitoverhere @willwill96 
@codice/ui 
@bdeining 
@djblue 
For Jira:
For GH Issues:
Fixes: #4700  …

DDF-04700 fix loading companion

---

platform/platform-paxweb-jettyconfig/src/main/java/org/codice/ddf/security/session/AttributeSharingHashSessionIdManager.java

…expired
Fixes session cleanup
@bdeining
@blen-desta
@brjeter
@coyotesqrl
@millerw8
@pklinef
@stustison
@troymohl
For Jira:
For GH Issues:
Fixes: #____ …

fix issue with sessions not being cleaned up correctly when expired

---

platform/platform-paxweb-jettyconfig/src/main/java/org/codice/ddf/security/session/AttributeSharingHashSessionIdManager.java

…expired (#4711)
(cherry picked from commit e04466f440089f4b9e803d76c479672c9a1d229b)
@blen-desta
@stustison
@troymohl
For Jira:
For GH Issues:
Fixes: #____ …

DDF-4709 fix issue with sessions not being cleaned up correctly when expired

---

ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/map.view.js

Adds a mapLoaded event trigger for when the DDF map is loaded so that actions can be performed on a fully loaded map.
@Schachte 
@adimka 
@zta6  
@codice/ui 
@bdeining
For Jira:
For GH Issues:
Fixes: #4706  …

DDF-04706 Adding mapLoaded event trigger.

---

distribution/ddf-dominion-pax-exam/src/main/java/org/codice/ddf/dominion/pax/exam/options/extensions/InstallDistributionExtension.java
pom.xml

It increases the timeout for installing the standard profile when running a dominion test from 3 minutes to 15 minutes to account for slower environemnt.
Updates codice-test to 0.8
@peterhuffer 
@kcover 
@codice/test 
@AzGoalie
@clockard
[DDF-4454](https://codice.atlassian.net/browse/DDF-4454) …

[2.13.x] DDF-4454 Increased dominion profile installation timeout

---

ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/workspaces-items/workspaces-items.tsx

See original PR that died from neglect: 
https://github.com/codice/ddf/pull/4226
I don't think the moment warning is showing up anymore I won't worry about that part
@AzGoalie
For Jira:
For GH Issues:
Fixes: #____ …

DDF-4469 Address react workspace unique key js warnings in console

---

catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/pom.xml
catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsSource.java
catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/resources/OSGI-INF/metatype/metatype.xml
catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsSourceTest.java
catalog/spatial/wfs/spatial-wfs-common/src/main/java/org/codice/ddf/spatial/ogc/wfs/catalog/common/AbstractWfsSource.java

The WFS 1.1.0 source allows its certificate alias, keystore, and SSL protocol to be configured programmatically but not through the Admin UI because its metatype.xml is missing them. This commit adds those three properties to the metatype.xml so they can be configured in the Admin UI. It also simplifies the refresh logic in the WFS 1.1.0 source so it will reconnect and reconfigure the available WFS features every time instead of having extensive logic to determine whether a reconnect is necessary. Refreshes do not happen frequently and reconnecting and reconfiguring the available WFS features is not that expensive.
@leo-sakh 
@samuelechu 
@glenhein 
@codice/io 
@codice/ogc 
@bdeining
@jlcsmith
1. In the admin console, run `log:set debug …

DDF-4716 Fix WFS 1.1.0 source's metatype.xml

---

catalog/spatial/registry/registry-api/src/main/java/org/codice/ddf/registry/api/internal/RegistryStore.java
distribution/docs/src/main/resources/content/_data/json-definition-intro.adoc
distribution/docs/src/main/resources/content/_sources/registry-store.adoc

Removes the "experimental" tag from components that are not experimental.
@codice/docs 
@brjeter
@clockard
@lessarderic
@mcalcote
@shaundmorris
verify content
For GH Issues:
Fixes: #4722  …

[2.13.X] DDF-4722 removed experimental label in docs

---

distribution/ddf-dominion/src/main/java/org/codice/ddf/dominion/options/DDFOptions.java

It increases the system timeout for for Dominion when running a dominion test in  slower environments.
Follow up to [PR 4710](https://github.com/codice/ddf/pull/4710)
@peterhuffer 
@kcover 
@codice/test 
@AzGoalie
@clockard
[DDF-4454](https://codice.atlassian.net/browse/DDF-4454) …

[2.13.x] DDF-4454 Increased dominion system timeout

---

distribution/docs/src/main/resources/content/_running/catalog-commands.adoc
distribution/docs/src/main/resources/content/_running/data-migration-intro.adoc

adds documentation for the `catalog:import` and `catalog:export` commands.
@codice/docs 
@brjeter
@clockard
@lessarderic
@ryeats
@rzwiefel
@shaundmorris
review new content
For GH Issues:
Fixes: #4724 
- ❗ …

[2.13.X] DDF-4724 documented catalog import and export commands

---

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/QueryMetacardApplication.java
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/query/data/metacard/QueryMetacardTypeImpl.java
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/workspace/transformer/impl/AssociatedQueryMetacardsHandler.java
distribution/docs/src/main/resources/content/_integrating/_endpoints/query-endpoints.adoc

- Provides the ability to order searches based on an attribute and sort order. 
@codice/data 
@ethantmanns
- Test the retrieve all endpoint against default values for `attr` and `sort_by`
- Test the retrieve all endpoint for other attributes. 
- Test the retrieve all endpoint for `asc` and `desc`
- None
For Jira:
For GH Issues:
Fixes: #4689 
None …

DDF-4689 Add backend support for sorting searches

---

ui/packages/catalog-ui-search/src/main/webapp/component/query-status/query-status-row.view.js

translates userql to cql on source name in order to map the characters in source names correctly
@ahoffer @tyler30clemens
@brjeter
Federate to a source with underscores in the source name
Create federated query to All Sources
Run query, then click the heart icon
In the subsequent dropdown, click on the filter icon next to the source with the underscore
Filter is created for source-id with underscores NOT replaced as question marks (e.g. NGA_CL_466 will show up as NGA?CL?466
For Jira:
For GH Issues:
Fixes: #4726
Screenshots
Checklist: …

DDF-4726 translate to cql for source name

---

platform/platform-paxweb-jettyconfig/src/main/java/org/codice/ddf/security/session/AttributeSharingHashSessionIdManager.java
platform/platform-paxweb-jettyconfig/src/main/java/org/codice/ddf/security/session/AttributeSharingSessionDataStore.java
platform/platform-paxweb-jettyconfig/src/main/resources/jetty.xml

Fixes a memory leak. This PR is a cherry pick of a commit that will also be merged to the master branch. See https://github.com/codice/ddf/pull/4740
@brjeter @stustison @clockard @troymohl

DDF-4709 fixed session memory cleanup

---

distribution/docs/src/main/resources/content/_tables/OpenSearchSource.adoc
distribution/docs/src/main/resources/content/_transformers/kml-metacard-xformer.adoc
distribution/docs/src/main/resources/content/_transformers/kml-queryresp-xformer.adoc
distribution/docs/src/main/resources/content/_transformers/kml-style-mapper.adoc

Minor copy edits to documentation files to remove extra characters that cause delays in generating pdf files. 
@austinsteffes @ahoffer @Kjames5269 
@codice/docs 
@brjeter
@clockard
@lessarderic
@shaundmorris
builds successfully. Content changes should be pretty much invisible when rendered. 
this will also eventually enable custom themes for pdfs
For Jira: …

DDF-2824 removed incorrectly encoded characters from documentation.

---

catalog/spatial/registry/registry-api/src/main/java/org/codice/ddf/registry/api/internal/RegistryStore.java
distribution/docs/src/main/resources/content/_developing/_devComponents/json-definition-files.adoc
distribution/docs/src/main/resources/content/_managing/_configuring/_sources/registry-store.adoc

Link to 2.13.x PR: #4723 & #4727
Removes the "experimental" tag from components that are not experimental.
@codice/docs 
@brjeter
@clockard
@lessarderic
@mcalcote
@shaundmorris
verify content
For GH Issues:
Fixes: #4722  …

DDF-4722 removed 'experimental' tag from docs

---

distribution/docs/src/main/resources/content/_managing/_running/catalog-commands.adoc
distribution/docs/src/main/resources/content/_managing/_running/data-migration-intro.adoc

Link to 2.13.x PR: #4724 
adds documentation for the `catalog:import` and `catalog:export` commands.
@codice/docs 
@brjeter
@clockard
@lessarderic
@ryeats
@rzwiefel
@shaundmorris
review new content
For GH Issues:
Fixes: #4724  …

[2.14.X] DDF-4724 documented catalog import and export commands

---

distribution/docs/src/main/resources/content/_managing/_running/catalog-commands.adoc
distribution/docs/src/main/resources/content/_managing/_running/data-migration-intro.adoc

Link to 2.13.x PR: #4725 
adds documentation for the `catalog:import` and `catalog:export` commands.
@codice/docs 
@brjeter
@clockard
@lessarderic
@ryeats
@rzwiefel
@shaundmorris
review new content
For GH Issues:
Fixes: #4724  …

DDF-4724 documented catalog import and export commands

---

Documentation-versions.html
index.html

updates github-pages branch for new 2.13.9 release
@brjeter
@clockard
@lessarderic
@shaundmorris
verify dates & version number
For GH Issues:
#4759  …

DDF-4759 update product website for 2.13.9 release

---

distribution/docs/src/main/resources/content/_architectures/_transformers/kml-metacard-xformer.adoc
distribution/docs/src/main/resources/content/_architectures/_transformers/kml-queryresp-xformer.adoc
distribution/docs/src/main/resources/content/_architectures/_transformers/kml-style-mapper.adoc
distribution/docs/src/main/resources/content/_reference/_tables/OpenSearchSource.adoc

Link to 2.13.x PR: #4744
Minor copy edits to documentation files to remove extra characters that cause delays in generating pdf files. 
@austinsteffes @ahoffer @Kjames5269 
@codice/docs 
@brjeter
@clockard
@lessarderic
@shaundmorris
builds successfully. Content changes should be pretty much invisible when rendered. 
this will also eventually enable custom themes for pdfs
For Jira: …

[2.14.x] DDF-2824 removed incorrectly encoded characters from documentation.

---

catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/SolrMetacardClientImpl.java

Lowers the `GET_BY_ID_LIMIT` constant to prevent DDF from sending urls that are too long to Solr when deleting many records from CSW
@brianfelix 
@samuelechu 
@leo-sakh 
@jrnorth 
@codice/solr 
@bdeining 
@troymohl
Ingest and delete many records (I recommend at least 1000) via csw deletion transaction, ensure that they are deleted and the csw does not return HTTP 400
For GH Issues:
Fixes: #4734  …

DDF-4734 DDF sends urls that are too long to Solr when deleting more than 100 IDs

---

distribution/ddf-common/src/main/resources/security/default.policy

Adds a createClassLoader RuntimePermission to catalog-core-camelcomponent
This was due to a failure for the postingest plugin to deliver a message to camelLogger after performing a csw transaction
@willwill96 
@bellcc 
@bdeining
@jrnorth 
1. Ingest 1+ records
2. Perform a csw deletion
3. Verify you receive the error described in issue #4761 
For GH Issues:
Fixes: #4761  …

DDF-4761 Added createClassLoader permission for catalog-core-camelcomponent

---

distribution/docs/pom.xml
distribution/docs/src/main/resources/templates/architectures.ftl
distribution/docs/src/main/resources/templates/build/integrating.ftl
distribution/docs/src/main/resources/templates/developing.ftl
distribution/docs/src/main/resources/templates/documentation.ftl
distribution/docs/src/main/resources/templates/integrating.ftl
distribution/docs/src/main/resources/templates/managing.ftl
distribution/docs/src/main/resources/templates/metadata.ftl
distribution/docs/src/main/resources/templates/overview.ftl
distribution/docs/src/main/resources/templates/quickstart.ftl
distribution/docs/src/main/resources/templates/reference.ftl
distribution/docs/src/main/resources/templates/using.ftl

Reconfigures the directory structure of the documentation build to include version number to prevent issues on quickbuilds or releases
@codice/build 
@codice/docs 
@brjeter
@clockard
@lessarderic
@mcalcote
- check out `master` branch
- build docs module with `mvn clean install`
- check out this branch
- build docs module with `mvn install` (leave previous build artifacts in target directory)
For GH Issues:
#4703 …

[2.13.x] DDF-4703 updated docs module to add version checking

---

distribution/docs/pom.xml
distribution/docs/src/main/resources/templates/architectures.ftl
distribution/docs/src/main/resources/templates/build/integrating.ftl
distribution/docs/src/main/resources/templates/developing.ftl
distribution/docs/src/main/resources/templates/documentation.ftl
distribution/docs/src/main/resources/templates/integrating.ftl
distribution/docs/src/main/resources/templates/managing.ftl
distribution/docs/src/main/resources/templates/metadata.ftl
distribution/docs/src/main/resources/templates/overview.ftl
distribution/docs/src/main/resources/templates/quickstart.ftl
distribution/docs/src/main/resources/templates/reference.ftl
distribution/docs/src/main/resources/templates/using.ftl

Reconfigures the directory structure of the documentation build to include version number to prevent issues on quickbuilds or releases
@codice/build 
@codice/docs 
@brjeter
@clockard
@lessarderic
@mcalcote
- check out `master` branch
- build docs module with `mvn clean install`
- check out this branch
- build docs module with `mvn install` (leave previous build artifacts in target directory)
For GH Issues:
#4703 …

[2.14.x] DDF-4703 updated docs module to add version checking

---

distribution/docs/pom.xml
distribution/docs/src/main/resources/templates/architectures.ftl
distribution/docs/src/main/resources/templates/build/integrating.ftl
distribution/docs/src/main/resources/templates/developing.ftl
distribution/docs/src/main/resources/templates/documentation.ftl
distribution/docs/src/main/resources/templates/integrating.ftl
distribution/docs/src/main/resources/templates/managing.ftl
distribution/docs/src/main/resources/templates/metadata.ftl
distribution/docs/src/main/resources/templates/overview.ftl
distribution/docs/src/main/resources/templates/quickstart.ftl
distribution/docs/src/main/resources/templates/reference.ftl
distribution/docs/src/main/resources/templates/using.ftl

Reconfigures the directory structure of the documentation build to include version number to prevent issues on quickbuilds or releases
@codice/build 
@codice/docs 
@brjeter
@clockard
@lessarderic
@mcalcote
- check out `master` branch
- build docs module with `mvn clean install`
- check out this branch
- build docs module with `mvn install` (leave previous build artifacts in target directory)
For GH Issues:
#4703 …

DDF-4703 updated docs module to add version checking

---

dependency-check-maven-config.xml

This is blocking https://github.com/codice/ddf/pull/4764
@bakejeyner @tyler30clemens 
@tbatie 
@vinamartin
For GH Issues:
Fixes: #4767 

DDF-04767 Suppress tomcat-embed-jasper CVE-2019-0232

---

distribution/docs/src/main/resources/content/_installing/install-with-zip.adoc
distribution/docs/src/main/resources/content/_introduction/integrating-intro.adoc
distribution/docs/src/main/resources/content/_quickstart/quickstart-installing.adoc

fixes typo that caused `{external-link}` property to render incorrectly in certain spots in the documentation.
@codice/docs 
@clockard
@emmberk
@lessarderic
@mcalcote
@shaundmorris
verify icon image renders instead of text
For Jira: …

[2.13.x] DDF-2824 fixed external link icon typo

---

ui/package.json
ui/packages/admin-core-logviewer/package.json
ui/packages/admin-federation-ui/package.json
ui/packages/admin-metrics-ui/package.json
ui/packages/admin-security-certificate-ui/package.json
ui/packages/broker-undelivered-messages-ui/package.json
ui/packages/catalog-admin-module-layout/package.json
ui/packages/catalog-admin-module-maplayers/package.json
ui/packages/catalog-admin-module-sources/package.json
ui/packages/catalog-ui-search/package.json
ui/packages/cesium-assets/package.json
ui/packages/geowebcache-admin-plugin/package.json
ui/packages/registry-admin-local-ui/package.json
ui/packages/registry-admin-remote-ui/package.json
ui/packages/resourcemanagement-querymonitor-ui/package.json
ui/packages/resourcemanagement-usage-ui/package.json
ui/packages/security-handler-guest/package.json
ui/packages/security-idp-server/package.json
ui/packages/security-servlet-logout/package.json
ui/packages/ui/package.json
ui/yarn.lock

@Bdthomson 
@Lambeaux 
@codice/ui 
@tbatie
CI build
https://github.com/connexta/ace/pull/9
Fixes: #4772

Updates DDF UI to latest version of ace

---

ui/packages/catalog-ui-search/src/main/webapp/component/paging/paging.view.js
ui/packages/catalog-ui-search/src/main/webapp/component/result-selector/result-selector.less
ui/packages/catalog-ui-search/src/main/webapp/js/model/Query.js
ui/packages/catalog-ui-search/src/main/webapp/js/model/QueryResponse.js

- Fixes how server side page indexes are calculated and stored.
- Fixes CSS for the "Update with new data?" button to prevent the text from getting cut off.
@adimka 
@bdeining 
@codice/ui 
@djblue
1. Setup multiple federated sources and set a page size of 5, 10, and 25 to ensure that you get the correct results.
2. Setup multiple federated sources where one returns results slower, and try the same page sizes, making sure that you wait until the slower source returns and you have the option to click the "Update with new data?" button.
For GH Issues:
Fixes: #4668
- ✏️ (Pencil) …

DDF-4668 Fix Server Side Paging Indices

---

catalog/core/catalog-core-standardframework/src/main/java/org/codice/ddf/catalog/sourcepoller/PollerRunner.java

Addresses SonarCloud issue related to missing logging parameter.  Ref https://sonarcloud.io/project/issues?id=ddf&open=AWpeMIEbyRjJygCrjxvx&resolved=false&sinceLeakPeriod=true&types=BUG
@jordanwilking @GabrielFabian 
@codice/build 
@rzwiefel 
@tbatie
Verify successful build
[DDF-1366](https://codice.atlassian.net/browse/DDF-1366) …

DDF-1366 fixes missing logging parameter

---

distribution/docs/src/main/resources/content/_integrating/integrating-intro.adoc
distribution/docs/src/main/resources/content/_managing/_installing/install-with-zip.adoc
distribution/docs/src/main/resources/content/_managing/_running/starting-intro.adoc
distribution/docs/src/main/resources/content/_quickstart/quickstart-installing.adoc

Link to 2.13.x PR: #4784 
fixes typo that caused `{external-link}` property to render incorrectly in certain spots in the documentation.
@codice/docs 
@clockard
@emmberk
@lessarderic
@mcalcote
@shaundmorris
verify icon image renders instead of text
For Jira: …

DDF-2824 fixed external link typo

---

ui/packages/catalog-ui-search/src/main/webapp/react-component/utils/query/query.tsx

Removes restrictions for unnecessary aspects of CQL queries in query.tsx.
@willwill96 
@zta6 
@codice/ui 
@djblue
This change will provide flexibility for anyone using this component to make CQL queries that don't require specific sources or faceting information.
Fixes: #4790 …

DDF-4790 Make facet, source, and count params optional on query.tsx

---

ui/packages/catalog-ui-search/src/main/webapp/component/paging/paging.view.js

- Fixes bulk selection not working
@Bdthomson @hayleynorton @nsuvarna 
@codice/ui 
@djblue 
- build / run / ingest test data
- verify clicking a result highlights the result and checks the checkbox
- verify select all and deselect all functionality working
- verify selection working as expected
For Jira:
For GH Issues:
Fixes: #4668  …

DDF-4668 Fix Bulk Selection

---

ui/packages/catalog-ui-search/src/main/webapp/js/ApplicationStart.js
ui/packages/catalog-ui-search/src/main/webapp/js/Entry.tsx

Fixes a slight regression around application initialization introduced by #4777.
@Bdthomson 
@bdeining 
UI should not fail to initialize.
Fixes: #4410

DDF-04410 Ensures UI properties are initialized before first usage

---

ui/packages/security-idp-server/src/main/resources/templates/login.handlebars
ui/packages/security-idp-server/src/main/webapp/js/view/Login.view.js

This PR adds a spinner to the login page when actively trying to login. This also clears the error message when trying to login. The `Clear` button was also fixed to clear error messages. When logging in, the buttons are disabled to make sure no more inputs are taken. 
@ahoffer 
@codice/ui 
@brjeter
- Verify all login attempts show a spinner and don't show error message when actively logging in
- Verify normal login works (correct username and password)
- Verify failed login shows error message when finished 
- Verify `Clear` button clears username, password, and error message
- Verify changing username or password hides the error message
- Verify unable to enter input for username/password, and cannot click buttons when actively logging in
- Test in …

DDF-4798 Add indications that user is actively trying to login

---

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/ws/JsonRpc.java
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/ws/SecureWebSocketServlet.java
ui/packages/catalog-ui-search/src/main/webapp/js/model/QueryResponse.js

- **The first commit should go through an abbreviated review**; It's a clean cherry-pick of the commit from a PR that was already reviewed and merged (#4368) and then temporarily reverted (#4473) due to a bug.
- The second commit fixes the bug where certain error codes were not being handled on the frontend, causing Intrigue to not work properly in those error scenarios.
@vinamartin 
@tbatie
- Build DDF (include ui in the build)
- Install DDF
Verify the first commit's functionality works:
- Ingest some records and run some queries to make sure Intrigue is working normally.
- With one of the executed queries still up, open a new tab for the AdminUI and logout.
- Go back to Intrigue and edit the open query and/or execute it.
- The query should now return no …

DDF-04318 (with bug fix) Check that the user is logged in for every Intrigue WebSocket request

---

dependency-check-maven-config.xml
platform/platform-paxweb-jettyconfig/src/main/java/org/codice/ddf/security/session/AttributeSharingHashSessionIdManager.java
platform/platform-paxweb-jettyconfig/src/main/java/org/codice/ddf/security/session/AttributeSharingSessionDataStore.java

Updates the "expiry" for the session across all contexts, so that the session is refreshed in all contexts.
@kcover @ahoffer @tyler30clemens @austinsteffes 
@clockard 
@stustison 
@troymohl 
- Install DDF
- Go to Intrigue and leave it idle for 11 minutes
- Make sure no red dialog boxes pop up saying "logged out" from the 9-11 minute mark
Fixes: #4812   …

[2.13.x]DDF-4812 Fix user sessions expiring prematurely

---

ui/packages/catalog-ui-search/src/main/webapp/component/dropdown/query-src/dropdown.query-src.view.js
ui/packages/catalog-ui-search/src/main/webapp/component/result-selector/result-selector.view.js
ui/packages/catalog-ui-search/src/main/webapp/react-component/utils/fetch/fetch.tsx
ui/yarn.lock

- yarn.lock cleanup
- Renames `class` to `className` to stop console warnings
- Warns developer when `window.fetch` is used directly
@adimka 
@tbatie 
@Bdthomson 
@rymach 
CI Build
For GH Issues:
Fixes: #4824

DDF-04824 Improves UI Developer Experience

---

ui/packages/catalog-ui-search/src/main/webapp/component/search-form-editor/search-form-editor.view.js

@willwill96 
@rymach 
@codice/ui 
@bdeining 
@djblue
- Create search forms with geospatial data
- Reopen the same search forms and ensure the geos appear in the search form editor
- Ensure no regressions with search forms in intrigue
For Jira:
For GH Issues:
Fixes: #4834  …

DDF-04834 Make Geos load in search form editor

---

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/SparkServlet.java

GZIP Intrigue backend JSON APIs
@adimka 
@tbatie 
@gjvera 
- Full build on CI 
- Quick build locally and look for gzip headers for Intrigue
Fixes: #4836

DDF-04836 GZIP Intrigue backend JSON APIs

---

distribution/docs/src/main/resources/content/_reference/_tables/PolicyManager.adoc
platform/security/policy/security-policy-context/src/main/resources/OSGI-INF/blueprint/blueprint.xml
platform/security/policy/security-policy-context/src/main/resources/OSGI-INF/metatype/metatype.xml

Added basic auth for /admin
@adimka
@djblue
@stustison
@tbatie
Dev server is can disable IdP. `yarn start`
Related to https://github.com/codice/ddf/issues/4481 …

DDF-04481 Added basic auth for /admin

---

ui/packages/catalog-ui-search/src/main/webapp/component/query-add/query-add.view.js
ui/packages/catalog-ui-search/src/main/webapp/component/search-form-editor/search-form-editor.view.js

Updates the search form in workspaces when the default search form is changed and when the default search form is edited, without needing to refresh the page.
@adimka 
@andrewzimmer 
@djblue 
@jrnorth
1. Open up the sidebar, navigate to search forms, and create some search forms
2. Change the default search form by opening up the three dot menu of a search form card and clicking `Make Default Form`
3. Switch the default form several times, verifying that the search form that appears when creating a query is updated each time.
4. Verify that queries created from these search forms are as expected. 
For Jira:
For GH Issues:
Fixes: #4817, #4823 
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71 …

DDF-04817,04823 Update search form in workspaces when default search form is changed or edited

---

platform/platform-paxweb-jettyconfig/src/main/java/org/codice/ddf/security/session/AttributeSharingHashSessionIdManager.java
platform/platform-paxweb-jettyconfig/src/main/java/org/codice/ddf/security/session/AttributeSharingSessionDataStore.java
platform/platform-paxweb-jettyconfig/src/test/java/org/codice/ddf/security/session/JettySessionManagementTest.java

**What does this PR do?**
Updates the "expiry" for the session across all contexts, so that the session is refreshed in all contexts.
**Who is reviewing it?**
@kcover @ahoffer @tyler30clemens @austinsteffes
@clockard
@stustison
@troymohl
**How should this be tested?**
- Install DDF
- Go to Intrigue and leave it idle for 11 minutes
- Make sure no red dialog boxes pop up saying "logged out" from the 9-11 minute mark
- Any background context you want to provide?
- What are the relevant tickets?
Fixes: #4812 …

DDF-4812 Fix user sessions expiring prematurely

---

catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/SolrMetacardClientImpl.java
catalog/core/catalog-core-tagsfilterplugin/src/main/java/org/codice/ddf/catalog/plugin/tagsfilter/TagsFilterQueryPlugin.java
catalog/core/catalog-core-tagsfilterplugin/src/test/java/org/codice/ddf/catalog/plugin/tagsfilter/TagsFilterQueryPluginTest.java
catalog/plugin/catalog-plugin-metacard-validation/src/main/java/ddf/catalog/metacard/validation/MetacardValidityFilterPlugin.java
catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/cql/CqlQueryResponse.java
ui/packages/catalog-ui-search/src/main/webapp/component/result-item/result-item.collection.tsx
ui/packages/catalog-ui-search/src/main/webapp/component/result-selector/result-selector.view.js
ui/packages/catalog-ui-search/src/main/webapp/js/model/QueryResponse.js

Gives back feedback and lets users know that their search was spell corrected.
@tbatie 
@bellcc 
@derekwilhelm 
@willwill96 
@tbatie
Enable spellcheck in the admin console
Search with single fields and multiple fields with spellcheck on where you misspell your search.
Ensure that results have text that states something like `Showing results for: ...`
For Jira:
For GH Issues:
Fixes: #____ …

DDF-4763 Give Google like results in the results view when a query is fixed by spellchecked

---

ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/list-create/list-create.js

fixes issues with creating more than one List in the List tab dropdown 
@Bdthomson @hayleynorton @nsuvarna @zta6 
@codice/ui 
@bdeining
@djblue 
- build / run
- In a new workspace go to the List tab
- verify that multiple Lists can be created
- run a search and create a List from a result via the + button
- verify the result in included in the list and the "create new list" button is still showing
For GH Issues:
Fixes: #4808  …

DDF-4808 fix A new list is not created from the drop down when the action is selected

---

ui/packages/catalog-ui-search/package.json
ui/packages/ui/.stylelintrc
ui/packages/ui/package.json

Removes stylelint dependencies from ui/packages/catalog-ui-search and ui/packages/ui
@willwill96 @gjvera @rymach @Lambeaux 
@codice/ui 
@bdeining
@djblue
1. Make a bad JS formatting change under ui/packages/ui and ui/packages/catalog-ui-search, like adding a bunch of extra newlines between two statements
2. Run `mvn clean install` from the ui dir
3. Verify the formatter still complains about the changes
For Jira:
For GH Issues:
Fixes: #4856  …

DDF-04856 Clean up stylelint

---

ui/packages/catalog-ui-search/package.json
ui/packages/catalog-ui-search/src/main/webapp/component/golden-layout/golden-layout.view.js
ui/packages/catalog-ui-search/src/main/webapp/component/visualization/visualization.view.js
ui/packages/catalog-ui-search/src/main/webapp/extension-points/extension-points.tsx
ui/packages/catalog-ui-search/src/main/webapp/extension-points/visualizations/index.tsx
ui/packages/catalog-ui-search/src/main/webapp/js/Entry.tsx
ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/visualization-selector/visualization-selector.js

Provide an extension point for visualizations so that downstream projects can add custom visualizations to the golden layout region.
@bellcc 
@codice/ui 
@rzwiefel 
@djblue
Ensure all existing visualization work as expected. Manually add a new visualization to visualizations/index.tsx
For Jira:
For GH Issues:
Fixes: #____ …

DDF-04804: Provide an extension point for visualizations in Intrigue

---

distribution/docs/src/main/resources/content/_configuring/content-directory-monitor.adoc

fixes slashes in CDM policy documentation
@tyler30clemens @ahoffer 
@codice/docs 
@brjeter
@emmberk
quick build and check docs
For Jira:
For GH Issues:
Fixes: #04859  …

[2.13.x] DDF-4859 fixes slashes in CDM policy documentation

---

distribution/docs/src/main/resources/content/_installing/java-reqs.adoc
distribution/docs/src/main/resources/content/_quickstart/quickstart-installing.adoc

Fixes documentation to not have duplicated sections. Improves the sections wording to ensure installation goes smoothly.
@codice/docs 
@brjeter
successful quickbuild and check documentation
For GH Issues:
Fixes: #4848  …

[2.13.x] DDF-4848 Change java installation doc duplication

---

Jenkinsfile

This PR removes NSP check from builds since it has been shutdown. Ideally NPM audit or something equivalent to it is brought in. However this is causing build issues so better to remove it for now.
https://blog.npmjs.org/post/175511531085/the-node-security-platform-service-is-shutting
@djblue 
@mcalcote 
@oconnormi 
@LinkMJB 
@blen-desta 
@codice/build 
@codice/ui 
@oconnormi
@mcalcote 
For GH Issues:
Fixes: #4603  …

DDF-4603 remove obsolete NSP check

---

.github/PULL_REQUEST_TEMPLATE

I no longer plan on being active and would like to remove myself from the PR template to reduce being tagged for reviews.
@vinamartin 
@rzwiefel 
@djblue 
@tbatie 
N/A …

Update Pull Request Template to remove Ethan Manns

---

platform/security/common/src/main/java/ddf/security/samlp/impl/SamlValidator.java

Does case-insensitive check on the destination since the URLs are converted to lower-case automatically in certain browsers which causes the validation to fail.
@tyler30clemens @austinsteffes @ahoffer 
@blen-desta 
@rzwiefel 
@stustison 
Run with DDF's hostname system property configured to the FQDN of the system.
Login to the AdminUI.
Logout.
For GH Issues:
Fixes: #4866  …

[2.13.x]DDF-04866 Fixes destination validation on logout

---

ui/packages/catalog-ui-search/src/main/webapp/js/CQLUtils.js

Adds a null check to prevent a console error when using a form with unknown attributes.
@Bdthomson 
@Schachte 
@codice/ui 
@bdeining 
@troymohl 
1. Add these files to `etc/forms`: [test-form.zip](https://github.com/codice/ddf/files/3218400/test-form.zip)
2. In the karaf console, execute `forms:load`
3. In intrigue, create a query using the form `Test Form` and run it
4. Ensure there are no console errors
For GH Issues:
Fixes: #4877  …

DDF-4877 Adding a null check for metacard property

---

platform/security/common/src/main/java/ddf/security/samlp/impl/SamlValidator.java

Does case-insensitive check on the destination since the URLs are converted to lower-case automatically in certain browsers which causes the validation to fail.
@tyler30clemens @austinsteffes @ahoffer 
@blen-desta 
@rzwiefel 
@stustison 
Run with DDF's hostname system property configured to the FQDN of the system.
Login to the AdminUI.
Logout.
For GH Issues:
Fixes: #4866  …

DDF-04866 Fixes destination validation on logout

---

platform/security/common/src/main/java/org/codice/ddf/security/common/Security.java
platform/security/common/src/test/java/org/codice/ddf/security/SecurityTest.java

This PR adds auditing to the org.codice.ddf.security.common.Security class.
@brjeter @stustison @garrettfreibott @austinsteffes @tyler30clemens 
@blen-desta
@brjeter
@stustison
At discretion of reviewer.
None.
Fixes: #4871 …

[2.13.x] DDF-4871 Audit system subject access or failed privilege escalation

---

platform/security/common/src/main/java/org/codice/ddf/security/common/Security.java
platform/security/common/src/test/java/org/codice/ddf/security/common/SecurityTest.java

Link to 2.13.x PR: #4872
@austinsteffes @tyler30clemens 
@brjeter @blen-desta @garrettfreibott
Testing is at reviewer's discretrion.
No.
Fixes: #4871  …

DDF-4871 Audit system subject access or failed privilege escalation

---

ui/packages/catalog-ui-search/src/main/webapp/component/search-form-editor/search-form-editor.view.js

one line change to fix search form editor
one pr removed this unnecessary require line and another added code that made it necessary
caught by @gjvera 
@codice/ui 
@AzGoalie
@bdeining
@djblue
For Jira:
For GH Issues:
Fixes: #____ …

DDF-0000 Add user require to search form editor

---

distribution/ddf-common/src/main/resources/security/configurations.policy

Adds detail to documentation in policy configuration fie
@emmberk @brjeter @austinsteffes @ricklarsen @tyler30clemens  @peterhuffer 
@codice/docs 
@brjeter
@clockard
@emmberk
@mcalcote
N/A
No.
Fixes: #4900  …

[2.13.x] DDF-04900 Improve policy file documentation

---

ui/packages/catalog-ui-search/src/main/webapp/component/location-new/inputs/masked-text-field.js
ui/packages/catalog-ui-search/src/main/webapp/component/location-new/utils/dms-utils.js
ui/packages/catalog-ui-search/src/main/webapp/react-component/location/base.line.js
ui/packages/catalog-ui-search/src/main/webapp/react-component/location/location.js
ui/packages/catalog-ui-search/src/main/webapp/react-component/location/point-radius.js

There was some poor feedback on the original implementation where the ui would not let you enter an invalid coordinate. This changes the behavior so when the user enters an invalid coordinate (e.g 99 for lat) the ui will change it to 90 and notify the user that it is an invalid coordinate.
Rework of #4229 
@willwill96 @mojogitoverhere 
@codice/ui 
@bdeining 
@djblue 
build/install
make a basic search or advanced search
go to `anyGeo` 
manually input coordinates for lat/lon
verify error message pops up when invalid coordinates are entered
For Jira:
[DDF-4467](https://codice.atlassian.net/browse/DDF-4467)
For GH Issues:
Fixes: #____ …

DDF-4467 rework of lat/lon validation

---

distribution/ddf-common/src/main/resources/security/configurations.policy

MASTER PORT of https://github.com/codice/ddf/pull/4902
Adds detail to documentation in policy configuration fie
@emmberk @brjeter @austinsteffes @ricklarsen @tyler30clemens  @peterhuffer 
@codice/docs 
@brjeter
@clockard
@emmberk
@mcalcote
N/A
No.
Fixes: #4900  …

DDF-04900 Improve policy file documentation

---

.github/PULL_REQUEST_TEMPLATE

Added Adam Dimka and Steve Lombardi as committers
Add new committers to the PR template 
@adimka 
@lambeaux
For GH Issues:
Fixes: #4294 
---
This change …

DDF-4294 Update PULL_REQUEST_TEMPLATE Additions

---

ui/packages/catalog-ui-search/.eslintrc.js
ui/packages/catalog-ui-search/src/main/webapp/component/associations-graph/associations-graph.view.js
ui/packages/catalog-ui-search/src/main/webapp/component/list-editor/list-editor.view.js
ui/packages/catalog-ui-search/src/main/webapp/component/location-new/utils/dd-utils.js
ui/packages/catalog-ui-search/src/main/webapp/component/location-new/utils/dms-utils.js
ui/packages/catalog-ui-search/src/main/webapp/component/location-new/utils/usng-utils.js
ui/packages/catalog-ui-search/src/main/webapp/component/location-new/utils/wkt-utils.js
ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-old.js
ui/packages/catalog-ui-search/src/main/webapp/component/property/property.view.js
ui/packages/catalog-ui-search/src/main/webapp/component/query-altitude/query-altitude.view.js
ui/packages/catalog-ui-search/src/main/webapp/component/query-time/query-time.view.js
ui/packages/catalog-ui-search/src/main/webapp/component/visualization/histogram/histogram.view.js
ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/DrawingUtility.js
ui/packages/catalog-ui-search/src/main/webapp/js/Autocomplete.js
ui/packages/catalog-ui-search/src/main/webapp/js/cql.js
ui/packages/catalog-ui-search/src/main/webapp/js/model/QueryResult.collection.js
ui/packages/catalog-ui-search/src/main/webapp/js/widgets/openlayers.bbox.js
ui/packages/catalog-ui-search/src/main/webapp/js/widgets/openlayers.circle.js
ui/packages/catalog-ui-search/src/main/webapp/js/widgets/openlayers.line.js
ui/packages/catalog-ui-search/src/main/webapp/lib/cesium-drawhelper/DrawHelper.js

it may be easier to review one commit at a time
note that linting won't happen until https://github.com/connexta/ace/pull/11 is merged and ddf is updated to point to the new version
@leo-sakh 
@gjvera 
@lamhuy 
@adimka 
@codice/ui 
@djblue 
build
For Jira:
For GH Issues:
Fixes: #04746 …

DDF-04746 enable eslint rule `no-var` for catalog-ui-search

---

ui/packages/catalog-ui-search/src/main/webapp/component/search-form-editor/search-form-editor.view.js

see https://github.com/codice/ddf/pull/4887/files
@codice/ui 
@AzGoalie
For Jira:
For GH Issues:
Fixes: #____ …

[2.15.x] DDF-0000 Add user require to search form editor

---

distribution/ddf-common/src/main/resources/security/default.policy
platform/security/sts/security-sts-server/pom.xml

Fixed issues with Merlin not initializing correctly
@bdeining 
@glenhein 
@rzwiefel
@stustison 
Downstream projects' itests pass.

DDF-04481 Fixed issues with Merlin not initializing correctly

---

distribution/docs/src/main/resources/content/_managing/_configuring/configuring-multi-factor-auth.adoc
distribution/docs/src/main/resources/content/_managing/_configuring/connecting-to-external-idp.adoc

Adds documentation on multi factor authentication and how to configure it with Keycloak.
@austinsteffes
@ahoffer
@codice/docs 
@brjeter
CI and check documentation 
verify all links work 
verify MFA works with keycloak and the system
For GH Issues:
Fixes: #4880 …

DDF-4880 Add docs on multi factor authentication with Keycloak

---

catalog/plugin/catalog-plugin-videothumbnail/src/main/java/org/codice/ddf/catalog/content/plugin/video/VideoThumbnailPlugin.java

Link to 2.13.x PR: #4908 
@tyler30clemens @blen-desta @brjeter @vinamartin
Resolves #4905 

DDF-04905 Prevent ffmpeg access control exception

---

.github/PULL_REQUEST_TEMPLATE

@troymohl 
@lamhuy 
@adimka
create a new pull request using the new template. if you scroll down a few pages you should see that the jira ticket link is no longer there
see additional information section on the issue https://github.com/codice/ddf/issues/4948
Fixes: #4948 …

Update PULL_REQUEST_TEMPLATE - remove jira ticket link

---

catalog/admin/module/catalog-admin-module-layout/pom.xml
catalog/admin/module/catalog-admin-module-maplayers/pom.xml
platform/platform-configuration/pom.xml

Removes unneeded package exports that are duplicated, causing some installation issues in downstream projects. Specifically:
`org.codice.ddf.catalog.admin.plugin` (no longer exported)
`org.codice.ddf.configuration` (still exported by another bundle, but will not include the `PlatformUIConfiguration.java` class)
@bdeining
@blen-desta
Install downstream projects (ping me for details).
For GH Issues:
Fixes: #4937  …

DDF-04937 Remove duplicate package exports

---

catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/DumpCommand.java
catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/ImportCommand.java
catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/synchronizations/CompletionSynchronization.java
catalog/core/catalog-core-solrcommands/src/main/java/org/codice/ddf/commands/solr/SolrCommands.java
platform/admin/core/admin-core-appservice/src/main/java/org/codice/ddf/admin/application/service/command/ProfileInstallCommand.java
platform/resource-bundle-locator/src/main/java/ddf/platform/resource/bundle/locator/ResourceBundleLocatorImpl.java
platform/security/rest/security-rest-cxfwrapper/src/main/java/org/codice/ddf/cxf/client/impl/SecureCxfClientFactoryImpl.java
platform/security/sts/security-sts-attributequerycommon/pom.xml
platform/security/sts/security-sts-attributequerycommon/src/main/java/org/codice/ddf/security/claims/attributequery/common/AttributeQueryClaimsHandler.java
platform/security/sts/security-sts-attributequerycommon/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
platform/solr/solr-factory-impl/src/main/java/org/codice/solr/factory/impl/HttpClientBuilder.java

Non-final methods that perform security checks, or elevate code and then call other non-final methods, may be overridden in ways to bypass those security checks. This PR fixes multiple instances of that. 
@ahoffer 
@brjeter
@stustison
CI build and testers discretion 
Fixes: #4951  …

DDF-4951 Changed methods that invoke security checks to final

---

ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/openlayers/openlayers.less

@jrnorth 
@leo-sakh 
@willwill96 
@BernardIgiri 
@maryformanek
@codice/ui 
@adimka 
@djblue
Navigate to search UI and verify the zoom controls for the map work
For Jira:
For GH Issues:
Fixes: #4944 
- ❗ …

DDF-04944 Adding zoom controls to map

---

README.md

updates documentation links in README.md file to point to more current resources
@ahoffer 
@jhunzik 
@codice/docs 
@AzGoalie
@brjeter
@clockard
@coyotesqrl
@emmberk
@lessarderic
@mcalcote
@shaundmorris
click the links
[ddf-2824](https://codice.atlassian.net/browse/DDF-2824)
(README) …

DDF-2824 updated documentation links in README

---

distribution/docs/src/main/resources/content/_integrating/_endpoints/ftp-endpoint.adoc
distribution/docs/src/main/resources/content/_integrating/_endpoints/opensearch-endpoint.adoc

Updated (simplified) the documentation for the FTP endpoint. 
@codice/docs 
@brjeter
@clockard
@lessarderic
@shaundmorris
For GH Issues:
: #4374 …

DDF-04374 updated docs for ftp endpoint

---

.github/PULL_REQUEST_TEMPLATE

Adding Aaron Hoffer, Gordo Canchola as Committers
@ahoffer 
@vinamartin 
@kcwire 
Fixes: #4922
---
This change is [<img …

DDF-4922 Added Committers to PR Template

---

distribution/ddf-common/src/main/resources/bin/setenv
distribution/ddf-common/src/main/resources/bin/setenv.bat

https://github.com/codice/ddf/pull/4953
@beyelerb 
@brjeter

[2.13.X] DDF-04953 Update setenv script to not override EXTRA_JAVA_OPTS if it already contains a value

---

distribution/docs/src/main/resources/content/_configuring/managing-keystores.adoc

Clarifies the Keystore and Truststore documentation.
@bakejeyner 
@brjeter 
@ricklarsen 
@stustison 
Related to https://github.com/codice/ddf/pull/4921 …

[2.13.x] Clarified keystore and truststore documentation

---

features/security/pom.xml
features/security/src/main/feature/feature.xml
platform/security/servlet/security-servlet-logout/pom.xml

Embed httpclient and httpcore in order to improve installation performance for downstream projects. See bc046dc.
@ahoffer 
@blen-desta
CI
Fixes: #4966  …

DDF-04966 Embed http libraries instead of running as bundle

---

ui/packages/catalog-ui-search/src/main/webapp/component/visualization/table/table-viz.view.js

Improve table visualization css
@bellcc 
@codice/ui 
@adimka
@djblue 
1. Ingest a piece of data
2. Open table visualization and make sure all three actions work.
Fixes: #4972

DDF-4792 Improve table visualization css

---

catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/RealTimeGetDelegate.java
catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/SolrMetacardClientImpl.java
catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/RealTimeGetDelegateTest.java
catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/SolrProviderRealTimeQueryTest.java

This refines the check to see if we should do a Solr RealTime Get so that we
only do it for filters that only contain checks for metacards with
specific ids. Before, we did it for any filter that contained an "id ="
operand, which could cause a query to only return metacards matching an
id when the filter should return other results as well.
@rymach @peterhuffer @paouelle
@codice/solr 
@clockard
@pklinef
query the catalog with a filter that contains some filter ORed with an id comparison.
Example: [title is like '*'] OR [id = <some metacard's id>]
The filter should return the metacard with the given id and anything that matches the rest of the filter. 
This bug was discovered because [Replication](https://github.com/connexta/replication) was not receiving the expected query results. …

DDF-4983 Fix check for Solr RealTime Get

---

.github/CODEOWNERS
ui/packages/catalog-ui-search/src/main/webapp/react-component/container/sharing/sharing.tsx

reviewers may want to view the changes from one commit at a time
@leo-sakh 
@gjvera 
@Bdthomson 
@codice/ui 
@adimka
@bdeining
see issue
no
For GH Issues:
Fixes: #4941  …

DDF-04941 Sharing breaks if the sharee's email contains capital letters

---

catalog/catalog-app/src/main/resources/features.xml
catalog/transformer/catalog-transformer-geojson-input/pom.xml
catalog/transformer/catalog-transformer-geojson-input/src/main/java/ddf/catalog/transformer/input/geojson/GeoJsonInputTransformer.java
catalog/transformer/catalog-transformer-geojson-input/src/main/resources/OSGI-INF/blueprint/blueprint.xml

@mdang8 
@brjeter
@figliold 
1. Build this PR and install DDF.
2. Create a file like the following:
```
{
"geometry": null,
"type": "Feature",
"properties": {
"metadata": "<metacard xmlns=\"urn:catalog:metacard\" xmlns:gml=\"http://www.opengis.net/gml\" xmlns:xlink=\"http://www.w3.org/1999/xlink\"\n          xmlns:smil=\"http://www.w3.org/2001/SMIL20/\" xmlns:smillang=\"http://www.w3.org/2001/SMIL20/Language\"\n          gml:id=\"asdfasdfasdfasdfasdasdf\">\n        <source>ddf.distribution</source>\n    <string name=\"resource-size\">\n        <value>30</value>\n    </string>\n    <dateTime name=\"created\">\n        <value>2000-06-19T17:32:02.779+00:00</value>\n    </dateTime>\n    <string name=\"ext.extracted.text\">\n        <value>something completely …
```

DDF-4991 - transform geojson metadata

---

catalog/transformer/pom.xml
dependency-check-maven-config.xml
pom.xml

Depends on https://github.com/codice/thirdparty/pull/33
@austinsteffes @ahoffer 
@figliold 
Test ingesting with the tika input transformer
Fixes: #5012  …

DDF-05012 Exclude bzip dependency from tika

---

ui/packages/catalog-ui-search/src/main/webapp/component/query-interactions/query-interactions.view.js
ui/packages/catalog-ui-search/src/main/webapp/react-component/container/metacard-interactions/export-interaction.tsx
ui/packages/catalog-ui-search/src/main/webapp/react-component/container/results-export/results-export.tsx
ui/packages/catalog-ui-search/src/main/webapp/react-component/utils/cql/cql.tsx
ui/packages/catalog-ui-search/src/main/webapp/react-component/utils/export/export.tsx

When exporting a single result you must have that result selected so that the results export view can pick up on that result. If you immediately click on the kebab menu then the result will not be selected and will fail to grab the source ID from the result. 
@hayleynorton 
@samuelechu 
@codice/test 
@bdeining 
@djblue
- Export a result without selecting it first. 
- Export a couple of results.
- Select more than one result, then click on the kebab menu for an individual result. Verify that only the exported result is the one you attempted to export. 
- Export results as compressed. 
- None
For GH Issues:
Fixes: #4897 
- None …

DDF-4897 Results export view cannot find source id

---

catalog/solr/catalog-solr-solrclient/pom.xml
catalog/solr/catalog-solr-solrclient/src/main/java/ddf/catalog/source/solr/rest/SolrRest.java
catalog/solr/catalog-solr-solrclient/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/solr/catalog-solr-solrclient/src/main/resources/OSGI-INF/metatype/metatype.xml
catalog/solr/catalog-solr-solrclient/src/test/java/ddf/catalog/source/solr/rest/SolrRestTest.java

Fixes problems with setting Solr relevancy after the changes to Solr authentication were made.
@Schachte 
@Lambeaux 
@codice/solr 
@adimka 
@bdeining 
@millerw8 
@pklinef
Navigate to the Admin UI -> Solr Catalog
Select Catalog Solr Relevancy Ranking
Change parameters to k1=1.11, b=.50
Click Save
Verify that Solr is updated: https://localhost:8994/solr/catalog/schema/fieldtypes?wt=json
Fixes: #4960  …

DDF-4960 Fix Solr Relevancy configuration

---

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/security/accesscontrol/AccessControlPreQueryPlugin.java

fixing constructor bug
@Lambeaux 
@stustison
@troymohl
- Run DDF
- Set breakpoint at QueryOperations.java:188
- Navigate to Workspace page
- At breakpoint, verify queryRequest > query > pageSize is 250
- F8, to step one step
- pageSize remain 250, instead of default 20
Fixes: #5010  …

DDF-5010 AccessControlPreQueryPlugin to copy all other query parameters

---

platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/ConfigurationMigrationManager.java

Address static analysis findings in migration
@jlcsmith 
@paouelle 
CI
Fixes: #5017 

DDF-05017 Address static analysis findings in migration

---

ui/packages/catalog-ui-search/src/main/webapp/component/paging/paging.view.js

NOTE:  I do realize I don't have an issue.  Let me know if you feel strongly I should make one.
Removes a listener from the paging.view that was calling a non existent function.
@djblue 
@adimka 
@bellcc 
Not really needed.
Do we want a ticket for these sorts of changes?
Fixes: #____ …

Removes dead code in paging.view

---

ui/packages/catalog-ui-search/src/main/webapp/behaviors/dropdown.behavior.utility.js

Fix dropdown calculated max height
@samuelechu 
@bdeining 
@codice/ui 
@adimka
@djblue 
Open dropdowns above and below 50% height line, verify they look right and the height isn't truncated.
Fixes: #5022 
**Before**
**After**
- ❗ …

DDF-5022 Fix dropdown calculated max height
