codice/ddf

- distribution/ddf-common/src/main/resources/etc/org.ops4j.pax.web.cfg
- test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/AbstractIntegrationTest.java
- test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestSecurity.java
- added new HTTP to HTTPS camel proxy service
- added integration test for anonymous SOAP HTTP access
- disabled HTTP in pax web configuration file
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/35)
> DDF-1197 created an HTTP to HTTPS proxy to use for legacy clients

- test/itests/pom.xml
- test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/AbstractIntegrationTest.java
- test/itests/test-itests-common/pom.xml
- test/itests/test-itests-common/src/test/java/ddf/common/test/KarafConsole.java
New common integration test package and class added to help testing Karaf console commands.
For some reason, a commit for DDF-1192 was included as part of this pull request. Not sure how I managed to do this, but you can ignore that one as it's already part of a separate PR.
@shaundmorris and @pklinef, please review and make sure you're ok with the new package I created and where I put the class.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/37)
> DDF-1210: Added KarafConsole class to allow console commands to be used in Pax Exam tests

- distribution/ddf/pom.xml
The opendj-embedded.app 1.3.0-SNAPSHOT should be in the nexus
@shaundmorris 
@lessarderic 
@roelens8
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/50)
> DDF-1254: Upgraded OpenDJ-embedded-app to 1.3.0-SNAPSHOT

- distribution/ddf-common/src/main/resources/common-bin.xml
- distribution/ddf/pom.xml
- distribution/pom.xml
- sdk/ddf-sso-query-widget/pom.xml
- sdk/pom.xml
- sdk/sample-metrics/pom.xml
- sdk/sample-plugins/pom.xml
- sdk/sample-soap-endpoint/pom.xml
- sdk/sample-transformers/xslt-identity-input-transformer/pom.xml
* Changed the build to download the documentation artifacts for each of the apps and place them in a "documentation" directory in the distribution .zip file. The html and pdf formats are included, not the asciidocs.
* Modified the following repos to reference the current ddf-parent version (3.0.3-SNAPSHOT), since the version they were referencing (3.0.2-SNAPSHOT) does not build the documentation automatically.
* ddf-admin
* ddf-catalog
* ddf-content
* ddf-platform
* ddf-spatial
* ddf-ui
* Along the way, I ran into some build errors in the ddf.sdk project because maven could not load the ${argLine} class. I fixed these
Reviewers: @ricklarsen @pklinef @clockard @roelens8 as hero
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on …
> DDF-1249: Include Documentation in DDF 2.8 Distribution

- distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestCatalog.java
- distribution/test/itests/test-itests-catalog/src/test/resources/metacard1.xml
- distribution/test/itests/test-itests-catalog/src/test/resources/metacard2.xml
- distribution/test/itests/test-itests-catalog/src/test/resources/metacard3.xml
- distribution/test/itests/test-itests-catalog/src/test/resources/metacard4.xml
Our current integration tests for OpenSearch, amongst other features, is a bit spare. With the XML formatting changes coming along with the parent ticket for this - DDF-1246 - I wanted to have a bit more confidence in the output we're generating.
This change is just scratching the surface, but it's a start.
+ @kcwire
+ @millerw8
+ @wmcnalli
+ @jlcsmith
+ @beyelerb
+ @emanns95
+ @jrnorth
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/54)
> DDF-1281 Improved and expanded integration test for OpenSearch.

- distribution/pom.xml
The owasp profile is now inherited from ddf-parent.
@coyotesqrl @rzwiefel @roelens8 @pklinef @tbatieConnexta
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/73)
> DDF-1198 Removed owasp profile from distribution pom.xml

- distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/AbstractIntegrationTest.java
- sdk/ddf-sso-query-widget/pom.xml
- sdk/ddf-sso-widget/pom.xml
- sdk/pom.xml
- sdk/sample-metrics/pom.xml
- sdk/sample-plugins/pom.xml
- sdk/sample-soap-endpoint/pom.xml
- sdk/sample-transformers/pom.xml
- sdk/sample-transformers/xslt-identity-input-transformer/pom.xml
- sdk/sdk-app/pom.xml
Updated SDK version to 2.8.0-SNAPSHOT from 2.3.0.ALPHA1-SNAPSHOT and increased catalog timeout to 10 minutes as 5 minutes isn't always enough depending on the number of builds running on the AWS instance.
@shaundmorris, @pklinef: Please review.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/77)
> DDF-1354: Updated SDK version and integration tests catalog timeout.

- distribution/sdk/sample-plugins/src/main/resources/features.xml
- distribution/sdk/sdk-app/src/main/resources/features.xml
The sdk module was moved under the distribution module, but the features files were not updated to have the correct maven coordinates.
@coyotesqrl @rzwiefel @roelens8 @pklinef @tbatieConnexta @shaundmorris
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/84)
> DDF-1372 Use correct maven coordinates in sdk features files

- distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/AbstractIntegrationTest.java
The sdk module was moved under the distribution module, so the itests need to be updated to the correct maven coordinates for the sdk-app.
@coyotesqrl @rzwiefel @roelens8 @pklinef @tbatie
> DDF-1374 Fix maven coordinates for sdk-app in itests

- catalog/pom.xml
- distribution/pom.xml
- distribution/test/pom.xml
- libs/pom.xml
- platform/pom.xml
- pom.xml
Changes the root artifact from ddf:ddf-reactor to ddf:ddf to more accurately reflect the fact that this is no longer simply a reactor but a parent pom.
Ryan, could you please hero this? 
I've added the associated ticket as a subtask to repository merge, so until this is completed I can't close out that task (in other words...quickly review, please?)
@pklinef 
@tbatie 
@jckilmer
@rzwiefel
@roelens8
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/89)
> DDF-1390 Change root artifactId

- libs/pom.xml
Removed the <distributionManagement> section from libs/pom.xml file so that the one defined in the parent pom is used instead. This makes the pom file consistent with all the other pom files and ensures that the same URL is used for ddf-site.
@coyotesqrl, please review.
@garrettfreibott, can you the hero this?
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/102)
> DDF-1402: Wrong ddf-site URL in libs pom file breaks nightly build

- platform/admin/core/admin-core-appservice/src/main/java/org/codice/ddf/admin/application/service/impl/ApplicationServiceBean.java
- platform/admin/core/admin-core-appservice/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- platform/admin/core/admin-core-appservice/src/test/java/org/codice/ddf/admin/application/service/impl/ApplicationServiceBeanTest.java
Fixed an issue with the testDestroyException test case where sometimes
ManagementFactory.getPlatformMBeanServer() would return null, which
caused the test to fail. Accomplished this by refactoring the test cases
for init() and destroy() so that they only interact with a mocked
mBeanServer.
@lessarderic
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/109)
> DDF-1172 Fix issue with testDestroyException case

- catalog/content/docs/pom.xml
- catalog/docs/pom.xml
- catalog/solr/docs/pom.xml
- catalog/spatial/docs/pom.xml
- catalog/ui/docs/pom.xml
- platform/admin/docs/pom.xml
- platform/docs/pom.xml
- platform/security/docs/pom.xml
Sets the execution phase of the owasp dependency-check plugin to none on docs projects so that it is not run.
@lessarderic 
@ricklarsen 
@tbatie 
@shaundmorris
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/130)
> DDF-1446: Disables owasp dependency-check on docs

- .gitignore
Fixes the matching line for the generated styles.css files to have the correct lead-in of two stars to match any initial directory prior to the webapp directory.
@tbatie 
@jckilmer
@rzwiefel
@roelens8
Ryan, please hero. I would suggest that this particular delta probably needs a full compile but as long as all the files are correctly ignored and none are incorrectly ignored, testing is overkill.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/132)
> DDF-1447 Fixes incorrectly formatted .gitignore line

- catalog/measure/catalog-measure-api/pom.xml
- catalog/measure/catalog-measure-api/src/main/java/ddf/measure/Distance.java
- catalog/measure/catalog-measure-api/src/test/java/ddf/measure/LinearUnitFromStringParametrizedTest.java
- catalog/measure/catalog-measure-api/src/test/java/ddf/measure/LinearUnitTest.java
Added a new method to support different variations of enum strings so that clients can use "foot" for FOOT_U_S for instance and also don't have to worry about case sensitivity,
@brendan-hofmann, @pklinef, can you please take a look before I merge this PR? I'd like to have it done before the end of the sprint. If you can't, no worries. Just let me know.
@shaundmorris, can you take a quick look at this before the tech session on Friday?
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/128)
> DDF-1443: Added fromString() method to LinearUnit enum.

- distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestSecurity.java
We need to ensure that we always start tests with anon access turned on because our tests expect to be able to ingest anonymously. Additionally, we have a new integration test that is making a configuration change and not waiting long enough for it to propagate.
@lessarderic 
@pklinef 
@rzwiefel
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/137)
> DDF-1442 Ensures that anonymous REST access is reestablished at the start of each security test

- catalog/content/core/content-core-catalogerplugin/src/main/java/ddf/content/plugin/cataloger/CatalogContentPlugin.java
- distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestCatalog.java
- distribution/test/itests/test-itests-catalog/src/test/resources/metacard5.xml
Recent changes that check for a security subject on a thread broke the
Directory Monitors ingest (Since it has no security subject) and was
throwing an uncaught runtime exception. Now we catch the exception to
allow the ingest to proceed and simply don't add a point of contact to
the metacard.
@coyotesqrl @brendan-hofmann @stustison 
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/129)
> DDF-1426 - Fixed Directory Monitor Security error

- distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/AbstractIntegrationTest.java
- platform/security/filter/security-filter-web-sso/src/main/java/org/codice/ddf/security/filter/websso/WebSSOFilter.java
- platform/security/filter/security-filter-web-sso/src/test/java/org/codice/ddf/security/filter/websso/WebSSOFilterTest.java
- platform/security/handler/security-handler-pki/src/main/java/org/codice/ddf/security/handler/pki/PKIHandler.java
- platform/security/handler/security-handler-saml/src/main/java/org/codice/ddf/security/handler/saml/SAMLAssertionHandler.java
Added extra logging statements to WebSSOFilter and all the handlers to figure out if they all get registered before the first doFilter() call.
Also, increased integration test timeouts and added code to log the state of all the inactive bundles when the test setup fails to help with debugging.
@stustison, @andrewkfiedler please review.
Let me know if you're ok with these changes and if so I'll have @shaundmorris hero it.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/101)
> DDF-1354: Added logging to track down integration test failures

- distribution/test/itests/test-itests-catalog/pom.xml
- distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/AbstractIntegrationTest.java
- distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestSecurity.java
- platform/admin/core/admin-core-api/pom.xml
- platform/admin/core/admin-core-api/src/main/java/org/codice/ddf/ui/admin/api/ConfigurationAdmin.java
- platform/admin/core/admin-core-api/src/main/java/org/codice/ddf/ui/admin/api/ConfigurationAdminExt.java
- platform/admin/core/admin-core-api/src/test/java/org/codice/ddf/ui/admin/api/ConfigurationAdminExtTest.java
- platform/admin/core/admin-core-api/src/test/java/org/codice/ddf/ui/admin/api/ConfigurationAdminTest.java
This resolves issues with preferences getting rejected
after being set by the Admin UI. Since Felix also requires
strongly typed properties, added an enum to do the
type-casted mapping in addition to cardinality.
@andrewkfiedler @shaundmorris @stustison 
Unit tests need work, but I wanted to start getting feedback on the implementation.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/123)
> DDF-1411 Enforce cardinality in ConfigurationAdmin

- distribution/test/itests/test-itests-catalog/pom.xml
- distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/AbstractIntegrationTest.java
- distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/CatalogBundle.java
- distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestCatalog.java
- distribution/test/itests/test-itests-common/pom.xml
- distribution/test/itests/test-itests-common/src/test/java/ddf/common/test/AdminConfig.java
- distribution/test/itests/test-itests-common/src/test/java/ddf/common/test/PaxExamRule.java
- distribution/test/itests/test-itests-common/src/test/java/ddf/common/test/PostTestConstruct.java
- distribution/test/itests/test-itests-common/src/test/java/ddf/common/test/ServiceManager.java
Most of the functionality of the base class has been pulled out to the new facade classes. In order for it to be initialized, PaxExamRule has been modified slightly to run a post-construction method. The methods that are now delegating to the new facade classes have all been deprecated with the intent that we will reroute all those calls directly to the appropriate class.
@pklinef 
@tbatie 
@jckilmer
@rzwiefel
@roelens8
Armand, please hero.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/135)
> DDF-1448 Refactors most of functionality out of AbstractIntegrationTest for greater reusability

- catalog/ui/search-ui/standard/pom.xml
- platform/security/security-admin-module/pom.xml
- pom.xml
Changed pom files to download node.js and npm from artifacts.codice.org
and temporarily added --force option to grunt tests.
@coyotesqrl, @stustison, can you take a quick look at this? This is not the final solution for our DDF build failures and I won't close DDF-1462 right now, but it should at least put the builds back on track until we have final solutions for the node.js/npm download and UI test failures.
I tested it yesterday and the build passed fine with those changes and I can even run the build on a faster machine.
Let me know what you think.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/145)
> DDF-1462: Address node.js and npm intermittent download failures

- distribution/test/itests/test-itests-catalog/pom.xml
- distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/CatalogBundle.java
- distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/SecurityPolicyConfigurator.java
- distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestCatalog.java
- distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestSecurity.java
- distribution/test/itests/test-itests-common/src/test/java/ddf/common/test/ServiceManager.java
- distribution/test/itests/test-itests-common/src/test/java/ddf/common/test/SynchronizedConfiguration.java
Removes arbitrary Thread.sleep() calls and favors explicit calls to updated services to see that their configurations have been changed before moving on.
@pklinef 
@jckilmer
@roelens8
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/141)
> DDF-1452 Fixes racy configuration changes in Integration Tests

- platform/security/common/pom.xml
- platform/security/common/src/main/java/org/codice/ddf/security/common/jaxrs/RestSecurity.java
- platform/security/common/src/test/java/org/codice/ddf/security/common/jaxrs/RestSecurityTest.java
- platform/security/handler/security-handler-saml/src/main/java/org/codice/ddf/security/handler/saml/SAMLAssertionHandler.java
- platform/security/handler/security-handler-saml/src/test/java/org/codice/ddf/security/handler/saml/SAMLAssertionHandlerTest.java
- CXF DeflateEncoderDecoder has a bug related to inflating a token
that inflated size is more than twice the size of the deflated token.
Replaced CXF deflate/inflate utility with java.util.zip.
- Replaced CXF Base64 with Apache Commons Base64 utility.
- Added decodeSaml to mirror encodeSaml to RestSecurity for better
cohesion.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/144)
> DDF-1453 Use java.util.zip to deflate/inflate tokens

- catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/controller/AbstractEventController.java
- distribution/test/itests/test-itests-catalog/pom.xml
- distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/AbstractIntegrationTest.java
- distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/SecurityPolicyConfigurator.java
- distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestCatalog.java
- distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestSecurity.java
- distribution/test/itests/test-itests-common/src/test/java/ddf/common/test/SynchronizedConfiguration.java
- platform/security/core/security-core-impl/src/main/java/ddf/security/common/util/SecurityProperties.java
- platform/security/pep/security-pep-interceptor/src/main/java/ddf/security/pep/interceptor/PEPAuthorizingInterceptor.java
- Added binding the subject to the thread in PEPAuthorizingInterceptor.
- Added support in SecurityPolicyConfigurator to configure all policy
options.
- Fixed whitelist context for SDK SOAP service in itests.
- Fixed potential NPE in search endpoint event controller.
@stustison @coyotesqrl @rzwiefel
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/155)
> DDF-1475 Support SecurityUtils.getSubject() in SOAP endpoints

- catalog/ui/search-ui/standard/README.md
- catalog/ui/search-ui/standard/src/main/webapp/js/view/Workspace.view.js
The code originally had 2 listeners listening to the same event
and caused a parent to rerender its children while the children
tried to rerender themselves. Now the rendering is handled by
the parent.
Also cleaned up some backbone to make it more standard.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/152)
> DDF-1407 Fix view destroyed errors in workspaces

- catalog/ui/search-ui/standard/src/main/webapp/js/model/Query.js
- catalog/ui/search-ui/standard/src/main/webapp/js/widgets/openlayers.bbox.js
When using the numeric input boxes to adjust the bounding box
North and South values, the box is either removed or moved to a
unknown location on the 2d map. This was because the values are
not being treated as numeric. This was solved by ensuring they are
numeric once they are retrieved from model.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/159)
> DDF-1476 - Updating bounding box causes inconsistent behavior

- distribution/ddf-common/src/main/resources/bin/setenv
Since Permgen was removed from the Java8 heap, command line startup arguments that
set its size issue a warning when the JVM is started.  This change removes those
arguments from distribution/ddf-common/src/main/resources/bin/setenv.
@kcwire 
@beyelerb 
@shane-voisard
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/170)
> DDF-1486 DDF start scripts should not set permsize when requiring java8

- catalog/opensearch/catalog-opensearch-source/src/main/java/ddf/catalog/source/opensearch/OpenSearchSource.java
- distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestFederation.java
Added logic to accept purely spatial queries to OpenSearchSource
and added a wildcard character as a contextual filter since
OpenSearch needs it. In addition, added an ITest to ensure pure
spatial federated OpenSearches work.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/175)
> DDF-1489 Fixed OpenSearchSource and added ITest

- platform/security/rest/security-rest-cxfwrapper/src/main/java/org/codice/ddf/cxf/SecureCxfClientFactory.java
- platform/security/security-admin-module/pom.xml
In the case where the authorization bean is null, we can simply create a new one and move forward.
@kcwire is the hero
@AzGoalie 
@stustison
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/183)
> DDF-1498 Fixes issue where magically and non-deterministically null authorization field causes auth failures.

- distribution/docs/src/main/resources/ExtContents.adoc
- distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestSecurity.java
- platform/security/common/src/main/java/org/codice/ddf/security/common/HttpUtils.java
- platform/security/common/src/main/java/org/codice/ddf/security/common/jaxrs/RestSecurity.java
- platform/security/common/src/test/java/org/codice/ddf/security/common/jaxrs/RestSecurityTest.java
- platform/security/filter/security-filter-web-sso/src/main/java/org/codice/ddf/security/filter/websso/WebSSOFilter.java
- platform/security/filter/security-filter-web-sso/src/test/java/org/codice/ddf/security/filter/websso/WebSSOFilterTest.java
- platform/security/handler/security-handler-saml/src/main/java/org/codice/ddf/security/handler/saml/SAMLAssertionHandler.java
- platform/security/handler/security-handler-saml/src/test/java/org/codice/ddf/security/handler/saml/SAMLAssertionHandlerTest.java
- platform/security/platform-security-core-api/src/main/java/ddf/security/SecurityConstants.java
Update ddf to use Authorization headers instead of cookies for storing SAML assertions.
Hero: @djblue
@stustison 
@pklinef
@andrew-fiedler
@mverret 
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/174)
> DDF-1472: DDF should support more standard ways of specifying a SAML assertion in the http header

- catalog/ui/search-ui/standard/src/main/webapp/css/searchPage.css
- catalog/ui/search-ui/standard/src/main/webapp/js/view/MetacardDetail.view.js
- catalog/ui/search-ui/standard/src/main/webapp/js/view/sliding.region.js
- catalog/ui/search-ui/standard/src/main/webapp/templates/metacard.handlebars
The nevigation menu and tabs for metacard records now is statically
fixed when scrolling through details and summary information.
@kcwire 
@millerw8 - Hero
@wmcnalli
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/169)
> DDF-1483 Modified Metacard Nav menu to be statically positioned

- distribution/test/itests/test-itests-common/src/test/java/ddf/common/test/AdminConfig.java
- distribution/test/itests/test-itests-common/src/test/java/ddf/common/test/ServiceManager.java
- distribution/test/itests/test-itests-common/src/test/java/ddf/common/test/config/ConfigurationPredicate.java
- distribution/test/itests/test-itests-common/src/test/java/ddf/common/test/config/ConfigurationPropertyMatches.java
Added a method to ServiceManager to restart one or more bundles. Also added a 
waitForConfiguration() method to AdminConfig along with a ConfigurationPredicate
class that wait for a property value to match a regular expression.
@garrettfreibott, @figliold, please review.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/189)
> DDF-1505: Add methods in integration test common classes to restart bundles and wait for configuration updates

- distribution/pom.xml
- There is an issue with ddf being built before the docs, as ddf is expecting certain docs to already exist.  In the current state, it will not find them locally and attempt to find them in the nexus (which won't have them, or in some cases just happens to have them).
https://codice.atlassian.net/browse/DDF-1502
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/187)
> DDF-1502 Moves docs module above ddf module

- distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestSolrCommands.java
Changed tests to poll or file creation to prevent tests from failing
because of timing issues.
@wmcnalli, @kcwire, @roelens8 please review.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/195)
> DDF-1491: Fix TestSolrCommands.testSolrBackupNumToKeep()

- distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestSecurity.java
The supposition is that an underlying library that used to be more lenient of whitespace was upgraded to one that is less so. The spec doesn't support whitespace in the token, so cleaning this in the test is the most correct solution.
@tbatie
@stustison 
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/204)
> DDF-1533 Fixes erroneous whitespace in BinarySecurityToken used for test class.

- distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestSecurity.java
- platform/security/sts/security-sts-x509validator/src/main/java/org/codice/ddf/security/validator/x509/X509PathTokenValidator.java
- platform/security/sts/security-sts-x509validator/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- platform/security/sts/security-sts-x509validator/src/test/java/org/codice/ddf/security/validator/x509/TestX509PathTokenValidator.java
The CXF x509 validator was being registered alongside our own path-token validator and at runtime we were getting one or the other non-deterministically. Additionally, the path-token validator was not differentiating between path and certificate validation.
@kcwire You're my hero!
@stustison 
@lessarderic
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/215)
> DDF-1540 Fixes x509 token/path validator.

- catalog/spatial/csw/spatial-csw-transformer/pom.xml
- catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/transformer/CswQueryResponseTransformer.java
- catalog/spatial/csw/spatial-csw-transformer/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/spatial/csw/spatial-csw-transformer/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/transformer/TestCswQueryResponseTransformer.java
- catalog/transformer/catalog-transformer-xml/pom.xml
- catalog/transformer/catalog-transformer-xml/src/main/java/ddf/catalog/transformer/api/MetacardMarshaller.java
- catalog/transformer/catalog-transformer-xml/src/main/java/ddf/catalog/transformer/api/PrintWriter.java
- catalog/transformer/catalog-transformer-xml/src/main/java/ddf/catalog/transformer/api/PrintWriterProvider.java
- catalog/transformer/catalog-transformer-xml/src/main/java/ddf/catalog/transformer/xml/EscapingPrintWriter.java
- catalog/transformer/catalog-transformer-xml/src/main/java/ddf/catalog/transformer/xml/MetacardMarshallerImpl.java
- catalog/transformer/catalog-transformer-xml/src/main/java/ddf/catalog/transformer/xml/PrintWriterProviderImpl.java
- catalog/transformer/catalog-transformer-xml/src/main/java/ddf/catalog/transformer/xml/XmlMetacardTransformer.java
- catalog/transformer/catalog-transformer-xml/src/main/java/ddf/catalog/transformer/xml/XmlResponseQueueTransformer.java
- catalog/transformer/catalog-transformer-xml/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/transformer/catalog-transformer-xml/src/test/java/ddf/catalog/transform/xml/IntegrationTest.java
- catalog/transformer/catalog-transformer-xml/src/test/java/ddf/catalog/transform/xml/TestEscapingPrintWriter.java
- catalog/transformer/catalog-transformer-xml/src/test/java/ddf/catalog/transform/xml/TestXmlMetacardTransformer.java
- catalog/transformer/catalog-transformer-xml/src/test/java/ddf/catalog/transform/xml/TestXmlResponseQueueTransformer.java
@kcwire @millerw8 @beyelerb @wmcnalli @coyotesqrl
- abstract and reuse xstream code as OSGI services.
- remove use of XStream facade.
- remove XStream walking object graph.
- multi-thread csw metacard marshalling.
- refine character/stream handling.
- lower unit test branch COVEREDRATIO b/c lack of other-code coverage skews build failure.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/163)
> DDF-1430 Optimize CSW Query transformation.

- catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/util/impl/FirstElementServiceSelectionStrategy.java
- catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/util/impl/ServiceSelectionStrategy.java
- catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/util/impl/ServiceSelector.java
- catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/util/impl/ServiceSelectorConverter.java
- catalog/core/catalog-core-api-impl/src/test/java/ddf/catalog/util/impl/TestServiceSelector.java
- catalog/spatial/geocoding/spatial-geocoding-geocoder/pom.xml
- catalog/spatial/geocoding/spatial-geocoding-geocoder/src/main/java/org/codice/ddf/spatial/geocoder/endpoint/GeoCoderEndpoint.java
- catalog/spatial/geocoding/spatial-geocoding-geocoder/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/spatial/geocoding/spatial-geocoding-geocoder/src/test/java/org/codice/ddf/spatial/geocoder/endpoint/TestGeoCoderEndpoint.java
- catalog/spatial/geocoding/spatial-geocoding-localsearch/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/spatial/geocoding/spatial-geocoding-websearch/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/spatial/spatial-app/src/main/resources/features.xml
- catalog/ui/search-ui/search-ui-app/src/main/resources/features.xml
Prior to this change, the webservice-gazetteer was being loaded as part of the
search-ui feature.  While the search-ui needs a gazetteer, the selection of a
specific gazetteer implementation should be left to configurations that are
loaded at a later time.  This change moves the gazetteer loading into the
install-profiles/*/features.xml.
@bdeining (Hero)
@kcwire 
@EIrwin
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/177)
> DDF-1493 Remove gazetteer feature from search-ui-app feature.

- distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestSecurity.java
Cleans up tokens a little bit and adds two new x509 validation tests to confirm that when a single cert is passed as a pkipath or a pkipath as a single cert, that validation fails.
@kcwire 
@tbatie Heroing this should really just be waiting for Bamboo to pass. It's only an itest change.
@jckilmer
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/216)
> DDF-1540 Adds two negative x509 validation itests.

- catalog/transformer/catalog-transformer-xml/src/main/java/ddf/catalog/transformer/xml/MetacardMarshallerImpl.java
- distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestFederation.java
The itests logs were getting filled with NPE's so dug into and found the root cause.  I also updated many of the assertions we make in the itests to be much more specific because looking for a string anywhere in the response is insufficient in many of the tests.
@lessarderic 
@coyotesqrl 
@pklinef
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/219)
> DDF-1430  - check for null argument map in MetcardMarshallerImpl

- catalog/spatial/csw/spatial-csw-source/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/source/CswSource.java
- catalog/spatial/csw/spatial-csw-source/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/source/TestCswSource.java
- catalog/spatial/csw/spatial-csw-source/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/source/TestCswSourceBase.java
Changed TestCswSourceBase.getGetRecordsTypeAsXml() to use the same CswJAXBElementProvider class CswSource is using and added the proper namespace on the typeNames attribute value Record to make the tests pass again.
Updated assertions that were inverting expected vs. actual.
Removed unused namespaces from expected requests, and switched default namespace to something more reasonable.
Disabled XMLUnit attribute order and comment validation.
Added more detailed output if the assertion is about to fail to help in case we run into other build failures.
Fixed compilation warnings.
@kcwire, @pklinef, @coyotesqrl please review.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/211)
> DDF-1528: TestCswSource test cases failing

- platform/security/common/src/main/java/org/codice/ddf/security/common/jaxrs/RestSecurity.java
- platform/security/common/src/test/java/org/codice/ddf/security/common/jaxrs/RestSecurityTest.java
- platform/security/rest/security-rest-cxfwrapper/src/main/java/org/codice/ddf/cxf/SecureCxfClientFactory.java
- platform/security/rest/security-rest-cxfwrapper/src/test/java/org/codice/ddf/cxf/SecureCxfClientFactoryTest.java
Setting the username and password on the HTTPConduit of the CXF client
periodically will not attach the authorization header to the outgoing
message. Adding the header directly to the client works.
@stustison @coyotesqrl @rzwiefel
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/231)
> DDF-1545 Add BASIC authorization header directly to CXF client

- platform/security/policy/security-policy-api/src/main/java/org/codice/ddf/security/policy/context/ContextPolicyManager.java
- platform/security/policy/security-policy-context/src/main/java/org/codice/ddf/security/policy/context/impl/PolicyManager.java
In rare cases (less rare in integration tests) configuration changes might occur while iterating over the policies. This causes a concurrent mod exception.
As a general rule, we should prefer copy collections in our codebase to avoid leakage.
@tbatie 
@rzwiefel
@roelens8
@lessarderic
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/223)
> DDF-1542 Returns a copy collection when retrieving PolicyManager context policies

- catalog/ui/search-ui/standard/src/main/webapp/js/view/Query.view.js
- Previously we were using the Math.ceil function during certain conversions.  This caused a significant loss of precision in both directions (view to model, and model to view).
- For the most part, this fixed the issue with the up / down arrows seen in https://codice.atlassian.net/browse/DDF-1513.  I went ahead and refactored the radiusConverter function to fix a seperate issue that cropped up, which was also related to precision.  Instead of always updating the view based on the model, the view is now only updated when the difference between view and model is greater than a certain threshold.  ~~I couldn't track down an example value (I searched cesium and ddf for thresholds, but couldn't find any references).~~   The threshold is based on a value I found in cesium.bbox.js (used for a …
> DDF-1512 Updates conversions to cause minimal loss of precision, fixes up / down arrows

- catalog/ui/search-ui/standard/src/main/webapp/js/model/Query.js
- catalog/ui/search-ui/standard/src/main/webapp/js/view/Query.view.js
- catalog/ui/search-ui/standard/src/main/webapp/templates/search/searchForm.handlebars
The “radiusValue” input field was receiving a default Backbone binding
because default bindings are assigned to elements with a name
attribute, and the input field had one. This binding overwrote the
value for the input field given by the binding for the hidden “radius”
field, which is the binding we want to control the view. Removing the
“radiusValue” input field’s name attribute prevents this default
binding from being instantiated.
This change required us to update the existing code that interacts with
the input field element to select it by id rather than by name.
@millerw8 is the hero
@beyelerb 
@stustison 
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/214)
> DDF-1539: Radius value is set correctly after a search

- catalog/transformer/catalog-transformer-tika-input/pom.xml
- catalog/transformer/catalog-transformer-tika-input/src/main/java/ddf/catalog/transformer/input/tika/TikaInputTransformer.java
@kcwire @jrnorth @bdeining 
- TikaInputTransformer should not rely on JRE/JDK implementation
of javax.xml.transform.TransformerFactory.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/233)
> DDF-1321 Use specific XML Transformer Factory.

- catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/util/impl/SourcePoller.java
- catalog/core/catalog-core-api/src/main/java/ddf/catalog/util/SourcePoller.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/CachingFederationStrategy.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/CatalogFrameworkImpl.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/resource/download/ReliableResourceDownloadManager.java
- catalog/core/catalog-core-standardframework/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/core/catalog-core-standardframework/src/main/resources/OSGI-INF/metatype/metatype.xml
- catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/event/retrievestatus/DownloadsStatusEventListenerTest.java
- catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/resource/download/ReliableResourceDownloadManagerTest.java
- catalog/docs/src/main/resources/ExtContents.adoc
- catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/controller/SearchController.java
- catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/endpoint/CometdEndpoint.java
- catalog/ui/search-ui/search-endpoint/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/ui/search-ui/search-endpoint/src/test/java/org/codice/ddf/ui/searchui/query/controller/SearchControllerTest.java
- catalog/ui/search-ui/search-endpoint/src/test/java/org/codice/ddf/ui/searchui/query/endpoint/CometdEndpointTest.java
- distribution/ddf-common/src/main/resources/etc/system.properties
- distribution/docs/src/main/resources/ManContents.adoc
- The default thread pool size is currently set to 128.
- Used system property for CachingFederationStrategy
- Use System Property for ReliableResourceDownloadManager
- Also updated the default thread pool size to be 128 for CachingFederationStrategy
- Removes setPoolSize method from CatalogFrameworkImpl, blueprint, and metatype
- Removes ability to set Federation Thread Pool Size from Admin UI.
- Removes setter from blueprint.
- Removes setPoolSize method from CatalogFrameworkImpl.  The pool is passed in through the constructor now.  Previously, the setPoolSize method wasn't actually doing anything.
- Updates ThreadPools of size 1 to be single threads
- While they are technically the same thing, this is more explicit.  This changes two instances of newScheduledThreadPools of size 1 to be …
> DDF-1515 Adds thread pool setting to system properties, updates various instances of thread pools

- catalog/core/catalog-core-federationstrategy/src/main/java/ddf/catalog/federation/impl/FifoFederationStrategy.java
- catalog/core/catalog-core-federationstrategy/src/main/java/ddf/catalog/federation/impl/SortedFederationStrategy.java
- catalog/core/catalog-core-standardframework/pom.xml
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/CachingFederationStrategy.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/SortedQueryMonitor.java
- catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/cache/solr/impl/SortedQueryMonitorTest.java
- catalog/spatial/csw/spatial-csw-source/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/source/CswSource.java
The old implementation calculated the timeout for each query at the time each source was checked. If a large number of queries against a large number of sources were queued up, this could lead to source being queried long past the time they should have timed out.
@pklinef 
@tbatie 
@roelens8 Hero this, please
@jckilmer
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/222)
> DDF-1546 Fixes federated query timeouts so they are measured from the start of the query.

- catalog/spatial/geocoding/spatial-geocoding-websearch/pom.xml
- catalog/spatial/geocoding/spatial-geocoding-websearch/src/main/java/org/codice/ddf/spatial/geocoder/geonames/GeoNamesWebService.java
The Geocoder endpoint previously used URLConnection, but this had a lot
of issues with response encoding. In order to avoid having to mask these
issues, it was replaced with CXF which doesn't have any of the issues.
@jrnorth  @kcwire @bdeining is hero
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/218)
> DDF-1530: Replaced URLConnection with CXF WebClient in GeocoderEndpoint

- platform/security/filter/security-filter-authorization/src/test/java/org/codice/ddf/security/filter/authorization/AuthorizationFilterTest.java
- platform/security/policy/security-policy-api/src/main/java/org/codice/ddf/security/policy/context/ContextPolicy.java
- platform/security/policy/security-policy-api/src/main/java/org/codice/ddf/security/policy/context/attributes/ContextAttributeMapping.java
- platform/security/policy/security-policy-api/src/main/java/org/codice/ddf/security/policy/context/attributes/DefaultContextAttributeMapping.java
- platform/security/policy/security-policy-context/src/main/java/org/codice/ddf/security/policy/context/impl/Policy.java
- platform/security/policy/security-policy-context/src/main/java/org/codice/ddf/security/policy/context/impl/PolicyManager.java
- platform/security/policy/security-policy-context/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- platform/security/policy/security-policy-context/src/main/resources/OSGI-INF/metatype/metatype.xml
- platform/security/policy/security-policy-context/src/test/java/org/codice/security/policy/context/PolicyManagerTest.java
Web Context Policy Manager settings are complex and require a one-to-one mapping between all fields
- Created maps for attributes, context realms and authorizations to perform roll backs if necessary before setting the policy manager
- Made policy manager thread safe by returning a copy of the policy store and by creating copies of any policy to be added
@jckilmer @rzwiefel  @roelens8 @coyotesqrl @ryeats
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/238)
> DDF-1510 Web Context Policy Manager settings are complex and require a one-to-one mapping between all fields

- platform/security/idp/security-idp-client/pom.xml
- platform/security/idp/security-idp-client/src/main/java/org/codice/ddf/security/idp/client/AssertionConsumerService.java
- platform/security/idp/security-idp-client/src/main/java/org/codice/ddf/security/idp/client/IdpHandler.java
- platform/security/idp/security-idp-client/src/main/java/org/codice/ddf/security/idp/client/RelayStates.java
- platform/security/idp/security-idp-client/src/main/resources/OSGI-INF/blueprint/blueprint.xml
Relay state cannot exceed 80 characters and it should not leak
information about the user action.  Relay state is now a GUID that
can be used to lookup the original redirect url after the user has
successfully logged into the IdP.  Relay state will expire if the
user does not return.
@coyotesqrl @rzwiefel @ryeats
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/265)
> DDF-1519 Encode relay state before sending to IdP

- distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/AbstractIntegrationTest.java
We see an intermittent failure with itests where the entire pax exam setup fails, causing all tests in a class to fail. Errors have been seen in the osgi code when it attempts to create periodic backups of the `.bundlefile` in `${ddf.home}/data/cache/org.eclipse.osgi`.
Working on the supposition that pax can explode the exam directly successfully but that on slow boxes the background backup thread may start too soon, this will turn off those periodic backups. They are not necessary for itests; this will have either a positive or neutral effect.
It is possible that this is only a symptom of a more basic problem exploding the exam folder in which case this will merely shift the error.
===
Assuming this passes Bamboo without exam setup failures...I'll re-run the CI build multiple times to …
> DDF-1572 Shuts off periodic bundlefile backups for itest exam folders.

- distribution/test/itests/test-itests-catalog/pom.xml
- distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestCatalog.java
An issue has been found during a demo in a production environment where attempting to save a large workspace fails with an error. This is caused by Lucene, which changed its behavior from logging and ignoring a too-large field to throwing an error if a field of >32776 bytes is indexed. We should not be indexing the data we put in the persistent store, but are for now. Two tests are added here: one with a small data size and one too large; the latter has been marked Ignored for now.
@kcwire 
@tbatie - Please hero this
@jckilmer
@ryeats
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/264)
> DDF-1571 Adds integration tests for persisting to workspace.

- distribution/ddf-common/src/main/resources/etc/system.properties
- distribution/test/itests/pom.xml
- distribution/test/itests/test-itests-catalog/pom.xml
- distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/AbstractIntegrationTest.java
- distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestSecurity.java
- distribution/test/pom.xml
- distribution/test/thirdparty/rest-assured/pom.xml
- platform/security/sts/security-sts-pkivalidator/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- platform/security/sts/security-sts-server/pom.xml
- platform/security/sts/security-sts-server/src/main/java/ddf/security/sts/SubjectDNConstraintsInterceptor.java
- platform/security/sts/security-sts-server/src/main/resources/META-INF/sts/wsdl/ws-trust-1.4-service.wsdl
- platform/security/sts/security-sts-server/src/main/resources/OSGI-INF/blueprint/cxf-sts.xml
-Added a system property that allow admins to set the STS Subject DN Constraints. By default it is ".*".
-Some of the security itests now use authorization
Reviewers: 
@stustison @djblue @clockard @ricklarsen @gordocanchola
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/267)
> DDF-1532:Makes Subject DN Constraints Configurable

- catalog/ui/search-ui/standard/src/main/webapp/js/model/Notification.js
- catalog/ui/search-ui/standard/src/main/webapp/js/module/Notification.module.js
The CometD listener attempts to parse the returned notification as a JSON string, but it’s actually a JSON object. Notifications have been returned as JSON objects since DDF-1415.
@EIrwin is the hero
@kcwire 
@beyelerb
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/275)
> DDF-1580: Remove notification parsing in CometD listener

- distribution/test/itests/test-itests-common/src/test/java/ddf/common/test/AdminConfig.java
Added null parameter to getConfiguration() calls to make sure Configuration objects
are never bound to the itest bundle.
Hero: @figliold  
Reviewers: @andrewkfiedler, @garrettfreibott  
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/282)
> DDF-1594: AdminConfig could bind Configuration objects to the itest bundle

- distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/AbstractIntegrationTest.java
Added installStartupFile() method and created ddfHome static field.
Hero: @garrettfreibott 
Reviewers: @andrewkfiedler, @figliold 
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/281)
> DDF-1593: Add ability to copy test file before itests are run

- platform/security/handler/security-handler-pki/src/main/java/org/codice/ddf/security/handler/pki/AbstractPKIHandler.java
- platform/security/handler/security-handler-pki/src/main/java/org/codice/ddf/security/handler/pki/CrlChecker.java
- platform/security/handler/security-handler-pki/src/test/java/org/codice/ddf/security/handler/pki/PKIHandlerTest.java
- Modified the CrlChecker to return an error message when the user
attempts to access a web context with a revoked certificate.
Previously, the user was presented with a blank page.
- Removed httpResponse from some CrlChecker methods that were
no longer needed after this change.
- Modified the unit tests to reflect these method changes.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/280)
> DDF-1592: Return Error Message For Revoked Certs

- platform/security/core/security-core-impl/src/main/java/ddf/security/http/impl/HttpSessionFactory.java
- platform/security/core/security-core-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- platform/security/filter/security-filter-login/src/main/java/org/codice/ddf/security/filter/login/LoginFilter.java
- platform/security/filter/security-filter-login/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- platform/security/filter/security-filter-login/src/test/java/org/codice/ddf/security/filter/login/LoginFilterTest.java
- platform/security/handler/security-handler-saml/src/main/java/org/codice/ddf/security/handler/saml/SAMLAssertionHandler.java
- platform/security/handler/security-handler-saml/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- platform/security/idp/security-idp-client/src/main/java/org/codice/ddf/security/idp/client/AssertionConsumerService.java
- platform/security/idp/security-idp-client/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- platform/security/platform-security-core-api/src/main/java/ddf/security/http/SessionFactory.java
Replace use of String literal global lock with a HTTP service creation OSGi service.
https://github.com/codice/ddf/search?utf8=%E2%9C%93&q=%22org.codice.ddf.security.NewHttpSession%22
1. Build new interface/impl/bundle _with tests_
2. Add to platform/security/core
3. Add to feature
4. Inject service to the bundles associated with the three linked classes
5. Remove interned String locks from three linked classes and use the new service
@rzwiefel @coyotesqrl @roelens8 @pklinef
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/283)
> DDF-1586:Create a HTTP session creation OSGi service

- catalog/ui/search-ui/standard/bower.json
- catalog/ui/search-ui/standard/src/main/webapp/js/model/Query.js
- catalog/ui/search-ui/standard/src/main/webapp/js/view/Query.view.js
- catalog/ui/search-ui/standard/src/main/webapp/templates/search/searchForm.handlebars
- catalog/ui/search-ui/standard/src/test/js/wd/usng.js
-Switching from USNG to Lat Lon would not properly update the Lat Lon values.
The template now looks to the 'map' version of these variables as opposed to
the raw versions. This continues the migration from 'north' -> 'mapNorth'
that was started in these USNG changes. The raw variables just track where the
cursor is and does not decide what is shown on the map or what is searched.
-Updated search function to use the 'map' versions of variables. Silently sets
the raw variables to the 'map' variables to not trigger a redraw but to affect
other code as little as possible - best not to percolate the 'map' change, except
where needed.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/274)
> DDF-1543 Fix USNG to LL switch and search bug

- platform/security/rest/security-rest-cxfwrapper/src/main/java/org/codice/ddf/cxf/SecureCxfClientFactory.java
@kcwire 
@wmcnalli hero
@bdeining 
This is a quick fix only, implemented as another constructor that takes username,password strings and sets them on the factory.  
Successfully built with:
mvn -pl :security-rest-cxfwrapper clean install
No other code in ddf currently uses this new constructor.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/292)
> DDF-1603 Quick fix to enable basic auth on redirects.

- README.md
The Travis-CI badge has reflected a state of failing for quite some time so figured it was time to at least remove that and advertise Gitter at the same time. I would love to find a way to get our bamboo badge on there as mentioned on the ticket.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/295)
> DDF-1604 added Gitter badge and removed Travis-ci badge

- catalog/ui/search-ui/standard/src/main/webapp/js/view/Workspace.view.js
Fixed a bug where saved searches in a workspace in the search ui could not be edited. I saw all of the unit tests in catalog/ui/search-ui/standard successfully pass.
@tbatie
@harrison-tarr
@rzwiefel
@coyotesqrl
@roelens8
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/289)
> DDF-1577 Editing saved searches in a workspace

- catalog/ui/search-ui/standard/src/main/webapp/js/view/Menu.view.js
Search UI was using blank username and password and not correctly removing the basic auth header on logout from the LDAP realm. The Admin UI was not invalidating at all.
@pklinef 
@tbatie 
@jckilmer
@rzwiefel
@roelens8
@ryeats
@tbatie will hero.
To hero, change to LDAP realm and logout.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/297)
> DDF-1613 Basic auth header invalidation requires non-blank username/password.

- distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestCatalog.java
- distribution/test/itests/test-itests-common/src/test/java/ddf/common/test/WaitCondition.java
Added generic class that waits for a certain condition to be met or a timeout to occurs.
Updated TestCatalog class to use the new `WaitCondition` class.
Our goal here should be to come up with a generic way to do waits in our itests, use it moving forward and eventually replace the existing waits we have with this. Please review thoroughly. New ideas and suggestions are welcome :-)
Reviewers:
* @coyotesqrl 
* @pklinef 
* @brendan-hofmann 
* @kcwire 
* @andrewkfiedler 
* @oconnormi 
* @figliold 
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/285)
> DDF-1600: Provide a generic wait framework for integration tests

- platform/security/handler/security-handler-saml/src/main/java/org/codice/ddf/security/handler/saml/SAMLAssertionHandler.java
This ticket needs to be back-ported to DDF SNAPSHOT-2.8.0.
There is currently a bug in SAMLAssertionHandler that adds SAML assertions to every request coming in when it's not needed. This noticeably slows down the performance of the system. 
@coyotesqrl @tbatie @rzwiefel @ryeats @pklinef
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/301)
> DDF-1616 SAMLAssertionHandler checks session when using basic authentication

- catalog/ui/search-ui/standard/pom.xml
- catalog/ui/search-ui/standard/src/test/js/wd/search.js
- catalog/ui/search-ui/standard/src/test/js/wd/shared.js
- catalog/ui/search-ui/standard/src/test/js/wd/usng.js
- catalog/ui/search-ui/standard/src/test/js/wd/workspaces.js
- Updates pom.xml to no longer use force when running grunt.  Now if a test failures, the build will fail.
- Updates a search test to use waitForConditionInBrowser to avoid a caching of an element that was becoming stale.
- Updates the usng tests to not use a refresh following each individual test case.  Now, a change event is triggered after changing values in order to make the tests work.
- Adds a stack trace to test failures, saves a screenshot as well in the images/failures folder.
- Aborts test suite following any failure.
- Adds a flag (--iterations) that can be passed to grunt in order to run each test a certain number of times.  This is useful for stability testing.  As a result, all the test suites are wrapped in a for loop (this caused the formatting to change for each suite). …
> DDF-1607 Fixes intermittant UI Test Failures

- distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestSecurity.java
- distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestXACML.java
- platform/security/core/security-core-impl/src/main/java/ddf/security/common/util/SecurityTokenHolder.java
- platform/security/core/security-core-impl/src/main/java/ddf/security/http/impl/HttpSessionFactory.java
- platform/security/core/security-core-impl/src/test/java/ddf/security/common/util/SecurityTokenHolderTest.java
- platform/security/filter/security-filter-login/src/main/java/org/codice/ddf/security/filter/login/LoginFilter.java
- platform/security/filter/security-filter-login/src/test/java/org/codice/ddf/security/filter/login/LoginFilterTest.java
- platform/security/handler/security-handler-saml/src/main/java/org/codice/ddf/security/handler/saml/SAMLAssertionHandler.java
- platform/security/handler/security-handler-saml/src/test/java/org/codice/ddf/security/handler/saml/SAMLAssertionHandlerTest.java
- platform/security/servlet/security-servlet-logout/pom.xml
- platform/security/servlet/security-servlet-logout/src/main/java/org/codice/ddf/security/servlet/logout/LogoutServlet.java
- platform/security/servlet/security-servlet-logout/src/test/java/org/codice/ddf/security/servlet/logout/TestLogoutServlet.java
- platform/security/sts/security-sts-upbstvalidator/src/main/java/org/codice/ddf/security/validator/uname/UPBSTValidator.java
- platform/security/sts/security-sts-upbstvalidator/src/test/java/org/codice/ddf/security/validator/uname/UPBSTValidatorTest.java
- platform/security/sts/security-sts-usernametokenvalidator/src/main/java/org/codice/ddf/security/validator/username/UsernameTokenValidator.java
- platform/security/sts/security-sts-usernametokenvalidator/src/test/java/org/codice/ddf/security/validator/username/TestUsernameTokenValidator.java
Users used to have the ability to login to one realm and gain access to all other realms, but this wasn't correct. Once a user logs in to a particular realm, he now only has access to that realm. (Example: If User Admin logs into search UI over the ldap realm, he does't have access to the Admin UI over the karaf realm) Also note that when a users logs out, all other users are also logged out of their realms.
For more info: https://codice.atlassian.net/browse/DDF-1597
Instructions to hero PR:
1. Install OpenDJEmbedded app
2. Set the following web contexts in the Web Context Policy Manager which are required for ldap to work:
/search=ldap
/cometd=ldap
/services=ldap
/logout=ldap
2. Set the Authentication type to: SAML | basic
3. Install the ldap features: security-sts-ldapclaimshandler and …
> DDF-1597 Authenticating against one realm now allows access to only that realm.

- distribution/docs/src/main/resources/ManContents.adoc
- distribution/test/itests/test-itests-catalog/pom.xml
- platform/security/encryption/platform-security-encryption-commands/src/main/java/ddf/security/command/EncryptCommand.java
- platform/security/encryption/platform-security-encryption-commands/src/test/java/ddf/security/command/EncryptCommandTest.java
- platform/security/encryption/platform-security-encryption-impl/pom.xml
- platform/security/encryption/platform-security-encryption-impl/src/main/java/ddf/security/encryption/impl/EncryptionServiceImpl.java
- platform/security/encryption/platform-security-encryption-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- platform/security/encryption/platform-security-encryption-impl/src/test/java/ddf/security/encryption/impl/EncryptionServiceImplTest.java
- platform/security/sts/security-sts-ldapclaimshandler/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- platform/security/sts/security-sts-ldapclaimshandler/src/main/resources/OSGI-INF/metatype/metatype.xml
- platform/security/sts/security-sts-ldapclaimshandler/src/test/java/ddf/security/sts/claimsHandler/ClaimsHandlerManagerTest.java
- platform/security/sts/security-sts-ldaplogin/src/main/resources/OSGI-INF/blueprint/karaf_ldap_config.xml
- platform/security/sts/security-sts-ldaplogin/src/main/resources/OSGI-INF/metatype/metatype.xml
- platform/security/sts/security-sts-ldaplogin/src/test/java/ddf/ldap/ldaplogin/LdapLoginConfigTest.java
- pom.xml
-Encryption service now uses Keyczar's api for encryption and decryption
-Encryption console command now outputs the encrypted password with the ENC wrapping
-Fixes up unit tests to work with the Keyczar encryption/decryption
@djblue will hero. 
@clockard @oscaritoro @stustison
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/300)
> DDF-1595: Changes encrypt/decrypt to use Keyczar

- platform/security/idp/security-idp-client/src/test/java/org/codice/ddf/security/idp/client/AssertionConsumerServiceTest.java
@roelens8 @coyotesqrl @tbatie(hero) @rzwiefel @stustison
> DDF-1627 added unit tests for all of the idp failure responses to the security-idp-client

- distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/AbstractIntegrationTest.java
- distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestCatalog.java
- distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestFanout.java
- distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestFederation.java
- distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestSecurity.java
- distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestSolrCommands.java
- distribution/test/itests/test-itests-catalog/src/test/resources/ddf.security.sts.client.configuration.cfg
Port numbers and URLs based thereon were declared as finals in
AbstractIntegrationTest. These are now dynamically allocated
based on what ports are in use. Test files had to be changed to
load in the new port numbers instead of using the class defaults.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/287)
> DDF-1601 Implement dynamic port allocation

- pom.xml
Summary of changes
* added scm server for github, this needs to be set in maven settings!
* updated scm tag settings (url/connection/developerconnection/tag)
* fixed passing arguments to the release plugin
* allowed release plugin to push tag changes
* updated checkstyle plugin for reports profile to 2.15
The scm tag settings may need to be changed.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/308)
> DDF-1620: Updated pom for automated release

- catalog/ui/search-ui/search-endpoint/pom.xml
- catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/controller/ActivityController.java
- catalog/ui/search-ui/search-endpoint/src/test/java/org/codice/ddf/ui/searchui/query/controller/ActivityControllerTest.java
- catalog/ui/search-ui/standard/src/main/webapp/js/model/Task.js
- catalog/ui/search-ui/standard/src/main/webapp/js/module/Tasks.module.js
-New activities were published on a CometD channel that was not being subscribed to in the Search UI. Fixed by publishing the Activities on an appropriate CometD channel.
-Add unit tests for ActivityController.
-Activities returned via CometD were being parsed as JSON strings, but the Activities are actually JSON objects. The returned Activities are no longer treated as JSON strings.
-Simplified the logic in the JavaScript Task model for extracting operations that don't have predefined actions.
-Activities' timestamps were being parsed as integers, but they are actually ISO 8601 strings. The timestamps are no longer parsed as integers.
@EIrwin is the hero
@kcwire 
@jlcsmith
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on …
> DDF-1581: Fix Activity/Task handling in the Search UI

- catalog/core/catalog-core-solr/pom.xml
- catalog/core/catalog-core-standardframework/pom.xml
- catalog/solr/catalog-solr-embedded-provider/pom.xml
- catalog/solr/catalog-solr-external-provider/pom.xml
- catalog/solr/catalog-solr-external-provider/src/main/resources/META-INF/services/javax.xml.stream.XMLInputFactory
- catalog/ui/search-ui/search-endpoint/pom.xml
- catalog/ui/search-ui/search-endpoint/src/main/resources/META-INF/services/javax.xml.stream.XMLInputFactory
- platform/solr/platform-solr-server-standalone/pom.xml
- pom.xml
This causes an indeterminate version to be selected at runtime, sometimes resulting in errors interacting with Lux.
@pklinef 
@tbatie Please hero this
@ryeats
@stustison
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/323)
> DDF-1640 Incorrectly configured Woodstox dependency configuration.

- catalog/admin/module/catalog-admin-module-sources/src/main/webapp/js/model/Service.js
- catalog/admin/module/catalog-admin-module-sources/src/main/webapp/js/model/Source.js
- catalog/admin/module/catalog-admin-module-sources/src/main/webapp/js/view/ModalSource.view.js
- catalog/admin/module/catalog-admin-module-sources/src/main/webapp/js/view/Source.view.js
- catalog/admin/module/catalog-admin-module-sources/src/main/webapp/templates/deleteSource.handlebars
- platform/admin/core/admin-core-api/src/main/java/org/codice/ddf/ui/admin/api/ConfigurationAdmin.java
Could create duplicate service configurations of the same type under
the same Source name
Could not create multiple service configurations of different types
under the same Source name
DDF-1633 Add "delete source" check
Deleting each service config was getting annoying during debugging
so I added the ability to delete all configs. This should be useful
to admins irl too.
DDF-1633 Allow editing a disabled source
ConfigurationAdmin would only match a metatype if it was enabled
now it will match in both case and allow updating
DDF-1633 Fix delete source
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/328)
> DDF-1633 Fix Admin UI source tab bugs

- libs/activities/pom.xml
- libs/notifications/pom.xml
During a routine scan of poms for cruft, these two blocks were found.
@pklinef 
@tbatie 
@jckilmer
@ryeats
Jason, please hero.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/335)
> DDF-1653 Removes erroneous instructions blocks from pom files.

- platform/admin/core/admin-core-api/src/main/java/org/codice/ddf/ui/admin/api/ConfigurationAdmin.java
- platform/admin/core/admin-core-api/src/main/java/org/codice/ddf/ui/admin/api/ConfigurationAdminMBean.java
- platform/admin/ui/src/main/webapp/css/style.css
- platform/admin/ui/src/main/webapp/index.html
- platform/admin/ui/src/main/webapp/js/application.js
- platform/admin/ui/src/main/webapp/js/controllers/Feature.controller.js
- platform/admin/ui/src/main/webapp/js/models/Alerts.js
- platform/admin/ui/src/main/webapp/js/models/Service.js
- platform/admin/ui/src/main/webapp/js/views/Alerts.view.js
- platform/admin/ui/src/main/webapp/js/views/application/Application.view.js
- platform/admin/ui/src/main/webapp/js/views/application/ApplicationGrid.view.js
- platform/admin/ui/src/main/webapp/js/views/configuration/ConfigurationEdit.view.js
- platform/admin/ui/src/main/webapp/js/views/installer/AnonClaims.view.js
- platform/admin/ui/src/main/webapp/less/configuration/style.less
- platform/admin/ui/src/main/webapp/main.js
- platform/admin/ui/src/main/webapp/templates/alerts.handlebars
- platform/admin/ui/src/main/webapp/templates/configuration/configurationEdit.handlebars
@djblue @AzGoalie @harrison-tarr @andrewkfiedler @stustison 
@clockard will hero
There are a couple of things you can do to manually try this out. In chrome, you can open a config to edit in the admin ui, then hit `/logout` in a separate  tab and try to save the configuration. You should get an error because you no longer have admin privileges to hit jolokia. You can also hook up a debugger and interfere on the backend to cause an exception to be thrown when the config is saved. This has the additional benefit of showing off the new spinner while the backend is suspended.
If any errors occur, they look something like this (`Forbidden` gets a special message):
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on …
> DDF-1612 Add error reporting for config editing in Admin UI

- platform/security/idp/security-idp-client/src/main/java/org/codice/ddf/security/idp/client/AssertionConsumerService.java
- platform/security/idp/security-idp-client/src/test/java/org/codice/ddf/security/idp/client/AssertionConsumerServiceTest.java
- platform/security/idp/security-idp-server/pom.xml
- platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/server/IdpEndpoint.java
- platform/security/idp/security-idp-server/src/test/java/org/codice/ddf/security/idp/server/IdpEndpointTest.java
- metadata no longer contains an invalid logout url
The createIdpMetadata method has a `isNotBlank` check to correctly deal with the null.
@pklinef @coyotesqrl @stustison
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/339)
> DDF-1605 - Fixed the IdP Server Logout Metadata

- catalog/ui/search-ui/simple/src/main/webapp/templates/recordContents.hbt
(Metacards without Created or Modified Date are now shown properly).
@wmcnalli 
@shane-voisard
@dcruver is hero
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/325)
> DDF-1643 Fixed Simple Search UI 

- distribution/docs/src/main/resources/ManContents.adoc
Including config.adoc[] files only work at head of file.
@pklinef @vinamartin @djblue @stustison @clockard
> DDF-1670: removed incorrect include statement in Managing documentation.

- platform/admin/ui/src/main/webapp/js/models/Service.js
- platform/admin/ui/src/main/webapp/js/views/configuration/ConfigurationEdit.view.js
@brendan-hofmann @andrewkfiedler @djblue 
@ahoffer is hero
To hero: 
1) Build normally
2) Edit a `metatype.xml` file with a boolean value and remove the `default` attribute from one of the `Attribute Descriptor` tags. 
3) Rebuild the module that includes that metatype.
4) Attempt to edit the configuration that corresponds to your edited metatype. Just open and save.
5) If it saved properly, it worked. If you get an error, it didn't.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/345)
> DDF-1660 Convert falsey boolean values to false

- platform/admin/ui/src/main/webapp/js/views/configuration/ConfigurationEdit.view.js
If someone imports a config that doesn't have a setting,
it can give an undefined boolean which causes issues. This
is now fixed
This is an additional bug fix that came up after the fact for https://github.com/codice/ddf/pull/345/
@jckilmer @andrewkfiedler @stustison
> DDF-1660 Fix bug with config

- distribution/docs/src/main/resources/ManContents.adoc
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestPlatform.java
- platform/platform-commands/pom.xml
- platform/platform-commands/src/main/java/org/codice/ddf/commands/platform/ExportCommand.java
- platform/platform-commands/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- platform/platform-configuration-listener/pom.xml
- platform/platform-configuration-listener/src/main/java/org/codice/ddf/configuration/store/ConfigurationFile.java
- platform/platform-configuration-listener/src/main/java/org/codice/ddf/configuration/store/ConfigurationFileDirectory.java
- platform/platform-configuration-listener/src/main/java/org/codice/ddf/configuration/store/ConfigurationFileFactory.java
- platform/platform-configuration-listener/src/main/java/org/codice/ddf/configuration/store/ConfigurationMigrationService.java
- platform/platform-configuration-listener/src/main/java/org/codice/ddf/configuration/store/ManagedServiceConfigurationFile.java
- platform/platform-configuration-listener/src/main/java/org/codice/ddf/configuration/store/ManagedServiceFactoryConfigurationFile.java
- platform/platform-configuration-listener/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- platform/platform-configuration-listener/src/test/java/org/codice/ddf/configuration/store/ConfigurationFileDirectoryTest.java
- platform/platform-configuration-listener/src/test/java/org/codice/ddf/configuration/store/ConfigurationFileFactoryTest.java
- platform/platform-configuration-listener/src/test/java/org/codice/ddf/configuration/store/ConfigurationFileTest.java
- platform/platform-configuration-listener/src/test/java/org/codice/ddf/configuration/store/ManagedServiceConfigurationFileTest.java
- platform/platform-configuration-listener/src/test/java/org/codice/ddf/configuration/store/ManagedServiceFactoryConfigurationFileTest.java
- platform/pom.xml
- Adds platform:config-export command to CLI
- Adds exportConfig method to ConfigurationFile
- Adds builder to ConfigurationFile (and subclasses)
- Adds ConfigurationMigrationService interface, which ConfigurationFileDirectory now implements.  It adds an export method to ConfigurationFileDirectory, which writes out current ConfigurationAdmin configurations to the {ddf.home}/etc/exported directory for now (can be changed through blueprint).
> DDF-1672 Adds CLI command to export configurations

- catalog/catalog-app/src/main/resources/features.xml
- catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/data/impl/AttributeImpl.java
- catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/data/impl/BasicTypes.java
- catalog/core/catalog-core-api-impl/src/test/java/ddf/catalog/data/impl/MetacardImplTest.java
- catalog/core/catalog-core-api/pom.xml
- catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/SolrFilterDelegate.java
- catalog/plugin/catalog-plugin-metacard-validation/pom.xml
- catalog/plugin/catalog-plugin-metacard-validation/src/main/java/ddf/catalog/metacard/validation/MetacardValidityCheckerPlugin.java
- catalog/plugin/catalog-plugin-metacard-validation/src/main/java/ddf/catalog/metacard/validation/MetacardValidityMarkerPlugin.java
- catalog/plugin/catalog-plugin-metacard-validation/src/main/java/ddf/catalog/metacard/validation/ValidationQueryDelegate.java
- catalog/plugin/catalog-plugin-metacard-validation/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/plugin/catalog-plugin-metacard-validation/src/main/resources/OSGI-INF/metatype/metatype.xml
- catalog/plugin/catalog-plugin-metacard-validation/src/test/java/ddf/catalog/metacard/validation/MetacardValidityCheckerPluginTest.java
- catalog/plugin/catalog-plugin-metacard-validation/src/test/java/ddf/catalog/metacard/validation/MetacardValidityMarkerPluginTest.java
- catalog/plugin/pom.xml
- catalog/transformer/catalog-transformer-tika-input/src/main/java/ddf/catalog/transformer/input/tika/TikaInputTransformer.java
- distribution/sdk/pom.xml
- distribution/sdk/sample-metacard-validator/pom.xml
- distribution/sdk/sample-metacard-validator/src/main/java/org/codice/ddf/sdk/validation/metacard/SampleMetacardValidator.java
- distribution/sdk/sample-metacard-validator/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- distribution/sdk/sample-metacard-validator/src/test/java/org/codice/ddf/sdk/validation/metacard/SampleMetacardValidatorTest.java
- distribution/sdk/sdk-app/src/main/resources/features.xml
- distribution/test/itests/test-itests-ddf/pom.xml
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalog.java
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFederation.java
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/common/CswQueryBuilder.java
Added a pre-ingest plugin to validate and mark metacards as invalid
or valid.
Added a pre-query plugin to check the query and if it is missing a
'valid-state' parameter, add `valid-state=true`.
Added a sample metacard validator to use for testing.
Edited metacard to allow setting metacards as invalid
@michaelmenousek @pklinef @brendan-hofmann @beyelerb
> DDF-1698 Mark invalid metacards as invalid

- platform/security/sts/security-sts-pkivalidator/src/main/java/org/codice/ddf/security/validator/pki/PKITokenValidator.java
- platform/security/sts/security-sts-pkivalidator/src/main/resources/OSGI-INF/metatype/metatype.xml
…subject cert instead of always validating the entire path
@pklinef @kcwire
> DDF-1716 updated pki validator to also allow for only validating the

- catalog/ui/search-ui/standard/src/test/js/wd/search.js
This change addresses test failures that were appearing on
VM environments with low CPU allocations.  The test was
proceeding before required DOM elements were rendered. This
change causes the test to wait for the required DOM element
before it tries to proceed.
@bdeining
> ddf-1708 intermittent test failures during build

- catalog/ui/search-ui/standard/src/main/webapp/js/view/filter/FilterItem.view.js
- catalog/ui/search-ui/standard/src/main/webapp/js/widgets/cesium.bbox.js
(mapped to mapN/S/E/W instead of N/S/E/W)
Relaxed the Epsilon for North/South East/West equality.  This was causing errors in the Advanced Search with 2d maps.
@wmcnalli 
@kcwire 
@shane-voisard is hero
@jrnorth
> DDF-1706 Fixed Advanced search UI BBOX and Geos 

- .gitignore
- distribution/ddf-common/src/main/resources/etc/certs/CertNew.sh
- platform/security/certificate/security-certificate-generator/pom.xml
- platform/security/certificate/security-certificate-generator/src/main/java/org/codice/ddf/security/certificate/generator/CertificateCommand.java
- platform/security/certificate/security-certificate-generator/src/main/java/org/codice/ddf/security/certificate/generator/CertificateGenerator.java
- platform/security/certificate/security-certificate-generator/src/main/java/org/codice/ddf/security/certificate/generator/CertificateGeneratorMBean.java
- platform/security/certificate/security-certificate-generator/src/main/java/org/codice/ddf/security/certificate/generator/KeyStoreFile.java
- platform/security/certificate/security-certificate-generator/src/test/java/org/codice/ddf/security/certificate/generator/CertificateGeneratorTest.java
- platform/security/certificate/security-certificate-generator/src/test/java/org/codice/ddf/security/certificate/generator/KeyStoreFileTest.java
CertNew.sh generates certificate signed by Demo CA and installs it in the server keystore
Shader plugin creates self-contained JAR used by script.
* The script usage is in the comments. To try it out, change to <DDF_HOME>/etc/keystores and 
* execute **sh CertNew.sh** create certs using your hostname
* execute **sh CertNew.sh <i>name</i> to create certs using what name you want.
* I didn't parameterize the script much for two reasons. First, I didn't want the user to be to have to figure out a bunch of stuff just to get going. Second, I didn't want to spend time building in flexibility that wasn't going to be use. Have a look and add comments if you think it would work differently.
* The automatically removes the keystore entry for *localhost* because it's presence can cause problems.
* …
> DDF-1695 script-generate-certs

- platform/admin/ui/src/main/webapp/js/views/configuration/ConfigurationEdit.view.js
- Previously, the modal('hide') method was being called on the incorrect element.
> DDF-1741 Updates save method to correctly dismiss modal

- catalog/ui/search-ui/standard/Gruntfile.js
- catalog/ui/search-ui/standard/package.json
- platform/admin/ui/Gruntfile.js
- platform/admin/ui/package.json
- platform/security/certificate/security-certificate-adminmodule/Gruntfile.js
- platform/security/certificate/security-certificate-adminmodule/package.json
- platform/security/security-admin-module/Gruntfile.js
- platform/security/security-admin-module/package.json
- The "Newer" plugin is designed to try and save time by only running a grunt task if there are changes or if the task has never been run before.  It relies on the task having src and destination files, comparing their modified times to determine if the task needs to run.  Because we compose our "less" files out of other "less" files by using the "import" command, our "less" compilation task only specifies a single source file.  This source file never really changes.  As a result, the recompilation will only occur if the destination file doesn't exist.  As such, changes to the imported "less" files are not being picked up.
> DDF-1693 Removes grunt "Newer" plugin

- platform/security/idp/security-idp-client/src/main/java/org/codice/ddf/security/idp/client/AssertionConsumerService.java
- platform/security/idp/security-idp-client/src/test/java/org/codice/ddf/security/idp/client/AssertionConsumerServiceTest.java
- platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/server/IdpEndpoint.java
- platform/security/idp/security-idp-server/src/test/java/org/codice/ddf/security/idp/server/IdpEndpointTest.java
@gordocanchola can hero (run build)
> DDF-1742 restricted SAML responses to only be valid over a secure channel

- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestPlatform.java
- platform/platform-commands/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- platform/platform-configuration-migration/src/main/java/org/codice/ddf/configuration/admin/ConfigurationAdminMigration.java
- platform/platform-configuration-migration/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- Blueprints were updated to turn ddf.home into a standard URI
before resolving directories using Path.
- Commands blueprint was also updated for this reason.
- TestPlatform itests were modified to use deleteQuietly to avoid
throwing an exception if the directory was already removed by a
previous itest.
@lessarderic @andrewkfiedler @figliold @oconnormi @bantillo
> DDF-1731: Update Blueprints and iTests

- platform/security/certificate/security-certificate-generator/src/main/java/org/codice/ddf/security/certificate/generator/PkiTools.java
Instruct developer or tester to check the hosts file
if Java cannot determine the machine's hostname while
generating demo certificates
@stustison Pls review and merge at your convenience.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codice/ddf/422)
> DDF-1758 Improved error message

- catalog/ui/search-ui/standard/src/main/webapp/js/model/Filter.js
- catalog/ui/search-ui/standard/src/main/webapp/js/model/Query.js
- catalog/ui/search-ui/standard/src/main/webapp/js/widgets/cesium.bbox.js
- catalog/ui/search-ui/standard/src/main/webapp/properties.js
Fixed the Advanced Search Bounding Box that was broken by changes made to cesium.bbox.js
Fixed the Properties.filter.ANY_GEO change that breaks multiple geo cql filtering
Fixed array boundaries (N/S and E/W equality) on 2d map
@dcruver is hero
@kcwire 
@stustison
> DDF-1706 Fixed Advanced Search UI BBox drawing

- platform/security/core/security-core-impl/src/main/java/ddf/security/samlp/impl/LogoutMessageImpl.java
- platform/security/core/security-core-impl/src/main/java/ddf/security/samlp/impl/SamlValidator.java
- platform/security/core/security-core-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- platform/security/core/security-core-impl/src/test/groovy/ddf/security/samlp/impl/LogoutMessageSpec.groovy
- platform/security/core/security-core-impl/src/test/groovy/ddf/security/samlp/impl/SamlValidatorBuilderTest.groovy
- platform/security/idp/security-idp-client/src/main/java/org/codice/ddf/security/idp/client/LogoutRequestService.java
- platform/security/idp/security-idp-client/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- platform/security/idp/security-idp-client/src/test/java/org/codice/ddf/security/idp/client/LogoutRequestServiceTest.java
- platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/server/IdpEndpoint.java
- platform/security/idp/security-idp-server/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- platform/security/platform-security-core-api/src/main/java/ddf/security/samlp/LogoutMessage.java
-Cleaned up verbiage contained in the SAML Logout code:
1. Renamed inResponse to requestId in the Builder class of SamlValidator.
2. Renamed issueTimeout to timeout in the Builder class of SamlValidator.
3. Renamed LogoutService to LogoutMessage.
4. Cleaned verbiage in various places throughout the SAML Logout code.
5. Renamed reqres to samlType in IdpEndpoint.
-Added additional NotNull annotations in LogoutMessageImpl.
If there is any verbiage that I had missed or any other suggestions, please say so in the comments.
@codice/green 
@rzwiefel (could you hero this)
> DDF-1739 SAML Logout verbiage cleanup

- catalog/plugin/catalog-plugin-metacard-validation/pom.xml
- catalog/plugin/catalog-plugin-metacard-validation/src/main/java/ddf/catalog/metacard/validation/MetacardValidityFilterPlugin.java
- catalog/plugin/catalog-plugin-metacard-validation/src/main/java/ddf/catalog/metacard/validation/MetacardValidityMarkerPlugin.java
- catalog/plugin/catalog-plugin-metacard-validation/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/plugin/catalog-plugin-metacard-validation/src/main/resources/OSGI-INF/metatype/metatype.xml
- catalog/plugin/catalog-plugin-metacard-validation/src/test/java/ddf/catalog/metacard/validation/MetacardValidityCheckerPluginTest.java
- catalog/plugin/catalog-plugin-metacard-validation/src/test/java/ddf/catalog/metacard/validation/MetacardValidityFilterPluginTest.java
- distribution/ddf-common/src/main/resources/etc/pdp/policies/access-policy.xml
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalog.java
- platform/security/pdp/security-pdp-authzrealm/src/main/resources/OSGI-INF/metatype/metatype.xml
Post query plugin sets Metacard SECURITY attribute according
to metatype configuration. Uses existing filter plugin to do actual
filtering.
Add default configuration in XACML and Java PDP to allow users with
system-admin attribute to view invalid metacards.
@codice/security @brendan-hofmann @vinamartin 
@AzGoalie is hero
> DDF-1745 Add post query plugin for filtering

- distribution/docs/src/main/resources/ManContents.adoc
- platform/platform-configuration-migration/src/main/java/org/codice/ddf/configuration/admin/ConfigurationAdminMigration.java
- platform/platform-configuration-migration/src/test/java/org/codice/ddf/configuration/admin/ConfigurationAdminMigrationTest.java
Updated unit test to use mocks instead.
@lessarderic @andrewkfiedler @oconnormi @bantillo @andrewkfiedler @garrettfreibott @Lambeaux
> DDF-1755: Refactor ConfigurationAdminMigrationTest to use real Path objects and PowerMock

- platform/security/platform-security-core-api/pom.xml
- platform/security/platform-security-core-api/src/main/java/ddf/security/samlp/SamlProtocol.java
- platform/security/sts/security-sts-attributequeryclaimshandler/pom.xml
- platform/security/sts/security-sts-attributequeryclaimshandler/src/main/java/org/codice/ddf/security/claims/attributequery/AttributeQueryClient.java
Moved the Soap builders from the AttributeQueryClient into SamlProtocol and initialized the builders via the InitializationService.
@rzwiefel @ryeats @coyotesqrl @tbatie 
ryeats is the hero.
> DDF-1785 Initialize SAML SOAP Builders in AttributeQueryClient

- platform/solr/solr-factory/src/test/java/org/codice/solr/factory/TestSolrServerFactory.java
- The tests in TestSolrServerFactory now use a valid Solr URL when fetching SolrServers from SolrServerFactory, which allows them to pass rather than hang indefinitely
- Add timeouts for the tests in TestSolrServerFactory
@jlcsmith @jaymcnallie @beyelerb @kcwire 
@shane-voisard is the hero
> DDF-1808 Fix test failures caused by an invalid Solr URL

- catalog/ui/search-ui/standard/src/main/webapp/css/searchPage.css
@jaymcnallie @bdeining 
A one line fix to a copy/paste error introduced by DDF-1776.
- div container for cesium map must have height set.
> DDF-1781 Fix bug introduced by DDF-1776.

- platform/admin/ui/Gruntfile.js
- platform/admin/ui/package.json
- platform/admin/ui/pom.xml
- platform/admin/ui/src/main/webapp/css/style.css
- platform/admin/ui/src/main/webapp/js/models/Alerts.js
- platform/admin/ui/src/main/webapp/js/models/module/Export.js
- platform/admin/ui/src/main/webapp/js/views/module/ExportModal.view.js
- platform/admin/ui/src/main/webapp/js/views/module/ModuleDetail.layout.js
- platform/admin/ui/src/main/webapp/less/application/common.less
- platform/admin/ui/src/main/webapp/less/mixins.less
- platform/admin/ui/src/main/webapp/templates/alerts.handlebars
- platform/admin/ui/src/main/webapp/templates/module/ExportModal.handlebars
- platform/admin/ui/src/main/webapp/templates/module/ModuleDetail.layout.handlebars
- platform/admin/ui/src/test/js/shared/utility.js
- platform/admin/ui/src/test/js/unit/Export.js
- Updated the Gruntfile to run only unit tests when calling the test task.  The other tests have been turned off for so long that they no longer work, and they were more integration tests than unit tests.  As such I've commented them out, so the unit test can at least run.
- Updated the package.json to add grunt-simple-mocha (for unit tests), requirejs, sinon (for mocking in unit tests), and squirejs (for mocking require dependencies in unit tests), and jsdom (to enabled us to use jQuery in unit tests which allows mocking $.ajax).  These all lay the foundation for our future UI unit testing.
- Updated the pom.xml to remove the —force on the grunt test.  Also added an execution to install the latest node.  We might want to revisit the topic of how to ensure the latest node version is …
> DDF-1825 Adds way to export configs from Admin UI

- distribution/docs/src/main/resources/_contents/mancontents.adoc
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestConfiguration.java
- platform/migration/platform-migration-commands/pom.xml
- platform/migration/platform-migration-commands/src/main/java/org/codice/ddf/migration/commands/ExportCommand.java
- platform/migration/platform-migration-commands/src/main/java/org/codice/ddf/migration/commands/MigrationCommands.java
- platform/migration/platform-migration-commands/src/main/java/org/codice/ddf/migration/commands/MigrationStatusCommand.java
- platform/migration/platform-migration-commands/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- platform/migration/platform-migration-commands/src/test/java/org/codice/ddf/migration/commands/ConfigStatusCommandTest.java
- platform/migration/platform-migration-commands/src/test/java/org/codice/ddf/migration/commands/ExportCommandTest.java
- platform/migration/pom.xml
- platform/platform-app/src/main/resources/features.xml
- platform/platform-commands/src/main/resources/OSGI-INF/blueprint/blueprint.xml
* Changed command namespace from `platform` to `migration`
* Renamed `config-export` to `export` and `config-status` to `status`
* Moved migration commands to the migration module
* Added argument for export directory
@garrettfreibott, @Lambeaux, @figliold, @lessarderic, @andrewkfiedler
> DDF-1820: As an Administrator, I want to be able to specify the directory where my configurations are exported

- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestConfiguration.java
- No real way to test this other than to try it for a week and see if the inconsistent test failures go away.  10 seconds is the polling time, so 11 seconds should always work.  We couldn't increase the polling frequency because the means to do so are still internal to sun.  See here for why: https://github.com/frohoff/jdk8u-jdk/blob/master/src/share/classes/sun/nio/fs/PollingWatchService.java#L108
> DDF-1832 Updates the sleep in a test from 10 to 11 seconds

- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/CatalogFrameworkImpl.java
- distribution/test/itests/test-itests-common/src/test/java/ddf/common/test/ServiceManager.java
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFanout.java
A small regression was introduced recently that ignored fanout. This resolves that and adds two integration tests for verification.
Please note that the new `stopManagedService` method in the `ServiceManager` has not been completely verified. It should work but I wouldn't say with certainty that it does work. It is there for future use for cleanup of itests and needs to be made more robust and verified.
@tbatie - Please hero this
@ryeats 
@kcwire 
@clockard
> DDF-1835 - Fixes site list returned when fanout is set to true.

- catalog/admin/module/catalog-admin-module-sources/src/main/webapp/js/model/Service.js
- catalog/admin/module/catalog-admin-module-sources/src/main/webapp/js/model/Source.js
- catalog/admin/module/catalog-admin-module-sources/src/main/webapp/js/view/ModalSource.view.js
- catalog/admin/module/catalog-admin-module-sources/src/main/webapp/js/view/Source.view.js
- All source types now shown when editing existing sources.
- Fixed duplicate source types when passing an initial model to
getSourceModelWithServices.
- Fixed race condition when switching source types from the dropdown.
@stustison @andrewkfiedler @codice/ui
> DDF-1841 Allow new source types to be added to existing sources

- catalog/core/catalog-core-commands/pom.xml
- catalog/core/catalog-core-solrcommands/pom.xml
- catalog/core/catalog-core-standardframework/pom.xml
- catalog/solr/catalog-solr-external-provider/pom.xml
- catalog/ui/search-ui/search-endpoint/pom.xml
- platform/persistence/platform-persistence-core-impl/pom.xml
- platform/persistence/platform-persistence-core-listeners/pom.xml
- platform/pom.xml
@coyotesqrl @roelens8 @ryeats @rzwiefel @tbatie @wbarnie 
Removed "*;resolution:=optional" imports from all pom files with the exception of ddf.catalog.transformer:catalog-responsequeuetransformer-html and ddf.test.thirdparty:rest-assured.
For the most part the required packages were explicitly imported, please comment if you think any of them should instead be embedded.
> DDF-1778 Remove *;resolution:=optional imports in pom files

- .gitignore
- distribution/test/features-xml/pom.xml
- distribution/test/itests/pom.xml
- distribution/test/performance/jmeter/catalog-transformer-xml/pom.xml
- distribution/test/performance/jmeter/catalog-transformer-xml/src/test/jmeter/XMLTransformerPerf-json.jmx
- distribution/test/performance/jmeter/catalog-transformer-xml/src/test/jmeter/jmeter.properties
- distribution/test/performance/jmeter/csw/pom.xml
- distribution/test/performance/jmeter/csw/src/test/jmeter/CSW-GetRecords.jmx
- distribution/test/performance/jmeter/csw/src/test/jmeter/jmeter.properties
- distribution/test/performance/jmeter/pom.xml
- distribution/test/performance/pom.xml
- distribution/test/pom.xml
- distribution/test/test-input-transformer-stubs/pom.xml
Please Review @coyotesqrl @stustison @pklinef @shaundmorris @vinamartin @andrewkfiedler @jckilmer 
Reviewers should install [JMeter ](http://jmeter.apache.org)to view the .jmx files
To run you should have a running DDF instance. Go to distribution/tests/performance and use the command: `mvn verify -Pjmeter`
The tests will default to use https/localhost/8993 for protocol/host/port... You can specify other values with `-Dtarget.protocol=[protocol]`, `-Dtarget.host=[hostname or ip]`, and/or `-Dtarget.port=[portnumber]`
> DDF-1746 Initial commit for DDF Backend Performance Tests

- catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/CswRecordCollection.java
- catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java
- catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/writer/CswRecordCollectionMessageBodyWriter.java
- catalog/spatial/csw/spatial-csw-endpoint/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/TestCswEndpoint.java
- catalog/spatial/csw/spatial-csw-source/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/source/CswSource.java
- catalog/spatial/docs/src/main/resources/_contents/intcontents.adoc
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalog.java
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/common/Library.java
**A lot of the changes in the pull request are formatting.** 
The most important code changes are within getRecordById() of CSWEndpoint.java for POST and GET. Also added unit and integration tests for code coverage and stability.
**Description of the functionality:**
A user can now retrieve a product through the getRecordById operation. The client sets the output schema to "http://www.iana.org/assignments/media-types/application/octet-stream" and the output format to "application/octet-stream". The endpoint will do the following: check that only one Id is provided otherwise throw an exception as multiple products cannot be retrieved. If both output format and output schema are set as mentioned above, the catalog framework will retrieve the resource object for that Id. From that object, it …
> DDF-1845 Added Product Retrieval Capability to CSW Endpoint

- catalog/spatial/csw/spatial-csw-transformer/pom.xml
- catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/DefaultCswRecordMap.java
- catalog/spatial/csw/spatial-csw-transformer/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/TestDefaultCswRecordMap.java
Updated the DefaultCswRecordMap so that xpath queries remain
unchanged when checking for namespace prefixes.  Unit tests have
been included to demonstrate the intended functionality is
implemented.
@tbatie @ryeats @roelens8 @rzwiefel @kcwire
> DDF-1855 Fixed csw xpath queries with namespaces

- platform/platform-scheduler/pom.xml
When building locally, Jacoco passes the platform-scheduler module. When building on Bamboo, it fails with the error
```
lines covered ratio is 0.35, but expected minimum is 0.36
```
In testing this out, I changed the expected minimum locally to 0.37 and received the error
```
lines covered ratio is 0.35, but expected minimum is 0.37
```
Clearly on my OS (and others') the floating point comparison between 0.35xxxxx and 0.36xxxxx is coming up true whereas on the Bamboo server it is returning false. Since the coverage number is being reported by Jacoco as 0.35, it should be dropped to match reality.
@rzwiefel 
@stustison 
@kcwire
> DDF-1875 Fix Jacoco floating point comparison issue with platform-scheduler line coverage

- catalog/core/catalog-core-standardframework/pom.xml
- catalog/opensearch/catalog-opensearch-endpoint/pom.xml
- platform/admin/core/admin-core-appservice/src/main/java/org/codice/ddf/admin/application/service/impl/ApplicationServiceImpl.java
Instead of updating the properties during a property set, attaches a service listener on initial boot waiting for the `BootFinished` service. When that service is published by Karaf, the boot sequence has completed and the config properties can safely be updated. On subsequent boots of the system, the listener is not attached.
@kcwire 
@pklinef 
@roelens8 Please hero - this will require multiple clean installations followed by reboots of the system.
> DDF-1648 Update the manner in which the ConfigurationAdmin properties are updated at initial boot.

- catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/CswConstants.java
- catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java
- catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/writer/CswRecordCollectionMessageBodyWriter.java
- catalog/spatial/csw/spatial-csw-endpoint/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/writer/CswRecordCollectionMessageBodyWriterTest.java
- catalog/spatial/csw/spatial-csw-source/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/source/CswSource.java
- catalog/spatial/csw/spatial-csw-source/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/source/reader/GetRecordsMessageBodyReader.java
- catalog/spatial/csw/spatial-csw-source/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/source/TestCswSourceBase.java
- catalog/spatial/csw/spatial-csw-source/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/source/reader/TestGetRecordsMessageBodyReader.java
- catalog/spatial/csw/spatial-csw-source/src/test/resources/getCapabilities.xml
-CswSource now uses the new product retrieval implemented through GetRecordById.
-Added a new custom HTTP header called: "X-Csw-Product," when returning the product data. 
Since the GetRecordsMessageBodyReader expects the response of the GetRecordById to be XML of the record, there needs to be a way to distinguish whether the response is the product data or the XML of the record. The custom header is checked to determine if the data coming in is a product.
@coyotesqrl @pklinef @kcwire @ryeats @bcwaters (hero) @tbatie @jckilmer @wbarnie
> DDF-1879 CSW Source now uses true product retrieval

- platform/admin/ui/src/main/webapp/js/models/Service.js
- platform/admin/ui/src/main/webapp/js/views/configuration/Service.view.js
- platform/admin/ui/src/main/webapp/templates/configuration/configurationRow.handlebars
- Adds a method to the Service model that returns the human readable name for a configuration.
- Updates the template for configurationRow to utilize the displayName property.
- Updates the service view to call the new model method to get a human readable name, and to merge this data into the object that is given to the template (that way it can access the displayName property).
> DDF-1877 Updates Admin UI to show human readable names for MSF configs

- platform/security/certificate/security-certificate-generator/pom.xml
- platform/security/certificate/security-certificate-generator/src/main/java/org/codice/ddf/security/certificate/generator/CertificateCommand.java
- platform/security/certificate/security-certificate-generator/src/main/java/org/codice/ddf/security/certificate/generator/KeyStoreFile.java
- platform/security/certificate/security-certificate-generator/src/test/java/org/codice/ddf/security/certificate/generator/CertificateGeneratorTest.java
- platform/security/certificate/security-certificate-keystoreeditor/pom.xml
- platform/security/certificate/security-certificate-keystoreeditor/src/main/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditor.java
- platform/security/certificate/security-certificate-keystoreeditor/src/test/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditorTest.java
- platform/security/platform-security-core-api/pom.xml
- platform/security/platform-security-core-api/src/main/java/ddf/security/SecurityConstants.java
Removed code duplication and refactored string constants out of CertificateGenerator and KeystoreEditor. They now use the constants defined in SecurityConstants.
@brendan-hofmann @ahoffer @zryan3
> DDF-1900: Removed duplicate code and refactored string literals

- catalog/core/catalog-core-commands/pom.xml
- catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/ValidateCommand.java
- catalog/core/catalog-core-commands/src/test/java/org/codice/ddf/commands/catalog/ValidateCommandTest.java
- catalog/schematron/catalog-schematron-plugin/src/main/java/ddf/services/schematron/SchematronValidationService.java
- catalog/schematron/catalog-schematron-plugin/src/test/java/ddf/services/schematron/SchematronValidationServiceTest.java
- distribution/docs/src/main/resources/_contents/running-contents.adoc
This PR adds the ability to validate xml from the karaf console.
This command will go through any validators you have configured and will help ensure the quality and validity of ingested data by providing feedback about where your data fails validation.
You can test it out by:
1) configuring a validator (e.g. DDF Catalog -> Configuration -> Schematron Validation Services)
2) Running "validate" on an xml file
@AzGoalie will hero.
@kcwire 
@brianfelix
> DDF-1907 Add ability to validate xml from the karaf console

- catalog/core/catalog-core-backupplugin/pom.xml
- catalog/core/catalog-core-backupplugin/src/main/java/ddf/catalog/backup/CatalogBackupPlugin.java
- catalog/core/catalog-core-backupplugin/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/core/catalog-core-backupplugin/src/main/resources/OSGI-INF/metatype/metatype.xml
- catalog/core/catalog-core-backupplugin/src/test/java/ddf/catalog/backup/CatalogBackupPluginTest.java
- pom.xml
This PR changes the Catalog Backup Plugin to create and delete metacards asynchronously. 
Creating metacards synchronously slows the ingest process. The changes all the calling thread
to return as soon as it hands work to the plugin. The plugin's executor service
process requests in order of submission.
@AzGoalie 
@lessarderic 
@harrison-tarr  
**Performance test**
1. Ingest a large set of XML files with the master version of the plugin installed. Compute the average or take the median time to process the files.
2. Uninstall the master version of the plugin. Install the PR version of the plugin.
3. Repeat the ingest and computer average/median time. The expected results is the ingest is faster with the PR plugin.
**Functional test**
1. Delete all the backup files (data/backup directory) …
> DDF-1862 Process backup commands asynchronously

- catalog/core/catalog-core-migratable/pom.xml
- catalog/core/catalog-core-migratable/src/main/java/org/codice/ddf/catalog/migratable/impl/CatalogMigratableImpl.java
- catalog/core/catalog-core-migratable/src/test/java/org/codice/ddf/catalog/migratable/impl/CatalogMigratableImplTest.java
- platform/migration/platform-migration-commands/pom.xml
- platform/migration/platform-migration-commands/src/main/java/org/codice/ddf/migration/commands/ExportCommand.java
- platform/migration/platform-migration-commands/src/test/java/org/codice/ddf/migration/commands/ExportCommandTest.java
- platform/platform-app/src/main/resources/features.xml
- platform/security/security-services-app/pom.xml
- platform/security/security-services-app/src/main/resources/features.xml
Moved Subject check code from CatalogMigratableImpl class to ExportCommand.
Updated all unit tests, feature files and pom files accordingly.
Reviewers: @stustison, @pklinef
> DDF-1914: migration:export command doesn't have a Subject when run

- catalog/core/catalog-core-metacardgroomerplugin/src/main/java/ddf/catalog/plugin/groomer/metacard/StandardMetacardGroomerPlugin.java
Reverts the metacard groomer to its original logic to always generate a metacard id
@pklinef 
Unit and Itests should be sufficient
This was originally changed for registry but we will be doing things differently now
DDF-1933
> DDF-1933 Reverted metacard groomer to always generate metacard id

- catalog/core/catalog-core-solr/pom.xml
- catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/DynamicSchemaResolver.java
- catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/SolrFilterDelegate.java
- catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/SolrMetacardClient.java
- catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/TestSolrFilterDelegate.java
- catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/TestSolrProvider.java
- platform/solr/platform-solr-server-standalone/src/main/resources/solr/conf/schema.xml
- Created a cache of known text attributes.
- Modified filter delegate to detect anyText queries and to use the
text attribute cache to search all text fields.
- Fixed sort key (_sk) dynamic fields to not be stored which reduces 
the amount of data returned from Solr.
@brendan-hofmann @jrnorth @jaymcnallie @codice/solr 
Ingest a metacard with text attributes not present in the metadata field.  You can use the content framework to do this.  Search for a string value not present in the metadata and verify it is returned.
https://codice.atlassian.net/browse/DDF-1396
> DDF-1396 Search all text attributes when doing anyText searches on Solr

- platform/branding-resources/src/main/java/org/codice/ddf/branding/impl/BrandingResourceProviderImpl.java
- platform/branding-resources/src/test/java/org/codice/ddf/branding/impl/TestBrandingResourceProviderImpl.java
Changed getEntry to getResource because getEntry is not finding resources in the bundle fragments since karaf 4.0.4 upgrade
> DDF-1930: Fixed branding logos which weren't being read from fragment bundles

- pom.xml
Change frontend-maven-plugin configuration to use Codice NPM and Node.js proxy
@stustison @oconnormi @oscaritoro @linkmjb
Full build.
Was removed when the Codice proxy was having issues and needed to be added back in.
DDF-1932, DDF-1648
Added <downloadRoot> back in the frontend-maven-plugin configuration.
> DDF-1932: DDF builds not using Codice NPM and Node.js as proxy anymore

- catalog/spatial/geocoding/spatial-geocoding-api/src/main/java/org/codice/ddf/spatial/geocoding/GeoEntryQueryException.java
- catalog/spatial/geocoding/spatial-geocoding-api/src/main/java/org/codice/ddf/spatial/geocoding/GeoEntryQueryable.java
- catalog/spatial/geocoding/spatial-geocoding-geocoder/src/main/java/org/codice/ddf/spatial/geocoder/GeoCoder.java
- catalog/spatial/geocoding/spatial-geocoding-geocoder/src/main/java/org/codice/ddf/spatial/geocoder/endpoint/GeoCoderEndpoint.java
- catalog/spatial/geocoding/spatial-geocoding-geocoder/src/test/java/org/codice/ddf/spatial/geocoder/endpoint/TestGeoCoderEndpoint.java
- catalog/spatial/geocoding/spatial-geocoding-localsearch/src/main/java/org/codice/ddf/spatial/geocoder/geonames/GeoNamesLocalIndex.java
- catalog/spatial/geocoding/spatial-geocoding-localsearch/src/test/java/org/codice/ddf/spatial/geocoder/geonames/TestGeoNamesLocalIndex.java
- catalog/spatial/geocoding/spatial-geocoding-lucene/pom.xml
- catalog/spatial/geocoding/spatial-geocoding-lucene/src/main/java/org/codice/ddf/spatial/geocoding/query/GeoNamesQueryLuceneDirectoryIndex.java
- catalog/spatial/geocoding/spatial-geocoding-lucene/src/main/java/org/codice/ddf/spatial/geocoding/query/GeoNamesQueryLuceneIndex.java
- catalog/spatial/geocoding/spatial-geocoding-lucene/src/test/java/org/codice/ddf/spatial/geocoding/query/TestGeoNamesQueryLuceneIndex.java
Updates the admin error log message received if a local file is not set for the offline gazetteer feature
hero @jrnorth 
@jrnorth @dcruver @kcwire @jaymcnallie @bdeining 
Search for a well-known location (eg. Phoenix) with the offline-gazetteer feature enabled in the DDF Spatial application. A local Geoname file should **not** be set in order to generate the error.
DDF-1922
> DDF-1922: Update query error message for offline gazetteer

- catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/RemoveAllCommand.java
- catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/DynamicSchemaResolver.java
- catalog/plugin/catalog-plugin-metacard-validation/src/main/java/ddf/catalog/metacard/validation/MetacardValidityCheckerPlugin.java
[DDF-1698](https://codice.atlassian.net/browse/DDF-1698) introduced a bug where when this new feature (catalog-plugin-metacard-validation) is on, `catalog:removeall` fails to remove all records. This was caused by a disparity between the expected batch size and the actual page size.
Most of the changes in this PR are formatting changes. The actual code changes are:
RemoveAllCommand:
line 37
line 292-309
line 332-349
DynamicSchemaResolver:
line 195-198
MetacardValidityCheckerPlugin:
line 60-63
@AzGoalie @brendan-hofmann @ahoffer
> DDF-1698 Fix catalog:removeall command

- catalog/opensearch/catalog-opensearch-endpoint/pom.xml
- catalog/rest/catalog-rest-endpoint/pom.xml
- platform/security/platform-security-session/pom.xml
- platform/security/sts/security-sts-ldaplogin/pom.xml
This PR updates pom files that had been using `DynamicImport-Package`, removing that directive and importing the packages directly.
@kcwire @pklinef @stustison 
1. The application should be built and itests run. 
2. The application should be deployed and the installation process should be run.
3. Finally, the `security-sts-ldaplogin` bundle (or the feature that contains it) should be installed to ensure that it works correctly.
N/A
[DDF-1944](https://codice.atlassian.net/browse/DDF-1944)
N/A
> DDF-1944 Removes DynamicImport-Package directives in bundles.

- catalog/content/core/content-core-directorymonitor/pom.xml
Adds missing dependencies to a broken bundle.
@jckilmer @ryeats @roelens8 @bcwaters 
DDF should be deployed and the content app started. If the app starts successfully, the dependencies will have been resolved.
N/A
[DDF-1956](https://codice.atlassian.net/browse/DDF-1956)
N/A
The content app won't start because this bundle is missing several embedded dependencies.
> DDF-1956 Missing dependencies for content-core-directorymonitor

- catalog/core/catalog-core-api-impl/pom.xml
- catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/filter/impl/SimpleFilterDelegate.java
- catalog/core/catalog-core-api/src/main/java/ddf/catalog/filter/FilterDelegate.java
- catalog/core/catalog-core-commons/pom.xml
- catalog/core/catalog-core-commons/src/main/java/ddf/catalog/filter/delegate/TagsFilterDelegate.java
- catalog/core/catalog-core-metricsplugin/src/main/java/ddf/catalog/metrics/QueryTypeFilterDelegate.java
- catalog/opensearch/catalog-opensearch-source/pom.xml
- catalog/opensearch/catalog-opensearch-source/src/main/java/ddf/catalog/source/opensearch/RestFilterDelegate.java
- catalog/plugin/catalog-plugin-metacard-validation/pom.xml
- catalog/plugin/catalog-plugin-metacard-validation/src/main/java/ddf/catalog/metacard/validation/ValidationQueryDelegate.java
- catalog/plugin/catalog-plugin-metacard-validation/src/test/java/ddf/catalog/metacard/validation/MetacardValidityCheckerPluginTest.java
- catalog/registry/catalog-registry-common/src/main/java/ddf/catalog/registry/common/filter/RegistryQueryDelegate.java
- catalog/spatial/csw/spatial-csw-source/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/source/CswFilterDelegate.java
- catalog/spatial/ogc/spatial-ogc-common/src/main/java/org/codice/ddf/spatial/ogc/catalog/common/ContentTypeFilterDelegate.java
- catalog/spatial/wfs/1.0.0/spatial-wfs-v1_0_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v1_0_0/catalog/source/WfsFilterDelegate.java
- catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/source/WfsFilterDelegate.java
- catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/controller/search/WktExtractionFilterDelegate.java
- Refactored the changes made in DDF-1869 into the class SimpleFilterDelegate
- Added generic classes to support xpath
- Implemented csw xpathExists, xpathIsNull, xpathIsFuzzy
@pklinef @ryeats @coyotesqrl @roelens8 
Make sure all itests pass and the three implemented csw xpaths work
The original work behind DDF-1869 (Refactor the FilterDelegate and all classes extending) was intended to clean up code and offer support for xpath. A better alternative to support xpath was thought of, which resulted in the DDF-1869 changes being moved into the SimpleFilterDelegate class, additional roll up operation methods  and generic methods were created to support xpath
DDF-1869
- [In progress in separate ticket] Update / Add Integration Tests
> DDF-1844: Add XPath support for additional Operators that have a PropertyName

- catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/CswSourceConfiguration.java
- catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/CswSubscribe.java
- catalog/spatial/csw/spatial-csw-endpoint/pom.xml
- catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java
- catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswQueryFactory.java
- catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswSubscriptionEndpoint.java
- catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/Validator.java
- catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/event/CswSubscription.java
- catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/event/CswSubscriptionConfigFactory.java
- catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/event/SendEvent.java
- catalog/spatial/csw/spatial-csw-endpoint/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/spatial/csw/spatial-csw-endpoint/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswSubscriptionEndpointTest.java
- catalog/spatial/csw/spatial-csw-endpoint/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/TestCswEndpoint.java
- catalog/spatial/csw/spatial-csw-endpoint/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/event/CswSubscriptionConfigFactoryTest.java
- catalog/spatial/csw/spatial-csw-endpoint/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/event/SendEventTest.java
- catalog/spatial/csw/spatial-csw-source/pom.xml
- catalog/spatial/csw/spatial-csw-source/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/source/CswSource.java
- catalog/spatial/csw/spatial-csw-source/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/spatial/csw/spatial-csw-source/src/main/resources/OSGI-INF/metatype/metatype.xml
- catalog/spatial/csw/spatial-csw-source/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/source/CswSourceStub.java
- catalog/spatial/csw/spatial-csw-source/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/source/TestCswSource.java
- catalog/spatial/docs/src/main/resources/_contents/integrating-contents.adoc
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/AbstractIntegrationTest.java
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFederation.java
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/common/Library.java
- distribution/test/itests/test-itests-ddf/src/test/resources/get-records-response.xml
Adds endpoints to the subscription service to handle incoming events from federated sources.  
Update CSW source so that it can be configured to subscribe to events for that source.
@roelens8 @bcwaters @coyotesqrl @tbatie @pklinef 
1. Start up two DDF's
2. Federate from one DDF to another selecting register for events and filling out the event endpoint
3. Post a subscription to the DDF that has the federated source with the response handler pointing to a jetty server that will display the output.
4. Ingest metacards into the federated DDF and verify that events are exchanged between the servers.
> DDF-1953 Create endpoint to consume events from a CSW subscription

- pom.xml
Remove `node` and `node_modules` during an `mvn clean`.
@djblue 
`mvn clean install` in a ui module, then `mvn clean`. Verify both directories are deleted. Could also do a full build/quickbuild of ddf to make sure nothing is broken.
I ran into this while jumping between different commits and doing builds. Changes to npm dependencies were rendering my working copy un-buildable. This change solves that problem. Anyone trying to build after updates to npm dependencies could also run into this problem.
https://codice.atlassian.net/browse/DDF-1972
> DDF-1972 add npm directories to mvn clean

- catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/CswRecordMetacardType.java
- catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/CswSourceConfiguration.java
- catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/GmdMetacardType.java
- catalog/spatial/csw/spatial-csw-endpoint/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/TestCswEndpoint.java
- catalog/spatial/csw/spatial-csw-source-common/pom.xml
- catalog/spatial/csw/spatial-csw-source-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/AbstractCswSource.java
- catalog/spatial/csw/spatial-csw-source-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/CswFilterDelegate.java
- catalog/spatial/csw/spatial-csw-source-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/reader/GetRecordsMessageBodyReader.java
- catalog/spatial/csw/spatial-csw-source-common/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/TestCswCqlFilter.java
- catalog/spatial/csw/spatial-csw-source-common/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/TestCswFilterDelegate.java
- catalog/spatial/csw/spatial-csw-source-common/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/TestCswSource.java
- catalog/spatial/csw/spatial-csw-source-common/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/TestCswSourceBase.java
- catalog/spatial/csw/spatial-csw-source-common/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/reader/TestGetRecordsMessageBodyReader.java
- catalog/spatial/csw/spatial-csw-source/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/spatial/csw/spatial-csw-source/src/main/resources/OSGI-INF/metatype/metatype.xml
- catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/XstreamPathConverter.java
- catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/transformer/GmdTransformer.java
- catalog/spatial/csw/spatial-csw-transformer/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/spatial/csw/spatial-csw-transformer/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/TestXstreamPathConverter.java
Adds support to query by the GMD Metadata / CSW ISO profile from the CSW Source
@jlcsmith @bdeining @glenhein
Configure a GMD CSW Federated Source - defaults should be sufficient - you can use server:
http://csw.data.gov.uk/geonetwork/srv/en/csw
DDF-1966
Conflicts:
catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/GmdMetacardType.java
catalog/spatial/csw/spatial-csw-source-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/AbstractCswSource.java
catalog/spatial/csw/spatial-csw-source-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/CswFilterDelegate.java
catalog/spatial/csw/spatial-csw-source/src/main/resources/OSGI-INF/blueprint/blueprint.xml
> DDF-1966 - added support to query by GMD_Metadata from CSW Source

- catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/CswConstants.java
- catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/CswJAXBElementProvider.java
- catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/GmdMetacardType.java
- catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java
- catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswQueryFactory.java
- catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/Validator.java
- catalog/spatial/csw/spatial-csw-endpoint/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/TestCswEndpoint.java
- catalog/spatial/csw/spatial-csw-source-common/pom.xml
- catalog/spatial/csw/spatial-csw-source-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/CswAbstractFilterDelegate.java
- catalog/spatial/csw/spatial-csw-source-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/CswFilterDelegate.java
- catalog/spatial/csw/spatial-csw-source-common/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/TestCswCqlFilter.java
- catalog/spatial/csw/spatial-csw-source-common/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/TestCswFilterDelegate.java
- catalog/spatial/csw/spatial-csw-source-common/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/TestCswSource.java
- catalog/spatial/csw/spatial-csw-source-common/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/TestCswSourceBase.java
- catalog/spatial/csw/spatial-csw-source/src/main/resources/OSGI-INF/metatype/metatype.xml
- catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/GmdConverter.java
- catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/XmlTree.java
- catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/XstreamPathConverter.java
- catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/XstreamPathValueTracker.java
- catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/XstreamTreeWriter.java
- catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/transformer/GmdTransformer.java
- catalog/spatial/csw/spatial-csw-transformer/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/spatial/csw/spatial-csw-transformer/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/TestGmdConverter.java
- catalog/spatial/csw/spatial-csw-transformer/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/TestXstreamPathConverter.java
- catalog/spatial/csw/spatial-csw-transformer/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/transformer/TestGmdTransformer.java
- catalog/spatial/csw/spatial-csw-transformer/src/test/resources/gmd/dataset.xml
- catalog/spatial/csw/spatial-csw-transformer/src/test/resources/gmd/metacard-as-GMD-sparse.xml
- catalog/spatial/csw/spatial-csw-transformer/src/test/resources/gmd/metacard-as-GMD.xml
Adds a a transformer to convert from metacard to the Geographic MetaData (GMD) format.
@kcwire @bdeining 
Metacards can be exported to the GMD format.  For example:
`dump -t gmd:MD_Metadata <dump dir>`
GMD is one of  the metadata formats required by the CSW ISO profile. See: http://www.isotc211.org/schemas/2005/gmd/
DDF-1976
> DDF-1976: Added GmdMetacardTransformer

- catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/operation/impl/OperationTransaction.java
- catalog/core/catalog-core-api/src/main/java/ddf/catalog/Constants.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/CatalogFrameworkImpl.java
Adds the an OperationTransaction to update and delete requests
@pklinef 
Successful bamboo build
This is being added to support CatalogStores and Registry to prevent repeat queries. This could also be used in the future to support operation rollbacks 
DDF-1987
- Added OperationTransaction to hold metacards and operation type.
> DDF-1987 Added property to update/delete requests that contains the original metacards before the operation is performed.

- distribution/ddf-common/src/main/resources/etc/jmx.acl.whitelist.cfg
- distribution/ddf-common/src/main/resources/etc/org.ops4j.pax.logging.cfg
- distribution/docs/src/main/resources/_contents/configuring-contents.adoc
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestPlatform.java
- platform/platform-app/pom.xml
- platform/platform-app/src/main/resources/features.xml
- platform/platform-logging/pom.xml
- platform/platform-logging/src/main/java/org/codice/ddf/platform/logging/LogEvent.java
- platform/platform-logging/src/main/java/org/codice/ddf/platform/logging/LoggingService.java
- platform/platform-logging/src/main/java/org/codice/ddf/platform/logging/LoggingServiceMBean.java
- platform/platform-logging/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- platform/platform-logging/src/main/resources/OSGI-INF/metatype/metatype.xml
- platform/platform-logging/src/test/java/org/codice/ddf/platform/logging/LogEventTest.java
- platform/platform-logging/src/test/java/org/codice/ddf/platform/logging/LoggingServiceTest.java
- platform/pom.xml
Provides a backend logging Jolokia endpoint
@garrettfreibott @lessarderic @Lambeaux @bantillo @oconnormi 
1) Start DDF
2) Run through the installer
3) Verify logs show up when hitting endpoint: https://localhost:8993/jolokia/exec/org.codice.ddf.logging.platform.LoggingServiceBean:service=logging-service/retrieveLogEvents
5) Verify "number of logs to store" can be changed via the Admin Console: DDF Platform -> Configuration -> Logging Service
DDF-1957
> DDF-1957: Create backend for Log Service

- catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/GmdConverter.java
- catalog/spatial/csw/spatial-csw-transformer/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/TestGmdConverter.java
GmdMetacardTransformer was mapping the metacard resource URI to the
resource in the produced Gmd metadata.  This URI is not always resolvable
by externals.  Updated the transformer to instead use the metacard
resource-download-url.
@kcwire @bdeining 
1) ingest data into the catalog (pdf for example) 
2) catalog:dump -t gmd:MD_Metadata 
3) verify the linkage URL in the GMD metadata is a valid link to the data.
- [X ] Update / Add Unit Tests
> DDF-1999: Fixed download URL in GmdMetacardTransformer

- pom.xml
Enables javadoc aggregation with the command `javadoc:aggregate`
@jlcsmith @shaundmorris @Lambeaux @jrnorth @mcalcote @oscaritoro @vinamartin @lessarderic 
generate aggregated javadocs with the maven command `mvn javadoc:aggregate`; complete javadocs should be found in the `ddf/target directory.
DDF-1910
n/a
> DDF-1910: updated javadocs profile to enable javadoc aggregation.

- catalog/spatial/geowebcache/geowebcache-app/pom.xml
Updated geowebcache-server-standalone version to 0.6 (uses pax logging)
@jlcsmith 
@kcwire 
Build DDF, console logging has already been tested by @jlcsmith 
https://codice.atlassian.net/browse/DDF-2004
> DDF-2004 Updated geowebcache-server-standalone version to 0.6

- distribution/ddf/pom.xml
- libs/libs-pomfix/bin/pom-fix
Fixes build errors on non-existent javadoc artifacts
@shaundmorris @djblue @clockard @pklinef 
Bamboo build should pass
[DDF-1910](https://codice.atlassian.net/browse/DDF-1910)
> DDF-1910: fix for javadoc dependencies

- platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/server/IdpEndpoint.java
The IDP path replaces the hardcoded "/services" with the root context from the system.properties.
@ryeats @rzwiefel @coyotesqrl @tbatie 
PRBS
N/A
DDF-2010
N/A
> DDF-2010 IDP path uses the root context from system.properties

- catalog/core/catalog-core-api/src/main/java/ddf/catalog/resource/DataUsageLimitExceededException.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/CatalogFrameworkImpl.java
- catalog/resourcemanagement/resourcemanagement-usage-plugin/pom.xml
- catalog/resourcemanagement/resourcemanagement-usage-plugin/src/main/java/org/codice/ddf/resourcemanagement/usage/ResourceUsagePlugin.java
- catalog/resourcemanagement/resourcemanagement-usage-plugin/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/resourcemanagement/resourcemanagement-usage-plugin/src/test/java/org/codice/ddf/resourcemanagement/usage/TestResourceUsagePlugin.java
- catalog/rest/catalog-rest-endpoint/pom.xml
- catalog/rest/catalog-rest-endpoint/src/main/java/org/codice/ddf/endpoints/rest/RESTEndpoint.java
- platform/persistence/platform-persistence-core-api/src/main/java/org/codice/ddf/persistence/attributes/AttributesStore.java
- platform/persistence/platform-persistence-core-attributes-impl/pom.xml
- platform/persistence/platform-persistence-core-attributes-impl/src/main/java/org/codice/ddf/persistence/attributes/internal/AttributesStoreImpl.java
- platform/persistence/platform-persistence-core-attributes-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- platform/persistence/platform-persistence-core-attributes-impl/src/main/resources/OSGI-INF/metatype/metatype.xml
- platform/persistence/platform-persistence-core-attributes-impl/src/test/java/org/codice/ddf/persistence/attributes/internal/TestAttributesStoreImpl.java
This PR imposes data limits on users via the Data Usage Admin plugin and throws a StopProcessingException when a user attempts to retrieve a product that exceeds their limit.  It also prevents increasing the usage amount for a user on a failed download.
@jlcsmith 
@kcwire 
@jrnorth 
@glenhein 
Build DDF, install Resource Management App, ingest some data, and attempt to exceed the data limit for a user.
https://codice.atlassian.net/browse/DDF-1931
https://codice.atlassian.net/browse/DDF-1931
> DDF-1931 Added Data Usage Limit for users

- catalog/spatial/csw/spatial-csw-endpoint/src/main/resources/OSGI-INF/blueprint/blueprint.xml
Fixes csw endpoint queries so they do not have metacard-tags added to queries with the default output schema.
@ryeats @stustison 
Verify all itest pass
Removes configuration that was accidentally left from DDF-1831
DDF-2919
> DDF-2019 Removed bad schemaToTagsMapping from CswEndpoints blueprint.xml

- distribution/test/itests/test-itests-common/src/test/java/ddf/common/test/AdminConfig.java
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/AbstractIntegrationTest.java
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestPlatform.java
Turns off itest logging and addes a flag to enable it
@coyotesqrl @ryeats @bcwaters @roelens8 @jckilmer 
Make sure all itests pass and that the flag `itestLogLevel `works properly
> DDF-2015: Turned off itest logging and added a flag to enable

- platform/platform-app/pom.xml
- platform/platform-app/src/main/resources/features.xml
- platform/security/interceptor/pom.xml
- platform/security/interceptor/security-interceptor-logger/pom.xml
- platform/security/interceptor/security-interceptor-logger/src/main/java/ddf/security/interceptor/SecurityInterceptorFeature.java
- platform/security/interceptor/security-interceptor-logger/src/main/java/ddf/security/interceptor/SecurityLoggerInInterceptor.java
- platform/security/interceptor/security-interceptor-logger/src/main/java/ddf/security/interceptor/SecurityLoggerOutInterceptor.java
- platform/security/interceptor/security-interceptor-logger/src/main/resources/OSGI-INF/blueprint/blueprint.xml
Adds interceptors that log all incoming and outgoing requests 
@codice/security @roelens8 @bcwaters @coyotesqrl @tbatie @jckilmer 
do a loopback federation verify that their are security logs for queries that are going out to the endpoint and coming in to the endpoint specified in the loopback configuration .
DDF-2021
```Admin is making an outbound request. Outbound endpoint: https://localhost:8993/services/csw
No subject associated with outbound request. Outbound endpoint: https://localhost:8993/services/csw
Admin is making an inbound request to  https://localhost:8993/services/csw. Request IP: 127.0.0.1, Port: 8080
No subject associated with inbound request to https://localhost:8993/services/csw. Request IP: 127.0.0.1, Port: 8080```
> DDF-2021 add outgoing and incoming audit logging interceptors.

- catalog/core/catalog-core-urlresourcereader/src/main/java/ddf/catalog/resource/impl/URLResourceReader.java
- catalog/core/catalog-core-urlresourcereader/src/main/resources/OSGI-INF/metatype/metatype.xml
- catalog/core/catalog-core-urlresourcereader/src/test/java/ddf/catalog/resource/impl/ResourceReaderTest.java
This PR sets the CXF setting to HTTP redirects by default (DDF-1588).  There are unit tests that verify the proper setting of the CFX property to follow redirects.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codice/ddf/635)
> DDF-1588 updated the URLResourceReader to follow redirects by default

- catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/data/impl/BasicTypes.java
- catalog/core/catalog-core-api/src/main/java/ddf/catalog/data/Metacard.java
- catalog/plugin/catalog-plugin-checksum/pom.xml
- catalog/plugin/catalog-plugin-checksum/src/main/java/org/codice/ddf/catalog/content/plugin/checksum/Checksum.java
- catalog/plugin/catalog-plugin-checksum/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/plugin/catalog-plugin-checksum/src/test/java/org/codice/ddf/catalog/content/plugin/checksum/TestChecksum.java
- Added implementation of PreUpdateStoragePlugin to Checksum Plugin
- Added missing checksum attributes to basic MetacardType
- Added unit tests
@rzwiefel @jrnorth @kcwire @beyelerb 
- Ingest and update content and verify the checksum attributes are populated
- ingest via cURL:
`curl -k -X POST -i -H "Content-Type: multipart/mixed"  -F upload=@<file> https://localhost:8993/services/catalog`
- update via cURL:
`curl -k -X PUT -i -H "Content-Type: multipart/mixed"  -F upload=@<file> https://localhost:8993/services/catalog/<id>`
- [X ] Update / Add Unit Tests
> DDF-1567: Checksum plugin modified to handle update requests

- catalog/rest/catalog-rest-endpoint/src/main/java/org/codice/ddf/endpoints/rest/RESTEndpoint.java
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalog.java
Adds content length header for cached product returns. 
@jaymcnallie @kcwire @bdeining 
Run the following ITest: 
mvn clean  test -nsu  -Dtest=TestCatalog#testCachedContentLengthHeader
DDF-2018
> DDF-2018 Added content-length header for cached products

- platform/security/common/src/main/java/org/codice/ddf/security/common/FailedLoginDelayer.java
- platform/security/filter/security-filter-login/pom.xml
- platform/security/filter/security-filter-login/src/main/java/org/codice/ddf/security/filter/login/LoginFilter.java
- platform/security/interceptor/security-interceptor-guest/src/main/java/org/codice/ddf/security/interceptor/GuestInterceptor.java
- platform/security/sts/security-sts-realm/src/main/java/ddf/security/realm/sts/AbstractStsRealm.java
- platform/security/sts/security-sts-realm/src/test/java/ddf/security/realm/sts/TestStsRealm.java
- platform/security/sts/security-sts-server/src/main/resources/OSGI-INF/blueprint/cxf-sts.xml
- platform/security/sts/security-sts-upbstvalidator/pom.xml
- platform/security/sts/security-sts-upbstvalidator/src/main/java/org/codice/ddf/security/validator/uname/UPBSTValidator.java
- platform/security/sts/security-sts-upbstvalidator/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- platform/security/sts/security-sts-upbstvalidator/src/test/java/org/codice/ddf/security/validator/uname/UPBSTValidatorTest.java
- platform/security/sts/security-sts-usernametokenvalidator/pom.xml
- platform/security/sts/security-sts-usernametokenvalidator/src/main/java/org/codice/ddf/security/validator/username/UsernameTokenValidator.java
- platform/security/sts/security-sts-usernametokenvalidator/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- platform/security/sts/security-sts-usernametokenvalidator/src/test/java/org/codice/ddf/security/validator/username/TestUsernameTokenValidator.java
Adds a delay mechanism on failed login attempts.
Also removes synchronization from `LoginFilter` and fixes `AbstractStsRealm` so it no longer shares an `STSClient` between threads.
@tbatie 
@roelens8 
@kcwire
@stustison
A full build will exercise the unit tests. Further manual testing is probably best managed by attaching a remote debugger to a running DDF instance and confirming that the delay code is invoked. Additionally, any attempt to login through the STS with incorrect credentials will be timed out so scripting an attack-like scenario should demonstrate that the system slows down the operation of the script while still allowing correct logins to pass.
N/A
DDF-2031
N/A
> DDF-2031 Adds a two-second delay on failed login to prevent automated password cracking

- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/CatalogFrameworkImpl.java
- catalog/rest/catalog-rest-endpoint/src/main/java/org/codice/ddf/endpoints/rest/RESTEndpoint.java
- catalog/spatial/csw/spatial-csw-source-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/AbstractCswSource.java
- catalog/spatial/csw/spatial-csw-source-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/CswResponseExceptionMapper.java
- catalog/spatial/wfs/1.0.0/spatial-wfs-v1_0_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v1_0_0/catalog/source/WfsSource.java
- catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/source/WfsSource.java
- catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/controller/search/QueryRunnable.java
- distribution/ddf-common/src/main/resources/etc/org.ops4j.pax.logging.cfg
Cleans up log stack traces for unavailable federated sources.
- Move unavailable source stack traces to DEBUG level
- Add checks for more specific exceptions
- Change CXF PhaseInterceptorChain default log level to ERROR to remove unwanted stack traces, can be set back to WARN using log:set command
@jaymcnallie @bdeining @kcwire @troymohl 
@jaymcnallie
@kcwire 
Build and start and instance of DDF and add federated sources with bologna information. 
Some WFS sources:
http://www.pyxisinnovation.com/pyxwiki/index.php?title=WFS_Servers
https://github.com/DamonOehlman/geofilter/issues/1
N/A
[DDF-1971](https://codice.atlassian.net/projects/DDF/issues/DDF-1971?filter=allissues)
N/A
> DDF-1971 Clean up federated source error log messages

- catalog/core/catalog-core-camelcomponent/pom.xml
- catalog/core/catalog-core-camelcomponent/src/main/java/ddf/camel/component/catalog/content/ContentProducer.java
- catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/ContentDirectoryMonitor.java
- catalog/core/catalog-core-directorymonitor/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/core/catalog-core-directorymonitor/src/main/resources/OSGI-INF/metatype/metatype.xml
- catalog/core/catalog-core-directorymonitor/src/test/java/org/codice/ddf/catalog/content/monitor/ContentDirectoryMonitorTest.java
This PR adds the ability to configure parameters in the content directory monitor that are available to any registered ingest process API.
@jrnorth 
@glenhein 
@rzwiefel 
@jlcsmith
@kcwire
Build DDF, set the log level for `ddf.camel` to DEBUG, create a content directory monitor, ingest a file, and observe the parameters in the log.  There are currently no classes that utilize the parameters.
https://codice.atlassian.net/browse/DDF-2034
https://codice.atlassian.net/browse/DDF-2034
> DDF-2034 Added parameter configuration to the content directory monitor

- platform/platform-app/src/main/resources/DDF_Custom_Mime_Type_Resolver.nitf.config
This PR adds NSIF and NSF to the NITF Custom Mime Types in DDF
@dcruver
@glenhein 
@jlcsmith
@kcwire
Build DDF and observe that the NITF Custom Mime Type has NSF and NSIF.
https://codice.atlassian.net/browse/CAL-30
https://codice.atlassian.net/browse/DDF-2038
> DDF-2038 Added NSF and NSIF to NITF Mime Type Configuration

- catalog/core/catalog-core-api/src/main/java/ddf/catalog/Constants.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/CatalogFrameworkImpl.java
- catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/impl/CatalogFrameworkImplTest.java
This PR makes it possible to retrieve a content item and its associated metacard in a single request.  
@stustison 
@peterhuffer 
@jaymcnallie
@kcwire
Run CatalogFrameworkImplTest.testGetResourceFromCache().
DDF-2039
Modified the CatalogFrameworkImpl to add the metacard (which was already
being retrieved) to the properties of the ResourceResponse.
> ddf-2039 Add the metacard to the properties of the ResourceResponse

- platform/security/sts/security-sts-attributequerycommon/src/main/java/org/codice/ddf/security/claims/attributequery/common/AttributeQueryClaimsHandler.java
- platform/security/sts/security-sts-attributequerycommon/src/test/java/org/codice/ddf/security/claims/attributequery/common/TestAttributeQueryClaimsHandler.java
- platform/security/sts/security-sts-ldapclaimshandler/pom.xml
- platform/security/sts/security-sts-ldapclaimshandler/src/test/java/ddf/security/sts/claimsHandler/LdapClaimsHandlerTest.java
- platform/security/sts/security-sts-ldapclaimshandler/src/test/java/ddf/security/sts/claimsHandler/RoleClaimsHandlerTest.java
- platform/security/sts/security-sts-propertyclaimshandler/pom.xml
- platform/security/sts/security-sts-propertyclaimshandler/src/main/java/org/codice/ddf/security/sts/claims/property/AttributeFileClaimsHandler.java
- platform/security/sts/security-sts-propertyclaimshandler/src/test/java/org/codice/ddf/security/sts/claims/property/TestAttributeFileClaimsHandler.java
- platform/security/sts/security-sts-propertyclaimshandler/src/test/java/org/codice/ddf/security/sts/claims/property/TestPropertyFileClaimsHandler.java
Some of the DDF ClaimsHandlers failed to guard against null Principals. Under rare conditions, the Principal passed has been seen to be null; this will protect against NPEs and return empty claims.
@jckilmer 
@bcwaters 
@pklinef
@stustison
Full build with unit and integration tests is sufficient to test.
In testing the possibility of emptying or removing the `users.properties` file and using an LDAP server as the sole realm provider, we found that there were some conditions at startup that could result in a null Principal. While this is a rare case, it is nonetheless a code path that needs to be protected.
DDF-2043
N/A
> DDF-2043 Guards against NPEs caused by null Principals being passed to ClaimsHandlers

- catalog/core/catalog-core-migratable/src/main/java/org/codice/ddf/catalog/migratable/impl/MetacardsMigratable.java
- catalog/core/catalog-core-migratable/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/core/catalog-core-migratable/src/test/java/org/codice/ddf/catalog/migratable/impl/MetacardsMigratableTest.java
- distribution/docs/src/main/resources/_contents/extending-contents.adoc
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestConfiguration.java
- platform/migration/platform-migratable-api/src/main/java/org/codice/ddf/migration/DescribableBean.java
- platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/ConfigurationMigrationManager.java
- platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/ConfigurationMigrationManagerMBean.java
- platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/ConfigurationMigrationService.java
- platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/migration/ConfigurationMigrationManagerTest.java
- platform/platform-api/src/main/java/org/codice/ddf/platform/services/common/Describable.java
- platform/platform-migratable/src/main/java/org/codice/ddf/platform/migratable/impl/PlatformMigratable.java
- platform/platform-migratable/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- platform/platform-migratable/src/test/java/org/codice/ddf/platform/migratable/impl/PlatformMigratableTest.java
- platform/security/security-migratable/src/main/java/org/codice/ddf/security/migratable/impl/SecurityMigratable.java
- platform/security/security-migratable/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- platform/security/security-migratable/src/test/java/org/codice/ddf/security/migratable/impl/SecurityMigratableTest.java
Extends `platform-migration` to look-up and return migratables that also implement describable. Warnings are logged when migratables are found that do not conform to this criteria.  
@lessarderic @garrettfreibott @oconnormi @figliold 
Full build - make sure DDF starts and that `migration:export` works. No need to ingest anything. 
We are exposing functionality for later consumption in the CLI and GUI. 
DDF-1970
> DDF-1970: As an Integrator, I want information on Migratables.

- distribution/docs/pom.xml
- javadoc-descriptor.xml
- pom.xml
Enables Javadoc to be generated, aggregated and deployed during a `mvn site` build. Javadoc is deployed in a zip file that can be unzipped and installed locally or hosted publicly. 
@jlcsmith @shaundmorris @lessarderic @mcalcote @brianfelix @vinamartin @gordocanchola @clockard @oscaritoro 
@kcwire
@lessarderic
run `mvn clean site` to confirm javadoc aggregated
run `mvn clean install` to confirm no side effects to regular build process.
https://codice.atlassian.net/browse/DDF-1910
> DDF-1910: corrected javadoc configuration.

- catalog/catalog-app/pom.xml
- catalog/catalog-app/src/main/resources/features.xml
- catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/data/impl/BasicTypes.java
- catalog/core/catalog-core-api/src/main/java/ddf/catalog/data/Metacard.java
- catalog/plugin/catalog-plugin-checksum/src/main/java/org/codice/ddf/catalog/content/plugin/checksum/Checksum.java
- catalog/plugin/catalog-plugin-checksum/src/test/java/org/codice/ddf/catalog/content/plugin/checksum/TestChecksum.java
- catalog/plugin/catalog-plugin-duplication/pom.xml
- catalog/plugin/catalog-plugin-duplication/src/main/java/ddf/catalog/metacard/duplication/DuplicationValidator.java
- catalog/plugin/catalog-plugin-duplication/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/plugin/catalog-plugin-duplication/src/main/resources/OSGI-INF/metatype/metatype.xml
- catalog/plugin/catalog-plugin-duplication/src/main/resources/describable.properties
- catalog/plugin/catalog-plugin-duplication/src/test/java/ddf/catalog/metacard/duplication/TestDuplicationValidator.java
- catalog/plugin/pom.xml
- distribution/docs/src/main/resources/_contents/_catalog-contents/configuring-catalog-contents.adoc
- checks for duplicates on ingested cards against configurable fields
- admin can configure a duplicate card to be marked with validation errors/warnings
@jrnorth 
@rzwiefel 
@bdeining 
@clockard 
@vinamartin 
@beyelerb 
@kcwire 
1) install the catalog-duplication-plugin feature
2) install the catalog-plugin-metacard-validation feature
3) Configure the duplication validator to check specific attributes for duplicates
4) Configure the metacard validity checker plugin to show invalid metacard on query
4) Ingest one or more items that may be duplicates (for instance, duplicate content)
The default configuration of the plugin checks the checksum attribute on the metacard against any other checksum in the local catalog.  The checksum is calculated on ingest of a content item.  A validation …
> DDF-2023: Added Duplication PreIngest Plugin

- catalog/core/catalog-core-api/src/main/java/ddf/catalog/Constants.java
- catalog/core/catalog-core-camelcomponent/pom.xml
- catalog/core/catalog-core-camelcomponent/src/main/java/ddf/camel/component/catalog/content/ContentProducer.java
- catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/ContentDirectoryMonitor.java
- catalog/core/catalog-core-directorymonitor/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/core/catalog-core-directorymonitor/src/main/resources/OSGI-INF/metatype/metatype.xml
- catalog/core/catalog-core-directorymonitor/src/test/java/org/codice/ddf/catalog/content/monitor/ContentDirectoryMonitorTest.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/CatalogFrameworkImpl.java
- catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/impl/CatalogFrameworkImplTest.java
This PR augments the existing Content Directory parameter passing code in the following ways:
1) Prevents the parameters being added to the CreateStorageRequest so that they are not exposed to ingest plugins
2) Parses parameters according to the attribute type, and ignores attributes that fail to parse
2) Overrides valid attributes on metacards with the passed parameters
@jrnorth
@dcruver
@jlcsmith
@kcwire
Build, Install, Configure the Content Directory Monitor with an overridable attribute, ingest some data, and verify the metacard attribute is overridden after ingest.
After discussion with @michaelmenousek, @kcwire and @jlcsmith, it was determined that this approach for metacard attribute overrides was the most logical.
https://codice.atlassian.net/browse/DDF-2034
> DDF-2034 Updated Parameter Configuration for Content Directory Monitor

- platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/cache/CookieCache.java
- platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/server/IdpEndpoint.java
Removes synchronization on methods calling securityManager.getSubject() as instances of the StsClient are not being shared anymore. Also, removes synchronization from other methods that are already thread safe.
@coyotesqrl @ryeats @kcwire @rzwiefel @tbatie @jckilmer @bcwaters 
@pklinef
@stustison
Test IDP Login/Logout and verify it still works
Run Jmeter test with IDP active and verify no errors/exceptions occurs
DDF-2049
> DDF-2049 Remove unnecessary synchronization in IDP Endpoint

- platform/security/platform-security-session/pom.xml
- platform/security/platform-security-session/src/main/java/org/codice/ddf/security/session/HashSessionIdManager.java
Provides a seed to the random number generator in the HashSessionIdManager 
@ryeats @bcwaters @coyotesqrl 
@shaundmorris
@stustison
Startup ddf and ensure you get unique session ids with multiple logins
- Used bouncycastle random bit generator to provide the random number generator with a good seed
> Improve the RNG seed for the HashSessionIdManager:

- distribution/docs/pom.xml
- platform/security/platform-security-session/pom.xml
- platform/security/platform-security-session/src/main/java/org/codice/ddf/security/session/HashSessionIdManager.java
- platform/security/sts/security-sts-server/src/main/java/ddf/security/sts/AuthNStatementProvider.java
- platform/util/platform-util/pom.xml
- platform/util/platform-util/src/main/java/org/codice/ddf/platform/util/RandomNumberGenerator.java
Sets the SessionIndex in the AuthenticationStatementBean to a uid
@ryeats 
@coyotesqrl 
@roelens8 
@pklinef 
@stustison
Ensure the sessionIndex varies in randomness
> DDF-2076: Use a RNG for the generation fo SessionIndex in the SAML element AuthnStatement

- distribution/docs/pom.xml
- distribution/docs/src/main/resources/_contents/securing-contents.adoc
- distribution/docs/src/test/java/ddf/docs/DocumentationTest.java
This PR adds a unit test to check the completeness of finished documentation. This will also fix the incremental builds for documentation PRs.
@lessarderic
@shaundmorris
full build with documentation profile on should pass all tests,
full build without documentation profile should also pass
This replaces a manual check of documentation and enables incremental builds to pass.
https://codice.atlassian.net/browse/DDF-2062
> DDF-2062: added unit test for docs

- .gitignore
- Documentation-versions.html
- _config.yml
Adds a configuration to generate a sitemap per github recommendation to include documentation files into search engine indexing.
@shaundmorris
check links on static html pages
https://help.github.com/articles/sitemaps-for-github-pages/
DDF-1915, 
N/A
> DDF-1910: added a config to generate a sitemap for indexing.

- distribution/ddf-common/src/main/resources/etc/pdp/policies/access-policy.xml
- platform/security/pdp/security-pdp-authzrealm/pom.xml
- platform/security/pdp/security-pdp-authzrealm/src/main/java/ddf/security/pdp/realm/AuthzRealm.java
- platform/security/pdp/security-pdp-authzrealm/src/main/java/ddf/security/pdp/realm/xacml/XACMLConstants.java
- platform/security/pdp/security-pdp-authzrealm/src/main/java/ddf/security/pdp/realm/xacml/XacmlPdp.java
- platform/security/pdp/security-pdp-authzrealm/src/main/java/ddf/security/pdp/realm/xacml/processor/PdpException.java
- platform/security/pdp/security-pdp-authzrealm/src/main/java/ddf/security/pdp/realm/xacml/processor/PollingPolicyFinderModule.java
- platform/security/pdp/security-pdp-authzrealm/src/main/java/ddf/security/pdp/realm/xacml/processor/XacmlClient.java
- platform/security/pdp/security-pdp-authzrealm/src/main/resources/OSGI-INF/metatype/metatype.xml
- platform/security/pdp/security-pdp-authzrealm/src/test/java/ddf/security/pdp/realm/xacml/XacmlPdpTest.java
- platform/security/pdp/security-pdp-authzrealm/src/test/java/ddf/security/pdp/realm/xacml/processor/XacmlClientTest.java
Moves DDF to Arbitro instead of balana.
Adds support for XACML environment variables.
@coyotesqrl @bcwaters @ryeats 
@beyelerb 
@stustison
unit/itests
> DDF-2088 updated DDF to use Arbitro

- distribution/ddf-common/src/main/resources/etc/certs/CertNew.cmd
- distribution/ddf-common/src/main/resources/etc/certs/CertNew.sh
- distribution/docs/src/main/resources/_contents/configuring-contents.adoc
- platform/security/certificate/security-certificate-generator/pom.xml
- platform/security/certificate/security-certificate-generator/src/main/java/org/codice/ddf/security/certificate/generator/CertificateCommand.java
- platform/security/certificate/security-certificate-generator/src/main/java/org/codice/ddf/security/certificate/generator/CertificateSigningRequest.java
- platform/security/certificate/security-certificate-generator/src/main/java/org/codice/ddf/security/certificate/generator/PkiTools.java
- platform/security/certificate/security-certificate-generator/src/test/java/org/codice/ddf/security/certificate/generator/CertificateSigningRequestTest.java
- platform/security/certificate/security-certificate-generator/src/test/java/org/codice/ddf/security/certificate/generator/PkiToolsTest.java
Updates the certificate signing functionality so it can accept either a common name or a distinguished name.
@ryeats @bcwaters @ahoffer @ricklarsen 
@shaundmorris
@stustison
- Full build and itest.
- Install with and without using the `dev=true` flag and ensure functionality. Further inspection of the keystore would be good.
- Use the shell script for generating a keypair trying both the CN and DN paths.
- Test the Windows script as well over both paths.
N/A
DDF-2084
N/A
Updates the CSR and the utility scripts that invoke the command directly in order to support the current operation, passing in a common name, and to support passing in a distinguished name.
> DDF-2084 Updates the model CertificateSigningRequest to allow passing through an FQDN.

- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/AbstractIntegrationTest.java
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestSingleSignOn.java
Fixes DDF itest Windows CI failures
@garrettfreibott @Lambeaux @oconnormi @bantillo 
@lessarderic
@shaundmorris
DDF-2064
- Changed code to make Karaf unpack directory configurable
- Added waitForAllBundles() after search UI feature is started in TestSingleSignOn.java
> DDF-2064: Investigate and fix DDF itest Windows CI failures

- catalog/spatial/geocoding/spatial-geocoding-websearch/pom.xml
- catalog/spatial/geocoding/spatial-geocoding-websearch/src/main/java/org/codice/ddf/spatial/geocoder/geonames/GeoNamesWebService.java
- catalog/spatial/geocoding/spatial-geocoding-websearch/src/test/java/org/codice/ddf/spatial/geocoder/geonames/TestGeoNamesWebService.java
- Previously, the GeoNames web service implementation was returning the name of the administrative division in which the nearby city resides rather than the name of the city. This PR fixes `GeoNamesWebService` so that it returns the name of the city.
- Filter nearby cities results to cities with a population of at least 5000
- Refactor JSON keys into string constants
- Fix `spatial-geocoding-websearch` test directory structure to match the Maven standard
@dcruver 
@bdeining 
@jlcsmith
@kcwire 
- Search using the web service gazetteer and verify the results are correct
- Create metacards with location data and verify that the spatial context information in the metacard summary pane includes the name of a nearby city
https://codice.atlassian.net/browse/DDF-1631
See ticket
> DDF-1631 Fix the GeoNames web service's getNearbyCity implementation

- distribution/ddf-common/src/main/resources/bin/setenv
This PR adds logic to bin/setenv to set the random seed generator on Linux systems.  
@bdeining 
@peterhuffer 
@beyelerb
@kcwire
1) acquire access to a Linux host that demonstrates this problem.  
2) deploy the modified setenv script to $DDF_HOME/bin.
3) start DDF as usual.
4) verify that the web applications are now accessible.
This is to solve an issue that prevented the security modules from being seeded and caused a timeout in the web applications.  The JVM delegates random number generation for the seed vales to the OS.  On Unix systems, it uses /dev/random.  On Linux systems, /dev/random will block until it has generated a truly random value.  This process can take tens of minutes, making the system unusable.  The /dev/urandom device provides slightly less randomness, but without …
> ddf-2095 ddf should prefer /dev/urandom on Linux

- catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/util/impl/SourcePollerRunner.java
- catalog/core/catalog-core-api-impl/src/test/java/ddf/catalog/util/impl/SourcePollerRunnerTest.java
This adds Comparator Logic to the SourcePollerRunner so that it will recognize a source regardless if it is a ServiceProxy or not.   This resolves a bug where the framework was not finding cached values and calling isAvailable on all sources when the UI, splash page, or services/rest/sources was called.  
I screwed up the formatting of this pull request description
@kcwire, @pklinef, and @clockard 
@kcwire
@pklinef
Run yourself some DDF, run the installer, add some federated sources (could be self-federated, csw, opensearch, whatever) and set a breakpoint on line 615 of CatalogFrameworkImpl.  Confirm that you arrive there, and that the source variable that is generated by executing that line of code is a cached version of the same source the variable represented prior to executing the …
> DDF-2097: Added logic to compare Sources based on attributes instead of hashcode

- catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/util/impl/SourcePollerRunner.java
- catalog/core/catalog-core-api-impl/src/test/java/ddf/catalog/util/impl/SourcePollerRunnerTest.java
Description
This adds Comparator Logic to the SourcePollerRunner so that it will recognize a source regardless if it is a ServiceProxy or not. This resolves a bug where the framework was not finding cached values and calling isAvailable on all sources when the UI, splash page, or services/rest/sources was called.
I screwed up the formatting of this pull request description
Reviewers:
@kcwire, @pklinef, and @clockard
2 committers to review/merge the PR
@kcwire
@pklinef
Run yourself some DDF, run the installer, add some federated sources (could be self-federated, csw, opensearch, whatever) and set a breakpoint on line 615 of CatalogFrameworkImpl. Confirm that you arrive there, and that the source variable that is generated by executing that line of code is a …
> DDF-2097: Added logic to compare Sources based on attributes instead of Object.hashcode()

- catalog/transformer/catalog-transformer-pdf/src/main/java/ddf/catalog/transformer/input/pdf/PdfInputTransformer.java
Fix possible NPE with pdf transformer
@jlcsmith @bdeining @kcwire @jrnorth 
@beyelerb
@jlcsmith
Upload a PDF, search for it, verify it appears in the search results. Look at the ddf log and make sure there is a log statement that contains "PDF Creation date was" if the PDF did have a creation date, and make sure there is a log statement that contains "PDF Modification date was" if the PDF did have a modification date.
I don't have a test PDF that is missing a creation date or modification date.
DDF-2098
If the PDF document has a null creation date or modification date, then
an NPE would be thrown from a log statement.
> DDF-2098 Fix possible null pointer exception in pdf transformer

- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/CachingFederationStrategy.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/ValidationQueryFactory.java
- catalog/core/catalog-core-standardframework/src/main/resources/OSGI-INF/metatype/sortedFederationStrategy.xml
- catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/cache/solr/impl/ValidationQueryFactoryTest.java
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/AbstractIntegrationTest.java
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalog.java
CachingFederationStrategy has a flag "showInvalidMetacards". This allows an administrator to either show or filter invalid metacards (validation warnings or errors). Now, an administrator can show or filter either validation warnings or errors. This is no longer restricted to none or all.
@spearskw @brendan-hofmann @coyotesqrl 
@kcwire
@pklinef 
Unit tests and integration tests should pass.
DDF-2096
> DDF-2096 Allow finer configuration of validation filtering

- distribution/test/itests/test-itests-ddf/pom.xml
- platform/admin/admin-app/pom.xml
This is a Spring cleaning PR. It is intended to remove a POM dependency which pulls in the wrong version of Karaf; additionally, it deletes a duplicate dependency.
@harrison-tarr @spearskw @tbatie @torvalds
@kcwire
@stustison 
You can open up `ddf/platform/admin/admin-app/pom.xml` and then look at the effective POM to ensure that the karaf 4 version is imported like this:
```xml
<dependency>
<groupId>org.apache.karaf.bundle</groupId>
<artifactId>org.apache.karaf.bundle.core</artifactId>
<version>4.0.4</version>
</dependency>
```
And the karaf 3 version *does not* exist:
```xml 
<dependency>
<groupId>org.codice</groupId>
<artifactId>org.apache.karaf.bundle.core</artifactId>
<version>3.0.0.1</version>
<scope>compile</scope>
</dependency>
```
This change was uncovered when trying to call the …
> DDF-1945 Remove karaf 3 import and duplicate dependency

- pom.xml
Update NPM and NodeJS versions to address build issues in Bamboo.
@coyotesqrl @ahoffer 
@pklinef
@shaundmorris
Build DDF
The problem is caused by older versions of nodejs (<= 4.2.x) that fail on idle connections (see https://github.com/nodejs/node/issues/3595). Upgrading to a more recent version of nodejs that fixes issue #3595 addresses this issue.
DDF-2116
> DDF-2116: NPM related build errors in Bamboo

- catalog/transformer/catalog-transformer-geojson-input/pom.xml
- catalog/transformer/catalog-transformer-geojson-input/src/main/java/ddf/catalog/transformer/input/geojson/GeoJsonInputTransformer.java
- catalog/transformer/catalog-transformer-geojson-input/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/transformer/catalog-transformer-geojson-input/src/test/java/ddf/catalog/transformer/input/geojson/TestGeoJsonExtensible.java
- catalog/transformer/catalog-transformer-geojson-input/src/test/java/ddf/catalog/transformer/input/geojson/TestGeoJsonInputTransformer.java
- catalog/transformer/catalog-transformer-geojson-metacard/src/main/java/ddf/catalog/transformer/metacard/geojson/GeoJsonMetacardTransformer.java
- catalog/transformer/catalog-transformer-geojson-metacard/src/test/java/ddf/catalog/transformer/metacard/geojson/TestGeoJsonMetacardTransformer.java
This PR adds support for multivalued attributes with the GeoJSON transformers.  It also replaces the MetacardTypeRegistry with MetacardType OSGi services and fixes a bug with geometry collection handling.
@rzwiefel 
@djblue 
@kcwire
@pklinef
Using any metacard with multivalued attributes, export and import the metacard using the GeoJSON transformer and verify the multivalued attributes are intact.
https://codice.atlassian.net/browse/DDF-519
https://codice.atlassian.net/browse/DDF-1460
https://codice.atlassian.net/browse/DDF-2090
> DDF-519 DDF-1460 DDF-2090 GeoJSON multivalued attribute support

- distribution/docs/src/main/resources/_contents/_admin-contents/managing-admin-contents.adoc
- platform/admin/ui/bower.json
- platform/admin/ui/src/main/java/org/codice/admin/ui/configuration/Configuration.java
- platform/admin/ui/src/main/resources/OSGI-INF/metatype/metatype.xml
- platform/admin/ui/src/main/webapp/index.html
- platform/admin/ui/src/main/webapp/js/application.js
- platform/admin/ui/src/main/webapp/js/controllers/Modal.controller.js
- platform/admin/ui/src/main/webapp/js/controllers/SystemUsage.controller.js
- platform/admin/ui/src/main/webapp/js/views/SystemUsageModal.view.js
- platform/admin/ui/src/main/webapp/main.js
- platform/admin/ui/src/main/webapp/templates/systemUsage.layout.handlebars
Adds support for a modal to appear when hitting the admin page via a config file in the DDF_HOME/etc folder.
@ryeats @djblue 
@shaundmorris
@pklinef 
1. Go to: Admin -> DDF Admin -> Admin UI Configuration
2. Add an entry to System Usage Message Title, System Usage Message, and check Enable System Usage Message
3. Refresh the page and a modal should appear
I used the modal architecture we currently have implemented in the search ui
> DDF-2114: Add modal pop up support for the admin UI

- catalog/catalog-app/src/main/resources/features.xml
- catalog/core/catalog-core-commands/pom.xml
- catalog/core/catalog-core-commands/src/main/resources/bin/export
- catalog/core/catalog-core-commands/src/main/resources/bin/export.bat
This PR adds a Unix and Windows script for the catalog:dump --include-content and signs the exported jar.
@dcruver 
@jrnorth 
@jlcsmith
@beyelerb 
Build DDF and Install the catalog-app.  Use the added scripts to dump the catalog and verify that the zip is signed correctly.
This PR is dependent on the merge of DDF-2050
https://codice.atlassian.net/browse/DDF-2050
https://codice.atlassian.net/browse/DDF-2121
> DDF-2121 Added binaries for export/import

- distribution/ddf-common/src/main/resources/common-bin.xml
- distribution/ddf-common/src/main/resources/etc/log4j2.config.xml
- distribution/ddf-common/src/main/resources/etc/org.ops4j.pax.logging.cfg
- platform/platform-app/src/main/resources/features.xml
- Upgrade to log4j2
- Add XML configuration
- Add sample configuration for security log failover
@roelens8 @tbatie 
@kcwire
@pklinef
1. Build and itests should all pass (logging should occur in itests)
2. DDF distro should be unzipped and the following pre-start steps should be performed:
- edit `etc/org.ops4j.pax.logging.cfg`, uncommenting the line for log4j2 and deleting the subsequent lines
- edit `etc/startup.properties` and replace the artifact `pax-logging-log4j2` with the artifact `pax-logging-service` (same version and group)
3. Start DDF and ensure that only the log4j2 service provider is started: `list -t 0` should show the `OPS4J Pax Logging - API` and `OPS4J Pax Logging - Log4j v2` bundles; the v1 Pax logging service should not appear.
4. Complete DDF installation.
5. Stop the …
> DDF-2117 Upgrades to log4j2 and adds sample configuration for failing over the security logs

- libs/klv/pom.xml
- libs/klv/src/main/java/org/codice/ddf/libs/klv/KlvDataElement.java
- libs/klv/src/main/java/org/codice/ddf/libs/klv/data/numerical/KlvByte.java
- libs/klv/src/main/java/org/codice/ddf/libs/klv/data/numerical/KlvDouble.java
- libs/klv/src/main/java/org/codice/ddf/libs/klv/data/numerical/KlvFloat.java
- libs/klv/src/main/java/org/codice/ddf/libs/klv/data/numerical/KlvInt.java
- libs/klv/src/main/java/org/codice/ddf/libs/klv/data/numerical/KlvIntegerEncodedFloatingPoint.java
- libs/klv/src/main/java/org/codice/ddf/libs/klv/data/numerical/KlvLong.java
- libs/klv/src/main/java/org/codice/ddf/libs/klv/data/numerical/KlvNumericalDataElement.java
- libs/klv/src/main/java/org/codice/ddf/libs/klv/data/numerical/KlvShort.java
- libs/klv/src/main/java/org/codice/ddf/libs/klv/data/numerical/KlvUnsignedByte.java
- libs/klv/src/test/java/org/codice/ddf/libs/klv/KlvDecoderTest.java
- libs/klv/src/test/java/org/codice/ddf/libs/klv/Utilities.java
Add support for error indicator values for KLV. Some KLV fields are defined with error values that need to be detected by the application layer.
@jlcsmith @jaymcnallie @kcwire @jrnorth 
@jaymcnallie
@jlcsmith
This is a low-level library that isn't used by anything else in DDF, so there isn't a way to test it beyond the unit tests.
This is to support the klv data in mpeg-ts streams.
DDF-2126
> DDF-2126 add support for error indicator values to klv library

- catalog/spatial/registry/pom.xml
- catalog/spatial/registry/registry-app/pom.xml
- catalog/spatial/registry/registry-app/src/main/resources/features.xml
- catalog/spatial/registry/registry-publication-update-handler/pom.xml
- catalog/spatial/registry/registry-publication-update-handler/src/main/java/org/codice/ddf/registry/publication/RegistryPublicationHandler.java
- catalog/spatial/registry/registry-publication-update-handler/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/spatial/registry/registry-publication-update-handler/src/test/java/org/codice/ddf/registry/publication/RegistryPublicationHandlerTest.java
Adds a handler to forward registry updates to remote registry the local registry has published to. This is being pulled from the ddf-registry repo
@roelens8  @lessarderic 
@lessarderic
@pklinef 
Right now prbs is the only way to test
Coming over from the ddf-registry repo
DDF-2044
> DDF-2044 Added RegistryPublicationHandler to send registry updates to remote registry the local registry has published to

- catalog/spatial/registry/pom.xml
- catalog/spatial/registry/registry-app/pom.xml
- catalog/spatial/registry/registry-app/src/main/resources/features.xml
- catalog/spatial/registry/registry-report-action-provider/pom.xml
- catalog/spatial/registry/registry-report-action-provider/src/main/java/org/codice/ddf/registry/report/action/provider/RegistryMetacardActionProvider.java
- catalog/spatial/registry/registry-report-action-provider/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/spatial/registry/registry-report-action-provider/src/test/java/org/codice/ddf/registry/report/action/provider/TestRegistryMetacardActionProvider.java
Create ActionProvider for registry metacards to provide an action (url). Currently this ActionProvider link is accessible when searching for metacards with the registry tag in the search UI and then checking the available actions. 
@rzwiefel @kcwire @coyotesqrl 
@pklinef
@shaundmorris
Build, Confirm ActionProvider link in Search UI
This can be tested by following these steps:
1. Installing the registry app
2. Ingesting a registry metacard `ingest -t rim:RegistryPackage /Users/PathToYourDDF/ddf/catalog/spatial/registry/registry-ebrim-transformer/src/test/resources/csw-full-registry-package.xml`
3. Ingesting a second non-registry metacard
4. Open the search UI and do a wildcard search, the use the Details option to search for a **metacard-tags** contains **registry** search
5. Select the …
> DDF-2008 Merge registry report action provider from ddf-registry into ddf

- catalog/admin/admin-poller-service/src/main/java/org/codice/ddf/catalog/admin/poller/AdminPollerServiceBean.java
- catalog/admin/admin-poller-service/src/test/java/org/codice/ddf/catalog/admin/poller/AdminPollerTest.java
- platform/admin/core/admin-core-api/src/main/java/org/codice/ddf/ui/admin/api/ConfigurationAdmin.java
- platform/admin/core/admin-core-api/src/main/java/org/codice/ddf/ui/admin/api/ConfigurationAdminExt.java
- platform/admin/core/admin-core-api/src/test/java/org/codice/ddf/ui/admin/api/ConfigurationAdminExtTest.java
- platform/admin/core/admin-core-api/src/test/java/org/codice/ddf/ui/admin/api/ConfigurationAdminTest.java
- platform/security/sts/security-sts-ldapclaimshandler/src/main/java/ddf/security/sts/claimsHandler/ClaimsHandlerManager.java
- platform/security/sts/security-sts-ldaplogin/src/main/java/ddf/ldap/ldaplogin/LdapLoginConfig.java
- platform/security/sts/security-sts-ldaplogin/src/main/resources/OSGI-INF/blueprint/karaf_ldap_config.xml
- platform/security/sts/security-sts-ldaplogin/src/test/java/ddf/ldap/ldaplogin/LdapLoginConfigTest.java
Passwords values within any configuration will not be visible when inspecting its HTML input element via the chrome/developer console.
@ryeats @coyotesqrl @tbatie @bcwaters @jckilmer 
@pklinef
@stustison
-Verify that when changing a password to its correct value within some configuration, the password value is shown as "password" when inspecting its input element via the chrome/developer console. Then verify the password is still correct by testing the feature containing that password property, still works. 
DDF-2083
> DDF-2083 Fix password values within configurations to not be visible when inspected via chrome/developer console.

- distribution/ddf-common/src/main/resources/etc/org.apache.felix.fileinstall-definitions.cfg
Fixes an issue where a comment was getting included in a directory name, as well as cleaning up some other unneeded properties.
@jrnorth 
@rzwiefel 
@lessarderic
@pklinef
- Double-check against the documentation [here](http://felix.apache.org/documentation/subprojects/apache-felix-file-install.html)
- Build, run, verify there's only one `generated-bundles` directory
[DDF-2138](https://codice.atlassian.net/browse/DDF-2138)
> DDF-2138 Fix tmpdir with comment in name

- catalog/opensearch/catalog-opensearch-source/src/main/java/ddf/catalog/source/opensearch/OpenSearchSource.java
- catalog/opensearch/catalog-opensearch-source/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/opensearch/catalog-opensearch-source/src/test/java/ddf/catalog/source/opensearch/TestOpenSearchSource.java
- catalog/spatial/csw/spatial-csw-common/pom.xml
- catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/CswSourceConfiguration.java
- catalog/spatial/csw/spatial-csw-source-common/pom.xml
- catalog/spatial/csw/spatial-csw-source-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/AbstractCswSource.java
- catalog/spatial/csw/spatial-csw-source-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/AbstractCswStore.java
- catalog/spatial/csw/spatial-csw-source-common/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/CswSourceStub.java
- catalog/spatial/csw/spatial-csw-source-common/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/TestCswSource.java
- catalog/spatial/csw/spatial-csw-source-common/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/reader/TestGetRecordsMessageBodyReader.java
- catalog/spatial/csw/spatial-csw-source/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/source/CswSourceImpl.java
- catalog/spatial/csw/spatial-csw-source/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/spatial/pom.xml
- catalog/spatial/registry/registry-api-impl/src/main/java/org/codice/ddf/registry/api/impl/RegistryStoreImpl.java
- catalog/spatial/registry/registry-api-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/spatial/registry/registry-api-impl/src/test/java/org/codice/ddf/registry/api/TestRegistryStore.java
- catalog/spatial/wfs/1.0.0/spatial-wfs-v1_0_0-source/pom.xml
- catalog/spatial/wfs/1.0.0/spatial-wfs-v1_0_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v1_0_0/catalog/source/WfsSource.java
- catalog/spatial/wfs/1.0.0/spatial-wfs-v1_0_0-source/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/spatial/wfs/1.0.0/spatial-wfs-v1_0_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v1_0_0/catalog/source/TestWfsSource.java
- catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/pom.xml
- catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/source/WfsSource.java
- catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/source/TestWfsSource.java
- platform/security/encryption/platform-security-encryption-impl/src/main/java/ddf/security/encryption/impl/EncryptionServiceImpl.java
- platform/security/encryption/platform-security-encryption-impl/src/test/java/ddf/security/encryption/impl/EncryptionServiceImplTest.java
The following sources now support decrypting encrypted passwords:
catalog-opensearch-source
spatial-csw-source
spatial-wfs-v2_0_0-source
spatial-wfs-v1_0_0-source
catalog-registry-api-impl
@ryeats @coyotesqrl @tbatie @jckilmer @bcwaters @kcwire 
@shaundmorris
@stustison 
Enter an unencrypted password in a password field of a source configuration. Check the logs and verify it says a clear text password has been passed in. If possible, encrypt the password and pass it in a source configuration and verify the source works.
DDF-2094
> DDF-2094 Add support for decrypting encrypted passwords in sources

- catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/endpoint/CometdEndpoint.java
- catalog/ui/search-ui/standard/src/main/webapp/js/cometd.js
- catalog/ui/search-ui/standard/test.js
- distribution/docs/src/main/resources/_contents/extending-contents.adoc
- distribution/docs/src/main/resources/_contents/integrating-contents.adoc
- distribution/sdk/sample-cometd/cometd-java-example/src/main/java/org/codice/ddf/sdk/cometd/AsyncClient.java
- distribution/sdk/sample-cometd/cometd-web-example/README.md
- distribution/sdk/sample-cometd/cometd-web-example/src/main/webapp/js/application.js
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestSingleSignOn.java
- platform/security/policy/security-policy-context/src/test/java/org/codice/security/policy/context/PolicyManagerTest.java
Moves the `/cometd` context.
@kcwire
@pklinef
Full build and itests; install and ingest; ensure that search UI works correctly.
Currently, the webcontext policy for the `/search` and `/cometd` contexts must be kept in lockstep. As there is no reason for the `/cometd` context to be directly beneath the root, this move will simplify security configuration for our users.
DDF-2134
N/A
> DDF-2134 Moves /cometd context beneath the /search context, to /search/cometd

- catalog/spatial/csw/spatial-csw-source-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/AbstractCswSource.java
- catalog/spatial/csw/spatial-csw-source-common/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/TestCswSource.java
Forces an immediate re-poll of CSW sources when their configuration changes. This will recheck availability when the configuration is updated rather than waiting until the CSW polling interval has passed.
@ryeats @adimka @bcwaters 
@jaymcnallie
@kcwire
Ensure that all tests pass; install; create a CSW Federated source with incorrect credentials and see that it does not connect. Edit the source and update with correct credentials and confirm that it reconnects.
N/A
DDF-2148
N/A
> DDF-2148 Force immediate re-poll of CSW source on configuration change.

- catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/CatalogCommands.java
- catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/DumpCommand.java
- catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/IngestCommand.java
- catalog/core/catalog-core-commands/src/test/java/org/codice/ddf/commands/catalog/TestDumpCommand.java
- catalog/core/catalog-core-commands/src/test/java/org/codice/ddf/commands/catalog/TestIngestCommand.java
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestConfiguration.java
This PR changes the default transformer in dump/ingest commands to use the XML transformer as opposed to using Java Serialized Objects.
@dcruver 
@glenhein 
@jlcsmith
@kcwire 
Build and Run DDF.  Run catalog:ingest and catalog:dump and verify that the transformers are correct.
https://codice.atlassian.net/browse/DDF-2112
> DDF-2112 Changed default transformer in catalog-core-commands to XML

- distribution/ddf-common/src/main/resources/bin/setenv
- distribution/ddf-common/src/main/resources/bin/setenv.bat
Updates the setenv file to only use posix shell commands (instead of the currently-used bash commands). Also moved the added -D option to the EXTRA_JAVA_OPS environment variable.
@dcruver @jrnorth 
@jlcsmith
@kcwire
Unzip and run on ubuntu - verify that the environment variable is added (assuming /bin/sh is pointing to dash instead of bash). You can echo the karaf executable line in the karaf file instead of executing it to see the actual final command execution.
Installing on CentOS 7 uncovered the fact that the current script was failing and not adding the -D option correctly, resulting in system hang. CentOS 7 by default uses dash instead of bash as /bin/sh.
DDF-2115
> DDF-2115 Updated the setenv script to use standard posix commands

- platform/security/expansion/security-expansion-impl/src/main/java/ddf/security/expansion/impl/AbstractExpansion.java
Fixes a bug in AbstractExpansion that was causing windows attributes expansion .cfg files to not be parsed
@Lambeaux @zryan3 @spearskw 
@lessarderic 
@stustison
DDF-2150
Switch to using Path constructor and logic
> DDF-2150 Fix path bug in AbstractExpansion

- catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/IngestCommand.java
- catalog/transformer/catalog-transformer-zip/src/main/java/org/codice/ddf/catalog/transformer/zip/ZipCompression.java
- catalog/transformer/catalog-transformer-zip/src/test/java/org/codice/ddf/catalog/transformer/zip/TestZipCompression.java
This PR adds a `metacards` folder to the zip file generated from catalog:dump --include-content.  Also updated catalog:ingest --include-content to respect this change.
@jrnorth 
@glenhein 
@jlcsmith
@kcwire
Build DDF and run catalog:ingest and catalog:dump using --include-content, and verify that the metacards file exists and the commands still work.
https://codice.atlassian.net/browse/DDF-2136
> DDF-2136 Added metacard peer folder to dump/ingest include content zip

- catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/controller/AbstractEventController.java
- catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/controller/ActivityController.java
- catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/controller/NotificationController.java
- catalog/ui/search-ui/search-endpoint/src/test/java/org/codice/ddf/ui/searchui/query/controller/ActivityControllerTest.java
- catalog/ui/search-ui/search-endpoint/src/test/java/org/codice/ddf/ui/searchui/query/controller/NotificationControllerTest.java
DDF search ui notifications were not sending. This fixes the subject lookup and causes the user to be registered correctly so that notifications are passed to them. Logic was also added to allow for the upload notification to be sent as well, since they only provide sessionId.
@oconnormi 
@figliold 
@lessarderic
@pklinef
Ingest a product form the search ui, make sure that a notification is delivered. Search and download that product with a clean Product_Cache, make sure that a notification is delivered.
Previous to this, upload notifications would work because of the way that the subject registration was failing. The sessionId search backup is a way to keep the upload notifications working, as well as any other notifications that send a sessionId only. If the upload notifications are …
> DDF-2147: Fixed CometD registration and lookup for notifications

- catalog/ui/search-ui/standard/Gruntfile.js
- pom.xml
Disables NPM install scripts to make build safer
@spearskw @AzGoalie @djblue 
@shaundmorris
@stustison
Make sure DDF still builds 👍 after clearing all npm, node and node_module directories from your DDF directory
DDF-2153
Add --ignore-scripts to top pom
> DDF-2153 Disable NPM install scripts

- catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/ContentDirectoryMonitor.java
- catalog/security/catalog-security-filter/src/main/java/ddf/catalog/security/filter/plugin/FilterPlugin.java
- catalog/spatial/csw/spatial-csw-source-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/AbstractCswSource.java
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestRegistry.java
- platform/platform-scheduler/src/main/java/ddf/platform/scheduler/CommandJob.java
- platform/security/common/src/main/java/org/codice/ddf/security/common/Security.java
- platform/security/common/src/test/java/org/codice/ddf/security/SecurityTest.java
Moves the subject role check from runWithSubjectOrElevate() into getSystemSubject() within the Security class. 
@ryeats @coyotesqrl @bcwaters @tbatie @jckilmer 
@pklinef
@stustison
PRBS.
There are some operations that require the system subject, but are not associated with a user. These operations cannot retrieve the system subject due to not having a java subject containing an admin role. In order to fix this, I have added a method that creates a java subject with an admin role and can run an action using that subject.
DDF-2113
> DDF-2113 Move subject role check for admin into getSystemSubject()

- pom.xml
Fixes a bug where in some cases the ExternalParser class could not be found, and an error would be thrown. This affected the FTP when trying to ingest a file whose transformer may not have been installed. For example, a .ntf file being ingested without the Imagery app.
@mweser @troymohl 
@jaymcnallie 
@kcwire
Successful full build and itests.
[DDF-2127](https://codice.atlassian.net/browse/DDF-2127)
> DDF-2127: Update Tika from version 1.11.0 to 1.13.0

- catalog/catalog-app/src/main/resources/features.xml
- catalog/core/catalog-core-ftp/pom.xml
- catalog/core/catalog-core-ftp/src/main/java/ddf/catalog/core/ftp/FtpServerStarter.java
- catalog/core/catalog-core-ftp/src/main/java/ddf/catalog/core/ftp/UserManagerImpl.java
- catalog/core/catalog-core-ftp/src/main/java/ddf/catalog/core/ftp/ftplets/FtpRequestHandler.java
- catalog/core/catalog-core-ftp/src/main/java/ddf/catalog/core/ftp/user/FtpUser.java
- catalog/core/catalog-core-ftp/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/core/catalog-core-ftp/src/test/java/ddf/catalog/core/ftp/UserManagerImplTest.java
- catalog/core/catalog-core-ftp/src/test/java/ddf/catalog/core/ftp/ftplets/FtpRequestHandlerTest.java
- catalog/core/pom.xml
- catalog/pom.xml
- distribution/docs/src/main/resources/_contents/_catalog-contents/integrating-catalog-contents.adoc
This PR provides an FTP endpoint for ingesting files into the DDF catalog. Features:
-Basic Auth
-PUT & MPUT operations
@mweser @troymohl @dcruver @ricklarsen 
@jaymcnallie
@kcwire
-Install the FTP feature in DDF Catalog -> Features
-Connect to the FTP server using your favorite client. Address is `localhost` and default port is `8021`. The login is the /etc/users.properties users. Default is admin/admin
-Ingest a file with the PUT or MPUT commands and verify it is correctly ingested and searchable in the Search UI.
_NOTE:_ Ingesting a .ntf file without first installing the Alliance Imagery App will cause Tika to throw an error and cause the FTP server to hang. There is a bug in Tika which is fixed in 1.12. DDF-2127 has been created to address this.
The purpose of the ticket is to …
> DDF-2048: Provides support for ingesting files through an FTP Endpoint

- catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/controller/AbstractEventController.java
Registers Guests by their sessionId so that multiple Guest usrs from the same IP address will have notifications delivered properly.
@lessarderic
@pklinef
Update to original DDF-2147 PR.
> DDF-2147: Fixed guest user cross-notifications

- catalog/plugin/catalog-plugin-videothumbnail/src/main/java/org/codice/ddf/catalog/content/plugin/video/VideoThumbnailPlugin.java
Send ffmpeg stderr and stdout to /dev/null instead of the console.
@rzwiefel @jrnorth @dcruver @kcwire 
@jaymcnallie
@jlcsmith
Steps to recreate:
start and install DDF
open search UI
Click upload and select a movie clip (.mpg, .mov, .ts) and click Start Upload
Once the upload finishes, note the ffmpeg output is not being logged to System.out in the karaf console.
There's no way to create a unit test for this, at least not that I know of.
DDF-2123
> DDF-2123 send ffmpeg stdout and stderr to /dev/null

- catalog/spatial/csw/spatial-csw-source-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/AbstractCswSource.java
- catalog/spatial/registry/registry-api-impl/pom.xml
- catalog/spatial/registry/registry-api-impl/src/main/java/org/codice/ddf/registry/api/impl/RegistryStoreImpl.java
- catalog/spatial/registry/registry-api-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/spatial/registry/registry-api-impl/src/main/resources/OSGI-INF/metatype/metatype.xml
- catalog/spatial/registry/registry-api-impl/src/test/java/org/codice/ddf/registry/api/impl/TestRegistryStore.java
- catalog/spatial/registry/registry-api/src/main/java/org/codice/ddf/registry/api/RegistryStore.java
This PR merges the changes made to the RegistryStoreImpl from ddf-registry to ddf. The logic has been updated since RegistryStoreImpl and the IdentityPlugin both were performing similar operations to update metacard ids within the ebrim method. This functionality was also improved with other minor changes and extra unit tests were added. 
@spearskw @harrison-tarr 
@pklinef
@shaundmorris
Please review the code, build and run the tests.
DDF-2057 Update RegistryStoreImpl to gather remote name for Remote Registry UI
DDF-2099 Improve test coverage in registry-api-impl
DDF-2109 Refactor Logic
Backend functionality - once the ui is merged a Remote Name field should be populated on the Remote Registries tab after the registry becomes available.
> DDF-2109 Merge RegistryStoreImpl from ddf-registry to ddf

- catalog/plugin/catalog-plugin-metacard-validation/pom.xml
- catalog/plugin/catalog-plugin-metacard-validation/src/main/java/ddf/catalog/metacard/validation/MetacardValidityFilterPlugin.java
- catalog/plugin/catalog-plugin-metacard-validation/src/main/java/ddf/catalog/metacard/validation/MetacardValidityMarkerPlugin.java
- catalog/plugin/catalog-plugin-metacard-validation/src/test/java/ddf/catalog/metacard/validation/MetacardValidityFilterPluginTest.java
- catalog/plugin/catalog-plugin-metacard-validation/src/test/java/ddf/catalog/metacard/validation/MetacardValidityMarkerPluginTest.java
- distribution/sdk/sample-metacard-validator/pom.xml
- distribution/sdk/sample-metacard-validator/src/main/java/org/codice/ddf/sdk/validation/metacard/SampleMetacardValidator.java
- distribution/sdk/sample-metacard-validator/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalog.java
Updates `MetacardValidityMarkerPlugin` so it runs on update requests.
@bdeining 
@glenhein 
@jlcsmith
@kcwire
Create a validator using a validation JSON file. Ingest a metacard that your validator will fail. Verify that the proper errors and warnings are present on the metacard. Submit an update request for the metacard that will allow your validator to pass it and verify that the updated metacard has no warnings or errors.
Ingest a metacard that your validator will pass. Submit an update request for the metacard that will cause your validator to fail it and verify that the updated metacard has the proper warnings and errors.
Also verify that enforced metacard validators still work (i.e. if you have an enforced metacard validator and it fails your metacard, that metacard …
> DDF-2082 Fix MetacardValidityMarkerPlugin so it runs on update requests

- catalog/spatial/registry/pom.xml
- catalog/spatial/registry/registry-app/pom.xml
- catalog/spatial/registry/registry-app/src/main/resources/features.xml
- catalog/spatial/registry/registry-federation-admin-api/src/main/java/org/codice/ddf/registry/federationadmin/FederationAdminMBean.java
- catalog/spatial/registry/registry-federation-admin-impl/pom.xml
- catalog/spatial/registry/registry-federation-admin-impl/src/main/java/org/codice/ddf/registry/federationadmin/impl/AdminHelper.java
- catalog/spatial/registry/registry-federation-admin-impl/src/main/java/org/codice/ddf/registry/federationadmin/impl/FederationAdmin.java
- catalog/spatial/registry/registry-federation-admin-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/spatial/registry/registry-federation-admin-impl/src/test/java/org/codice/ddf/registry/federationadmin/impl/FederationAdminTest.java
- catalog/spatial/registry/registry-federation-admin-impl/src/test/resources/csw-full-registry-package.xml
- catalog/spatial/registry/registry-federation-admin-impl/src/test/resources/csw-registry-package-smaller.xml
- catalog/spatial/registry/registry-federation-admin-impl/src/test/resources/etc/registry/registry-custom-slots.json
- catalog/spatial/registry/registry-schema-bindings/pom.xml
- distribution/ddf-common/src/main/resources/etc/registry/registry-custom-slots.json
Adds the registry-federation-admin-impl module which provides an mbean for accessing/update registry information. This is an initial PR and can't be heroed or built until other peer PRs are merged.
@AzGoalie @spearskw 
@figliold 
@stustison
Outside of unit/itests 
1) Bring up an instance of DDF and start the DDF Registry app
2) Hit the endpoint https://localhost:8993/admin/jolokia/read/org.codice.ddf.registry:type=FederationAdminMBean/LocalNodes
3) Verify that you get a response back that has the following
- one identity node in the 'nodes' array
- six entries in the custom slots
- two entries in the auto populate service bindings
This module is coming over from the ddf-registry repo.
DDF-2101
> DDF-2101 Created registry-federation-admin-impl to enable UI access to registry features

- catalog/spatial/registry/registry-federation-admin-service-impl/src/main/java/org/codice/ddf/registry/federationadmin/service/impl/FederationAdminServiceImpl.java
Fixes but in FederationAdminService where the init method isn't using the admin subject.
@mcalcote @oscaritoro 
@shaundmorris
Startup ddf and install registry. Look at the logs and verify there is no error coming from the FederationAdminService
DDF-2178
> DDF-2178 Fixed FederationAdminServiceImpl init missing subject issue

- distribution/ddf-common/src/main/resources/etc/shell.init.script
Fixes the temporary crutch that is waitForReady (and aliases it to `wfr`)
@vinamartin 
@tbatie 
@stustison
@coyotesqrl  😄
> DDF-2182: Fixed waitForReady script to wait for 3 bundle fragments.

- catalog/spatial/registry/registry-federation-admin-service-impl/src/main/java/org/codice/ddf/registry/federationadmin/service/impl/FederationAdminServiceImpl.java
- catalog/spatial/registry/registry-federation-admin-service-impl/src/main/java/org/codice/ddf/registry/federationadmin/service/impl/RegistryPublicationServiceImpl.java
- catalog/spatial/registry/registry-federation-admin-service-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/spatial/registry/registry-federation-admin-service-impl/src/test/java/org/codice/ddf/registry/federationadmin/service/impl/FederationAdminServiceImplTest.java
- catalog/spatial/registry/registry-federation-admin-service-impl/src/test/java/org/codice/ddf/registry/federationadmin/service/impl/RegistryPublicationServiceImplTest.java
- catalog/spatial/registry/registry-federation-admin-service/src/main/java/org/codice/ddf/registry/federationadmin/service/FederationAdminService.java
- catalog/spatial/registry/registry-federation-admin-service/src/main/java/org/codice/ddf/registry/federationadmin/service/RegistryPublicationService.java
- catalog/spatial/registry/registry-publication-update-handler/src/main/java/org/codice/ddf/registry/publication/RegistryPublicationHandler.java
- catalog/spatial/registry/registry-publication-update-handler/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/spatial/registry/registry-publication-update-handler/src/test/java/org/codice/ddf/registry/publication/RegistryPublicationHandlerTest.java
A new service is added to handle publishing, unpublishing, and updating published registries.
@clockard @ryeats
@figliold
@shaundmorris
DDF-2181
Creating RegistryPublicationService used for publishing, unpublishing, and pushing local metacard to the published locations
Adding getLocalRegistryIdentityMetacard to FederationAdminService
Changing RegistryPublicationHandler to using the RegsitryPublicationService for the update
> DDF-2181 Create registry publication service

- catalog/core/catalog-core-standardframework/pom.xml
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/ResourceCacheInterface.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/impl/ResourceCacheImpl.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/CatalogFrameworkImpl.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/FrameworkProperties.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/resource/data/ReliableResource.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/resource/download/ReliableResourceDownloadManager.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/resource/download/ReliableResourceDownloader.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/resource/download/ReliableResourceDownloaderConfig.java
- catalog/core/catalog-core-standardframework/src/main/java/org/codice/ddf/catalog/resource/cache/ResourceCache.java
- catalog/core/catalog-core-standardframework/src/main/java/org/codice/ddf/catalog/resource/cache/impl/ResourceCacheImpl.java
- catalog/core/catalog-core-standardframework/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/cache/ResourceCacheImplSizeLimitTest.java
- catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/cache/impl/ResourceCacheImplTest.java
- catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/event/retrievestatus/DownloadsStatusEventListenerTest.java
- catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/impl/CatalogFrameworkImplTest.java
- catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/resource/download/ReliableResourceDownloadManagerTest.java
- catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/resource/download/ReliableResourceDownloaderTest.java
Created new `org.codice.ddf.resource.cache.ResourceCache` interface, deprecated existing `ResourceCacheInterface`, added new interface to `ResourceCache` class with implementations that delegate to the existing code and wrote unit tests.
@figliold 
@Lambeaux 
@cmthom10 
@oconnormi 
@bantillo 
@coyotesqrl
@pklinef
Build and run integration tests
See https://codice.atlassian.net/browse/DDF-2185
See https://codice.atlassian.net/browse/DDF-2185
> DDF-2185: Create new cache interface and deprecate ResourceCacheInterface

- distribution/docs/src/main/resources/_contents/_security-contents/integrating-security-contents.adoc
- platform/security/sts/security-sts-ldaplogin/pom.xml
- platform/security/sts/security-sts-ldaplogin/src/main/java/ddf/ldap/ldaplogin/LdapLoginConfig.java
- platform/security/sts/security-sts-ldaplogin/src/main/java/ddf/ldap/ldaplogin/LdapService.java
- platform/security/sts/security-sts-ldaplogin/src/main/resources/OSGI-INF/blueprint/karaf_ldap_config.xml
- platform/security/sts/security-sts-ldaplogin/src/test/java/ddf/ldap/ldaplogin/LdapLoginConfigTest.java
- Updates the LDAP login bundle so it will actually use the configured username attribute
- Updates the LDAP Claims Handler and LDAP Login configuration documentation
@bdeining 
@jlcsmith
@stustison
Set up the embedded LDAP server (or some other LDAP server) with a username attribute other than "uid". Start the LDAP login bundle and configure it to use that username attribute. Verify that you can log in via LDAP.
[DDF-2183](https://codice.atlassian.net/browse/DDF-2183)
> DDF-2183 STS LDAP login bundle uses the configured username attribute

- distribution/test/itests/test-itests-common/pom.xml
- distribution/test/itests/test-itests-common/src/test/java/ddf/common/test/mock/csw/FederatedCswMockServer.java
- distribution/test/itests/test-itests-common/src/test/java/ddf/common/test/restito/ChunkedContent.java
- distribution/test/itests/test-itests-common/src/test/resources/csw-get-capabilities-response.xml
- distribution/test/itests/test-itests-common/src/test/resources/csw-query-response-modified.xml
- distribution/test/itests/test-itests-common/src/test/resources/csw-query-response.xml
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFederation.java
- distribution/test/itests/test-itests-ddf/src/test/resources/open-search-stub-query-response.xml
Adds integration tests for federated resource downloading and caching. Also adds a reusable restito stub server class and a retrieval action class for live csw itest federation.
@tbatie 
@oconnormi 
@bantillo 
@Lambeaux 
@cmthom10 
@figliold
@lessarderic
- Added integration tests to test current resource downloading functionality.
- Added reusable classes for setting up a federated CSW stub server for
integration tests
> DDF-2168: Add integration tests for resource download & caching

- catalog/catalog-app/src/main/resources/features.xml
- catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/data/impl/BasicTypes.java
- catalog/core/catalog-core-api/src/main/java/ddf/catalog/data/Metacard.java
- catalog/core/catalog-core-resourcestatusplugin/pom.xml
- catalog/core/catalog-core-resourcestatusplugin/src/main/java/ddf/catalog/core/resourcestatus/metacard/MetacardResourceStatus.java
- catalog/core/catalog-core-resourcestatusplugin/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/core/catalog-core-resourcestatusplugin/src/test/java/ddf/catalog/core/resourcestatus/metacard/MetacardResourceStatusTest.java
- catalog/core/pom.xml
- distribution/docs/src/main/resources/_contents/integrating-contents.adoc
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalog.java
* Adds a field to each `Metacard` to allow for indicating the cache status of a related resource
* Adds a `PostQueryPlugin` to check the resource cache for resources related to each `Metacard`
@lessarderic 
@Lambeaux 
@figliold 
@shaundmorris 
1. Upload a resource to the DDF
2. run `catalog:inspect <id>` and verify `resource.cache-status` is `false`
3. trigger retrieval of the resource
4. run `catalog:inspect <id>` and verify that `resource.cache-status` is now set to `true`
[DDF-2175](https://codice.atlassian.net/browse/DDF-2175)
> DDF-2175: Added field to indicate resource cache status

- catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/event/impl/SubscriptionImpl.java
- catalog/core/catalog-core-api/src/main/java/ddf/catalog/event/Subscription.java
- catalog/core/catalog-core-api/src/main/java/ddf/catalog/operation/Pingable.java
- catalog/core/catalog-core-eventcommands/src/main/java/ddf/catalog/pubsub/command/DeleteCommand.java
- catalog/core/catalog-core-eventcommands/src/main/java/ddf/catalog/pubsub/command/ListCommand.java
- catalog/core/catalog-core-eventcommands/src/main/java/ddf/catalog/pubsub/command/SubscriptionsCommand.java
- catalog/core/catalog-core-eventcommands/src/test/java/ddf/catalog/pubsub/command/ListCommandTest.java
- catalog/core/catalog-core-impl/pubsub/src/main/java/ddf/catalog/pubsub/EventProcessorImpl.java
- catalog/core/catalog-core-impl/pubsub/src/main/java/ddf/catalog/pubsub/FanoutEventProcessor.java
- catalog/core/catalog-core-impl/pubsub/src/main/java/ddf/catalog/pubsub/PublishedEventHandler.java
- catalog/core/catalog-core-impl/pubsub/src/test/java/ddf/catalog/pubsub/MockSubscription.java
- catalog/core/catalog-core-standardframework/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/spatial/csw/spatial-csw-endpoint/pom.xml
- catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswSubscriptionEndpoint.java
- catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/event/CswSubscription.java
- catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/event/SendEvent.java
- catalog/spatial/csw/spatial-csw-endpoint/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/spatial/csw/spatial-csw-endpoint/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/event/SendEventTest.java
- platform/security/common/src/main/java/org/codice/ddf/security/common/OutgoingSubjectRetrievalInterceptor.java
- platform/security/common/src/main/java/org/codice/ddf/security/common/Security.java
- platform/security/interceptor/security-interceptor-guest/src/main/java/org/codice/ddf/security/interceptor/GuestInterceptor.java
- platform/security/interceptor/security-interceptor-guest/src/main/resources/OSGI-INF/blueprint/blueprint.xml
updates the OutgoingSubjectRetrievalInterceptor to support the jax-ws handler interface, move the CSW ping logic into the event processor so that all subscriptions are checked to see if they are active before an event is processed. Adds logic to obtain a guest subject to the Security utility class.
@pklinef subbing in @lessarderic 
@stustison 
@jckilmer @coyotesqrl @tbatie @roelens8 @bcwaters 
run itests
This is just cleaning up logic driven by other security related tickets.
> DDF-2140 Check if response handler is active before evaluating if an event should be sent

- catalog/core/catalog-core-standardframework/pom.xml
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/CatalogFrameworkImpl.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/FrameworkProperties.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/resource/download/ReliableResourceDownloadManager.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/resource/download/ReliableResourceDownloaderConfig.java
- catalog/core/catalog-core-standardframework/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/core/catalog-core-standardframework/src/main/resources/OSGI-INF/metatype/downloadManager.xml
- catalog/core/catalog-core-standardframework/src/main/resources/OSGI-INF/metatype/metatype.xml
- catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/event/retrievestatus/DownloadsStatusEventListenerTest.java
- catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/impl/CatalogFrameworkImplTest.java
- catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/resource/download/ReliableResourceDownloadManagerTest.java
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/CatalogBundle.java
Removes the dependency between CatalogFrameworkImpl (CFI) and ResourceCache
* ResourceCache is injected into ReliableResourceDownloadManager (RRDM)
* RRDM takes only a single ctor arg of `ReliableResourceDownloaderConfig` (RRDC)
* RRDM now has a metatype for configuring Resource Download and Cache settings
* CFI no longer configures caching or resource download settings
@lessarderic 
@Lambeaux 
@figliold 
@coyotesqrl
@pklinef 
Ingest a product and check that it is cached after download
[DDF-2202](https://codice.atlassian.net/browse/DDF-2202)
> DDF-2202: Remove dependency between CatalogFrameworkImpl and ResourceCache

- catalog/core/catalog-core-camelcomponent/src/main/java/ddf/camel/component/catalog/inputtransformer/InputTransformerProducer.java
- catalog/opensearch/catalog-opensearch-source/src/main/java/ddf/catalog/source/opensearch/OpenSearchSource.java
- catalog/rest/catalog-rest-endpoint/src/main/java/org/codice/ddf/endpoints/rest/RESTEndpoint.java
- catalog/spatial/geocoding/spatial-geocoding-extract/pom.xml
- catalog/spatial/geocoding/spatial-geocoding-extract/src/main/java/org/codice/ddf/spatial/geocoding/extract/GeoNamesFileExtractor.java
- catalog/spatial/registry/registry-ebrim-transformer/pom.xml
- catalog/spatial/registry/registry-ebrim-transformer/src/main/java/org/codice/ddf/registry/transformer/RegistryTransformer.java
- catalog/transformer/catalog-transformer-pptx/src/main/java/ddf/catalog/transformer/input/pptx/PptxInputTransformer.java
- catalog/transformer/catalog-transformer-tika-input/pom.xml
- catalog/transformer/catalog-transformer-tika-input/src/main/java/ddf/catalog/transformer/input/tika/TikaInputTransformer.java
- distribution/docs/src/main/resources/_contents/_platform-contents/extending-platform-contents.adoc
- platform/platform-app/src/main/resources/features.xml
- platform/platform-filter-delegate/pom.xml
- platform/util/platform-util/pom.xml
- platform/util/platform-util/src/main/java/org/codice/ddf/platform/util/TemporaryFileBackedOutputStream.java
- platform/util/platform-util/src/test/java/org/codice/ddf/platform/util/TestTemporaryFileBackedOutputStream.java
Create a wrapper class around FileBackedOutputStream that automatically deletes the temporary backing file.
@jrnorth @rzwiefel @kcwire @dcruver 
@beyelerb
@kcwire
Run unit tests. 
FileBackedOutputStream does not delete its temp file when close() is called. Must call reset() as well.
DDF-2154
> DDF-2154 create a better wrapped version of FileBackedOutputStream

- catalog/pom.xml
- catalog/spatial/registry/pom.xml
- catalog/spatial/registry/registry-app/pom.xml
- catalog/spatial/registry/registry-app/src/main/resources/features.xml
- catalog/spatial/registry/registry-publication-action-provider/pom.xml
- catalog/spatial/registry/registry-publication-action-provider/src/main/java/org/codice/ddf/registry/publication/action/provider/RegistryPublicationActionProvider.java
- catalog/spatial/registry/registry-publication-action-provider/src/main/java/org/codice/ddf/registry/publication/manager/RegistryPublicationManager.java
- catalog/spatial/registry/registry-publication-action-provider/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/spatial/registry/registry-publication-action-provider/src/test/java/org/codice/ddf/registry/publication/action/provider/RegistryPublicationActionProviderTest.java
- catalog/spatial/registry/registry-publication-action-provider/src/test/java/org/codice/ddf/registry/publication/manager/RegistryPublicationManagerTest.java
A new action provider is being added that returns a RESTful endpoint used for publishing/unpublishing a registry node.
@ryeats @lessarderic 
@figliold
@shaundmorris 
DDF-2165
Adding RegistryPublicationActionProvider
Provides the action(RESTful endpoint) to publish/unpublish a registry entry to an external source
> DDF-2165 Create registry action provider for publishing/unpublishing

- catalog/spatial/registry/registry-publication-update-handler/src/main/java/org/codice/ddf/registry/publication/RegistryPublicationHandler.java
- catalog/spatial/registry/registry-source-configuration-handler/src/main/java/org/codice/ddf/registry/source/configuration/SourceConfigurationHandler.java
- platform/security/common/src/main/java/org/codice/ddf/security/common/Security.java
- platform/security/common/src/test/java/org/codice/ddf/security/SecurityTest.java
Runs some 'system' commands in the registry handlers as admin so the commands don't get blocked by security.
@coyotesqrl
@stustison 
Startup DDF and install the DDF-Registry app. Add a new additional node in the DDF-Registry->Local Node Information with at least one service binding. Verify that the node shows up in the sources tab as disabled. Configure the DDF-Registry to auto start configurations by going to DDF-Registry->Configuration-> Registry Source Configuration Handler and checking Activate Configurations and unchecking Preserve Active Configuration. Save the configuration and go back to the sources tab and verify that the node is no longer disabled. 
DDF-2219
> DDF-2219 Fixed Registry handlers to use the admin subject when executing system call

- catalog/core/catalog-core-api/src/main/java/ddf/catalog/content/operation/ContentMetadataExtractor.java
- catalog/security/catalog-security-metacardattributeplugin/src/main/java/org/codice/ddf/catalog/security/policy/metacard/MetacardAttributeSecurityPolicyPlugin.java
- catalog/security/catalog-security-metacardattributeplugin/src/main/resources/OSGI-INF/metatype/metatype.xml
- catalog/security/catalog-security-metacardattributeplugin/src/test/java/org/codice/ddf/catalog/security/policy/metacard/MetacardAttributeSecurityPolicyPluginTest.java
- catalog/transformer/catalog-transformer-common/src/main/java/ddf/catalog/transformer/common/tika/MetacardCreator.java
- catalog/transformer/catalog-transformer-common/src/test/java/ddf/catalog/transformer/common/tika/MetacardCreatorTest.java
- catalog/transformer/catalog-transformer-pdf/pom.xml
- catalog/transformer/catalog-transformer-pdf/src/main/java/ddf/catalog/transformer/input/pdf/PdfInputTransformer.java
- catalog/transformer/catalog-transformer-pdf/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/transformer/catalog-transformer-pdf/src/test/groovy/ddf/catalog/transformer/input/pdf/PdfInputTransformerSpecTest.groovy
- catalog/transformer/catalog-transformer-tika-input/pom.xml
- catalog/transformer/catalog-transformer-tika-input/src/main/java/ddf/catalog/transformer/input/tika/TikaInputTransformer.java
- catalog/transformer/catalog-transformer-tika-input/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/transformer/catalog-transformer-tika-input/src/test/java/ddf/catalog/transformer/input/tika/TikaInputTransformerTest.java
- distribution/docs/src/main/resources/_contents/_catalog-contents/configuring-catalog-contents.adoc
- distribution/docs/src/main/resources/_contents/securing-contents.adoc
This PR adds a new service interface for reading the content of a text document and parsing out any specific metadata it may have to be added to its associated `Metacard`s. The two text importers - 
Tika and PDF - have been updated to find the `ContentMetadataExtractor` implementors and process each of them in turn.
This change also updates the `MetacardAttributeSecurityPolicyPlugin` so that it takes key-value pairs of attribute names. The metacard is checked to see if it has attributes named by those keys and then creates security policy map entries keyed by the values.
@rzwiefel @bcwaters @brendan-hofmann 
@kcwire
@stustison
A full build/test run should be sufficient at this time. (An) implementation(s) of the `ContentMetadataExtractor` could be built and deployed and then tested …
> DDF-2188 Adds new service definition for extracting metadata from text content files.

- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/resource/download/ReliableResourceDownloadManager.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/resource/download/ReliableResourceDownloader.java
Consolidates all publish events to the `ReliableResourceDownloader` which is responsible for the full download lifecycle. Only the "Download Started" event was still in the manager and had to be moved. 
@cmthom10 
@figliold 
@emanns95
@lessarderic
@shaundmorris
Validate the build. Using a CometD client of your choice, initiate downloads and ensure the JSON notification for **Download.STARTED** is received. See @oconnormi or @Lambeaux for more details. 
This is part of the reliable resource refactor for a new download endpoint. See @lessarderic for more information if desired.
**DDF-2194**, DDF-2210, and DDF-2215
> DDF-2194: Move the "Download Started" publish event to the ReliableResourceDownloader

- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestRegistry.java
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/common/Library.java
- distribution/test/itests/test-itests-ddf/src/test/resources/csw-query.xml
- distribution/test/itests/test-itests-ddf/src/test/resources/csw-rim-node.xml
Updated the registry itests to test the functionality of the `RegistryStore`(update, create, and delete) tested by calling upon methods within the `FederationAdminServiceImpl`. Also tests the functionality of the REST endpoint. 
@clockard 
@vinamartin 
@brianfelix 
@mcalcote 
@lessarderic
@stustison 
Build and run itests
- `FederationAdminService` is not declared globally because within the itest it loads at a different time causing a `ClassNotFoundException`
- The reasoning behind using `FederationAdminServiceImpl` within the itest is to test the functionality of the `RegistryStore`. Currently, there is not a REST endpoint that provides CUD operations with a destination which is required to test the `RegistryStore`, making the `RegistryStore` only reachable through …
> DDF-2146 Update Registry itests

- catalog/spatial/registry/registry-federation-admin-service-impl/pom.xml
- catalog/spatial/registry/registry-federation-admin-service-impl/src/main/java/org/codice/ddf/registry/federationadmin/service/impl/FederationAdminServiceImpl.java
- catalog/spatial/registry/registry-federation-admin-service-impl/src/main/java/org/codice/ddf/registry/federationadmin/service/impl/IdentityNodeInitialization.java
- catalog/spatial/registry/registry-federation-admin-service-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/spatial/registry/registry-federation-admin-service-impl/src/test/java/org/codice/ddf/registry/federationadmin/service/impl/FederationAdminServiceImplTest.java
- catalog/spatial/registry/registry-federation-admin-service-impl/src/test/java/org/codice/ddf/registry/federationadmin/service/impl/IdentityNodeInitializationTest.java
Extracts the identity node intialization methods, `init(),  createIdentityNode(), getRegistryMetcardFromRegistryPackage()` from `FederationAdminServiceImpl` and places them within the new class `IdentityNodeInitialization` . A new test class was implemented due to this change: `IdentityNodeInitializationTest` and a bean was setup in the blueprint. 
@clockard 
@brianfelix 
@vinamartin 
@mcalcote
@pklinef 
@shaundmorris 
- Build and run, make sure that the registry identity node is being created properly when the DDF Registry starts. 
- There is a known issue where modifiedTime and lastUpdated of the identity metacard attributes were slightly off. Double check to make sure these values are the same. 
DDF-2176
> DDF-2176 Break up FederationAdminServiceImpl to reduce the class' complexity and better adhere to the Single Responsibility Principle

- distribution/docs/src/main/resources/_contents/_catalog-contents/extending-catalog-contents.adoc
Documents the XmlInputTransformer, SaxEventHandlers, SaxEventHandlerFactories, SaxEventHandlerDelegate and how they can all be used together to make a configurable, extensible Xml Input Transformer.
@NGoss @ricklarsen 
@jaymcnallie
@shaundmorris 
and SaxEventHandlerFactories, XmlInputTransformer, SaxEventHandlerDelegate
> DDF-2230 Add docs for SaxEventHandlers

- catalog/ui/search-ui/standard/src/main/webapp/js/model/Filter.js
- catalog/ui/search-ui/standard/src/main/webapp/js/model/Query.js
- catalog/ui/search-ui/standard/src/main/webapp/js/view/filter/FacetItem.view.js
- catalog/ui/search-ui/standard/src/main/webapp/js/view/filter/FilterCollection.view.js
- catalog/ui/search-ui/standard/src/main/webapp/js/view/filter/FilterItem.view.js
- catalog/ui/search-ui/standard/src/main/webapp/templates/filter/facet.item.handlebars
Fixed the metadata-content-type filter query parameter.
@ahoffer @brendan-hofmann @andrewkfiedler 
@stustison 
@pklinef
Ingest two different types of files (png/pdf) and do an initial search.
Verify that all the checkboxes under Metacard-Content-Type are unchecked.
Verify that adding and removing checkmarks changes the query with the proper content type.
Verify that searching with new metacard-content-type queries return the results of their respective types.
> DDF-2220: Additional query parameters are not preserved after a search is performed

- catalog/ui/search-ui/standard/bower.json
- catalog/ui/search-ui/standard/src/main/webapp/js/view/cesium.metacard.js
- catalog/ui/search-ui/standard/src/main/webapp/js/widgets/cesium.bbox.js
- catalog/ui/search-ui/standard/src/main/webapp/js/widgets/cesium.circle.js
- catalog/ui/search-ui/standard/src/main/webapp/js/widgets/cesium.polygon.js
- catalog/ui/search-ui/standard/src/main/webapp/js/widgets/filter.cesium.geometry.group.js
Moves Cesium up to 1.17.  This is the highest we can currently upgrade without breaking the Standard Search UI.  This PR was verified in Chrome, Firefox and Internet Explorer
@codice/ui 
@pklinef 
@stustison
Build and test Standard Search UI in Chrome, Firefox, Internet Explorer
When testing on Safari, it was noticed that DDF master would not render Cesium.  A ticket will be created for this issue.
https://codice.atlassian.net/browse/DDF-2237
> DDF-2237 Upgraded Cesium to 1.17

- distribution/sdk/sdk-app/src/main/resources/features.xml
Changes the sample metacard validator to `install="manual"`, so integration tests that want to use it have to manually start and stop the feature.
@stustison
Run itests
> DDF-2125 Require sample metacard validator to be installed manually

- catalog/core/catalog-core-metricsplugin/src/main/java/ddf/catalog/metrics/CatalogMetrics.java
- catalog/spatial/registry/registry-admin-modules/registry-admin-remote-ui/src/main/webapp/js/model/Registry.js
- catalog/spatial/registry/registry-admin-modules/registry-admin-remote-ui/src/main/webapp/js/view/ModalRegistry.view.js
- catalog/spatial/registry/registry-admin-modules/registry-admin-remote-ui/src/main/webapp/templates/registryList.handlebars
- catalog/spatial/registry/registry-api-impl/pom.xml
- catalog/spatial/registry/registry-api-impl/src/main/java/org/codice/ddf/registry/api/impl/RegistryStoreImpl.java
- catalog/spatial/registry/registry-api-impl/src/main/java/org/codice/ddf/registry/api/impl/RegistryStorePublisher.java
- catalog/spatial/registry/registry-api-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/spatial/registry/registry-api-impl/src/main/resources/OSGI-INF/metatype/metatype.xml
- catalog/spatial/registry/registry-api-impl/src/test/java/org/codice/ddf/registry/api/impl/TestRegistryStore.java
- catalog/spatial/registry/registry-api-impl/src/test/java/org/codice/ddf/registry/api/impl/TestRegistryStorePublisher.java
- catalog/spatial/registry/registry-api/src/main/java/org/codice/ddf/registry/api/RegistryStore.java
- catalog/spatial/registry/registry-federation-admin-service-impl/pom.xml
- catalog/spatial/registry/registry-federation-admin-service-impl/src/main/java/org/codice/ddf/registry/federationadmin/service/impl/FederationAdminServiceImpl.java
- catalog/spatial/registry/registry-federation-admin-service-impl/src/main/java/org/codice/ddf/registry/federationadmin/service/impl/RefreshRegistrySubscriptions.java
- catalog/spatial/registry/registry-federation-admin-service-impl/src/main/java/org/codice/ddf/registry/federationadmin/service/impl/RegistryPublicationServiceImpl.java
- catalog/spatial/registry/registry-federation-admin-service-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/spatial/registry/registry-federation-admin-service-impl/src/test/java/org/codice/ddf/registry/federationadmin/service/impl/FederationAdminServiceImplTest.java
- catalog/spatial/registry/registry-federation-admin-service-impl/src/test/java/org/codice/ddf/registry/federationadmin/service/impl/RefreshRegistrySubscriptionsTest.java
- catalog/spatial/registry/registry-federation-admin-service-impl/src/test/java/org/codice/ddf/registry/federationadmin/service/impl/RegistryPublicationServiceImplTest.java
- catalog/spatial/registry/registry-federation-admin-service/src/main/java/org/codice/ddf/registry/federationadmin/service/FederationAdminService.java
- catalog/spatial/registry/registry-identification-plugin/src/test/java/org/codice/ddf/registry/identification/IdentificationPluginTest.java
- catalog/spatial/registry/registry-publication-action-provider/src/main/java/org/codice/ddf/registry/publication/action/provider/RegistryPublicationActionProvider.java
- catalog/spatial/registry/registry-publication-action-provider/src/test/java/org/codice/ddf/registry/publication/action/provider/RegistryPublicationActionProviderTest.java
- catalog/spatial/registry/registry-rest-endpoint/src/main/java/org/codice/ddf/registry/rest/endpoint/RegistryRestEndpoint.java
- catalog/spatial/registry/registry-rest-endpoint/src/test/java/org/codice/ddf/registry/rest/endpoint/RegistryRestEndpointTest.java
Add an Auto-Publish(Auto Push) Configuration property to the RegistryStore. This configuration is accessible in the add/edit modal on the remote registries tab in the registry app ui.
There are also fixes to subscription and publish services within the registry that manifested when this functionality was added.
@gordocanchola @vinamartin @ani6gup @clockard 
@coyotesqrl @figliold 
Install registry app (with security) and connect to a second registry by adding it in the remote registries tab of the registry app with Auto-Push on. Observe presence of registry identity metacard when querying metacards in the second DDF's solr once the remote becomes 'available' on the first registry. 
Minor UI updates are in this PR fixing the remote name as well as adding the autoPush to the registry …
> DDF-2177 Add Auto Push configuration property to the registry store

- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/impl/MetacardComparator.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/impl/ResourceCacheImpl.java
- catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/cache/impl/MetacardComparatorTest.java
- catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/cache/impl/ResourceCacheImplTest.java
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalog.java
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFederation.java
Updates ResourceCache to compare 2 metacards using their attributes instead of using the hashcodes.
@lessarderic 
@figliold
@Lambeaux 
@coyotesqrl
@shaundmorris
1. Start DIB
2. Enable file Uploader in Admin Console for Search UI
3. Setup JSON Federated Source
4. Upload image file (see attachment)
5. Run "*" query from Search UI
6. On the Actions tab, select "Export as resource"
7. Verify product is in the Product Cache (<dib.home>/dib-enterprise-suite-4.3.0-SNAPSHOT/data/Product_Cache)
8. Run "*" query again
9. Product should still be in the product cache
DDF-2189
> DDF-2189 Cached resource is deleted when a new search is done

- catalog/core/catalog-core-metricsplugin/src/main/java/ddf/catalog/metrics/CatalogMetrics.java
- catalog/spatial/registry/registry-admin-modules/registry-admin-remote-ui/src/main/webapp/js/model/Registry.js
- catalog/spatial/registry/registry-admin-modules/registry-admin-remote-ui/src/main/webapp/js/view/ModalRegistry.view.js
- catalog/spatial/registry/registry-admin-modules/registry-admin-remote-ui/src/main/webapp/templates/registryList.handlebars
- catalog/spatial/registry/registry-api-impl/pom.xml
- catalog/spatial/registry/registry-api-impl/src/main/java/org/codice/ddf/registry/api/impl/RegistryStoreImpl.java
- catalog/spatial/registry/registry-api-impl/src/main/java/org/codice/ddf/registry/api/impl/RegistryStorePublisher.java
- catalog/spatial/registry/registry-api-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/spatial/registry/registry-api-impl/src/main/resources/OSGI-INF/metatype/metatype.xml
- catalog/spatial/registry/registry-api-impl/src/test/java/org/codice/ddf/registry/api/impl/TestRegistryStore.java
- catalog/spatial/registry/registry-api-impl/src/test/java/org/codice/ddf/registry/api/impl/TestRegistryStorePublisher.java
- catalog/spatial/registry/registry-api/src/main/java/org/codice/ddf/registry/api/RegistryStore.java
- catalog/spatial/registry/registry-federation-admin-service-impl/pom.xml
- catalog/spatial/registry/registry-federation-admin-service-impl/src/main/java/org/codice/ddf/registry/federationadmin/service/impl/FederationAdminServiceImpl.java
- catalog/spatial/registry/registry-federation-admin-service-impl/src/main/java/org/codice/ddf/registry/federationadmin/service/impl/RefreshRegistrySubscriptions.java
- catalog/spatial/registry/registry-federation-admin-service-impl/src/main/java/org/codice/ddf/registry/federationadmin/service/impl/RegistryPublicationServiceImpl.java
- catalog/spatial/registry/registry-federation-admin-service-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/spatial/registry/registry-federation-admin-service-impl/src/test/java/org/codice/ddf/registry/federationadmin/service/impl/FederationAdminServiceImplTest.java
- catalog/spatial/registry/registry-federation-admin-service-impl/src/test/java/org/codice/ddf/registry/federationadmin/service/impl/RefreshRegistrySubscriptionsTest.java
- catalog/spatial/registry/registry-federation-admin-service-impl/src/test/java/org/codice/ddf/registry/federationadmin/service/impl/RegistryPublicationServiceImplTest.java
- catalog/spatial/registry/registry-federation-admin-service/src/main/java/org/codice/ddf/registry/federationadmin/service/FederationAdminService.java
- catalog/spatial/registry/registry-identification-plugin/src/test/java/org/codice/ddf/registry/identification/IdentificationPluginTest.java
- catalog/spatial/registry/registry-publication-action-provider/src/main/java/org/codice/ddf/registry/publication/action/provider/RegistryPublicationActionProvider.java
- catalog/spatial/registry/registry-publication-action-provider/src/test/java/org/codice/ddf/registry/publication/action/provider/RegistryPublicationActionProviderTest.java
- catalog/spatial/registry/registry-rest-endpoint/src/main/java/org/codice/ddf/registry/rest/endpoint/RegistryRestEndpoint.java
- catalog/spatial/registry/registry-rest-endpoint/src/test/java/org/codice/ddf/registry/rest/endpoint/RegistryRestEndpointTest.java
Add an Auto-Publish(Auto Push) Configuration property to the RegistryStore. This configuration is accessible in the add/edit modal on the remote registries tab in the registry app ui.
There are also fixes to subscription and publish services within the registry that manifested when this functionality was added.
@shaundmorris
@stustison
Bamboo
This PR was merged on master: https://github.com/codice/ddf/pull/897
DDF-2177
(https://cloud.githubusercontent.com/assets/11355332/16322345/5730eb1e-3957-11e6-9869-a96af2201aba.png)
> DDF-2177 Add Auto Push configuration property to registry store, plus subscription improvements and fixes

- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/CachingFederationStrategy.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/CatalogFrameworkImpl.java
Fixes compatibility issues by removing the anytag query from inside catalogframework and instead uses a flag in caching federation strategy
@ryeats 
@tbatie 
@coyotesqrl
@pklinef
@stustison
> DDF-2131: removed anytags query from catalogframework

- catalog/security/catalog-security-metacardattributeplugin/src/main/java/org/codice/ddf/catalog/security/policy/metacard/MetacardAttributeSecurityPolicyPlugin.java
- catalog/security/catalog-security-metacardattributeplugin/src/main/resources/OSGI-INF/metatype/metatype.xml
- catalog/security/catalog-security-metacardattributeplugin/src/test/java/org/codice/ddf/catalog/security/policy/metacard/MetacardAttributeSecurityPolicyPluginTest.java
- catalog/transformer/catalog-transformer-pdf/src/main/java/ddf/catalog/transformer/input/pdf/PdfInputTransformer.java
- distribution/docs/src/main/resources/_contents/securing-contents.adoc
Multiple source attributes can target the same destination security attribute. This can be accomplished by getting a union of the values or the intersection. This supports both configurations.
@ryeats @tbatie 
@coyotesqrl
@stustison
Full build and test. Installing DDF and configuring the MetacardAttributeSecurityPolicyPlugin should display two separate lists of mappings that can be added, one for intersections and one for unions.
N/A
DDF-2188
> DDF-2188 Updates the MetacardAttributeSecurityPolicyPlugin to support unions and intersections of destination security attributes.

- catalog/security/catalog-security-metacardattributeplugin/src/main/java/org/codice/ddf/catalog/security/policy/metacard/MetacardAttributeSecurityPolicyPlugin.java
- catalog/security/catalog-security-metacardattributeplugin/src/main/resources/OSGI-INF/metatype/metatype.xml
- catalog/security/catalog-security-metacardattributeplugin/src/test/java/org/codice/ddf/catalog/security/policy/metacard/MetacardAttributeSecurityPolicyPluginTest.java
- catalog/transformer/catalog-transformer-pdf/src/main/java/ddf/catalog/transformer/input/pdf/PdfInputTransformer.java
- distribution/docs/src/main/resources/_contents/securing-contents.adoc
Multiple source attributes can target the same destination security attribute. This can be accomplished by getting a union of the values or the intersection. This supports both configurations.
@ryeats @tbatie 
@coyotesqrl
@stustison
Full build and test. Installing DDF and configuring the MetacardAttributeSecurityPolicyPlugin should display two separate lists of mappings that can be added, one for intersections and one for unions.
N/A
DDF-2188
> DDF-2188-2.9.X Updates the MetacardAttributeSecurityPolicyPlugin to support unions and intersections

- catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/event/SendEvent.java
- catalog/spatial/csw/spatial-csw-endpoint/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/event/SendEventTest.java
fix the default polling interval which was getting set to 0 to be for 30 minutes instead
@tbatie @bcwaters @adimka
@coyotesqrl
@shaundmorris
run the unit tests
- [ x] Update / Add Unit Tests
> DDF-2262 Fix default subscription polling interval

- catalog/core/catalog-core-federationstrategy/src/test/java/ddf/catalog/federation/impl/FederationStrategyTest.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/history/Historian.java
- catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/impl/CatalogFrameworkImplTest.java
Enables the historian to be on by default. 
@coyotesqrl
@pklinef
@shaundmorris 
- this was originally supposed to be on by default but there was some discord between the initialized value and metatype default
> DDF-2131: Set historian to be on by default

- distribution/test/itests/test-itests-ddf/pom.xml
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/AbstractIntegrationTest.java
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFtp.java
Created new integration tests for coverage of the FTP endpoint for ingest capability. 
Test suite includes following test cases:
- verify successful connection to FTP server
- verify successful PUT of file to FTP server (storeFile)
- verify successful PUT of file to FTP server using streaming method (storeFileStream)
New dependency on Apache Commons Net for FTP/S client APIs.
@peterhuffer @emmberk @mweser @troymohl 
@jaymcnallie
@kcwire
Run the new "TestFtp" automated itest suite:
1) cd ddf/distribution/test/itests/test-itests-ddf
2) mvn test -Dtest=TestFtp
These tests were intended to provide integration test coverage of the new insecure FTP endpoint capability for ingest, implemented under DDF-2048.
https://codice.atlassian.net/browse/DDF-2048
As an integrator, I would like an FTP …
> DDF-2191 Created integration tests covering ingest through the FTP endpoint

- catalog/transformer/catalog-transformer-streaming-lib/src/main/java/org/codice/ddf/transformer/xml/streaming/lib/SaxEventHandlerDelegate.java
- catalog/transformer/catalog-transformer-streaming-lib/src/main/java/org/codice/ddf/transformer/xml/streaming/lib/SaxEventToXmlElementConverter.java
- catalog/transformer/catalog-transformer-streaming-lib/src/test/java/org/codice/ddf/transformer/xml/streaming/lib/TestGenericXmlLib.java
SaxEventToXmlConverter can handle nested prefix redeclarations
@AzGoalie @brendan-hofmann 
@kcwire
@shaundmorris
The unit tests should be sufficient
DDF-2250
specifically nested redeclaration of a namespace prefix
> DDF-2250 Make SaxEventToXmlConverter handle edge cases

- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/CatalogFrameworkImpl.java
Fixes an issue with the historian trying to version remote create/update/delete operations
@pklinef
@shaundmorris
Verified build and itests pass
DDF-2131
Moved Historian call in CatalogFrameworkImpl inside Request.isLocal block to prevent it from trying version remote Create/Update/Delte operations
> DDF-2131 Moved Historian call in CatalogFrameworkImpl

- catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/ValidateCommand.java
- catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/validation/ValidateExecutor.java
- catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/validation/ValidatePrinter.java
- catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/validation/ValidateReport.java
- catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/validation/ValidateReportEntry.java
- catalog/core/catalog-core-commands/src/test/java/org/codice/ddf/commands/catalog/TestValidateCommand.java
This PR enables the Validate Command to accept paths pointing to directories as arguments and supports validating all the files in the specified directory and its subdirectories. The user can now also query the catalog in order to find metacards to validate.
@ahoffer 
@spearskw 
@AzGoalie 
@coyotesqrl 
@shaundmorris
Attempt the following commands:
- `catalog:validate --path <pathToDirectory>`
- `catalog:validate --path <pathToFile>`
- `catalog:validate --query <metacardQuery>` (make sure to use a query that'll actually return results)
> DDF-2244 Add batching to the validation command and allow it to handle catalog queries

- distribution/install-profiles/src/main/resources/features.xml
Adds registry-app to standard and development install profiles. 
@mcalcote 
@lessarderic
@stustison
Full build, start up the DDF, install with Development setting and make sure registry-app has started.
https://codice.atlassian.net/browse/DDF-2271
> DDF-2271- Adds Registry app to install profiles

- catalog/catalog-app/src/main/resources/features.xml
- catalog/core/catalog-core-standardframework/pom.xml
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/resource/actions/DownloadResourceActionProvider.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/resource/download/DownloadInfo.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/resource/download/ReliableResourceDownloadManager.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/resource/download/ResourceDownloadEndpoint.java
- catalog/core/catalog-core-standardframework/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/resource/actions/DownloadResourceActionProviderTest.java
- catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/resource/download/DownloadInfoTest.java
- catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/resource/download/ReliableResourceDownloadManagerTest.java
- catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/resource/download/ResourceDownloadEndpointTest.java
- distribution/test/itests/test-itests-common/src/test/java/ddf/common/test/WaitCondition.java
- distribution/test/itests/test-itests-common/src/test/java/ddf/common/test/mock/csw/FederatedCswMockServer.java
- distribution/test/itests/test-itests-common/src/test/java/ddf/common/test/restito/ChunkedContent.java
- distribution/test/itests/test-itests-common/src/test/resources/csw-query-response-modified.xml
- distribution/test/itests/test-itests-common/src/test/resources/csw-query-response.xml
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/AbstractIntegrationTest.java
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFederation.java
- distribution/test/itests/test-itests-ddf/src/test/resources/csw-query-response.xml
- Added logic to the ReliableResourceDownloadManager to get the list of in-progress downloads
- Added unit tests for DownloadInfo and ReliableResourceDownloadManager
- Added experimental note to resource download endpoint and reformatted TestFederation code.
- Added new method to WaitCondition class to return the last result returned by the Callable.
@cmthom10 
@oconnormi 
@Lambeaux 
@bantillo 
@jlcsmith
@pklinef
Run integration tests
DDF-2239
DDF-2207
> DDF-2239: As an Integrator, I need the ability to get the list of all current cache downloads for all users

- catalog/transformer/catalog-transformer-pdf/pom.xml
- catalog/transformer/catalog-transformer-pdf/src/main/java/ddf/catalog/transformer/input/pdf/GeoPdfParser.java
- catalog/transformer/catalog-transformer-pdf/src/main/java/ddf/catalog/transformer/input/pdf/PdfInputTransformer.java
- catalog/transformer/catalog-transformer-pdf/src/test/java/ddf/catalog/transformer/input/pdf/GeoPdfDocumentGenerator.java
- catalog/transformer/catalog-transformer-pdf/src/test/java/ddf/catalog/transformer/input/pdf/TestGeoPdfParser.java
This PR adds support to parse WGS84 locations from GeoPDF files when present.
@jlcsmith
@kcwire 
Install DDF, Ingest GeoPDFs that contain `GEOGRAPHIC` projection types, and observe the location is properly set via the Standard Search UI (contact me for example data)
https://codice.atlassian.net/browse/DDF-2260
> DDF-2260 Added support for GeoPDF WGS84 location parsing

- catalog/core/catalog-core-commands/src/main/resources/bin/catalog-export
- catalog/core/catalog-core-commands/src/main/resources/bin/catalog-export.bat
- Provides a CQL filter when dumping the catalog contents to file (used to import/export the entire catalog) using the existing catalog-export scripts in $DDF_HOME/bin. 
- Enhanced usage statements for the scripts.
@bdeining @jrnorth @glenhein 
@jlcsmith @kcwire
**OSX**
1. Build and run DDF.
2. Ingest at least two items into catalog.
3. Navigate to $DDF_HOME/bin 
4. chmod +x catalog-export  (see bug https://codice.atlassian.net/browse/DDF-2240) 
5. Run catalog-export from the command line:
-   Regression test the original capability: 
`catalog-export -d DIRECTORY -z ZIPFILE -k KEYSTORE`
e.g. `catalog-export -d /Users/leahreese/Downloads -z test.zip -k ../etc/keystores/serverKeystore.jks`
Provide passphrase for keystore. Verify this generated a zipfile containing ALL ingested items at the …
> DDF-2233 Add CQL filter expression support for the catalog-export scripts to dump filtered metacards

- catalog/schematron/catalog-schematron-plugin/pom.xml
- catalog/schematron/catalog-schematron-plugin/src/main/java/ddf/services/schematron/SchematronValidationService.java
- catalog/schematron/catalog-schematron-plugin/src/test/java/ddf/services/schematron/SchematronValidationServiceTest.java
Fix schematron marking null/empty metadata as invalid, potentially causing it to get lost from ingest/query.
@spearskw @djblue 
@coyotesqrl
@pklinef
Create an enforced schematron validator configuration, then verify that it is still possible to ingest metacards with null/empty metadata.
This issue was discovered while playing with the new catalog search ui. Attempting to store workspace data was failing when an enforced schematron validator was configured.
https://codice.atlassian.net/browse/DDF-2289
> DDF-2289 Gracefully handle null/empty metadata in schematron validator

- catalog/rest/catalog-rest-endpoint/src/main/java/org/codice/ddf/endpoints/rest/RESTEndpoint.java
This PR adds a catch for DataUsageLimitExceededException so a client knows why their download failed.
@lcrosenbu @jrnorth   
@jlcsmith
@stustison
Build DDF Development, Ingest a resource, Download the resource, Set the Usage Limit for the current user to a small number, Attempt to Download again and observe the error message.
https://codice.atlassian.net/browse/DDF-2273
https://codice.atlassian.net/browse/DDF-2273
> DDF-2273 Added catch for DataUsageLimitExceededException in REST endpoint

- catalog/spatial/registry/registry-admin-modules/registry-admin-remote-ui/src/main/webapp/js/model/Registry.js
- catalog/spatial/registry/registry-admin-modules/registry-admin-remote-ui/src/main/webapp/js/view/ModalConfig.view.js
- catalog/spatial/registry/registry-admin-modules/registry-admin-remote-ui/src/main/webapp/js/view/ModalRegistry.view.js
- catalog/spatial/registry/registry-admin-modules/registry-admin-remote-ui/src/main/webapp/js/view/Registry.view.js
- catalog/spatial/registry/registry-admin-modules/registry-admin-remote-ui/src/main/webapp/less/styles.less
- catalog/spatial/registry/registry-admin-modules/registry-admin-remote-ui/src/main/webapp/templates/configModal.handlebars
- catalog/spatial/registry/registry-admin-modules/registry-admin-remote-ui/src/main/webapp/templates/registryModal.handlebars
- catalog/spatial/registry/registry-admin-modules/registry-admin-remote-ui/src/main/webapp/templates/registryRow.handlebars
- catalog/spatial/registry/registry-admin-modules/registry-admin-remote-ui/src/main/webapp/templates/textType.handlebars
- catalog/spatial/registry/registry-api-impl/src/main/resources/OSGI-INF/metatype/metatype.xml
As a user, I want to be able to switch between registry types when adding a remote registry in the registry-app. 
If multiple registry configurations are present at the time a new remote registry is added, a modal will pop up allowing the user to select the type before continuing to the standard add dialog.
@clockard @vinamartin @brianfelix @gordocanchola @ani6gup 
@djblue @andrewkfiedler 
@pklinef
@stustison
@shaundmorris 
Implement a second type of registry store, then run DDF and add a remote registry in the Registry-App.
Please see me for further details about how to test this PR.
Currently the ui selects a single configuration for the user, but this should be changed so that the user can select the registry type upon creation.
DDF-2254
> DDF-2254 Added ablility to switch between remote registry types when adding a remote in the registry-app

- catalog/catalog-app/pom.xml
- catalog/catalog-app/src/main/resources/features.xml
- catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/SolrCatalogProvider.java
- catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/SolrMetacardClient.java
- catalog/core/catalog-core-standardframework/pom.xml
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/CachingFederationStrategy.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/SolrCache.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/SolrCacheSource.java
- catalog/core/catalog-core-standardframework/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/core/catalog-core-standardframework/src/main/resources/describable.properties
- catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/cache/solr/impl/SolrCacheSourceTest.java
- catalog/core/catalog-core-standardframework/src/test/resources/describable.properties
- catalog/core/catalog-core-tagsfilterplugin/pom.xml
- catalog/core/catalog-core-tagsfilterplugin/src/main/java/org/codice/ddf/catalog/plugin/tagsfilter/TagsFilterQueryPlugin.java
- catalog/core/catalog-core-tagsfilterplugin/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/core/catalog-core-tagsfilterplugin/src/test/java/org/codice/ddf/catalog/plugin/tagsfilter/TagsFilterQueryPluginTest.java
- catalog/core/pom.xml
Also moves the addition of the default filter tag to a new `PreFederatedQueryPlugin` now that it can take advantage of the existance of the new Source.
@rzwiefel @clockard @tbatie @kcwire 
@pklinef
@stustison
Full build and test. Execute queries with and without tag filters.
We have been adding properties to queries and updating the `CachingFederationStrategy` with branching logic based on those properties instead of creating `PreFederatedQueryPlugin`s to isolate that work. By adding the new `SolrCacheSource` we can stop corrupting the strategy's code.
DDF-1940
N/A
> DDF-1940 Creates a new internal-only SolrCacheSource to extract and reduce customizations in the CachingFederationStrategy.

- catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/IngestCommand.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/resourceretriever/LocalResourceRetriever.java
- catalog/transformer/catalog-transformer-zip/pom.xml
- catalog/transformer/catalog-transformer-zip/src/main/java/org/codice/ddf/catalog/transformer/zip/ZipCompression.java
- catalog/transformer/catalog-transformer-zip/src/main/java/org/codice/ddf/catalog/transformer/zip/ZipValidationException.java
- catalog/transformer/catalog-transformer-zip/src/test/java/org/codice/ddf/catalog/transformer/zip/TestZipCompression.java
- catalog/transformer/catalog-transformer-zip/src/test/java/org/codice/ddf/catalog/transformer/zip/TestZipDecompression.java
- catalog/transformer/catalog-transformer-zip/src/test/java/org/codice/ddf/catalog/transformer/zip/TestZipValidator.java
This PR updates the catalog:ingest --include-content functionality to prevent duplicating content generated from history metacards, as well as refactoring and code coverage.
@glenhein @dcruver 
@jlcsmith
@kcwire
Build DDF
Turn on Versioning Plugin and Configure the Historian
Deploy sdk-sample-storageplugin
Ingest some images
Update some of the metacards using Postman or the Catalog UI
Dump Images using `catalog:dump --include-content`
Observe that `Update` history metacards are not duplicating content within the Zip file
Sign the zip file using jarsigner (or optionally use the catalog-dump script in `/bin`)
Build a new DDF
Ingest the zip using `catalog:ingest --include-content` and verify all metadata and content is preserved.
https://codice.atlassian.net/browse/DDF-2243
> DDF-2243 Changed ZipCompression to prevent duplicating history metacards and did some refactoring

- platform/platform-app/src/main/resources/features.xml
- pom.xml
Upgrade camel to 2.16.3 and adds the ability to install the camel-amqp component.
@ryeats @coyotesqrl
@kcwire 
@jaymcnallie
Make sure integration tests pass and that the camel-amqp feature can install correctly.
DDF-2264
> DDF-2264 Upgrade Camel to 2.16.3 and add support for camel-amqp

- catalog/transformer/catalog-transformer-common/src/main/java/ddf/catalog/transformer/common/tika/MetacardCreator.java
- catalog/transformer/catalog-transformer-common/src/test/java/ddf/catalog/transformer/common/tika/MetacardCreatorTest.java
- catalog/transformer/catalog-transformer-pdf/src/main/java/ddf/catalog/transformer/input/pdf/PdfInputTransformer.java
- catalog/transformer/catalog-transformer-pdf/src/test/groovy/ddf/catalog/transformer/input/pdf/PdfInputTransformerSpecTest.groovy
- catalog/transformer/catalog-transformer-tika-input/src/main/java/ddf/catalog/transformer/input/tika/TikaInputTransformer.java
- catalog/transformer/catalog-transformer-tika-input/src/test/java/ddf/catalog/transformer/input/tika/TikaInputTransformerTest.java
Instead of creating a new type on the fly, inject the additional attributes from the content extractors into the Basic MetacardType.
@kcwire
@pklinef
Full build/test run should be sufficient.
When initially implemented, new metacard types were being generated on the fly. The correct solution is to add attributes to the Basic type so the two input transformers produce metacards of the same type whether or not content extractors are deployed to the system.
DDF-2308
N/A
> DDF-2308 Updates the Tika and Pdf InputTransformers to use Basic MetacardType with or without content extractors present.

- distribution/docs/src/main/resources/_contents/installing-contents.adoc
Fixes a formatting error in the pdf version of documentation. 
@mcalcote @Lambeaux @jrnorth 
@lessarderic
@shaundmorris
Table on page 15 of the rendered `documentation.pdf` was formerly bleeding off the edge of the page. Table should be contained within page margins now.
DDF-1963
> DDF-1963: fix for broken table formatting in installation docs

- platform/platform-scheduler/pom.xml
- platform/platform-scheduler/src/main/java/ddf/platform/scheduler/CommandJob.java
- platform/platform-scheduler/src/test/java/ddf/platform/scheduler/TestCommandJob.java
Use the new SessionFactory in karaf for getting a command session and executing a command.
@jrnorth 
@kcwire 
@stustison 
@bdeining 
@beyelerb
@jlcsmith
Build. Go to config -> ddf platform -> configuration -> platform command scheduler. Configure a command, such as "log:get" for with a reasonable interval, such as 10 seconds. Watch the log file for the output from the command.
DDF-2284
> DDF-2284 use new SessionFactory from karaf

- platform/platform-scheduler/pom.xml
- platform/platform-scheduler/src/main/java/ddf/platform/scheduler/CommandJob.java
- platform/platform-scheduler/src/test/java/ddf/platform/scheduler/TestCommandJob.java
Use the new SessionFactory in karaf for getting a command session and executing a command.
@jrnorth 
@kcwire 
@stustison 
@bdeining 
@beyelerb
@jlcsmith
Build. Go to config -> ddf platform -> configuration -> platform command scheduler. Configure a command, such as "log:get" for with a reasonable interval, such as 10 seconds. Watch the log file for the output from the command.
DDF-2284
> DDF-2284 use new SessionFactory in karaf

- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/SolrCache.java
Fixes this NullPointerException when performing a search via the Search UI:
```bash
16:19:23,417 | WARN  | ool-51-thread-17 | talog.cache.solr.impl.SortedQueryMonitor  161 | re-standardframework | Couldn't get results from completed federated query. ddf.catalog.cache.solr.impl.SolrCacheSource, null
java.lang.NullPointerException
java.util.concurrent.ExecutionException: java.lang.NullPointerException
at java.util.concurrent.FutureTask.report(FutureTask.java:122)[:1.8.0_73]
at java.util.concurrent.FutureTask.get(FutureTask.java:192)[:1.8.0_73]
at ddf.catalog.cache.solr.impl.SortedQueryMonitor.run(SortedQueryMonitor.java:135)[329:catalog-core-standardframework:2.10.0.SNAPSHOT]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_73]
at …
```
> DDF-1940: Fixes NullPointerException when trying to add sourceQueries in SolrCache when SourceIds is null

- catalog/transformer/catalog-transformer-common/src/main/java/ddf/catalog/transformer/common/tika/MetacardCreator.java
- catalog/transformer/catalog-transformer-common/src/test/java/ddf/catalog/transformer/common/tika/MetacardCreatorTest.java
- catalog/transformer/catalog-transformer-pdf/src/main/java/ddf/catalog/transformer/input/pdf/PdfInputTransformer.java
- catalog/transformer/catalog-transformer-pdf/src/test/groovy/ddf/catalog/transformer/input/pdf/PdfInputTransformerSpecTest.groovy
- catalog/transformer/catalog-transformer-tika-input/src/main/java/ddf/catalog/transformer/input/tika/TikaInputTransformer.java
- catalog/transformer/catalog-transformer-tika-input/src/test/java/ddf/catalog/transformer/input/tika/TikaInputTransformerTest.java
Instead of creating a new type on the fly, inject the additional attributes from the content extractors into the Basic MetacardType.
This cherry pick required some massaging to work with 2.9.
@kcwire
@pklinef
Full build/test run should be sufficient.
When initially implemented, new metacard types were being generated on the fly. The correct solution is to add attributes to the Basic type so the two input transformers produce metacards of the same type whether or not content extractors are deployed to the system.
DDF-2308
N/A
> DDF-2308 2.9.X Updates the Tika and Pdf InputTransformers to use Basic MetacardType with or without content extractors present.

- catalog/catalog-app/pom.xml
- catalog/catalog-app/src/main/resources/features.xml
- catalog/plugin/catalog-plugin-expirationdate/pom.xml
- catalog/plugin/catalog-plugin-expirationdate/src/main/java/org/codice/ddf/catalog/plugin/expiration/ExpirationDatePlugin.java
- catalog/plugin/catalog-plugin-expirationdate/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/plugin/catalog-plugin-expirationdate/src/main/resources/OSGI-INF/metatype/metatype.xml
- catalog/plugin/catalog-plugin-expirationdate/src/test/java/org/codice/ddf/catalog/plugin/expiration/TestExpirationDatePlugin.java
- catalog/plugin/pom.xml
- catalog/spatial/registry/registry-identification-plugin/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- distribution/docs/src/main/resources/_contents/_catalog-contents/configuring-catalog-contents.adoc
Added a new pre-ingest plugin to add expiration dates to metacards. The expiration date is calculated relative to the modified date. Expiration dates added upon ingest will enable the `catalog:removeall --expired` option to be more useful to manage the size of the catalog. 
The Expiration Date Plugin provides three configuration options: 
- Offset from modified date (in days), defaulted to 30 days
- Overwrite empty expiration dates, defaulted to TRUE
- Overwrite existing, non-empty expiration dates, defaulted to FALSE
@bdeining 
@jrnorth 
@figliold 
@jlcsmith
@kcwire
Run DDF, verify plugin is installed, and verify configuration in the Admin Console under DDF Catalog.
Ingest three data samples:
1. Data with empty expiration date
2. Data with expiration date set to a time in the past
3. …
> DDF-2274 Add pre ingest plugin to add expiration date to enable removal of expired records

- catalog/catalog-app/src/main/resources/features.xml
Turns catalog-core-validationparser on by default
@coyotesqrl @pklinef  @jlcsmith @jrnorth 
@stustison 
@kcwire
https://codice.atlassian.net/browse/DDF-2278
> DDF-2278: Turn catalog-core-validationparser on by default

- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/resource/download/ReliableResourceDownloadManager.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/resource/download/ResourceDownloadEndpoint.java
- distribution/test/itests/test-itests-common/src/test/java/ddf/common/test/mock/csw/FederatedCswMockServer.java
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/CatalogBundle.java
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFederation.java
Adds two new tests to TestFederation, testProductDownloadListWithTwoActiveDownloads and  testProductDownloadListWithTwoActiveDownloadsOneFails, to confirm that downloading two products at once performs as expected. 
@Lambeaux 
@oconnormi 
@bantillo
@figliold
@lessarderic
Run TestFederation tests.
Updated some files outside of TestFederation.
Commit Messages: 
- -New itests to determine that two products can be downloaded at once.
Includes an itest for  if one download fails the other continues to download.
- -testProductDownloadListWithTwoActiveDownloadsOneFails now working as expected in TestFederation.
Cleaned up testProductDownloadListWithTwoActiveDownloadsOneFails and testProductDownloadListWithTwoActiveDownloads.
- …
> DDF-2281 Add automated tests for simultaneous downloads

- catalog/core/catalog-core-localstorageprovider/pom.xml
- catalog/core/catalog-core-localstorageprovider/src/main/java/org/codice/ddf/catalog/content/impl/FileSystemStorageProvider.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/CatalogFrameworkImpl.java
Close InputStream objects returned by ContentItem#getInputStream.
@bdeining
@jrnorth
@kcwire
@lcrosenbu 
@beyelerb
@jlcsmith
Build and run under Windows. Configure the content directory monitor. Copy multiple files into the monitored directory. Watch the log file and verify that no errors are thrown. 
DDF-2322
> DDF-2322 close InputStream objects returned by ContentItem#getInputStream

- catalog/ui/search-ui/standard/src/main/java/org/codice/ddf/ui/searchui/standard/properties/ConfigurationStore.java
- catalog/ui/search-ui/standard/src/main/webapp/js/controllers/cesium.controller.js
- catalog/ui/search-ui/standard/src/main/webapp/js/controllers/cesium.layerCollection.controller.js
- catalog/ui/search-ui/standard/src/main/webapp/js/controllers/common.layerCollection.controller.js
- catalog/ui/search-ui/standard/src/main/webapp/js/controllers/openlayers.controller.js
- catalog/ui/search-ui/standard/src/main/webapp/js/model/user.js
- catalog/ui/search-ui/standard/src/main/webapp/js/view/preferences/PreferencesModal.view.js
- catalog/ui/search-ui/standard/src/main/webapp/templates/preferences/layer.list.handlebars
- catalog/ui/search-ui/standard/src/main/webapp/templates/preferences/layerPicker.handlebars
- saving the search ui config no longer starts/stops proxies unless they change
- users with saved preferences will no longer lose map tiles after a config change
- fixed issue with search ui layers not updating correctly after preferences are saved
- fixed layer ordering to use alpha instead of arbitrary indexes so that all layers are visible without manual reordering
@andrewkfiedler @djblue @coyotesqrl 
@pklinef
@stustison
> DDF-2307 fixed issues with search ui map layers with saving search ui config and messing up proxies for users with saved preferences

- catalog/core/catalog-core-metacardgroomerplugin/src/main/java/ddf/catalog/plugin/groomer/metacard/StandardMetacardGroomerPlugin.java
- catalog/core/catalog-core-metacardgroomerplugin/src/test/java/ddf/catalog/plugin/groomer/TestMetacardGroomerPlugin.java
To support the new DDF taxonomy, the Metadata Groomer pre-ingest plugin was updated to set the Metacard.CREATED and Metacard.MODIFIED fields upon ingest to the current date/time for the new ddf.catalog.data.types.Metacard class. Additionally, the Metacard.MODIFIED field is updated to the current date/time for an update operation. 
@bdeining
@jrnorth
@coyotesqrl
@jlcsmith
@kcwire
Build and run DDF.
Verify that after ingest, the metacard reflects the current date/time for both `metacard.created` and `metacard.modified` date/time values.
**_Note: The transformers in their current state do not support the new taxonomy. Please use the following as a definitions.json file to dynamically apply these attributes across all metacard types for testing._**
```
{
"attributeTypes": { …
```
> DDF-2317 Set metacard.created and metacard.modified dates in Metacard Groomer Plugin to align to new taxonomy

- catalog/spatial/registry/registry-api-impl/pom.xml
- catalog/spatial/registry/registry-api-impl/src/main/java/org/codice/ddf/registry/api/impl/RegistryStoreImpl.java
- catalog/spatial/registry/registry-api-impl/src/main/java/org/codice/ddf/registry/api/impl/RegistryStorePublisher.java
- catalog/spatial/registry/registry-api-impl/src/test/java/org/codice/ddf/registry/api/impl/TestRegistryStore.java
- catalog/spatial/registry/registry-common/pom.xml
- catalog/spatial/registry/registry-common/src/main/java/org/codice/ddf/registry/common/metacard/RegistryUtility.java
- catalog/spatial/registry/registry-common/src/test/java/org/codice/ddf/registry/common/metacard/TestRegistryUtility.java
- catalog/spatial/registry/registry-ebrim-transformer/src/main/java/org/codice/ddf/registry/transformer/RegistryTransformer.java
- catalog/spatial/registry/registry-federation-admin-impl/src/main/java/org/codice/ddf/registry/federationadmin/impl/FederationAdmin.java
- catalog/spatial/registry/registry-federation-admin-impl/src/test/java/org/codice/ddf/registry/federationadmin/impl/FederationAdminTest.java
- catalog/spatial/registry/registry-federation-admin-service-impl/pom.xml
- catalog/spatial/registry/registry-federation-admin-service-impl/src/main/java/org/codice/ddf/registry/federationadmin/service/impl/FederationAdminServiceImpl.java
- catalog/spatial/registry/registry-federation-admin-service-impl/src/main/java/org/codice/ddf/registry/federationadmin/service/impl/RefreshRegistrySubscriptions.java
- catalog/spatial/registry/registry-federation-admin-service-impl/src/main/java/org/codice/ddf/registry/federationadmin/service/impl/RegistryPublicationServiceImpl.java
- catalog/spatial/registry/registry-identification-plugin/pom.xml
- catalog/spatial/registry/registry-identification-plugin/src/main/java/org/codice/ddf/registry/identification/IdentificationPlugin.java
- catalog/spatial/registry/registry-identification-plugin/src/test/java/org/codice/ddf/registry/identification/IdentificationPluginTest.java
- catalog/spatial/registry/registry-policy-plugin/src/main/java/org/codice/ddf/registry/policy/RegistryPolicyPlugin.java
- catalog/spatial/registry/registry-policy-plugin/src/test/java/org/codice/ddf/registry/policy/RegistryPolicyPluginTest.java
- catalog/spatial/registry/registry-publication-action-provider/pom.xml
- catalog/spatial/registry/registry-publication-action-provider/src/main/java/org/codice/ddf/registry/publication/action/provider/RegistryPublicationActionProvider.java
- catalog/spatial/registry/registry-publication-action-provider/src/main/java/org/codice/ddf/registry/publication/manager/RegistryPublicationManager.java
- catalog/spatial/registry/registry-publication-action-provider/src/test/java/org/codice/ddf/registry/publication/manager/RegistryPublicationManagerTest.java
- catalog/spatial/registry/registry-publication-update-handler/src/main/java/org/codice/ddf/registry/publication/RegistryPublicationHandler.java
- catalog/spatial/registry/registry-report-action-provider/pom.xml
- catalog/spatial/registry/registry-report-action-provider/src/main/java/org/codice/ddf/registry/report/action/provider/RegistryReportActionProvider.java
- catalog/spatial/registry/registry-report-action-provider/src/test/java/org/codice/ddf/registry/report/action/provider/TestRegistryReportActionProvider.java
- catalog/spatial/registry/registry-source-configuration-handler/pom.xml
- catalog/spatial/registry/registry-source-configuration-handler/src/main/java/org/codice/ddf/registry/source/configuration/SourceConfigurationHandler.java
A RegistryUtility class was added to registry commons which performs several common operations including: hasRegistryId, getRegistryId, isLocalNode, isIdentityNode, getStringAttribute and getListOfStringAttribute.
Javadocs on the class provide details about these methods and instructions for use. 
Changes were also made throughout the registry in an attempt to use these new methods where appropriate.
@clockard @gordocanchola @vinamartin @brianfelix @ani6gup 
@coyotesqrl @shaundmorris 
Bamboo, Hero, Reviewing the Logic and Manual testing of Registry functionality
Throughout the registry we do a lot of checking/getting of a some fields like registry-id. In many places we don't actually check to see if the attribute exists because it is just assumed to exist on registry metacards. Make a …
> DDF-2199 Add utility to registry to help with common registry metacard operations

- catalog/spatial/registry/registry-api-impl/pom.xml
- catalog/spatial/registry/registry-api-impl/src/main/java/org/codice/ddf/registry/api/impl/RegistryStoreImpl.java
- catalog/spatial/registry/registry-api-impl/src/main/java/org/codice/ddf/registry/api/impl/RegistryStorePublisher.java
- catalog/spatial/registry/registry-api-impl/src/test/java/org/codice/ddf/registry/api/impl/TestRegistryStore.java
- catalog/spatial/registry/registry-common/pom.xml
- catalog/spatial/registry/registry-common/src/main/java/org/codice/ddf/registry/common/metacard/RegistryUtility.java
- catalog/spatial/registry/registry-common/src/test/java/org/codice/ddf/registry/common/metacard/TestRegistryUtility.java
- catalog/spatial/registry/registry-ebrim-transformer/src/main/java/org/codice/ddf/registry/transformer/RegistryTransformer.java
- catalog/spatial/registry/registry-federation-admin-impl/src/main/java/org/codice/ddf/registry/federationadmin/impl/FederationAdmin.java
- catalog/spatial/registry/registry-federation-admin-impl/src/test/java/org/codice/ddf/registry/federationadmin/impl/FederationAdminTest.java
- catalog/spatial/registry/registry-federation-admin-service-impl/pom.xml
- catalog/spatial/registry/registry-federation-admin-service-impl/src/main/java/org/codice/ddf/registry/federationadmin/service/impl/FederationAdminServiceImpl.java
- catalog/spatial/registry/registry-federation-admin-service-impl/src/main/java/org/codice/ddf/registry/federationadmin/service/impl/RefreshRegistrySubscriptions.java
- catalog/spatial/registry/registry-federation-admin-service-impl/src/main/java/org/codice/ddf/registry/federationadmin/service/impl/RegistryPublicationServiceImpl.java
- catalog/spatial/registry/registry-identification-plugin/pom.xml
- catalog/spatial/registry/registry-identification-plugin/src/main/java/org/codice/ddf/registry/identification/IdentificationPlugin.java
- catalog/spatial/registry/registry-identification-plugin/src/test/java/org/codice/ddf/registry/identification/IdentificationPluginTest.java
- catalog/spatial/registry/registry-policy-plugin/src/main/java/org/codice/ddf/registry/policy/RegistryPolicyPlugin.java
- catalog/spatial/registry/registry-policy-plugin/src/test/java/org/codice/ddf/registry/policy/RegistryPolicyPluginTest.java
- catalog/spatial/registry/registry-publication-action-provider/pom.xml
- catalog/spatial/registry/registry-publication-action-provider/src/main/java/org/codice/ddf/registry/publication/action/provider/RegistryPublicationActionProvider.java
- catalog/spatial/registry/registry-publication-action-provider/src/main/java/org/codice/ddf/registry/publication/manager/RegistryPublicationManager.java
- catalog/spatial/registry/registry-publication-action-provider/src/test/java/org/codice/ddf/registry/publication/manager/RegistryPublicationManagerTest.java
- catalog/spatial/registry/registry-publication-update-handler/src/main/java/org/codice/ddf/registry/publication/RegistryPublicationHandler.java
- catalog/spatial/registry/registry-report-action-provider/pom.xml
- catalog/spatial/registry/registry-report-action-provider/src/main/java/org/codice/ddf/registry/report/action/provider/RegistryReportActionProvider.java
- catalog/spatial/registry/registry-report-action-provider/src/test/java/org/codice/ddf/registry/report/action/provider/TestRegistryReportActionProvider.java
- catalog/spatial/registry/registry-source-configuration-handler/pom.xml
- catalog/spatial/registry/registry-source-configuration-handler/src/main/java/org/codice/ddf/registry/source/configuration/SourceConfigurationHandler.java
A RegistryUtility class was added to registry commons which performs several common operations including: hasRegistryId, getRegistryId, isLocalNode, isIdentityNode, getStringAttribute and getListOfStringAttribute.
Javadocs on the class provide details about these methods and instructions for use.
Changes were also made throughout the registry in an attempt to use these new methods where appropriate.
@clockard @gordocanchola @vinamartin @brianfelix @ani6gup
@shaundmorris
@coyotesqrl 
Bamboo, Hero, Reviewing the Logic and Manual testing of Registry functionality
Throughout the registry we do a lot of checking/getting of a some fields like registry-id. In many places we don't actually check to see if the attribute exists because it is just assumed to exist on registry metacards. Make a …
> Ddf 2199 2.9.x Add utility to registry to help with common registry metacard operations

- distribution/ddf-common/src/main/resources/etc/system.properties
Disables the remote version check
@ryeats, @stustison 
@coyotesqrl
@pklinef
Build and unzip; run a full install of the app and see that the erroneous `fatal error` message no longer appears.
N/A
DDF-2335
N/A
> DDF-2335 Disable the Hazelcast version check on startup.

- distribution/sdk/sdk-app/pom.xml
Fixes maven deploy issue which attempted to deploy the sdk features.xml file twice. This resulted in maven deploy failing overall. 
@brendan-hofmann @coyotesqrl @oconnormi 
@jaymcnallie 
@shaundmorris
Full build. Run maven deploy on the sdk-app with a released/fixed version set in the pom.xml
This only has been discovered/reproduced during a release with the Nexus repository set to not allow redeployed artifacts
DDF-2292
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codice/ddf/1048)
> DDF-2292 Fixed sdk-app redeploy issue by switching the packaging to pom

- catalog/spatial/registry/registry-policy-plugin/src/main/java/org/codice/ddf/registry/policy/RegistryPolicyPlugin.java
While resolving merge conflicts from the previous 2199 PR, a null check was lost in RegistryPolicyPlugin.getWritePolicy. This PR fixes that.
@harrison-tarr @gordocanchola @clockard @spearskw 
@coyotesqrl
@shaundmorris
Build
https://github.com/codice/ddf/pull/1049
DDF-2199
> DDF-2199 Added null metacard check to RegistryPolicyPlugin

- catalog/spatial/registry/registry-source-configuration-handler/pom.xml
- catalog/spatial/registry/registry-source-configuration-handler/src/main/java/org/codice/ddf/registry/source/configuration/SourceConfigurationHandler.java
- catalog/spatial/registry/registry-source-configuration-handler/src/test/java/org/codice/ddf/registry/source/configuration/SourceConfigurationHandlerTest.java
Updating SourceConfigurationHandler to update ID information for stale configurations. Updating to handle the case where the same factory pid may have multiple binding types.
@mcalcote @clockard @ryeats 
@figliold 
@shaundmorris 
DDF-2313
Fixing SourceConfigurationHandler to account for registry entry with multiple bindings with the same fpid but different bindingTypes
Fixing SourceConfigurationHandler to update ID for stale configuration.
Updating tests
> DDF-2313 SourceConfigurationHandler doesn't handle multiple bindings with same fpid but different bindingTypes

- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/java/org/codice/ddf/registry/admin/plugin/RegistryPlugin.java
- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/model/FieldDescriptors.js
- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/model/Node.js
- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/view/Association.view.js
- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/view/CustomizableField.view.js
- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/view/Field.view.js
- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/view/NodeModal.view.js
- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/view/Registry.view.js
- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/view/Segment.view.js
- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/less/styles.less
- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/templates/associationList.handlebars
- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/templates/associationRow.handlebars
- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/templates/customFieldList.handlebars
- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/templates/field.handlebars
- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/templates/nodeList.handlebars
- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/templates/nodeModal.handlebars
- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/templates/registryPage.handlebars
- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/templates/segmentList.handlebars
- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/templates/segmentRow.handlebars
- catalog/spatial/registry/registry-federation-admin-impl/src/main/java/org/codice/ddf/registry/federationadmin/impl/FederationAdmin.java
- catalog/spatial/registry/registry-federation-admin-impl/src/test/java/org/codice/ddf/registry/federationadmin/impl/FederationAdminTest.java
The remote nodes are now displayed in the local nodes page. The nodes can be opened for inspection but not can't be modified
@clockard @mcalcote @vinamartin @brianfelix @ani6gup @andrewkfiedler 
@coyotesqrl 
@stustison
Two ddf instances are needed to manually test. Edit the identity node of the remote instance trying to add a value for each section.
In the local ddf, add the remote instance in the remote registries tab.
Verify the node information shows up under the Remote Nodes section
Open the node and verify the information cannot be modified.
Close the modal and click the delete button.
Verify that the node was removed.
DDF-2267
Changing FederationAdmin's deleteLocalEntry to call getRegistryMetacardsByIds, updating unit tests
Adding check to see if the construct title is a string or a …
> DDF-2267 Registry UI to Display All Nodes

- catalog/spatial/registry/registry-source-configuration-handler/pom.xml
- catalog/spatial/registry/registry-source-configuration-handler/src/main/java/org/codice/ddf/registry/source/configuration/SourceConfigurationHandler.java
- catalog/spatial/registry/registry-source-configuration-handler/src/test/java/org/codice/ddf/registry/source/configuration/SourceConfigurationHandlerTest.java
Updating SourceConfigurationHandler to update ID information for stale configurations. Updating to handle the case where the same factory pid may have multiple binding types.
@mcalcote @clockard 
@shaundmorris 
This is the 2.9.x back port for DDF-2313. This has been reviewed and hero'd under PR:
https://github.com/codice/ddf/pull/1043
DDF-2313
Fixing SourceConfigurationHandler to account for registry entry with multiple bindings with the same fpid but different bindingTypes
Fixing SourceConfigurationHandler to update ID for stale configuration.
Updating tets
> DDF-2313 SourceConfigurationHandler fixes (#1043)

- platform/security/pdp/security-pdp-authzrealm/src/main/java/ddf/security/pdp/realm/xacml/XacmlPdp.java
- platform/security/platform-security-core-api/pom.xml
- platform/security/platform-security-core-api/src/main/java/ddf/security/principal/GuestPrincipal.java
- platform/security/sts/security-sts-guestvalidator/src/main/java/org/codice/ddf/security/validator/guest/GuestValidator.java
@tbatie @ryeats @adimka
@figliold
@stustison
Build DDF, go to localhost:8993/admin, and confirm that the log no longer shows:
"couldn't create urn:oasis:names:tc:xacml:2.0:data-type:ipAddress attribute based on DOM node"
When the subject's IPv6 address is retrieved from shiro the string is in the format of: 0:0:0:0:0:0:0:0
In order to conform to the Xacml policy IPv6 addresses need to have brackets around them as follows: [0:0:0:0:0:0:0:0]
> DDF-2288 fix XacmlPdp to properly format Ipv6 atrributes

- platform/security/pdp/security-pdp-authzrealm/src/main/java/ddf/security/pdp/realm/xacml/XacmlPdp.java
- platform/security/platform-security-core-api/pom.xml
- platform/security/platform-security-core-api/src/main/java/ddf/security/principal/GuestPrincipal.java
- platform/security/sts/security-sts-guestvalidator/src/main/java/org/codice/ddf/security/validator/guest/GuestValidator.java
@figliold
@stustison
2.9.x PR
If it is merged into DDF master then this PR is good to merge
When the subject's IPv6 address is retrieved from shiro the string is in the format of: 0.0.0.0.0.0.0.0
In order to conform to the Xacml policy IPv6 addresses need to have brackets around them as follows: [0.0.0.0.0.0.0]
> DDF-2288-2.9.x fix XacmlPdp to properly format Ipv6 atrributes

- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/java/org/codice/ddf/registry/admin/plugin/RegistryPlugin.java
- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/model/FieldDescriptors.js
- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/model/Node.js
- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/view/Association.view.js
- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/view/CustomizableField.view.js
- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/view/Field.view.js
- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/view/NodeModal.view.js
- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/view/Registry.view.js
- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/view/Segment.view.js
- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/less/styles.less
- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/templates/associationList.handlebars
- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/templates/associationRow.handlebars
- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/templates/customFieldList.handlebars
- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/templates/field.handlebars
- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/templates/nodeList.handlebars
- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/templates/nodeModal.handlebars
- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/templates/registryPage.handlebars
- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/templates/segmentList.handlebars
- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/templates/segmentRow.handlebars
- catalog/spatial/registry/registry-federation-admin-impl/src/main/java/org/codice/ddf/registry/federationadmin/impl/FederationAdmin.java
- catalog/spatial/registry/registry-federation-admin-impl/src/test/java/org/codice/ddf/registry/federationadmin/impl/FederationAdminTest.java
The remote nodes are now displayed in the local nodes page. The nodes can be opened for inspection but not can't be modified
@shaundmorris 
Two ddf instances are needed to manually test. Edit the identity node of the remote instance trying to add a value for each section.
In the local ddf, add the remote instance in the remote registries tab.
Verify the node information shows up under the Remote Nodes section
Open the node and verify the information cannot be modified.
Close the modal and click the delete button.
Verify that the node was removed.
This is the 2.9.x backport of the functionality. The changes have been reviewed and merged: 
https://github.com/codice/ddf/pull/1004
DDF-2267
Changing FederationAdmin's deleteLocalEntry to call getRegistryMetacardsByIds, updating unit tests …
> DDF-2267 Registry UI to Display All Nodes (#1004) 2.9.x backport

- catalog/ui/search-ui/standard/src/main/webapp/js/model/NearbyLocation.js
The PR fixes the issue that the /services/REST/v1/Locations/nearby/cities/ endpoint is returning a 404 when a record on the search results with a location is opened to the Summary tab. These warnings were logged:
```bash
08:59:27,570 | WARN  | tp2056892729-585 | org.apache.cxf.jaxrs.utils.JAXRSUtils     524 | xf-rt-frontend-jaxrs | No operation matching request path "/services/REST/v1/Locations/nearby/cities/" is found, Relative Path: /nearby/cities/, HTTP Method: GET, ContentType: */*, Accept: application/json,text/javascript,*/*;q=0.01,. Please enable FINE/TRACE log level for more details.
08:59:27,571 | WARN  | tp2056892729-585 | jaxrs.impl.WebApplicationExceptionMapper   72 | xf-rt-frontend-jaxrs | javax.ws.rs.ClientErrorException: HTTP 404 Not Found ...
```
This issue was traced to …
> DDF-2326: Fixed issue with no location in nearby/cities/ request on Search UI

- catalog/ftp/pom.xml
- catalog/ftp/src/main/java/ddf/catalog/ftp/UserManagerImpl.java
- catalog/ftp/src/main/java/ddf/catalog/ftp/ftplets/FtpRequestHandler.java
- catalog/ftp/src/test/java/ddf/catalog/ftp/ftplets/FtpRequestHandlerTest.java
-Use subject.execute() instead of attaching subject to CreateRequestImpl object properties
-Updates existing FTP user's subject
-Return an FtpReply.DISCONNECT if subject null on file upload
@mweser @emmberk @stustison @troymohl 
@jaymcnallie
@kcwire 
-Run DDF
-Install `catalog-ftp` feature
-Restart DDF
-Ingest via ftp
On a restart of DDF with the FTP feature installed, the FTP Endpoint could not find the SecurityManager.
> DDF-2048: Fix not found security manager on FTP Endpoint

- catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/data/impl/BasicTypes.java
- catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/data/impl/types/AssociationsAttributes.java
- catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/data/impl/types/ContactAttributes.java
- catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/data/impl/types/CoreAttributes.java
- catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/data/impl/types/DateTimeAttributes.java
- catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/data/impl/types/LocationAttributes.java
- catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/data/impl/types/MediaAttributes.java
- catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/data/impl/types/TopicAttributes.java
- catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/data/impl/types/ValidationAttributes.java
- catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/data/impl/types/VersionAttributes.java
Fixes new metacard types to return immutable sets of attributes instead of mutable sets.
@bdeining 
@glenhein 
@jlcsmith
@pklinef
https://codice.atlassian.net/browse/DDF-2275
> DDF-2275 Return immutable attribute sets

- catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/data/impl/types/MediaAttributes.java
Fix media.frame-center and media.compression. Change media.frame-center to GEO_TYPE and non-tokenized, change media.compression to STRING.
@bdeining 
@rzwiefel 
@jlcsmith
@kcwire
Run unit tests.
DDF-2275
> DDF-2275 fix media.frame-center and media.compression

- catalog/core/catalog-core-api/src/main/java/ddf/catalog/source/SourceCache.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/SolrCacheSource.java
- catalog/core/catalog-core-tagsfilterplugin/pom.xml
- catalog/core/catalog-core-tagsfilterplugin/src/main/java/org/codice/ddf/catalog/plugin/tagsfilter/TagsFilterQueryPlugin.java
- catalog/core/catalog-core-tagsfilterplugin/src/test/java/org/codice/ddf/catalog/plugin/tagsfilter/TagsFilterQueryPluginTest.java
Fixes issue with querying against the cache. Now only resources are queried by default.
@rzwiefel 
@andrewkfiedler  
@coyotesqrl 
@pklinef
A full build.
[DDF-2347](https://codice.atlassian.net/browse/DDF-2347)
> DDF-2347: Updated catalog framework to only query resources by default

- catalog/core/catalog-core-api/src/main/java/ddf/catalog/source/SourceCache.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/SolrCacheSource.java
- catalog/core/catalog-core-tagsfilterplugin/pom.xml
- catalog/core/catalog-core-tagsfilterplugin/src/main/java/org/codice/ddf/catalog/plugin/tagsfilter/TagsFilterQueryPlugin.java
- catalog/core/catalog-core-tagsfilterplugin/src/test/java/org/codice/ddf/catalog/plugin/tagsfilter/TagsFilterQueryPluginTest.java
Fixes issue with querying against the cache. Now only resources are queried by default.
@rzwiefel 
@andrewkfiedler  
@coyotesqrl 
@pklinef
A full build.
[DDF-2347](https://codice.atlassian.net/browse/DDF-2347)
> DDF-2347 [2.9.x]: Updated catalog framework to only query resources by default

- catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/data/impl/types/CoreAttributes.java
- catalog/core/catalog-core-api/src/main/java/ddf/catalog/data/types/Core.java
- distribution/ddf-common/src/main/resources/etc/definitions/core-attributes-validator.json
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalog.java
- distribution/test/itests/test-itests-ddf/src/test/resources/customtypedefinitions.json
- distribution/test/itests/test-itests-ddf/src/test/resources/metacard-datatype-validation.xml
Adds the DataType attribute to the Core Taxonomy to describe at a high level the type of data being cataloged.
@bdeining 
@jlcsmith
@kcwire 
Run the integration tests.
Added the attribute as well as default validation rules that enforce the valid values. Additional changes were made to the integration tests where a default feature no longer needs to be started. Added cleanup to content directory test.
https://codice.atlassian.net/browse/DDF-2332
> DDF-2332: Add data type attribute to Core taxonomy

- catalog/spatial/registry/registry-source-configuration-handler/pom.xml
- catalog/spatial/registry/registry-source-configuration-handler/src/main/java/org/codice/ddf/registry/source/configuration/SourceConfigurationHandler.java
- catalog/spatial/registry/registry-source-configuration-handler/src/test/java/org/codice/ddf/registry/source/configuration/SourceConfigurationHandlerTest.java
This PR adds null check to config.getProperties
@clockard @ani6gup @mcalcote @vinamartin @ryeats 
@figliold
@shaundmorris
Start up DDF with registry. 
Open the DDF Catalog app. 
Open the Node Information tab
Open the identity node and open the Services tab.
Add a service with at least one binding. Save
Open the Sources tab.
Verify a source exists for you identity node, you may have to refresh the list.
DDF-2313
Fixing Null Pointer exception.
> DDF-2313: SourceConfigurationHandler Null pointer introduced

- catalog/core/catalog-core-federationstrategy/src/test/java/ddf/catalog/federation/impl/FederationStrategyTest.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/CatalogFrameworkImpl.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/CreateOperations.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/DeleteOperations.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/OperationsCrudSupport.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/OperationsMetacardSupport.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/OperationsSecuritySupport.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/QueryOperations.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/ResourceOperations.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/SourceOperations.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/TransformOperations.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/UpdateOperations.java
- catalog/core/catalog-core-standardframework/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/impl/CatalogFrameworkImplTest.java
- catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/impl/CatalogFrameworkQueryTest.java
- catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/impl/FanoutCatalogFrameworkTest.java
This is the first phase of a change to `CatalogFrameworkImpl` which turns it into a facade over several logical delegate classes. These delegates silo logically like functionality in order to facilitate further refactoring, cleanup, and future maintenance.
@rzwiefel @kcwire @ryeats @tbatie 
@pklinef
@shaundmorris
@stustison
As this breaks apart one of the core components of DDF, it will require not only a full build with itests, but an extensive run through manual use of the system to ensure that no functionality has been broken.
The current version of `CatalogFrameworkImpl` in master is 3397 lines long and contains much duplicative, redundant code. It is difficult to maintain and rather fragile. By breaking it up, we can isolate logical silos of work that are easier to reason about, …
> DDF-2344 Pull out functionality from CatalogFrameworkImpl to logical subcomponents.

- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/resource/download/ReliableResourceDownloader.java
- catalog/core/catalog-core-urlresourcereader/src/main/java/ddf/catalog/resource/impl/URLResourceReader.java
- catalog/core/catalog-core-urlresourcereader/src/test/java/ddf/catalog/resource/impl/ResourceReaderTest.java
- catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/CswRecordCollection.java
- catalog/spatial/csw/spatial-csw-source-common/pom.xml
- catalog/spatial/csw/spatial-csw-source-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/AbstractCswSource.java
- catalog/spatial/csw/spatial-csw-source-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/reader/GetRecordsMessageBodyReader.java
- catalog/spatial/csw/spatial-csw-source-common/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/TestCswSource.java
- catalog/spatial/csw/spatial-csw-source-common/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/reader/TestGetRecordsMessageBodyReader.java
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFederation.java
Adds range header support for product retrieval retries. When the ReliableResourceDownloader attempts to retry retrieval of a product, it will no longer start over from the beginning of the download every time. There was also a major bug where DDF would properly use range headers to retrieve a product during a retry, but it would skip bytes in the input stream regardless of whether or not the server responding supported it or not, meaning unread data would be skipped and the file would become corrupted.
@pklinef 
@oconnormi 
@jrnorth 
@coyotesqrl
@figliold 
itests were added to check that the CSW retrieval works properly and to test retries via simulated network disconnects. There were also a few itests for simple opensearch downloads. There is a ticket out that we will be picking up soon …
> DDF-2300: Range Headers are now supported for Product Retrieval

- catalog/admin/module/catalog-admin-module-sources/src/main/webapp/js/view/Utils.js
This PR fixes the issue where the Source modal won't open up if there is a single quote in the source's name.
@mcalcote @clockard @vinamartin @ryeats @ani6gup @brianfelix @djblue 
@figliold 
@shaundmorris
Start up DDF with registry. 
Open the DDF Catalog app. 
Open the Node Information tab
Open the identity node and rename it to something containing a single quote
Open the Services tab.
Add a service with at least one binding. Save
Open the Sources tab.
Verify a source exists for you identity node, you may have to refresh the list.
Click on the source and verify the modal opens up.
DDF-2346
Updating the popover selector to remove the attribute check for 'data-title'.
An update was made to the backing library JQuery (or Sizzle) where the data-title attribute value containing a single quote …
> DDF-2346: Source Modal does not like single quoted names

- catalog/admin/module/catalog-admin-module-sources/src/main/webapp/js/view/Utils.js
This PR fixes the issue where the Source modal won't open up if there is a single quote in the source's name.
@mcalcote @clockard @vinamartin @ryeats @ani6gup @brianfelix @djblue 
@shaundmorris
Start up DDF with registry. 
Open the DDF Catalog app. 
Open the Node Information tab
Open the identity node and rename it to something containing a single quote
Open the Services tab.
Add a service with at least one binding. Save
Open the Sources tab.
Verify a source exists for you identity node, you may have to refresh the list.
Click on the source and verify the modal opens up.
These changes were reviewed, hero'ed, and manually tested: https://github.com/codice/ddf/pull/1083
DDF-2346
Updating the popover selector to remove the attribute check for 'data-title'.
An update was made to the backing …
> DDF-2346: Source Modal does not like single quoted names (#1083)

- catalog/catalog-app/pom.xml
- catalog/catalog-app/src/main/resources/features.xml
- catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/operation/impl/UpdateRequestImpl.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/UpdateOperations.java
- catalog/plugin/catalog-plugin-content-uri/pom.xml
- catalog/plugin/catalog-plugin-content-uri/src/main/java/org/codice/ddf/catalog/content/plugin/uri/ContentUriAccessPlugin.java
- catalog/plugin/catalog-plugin-content-uri/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/plugin/catalog-plugin-content-uri/src/test/java/org/codice/ddf/catalog/content/plugin/uri/TestContentUriAccessPlugin.java
- catalog/plugin/pom.xml
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalog.java
Adds an `AccessPlugin` that prevents resource URIs in the content store from being overwritten.
@harrison-tarr @ahoffer 
@pklinef
@stustison
Ingest a product to the content store, such as via the search UI. Verify that attempting to overwrite the resource URI of the generated metacard is rejected.
https://codice.atlassian.net/browse/DDF-2327
> DDF-2327 Add content uri overwrite protection

- distribution/ddf-common/src/main/resources/etc/system.properties
fix issue ingesting images caused by generating thumbnails on headless server
@tbatie @adimka @bcwaters 
@coyotesqrl
@shaundmorris
run a ddf on a headless server and successfully ingest an image and verify that a thumbnail is generated
> DDF-2359 fix issues ingesting images on a headless server

- distribution/docs/src/main/resources/_contents/installing-contents.adoc
- distribution/docs/src/main/resources/_contents/quickstart-contents.adoc
Adds a recommendation to use a Java version of 8u60 or higher.
@vinamartin @Lambeaux @jrnorth 
@shaundmorris
@stustison
review documentation
[DDF-2365](https://codice.atlassian.net/browse/DDF-2365)
> DDF-2365: updated recommended Java version in DDF docs

- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/resource/download/ReliableResourceDownloader.java
- catalog/core/catalog-core-urlresourcereader/src/main/java/ddf/catalog/resource/impl/URLResourceReader.java
- catalog/core/catalog-core-urlresourcereader/src/test/java/ddf/catalog/resource/impl/ResourceReaderTest.java
- catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/CswRecordCollection.java
- catalog/spatial/csw/spatial-csw-source-common/pom.xml
- catalog/spatial/csw/spatial-csw-source-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/AbstractCswSource.java
- catalog/spatial/csw/spatial-csw-source-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/reader/GetRecordsMessageBodyReader.java
- catalog/spatial/csw/spatial-csw-source-common/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/TestCswSource.java
- catalog/spatial/csw/spatial-csw-source-common/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/reader/TestGetRecordsMessageBodyReader.java
- distribution/test/itests/test-itests-common/src/test/java/ddf/common/test/mock/csw/FederatedCswMockServer.java
- distribution/test/itests/test-itests-common/src/test/java/ddf/common/test/restito/ChunkedContent.java
- distribution/test/itests/test-itests-common/src/test/java/ddf/common/test/restito/HeaderCapture.java
- distribution/test/itests/test-itests-common/src/test/resources/csw-get-capabilities-response.xml
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFederation.java
- distribution/test/itests/test-itests-ddf/src/test/resources/csw-query-response.xml
**BACKPORT OF https://github.com/codice/ddf/pull/1064**
**What does this backport do?**
Backport is identical to original PR but also brings in some additional download itests to make sure that future backports won't break range-header and download functionality
**Choose 2 committers to review/merge the PR:**
@coyotesqrl 
@shaundmorris 
**-- ORIGINAL PR MESSAGE --**
**What does this PR do?**
Adds range header support for product retrieval retries. When the ReliableResourceDownloader attempts to retry retrieval of a product, it will no longer start over from the beginning of the download every time. There was also a major bug where DDF would properly use range headers to retrieve a product during a retry, but it would skip bytes in the input stream regardless of whether or not the server …
> DDF-2300: Range Headers supported for Product Retrieval & itests

- catalog/plugin/catalog-plugin-metacard-validation/src/main/java/ddf/catalog/metacard/validation/MetacardValidityFilterPlugin.java
- catalog/plugin/catalog-plugin-metacard-validation/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/plugin/catalog-plugin-metacard-validation/src/main/resources/OSGI-INF/metatype/metatype.xml
- catalog/plugin/catalog-plugin-metacard-validation/src/test/java/ddf/catalog/metacard/validation/MetacardValidityFilterPluginTest.java
- distribution/sdk/sample-metacard-validator/src/main/java/org/codice/ddf/sdk/validation/metacard/SampleMetacardValidator.java
- distribution/sdk/sample-metacard-validator/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- distribution/sdk/sample-metacard-validator/src/test/java/org/codice/ddf/sdk/validation/metacard/SampleMetacardValidatorTest.java
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/AbstractIntegrationTest.java
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalog.java
- distribution/test/itests/test-itests-ddf/src/test/resources/FilterPluginRes/sampleCleanMetacard.xml
- distribution/test/itests/test-itests-ddf/src/test/resources/FilterPluginRes/sampleErrorMetacard.xml
- distribution/test/itests/test-itests-ddf/src/test/resources/FilterPluginRes/sampleWarningMetacard.xml
Added a configuration in MetacardValidityFilterPlugin to distinguish between filtering metacards with validation errors, validation warnings, or neither.
@AzGoalie 
@coyotesqrl
@shaundmorris
> DDF-2356 Added configuration to distinguish between filtering metacards with errors or warnings

- catalog/core/catalog-core-commands/pom.xml
- catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/SeedCommand.java
- catalog/core/catalog-core-commands/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/core/catalog-core-commands/src/test/java/org/codice/ddf/commands/catalog/TestSeedCommand.java
Adds a `catalog:seed` command that allows the user to seed the local metacard and product caches from the enterprise or from specific federated sources.
@bdeining 
@glenhein 
@rzwiefel 
@jlcsmith 
@coyotesqrl 
Set up two DDFs. Ingest some products on DDF-1. On DDF-2, add DDF-1 as a federated source.
Run the `catalog:seed` command on DDF-2 with different values for the `--cql`, `--product-limit`, and `--source` options and verify that the expected metacards and products are added to the local caches.
[DDF-2333](https://codice.atlassian.net/browse/DDF-2333)
> DDF-2333 Add a command for seeding the metacard and product caches

- catalog/ui/search-ui/standard/src/main/webapp/js/model/user.js
- catalog/ui/search-ui/standard/src/main/webapp/js/view/preferences/PreferencesModal.view.js
Fixes regressions caused by the original DDF-2307 commit.
- Fix restore button to use properties
- Sort views by label instead of alpha
- Fix render order to avoid model binder errors when sorting the
collection
- Fix user model to not modify the original layer from properties
@djblue 
@pklinef
@stustison
Use the restore defaults button in the Standard UI map preferences.
https://codice.atlassian.net/browse/DDF-2307
> DDF-2307 Fix map preferences restore button

- catalog/plugin/catalog-plugin-metacard-validation/src/main/java/ddf/catalog/metacard/validation/MetacardValidityMarkerPlugin.java
- catalog/plugin/catalog-plugin-metacard-validation/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/plugin/catalog-plugin-metacard-validation/src/main/resources/OSGI-INF/metatype/metatype.xml
- catalog/plugin/catalog-plugin-metacard-validation/src/test/java/ddf/catalog/metacard/validation/MetacardValidityMarkerPluginTest.java
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/AbstractIntegrationTest.java
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalog.java
Adds the ability to configure whether to enforce validation warnings, errors, both, or neither out of the enforced validators.
before it can get merged; if a component team is listed, at least one of its members needs to approve)?
@coyotesqrl
@shaundmorris
Full build with tests
> DDF-2369 Add configuration to distinguish between enforcing validation errors and warnings

- catalog/spatial/registry/registry-federation-admin-impl/pom.xml
- catalog/spatial/registry/registry-federation-admin-impl/src/main/java/org/codice/ddf/registry/federationadmin/impl/FederationAdmin.java
- catalog/spatial/registry/registry-federation-admin-service-impl/src/main/java/org/codice/ddf/registry/federationadmin/service/impl/IdentityNodeInitialization.java
- catalog/spatial/registry/registry-schema-bindings/pom.xml
- catalog/spatial/registry/registry-schema-bindings/src/main/java/org/codice/ddf/registry/schemabindings/helper/MetacardMarshaller.java
- catalog/spatial/registry/registry-schema-bindings/src/main/java/org/codice/ddf/registry/schemabindings/helper/RegistryNamespacePrefixMapper.java
Previously, the Registry Metacard XML displayed the wrong namespace dateTime. 
While this currently doesn't cause any issues, it could in the future. This PR changes it to be the xs namespace. 
@clockard @mcalcote @gordocanchola 
@figliold 
@shaundmorris
Start up a DDF with DDF registry, then look for the identity node metacard in Solr (ddf distribution is the default name). Look in the metadata xml and ensure that dateTime fields have the slotType `xs:dateTime`. 
Additionally, verify the output is schema valid
https://codice.atlassian.net/browse/DDF-2348
> DDF-2348: Changes the Registry Metacard XML to have the xs namespace for dateTime

- catalog/plugin/catalog-plugin-metacard-validation/src/main/java/ddf/catalog/metacard/validation/MetacardValidityMarkerPlugin.java
- catalog/plugin/catalog-plugin-metacard-validation/src/test/java/ddf/catalog/metacard/validation/MetacardValidityMarkerPluginTest.java
Adds tags (VALID or INVALID) to a metacard when it is validated.
@harrison-tarr @emanns95 
@coyotesqrl
@lessarderic
Ingest some data that will run through a validator and verify in the search UI that it has the metacard tag VALID. Repeat with an invalid data and verify that it contains INVALID when show invalid metacards is enabled in the admin ui.
DDF-2374
> DDF-2374: Added metacard tags for valid/invalid metacards.

- catalog/spatial/registry/registry-ebrim-transformer/pom.xml
- catalog/spatial/registry/registry-ebrim-transformer/src/main/java/org/codice/ddf/registry/converter/RegistryPackageConverter.java
- catalog/spatial/registry/registry-ebrim-transformer/src/test/java/org/codice/ddf/registry/transformer/RegistryTransformerTest.java
- catalog/spatial/registry/registry-ebrim-transformer/src/test/resources/csw-null-metacard-attributes.xml
Provides null checks within metacard attributes. For instance, the phone number area code would return "(null) 123-4353" instead of "123-4353". The phone number and address metacard attributes now have more null checks. 
@mcalcote @vinamartin @gordocanchola @clockard @brianfelix 
@figliold
@stustison
Build and check it passed 
Bug was found while working on [DDF-2251](https://github.com/codice/ddf/pull/1053). Since the summary report pulled attribute values from the metacard, parts of these values such as the phone area code or the country of an address would show null if not provided. 
DDF-2334
> DDF-2334 Null values displayed in metacard organization attributes

- catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/data/impl/types/MediaAttributes.java
Changes frames per second and bits per second to be double instead of integer.
@bdeining 
@jlcsmith
@kcwire
Bits per second and frames per second are not necessarily always integers.
https://codice.atlassian.net/browse/DDF-2245
> DDF-2245: Updated frames per second and bits per second to support double value instead of integer.

- distribution/ddf-common/src/main/resources/etc/artemis.xml
- distribution/ddf-common/src/main/resources/etc/org.apache.activemq.artemis.cfg
- distribution/ddf-common/src/main/resources/etc/system.properties
- distribution/ddf/pom.xml
- distribution/ddf/src/main/filtered-resources/etc/org.apache.karaf.features.cfg
- distribution/ddf/src/main/filtered-resources/etc/org.codice.ddf.admin.application.service.impl.ApplicationServiceImpl.config
- platform/platform-app/src/main/resources/features.xml
- pom.xml
Adds a message bus application (Apache Artemis) allowing message communication from JMS queues and topics.
@coyotesqrl 
@ryeats 
@pklinef 
@jaymcnallie
@kcwire
Install artemis-amqp, and make sure it installs correctly.
Once artemis is installed, do a port scan on port 5672 using localhost to verify the connection to the message bus is open.
DDF-2321
> DDF-2321 Add artemis message bus features

- catalog/pom.xml
- pom.xml
OWASP will now pass. Some transitive dependency was bringing in a bad version of commons-fileupload that was not even being used. 
@tbatie 
@adimka 
@stustison 
@coyotesqrl
@shaundmorris
Invoke an OWASP-only check on a clean quick-build and ensure it passes. Can be done on Jenkins if desired.
> DDF-2316: Force commons-fileupload to 1.3.2 in solr pom to fix OWASP. 

- catalog/plugin/catalog-plugin-metacard-validation/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/plugin/catalog-plugin-metacard-validation/src/main/resources/OSGI-INF/metatype/metatype.xml
Updated the metatype.xml so that the ValidityFilterPlugin can be configured accurately through the UI.
@coyotesqrl 
@shaundmorris
Full build + check ddf-catalog configuration to make sure the filterplugin is configurable through the UI.
This is a fix to an error that was merged in with: https://github.com/codice/ddf/commit/d8566c85a5cd2c0c748e4ef0e503a79a2775c7f0
> DDF-2356 Updated the metatype.xml for ValidityFilterPlugin

- catalog/transformer/catalog-transformer-pptx/pom.xml
- catalog/transformer/catalog-transformer-pptx/src/main/java/ddf/catalog/transformer/input/pptx/PptxInputTransformer.java
- catalog/transformer/catalog-transformer-pptx/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/transformer/catalog-transformer-pptx/src/main/resources/OSGI-INF/metatype/metatype.xml
- catalog/transformer/catalog-transformer-pptx/src/test/java/ddf/catalog/transformer/input/pptx/PptxInputTransformerTest.java
- catalog/transformer/catalog-transformer-pptx/src/test/java/ddf/catalog/transformer/input/pptx/TestPptxInputTransformer.java
This PR adds the ability to optionally set the title as the metadata title on ingested PPTX files or use the filename.
@jlcsmith
@kcwire
Build and install DDF, configure the `PowerPoint Input Transformer` and observe correct behavior on PPTX ingest
https://codice.atlassian.net/browse/DDF-2379
> DDF-2379 Added a configuration to set the title as the metadata title in the Pptx Input Transformer

- catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/transformer/GmdTransformer.java
This PR adds back in a runtime exception that was accidentally removed. 
@peterhuffer  @troymohl  
@jlcsmith
@kcwire
@jaymcnallie 
Build DDF
It was observed that some extending projects were having problems on failed ingests because this exception was taken out.
> DDF-2328 Added in runtime exception that was accidentally removed due to ambiguity

- catalog/ftp/src/main/java/ddf/catalog/ftp/FtpServerStarter.java
- catalog/ftp/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/ftp/src/main/resources/OSGI-INF/metatype/metatype.xml
- catalog/ftp/src/test/java/ddf/catalog/ftp/FtpServerStarterTest.java
- distribution/ddf-common/src/main/resources/etc/system.properties
- distribution/docs/src/main/resources/_contents/_catalog-contents/integrating-catalog-contents.adoc
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFtp.java
This PR refactors the default port for the FTP endpoint so that it is configurable in system.properties. The FTP endpoint port in TestFtp itest is now set to a DynamicPort.
@lcrosenbu @peterhuffer @troymohl @mweser
@lessarderic 
@kcwire
1. Ensure FtpServerStarterTest and TestFtp itest pass.
2. Confirm that the FTP endpoint port number is configurable in system.properties:
1. Build DDF.
2. Change `org.codice.ddf.catalog.ftp.port` in $DDF_HOME/etc/system.properties file to a new port.
3. Start DDF, and start the FTP Endpoint feature (see https://github.com/codice/ddf/pull/784).
4. Using a FTP client of your choice (see https://github.com/codice/ddf/pull/784), confirm that the default port number for the FTP endpoint is now the new port that you set in the system.properties file.
5. Confirm …
> DDF-2249: Refactored the FTP endpoint default port to be configurable in system.properties

- platform/admin/ui/src/main/webapp/js/models/Alerts.js
- platform/admin/ui/src/main/webapp/js/util/SessionRefresherUtil.js
- platform/admin/ui/src/main/webapp/main.js
Adds a warning banner if the user session expires
@tbatie @adimka @djblue 
@shaundmorris
@stustison
log in to the admin console with two tabs logout with one of them and then try to do some action on the other and verify the banner changes to a warning about being logged out.
> DDF-2385 add banner warning to admin console when user session expires

- distribution/ddf/pom.xml
Upgrade to opendj-osgi 1.3.3
@Lambeaux @kcwire 
@coyotesqrl 
@shaundmorris
Full Build
Login using an LDAP user
A windows fix was added to opendj-osgi 1.3.3
DDF-2406
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codice/ddf/1151)
> DDF-2406 Upgraded to opendj-osgi 1.3.3

- catalog/schematron/catalog-schematron-plugin/src/main/resources/OSGI-INF/blueprint/blueprint.xml
Enables the properties of a SchematronValidationService to be filterable.
@harrison-tarr @brendan-hofmann @ahoffer 
@coyotesqrl
@lessarderic
> DDF-2421: Enabled filtering of schematron validation properties

- platform/security/sts/security-sts-guestvalidator/src/main/java/org/codice/ddf/security/validator/guest/GuestValidator.java
- platform/security/sts/security-sts-guestvalidator/src/test/java/org/codice/ddf/security/validator/guest/GuestValidatorTest.java
Fix scoped ipv6 addresses in guest tokens.
@clockard 
@glenhein 
@pklinef
@stustison
Verify that your computer asks for a guest token with a scoped ipv6 address. I was able to reliably produce this by using `?dev=true` to change my cert. Make sure (in a private session) that you can access guest pages like the login page.
This should be backported to 2.9.x and the same fix applied to videographer in alliance.
DDF-2416
> DDF-2416 Fix ip validation of guest tokens

- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFederation.java
Fixes the TestFederation intermittent itests failures that have been occurring recently with the bamboo nightly master build and bamboo PR builds.
@emanns95 
@figliold 
@kcwire 
@coyotesqrl 
Bamboo PR tests passed a few times in a row, but the master build and other PR builds should be watched after this gets merged in to make sure that the issue is completely gone.
> DDF-2422: TestFederation iTest Intermittent Failures

- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/ResourceOperations.java
fixes resource usage not counting against first users downloads
@bdeining @lcrosenbu @jrnorth @codice/core-api (which doesn't exist but should :) )
@jlcsmith
@lessarderic 
- This was caused by the sources not putting the resource request properties into the response.
> DDF-2368: Fixed resource usage not counting user's first download

- platform/admin/core/admin-core-logviewer/package.json
- platform/admin/core/admin-core-logviewer/src/main/resources/index.html
- platform/admin/core/admin-core-logviewer/src/main/webapp/js/components/log-viewer/log-viewer.less
- platform/admin/core/admin-core-logviewer/src/main/webapp/js/filter.js
- platform/admin/core/admin-core-logviewer/src/main/webapp/js/levels.js
- platform/admin/core/admin-core-logviewer/src/test/js/filter.js
The Log Viewer level filter now shows all logs with a severity higher-than-or-equal to the selected level. Ex, is the user chooses "WARN", it will show all logs with levels WARN and ERROR.
Some formatting bugs introduced in DDF-2270 were also fixed.
@djblue 
@oconnormi 
@lessarderic
@shaundmorris
Unit tests were added, so a full build should be enough.
> DDF-2391: Log Viewer Filtering Includes Higher Severities

- platform/security/sts/security-sts-guestvalidator/src/main/java/org/codice/ddf/security/validator/guest/GuestValidator.java
- platform/security/sts/security-sts-guestvalidator/src/test/java/org/codice/ddf/security/validator/guest/GuestValidatorTest.java
Fix scoped ipv6 addresses in guest tokens.
@clockard 
@glenhein 
@pklinef
@stustison
Verify that your computer asks for a guest token with a scoped ipv6 address. I was able to reliably produce this by using `?dev=true` to change my cert. Make sure (in a private session) that you can access guest pages like the login page.
This is a backport of #1160 
DDF-2416
> DDF-2416 Fix ipv6 validation of guest tokens

- catalog/core/catalog-core-api/src/main/java/ddf/catalog/data/types/Core.java
Reverts Core Attribute DERIVED RESOURCE URI to the original metacard attribute name for backwards compatibility.
@bdeining 
@dcruver 
@jlcsmith
@kcwire
Verify CAL-119 PR https://github.com/codice/alliance/pull/130. Ensure `resource.derived-uri` attribute is set on metacard for ingested NITF images.
The image chipping PR (https://github.com/codice/alliance/pull/130) in Alliance is dependent on this change.
https://codice.atlassian.net/browse/DDF-2275
Relates To: https://codice.atlassian.net/browse/CAL-119
N/A
> DDF-2275 Reverted DERIVED_RESOURCE_URI to the original metacard attribute name

- catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/data/impl/BasicTypes.java
- catalog/core/catalog-core-api/src/main/java/ddf/catalog/data/AttributeType.java
- catalog/core/catalog-core-api/src/main/java/ddf/catalog/data/types/Validation.java
- catalog/plugin/catalog-plugin-metacard-validation/src/main/java/ddf/catalog/metacard/validation/MetacardValidityMarkerPlugin.java
- catalog/plugin/catalog-plugin-metacard-validation/src/test/java/ddf/catalog/metacard/validation/MetacardValidityMarkerPluginTest.java
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/AbstractIntegrationTest.java
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalog.java
Adds which validators a metacard has been run through and indicates whether there are validation errors or warnings for each validator run.
@AzGoalie 
@coyotesqrl
@shaundmorris
Full Build
> DDF-2372 Allow metacards to track which validators have been run

- catalog/plugin/catalog-plugin-metacard-validation/src/main/resources/OSGI-INF/metatype/metatype.xml
- distribution/docs/src/main/resources/_contents/_catalog-contents/extending-catalog-contents.adoc
Changed metatype to have no cardinality so that enforcement is configurable using a checkbox rather than a text field
@AzGoalie 
@coyotesqrl
@shaundmorris
Build and verify metatype
This is to correct a mistake from https://github.com/codice/ddf/pull/1112
> DDF-2369 Changed metatpye.xml for ValidityMarkerPlugin configuration

- catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/validation/impl/validator/EnumerationValidator.java
- catalog/core/catalog-core-api-impl/src/test/java/ddf/catalog/validation/impl/EnumerationValidatorTest.java
- catalog/core/catalog-core-validationparser/pom.xml
- catalog/core/catalog-core-validationparser/src/main/java/ddf/catalog/validation/impl/ValidationParser.java
- catalog/core/catalog-core-validator/src/test/java/ddf/catalog/validation/impl/ReportingMetacardValidatorImplTest.java
- distribution/ddf-common/src/main/resources/etc/definitions/core-attributes-validator.json
- distribution/docs/src/main/resources/_contents/_catalog-contents/integrating-catalog-contents.adoc
Adds a case in-sensitive enumeration validator.
@bdeining 
@jrnorth 
@jlcsmith
@pklinef
Run the JUnit tests
Existing enumeration validator was case sensitive. Other systems may specify a value all caps or all lower-case and we want those values to be evaluated against the same list (e.g. Document and document are both considered valid attribute values). 
https://codice.atlassian.net/browse/DDF-2366
> DDF-2366: Added a case-insensitive enumeration validator for attribute validation.

- catalog/spatial/registry/registry-api-impl/src/main/java/org/codice/ddf/registry/api/impl/RegistryStoreCleanupHandler.java
- catalog/spatial/registry/registry-api-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/spatial/registry/registry-api-impl/src/main/resources/OSGI-INF/metatype/metatype.xml
- catalog/spatial/registry/registry-api-impl/src/test/java/org/codice/ddf/registry/api/impl/RegistryStoreCleanupHandlerTest.java
- catalog/spatial/registry/registry-federation-admin-service-impl/src/main/java/org/codice/ddf/registry/federationadmin/service/impl/RefreshRegistryEntries.java
- catalog/spatial/registry/registry-federation-admin-service-impl/src/main/resources/OSGI-INF/metatype/metatype.xml
- catalog/spatial/registry/registry-federation-admin-service-impl/src/test/java/org/codice/ddf/registry/federationadmin/service/impl/RefreshRegistryEntriesTest.java
Adds cleanup logic for registry entries when a remote registry is removed or if a remote registry stops providing certain registry entries.
@mcalcote @tbatie @gordocanchola 
@figliold
@lessarderic
Build and unit/itests pass. 
Manually test by setting up two registries (reg1 and reg2) and have one subscribe to the other (reg1 subscribes to reg2). 
Add a secondary local node to reg2 to and verify that node shows up after 30 seconds or so in reg1 Node Information tab.
Remove secondary local node on reg2 and verify that after 30 seconds or so it is removed from reg1 Node Information tab.
Remove remote registry connection to reg2 on reg1. Verify reg2 identity node is removed from reg1 Node Information.
DDF-2266
> DDF-2266 Added RegistryStoreCleanupHandler to cleanup registry entries once a remote registry is removed.

- catalog/ftp/src/main/java/ddf/catalog/ftp/FtpServerStarter.java
- catalog/ftp/src/test/java/ddf/catalog/ftp/FtpServerStarterTest.java
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFtp.java
This PR adds itests for the FTPS endpoint, specifically testing that changing the clientAuth configuration for the ftp-endpoint feature causes the FTP server to close connections with clients as expected.
@lcrosenbu @peterhuffer @troymohl @tbatie
@jaymcnallie
@kcwire
Confirm that TestFtp itests pass.
The FTP endpoint will shut down the connection if the client does not have a valid certificate (or does not have a certificate set) when the clientAuth configuration for the ftp-endpoint feature is set to `need`. The four cases can be tested by using the `curl` command and changing the clientAuth configuration (See https://github.com/codice/ddf/pull/926):
1. Set `clientAuth = want` on Admin UI, then `curl --insecure -v -S --ftp-ssl -ftp-method singlecwd -E /path/to/client/cert:certPassword …
> DDF-2373 Added itests for FTPS endpoint

- catalog/core/catalog-core-api-impl/src/test/java/ddf/catalog/impl/MockMemoryProvider.java
- catalog/core/catalog-core-api/src/main/java/ddf/catalog/Constants.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/DeleteOperations.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/QueryOperations.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/UpdateOperations.java
- catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/impl/CatalogFrameworkImplTest.java
- catalog/core/catalog-core-versioning/versioning-common/src/main/java/ddf/catalog/core/versioning/MetacardVersion.java
- catalog/core/catalog-core-versioning/versioning-common/src/test/groovy/ddf/catalog/core/versioning/HistoryMetacardImplSpecTest.groovy
- catalog/spatial/registry/registry-common/pom.xml
- catalog/spatial/registry/registry-common/src/main/java/org/codice/ddf/registry/common/metacard/RegistryObjectMetacardType.java
- catalog/transformer/catalog-transformer-zip/pom.xml
Fixes versioning. 
@jrnorth @djblue @kcwire 
@coyotesqrl
@pklinef
Ingest some non-resource metacard. Ensure in solr that all attributes were versioned. 
There was a bug originally where we were storing only the basic attributes of a metacard in the revisions. Once that was fixed it exposed another problem that was caused when updating by something other than metacard id. (Needed to be unique attribute when we go to search and update/delete it, but with history enabled there was now two of these 'unique' values on metacards)
DDF-2296
> DDF-2296: Fixed bug in Versioning

- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/ResourceOperations.java
- catalog/core/catalog-core-standardframework/src/test/groovy/ddf/catalog/impl/operations/ResourceOperationsTest.groovy
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFederation.java
*This is a re-pullrequest since catalogframework rework*
Adds back the anytag search into the catalog framework queries while getting resources
@djblue 
@ryeats 
@stustison 
@kcwire 
@coyotesqrl
@pklinef
> DDF-2296: Fixed local resource query to include anytag search

- distribution/docs/src/main/resources/_contents/config.adoc
Fix for adoc bug that causes ToC headers to appear in table cells. 
@lcrosenbu @Lambeaux @jrnorth 
@coyotesqrl
@pklinef
verify tables no longer appear in html documentation output. `ctrl+f` for "Table of Contents" should have one result. (The _real_ ToC).
Newer version of asciidoctor introduced a regression causing "Table of Contents" headers to appear in table cells. This is the approved workaround per https://github.com/asciidoctor/asciidoctor/issues/1582
before (bad): 
after (good):
> DDF-2309: fix for adoc bug causing ToC to appear in table cells

- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/model/Field.js
- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/model/Segment.js
- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/view/NodeModal.view.js
- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/main.js
- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/templates/nodeList.handlebars
The Registry Node Information screen will not display information if an invalid date is in any node's information. This would result in node modals not being accessable and not being displayed in the UI. 
This PR fixes the issue by replacing any invalid dates/times with a valid date/time representing now. These new valid values are not saved to the node unless the user chooses to do so.
@vinamartin @clockard @gordocanchola @brianfelix @ani6gup @andrewkfiedler 
@pklinef
@stustison
1. Verify Invalid Dates are not accepted from the User
Boot up the Registry-App an attempt to enter an invalid date/time (can only be performed on FireFox or IE) for any of the date fields, and more specifically the custom fields.
Invalid dates should not be saved to the node.
2. Verify Invalid Dates from another …
> DDF-2345 Update Registry Node Info screen to handle invalid dates

- catalog/core/catalog-core-standardframework/src/test/groovy/ddf/catalog/impl/operations/SourceOperationsTest.groovy
DDF-2440: Fixes the async conditional wait condition from the default of 1 second to five more seconds than the sourcepoller's interval.
This will allow the SourcePoller time to run its operation in the background.
@tbatie @brendan-hofmann 
@coyotesqrl
@lessarderic
Full build/test run.
The async operations usage in here was believed to be sufficient to wait until the underlying code had been run but clearly that is not the case. We should resolve these tests; however, keeping the live at this time is causing intermittent build failures.
DDF-2440
N/A
> DDF-2440: Fixes the async conditional wait for SourcePoller tests.

- catalog/core/catalog-core-standardframework/pom.xml
- catalog/core/catalog-core-validationparser/pom.xml
- catalog/core/catalog-core-versioning/versioning-common/pom.xml
- catalog/transformer/catalog-transformer-pdf/pom.xml
- catalog/transformer/catalog-transformer-pptx/pom.xml
- catalog/ui/search-ui/search-endpoint/pom.xml
- libs/pom.xml
- libs/spock-shaded/pom.xml
- platform/security/common/pom.xml
- platform/security/core/security-core-impl/pom.xml
- platform/security/idp/security-idp-server/pom.xml
- pom.xml
Creates uber jar and moves the plugin invocation.
Now to add Spock tests to a bundle, users will need only add one dependency to the new spock shaded jar and do nothing else.
@tbatie @adimka 
@coyotesqrl
@jlcsmith 
A full build with unit tests should be sufficient. Compilation errors would indicate issues with the shaded jar; coverage errors would indicate that the gmaven-plus plugin was not correctly being invoked.
N/A
DDF-2426
N/A
> DDF-2426 Creates shaded uber jar for Spock and moves the gmaven-plus plugin invocation to the root pom

- platform/admin/core/admin-core-appservice/pom.xml
- platform/admin/core/admin-core-appservice/src/test/java/org/codice/ddf/admin/application/rest/ApplicationUploadEndpointTest.java
- platform/admin/core/admin-core-appservice/src/test/java/org/codice/ddf/admin/application/service/command/AddApplicationCommandTest.java
- platform/admin/core/admin-core-appservice/src/test/java/org/codice/ddf/admin/application/service/command/completers/ActiveApplicationsCompleterTest.java
- platform/admin/core/admin-core-appservice/src/test/java/org/codice/ddf/admin/application/service/command/completers/AllApplicationsCompleterTest.java
- platform/admin/core/admin-core-appservice/src/test/java/org/codice/ddf/admin/application/service/command/completers/NotActiveApplicationsCompleterTest.java
- platform/admin/core/admin-core-appservice/src/test/java/org/codice/ddf/admin/application/service/impl/ApplicationConfigInstallerTest.java
- platform/admin/core/admin-core-appservice/src/test/java/org/codice/ddf/admin/application/service/impl/ApplicationFileInstallerTest.java
- platform/admin/core/admin-core-appservice/src/test/java/org/codice/ddf/admin/application/service/impl/ApplicationServiceBeanTest.java
- platform/admin/core/admin-core-appservice/src/test/java/org/codice/ddf/admin/application/service/impl/ApplicationServiceImplTest.java
These tests are very fragile - as evidenced by the fact one test is broken after logging changes have been made - and should not be expecting specific log output. In order to fix the broken build, this change ignores the broken test. The associated ticket will remain open and the other tests will be fixed in short order.
@brendan-hofmann @rzwiefel 
@beyelerb
@stustison
Full build/test run to ensure the unit test is not causing the build to fail.
Logging recently went through an overhaul/cleanup and fragile tests like these are prone to break under those changes.
DDF-2443
N/A
> DDF-2443: Ignores one unit test depending on specific log output and comments others

- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/model/Field.js
- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/model/Segment.js
- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/view/NodeModal.view.js
- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/main.js
- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/templates/nodeList.handlebars
The Registry Node Information screen will not display information if an invalid date is in any node's information. This would result in node modals not being accessible and not being displayed in the UI.
This PR fixes the issue by replacing any invalid dates/times with a valid date/time representing now. Additionally, the user's input is also validated and an error warning appears if needed. These new valid values are not saved to the node unless the user chooses to do so.
@pklinef
@shaundmorris
@stustison
Confirm Local Node modal still functions as expected.
Merged into master -> https://github.com/codice/ddf/pull/1114
DDF-2345
> DDF-2345 -> 2.9.x Update Registry Node Info screen to handle invalid dates

- catalog/admin/module/catalog-admin-module-sources/src/main/webapp/templates/sourceList.handlebars
- catalog/admin/module/catalog-admin-module-sources/src/main/webapp/templates/sourceRow.handlebars
- catalog/spatial/registry/registry-source-configuration-handler/src/main/java/org/codice/ddf/registry/source/configuration/SourceConfigurationHandler.java
- catalog/spatial/registry/registry-source-configuration-handler/src/test/java/org/codice/ddf/registry/source/configuration/SourceConfigurationHandlerTest.java
Removed local node from sources tab table and made disabled sources show no status.
@tbatie @vinamartin 
@coyotesqrl
@stustison
Startup an instance and add a csw service binding to the identity node. 
Verify that there are no sources created in the sources tab
Create a secondary local node with a csw service binding. Verify that it comes up in the sources tab and when it is disabled the status column is empty.
DDF-2420
> DDF-2420 Removed local node from sources tab table and made disabled sources show no status.

- catalog/transformer/catalog-transformer-pdf/pom.xml
- catalog/transformer/catalog-transformer-pdf/src/main/java/ddf/catalog/transformer/input/pdf/CheckedFunction.java
- catalog/transformer/catalog-transformer-pdf/src/main/java/ddf/catalog/transformer/input/pdf/GeoPdfParserImpl.java
- catalog/transformer/catalog-transformer-pdf/src/main/java/ddf/catalog/transformer/input/pdf/PDDocumentGenerator.java
- catalog/transformer/catalog-transformer-pdf/src/main/java/ddf/catalog/transformer/input/pdf/PDDocumentGeneratorImpl.java
- catalog/transformer/catalog-transformer-pdf/src/main/java/ddf/catalog/transformer/input/pdf/PdfInputTransformer.java
- catalog/transformer/catalog-transformer-pdf/src/main/java/ddf/catalog/transformer/input/pdf/PdfThumbnailGenerator.java
- catalog/transformer/catalog-transformer-pdf/src/main/java/ddf/catalog/transformer/input/pdf/PdfThumbnailGeneratorImpl.java
- catalog/transformer/catalog-transformer-pdf/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/transformer/catalog-transformer-pdf/src/main/resources/OSGI-INF/metatype/metatype.xml
- catalog/transformer/catalog-transformer-pdf/src/test/groovy/ddf/catalog/transformer/input/pdf/PdfInputTransformerSpecTest.groovy
- catalog/transformer/catalog-transformer-pdf/src/test/java/ddf/catalog/transformer/input/pdf/GeoPdfDocumentGenerator.java
- catalog/transformer/catalog-transformer-pdf/src/test/java/ddf/catalog/transformer/input/pdf/GeoPdfParserTest.java
- catalog/transformer/catalog-transformer-pdf/src/test/java/ddf/catalog/transformer/input/pdf/PdfInputTransformerTest.java
Update PdfInputTransformer for new taxonomy. This is the second attempt, which includes the content metadata extractors.
@bdeining 
@jrnorth 
@rzwiefel 
@coyotesqrl 
@jlcsmith
Ingest a PDF and check SOLR for non-new-taxonomy fields.
DDF-2341
> DDF-2341 update PdfInputTransformer for new taxonomy

- catalog/opensearch/catalog-opensearch-endpoint/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFederation.java
Fixed opensearch CatalogEndpoint urlBindingName
The urlBindingName for opensearch was wrong so the wrong property was set in the config causing the opensearch source to use its default values making it a loopback source instead of connecting to the correct endpoint
@kcwire
@shaundmorris
Since this won't affect any unit or itests just quick build ddf and bring up an instance with registry installed. Add a service with a opensearch binding. Verify the source created in the sources tab has a correctly populated url and not one containing default variables. 
DDF-2434
> DDF-2434 Fixed opensearch CatalogEndpoint urlBindingName

- catalog/ui/search-ui/standard/src/main/webapp/js/view/Query.view.js
There was a bug where an empty query would be created in a Search UI Workspace if the "< Workspace" back button is clicked on instead of the cancel button. To fix this bug, the "< Workspace" back button has been to hidden to prevent a user from clicking on it in the first place.
@djblue 
@stustison 
@jaymcnallie
@pklinef
1. Create a Workspace
2. Click on the Workspace
3. Click on the "+" to edit a Worksapce
4. Notice that the "< Workspace" button has disappeared, click "Cancel" to cancel editing a query in a Workspace, and that no empty query was generated in the workspace.
DDF-1789
> DDF-1789 Hide workspace back button in the "Add/Edit Search" view to prevent empty queries from generating in the workspace

- catalog/spatial/registry/registry-federation-admin-service-impl/src/main/java/org/codice/ddf/registry/federationadmin/service/impl/RefreshRegistryEntries.java
- catalog/spatial/registry/registry-federation-admin-service-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/spatial/registry/registry-federation-admin-service-impl/src/main/resources/OSGI-INF/metatype/metatype.xml
- catalog/spatial/registry/registry-federation-admin-service-impl/src/test/java/org/codice/ddf/registry/federationadmin/service/impl/RefreshRegistryEntriesTest.java
Multithreads the registry subscription polling.
@tbatie  @mcalcote 
@figliold
@lessarderic
Setup a couple of ddfs and make sure the subscription between them still works
DDF-2282
- Also switched to an internal scheduler for polling instead of a camel route
> DDF-2282  Updated RefreshRegistryEntries remote registry queries to be multi-threaded

- catalog/spatial/registry/registry-api-impl/src/main/java/org/codice/ddf/registry/api/impl/RegistryStoreCleanupHandler.java
- catalog/spatial/registry/registry-api-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/spatial/registry/registry-api-impl/src/main/resources/OSGI-INF/metatype/metatype.xml
- catalog/spatial/registry/registry-api-impl/src/test/java/org/codice/ddf/registry/api/impl/RegistryStoreCleanupHandlerTest.java
- catalog/spatial/registry/registry-federation-admin-service-impl/src/main/java/org/codice/ddf/registry/federationadmin/service/impl/RefreshRegistryEntries.java
- catalog/spatial/registry/registry-federation-admin-service-impl/src/main/resources/OSGI-INF/metatype/metatype.xml
- catalog/spatial/registry/registry-federation-admin-service-impl/src/test/java/org/codice/ddf/registry/federationadmin/service/impl/RefreshRegistryEntriesTest.java
Backport for https://github.com/codice/ddf/pull/1150
@lessarderic 
Verify bamboo passes
https://github.com/codice/ddf/pull/1150
DDf-2266
- Includes subscription cleanup logic as well for when remote registries stop providing certain registry entries.
(cherry picked from commit 41f9d4e)
> DDF-2266 Backport - Added RegistryStoreCleanupHandler to cleanup registry entries once a remote registry is removed

- catalog/opensearch/catalog-opensearch-endpoint/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFederation.java
Back port of https://github.com/codice/ddf/pull/1184
@shaundmorris
Verify bambo passes
DDF-2434
(cherry picked from commit 0860ca1)
> DDF-2434 Backport - Fixed opensearch CatalogEndpoint urlBindingName

- catalog/spatial/registry/registry-federation-admin-service-impl/src/main/java/org/codice/ddf/registry/federationadmin/service/impl/RefreshRegistryEntries.java
- catalog/spatial/registry/registry-federation-admin-service-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/spatial/registry/registry-federation-admin-service-impl/src/main/resources/OSGI-INF/metatype/metatype.xml
- catalog/spatial/registry/registry-federation-admin-service-impl/src/test/java/org/codice/ddf/registry/federationadmin/service/impl/RefreshRegistryEntriesTest.java
Backport for https://github.com/codice/ddf/pull/1183
@lessarderic
Verify bamboo build passes
DDF-2282
- Also switched to an internal scheduler for polling instead of a camel route
(cherry picked from commit b6ecb4e)
> DDF-2282  Backport - Updated RefreshRegistryEntries remote registry queries to be multi-threaded

- catalog/ui/search-ui/standard/src/main/webapp/js/view/Query.view.js
- catalog/ui/search-ui/standard/src/main/webapp/templates/search/searchForm.handlebars
Add refresh calls when Specific Sources or Specific Types are selected.
This keeps them up to the date with the model changes caused by the
other options.
@andrewkfiedler @emanns95
@lessarderic
@pklinef
@shaundmorris
@stustison
Follow the instructions in the ticket and verify it no longer misbehaves. Test both Types and Sources.
https://codice.atlassian.net/browse/DDF-2446
> DDF-2446 Fix view/model sync in query multiselects

- catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/service/SearchService.java
When a textual query was performed with an empty value, while in the faceted view of the Search UI, an exception occurred as an empty CQL filter is not parseable. This has been changed to now perform a wildcard search if the value is empty.
-Added a conditional statement to prevent an empty CQL filter from being parsed. 
-If the CQL filter is empty (null), it'll be initialized with a wildcard contextual filter, which is what the code already does. 
@dcruver
@coyotesqrl 
@stustison 
@jaymcnallie
@pklinef 
1. Ingest a file.
2. Perform a query while in the faceted view of the Search UI using an empty value.
3. Verify a result has returned.
4. Verify no exception has occurred in the logs.
DDF-2171
> DDF-2171 Performing a textual search with an empty value will now default to a wildcard search, when in the faceted search view

- libs/owasp-diff-runner/src/test/java/ddf/lib/TestOwaspDiffRunner.java
Fixs the tests to ignore a passed maven.repo.local property.
@Lambeaux @adimka 
@coyotesqrl
@figliold 
owasp-diff-runner module builds when the maven.local.repo points to a directory that doesn't exist
> DDF-2414: Override maven.repo.local property in owasp-diff-runner tests

- catalog/admin/module/catalog-admin-module-sources/src/main/webapp/js/view/ModalSource.view.js
Fixes the status indicators on the operation actions in the source modal. The issue was the id that is used for the element id is the action provider id which has '.' in the it that need to be escaped for the css selector to work. Also set the spinner to display 'inline-block' so the spinner actually spins.
@vinamartin @ryeats @gordocanchola 
@coyotesqrl
@stustison
Install two instances of ddf with registry. Add a service binding to reg1. Add a remote registry on reg1 that only allows push to reg2. Go to the sources tab and open up the one source. At the bottom of the modal click the 'Publish to <reg2>' text and verify you get status back on the operation.
DDF-2415
After clicking the link and a successful publish you will see
After refresh of the dialog you will see
AFter clicking the …
> DDF-2415 Fixed publish/unpublish status indicators in source modal

- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/model/Node.collection.js
- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/view/Registry.view.js
Sorts registry nodes in the UI alphabetically. 
@clockard 
@vinamartin 
@figliold
@shaundmorris
Ensure DDF passes a full build. Then do the following: 
* Install the registry (if it is not installed already)
* Go to the _DDF Registry_ in the _Admin UI_
* On the first tab (default) called _Node Information_, add some local nodes in a non-alphabetical order with respect to their names. Ensure that the list of nodes remains alphabetically sorted. 
* Delete a node. Ensure the list of nodes remains alphabetically sorted. 
* See Lombardi for a sample CSW xml message that will provide local nodes. _POST_ that message to `/services/csw` and ensure the remote nodes are alphabetically sorted. 
This is an improvement directly related to community feedback.
> DDF-2449: Registry nodes are now sorted alphabetically.

- distribution/docs/src/main/resources/_contents/introduction-contents.adoc
Updates use of ${branding} in Introductory section of documentation that should be ${ddf-branding}.
@mcalcote @vinamartin
@coyotesqrl
@shaundmorris
docs render correctly. 
https://codice.atlassian.net/browse/DDF-2393
n/a
> DDF-2393:fixed branding usage in docs intro

- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/model/Segment.js
- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/view/Registry.view.js
- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/templates/nodeRow.handlebars
Normalizes the dates which previously may have been formatted differently than CSW nodes, this change ensures they will appear consistently when viewing the various nodes from the Local Node UI. This also improves the dates' user readability in the ui across all supported browsers.
@clockard @vinamartin @gordocanchola @brianfelix @andrewkfiedler 
@pklinef
@stustison 
Start Registry App and use the remote node ui to connect to a node with non-normalized dates, then navigate to the local node ui and observe the live dates formatting. **Please see me** for specific steps to verify the original issue has been addressed.
**Hero testing should confirm the changes in Firefox, IE and Chrome**
The previous work under DDF-2345 was bug fixes and implementing the moment.js library so I chose to use …
> DDF-2345 Further enforced registry node date formatting

- catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/DynamicSchemaResolver.java
Fixes exceptions caused by (mostly) duplicate attribute descriptors. 
@mcalcote @emanns95 @codice/solr 
@stustison
@pklinef 
https://codice.atlassian.net/browse/DDF-2450
- Previously when you would have identically named attributes on a metacard
solr would throw an exception if you try to store them. This fixes by making
sure that there is not a field value for a given field name already set on
the solr document. This will also continue the legacy behavior of the first
attribute in gets set as the value of a metacard.
> DDF-2450: Fixes solr exceptions when attributes name clash

- catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/data/impl/types/AssociationsAttributes.java
- catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/data/impl/types/CoreAttributes.java
Updating attribute descriptors that were not what we wanted them to be.  There will be a separate PR to update `DynamicSchemaResolver` and the `MetacardType` to attempt to prevent against duplicates coming in externally. 
@bdeining @brendan-hofmann 
@jlcsmith
@pklinef
> DDF-2423: Updating new attribute descriptors

- catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/DuplicateCommands.java
- catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/MigrateCommand.java
- catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/ReplicationCommand.java
- catalog/core/catalog-core-commands/src/test/java/org/codice/ddf/commands/catalog/TestReplicationCommand.java
- Adds an additional --lastMinute (-min) and --lastSeconds (-s) temporal options to DuplicateCommands to allow for finer granularity in selecting metacards to operate on
- For DuplicateCommands, Adds temporalProperty option to temporal operations which allows filtering metacards by "created", "modified", "effective", and "expiration" properties.
- Changed default temporalProperty from Metacard.EFFECTIVE to Core.CREATED to align with taxonomy
@glenhein @mweser @emmberk @millerw8 
@jlcsmith
@stustison
Start an instance of DDF and ingest some metacards. Use the `catalog:replicate` command with `--lastSeconds` and `--lastMinutes` tags (for example, `catalog:replicate -t --lastSeconds 77777` will replicate metacards whose products were created 77777 seconds ago). Also use the …
> DDF-2430: Add additional temporal options to DuplicateCommands

- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/model/Segment.js
- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/view/Registry.view.js
- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/templates/nodeRow.handlebars
Normalizes the dates which previously may have been formatted differently than CSW nodes, this change ensures they will appear consistently when viewing the various nodes from the Local Node UI. This also improves the dates' user readability in the ui across all supported browsers.
@clockard @vinamartin @gordocanchola @brianfelix @andrewkfiedler 
@pklinef
@stustison 
@shaundmorris 
Start Registry App and use the remote node ui to connect to a node with non-normalized dates, then navigate to the local node ui and observe the live dates formatting. **Please see me** for specific steps to verify the original issue has been addressed.
**Hero testing should confirm the changes in Firefox, IE and Chrome**
The previous work under DDF-2345 was bug fixes and implementing the moment.js library so I …
> DDF-2345 -> 2.9.X Further enforced registry node date formatting

- catalog/core/catalog-core-commons/src/main/java/ddf/catalog/filter/delegate/TagsFilterDelegate.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/DeleteOperations.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/UpdateOperations.java
- catalog/spatial/registry/registry-api-impl/src/main/java/org/codice/ddf/registry/api/impl/RegistryStoreImpl.java
- catalog/spatial/registry/registry-api-impl/src/test/java/org/codice/ddf/registry/api/impl/TestRegistryStore.java
- catalog/spatial/registry/registry-federation-admin-service-impl/src/main/java/org/codice/ddf/registry/federationadmin/service/impl/FederationAdminServiceImpl.java
- catalog/spatial/registry/registry-identification-plugin/pom.xml
- catalog/spatial/registry/registry-identification-plugin/src/main/java/org/codice/ddf/registry/identification/IdentificationPlugin.java
- catalog/spatial/registry/registry-identification-plugin/src/main/java/org/codice/ddf/registry/identification/RegistryIdPostIngestPlugin.java
- catalog/spatial/registry/registry-identification-plugin/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/spatial/registry/registry-identification-plugin/src/test/java/org/codice/ddf/registry/identification/IdentificationPluginTest.java
- catalog/spatial/registry/registry-identification-plugin/src/test/java/org/codice/ddf/registry/identification/RegistryIdPostIngestPluginTest.java
Fixes a duplication issue where loopback registry configurations cause local nodes to be duplicated.
There had been duplication logic in the IdentificationPlugin before but was removed when we
added the internal registry entries. Added the logic back in a separate class and only apply it to registry entries that aren't internal.
@stustison 
@figliold
Install ddf and ddf-registry. Create a loopback remote registry. After a minute or so go to solr and verify there is only one registry metacard entry (metacard-tags=registry)
DDF-2438
> DDF-2438 Fixed registry entry duplication issue in IdentificationPlugin

- catalog/spatial/registry/registry-policy-plugin/src/main/java/org/codice/ddf/registry/policy/RegistryPolicyPlugin.java
- catalog/spatial/registry/registry-policy-plugin/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/spatial/registry/registry-policy-plugin/src/main/resources/OSGI-INF/metatype/metatype.xml
- catalog/spatial/registry/registry-policy-plugin/src/test/java/org/codice/ddf/registry/policy/RegistryPolicyPluginTest.java
Currently the RegistryPolicyPlugin only has one configuration for all write operations (create/update/delete). This PR provides a way to configure access to each individual type of operation so you can control the create/update/delete operations separately.
@clockard @vinamartin @gordocanchola @brianfelix 
@coyotesqrl
@figliold
Build and confirm Registry Operations perform as expected
DDF-2458
> DDF-2458 Provide finer grain control of registry write operations

- catalog/admin/admin-poller-service/pom.xml
- catalog/admin/admin-poller-service/src/main/java/org/codice/ddf/catalog/admin/poller/AdminPollerServiceBean.java
- catalog/admin/admin-poller-service/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/admin/admin-poller-service/src/main/resources/OSGI-INF/metatype/metatype.xml
- catalog/admin/admin-poller-service/src/test/groovy/org/codice/ddf/catalog/admin/poller/AdminPollerServiceBeanTest.groovy
- catalog/admin/admin-poller-service/src/test/java/org/codice/ddf/catalog/admin/poller/AdminPollerTest.java
- distribution/docs/src/main/resources/_contents/configuring-from-the-admin-console-contents.adoc
Allows the filter being used to generate the list of source types to be configured from the admin UI. The default settings no longer list Schematron and any other offending pids can be easily excluded through the UI.
Updates documentation about this process.
@coyotesqrl 
@shaundmorris 
1. Make sure Schematron Validation Services doesn't appear as an source configuration option in the Catalog UI upon first starting the system.
2. Confirm the Admin Poller Service modal works on the System tab of the Admin UI
3. Confirm Schematron's the default settings appear in the modal (see screenshot).
4. Add a few patterns (\*csw\*, \*Csw\*, \*Federated\*, \*federated\*) and restart ddf to confirm that adding to the filter list removes sources.
5. Since the modal has been acting up, …
> DDF-2455 SchematronValidationService incorrectly appears as a source type

- catalog/spatial/registry/registry-policy-plugin/src/main/java/org/codice/ddf/registry/policy/RegistryPolicyPlugin.java
- catalog/spatial/registry/registry-policy-plugin/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/spatial/registry/registry-policy-plugin/src/main/resources/OSGI-INF/metatype/metatype.xml
- catalog/spatial/registry/registry-policy-plugin/src/test/java/org/codice/ddf/registry/policy/RegistryPolicyPluginTest.java
Currently the RegistryPolicyPlugin only has one configuration for all write operations (create/update/delete). This PR provides a way to configure access to each individual type of operation so you can control the create/update/delete operations separately.
@clockard @vinamartin @gordocanchola @brianfelix 
@coyotesqrl
@figliold
@shaundmorris 
Build and confirm Registry Operations perform as expected
Merged on Master https://github.com/codice/ddf/pull/1234
DDF-2458
> DDF-2458 -> 2.9.x Provide finer grain control of registry write operations

- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/model/Node.js
- catalog/spatial/registry/registry-common/src/main/java/org/codice/ddf/registry/common/metacard/RegistryObjectMetacardType.java
- catalog/spatial/registry/registry-common/src/test/java/org/codice/ddf/registry/common/metacard/TestRegistryObjectMetacardType.java
- catalog/spatial/registry/registry-ebrim-transformer/pom.xml
- catalog/spatial/registry/registry-ebrim-transformer/src/main/java/org/codice/ddf/registry/converter/RegistryPackageConverter.java
- catalog/spatial/registry/registry-ebrim-transformer/src/main/java/org/codice/ddf/registry/transformer/RegistryTransformer.java
- catalog/spatial/registry/registry-ebrim-transformer/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/spatial/registry/registry-ebrim-transformer/src/test/java/org/codice/ddf/registry/transformer/RegistryTransformerTest.java
- catalog/spatial/registry/registry-federation-admin-service-impl/src/main/java/org/codice/ddf/registry/federationadmin/service/impl/FederationAdminServiceImpl.java
- catalog/spatial/registry/registry-federation-admin-service-impl/src/main/java/org/codice/ddf/registry/federationadmin/service/impl/RefreshRegistryEntries.java
- catalog/spatial/registry/registry-federation-admin-service-impl/src/test/java/org/codice/ddf/registry/federationadmin/service/impl/FederationAdminServiceImplTest.java
- catalog/spatial/registry/registry-federation-admin-service-impl/src/test/java/org/codice/ddf/registry/federationadmin/service/impl/IdentityNodeInitializationTest.java
- catalog/spatial/registry/registry-rest-endpoint/src/main/java/org/codice/ddf/registry/rest/endpoint/report/RegistryReportBuilder.java
- catalog/spatial/registry/registry-rest-endpoint/src/test/java/org/codice/ddf/registry/rest/endpoint/report/RegistryReportBuilderTest.java
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestRegistry.java
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/common/Library.java
The registry apps RegistryObjectMetacardType was updated to conform to the new metacard attribute taxonomy.
This means 
1) RegistryObjectMetacardType now only has registry specific attributes. For 'common' attributes we now use the names from the new attribute classes.
2) All registry specific attributes have been renamed to be `registry.<current-attribute-name>`
Exception to this is the transient attributes which is `registry.local.<current-attribute-name>`
3) The registry-api blueprint was built-up and now exposes the registry metatype as a service. 
4) The registry transformer/package converter no longer parses out the content type from the metacard and the content type is no longer used as a filter for evaluating registry metacards 
@clockard @gordocanchola @vinamartin @brianfelix …
> DDF-2382 Update the registry to use metacard attribute taxonomy

- catalog/spatial/registry/registry-api-impl/src/main/java/org/codice/ddf/registry/api/impl/RegistryStoreCleanupHandler.java
- catalog/spatial/registry/registry-api-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/spatial/registry/registry-api-impl/src/test/java/org/codice/ddf/registry/api/impl/RegistryStoreCleanupHandlerTest.java
- catalog/spatial/registry/registry-federation-admin-service-impl/src/main/java/org/codice/ddf/registry/federationadmin/service/impl/RegistryPublicationServiceImpl.java
- catalog/spatial/registry/registry-federation-admin-service-impl/src/test/java/org/codice/ddf/registry/federationadmin/service/impl/RegistryPublicationServiceImplTest.java
Fixes a bug with the registry store cleanup handler where the store reference can be removed before the cleanup logic can be run. 
Also adds a simple retry to publication updates
@mcalcote @vinamartin @tbatie 
@coyotesqrl
@figliold 
Bring up two instances of ddf with the registry running. Have one of the registries subscribe to the other. Verify that you get the other nodes information. Now remove the remote registry you just created. Verify that the node you received from the other registry has been removed.
DDF-2266
> DDF-2266 Fix registry store cleanup bugs

- catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/controller/SearchController.java
- catalog/ui/search-ui/search-endpoint/src/test/java/org/codice/ddf/ui/searchui/query/controller/SearchControllerTest.java
- catalog/ui/search-ui/standard/src/main/webapp/js/view/Progress.view.js
This change fixes 2 bugs in the processing of federated search results.
First, it fixes a threading bug in SearchController that was blocking results
from being returned to the UI. Code had been added to handle exceptions, but
that code wasn't running in its own thread. As a result, the error-checking
prevented the method from returning.
Second, it fixes a minor bug in the case when the local solr results are
empty and those results weren't being merged into the set of cached
results. This was preventing the progress bar from being updated correctly.
@roelens8 
@bdeining 
@pklinef
@stustison
1) install the bundle provided by the bug submitter (available here: https://groups.google.com/forum/#!topic/ddf-users/F_kKYMsiEzg)
2) Perform some queries with various numbers in the search box (10, …
> DDF-2297 Federated queries sometimes fail to return results

- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/view/Field.view.js
- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/view/NodeModal.view.js
- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/view/Segment.view.js
- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/less/styles.less
- catalog/spatial/registry/registry-federation-admin-service-impl/src/main/java/org/codice/ddf/registry/federationadmin/service/impl/IdentityNodeInitialization.java
- catalog/spatial/registry/registry-federation-admin-service-impl/src/test/java/org/codice/ddf/registry/federationadmin/service/impl/IdentityNodeInitializationTest.java
Previously, the default registry name would be `ddf.distribution` before being set by a user if the registry was selected at install. 
The name is now bound to the site name system property. 
The editable field is now disabled and I've grayed it out for clarity.
@djblue @clockard @brianfelix 
@figliold
@pklinef
Install a ddf and select the registry app to be installed during the installer process.
Change the site name to any other name using the installer. 
Verify that after restart, the name is the name chosen during the installer. Add additional local nodes and verify they can be renamed (the name is not grayed out). 
DDF-2461
> DDF-2461 Syncs registry name with site name

- distribution/test/itests/test-itests-common/src/test/java/ddf/common/test/ServiceManager.java
- distribution/test/itests/test-itests-common/src/test/java/ddf/common/test/ServiceManagerImpl.java
Changed start and stop feature methods used by the integration code to wait for the feature state to change before returning.
Also added a new method to wait for a list of bundles to be uninstalled.
@tbatie 
@oconnormi 
@figliold
@pklinef
Full build, including integration tests.
https://codice.atlassian.net/browse/DDF-2462
> DDF-2462: Start and stop feature utility methods used for integration tests do not wait when requested

- catalog/admin/admin-poller-service/pom.xml
- catalog/admin/admin-poller-service/src/main/java/org/codice/ddf/catalog/admin/poller/AdminPollerServiceBean.java
- catalog/admin/admin-poller-service/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/admin/admin-poller-service/src/main/resources/OSGI-INF/metatype/metatype.xml
- catalog/admin/admin-poller-service/src/test/groovy/org/codice/ddf/catalog/admin/poller/AdminPollerServiceBeanTest.groovy
- catalog/admin/admin-poller-service/src/test/java/org/codice/ddf/catalog/admin/poller/AdminPollerTest.java
- distribution/docs/src/main/resources/_contents/configuring-from-the-admin-console-contents.adoc
Backport of DDF-2455
@coyotesqrl
@shaundmorris 
1. Make sure Schematron Validation Services doesn't appear as an source configuration option in the Catalog UI upon first starting the system.
2. Confirm the Admin Poller Service modal works on the System tab of the Admin UI
3. Confirm Schematron's the default settings appear in the modal (see screenshot).
4. Add a few patterns (*csw*, *Csw*, *Federated*, *federated*) and restart ddf to confirm that adding to the filter list removes sources.
5. Since the modal has been acting up, re-install ddf and confirm the modal appears on the first click without having to refresh the page.
DDF-2455
> DDF-2455 SchematronValidationService incorrectly appears in sources

- catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/IngestCommand.java
Fixes bug where some records might not be ingested with no error logged if the zip file to be ingested contained more than `--batchsize` * `--multithreaded` metacards.
This also cleans up the threading logic, relying on a Phaser used as a CountUp/DownLatch instead of flags and Thread.sleeps().
This needs to be backported to 2.9.x but might require a slightly more complex cherrypick as some other changes have been introduced to master and not backported.
@bdeining @rzwiefel @tbatie 
@kcwire
@pklinef
- Full build/test run.
- Threading tests
- Get some metacards to be ingested by any transformer and put them into a directory. I would recommend at least 100.
- Ingest through the karaf command line (include the `-p` flag to speed the tests, passing various values for the `-b` (`--batchsize`) …
> DDF-2474 Fixes issue with ingesting a large zip file with more metacards than space in blocking queue.

- platform/admin/core/admin-core-logviewer/src/main/webapp/js/components/error-message/error-message.less
Fixes a small css typo that causes the logviewer's "Network Error" banner to display the wrong color.
@lessarderic
> DDF-2453: LogViewer Pause/Resume Polling

- .gitignore
- distribution/ddf/pom.xml
- libs/activities/pom.xml
- libs/checksum/pom.xml
- libs/common-system/pom.xml
- libs/notifications/pom.xml
- libs/platform-configuration-impl/pom.xml
- pom.xml
* Adds javadocs to release profile
* Adds sources to the release profile
* Ensures release profile is triggered during release
* Adds additional gitignores for maven
* Removes unnecessary maven-release-plugin configurations from child modules
@pklinef
@shaundmorris
* Run `mvn release:prepare -Dmaven.repo.local=/tmp/m2` this should create javadoc and source jars for all artifacts
Previously javadoc and source jars were not created automatically during a release
[DDF-2452](https://codice.atlassian.net/browse/DDF-2452)
> DDF-2452: Added javadoc and sources to the release profile

- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/model/Node.js
- catalog/spatial/registry/registry-common/src/main/java/org/codice/ddf/registry/common/metacard/RegistryObjectMetacardType.java
- catalog/spatial/registry/registry-ebrim-transformer/src/main/java/org/codice/ddf/registry/converter/RegistryPackageConverter.java
- catalog/spatial/registry/registry-ebrim-transformer/src/test/java/org/codice/ddf/registry/transformer/RegistryTransformerTest.java
- catalog/spatial/registry/registry-federation-admin-service-impl/src/main/java/org/codice/ddf/registry/federationadmin/service/impl/FederationAdminServiceImpl.java
- catalog/spatial/registry/registry-federation-admin-service-impl/src/main/java/org/codice/ddf/registry/federationadmin/service/impl/RefreshRegistryEntries.java
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestRegistry.java
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/common/Library.java
The registry apps RegistryObjectMetacardType was updated to match the changes to the new metacard attribute taxonomy that were made in the master branch, but are not fully ported to 2.9.x.
This means the constants were changed such that the branches' registry functionality will still be compatible between builds.
@clockard @gordocanchola @vinamartin @brianfelix @brendan-hofmann 
@pklinef 
@jlcsmith 
Install DDF, Start the Registry App and confirm the identity node is present in the local nodes tab. Confirm edits to the nodes are retained and that connections can still be made using the remote nodes tab.
This PR does not match the changes made in the ticket on the master branch, but does update the registry metacard fields to match the master changes for future …
> DDF-2382 - 2.9.X - Update Registry Metacard Attributes to reflect common metacard taxonomy changes

- platform/admin/core/admin-core-api/src/main/java/org/codice/ddf/ui/admin/api/impl/SystemPropertiesAdmin.java
- platform/admin/core/admin-core-api/src/test/java/org/codice/ddf/ui/admin/api/SystemPropertiesAdminTest.java
Updates the Admin UI so that the system.port is derived from the protocol selection and the port number entered for either HTTP or HTTPS port.
@lcrosenbu 
@peterhuffer 
@kcwire
@pklinef
Perform a build and install of DDF. Change the port and/or protocol in the Admin UI. Verify <install>/etc/system.properties has the correct value for property: org.codice.ddf.system.port
https://codice.atlassian.net/browse/DDF-2477
> DDF-2477: Admin UI no longer requires setting the system port. That is derived from the HTTP or HTTPS port and the selected default protocol.

- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/view/Registry.view.js
- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/less/styles.less
- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/templates/regenerateSourcesModal.handlebars
- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/templates/registryPage.handlebars
- catalog/spatial/registry/registry-federation-admin-api/src/main/java/org/codice/ddf/registry/federationadmin/internal/FederationAdminMBean.java
- catalog/spatial/registry/registry-federation-admin-impl/pom.xml
- catalog/spatial/registry/registry-federation-admin-impl/src/main/java/org/codice/ddf/registry/federationadmin/impl/FederationAdmin.java
- catalog/spatial/registry/registry-federation-admin-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/spatial/registry/registry-federation-admin-impl/src/test/java/org/codice/ddf/registry/federationadmin/impl/FederationAdminTest.java
- catalog/spatial/registry/registry-federation-admin-service/src/main/java/org/codice/ddf/registry/federationadmin/service/internal/RegistrySourceConfiguration.java
- catalog/spatial/registry/registry-source-configuration-handler/src/main/java/org/codice/ddf/registry/source/configuration/SourceConfigurationHandler.java
- catalog/spatial/registry/registry-source-configuration-handler/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/spatial/registry/registry-source-configuration-handler/src/test/java/org/codice/ddf/registry/source/configuration/SourceConfigurationHandlerTest.java
Adds a button to the registry Node Information tab to regenerate sources from the registry entries.
@brianfelix @andrewkfiedler 
@pklinef
@shaundmorris 
Bring up a ddf instance with registry installed.
Create a secondary local node with a new service with a csw binding.
Go to the sources tab and delete the source associated with the secondary node you just created.
On the Node Information tab click the 'Regenerate Sources' button and verify that the source has been recreated.
DDF-2454
Node Information screen with the 'Regenerate Sources' button in the upper right
Conformation dialog for operation.
> DDF-2454 Added ability to regenerate sources from registry nodes

- catalog/core/catalog-core-standardframework/pom.xml
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/CatalogFrameworkImpl.java
- catalog/core/catalog-core-standardframework/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/core/catalog-core-standardframework/src/main/resources/OSGI-INF/metatype/metatype.xml
- catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/impl/FanoutCatalogFrameworkTest.java
- distribution/test/itests/test-itests-common/src/test/java/ddf/common/test/catalog/CatalogIngest.java
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/CatalogBundle.java
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalog.java
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFanout.java
This ticket adds the ability for fanout to write to its local store. A blacklist is added to give the admin control over what metacard tags should be rejected while in fanout mode.
@coyotesqrl 
@pklinef 
DDF-2361
…nout is enabled
Fanout is changing to allow access to the local store. The fanout requests will be rejected if fanout is enabled and the request contains a metacard with a tag on the blacklist.
CatalogFrameWorkImpl.java
Adding a fanoutTagBlacklist that will be used to determine which catalog requests should be blocked.
Changing the tests for fanout flag to now check the blacklist
blueprint.xml
Updating catalogFrameworkImpl with metatype info and default values for fanoutProxyTagBlacklist and filterAdapter
metatype.xml
Adding fanoutTagBlackList
Adding fanoutProxyTagBlacklist
> DDF-2361 - (2.9.x) Enable fanout and ddf registry to be used at the same time in the same ddf instance

- catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/CatalogCommands.java
- catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/DumpCommand.java
- catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/IngestCommand.java
- catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/RemoveCommand.java
- catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/ReplicationCommand.java
- catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/SubjectCommands.java
- catalog/core/catalog-core-commands/src/test/java/org/codice/ddf/commands/catalog/TestDumpCommand.java
- catalog/core/catalog-core-commands/src/test/java/org/codice/ddf/commands/catalog/TestIngestCommand.java
- catalog/transformer/catalog-transformer-zip/src/main/java/org/codice/ddf/catalog/transformer/zip/ZipValidator.java
- catalog/transformer/catalog-transformer-zip/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/transformer/catalog-transformer-zip/src/test/java/org/codice/ddf/catalog/transformer/zip/TestZipValidator.java
Fixes bug where some records might not be ingested with no error logged if the zip file to be ingested contained more than `--batchsize` * `--multithreaded` metacards.
**This is a backport of [DDF-2474](https://github.com/codice/ddf/pull/1253) but also backports changes from [DDF-2112](https://github.com/codice/ddf/pull/779) and [DDF-2243](https://github.com/codice/ddf/pull/945). It also includes some log-level changes.**
This also cleans up the threading logic, relying on a Phaser used as a CountUp/DownLatch instead of flags and Thread.sleeps().
This needs to be backported to 2.9.x but might require a slightly more complex cherrypick as some other changes have been introduced to master and not backported.
@bdeining @rzwiefel @tbatie 
@kcwire
@pklinef
- Full build/test run.
- Threading …
> DDF-2474 Fixes issue with ingesting a large zip file with more metacards than space in blocking queue

- catalog/ui/search-ui/standard/src/main/webapp/js/view/Modal.js
- catalog/ui/search-ui/standard/src/main/webapp/js/view/ingest/IngestMenu.js
- catalog/ui/search-ui/standard/src/main/webapp/js/view/ingest/IngestModal.view.js
Fixes the Search UI file upload dialog so it can be reopened if its closed while resources are being uploaded.
@jrnorth
@azgoalie
@emanns95 
@ahoffer
@NGoss
@spearskw
@timothytierney
@shaundmorris 
@stustison
Open the file upload dialog and select two large files to upload. While the uploads are in progress, close the dialog using the x. Once the dialog has been closed, it cannot be re-opened.
This PR relates to: https://github.com/codice/ddf/pull/1268
> DDF-2480 Fixed upload dialog to reopen if closed during an upload

- catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/service/SearchService.java
Backport to 2.9.x
Original PR: https://github.com/codice/ddf/pull/1202
@jaymcnallie @dcruver
> DDF-2171 Performing a textual search with an empty value will now default to a wildcard search, when in the faceted search view (2.9.x)

- catalog/ui/search-ui/standard/src/main/webapp/js/view/Modal.js
- catalog/ui/search-ui/standard/src/main/webapp/js/view/ingest/IngestMenu.js
- catalog/ui/search-ui/standard/src/main/webapp/js/view/ingest/IngestModal.view.js
Fixes the Search UI file upload dialog so it can be reopened if its closed while resources are being uploaded.
@timothytierney
@jrnorth 
@spearskw 
@shaundmorris
@stustison
Open the file upload dialog and select two large files to upload. While the uploads are in progress, close the dialog using the x. Once the dialog has been closed, it cannot be re-opened.
> DDF-2480 (Backport) Fixed upload dialog to reopen if closed during an upload

- catalog/spatial/registry/registry-api-impl/src/main/java/org/codice/ddf/registry/api/impl/RegistryStoreImpl.java
- catalog/spatial/registry/registry-common/src/main/java/org/codice/ddf/registry/common/RegistryConstants.java
- catalog/spatial/registry/registry-publication-action-provider/src/main/java/org/codice/ddf/registry/publication/action/provider/RegistryPublicationActionProvider.java
- catalog/spatial/registry/registry-publication-action-provider/src/test/java/org/codice/ddf/registry/publication/action/provider/RegistryPublicationActionProviderTest.java
- catalog/spatial/registry/registry-report-action-provider/src/main/java/org/codice/ddf/registry/report/action/provider/RegistryReportActionProvider.java
- catalog/spatial/registry/registry-report-action-provider/src/test/java/org/codice/ddf/registry/report/action/provider/TestRegistryReportActionProvider.java
- catalog/spatial/registry/registry-source-configuration-handler/src/main/java/org/codice/ddf/registry/source/configuration/SourceConfigurationHandler.java
- catalog/spatial/registry/registry-source-configuration-handler/src/test/java/org/codice/ddf/registry/source/configuration/SourceConfigurationHandlerTest.java
Changes the key used to store registry id information in configuration files from the metacard metatype of registry.registry-id to just a constant of registry-id. The `.` in the name causes the property to be lost when passed to backbone UIs on the front end.
@mcalcote @gordocanchola 
@figliold
@shaundmorris
Install ddf with registry. 
Create a secondary local node with a service binding
Go to the sources tab and make a change to the source that was generated for the secondary local node
Update something on the secondary node (like description) and save it. 
Reload the sources tab and verify that there is still only the one entry without an id in the name
DDF-2382
> DDF-2382 Fix registry-id key used in configurations.

- catalog/ui/search-ui/standard/src/main/webapp/js/view/ingest/IngestModal.view.js
This PR fixes a bug where the Ingest Modal in the Standard Search UI initially showed `NaN%` instead of 0.
@lcrosenbu 
@jlcsmith
@kcwire
Build and Install DDF, ingest through the Standard Search UI and observe no `NaN%` when starting the uploads.
https://codice.atlassian.net/browse/DDF-2349
https://codice.atlassian.net/browse/DDF-2349
> DDF-2349 Fixed NaN on ingest modal

- catalog/core/catalog-core-standardframework/pom.xml
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/CatalogFrameworkImpl.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/CreateOperations.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/DeleteOperations.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/QueryOperations.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/UpdateOperations.java
- catalog/core/catalog-core-standardframework/src/main/resources/OSGI-INF/blueprint/delegate-operators.xml
- catalog/core/catalog-core-standardframework/src/main/resources/OSGI-INF/metatype/metatype.xml
- catalog/core/catalog-core-standardframework/src/test/groovy/ddf/catalog/impl/operations/QueryOperationsTest.groovy
- catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/impl/FanoutCatalogFrameworkTest.java
- distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/CatalogBundle.java
- distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/catalog/CatalogTestCommons.java
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFanout.java
This ticket adds the ability for fanout to write to its local store. A blacklist is added to give the admin control over what metacard tags should be rejected while in fanout mode.
@figliold  
@pklinef 
DDF-2361
Fanout is changing to allow access to the local store. The fanout requests will be rejected if fanout is enabled and the request contains a metacard with a tag on the blacklist.
CatalogFrameWorkImpl.java
Adding a fanoutTagBlackList that will be used to determine which catalog requests should be blocked.
Changing the tests for fanout flag to now check the blacklist
delegate-operators.xml (blueprint)
Updating cfQueryOps with metatype info and default values for fanoutProxyTagBlacklist
metatype.xml
Adding fanoutTagBlackList to Catalog Standard Framework
Adding fanoutProxyTagBlacklist …
> DDF-2361 - Enable fanout and ddf registry to be used at the same time in the same ddf instance

- catalog/catalog-app/src/main/resources/features.xml
- catalog/core/catalog-core-camelcomponent/src/main/java/ddf/camel/component/catalog/content/ContentComponentResolver.java
- catalog/core/catalog-core-directorymonitor/pom.xml
- catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/ContentDirectoryMonitor.java
- catalog/core/catalog-core-directorymonitor/src/test/java/org/codice/ddf/catalog/content/monitor/ContentDirectoryMonitorTest.java
CDMs now wait for the "content" CamelComponent before adding routes.
* Have the CDM retry adding routes for a given period of time.
* Wait for the content CamelComponent instead of recursively retrying on exceptions.
@shaundmorris 
@jlcsmith
@lessarderic 
@pklinef
* Ensure the PR passes a full build (hero)
* Setup a monitored directory and ensure content is still ingested after a system reboot
> DDF-2459: Content directory monitors now keep working after system restart

- catalog/catalog-app/src/main/resources/features.xml
- catalog/core/catalog-core-camelcomponent/src/main/java/ddf/camel/component/catalog/content/ContentComponentResolver.java
- catalog/core/catalog-core-directorymonitor/pom.xml
- catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/ContentDirectoryMonitor.java
- catalog/core/catalog-core-directorymonitor/src/test/java/org/codice/ddf/catalog/content/monitor/ContentDirectoryMonitorTest.java
Backports DDF-2459 for `2.9.x`
@shaundmorris
@lessarderic
@pklinef
Ensure content directory monitors keep ingesting files dropped into their directories after a system reboot. 
CDMs now wait for the "content" CamelComponent before adding routes.
Have the CDM retry adding routes for a given period of time.
Wait for the content CamelComponent instead of recursively retrying on exceptions.
Rework unit tests.
> DDF-2459: Content directory monitors now keep working after system restart (backport)

- catalog/ui/search-ui/standard/src/main/webapp/js/view/ingest/IngestModal.view.js
This PR fixes a bug where the Ingest Modal in the Standard Search UI initially showed `NaN%` instead of 0.
@lcrosenbu 
@jlcsmith
@kcwire
Build and Install DDF, ingest through the Standard Search UI and observe no `NaN%` when starting the uploads.
https://codice.atlassian.net/browse/DDF-2349
https://codice.atlassian.net/browse/DDF-2349
> (2.9.x) DDF-2349 Fixed NaN on ingest modal

- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/CreateOperations.java
This PR reorders the execution of applyAttributeOverrides so that they can additionally be applied to injectable attributes through the Content Directory Monitor
@lcrosenbu @peterhuffer 
@jlcsmith
@coyotesqrl 
Build and Install DDF, configure an injectable attribute, configure the Content Directory Monitor to override the value and observe the expected behavior
https://codice.atlassian.net/browse/DDF-2503
> DDF-2503 Reordered the execution of applyAttributeOverrides to run after injectAttributes

- catalog/transformer/catalog-transformer-xml/src/main/resources/OSGI-INF/metatype/metatype.xml
- distribution/docs/src/main/resources/_contents/_configuring/configuring-as-fanout-proxy-contents.adoc
- distribution/docs/src/main/resources/_contents/_draft-admin-contents/managing-admin-contents.adoc
- distribution/docs/src/main/resources/_contents/_draft-catalog-contents/managing-catalog-contents.adoc
- distribution/docs/src/main/resources/_contents/_draft-geowebcache-contents/managing-geowebcache-contents.adoc
- distribution/docs/src/main/resources/_contents/_draft-platform-contents/managing-platform-contents.adoc
- distribution/docs/src/main/resources/_contents/_tables/conf-MetricsReporting-table-contents.adoc
- distribution/docs/src/main/resources/_contents/_tables/conf-OpenSearchSource-table-contents.adoc
- distribution/docs/src/main/resources/_contents/_tables/conf-ddf.catalog.CatalogFrameworkImpl-table-contents.adoc
- distribution/docs/src/main/resources/_contents/_tables/conf-ddf.catalog.metacard.duplication.DuplicationValidator-table-contents.adoc
- distribution/docs/src/main/resources/_contents/_tables/conf-ddf.catalog.transformer.xml.XmlResponseQueueTransformer-table-contents.adoc
- distribution/docs/src/main/resources/_contents/_tables/conf-ddf.platform.scheduler.Command-table-contents.adoc
- distribution/docs/src/main/resources/_contents/_tables/conf-ddf.platform.ui.config-table-contents.adoc
- distribution/docs/src/main/resources/_contents/_tables/conf-ddf.services.schematron.SchematronValidationService-table-contents.adoc
- distribution/docs/src/main/resources/_contents/_tables/conf-ddf_Custom_Mime_Type_Resolver-table-contents.adoc
- distribution/docs/src/main/resources/_contents/_tables/conf-org.codice.admin.ui.configuration-table-contents.adoc
- distribution/docs/src/main/resources/_contents/_tables/conf-org.codice.ddf.admin.config.policy.AdminConfigPolicy-table-contents.adoc
- distribution/docs/src/main/resources/_contents/_tables/conf-org.codice.ddf.catalog.plugin.expiration.ExpirationDatePlugin-table-contents.adoc
- distribution/docs/src/main/resources/_contents/_tables/conf-org.codice.ddf.catalog.security.CatalogPolicy-table-contents.adoc
- distribution/docs/src/main/resources/_contents/_tables/conf-org.codice.ddf.catalog.security.policy.metacard.MetacardAttributeSecurityPolicyPlugin-table-contents.adoc
- distribution/docs/src/main/resources/_contents/_tables/conf-org.codice.ddf.catalog.security.policy.xml.XmlAttributeSecurityPolicyPlugin-table-contents.adoc
- distribution/docs/src/main/resources/_contents/_tables/conf-org.codice.ddf.distribution.landing-page.properties-table-contents.adoc
- distribution/docs/src/main/resources/_contents/_tables/conf-org.codice.ddf.persistence.internal.PersistentStoreImpl-table-contents.adoc
- distribution/docs/src/main/resources/_contents/_tables/conf-org.codice.ddf.platform.logging.LoggingService-table-contents.adoc
- distribution/docs/src/main/resources/_contents/_tables/conf-plugin.backup-table-contents.adoc
- distribution/docs/src/main/resources/_contents/_tables/org.codice.admin.ui.configuration-table-contents.adoc
- distribution/docs/src/main/resources/_contents/_tables/org.codice.ddf.admin.config.policy.AdminConfigPolicy-table-contents.adoc
- distribution/docs/src/main/resources/draft-documentation.adoc
- platform/admin/ui/src/main/resources/OSGI-INF/metatype/metatype.xml
Revises the current `Managing <application>` sections for the Admin, Catalog, GeoWebCache, and Platform Applications.
- Non-app-specific content has been moved to more general sections.
- Renamed sections from `Managing <app>` to `<App> Reference`
- Formatting standardized.
@spearskw @emanns95 @mweser 
@coyotesqrl
@pklinef
Review doc contents
Sub-task of DDF-2309; See PR https://github.com/codice/ddf/pull/1036
The changes here will not yet be visible in the published documentation. To view new version, open draft-documentation in either html or pdf in the docs target directory. [pdf version attached to this PR] Once all changes are integrated, the draft-documentation will supersede the current version.
https://codice.atlassian.net/browse/DDF-2395 …
> Ddf 2395 Update Application reference section

- catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/DuplicateCommands.java
- catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/MigrateCommand.java
- catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/ReplicateCommand.java
This PR adds `--from` and `--to` options to the Migrate Command to specify the providers, and it adds a `--list` option to list the available providers.
@bdeining @glenhein @peterhuffer 
@beyelerb
@kcwire
Add an external provider, and test that the `catalog:migrate` and the options work as expected when migrating from this new external provider to the `SolrHttpCatalogProvider`.
https://codice.atlassian.net/browse/DDF-2498
> DDF-2498 Added ability to specify source and target for Migrate Command

- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/model/Node.collection.js
- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/view/Registry.view.js
- catalog/spatial/registry/registry-source-configuration-handler/src/main/java/org/codice/ddf/registry/source/configuration/SourceConfigurationHandler.java
Sorts the order of entries that show up in the regenerate sources dialog and also keep the identity node from showing up in that list.
@vinamartin @gordocanchola @Lambeaux 
@kcwire
@stustison
@figliold 
Start up an instance and add some secondary nodes. Verify that when you click the 'Regenerate Sources' button that the resulting dialog shows the entries in alphabetical order and that the identity node is not in the list.
Based on feedback from sprint review and @mcalcote 
DDF-2354
> DDF-2454 Sort order of source regeneration entries in dialog and disallow identity node.

- catalog/transformer/catalog-transformer-xml/src/main/resources/OSGI-INF/blueprint/blueprint.xml
Uses the global pool instead of creating a new FJP for `XmlResponseQueueTransformer`.
As of Java 8, there is a common pool that can be used for FJ tasks. It should not be _overused_ in order to prevent pool contention, but this transformer does not have any tasks that run long enough to cause issues for other pool users.
@ahoffer @ryeats 
@lessarderic
@stustison
Build/test. Install DDF and ingest a record, then execute an opensearch query with output in xml.
Example: `https://localhost:8993/services/catalog/query?q=*&mr=10&format=xml`
N/A
DDF-1560
N/A
> DDF-1560 Updates the ForkJoinPool in XmResponseQueueTransformer to be the global pool.

- catalog/core/catalog-core-solr/pom.xml
- catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/DynamicSchemaResolver.java
- catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/SolrFilterDelegate.java
- catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/SolrMetacardClient.java
- catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/MockMetacard.java
- catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/TestSolrFilterDelegate.java
- catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/TestSolrProvider.java
- platform/solr/platform-solr-server-standalone/src/main/resources/solr/conf/schema.xml
* LatLonType is optimized for distance sorting unlike the
SpatialRecursivePrefixTreeFieldType.  Switched to LatLonType for
sorting of geometry attributes.  
* Can now sort by distance on any geometry field.
@brendan-hofmann @jrnorth @codice/solr 
@coyotesqrl 
@pklinef
Ingest quarter of a million or more metacards with locations.  Index a new metacard with a location to clear any spatial cache.  Do a spatial query and sort by distance.  Results should return in less than a second compared to before which could take minutes.
https://codice.atlassian.net/browse/DDF-2506
> DDF-2506 Use LatLonType for geometry sort keys

- catalog/spatial/registry/registry-api-impl/src/main/resources/OSGI-INF/metatype/metatype.xml
@jrnorth
@azgoalie
@emanns95 
@ahoffer
@NGoss
@spearskw
@shaundmorris 
@stustison
Open the Admin app, then the DDF Registry app and click on the Configuration Tab.  Click on the CSW Registry Store and view the "Password" field.  It should be blank (not a series of dots).
Enter in a password and notice the dots display.  Save the entry and then reopen it.  The password should now display dots as the password has a value.
Click on CSW Registry Store again for a new entry and the "Password" field should be blank.
> DDF-2513 (Backport) Fix password UI in CSW Registry Store

- catalog/spatial/registry/registry-api-impl/src/main/resources/OSGI-INF/metatype/metatype.xml
@jrnorth
@azgoalie
@emanns95 
@ahoffer
@NGoss
@spearskw
@shaundmorris 
@stustison
Open the Admin app, then the DDF Registry app and click on the Configuration Tab.  Click on the CSW Registry Store and view the "Password" field.  It should be blank (not a series of dots).
Enter in a password and notice the dots display.  Save the entry and then reopen it.  The password should now display dots as the password has a value.
Click on CSW Registry Store again for a new entry and the "Password" field should be blank.
…guration password field
> DDF-2513 Fix password UI in CSW Registry Store

- catalog/ui/search-ui/standard/src/main/webapp/templates/metacard.handlebars
This PR turns Resource Derived Download URLS into anchors for a better user experience
@glenhein @peterhuffer 
@jlcsmith
@stustison 
Build and Install DDF, ingest an image and observe anchors in Resource Derived Download URLs
https://codice.atlassian.net/browse/DDF-2499
> DDF-2499 Turned Resource Derived Download URLs into anchors in Standard Search

- platform/admin/admin-app/pom.xml
- platform/admin/admin-app/src/main/resources/features.xml
- platform/admin/modules/admin-modules-docs/pom.xml
- platform/admin/modules/admin-modules-docs/src/main/java/org/codice/ui/admin/docs/DocsModule.java
- platform/admin/modules/admin-modules-docs/src/main/java/org/codice/ui/admin/docs/DocsRequestSupplier.java
- platform/admin/modules/admin-modules-docs/src/main/java/org/codice/ui/admin/docs/DocsSparkApplication.java
- platform/admin/modules/admin-modules-docs/src/main/java/org/codice/ui/admin/docs/SparkServlet.java
- platform/admin/modules/admin-modules-docs/src/main/resources/404.html
- platform/admin/modules/admin-modules-docs/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- platform/admin/modules/admin-modules-docs/src/test/java/org/codice/ui/admin/docs/TestAdminDocsModule.java
- platform/admin/modules/pom.xml
Adds documentation to admin UI
@djblue @ricklarsen 
@coyotesqrl
@pklinef
Build the distribution with documentation, do a full install, make sure docs are displayed in the admin UI. Remove the documentation root folder and make sure "Documentation not found" message is displayed properly.
> DDF-2517: Display documentation in the admin UI

- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/index.html
- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/js/view/Field.view.js
- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/less/styles.less
- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/templates/field.handlebars
- distribution/docs/src/main/resources/_contents/_draft-registry-contents/managing-registry-contents.adoc
- distribution/docs/src/main/resources/_contents/_registry-contents/managing-registry-contents.adoc
Addes the ability to set autocomplete suggestions for registry fields.
@andrewkfiedler @mcalcote @ricklarsen 
@figliold 
@pklinef
After unzipping a ddf edit the etc/registry/registry-custom-slots.json and add the following for the securityLevel object  `"possibleValues": ["attribute1=val1","attribute2=val2","something=else"],`.
Install the ddf with the registry and go to the Node Information tab and open up the identity node.
Add a field to the security attributes and start typing 'a' and verify that you see suggestions from the list you entered earlier.
DDF-2534
Documentation section added
> DDF-2534 Add autocomplete/suggestion support to the registry node modal fields

- catalog/catalog-app/pom.xml
- catalog/catalog-app/src/main/resources/features.xml
- catalog/core/catalog-core-api/src/main/java/ddf/catalog/plugin/PreAuthorizationPlugin.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/FrameworkProperties.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/CreateOperations.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/DeleteOperations.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/QueryOperations.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/ResourceOperations.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/UpdateOperations.java
- catalog/core/catalog-core-standardframework/src/main/resources/OSGI-INF/blueprint/frameworkprops.xml
- catalog/core/catalog-core-standardframework/src/main/resources/OSGI-INF/blueprint/plugins.xml
- catalog/plugin/catalog-plugin-clientinfo/pom.xml
- catalog/plugin/catalog-plugin-clientinfo/src/main/java/org/codice/ddf/catalog/plugin/clientinfo/ClientInfoPlugin.java
- catalog/plugin/catalog-plugin-clientinfo/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/plugin/catalog-plugin-clientinfo/src/test/java/org/codice/ddf/catalog/plugin/clientinfo/ClientInfoPluginTest.java
- catalog/plugin/pom.xml
- platform/platform-app/pom.xml
- platform/platform-app/src/main/resources/features.xml
- platform/platform-filter-clientinfo/pom.xml
- platform/platform-filter-clientinfo/src/main/java/org/codice/ddf/platform/filter/clientinfo/ClientInfoFilter.java
- platform/platform-filter-clientinfo/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- platform/platform-filter-clientinfo/src/test/java/org/codice/ddf/platform/filter/clientinfo/impl/ClientInfoFilterTest.java
- platform/pom.xml
Adds client-specific information (from the javax.servlet API) to catalog framework request properties, using a servlet filter (_platform-filter-clientinfo_) and a `PreAuthorizationPlugin` (_catalog-plugin-clientinfo_) to ensure the information is available as early as possible in the processing chain. 
Expose client info within request properties using a `PreAuthorizationPlugin` and a servlet filter.
Client-specific information (e.g. IP address, hostname, etc) is needed for metacard enrichment.
* Added a PreAuthorizationPlugin extension point.
* Updated relevant catalog operations.
* Added a servlet filter to copy servlet request data into the ThreadContext.
* Added a PreAuthorizationPlugin implementation to copy client info from the ThreadContext to the catalog request properties.
* …
> DDF-2500: Expose client info within request properties using a PreAuthorizationPlugin and a servlet filter.

- catalog/ui/search-ui/standard/src/main/webapp/templates/metacard.handlebars
This PR turns Resource Derived Download URLS into anchors for a better user experience
@glenhein @peterhuffer 
@jlcsmith
@stustison 
Build and Install DDF, ingest an image and observe anchors in Resource Derived Download URLs
https://codice.atlassian.net/browse/DDF-2499
> (2.9.x) DDF-2499 Turned Resource Derived Download URLs into anchors in Standard Search

- distribution/docs/src/main/resources/_contents/running-contents.adoc
This PR fixes a problem with the documentation that was described in 
ddf-2360.  There were undocumented environment vars that were required to run the ddf as a service .
Also removed a reference to PermGen memory (since it is no longer used in the now required JDK 8)
Also removed some quotation marks around an env var prevented proper evaluation of a path.
@ricklarsen @oconnormi 
@shaundmorris
Review documentation.  
Install the DDF as a service on Linux.  Make sure it works.
Tested Environment:  Centos7 standard installation with oracle JDK 8.
ddf-2360
Insert missing environment vars needed to run the ddf as a linux service
> DDF-2360 Updated documentation to reflect move to JDK 8 and to

- CHANGES.md
- catalog/ui/search-ui/standard/src/main/webapp/templates/metacard.handlebars
Some fields in the Search UI weren't correctly escaping some characters. This PR updates the metacard.handlebars template to properly escape the strings. 
I'll be adding some test coverage to this, however, just wanted to get a preliminary review up to see if this seems like the correct solution. If you know of anywhere else where we are using `safeString` in our templates, please let me know. 
@garrettfreibott @andrewkfiedler @djblue @brianfelix 
@pklinef
@stustison
[xss-check-metacard.txt](https://github.com/codice/ddf/files/527626/xss-check-metacard.txt)
Change this file to a `.xml` file and then ingest. 
Execute a search and make sure the search UI has escaped the metacard contents. 
https://codice.atlassian.net/browse/DDF-2538
> DDF-2538: Properly escapes strings in the metacard.handlebars

- PULL_REQUEST_TEMPLATE
Updates the pull request template to make component team tagging more accessible to people opening PRs.
@tbatie @djblue 
@coyotesqrl
@shaundmorris 
This allows the person opening the PR to easily see a component team's members and tag an appropriate component team reviewer.
[DDF-2536](https://codice.atlassian.net/browse/)
> DDF-2536 Add component team links to PR template

- catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/CqlCommands.java
- distribution/docs/src/main/resources/_contents/running-contents.adoc
During a refactor and extension of functionality, the `DumpCommand` was made to extend a new `CqlCommands` base class, giving it additional query flexibility. That change duplicated the `-t` alias for a command argument. This changes the alias for the `--temporal` argument to be `-dt` so it will not conflict with the `--transformer` alias.
@emmberk @brendan-hofmann  …
> DDF-2515 Deduplicates command argument alias.

- catalog/admin/module/catalog-admin-module-sources/src/main/webapp/less/styles.less
- catalog/admin/module/catalog-admin-module-sources/src/main/webapp/templates/configuration/textTypeList.handlebars
Fixes formatting on Admin UI source editor fields.
@bdeining 
@glenhein 
@peterhuffer 
@coyotesqrl
@lessarderic
1. Run instance of DDF 
2. Verify when adding source to DDF-Catalog that all textboxes have the same width
Before:
After:
> DDF-1702 Fix formatting on Admin UI source editor fields

- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFederation.java
Attempts to shut down this feature appear to be thwarted by the karaf dependency graph; as it is turned on by default, it should be left turned on for all itests to ensure there are no conflicts caused by it.
@jrnorth @brendan-hofmann 
@lessarderic …
> DDF-2545 Removes itest start/stop of catalog-plugin-metacard-validation feature

- catalog/catalog-app/pom.xml
- catalog/catalog-app/src/main/resources/features.xml
- catalog/core/catalog-core-metacardtype/pom.xml
- catalog/core/catalog-core-metacardtype/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/core/pom.xml
- catalog/transformer/catalog-transformer-common/src/main/java/ddf/catalog/transformer/common/tika/MetacardCreator.java
- catalog/transformer/catalog-transformer-common/src/test/java/ddf/catalog/transformer/common/tika/MetacardCreatorTest.java
- catalog/transformer/catalog-transformer-pptx/src/test/java/ddf/catalog/transformer/input/pptx/PptxInputTransformerTest.java
- catalog/transformer/catalog-transformer-tika-input/src/main/java/ddf/catalog/transformer/input/tika/TikaInputTransformer.java
- catalog/transformer/catalog-transformer-tika-input/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/transformer/catalog-transformer-tika-input/src/test/java/ddf/catalog/transformer/input/tika/TikaInputTransformerTest.java
- catalog/transformer/catalog-transformer-video-input/src/main/java/ddf/catalog/transformer/input/video/VideoInputTransformer.java
- catalog/transformer/catalog-transformer-video-input/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/transformer/catalog-transformer-video-input/src/test/java/ddf/catalog/transformer/input/video/VideoInputTransformerTest.java
DDF-2516 Updated Tika, Video, and Pptx InputTransformers to use new taxonomy
- Replaced usages of Basic MetacardType in tika related transformers
- Replaced uage of Basic MetacardType in MetacardCreator
- Made MetacardType an argument in MetacardCreator
@lcrosenbu @rzwiefel @bdeining @coyotesqrl 
@kcwire 
1) Ingest video, pptx, and jpeg (or other formats supported by the tika transformer)
2) Verify attributes from the new taxonomy (like metacard.created/modified) are present in ingested metacards
> DDF-2516 Updated Tika, Video, and Pptx InputTransformers to use new taxonomy

- catalog/admin/admin-poller-service/pom.xml
- catalog/spatial/geocoding/spatial-geocoding-localsearch/pom.xml
- catalog/spatial/geocoding/spatial-geocoding-plugin/pom.xml
- catalog/spatial/geocoding/spatial-geocoding-websearch/pom.xml
- distribution/docs/pom.xml
- distribution/test/itests/pom.xml
- pom.xml
Updates ddf.version to project.version for DDF modules in order for the mvn release plugin to run correctly.
@bdeining 
@peterhuffer 
@oconnormi 
@coyotesqrl
@pklinef
Run:
mvn release:prepare
Once you choose a version number for the release and the pom files are updated the release will start building. Previously it would fail while updating pom files.
https://codice.atlassian.net/browse/DDF-2549
> DDF-2549: DDF projects should reference project.version for mvn release plugin

- distribution/docs/src/main/resources/_contents/extending-contents.adoc
fixes maven property in example pom file that should not resolve to a local path. 
@coyotesqrl @kcwire @shaundmorris 
@coyotesqrl
@kcwire
@shaundmorris
`Creating a KAR file` section of Extending documentation should have `${project.build.directory} instead of local users home directory.
[DDF-2553](https://codice.atlassian.net/browse/DDF-2553)
> DDF-2553 fixed example maven property in docs

- libs/mpeg-transport-stream/pom.xml
- libs/mpeg-transport-stream/src/main/java/org/codice/ddf/libs/mpeg/transport/MTSValidPacketIterator.java
- libs/mpeg-transport-stream/src/main/java/org/codice/ddf/libs/mpeg/transport/MpegTransportStreamMetadataExtractor.java
- libs/mpeg-transport-stream/src/test/java/org/codice/ddf/libs/mpeg/transport/MTSValidPacketIteratorTest.java
Provides the **first** part of a two-part fix to allow certain cases of mpegts video clips to ingest without error. This addresses the exception thrown by a third party library. 
@bdeining 
@glenhein 
@jrnorth 
@jlcsmith
@kcwire
In conjunction with [CAL PR 173](https://github.com/codice/alliance/pull/173); ingest video products, both good ones and some with bad packets (unexpected packet length - not necessarily corrupt data), and ensure the products successfully ingest and appear during search. Since security markings might be ignored, be sure to login to a profile that has access to system high. 
Also, a full build should pass with all necessary components. Pay extra attention to see if anything out of the ordinary has changed as a result of …
> DDF-2540: Mpegts clips with incomplete packets can now be ingested

- catalog/spatial/registry/registry-schema-bindings/pom.xml
- catalog/spatial/registry/registry-schema-bindings/src/main/java/org/codice/ddf/registry/schemabindings/helper/RegistryPackageTypeHelper.java
- catalog/spatial/registry/registry-schema-bindings/src/test/java/org/codice/ddf/registry/schemabindings/helper/RegistryPackageTypeHelperTest.java
- catalog/spatial/registry/registry-schema-bindings/src/test/resources/csw-full-registry-package.xml
This PR adds methods to the RegistryPackageTypeHelper that get objects associated by id.
@figliold 
@shaundmorris 
DDF-2518
Adding methods to get associated objects by sourceObjectId
Adding tests and updating test xml file
> DDF-2518 - Add methods to RegistryPackageTypeHelper that get objects by association

- catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswQueryFactory.java
- catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/mappings/CswRecordMapperFilterVisitor.java
- catalog/spatial/csw/spatial-csw-endpoint/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/spatial/csw/spatial-csw-endpoint/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswQueryFactoryTest.java
- catalog/spatial/csw/spatial-csw-endpoint/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/mappings/TestCswRecordMapperFilterVisitor.java
- catalog/spatial/csw/spatial-csw-source-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/CswFilterDelegate.java
- catalog/spatial/csw/spatial-csw-source-common/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/TestCswFilterDelegate.java
- distribution/test/itests/test-itests-common/src/main/resources/csw-query.xml
- distribution/test/itests/test-itests-common/src/main/resources/xml/record/testNumerical.xml
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalog.java
CSW numerical queries were getting no results due to being rejected thanks to a default matchcase of "false". Now numerical queries will default to true.
@jrnorth 
@coyotesqrl
@kcwire
Full build and ingest a metacard that will have a numerical attribute. Confirm that a refined search over a CSW endpoint on that numerical attribute gets results.
> DDF-2507 CSW matchcase will now be ignored for non-string queries

- catalog/transformer/catalog-transformer-streaming-impl/pom.xml
- catalog/transformer/catalog-transformer-streaming-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/transformer/catalog-transformer-streaming-impl/src/test/java/org/codice/ddf/transformer/xml/streaming/impl/TestXmlInputTransformer.java
- catalog/transformer/catalog-transformer-streaming-lib/pom.xml
- catalog/transformer/catalog-transformer-streaming-lib/src/main/java/org/codice/ddf/transformer/xml/streaming/lib/MetacardTypeRegister.java
- catalog/transformer/catalog-transformer-streaming-lib/src/main/java/org/codice/ddf/transformer/xml/streaming/lib/XmlInputTransformer.java
- catalog/transformer/catalog-transformer-streaming-lib/src/test/java/org/codice/ddf/transformer/xml/streaming/lib/TestGenericXmlLib.java
- catalog/transformer/catalog-transformer-streaming-lib/src/test/java/org/codice/ddf/transformer/xml/streaming/lib/TestMetacardTypeRegister.java
The attributes for metacards created using the XmlInputTransformer do not register the MetacardType Attributes. These attributes are now registered.
@jrnorth 
@coyotesqrl
@kcwire
Full build and ingest xml data with a numerical field. Check that the field can be searched on.
> DDF-2507 Added MetacardType attribute registration to XmlInputTransformer

- platform/platform-app/src/main/resources/DDF_Custom_Mime_Type_Resolver.nitf.config
Adds support to file extensions beyond ".nitf" to ".r0" to ".r7". Enables extracting metadata from such files with such extensions.
@troymohl @bdeining @peterhuffer @emmberk  
@coyotesqrl
@jlcsmith 
1. Run instance of DDF
2. Attempt ingestion of sample .r5 file in search UI
3. If metadata extracted (no error at upload), then it is successful.
> DDF-2566 Add File Extensions to NITF Content Resolver

- distribution/test/itests/README.md
- distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/AbstractIntegrationTest.java
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFederation.java
Added the ability to mark specific unit tests as unstable and be able to enable or disable them using a system property.
Updated the README.md file to include this new flag.
Also marked `TestFederation.testAsyncDownloadActionPresentUsingCometDClient()` as unstable until the root cause of the intermittent failures is addressed in a follow on PR.
@tbatie 
@coyotesqrl
@pklinef 
Run integration tests with and without the `-DincludeUnstableTests=true` flag and make sure the unstable test is ran or skipped.
[DDF-2581](https://codice.atlassian.net/browse/DDF-2581)
> DDF-2581: TestFederation testAsyncDownloadActionPresentUsingCometDClient fails intermittently

- CHANGES.md
- platform/security/rest/security-rest-cxfwrapper/pom.xml
- platform/security/rest/security-rest-cxfwrapper/src/main/java/org/codice/ddf/cxf/SecureCxfClientFactory.java
- platform/security/rest/security-rest-cxfwrapper/src/test/java/org/codice/ddf/cxf/SecureCxfClientFactoryTest.java
This PR fixes an issue where the CSW source would fail to resolve the default URIs.
@brendan-hofmann @ahoffer @timothytierney
@shaundmorris
Build DDF and create a new CSW source in the catalog, verify that the URI resolves and no exceptions are thrown in the log.
[DDF-2557](https://codice.atlassian.net/browse/DDF-2557)
Added a call to PropertyResolver.resolveProperties to parse out
and resolve any system properties which may be in the endpointUrl passed
to the SecureCxfClientFactory.
> DDF-2557 Resolve system properties in endpoint url

- catalog/plugin/catalog-plugin-metacardingest-network/pom.xml
- catalog/plugin/catalog-plugin-metacardingest-network/src/main/java/org/codice/ddf/catalog/plugin/metacard/util/KeyValueParser.java
- catalog/plugin/catalog-plugin-metacardingest-network/src/test/java/org/codice/ddf/catalog/plugin/metacard/util/KeyValueParserTest.java
- catalog/plugin/pom.xml
Provides a helper class for the core ticket. This one in particular is for parsing strings of the form `key = value`. 
If context is desired for how this will be used, see the [massive, feature complete PR](https://github.com/codice/ddf/pull/1353) for all the code. 
@lessarderic 
@figliold 
@shaundmorris 
@brjeter 
@pklinef 
@stustison
If unit tests pass, along with the full build, this is sufficient for now. 
This is a small piece of a much bigger change-set that will allow admins to add attributes to metacards based on the originating IP, hostname, scheme, or context path. 
[DDF-2502](https://codice.atlassian.net/browse/DDF-2502)
> DDF-2502: Add a key-value parser for expressing new attributes to be added on metacards

- catalog/core/catalog-core-contentresourcereader/src/main/java/org/codice/ddf/catalog/content/resource/reader/DerivedContentActionProvider.java
- catalog/core/catalog-core-contentresourcereader/src/test/java/org/codice/ddf/catalog/content/resource/reader/DerivedContentActionProviderTest.java
Custom checking on derived resource URI for remote resources, which are not formatted the same as local resources. Fixes issue where actions display a URL as the action title, due to failure of URI parsing.
@bdeining @dcruver @glenhein 
@coyotesqrl
@jlcsmith
- This bug presented itself originally in Alliance. For testing, build and run the latest Alliance on top of this version of DDF. 
- Configure a CSW loopback source under `DDF Spatial` --> `CSW Specification Profile Federated Source` to mimic a remote source. 
-- Add Source ID name
-- Change CSW URL to local:   `https://localhost:8993/services/csw`
-- Change “Output Schema” to:    `urn:catalog:metacard`
- Ingest a NITF formatted file, then perform a search to find the ingested file.
- …
> DDF-2582 Derived Resource Action Titles

- platform/util/platform-util/src/main/java/org/codice/ddf/platform/util/XMLUtils.java
- platform/util/platform-util/src/test/java/org/codice/ddf/platform/util/XMLUtilsTest.java
There is a lot of boilerplate code setting up an XML parser, writing a loop to catch events, and handling checked errors. This PR adds a public method that accepts a function and an instance of a new inner class. Developers who create new modules that require XML parsing can make use of this method.
@brendan-hofmann @tbatie @mweser @AzGoalie 
@coyotesqrl
@pklinef
There are unit tests for the changes in XMLUtilsTest class
- [N/A ] Documentation Updated
- [ N/A] Change Log Updated
- [ Yes] Update / Add Unit Tests
- [ N/A] Update / Add Integration Tests
> DDF-2578 Add API to XMLUtils class

- catalog/spatial/wfs/1.0.0/spatial-wfs-v1_0_0-common/src/test/java/org/codice/ddf/spatial/ogc/wfs/v1_0_0/catalog/common/FeatureMetacardTypeTest.java
- catalog/spatial/wfs/1.0.0/spatial-wfs-v1_0_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v1_0_0/catalog/source/TestWfsSource.java
- catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-common/src/test/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/common/FeatureMetacardTypeTest.java
- catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-converter/src/test/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/converter/impl/TestGenericFeatureConverter.java
- catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/source/WfsSource.java
- catalog/spatial/wfs/pom.xml
- catalog/spatial/wfs/spatial-wfs-common/src/main/java/org/codice/ddf/spatial/ogc/wfs/catalog/common/FeatureMetacardType.java
- catalog/spatial/wfs/spatial-wfs-converter/src/main/java/org/codice/ddf/spatial/ogc/wfs/catalog/converter/impl/AbstractFeatureConverter.java
- Adds taxonomy attributes into Feature MetacardTypes
- Adds ext. prefix to all WFS Feature specific attributes
@glenhein @mweser @emmberk @brjeter 
@kcwire
@lessarderic
Full build.
Connect to a WFS source and verify that non normalized attributes are prefixed with `ext.`
> DDF-2560: Update WFS Feature MetacardType to use taxonomy

- catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/ContentDirectoryMonitor.java
- catalog/core/catalog-core-directorymonitor/src/test/java/org/codice/ddf/catalog/content/monitor/ContentDirectoryMonitorTest.java
This PR adds a readLock to Camel Routes in the Content Directory Monitor so large files can be ingested properly.
@lcrosenbu @brendan-hofmann 
@jlcsmith
@kcwire
Build / Install / Configure CDM / Ingest Large File / Observe Correct Behavior
[DDF-2594](https://codice.atlassian.net/browse/DDF-2594)
> DDF-2594 Added readLock to content directory monitor Camel routes

- catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/ContentDirectoryMonitor.java
- catalog/core/catalog-core-directorymonitor/src/test/java/org/codice/ddf/catalog/content/monitor/ContentDirectoryMonitorTest.java
This PR adds a readLock to Camel Routes in the Content Directory Monitor so large files can be ingested properly.
@lcrosenbu @brendan-hofmann 
@jlcsmith
@kcwire
Build / Install / Configure CDM / Ingest Large File / Observe Correct Behavior
[DDF-2594](https://codice.atlassian.net/browse/DDF-2594)
> (2.9.x) DDF-2594 Added readLock to content directory monitor Camel routes

- CHANGES.md
- platform/security/rest/security-rest-cxfwrapper/pom.xml
- platform/security/rest/security-rest-cxfwrapper/src/main/java/org/codice/ddf/cxf/SecureCxfClientFactory.java
- platform/security/rest/security-rest-cxfwrapper/src/test/java/org/codice/ddf/cxf/SecureCxfClientFactoryTest.java
This PR fixes an issue where the CSW source would fail to resolve the default URIs.
@brendan-hofmann @ahoffer @timothytierney
@jlcsmith 
@shaundmorris
Build DDF and create a new CSW source in the catalog, verify that the URI resolves and no exceptions are thrown in the log.
[DDF-2557](https://codice.atlassian.net/browse/DDF-2557)
Added a call to PropertyResolver.resolveProperties to parse out
and resolve any system properties which may be in the endpointUrl passed
to the SecureCxfClientFactory.
> (2.9.x) DDF-2557 Resolve system properties in endpoint url

- catalog/plugin/catalog-plugin-metacardingest-network/src/main/java/org/codice/ddf/catalog/plugin/metacard/util/AttributeFactory.java
- catalog/plugin/catalog-plugin-metacardingest-network/src/main/java/org/codice/ddf/catalog/plugin/metacard/util/MetacardServices.java
- catalog/plugin/catalog-plugin-metacardingest-network/src/test/java/org/codice/ddf/catalog/plugin/metacard/util/AttributeFactoryTest.java
- catalog/plugin/catalog-plugin-metacardingest-network/src/test/java/org/codice/ddf/catalog/plugin/metacard/util/MetacardServicesTest.java
Provides a helper class for the core ticket. This one in particular is for adding attributes to metacards, performing correct attribute processing from string values, and iterating over the system's published `MetacardType`s. 
Attributes already set are not overwritten.
If context is desired for how this will be used, see the [massive, feature complete PR](https://github.com/codice/ddf/pull/1353) for all the code. 
@lessarderic 
@figliold 
@shaundmorris 
@brjeter 
@pklinef 
@stustison
If unit tests pass, along with the full build, this is sufficient for now. 
This is a small piece of a much bigger change-set that will allow admins to add attributes to metacards based on the originating IP, hostname, scheme, or context path. …
> DDF-2502: Added an AttributeHelper for creating new attributes on metacards

- catalog/rest/catalog-rest-endpoint/src/main/java/org/codice/ddf/endpoints/rest/RESTEndpoint.java
This PR adds a catch for DataUsageLimitExceededException so a client knows why their download failed.
@lcrosenbu @jrnorth   
@jlcsmith
@lessarderic 
Build DDF Development, Ingest a resource, Download the resource, Set the Usage Limit for the current user to a small number, Attempt to Download again and observe the error message.
https://codice.atlassian.net/browse/DDF-2273
https://codice.atlassian.net/browse/DDF-2273
> (2.9.x) DDF-2273 Added catch for DataUsageLimitExceededException in REST endpoint

- catalog/ui/search-ui/standard/src/main/doc/_contents/help-contents.adoc
removes dead image links from `HELP` docs in search UI
@mcalcote @Lambeaux @jrnorth 
@pklinef
@shaundmorris
Verify `Help` docs
[DDF-2593](https://codice.atlassian.net/browse/DDF-2593)
> Ddf 2593 Remove old screenshots from Search UI "Help" documentation

- distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/AdminConfig.java
- distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/CatalogBundle.java
- distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/ServiceManager.java
- distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/ServiceManagerImpl.java
- Raises the default level for printing inactive bundles to ERROR
- Logs any failed config files from the etc directory that do not start in time
- Adds printing of inactive bundles to many more of the failure condition states, as failed bundles are a likely underlying cause
@mweser @vinamartin @emanns95 
N/A
@lessarderic
@shaundmorris
Intentionally breaking a bundle so it cannot resolve and then running an itest that relies on that bundle would trigger the logging of inactive bundles.
Creating a configuration file that does not deploy would trigger the logging of unstarted/remaining config files, followed by the logging of inactive bundles.
For my testing, I ran an itest through the debugger in order to force some of the failure conditions - it is trivial to run through the …
> DDF-2598 - Improves and increases logging during exam setup for itests.

- distribution/test/itests/test-itests-common/src/test/java/ddf/common/test/AdminConfig.java
- distribution/test/itests/test-itests-common/src/test/java/ddf/common/test/ServiceManager.java
- distribution/test/itests/test-itests-common/src/test/java/ddf/common/test/ServiceManagerImpl.java
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/CatalogBundle.java
- Raises the default level for printing inactive bundles to ERROR
- Logs any failed config files from the etc directory that do not start in time
- Adds printing of inactive bundles to many more of the failure condition states, as failed bundles are a likely underlying cause
@mweser @vinamartin @emanns95 
N/A
@lessarderic
@shaundmorris
Intentionally breaking a bundle so it cannot resolve and then running an itest that relies on that bundle would trigger the logging of inactive bundles.
Creating a configuration file that does not deploy would trigger the logging of unstarted/remaining config files, followed by the logging of inactive bundles.
For my testing, I ran an itest through the debugger in order to force some of the failure conditions - it is trivial to run through the …
> DDF-2598 - (2.9.x) Improves and increases logging during exam setup for itests

- catalog/ui/search-ui/standard/src/main/webapp/js/HandlebarsHelpers.js
- catalog/ui/search-ui/standard/src/main/webapp/templates/metacard.handlebars
Enable multi-valued url attribute links in search ui
@brendan-hofmann @andrewkfiedler 
@coyotesqrl
@pklinef
Verify multi-valued url attributes show up as links
https://codice.atlassian.net/browse/DDF-2599
> DDF-2599 Enable multi-valued url attribute links in search ui

- catalog/spatial/registry/registry-publication-update-handler/src/main/java/org/codice/ddf/registry/publication/RegistryPublicationHandler.java
- catalog/spatial/registry/registry-publication-update-handler/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/spatial/registry/registry-publication-update-handler/src/test/java/org/codice/ddf/registry/publication/RegistryPublicationHandlerTest.java
When updates to local nodes occur, sometimes the changes don't get propagated to published locations. The event handler that processes the update has to query the catalog for the changed metacard but the update to the metacard hasn't been persisted yet. This PR adds a delay to the publication update to fix this problem.
@gordocanchola @spearskw 
@figliold
@shaundmorris
Verify publication updates work.
DDF-2591
> DDF-2591 Added delay to publication updates.

- platform/security/sts/security-sts-ldapclaimshandler/src/main/java/ddf/security/sts/claimsHandler/AttributeMapLoader.java
- platform/security/sts/security-sts-ldapclaimshandler/src/main/java/ddf/security/sts/claimsHandler/ClaimsHandlerManager.java
- platform/security/sts/security-sts-ldapclaimshandler/src/main/java/ddf/security/sts/claimsHandler/LdapClaimsHandler.java
- platform/security/sts/security-sts-ldapclaimshandler/src/main/java/ddf/security/sts/claimsHandler/RoleClaimsHandler.java
- platform/security/sts/security-sts-ldapclaimshandler/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- platform/security/sts/security-sts-ldapclaimshandler/src/main/resources/OSGI-INF/metatype/metatype.xml
- platform/security/sts/security-sts-ldapclaimshandler/src/test/java/ddf/security/sts/claimsHandler/AttributeMapLoaderTest.java
- platform/security/sts/security-sts-ldapclaimshandler/src/test/java/ddf/security/sts/claimsHandler/ClaimsHandlerManagerTest.java
Adds a config option to the LDAP claims handlers to allow an admin to override user cert DNs with the specified base user DN
@pklinef @tbatie @adimka 
@coyotesqrl
@stustison
> DDF-2602 allow for a user cert dn to be overridden

- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/templates/field.handlebars
The latitude and longitude of remote repositories should not be editable locally.
@clockard @mcalcote 
@mcalcote 
@lessarderic
@shaundmorris
Build, unzip, and start DDF.
Install the registry application.
Add a remote repository.
View the node information of the remote repository.
Latitude and longitude attributes should be read-only
https://codice.atlassian.net/browse/DDF-2604
- [N/A] Change Log Updated
> DDF-2604 Latitude and Longitude attributes should not be editable

- dependency-check-maven-config.xml
- platform/solr/platform-solr-server-standalone/dependency-check-maven-config.xml
Suppresses the OWASP warning for this vulnerability since our project does not use the Java class that has the vulnerabilty.
@lessarderic @shaundmorris @Lambeaux 
@lessarderic
@shaundmorris 
Run a successful build with the owasp profile `mvn clean instal -Powasp`
[DDF-2590](https://codice.atlassian.net/browse/DDF-2590)
> DDF-2590: Suppressing OWASP warning because security vulnerability does not exist

- distribution/ddf-common/src/main/resources/etc/system.properties
Creates two fields in system.properties denoting the locale. This is useful for future cases where a string comparison may rely on a locale's capitalization standards to avoid unpredictable character behaviours. 
DDF-2585
@ahoffer @emanns95 @bdeining  
@coyotesqrl
@shaundmorris 
If it builds, it is good.
> DDF-2585 Add locale to system.properties

- dependency-check-maven-config.xml
- platform/solr/platform-solr-server-standalone/dependency-check-maven-config.xml
Suppresses the OWASP warning for this vulnerability since our project does not use the Java class that has the vulnerabilty.
@lessarderic @shaundmorris @Lambeaux
@lessarderic
@shaundmorris 
Run a successful build with the owasp profile `mvn clean install -Powasp`
[DDF-2590](https://codice.atlassian.net/browse/DDF-2590)
> [2.9.x]DDF-2590: Suppressing OWASP warning because security vulnerability does not exist

- distribution/test/itests/test-itests-dependencies-app/src/main/filtered-resources/features.xml
- platform/admin/core/admin-core-appservice/src/main/java/org/codice/ddf/admin/application/service/impl/ApplicationImpl.java
- platform/admin/core/admin-core-appservice/src/test/java/org/codice/ddf/admin/application/service/impl/ApplicationImplTest.java
Stops printing the log entry "Error occured while trying to parse information for application. Application created but may have missing information." Problem in string parsing routines that expected the format "xml-specs-api-2.5.0". Names like "test-dependencies" caused the error.
New behavior tolerates both formats.
New behavior exposes exception if repository cannot be loaded. Repository methods getName(), getFeatures(), both attempt to load the repository.
Updates two features.xml files. Names conform to expectations.
New behavior throws exception if name cannot be parsed unambiguously.
@clockard @brendan-hofmann @vinamartin @pklinef 
@pklinef
@shaundmorris
The hero build should NOT contains the log entry "Error …
> DDF-2596 Reduce number of log entries by ApplicationImpl

- platform/admin/core/admin-core-appservice/src/main/java/org/codice/ddf/admin/application/service/impl/ApplicationFileInstaller.java
Adds protections against DTD entity expansion vulnerabilities by setting features in new instances of DocumentBuilderFactory. Disables `load-dtd-grammar` and `load-external-dtd`.
Backport of https://github.com/codice/ddf/pull/1450
@ahoffer @emanns95 @spearskw @brendan-hofmann 
@coyotesqrl
@stustison
Ticket does not touch any tests, so a normal build should suffice.
Flagged issue from Fortify static analysis.
[](https://codice.atlassian.net/browse/DDF-2616)
> DDF-2616 Protect against DTD and entity expansion

- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/CatalogFrameworkImpl.java
Fixes the logic to retrieve the `Subject` using `SecurityUtils` since the `SecurityPlugin` has not processed and set it on the `CreateRequest`'s properties yet. This way, the Point of Contact attribute is set on the metacard correctly.
@lessarderic @Lambeaux @shaundmorris  
@coyotesqrl 
@stustison
- Run a full build.
- Deploy DDF and ingest a product. Verify the associated metacard's Point of Contact is set.
[DDF-2630](https://codice.atlassian.net/browse/DDF-2630)
> [2.9.x]DDF-2630: Adding logic to retrieve the Subject correctly so that Point of Contact is actually set on the metacard.

- platform/persistence/platform-persistence-core-api/src/main/java/org/codice/ddf/persistence/PersistentItem.java
- platform/persistence/platform-persistence-core-impl/src/main/java/org/codice/ddf/persistence/internal/PersistentStoreImpl.java
see title
@jlcsmith @stustison 
Currently if you wish to store a large blob of data in the persistence store you must use TEXT, which has a hard limit of 32k. This adds support for binary which can be much bigger.
https://codice.atlassian.net/browse/DDF-2567
> DDF-2567: Added binary type support to persistence store

- catalog/spatial/csw/spatial-csw-source-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/AbstractCswSource.java
- catalog/spatial/csw/spatial-csw-source-common/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/TestCswSource.java
This PR removes the potential for an NPE in AbstractCswSource when creating the sort order.  This was observed when using SortBy.NATURAL_ORDERING.
@rzwiefel @lcrosenbu 
@jlcsmith
@kcwire
Build / Install / Configure Federated CSW / Observe No NPE
[DDF-2601](https://codice.atlassian.net/browse/DDF-2601)
> DDF-2601 Fixed NPE in AbstractCswSource.java

- catalog/spatial/registry/registry-admin-modules/registry-admin-remote-ui/src/main/webapp/js/HandlebarsHelpers.js
- catalog/spatial/registry/registry-admin-modules/registry-admin-remote-ui/src/main/webapp/main.js
- catalog/spatial/registry/registry-admin-modules/registry-admin-remote-ui/src/main/webapp/templates/configuration/configurationItem.handlebars
Adds the suggested csw url text of `https://hostname.here:port#/services/csw` to the Registry Url field when adding a new registry from the remote tab in the DDF Registry.
@clockard @brianfelix @gordocanchola @vinamartin 
@coyotesqrl 
@lessarderic
Build changes, Boot DDF, Install DDF Registry App, Navigate to Remote Registry Tab in the Registry App, Click the + button to add a new Registry, Observe the suggested greyed out text in the url field
This change should detect if the registry type is described as a csw type and shouldn't appear if another custom registry store was to be implemented as long as it wasn't described as "CSW". 
[DDF-2057](https://codice.atlassian.net/browse/DDF-2057)
> DDF-2057 Updated csw url suggestion text in add remote registry modal

- catalog/core/catalog-core-api/src/main/java/ddf/catalog/data/AttributeRegistry.java
- catalog/core/catalog-core-attributeregistry/src/main/java/ddf/catalog/data/impl/AttributeRegistryImpl.java
- catalog/core/catalog-core-attributeregistry/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/core/catalog-core-attributeregistry/src/test/java/ddf/catalog/data/impl/AttributeRegistryImplTest.java
- catalog/core/catalog-core-validationparser/src/main/java/ddf/catalog/validation/impl/ValidationParser.java
- catalog/core/catalog-core-validationparser/src/test/groovy/ddf/catalog/validation/impl/ValidationParserSpecTest.groovy
This PR registers attributes of MetacardTypes when they are registered in DDF. 
@lcrosenbu @jrnorth 
@jlcsmith
@kcwire
Build / Run / `log:set DEBUG ddf.catalog.data.impl` / Install / Observe attribute registration for each metacard type.
Extensions of DDF ( e.x. Alliance) contain additional attributes on Metacards that should be registered in the AttributeRegistry.
[DDF-2621](https://codice.atlassian.net/browse/DDF-2621)
…
> DDF-2621 Refactored the AttributeRegistry to dynamically register attributes from all MetacardTypes as they become available

- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestConfiguration.java
- platform/platform-migratable/src/main/java/org/codice/ddf/platform/migratable/impl/PlatformMigratable.java
- platform/platform-migratable/src/test/java/org/codice/ddf/platform/migratable/impl/PlatformMigratableTest.java
Adds the `users.attributes` file to the list of migrated files in `PlatformMigratable` and updates the tests accordingly. 
@oconnormi 
@brjeter 
@shaundmorris 
@figliold
@lessarderic
* Ensure a full build passes with all tests - pay special attention to `TestConfiguration`
* Spin up DDF and complete the install procedure; then run the `migration:export` command and ensure that the `users.attributes` file is in `$DDF_ROOT$/etc/exported`
* Repeat the process when specifying an external export target
This bug fix will help address possible security issues and ease efforts for high-availability. 
[DDF-2633](https://codice.atlassian.net/browse/DDF-2633)
> DDF-2633: Config file users.attributes now gets migrated

- catalog/core/catalog-core-backupplugin/pom.xml
- catalog/core/catalog-core-directorymonitor/pom.xml
- platform/platform-app/pom.xml
- platform/platform-app/src/main/resources/features.xml
- platform/util/platform-util/pom.xml
- platform/util/platform-util/src/main/java/org/codice/ddf/platform/util/TemporaryFileBackedOutputStream.java
- pom.xml
* Create an retry utility that will re-execute an operation if that operation throws an exception
* Update TemporaryFileBackedOutputStream to use the retry utility when resetting the underlying FileBackedOutputStream (google).
@bdeining 
@rzwiefel 
@coyotesqrl 
@dcruver 
@lessarderic
@stustison
To directly test the retry code, run the unit tests in org.codice.ddf.platform.util.OperationRunnerTest.
To directly test TFBOS (and thus indirectly test the retry code), exercise any part of the system that uses TFBOS. For example, anything that calls InputTransformerProducer#generateMetacard.
It was discovered that in a windows vm, the TFBOS was unable to delete its temporary file, even …
> DDF-2588 Create a retry utility and update TFBOS to use it

- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/CreateOperations.java
Fixes the logic to retrieve the `Subject` using `SecurityUtils` since the `SecurityPlugin` has not processed and set it on the `CreateRequest`'s properties yet. This way, the Point of Contact attribute is set on the metacard correctly.
@lessarderic @Lambeaux @shaundmorris  
@coyotesqrl 
@stustison
- Run a full build.
- Deploy DDF and ingest a product. Verify the associated metacard's Point of Contact is set.
[DDF-2630](https://codice.atlassian.net/browse/DDF-2630)
> DDF-2630: Adding logic to retrieve the Subject correctly so that Point of Contact is actually set on the metacard.

- catalog/spatial/csw/spatial-csw-source-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/AbstractCswSource.java
- catalog/spatial/csw/spatial-csw-source-common/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/TestCswSource.java
This PR removes the potential for an NPE in AbstractCswSource when creating the sort order.  This was observed when using SortBy.NATURAL_ORDERING.
@rzwiefel @lcrosenbu 
@jlcsmith
@kcwire
Build / Install / Configure Federated CSW / Observe No NPE
[DDF-2601](https://codice.atlassian.net/browse/DDF-2601)
> (2.9.x) DDF-2601 Fixed NPE in AbstractCswSource.java

- catalog/spatial/registry/registry-admin-modules/registry-admin-local-ui/src/main/webapp/templates/field.handlebars
The latitude and longitude of remote repositories should not be editable locally.
Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged)?
@clockard @mcalcote
Select at least one member from relevant component team(s) from below (at least one
@mcalcote
Choose 2 committers to review/merge the PR (please choose ONLY two committers from below, delete the rest).
@lessarderic
@shaundmorris
Install the registry application.
Add a remote repository.
View the node information of the remote repository.
Latitude and longitude attributes should be read-only
No.
DDF-2613 …
> DDF-2613 Latitude and Longitude attributes should not be editable

- catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/CswRecordConverter.java
- catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/transformer/AbstractGmdTransformer.java
- catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/transformer/CswQueryResponseTransformer.java
- catalog/spatial/csw/spatial-csw-transformer/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/TestCswRecordConverter.java
This PR sets the mime type for CSW and GMD so that they are exported with an `.xml` extension.
@jlcsmith
@kcwire
Build / Install / Ingest Data / Export as csw:Record and GMD and observe the record has an `.xml` extension on export.
> DDF-2600 Added mime type to CSW and GMD

- catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/content/data/impl/ContentItemValidator.java
- catalog/core/catalog-core-api-impl/src/test/java/ddf/catalog/content/data/impl/ContentItemValidatorTest.java
- catalog/core/catalog-core-localstorageprovider/pom.xml
- catalog/core/catalog-core-localstorageprovider/src/main/java/org/codice/ddf/catalog/content/impl/FileSystemStorageProvider.java
- catalog/core/catalog-core-localstorageprovider/src/test/java/org/codice/ddf/catalog/content/impl/FileSystemStorageProviderTest.java
Windows does not allow ":" in a file path. We assumed that we could translate the URI in storage provider to a native file path. This is not always the case. We now validate each URI to make sure it conforms to our storage provider spec.
anyone
@jlcsmith 
@kcwire
> DDF-2520: Fixes windows path issue in storage provider

- catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/SolrFilterDelegate.java
- catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/TestSolrFilterDelegate.java
- catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/TestSolrProvider.java
Makes querying consistent when querying between ANY_TEXT or fields directly when a query contains a wildcard and the field contains hyphens.
@jlcsmith 
@kcwire
@pklinef
Ingest metacard with title containing hyphens and verify that can be retrieved by the exact field with a query that contains a wildcard (i.e. "title like "abc-12*")
[DDF-2636 ](https://codice.atlassian.net/browse/DDF-2636)
> DDF-2636 resolve querying with wildcards on fields containing hyphens

- CHANGES.md
- catalog/core/catalog-core-urlresourcereader/src/main/java/ddf/catalog/resource/impl/URLResourceReader.java
- catalog/core/catalog-core-urlresourcereader/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/core/catalog-core-urlresourcereader/src/test/java/ddf/catalog/resource/impl/ResourceReaderTest.java
- catalog/spatial/ogc/spatial-ogc-urlresourcereader/src/test/java/org/codice/ddf/spatial/ogc/catalog/resource/impl/TestResourceReader.java
Updates the URLResourceReader so it will use basic auth if username/password is present.
@gordocanchola @brianfelix
@shaundmorris
@stustison
This is a port from the 2.9.x branch https://github.com/codice/ddf/pull/1363
DDF-2547
> DDF-2547 Updated URLResourceReader to use basic auth username/password if present

- catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/DumpCommand.java
This PR closes the InputStream of the Zip file generated by the DumpCommand
@peterhuffer 
@coyotesqrl
@jlcsmith
Build / Install / Ingest / catalog:dump --include-content / verify file can be deleted and is not being used by java
[DDF-2657](https://codice.atlassian.net/browse/DDF-2657)
> DDF-2657 Closed InputStream of zip file generated by dump command

- catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/DumpCommand.java
This PR closes the InputStream of the Zip file generated by the DumpCommand
@peterhuffer 
@coyotesqrl
@jlcsmith
Build / Install / Ingest / catalog:dump --include-content / verify file can be deleted and is not being used by java
[DDF-2657](https://codice.atlassian.net/browse/DDF-2657)
> (2.9.x) DDF-2657 Closed InputStream of zip file generated by dump command

- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/CatalogFrameworkImpl.java
When multiple InputTransformers are present that all handle a given mime-type (e.g. text/xml) they should each be called until one successfully creates a metacard. Currently, if any of them throw an exception, the processing chain is stopped and the other InputTransformers are not called.
@jrnorth 
@jlcsmith 
@pklinef
Build / Install / log:set DEBUG ddf.catalog.impl / Ingest XML and observe multiple transformers are called
[DDF-2320](https://codice.atlassian.net/browse/DDF-2320)
> (2.9.x) DDF-2320 Updated CatalogFramework to try all InputTransformers before failing ingest

- catalog/spatial/kml/spatial-kml-networklinkendpoint/src/main/java/org/codice/ddf/spatial/kml/endpoint/KmlEndpoint.java
- catalog/spatial/kml/spatial-kml-networklinkendpoint/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/spatial/kml/spatial-kml-networklinkendpoint/src/test/java/org/codice/ddf/spatial/kml/endpoint/TestKmlEndpoint.java
- catalog/ui/search-ui/simple/src/main/java/org/codice/ddf/ui/searchui/simple/properties/ConfigurationStore.java
- catalog/ui/search-ui/simple/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/ui/search-ui/standard/src/main/java/org/codice/ddf/ui/searchui/standard/properties/ConfigurationStore.java
- catalog/ui/search-ui/standard/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- distribution/ddf-branding-plugin/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- platform/admin/ui/src/main/java/org/codice/admin/ui/configuration/Configuration.java
- platform/admin/ui/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- platform/branding-api/pom.xml
- platform/branding-api/src/main/java/org/codice/ddf/branding/BrandingRegistry.java
- platform/branding-api/src/main/java/org/codice/ddf/branding/BrandingRegistryImpl.java
- platform/branding-api/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- platform/branding-api/src/test/java/org/codice/ddf/branding/BrandingRegistryTest.java
- platform/landing-page/pom.xml
- platform/landing-page/src/main/java/org/codice/ddf/landing/LandingPage.java
- platform/landing-page/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- platform/landing-page/src/test/java/org/codice/ddf/landing/TestLandingPage.java
- platform/platform-app/src/main/resources/features.xml
- platform/platform-configuration/src/main/java/org/codice/ddf/configuration/PlatformUiConfiguration.java
- platform/platform-configuration/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- platform/platform-configuration/src/test/java/org/codice/ddf/configuration/PlatformUiConfigurationTest.java
- platform/security/handler/security-handler-guest/src/main/java/org/codice/ddf/security/handler/guest/configuration/Configuration.java
- platform/security/handler/security-handler-guest/src/main/resources/OSGI-INF/blueprint/blueprint.xml
When using implementations of the BrandingPlugin other than the DdfBrandingPlugin, these can be installed at a late enough stage that the LandingPage times out waiting for the dependency.
Instead, the LandingPage should always start the DdfBrandingPlugin and then when another implementation becomes available, should use that instead.
In addition, this PR takes the fix from the LandingPage java and blueprint and applies it to any other classes that use a BrandingPlugin in DDF.
@roelens8 
@jrnorth 
@kcwire 
@jaymcnallie 
Build and run DDF. Hot deploy a different branding plugin implementation with a ranking higher than 0. Verify that in branded places, the branding is replaced. (Eg, landing page, admin ui, search …
> DDF-2637 Remove tight dependencies on BrandingPlugin

- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/CachingFederationStrategy.java
This PR adds sources to the SolrCacheSource's query request. This will allow the solr query to filter on sourceIds provided. Returning results for only the sources selected.
@clockard @mcalcote @vinamartin @brianfelix 
@pklinef
@shaundmorris
Install multiple instances of the DDF (or use loopback sources)
Open the Search UI one each instance and injest at least one product.
Select an instance to federate to the other sources
Open the admin console for the selected instance and create a source for each of the other instances
Open the Search UI for the selected instance and perform a search of all source
Verify all expected results …
> DDF-2654 - Results are returned from all federated sources when querying a specific source from the Standard Search UI

- catalog/transformer/catalog-transformer-tika-input/src/main/java/ddf/catalog/transformer/input/tika/TikaInputTransformer.java
This PR adds the mime type aliases defined in the Default Mime Type Registry for Tika to the Tike Input transformer service properties
@troymohl 
@jlcsmith
@kcwire
Build / log:set DEBUG ddf.catalog.transformer.input.tika / Install / verify debug
```12:59:35,300 | DEBUG | eb2-be9ea68d2ae2 | nsformer.input.tika.TikaInputTransformer  372 | ka-input-transformer | supported mime types ``` contains text/xml alias
Complete alias list can be found here : 
http://grepcode.com/file/repo1.maven.org/maven2/org.apache.tika/tika-core/1.9/org/apache/tika/mime/tika-mimetypes.xml
[DDF-2672](https://codice.atlassian.net/browse/DDF-2672)
> DDF-2672 Added Mime Type Aliases to Tika Input Transformer service properties

- catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.email.xml
Change default email notification reply address to donotreply@example.com
@bdeining 
@rzwiefel 
@jlcsmith
@kcwire
Build & install. Navigate to the admin screen for Email Notifications and confirm that the default reply address is donotreply@example.com.
[DDF-2696](https://codice.atlassian.net/browse/DDF-2696)
> DDF-2696 Change default email notification reply address

- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/CachingFederationStrategy.java
This is the port to master of the following:
This PR adds sources to the SolrCacheSource's query request. This will allow the solr query to filter on sourceIds provided. Returning results for only the sources selected.
@clockard @mcalcote @vinamartin @brianfelix 
@pklinef
@shaundmorris
Install multiple instances of the DDF (or use loopback sources)
Open the Search UI one each instance and injest at least one product.
Select an instance to federate to the other sources
Open the admin console for the selected instance and create a source for each of the other instances
Open the Search UI for the selected instance and perform a search …
> DDF-2654 - (Port to master) Results are returned from all federated sources when querying a specific source from the Standard Search UI

- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalog.java
Changes the testCachedContentLengthHeader itest in TestCatalog to clear the catalog's cache before the test is run and also ensure the cache is queried. 
@rzwiefel @clockard @gordocanchola @tbatie 
@coyotesqrl
@stustison
Run TestCatalog#testCachedContentLengthHeader
This test has been reported as flaky a few times in the past. With these changes hopefully the test will fail more accurately. 
[DDF-2423](https://codice.atlassian.net/browse/DDF-2423)
> DDF-2423 Updated TestCatalog cache itest to reduce flakiness

- catalog/core/catalog-core-standardframework/pom.xml
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/CreateOperations.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/MetacardFactory.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/OperationsMetacardSupport.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/UpdateOperations.java
- catalog/core/catalog-core-standardframework/src/test/groovy/ddf/catalog/impl/operations/MetacardFactoryTest.groovy
- catalog/core/catalog-core-standardframework/src/test/groovy/ddf/catalog/impl/operations/OperationsMetacardSupportTest.groovy
- catalog/security/catalog-security-plugin/pom.xml
- catalog/security/catalog-security-plugin/src/main/java/ddf/catalog/security/plugin/SecurityPlugin.java
- catalog/security/catalog-security-plugin/src/test/java/ddf/catalog/security/plugin/SecurityPluginTest.java
- distribution/ddf-common/src/main/resources/etc/definitions/core-attribute-injectors.json
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalog.java
- Moves logic for setting point of contact from the `MetacardFactory` to the `SecurityPlugin`, so that all ingested metacards hit the logic instead of just metacards with associated products.
- Configured attribute injector for point of contact, so that the attribute descriptor is put on all metacards and thus the attribute is persisted.
- Updated itests.
@Lambeaux @brendan-hofmann @jrnorth @shaundmorris 
@figliold
@stustison
- Run a full build against an empty repo.
- Ingest metacards of different types as at least two different users. Verify the `Point of Contact` attribute is set to the uploader's user name for every metacard. ("Guest" if not signed in)
This builds the …
> DDF-2661: Fix point of contact to be set on all created metacards.

- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/CatalogFrameworkImpl.java
- catalog/security/catalog-security-plugin/pom.xml
- catalog/security/catalog-security-plugin/src/main/java/ddf/catalog/security/plugin/SecurityPlugin.java
- catalog/security/catalog-security-plugin/src/test/java/ddf/catalog/security/plugin/SecurityPluginTest.java
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalog.java
- Moves logic for setting point of contact from the `CatalogFrameworkImpl` to the `SecurityPlugin`, so that all ingested metacards hit the logic instead of just metacards with associated products.
- Updated itests.
@Lambeaux @brendan-hofmann @jrnorth @shaundmorris 
@figliold
@stustison
- Run a full build against an empty repo.
- Ingest metacards of different types as at least two different users. Verify the `Point of Contact` attribute is set to the uploader's user name for every metacard. ("Guest" if not signed in)
This builds the foundation for a feature that adds a security exception for all metacard point-of-contact fields so the uploader can see their product …
> [2.9.x]DDF-2661: Backport to fix point of contact for creating metacards.

- distribution/ddf-common/src/main/resources/etc/log4j2.config.xml
- distribution/ddf-common/src/main/resources/etc/org.ops4j.pax.logging.cfg
- distribution/docs/src/main/resources/_contents/_installing/installing-intro-contents.adoc
- distribution/docs/src/main/resources/_contents/extending-contents.adoc
- distribution/docs/src/main/resources/_contents/installing-contents.adoc
Configures all logs from `org.apache.solr` to go to a separate log file instead of in the main log. This is to reduce noise in the main log, but still have solr logs for debugging.
@Lambeaux @figliold @ricklarsen 
@pklinef
@shaundmorris 
- Build and run (including stepping through setup).
- Restart DDF. This will produce some solr errors when trying to create the Solr cores (see below for example). `log:tail` and verify there are no such errors in the console. Check `{karaf.home}/data/log/solr.log` and verify the solr logs are there including the errors.
```ERROR | qtp255340046-91  | org.apache.solr.common.SolrException      148 | lr-server-standalone | org.apache.solr.common.SolrException: Error CREATEing SolrCore 'metacard_cache': Could …
```
> DDF-2617: Configuring solr to log to separate log file to reduce noise in main log.

- distribution/ddf-common/src/main/resources/etc/log4j2.config.xml
- distribution/ddf-common/src/main/resources/etc/org.ops4j.pax.logging.cfg
- distribution/docs/src/main/resources/_contents/extending-contents.adoc
- distribution/docs/src/main/resources/_contents/installing-contents.adoc
Configures all logs from `org.apache.solr` to go to a separate log file instead of in the main log. This is to reduce noise in the main log, but still have solr logs for debugging.
@Lambeaux @figliold 
@pklinef
@shaundmorris 
- Build and run (including stepping through setup).
- Restart DDF. This will produce some solr errors when trying to create the Solr cores (see below for example). `log:tail` and verify there are no such errors in the console. Check `{karaf.home}/data/log/solr.log` and verify the solr logs are there including the errors.
```ERROR | qtp255340046-91  | org.apache.solr.common.SolrException      148 | lr-server-standalone | org.apache.solr.common.SolrException: Error CREATEing SolrCore 'metacard_cache': Could not create a …
```
> [2.9.x]DDF-2617: Configuring solr to log to separate log file to reduce noise in main log. 

- distribution/docs/src/main/resources/_contents/_data/neutral-taxonomy-categories-contents.adoc
- distribution/docs/src/main/resources/_contents/_data/neutral-taxonomy-intro-contents.adoc
- distribution/docs/src/main/resources/_contents/_data/neutral-taxonomy-tables-contents.adoc
- distribution/docs/src/main/resources/draft-documentation.adoc
adds template/outline for documenting neutral taxonomy. 
@brendan-hofmann @emanns95 @Lambeaux @mcalcote @vinamartin @jrnorth 
@jlcsmith
@shaundmorris
verify outline, build docs successfully
[DDF-2684](https://codice.atlassian.net/browse/DDF-2684)
[DDF-2682](https://codice.atlassian.net/browse/DDF-2682)
> DDF-2684 added documentation for neutral taxonomy

- catalog/ui/catalog-ui-search/src/main/webapp/component/metacard-interactions/metacard-interactions.hbs
The help description for the "Hide from Future Searches" is currently displayed as "Adds to a list of results that will be hidden from future searches. To clear this list, go to the toolbar, click Edit, and then click reset blacklist." 
The Edit menu was removed, and the way to reset the blacklist is now achieved by clicking the Settings (gear/cog icon on the top right) and choose "Hidden". The blacklisted results can then be individually or globally unhidden from this area.
@bdeining 
@ricklarsen 
@jlcsmith
- Build and install DDF.
- Open the Catalog UI.
- Ingest and perform a search. View the results.
- Choose one of the results, click the menu so that the `Hide from Future Searches` option is displayed.
- Click the Help (?) …
> DDF-2701 Updated incorrect help message for "Hide from Future Searches"

- platform/admin/core/admin-core-appservice/src/main/java/org/codice/ddf/admin/application/service/impl/ApplicationImpl.java
- platform/admin/core/admin-core-appservice/src/test/java/org/codice/ddf/admin/application/service/impl/ApplicationImplTest.java
A recent merge caused issues when creating a release for reflex because we used a dash after the version number since it was an out of band release.
@clockard @brendan-hofmann
@ahoffer 
@figliold
@shaundmorris
unit and itests
when trying to do an out of band release with a dash in the version this issue caused application deployment to fail.
> DDF-2596 releases contain dashes in the version not deploying

- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/CreateOperations.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/OperationsMetacardSupport.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/OperationsStorageSupport.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/UpdateOperations.java
- catalog/core/catalog-core-standardframework/src/test/groovy/ddf/catalog/impl/operations/OperationsMetacardSupportTest.groovy
- catalog/core/catalog-core-standardframework/src/test/groovy/ddf/catalog/impl/operations/OperationsStorageSupportTest.groovy
- catalog/plugin/catalog-plugin-videothumbnail/pom.xml
- catalog/plugin/catalog-plugin-videothumbnail/src/main/java/org/codice/ddf/catalog/content/plugin/video/VideoThumbnailPlugin.java
- catalog/plugin/catalog-plugin-videothumbnail/src/test/java/org/codice/ddf/catalog/content/plugin/video/TestVideoThumbnailPlugin.java
Fixes an issue observed with submitting an `UpdateStorageRequest` containing multiple `ContentItem`s with the same ID (multiple `ContentItem`s linked to the same `Metacard`. For example, NITF derived images) back to the `Catalog`where the tmp files of the derived `ContentItem` would fail to be deleted due to being overridden in the `Map`.
@troymohl @emmberk @glenhein 
@pklinef
@stustison
Full build. 
The only way I currently know how to test this manually would be to build [this](https://github.com/codice/ddf/pull/1495) branch with this PR. Then build Alliance with [CAL-204](https://github.com/codice/alliance/pull/225), ingest a NITF and observe that there are no temp files left behind in `/data/tmp/`
[DDF-2688](https://codice.atlassian.net/browse/DDF-2688)
> DDF-2688: Fix extra tmp files being left in /data/tmp/

- catalog/core/catalog-core-standardframework/pom.xml
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/OperationsMetacardSupport.java
- catalog/core/catalog-core-standardframework/src/test/groovy/ddf/catalog/impl/operations/OperationsMetacardSupportTest.groovy
Resolve an issue with mimetype resolution in tika's probabilistic detector.
@AzGoalie 
@ahoffer 
@pklinef
@stustison
Verify that a text file with a `.bin` extension gets a mimetype of `text/plain` instead of the default.
This issue was failing silently because we caught the IOException and logged it at `DEBUG`.
[](https://codice.atlassian.net/browse/DDF-2697)
> DDF-2697 Fix mark/reset IOException

- catalog/admin/module/catalog-admin-module-sources/src/main/webapp/js/model/Source.js
- catalog/admin/module/catalog-admin-module-sources/src/main/webapp/js/view/Source.view.js
- catalog/admin/module/catalog-admin-module-sources/src/main/webapp/templates/sourceList.handlebars
- catalog/admin/module/catalog-admin-module-sources/src/main/webapp/templates/sourceRow.handlebars
* Adds a column to the sources list to display the currently active URL
* Adds a warning when the currently active URL is pointing at `localhost` or `org.codice.ddf.system.hostname`
@figliold 
@brjeter 
@Lambeaux 
@bantillo 
@Joy603 
@codice/ui 
@lessarderic
@pklinef
[DDF-2671](https://codice.atlassian.net/browse/DDF-2671)
> DDF-2671: Added visibility of each sources active url and warnings for local addresses

- catalog/ui/catalog-ui-search/src/main/webapp/lib/cesium-drawhelper/DrawHelper.js
- catalog/ui/search-ui/standard/src/main/webapp/lib/cesium-drawhelper/DrawHelper.js
- See leforthomas/cesium-drawhelper#13 for details.
- At lower zooms, points were being erroneously removed from drawings.
Updates the vendored version of DrawHelper to pull in a fix for lower zoom drawings.
@jlcsmith 
@kcwire 
@jlcsmith
@kcwire
Zoom to street level somewhere and draw a line or a polygon. 
This applies the fix to both the standard and the catalog ui.
https://codice.atlassian.net/browse/DDF-2687
Before: https://gfycat.com/SereneSelfassuredBoto
After: https://gfycat.com/ElectricLittleHummingbird
> DDF-2687 Update vendored DrawHelper to not remove overlapping points

- catalog/ui/catalog-ui-search/src/main/webapp/component/visualization/maps/cesium/map.cesium.js
- catalog/ui/catalog-ui-search/src/main/webapp/js/controllers/cesium.layerCollection.controller.js
- catalog/ui/search-ui/standard/src/main/webapp/js/controllers/cesium.controller.js
- catalog/ui/search-ui/standard/src/main/webapp/js/controllers/cesium.layerCollection.controller.js
- See https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Widgets/CesiumWidget/CesiumWidget.js#L317
- If we don't set it to false, a default server is set that can't be reached in closed environments.  While we used to eventually remove the default, this will ensure the default isn't even set.
@rzwiefel 
@bdeining 
@jlcsmith 
Go to each of the search UIs.  Open the network developer tools and look for a request to https://dev.virtualearth.net/REST/v1/Imagery/Metadata/Aerial?incl=ImageryProviders&key=0&jsonp=loadJsonp402905 when Cesium gets loaded.  If it doesn't show up, you're good.
https://codice.atlassian.net/browse/DDF-2707
> DDF-2707 Update cesium initialization to set imageryProvider to false

- catalog/ui/catalog-ui-app/src/main/resources/etc/org.codice.ddf.catalog.ui.config
- catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/config/ConfigurationApplication.java
- catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.config.xml
- catalog/ui/catalog-ui-search/src/main/webapp/component/editor/editor.less
- catalog/ui/catalog-ui-search/src/main/webapp/component/metacard-associations/metacard-associations.less
- catalog/ui/catalog-ui-search/src/main/webapp/component/metacard-history/metacard-history.less
- catalog/ui/catalog-ui-search/src/main/webapp/component/tabs/metacard/tabs-metacard.less
- catalog/ui/catalog-ui-search/src/main/webapp/component/tabs/metacard/tabs-metacard.view.js
- catalog/ui/catalog-ui-search/src/main/webapp/component/tabs/metacards/tabs-metacards.less
- catalog/ui/catalog-ui-search/src/main/webapp/component/tabs/metacards/tabs-metacards.view.js
- catalog/ui/catalog-ui-search/src/main/webapp/properties.js
- Adds an administrative option to hide editing capability in the Catalog UI from the catalog.ui.config.
- Note that this doesn't do anything to restrict editing on the backend.
- Default is to allow editing.
@clockard 
@pklinef
@rzwiefel 
Go to the Catalog UI and verify that editing is not allowed by default.   Editing should be hidden from the Summary, Details, History, & Associations views.  The Overwrite and Archive tabs should be hidden entirely.  When selecting multiple metacards as once, only the Details tab should be available and editing should be hidden from it.
Then go to the Admin UI and proceed to the org.codice.ddf.catalog.ui.config.  Turn the config for Allow Editing to true.  Return to the Catalog UI and verify the opposite of what you verified for when …
> DDF-2706 Add configuration option to hide editing capability in the Catalog UI

- catalog/ui/catalog-ui-search/src/main/webapp/js/model/Workspace.js
- It's possible for the initial fetch of workspaces from the cloud to take so long that a user can create a new cloud workspace in the meantime, then the fetch comes back missing that workspace and the workspace gets obliterated while you’re in it.
While the chance is very slim, we should defend against it by making the fetch non-destructive.
@jlcsmith
@kcwire
This one is hard to test (since it's a race condition).  I had to manually force it to happen by updating the code.
You can do the same by going to this area of the code: https://github.com/codice/ddf/blob/master/catalog/ui/catalog-ui-search/src/main/webapp/js/model/Workspace.js#L128
Then changing the line `this.fetch()` to
```
this.createWorkspace('Hey look a race condition'); …
```
> DDF-2690 Remove race condition in initial workspace fetch

- catalog/ui/catalog-ui-search/src/main/webapp/component/metacard/metacard.js
- As soon as a source returns the metacard, the query is now stopped.  This will prevent issues with connections to slow sources being left open unnecessarily.
@jlcsmith 
@bdeining 
@kcwire
This only affects the https://localhost:8993/search/catalog/#metacards/ route.  To test it, connect more than one source.  Then route to a metacard.  You should see that outstanding searches are canceled as soon as the metacard is found.  
A limited number of connections can be opened per domain in the browser, so this is integral to making sure unnecessary connections to slow sources are left open.
https://codice.atlassian.net/browse/DDF-2703
[Cancellation](https://webmshare.com/play/NdJbg)
> DDF-2703 Update metacard model to stop searching as soon as possible

- catalog/ui/catalog-ui-search/src/main/webapp/component/metacard-actions/metacard-actions.view.js
- catalog/ui/catalog-ui-search/src/main/webapp/component/metacard-archive/metacard-archive.view.js
- catalog/ui/catalog-ui-search/src/main/webapp/component/metacard-history/metacard-history.view.js
- catalog/ui/catalog-ui-search/src/main/webapp/component/metacard-quality/metacard-quality.view.js
- catalog/ui/catalog-ui-search/src/main/webapp/component/tabs/metacard/tabs-metacard.view.js
- Previously the revert action was using a response from the endpoint.  However, this response could not be used directly as special parsing is done for results in the result collection.  Specifically, the thumbnail gets converted to a URI.
- Now the metacard is immediately tagged as a revision, pending refresh from the cql endpoint.  If the refresh takes too long, the user is pushed back to the default view with a warning instructing them that they'll receive write control again once the data returns (if it makes sense based on the returned data).
- Updated single metacard inspector view to throttle rather than debounce refreshes to current metacard data.  This makes for a more consistent experience if the refresh happens to come back a ms or so too late and the warning pops up.  If we …
> DDF-2692 Update revert action to refresh result data differently

- catalog/ui/search-ui/search-redirect/src/main/resources/OSGI-INF/metatype/metatype.xml
- catalog/ui/search-ui/search-ui-app/src/main/resources/org.codice.ddf.ui.searchui.filter.RedirectServlet.config
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestSingleSignOn.java
Makes the catalog ui the default search ui when redirecting from /search
@vinamartin @brianfelix 
@pklinef
Install DDF and go to the https://localhost:8993/search and verify that you are redirected to the catalog ui 
https://codice.atlassian.net/browse/DDF-2704
> DDF-2704 Make the catalog ui the default search ui

- catalog/core/catalog-core-solr/pom.xml
- catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/SolrCatalogProvider.java
- catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/SolrMetacardClient.java
- catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/SolrMetacardClientImpl.java
- catalog/core/catalog-core-standardframework/pom.xml
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/CacheSolrMetacardClient.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/CachingFederationStrategy.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/InitializedSolrClientAdaptor.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/NoOpSolrMetacardClient.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/SolrCache.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/SolrClientAdaptor.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/UninitializedSolrClientAdaptor.java
- catalog/core/catalog-core-standardframework/src/main/resources/OSGI-INF/blueprint/fedstrategy.xml
- catalog/core/catalog-core-standardframework/src/main/resources/OSGI-INF/metatype/sortedFederationStrategy.xml
- catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/cache/solr/impl/InitializedSolrClientAdaptorTest.java
- catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/cache/solr/impl/NoOpSolrMetacardClientTest.java
- catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/cache/solr/impl/SolrCacheTest.java
- catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/cache/solr/impl/SolrClientAdaptorTest.java
- catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/cache/solr/impl/UninitializedSolrClientAdaptorTest.java
- catalog/solr/catalog-solr-provider/pom.xml
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalog.java
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestEmbeddedSolr.java
- platform/persistence/platform-persistence-core-impl/pom.xml
- platform/solr/solr-factory/src/main/java/org/codice/solr/factory/impl/EmbeddedSolrFactory.java
Changes the Catalog's Solr cache code to use the new common Solr provider.
@brjeter 
@oconnormi 
@Lambeaux 
@figliold
@pklinef
Manually test that Catalog metacards are cached properly when the Solr provider is configured as embedded, external/http and cloud. Also test that the `catalog:removeall --cache` command works as expected in all three configurations.
[DDF-2629](https://codice.atlassian.net/browse/DDF-2629)
> DDF 2629: Change code to use new SolrClientFactoryImpl

- catalog/rest/catalog-rest-endpoint/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- platform/mime/tika/platform-mime-tika-resolver/src/main/resources/OSGI-INF/blueprint/blueprint.xml
The blueprint reference in the REST endpoint is intended to be the TikaMimeTypeResolver, but without a filter, there is potential for this reference to be other implementations of the MimeTypeResolver interface.  This was observed in a windows environment, which caused some file extensions to not be present during REST calls.
@jrnorth 
@jlcsmith
@kcwire
Build / Install / Ingest Data / Use REST endpoint to download various filetypes and verify their extensions.
[DDF-2699](https://codice.atlassian.net/browse/DDF-2699)
> DDF-2699 Added filter for TikaMimeTypeResolver in the REST Endpoint blueprint

- catalog/ui/catalog-ui-search/src/main/webapp/component/singletons/metacard-definitions.js
- catalog/ui/catalog-ui-search/src/main/webapp/component/visualization/table/row.view.js
- catalog/ui/catalog-ui-search/src/main/webapp/component/visualization/table/table-rearrange.view.js
- catalog/ui/catalog-ui-search/src/main/webapp/component/visualization/table/table-visibility.view.js
- catalog/ui/catalog-ui-search/src/main/webapp/component/visualization/table/thead.view.js
- All 'Binary' type attributes were being hidden from the table visualization, so an exception is now added for thumbnails.
@rzwiefel 
@djblue 
@jlcsmith 
Ingest data with thumbnails and use the table visualization.  Verify that the thumbnails show up in the table.  Also check the rearrange columns view and the hide / show columns view to make sure they show up there.
https://codice.atlassian.net/browse/DDF-2711
> DDF-2711 Add exception for thumbnails to be shown in table visualization

- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/DeleteOperations.java
Fixes catalog:removeall command when using Solr Cloud.  Previously the catalog:removeall command resulted in "Could not find all metacards specified in request" error on the command line when DDF was configured to use Solr Cloud.
@brjeter 
@oconnormi 
@lessarderic
@pklinef
Manual tests: 
1) Configure DDF to use Solr Cloud in system.properties (this will require setup zookeeper and solr cloud)
2) Ingest
3) Run catalog:removeall 
4) Verify all metacards removed from catalog
https://codice.atlassian.net/browse/DDF-2467
> DDF-2467: Fixes catalog:removeall command when using Solr Cloud

- CHANGES.md
- catalog/ui/catalog-ui-search/src/main/webapp/component/query-interactions/query-interactions.hbs
- catalog/ui/catalog-ui-search/src/main/webapp/component/query-interactions/query-interactions.view.js
- catalog/ui/catalog-ui-search/src/main/webapp/js/model/Query.js
- distribution/docs/src/main/resources/_contents/_using/using-catalog-search-ui-contents.adoc
Using the dropdown option menu on a single query in the catalog UI will now present an option called Search Historical which queries metacards that have been tagged as revisions.
@clockard @brianfelix @vinamartin @gordocanchola @emmberk 
[UI](https://github.com/orgs/codice/teams/ui) @rzwiefel 
@pklinef
Install the DDF Registry App and then open the Registry App tile in the Admin UI and update the local node to generate a revision in the catalog. Open the Catalog UI, enter the local workspace template and perform a default search (which should return 0 results), then use the new Search Historical query option from the dropdown. You should see the registry revision metacard. 
This functionality could assist in finding historical data on resource metacards that are updated …
> DDF-2724 Add the ability to search historical data to the query options in the Catalog UI

- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/MetacardFactory.java
- catalog/core/catalog-core-standardframework/src/test/groovy/ddf/catalog/impl/operations/MetacardFactoryTest.groovy
- catalog/rest/catalog-rest-endpoint/src/main/java/org/codice/ddf/endpoints/rest/RESTEndpoint.java
When multiple InputTransformers are present that all handle a given mime-type (e.g. text/xml) they should each be called until one successfully creates a metacard. Currently, if any of them throw an exception, the processing chain is stopped and the other InputTransformers are not called.
@jrnorth 
@jlcsmith 
@pklinef
Build / Install / log:set DEBUG ddf.catalog.impl / Ingest XML and observe multiple transformers are called / use PostMan to test the rest endpoint
[DDF-2320](https://codice.atlassian.net/browse/DDF-2320)
> DDF-2320 Updated CatalogFramework to try all InputTransformers before failing ingest

- catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/data/impl/types/MediaAttributes.java
- catalog/core/catalog-core-api/src/main/java/ddf/catalog/data/types/Media.java
- catalog/transformer/catalog-transformer-common/pom.xml
- catalog/transformer/catalog-transformer-common/src/main/java/ddf/catalog/transformer/common/tika/MetacardCreator.java
- catalog/transformer/catalog-transformer-common/src/test/java/ddf/catalog/transformer/common/tika/MetacardCreatorTest.java
- catalog/transformer/catalog-transformer-tika-input/pom.xml
- catalog/transformer/catalog-transformer-tika-input/src/main/java/ddf/catalog/transformer/input/tika/TikaInputTransformer.java
- catalog/transformer/catalog-transformer-tika-input/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/transformer/catalog-transformer-tika-input/src/test/java/ddf/catalog/transformer/input/tika/TikaInputTransformerTest.java
- distribution/docs/src/main/resources/_contents/_formats/supported-file-formats-contents.adoc
Adds more attributes to metacards when ingesting pdf, excel, jpeg, officedoc, mpeg, mp4, or powerpoint files using the Fallback/TikaInputTransformer.
@vinamartin @clockard @gordocanchola @mcalcote 
@mcalcote 
@figliold 
@pklinef  
Ingest one of the filetypes listed above and verify that the metadata attributes that are populated in the filetype also get populated in a the corresponding metacard attributes.
Mapped attributes found in metadata to corresponding metacard attributes when ingesting pdf, excel, jpeg, officedoc, mpeg, mp4, and powerpoint files using the fallback/tika
transformer.
> DDF-2645: Added more attributes to the fallback/tika transformer

- catalog/ui/search-ui/standard/pom.xml
- distribution/docs/pom.xml
Removes external referencing stylesheets from the html documentation.
@ricklarsen @brendan-hofmann @djblue 
[Docs](https://github.com/orgs/codice/teams/docs) @ahoffer 
@coyotesqrl
@pklinef
Quickbuild and install, open documentation from the admin ui and standard search ui. Verify in the source code that there are no external referencing stylesheets.
> DDF-2718: Removed external referencing stylesheets from documentation

- catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/MetacardApplication.java
- the catalog framework update request that takes an array of ids and list of metacards must have both sets in the correct respective order
this ensures the ids are in that correct order.
anyone
@coyotesqrl
ensure multi-select and edit does not throw an exception
https://codice.atlassian.net/browse/DDF-2722
> DDF-2722 Fixes update id ordering bug

- catalog/spatial/spatial-app/src/main/resources/features.xml
This PR sets the `spatial-geocoding-plugin` to install automatically with the `spatial-app` so that geolocated metacard* will have the `location.country-code` attribute set.
@mcalcote @brianfelix @peterhuffer 
@kcwire
@shaundmorris
1. Confirm that the `spatial-geocoding-plugin` is installed automatically as part of the `spatial-app`.
2. Ingest a geolocated metacard*, and confirm that the `location.country-code` attribute is set correctly on the metacard.
Adding the country code to metacards was already implemented by https://github.com/codice/ddf/pull/1171. This purpose of this PR is to set this capability to auto-install.
*Note: Metacards must implement a  `MetacardType` that has the 
[`Location#COUNTRY_CODE` …
> DDF-2325 Set the country code plugin to auto install

- catalog/core/catalog-core-standardframework/pom.xml
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/resource/download/ReliableResourceDownloader.java
- catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/resource/download/ReliableResourceDownloaderTest.java
According to static analysis, reliableResourceStatus in ReliableResourceDownloader could be null
when reliableResourceStatus.getBytesRead is called on line 247. Added a safeguard against this.
@ahoffer @emanns95 @AzGoalie @mweser @brendan-hofmann 
@shaundmorris 
Make sure full build passes.
[](https://codice.atlassian.net/browse/2720)
> DDF-2720 Add null check to fix potential null dereference

- catalog/pom.xml
- catalog/spatial/pom.xml
- catalog/spatial/registry/pom.xml
Upgrades the XStream dependency to version 1.4.9 due to security vulnerabilities.
@clockard 
@mcalcote 
@shaundmorris
@stustison
Full clean build, all itests should pass.
[DDF-2719](https://codice.atlassian.net/browse/DDF-2719)
> DDF-2719 Upgrade Dependency - XStream Bundle 1.4.3 to 1.4.9

- catalog/ui/catalog-ui-search/pom.xml
Remove an unused dependency committed via https://github.com/codice/ddf-ui/pull/7
Description of the PR is nightly email notifications of queries in workspaces.
The manifests of builds show this library as not being used.
@clockard 
@brianfelix 
@mcalcote
@vinamartin 
@cruzj6
@pklinef
@shaundmorris
Attempt a full build. All tests should pass. The compiled DDF should be unziped and executed. Confirm that workspaces are working in the new search UI.
[DDF-2728](https://codice.atlassian.net/browse/DDF-2728)
N/A
> DDF-2728 Remove EHCache dependency from catalog ui

- distribution/docs/src/main/resources/_contents/_securing/managing-certificates-contents.adoc
- distribution/docs/src/main/resources/_contents/securing-contents.adoc
- platform/security/handler/security-handler-pki/src/main/java/org/codice/ddf/security/handler/pki/CrlChecker.java
- platform/security/handler/security-handler-pki/src/test/java/org/codice/ddf/security/handler/pki/CrlCheckerTest.java
Adds the ability to specify any valid URL for the location of a CRL in the CrlChecker's createCrl method.
@stustison 
@clockard
@brianfelix
@mcalcote
@vinamartin
@taz77 
@shaundmorris
@stustison
Tested by specifying a URL location of a CRL in the encryption.properties file.
[DDF-2732](https://codice.atlassian.net/browse/DDF-2732)
- [-] Update / Add Unit Tests
> DDF-2732: Update CrlChecker to accept any valid URL for the location of the CRL

- catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/workspace/WorkspaceMetacardImpl.java
- catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/workspace/WorkspaceMetacardType.java
- catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/blueprint/blueprint.xml
This PR registers the WorkspaceMetacardType in the service registry so it can be reference throughout DDF.
@djblue 
@jlcsmith
Build / Install / Create Some Workspaces / `log:set DEBUG ddf.catalog.transformer`/`dump --cql "\"metacard-tags\" like 'workspace'"` / `catalog:ingest -t xml` / Reingest the workspace metacards and observe that the XML input transformer references the WorkspaceMetacardType.
Additionally, verify that Workspaces still have expected behavior
[DDF-2708](https://codice.atlassian.net/browse/DDF-2708)
> DDF-2708 Refactored Catalog UI to register WorkspaceMetacardType in the service registry

- catalog/core/catalog-core-api/src/main/java/ddf/catalog/Constants.java
- catalog/core/catalog-core-camelcomponent/pom.xml
- catalog/core/catalog-core-camelcomponent/src/main/java/ddf/camel/component/catalog/content/ContentProducer.java
- catalog/core/catalog-core-camelcomponent/src/main/java/ddf/camel/component/catalog/content/ContentProducerDataAccessObject.java
- catalog/core/catalog-core-camelcomponent/src/main/java/ddf/camel/component/catalog/content/FileSystemDataAccessObject.java
- catalog/core/catalog-core-camelcomponent/src/main/java/ddf/camel/component/catalog/content/FileSystemPersistenceProvider.java
- catalog/core/catalog-core-camelcomponent/src/test/java/ddf/camel/component/catalog/content/ContentProducerDataAccessObjectTest.java
- catalog/core/catalog-core-camelcomponent/src/test/java/ddf/camel/component/catalog/content/ContentProducerTest.java
- catalog/core/catalog-core-camelcomponent/src/test/java/ddf/camel/component/catalog/content/FileSystemDataAccessObjectTest.java
- catalog/core/catalog-core-camelcomponent/src/test/java/ddf/camel/component/catalog/content/FileSystemPersistenceProviderTest.java
- catalog/core/catalog-core-directorymonitor/pom.xml
- catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/ContentDirectoryMonitor.java
- catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/DurableFileComponent.java
- catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/DurableFileConsumer.java
- catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/DurableFileEndpoint.java
- catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/EventfulFileWrapper.java
- catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/FileSystemPersistenceProvider.java
- catalog/core/catalog-core-directorymonitor/src/main/resources/META-INF/services/org/apache/camel/component/durable
- catalog/core/catalog-core-directorymonitor/src/main/resources/OSGI-INF/metatype/metatype.xml
- catalog/core/catalog-core-directorymonitor/src/test/java/org/codice/ddf/catalog/content/monitor/ContentDirectoryMonitorTest.java
- catalog/core/catalog-core-localstorageprovider/pom.xml
- catalog/core/catalog-core-localstorageprovider/src/main/java/org/codice/ddf/catalog/content/impl/FileSystemStorageProvider.java
- catalog/core/catalog-core-localstorageprovider/src/test/java/org/codice/ddf/catalog/content/impl/FileSystemStorageProviderTest.java
- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/CreateOperations.java
- catalog/core/catalog-core-standardframework/src/test/groovy/ddf/catalog/impl/operations/CreateOperationsTest.groovy
- distribution/docs/src/main/resources/_contents/_resources/content-directory-monitor-contents.adoc
- distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/ServiceManager.java
- distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/ServiceManagerImpl.java
- distribution/test/itests/test-itests-ddf/pom.xml
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalog.java
- Adds a new camel component that can track deletes
- Adds durable monitoring; can detect offline events
- Adds update/delete to ContentProducer
- Adds reference storage to FileSystemStorageProvider
@AzGoalie 
@emanns95 
@pklinef
@shaundmorris
@stustison
Monitor a local/network directory tree, verify that create/update/delete is reflected appropriately in the catalog.
[](https://codice.atlassian.net/browse/2710)
Needs docs, needs some miscellaneous cleanup. Looking for feedback on overall design, API usage, etc.
> DDF-2710 Add in-place directory monitoring

- catalog/ui/catalog-ui-search/pom.xml
This PR removes the dependency on `terracotta-toolkit-runtime-ee` in `catalog-ui-search` that is causing the OWASP build to fail.
@taz77 @clockard @vinamartin 
@pklinef
@shaundmorris
Confirm full build succeeds.
The EHCache dependency was removed in https://github.com/codice/ddf/pull/1588.
[DDF-2752](https://codice.atlassian.net/browse/DDF-2752)
> DDF-2752 Removed terracotta-toolkit-runtime-ee dependency in catalog-ui-search

- catalog/transformer/catalog-transformer-tika-input/src/main/resources/OSGI-INF/blueprint/blueprint.xml
The Tika MetacardType beans were created, but not exposed. This change exposes those MetacardType beans as services.
@clockard @brianfelix @gordocanchola @emmberk 
@coyotesqrl
@figliold
Install DDF and use the tika transformer to ingest an Mp4 file. Then use Solr to confirm the Audio_Sample_Rate attribute is set.
[DDF-2645](https://codice.atlassian.net/browse/DDF-2645)
> DDF-2645 Exposed Tika fallback metacard types as services

- catalog/spatial/registry/registry-source-configuration-handler/src/main/java/org/codice/ddf/registry/source/configuration/SourceConfigurationHandler.java
Fixes the activation of sources after being regenerated
@gordocanchola @mcalcote 
@coyotesqrl
@figliold
Install DDF and start the Registry.
On the Node Information page create a secondary local node and add a service with a valid binding
Verify there is an source for the binding on the sources tab and activate it.
In Registry -> Configuration -> Registry Source Configuration Handler check the Activate Configurations checkbox
On the Node Information page click the Regenerate Sources and select the secondary node
Refresh the sources tab and verify there is still an active source for the secondary node binding.
https://codice.atlassian.net/browse/DDF-2750#### Screenshots (if appropriate)
> DDF-2750 Fixed regenerated sources activation status

- catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/workspace/WorkspaceTransformer.java
Causes workspace transformer to merge duplicate keys instead of throwing an exception. While our current and future system should try not to have duplicate keys, it was allowed in some legacy configurations so must be supported to deal with them. 
- Now when encountering duplicate attribute descriptors, the workspace transformer will not throw an exception
anyone
@jlcsmith
@kcwire
ingest a duplicate attribute descriptor. log in to ui. attempt to create workspace and ensure it doesn't fail.
Example Attribute descriptor that duplicates a builtin descriptor that can be put into `etc/definitions`
```json
{
"inject": [
{
"attribute": "effective"
}
],
"attributeTypes": {
"effective": {
"type": "DATE_TYPE",
"display": "Date Published", …
```
> DDF-2755 Fixed workspace transformer merge bug

- platform/admin/core/admin-core-api/pom.xml
- platform/admin/core/admin-core-api/src/main/java/org/codice/ddf/ui/admin/api/ConfigurationAdmin.java
- platform/admin/core/admin-core-api/src/main/java/org/codice/ddf/ui/admin/api/ConfigurationAdminMBean.java
- platform/admin/core/admin-core-api/src/main/java/org/codice/ddf/ui/admin/api/GuestClaimsHandlerExt.java
- platform/admin/core/admin-core-api/src/main/java/org/codice/ddf/ui/admin/api/util/PropertiesFileReader.java
- platform/admin/core/admin-core-api/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- platform/admin/core/admin-core-api/src/test/java/org/codice/ddf/ui/admin/api/ConfigurationAdminTest.java
- platform/admin/core/admin-core-api/src/test/java/org/codice/ddf/ui/admin/api/GuestClaimsHandlerContractTest.java
- platform/admin/core/admin-core-api/src/test/java/org/codice/ddf/ui/admin/api/GuestClaimsHandlerExtTest.java
- platform/admin/ui/src/main/webapp/js/views/installer/GuestClaims.view.js
Refactors admin code, mainly `GuestClaimsHandlerExt`, and provides an abstraction for linking UI banner configs to default security profile configs. 
@stustison 
@shaundmorris 
@brjeter 
@Joy603 
No link for configuration and administration team? 
@figliold
@lessarderic
Install DDF several times, each time picking a new default security profile (if any exist) and ensure the UI banners are updated accordingly. 
This work is closely related to the profile install work that will fix the guest and system high user. 
The issues share common refactoring. 
[DDF-2712](https://codice.atlassian.net/browse/DDF-2712)
[DDF-2640](https://codice.atlassian.net/browse/DDF-2640)
> DDF-2712: Allow UI banner default customization based on security defaults

- platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/admin/ConfigurationFilesPoller.java
- platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/admin/ConfigurationFilesPollerTest.java
Moved the WatchService directory registration in the `ConfigurationFilesPoller` `init()` method to ensure that no file creation and/or modification events are missed.
Fixes a race condition in the ConfigurationFilesPoller class that could cause some configuration files to not be read in at system startup.
@brjeter 
@oconnormi 
@figliold
@pklinef
Full builds including all integration tests.
[DDF-2759](https://codice.atlassian.net/browse/DDF-2759)
> DDF-2759: Feature configuration files are not always being processed

- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/OverrideAttributesSupport.java
- catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/impl/operations/OverrideAttributesSupportTest.java
- catalog/plugin/catalog-plugin-content-uri/src/main/java/org/codice/ddf/catalog/content/plugin/uri/ContentUriAccessPlugin.java
- catalog/plugin/catalog-plugin-content-uri/src/test/java/org/codice/ddf/catalog/content/plugin/uri/ContentUriAccessPluginTest.java
- catalog/rest/catalog-rest-endpoint/src/main/java/org/codice/ddf/endpoints/rest/RESTEndpoint.java
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalog.java
- Fix resource-uri being overriden by null update
@emmberk @troymohl @brendan-hofmann 
@pklinef
@stustison
Full Build.
Existing `Metacard`'s URIs should not be able to be overridden in order to prevent resources with no references to it.
[DDF-2745](https://codice.atlassian.net/browse/DDF-2745)
> DDF-2745: Fix resource-uri being overriden by null update

- catalog/core/catalog-core-federationstrategy/src/test/java/ddf/catalog/federation/impl/FederationStrategyTest.java
- Increases the timeout on a unit test that failed.
- Added timeout to other unit tests that previously could get stuck waiting forever.
@Lambeaux @oconnormi 
@figliold 
@lessarderic 
Run `FederationStrategyTest`
[DDF-2761](https://codice.atlassian.net/browse/DDF-2761)
> DDF-2761: Solving unit test multithreading issue

- platform/persistence/platform-persistence-commands/src/main/java/org/codice/ddf/persistence/commands/AbstractStoreCommand.java
- platform/persistence/platform-persistence-core-api/src/main/java/org/codice/ddf/persistence/PersistentStore.java
Added subscriptions persistence store type to persistence store commands.  The subscriptions store was introduced with Catalog UI for email notifications on a workspace.
@bdeining @rzwiefel 
@kcwire
1) Create one or more email notification subscriptions by subscribing to workspaces.
2) Verify persistence store commands:
store:list -t subscriptions
store:delete -t subscriptions
[](https://codice.atlassian.net/browse/DDF-2644)
> DDF-2644 Added subscriptions persistence store type to commands

- catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.config.xml
- catalog/ui/search-ui-app/src/main/resources/etc/org.codice.ddf.catalog.ui.config
- catalog/ui/search-ui/standard/src/main/java/org/codice/ddf/ui/searchui/standard/properties/ConfigurationStore.java
- catalog/ui/search-ui/standard/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/ui/search-ui/standard/src/main/resources/OSGI-INF/metatype/metatype.xml
- distribution/docs/src/main/resources/_contents/_tables/org.codice.ddf.catalog.ui.config-table-contents.adoc
Removes the bluemarble tile layer and have the cesium globe rely on the default Natural Earth image.
@clockard @gordocanchola @vinamartin @brianfelix @emmberk @taz77 @cruzj6 
[UI](https://github.com/orgs/codice/teams/ui) @garrettfreibott 
@pklinef 
Install a default DDF, then load the Search UIs and confirm the static Natural Earth image is visible on the cesium globe. 
The Standard and Catalog UIs had a default bluemarble WMS tile server configured that was unreliable and lead to no globe appearing at all. This tile server was removed, but not replaced since additional considerations would have to be made regarding proper attribution and usage of alternatives. Natural Earth maps are in the public domain, require no permission and no attribution. …
> DDF-2739 Remove default bluemarble WMS tile server

- distribution/docs/src/main/resources/_contents/_tables/org.codice.ddf.distribution.landing-page.properties-table-contents.adoc
Removes an incorrect line in the Landing Page documentation. The format is strictly enforced on the landing page so prior to this change this documentation did not reflect the actual behavior.
@spearskw @brendan-hofmann 
@ricklarsen 
@coyotesqrl
@figliold 
Follow the documentation instructions for configuring the landing page with this update, and verify that using the given format works.
[](https://codice.atlassian.net/browse/DDF-2766)
> DDF-2766 Removes incorrect line from Landing Page docs

- platform/admin/ui/src/main/webapp/less/installer/style.less
-Makes the selector more specific so that configurations with "Description" fields don't appear grayed out
@djblue @tbatie 
@lessarderic
Make sure the tiles on the admin console still show up with gray descriptions, however, in the configuration for the landing page, the description field should show up black.
[](https://codice.atlassian.net/browse/DDF-2772)
> DDF-2772 Fixes gray appearance for "Description" field in configs

- catalog/spatial/registry/registry-admin-modules/registry-admin-remote-ui/src/main/webapp/js/HandlebarsHelpers.js
Replaces the use of the .includes() javascript function in the Remote Registry modal. This function is not supported by Internet Explorer and would cause the modal not to open.
@clockard @brianfelix @vinamartin @gordocanchola @emmberk @cruzj6 @taz77 
[UI](https://github.com/orgs/codice/teams/ui) @garrettfreibott 
@pklinef 
Boot DDF and install the Registry, then navigate to the Remote Registries tab in the Registry App. Click the `+` button to Add a remote Registry. The modal should open and the browser console should be free of .include( errors.
This change is specifically for IE10, but should be confirmed in Chrome & FF.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes#Browser_compatibility …
> DDF-2057 Replace use of .includes function in handlebars with .indexOf for IE compatibility

- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/CachingFederationStrategy.java
- distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/AbstractIntegrationTest.java
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFederation.java
Fixes CachingFederationStrategy so metacard cache queries will have the right source ids.
@bdeining @mcalcote 
@pklinef
@shaundmorris
Verify itests pass
[](https://codice.atlassian.net/browse/DDF-2612)
> DDF-2612 Fixed CachingFederationStrategy source id issue and added itest to verify cache works

- catalog/core/catalog-core-api/src/main/java/ddf/catalog/data/types/Associations.java
- distribution/docs/src/main/resources/_contents/_data/associations-attributes-table-contents.adoc
DDF-2776 Change constant for Associations.EXTERNAL from metacard.associations.external to associations.external
@brendan-hofmann @rzwiefel 
@coyotesqrl
@figliold 
[DDF-2776](https://codice.atlassian.net/browse/)
> DDF-2776 Change constant for Associations.EXTERNAL from metacard.associations.external to associations.external

- catalog/ui/catalog-ui-search/src/main/webapp/js/QueryPolling.js
- catalog/ui/catalog-ui-search/src/main/webapp/js/model/Query.js
- catalog/ui/catalog-ui-search/src/main/webapp/js/model/Sources.js
- Previously they only retried when the network request failed.  Now they will retry if the request succeeded, but the query status says unsuccessful.
- Also updates the Sources polling to continueOnError rather than stop.
- Updates Source polling to not begin immediately, since we fetch immediately.
@djblue 
@rzwiefel 
@jlcsmith 
@pklinef 
Add a standing search.  Cause it to fail but still return a 200.  Ensure that when queries can once again run successfully, a retry is made for the failed time range.
Previously the retries were only made when network requests outright failed.  Now they will happen if the status of a query is unsuccessful as well.
https://codice.atlassian.net/browse/DDF-2763
> DDF-2763 Updates standing searches to retry when query status is unsuccessful

- catalog/ui/catalog-ui-search/package.json
- catalog/ui/catalog-ui-search/src/main/webapp/index.html
- catalog/ui/catalog-ui-search/src/main/webapp/less/components/bootstrapDatepicker.less
- catalog/ui/catalog-ui-search/webpack/config/base.js
- catalog/ui/catalog-ui-search/yarn.lock
- The datepicker was switched from being resolved through bower to being resolved through npm recently, with https://github.com/codice/ddf/commit/fc8a567a9e76f4020cbe7f2a92b1d37b3939d470
- Unfortunately, the css has been missing since that commit.  When I added the css back in using webpack, I noticed the datepicker had some regressions.  As such, I rolled it back to the original bower version.
@pklinef 
@djblue 
@rzwiefel 
@tbatie 
Check out the Catalog UI and ensure the datepicker has the correct css.
> DDF-2644 Fixes issue with datepicker dependency that was switched to npm

- catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/CachingFederationStrategy.java
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFederation.java
Reverts the change to CachingFederationStrategy that fixed the caching query but broke the enterprize query.
@brendan-hofmann @emanns95 
@pklinef
@stustison
[DDF-2612](https://codice.atlassian.net/browse/)
> DDF-2612 Revert CachingFederationStrategy cache fix.

- catalog/schematron/catalog-schematron-plugin/src/main/java/ddf/services/schematron/SchematronReport.java
- catalog/schematron/catalog-schematron-plugin/src/main/java/ddf/services/schematron/SchematronValidationService.java
- catalog/schematron/catalog-schematron-plugin/src/main/java/ddf/services/schematron/SvrlReport.java
- catalog/schematron/catalog-schematron-plugin/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/schematron/catalog-schematron-plugin/src/test/java/ddf/services/schematron/SchematronValidationServiceTest.java
The validation  errors and warnings do not show on the "Quality" tab of the catalog search UI because the schema and schematron validators do not implement the ReportingMetacardValidator interface.
Implements the ReportingMetacardValidator in several classes and updates their service definitions.
@emanns95 
@AzGoalie 
@mweser 
@rzwiefel 
@pklinef
Ingest files with schema or schematron warnings.
Retrieve them as metacards in the catalog search UI.
Navigate to the "Quality" tab on the results page.
The expected result is that the warnings are displayed in the tab.
https://codice.atlassian.net/browse/DDF-2769
> DDF-2769 Validation problems not shown in Search UI "Quality" tab

- distribution/docs/src/main/resources/_contents/_installing/installing-intro-contents.adoc
- distribution/docs/src/main/resources/_contents/_running/starting-intro-contents.adoc
Updates the documentation to show that the `-h localhost` option must be used on Windows when running `client.bat`.
Also addressed a few other minor issues in the installation documentation related to Windows.
@Joy603 
@brjeter 
@ricklarsen 
@figliold
@kcwire
Build the documentation and make sure information is accurate.
[DDF-2774](https://codice.atlassian.net/browse/DDF-2774)
> DDF-2774: client.bat script does not give access to the DDF console

- distribution/ddf-common/src/main/resources/etc/system.properties
Moved Karaf's lock file from home directory to home/instances so that a user without write permissions in the home directory (such as on a hardened system) can run ddf.
@mcalcote @clockard @gordocanchola @vinamartin
@stustison 
@pklinef 
@stustison
[](https://codice.atlassian.net/browse/DDF-2782)
> DDF-2782: Moved the location of Karaf's lock file

- catalog/core/catalog-core-directorymonitor/pom.xml
- catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/ContentDirectoryMonitor.java
- catalog/core/catalog-core-directorymonitor/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/core/catalog-core-directorymonitor/src/main/resources/OSGI-INF/metatype/metatype.xml
- catalog/core/catalog-core-directorymonitor/src/test/java/org/codice/ddf/catalog/content/monitor/ContentDirectoryMonitorTest.java
- distribution/docs/src/main/resources/_contents/_resources/content-directory-monitor-contents.adoc
This PR adds the ability to specify how many threads to use when configuring a Content Directory Monitor so files can be consumed in parallel.  It also reduces the default size of the readLockInterval to a more reasonable value. 
@jlcsmith
@kcwire
Build / Install / configure CDM with multiple threads / Observe Parallel Processing 
[DDF-2331](https://codice.atlassian.net/browse/DDF-2331)
> DDF-2331 Made thread pool and readLockInterval configurable in Content Directory Monitor

- catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.config.xml
- catalog/ui/search-ui-app/src/main/resources/etc/org.codice.ddf.catalog.ui.config
removes unnecessary hidden attributes
@mcalcote 
@jlcsmith
> DDF-2644 remove unecessary hidden attributes

- catalog/ui/catalog-ui-search/package.json
- catalog/ui/catalog-ui-search/yarn.lock
- Update Cesium from 1.26.0 to 1.30.0 to fix issue seen in https://github.com/AnalyticalGraphicsInc/cesium/issues/4563
@tbatie 
@figliold
@lessarderic
Verify map still works as expected.  It's possible new regressions were introduced, however I didn't notice any.  
https://github.com/AnalyticalGraphicsInc/cesium/issues/4563
https://codice.atlassian.net/browse/DDF-2780
> DDF-2780 Update to latest Cesium

- catalog/spatial/csw/spatial-csw-source/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/spatial/wfs/1.0.0/spatial-wfs-v1_0_0-source/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/main/resources/OSGI-INF/blueprint/blueprint.xml
Sets the default value of the forceSpatialFilter property of a CSW source instead of leaving it null.
@tbatie @bdeining @djblue 
@coyotesqrl
@kcwire
This default value prevents the successful creation of CSW sources that do not specifically assign this value and do not use the Admin Console source creator (Where it's populated via the metatype).
[DDF-2765](https://codice.atlassian.net/browse/)
> DDF-2765 CSW and WFS forceSpatialFilter should default to NO_FILTER instead of null

- catalog/ui/catalog-ui-search/src/main/webapp/lib/cesium-drawhelper/DrawHelper.js
- https://github.com/codice/ddf/pull/1534 made a change to DrawHelper which allowed drawings at higher zooms to work.  However, DrawHelper was relying on this to remove the extra points that occur when finishing a drawing.  As a result, we need to remove the final two points on all polygon / line drawings.
@djblue 
@pklinef 
Create line and polygon drawings in Cesium and verify that they contain only the number of points you that were drawn.  
https://codice.atlassian.net/browse/DDF-2779
> DDF-2779 Remove extra points from line / polygon drawings in Cesium

- catalog/ui/catalog-ui-search/src/main/webapp/js/model/Metacard.js
Old code assumed that there would always have a preceding parameter before adding the timestamp, this PR updates to remove that assumption.
@djblue @garrettfreibott 
@pklinef 
Build catalog-ui-search
[](https://codice.atlassian.net/browse/DDF-2787)
> DDF-2787- Updates how thumbnail action url is generated

- catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/util/impl/CachedSource.java
Simplifies `equals()` and `hashcode()` methods so they remain invariant.
@coyotesqrl
@pklinef
@stustison
Unit tests for the `catalog-core-standardframework` bundle on machines of varying speed should all pass.
> DDF-2789 Updates equals and hashcode methods on CachedSource so they remain invariant.

- catalog/transformer/catalog-transformer-streaming-api/src/main/java/org/codice/ddf/transformer/xml/streaming/SaxEventHandler.java
- catalog/transformer/catalog-transformer-streaming-api/src/main/java/org/codice/ddf/transformer/xml/streaming/SaxEventHandlerFactory.java
- catalog/transformer/catalog-transformer-streaming-impl/src/main/java/org/codice/ddf/transformer/xml/streaming/impl/GmlHandler.java
- catalog/transformer/catalog-transformer-streaming-impl/src/main/java/org/codice/ddf/transformer/xml/streaming/impl/GmlHandlerFactory.java
- catalog/transformer/catalog-transformer-streaming-impl/src/main/java/org/codice/ddf/transformer/xml/streaming/impl/XmlSaxEventHandlerFactoryImpl.java
- catalog/transformer/catalog-transformer-streaming-impl/src/main/java/org/codice/ddf/transformer/xml/streaming/impl/XmlSaxEventHandlerImpl.java
- catalog/transformer/catalog-transformer-streaming-impl/src/test/java/org/codice/ddf/transformer/xml/streaming/impl/TestXmlInputTransformer.java
- catalog/transformer/catalog-transformer-streaming-lib/pom.xml
- catalog/transformer/catalog-transformer-streaming-lib/src/main/java/org/codice/ddf/transformer/xml/streaming/lib/SaxEventHandlerDelegate.java
- catalog/transformer/catalog-transformer-streaming-lib/src/main/java/org/codice/ddf/transformer/xml/streaming/lib/SaxEventHandlerUtils.java
- catalog/transformer/catalog-transformer-streaming-lib/src/main/java/org/codice/ddf/transformer/xml/streaming/lib/XmlInputTransformer.java
- catalog/transformer/catalog-transformer-streaming-lib/src/test/java/org/codice/ddf/transformer/xml/streaming/lib/SaxEventHandlerUtilsTest.java
- catalog/transformer/catalog-transformer-streaming-lib/src/test/java/org/codice/ddf/transformer/xml/streaming/lib/TestGenericXmlLib.java
This ticket moves the getSupportedAttributeDescriptors methods from the SaxEventHandlerFactories to the SaxEventHandlers. This move is needed in the case where handler data determines the attribute descriptors.
This ticket also changes the SaxEventHandlerDelegate to no longer put duplicate attributes on a metacard blindly. It now checks the AttributeDescriptor's multivalued flag to see if having multiple values is permitted. If multivalued is false it just keeps the first value, ignoring any following ones. 
This PR also splits the delegates read method into read and getMetacard methods.
@clockard @kcwire @mcalcote 
@pklinef
@shaundmorris
Removing getSupportedAttributeDescriptors …
> DDF-2740 Update SaxEventHandlers to return attribute descriptors

- catalog/ui/catalog-ui-search/src/main/webapp/js/ApplicationStart.js
- Starting before then could cause issues with routing to notifications, or inconsistencies in the display username.
- We were already waiting for the initial workspace fetch, so this adds on to that.  Now we wait for both the initial workspace and the initial user fetch before starting.
@djblue 
@rzwiefel 
@pklinef 
Cause a notification (such as by uploading).  Make sure your settings have persistent notifications. Go to it. Refresh. Test with network latency to see the improvement from the old way.
Another way is to add setTimeouts into the code around the initial fetches to see the app wait for them to complete.
https://codice.atlassian.net/browse/DDF-2781
> DDF-2781 Update app to start only after initial user fetch

- catalog/ui/catalog-ui-search/src/main/webapp/component/slideout/left/slideout.left.less
- catalog/ui/catalog-ui-search/src/main/webapp/component/slideout/right/slideout.right.less
- catalog/ui/catalog-ui-search/src/main/webapp/component/slideout/slideout.less
- catalog/ui/catalog-ui-search/src/main/webapp/component/workspaces-templates/workspaces-templates.less
- catalog/ui/catalog-ui-search/src/main/webapp/js/application.js
- catalog/ui/catalog-ui-search/src/main/webapp/less/components/content.less
- catalog/ui/catalog-ui-search/src/main/webapp/less/components/headerAndFooter.less
- catalog/ui/catalog-ui-search/src/main/webapp/less/components/init.less
- catalog/ui/catalog-ui-search/src/main/webapp/less/components/loading.less
- catalog/ui/catalog-ui-search/src/main/webapp/templates/footer.layout.handlebars
- catalog/ui/catalog-ui-search/src/main/webapp/templates/header.layout.handlebars
- Previously, the header and footer didn't take into account the current user's zoom.  Now they do.  Various updates to css to take this into account.
- Simplified the header and footer templates.  Updated their regions to use replace element to simplify things further.  Added a tooltip in case the text is cut off.
@Lambeaux 
@pklinef
Add a header using the Platform config.  Verify it shows up in the Catalog UI, and that it resizes correctly during zoom changes.  Also open each of the slideouts and verify they adjust accordingly with the header.  Verify that you can scroll all the way to the bottom of the templates when they are expanded.
Add a footer and reverify.
Remove the header and reverify.
https://codice.atlassian.net/browse/DDF-2786
> DDF-2786 Fix issue with header and footer during zoom

- catalog/ui/catalog-ui-search/src/main/webapp/component/slideout/left/slideout.left.less
- catalog/ui/catalog-ui-search/src/main/webapp/component/slideout/right/slideout.right.less
- catalog/ui/catalog-ui-search/src/main/webapp/component/slideout/slideout.less
- catalog/ui/catalog-ui-search/src/main/webapp/component/workspaces-templates/workspaces-templates.less
- catalog/ui/catalog-ui-search/src/main/webapp/js/application.js
- catalog/ui/catalog-ui-search/src/main/webapp/less/components/content.less
- catalog/ui/catalog-ui-search/src/main/webapp/less/components/headerAndFooter.less
- catalog/ui/catalog-ui-search/src/main/webapp/less/components/init.less
- catalog/ui/catalog-ui-search/src/main/webapp/less/components/loading.less
- catalog/ui/catalog-ui-search/src/main/webapp/templates/footer.layout.handlebars
- catalog/ui/catalog-ui-search/src/main/webapp/templates/header.layout.handlebars
- Previously, the header and footer didn't take into account the current user's zoom.  Now they do.  Various updates to css to take this into account.
- Simplified the header and footer templates.  Updated their regions to use replace element to simplify things further.  Added a tooltip in case the text is cut off.
@Lambeaux 
@pklinef
Add a header using the Platform config.  Verify it shows up in the Catalog UI, and that it resizes correctly during zoom changes.  Also open each of the slideouts and verify they adjust accordingly with the header.  Verify that you can scroll all the way to the bottom of the templates when they are expanded.
Add a footer and reverify.
Remove the header and reverify.
https://codice.atlassian.net/browse/DDF-2786
> (2.10.x) DDF-2786 Fix issue with header and footer during zoom

- catalog/core/catalog-core-actions/src/main/java/org/codice/ddf/catalog/actions/AbstractMetacardActionProvider.java
- catalog/core/catalog-core-actions/src/test/java/org/codice/ddf/catalog/actions/AbstractMetacardActionProviderTest.java
- catalog/rest/catalog-rest-endpoint/src/test/java/org/codice/ddf/endpoints/rest/action/TestMetacardTransformerActionProvider.java
- catalog/rest/catalog-rest-endpoint/src/test/java/org/codice/ddf/endpoints/rest/action/TestViewMetacardActionProvider.java
- catalog/spatial/registry/registry-ebrim-transformer/src/main/resources/OSGI-INF/blueprint/blueprint.xml
Adds service property to the RegistryTransformer service so it doesn't get displayed as an action for normal metacards. Updated the AbstractMetacardActionProvider so it will only return true for canHandle if the metacard is a resource metacard. Non resource metacards would fail if these actions were attempted.
@mcalcote @gordocanchola 
@figliold
@pklinef
Install DDF, include the Registry in the  install.
In the Admin UI Standard Search UI->Catalog UI Search remove 'metacard-tags' from the Hidden Fields. 
Go to the Catalog UI and upload a file. 
Perform a search and go to the actions tab of that result and verify that Export as rim:RegistryPackage is not present.
Update your search by going to the advanced tab and adding another …
> DDF-2775 Update to ensure actions displayed in the catalog/search ui are appropriate for the metacards tag.

- catalog/catalog-app/pom.xml
- catalog/catalog-app/src/main/resources/features.xml
- catalog/plugin/catalog-plugin-pointofcontactupdate/pom.xml
- catalog/plugin/catalog-plugin-pointofcontactupdate/src/main/java/org/codice/ddf/catalog/plugin/metacard/PointOfContactUpdatePlugin.java
- catalog/plugin/catalog-plugin-pointofcontactupdate/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/plugin/catalog-plugin-pointofcontactupdate/src/test/java/org/codice/ddf/catalog/plugin/metacard/PointOfContactUpdatePluginTest.java
- catalog/plugin/pom.xml
- catalog/security/catalog-security-plugin/src/main/java/ddf/catalog/security/plugin/SecurityPlugin.java
- catalog/security/catalog-security-plugin/src/test/java/ddf/catalog/security/plugin/SecurityPluginTest.java
- catalog/security/catalog-security-pointofcontact-policyplugin/pom.xml
- catalog/security/catalog-security-pointofcontact-policyplugin/src/main/java/org/codice/ddf/catalog/security/policy/metacard/PointOfContactPolicyPlugin.java
- catalog/security/catalog-security-pointofcontact-policyplugin/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/security/catalog-security-pointofcontact-policyplugin/src/test/java/org/codice/ddf/catalog/security/policy/metacard/PointOfContactPolicyPluginTest.java
- catalog/security/pom.xml
- catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.config.xml
- catalog/ui/search-ui-app/src/main/resources/etc/org.codice.ddf.catalog.ui.config
- distribution/test/itests/test-itests-common/src/main/resources/definitions.json
- distribution/test/itests/test-itests-common/src/main/resources/json/record/SimpleGeoJsonRecord
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalog.java
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalogSearchUi.java
Makes the Point of Contact field read-only and fixes `point-of-contact` to be set to the email and only when it's a resource metacard.
Note: This is the first PR for this ticket. The second one will depend on this one.
@Lambeaux @figliold @shaundmorris 
@lessarderic 
@stustison
- Build and deploy DDF
- Ingest a metacard
- Verify in the Catalog UI that the metacard's `Point of Contact` field is set to the email address of current user (i.e. admin@localhost.local if signed in as admin) and that the field is read-only.
- Go to the Catalog UI configurations in the AdminUI and remove `point-of-contact` from the list of read-only attributes. Save.
- Go back to the Catalog UI and try to edit the `Point of Contact` field on the metacard. …
> [2.10.x]DDF-2715: Making Point of Contact read-only

- distribution/docs/src/main/resources/_contents/_securing/managing-certificates-contents.adoc
- distribution/docs/src/main/resources/_contents/_sources/confluence-federated-source-contents.adoc
- distribution/docs/src/main/resources/_contents/_sources/federated-sources-contents.adoc
- distribution/docs/src/main/resources/documentation.adoc
updates federated sources to include confluence source docs.
@Lambeaux @vinamartin @mcalcote @jrnorth @ahoffer @clockard 
@coyotesqrl
@pklinef
@shaundmorris
Verify confluence docs present in docs.
[DDF-2802](https://codice.atlassian.net/browse/DDF-2802)
> DDF-2802 fix for confluence source docs (2.10.x)

- catalog/core/catalog-core-camelcomponent/src/main/java/ddf/camel/component/catalog/content/ContentProducerDataAccessObject.java
- catalog/core/catalog-core-camelcomponent/src/test/java/ddf/camel/component/catalog/content/ContentProducerDataAccessObjectTest.java
- catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/ContentDirectoryMonitor.java
- catalog/core/catalog-core-directorymonitor/src/main/resources/OSGI-INF/metatype/metatype.xml
- catalog/core/catalog-core-directorymonitor/src/test/java/org/codice/ddf/catalog/content/monitor/ContentDirectoryMonitorTest.java
Pass in map of attribute overrides to routeDefinition instead of comma-separated string to ensure attributes with commas do not cause an error
@ryeats 
@coyotesqrl
@millerw8 
* Monitor a directory
* Set an attribute override of `location=Polygon((10 10, 10 20, 20 20, 20 10, 10 10 ))`
* Check that the override works for files placed in the directory (`catalog:inspect metacard`)
[DDF-2795](https://codice.atlassian.net/browse/DDF-2795)
> DDF-2795 Fix attribute overrides in directory monitor causing an error if the value has a comma

- distribution/docs/src/main/resources/_contents/_securing/environment-hardening-contents.adoc
2.10.x port from https://github.com/codice/ddf/pull/1690
Added a row to the Environment Hardening suggestions that describes how to update the Session Timeout to the recommended 10 minutes.
@ricklarsen @ahoffer 
[Docs](https://github.com/orgs/codice/teams/docs) @Lambeaux 
@shaundmorris
@stustison
Read the changes, observe the generated table.
[DDF-2804](https://codice.atlassian.net/browse/DDF-2804)
(PDF)
> DDF-2804 -> 2.10.x Update hardening guide to recommend 10 minute session timeout

- catalog/spatial/registry/registry-policy-plugin/src/main/java/org/codice/ddf/registry/policy/RegistryPolicyPlugin.java
- catalog/spatial/registry/registry-policy-plugin/src/test/java/org/codice/ddf/registry/policy/RegistryPolicyPluginTest.java
- distribution/test/itests/test-itests-common/src/main/resources/csw-rim-node.xml
- platform/security/platform-security-core-api/src/main/java/ddf/security/permission/Permissions.java
This change adds additional user defined security attributes from the Security Attributes field on the node information modal to the item policy that is generated in the RegistryPolicyPlugin. 
@clockard @emmberk @vinamartin @brianfelix @gordocanchola 
[Security](https://github.com/orgs/codice/teams/security) @adimka 
@coyotesqrl
@stustison
Set up a DDF Registry with the Security Attributes set on the General Information tab of the local node, then try to connect to it with a second DDF without the same security attributes. The registry node should not get pulled (though the connection should return a response).
Further considerations will have to be made for any other elements of a local node that can have Security Attributes assigned. …
> DDF-2794 Adjusted RegistryPolicyPlugin to set user defined security attributes on the item policy

- catalog/ui/catalog-ui-search/pom.xml
Add Jetty dependency to Catalog UI Search pom.xml
This removes an exception in the log relating to GzipFilters being deprecated.
@ahoffer @brendan-hofmann @emanns95 @spearskw 
@shaundmorris
@stustison
Simple build to verify UI is loaded correctly in admin UI.
[](https://codice.atlassian.net/browse/DDF-2806)
> DDF-2806 Add Jetty dependency to Catalog UI Search pom.xml

- distribution/test/itests/test-itests-common/src/main/resources/TestSpatial/csw/request/query/CswCompoundNot.xml
- distribution/test/itests/test-itests-common/src/main/resources/TestSpatial/csw/request/query/CswCompoundNotBeforeDateAndLikeText.xml
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestSpatial.java
This PR adds 2 integration tests for ogc:NOT filters in TestSpatial to prevent any regressions.
@troymohl @rzwiefel 
@jrnorth 
@kcwire
@millerw8
Build DDF
[DDF-2808](https://codice.atlassian.net/browse/DDF-2808)
> DDF-2808 Added integration test for ogc:Not filters

- catalog/spatial/registry/registry-policy-plugin/src/main/java/org/codice/ddf/registry/policy/RegistryPolicyPlugin.java
- catalog/spatial/registry/registry-policy-plugin/src/test/java/org/codice/ddf/registry/policy/RegistryPolicyPluginTest.java
- distribution/test/itests/test-itests-common/src/main/resources/csw-rim-node.xml
- platform/security/platform-security-core-api/src/main/java/ddf/security/permission/Permissions.java
Port of https://github.com/codice/ddf/pull/1678
This change adds additional user defined security attributes from the Security Attributes field on the node information modal to the item policy that is generated in the RegistryPolicyPlugin. 
Permissions.java was also updated to trim whitespace from security attributes.
@clockard @emmberk @vinamartin @brianfelix @gordocanchola 
[Security](https://github.com/orgs/codice/teams/security) @adimka 
@coyotesqrl
@stustison
Set up a DDF Registry with the Security Attributes set on the General Information tab of the local node, then try to connect to it with a second DDF without the same security attributes. The registry node should not get pulled (though the connection should return a response).
Further considerations will have to be made for any …
> DDF-2794 -> 2.10.x Adjusted RegistryPolicyPlugin to set user defined security attributes on the item policy

- catalog/core/catalog-core-camelcomponent/src/main/java/ddf/camel/component/catalog/content/ContentProducerDataAccessObject.java
- catalog/core/catalog-core-camelcomponent/src/test/java/ddf/camel/component/catalog/content/ContentProducerDataAccessObjectTest.java
- catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/ContentDirectoryMonitor.java
- catalog/core/catalog-core-directorymonitor/src/main/resources/OSGI-INF/metatype/metatype.xml
- catalog/core/catalog-core-directorymonitor/src/test/java/org/codice/ddf/catalog/content/monitor/ContentDirectoryMonitorTest.java
Pass in map of attribute overrides to routeDefinition instead of comma-separated string to ensure attributes with commas do not cause an error
@ryeats 
@coyotesqrl
@jlcsmith  
* Monitor a directory
* Set an attribute override of `location=Polygon((10 10, 10 20, 20 20, 20 10, 10 10 ))`
* Check that the override works for files placed in the directory (`catalog:inspect metacard`)
[DDF-2795](https://codice.atlassian.net/browse/DDF-2795)
> [Backport] DDF-2795 Fix attribute overrides in directory monitor causing an error if the value has a comma

- catalog/transformer/catalog-transformer-streaming-api/src/main/java/org/codice/ddf/transformer/xml/streaming/SaxEventHandler.java
- catalog/transformer/catalog-transformer-streaming-api/src/main/java/org/codice/ddf/transformer/xml/streaming/SaxEventHandlerFactory.java
- catalog/transformer/catalog-transformer-streaming-impl/src/main/java/org/codice/ddf/transformer/xml/streaming/impl/GmlHandler.java
- catalog/transformer/catalog-transformer-streaming-impl/src/main/java/org/codice/ddf/transformer/xml/streaming/impl/GmlHandlerFactory.java
- catalog/transformer/catalog-transformer-streaming-impl/src/main/java/org/codice/ddf/transformer/xml/streaming/impl/XmlSaxEventHandlerFactoryImpl.java
- catalog/transformer/catalog-transformer-streaming-impl/src/main/java/org/codice/ddf/transformer/xml/streaming/impl/XmlSaxEventHandlerImpl.java
- catalog/transformer/catalog-transformer-streaming-impl/src/test/java/org/codice/ddf/transformer/xml/streaming/impl/TestXmlInputTransformer.java
- catalog/transformer/catalog-transformer-streaming-lib/pom.xml
- catalog/transformer/catalog-transformer-streaming-lib/src/main/java/org/codice/ddf/transformer/xml/streaming/lib/SaxEventHandlerDelegate.java
- catalog/transformer/catalog-transformer-streaming-lib/src/main/java/org/codice/ddf/transformer/xml/streaming/lib/SaxEventHandlerUtils.java
- catalog/transformer/catalog-transformer-streaming-lib/src/main/java/org/codice/ddf/transformer/xml/streaming/lib/XmlInputTransformer.java
- catalog/transformer/catalog-transformer-streaming-lib/src/test/java/org/codice/ddf/transformer/xml/streaming/lib/SaxEventHandlerUtilsTest.java
- catalog/transformer/catalog-transformer-streaming-lib/src/test/java/org/codice/ddf/transformer/xml/streaming/lib/TestGenericXmlLib.java
This ticket is the back port of the following functionality.
This ticket moves the getSupportedAttributeDescriptors methods from the SaxEventHandlerFactories to the SaxEventHandlers. This move is needed in the case where handler data determines the attribute descriptors.
This ticket also changes the SaxEventHandlerDelegate to no longer put duplicate attributes on a metacard blindly. It now checks the AttributeDescriptor's multivalued flag to see if having multiple values is permitted. If multivalued is false it just keeps the first value, ignoring any following ones.
This PR also splits the delegates read method into read and getMetacard methods.
@clockard @mcalcote 
@pklinef …
> DDF-2740 (2.10.1 back port) Update SaxEventHandlers to return attribute descriptors

- catalog/ui/catalog-ui-search/src/main/webapp/js/CQLUtils.js
- catalog/ui/catalog-ui-search/src/main/webapp/js/widgets/cesium.polygon.js
backport of https://github.com/codice/ddf/pull/1647
> (2.10.x) DDF-2785 Prevents duplicate points from being added onto the ends of polygons

- catalog/ui/catalog-ui-search/src/main/webapp/lib/cesium-drawhelper/DrawHelper.js
Backport of https://github.com/codice/ddf/pull/1647
> (2.10.x) DDF-2779 Remove extra points from line / polygon drawings in Cesium

- catalog/ui/catalog-ui-search/src/main/webapp/component/sort-item/sort-item.view.js
- catalog/ui/catalog-ui-search/src/main/webapp/component/visualization/table/thead.view.js
- catalog/ui/catalog-ui-search/src/main/webapp/js/model/Metacard.js
- Updates sorting to always push null or undefined values to the end of a sort (regardless of ascending or descending).
- Blanks are handled as they should by the particular datatype.  Hence, for a String type ascending puts them at the top, and descending at the bottom.
- Updated string comparisons to be case insensitive to better fit user expectations.
- Fixed issues where certain attributes were sortable from the normal sort view, but not from the table view.
@jlcsmith 
@bdeining 
@rzwiefel 
Ingest some varied data.  Start testing various sorts.  Confirm that attributes with null or undefined values are always pushed to the end of a sort (regardless of ascending or descending).  
https://codice.atlassian.net/browse/DDF-2792
> DDF-2792 Update client side sorting to handle null / blank values more consistently

- catalog/transformer/catalog-transformer-tika-input/src/main/resources/OSGI-INF/blueprint/blueprint.xml
This PR adds AssociationsAttributes to fallback Tika MetacardTypes so they can be seen in the Catalog UI
@mcalcote @brianfelix 
@pklinef
@stustison
Build / Install / Ingest Tika Content / Verify Associations work
[DDF-2645](https://codice.atlassian.net/browse/DDF-2645)
> (2.10.x) DDF-2645 Added Associations Attributes to Tika Input Transformer fallback MetacardTypes

- catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/SolrFilterDelegate.java
- catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/SolrFilterDelegateTest.java
Fixes a problem where simple polygons (like rectangles) were getting converted into simpler WKT shapes that were not recognized by other classes.
@lessarderic
@shaundmorris
Verify unit and itests pass on DDF and downstream projects
[DDF-2814](https://codice.atlassian.net/browse/DDF-2814)
> DDF-2814 Fix SolrFilterDelegate to not convert polygons into simpler shapes

- distribution/ddf-common/src/main/resources/etc/org.ops4j.pax.url.mvn.cfg
Fixes KAR hot deployment and prevents Karaf from using the local machine's Maven settings.xml file and repository.
_Please note that when hot deploying, a WARN message similar to the following will now appear in the log:_
```
07:57:26,274 | WARN  | pool-2-thread-1  | n.internal.config.MavenConfigurationImpl  177 | ging.pax-logging-api | Settings file [thisdirectorydoesnotexist/settings.xml] cannot be used and will be skipped (malformed url or file does not exist)
```
@rzwiefel @brendan-hofmann 
@lessarderic
@stustison
On a production box, or one where your local `.m2` directory has been removed, attempt to hot deploy a KAR. It should succeed (assuming it is a correctly constructed KAR).
N/A
[DDF-2830](https://codice.atlassian.net/browse/DDF-2830)
N/A
> DDF-2830 [2.10.x] Updates the local repository list Karaf searches to support hot deployment

- CHANGES.md
- distribution/docs/src/main/resources/_contents/_security-contents/managing-security-contents.adoc
- distribution/docs/src/main/resources/_contents/_tables/conf-org.codice.ddf.security.response.filter.ResponseHeaderConfig-table-contents.adoc
- distribution/docs/src/main/resources/_contents/_tables/org.codice.ddf.security.response.filter.ResponseHeaderConfig.adoc
- platform/security/filter/pom.xml
- platform/security/filter/security-filter-response/pom.xml
- platform/security/filter/security-filter-response/src/main/java/org/codice/ddf/security/response/filter/ResponseSecurityFilter.java
- platform/security/filter/security-filter-response/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- platform/security/filter/security-filter-response/src/main/resources/OSGI-INF/metatype/metatype.xml
- platform/security/security-services-app/pom.xml
- platform/security/security-services-app/src/main/resources/features.xml
A configurable servlet filter was added that attaches content security policy, x frame options and xss protection headers to responses.
@clockard @emmberk @vinamartin @brianfelix @ricklarsen 
[Security](https://github.com/orgs/codice/teams/security) @bdeining 
@stustison
Install DDF and load into the Admin UI. Using the developer tools built into the browser, inspect the response headers as the pages load. Confirm the new response headers are present (CSP, XSS, XFrame)
Navigate to the Security App, Configuration Tab and update the HTTP Response Security config values. Load the Catalog UI and check the response headers as the page loads.
https://www.owasp.org/index.php/Content_Security_Policy
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection …
> DDF-2817 A configurable servlet filter now attaches content security policy, xss protection and x-frame-options headers to responses

- README.md
- catalog/core/catalog-core-standardframework/pom.xml
- catalog/spatial/geocoding/spatial-geocoding-geocoder/pom.xml
- catalog/ui/search-ui/standard/pom.xml
- distribution/ddf/pom.xml
- distribution/docs/pom.xml
- pom.xml
**Description of the changes for each file in order:**
_README.md_
Updates build instructions in the README to reflect the changes below. 
_catalog-core-standardframework/pom.xml_
Removes unused integration test profile
_spatial-geocoding-geocoder/pom.xml_
Updates this pom to have `<rules` which was breaking 
_search-ui/standard/pom.xml, distribution/ddf/pom.xml, distribution/docs/pom.xml_
Changes the documentation profile to be activated when the property “skipDocs” is false or not provided. (Reference an example here: http://maven.apache.org/guides/introduction/introduction-to-profiles.html). This was done to prevent issues with profile activation that were happening. 
From the Maven website, emphasis mine:
_[A profile using `<activeByDefault>`] will automatically be active for all …
> DDF-2807: Cleans up maven profiles & adds quickbuild

- CHANGES.md
- distribution/docs/src/main/resources/_contents/_security-contents/managing-security-contents.adoc
- distribution/docs/src/main/resources/_contents/_tables/conf-org.codice.ddf.security.response.filter.ResponseHeaderConfig-table-contents.adoc
- distribution/docs/src/main/resources/_contents/_tables/org.codice.ddf.security.response.filter.ResponseHeaderConfig.adoc
- platform/security/filter/pom.xml
- platform/security/filter/security-filter-response/pom.xml
- platform/security/filter/security-filter-response/src/main/java/org/codice/ddf/security/response/filter/ResponseSecurityFilter.java
- platform/security/filter/security-filter-response/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- platform/security/filter/security-filter-response/src/main/resources/OSGI-INF/metatype/metatype.xml
- platform/security/security-services-app/pom.xml
- platform/security/security-services-app/src/main/resources/features.xml
Forward port of https://github.com/codice/ddf/pull/1717
A configurable servlet filter was added that attaches content security policy, x frame options and xss protection headers to responses.
@clockard @emmberk @vinamartin @brianfelix @ricklarsen 
[Security](https://github.com/orgs/codice/teams/security) @bdeining 
@stustison
Install DDF and load into the Admin UI. Using the developer tools built into the browser, inspect the response headers as the pages load. Confirm the new response headers are present (CSP, XSS, XFrame)
Navigate to the Security App, Configuration Tab and update the HTTP Response Security config values. Load the Catalog UI and check the response headers as the page loads.
https://www.owasp.org/index.php/Content_Security_Policy …
> DDF-2817 A configurable servlet filter now attaches Content Security Policy, X-XSS-Protection and X-Frame-Options headers to responses

- distribution/ddf-common/src/main/resources/etc/org.ops4j.pax.url.mvn.cfg
Fixes KAR hot deployment.
This change also backs out the kludge put in in #1721 to prevent the local maven repository from being searched.
_Please note that when hot deploying, a WARN message similar to the following will now appear in the log:_
```
07:57:26,274 | WARN  | pool-2-thread-1  | n.internal.config.MavenConfigurationImpl  177 | ging.pax-logging-api | Settings file [thisdirectorydoesnotexist/settings.xml] cannot be used and will be skipped (malformed url or file does not exist)
```
@rzwiefel @brendan-hofmann 
@lessarderic
@stustison
On a production box, or one where your local `.m2` directory has been removed, attempt to hot deploy a KAR. It should succeed (assuming it is a correctly constructed KAR).
N/A
[DDF-2830](https://codice.atlassian.net/browse/DDF-2830)
N/A
> DDF-2830 Updates the local repository list Karaf searches to support hot deployment

- README.md
- catalog/core/catalog-core-standardframework/pom.xml
- catalog/spatial/geocoding/spatial-geocoding-geocoder/pom.xml
- catalog/ui/search-ui/standard/pom.xml
- distribution/ddf/pom.xml
- distribution/docs/pom.xml
- pom.xml
Changes the documentation profile to be activated when the property “skipDocs” is false or not provided. (Reference an example here: http://maven.apache.org/guides/introduction/introduction-to-profiles.html). This was done to prevent issues with profile activation that were happening. 
From the Maven website, emphasis mine:
_[A profile using `<activeByDefault>`] will automatically be active for all builds unless another profile **in the same POM** is activated using one of the previously described methods. All profiles that are active by default are **automatically deactivated** when a profile in the POM is activated on the command line or through its activation config._
By changing it to property based activation, the profile will still run by default without being deactivated by other …
> DDF-2807: Fixes documentation profile activation bug

- catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/SolrFilterDelegate.java
- catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/SolrFilterDelegateTest.java
- catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/SolrProviderTest.java
This PR adds support to match empty strings (search for metacards with an empty attribute)
@rzwiefel 
@jlcsmith
@pklinef
Build / Install / Ingest Data / Verify queries
Note : There is no frontend support; so the query may have to be done through cURL or Postman
[DDF-2791](https://codice.atlassian.net/browse/DDF-2791)
> DDF-2791 Added support for queries with empty values in SolrFilterDelegate

- catalog/ui/catalog-ui-search/src/main/webapp/component/filter-builder/filter-builder.view.js
- catalog/ui/catalog-ui-search/src/main/webapp/component/filter/filter.view.js
- catalog/ui/catalog-ui-search/src/main/webapp/js/model/Metacard.js
- https://codice.atlassian.net/browse/DDF-2791 (https://github.com/codice/ddf/pull/1672) adds support for empty string queries on the server, so this adds support on the client.
- Removes guards against empty string in filter.view and filter-builder.view.
- This only adds support for empty string fields.
- Updates how client side filtering is done on empty fields to match how the server side querying currently works.  As of now, searching for an empty string on a particular field will return all the null and blank valued results for that field.  On a side note, searching for wildcard (*) filters out all null and blank valued results (both client and server side).
- Removes some unnecessary cruft from Metacard.  There's no need to listen to the unfiltered collection anymore (it already …
> DDF-2799 Add support for empty string queries to Catalog UI

- catalog/ui/catalog-ui-search/src/main/webapp/component/upload-item/upload-item.less
- catalog/ui/catalog-ui-search/src/main/webapp/js/model/Upload.js
- Previously the check only included attribute validation.  Now it will look for both metacard and attribute validation.
@rzwiefel 
@jlcsmith 
@troymohl 
Add a metacard validator and an attribute validator.  Verify that with one, the other, or both violated that they get flagged on the upload view.
https://codice.atlassian.net/browse/DDF-2832
> DDF-2832 Update upload validation check to include metacard validation in addition to attribute validation

- catalog/ui/catalog-ui-search/src/main/webapp/component/editor/metacard-basic/metacard-basic.view.js
- catalog/ui/catalog-ui-search/src/main/webapp/component/editor/metacards-basic/metacards-basic.view.js
- catalog/ui/catalog-ui-search/src/main/webapp/component/input/thumbnail/input-thumbnail.hbs
- catalog/ui/catalog-ui-search/src/main/webapp/component/input/thumbnail/input-thumbnail.less
- catalog/ui/catalog-ui-search/src/main/webapp/component/input/thumbnail/input-thumbnail.view.js
- catalog/ui/catalog-ui-search/src/main/webapp/component/result-item/result-item.hbs
- catalog/ui/catalog-ui-search/src/main/webapp/component/visualization/table/row.view.js
- catalog/ui/catalog-ui-search/src/main/webapp/js/Common.js
- catalog/ui/catalog-ui-search/src/main/webapp/js/HandlebarsHelpers.js
- catalog/ui/catalog-ui-search/src/main/webapp/js/ResultUtils.js
- Removes the use of canvas from the input-thumbnail component.  Now we directly use the img tag.
- Updates metacard edit views to use a new method in ResultUtils that allows easy updates to metacards throughout the system.
- Adds a convenience method to Common to allow determining the correct format to be used in an img src field. Updates to various files to use this new method.  This allows us to not care whether the img string is a url or a base64 encoding.
- Adds some error handling to the input-thumbnail component for when users select files that aren't images.
@figliold 
@jlcsmith 
@rzwiefel 
@djblue 
Go to the summary view of a metacard.  Test out uploading new thumbnails.  Verify that things update correct.  
Test out bulk editing metacards to ensure there are no …
> DDF-2783 Updates summary view to allow animated thumbnails

- catalog/transformer/catalog-transformer-tika-input/src/main/resources/OSGI-INF/blueprint/blueprint.xml
This PR adds AssociationsAttributes to fallback Tika MetacardTypes so they can be seen in the Catalog UI
@mcalcote @brianfelix 
@pklinef
@stustison
Build / Install / Ingest Tika Content / Verify Associations work
[DDF-2645](https://codice.atlassian.net/browse/DDF-2645)
> DDF-2645 Added Associations Attributes to Tika Input Transformer fallback MetacardTypes

- catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/SolrFilterDelegate.java
- catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/SolrFilterDelegateTest.java
- catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/SolrProviderTest.java
This PR adds support to match empty strings (search for metacards with an empty attribute)
@rzwiefel 
@jlcsmith
@pklinef
Build / Install / Ingest Data / Verify queries
Note : There is no frontend support; so the query may have to be done through cURL or Postman
[DDF-2791](https://codice.atlassian.net/browse/DDF-2791)
> (2.10.x) DDF-2791 Added support for queries with empty values in SolrFilterDelegate

- catalog/ui/catalog-ui-search/src/main/webapp/component/filter-builder/filter-builder.hbs
- catalog/ui/catalog-ui-search/src/main/webapp/component/filter-builder/filter-builder.view.js
- catalog/ui/catalog-ui-search/src/main/webapp/js/cql.js
- catalog/ui/catalog-ui-search/src/main/webapp/js/model/Metacard.js
- Adds the ability to perform queries with the 'NOT' operator to the Catalog UI.
- This allows users to exclude results from their query.  If structured correctly a user can also query for all results that lack a particular attribute.
- Right now they're tentatively named 'NOT AND' and 'NOT OR'.  Please comment with some suggestions.
@djblue 
@rzwiefel 
@tbatie 
@jlcsmith 
@pklinef 
Go to the Advanced Query view and select one of the 'NOT' operators.  Verify it works as expected.
Go to the results for a query.  Add a client side filter with one of the 'NOT' operators.  Verify it works as expected.
> DDF-2805 Add ability to perform queries with the 'NOT' operator to the Catalog UI

- catalog/resourcemanagement/resourcemanagement-usage-ui/src/main/webapp/css/index.css
- catalog/resourcemanagement/resourcemanagement-usage-ui/src/main/webapp/js/model/DataUsage.js
- catalog/resourcemanagement/resourcemanagement-usage-ui/src/main/webapp/templates/dataUsageTable.handlebars
This PR fixes an issue with the table size display on the Data Usage Admin Plugin, and encodes the user string.
@rzwiefel @lcrosenbu 
@jlcsmith
Build / Install Experimental / Set Local Resource Tracking on Resource Management / Log in as user with certificate and verify manipulations are correct
[DDF-2790](https://codice.atlassian.net/browse/DDF-2790)
https://codice.atlassian.net/browse/DDF-2790
> (2.10.x) DDF-2790 Fixed Resource Usage Admin App issues

- catalog/catalog-app/pom.xml
- catalog/catalog-app/src/main/resources/features.xml
- catalog/plugin/catalog-plugin-pointofcontactupdate/pom.xml
- catalog/plugin/catalog-plugin-pointofcontactupdate/src/main/java/org/codice/ddf/catalog/plugin/metacard/PointOfContactUpdatePlugin.java
- catalog/plugin/catalog-plugin-pointofcontactupdate/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/plugin/catalog-plugin-pointofcontactupdate/src/test/java/org/codice/ddf/catalog/plugin/metacard/PointOfContactUpdatePluginTest.java
- catalog/plugin/pom.xml
- catalog/security/catalog-security-plugin/src/main/java/ddf/catalog/security/plugin/SecurityPlugin.java
- catalog/security/catalog-security-plugin/src/test/java/ddf/catalog/security/plugin/SecurityPluginTest.java
- catalog/security/catalog-security-pointofcontact-policyplugin/pom.xml
- catalog/security/catalog-security-pointofcontact-policyplugin/src/main/java/org/codice/ddf/catalog/security/policy/metacard/PointOfContactPolicyPlugin.java
- catalog/security/catalog-security-pointofcontact-policyplugin/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- catalog/security/catalog-security-pointofcontact-policyplugin/src/test/java/org/codice/ddf/catalog/security/policy/metacard/PointOfContactPolicyPluginTest.java
- catalog/security/pom.xml
- catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.config.xml
- catalog/ui/search-ui-app/src/main/resources/etc/org.codice.ddf.catalog.ui.config
- distribution/test/itests/test-itests-common/src/main/resources/definitions.json
- distribution/test/itests/test-itests-common/src/main/resources/json/record/SimpleGeoJsonRecord
- distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalog.java
BACKPORT ALREADY MERGED
Makes the Point of Contact field read-only and fixes point-of-contact to be set to the email and only when it's a resource metacard.
Note: This is the first PR for this ticket. The second one will depend on this one.
@Lambeaux @figliold 
@lessarderic
@stustison
- Build and deploy DDF
- Ingest a metacard
- Verify in the Catalog UI that the metacard's `Point of Contact` field is set to the email address of current user (i.e. admin@localhost.local if signed in as admin) and that the field is read-only.
- Go to the Catalog UI configurations in the AdminUI and remove `point-of-contact` from the list of read-only attributes. Save.
- Go back to the Catalog UI and try to edit the `Point of Contact` field on the …
> DDF-2715: Making Point of Contact read-only

- pom.xml
Adds the `gitflow-incremental-builder` build extension to the root `pom.xml` to support local and PR incremental builds.
@oconnormi 
@LinkMJB 
@coyotesqrl
@shaundmorris
1. Run `mvn clean install` and make sure a normal build is executed.
1. Make a local change to a source file, run `mvn -Dgib.enaled=true clean install` and make sure only the module that was changed and all its dependent modules are built
[DDF-2843](https://codice.atlassian.net/browse/DDF-2843)
> DDF-2843: Add incremental builder extension to speed up PR builds

- catalog/resourcemanagement/resourcemanagement-usage-ui/src/main/webapp/css/index.css
- catalog/resourcemanagement/resourcemanagement-usage-ui/src/main/webapp/js/model/DataUsage.js
- catalog/resourcemanagement/resourcemanagement-usage-ui/src/main/webapp/templates/dataUsageTable.handlebars
This PR fixes an issue with the table size display on the Data Usage Admin Plugin, and encodes the user string.
@rzwiefel @lcrosenbu 
@jlcsmith
Build / Install Experimental / Set Local Resource Tracking on Resource Management / Log in as user with certificate and verify manipulations are correct
[DDF-2790](https://codice.atlassian.net/browse/DDF-2790)
https://codice.atlassian.net/browse/DDF-2790
> DDF-2790 Fixed Resource Usage Admin App issues

- distribution/docs/src/main/resources/_contents/_running/starting-intro-contents.adoc
Karaf has a hard-coded limit for the "wrapper.java.maxmemory" property of 4G.  
Updated the docs to use the java max heap space argument
@bdeining @brendan-hofmann 
@kcwire
> DDF-2360 Corrected instructions for DDF heap setting in windows service wrapper

- catalog/ui/catalog-ui-search/src/main/webapp/js/controllers/cesium.layerCollection.controller.js
- catalog/ui/search-ui/standard/src/main/webapp/js/controllers/cesium.layerCollection.controller.js
This PR sets the TilingScheme appropriately for EPSG:4326 WMTS projections
@djblue 
@jlcsmith
Build / Install / Configure Catalog UI Imagery Provider with a WMTS layer that is in EPSG:4326 / Verify layer is positioned properly.
http://suite.opengeo.org/geoserver/gwc/service/wmts
`[{"type": "WMT","url": "http://suite.opengeo.org/geoserver/gwc/service/wmts", "layer" : "opengeo:countries", "style" : "", "format" : "image/jpeg", "tileMatrixSetID": "EPSG:4326", "tileMatrixLabels" : ['EPSG:4326:0', 'EPSG:4326:1', 'EPSG:4326:2', 'EPSG:4326:3', 'EPSG:4326:4', 'EPSG:4326:5', 'EPSG:4326:6', 'EPSG:4326:7', 'EPSG:4326:8', 'EPSG:4326:9', 'EPSG:4326:10', 'EPSG:4326:11', 'EPSG:4326:12', 'EPSG:4326:13', 'EPSG:4326:14', …
> DDF-2778 Added support for WMTS EPSG:4326 in Cesium

- catalog/ui/catalog-ui-search/src/main/webapp/js/controllers/ol.layerCollection.controller.js
This PR adds support for AGM in OpenLayers.  Configuring an ArcGis provider now works in 2D and 3D maps without having to change the configuration in the Admin UI.
@djblue 
@jlcsmith
Build / Install / Configure / Verify EPSG:4326 / Verify EPSG:3857 on Cesium & OpenLayers
`[{"type": "AGM","url": "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/" }]`
http://resources.arcgis.com/en/help/rest/apiref/wmtstile.html
[DDF-2512](https://codice.atlassian.net/browse/DDF-2512)
> DDF-2512 Added AGM support to OpenLayers

- CHANGES.md
- distribution/ddf-common/src/main/resources/etc/system.properties
- distribution/docs/src/main/resources/_contents/_configuring/configuring-global-settings-contents.adoc
- platform/util/platform-util-unavailableurls/pom.xml
- platform/util/platform-util-unavailableurls/src/main/java/org/codice/ddf/platform/util/http/UnavailableUrls.java
- platform/util/platform-util-unavailableurls/src/test/java/org/codice/ddf/platform/util/http/UnavailableUrlsTest.java
Change retry interval for unavailable endpoints
The max retry interval can now be set in system properties and defaults to 300 seconds.
The initial retry interval can be set in system properties and defaults to 10 seconds.
The exponential behavior is noW doubling the interval instead of growing it by a factor of 10.
The unit test includes a check to make sure no interval is longer than the max.
@stustison @brendan-hofmann @codymacdonald
@coyotesqrl
@stustison
Run unit and integration tests.
If a source is created and the endpoint is not available, DDF will periodically try to establish a connection. The problem is the retry period. The interval between retries grows exponentially, up to 420 minutes (7 hours).  Here is a table
||Retry #||Actual Timeout||
|1| 10 seconds|
|2| 2 minutes 45 …
> DDF-2831 Made retry intervals for Catalog Sources configurable

- distribution/ddf-common/src/main/resources/common-bin.xml
Combined Doc and Documentation folders into a single folder
@clockard @mcalcote @vinamartin @emmberk 
@ricklarsen 
@figliold 
@pklinef 
Build the distro using a build profile that includes documentation (mvn javadoc:aggregate OR mvn release are two such examples) and ensure that all documentation and javadocs are in the documentation folder.
[](https://codice.atlassian.net/browse/DDF-2829)
> DDF-2829: Combined Doc and Documentation folders into a single folder

- distribution/kernel/pom.xml
A build order issue appeared after the 2.10.1 release was cut. A dependency was not included in the pom for kernel even though it is being packaged into its feature. This adds that missing dependency.
@oconnormi @emanns95 
@lessarderic
@shaundmorris
A successful CI build should be sufficient.
N/A
[DDF-2859](https://codice.atlassian.net/browse/DDF-2859)
N/A
> DDF-2859 [2.10.x] Adds ddf-branding-plugin dependency to kernel module

- platform/util/platform-util/pom.xml
Removes bouncy castle from platform-util's shaded jar as the libraries are already included in bundle 0.
@tbatie @Lambeaux 
@kcwire
@stustison
Full CI run, then an installation and verification that common security tasks (authC/Z) work by logging into Admin and Search, preferably using both Karaf and LDAP realms.
N/A
[DDF-2858](https://codice.atlassian.net/browse/DDF-2858)
N/A
> DDF-2858 [2.10.x] Removes Bouncy castle from platform-util shaded jar

- platform/util/platform-util/pom.xml
Removes bouncy castle from platform-util's shaded jar as the libraries are already included in bundle 0.
Forward-port of #1775 
@kcwire
@stustison
As a full heroing run was performed against 2.10.x, a successful CI run should be sufficient for this branch.
N/A
[DDF-2858](https://codice.atlassian.net/browse/DDF-2858)
N/A
> DDF-2858 Removes Bouncy castle from platform-util shaded jar

- catalog/core/catalog-core-directorymonitor/pom.xml
- catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/ContentDirectoryMonitor.java
- catalog/core/catalog-core-directorymonitor/src/main/resources/OSGI-INF/metatype/metatype.xml
- catalog/core/catalog-core-directorymonitor/src/test/java/org/codice/ddf/catalog/content/monitor/ContentDirectoryMonitorTest.java
- distribution/ddf-common/src/main/resources/etc/system.properties
- distribution/docs/src/main/resources/_contents/_resources/content-directory-monitor-contents.adoc
This PR reads the bad.files.* properties in the system.properties file and creates a blacklist for ingesting files through the CDM.
@Lambeaux 
@jlcsmith
@kcwire
Build / Install / Configure CDM / Observe blacklisted file types
[DDF-2851](https://codice.atlassian.net/browse/DDF-2851)
> DDF-2851 Added a file pattern blacklist to the content directory monitor
