codice/ddf

distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/AbstractIntegrationTest.java, distribution/test/itests/test-itests-ddf/pom.xml
Changes the port the itests use for Solr server.
Solr makes some assumptions about ports. It assumes the main port and kill port are exactly 1000 apart. Therefore, attempting to run two instances of Solr, one at 8994 and another at 9994 causes problems. This PR fixes the problem so the itests do not conflict with a running instance of DDF.
@mcalcote @ethantmanns @austinsteffes @kcover 
@clockard
@figliold
@lessarderic
Run itests. Confirm that Solr server is running on port 9784 and that the itests are able to communicate with Solr. …
=> DDF-3340 Deconflict itest Solr port

platform/security/idp/security-idp-client/pom.xml, platform/security/idp/security-idp-client/src/main/java/org/codice/ddf/security/idp/client/AssertionConsumerService.java, platform/security/idp/security-idp-client/src/test/java/org/codice/ddf/security/idp/client/AssertionConsumerServiceTest.java
- Teams tagged
Link to 2.13.x PR: #3667
____
@ahoffer @blen-desta @brjeter 
@tbatie 
@rzwiefel  …
=> DDF-4059 Adding a null check in AssertionConsumerService:getSamlResponse()

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/handlers/CqlTransformHandler.java
Fixed a bug found in the cql transform handler which is used to create a result set and map the request's arguments to transformer arguments. Previously string arguments were not mapped over properly because they come through as a `CharSequence` which does not implement `Serializable`. 
@brianfelix 
@bdeining
@coyotesqrl 
Testing this is a bit tricky since the only transformer that accepts string arguments is the zip compressor and that transformer hasn't been working properly. I can update the testing instructions if there are better ideas for how to test this code.
1. Set a breakpoint in the `CqlTransformHandler` after `Map<String, Serializable> arguments` is instantiated in the `transform` method. 
2. …
=> DDF-4124 CQL transform handler does not map string values when retrieving serializable values from post body	

distribution/ddf-common/src/main/resources-filtered/etc/startup.properties, distribution/ddf-common/src/main/resources/common-bin.xml, distribution/ddf-common/src/main/resources/security/default.policy, distribution/kernel/pom.xml, platform/osgi/platform-osgi-condpermadmin/pom.xml, platform/osgi/platform-osgi-condpermadmin/src/main/java/org/codice/ddf/condpermadmin/PermissionActivator.java, platform/osgi/platform-osgi-condpermadmin/src/test/java/org/codice/ddf/condpermadmin/PermissionActivatorTest.java, pom.xml
This PR updates the kernel to include 2 AC debugger-specific bundles which by design do nothing except start. The backdoor bundle is meant to be discovered by the debugger using reflection to optimize the communication between the VM being debugged and the debugger. The PermissionActivator is also enhanced to implement an AC debugger service which would allow it to temporarily grant permissions. The service is protected against anybody but the AC debugger backdoor to get their hands on it. 
@figliold 
@coyotesqrl
@stustison 
- Make sure the build passes
- Unzip the distribution
- Modify the default policy file to remove `permission java.io.FilePermission "${ddf.home.perm}-", "write, delete";` from the `platform-migration` …
=> DDF-4045 Enhanced PermissionActivator to implement the AC debugger

catalog/async/catalog-async-data-api/src/main/java/org/codice/ddf/catalog/async/data/api/internal/ProcessResource.java, catalog/async/catalog-async-data/src/main/java/org/codice/ddf/catalog/async/data/impl/LazyProcessResourceImpl.java, catalog/async/catalog-async-data/src/main/java/org/codice/ddf/catalog/async/data/impl/ProcessResourceImpl.java, catalog/async/catalog-async-data/src/test/groovy/org/codice/ddf/catalog/async/data/LazyProcessResourceImplSpec.groovy, catalog/async/catalog-async-data/src/test/groovy/org/codice/ddf/catalog/async/data/ProcessResourceImplSpec.groovy
Before, calling getInputStream on a ProcessResource would always return
the same input stream, which, once read would no longer be useful. Now
the first call to getInputStream will create a file backed output stream of the data in the
input stream so that new input streams can be created each time. Once
new input streams are no longer needed the file backed output stream
will need to be closed by calling the close method of the
ProcessResource.
@figliold
@vinamartin
Unit tests
To hero, install alliance and start the async processing framework and the nitf post processing plugin. Then ingest some nitfs and make sure that the nitfs are ingested properly and the logs are quiet.
[DDF-4093](https://codice.atlassian.net/browse/DDF-4093) …
=> DDF-4093  Make getInputStream idempotent

distribution/test/itests/pom.xml, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestPlatform.java, distribution/test/itests/test-itests-dependencies-app/src/main/filtered-resources/features.xml, features/security/src/main/feature/feature.xml, platform/security/sts/security-sts-server/pom.xml, platform/security/sts/security-sts-server/src/main/java/ddf/security/sts/MemoryTokenStore.java, platform/security/sts/security-sts-server/src/main/resources/OSGI-INF/blueprint/tokenstore.xml
Updates InMemoryTokenStore to use Guava instead of ehCache. 
This cleans up a problem with growing .data files in <ddf.home>/data/tmp
@adimka 
@Bdthomson 
@bdeining
@stustison
Full build with tests
1. Login/Logout to admin UI and search UI a couple of times.
Verify no data is stored in the <ddf.home>/data/tmp/*cxf*/*.data file
Will backport to 2.13.x once this PR is approved. 
[DDF-4089](https://codice.atlassian.net/browse/DDF-4089) …
=> DDF-4089 Change to Guava Cache implementation for in memory token cache

catalog/opensearch/catalog-opensearch-source/src/main/java/org/codice/ddf/opensearch/source/OpenSearchParserImpl.java, catalog/opensearch/catalog-opensearch-source/src/test/groovy/org/codice/ddf/opensearch/source/OpenSearchParserImplSpec.groovy, catalog/opensearch/catalog-opensearch-source/src/test/groovy/org/codice/ddf/opensearch/source/OpenSearchSourceSpec.groovy, catalog/opensearch/catalog-opensearch-source/src/test/java/org/codice/ddf/opensearch/source/OpenSearchParserImplTest.java
This PR fixes querying an OpenSearchSource by a keyword that contains a space.
@peterhuffer @kcover @lamhuy 
@codice/io 
@bdeining
@clockard
1. Ingest a product that contains a phrase with spaces. (I modified [this test file](https://github.com/codice/ddf/blob/dfbce3ca3636bb80c98e5c2271e917686e5dd8d9/distribution/test/itests/test-itests-common/src/main/resources/metacard1.xml#L22) to have a title of `Metacard 1`.)
2. Create a loopback OpenSearch source.
3. Confirm that the product is returned when you search for it by the phrase. 
The search phrase was being encoded twice: first with the URLEncoder (the part that is removed in the PR) and second in the `WebClient` after `replaceQueryParam`.
[DDF-4130](https://codice.atlassian.net/browse/DDF-4130) …
=> [2.13.x] DDF-4130 Fixed searching an OpenSearchSource by a keyword that contains a space

catalog/ui/catalog-ui-search/pom.xml, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/delegate/SearchTerm.java, catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/query/delegate/SearchTermTest.java
Replaces standard Java regex search with time-limited regex for the `SearchTerm` class.
@brjeter @blen-desta
@clockard
@tbatie
The only extant public path to the `SearchTerm` regex functionality comes through `CqlResult` which tokenizes and sanitizes the search. There is currently no production path through that could trigger a questionable regex.
The added unit tests will demonstrate and affirm the issue, so a successful CI build is sufficient at this time.
[DDF-4113](https://codice.atlassian.net/browse/DDF-4113) …
=> DDF-4113 Swaps in time-limited RegEx matcher to SearchTerm

catalog/core/catalog-core-commands/pom.xml, catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/ExportCommand.java, catalog/spatial/geocoding/spatial-geocoding-extract/pom.xml, catalog/transformer/catalog-transformer-zip/pom.xml, catalog/transformer/catalog-transformer-zip/src/main/java/org/codice/ddf/catalog/transformer/zip/ZipCompression.java, distribution/docs/src/main/resources/content/_dependencyList/ddf-dependency-list.adoc
Removes the zip4j dependency from a few files as it is contains the vulnerability CVE-2018-1002202. 
@clockard 
@coyotesqrl 
> Start a DDF 
> profile:install standard
> ingest something into ddf
> catalog:export --delete=true --skip-signature-verification
> catalog:import --skip-signature-verification <created_file>
> query ddf see that everything has been added. Download any resource without errors
BugFix
> ingest a lot of data into DDF, 35000+
> run a catalog:export catalog:export --delete=false --skip-signature-verification
> insure no errors appear in the Karaf console.
> cd into the log directory `<ddf_home>/data/log/`
> run `grep "localhost Ids of exported metacards and content" security.log | cut -f2 -d _ | wc -w` 
> that …
=> [2.13.x] DDF-4112 removing zip4j dependency in: spatial-geocoding-extract, catalog-transformer-zip, catalog-core-commands, and docs.

ui/packages/catalog-ui-search/src/main/webapp/react-component/text-field/text-field.js
Fixes disappearing latitude and longitude values
@tbatie 
@ethantmanns 
@djblue
1) Open Intrigue basic search form
2) Enter 0 for the latitude and 20 for the longitude
3) Verify latitude and longitude values do not disappear
https://codice.atlassian.net/browse/DDF-4137 …
=> [2.13.x] DDF-4137: Intrigue basic search form - "0" latitude and longitude values disappear

catalog/core/catalog-core-api/src/main/java/ddf/catalog/plugin/PreFederatedLocalProviderQueryPlugin.java, catalog/core/catalog-core-tagsfilterplugin/src/main/java/org/codice/ddf/catalog/plugin/tagsfilter/TagsFilterQueryPlugin.java, catalog/core/catalog-core-validationfilterplugin/src/main/java/org/codice/ddf/catalog/plugin/validationfilter/ValidationFilterPlugin.java, catalog/core/catalog-core-validationfilterplugin/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/core/catalog-core-validationfilterplugin/src/test/java/org/codice/ddf/catalog/plugin/validationfilter/ValidationFilterPluginTest.java
ValidationFilterPlugin to execute only for local provider. 
as a PreFederateQueryPlugin, this plugin get execute for all 'sources'
but we only want this logic to be applied for 'catalogProvider' only i.e. solr provider and not during federated sources
@Bdthomson 
@coyotesqrl 
@bdeining
@clockard
@millerw8
@pklinef 
@bdeining
@clockard
@millerw8
Create a loop back CSW federation
Login UI as admin
Turn log:set DEBUG org.apache.cxf
Perform a wild card federated search for the loop back source
Verify the outbound message in the log does not contain any VALIDATION constraint filter
Verify no error in the log
https://codice.atlassian.net/browse/DDF-4138
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Reque …
=> DDF-4138 ValidationFilterPlugin to execute only for local provider

distribution/ddf-common/src/main/resources/bin/ddfsolr
Fixes a mismatch between what the ddfsolr script expects and what is in the system.properties file.
This is not a problem on master.
@mcalcote @ricklarsen @austinsteffes @garrettfreibott 
If you don't know who to ask, you can request reviews in https://groups.google.com/forum/#!forum/ddf-developers .
-->
@clockard
@vinamartin
- I have tested it. To test it yourself, build DDF and unzip the distro. 
- Change Solr to http instead of https:
- Edit system.properties. Set **solr.http.protocol=http**
- Start Solr 
- **bin/ddfsolr start**
- Open the Solr admin view at http://localhost:8994
- Verify the Solr heap is allocated 2 gigabytes
No. None. …
=> [2.13.x] DDF-4145 Fix mismatch in Solr property name

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/forms/TemplateTransformer.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/forms/model/pojo/CommonTemplate.java, distribution/docs/src/main/resources/content/_using/using-catalog-search-ui.adoc, ui/packages/catalog-ui-search/src/main/webapp/component/query-add/query-add.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/query-template-sharing/query-template-sharing.hbs, ui/packages/catalog-ui-search/src/main/webapp/component/query-template-sharing/query-template-sharing.less, ui/packages/catalog-ui-search/src/main/webapp/component/query-template-sharing/query-template-sharing.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/result-form/result-form.collection.js, ui/packages/catalog-ui-search/src/main/webapp/component/result-form/result-form.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/search-form-interactions/search-form-interactions.less, ui/packages/catalog-ui-search/src/main/webapp/component/search-form-interactions/search-form-interactions.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/search-form/forms-sharing/search-form-sharing.collection.js, ui/packages/catalog-ui-search/src/main/webapp/component/search-form/search-form.collection.js, ui/packages/catalog-ui-search/src/main/webapp/component/search-form/search-form.js, ui/packages/catalog-ui-search/src/main/webapp/component/tabs/search-form/tabs.search-form.js, ui/packages/catalog-ui-search/src/main/webapp/component/workspace-interactions/workspace-interactions.less, ui/packages/catalog-ui-search/src/main/webapp/component/workspace-interactions/workspace-interactions.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/workspace-sharing/workspace-sharing.hbs, ui/packages/catalog-ui-search/src/main/webapp/component/workspace-sharing/workspace-sharing.less, ui/packages/catalog-ui-search/src/main/webapp/component/workspace-sharing/workspace-sharing.view.js
Depends on https://github.com/codice/ddf/pull/3655
@Schachte 
@djblue 
@bdeining
Overview:
for workspaces, search forms, and result forms:
* confirm sharing through the access-administrators field works 
* confirm interactions menu (three dot) only displays `Share` if the current user is the owner or on 
the access-administrators list
Steps:
- build
- add empty folder `etc/forms`
- In `users.attributes`:
```
{
"admin" : {
"http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress":"admin@localhost.local"
},
"localhost" : {
"http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress":"system@localhost.local"
},
"dummy" : {
"http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress":"dummy@example.com"
}
}
```
- In `users.properties`:
``` …
```
=> DDF-4108 Update UI sharing modal component to account for access-control administrators

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/impl/CachedResourceMetacardComparator.java, catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/cache/impl/CachedResourceMetacardComparatorTest.java
Backport for this PR: https://github.com/codice/ddf/pull/3611
Fixes deletion of cached metacards when cachedMetacard == updatedMetacard under federated environments
@mcalcote 
@ahoffer
@lessarderic
@clockard 
set up a federation
ingest a word document or something with metadata
query and download it
re-search query and make sure product is still in the product/cache -> good
then
download -> edit metadata -> requery -> make sure product is not cached since cached metadata != updated metadata
DDF-4057
Screenshots
Checklist: …
=> [2.13.x] DDF-4057 Remote resources copied to local always evicted which prevents users from pre-caching resources 

catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/ExportCommand.java, catalog/transformer/catalog-transformer-zip/src/main/java/org/codice/ddf/catalog/transformer/zip/ZipCompression.java
- Teams tagged
Backporting the latest change made in #3749 that @paouelle brought to the spotlight while reviewing the forward port. All System.getProperty("javax.net.ssl.*"); should be inside of doPrivileged blocks. 
@bakejeyner @brjeter
@clockard
@coyotesqrl
Testing steps:
Add the jarsigner to default.policy or turn off the security manager. /shrug
Run catalog:export delete=false
shouldn't see any security manager errors. …
=> [2.13.x] DDF-4112 Adding privileged calls around System.getProperties in catalog:export

catalog/core/catalog-core-commands/pom.xml, catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/ExportCommand.java, catalog/spatial/geocoding/spatial-geocoding-extract/pom.xml, catalog/transformer/catalog-transformer-zip/pom.xml, catalog/transformer/catalog-transformer-zip/src/main/java/org/codice/ddf/catalog/transformer/zip/ZipCompression.java, distribution/docs/src/main/resources/content/_reference/_dependencyList/ddf-dependency-list.adoc
- Teams tagged
Link to 2.13.x PR: #3711
____
@bakejeyner @brjeter
@clockard
@coyotesqrl …
=> DDF-4112 removing zip4j dependency in: spatial-geocoding-extract, catalog-transformer-zip, catalog-core-commands, and docs.

pom.xml
It upgrades the AC debugger to the latest version 1.4 which added support for bundle permissions defined in protection domains.
@ethantmanns 
@bakejeyner 
@coyotesqrl
@tbatie
- build passing
- attach AC debugger and use --debug and --continuous options
- ingest PDF document with fonts; the debugger should simply ignore this security exception and continue as it it had failed normally
[DDF-4155](https://codice.atlassian.net/browse/DDF-4155) …
=> DDF-4155 Updated AC debugger to 1.4

distribution/ddf-common/src/main/resources/bin/ddf, distribution/ddf-common/src/main/resources/bin/ddf.bat
Backport of https://github.com/codice/ddf/pull/3739
Sets the start scripts on window and *nix to not start/exit if JAVA_HOME is not set
@garrettfreibott @ahoffer @mcalcote
@clockard
@shaundmorris 
Unset JAVA_HOME
Start up DDF
DDF should not start and should output message saying to set JAVA_HOME to start
DDF-4122
Screenshots
Checklist:
Please see Notes on Review Process for …
=> [2.13.x] DDF-4122 Do not start DDF if JAVA_HOME not set

ui/packages/registry-admin-local-ui/src/main/webapp/js/model/Field.js
Fixes registry date validation error message and makes the time field not required.
@figliold
@shaundmorris 
@vinamartin
Install DDF and the Registry App
Open up Catalog->Node Info->Identity Node
Under the Content Collection tab add a custom date field "testdate" of type "date"
Enter a date but no time.
Verify no validation error message is shown and the configuration can be saved. 
[DDF-4161](https://codice.atlassian.net/browse/DDF-4161)
=> DDF-4161 Fix registry date field validation error

distribution/ddf-common/src/main/resources/common-bin.xml, distribution/ddf-common/src/main/resources/etc/blacklisted.properties, features/pom.xml
(the karaf decanter bundle cassandra still uses them)
- Teams tagged
Link to 2.13.x PR: #3741
____
@blen-desta @brjeter
@clockard
@tbatie …
=> DDF-4129 Updating netty versions and blacklisting them where needed 

ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/cesium/cesium.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/cesium/map.cesium.js
related master PR https://github.com/codice/ddf/pull/3758
fix 3D map loading
null check on terrainProvider property
log error
@adimka
@bdeining
@troymohl
@bdeining
@millerw8
@clockard
Build, ensure 3D map load with terrainProvider property set to blank
admin config > Search UI > catalog ui
https://codice.atlassian.net/browse/DDF-4153
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging …
=> [2.13.x] DDF-4153 add null check and logging for 3D map view

catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/blueprint/blueprint.xml
Fixes problem in master with Intrigue unable to get metacardtypes due to blueprint.xml parameter ordering on EndpointUtil.
@djblue 
@BernardIgiri 
@bdeining
Build DDF and launch UI. Verify no errors in Inspector.
[DDF-4174](https://codice.atlassian.net/browse/DDF-4174) …
=> DDF-4174 Fix blueprint.xml parameter order for EndpointUtil

distribution/docs/src/main/resources/content/_managing/_running/ddf-service.adoc
Adds documentation for a step in installing the service wrapper that is now needed as of the Karaf 4.2.0 upgrade (https://github.com/codice/ddf/pull/3635). This was found in the hero process of PR 3635, but I forgot to push up the change before merging the original PR.
@coyotesqrl 
Generate the docs and verify the format of the modified section.
[DDF-3908](https://codice.atlassian.net/browse/DDF-3908) …
=> DDF-3908 Add additional step to docs for the service wrapper

distribution/ddf-common/src/main/resources/common-bin.xml
The distribution was trying to exclude the pax-web JSP jar, which was causing failures when starting up with an empty m2 repo:
> Error resolving artifact org.ops4j.pax.web:pax-web-jsp:jar:7.2.3: [Could not find artifact org.ops4j.pax.web:pax-web-jsp:jar:7.2.3]
@clockard
@coyotesqrl 
Clean your m2 repo and start up DDF. Verify the above error is not in the logs.
[DDF-3908](https://codice.atlassian.net/browse/DDF-3908) …
=> DDF-3908 Remove jsp exclude causing startup failures with empty m2

distribution/ddf-common/src/main/resources/security/default.policy
Karaf's SSH bundles didn't have read or write access to many of the
files on the system. This would require the user to add permissions for
the ssh bundles if they wanted to use certain commands through ssh.
Since any commands run through ssh will go through other bundles that
will be properly secured, this wont create any security vulnerabilities.
We also only allow ssh connections from the host machine so it would be
very difficult for an unauthorized user to access ddf via ssh.
@peterhuffer  @emmberk 
@clockard
Install ddf and ssh into the karaf shell. Then try to ingest a file from outside the user and ddf home directories.
[DDF-4175](https://codice.atlassian.net/browse/DDF-4175) …
=> DDF-4175 Give SSH bundles read/write access to all files

distribution/ddf-common/src/main/resources/security/default.policy, platform/security/sts/security-sts-ldapclaimshandler/src/main/java/ddf/security/sts/claimsHandler/ClaimsHandlerManager.java, platform/security/sts/security-sts-ldapclaimshandler/src/main/java/ddf/security/sts/claimsHandler/LdapClaimsHandler.java, platform/security/sts/security-sts-ldapclaimshandler/src/main/java/ddf/security/sts/claimsHandler/RoleClaimsHandler.java, platform/security/sts/security-sts-ldapclaimshandler/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/security/sts/security-sts-ldapclaimshandler/src/main/resources/OSGI-INF/metatype/metatype.xml, platform/security/sts/security-sts-ldapclaimshandler/src/test/java/ddf/security/sts/claimsHandler/RoleClaimsHandlerTest.java, platform/security/sts/security-sts-ldaplogin/src/main/java/ddf/ldap/ldaplogin/LdapConnectionPooledObjectFactory.java, platform/security/sts/security-sts-ldaplogin/src/main/java/ddf/ldap/ldaplogin/LdapLoginConfig.java, platform/security/sts/security-sts-ldaplogin/src/main/resources/OSGI-INF/blueprint/karaf_ldap_config.xml, platform/security/sts/security-sts-ldaplogin/src/main/resources/OSGI-INF/metatype/metatype.xml, platform/security/sts/security-sts-ldaplogin/src/test/java/ddf/ldap/ldaplogin/LdapLoginConfigTest.java, platform/security/sts/security-sts-ldaplogin/src/test/java/ddf/ldap/ldaplogin/LdapModuleTest.java
Remove LDAP structure assumptions, enable LDAP login and attribute claims to work with nested user OUs, allow multiple ldap servers in a single configuration for load balancing / failover
@ryeats @KalCramer @harrison-tarr 
@stustison
@tbatie 
@coyotesqrl 
Create a user in a nested OU under the base user DN 
Set their uid and cn to be different values (e.g. uid=user1, cn=User One)
Add the user to a group and verify that they can log in and that their group information is successfully added.  If added to the admin group the user should be able to log into the admin console
[DDF-4090](https://codice.atlassian.net/browse/DDF-4090)
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guideline …
=> [2.13.x] DDF-4090 - Remove LDAP structure assumptions

platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/server/IdpEndpoint.java, platform/security/sts/security-sts-server/src/main/resources/OSGI-INF/blueprint/cxf-sts.xml, platform/security/sts/security-sts-server/src/main/resources/OSGI-INF/metatype/metatype.xml
Resolved SAML compliance issues when DDF is configured behind a proxy.
@coyotesqrl
@stustison 
- Verify that the [SAML-CTK](https://github.com/codice/saml-conformance) tests pass with out-the-box DDF
- Configure DDF behind a proxy both **with** and **without** an external context and verify that the [SAML-CTK](https://github.com/codice/saml-conformance) tests pass. 
See the testing steps on https://github.com/codice/ddf/pull/3692 for steps on how to configure DDF behind a proxy.
[DDF-4171](https://codice.atlassian.net/browse/DDF-4171)
- ✏️ (Pencil) This comment is a nitpick …
=> [2.13.x] DDF-4171 - Resolved SAML compliance issues when DDF is configured behind a proxy

.gitignore, distribution/docs/src/main/resources/content/_architectures/_resources/url-resource-reader.adoc, distribution/docs/src/test/java/ddf/docs/DocumentationTest.java
Link to 2.13.x PR: [#3772](https://github.com/codice/ddf/pull/3772)
Fixes documentation unit test to be platform-independent.
@clockard
@lessarderic
@shaundmorris
builds successfully and test passes …
=> DDF-2824 improvement to docs unit test

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/config/ConfigurationApplication.java, catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.xml, catalog/ui/search-ui-app/src/main/resources/etc/org.codice.ddf.catalog.ui.config, distribution/docs/pom.xml, distribution/docs/src/main/resources/content/_reference/_tables/catalog.ui.config.adoc, ui/packages/catalog-ui-search/src/main/webapp/component/query-basic/query-basic.view.js
Update Basic Search Form to use configurable attribute for type; right now it is hardcoded to use the datatype attribute.
@bdeining @Bdthomson @alanchampion 
@djblue
- build/run
- Run a Basic Search with a specific Match Type selected 
- verify type selected was searched with "datatype" and "metadata-content-type" 
- in Admin search ui config set Basic Search Match Type Metacard Attribute to a valid metacard attribute
- run another search and verify type selected was searched with "metadata-content-type" and the attribute set in admin config
- in Admin search ui config set Basic Search Match Type Metacard Attribute to an invalid metacard attribute
- run another search and verify type selected was searched with "metadata-content-type" …
=> DDF-4160 Update Basic Search Form to use configurable attribute for type

distribution/test/itests/pom.xml, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestPlatform.java, distribution/test/itests/test-itests-dependencies-app/src/main/filtered-resources/features.xml, features/security/src/main/feature/feature.xml, platform/security/sts/security-sts-server/pom.xml, platform/security/sts/security-sts-server/src/main/java/ddf/security/sts/MemoryTokenStore.java, platform/security/sts/security-sts-server/src/main/resources/OSGI-INF/blueprint/tokenstore.xml
Updates InMemoryTokenStore to use Guava instead of ehCache.
This cleans up a problem with growing .data files in <ddf.home>/data/tmp
Port to 2.13.x of https://github.com/codice/ddf/pull/3662
@adimka
@Bdthomson
@bdeining 
@stustison 
Full build with tests
Login/Logout to admin UI and search UI a couple of times.
Verify no data is stored in the <ddf.home>/data/tmp/cxf/*.data file
[DDF-4089](https://codice.atlassian.net/browse/DDF-4089) …
=> DDF-4089 [2.13.x] Change to Guava Cache implementation for in memory token cache 

pom.xml
- Locks down the maven-install-plugins version to 2.5.2. With 3.0.0-M1, any modules that have attachments but do not have primary artifacts will now fail with an exception instead of printing a warning, like 2.5.2 and before would. This primarily effects the feature modules which have only attachments - so they now fail to build on 3.0.0+.
@paouelle @emmberk @kcover @tbatie 
@codice/build 
@clockard
@coyotesqrl
Full build
https://issues.apache.org/jira/browse/MINSTALL-151
[DDF-4191](https://codice.atlassian.net/browse/DDF-4191) …
=> [2.13.x] DDF-4191 Fix mvn install issue

ui/packages/ui/src/main/webapp/js/models/installer/Configuration.js
Makes the installer set system.hostname to the given hostname when the query parameter dev=true
@oconnormi @emmberk @kcover @peterhuffer @mdang8 
@codice/ui 
@clockard
@vinamartin
set dev=true in the query string and check that hostname is set for both external.hostname and system.hostname.
#3747
[DDF-4193](https://codice.atlassian.net/browse/DDF-4193) …
=> DDF-4193 make the installer set system.hostname to the given hostname when dev=true

distribution/docs/src/main/resources/content/_managing/_configuring/global-settings.adoc
Fixed a typo in the Global Settings documentation with the "Internal Default Port" property.
@oconnormi @pvargas @peterhuffer @emmberk @kcover 
@codice/docs 
@clockard
@coyotesqrl
[DDF-4198](https://codice.atlassian.net/browse/DDF-4198) …
=> DDF-4198 Fixed a typo in the property for 'Internal Default Port'

distribution/docs/src/main/resources/content/_endpoints/csw-endpoint.adoc
Adds doc section telling user how to specify which input transformer to use on CSW Insert requests.
@paouelle 
@jhunzik 
@codice/docs 
@figliold
@tbatie
Build docs and visual inspection.
[DDF-4190](https://codice.atlassian.net/browse/DDF-4190) …
=> DDF-4190 Added docs on selecting transformer for CSW Insert

ui/packages/ui/src/main/webapp/less/common/banner.less, ui/packages/ui/src/main/webapp/less/installer/style.less
Backporting #3822 
Fixes problem where input boxes would end up on top of header and footer banners.
@emmberk @peterhuffer @oconnormi @kcover 
@codice/ui 
@clockard @rzwiefel 
[DDF-4189](https://codice.atlassian.net/browse/DDF-4189) …
=> [2.13.x] DDF-4189 Fix banner z-index. 

ui/packages/ui/src/main/webapp/js/models/installer/Configuration.js
Backports #3832 
Makes the installer set system.hostname to the given hostname when the query parameter dev=true
@oconnormi @emmberk @kcover @peterhuffer @mdang8 
@codice/ui 
@clockard
@vinamartin
set dev=true in the query string and check that hostname is set for both external.hostname and system.hostname.
#3747
[DDF-4193](https://codice.atlassian.net/browse/DDF-4193) …
=> [backport] DDF-4193 make the installer set system.hostname to the given hostname when dev=true

ui/packages/catalog-ui-search/src/main/webapp/js/cql.js, ui/packages/catalog-ui-search/src/main/webapp/js/cql.spec.js
Adds support for single ' property names in cql.js
@Bdthomson 
@Schachte 
@bdeining
@djblue
Full build.
Modify the ddf.home/etc/org.codice.ddf.catalog.ui.config and set listTemplates to something like:
listTemplates=[ \
"{\"id\":\ \"Targets\",\ \"list.icon\":\ \"target\",\ \"list.cql\":\ \"(('title'\ \=\ 'User\ Defined'\))"\ }", \
]
Create a list of type target
Query for data, and Click the Add/Remove from list drop down and verify your list created previously is in the list. Unless the title is User Defined you won't be able to add to that list though. It showing in the dropdown is enough to verify this PR.
Currently properties can be escaped with " but not ', single quotes gives the ability to nest within already quoted configuration settings like …
=> DDF-4183 Single quoted property name support in cql.js

distribution/docs/src/main/resources/content/_integrating/_endpoints/csw-endpoint.adoc
Adds doc section telling user how to specify which input transformer to use on CSW Insert requests.
@paouelle 
@jhunzik 
@codice/docs 
@figliold
@tbatie
Build docs and visual inspection.
[DDF-4190](https://codice.atlassian.net/browse/DDF-4190) …
=> [FORWARDPORT] DDF-4190 Added docs on selecting transformer for CSW Insert

ui/packages/catalog-ui-search/src/main/webapp/component/query-adhoc/query-adhoc.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/query-basic/query-basic.view.js
- The Basic Search Form says "%" can be used as a wildcard but that is not the behavior. This is removed.
- The Text Search Form does behave like "%" is a wildcard. This functionality is changed to be consistent with other search forms.
@garrettfreibott @blen-desta 
@rzwiefel  
- Pull up the Basic Search Form in Intrigue and verify the help text does not mention "%"
- Verify the Text Search Form in Intrigue does not count % as a wildcard.
[DDF-4203](https://codice.atlassian.net/browse/DDF-4203) …
=> [2.13.x] DDF-4203 Fixes "%" wildcard discrepancies in Intrigue

distribution/docs/src/main/resources/content/_configuring/global-settings.adoc
Back ports #3838
Fixed a typo in the Global Settings documentation with the "Internal Default Port" property.
@oconnormi @pvargas @peterhuffer @emmberk @kcover 
@codice/docs 
@clockard
@coyotesqrl
[DDF-4198](https://codice.atlassian.net/browse/DDF-4198) …
=> [2.13.x] DDF-4198 Fixed a typo in the property for 'Internal Default Port'

catalog/transformer/catalog-transformer-pdf/src/main/java/ddf/catalog/transformer/input/pdf/PdfInputTransformer.java, catalog/transformer/catalog-transformer-pdf/src/main/resources/OSGI-INF/metatype/metatype.xml, distribution/docs/src/main/resources/content/_reference/_tables/ddf.catalog.transformer.input.pdf.PdfInputTransformer.adoc
It increases the `Maximum xml metadata length` to 5MB, since the previous default work for larger files
@oconnormi @mdang8 @kcover @emmberk @peterhuffer 
@clockard
@coyotesqrl 
Ingest a large PDF through the Content Directory Monitor
[DDF-4208](https://codice.atlassian.net/browse/DDF-4208) …
=> DDF-4208 Increase default `Maximum xml metadata length` to 5MB.

distribution/ddf-common/src/main/resources/bin/ddf, distribution/ddf-common/src/main/resources/bin/ddf.bat, distribution/ddf-common/src/main/resources/security/default.policy, platform/admin/core/admin-core-appservice/pom.xml, platform/admin/core/admin-core-appservice/src/main/java/org/codice/ddf/admin/application/service/impl/ApplicationServiceBean.java, platform/admin/core/admin-core-appservice/src/main/java/org/codice/ddf/admin/application/service/impl/ApplicationServiceBeanMBean.java, platform/admin/core/admin-core-appservice/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/admin/core/admin-core-appservice/src/test/java/org/codice/ddf/admin/application/service/impl/ApplicationServiceBeanTest.java, platform/migration/platform-migration/pom.xml, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/ConfigurationMigrationManager.java, platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/migration/AbstractMigrationSupport.java, platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/migration/ConfigurationMigrationManagerTest.java, ui/packages/ui/src/main/webapp/js/models/Installer.js
It modified the installer UI such that when comes time to restart DDF, it actually does it not through karaf reboot behavior but takes advantage of the restart logic defined inside the `ddf` and `ddf.bat` scripts. This has the advantages that the ddf scripts will actually restart Solr as well if it needs to.
It also modified migration:import to do the same thing.
@ethantmanns 
@jhunzik 
@figliold
@tbatie
1- Unzip DDF and proceed through the UI installer
2- Click restart
3- Verify that Solr is being shutdown and then restarted in addition to DDF
4- Perform a migration:export
5- Perform a migration:import
6- Same as step 3
[DDF-4147](https://codice.atlassian.net/browse/DDF-4147)
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/ …
=> [2.13.x] DDF-4147 Modified UI installer and migration:import to restart Solr as well as DDF

catalog/transformer/catalog-transformer-pdf/src/main/java/ddf/catalog/transformer/input/pdf/PdfInputTransformer.java, catalog/transformer/catalog-transformer-pdf/src/main/resources/OSGI-INF/metatype/metatype.xml, distribution/docs/src/main/resources/content/_tables/ddf.catalog.transformer.input.pdf.PdfInputTransformer.adoc
Backports #3849 
It increases the `Maximum xml metadata length` to 5MB, since the previous default work for larger files
@oconnormi @mdang8 @kcover @emmberk @peterhuffer 
@clockard
@coyotesqrl 
Ingest a large PDF through the Content Directory Monitor
[DDF-4208](https://codice.atlassian.net/browse/DDF-4208) …
=> [2.13.X backport] DDF-4208 Increase default `Maximum xml metadata length` to 5MB.

catalog/core/catalog-core-actions/pom.xml, catalog/core/catalog-core-api-impl/pom.xml, catalog/core/catalog-core-api/pom.xml, catalog/core/catalog-core-camelcomponent/pom.xml, catalog/core/catalog-core-impl/pubsub-tracker/pom.xml, catalog/core/catalog-core-localstorageprovider/pom.xml, catalog/plugin/catalog-plugin-security-audit/pom.xml, catalog/rest/catalog-rest-endpoint/pom.xml, catalog/spatial/registry/registry-federation-admin-service-impl/pom.xml, catalog/spatial/registry/registry-report-action-provider/pom.xml, catalog/spatial/wfs/1.0.0/spatial-wfs-v1_0_0-source/pom.xml, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/pom.xml, catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/pom.xml, catalog/spatial/wfs/spatial-wfs-featuretransformer-handlebars/pom.xml, catalog/spatial/wfs/spatial-wfs-mapper/pom.xml, catalog/transformer/catalog-transformer-common/pom.xml, catalog/ui/catalog-ui-search-api/pom.xml, catalog/ui/catalog-ui-search/pom.xml, distribution/sdk/sample-transformers/xslt-identity-input-transformer/pom.xml
- Removes unused dependencies from `catalog-core-api` pom.
- Updates other poms to explicitly declare their dependencies they were receiving transitively from `catalog-core-api`
- This will break downstream projects if they do not explicitly depend on a dependency they were receiving transitively.
@emmberk @tbatie @stustison @clockard 
@codice/build 
@coyotesqrl
@vinamartin
Full build.
Noticed when doing a jackson upgrade that a lot of modules had transitive dependencies on jackson-core library because `catalog-core-api` defined the `org.codice.thirdparty/tika-bundle` dependency.
[DDF-2985](https://codice.atlassian.net/browse/DDF-2985)
Going to use this ticket and keep it open as a ticket for general cleanup of poms. …
=> DDF-2985 Cleanup unused catalog-core-api dependencies

platform/sync-installer/sync-installer-impl/pom.xml, platform/sync-installer/sync-installer-impl/src/main/java/org/codice/ddf/sync/installer/impl/SynchronizedInstallerImpl.java, platform/sync-installer/sync-installer-impl/src/main/java/org/codice/ddf/sync/installer/impl/WaitForReadyCommand.java, platform/sync-installer/sync-installer-impl/src/test/groovy/org/codice/ddf/sync/installer/impl/SynchronizedInstallerImplSpec.groovy
- Changing logging to print a diagnosis of the bundle instead of the headers & imports
- Added an option to the wait-for-ready command to specify time to wait
@troymohl 
@paouelle 
@coyotesqrl 
@figliold  
Run the wait for ready command on bundles in the failed/graceperiod state and ensure the logs look as expected.
```
admin@root()> wait-for-ready -wt 100
15:30:20,873 | INFO  | or-ready -wt 100 | installer.impl.SynchronizedInstallerImpl  444 | sync-installer-impl  | Printing unsatisfied bundle requirements:
---------------------------------------------------------------
Bundle Name: DDF :: Admin Console :: Query :: Security :: LDAP
Status: Failure
Diagnosis:
Blueprint
10/4/18 1:54 PM
Exception:
null
java.util.concurrent.TimeoutException
at …
```
=> DDF-4163: Improve SynchronizedInstaller bundle error logging

ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/user/user.tsx
Ran `yarn format -w` in the ddf/ui directory and this was the result. These two blank lines were causing local build failures on Windows. 
`[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6.CODICE:yarn (build) on project ui: Failed to run task: 'yarn run build' failed.`
in
`[INFO] C:\repos\ddf\ui\packages\catalog-ui-search\src\main\webapp\react-component\presentation\user\user.tsx
[INFO] => has formatting issues`
@ahoffer @garrettfreibott @ricklarsen @austinsteffes 
@codice/ui 
@figliold
Build the ui module. …
=> DDF-4106 Yarn format user.tsx file

distribution/docs/src/main/resources/content/_using/using-catalog-search-ui.adoc
When searching with a wildcard, beginning and end punctuation are stripped off to make sure the search is done solely on the word. Inner punctuation of the word is still valid. This updates the docs to let the user know that including punctuation at the beginning or the end of a word will not return the result. 
@jhunzik 
@ethantmanns 
@paouelle 
@tbatie 
@figliold 
Install and run DDF
Verify changes are there in the docs
https://codice.atlassian.net/browse/DDF-4214 …
=> [2.13.x] DDF-4214 Updated docs for searching with wildcard

distribution/docs/src/main/resources/content/_using/using-catalog-search-ui.adoc
Link to 2.13.x PR: #3868 
When searching with a wildcard, beginning and end punctuation are stripped off to make sure the search is done solely on the word. Inner punctuation of the word is still valid. This updates the docs to let the user know that including punctuation at the beginning or the end of a word will not return the result.
@ethantmanns 
@jhunzik 
@paouelle 
@tbatie 
@figliold 
@ricklarsen 
Install and run DDF
Verify changes are there in the docs
https://codice.atlassian.net/browse/DDF-4214 …
=> DDF-4214 Updated docs for searching with wildcard

dependency-check-maven-config.xml
Suppress geowebcache reported OWASP vulnerability. Geowebcache is off by default, and not recommended to be used in a production environment.
@paouelle @kcover @mdang8
@codice/build 
@clockard
@coyotesqrl
CI build.
[DDF-4231](https://codice.atlassian.net/browse/DDF-4231) …
=> DDF-4231 Fix OWASP scan for geowebcache

distribution/ddf-common/src/main/resources/security/default.policy, platform/security/sts/security-sts-ldapclaimshandler/src/main/java/ddf/security/sts/claimsHandler/ClaimsHandlerManager.java, platform/security/sts/security-sts-ldapclaimshandler/src/main/java/ddf/security/sts/claimsHandler/LdapClaimsHandler.java, platform/security/sts/security-sts-ldapclaimshandler/src/main/java/ddf/security/sts/claimsHandler/RoleClaimsHandler.java, platform/security/sts/security-sts-ldapclaimshandler/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/security/sts/security-sts-ldapclaimshandler/src/main/resources/OSGI-INF/metatype/metatype.xml, platform/security/sts/security-sts-ldapclaimshandler/src/test/java/ddf/security/sts/claimsHandler/RoleClaimsHandlerTest.java, platform/security/sts/security-sts-ldaplogin/src/main/java/ddf/ldap/ldaplogin/LdapConnectionPooledObjectFactory.java, platform/security/sts/security-sts-ldaplogin/src/main/java/ddf/ldap/ldaplogin/LdapLoginConfig.java, platform/security/sts/security-sts-ldaplogin/src/main/resources/OSGI-INF/blueprint/karaf_ldap_config.xml, platform/security/sts/security-sts-ldaplogin/src/main/resources/OSGI-INF/metatype/metatype.xml, platform/security/sts/security-sts-ldaplogin/src/test/java/ddf/ldap/ldaplogin/LdapLoginConfigTest.java, platform/security/sts/security-sts-ldaplogin/src/test/java/ddf/ldap/ldaplogin/LdapModuleTest.java
Link to 2.13.x PR: [#3665](https://github.com/codice/ddf/pull/3665)
____
Remove LDAP structure assumptions, enable LDAP login and attribute claims to work with nested user OUs, allow multiple ldap servers in a single configuration for load balancing / failover
@ryeats 
@KalCramer 
@coyotesqrl
@stustison
@tbatie
Create a user in a nested OU under the base user DN
Set their uid and cn to be different values (e.g. uid=user1, cn=User One)
Add the user to a group and verify that they can log in and that their group information is successfully added. If added to the admin group the user should be able to log into the admin console
[DDF-4090](https://codice.atlassian.net/browse/DDF-4090) …
=> DDF-4090 - Remove LDAP structure assumptions

catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/blueprint/blueprint.xml
Link to 2.13.x PR: #3796 
____
-->
BACKPORT - Fixes problem in master with Intrigue unable to get metacardtypes due to blueprint.xml parameter ordering on EndpointUtil.
@ethantmanns 
@jhunzik 
@paouelle 
@codice/ui 
@tbatie 
@figliold 
@clockard 
Build DDF and launch UI. Verify no errors in Inspector.
https://codice.atlassian.net/browse/DDF-4174 …
=> [2.13.x] DDF-4174 Fixed blueprint.xml parameter order for EndpointUtil

platform/security/certificate/security-certificate-keystoreeditor/src/main/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditor.java
Link to 2.13.x PR: [#3872](https://github.com/codice/ddf/pull/3872)
PKCS12 files typically have .p12 OR .pfx extenstions. Currently, DDF only accepts .p12 during installation. This PR allows for .pfx files to be uploaded as well.
@ahoffer 
@mcalcote 
@tbatie 
@stustison
Ensure that uploading a valid PKCS12 certificate with .pfx extension no longer returns an error in the installer. Ensure that an alias in the keystore matches the hostname being set.
[DDF-4216](https://codice.atlassian.net/browse/DDF-4216) …
=> DDF-4216: Allow pfx keystore upload during installation

ui/packages/catalog-ui-search/src/main/webapp/component/search-form-interactions/search-form-interactions.less, ui/packages/catalog-ui-search/src/main/webapp/component/search-form/search-form.hbs, ui/packages/catalog-ui-search/src/main/webapp/component/search-form/search-form.less, ui/packages/catalog-ui-search/src/main/webapp/component/search-form/search-form.view.js
The `Clear Default` option should only be available on the currently selected default (actions should be form specific). Mark the currently selected default form with icon for easy identification of current default.
@Schachte @Bdthomson @alanchampion 
@codice/ui
@bdeining 
- build/run
- enable search forms by creating ect/forms directory and enabling experimental
- in the UI start a new query and select `Use Another Search Form` and create multiple custom search forms
- verify that forms not selected as default have `Make Default` option available and no `Clear Default` option
- verify a form selected as default has a star displayed at the top right and has the `Clear Default` option available
- verify no regression in default search form functionality
- Delete the form …
=> DDF-4225 Update default search form behavior

ui/packages/catalog-ui-search/src/main/webapp/component/component.less, ui/packages/catalog-ui-search/src/main/webapp/component/search-form/search-form.collection.less, ui/packages/catalog-ui-search/src/main/webapp/component/search-form/search-form.collection.view.js
- Filters the search form page to only contain New Form button + all custom forms
- Centers the search forms page content so that it looks similar to the Workspaces page 
@andrewzimmer @Bdthomson 
@bdeining 
- Ensure that the Basic and Text searches are still available under "Use Another Search Form" in the search dropdown menu 
- Verify that the Search Forms page looks like the "after" screenshot below (note that I had the custom search forms enabled in the screenshot, which do not show up by default) 
[DDF-4256](https://codice.atlassian.net/browse/DDF-4256)
Before
After
- ✏️ …
=> DDF-4256 Filtered search forms page to only show New Form and Custom Forms

distribution/docs/src/main/resources/content/_architectures/_catalogFrameworks/standard-catalog-framework.adoc, distribution/docs/src/main/resources/content/_devComponents/editing-docs.adoc, distribution/docs/src/test/java/ddf/docs/DocumentationTest.java
Link to 2.13.x PR: [#3870]https://github.com/codice/ddf/pull/3870
Adds section to developers' docs on contributing/editing documentation.
@garrettfreibott @austinsteffes @ahoffer @mcalcote 
@codice/docs 
@clockard
@lessarderic
@shaundmorris
- Review content
- Builds successfully
[DDF-4194](https://codice.atlassian.net/browse/DDF-4194) …
=> DDF-4194 added how to contribute docs section to developers' docs

pom.xml
- Locks down maven-deploy-plugin version. Version 3.0.0-M1 now fails builds, instead of printing a warning, on modules with no primary artifact specified.
@paouelle @emmberk @oconnormi 
@codice/build 
@clockard
@tbatie
Full build.
In maven-deploy-plugin version 3.0.0-M1 now fails builds for modules without primary artifacts, whereas before it would look for attachments. Our feature modules have attachments, not primary artifacts. Version 2.8.2 only prints a warning.
[DDF-2985](https://codice.atlassian.net/browse/DDF-2985) …
=> [2.13.x] DDF-2985 Fix deploy for modules without primary artifact

catalog/transformer/catalog-transformer-xml/pom.xml, catalog/transformer/catalog-transformer-xml/src/main/java/ddf/catalog/transformer/xml/adapter/ObjectAdapter.java, catalog/transformer/catalog-transformer-xml/src/test/java/ddf/catalog/transform/xml/adapter/AttributeAdapterTest.java, catalog/transformer/catalog-transformer-xml/src/test/java/ddf/catalog/transform/xml/adapter/MetacardTypeAdapterTest.java
Resolves issue with metacard XML unmarshalling of object types. Object is now returned as the original Serializable instead of a byte array.
@paouelle 
@jhunzik 
@clockard
@figliold
@lessarderic
@tbatie
* Create metacard with an attribute that's an object type
* Federate it over CSW (so that it will be transferred over as metacard XML) OR query the metacardXML and re-ingest it
* Look at the resulting metacard and see if the object is preserved as its original type
* This affect CSW federation
[DDF-4264](https://codice.atlassian.net/browse/DDF-4264)
- ✏️ (Pencil) This comment is …
=> DDF-4264 Fixes XML unmarshaller object parsing

catalog/transformer/catalog-transformer-xml/pom.xml, catalog/transformer/catalog-transformer-xml/src/main/java/ddf/catalog/transformer/xml/adapter/ObjectAdapter.java, catalog/transformer/catalog-transformer-xml/src/test/java/ddf/catalog/transform/xml/adapter/AttributeAdapterTest.java, catalog/transformer/catalog-transformer-xml/src/test/java/ddf/catalog/transform/xml/adapter/MetacardTypeAdapterTest.java
Link to 2.13.x PR: #3924
____
Resolves issue with metacard XML unmarshalling of object types. Object is now returned as the original Serializable instead of a byte array.
@paouelle 
@jhunzik 
@clockard
@figliold
@lessarderic
@tbatie
* Create metacard with an attribute that's an object type
* Federate it over CSW (so that it will be transferred over as metacard XML) OR query the metacardXML and re-ingest it
* Look at the resulting metacard and see if the object is preserved as its original type
* This affect CSW federation
[DDF-4264](https://codice.atlassian.net/browse/DDF-4264) …
=> [FORWARDPORT] DDF-4264 Fixes XML unmarshaller object parsing (#3924)

catalog/catalog-app/pom.xml, catalog/catalog-app/src/main/resources/features.xml, distribution/ddf-common/src/main/resources-filtered/etc/application-definitions/security-services.json, features/test-utilities/src/main/feature/feature.xml, libs/test-common/src/main/java/org/codice/ddf/test/common/features/AppsFeatures.java, libs/test-common/src/main/java/org/codice/ddf/test/common/features/InstallProfilesFeatures.java, libs/test-common/src/main/java/org/codice/ddf/test/common/features/TestUtilitiesFeatures.java, libs/test-common/src/main/java/org/codice/ddf/test/common/options/BasicOptions.java, libs/test-common/src/main/java/org/codice/ddf/test/common/options/DebugOptions.java, libs/test-common/src/main/java/org/codice/ddf/test/common/options/LoggingOptions.java, libs/test-common/src/main/java/org/codice/ddf/test/common/options/PortOptions.java
- Changed configurations options for component tests to be recorded and
retrievable from a config file at runtime
- Cleaned up several features
- Added ldap services to security app json
@blen-desta 
@peterhuffer 
@coyotesqrl 
@figliold 
CI passes …
=> DDF-4259: Component tests configurations should be easily retrievable at test runtime

ui/packages/catalog-ui-search/src/main/webapp/component/visualization/table/row.view.js
Align the logic that determines if an attribute is hidden when rendering thumbnail hovers.
@brianfelix 
@jrnorth 
@leo-sakh 
@codice/ui 
@bdeining
To reproduce the error on master, add `^thumbnail$` to the list of hidden attributes in `Catalog UI Search Hidden Attributes`.  Upload a document that produces a thumbnail, such a PNG. Add the `Table` visual. The search results should indicate that there is one result, but no results will be shown. Also, in the javascript console, you should see a message like `Error: An "el" undefined must exist in DOM`. Repeat this steps with this PR and confirm that the search results are displayed and the console message is no longer present.
[DDF-4273](https://codice.atlassian.net/browse/DDF-4273) …
=> DDF-4273 properly handle hidden attributes in Table visual

catalog/validator/catalog-validator-metacardduplication/pom.xml, catalog/validator/catalog-validator-metacardduplication/src/main/java/org/codice/ddf/validator/metacard/duplication/DuplicationValidator.java, distribution/ddf-common/src/main/resources-filtered/etc/application-definitions/catalog.json
- Updated DuplicationValidator query filter to not include a `NOT id = <metacard_id>`, and instead filter out the metacard from the query result set.
This is because when we do a query by ID now, we do a Solr real time query. In the case of a `NOT id`, we attempt to query the real time index with the metacard ID, but this is not what we want in this particular case. This change was chosen for minimal impact.
- Adds Duplication Validator to the Catalog App json definition.
@kcover @pklinef @bakejeyner 
@codice/data 
@clockard
@figliold
Ingest an item via Intrigue. Ingest the same item again and verify a warning is placed on it.
This bug started occurring when query by ids were made to respect all of the query's filter.
[DDF-4217](https://codice.atlassian.net/browse/DDF-4217)
Please see …
=> [2.13.x] DDF-4217 Fix DuplicationValidator catalog query not returning results

distribution/ddf-common/src/main/resources/security/default.policy
Sync-installer attaches itself to the thread that's running
org.apache.karaf.features.core when installing a feature. This means
the sync-installer needs to have the same permissions as
karaf.features.core to avoid unwanted Access Control Exceptions.
@peterhuffer @emmberk @oconnormi @pvargas @mdang8 
@clockard
@tbatie
Contact me for testing steps. …
=> DDF-3945 Align sync-installer permissions with karaf.features.core

catalog/ui/catalog-ui-search/pom.xml, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/QueryApplication.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/suggestion/LatLon.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/suggestion/LatLonCoordinateProcessor.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/suggestion/MgrsCoordinateProcessor.java, catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/query/suggestion/LatLonCoordinateProcessorTest.java, catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/query/suggestion/MgrsCoordinateProcessorTest.java, catalog/ui/search-ui-app/src/main/resources/features.xml, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/map.less, ui/packages/catalog-ui-search/src/main/webapp/react-component/auto-complete/auto-complete.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/location/gazetteer.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/location/keyword.js
The gazetteer search box will now identify MGRS coordinates entered into the box and users can pan to the extent of those coordinates. 
@BernardIgiri 
@Variadicism 
@samuelechu 
@codice/ui 
@bdeining 
@millerw8
- Use wizard under the *catalog* category of configuration
- Select a provider (https://wiki.openstreetmap.org/wiki/Tile_servers)
- Uncheck _Proxy Imagery Provider URL
Ensure the offline gazetteer is being used. Literal suggestions are not currently supported with the online one. Try typing some MGRS coordinates into the search box and panning around **both** maps using this technique. 
Some examples:
1. `12S` should yield itself as a suggestion and pan to the main grid with AZ in view
1. `12S VB` should yield itself as a suggestion and pan to the 100 km grid encompassing the south …
=> DDF-4238 As a user, I would like to enter MGRS coordinates into the gazetteer search box so I can pan to a certain location quickly

platform/error/platform-error-impl/src/main/resources/codeMessages.properties, platform/error/platform-error-servlet/src/main/java/org/codice/ddf/platform/error/servlet/ErrorServlet.java
Errors from the backend that happen during a POST request were not being handled by the ErrorServlet, so the default Jetty error page was being shown instead. (see screenshot below)
@Kjames5269 @bakejeyner 
@clockard
@coyotesqrl 
- Spin up DDF
- Go to https://localhost:8993/services/csw
- Login to the IdP
- Our custom error page should display with a 403 instead of the 405 like the below screenshot.
[DDF-4284](https://codice.atlassian.net/browse/DDF-4284) …
=> [2.13.x]DDF-4284 Adding POST support for the ErrorServlet

ui/packages/catalog-ui-search/src/main/webapp/component/select/select.collection.view.js
Link to master PR: #3660
[BACKPORT] Using an advanced search in Intrigue and searching the field with the dropdown (defaulted to anyText) returns results based on the real value, not the label. This made it confusing for users because what was searched for was not always displayed. Now the results in the dropdown correspond with what is being searched. 
@paouelle 
@jhunzik
@codice/ui
@tbatie
@figliold
Create a new advanced query in Intrigue and add a new field. Open the field drop down (defaults to anyText) and type "created" to get results and "ext.created" to not get results. Search other attributes and verify that they autocomplete based on what is displayed to the user. 
[](https://codice.atlassian.net/browse/DDF-4099) …
=> [2.13.x] DDF-4099 Search should autocomplete on label, not real value

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/MetacardApplication.java, catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/blueprint/blueprint.xml
This PR is an amendment to https://github.com/codice/ddf/pull/3893 to allows privilege `system-user` to view all workspaces
@millerw8
@bdeining
@rzwiefel
@bdeining
@millerw8
Quickbuild and install DDF standard profile
login as admin
create a new workspace
logout and login as localhost
navigate to the workspace page
verify workspace created earlier by admin is available
https://codice.atlassian.net/browse/DDF-4220 …
=> DDF-4220 allows system-user to query for all workspaces

features/security/src/main/feature/feature.xml, pom.xml
Upgrades DDF to depend on `cas-client-core` 3.5.0, and changes the `security-cas` feature to install the thirdparty CAS client bundle. The thirdparty bundle contains a fix that allows DDF to support CAS auth behind a proxy.
This PR depends on https://github.com/codice/thirdparty/pull/27
@alexaabrd @brendan-hofmann @vinamartin @beyelerb 
[DDF-4286](https://codice.atlassian.net/browse/DDF-4286)
- ❓ …
=> [2.13.x] DDF-4286 Upgrade to Codice thirdparty CAS client bundle

ui/packages/catalog-ui-search/src/main/webapp/component/search-form-selector/search-form-selector.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/search-form/forms-sharing/search-form-sharing-tab-container.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/search-form/forms-sharing/search-form-sharing.collection.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/search-form/search-form-tab-container.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/search-form/search-form.collection.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/search-form/search-form.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/tabs/search-form/tabs.search-form.view.js
Remove search form interaction menu when accessing the search form via the workspace.
@leo-sakh 
@brianfelix 
@jrnorth 
@codice/ui 
@bdeining
First, create a search form as admin. Confirm that the search form menu interaction is not displayed when accessing via the workspace. Confirm that the search form menu interaction is displayed when accessing via the Search Form component. Share the search form with guest. Logout and re-enter as guest. Confirm that the interaction menu is displayed under the collection of shared search forms when accessing via the Search Form component and not display when accessing via the workspace. 
[DDF-4283](https://codice.atlassian.net/browse/DDF-4283) …
=> DDF-4283 remove search form interaction menu when accessing the search form via the workspace

distribution/docs/src/main/resources/content/_running/editing-attributes.adoc
adds a warning to the docs for metadata editing that metacards that come from connected sources or fanout will appear local but will not be editable. 
@garrettfreibott @mcalcote @ahoffer @austinsteffes 
@codice/docs 
@clockard
@lessarderic
@shaundmorris
Review content
[DDF-4305](https://codice.atlassian.net/browse/DDF-4305) …
=> DDF-4305 updated docs for editing metadata attributes

ui/packages/catalog-ui-search/src/main/webapp/behaviors/dropdown.behavior.utility.js
- Legacy dropdowns weren't seeing clicks inside the new dropdowns.
- Updates the dropdown code to properly check clicks.
@djblue 
@Bdthomson 
@andrewzimmer 
@Schachte 
@rzwiefel 
Verify that the dropdown in the screenshot (
=> DDF-4106 Fixes dropdown interop

ui/packages/catalog-ui-search/src/main/webapp/react-component/location/gazetteer.js
Fixes check for multipolygon. Before it was incorrectly identifying single polygons as multipolygons
@gjvera 
@bdeining 
@djblue 
1. Build and install
2. Verify that the gazetteer box in the top-right is working with online data
- Search for several locations, and ensure that it pans correctly.
3. Run `gazetteer:update "$ddf.data/countries.geo.json"` from Karaf (updates the offline gazetteer data).
4. Turn off online gazetteer in the admin console.
5. Verify that the gazetteer box in the top-right is working with offline data
- Search for a combination of multipolygons and single polygons (examples below and more can be found from the `countries.geo.json` file
- Multipolygons: Russia, Italy, Canada, United States of America
- Polygons: Dominican Republic, Algeria, South …
=> DDF-4324 Fixed Multipolygon Check in Gazetteer Box

ui/packages/catalog-ui-search/src/main/webapp/component/query-advanced/query-advanced.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/search-form-editor/search-form-editor.view.js
Adds some validation for creating search forms. Titles cannot be blank when saving.
@willwill96 @GabrielFabian 
@codice/ui 
@djblue 
Go to search forms page and attempt to create a search form with no title
verify error message is displayed
[DDF-4321](https://codice.atlassian.net/browse/DDF-4321) …
=> DDF-4321 Search forms can be saved with no title

catalog/plugin/catalog-plugin-metacardbackup-s3storage/pom.xml, catalog/plugin/catalog-plugin-metacardbackup-s3storage/src/main/java/org/codice/ddf/catalog/plugin/metacard/backup/storage/s3storage/MetacardS3StorageRoute.java, catalog/plugin/catalog-plugin-metacardbackup-s3storage/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/plugin/catalog-plugin-metacardbackup-s3storage/src/main/resources/OSGI-INF/metatype/metatype.xml, catalog/plugin/catalog-plugin-metacardbackup-s3storage/src/test/java/org/codice/ddf/catalog/plugin/metacard/backup/storage/s3storage/MetacardBackupS3StorageTest.java
Fixes how the S3 endpoint is set with the changes in Camel 2.22. Need to construct the AmazonS3 client using the clientbuilder. 
@ryeats 
@Bdthomson 
@codice/io 
@bdeining
@clockard
In order to fully test, you need to have an S3 environment present. Configure the Metacard S3 Route to connect to S3 and verify that ingesting catalog data writes a file to S3.
The correct way to connect to a specific S3 endpoint changed with Camel 2.22. Since everything is property driven (vs compiled API), this change was not noticed during the Camel 2.22 upgrade.
[DDF-4297](https://codice.atlassian.net/browse/DDF-4297) …
=> DDF-4297 Fix camel S3 connection with changes in Camel 2.22

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/forms/TemplateTransformer.java, catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/forms/TemplateTransformerTest.java
Backend will properly handle missing or empty titles on submitted search forms. 
@Schachte 
@gjvera 
@bdeining 
@millerw8
@codice/io
Try to save a new search form with an empty or blank title. The exception should be logged at DEBUG on the backend and the UI should correctly prompt the user to fix the mistake. 
[DDF-4321](https://codice.atlassian.net/browse/DDF-4321) …
=> DDF-4321 Adds backend validation for search forms with missing or empty titles

ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/dropdown/dropdown.tsx
- The new dropdown styling wasn't taking the bottom / top styling into account.  So if it was too close to the bottom and flipped, the styling was still such that it stayed on the bottom (whereas the height updated as if it wasn't).  This caused the dropdown to go off the screen.
@Lambeaux 
@djblue 
@bellcc 
@andrewzimmer 
@bdeining 
@codice/ui  …
=> DDF-4106 Updates new dropdown to take bottom or top into account

catalog/pom.xml, catalog/ui/catalog-ui-search/pom.xml, platform/admin/pom.xml, pom.xml
Fixes a bug in [#3918](https://github.com/codice/ddf/pull/3918) where jacoco coverage reports were not being generated. The fix is to remove the empty default `<jacoco.argline/>` property from the root pom and let jacoco set `jacoco.argline` instead.
@blen-desta 
@Kjames5269 
@willwill96 
@clockard
@coyotesqrl 
On both Mac and Windows, run `mvn clean verify` under `<ddf_home>/catalog/ui/catalog-ui-search`. Verify that jacoco coverage checks are being ran:
```
[INFO] --- jacoco-maven-plugin:0.8.1:check (default-check) @ catalog-ui-search ---
[INFO] Loading execution data file C:\Projects\Source\ddf\catalog\ui\catalog-ui-search\target\jacoco.exec
[INFO] Analyzed bundle 'catalog-ui-search' with 151 classes
[INFO] All coverage checks have been met.
[INFO] …
```
=> DDF-4260 Fix surefire argline to include jacoco

distribution/ddf-common/src/main/resources/etc/hazelcast.xml
Disables the Hazelcast listener on port 5701 by default.
@rzwiefel 
@tbatie 
@clockard
@shaundmorris 
@stustison
Build and run the distribution and make sure that port 5701 isn't open (eg. nmap, telnet or netcat)
[DDF-4337](https://codice.atlassian.net/browse/DDF-4337) …
=> [2.13.x] DDF-4337: Disable Hazelcast Port 5701 by Default

catalog/plugin/catalog-plugin-metacardbackup-s3storage/pom.xml, catalog/plugin/catalog-plugin-metacardbackup-s3storage/src/main/java/org/codice/ddf/catalog/plugin/metacard/backup/storage/s3storage/MetacardS3StorageRoute.java, catalog/plugin/catalog-plugin-metacardbackup-s3storage/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/plugin/catalog-plugin-metacardbackup-s3storage/src/main/resources/OSGI-INF/metatype/metatype.xml, catalog/plugin/catalog-plugin-metacardbackup-s3storage/src/test/java/org/codice/ddf/catalog/plugin/metacard/backup/storage/s3storage/MetacardBackupS3StorageTest.java
Backport to 2.13.x of https://github.com/codice/ddf/pull/3987
This fixes configuration of Camel S3 with the Camel 2.22 upgrade.
@ryeats 
@Bdthomson 
@codice/io 
@bdeining
@clockard
In order to fully test, you need to have an S3 environment present. Configure the Metacard S3 Route to connect to S3 and verify that ingesting catalog data writes a file to S3.
The correct way to connect to a specific S3 endpoint changed with Camel 2.22. Since everything is property driven (vs compiled API), this change was not noticed during the Camel 2.22 upgrade.
[DDF-4297](https://codice.atlassian.net/browse/DDF-4297) …
=> [2.13.x] DDF-4297 Fix camel S3 connection with changes in Camel 2.22

ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/cesium/map.cesium.js, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/map.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/openlayers/map.openlayers.js, ui/packages/catalog-ui-search/src/main/webapp/js/model/User.js
Allow the user to save the current map location and zoom, and then return to that location by clicking the Home button. Also, zoom to home when a new workspace is created.
NOTE: The "Save" button is temporary. @andrewkfiedler and @Lambeaux have plans to convert the map code to React, which will make it easy to implement a "split button dropdown" that will combine the Home and Save buttons.
@brianfelix 
@jrnorth 
@leo-sakh 
@codice/ui 
@bdeining
Navigate to a variety of map locations and zoom levels. Click the Save button (next to the Home button). Navigate to a different location and map. Click the Home button. Confirm that the map
returns to the desired location. Test with extreme locations, like being zoomed all the way out. …
=> DDF-4325 Allow the user to set their home location for 2D and 3D maps

catalog/confluence/catalog-confluence-source/src/main/java/org/codice/ddf/confluence/source/ConfluenceInputTransformer.java, catalog/confluence/catalog-confluence-source/src/test/java/org/codice/ddf/confluence/source/ConfluenceInputTransformerTest.java, catalog/confluence/catalog-confluence-source/src/test/resources/anonymous_user_response.json
- Make username no longer required from a Confluence response when transforming results into Metacards. Instead put "Unknown" if username is not present.
@emmberk @kcover @pvargas @mdang8 
@codice/io 
@clockard
@vinamartin
Query a confluence server for anonymous content. See me for details.
[DDF-4347](https://codice.atlassian.net/browse/DDF-4347) …
=> [2.13.x] DDF-4347 Allow Confluence to query anonymous content

ui/packages/catalog-ui-search/src/main/webapp/component/router/router.less, ui/yarn.lock
Makes the indicator for visual placement visible again on the UI
@bdeining
- Drag visuals around as in the video below and ensure you can see an indicator 
- ❗ …
=> DDF-4351 Made visualization placement indicator visible again

catalog/opensearch/catalog-opensearch-source/pom.xml, catalog/opensearch/catalog-opensearch-source/src/main/java/org/codice/ddf/opensearch/source/OpenSearchSource.java, catalog/opensearch/catalog-opensearch-source/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/opensearch/catalog-opensearch-source/src/main/resources/OSGI-INF/metatype/metatype.xml, catalog/opensearch/catalog-opensearch-source/src/test/groovy/org/codice/ddf/opensearch/source/OpenSearchSourceSpec.groovy, distribution/docs/src/main/resources/content/_reference/_tables/OpenSearchSource.adoc, libs/geospatial/src/main/java/org/codice/ddf/libs/geo/util/GeospatialUtil.java, libs/geospatial/src/test/java/org/codice/ddf/libs/geo/GeoUtilTest.java
Adds a utility to convert point radii searches into more accurate multi-polygon searches.
@bdeining @Schachte @troymohl @millerw8 
@bdeining
Full build
Configure an opensearch source
Turn on CXF logging
Perform anygeo searches with multiple point radii searches
verify on the outgoing opensearch url, the geometry collection contains the correct circle polygon data
[DDF-3914](https://codice.atlassian.net/browse/3914) …
=> DDF-3914 added better approximation of multi point radius anyGeo search

ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-old.js, ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-old.view.js
Fixes incorrect model attribute name which prevents clearing of field when switching tabs in the anyGeo component
@Variadicism 
@Lambeaux 
@dimitry-sherman
@BernardIgiri 
@codice/ui 
@bdeining
@millerw8 
Verify that upper Left Northing field is cleared when switching tabs to/from Bounding Box in the anyGeo component.
Tested switching to/from all different shapes
[DDF-4301](https://codice.atlassian.net/browse/DDF-4301) …
=> DDF-4301 anyGeo BBox - upper-left northing field not cleared when switching shape tabs

distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/catalog/CatalogTestCommons.java, distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/config/ConfigureTestCommons.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalog.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalogValidation.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFanout.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestSecurityAuditPlugin.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestSpatial.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestSecurity.java
The primary purpose is to clean up the usages of the test configuration helper methods defined in ConfigureTestCommons, but also achieves the following:
* Makes configuration helper methods return old props so tests can better reset themselves
* Makes configuration helper methods wait and check to make sure the configuration change was registered before proceeding
* Fixes AuthzRealm configuration method in ConfigureTestCommons
* Added more useful rest helper methods to CatalogTestCommons
* Cleans up lots of static analysis findings
* Simplifies TestCatalogValidation (reduces much unnecessary configuration)
* Removes un-needed configuration in TestCatalog
* Fixes tests in TestSecurity that were not working as intended (did not cover what they were intended to cover)
* Localizes TestSpatial …
=> DDF-3955 DDF itest configuration cleanup

distribution/docs/src/main/resources/content/scripts.html
Tables elements in the documentation (tables, codeblocks, notes, warnings, etc) didn't obey max-width and overflowed , so in the Admin UI's iFrame they were being cut off. This PR makes all table elements scrollable when they exceed the max-width.
@mcalcote
@ahoffer
@codice/docs
@codice/ui
@vinamartin
Build docs and deploy generated docs in distribution/docs/target/docs/html/.asciidoctor to /documentation/ddf/docs-2.14.0-SNAPSHOT/html/
Verify all tables and codeblocks are visible from the admin UI
DDF-4349
Checklist:
Update / Add …
=> [2.13.x] DDF-4349 Make documentation table elements scroll at max-width

ui/packages/catalog-ui-search/src/main/webapp/component/filter-builder/filter-builder.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/query-add/query-add.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/query-advanced/query-advanced.view.js
Forward ports #4006 
Applies UI fixes to Intrigue for handling anyText queries made with the different search forms to support legacy sources. Changes the default text input in basic and simple search forms to be blank. Changes the default `anyText` input in advanced forms to be `*`. For all three forms, the default query will be `anyText is like %`. Adding temporal/spatial criteria in basic forms will result in not defaulting to adding an `anyText is like %` filter in the query.
@peterhuffer @pvargas @kcover @emmberk
@codice/ui 
@clockard
- Open Intrigue and start a search with an advanced form
- Verify that there is a `*` value pre-filled in the `anyText` input
- Click `Search` and verify that the resulting query is `anyText is like %`
- Edit the search and clear the …
=> DDF-4300 UI fix for advanced queries when anyText input is blank

ui/packages/catalog-ui-search/src/main/webapp/react-component/menu/menu.js
This changes menu behavior to select the first item in the menu by default.
@Lambeaux 
@BernardIgiri  
@codice/ui
@djblue 
* Build and install.
* Open a workspace.
* Open the Gazetteer search box atop a map and type in two or more characters. The characters must result in one or more suggestions. Check that the first item in the list of suggestions that appears is highlighted.
* Hit Enter. The Gazetteer search suggestions dropdown should close and the first suggestion should now appear in the search box. The map should pan and zoom to the location of the selected Gazetteer geography.
* Change the characters inserted to generate new suggestions and hit Enter again. Ensure that the map now closes the search bar with your new first suggestion and pans and zooms to the new …
=> DDF-4357 Select the first item in menus when opened

distribution/ddf-common/src/main/resources/etc/log4j2.config.xml, distribution/ddf-common/src/main/resources/etc/org.ops4j.pax.logging.cfg, distribution/ddf-common/src/main/resources/security/configurations.policy, distribution/ddf-common/src/main/resources/security/default.policy, distribution/docs/src/main/resources/content/_securing/auditing.adoc
This PR
* Updates ddf.log pattern in log4j2.config.xml to match org.ops4j.pax.logging.cfg
* Updates formatting in the Enabling Fallback Audit Logging documentation
* Fixes a permission to read log4j2.config.xml. The permission was back-ported in #3828 without reverting the file name change made in #3609.
@brjeter @bakejeyner @blen-desta @Kjames5269
@clockard
@vinamartin
* With a fresh zip, unzip, and start up DDF. (You do not need to install.)
1. Confirm that log commands work (`log:set`, `log:tail`, `log:get`).
2. Confirm that the format of log files look correct.
* With a fresh zip, unzip, and follow the `Enabling Fallback Audit Logging` of the documentation to use the log4j2.config.xml log configuration file instead of the org.ops4j.pax.logging.cfg log configuration file. (You do not …
=> [2.13.x] DDF-4369 Fixed permission to enable fallback audit logging

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/suggestion/MgrsCoordinateProcessor.java, catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/query/suggestion/MgrsCoordinateProcessorTest.java, pom.xml
Zones such as 67Q or 90K will still produce suggestions and the map will pan to some location, but it will be nonsense. In a typical scenario this isn't too bad because users familiar with MGRS realize these values don't have significance.
However, the suggestion itself is still misleading. Revise the suggester so that MGRS with invalid zone numbers do not appear as suggestions.
@millerw8
@Variadicism 
@bdeining 
@Lambeaux 
@samuelechu 
Try entering an invalid MGRS zone such as 0 or 64, no suggestion should be displayed. …
=> #DDF-4360 MGRS suggestions still appear when zone numbers are out of bounds

ui/packages/catalog-ui-search/src/main/webapp/react-component/menu/menu.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/menu/menu.spec.js
When a menu is opened or its children are changed, it has to select an active element if an element still existing there was not active before. In this case, if a menu item is selected, then it is intuitive to make the same element active.
@BernardIgiri 
@samuelechu 
@codice/ui
@djblue
* Navigate to a units selection menu. One can be found for the "Radius" field in the search editor by selecting "Somewhere Specific" under "Located", then "Point Radius" under "Location".
* Open the menu. Ensure that the selected unit value (the one with a :white_check_mark: next to it) is also active. Active elements often but don't always have a thin blue box around them. If it does not, use the arrow keys to shift the active element to locate it.
* Open the Gazetteer search box on the top …
=> DDF-4366 Make the default active element upon opening a menu the selected item if there is one

distribution/ddf-common/src/main/resources/etc/log4j2.xml, distribution/ddf-common/src/main/resources/etc/org.ops4j.pax.logging.cfg, distribution/ddf-common/src/main/resources/security/configurations.policy, distribution/docs/src/main/resources/content/_managing/_securing/auditing.adoc
Link to 2.13.x PR: https://github.com/codice/ddf/pull/4088
This PR is not a clean cherry-pick. It does not update the permission in default.policy, and it removes a warning in Enabling Fallback Audit Logging section of the documentation that is no longer an issue in Karaf 4.2.0 ([KARAF-5354](https://issues.apache.org/jira/browse/KARAF-5354)).
After this PR, these files should match between 2.13.x and master:
- auditing.adoc
- configurations.policy
- org.ops4j.pax.logging.cfg
- log4j2.xml
@kcover @blen-desta 
@codice/docs 
@brjeter
@clockard
This PR does not need to be manually tested because it does not make any functional changes that needs to be heroed.
[DDF-4369](https://codice.atlassian.net/browse/DDF-4369) …
=> DDF-4369 Updated formatting in the Enabling Fallback Audit Logging documentation

catalog/core/catalog-core-commons/src/main/java/ddf/util/XPathHelper.java, catalog/core/catalog-core-commons/src/test/java/ddf/catalog/impl/XPathHelperTest.java
ABBREVIATED REVIEW BETWEEN 2.13.X AND MASTER IS IN EFFECT
Link to 2.13.x PR: #4106 
This PR allows XPathhelper print to analyze and print xml attributes
@garrettfreibott @ahoffer @mcalcote 
@brjeter
@clockard
@vinamartin
[DDF-4382](https://codice.atlassian.net/browse/DDF-4382) …
=> DDF-4382 XPathHelper print removes the tags and attributes from the results

ui/packages/catalog-ui-search/src/main/webapp/js/model/QueryResponse.js
Fixes an issue when making searches in Intrigue where there are 250+ results returned. The counts at the bottom of the result list now match with the expected number of results. The queued results are changed to reset instead of being added because the add operation is slow enough that it can cause partial merges to happen and results being removed. The issue was more commonly observed on Firefox browsers than Chrome because the operation was finishing outside of the default auto-merge time threshold.
@emmberk @kcover @peterhuffer @pvargas @brianfelix 
@codice/ui 
@clockard 
- Open Intrigue in a Chrome browser
- Ingest 265 (or any number greater than 250) metacards using the UI uploader
- Start a wildcard search and verify that the results text at the top query details box …
=> DDF-4367 Fix search results merging in Intrigue

platform/admin/core/admin-core-impl/src/main/java/org/codice/ddf/admin/core/impl/SystemPropertiesAdmin.java, platform/admin/core/admin-core-impl/src/test/java/org/codice/ddf/admin/core/impl/SystemPropertiesAdminTest.java, ui/packages/ui/src/main/webapp/js/models/installer/Configuration.js, ui/packages/ui/src/main/webapp/js/views/installer/Configuration.view.js, ui/packages/ui/src/main/webapp/less/installer/style.less
Adds internal hostname and port to the installer and reverts https://github.com/codice/ddf/pull/3841. 
Updates less because the titles are slightly longer. 
Should the behavior for ?dev=true remain the same?
@mcalcote @oconnormi @austinsteffes 
@clockard
Walk through the installer and make sure that updating the external and internal ports takes effect. 
Verify you can still log in after using ?dev=true
[DDF-4350 Installer doesn't allow users to input internal/system hostname and port](https://codice.atlassian.net/browse/DDF-4350) …
=> DDF-4350 Add internal/system hostname and port to the installer

ui/packages/ui/src/main/webapp/templates/installer/finish.handlebars
Realigns the "Restart now" and "Restart later" buttons on the last screen of the installer wizard.
@mdang8  @pvargas @oconnormi @mcalcote 
@codice/ui 
@clockard
[DDF-4375](https://codice.atlassian.net/browse/DDF-4375) …
=> DDF-4375 Added classes to realign navigation buttons

ui/packages/catalog-ui-search/src/main/webapp/react-component/container/workspaces-items-container/workspaces-items-container.tsx
Fixes a bug with work spaces not being sorted by last modified due to a change in how dates were formatted.
@pvargas @mdang8 @oconnormi 
@codice/ui 
@vinamartin
1. In DDF Intrigue, create a new workspace named "Workspace 1".
2. Then repeat step 1, this time naming them "Workspace 2" and "Workspace 3".
3. On the workspaces screen set the sorting order to "last modified".
4. The order of the workspaces should be "Workspace 3", "Workspace 2", "Workspace 1".
5. Enter "Workspace 2" and execute a search, then hit save.
6. Back on the workspaces screen the order should now be "Workspace 2", "Workspace 3", "Workspace 1".
The change from boon to GSON (#3986) meant that date format had changed as well. In this case a date that used to be a number (as seconds from the epoch) became a …
=> DDF-4381 Fixing sorting order of recently used workspaces

distribution/ddf-common/src/main/resources/etc/log4j2.xml, distribution/ddf-common/src/main/resources/etc/org.ops4j.pax.logging.cfg
The solr.log file “${karaf.data}/log/solr.log” is not used now that Solr runs as its own process.
This removes it from our logging configuration.
@ahoffer @austinsteffes @ricklarsen @mcalcote 
@clockard
@tbatie
Verify there is no longer a solr.log in the /data/log directory and that there are no errors in the log about the logging configuration on startup. 
[DDF-4406 Remove references to unsed solr.log file](https://codice.atlassian.net/browse/DDF-4406) …
=> DDF-4406 Removes references to unused solr.log file

ui/packages/catalog-ui-search/src/main/webapp/component/query-interactions/query-interactions.hbs
Removes refresh result count button from UI. The "Refresh Result Count" button on the release branch will be removed as it is not needed for current release branch needs and this satisfies the requirements of this bug ticket
@mcalcote 
@ahoffer 
@shaundmorris
@vinamartin
clean quick build and check that button is removed …
=> [2.13.x] DDF-4120 Remove Refresh Result Count in UI

ui/packages/catalog-ui-search/src/main/webapp/component/search-form-editor/search-form-editor.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/search-form/search-form-tab-container.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/search-form/search-form.js, ui/packages/catalog-ui-search/src/main/webapp/component/search-form/search-form.view.js
Changes to search form settings (Sorts, Source and Result Form) were being saved on the backend, but weren't being properly displayed in the editor after refresh. This PR moves the flattening of these attributes, which are nested in `querySettings`, so that they can be accessed in the search form editor
@bdeining
- Create and save a search form with settings different from the defaults
- Refresh the page
- Open that search form in the editor
- Verify that the correct settings are displayed
This PR depends on [DDF-4368](https://github.com/codice/ddf/pull/4135)
[DDF-4411](https://codice.atlassian.net/browse/DDF-4411) …
=> DDF-4411 Making search form settings persist after refresh

ui/packages/catalog-ui-search/src/main/webapp/js/CQLUtils.js, ui/packages/catalog-ui-search/src/main/webapp/js/CQLUtils.spec.js, ui/packages/catalog-ui-search/src/main/webapp/js/cql.js, ui/packages/catalog-ui-search/src/main/webapp/js/cql.spec.js
Correctly maintains or removes double quotes around property names when swapping between CQL and the Filter AST / JSON. 
@Variadicism 
@samuelechu 
@codice/ui 
@bdeining 
Inspect the search forms network traffic and ensure attribute names on the Filter JSON are **not** wrapped in double quotes. 
Inspect regular query network traffic (turn off websockets) and ensure property names on the CQL string are always wrapped in double quotes. 
Ingest data and ensure querying still returns the expected results. Repeat the test with the local catalog turned off and an OpenSearch loopback source turned on. 
As the UI evolves, the lack of adequate semantic validation for search forms is causing Solr to be polluted with heterogeneous or invalid values. This is a crucial step to fix an …
=> DDF-4410 Fix issue where search form attribute names were being wrapped in double quotes

catalog/core/catalog-core-eventcommands/pom.xml, catalog/core/catalog-core-eventcommands/src/main/java/org/codice/ddf/catalog/pubsub/command/ListCommand.java, catalog/core/catalog-core-eventcommands/src/test/java/org/codice/ddf/catalog/pubsub/command/ListCommandTest.java, distribution/ddf-common/src/main/resources/security/default.policy, platform/security/rest/security-rest-cxfwrapper/src/main/java/org/codice/ddf/cxf/paos/PaosInInterceptor.java, ui/packages/catalog-admin-module-sources/src/main/webapp/js/model/Source.js, ui/packages/catalog-admin-module-sources/src/main/webapp/js/model/Status.js
* Fixes PAOS Interceptor to support backend HTTP DELETE requests to secured REST. This required changing the interceptor to compute the request content length correctly.
* Cleans up old source polling events when changes are made in the Sources UI. Previously, old events weren't removed and while using the Sources UI outdated events would spam the backend.
* Resolves an AccessControlException in the subscriptions:list command.
* Improves the output of the subscriptions:list command so an admin can tell whether it's an enterprise subscription or a source-specific subscription.
@bakejeyner @blen-desta @Kjames5269 @brjeter 
@coyotesqrl
TEST 1: Sources UI
1. Create a new source in the sources UI, and open the browser dev tools to view the network tab.
2. Select and close the source edit modal …
=> [2.13.x] DDF-{4365, 4370, 4372, 4374} Minor bugfixes/improvements

ui/packages/registry-admin-remote-ui/src/main/webapp/less/styles.less
Adds a CSS fix to keep long texts from breaking out their textboxes in popovers.
@pvargas 
@mdang8 
@emmberk 
@clockard 
Verify in downstream project.
Implement a popover with a long unbreaking string of text. Verify it does not break out of the popover.
[DDF-4409](https://codice.atlassian.net/browse/DDF-4409) …
=> [2.13.x] DDF-4409 Fixing CSS to keep text breaking out of popovers

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/MetacardApplication.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalogSearchUi.java
- Fixes a bug where a workspace created from another workspace that already has 10 queries cannot be saved. 
- Updates integration tests for this use case. 
@coyotesqrl 
@vinamartin
- Create a workspace with 10 metacards.
- Add another query and select `Create New Workspace From Search`
- Save this newly created workspace. 
- Verify that the workspace and query are properly associated by refreshing the page.
The workspace/query metacard separation changed the data model. Previously `POST /workspaces` was never called with any existing queries. Consequently this endpoint wasn't creating the query metacards it needed so it was created a detached association. 
[DDF-4412](https://codice.atlassian.net/browse/DDF-4412) …
=> DDF-4412 Cannot save new workspace created from another workspace

distribution/docs/src/main/resources/content/_configuring/hiding-errors-by-role.adoc
Updated docs for hiding errors and warnings from users based on roles to suggest making roles unique to the system if the admin wishes to hide invalid results from all external systems. If the user roles are very common, it is possible for another system to duplicate those roles for their own users and see results they were not intended to see.
@peterhuffer 
@jhunzik 
@codice/docs 
@rzwiefel
@tbatie
@vinamartin
Build and inspect documentation.
This is a docs update to support the changes added in https://github.com/codice/ddf/pull/3931.
[DDF-4224](https://codice.atlassian.net/browse/DDF-4224) …
=> DDF-4424 Updated Metacard Validity Filter Plugin docs

ui/packages/registry-admin-remote-ui/src/main/webapp/less/styles.less
Link to 2.13.x PR: #4152
Adds a CSS fix to keep long texts from breaking out their textboxes in popovers.
@pvargas 
@mdang8 
@emmberk 
@clockard 
Verify in downstream project.
Implement a popover with a long unbreaking string of text. Verify it does not break out of the popover.
[DDF-4409](https://codice.atlassian.net/browse/DDF-4409) …
=> DDF-4409 Fixing CSS to keep text breaking out of popovers

ui/packages/catalog-ui-search/src/main/webapp/component/ingest-editor/ingest-editor.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/property/property.collection.view.js
Before this change we were initializing the upload editor properties to the default which has showValidationIssues to true. This caused values with a list of suggested attributes to become required and as a result unable to be saved without selecting an option.
This sets showValidationIssues to false on load since we validate before trying to upload. 
@SmithJosh @mcalcote @austinsteffes @rzwiefel 
Navigate to the Admin UI -> Search UI -> Configuration -> Catalog UI Search.
Configure a few attributes, one with some provided values and another without any. (As shown in this screenshot for example). 
Navigate to Intrigue and select Upload. 
Verify that you don't see any errors on load. 
Upload an item without selecting any values for either of the upload …
=> DDF-4415 Initializes upload editor to not show validation issues on load

ui/packages/catalog-ui-search/src/main/webapp/component/result-selector/result-selector.less, ui/packages/catalog-ui-search/src/main/webapp/component/result-selector/result-selector.view.js, ui/packages/catalog-ui-search/src/main/webapp/js/model/QueryResponse.js
Fixes the issue where if a user has the table view open. Preference http requests are sent multiple times per second
@Bdthomson 
@codice/ui 
@bdeining 
Ingest data
Set up multiple loopback sources
Open the network tab in dev tools
Look at the `preferences` requests that are being sent out
ensure there are not requests being sent out after the query is done …
=> DDF-4431 Updates results rendering to be debounced

distribution/docs/src/main/resources/content/_managing/_configuring/hiding-errors-by-role.adoc
Link to 2.13.x PR: #4172 
____
Updated docs for hiding errors and warnings from users based on roles to suggest making roles unique to the system if the admin wishes to hide invalid results from all external systems. If the user roles are very common, it is possible for another system to duplicate those roles for their own users and see results they were not intended to see.
@peterhuffer 
@jhunzik 
@codice/docs 
@rzwiefel
@tbatie
@vinamartin
Build and inspect documentation.
This is a docs update to support the changes added in https://github.com/codice/ddf/pull/3931.
[DDF-4224](https://codice.atlassian.net/browse/DDF-4224) …
=> DDF-4424 Updated Metacard Validity Filter Plugin docs (#4172)

distribution/ddf-common/src/main/resources/etc/users.attributes
add required roles to users.attributes so that a bunch of unnecessary roles don't have to be created in a credential store on a secured system.
@beyelerb 
@clockard 
@stustison …
=> DDF-4396 Add required roles to users.attributes

catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/DumpCommand.java, catalog/core/catalog-core-solrcommands/pom.xml, catalog/core/catalog-core-solrcommands/src/main/java/org/codice/ddf/commands/solr/BackupCommand.java, catalog/core/catalog-core-solrcommands/src/main/java/org/codice/ddf/commands/solr/RestoreCommand.java, catalog/core/catalog-core-solrcommands/src/main/java/org/codice/ddf/commands/solr/SolrCommands.java, catalog/core/catalog-core-solrcommands/src/test/java/org/codice/ddf/commands/solr/BackupCommandTest.java, catalog/core/catalog-core-solrcommands/src/test/java/org/codice/ddf/commands/solr/RestoreCommandTest.java, catalog/core/catalog-core-solrcommands/src/test/java/org/codice/ddf/commands/solr/SolrCommandTest.java, distribution/docs/src/main/resources/content/_managing/_running/available-console-commands.adoc, distribution/docs/src/main/resources/content/_managing/_running/solr-commands.adoc, platform/solr/solr-factory-impl/src/main/java/org/codice/solr/factory/impl/HttpSolrClientFactory.java, platform/solr/solr-factory-impl/src/main/java/org/codice/solr/factory/impl/SolrCloudClientFactory.java, platform/solr/solr-factory-impl/src/test/groovy/org/codice/solr/factory/impl/HttpSolrClientFactorySpec.groovy
This fixes the catalog:dump command to work correctly for Solr cloud. Updates the solr:backup for Solr 7 cloud and also refactors the code slightly to support the addition of the solr:restore command.
@Bdthomson 
@rymach 
@dannythk 
@mcalcote 
@ahoffer 
@codice/solr 
@bdeining
@pklinef
@ricklarsen 
Manual testing would require a Solr 7 cloud instance that you can backup/restore various cores. 
*Merged* This PR includes changes in https://github.com/codice/ddf/pull/4160. Once that PR has been merged, this one will be rebased. 
[DDF-4218](https://codice.atlassian.net/browse/DDF-4218) …
=> DDF-4218 Fix solr:backup and add solr:restore command

ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-old.js
Fixes a boolean condition that was erroneously inverted and caused Intrigue's USNG/MGRS point-radius input box to break.
@samuelechu 
@Lambeaux 
@codice/ui 
@bdeining 
1. Ingest some records with location metadata.
2. Open Intrigue with either a 2D or 3D map view (or both).
3. Open Advanced Search.
4. Select the anyGeo field.
5. Select Point-Radius.
6. Select USNG/MGRS.
7. Type a valid USNG or MGRS string into the box.
8. Verify a circle is drawn on the map in the expected location.
9. Run the search and verify the results returned are within the circle.
[DDF-4428](https://codice.atlassian.net/browse/DDF-4428) …
=> DDF-4428 Fix USNG/MGRS point-radius input box

ui/packages/catalog-ui-search/src/main/webapp/component/search-form/forms-sharing/search-form-sharing.collection.js
If there are any system search forms present in the `forms` directory, they will also appear in the Shared search forms tab. This pr fixes that bug
@bdeining 
@djblue 
[DDF-4438](https://codice.atlassian.net/browse/DDF-4438) …
=> DDF-4438 Fixing system search forms in shared tab

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/CachingFederationStrategy.java, catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/cache/solr/impl/CachingFederationStrategyTest.java
`CachingFederationStrategy` was dropping distance & relevancy scores . This pr fixes that.
@blen-desta 
@Kjames5269 
@brjeter
@coyotesqrl
Ask me for test steps.
[DDF-4377](https://codice.atlassian.net/browse/DDF-4377) …
=> [2.13.x]DDF-4377 Fix the dropped relevancy score when querying by id

catalog/confluence/catalog-confluence-source/src/main/resources/OSGI-INF/blueprint/blueprint.xml
DDF-4452 Fix Confluence connected source blueprint constructor args
@kcover @peterhuffer 
@mcalcote
@vinamartin
Install DDF and create a confluence connected source and verify it can connect to a confluence server (shows as available in AdminUI Sources tab)
This blueprint update was missed when DDF-4047 worked
[DDF-4452](https://codice.atlassian.net/browse/DDF-4452)
=>  DDF-4452 Fix Confluence connected source blueprint constructor args

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/util/EndpointUtil.java, catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/util/EndpointUtilTest.java
The GsonBuilder in EndpointUtil currently uses inconsistent time formats; this sets it to ISO
@bdeining
@djblue
- Create a workspace
- Look at the workspace network request
- Verify that the date formats match the second screenshot below, not the first
[DDF-4441](https://codice.atlassian.net/browse/DDF-4441)
**BEFORE**
**AFTER** …
=> DDF-4441 Set date/time format in EndpointUtil

ui/packages/catalog-ui-search/src/main/webapp/component/search-form/search-form.view.js
Fixes intermittent search button disappearance. 
@Schachte 
@adimka 
@middlets719 
@codice/ui 
@bdeining
Follow defect reproduction steps in [DDF-4449](https://codice.atlassian.net/browse/DDF-4449) and verify that defect does not manifest. Test for regressions in search form + workspace functionality, specifically related to persistence of user's choices of workspace/search forms after refreshing the browser. 
[DDF-4449](https://codice.atlassian.net/browse/DDF-4449) …
=> DDF-4449 Advanced Search - Intermittent Search button disappears from the template

ui/packages/catalog-ui-search/src/main/webapp/component/golden-layout/golden-layout.less
Set golden-layout-toolbar height to 0
Fixes a CSS problem where Search UI tabs disappear when adding attributes in the inspector.
@pvargas 
@mdang8 
@rfding
@aperullo 
@codice/ui 
@emmberk
@oconnormi
1. Pull and build DDF
2. Ingest records into DDF.
3. Go to the Search UI, search for the documents.
4. In the **Inspector** window, select the **Details** tab. Select **Actions -> Add**, and add any attribute from the dropdown.
5. Verify that the tab for the **Inspector** window is still visible. Test that the tab remains visible for different configurations of the window within the layout.
[DDF-4067](https://codice.atlassian.net/browse/DDF-4067)
Before
After …
=> [2.13.x] DDF-4067 Tabs in Intrigue are hidden after adding an attribute

features/solr/src/main/feature/feature.xml, platform/platform-filter-delegate/pom.xml, platform/platform-filter-delegate/src/main/java/org/codice/ddf/platform/filter/delegate/FilterInjector.java, platform/solr/platform-solr-server-standalone/pom.xml, platform/solr/platform-solr-server-standalone/src/main/webapp/WEB-INF/web.xml, pom.xml
Link to 2.11.x PR: https://github.com/codice/ddf/pull/4212
DelegateServletFilter was not being added properly to the embedded solr, so it was added manually to the web.xml and an exception was added so that it does not get applied programmatically.
Also adds a fixed maven-install-plugin version. A newer version was being pulled in and causing build failures.
@tbatie 
@bakejeyner 
@ryeats 
@codice/solr 
@clockard 
@stustison
@tbatie 
@vinamartin 
Attempt to access anything under the /solr context at https://<ddf_url>:8993/solr/ and ensure that it redirects you to a login page like similar protected contexts.
This affects the embedded Solr only, so a similar PR will also be made to the 2.11.x branch. The 2.13.x and master branches use a standalone Solr that works properly. …
=> [2.12.x] DDF-4440: Resolve Authentication Inconsistency with Embedded Solr

distribution/sdk/pom.xml, platform/migration/platform-migration/pom.xml, platform/platform-filter-delegate/pom.xml, platform/platform-filter-delegate/src/main/java/org/codice/ddf/platform/filter/delegate/FilterInjector.java, platform/solr/platform-solr-server-standalone/pom.xml, platform/solr/platform-solr-server-standalone/src/main/webapp/WEB-INF/web.xml
Link to 2.12.x PR: https://github.com/codice/ddf/pull/4206
DelegateServletFilter was not being added properly to the embedded solr, so it was added manually to the web.xml and an exception was added so that it does not get applied programmatically.
Also removes sample-cometd from the build as it uses Bower, which is no longer available.  I didn't remove the code itself because it could still be useful as historical reference. This also mimics how we have this code in master -- available, but not part of the build.
@tbatie 
@bakejeyner 
@ryeats 
@codice/solr 
@clockard 
@stustison
@tbatie 
@vinamartin 
Attempt to access anything under the /solr context at https://<ddf_url>:8993/solr/ and ensure that it redirects you to a login page like similar protected contexts.
This …
=> [2.11.x] DDF-4440: Resolve Authentication Inconsistency with Embedded Solr

distribution/docs/src/main/resources/content/_sources/default-storage-provider.adoc, distribution/docs/src/main/resources/content/_sources/registry-store.adoc
Adds configuration documentation for the default Content File System Storage Provider.
@bakejeyner @austinsteffes @ahoffer 
@codice/docs 
@brjeter
@clockard
@lessarderic
@mcalcote
@shaundmorris
new content included in a successful build
[DDF-4470](https://codice.atlassian.net/browse/DDF-4470) …
=> DDF-4470 added documentation for Content File System Storage Provider

catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/LatestCommand.java, distribution/docs/src/main/resources/content/_running/catalog-commands.adoc
Currently, the Latest Command uses the modified time to determine the order for displaying the latest records which can be confusing since a record with an old modified time may show up out of order even though it is freshly ingested. 
It should be using the new taxonomy Metacard.Modified to show the records in the correct order.
@Kjames5269 @AzGoalie 
@emmberk
@ethantmanns 
Ingest anything. Run catalog:latest and verify the things you ingested show up.
Ingest the following (ingest -t xml) and verify it shows up at the top of the list despite having an older modified date:
```<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<metacard xmlns="urn:catalog:metacard">
<type>ddf.metacard</type>
<source>ddf.distribution</source>
<string name="title">
<value>sample metacard</value> …
```
=> [2.13.x] DDF-4473 Changes Latest Command to use Metacard.Modifed instead of Modified

ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/map.model.js, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/map.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/openlayers/map.openlayers.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/utils/wrap-num/index.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/utils/wrap-num/wrap-num.tsx
Ensures that the longitude in `map.openlayers.js` is normalized to be within the valid range of [-180,180]
@bdeining
@millerw8
Verify that the tooltip is still working correctly with DMS and decimal on the 2D map
[DDF-4448](https://codice.atlassian.net/browse/DDF-4448) …
=> DDF-4448 Normalized longitude in Map view

catalog/core/catalog-core-solr/pom.xml, catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/SolrFilterDelegate.java, catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/provider/SolrProviderQuery.java
Fixes a bug with anyText equality searches where results were still returned when searching with only part of the field value. Example: A metacard with Title="Look a title" would still be returned if you made a query with `anyText = "Look"`
@Kjames5269 
@vinamartin 
@codice/solr 
@emmberk
@pklinef
- Ingest a metacard with a title (or some other text field)
- Perform an anyText equality search on that field and verify you only get the result back when the search phrase matches the field exactly.
[DDF-4445](https://codice.atlassian.net/browse/DDF-4445)
- [ n/a] Update / Add Threat Dragon models …
=> [2.13.x] DDF-4445 Add logic to apply the correct Solr field suffix to the anyText equality queries

distribution/ddf-common/src/main/resources/security/default.policy
When using the feature install command for a feature that drops a config file in etc, an `AccessControlException` was occurring. This fixes that.
@coyotesqrl 
@emmberk 
- Install through the UI
- Restart, using the "Restart Now" button
- When the system is back up: `feature:install broker-app`
- Verify the command completes successfully without printing an `AccessControlException` to stdout.
[DDF-4480](https://codice.atlassian.net/browse/DDF-4480) …
=> DDF-4480 Add permission for feature install command

catalog/core/catalog-core-solr/pom.xml, catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/SolrFilterDelegate.java, catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/provider/SolrProviderQuery.java
Link to 2.13.x PR: #4205 
Fixes a bug with anyText equality searches where results were still returned when searching with only part of the field value. Example: A metacard with Title="Look a title" would still be returned if you made a query with `anyText = "Look"`
@Kjames5269 
@emmberk 
@codice/solr 
@vinamartin
@pklinef
- Ingest a metacard with a title (or some other text field)
- Perform an anyText equality search on that field and verify you only get the result back when the search phrase matches the field exactly.
[DDF-4445](https://codice.atlassian.net/browse/DDF-4445)
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Requ …
=> DDF-4445 Add logic to apply the correct Solr field suffix to the anyText equality queries 

.github/ISSUE_TEMPLATE.md, .github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/improvement.md
Gets the conversation started on fixing the issue template. There are issues that aren't just bugs that also need to be addressed and handled gracefully by the template without making it into a cluttered mess.
I'd love to hear thoughts on the suggestion. This only addresses issues that are categorized into improvements, documentation and bugs.
The hardest issue to handle is documentation since that needs the least information about it, only a description and version, but for improvements and bug issues you can discuss what the expected behavior is `after` the change is implemented, and bugs issues just need the rest of the information. 
@coyotesqrl @ricklarsen @rymach @vinamartin 
@codice/website ?
Consider different issues that may arise and see if they are gracefully handled by the …
=> DDF-04286 First pass at trying to improve the issue template

platform/persistence/platform-persistence-commands/src/main/java/org/codice/ddf/persistence/commands/AbstractStoreCommand.java
Changes the store:list --help output for "-t" to output the same choices as it does when given an invalid input.
From
> attributes, preferences, metacard, saved_query, notification, activity, subscriptions or workspace
to
> metacard, saved_query, notification, activity, workspace, preferences, attributes, subscriptions, event_subscriptions, alerts, or decanter
@pvargas @mdang8 @oconnormi 
@clockard
@vinamartin
[DDF-4378](https://codice.atlassian.net/browse/DDF-4378) …
=> DDF-4378 Making store:list options consistent across --help and -t

platform/persistence/platform-persistence-commands/src/main/java/org/codice/ddf/persistence/commands/AbstractStoreCommand.java
Backports #4102 
Changes the store:list --help output for "-t" to output the same choices as it does when given an invalid input.
From
> attributes, preferences, metacard, saved_query, notification, activity, subscriptions or workspace
to
> metacard, saved_query, notification, activity, workspace, preferences, attributes, subscriptions, event_subscriptions, alerts, or decanter
@pvargas @mdang8 @oconnormi 
@clockard
@vinamartin
[DDF-4378](https://codice.atlassian.net/browse/DDF-4378) …
=> [2.13.x] DDF-4378 Making store:list options consistent across --help and -t

distribution/docs/src/main/resources/content/_architectures/_resources/url-resource-reader.adoc
Link to 2.13.x PR: #4296
The order for the docs of the URL Resource Reader is a little bit confusing. This PR changes the order to have the permissions mentioned first and then configuring, to match the CDM's documentation.
@ahoffer
@austinsteffes
@codice/docs 
@brjeter
@ricklarsen
Build docs and verify configuring the permissions is mentioned before configuring the URL Resource Reader is mentioned
For GH Issues:
Fixes: #4295 …
=> DDF-04295 Reorder documentation for URL Resource Reader to match CDMs layout

ui/packages/catalog-ui-search/src/main/webapp/component/list-interactions/list-interactions.hbs, ui/packages/catalog-ui-search/src/main/webapp/component/list-interactions/list-interactions.less, ui/packages/catalog-ui-search/src/main/webapp/component/list-interactions/list-interactions.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/list-item/list-item.collection.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/list-item/list-item.hbs, ui/packages/catalog-ui-search/src/main/webapp/component/list-item/list-item.less, ui/packages/catalog-ui-search/src/main/webapp/component/list-item/list-item.view.js
Setting the ID of the List to user preferences for the List chosen as default
Adding the 'Make Default List' option to the 3 dot menu of each List
Adding the 'Clear Default List' option to the 3 dot menu of the List set as default
Adding a comparator to the list-item.collection.view to set default List to top of list
This PR adds the ability to set a list as default. The default list will move to the top of the list and have the star icon.
@Schachte @middlets719 @zta6 @adimka @djblue @bdeining 
@bdeining
@djblue
Install DDF
Open Intrigue.
Open a workspace
Select the Lists tab
Create a few new lists
Verify they are ordered by name
Open the 3 dot menu of a List and select `Make Default List`
Verify the List is moved to the top of the lists and it has the star icon
Open the 3 dot menu of the …
=> DDF-04262 Add the ability to set a default list

features/camel/src/main/feature/feature.xml, features/pom.xml, platform/admin/core/admin-core-insecuredefaults/pom.xml
Upgrades Camel's transitive `c3p0` version `0.9.5.2` dependency from the Quartz component(s) to `0.9.5.3`. Embedded versions used by pure quartz have not been touched. 
@bdeining 
@stustison
Full build followed by thorough testing of features that use scheduling over Camel. Re-test the following PR's testing steps: https://github.com/codice/ddf/pull/2551
Fixes: #4320  …
=> DDF-04320 Force Camel's quartz component to use newer version of c3p0

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/security/AccessControlAccessPlugin.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/security/AccessControlPreIngestPlugin.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/security/AccessControlUtil.java, catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/security/AccessControlAccessPluginTest.java, catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/security/AccessControlPolicyPluginTest.java, catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/security/AccessControlUtilTest.java, catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/security/AclTestSupport.java, catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/security/AclTestSupportTest.java
Fixes an issue where direct use of the metacard `PATCH` endpoint could result in sharing permissions being changed incorrectly. 
@Schachte 
@samuelechu 
@stustison
Setup the DDF distro with two new users, by modifying `users.properties` and `users.attributes` respectively:
_users.properties_
```
kyle=kyle,group,viewer
steve=steve,group,viewer
```
_users.attributes_
```
"steve" : {
"http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress":"steve@localhost.local"
},
"kyle" : {
"http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress":"kyle@localhost.local"
}
```
Have user `steve` create two search forms and share them with `kyle` at the READ/WRITE level, **not** READ-ONLY or READ/WRITE/SHARE levels (kyle's email …
=> DDF-4447 Patching metacards directly over HTTP should consider the context of sharing attribute changes

catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/data/impl/MetacardTypeImpl.java, catalog/core/catalog-core-attributeregistry/pom.xml, catalog/spatial/kml/spatial-kml-transformer/src/test/java/org/codice/ddf/spatial/kml/transformer/MockMetacardType.java, catalog/spatial/registry/registry-common/src/main/java/org/codice/ddf/registry/common/metacard/RegistryObjectMetacardType.java, catalog/spatial/wfs/spatial-wfs-common/src/main/java/org/codice/ddf/spatial/ogc/wfs/catalog/common/FeatureMetacardType.java, catalog/transformer/catalog-transformer-common/src/main/java/ddf/catalog/transformer/common/tika/Mp4MetacardType.java
Optimizes the `MetacardTypeImpl.getAttributeDescriptor` call such that a lazy-initialized map is created the first time it is called, and used for subsequent calls after that to avoid a O(n) operation on each call.
@zta6 
@leo-sakh 
@bdeining
@pklinef
@rzwiefel 
@clockard 
The lazy-initialization approach was taken due to the number of places that `descriptors` is directly added to by subclasses. This keeps the changeset small while still providing a performance improvement benefit.
Fixes: #04261 …
=> DDF-04261 Optimize MetacardTypeImpl getAttributeDescriptor

platform/security/idp/security-idp-client/src/main/java/org/codice/ddf/security/idp/client/LogoutRequestService.java, ui/packages/security-servlet-logout/src/main/resources/logout-response.html
This PR adds better logging to inform the user that they are not actually logged out after a failed automatic logout attempt. This occurs about 5% of the time, and the other times, it returns a successful logout. 
@ahoffer 
@brjeter 
@stustison 
1. Install and login through the UI
2. Wait and be idle on the UI until session expiring countdown executes
3. Have chance of being redirected to a successful logout, or `Unable to logout. Please try again.`
It was discovered that there was a null pointer exception from a race condition. Due to being extremely rare to reproduce, it was decided to just better log that the user is not logged out. 
For GH Issues:
Work for: #4316 
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/7 …
=> [2.13.x] DDF-04316 Add better logging for failed automatic logout

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/MetacardApplication.java, catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/metacard/MetacardApplicationTest.java
These represent logically separate fixes (discovered with the same set of tests). 
Fixes an NPE in the metacard `PATCH` endpoint. Also adds unit tests and fixes a separate issue revealed by those tests. **Do not squash commits** when merging. They are logically separate fixes that compile independently. 
@Schachte 
@samuelechu 
@codice/ui 
@stustison
Attempt a `PATCH` request to `https://localhost:8993/search/catalog/internal/metacards` with a target metacard ID that: 
1. Does not exist
2. The user subject does not have permission to see
Verify the response is `404` and not `500`; also ensure the stacktrace is logged at DEBUG and is not an NPE logged at ERROR. 
Sample HTTP Body for the `PATCH` request: 
```
[
{
"ids": [ …
```
=> DDF-4450 Patching metacards directly over HTTP results in an NPE when the metacard to be patched does not exist

catalog/spatial/registry/registry-source-configuration-handler/src/main/java/org/codice/ddf/registry/source/configuration/SourceConfigurationHandler.java, platform/admin/core/admin-core-impl/pom.xml, platform/admin/core/admin-core-impl/src/main/java/org/codice/ddf/admin/core/impl/ConfigurationAdminImpl.java, platform/admin/core/admin-core-impl/src/test/java/org/codice/ddf/admin/core/impl/ConfigurationAdminImplTest.java
Disabling sources that are created with a configuration file will cause the source to be deleted. This is because the property `felix.fileinstall.filename` is being copied to the disabled when it should not be. This pr fixes this and ensures only the correct properties are copied.
@Bdthomson @Lambeaux 
@troymohl @bdeining 
[DDF-4471](https://codice.atlassian.net/browse/DDF-4471) …
=> DDF-4471 Disabling sources sometimes causes them to disappear from the sources tab in the Admin UI

platform/security/idp/security-idp-client/src/main/java/org/codice/ddf/security/idp/client/LogoutRequestService.java, ui/packages/security-servlet-logout/src/main/resources/logout-response.html
Link to 2.13.x PR: #4319 
This PR adds better logging to inform the user that they are not actually logged out after a failed automatic logout attempt. This occurs about 5% of the time, and the other times, it returns a successful logout.
@ahoffer 
@brjeter 
@stustison 
1. Install and login through the UI
2. Wait and be idle on the UI until session expiring countdown executes
3. Have chance of being redirected to a successful logout, or `Unable to logout. Please try again.`
It was discovered that there was a null pointer exception from a race condition. Due to being extremely rare to reproduce, it was decided to just better log that the user is not logged out.
For GH Issues:
Fixes: #4316  …
=> DDF-04316 Add better logging for failed automatic logout

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/QueryApplication.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/ws/JsonRpc.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/ws/SecureWebSocketException.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/ws/SecureWebSocketServlet.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/ws/WebSocketAuthenticationException.java, ui/packages/catalog-ui-search/src/main/webapp/js/model/QueryResponse.js
Updates the backend of Intrigue's WebSocket implementation to get the User's security token holder, when the WebSocket connection is initially opened. Then, at every request, the security token holder is checked. If it's empty, send an error because the user is no longer logged in under the same Http session.
**NOTE:** The third commit is the most complex change to review, but that commit should be easier to review if you review it in on its own.
@coyotesqrl
@djblue
@stustison
- Ingest some records and run some queries to make sure Intrigue is working normally.
- With one of the executed queries still up, open a new tab for the AdminUI and logout.
- Go back to Intrigue and edit the open query and/or execute it.
- The query should now return no …
=> [2.13.x]DDF-04318 Check that the user is logged in for every Intrigue WebSocket request

ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/map.less
- Adds space around the map actions / buttons so that the user is more
easily able to associate them with the map, and so that overall it's
more aesthetically pleasing.
@TeresaHudson 
@tbatie 
@jhunzik 
@samuelechu 
@mcalcote 
Open the 2d and 3d maps and verify there is space around them.  Verify it works on smaller screens as well.
For GH Issues:
Fixes: #4338
=> DDF-04338 Adds space around the map actions / buttons

distribution/docs/src/main/resources/content/_managing/_configuring/environment-hardening.adoc
Adds documentation mentioning that shell commands are disabled by default due to security concerns. Also documents the existence of a whitelist for shell commands.
@glenhein 
@rzwiefel 
@codice/docs
@coyotesqrl
@ricklarsen 
Build and view documentation section.
Fixes: #4367  …
=> DDF-04367 Add documentation on shell command whitelist

features/admin/src/main/feature/feature.xml, features/camel/src/main/feature/feature.xml
The default users deletion was not working or showing notifications to the AdminUI after removing the camel-quartz2 dependency when updating c3p0. This PR is a quick fix to add the camel-quartz2 feature and fix the wrap for the c3p0 artifact. 
@ahoffer
@Lambeaux
@bjeter
@emmberk
@stustison
See #4370
Work for: #4370 
Example of AdminUI notification  …
=> [2.13.x] DDF-04370 Fixed quartz2 feature dependency for DefaultUsersDeletionScheduler

catalog/plugin/catalog-plugin-metacard-validation/src/main/resources/OSGI-INF/metatype/metatype.xml, distribution/ddf-common/src/main/resources/etc/ddf.catalog.metacard.validation.MetacardValidityFilterPlugin.config, distribution/ddf-common/src/main/resources/etc/users.properties, distribution/docs/src/main/resources/content/_managing/_configuring/hiding-errors-by-role.adoc, distribution/docs/src/main/resources/content/_managing/_securing/hardening-checklist.adoc, distribution/docs/src/main/resources/content/_reference/_tables/MetacardValidityFilterPlugin.adoc, distribution/test/itests/test-itests-common/src/main/resources/etc/test-users.properties, platform/admin/core/admin-core-impl/src/main/java/org/codice/ddf/admin/core/impl/SystemPropertiesAdmin.java, platform/security/sts/security-sts-propertyclaimshandler/src/test/resources/users.properties
Link to 2.13.x PR: #4388 
At installation, a role including the hostname is added and used in the MetacardValidityFilterPlugin
@ahoffer @tyler30clemens
@brjeter
@lessarderic
@mcalcote
* Install with dev=true
* Navigate to admin ui -> catalog -> configuration -> Metacard Validation Filter Plugin
* Make sure Attribute Map's value contains ${your host name}-data-manager
* Upload invalid metacard in catalog. Ensure you can see the result in the search
* Sign out and sign in as admin. Ensure you can NOT see the result in the search
For GH Issues:
Fixes: #4321 
- ✏️ …
=> DDF-4321 adding new role with hostname to control validation filtering

distribution/docs/src/main/resources/content/_configuring/environment-hardening.adoc
*BACKPORT OF #4369*
Adds documentation mentioning that shell commands are disabled by default due to security concerns. Also documents the existence of a whitelist for shell commands.
@glenhein 
@rzwiefel 
@codice/docs
@coyotesqrl
@ricklarsen 
Build and view documentation section.
Fixes: #4367  …
=> DDF-04367 Add documentation on shell command whitelist (#4369)

ui/packages/catalog-ui-search/src/main/webapp/component/filter/filter.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-old.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-serialization.js, ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-serialization.spec.js, ui/packages/catalog-ui-search/src/main/webapp/component/query-advanced/query-advanced.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/query-basic/query-basic.view.js, ui/packages/catalog-ui-search/src/main/webapp/js/CQLUtils.js, ui/packages/catalog-ui-search/src/main/webapp/js/model/Query.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/container/metacard-interactions/index.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/location/keyword.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/location/location.js
One common complaint we have received is the lack of preservation pertinent to queries being saved from Intrigue.
**Two Main Issues:**
* Queries saved from a keyword re-render as a polygon or multipolygon (keyword metadata is lost and not preserved)
* Queries saved from bounding box re-render as polygon (bbox corner points are not preserved and fail to reconstruct the correct bbox mode)
This user experience is strange and causes a lot of confusion due to lack of preserved information related to the original query.
@Bdthomson 
@bdeining 
@middlets719 
@adimka 
@bdeining 
@troymohl 
@millerw8 
@djblue 
Create queries for all the location types using the advanced query builder, persist them, refresh, ensure that bbox and keywords persisted and reloaded correctly. 
Fixes: …
=> DDF-04346 - Preserving Original Query Structure For Advanced Queries

ui/packages/catalog-ui-search/src/main/webapp/component/search-form/search-form.collection.view.js
This PR [DDF-4449](https://github.com/codice/ddf/pull/4211) fixed a defect where the search button was replaced by a 'save' button in advanced search forms. 
Then search forms were refactored and it seems the defect was reintroduced in the refactor. 
This new PR re-applies the fix in the proper place after the refactor. 
@codice/ui 
@djblue
Follow reproduction steps on ticket [DDF-4449](https://codice.atlassian.net/browse/DDF-4449), verify that defect does not manifest itself.
Verify there is no regression in search forms; check that if you select a certain type of search form (basic/advanced/text) and then refresh the page the search button defaults to the previously selected form type.
For Jira:
[DDF-4449](https://codice.atlassian.net/browse/DDF-4449)
For GH Issues: …
=> DDF-4449 re-apply fix for intermittent save button appearing in search forms

ui/packages/catalog-ui-search/src/main/webapp/component/map-info/map-info.view.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/utils/left-pad/index.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/utils/left-pad/left-pad.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/utils/left-pad/leftpad.spec.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/utils/wrap-num/wrap-num.spec.js
Before, the `leftPad` method in `map-info.view.js`, which is used in the tooltip's `<span>` to format the latitude and longitude, was being passed `Math.floor(lat)` and `Math.floor(lon)`. This caused the off-by-one error because when `Math.floor()` is evaluated on -179.152798 for example, it returns -180. This PR makes some adjustments to avoid the off-by-one behavior on negative decimal coordinates in both the 2D and 3D maps.
@Bdthomson 
@andrewzimmer 
@nsuvarna 
@bdeining
@djblue 
Follow the steps to reproduce in the issue and verify that you now see the expected behavior
For GH Issues:
Fixes: #4363 
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging …
=> DDF-04363 Fixed off-by-one error for negative decimal coordinates in tooltip

catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/DumpCommand.java, catalog/core/catalog-core-commands/src/test/java/org/codice/ddf/commands/catalog/DumpCommandTest.java, catalog/transformer/catalog-transformer-zip/pom.xml, catalog/transformer/catalog-transformer-zip/src/main/java/org/codice/ddf/catalog/transformer/zip/ZipCompression.java, catalog/transformer/catalog-transformer-zip/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/transformer/catalog-transformer-zip/src/test/java/org/codice/ddf/catalog/transformer/zip/ZipCompressionTest.java, catalog/transformer/catalog-transformer-zip/src/test/resources/export.html
- Modifies `ZipCompressor` so that it no longer requires an absolute file path to function properly. 
- Adds the ability to export the metacards with a different file format such as HTML. 
@derekwilhelm 
@jlcsmith 
@rzwiefel 
- Ingest a couple of metacards
- Invoke the query response transformer. You can use this postman request. 
- The CQL in the attached request matches everything. 
- Note that you may have to add a `.zip` onto the downloaded file to be able to unpack it. This is not a failure of the transformer but one of the client that you're using. 
- Verify that no regressions in the `catalog:dump` command exist. 
- We wanted the ability to export a result set as a compressed file. 
[DDF-4465](https://codice.atlassian.net/browse/DDF-4465)
Please see …
=> DDF-4465 Export metacards to a compressed file in a specified format

ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/openlayers/map.openlayers.js
We initially added a utility function in openlayers API to support drawing on the map for MultiPolygons.
This achieved the overarching task of drawing the polygons correctly, but failed to do anything more advanced, like listen to model changes on buffer, etc.
Fortunately, this is actually already fully covered and taken care of here:
[/ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/openlayers/map.openlayers.js@`master`#L596](https://github.com/codice/ddf/blob/master/ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/openlayers/map.openlayers.js#L596)
The redundant (and confusing) function that does the same thing, but less is here:
[/ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/openlayers/map.openlayers.js@` …
=> DDF-4422 Removing Openlayers MultiPolygon Rendering Utility

ui/packages/catalog-ui-search/src/main/webapp/react-component/container/marionette-region-container/marionette-region-container.spec.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/container/marionette-region-container/marionette-region-container.tsx
- Fixes this.region undefined in Marionette Region Container
- The issue would happen if the view prop to the component changed
before the component was able to be initially mounted to the DOM.
Since we only use props (no local state), updating componentDidUpdate
to return until this.region exists is sufficient.
- Added a test for this scenario.
@djblue 
@tbatie 
@samuelechu 
@adimka 
Ensure the build passes, specifically the new test.  If you want to try out the failure, update the component to not have my changes and run the test.  It'll fail without them.
So far nothing in the codebase updates the props in this manner, but once https://github.com/codice/ddf/pull/4310 is in that will no longer be the case.  Basically, this is to prevent future issues.
For GH Issues:
Fixes: #4411 
Please …
=> DDF-04411 Fixes this.region undefined issue in MRC

features/admin/src/main/feature/feature.xml, features/camel/src/main/feature/feature.xml
Link to 2.13.x PR: #4377 
The default users deletion was not working or showing notifications to the AdminUI after removing the camel-quartz2 dependency when updating c3p0. This PR is a quick fix to add the camel-quartz2 feature and fix the wrap for the c3p0 artifact.
@ahoffer 
@Lambeaux 
@brjeter 
@stustison 
@emmberk 
See #4377 and its comments 
For GH Issues:
Fixes: #4370 
- ❓ …
=> DDF-04370 Fixed quartz2 feature dependency for DefaultUsersDeletionScheduler

platform/security/idp/security-idp-client/src/main/java/org/codice/ddf/security/idp/client/IdpLogoutActionProvider.java, platform/security/idp/security-idp-client/src/test/java/org/codice/ddf/security/idp/client/IdpLogoutActionProviderTest.java
Fixes logout. An error used to show up ~ 50% of the time that would prevent the user from being logged out.
@blen-desta 
@brjeter 
@stustison 
1. Build, start, and install DDF.
1. Log into the system.
1. Log out of the system. An error should *not* be shown and the user should get logged out.
1. Repeat steps 2 & 3 until you are confident the error is no longer present.
For GH Issues:
Fixes: #4462 
- …
=> [2.13.x]DDF-04462 Fix logout

distribution/ddf-common/src/main/resources/bin/ddf, distribution/ddf-common/src/main/resources/bin/ddf.bat, distribution/docs/src/main/resources/content/_installing/hardware-reqs.adoc, distribution/docs/src/main/resources/content/_installing/java-reqs.adoc, distribution/docs/src/main/resources/content/_quickstart/quickstart-installing.adoc
changes documentation to denote that JDK is not a required installation step and instead JRE can be used if it is not a development system
@tyler30clemens @ahoffer 
@codice/docs  
@brjeter
Build and check out docs locally for correctness
Unset JAVA_HOME
Start up DDF
DDF should not start and should output message saying to set JAVA_HOME to start
(Set JRE_HOME and DDF should start up)
For GH Issues:
Fixes: #4430  …
=> [2.13.x]DDF-4430 Changing docs to show JDK is not required for installation

ui/packages/catalog-ui-search/src/main/webapp/component/filter/filter.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-serialization.js, ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-serialization.spec.js, ui/packages/catalog-ui-search/src/main/webapp/component/query-advanced/query-advanced.view.js
1) Fixes incorrect deserialization of point-radius from geojson filtertree when rendering circles on map. 
2) Fixes issue where we would excessively render AND boolean clauses on queries in the advanced query editor. 
@codice/ui 
@bdeining 
@djblue 
Create a point radius from advanced query window, ensure that it renders correctly when re-editing. 
For GH Issues:
Fixes: #4456 …
=> DDF-04456 Fixing point/rad and excess boolean ANDS

.gitattributes, distribution/ddf-common/src/main/resources/etc/certs/CertNew.cmd
Changes line endings for `.cmd` files
@aperullo @ahoffer 
@codice/build @codice/solr 
@rzwiefel @vinamartin
Test running the `.cmd` files on windows, verify they don't fail and don't require changing line endings
We had a setting that enforced CRLF for `.bat` files only, we need to also enforce CRLF for `.cmd` files and fix any that had LF instead of CRLF.
[DDF-4432](https://codice.atlassian.net/browse/DDF-4432)
- ❓ …
=> [2.13.x] DDF-4432 Enforce CRLF for .cmd files

catalog/ui/catalog-ui-search/pom.xml, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/config/ConfigurationApplication.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/security/FacetAttributeAccessPlugin.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/security/FacetWhitelistConfiguration.java, catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.facetwhitelist.xml, catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/config/ConfigurationApplicationTest.java, catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/forms/SearchFormsLoaderTest.java, catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/forms/commands/SearchFormsManageCommandTest.java, catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/security/FacetAttributePluginTest.java, ui/packages/catalog-ui-search/src/main/webapp/component/filter-builder/filter-builder.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/filter/filter.collection.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/filter/filter.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/multivalue/multivalue.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/query-advanced/query-advanced.view.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/utils/query/index.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/utils/query/query.tsx
Adds Faceting driven dropdown to the advanced query form. An `AccessPlugin` uses an admin configurable list of attributes to determine which attributes are able to be faceted against. If you try to issue a faceted query on an attribute not included in that list, a `StopProcessingException` will be thrown. By default, this list is empty so systems must opt in to faceting driven autocomplete.
As of right now, only string, float, and integer attributes will support this dropdown. Future work will include investigation into how best to handle dates and locations.
Also fixes some unit tests that were broken on Windows due to platform dependent operations. These changes are in `SearchFormsLoaderTest` and `SearchFormsManageCommandTest`.
@gjvera 
@bdeining 
@djblue 
1. Ingest a …
=> DDF-04408 Adds faceting driven auto-complete to ui

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/ws/JsonRpc.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/ws/SecureWebSocketServlet.java, ui/packages/catalog-ui-search/src/main/webapp/js/model/QueryResponse.js
My recent websockets bug fix broke some error cases, such as having an unavailable source: https://github.com/codice/ddf/pull/4368
This reverts that change temporarily to unblock others, and I will put in a permanent fix later.
@andrewkfiedler @tbatie @tyler30clemens @austinsteffes 
- Build DDF (include ui in the build)
- Install DDF
- Create two Opensearch sources, 1 with a madeup hostname and 1 with the default loopback value.
- Go to Intrigue and ingest a couple of records
- Try and execute the default wildcard search
- It should return records but show a red triangle indicating one of the sources is unavailable
For GH Issues:
Fixes: #4318 …
=> DDF-04318 Temporarily undo recent websockets change which breaks search when there is an unavailable source

ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-old.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-serialization.js, ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-serialization.spec.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/location/location.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/text-field/text-field.js
- Fixed backward compat. with CQL distance/units
- Fix clientside filtering
- Fixed keyword component not properly rendering the multipoly/poly components
- Fixed not properly representing geojson spec in location-serialization
- Fixed text-field 0 value to look for undefined values more explicitly
@bdeining 
@middlets719 
@djblue 
@codice/ui 
@djblue 
@bdeining 
This PR should be tested in 2 parts:
1) Need to perform queries including all serialization types. BBox, Polygon, Line, etc. 
2) Save the queries individually or combined. 
3) Refresh the page
4) Ensure that the original structure of the query was fully preserved (bbox re-renders as bbox and keyword rerenders as keyword)
**Important Note**
> Within the preservation of a keyword, beneath the …
=> DDF-04474 Fixing Location Serialization Failures With Query Preservation & Clientside Filtering

distribution/ddf-common/src/main/resources/bin/ddf, distribution/ddf-common/src/main/resources/bin/ddf.bat, distribution/docs/src/main/resources/content/_installing/java-reqs.adoc, distribution/docs/src/main/resources/content/_managing/_installing/hardware-reqs.adoc, distribution/docs/src/main/resources/content/_quickstart/quickstart-installing.adoc
Link to 2.13.x PR: #4443
Changes documentation to denote that JDK is not a required installation step and instead JRE can be used if it is not a development system.
@ethantmanns
@vinamartin
Build and check out docs locally for correctness
Unset JAVA_HOME
Start up DDF
DDF should not start and should output message saying to set JAVA_HOME to start
(Set JRE_HOME and DDF should start up)
For GH Issues:
Fixes: #4430  …
=> DDF-4430 Changing docs to show JDK is not required for installation 

catalog/opensearch/catalog-opensearch-source/src/main/java/org/codice/ddf/opensearch/source/OpenSearchSource.java, catalog/opensearch/catalog-opensearch-source/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/opensearch/catalog-opensearch-source/src/main/resources/OSGI-INF/metatype/metatype.xml, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestSecurity.java
Fixes #4284 
The OpenSearchSource doesn't have a configurable poll interval. We have a server admin that would like us to stop polling him every minute. Other sources allow you to change the poll interval, but not this one. This change adds Poll interval configuration for OpensearchSource.
@leo-sakh 
@glenhein 
@bdeining
@troymohl
@lamhuy 
Add a loopback source
Turn up cxf logging to watch poll
etc.
=> DDF-04284 Poll interval configuration for OpensearchSource

ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/map.view.js
Fixes a bug where announcements were being deferred to the next saving of user preferences when saving the same location twice.
@gjvera 
@rymach 
@bdeining 
@djblue 
1. Pan to some location
2. Click `Set Home` Twice from the Home dropdown
- One announcement should show up for each time you click `Set Home`
4. Click on the cog in the top right and go to `Theme Settings`
5. Click and drag the zoom bar to set a new zoom level.
- Verify no announcements regarding map home location come up
When you click `Set Home` a listener is created for the response on a network request for updating user preferences regardless of whether the location has changed. If the location hasn't changed, then the network request never goes out and the listener gets deferred to the next time the …
=> DDF-04479 Fix Set Map Home Deferred Announcements

distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/AbstractIntegrationTest.java
- Increase allowed timeout for feature startup during itests.
@tyler30clemens @AzGoalie @austinsteffes 
@codice/test 
@brjeter
@ethantmanns
CI build.
Some downstream features can take longer to start.
Fixes: #4321  …
=> DDF-04321 Allow more time for itest feature startup

catalog/spatial/wfs/1.0.0/spatial-wfs-v1_0_0-source/pom.xml, catalog/spatial/wfs/1.0.0/spatial-wfs-v1_0_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v1_0_0/catalog/source/WfsSource.java, catalog/spatial/wfs/1.0.0/spatial-wfs-v1_0_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v1_0_0/catalog/source/WfsSourceTest.java, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/pom.xml, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsSource.java, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsSourceTest.java, catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/pom.xml, catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/source/WfsSource.java, catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/source/WfsSourceTest.java
Fixes the WFS 1.0.0, 1.1.0, and 2.0.0 sources so their configured connect and receive timeouts will actually be used for connections to the external WFS server.
@leo-sakh 
@codice/io 
@bdeining
@troymohl
Repeat the following steps for a WFS 1.0.0, 1.1.0, and 2.0.0 source:
**Note:** run `log:set debug org.codice.ddf.spatial.ogc.wfs.v110.catalog.source` before testing the 1.1.0 source.
1. Create a new WFS source.
2. Set the WFS URL to point to a valid WFS server.
a. http://giswebservices.massgis.state.ma.us/geoserver/wfs is a public WFS server that will work for testing this.
b. **Important:** If you use this server, you must set `Forced Feature Type` to GISDATA.MINLL1_ARC
3. Click `Save`.
4. Enable the source via the `Active Binding` dropdown.
5. Verify the source shows up …
=> [2.13.x] DDF-04486 Enforce the WFS sources' configured connect and receive timeouts

platform/admin/core/admin-core-impl/src/main/java/org/codice/ddf/admin/core/impl/SystemPropertiesAdmin.java, platform/admin/core/admin-core-impl/src/test/java/org/codice/ddf/admin/core/impl/SystemPropertiesAdminTest.java, platform/admin/core/admin-core-impl/src/test/resources/custom.system.properties
Expands the external host and port properties so that they align with what is displayed in the UI. This makes it so when a user updates the internal host/port in the installer the external ones are not touched.
Backport of https://github.com/codice/ddf/pull/4429
@Kjames5269 @jhunzik 
@clockard
@emmberk
Run through the installer and try
- Setting just the internal hostname and ports, verify that custom.system.properties reflects what was set in the UI
- Setting just the external hostname and ports, verify that custom.system.properties reflects what was set in the UI
- Setting both external and internal hostname and ports, verify that custom.system.properties reflects what was set in the UI
- Verify ?dev=true still works as expected when setting internal/external ports (functionality should …
=> DDF-04426 [2.13.x] Expands external host/port properties

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/QueryOperations.java, catalog/spatial/registry/registry-api-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestRegistry.java
This PR updates the CSW Registry Store to not be registered as a FederatedSource service. This PR is required by https://github.com/codice/ddf/pull/3858. Because RegistryStoreImpl was unnecessarily being registered as 2 different types of Sources, the SourcePoller was recognizing 2 different sources with the same key. See https://github.com/codice/ddf/pull/3858#discussion_r229886462.
@jhunzik @peterhuffer 
@codice/io
@clockard
@vinamartin
Confirm that the Csw Registry Store still works
- view connection status
- push/pull
You should no longer see the registry as a source in the Admin Console or Intrigue. Confirm that no documentation updates were missed.
[DDF-1366](https://codice.atlassian.net/browse/DDF-1366) …
=> [2.13.x] DDF-1366 Updated the CSW Registry Store to not be registered as a FederatedSource service

ui/packages/catalog-ui-search/src/main/webapp/component/filter/filter.view.js
When updating the filter, the type of the previously selected attribute is compared to the type of the currently selected attribute. If they're not the same type, the value is cleared to avoid unexpected/undesired values. 
@andrewzimmer @Bdthomson 
@bdeining 
@djblue 
@millerw8 
- Switch to `anyGeo` and draw a shape
- Switch to `anyText` and verify that the value is empty
- Fill in a value and switch to a Boolean attribute
- Verify that the value is empty
- Switch to any other String attribute and enter a number
- Switch to a Date attribute and verify that the value is empty
- Choose a date and switch to another Date attribute
- Verify that the same date remains
- Switch between other attributes of the same type and make sure that the values remain (with the exception of …
=> DDF-04518 Cleared query attribute value when switching between attributes of different types

ui/packages/catalog-ui-search/src/main/webapp/js/model/QueryResponse.js
This is equivalent to the second commit from #4540. The first commit from #4540 is not necessary since the original change that caused this bug was never reverted on `2.13.x`
@tbatie
- Build DDF (include ui in the build)
- Install DDF
Verify the first commit's functionality works:
- Ingest some records and run some queries to make sure Intrigue is working normally.
- With one of the executed queries still up, open a new tab for the AdminUI and logout.
- Go back to Intrigue and edit the open query and/or execute it.
- The query should now return no results with an error icon next to the query.
Verify the second commit's bug fix:
- Create two Opensearch sources, 1 with a madeup hostname and 1 with the default loopback value.
- Try and execute …
=> [2.13.x]DDF-04318 Fix the error handling in Intrigue WebSockets

ui/packages/catalog-ui-search/src/main/webapp/component/query-title/query-title.less
Fixes styling in Comfortable view.
@andrewzimmer 
@willwill96 
@codice/ui 
@djblue 
Choose "Comfortable" spacing in Settings > Theme and verify that you can see the "Search Name" placeholder text when opening a new basic/text search.
For GH Issues:
Fixes: #4550
Before
After …
=> DDF-4550 Fixing styling for basic/text search

ui/packages/catalog-ui-search/src/main/webapp/component/query-interactions/query-interactions.view.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/container/results-export/results-export.tsx
Adds the ability for a user to export multiple results in a zip file.
@bdeining @andrewkfiedler @bellcc @cantstoptheunk 
@codice/ui 
@bdeining 
Perform a query.
Select one or more results.
Clicks Export Selected (zip).
Selects transformer to apply on result(s).
Hits download button.
Verify zipped file with contents of the export is downloaded to your machine.
Unzip the export and verify contents.
Fixes: #4553 …
=> DDF-04553 added functionality for multi-zipped exports

distribution/ddf-common/src/main/resources/bin/ddf, distribution/ddf-common/src/main/resources/bin/ddfsolr
The Solr start script generates a stop key every time Solr is started
@garrettfreibott  @mcalcote @brjeter @tyler30clemens @austinsteffes 
@codice/solr 
@clockard 
@brjeter 
For GH Issues:
Fixes: #4487 
####Testing
* Should be tested on both **Mac and Linux**
* Test `ddfsolr start`,  `ddfsolr restart`,  and `ddfsolr stop`
* Test that `ddfsolr stop` removes the file named STOPKEY
* Test that the Solr process is eventually killed even if the STOPKEY file is missing (usually 180 seconds) 
- [No] Documentation Updated
- [No] Update / Add Threat Dragon models
- [No] Update / Add Unit Tests
- [No] Update / Add Integration Tests …
=> [2.13.x] DDF-04487 Solr stop key for *nix

ui/packages/catalog-ui-search/src/main/webapp/js/model/Query.js
The `$.when` API does not support passing in an array of Promise-like objects. This was causing the `then()` callback to be executed immediately, cancelling the first local list query, and always sending out the federated queries. This PR spreads the array of Promises to conform with the `when` API
@willwill96 @gjvera @rymach @Lambeaux 
@bdeining
@djblue
1. Ingest some data
2. Create a new list and add the local data to it
3. Open the network tab
4. Run a search based on the list and verify only one cql request is sent out to the local catalog
5. Add a federated source with some data
6. Add a federated result to the list
7. Run a search based on the list and verify a cql request is sent out to the local catalog and another is sent out to the federated source
For Jira: …
=> DDF-04566 The local query issued as part of a list search always fails

distribution/ddf-common/src/main/resources/etc/shell.init.script
Adds retry logic to wfr command
@Kjames5269 
@paouelle
@rzwiefel
@tbatie
Start up DDF and run `wfr` right away to ensure that `wfr` works before the `system:wait-for-ready` bundle comes up.
For GH Issues:
Fixes: #4590
=> DDF-4590 Add retry logic to wfr command

ui/packages/catalog-ui-search/src/main/webapp/react-component/container/input-wrappers/number/number.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/container/table-export/table-export.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/table-export/table-export.tsx
@bdeining 
@adimka 
@middlets719 
@zta6 
@djblue 
- Adds message on admin export limit when `Exporting All`
- Adds placeholder update for numerical field `Enter number of results you would like to export`
- Refactor baseline input to allow for placeholder from props
1. Ingest data into DDF
2. Open table view
3. Select the `Export` button
4. When choosing `All` from the dropdown, it should display a message if it exceeds the admin configurable limit (see note below to modify the limit)
```
To modify the admin configurable limit to a lower number to make it easier to test this, open up the catalog-ui-search settings from the admin page. Set this number to something small like 5, then retest
```
1. When following the above steps for exporting, swap the …
=> DDF-04524 Enabling Warning Message on Export Results (All) 

ui/packages/catalog-ui-search/src/main/webapp/component/between-time/between-time.view.js
Fixes the BETWEEN Time Filter in Query Forms
When you don't select a date, the value of the filter is undefined. If you try to switch to another filter, an error is thrown and the query form becomes broken
@gjvera 
@rymach 
@Lambeaux 
@djblue 
@bdeining 
1. Ingest some data with date information 
2. Create a query on a date attribute (i.e `created`)
3. Choose the BETWEEN comparator
4. Without selecting any dates, switch to another comparator 
- Verify the comparator switches to the new comparator
5. Repeat steps 2 and 3
6. After selecting dates, switch to another comparator
- Verify the comparator switches to the new comparator
7. Test the BETWEEN filter for regressions by running a search and verifying the correct results come back 
For Jira: …
=> DDF-4581 Fix Between Time Filter

catalog/core/catalog-core-camelcomponent/src/main/java/ddf/camel/component/catalog/framework/FrameworkProducer.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/AsyncFileEntry.java, catalog/core/catalog-core-directorymonitor/src/test/java/org/codice/ddf/catalog/content/monitor/AsyncFileAlterationObserverTest.java
Addresses @lessarderic 's comments from #4617 
Due to the severity of the bug, these comments were not able to be addressed in that PR. These changes are not 100% necessary but are very useful to have. 
@lessarderic 
@peterhuffer @kcover @clockard @jhunzik @brjeter 
@codice/io 
CI.
@lessarderic In reference to camel route unit testing: https://github.com/codice/ddf/pull/4617#discussion_r271114633
> Since we're actually expecting a different exception than the one thrown (`IngestException`) in these tests, would it be worth using JUnit's https://junit.org/junit4/javadoc/latest/org/junit/rules/ExpectedException.html and validate that the cause is what we expect?
I tried implementing thrown.expect but was running into strange errors because the exception includes a bunch of other exceptions. …
=> [2.13.x] DDF-4424 Increasing sustainability of the CDM codebase

catalog/catalog-app/src/main/resources/features.xml, catalog/core/catalog-core-directorymonitor/pom.xml, catalog/core/catalog-core-directorymonitor/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/core/catalog-core-directorymonitor/src/test/java/org/codice/ddf/catalog/content/monitor/ContentDirectoryMonitorIT.java, catalog/transformer/catalog-transformer-bootflag/pom.xml, catalog/transformer/catalog-transformer-bootflag/src/main/java/org/codice/ddf/catalog/transformer/bootflag/InputTransformerBootServiceFlag.java, catalog/transformer/catalog-transformer-bootflag/src/test/java/org/codice/ddf/catalog/transformer/bootflag/InputTransformerBootServiceFlagTest.java, distribution/ddf-common/src/main/resources/etc/transformers/README.md, distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/AbstractIntegrationTest.java, distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/ServiceManagerImpl.java
Set generic timeout back to 2 min and increase features and bundles timeout for better features and bundles startup for itests.
@peterhuffer
@bakejeyner
@codice/test 
@AzGoalie
@brjeter
@clockard
- **Run downstream itests and verify they pass**
- **Test the CDM**:
Set log:set TRACE org.codice.ddf.catalog.transformer.bootflag for detailed logs.
Verify the following scenarios.
Start a normal CDM (move/delete/inplace) and verify it begins ingesting
Start a normal CDM (move/delete/inplace). Restart the distribution and verify it does not start until all InputTransformers are available (view logs).
Before a fresh install, edit the ddf-default-input-transformers.json file to include an InputTransformer ID that doesn't exist. Verify install fails.
Some downstream features and …
=> DDF-04321 Fix downstream CDM itest performance/timeout issues

ui/packages/catalog-ui-search/src/main/webapp/component/content/alert/content.alert.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/content/content.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/content/upload/content.upload.view.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/container/multi-select-actions/multi-select-actions.tsx
Each view that instantiates the content view now overrides a `selectionInterface` variable with their specific selection interfaces
@Bdthomson @andrewzimmer @nsuvarna 
@djblue
- Upload some items
- View the upload
- Select some items 
- Verify that the export is button is enabled and exports the selected results when clicked
Fixes: #4638 …
=> DDF-4638 fixed bulk actions not getting enabled in upload view

ui/packages/catalog-ui-search/src/main/webapp/component/visualization/low-bandwidth-map/low-bandwidth-map.hbs
This commit removes the word 'Anyway' from the text 'Continue to Map Anyway' that appears in the top button of the component that loads in place of a map when in UI Lite.
@samuelechu 
@brianfelix 
@codice/ui 
@djblue
1. Build and start DDF (if necessary, see the readme for more specific directions)
2. Run `profile:install standard` from the resulting Karaf console (at least on my shell, the text of runnable commands is colored blue, nonrunnable red. `profile:install` tends to take a minute to load as runnable).
2. Open DDF in your browser (https://localhost:8993/search/catalog/) and click the button labeled 'Sign in as Guest', which should redirect you a page whose base URL is in fact https://localhost:8993/search/catalog/.
3.  Open a map. If you do not see a tab …
=> DDF-4683 Remove 'Anyway' from warning module in UI Lite

ui/packages/catalog-ui-search/src/main/webapp/component/search-form-list/search-form-list.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/search-interactions/search-interactions.hbs, ui/packages/catalog-ui-search/src/main/webapp/component/search-interactions/search-interactions.less
Depends on https://github.com/codice/ddf/pull/4653 for search form selection to work
- Highlights elements on hover
- Keeps the filter box on top of the list so it is always reachable
- Adds a "Nothing Found" message if the filter doesn't match anything (like the attribute dropdown for queries)
- Adds divider lines between the search interactions
@codice/ui @willwill96 @gjvera @Lambeaux @rymach 
@bdeining
@djblue
- Verify the dividers in the text/basic/advanced dropdown look good
- Click "Use Another Search Form" and verify the "no search forms" message is shown when the user has no search forms
- Create a few forms (~3)
- Verify the forms appear in the list, are functional, and there is no scrollbar
- Verify filtering works
- Create even more forms until the list overflows (need about …
=> DDF-04657 Improve search form selection UX

distribution/ddf-common/src/main/resources/security/default.policy, distribution/docs/src/main/resources/content/_running/ddf-service.adoc
The 3D globe would not load for some downstream products. There was a security manager exception that was blocking `org.codice.thirdparty.commons-httpclient`. This PR fixes this issue, as well as fixes a small typo. 
@ahoffer 
@codice/docs 
@stustison 
@brjeter
CI build 
For GH Issues:
Work for: #4661  …
=> [2.13.x] DDF-4661 Add security permission for 3D globe to load correctly

catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/SolrMetacardClientImpl.java
when setting the solr sort parameter, incorrect UPPER case value from Enum are set for the query. Resulting in the default alphanumeric facet name sort instead of facet count sort
@bdeining 
@millerw8 
@Bdthomson 
Since DDF does not have any facet endpoint. This issue is not reproducible just in DDF
Using a `<Redacted>`OpenSearchEndpoint to reproduce
- Run and Install development profile
- Ingest some records
- Whitelist the facet field of interest
- Query query?q=*&facetFieldNames=<facetFieldOfInterest>&facetSort=recordCount&facetLimit=100
- Verify all facet value coming back and it is sorted by recordCount, not by facetName alphanumeric before this fix
- Query query?q=*&facetFieldNames=<facetFieldOfInterest>&facetSort=recordCount&facetLimit=1
- Verify the single facet name is the …
=> DDF-4688 setting the correct facet sort value

distribution/ddf-common/src/main/resources/security/default.policy, distribution/docs/src/main/resources/content/_managing/_running/ddf-service.adoc
Link to 2.13.x PR: #4662 
The 3D globe would not load for some downstream products. There was a security manager exception that was blocking `org.codice.thirdparty.commons-httpclient`. This PR fixes this issue, as well as fixes a small typo.
@ahoffer 
@codice/docs 
@brjeter
@stustison
CI build 
For GH Issues:
Fixes: #4661  …
=> DDF-4661 Add security permission for 3D globe to load correctly

catalog/core/catalog-core-standardframework/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/rest/catalog-rest-impl/src/main/java/org/codice/ddf/rest/impl/CatalogServiceImpl.java, ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/source-item/source-item.tsx
Within the SourceItem.tsx, we support plugging in the option to add links in the sources page to open up modals (ideally for authentication mechanisms). Unfortunately, due to various cross origin restrictions and oddities with iframes and associated security, a lot of these external domains are getting blocked in the iframe.
It would be nice if we make a slight modification to allow things other than strictly iframes, such as a new window. This replicates a similar flow to a lot of big names (github, facebook, google, etc) that physically launch a new window, not an iframe.
@bdeining 
@djblue 
@Bdthomson 
@middlets719 
@adimka 
@zta6 
View sources page and ensure functionality has not regressed. 
For GH Issues:
Fixes: #4676
=> DDF-4676 Adding ID to sources endpoint for actions and updated source action provider

distribution/ddf-common/src/main/resources-filtered/etc/application-definitions/security-services.json
This PR adds back the ldap configurations to the Security application
@austinsteffes
@ahoffer
@jhunzik
@codice/ui 
@brjeter
@clockard
1. Standard install of DDF
2. Go to System features to install all the ldap features 
3. Close tab and open tab again to allow to refresh 
4. See the ldap configurations present under System -> Configurations 
5. See the ldap configurations present under Security -> Configurations 
For GH Issues:
Work for: #4704 …
=> [2.13.x] DDF-4704 Added ldap configurations to Security App

ui/packages/catalog-ui-search/src/main/webapp/react-component/container/metacard-interactions/location-interaction.tsx
Fixes an issue where searches created from location don't persist the filters to search forms.
The query was setting the cql correctly, but wasn't setting the filterTree which is how search forms deconstruct the query.
@gjvera 
@rymach 
@Lambeaux 
@bdeining
@djblue
1. Ingest at least one document with a single location
2. Ingest at least one document with multiple locations
3. For each of those documents:
a. Create a search from location (a metacard interaction in the ellipsis menu of a result metacard)
b. Edit the search and verify that the geo data is present in the search form
c. Save the workspace and reload
d. Verify that the geo data is still present
For GH Issues:
Fixes: #4625  …
=> DDF-4625 Search From Location to Persist Filters

distribution/ddf-common/src/main/resources/etc/shell.init.script
Adds retry logic to wfr command
@Bdthomson 
@Kjames5269 
@rzwiefel
@tbatie
Start up DDF and run `wfr` right away to ensure that `wfr` works before the `system:wait-for-ready` bundle comes up.
For GH Issues:
Fixes: #4590
=> [2.13.x] DDF-4590 Add retry logic

ui/packages/catalog-ui-search/src/main/webapp/react-component/container/metacard-interactions/export-interaction.tsx
Fixes an issue with the inspector view where multiple results could not be exported.
@adimka 
@samuelechu  
@djblue
@jrnorth 
1.) Install ddf
2.) Ingest data
3.) From Intrigue, run a query that returns multiple results.
4.) Select multiple results from the results pane using either the checkboxes or shift clicking.
5.) Open the inspector view.
6.) From the inspector view, click the ellipses menu and select "Export As".
7.) Choose any format and click export
8.) Open the file created from step 7 and verify that all selected results were exported.
Fixes: #4692  …
=> DDF-04692 Inspector view now exports multiple results

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/QueryMetacardApplication.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/query/data/metacard/QueryMetacardTypeImpl.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/query/data/model/QueryBasic.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/query/util/QueryAttributes.java, catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/metacard/QueryMetacardApplicationTest.java, distribution/docs/src/main/resources/content/_integrating/_endpoints/query-endpoints.adoc
- Adds the ability to perform a fuzzy search against `title`, `owner`, `sources`, and `description`. 
@glenhein 
@ethantmanns
- Ingest a couple of query metacards with similar and different titles
- Perform a fuzzy search against the query metacards and determine if the results are close to your `text` parameter. 
- None
For GH Issues:
Fixes: #4736 
- None
- ❓ (Question …
=> DDF-4736 Perform a fuzzy search against a few query metacard attributes

catalog/spatial/registry/registry-api/src/main/java/org/codice/ddf/registry/api/internal/RegistryStore.java, distribution/docs/src/main/resources/content/_developing/_devComponents/json-definition-files.adoc, distribution/docs/src/main/resources/content/_managing/_configuring/_sources/registry-store.adoc
Link to 2.13.x PR: #4723 
Removes the "experimental" tag from components that are not experimental.
@codice/docs 
@brjeter
@clockard
@lessarderic
@mcalcote
@shaundmorris
verify content
For GH Issues:
Fixes: #4722  …
=> [2.14.X] DDF-4722 removed 'experimental' tag from docs

ui/packages/catalog-ui-search/src/main/webapp/component/result-selector/result-selector.less, ui/packages/catalog-ui-search/src/main/webapp/component/selection-checkbox/selection-checkbox.view.js
fix Select All checkbox incorrectly checked when switching between Search and List tabs
fixes Select All checkbox spacing
@Bdthomson @hayleynorton @nsuvarna 
@codice/ui 
@bdeining
@djblue
- build / run / ingest data
- Create a list and add a result
- in Search tab select a different result via the checkbox
- switch to List tab, verify the "Select All" checkbox is not checked
- select various results and switch back and forth between tabs, verify the the "Select All" checkbox is only checked if the all current results and selected
For GH Issues:
Fixes: #4738  …
=> DDF-4738 fix Select All checkbox incorrectly checked when switching between Search and List tabs

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/MetacardApplication.java, ui/packages/catalog-ui-search/src/main/webapp/react-component/container/sharing/sharing.tsx
Removes subscription if a user's sharing permissions are removed
@willwill96 
@rymach 
@Lambeaux 
@bdeining 
@troymohl 
As user A create a workspace X and share it with user B,
log in as user B and subscribe to workspace X
log back in as user A and remove the sharing permissions of user B
set a breakpoint on line 189 of `SubscriptionsPersistenStoreImpl.java` 
subscribe and unsubscribe from workspace X (to trigger breakpoint)
verify results[0]["email_txt"] does not contain the email of user B 
Currently there is no way to grab user attributes server side. So, there is not a way to unsubscribe by group. This temporary solution only supports unsubscribing by specific emails, and will not unsubscribe if the guest group has read or higher permissions. There will likely be a …
=> DDF-04614 Fixing subscription removal

catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsSource.java, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsSourceTest.java
Fixes `WfsSource` paging stop index calculation.
@hayleynorton 
@glenhein 
@bdeining 
@jrnorth 
1. Query the WFS Source and attempt to page past the first page.
For GH Issues:
Fixes: #4769  …
=> DDF-4769 Fix WFS 1.1.0 Source Page Calculation

catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/pom.xml, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsFilterDelegate.java, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsFilterDelegateTest.java
Implements `after`, `before`, `during`, and `relative` in the WFS 1.1.0 filter delegate.
@leo-sakh 
@samuelechu 
@brianfelix 
@codice/io 
@codice/ogc 
@bdeining
@troymohl
1. Create a WFS 1.1.0 source with the URL http://services.azgs.az.gov/ArcGIS/services/aasggeothermal/CAWellLogs/MapServer/WFSServer
a. Disable the CN check and allow redirects. Leave everything else as-is.
2. In the Karaf console, run `log:set info org.apache.cxf` and `log:set warn org.apache.camel`.
3. Open Intrigue.
4. Run `AFTER`, `BEFORE`, `BETWEEN`, and `RELATIVE` temporal queries on the `ext.WellLog.StatusDate` field against the WFS source you configured. To verify correctness for each:
a. Check DDF's logs for an `Outbound Message` to …
=> DDF-4644 Add support for temporal queries to WFS 1.1.0 source

catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsFilterDelegate.java, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsFilterDelegateTest.java
The envelope now specifies the bounding box's corners using the lowerCorner and upperCorner properties instead of the coordinates property which was deprecated with GML version 3.1.0.
@leo-sakh 
@brianfelix 
@samuelechu 
@codice/io 
@codice/ogc 
@bdeining
@troymohl
1. Create a WFS 1.1.0 source with the URL http://services.azgs.az.gov/ArcGIS/services/OneGeology/AZGS_Arizona_Geology_WFS/MapServer/WFSServer
a. Disable the CN check and allow redirects. Set the `Forced Spatial Filter Type` to `BBOX`. Leave everything else as-is.
2. In the Karaf console, run `log:set info org.apache.cxf` and `log:set warn org.apache.camel`.
3. Open Intrigue.
4. Run an `anyGeo` bounding box query against the source you just configured.
a. Note that you will not receive any results …
=> DDF-4648 Update WFS 1.1 bounding box to be GML 3.1.1 compliant

ui/packages/catalog-ui-search/src/main/webapp/extension-points/extension-points.tsx, ui/packages/catalog-ui-search/src/main/webapp/extension-points/providers/index.tsx, ui/packages/catalog-ui-search/src/main/webapp/extension-points/providers/providers.container.tsx, ui/packages/catalog-ui-search/src/main/webapp/js/Entry.tsx, ui/packages/catalog-ui-search/src/main/webapp/js/extensions/marionette.ItemView.attachElContent.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/container/router-container/router-container.tsx
- Provides an extension point in DDF for specify redux providers at the top level of the dom tree. 
@codice/ui 
@tbatie
- Verify that DDF works as expected in terms of internationalization. This is unfortunately the only way to test this inside of DDF. 
- Verify downstream that internationalization works as expected. 
- None
For GH Issues:
Fixes: #4779 
- None
- ❓ …
=> DDF-4779 Extension point for redux providers

distribution/docs/src/main/resources/content/_quickstart/quickstart-installing.adoc
corrects the quick start instructions for remote headless server installation. 
@codice/docs 
@clockard
@emmberk
@lessarderic
@shaundmorris
For GH Issues:
Fixes: #4782  …
=> [2.13.x] DDF-4782 updated quick start installation instructions

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/security/accesscontrol/AccessControlPreQueryPlugin.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/security/accesscontrol/TagAggregationVisitor.java, catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/security/accesscontrol/TagAggregationVisitorTest.java
Fixes a bug where `NEAR` filters would cause the access control pre-query plugin to throw an exception. 
Also introduces some logging improvements in the pre-query plugin itself.
@Bdthomson 
@codice/ogc 
@bdeining 
@jrnorth
Use the CSW endpoint to conduct a search, ensuring the filter contains the `NEAR` / proximity function, and verify no exception is thrown and the search succeeds as expected. Unzip and install DDF using `profile:install standard`. 
Using Postman or a similar tool, `POST` the following to `https://localhost:8993/services/csw` and verify the following response. It need not return results as long as it does not throw an exception. 
```
<?xml version="1.0" ?>
<GetRecords xmlns="http://www.opengis.net/cat/csw/2.0.2"
xmlns:ogc="http://www.opengis.net/ogc" …
```
=> DDF-4249 Do not simplify filters prior to introspection because not all custom filter functions support evaluation

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/security/accesscontrol/AccessControlTags.java, catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.security.xml, catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/security/accesscontrol/AccessControlTagsTest.java
Adds support for providing a set of values on the `access-controlled-tag` so that the relationship between metacard types and access controlled tags do not need to be 1-to-1, for example: 
```
<service ref="attributeGroupMetacardType" interface="ddf.catalog.data.MetacardType">
<service-properties>
<entry key="name" value="attribute-group"/>
<entry key="access-controlled-tag">
<set>
<value>tag1</value>
<value>tag2</value>
</set>
</entry>
</service-properties>
</service>
```
Also re-words a configuration's description for more clarity. 
@Schachte 
@bdeining 
@jrnorth 
Complete the following:
1. Unzip and startup DDF
1. Run `log:set TRACE org.codice.ddf.catalog.ui.security.accesscontrol`
1. Run `profile:install standard`
1. Shutdown DDF by running `halt` …
=> DDF-4249 Add support for multiple access controlled tags per metacard type

catalog/catalog-app/pom.xml, catalog/core/catalog-core-directorymonitor/pom.xml, catalog/migrate/workspace-query-separation/pom.xml
- remove duplicate dependencies
- add version
warnings:
```
$ mvn clean | grep -i warn
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for ddf.catalog.core:catalog-core-directorymonitor:bundle:2.15.0-SNAPSHOT
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: com.google.code.gson:gson:jar -> duplicate declaration of version ${gson.version} @ ddf.catalog.core:catalog-core-directorymonitor:[unknown-version], /projects/ddf/catalog/core/catalog-core-directorymonitor/pom.xml, line 144, column 21
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for ddf.catalog:catalog-app:pom:2.15.0-SNAPSHOT
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: …
```
=> DDF-04748 Address some pom warnings

catalog/spatial/wfs/spatial-wfs-featuretransformer-handlebars/pom.xml, catalog/spatial/wfs/spatial-wfs-featuretransformer-handlebars/src/main/java/org/codice/ddf/spatial/ogc/wfs/transformer/handlebars/HandlebarsWfsFeatureTransformer.java, catalog/spatial/wfs/spatial-wfs-featuretransformer-handlebars/src/main/resources/OSGI-INF/metatype/metatype.xml, catalog/spatial/wfs/spatial-wfs-featuretransformer-handlebars/src/test/java/org/codice/ddf/spatial/ogc/wfs/transformer/handlebars/HandlebarsWfsFeatureTransformerTest.java, catalog/spatial/wfs/spatial-wfs-featuretransformer-handlebars/src/test/resources/FeatureMember.xml
HandlebarsWfsFeatureTransformer now adds the XML attributes of all the elements in the feature to its internal map. The key is of the form elementName@attributeName to make sure attributes with the same name on different elements do not overwrite each other. In your mapping JSON you can specify "elementName@attributeName" as your feature name and use it in your Handlebars template to get the attribute's value.
@dcruver 
@leo-sakh 
@brianfelix 
@codice/ogc 
@bdeining
@troymohl
1. In the Admin UI, open the Spatial app.
2. Click `WFS Feature to Metacard Templated Mapping`.
a. For `Feature Type`, enter `{http://stategeothermaldata.org/uri-gin/aasg/xmlschema/welllog/0.8}AZWellLogs`
b. Set the `Coordinate Order` to `Lat/Lon`.
c. Add the following to `Attribute Mappings`: …
=> DDF-4659 Make HandlebarsWfsFeatureTransformer handle XML attributes

distribution/docs/src/main/resources/content/_quickstart/quickstart-installing.adoc
Link to 2.13.x PR: #4783 
corrects the quick start instructions for remote headless server installation. 
@codice/docs 
@clockard
@emmberk
@lessarderic
@shaundmorris
For GH Issues:
Fixes: #4782 
- ❗ …
=> DDF-4782 updated quick start installation instructions

distribution/ddf-common/src/main/resources/bin/ddfsolr
Ensure that  the Solr stopkey file is generated in the correct directory for *NIX systems.
@austinsteffes @brendan-hofmann @brjeter @tyler30clemens 
@codice/solr 
@vinamartin 
@brjeter 
Can only be testing on *NIX systems.
1. Build and unzip DDF distro
2. Start DDF from OUTSIDE the bin directory. For example `ddf-distro/bin/ddf`
3. Check that the SOLR_STOPKEY file exists in the bin directory  `ddf-distro/bin` and NOT in the directory where the command was run.
Fixes: #4816 …
=> [2.13.x] DDF-04816 Create stopkey file in script directory

distribution/ddf-common/src/main/resources/security/default.policy
When starting/restarting the system, the org.apache.karaf.deployer.blueprint asks for permission to read all files recursively in the etc directory: `BlueprintDeploymentListener AccessControlException jave.io.FilePermission unable to parse deployed file <DDF_HOME>\etc\....config`. This PR makes it so that permission is granted to read all files in the etc directory. 
@ahoffer 
@brjeter 
@emmberk 
@stustison 
1. Install DDF through UI and restart system and verify no AccessControlExceptions
2. Manually restart the system and verify no AccessControlExceptions
For GH Issues:
Work for: #4826   …
=> [2.13.x] DDF-4826 Broaden scope of karaf deployer blueprint policy

distribution/ddf-common/src/main/resources/bin/ddfsolr
Master port of https://github.com/codice/ddf/pull/4818/files
@brjeter @austinsteffes @tyler30clemens bakejeyner
@vinamartin
Can only be testing on *NIX systems.
1. Build and unzip DDF distro
2. Start DDF from OUTSIDE the bin directory. For example ddf-distro/bin/ddf
3. Check that the SOLR_STOPKEY file exists in the bin directory ddf-distro/bin and NOT in the directory where the command was run.
Fixes: #4816
- ❓ …
=> DDF-04816 Create stopkey file in script directory

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/SparkServlet.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/QueryApplication.java
Selectively gzips request based on accept headers and previous content encoding.
@rzwiefel 
@tbatie 
@bellcc 
@gjvera 
- `mvn clean install` in `catalog/ui/catalog-ui-search`, quick build the rest
- disable web sockets in admin ui
- ensure query work in intrigue
#4837 adds GZIP, but some endpoints were already gzipping their content. This resulted in gzipping the content twice which the browser cannot decode. This PR should disable the second round of gzipping.
For GH Issues:
Fixes: #4836
=> DDF-04836 Prevents double GZIP of Intrigue backend JSON APIs

catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/pom.xml, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/CoordinateStrategy.java, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/LatLonCoordinateStrategy.java, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/LonLatCoordinateStrategy.java, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsFilterDelegate.java, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsSource.java, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/LatLonCoordinateStrategyTest.java, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/LonLatCoordinateStrategyTest.java, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsFilterDelegateTest.java, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsSourceTest.java
Updates the WFS 1.1.0 `FilterDelegate` to use the configured coordinate order of its corresponding source to determine the coordinate order to use when it constructs the query.
@samuelechu 
@leo-sakh 
@glenhein 
@codice/io 
@codice/ogc 
@bdeining
@jlcsmith
1. Run `log:set info org.apache.cxf` and `log:set warn org.apache.camel`.
2. Create a WFS 1.1.0 source with the URL http://services.azgs.az.gov/ArcGIS/services/aasggeothermal/AZWellLogs/MapServer/WFSServer
3. Run various `anyGeo` queries against the source, using `Line`, `Polygon`, `Point-Radius`, and `Bounding Box`.
a. When you run a query there will be a `GetFeature` XML blob printed in the logs that contains the geospatial query. Use this to verify each query's correctness.
b. For each query, run it as both `Lat/Lon` …
=> DDF-4811 Match the coordinate order of each WFS 1.1.0 query to that of its source

catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/SolrMetacardClientImpl.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/cql/CqlQueryResponse.java, ui/packages/catalog-ui-search/src/main/webapp/component/result-item/result-item.collection.tsx, ui/packages/catalog-ui-search/src/main/webapp/component/result-selector/result-selector.view.js, ui/packages/catalog-ui-search/src/main/webapp/js/model/QueryResponse.js
Provide a Did you mean option to re-query with spellcheck turned off. Note that the did you mean option will only present itself on the Results panel if spellcheck is turned on. 
@bellcc 
@tbatie 
@derekwilhelm 
@tbatie
For Jira:
For GH Issues:
Fixes: #____ …
=> DDF-4845 Adding a Did you mean re-query option in Results Panel

distribution/docs/src/main/resources/content/_managing/_configuring/content-directory-monitor.adoc
Master port of https://github.com/codice/ddf/pull/4860
Fixes slashes in CDM policy documentation
@tyler30clemens @ahoffer
@codice/docs
@brjeter
@emmberk
quick build and check docs
No.
Fixes: #4859
=> DDF-4859 fixes slashes in CDM policy documentation

ui/packages/catalog-ui-search/src/main/webapp/js/model/Workspace.js
- We update totalHits when search results are returned, so we need to ignore this model change.  Otherwise, every time results are returned the workspace will appear to need saving.
@Bdthomson 
@djblue 
@bellcc  
Create a search.
Save the workspace.
Run a search (must return results).
Note that the workspace appears to need saving.
I don't think this is the only attribute we need to mark as ignored, but it's a start.  We've also added some spellcheck features that might be causing a similar issue.  I couldn't get the spellcheck things to show up though (I think they're off by default, and I couldn't get the Admin UI working).
For GH Issues:
Fixes: #4873
=> DDF-4873 Add totalHits to ignored attributes

distribution/ddf-common/src/main/resources/bin/ddfsolr.bat
Suppress error message about missing STOPKEY file. The script that calls ddfsolr.bat first calls stop to shutdown any current running Solr instances on the designated port. Because stop is called before start, there will never be a STOPKEY file and in those cases the missing file message is spurious.
@nsuvarna @brjeter @tyler30clemens @austinsteffes 
@codice/solr 
@brjeter
@mcalcote
@rzwiefel
Can only be tested on Window -- Windows specific change.
When starting DDF, the error message "The system cannot find the specified file" should no longer be printed to the terminal.
Fixes: #4584 …
=> DDF-04584 Suppress stopkey file error message on Windows

platform/admin/admin-configuration-configupdater/src/main/java/org/codice/ddf/admin/configuration/ConfigurationUpdater.java, platform/admin/admin-configuration-configupdater/src/test/java/org/codice/ddf/admin/configuration/ConfigurationUpdaterTest.java, platform/admin/core/admin-core-impl/src/main/java/org/codice/ddf/admin/core/impl/AdminConsoleService.java, platform/osgi/platform-osgi-configadmin/src/main/java/org/codice/felix/cm/file/ConfigurationContextImpl.java, platform/osgi/platform-osgi-configadmin/src/test/java/org/codice/felix/cm/file/ConfigurationContextImplTest.java
**Do not squash the commits - they have been logically separated by issue & resolution**
Fixes separate root causes that are combining to form strange symptoms, such as the automatic duplication of source configurations and the leaking of internal properties into etc files. 
@gjvera 
@Bdthomson 
@andrewzimmer 
@paouelle
@brjeter
@bdeining 
@troymohl
1. Verify the reproduction instructions (https://github.com/codice/ddf/issues/4832) no longer yield duplicate configurations. 
1. Also verify that no `service.bundleLocation` properties gets written to etc files after an update via the Admin UI. 
Fixes: #4832  …
=> DDF-4832 Several configuration bug fixes (do not squash)

distribution/ddf-common/src/main/resources/security/default.policy
Increased scope from ddfhome/etc/definitions to ddfhome/etc
Broaden scope of karaf deployer blueprint policy
@stustison @jordanwilking @bellcc @tbatie @glenhein 
- Ensure CI Passes
- Build and install locally and ensure it installs correctly. Insure config files inside of `<DDF_HOME>/etc` are read successfully. Add Config to test if none exist.
Fixes: #4826
- [NA] Documentation Updated
- [NA] Update / Add Threat Dragon models
- Deployer must be able to read all configurations under ETC …
=> DDF-4826 Broaden scope of karaf deployer blueprint policy

ui/packages/catalog-ui-search/src/main/webapp/js/widgets/cesium.base.line.js, ui/packages/catalog-ui-search/src/main/webapp/js/widgets/cesium.polygon.js, ui/packages/catalog-ui-search/src/main/webapp/js/widgets/openlayers.polygon.js
Currently polygons are being buffered as linestrings causing the buffer the extend both inward/outward. This gives the buffer the appearance of being split between the two directions, and this can also result in inner shapes being created within the polygon that appear to be "holes" in the search area
With this fix, the polygon will only buffer outward and another polygon with dotted lines will be added to represent the originally drawn shape (demo video below)
@Bdthomson @hayleynorton @lamhuy 
@codice/ui 
@djblue 
- ingest records with location data
- create several `anyGeo` searches with different polygons and verify that the correct results 
- repeat many times with different shapes/buffers on both 2d/3d maps
For GH Issues:
Fixes: #4828 
demo …
=> DDF-4828 fix Incorrect buffer for Polygons

ui/packages/catalog-ui-search/src/main/webapp/react-component/dropdown/dropdown.js
Fixes a render loop in dropdown.js caused by React's equality check not being sufficient for this model.
@samuelechu @mojogitoverhere 
@codice/ui 
@djblue
@vinamartin
Open a component using react-comppnent/dropdown/dropdown.js
Throw a debug in that component's render method.
Ensure that the debug isn't hit constantly.
Fixes: #4903  …
=> DDF-4903 Fix render loop caused by poller in dropdown.js

catalog/plugin/catalog-plugin-videothumbnail/src/main/java/org/codice/ddf/catalog/content/plugin/video/VideoThumbnailPlugin.java, dependency-check-maven-config.xml
Wraps the call to start an OS process (execute ffmpeg) in a do-privilege
@austinsteffes @tyler30clemens @peterhuffer @brjeter 
@blen-desta
@emmberk
@peterhuffer Can you hero this? You've had the best luck reproducing the problem during replication.
None
Fixes: #4905 
N/A …
=> [2.13.x] DDF-04905 Prevent ffmpeg access control exception

ui/packages/catalog-ui-search/src/main/webapp/component/filter/filter.view.js
Fixes issue where queries on attributes in the suggestion whitelist would fail to update when they were ran. Instead of using the value selected in the dropdown, the outgoing query would use whatever previous value was entered.
@adimka @Lambeaux @brianfelix @kentmorrissey 
@bdeining
@djblue
1. Ingest some images
2. Add `media.type` to the `Catalog UI Search Attribute Suggestion Whitelist`
3. Navigate to Intrigue and open the Network tab of dev tools
4. Create a new advanced search. Notice that the default options are `anyText=''`.
5. Change `anyText` to `media.type` and select one of the dropdown options for `media.type` like `image/png` (depending on what was ingested)
6. Click Search
7. Verify the outgoing cql is `media.type=image/png` instead of `media.type''`
Found while heroing …
=> DDF-4864 Fix queries on attributes in the suggestion whitelist

ui/packages/catalog-ui-search/src/main/webapp/component/select/filterHelper.js, ui/packages/catalog-ui-search/src/main/webapp/component/select/filterHelper.spec.js
Fixes a bug where the dropdown input will not accept the wildcard symbol or display it as an autocomplete option. If an attribute is configured to use faceting, this can be reproduced. 
@gjvera 
@willwill96 
@codice/ui 
@bdeining 
@djblue
Refer to the reproduction instructions from the issue (#4850). 
Faceting is a feature that allows attributes to be configured to support "autocomplete". This is done by querying the catalog for all occurrences of the attribute and generating a list of unique results that the user may pick from. 
Fixes: #4850 
**How it should behave**
**How it actually behaves**
**Behavior with the fix** …
=> DDF-4850 Fix issue where dropdown input will prevent the user from using the wildcard (*) operator

dependency-check-maven-config.xml
UPDATED: Added a suppression for CVE-2019-8457 sql-lite which is a dependency of the geowebcache server. 
Addresses finding for CVE-2018-8029. DDF does use version of JARs affected by this CVE. However, the vulnerability is specific to the user account for a Apache YARN, a Hadoop resource manager. DDF does not make use of YARN.
@brjeter @austinsteffes @tyler30clemens @clockard 
@bdeining
@blen-desta
Either pass a CI build or build locally with the -Powasp profile.
No.
#4914 
None. …
=> DDF-04914 Address Multiple OWASP Issues

platform/platform-paxweb-jettyconfig/src/main/java/org/codice/ddf/security/session/AttributeSharingHashSessionIdManager.java
Audits session timeouts and the invalidation of sessions.
@brjeter @austinsteffes @tyler30clemens 
@blen-desta
@brjeter
Looks for entries in the security.log file. Look for "Invalidating session ID" and "Expiring session ID". For example:
``` 
[INFO] 2019-05-29T18:25:46,048 | eduler-724075079 | securityLogger  |  Subject: UNKNOWN Expiring session ID node0irj3y6x443fy10c26oma0ioju28
```
```
[INFO ] 2019-05-29T11:07:08,030 | qtp81849058-94   | securityLogger  |  Subject: UNKNOWN Request IP: 127.0.0.1, Port: 43176 Invalidating session ID node01k84q68e1lw9g1nwtuo2wn5oht2
```
Fixes: #4892 
None …
=> DDF-04892 Audit session timeouts

ui/packages/catalog-ui-search/package.json, ui/yarn.lock
Bumps usng.js version in catalog-ui-search
@rymach 
@bdeining 
@samuelechu 
- `yarn install`
- `yarn start` in `ui/packages/catalog-ui-search`
- ensure warning is gone from webpack build output
- ensure no regression in location component
Fixes: #4824
=> DDF-04824 Bumps usng.js version in catalog-ui-search

distribution/ddf-common/src/main/resources/bin/setenv, distribution/ddf-common/src/main/resources/bin/setenv.bat
Updates the setenv script to prevent overriding the EXTRA_JAVA_OPTS environment variable if it already contains a value prior to running the script (this only applies on linux machines). The script will just append the existing value of the variable to the new value set within the script. 
@codice/build 
@ryeats
@stustison
@beyelerb 
On a Linux machine, perform the following steps:
1. Prior to running DDF, set the EXTRA_JAVA_OPTS environment variable to some value such as:
"-Dhttps.proxyHost=test"
2. Run the DDF start script to start DDF.
3. Inside of the Karaf console, execute the command: "system:property", and verify the "https.proxyHost=test" entry within the output exists.
Prior to this PR, the setenv script would would wipe away any value already set to the EXTRA_JAVA_OPTS system …
=> DDF-04950 Update setenv script to not override EXTRA_JAVA_OPTS if it already contains a value

catalog/core/catalog-core-solr/pom.xml, catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/SolrMetacardClientImpl.java, catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/SolrMetacardClientImplTest.java, ui/packages/catalog-ui-search/src/main/webapp/component/result-item/result-item.collection.tsx, ui/packages/catalog-ui-search/src/main/webapp/component/result-selector/result-selector.view.js
Fixes a potential NPE in SolrMetacardClientImpl in the case where the set of results returns null after a query is run. 
Also makes a small change to the spellcheck UI code for a downstream project, and added add unit tests
@Bdthomson 
@bellcc 
@vinamartin 
@codice/solr 
@paouelle
@pklinef
Test spellcheck features, did you mean and showing results for and regression testing on normal searches.
Fixes: #____ …
=> DDF-4962 NPE is thrown when the Solr Response results are empty

catalog/transformer/catalog-transformer-preview/src/main/java/org/codice/ddf/transformer/preview/actions/PreviewActionProvider.java, catalog/transformer/catalog-transformer-preview/src/main/resources/OSGI-INF/blueprint/blueprint.xml, ui/packages/catalog-ui-search/src/main/webapp/component/metacard-preview/metacard-preview.view.js, ui/packages/catalog-ui-search/src/main/webapp/js/model/QueryResult.js
- Change action id for Text Preview to be unique to prevent clobbering issues
- Remove broken reference to css file that does not exist anymore when rendering preview tab
@glenhein 
@codice/ui 
@djblue 
@rzwiefel 
1. Upload a text file and a pdf file and go to the preview tab, verifying that the preview tab shows the contents of the files.
2. Upload a text file containing html that has a `<script>` tag that sends an `alert()` inside of it and check that when you load the preview tab that alert isn't sent.
No
For GH Issues:
Fixes: #4946 
- Documentation Updated - N/A
- Update / Add Threat Dragon models - N/A
- Update / Add Unit Tests - N/A
- Update / Add Integration Tests - N/A …
=> DDF-4946 Fix Preview Tab

ui/packages/catalog-ui-search/src/main/webapp/react-component/dropdown/dropdown.js
Fixes a bug with the closing of the React Dropdown component introduced by #4843 
@hayleynorton 
@andrewzimmer 
@samuelechu 
@zta6 
@bdeining
@djblue
1. Open DDF Intrigue
2. Verify that you can open and close components using the react dropdown (for example, the gazetteer dropdown in the top right)
- Note that many of our dropdowns still use the marionette dropdown as opposed to the react one, so you can't just test a random dropown in Intrigue
3. Spot test those components for regressions
[This line](https://github.com/codice/ddf/blob/58b9ab3af4294dd863848e7365211ad47a031703/ui/packages/catalog-ui-search/src/main/webapp/react-component/dropdown/dropdown.js#L144) is the issue.
That line checks to see if the passed in parameter is undefined and performs boolean logic. The …
=> DDF-4958 Fix React Dropdown Closing

catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/SolrMetacardClientImpl.java, platform/solr/solr-schema/src/main/resources/solr/conf/schema.xml, platform/solr/solr-schema/src/main/resources/solr/conf/solrconfig.xml
Removes index based spellcheck from performing dictionary builds on commit and changes the configuration so that the back end spellcheck capability is only executed if enabled in the query itself as opposed to always executing and only handling the results if it is enabled.
@brjeter 
@pklinef 
@codice/solr 
@rzwiefel
@troymohl
Fixes: #4977  …
=> DDF-4977 - Only run back end spellcheck when enabled

ui/packages/catalog-ui-search/src/main/webapp/react-component/container/results-export/results-export.tsx
The source name and/or ID may contain certain URI reserved characters that should not be left unencoded in the path component, such as '?' and '/'. If these are not URI-encoded then the export URL will be wrong or invalid and will not work.
@bellcc 
@gjvera 
@BernardIgiri 
@bennuttle
@codice/ui 
@djblue
1. Ingest some records into DDF.
2. Create a loopback federated source whose name has a `/` in it.
3. Run a query on the source.
4. Attempt to export any single result as any file type, although the file type you choose should be one that the given result will support.
5. Verify the export is successful.
6. Optionally, open the network tab of your browser's developer tools and verify the source name in the export request URL is percent-encoded.
Fixes: #4930 
Please see …
=> DDF-04930 URI-encode the result's source and ID in the export URL

ui/packages/catalog-ui-search/src/main/webapp/react-component/container/multi-select-actions/multi-select-actions.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/multi-select-actions/multi-select-actions.tsx
Removes export multi select action because it's confusing to have 2 places to do the same thing.
@bellcc 
@djblue 
@codice/ui 
@adimka
@bdeining 
Startup the UI and see that the export action is removed.
Fixes: #5007
*Before*
*After* …
=> DDF-5007 Remove Export Action

ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/navigation-right/navigation-right.tsx
It swaps the 'logged in' user avatar with the user name, adds a border to the left side of the login button, and adds spacing around it. 
@djblue 
@adimka 
Open DDF and review it in the top right corner.
Fixes: #5019
- …
=> DDF-05019 Updated navigation right user section for spacing.

ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/user-settings/user-settings.tsx
Allow settings components to render children
Allow settings components to pass in their own onClick handlers
@andrewzimmer 
@willwill96 
@hayleynorton 
@adimka
@bdeining
Verify that all items in the settings pane still function as desired
Verify that there are no errors in the developer console
Test downstream
Fixes: #5014  …
=> DDF-05014 Add extensibility to settings pane

catalog/transformer/catalog-transformer-xml/src/main/java/ddf/catalog/transformer/xml/adapter/GeometryAdapter.java, catalog/transformer/catalog-transformer-xml/src/test/java/ddf/catalog/transform/xml/XmlInputTransformerTest.java, catalog/transformer/catalog-transformer-xml/src/test/resources/metacard-emptygeo1.xml, catalog/transformer/catalog-transformer-xml/src/test/resources/metacard-emptygeo2.xml
Fixes issue with XML Input Transformer that can fail to create metacards having certain empty geometries
@bdeining
@rzwiefel
Ingest Metacard XML with a geometry like the following 
```
<ns3:geometry name="location">
<ns3:value>
<ns1:LineString/>
</ns3:value>
</ns3:geometry>
```
(https://github.com/codice/ddf/blob/e1d3fa3adf6e3483348acf89aeb6880ce9388387/catalog/transformer/catalog-transformer-xml/src/test/resources/metacard-emptygeo1.xml / https://github.com/codice/ddf/blob/e1d3fa3adf6e3483348acf89aeb6880ce9388387/catalog/transformer/catalog-transformer-xml/src/test/resources/metacard-emptygeo2.xml)
ingest using catalog:ingest -t xml or similar 
metacard should ingest successfully and have an empty location attribute
https://github.com/codice/ddf/issues/5024
Please …
=> DDF-5024 XML Transformer handling of empty geos

ui/packages/catalog-ui-search/src/main/webapp/react-component/container/theme-container/theme-container.tsx, ui/packages/catalog-ui-search/src/main/webapp/styles/vars.less
Updated the theme level font sizes to correspond with 12px, 16px and 20px when the browser default is 16px. This sets the stage for creating a vertical rhythm and proper typography hierarchies in the design. It will help to accommodate a more dense data display while still allowing for enough space between things. 
@lifenouveau 
@maryformanek 
@adimka 
@djblue 
The typography size updates will affect the entire UI and can be viewed by looking anywhere. 
Fixes: #5019 …
=> DDF-05019 Updated theme font sizes

ui/packages/catalog-ui-search/src/main/webapp/css/searchPage.css
- Removes old search page css from standard search.  At some point it started winning out in terms of specificity for rules, which mucked with some of the Intrigue styling, such as the consent banner and the initial loading.
@Bdthomson 
@djblue 
@adimka 
Verify that the consent banner background and text color contrast with one another.
Fixes: #5071
=> DDF-5071 Remove old css

ui/packages/catalog-ui-search/src/main/webapp/component/filter-builder/filter-builder.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/filter/filter.collection.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/filter/filter.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/query-add/query-add.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/query-editor/query-editor.view.js
Allows for a list of attribute id's to be passed into the options of a FilterBuilder view, and uses the list to filter the metacard attributes to be displayed in the filter's dropdown
@andrewzimmer 
@zta6 
@willwill96 
@adimka
@bdeining
Verify there are no regressions in the query filters
Fixes: #5004  …
=> DDF-5004 Added extensibility to filters to accept a subset of attributes

ui/packages/catalog-ui-search/src/main/webapp/css/searchPage.css
Port of this PR https://github.com/codice/ddf/pull/5073
-->
Removes old search page css from standard search. At some point it started winning out in terms of specificity for rules, which mucked with some of the Intrigue styling, such as the consent banner and the initial loading.
@Bdthomson
@adimka
@vinamartin 
Verify that the consent banner background and text color contrast with one another.
Fixes: #5071
=> [2.16.x] DDF-5071 Remove old css 

distribution/docs/src/main/resources/templates/architectures.ftl, distribution/docs/src/main/resources/templates/developing.ftl, distribution/docs/src/main/resources/templates/documentation.ftl, distribution/docs/src/main/resources/templates/integrating.ftl, distribution/docs/src/main/resources/templates/managing.ftl, distribution/docs/src/main/resources/templates/metadata.ftl, distribution/docs/src/main/resources/templates/overview.ftl, distribution/docs/src/main/resources/templates/quickstart.ftl, distribution/docs/src/main/resources/templates/reference.ftl, distribution/docs/src/main/resources/templates/using.ftl
Cleans up log warnings within the Documentation module build (it works without these changes, but has warnings in the build logs about `conversion missing for backend pdf`. The scripts being included have no effect on the pdf build, so the templates now perform a check and skip including them during pdf generation. 
@codice/docs 
@adimka
@ahoffer
@brjeter
@lessarderic
build the docs module with `mvn clean install -Prelease`. the noise in the log should be gone. …
=> DDF-2824 added conditional to docs templates

distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalog.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalogSearchUi.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFederation.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestRegistry.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestSecurity.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestSingleSignOn.java
- Updates Itest Rest Assured logging to change from `log().all()` to `log().ifValidationFailed()`. This will help not pollute the build logs with http logging for successful itests (but still include failed test logs)
- The rest assured docs state that `log().all()` is primarily a debugging mechanism for when writing tests
- Removes unused formatter statements that are no longer needed/respected.
Currently no ticket, let me know if anyone thinks its necessary to track.
@codice/test
anyone …
=> Update rest assured logging and removed unused formatter lines

catalog/core/catalog-core-impl/pubsub-tracker/src/main/java/ddf/catalog/pubsub/tracker/SubscriptionTracker.java, catalog/core/catalog-core-impl/pubsub-tracker/src/main/resources/OSGI-INF/blueprint/events_blueprint.xml
Updates EventProcessor to be optional for PubSub because the bundles were getting stuck waiting after the necessary `catalog-core-standardframework` was destroyed. This occurs whenever subscriptions are created, and can take longer than 10min to shutdown. This fixes that issue. 
@Kjames5269 
@ahoffer
@brjeter
@clockard 
1. Install
2. Add subscription in downstream product (see me for how to do so if necessary)
3. Shutdown
4. Verify this took no more than 3min to do so
Fixes: #5084  …
=> DDF-5084 Updated EventProcessor to be optional for PubSub for better shutdown

ui/packages/catalog-ui-search/src/main/webapp/component/filter/filter.view.js
Moves the updateValueFromInput call to after the new view is set so the value of the old is not used.
@rzwiefel @Bdthomson
Start an advanced query, enter any value. 
Switch to the "near" filter comparator. 
Select "search".
Validate that the query editor closes and the query executes.
Fixes: #DDF-05055 …
=> DDF-05055 Fix value retention across filter comparators

catalog/core/catalog-core-impl/pubsub-tracker/src/main/java/ddf/catalog/pubsub/tracker/SubscriptionTracker.java, catalog/core/catalog-core-impl/pubsub-tracker/src/main/resources/OSGI-INF/blueprint/events_blueprint.xml, dependency-check-maven-config.xml
Link to master PR: #5086 
Updates EventProcessor to be optional for PubSub because the bundles were getting stuck waiting after the necessary catalog-core-standardframework was destroyed. This occurs whenever subscriptions are created, and can take longer than 10min to shutdown. This fixes that issue.
@Kjames5269 
@codice/build 
@AzGoalie
@brjeter 
@vinamartin
Install
Add subscription in downstream product (see me for how to do so if necessary)
Shutdown
Verify this took no more than 3min to do so
Fixes: #5084  …
=> [2.16.x] DDF-5084 Updated EventProcessor to be optional for better shutdown

dependency-check-maven-config.xml
OWASP is failing builds for the CVE-2018-11307 for jackson-databind dependency in ehcache jar. This PR suppresses that CVE because version 2.9.8 is what is visibly seen within the project. Solr does not use Batis, and it does not have the exploit for the polymorphic handling / default typing for jackson.
@kcover 
@Kjames5269 
@codice/build 
@brjeter
@stustison
@rzwiefel 
CI build 
Fixes: #5119
- ❓ …
=> DDF-5119 Suppress jackson-databind CVE-2018-11307

distribution/ddf-common/src/main/resources/security/configurations.policy
It was discovered that the URL Resource Reader was failing to work with resources outside of certain directories because it needed the `catalog-core-standardframework` module to have permissions. This PR fixes that to allow it to work with other directories as well. 
@Kjames5269 
@ahoffer
@brjeter
@stustison
(see me for test resources and finer details)
0. Create path outside of DDF and put image resource there
1. Unzip and edit `configurations.policy` file to have permissions to directory in step 0
2. Install standard 
3. Edit URL Resource Reader configuration to have access to path in step 0
4. Ingest xml resource through command line (make sure resource-uri property is same as step 0)
5. Go to Intrigue and hit download button on ingested product
6. Verify no issues and …
=> DDF-5126 Granted standardframework module permission for URL Resource Reader

catalog/core/catalog-core-urlresourcereader/src/main/java/ddf/catalog/resource/impl/URLResourceReader.java, distribution/ddf-common/src/main/resources/security/configurations.policy
Link to 2.16.x PR: #5139 
When working on the 2.16.x port, it was discovered that there was a better solution by adding a doPrivileged block instead. This PR reverts the changes from #5128 and uses the better solution. 
@peterhuffer 
@austinsteffes
@Kjames5269
@ahoffer
@brjeter
@stustison 
See #5139 
Fixes: #5126  …
=> DDF-5126 Add doPrivileged for UrlResourceReader

catalog/core/catalog-core-urlresourcereader/src/main/java/ddf/catalog/resource/impl/URLResourceReader.java
It was discovered that the URL Resource Reader was failing to work with resources outside of certain directories because it needed a doPrivileged block around the canonical path. This PR fixes that to allow it to work with other directories as well.
@austinsteffes
@Kjames5269
@ahoffer 
@brjeter
@stustison
(see me for test resources and finer details)
0. Create path outside of DDF and put image resource there
1. Unzip and edit configurations.policy file to have permissions to directory in step 0
2. Install standard
3. Edit URL Resource Reader configuration to have access to path in step 0
4. Ingest xml resource through command line (make sure resource-uri property is same as step 0)
5. Go to Intrigue and hit download button on ingested product
6. Verify no issues and image is returned
Work …
=> [2.16.x] DDF-5126 Add doPrivilged for UrlResourceReader

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/query/data/metacard/QueryMetacardTypeImpl.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/query/data/model/QueryBasic.java
- Add the security attributes to query metacards to enable sharing of queries. 
@rececoffin 
@Bdthomson 
@codice/data 
@vinamartin
1. Add a new user to DDF. 
2. Ingest a query metacard as a different user. 
3. Update the query metacard to contain the email address for your new user. 
4. Verify that this new user can retrieve this query. 
- None
Fixes: #5153 
- None  …
=> DDF-5153 Added security attributes to query metacards

catalog/transformer/catalog-transformer-bootflag/src/main/java/org/codice/ddf/catalog/transformer/bootflag/InputTransformerBootServiceFlag.java
Decreases Input Transformer Boot Service poll time to every half second from every 20 seconds
- 46.6s avg pre change
- 45.4s avg post change
_As ran across 5 individual runs of `profile:install`_
anyone
Ensure CDM does not start ingesting before all services are up …
=> DDF-4320 Decrease Input Transformer Boot Service Poll time to every half second

ui/packages/catalog-ui-search/src/main/webapp/react-component/utils/fetch/fetch.tsx
Adds cache busting to react-component/utils/fetch
@jrnorth 
@rymach 
@adimka 
Ensure urls sent out by fetch have a timestamp attached.
Fixes: #5173
=> DDF-05173 Adds cache busting to react-component/utils/fetch

ui/packages/catalog-ui-search/src/main/webapp/react-component/location/location.js
Fixes a bug in location attribute filters where the area wasn't expanding when a shape is selected. See screenshot below.
@willwill96 
@andrewzimmer 
@zta6 
@adimka 
@bdeining 
Verify that the spacing is correct in new queries and existing queries in the editor when a shape is and isn't selected
Fixes: #5117 
Before
After …
=> DDF-5117 Fixed location spacing bug in query editor

dependency-check-maven-config.xml, platform/security/platform-security-core-api/src/main/java/ddf/security/SubjectUtils.java
Adds null checking to `SubjectUtils.getSubjectAttributes`.
@blen-desta 
@stustison 
@bdeining 
Easy:
1. Build, run, and install DDF.
2. Login and logout using 2 different methods (PKI and BASIC, for example).
More Involved:
1. Build, run, and install DDF with debugging enabled.
2. Put a breakpoint at the top of `SubjectUtils.getSubjectAttributes`.
3. Log into DDF and perform operations until the breakpoint is hit.
4. (Feel free to message me about clarifying this one) Modify the subject object so on of its attributes contains a list containing only `null`.
5. Step through the rest of the `getSubjectAttributes` method. It should not error out.
Fixes: #5160 
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guideli …
=> Add null checking to SubjectUtils

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/MetacardApplication.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/query/data/metacard/QueryMetacardImpl.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/workspace/transformer/impl/AssociatedQueryMetacardsHandler.java, catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/metacard/workspace/transformer/impl/AssociatedQueryMetacardsHandlerTest.java
When creating or updating query metacards, MetacardApplication always transformed the incoming query JSON to a workspace metacard before handing it to AssociatedQueryMetacardsHandler, who transformed it to a query metacard using QueryMetacardImpl's copy constructor. Recently, the 'metacard-tags' attribute was added to the query metacard type. QueryMetacardImpl's copy constructor set its tag to 'query' and then copied all of the query metacard type's attributes from the source metacard to itself. Since the query metacard type's attributes now contain 'metacard-tags', the tags of the source metacard were copied too, overwriting the tag of 'query' that had already been set. In this case, the source metacard was a workspace metacard so all query metacards that were created in this manner had …
=> DDF-5165 Fix a bug causing query metacards to have the wrong tag

ui/packages/catalog-ui-search/src/main/webapp/react-component/filter/filter.js
Fixed issue where user couldn't enter into search forms inputs.
There were missing props after a refactor before getting merged in.
@Bdthomson 
@andrewzimmer 
@hayleynorton 
@zta6 
@bdeining 
@djblue 
Test search form functionality. Verify you can type into search forms and search properly with them.
Fixes: #5096  …
=> DDF-5096 Fix Missing Props 

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/QueryMetacardApplication.java
Fix query application solr query tags.
@bellcc 
@bdeining
@jlcsmith
Make sure query templates are not returned from QueryApplication endpoints.
Query templates were being returned in the list of queries.
Because `like` tokenizes based on characters such as ` `, `_`, or `-` and found that it matched a token of `query-template`.
Fixes: #5216  …
=> DDF-5216 Fix query application solr query

features/security/pom.xml, features/security/src/main/feature/feature.xml, platform/security/sts/pom.xml, platform/security/sts/security-sts-usernametokenvalidator/pom.xml, platform/security/sts/security-sts-usernametokenvalidator/src/main/java/org/codice/ddf/security/validator/username/UsernameTokenValidator.java, platform/security/sts/security-sts-usernametokenvalidator/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/security/sts/security-sts-usernametokenvalidator/src/test/java/org/codice/ddf/security/validator/username/UsernameTokenValidatorTest.java, platform/security/sts/security-sts-usernametokenvalidator/src/test/resources/user-no-password.xml, platform/security/sts/security-sts-usernametokenvalidator/src/test/resources/user.xml
This reverts commit e8135dbeefb21226312182d457eb331b8da8fb24 and restores the source for
the module that is needed.
The source was mistakenly deleted for security-sts-usernametokenvalidator. However since the feature file and corresponding pom dependency still existed and it was able to find the jar magically because there was a snapshot version built it continued to work (even though the code was deleted). When the feature file reference was removed however the tokenvalidator that was being registered by the ghost bundle all of a sudden stopped working. This adds back the source for usernametokenvalidator and puts back the featurefile references as well since the source now exists again!
@bakejeyner @blen-desta @mcat97 @nsuvarna @samuelechu @jlcsmith
=> Revert "remove non-existent dependency (#5213)" and restores source

platform/security/core/security-core-services/pom.xml, platform/security/core/security-core-services/src/main/java/ddf/security/service/impl/SubjectIdentityImpl.java, platform/security/core/security-core-services/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/security/core/security-core-services/src/test/java/ddf/security/service/impl/SubjectIdentityTest.java
The ddf.security.impl package is exported by both security-core-services and security-core-impl. The duplicate export can cause the security-core-services bundle to fail to start which causes all other dependent bundles to fail.
This PR resolves the duplicate export.
@rzwiefel @derekwilhelm 
@rzwiefel
Full build
Fixes: #____ …
=> [2.17.x] DDF-05230 resolves duplicate security package export

ui/packages/catalog-ui-search/src/main/webapp/js/extensions/marionette.ItemView.attachElContent.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/backbone-container/backbone-container.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/dropdown/dropdown.tsx
- Because Application setup is called before entry is executed, it's possible for anything executed in setup to receive out of date extension points if they grab an extension point and store it in a variable for later.
Easiest way is to see if your providers downstream start working more reliably.  There's a good chance people have just been double wrapping because they noticed something wasn't working right, such as a redux store not showing up.
Fixes: #5228
=> DDF-5228 Updates usage of extension providers so they're always applied correctly

ui/packages/catalog-ui-search/package.json, ui/packages/catalog-ui-search/src/main/webapp/react-component/dropdown/dropdown.js
Removes background color from dropdown components.
See https://github.com/codice/ddf/pull/5220
@jordanwilking
@rzwiefel
@codice/ui
@adimka
@vinamartin
Opening up dropdowns and making sure they weren't relying on this background color being set.
Fixes: #5219
* ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist.
* ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for …
=> [2.17.x] DDF-5219 Remove background from dropdown elements

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/QueryMetacardApplication.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/query/data/model/QueryBasic.java
Adds security.access-individuals to query metacard when created using the `/queries` route.
See https://github.com/codice/ddf/pull/5244
@blen-desta
@bellcc
@jlcsmith
@rzwiefel
@vinamartin
Create a custom user 1, create a search.
Create a custom user 2, hit the queries endpoint route, verify you don't see user 1's search.
Example User files
`users.attributes`
```json
{
"admin" : {
"http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress":"admin@localhost.local",
"http://schemas.xmlsoap.org/ws/2005/05/identity/claims/role": ["admin","manager","viewer","system-admin","systembundles"]
},
"localhost" : {
"http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress":"system@localhost.local",
"http://schemas.xmlsoap.org/ws/2005/05/identity/claims/role": …
```
=> [2.17.x] DDF-5243 Add security access individuals on create query route

dependency-check-maven-config.xml
Suppresses Solr CVE-2019-0193 that is not hit with current DDF Solr configuration.
CVE: https://nvd.nist.gov/vuln/detail/CVE-2019-0193
Solr analysis: https://issues.apache.org/jira/browse/SOLR-13669 
Also suppressed false positive match on unrelated CVE-2017-16026. This CVE is related to a node module that has nothing to do with the DDF security module OWASP matched. https://nvd.nist.gov/vuln/detail/CVE-2017-16026
@bdeining  
@bakejeyner 
@codice/solr 
@coyotesqrl
@stustison
Fixes: #5232  …
=> DDF-5232 Suppress Solr CVE that doesn't apply to current DDF Solr Config

catalog/spatial/wfs/spatial-wfs-featuretransformer-xstream/pom.xml, catalog/spatial/wfs/spatial-wfs-featuretransformer-xstream/src/main/java/org/codice/ddf/spatial/ogc/wfs/transformer/xstream/XStreamWfs11FeatureTransformer.java, catalog/spatial/wfs/spatial-wfs-featuretransformer-xstream/src/test/java/org/codice/ddf/spatial/ogc/wfs/transformer/xstream/XStreamWfs11FeatureTransformerTest.java, catalog/spatial/wfs/spatial-wfs-featuretransformer-xstream/src/test/resources/Neverland_FeatureType.xsd
In the case that a metacard mapper was present, the coordinate order was not set, which caused the generic feature converter to not flip the coordinates of lat/lon features when it should have. This PR ensures the coordinate order is always set on the generic feature converter so it knows when to flip the coordinates.
@glenhein 
@leo-sakh 
@bennuttle 
@gjvera 
@codice/ogc 
@jlcsmith
@troymohl
1. In the Admin UI, open the Spatial app.
2. Click `Metacard to WFS Feature Map`.
3. For `Feature Type`, enter `{http://stategeothermaldata.org/uri-gin/aasg/xmlschema/welllog/0.8}AZWellLogs`.
4. For `Metacard Geography to WFS Feature Property Mapping`, enter `ext.AZWellLogs.Shape`.
5. Click `Save changes`.
6. Create a WFS 1.1.0 source with the URL …
=> DDF-05092 Always set the WFS 1.1 generic feature converter coordinate order

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/QueryMetacardApplication.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/query/data/model/QueryBasic.java
Adds security.access-individuals to query metacard when created using the `/queries` route.
@blen-desta 
@bellcc 
@jlcsmith 
@rzwiefel 
@vinamartin
Create a custom user 1, create a search.
Create a custom user 2, hit the queries endpoint route, verify you don't see user 1's search.
Example User files
`users.attributes`
```json
{
"admin" : {
"http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress":"admin@localhost.local",
"http://schemas.xmlsoap.org/ws/2005/05/identity/claims/role": ["admin","manager","viewer","system-admin","systembundles"]
},
"localhost" : {
"http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress":"system@localhost.local",
"http://schemas.xmlsoap.org/ws/2005/05/identity/claims/role": …
```
=> DDF-5243 Add security access individuals on create query route

ui/packages/catalog-ui-search/src/main/webapp/extension-points/extension-points.tsx, ui/packages/catalog-ui-search/src/main/webapp/extension-points/multi-select-actions/index.tsx, ui/packages/catalog-ui-search/src/main/webapp/extension-points/multi-select-actions/multi-select-actions.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/multi-select-actions/presentation.tsx
Moves multi-select-actions from plugins to extension-points
@andrewzimmer 
@willwill96 
@zta6 
@adimka
@bdeining 
Verify there are no console errors and that the UI loads properly. The multi-select-action bar should not show up anywhere on the UI
Fixes: #5277  …
=> DDF-5277 Moved multi-select-actions to extension-points

ui/packages/catalog-ui-search/src/main/webapp/js/cql.js, ui/packages/catalog-ui-search/src/main/webapp/js/cql.spec.js
Allow for empty strings in front end CQL parsing. Other attributes are allowed to be empty. This change is necessary for a downstream project to filter out empty strings in queries.
@hayleynorton 
@andrewzimmer 
@willwill96 
@bdeining
Verify there are no regressions in querying
Fixes: #5223  …
=> DDF-5223 Allow parsing of empty time strings in CQL

catalog/core/catalog-core-solr/pom.xml, catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/SolrFilterDelegate.java, catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/SolrFilterDelegateTest.java, catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/provider/SolrProviderQuery.java
DDF generates invalid Solr queries for "=" relationships for numerics when the value is negative. This means the user cannot query for an exact negative value of numeric fields.
@codice/solr 
@clockard
@pklinef
ingest a file that contains a numeric value (ex. media.height)
issue query from the ui (ex. media.height=-1)
observe no errors and correct query is issued against sor
Fixes: #5275 …
=> DDF-5275 Escaped negative numbers for equality queries and increased coverage

distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/callables/GetConfigurationProperties.java, platform/admin/admin-configuration-configupdater/src/main/java/org/codice/ddf/admin/configuration/ConfigurationUpdater.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/admin/ExportMigrationConfigurationAdminContext.java, platform/security/core/security-core-impl/src/main/java/ddf/security/assertion/jwt/impl/SecurityAssertionJwt.java, platform/security/encryption/platform-security-encryption-crypter/src/main/java/ddf/security/encryption/crypter/Crypter.java, platform/security/encryption/platform-security-encryption-impl/src/main/java/ddf/security/encryption/impl/EncryptionServiceImpl.java
- SLF4J logging statements should use parameterized logging   (https://www.slf4j.org/faq.html#logging_performance) instead of String.format().
- Parameterized logging statements need to use {} as the formatting anchor, not Java-style formatting anchors like %s.
@bennuttle 
@gjvera 
@clockard
@jlcsmith 
Full build is sufficient.
Fixes: #5263  …
=> [2.17.x] DDF-5263 Fix improper SLF4J usages

distribution/ddf-common/src/main/resources/etc/migration.properties, distribution/docs/src/main/resources/content/_managing/_configuring/reusing-configurations.adoc, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/admin/ConfigurationAdminMigratable.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/admin/ImportMigrationConfigurationAdminContext.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/admin/ImportMigrationConfigurationAdminEntry.java, platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/admin/ConfigurationAdminMigratableTest.java
Adds support for upgrading CDM and URL Resource Reader configurations with migration across versions.
@ahoffer 
@brjeter
@paouelle
1. Install an old release version of DDF that is in the list of "supported versions" and create CDM and URL Resource Reader configurations (including configurations.policy change) 
2. Run migration:export, which creates 3 files under the `etc/exported directory`
3. Shutdown
4. Start up a DDF built on this PR's changes
5. Install with `profile:install standard`
6. Copy all 3 files from step 2 into this newly installed DDF under <ddf-home>/exported.
7. Run `migration:import -f`
8. After the system automatically restarts, verify all config changes are present in the new DDF and CDM works
Work for: #5298  …
=> [2.16.x] DDF-5298 Added support for upgrading CDM configurations with migration

ui/packages/catalog-ui-search/src/main/webapp/component/tabs/metacard/tabs-metacard.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/tabs/metacards/tabs-metacards.view.js
Prevents rendering of the tabs view inside of inspector until other operations have finished.
@vinamartin 
@rzwiefel 
@bdeining
I haven't found a way to actually break this in DDF but it can be replicated in downstream packages with UI heavy visualizations.
Fixes: #5338  …
=> DDF-5338 Use setTimeout to put child render at the top of the stack

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/query/data/model/QueryBasic.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalogSearchUi.java
Updates @SerializedName in QueryBasic, so hitting QueryMetacardApplication's endpoints will serialize "src" into QueryBasic's sources variable. 
@Bdthomson 
@vinamartin 
@troymohl
@vinamartin
- Use Postman to POST to this endpoint: https://localhost:8993/search/catalog/internal/queries
- You're sending "src", but the response should still come back as "sources". 
- The body should look something like this:
```
{
"cql": "(\"anyText\" ILIKE 'postman')",
"filterTree": "{\"type\":\"AND\",\"filters\":[{\"type\":\"ILIKE\",\"property\":\"anyText\",\"value\":\"postman\"}]}",
"excludeUnnecessaryAttributes": true,
"count": 250,
"start": 1,
"federation": "selected",
"sorts": [
{
"attribute": "modified",
"direction": "descending"
}
],
"serverPageIndex": 1,
"type": "advanced", …
```
=> DDF-5317 Change serialized name in QueryBasic to "src"

platform/security/core/security-core-services/pom.xml, platform/security/core/security-core-services/src/main/java/ddf/security/service/impl/SubjectIdentityImpl.java, platform/security/core/security-core-services/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/security/core/security-core-services/src/test/java/ddf/security/service/impl/SubjectIdentityTest.java
Backport of https://github.com/codice/ddf/pull/5231
The ddf.security.impl package is exported by both security-core-services and security-core-impl. The duplicate export can cause the security-core-services bundle to fail to start which causes all other dependent bundles to fail.
This PR resolves the duplicate export
@derekwilhelm @Bdthomson   
@stustison 
@vinamartin
Fixes: #____ …
=> DDF-05230 resolves duplicate security package export (#5231)

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/query/data/model/QueryBasic.java
- Adds group sharing attributes to query basic so that you can update and retrieve them. 
@rececoffin 
@codice/data 
@vinamartin
1. Create a query metacard. 
2. Update that query metacard with a group.
3. Retrieve that query metacard to verify that the newly updated group shows up. 
- None
Fixes: #5253 
- None …
=> DDF-5253 Adds group sharing attributes to query basic

platform/security/certificate/security-ocsp-checker/pom.xml, platform/security/certificate/security-ocsp-checker/src/main/java/org/codice/ddf/security/ocsp/checker/OcspChecker.java, platform/security/certificate/security-ocsp-checker/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/security/certificate/security-ocsp-checker/src/test/resources/simplelogger.properties
Refer to https://github.com/codice/ddf/pull/5272 for more information
=> [2.16.x] DDF-05271 Fix OCSP Checker to only revoke certificates that contain a revoked certificate status

dependency-check-maven-config.xml
Link to 2.16.x PR: #5316 
Suppresses CVE warning for a dependency required by Artemis.
@brjeter
@clockard 
@stustison
Full build with OWASP
The final solution to this will be to move the Artemis feature into a separate repository and compose it into distributions as required vs embedding directly into DDF.
Suppress additional CVE against jruby-complete.
Work for: #5315 
- ❓ (Question …
=> [2.16.x] DDF-5315 Suppress beanutils from Artemis dependency

platform/security/certificate/security-ocsp-checker/pom.xml, platform/security/certificate/security-ocsp-checker/src/main/java/org/codice/ddf/security/ocsp/checker/OcspChecker.java, platform/security/certificate/security-ocsp-checker/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/security/certificate/security-ocsp-checker/src/test/resources/simplelogger.properties
Updates the OCSP checker to only revoke certificates that contain a revoked status. 
There was an issue with the OCSP Checker that would potentially revoke a "good" or "unknown" certificate in the case that the OCSP response returned multiple certificates with their statuses. The checker would return the certificate status of the first certificate in the response list, without checking whether or not that certificate matched the certificate issued in the OCSP request (the user's cert). The OCSP Checker now checks in the OCSP Response for the certificate that matches the certificate issued in the OCSP request (via the certificate serial number) and revoke it only if it contains a revoked status.
Added trace logging of the OCSP request and response for easier troubleshooting. …
=> DDF-05271 Fix OCSP Checker to only revoke certificates that contain a revoked certificate status

catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java, catalog/spatial/csw/spatial-csw-endpoint/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/spatial/csw/spatial-csw-endpoint/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpointTest.java, distribution/docs/src/main/resources/content/_managing/_configuring/configuring-csw-endpoint.adoc
Adds threading to incoming CSW transactions to parallel process incoming data through the Catalog Framework.
@jrnorth 
@leo-sakh 
@codice/io 
@adimka
@bdeining 
@millerw8 
Test a CSW transaction with multiple records. Verify CPU usage >100% during processing (indicates parallel processing being performed).
Fixes: #5115  …
=> DDF-5115 Thread CSW transactions

distribution/ddf-common/src/main/resources/security/default.policy, distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/AbstractIntegrationTest.java
**First commit:** Fixes an AC exception that happens when Installing a feature that drops a config file, causing the installation to fail
**Second commit:** Increase itest timeout, which has been causing flakiness in CI, especially for downstream projects (taken from [this PR on master](https://github.com/codice/ddf/pull/5169/files) )
@austinsteffes @tyler30clemens 
@blen-desta 
@stustison
Successful CI.
Fixes: #5361  …
=> [2.16.x] Fix for AC exception during installation and itest tuning

distribution/ddf-common/src/main/resources/security/default.policy
Forward port from 2.16.x PR: https://github.com/codice/ddf/pull/5362
Fixes an AC exception that happens when Installing a feature that drops a config file, causing the installation to fail
@austinsteffes @tyler30clemens 
@blen-desta 
@stustison
Successful CI.
Fixes: #5361  …
=> DDF-5361 Update policy file for installing a feature that drops a config file

ui/packages/catalog-ui-search/src/main/webapp/react-component/theme/theme.tsx
- Without a dot at the front, this `off` wasn't removing the events for the instance.  This caused them to build up over time.
Easiest is to verify by checking out master and seeing the behavior there first.  Open the chrome dev tools, go to the memory section.  Have a workspace with two searches.  Switch back and forth between them a few times so that results render.  On the memory section, take a heap snapshot.  Filter to theme.  Note the number of objects.  Switch back and forth searches a few more times.  Take another heap snapshot.  Note the number of objects (should be higher on master).
Do the same thing on this PR and note the number of objects remains constant between multiple switches.
I'll attach some screenshots of the snapshots as proof.
Fixes: #5357 
This branch after a few …
=> DDF-5357 Fixes memory leak in theme

distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/callables/GetConfigurationProperties.java, platform/admin/admin-configuration-configupdater/src/main/java/org/codice/ddf/admin/configuration/ConfigurationUpdater.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/admin/ExportMigrationConfigurationAdminContext.java, platform/security/core/security-core-impl/src/main/java/ddf/security/assertion/jwt/impl/SecurityAssertionJwt.java, platform/security/encryption/platform-security-encryption-crypter/src/main/java/ddf/security/encryption/crypter/Crypter.java, platform/security/encryption/platform-security-encryption-impl/src/main/java/ddf/security/encryption/impl/EncryptionServiceImpl.java
Link to 2.17.x PR: #5264 
- SLF4J logging statements should use parameterized logging (https://www.slf4j.org/faq.html#logging_performance) instead of String.format().
- Parameterized logging statements need to use {} as the formatting anchor, not Java-style formatting anchors like %s.
@bennuttle 
@gjvera 
@ryeats 
@shaundmorris
Full build is sufficient.
Fixes: #5263  …
=> DDF-5263 Fix improper SLF4J usages

distribution/ddf-common/src/main/resources/etc/migration.properties, distribution/docs/src/main/resources/content/_managing/_configuring/reusing-configurations.adoc, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/admin/ConfigurationAdminMigratable.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/admin/ImportMigrationConfigurationAdminContext.java, platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/admin/ConfigurationAdminMigratableTest.java
Added support for upgrading registry and source configurations with migration across accepted versions
@ahoffer 
@brjeter
@paouelle
1. Install an old release version of DDF that is in the list of "supported versions" and create registry and source configurations
2. Run `migration:export`, which creates 3 files under the etc/exported directory
3. Shutdown
4. Start up a DDF built on this PR's changes
5. Install with `profile:install standard`
6. Copy all 3 files from step 2 into this newly installed DDF under /exported.
7. Run `migration:import -f`
8. After the system automatically restarts, verify all config changes are present in the new DDF and they work
Work for: #5354  …
=> [2.16.x] DDF-5354 Added support for registry/sources configs with migration

platform/security/handler/security-handler-oidc/src/main/java/org/codice/ddf/security/handler/oidc/OidcHandlerConfigurationImpl.java
Removes throwing error in config impl to prevent flooding logs. (See #5386) 
@blen-desta 
@bakejeyner 
@bdeining 
@nsuvarna 
Fixes: #5386
=> DDF-5386 Removing Error In OidcHandlerConfigurationImpl To Prevent Log Flooding

distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/callables/GetConfigurationProperties.java, platform/admin/admin-configuration-configupdater/src/main/java/org/codice/ddf/admin/configuration/ConfigurationUpdater.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/admin/ExportMigrationConfigurationAdminContext.java, platform/security/core/security-core-impl/src/main/java/ddf/security/assertion/jwt/impl/SecurityAssertionJwt.java, platform/security/encryption/platform-security-encryption-crypter/src/main/java/ddf/security/encryption/crypter/Crypter.java, platform/security/encryption/platform-security-encryption-impl/src/main/java/ddf/security/encryption/impl/EncryptionServiceImpl.java
- SLF4J logging statements should use parameterized logging (https://www.slf4j.org/faq.html#logging_performance) instead of String.format().
- Parameterized logging statements need to use {} as the formatting anchor, not Java-style formatting anchors like %s.
@bennuttle 
@gjvera 
@pklinef  
@shaundmorris
Full build is sufficient.
Fixes: #5263  …
=> [2.18.x] DDF-5263 Fix improper SLF4J usages

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/security/app/UserApplication.java, catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/blueprint/blueprint.xml, ui/packages/catalog-ui-search/src/main/webapp/component/alert-item/alert-item.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/singletons/user-notifications.js, ui/packages/catalog-ui-search/src/main/webapp/js/QueryPolling.js, ui/packages/catalog-ui-search/src/main/webapp/js/model/User.js
It separates user alerts to be read from their own core, rather than the preferences core. They are still added to the alerts section of the user object before it is sent to the UI, in order to minimize changes needed to the User model. The primary motivation for this change is to fix an issue in a downstream project created by the lack of granularity in the preferences blob.
Deletion of alerts has changed somewhat; upload notifications are still deleted by overwriting the preferences blob, but alert notifications are now deleted by sending their ids to the user/notifications endpoint. A large benefit of this is that it allows us to specify specific alerts to delete, rather than deleting them all for a given user and rewriting them all every time. Another benefit of this is that it won't …
=> DDF-5312 User alerts use notifications core

distribution/docs/src/main/resources/content/_managing/_configuring/reusing-configurations.adoc, features/migration/pom.xml, features/migration/src/main/feature/feature.xml, platform/migration/platform-migration/pom.xml, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/admin/ConfigurationAdminMigratable.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/admin/ImportMigrationConfigurationAdminContext.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/admin/ImportMigrationConfigurationAdminEntry.java, platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/admin/ConfigurationAdminMigratableTest.java
Port from 2.16.x: #5320 
Second commit contains additional logic
Adds support for upgrading `Web Context Policy Manger`, `Guest Claims Configuration`, `STS Server`, and `Session` security configurations with migration across versions.
@ahoffer 
@codice/core-apis  
@brjeter
@paouelle
See #5320 
Fixes: #5311  …
=> DDF-5311 Added support for upgrading some security configs with migration

ui/packages/catalog-ui-search/src/main/webapp/component/query-add/query-add.view.js
This PR fixes an issue where queries were executed twice upon initial invocation. 
@Schachte 
@nsuvarna 
@codice/ui
@djblue
@bdeining
@blen-desta 
@vinamartin 
1. Run a query and observe only one `cql` item appears in the Network Tab of your browser.
Fixes: [#5384](https://github.com/codice/ddf/issues/5384) …
=> [2.18.x] DDF-5384 Fixed double execution of query

ui/packages/catalog-ui-search/src/main/webapp/react-component/theme/theme.tsx
- Without a dot at the front, this `off` wasn't removing the events for the instance.  This caused them to build up over time.
Easiest is to verify by checking out master and seeing the behavior there first.  Open the chrome dev tools, go to the memory section.  Have a workspace with two searches.  Switch back and forth between them a few times so that results render.  On the memory section, take a heap snapshot.  Filter to theme.  Note the number of objects.  Switch back and forth searches a few more times.  Take another heap snapshot.  Note the number of objects (should be higher on master).
Do the same thing on this PR and note the number of objects remains constant between multiple switches.
I'll attach some screenshots of the snapshots as proof.
Fixes: #5357 
This branch after a few …
=> [2.18.x] DDF-5357 Fixes memory leak in theme

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/forms/builder/AttributeValueNormalizer.java
This PR allows date type fields to be saved with an empty value in search forms. Previously on save an ambiguous error would appear and the search form could not be saved. Seeing as other fields may be saved with blank fields it was not clear that was the issue.
@rzwiefel 
@Lambeaux 
@codice/solr 
@rzwiefel 
@Lambeaux 
This should be tested by saving a search form with an empty date attribute.
1. Create a search form with the datetime.start before filter and an empty field.
2. Access Workspaces -> create a new workspace or access an existing one
3. Select Create a search -> select the ellipses menu and choose "Use Another Search Form"
4. Select the form you made in step 1 and ensure the datetime.start filter value is empty (the placeholder will be present) when it is initialized. 
Fixes: …
=> DDF-#04993 Allows for empty dates in search forms

ui/packages/catalog-ui-search/src/main/webapp/component/query-add/query-add.view.js
This PR fixes an issue where queries were executed twice upon initial invocation. 
@Schachte 
@nsuvarna 
@codice/ui
@djblue
@bdeining
@blen-desta 
@vinamartin 
1. Run a query and observe only one `cql` item appears in the Network Tab of your browser.
Fixes: [#5384](https://github.com/codice/ddf/issues/5384)
Forward port of [#5385](https://github.com/codice/ddf/pull/5385) …
=> DDF-5834 Fixed double invokation of query

distribution/ddf-common/src/main/resources/etc/org.ops4j.pax.web.cfg, features/security/src/main/feature/feature.xml
Instead of having the Jetty Authenticator properties set out-of-the-box, only set them when the platform-paxwebjettyconfig feature installed.
This shouldn't have any functional effect on the system as-is, since the platform-paxwebjettyconfig feature is installed at the beginning of the standard installation. The reason for doing this for the feature Component Tests get `No LoginService found` exceptions in the logs (see the issue for more details).
@lamhuy 
@codice/test
@AzGoalie 
@paouelle 
@ryeats 
Fixes: #5418  …
=> DDF-5418 Fix the No LoginService found exceptions in the feature Component Tests

ui/packages/catalog-ui-search/src/main/webapp/js/router.js
Moves the not found route to the last position to ensure other routes aren't overwritten - for example if the routes are extended. 
@Bdthomson 
@djblue 
@vinamartin 
@codice/ui 
@vinamartin 
This can be tested by navigating to different routes and ensuring you are directed where you expected. 
If you wanted to override routes down stream the required order would cause the not found route to be before your extended routes. 
Fixes: #05426 …
=> DDF-5426 Ensures the "not found" route is the last route

distribution/test/itests/README.md, distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/AbstractIntegrationTest.java, distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/SynchronizedConfiguration.java, distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/config/ConfigureTestCommons.java, distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/opensearch/OpenSearchFeature.java, distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/security/SecurityPolicyConfigurator.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalog.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalogSearchUi.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalogValidation.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFanout.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFederation.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFtp.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestRegistry.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestSecurityAuditPlugin.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestSpatial.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestOidc.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestPlatform.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestSecurity.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestSingleSignOn.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestSolrCommands.java, libs/test-common/src/main/java/org/codice/ddf/test/common/annotations/BeforeSuite.java, libs/test-common/src/main/java/org/codice/ddf/test/common/annotations/ExamResultLogger.java, libs/test-common/src/main/java/org/codice/ddf/test/common/annotations/PaxExamRule.java
Currently, the whole container resets after each itest class. Instead, the tests now properly clean up afterwards to save some time. I've seen about 3-4 minutes shaved off due to this change.
@clockard
@coyotesqrl 
@pklinef 
@shaundmorris
@stustison 
@AzGoalie 
@codice/build 
CI
Fixes: #5395  …
=> DDF-5395 Cleanup after itests instead of resetting the system after every class

catalog/core/catalog-core-directorymonitor/pom.xml, catalog/core/catalog-core-directorymonitor/src/test/java/org/codice/ddf/catalog/content/monitor/ContentDirectoryMonitorIT.java, catalog/core/catalog-core-directorymonitor/src/test/java/org/codice/ddf/catalog/content/monitor/features/SecurityFeatures.java, catalog/rest/catalog-rest-endpoint/pom.xml, catalog/rest/catalog-rest-endpoint/src/test/java/org/codice/ddf/endpoints/rest/RestEndpointIT.java, distribution/ddf-common/src/main/resources-filtered/etc/custom.properties, features/camel/src/main/feature/feature.xml, features/cxf/pom.xml, features/cxf/src/main/feature/feature.xml, features/pom.xml, features/security/pom.xml, features/security/src/main/feature/feature.xml, libs/bundles/libs-bundles-opensaml/pom.xml, libs/bundles/pom.xml, libs/pom.xml, platform/security/platform-security-core-api/pom.xml, platform/security/pom.xml, pom.xml
Upgrades the Guava version used by DDF code and OpenSAML code to `25.1-jre`.
@ryeats 
@brianfelix 
@bdeining 
@stustison
- Full build. ✅ 
- SAML Conformance (https://github.com/codice/saml-conformance). ✅ 
- Container starts up, Intrigue is usable logged in. ✅ 
- Features that depend on older Guava versions can be installed (i.e. camel-protobuf). ✅ 
There are several areas of the code where impls are leaking through APIs and, in an OSGi context, are causing unrelated components to inherit problems from their transitive dependencies. This means that the version of Guava that we use and the version of Guava that OpenSAML uses needs to be upgraded in lockstep. The immediate follow-on to this PR will be the following: 
- Cleaning up the security APIs …
=> DDF-5324 Upgrades Guava to 25.1 and forces OpenSAML to use the same version

ui/.eslintrc.js, ui/package.json, ui/packages/admin-metrics-ui/server.js, ui/packages/admin-security-certificate-ui/server.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/button/button.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/theme/theme.tsx, ui/packages/registry-admin-local-ui/server.js, ui/packages/registry-admin-remote-ui/server.js, ui/packages/security-handler-guest/server.js, ui/packages/security-handler-guest/test.js, ui/packages/security-logout/server.js, ui/packages/ui/src/main/webapp/components/hocs/backbone/backbone.tsx, ui/yarn.lock
this needs to be ON so the app can be deployed in a reverse proxy 
https://serverfault.com/a/561897
upgraded to latest ace
=> DDF-04746 eslint: turn on no-absolute-path-references (previously named no-absolute-urls)

ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/button/button.tsx
Removes a misplaced `@ts-ignore` comment introduced by https://github.com/codice/ddf/pull/5409
@rymach 
@brianfelix 
@bdeining
@djblue
Verify the buttons no longer contain `// @ts-ignore` text
Fixes: #4745 
BEFORE
AFTER
=> DDF-04746 Remove misplaced @ts-ignore

catalog/spatial/geocoding/spatial-geocoding-endpoint/pom.xml, catalog/spatial/geocoding/spatial-geocoding-endpoint/src/main/java/org/codice/ddf/spatial/geocoder/endpoint/GeoCoderEndpoint.java
Adds a second layer of protection for XSS Reflection attacks against `GeoCoderEndpoint`.
@garrettfreibott @bakejeyner 
@blen-desta
@brjeter
Postman/curl queries against the endpoint with various input values for the `jsonp` parameter should either return 400 or should return the sanitized input. If any `jsonp` is actually changed in the process of sanitizing, that would indicate a potential hole in the underlying regex that this change will resolve.
https://localhost:8993/services/REST/v1/Locations?jsonp=TEST_VAL&query=phoenix
Fixes: #5474  …
=> [MASTER] DDF-5474 Escapes user-input jsonp parameter on GeoCoderEndpoint.getLocation calls

catalog/spatial/geocoding/spatial-geocoding-endpoint/pom.xml, catalog/spatial/geocoding/spatial-geocoding-endpoint/src/main/java/org/codice/ddf/spatial/geocoder/endpoint/GeoCoderEndpoint.java
Cherry pick of #5475 
@bakejeyner @garrettfreibott 
@blen-desta
@brjeter
Cherry-pick; CI sufficient.
Fixes: #5474 
=> [2.19.x] DDF-5474 Escapes user-input jsonp parameter on GeoCoderEndpoint.getLocation calls

platform/security/sts/security-sts-ldaplogin/src/main/java/ddf/ldap/ldaplogin/SslLdapLoginModule.java
The Karaf upgrade from 4.2.2 to 4.2.6 added some flags in their LDAP authentication module. As such, we need to set said flags accordingly in our `SslLdapLoginModule` in order for LDAP authentication to work properly.
Also, the `logout()` and `abort()` methods overrides are no longer necessary and are removed from the `SslLdapLoginModule`.
@blen-desta 
@stustison 
Test steps described in issue #5466.
Fixes: #5466 …
=> DDF-5466 Fix LDAP after Karaf upgrade

platform/security/sts/security-sts-ldaplogin/src/main/java/ddf/ldap/ldaplogin/SslLdapLoginModule.java
The Karaf upgrade from 4.2.2 to 4.2.6 added some flags in their LDAP authentication module. As such, we need to set said flags accordingly in our `SslLdapLoginModule` in order for LDAP authentication to work properly.
Also, the `logout()` and `abort()` methods overrides are no longer necessary and are removed from the `SslLdapLoginModule`.
@blen-desta 
@stustison 
Test steps described in issue #5466.
Fixes: #5466 …
=> [2.19.x] DDF-5466 Fix LDAP after Karaf upgrade (#5467)

ui/packages/catalog-ui-search/src/main/webapp/component/location-new/geo-components/coordinates.js, ui/packages/catalog-ui-search/src/main/webapp/component/location-new/geo-components/masks.js
Allows for the editing/manual entry of DMS decimals. 
Allows three places of decimal precision, which is equivalent to the 6 digits of precision that we along in the Decimal Degrees format. 
@andrewzimmer 
@hayleynorton 
@codice/ui 
@bdeining
@djblue
Verify that when performing an anyGeo search with a Bounding Box or Pt. Rad geo you are able to manually enter decimals in the DMS coordinate input boxes. Also verify that converting back and forth between DMS and other coordinate formats works properly. Verify that there is never more than 3 digits of decimal precision displayed to the user.
Fixes: #5505  …
=> [2.19.x] DDF-5505 Allow editing of DMS Decimals

catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/DynamicSchemaResolver.java, catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/SolrCatalogProvider.java, catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/DynamicSchemaResolverTest.java, catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/SolrProviderRealTimeQueryTest.java, catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/SolrProviderTest.java, catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/provider/SolrProviderCreate.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/CacheSolrMetacardClient.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/SolrCache.java, catalog/core/catalog-core-standardframework/src/main/resources/OSGI-INF/blueprint/fedstrategy.xml, catalog/solr/catalog-solr-provider/src/main/java/ddf/catalog/solr/provider/SolrCatalogProvider.java, catalog/solr/catalog-solr-provider/src/main/resources/OSGI-INF/blueprint/blueprint.xml
Improve DynamicSchemaResolver so that is pre-populates its cache with all metacard types. This is done by creating a reference listener in blueprint for metacard types and adding/removing those types from the resolver.
@pklinef 
@rzwiefel 
@derekwilhelm 
@codice/solr 
@bdeining
@bdthomson
The original problem can be reproduced by first installing a master build. Then, using the karaf console, run `catalog:search --cql '"security.access-groups" IS NULL'`. You should see an exception in the logs with the message `Anonymous Field Property does not exist. security.access-groups`.
With this PR, you should no longer see the exception.
This is affecting downstream projects.
Fixes: #5535 
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+ …
=> DDF-5535 improve DynamicSchemaResolver so that is pre-populates its cache with all metacard types

ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-serialization.js, ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-serialization.spec.js
Fixes a bug where updating a bounding box in an anyGeo search didn't the bounding box in the query. 
@andrewzimmer 
@willwill96 
@hayleynorton 
@codice/ui 
@bdeining
@bdthomson
1. Ingest multiple pieces of data with location information. 
2. Create an anyGeo bounding box search that will return some of the ingested data
3. Run the search
4. Edit the search, draw a new bounding box that should return a different piece of data
5. re-run the search
6. verify that the search returns results within the new, updated bounding box.
7. Test anyGeo querying with other geo types and make sure they still function correctly. 
8. Test some basic AOI functionality with bounding boxes and make sure that they still function correctly. 
Fixes: #5513  …
=> [2.18.x] DDF-5513 Fix anyGeo bounding box not updating correctly

catalog/spatial/wfs/spatial-wfs-featuretransformer-handlebars/pom.xml, catalog/spatial/wfs/spatial-wfs-featuretransformer-handlebars/src/main/java/org/codice/ddf/spatial/ogc/wfs/transformer/handlebars/HandlebarsWfsFeatureTransformer.java, catalog/transformer/catalog-transformer-streaming-impl/src/main/java/org/codice/ddf/transformer/xml/streaming/impl/Gml3ToWktImpl.java, catalog/transformer/catalog-transformer-streaming-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/transformer/catalog-transformer-streaming-impl/src/test/java/org/codice/ddf/transformer/xml/streaming/impl/Gml3ToWktImplTest.java, catalog/transformer/catalog-transformer-streaming-impl/src/test/java/org/codice/ddf/transformer/xml/streaming/impl/XmlInputTransformerTest.java
`Gml3ToWktImpl` now uses a `SAXParser` with GeoTools' `GMLParserDelegate` instead of GeoTools' `Parser` class. The `Parser` class creates a new `SAXParserFactory` on every parse() call which results in bad performance when batches of GML are parsed. Now, `Gml3ToWktImpl` creates a single `SAXParserFactory` and uses it to create `SAXParser`s (which is expected to be thread safe according to the JAXP 1.6 spec, section 4.14) which use GeoTools' `GMLParserDelegate` to handle the GML, so `Gml3ToWktImpl`'s functionality should remain unchanged.
As stated in the issue (#5455), the WFS 1.1.0 source is where this issue was discovered so I ran some JMeter load tests (100 requests, 5 concurrent users) against DDF's `/cql` endpoint with queries to a WFS 1.1.0 source with and without this change …
=> DDF-5455 Improve GML parsing performance

ui/packages/catalog-ui-search/src/main/webapp/component/list-item/list-item.hbs, ui/packages/catalog-ui-search/src/main/webapp/js/model/List.js
This PR removes the upload button from the List menu if `Search UI -> Configuration -> Catalog UI search -> Show Uploader` is checked.
This work was done by @mdang8 for the UC hackathon.
@mdang8 
@rfding
@codice/ui 
@clockard
- Navigate to `Search UI -> Configuration -> Catalog UI search -> Show Uploader`
- Ensure the box is unchecked
- Navigate to `Intrigue -> Lists`
- Verify the upload icon is present
- Navigate to `Search UI -> Configuration -> Catalog UI search -> Show Uploader`
- Ensure the box is *checked*
- Navigate to `Intrigue -> Lists`
- Verify the upload icon is *not* present
Fixes: #5549
List menu with button unchecked:
List menu with button checked:
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981 …
=> DDF-5549 Removing the upload icon in the list menu if uploads are not enabled

platform/security/encryption/platform-security-encryption-crypter/src/main/java/ddf/security/encryption/crypter/Crypter.java
**Crypter.encrypt()** returns a IOStream that deletes files on stream close.
@aaronilovici 
@bakejeyner 
@clockard
@ahoffer 
1. build DDF and go to the Search UI
2. Ingest a file in the search ui
3. Check the directory **data/tmp**, verify that there are no files starting with "encryption"
Fixes: #5561  …
=> DDF-5561 crypter deletes file on stream close

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/cql/CqlRequest.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/security/app/UserApplication.java, ui/packages/catalog-ui-search/src/main/webapp/component/alert/alert.js, ui/packages/catalog-ui-search/src/main/webapp/js/model/Query.js
Queries will only be created for sources that notifications specify. If no sources are specified, an enterprise query will be performed as before. Additionally, the notificationId itself is attached to these queries to help identify how they were generated.  
@jrnorth 
@codice/ui 
Ingest some data, and schedule a query. In the network request tab, a query should be generated for each available source, and the notification Id should be attached as the `cacheId`
Fixes: #5526  …
=> [2.19.x] Allow notifications to specify which sources they query

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/MetacardFactory.java, catalog/core/catalog-core-standardframework/src/test/groovy/ddf/catalog/impl/operations/MetacardFactorySpec.groovy, catalog/transformer/catalog-transformer-pptx/src/main/java/ddf/catalog/transformer/input/pptx/PptxInputTransformer.java
Allows Pptx files with password protection to be ingested by DDF. Also removes the temp file of the pptx file from **data/tmp**
@aaronilovici 
@rfding 
@brjeter
@clockard
1. Build this branch and start DDF
2. Create a password protected powerpoint: https://support.office.com/en-us/article/password-protection-for-presentations-in-powerpoint-33dfadad-f231-4bd1-8bf6-d15e1671da41
3. Ingest this powerpoint
4. Check that the powerpoint exists in the catalog, and that there is no temporary pptx file in the directory **data/tmp/**
Fixes: #5554  …
=> DDF-5554 password protected pptx files get ingested and removed in tmp

catalog/spatial/wfs/spatial-wfs-featuretransformer-handlebars/pom.xml, catalog/spatial/wfs/spatial-wfs-featuretransformer-handlebars/src/main/java/org/codice/ddf/spatial/ogc/wfs/transformer/handlebars/HandlebarsWfsFeatureTransformer.java, catalog/transformer/catalog-transformer-streaming-impl/src/main/java/org/codice/ddf/transformer/xml/streaming/impl/Gml3ToWktImpl.java, catalog/transformer/catalog-transformer-streaming-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/transformer/catalog-transformer-streaming-impl/src/test/java/org/codice/ddf/transformer/xml/streaming/impl/Gml3ToWktImplTest.java, catalog/transformer/catalog-transformer-streaming-impl/src/test/java/org/codice/ddf/transformer/xml/streaming/impl/XmlInputTransformerTest.java
`Gml3ToWktImpl` now uses a `SAXParser` with GeoTools' `GMLParserDelegate` instead of GeoTools' `Parser` class. The `Parser` class creates a new `SAXParserFactory` on every parse() call which results in bad performance when batches of GML are parsed. Now, `Gml3ToWktImpl` creates a single `SAXParserFactory` and uses it to create `SAXParser`s (which is expected to be thread safe according to the JAXP 1.6 spec, section 4.14) which use GeoTools' `GMLParserDelegate` to handle the GML, so `Gml3ToWktImpl`'s functionality should remain unchanged.
As stated in the issue (#5455), the WFS 1.1.0 source is where this issue was discovered so I ran some JMeter load tests (100 requests, 5 concurrent users) against DDF's `/cql` endpoint with queries to a WFS 1.1.0 source with and without this change …
=> [2.19.x] DDF-5455 Improve GML parsing performance

catalog/spatial/wfs/spatial-wfs-featuretransformer-handlebars/pom.xml, catalog/spatial/wfs/spatial-wfs-featuretransformer-handlebars/src/main/java/org/codice/ddf/spatial/ogc/wfs/transformer/handlebars/HandlebarsWfsFeatureTransformer.java, catalog/transformer/catalog-transformer-streaming-impl/src/main/java/org/codice/ddf/transformer/xml/streaming/impl/Gml3ToWktImpl.java, catalog/transformer/catalog-transformer-streaming-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/transformer/catalog-transformer-streaming-impl/src/test/java/org/codice/ddf/transformer/xml/streaming/impl/Gml3ToWktImplTest.java, catalog/transformer/catalog-transformer-streaming-impl/src/test/java/org/codice/ddf/transformer/xml/streaming/impl/XmlInputTransformerTest.java
`Gml3ToWktImpl` now uses a `SAXParser` with GeoTools' `GMLParserDelegate` instead of GeoTools' `Parser` class. The `Parser` class creates a new `SAXParserFactory` on every parse() call which results in bad performance when batches of GML are parsed. Now, `Gml3ToWktImpl` creates a single `SAXParserFactory` and uses it to create `SAXParser`s (which is expected to be thread safe according to the JAXP 1.6 spec, section 4.14) which use GeoTools' `GMLParserDelegate` to handle the GML, so `Gml3ToWktImpl`'s functionality should remain unchanged.
As stated in the issue (#5455), the WFS 1.1.0 source is where this issue was discovered so I ran some JMeter load tests (100 requests, 5 concurrent users) against DDF's `/cql` endpoint with queries to a WFS 1.1.0 source with and without this change …
=> [2.18.x] DDF-5455 Improve GML parsing performance

distribution/docs/src/main/resources/content/_architectures/_migrationApi/migration-api.adoc, distribution/docs/src/main/resources/content/_architectures/_resources/retrieving-resources-options.adoc, distribution/docs/src/main/resources/content/_architectures/_resources/retrieving-resources.adoc, distribution/docs/src/main/resources/content/_developing/_devComponents/custom-catalog-frameworks.adoc, distribution/docs/src/main/resources/content/_developing/_devComponents/custom-filters.adoc, distribution/docs/src/main/resources/content/_developing/_devComponents/custom-plugins.adoc, distribution/docs/src/main/resources/content/_developing/_devComponents/custom-query-options.adoc, distribution/docs/src/main/resources/content/_developing/_devComponents/custom-registry-clients.adoc, distribution/docs/src/main/resources/content/_developing/_devComponents/custom-sources.adoc, distribution/docs/src/main/resources/content/_integrating/_endpoints/catalog-rest-endpoint.adoc, distribution/docs/src/main/resources/content/_integrating/_endpoints/csw-endpoint.adoc, distribution/docs/src/main/resources/content/_integrating/_endpoints/opensearch-endpoint.adoc, distribution/docs/src/main/resources/content/_managing/_configuring/hardening-solr.adoc, distribution/docs/src/main/resources/content/_managing/_configuring/map-configuration-intrigue.adoc, distribution/docs/src/main/resources/content/_managing/_configuring/setting-internal-policies.adoc, distribution/docs/src/main/resources/content/_managing/_securing/managing-crl.adoc
Backticks are used to monospace and set off terms in the documentation. These changes clear up typos or misapplications of monospace formatting. 
@codice/docs 
@ahoffer
@brjeter
@clockard
@lessarderic
@mcalcote
build page and search for '`' in rendered html docs
ddf-2824 …
=> DDF-2824 cleaned up stray backticks in documentation

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/cql/CqlRequest.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/security/app/UserApplication.java, ui/packages/catalog-ui-search/src/main/webapp/component/alert/alert.js, ui/packages/catalog-ui-search/src/main/webapp/js/model/Query.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/multi-select-actions/container.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/multi-select-actions/presentation.tsx
Queries will only be created for sources that notifications specify. If no sources are specified, an enterprise query will be performed as before. Additionally, the notification Id itself is attached to these queries to help identify how they were generated.
Also,
We pass the selection interface as a prop to the multi select component, so it can access whatever the current selection interface is in a given environment. The ability to select all alert results is also added.
@codice/ui 
@jrnorth
Ingest some data, and schedule a query. In the network request tab, a query should be generated for each available source, and the notification Id should be attached as the cacheId. Use the top checkbox to select all results, and verify that each of them have a checkmark added to …
=> [DDF-5567][DDF-5526] Notifications specify the source they query; results are selectable.  

catalog/spatial/wfs/spatial-wfs-featuretransformer-handlebars/pom.xml, catalog/spatial/wfs/spatial-wfs-featuretransformer-handlebars/src/main/java/org/codice/ddf/spatial/ogc/wfs/transformer/handlebars/HandlebarsWfsFeatureTransformer.java, catalog/transformer/catalog-transformer-streaming-impl/src/main/java/org/codice/ddf/transformer/xml/streaming/impl/Gml3ToWktImpl.java, catalog/transformer/catalog-transformer-streaming-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/transformer/catalog-transformer-streaming-impl/src/test/java/org/codice/ddf/transformer/xml/streaming/impl/Gml3ToWktImplTest.java, catalog/transformer/catalog-transformer-streaming-impl/src/test/java/org/codice/ddf/transformer/xml/streaming/impl/XmlInputTransformerTest.java
`Gml3ToWktImpl` now uses a `SAXParser` with GeoTools' `GMLParserDelegate` instead of GeoTools' `Parser` class. The `Parser` class creates a new `SAXParserFactory` on every parse() call which results in bad performance when batches of GML are parsed. Now, `Gml3ToWktImpl` creates a single `SAXParserFactory` and uses it to create `SAXParser`s (which is expected to be thread safe according to the JAXP 1.6 spec, section 4.14) which use GeoTools' `GMLParserDelegate` to handle the GML, so `Gml3ToWktImpl`'s functionality should remain unchanged.
As stated in the issue (#5455), the WFS 1.1.0 source is where this issue was discovered so I ran some JMeter load tests (100 requests, 5 concurrent users) against DDF's `/cql` endpoint with queries to a WFS 1.1.0 source with and without this change …
=> [2.20.x] DDF-5455 Improve GML parsing performance

distribution/solr-distro/src/main/resources/bin/solr, distribution/solr-distro/src/main/resources/bin/solr.cmd
Fixes start scripts for solr to refer to the correct location for the log4j config file
(Cherrypicked from #5656)
@sgalla @KalCramer 
@jrnorth
@ryeats
Start server and ensure no error appears in log like `ERROR StatusLogger Unable to access...` referring to solr log4j configuration file.
Fixes: #5655  …
=> DDF-5655 Corrects location of solr log4j configuration script in start scripts

distribution/solr-distro/src/main/resources/bin/solr, distribution/solr-distro/src/main/resources/bin/solr.cmd
Fixes start scripts for solr to refer to the correct location for the log4j config file
@sgalla @KalCramer 
@jrnorth
@ryeats
Start server and ensure no error appears in log like `ERROR StatusLogger Unable to access...` referring to solr log4j configuration file.
Fixes: #5655  …
=> [2.21.x] DDF-5655 Corrects location of solr log4j configuration script in start scripts

Jenkinsfile
Archive the dependency-check aggregate report after the owasp stage finishes successfully
@TonyMorrison 
@LinkMJB 
@shaundmorris 
@codice/build 
N/A
N/A
Fixes: #5635 …
=> DDF-5635: Attach dependency check report to build.

ui/packages/catalog-ui-search/src/main/webapp/component/announcement/announcement.less, ui/packages/catalog-ui-search/src/main/webapp/component/query-add/query-add.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/query-advanced/query-advanced.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/query-basic/query-basic.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/query-editor/query-editor.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/query-settings/query-settings.view.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/location/base.line.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/utils/validation/index.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/utils/validation/validation.tsx
_Only review the last commit; this PR is based on https://github.com/codice/ddf/pull/5571 and https://github.com/codice/ddf/pull/5594_
Converts WKT strings to the correct format automatically instead of relying on error messages to inform the user of the correct format and making them convert it themselves.
@zta6 @cassandrabailey293 
@codice/ui 
@bdeining
@Bdthomson 
Copy and paste WKT strings into the Polygon and Line geo filter fields. Verify that they're being immediately converted into the correct format, the shapes are still showing up on the map and you can successfully execute the search without any error messages.
Note about multipolygons: each polygon in a multipolygon must have at least 4 coordinate pairs (first and last should be the same). Test with multipolygons where at …
=> [2.19.x] DDF-5610 Automatically convert WKT strings to correct format in polygon and line geo filters

ui/packages/catalog-ui-search/src/main/webapp/component/query-add/query-add.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/query-adhoc/query-adhoc.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/query-advanced/query-advanced.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/query-basic/query-basic.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/query-editor/query-editor.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/query-settings/query-settings.view.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/utils/validation/index.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/utils/validation/validation.tsx
Refactors the geostring validation logic into the child components instead of in `query-add`. 
Additionally, refactors for the `validate` function are contained in this PR. The naming was confusing, so names have been fixed and logic slightly altered for clarity. rather than calling two `validate` functions, we now call `getErrorMessages`, which were formerly the `validate` functions in the view classes (originally, the `isValid` functions). This is clearer because `validate` was just returning error messages anyway. 
The `validate` function in `validation.tsx`, as well as the newly added `validateFilters`, were refactored. `validate`'s main function was to show the error messages, if any existed. In this refactor, checking for the existence of error messages has been moved out of this …
=> [2.19.x] DDF-5593 geostring validation

distribution/docs/src/main/resources/content/_architectures/_catalogFrameworks/catalog-api.adoc, distribution/docs/src/main/resources/content/_architectures/_catalogFrameworks/catalog-framework-camel-component.adoc, distribution/docs/src/main/resources/content/_architectures/_catalogFrameworks/catalog-framework-intro.adoc, distribution/docs/src/main/resources/content/_architectures/_plugins/catalog-metrics-plugin.adoc, distribution/docs/src/main/resources/content/_developing/_devComponents/custom-sts-claims-handlers.adoc, distribution/docs/src/main/resources/content/_developing/_devComponents/managed-service-factories.adoc
Updates documentation to avoid having section headings with duplicate titles.
@codice/docs 
@ahoffer
@lessarderic
@mcalcote
@shaundmorris
review content updates
Section headers are automatically made into anchors for ease of linking. Duplicate anchors could cause a link to not point to the intended section of the documentation. …
=> DDF-2824 fix for duplicate anchors in documentation

ui/packages/catalog-ui-search/src/main/webapp/component/query-add/query-add.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/query-adhoc/query-adhoc.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/query-advanced/query-advanced.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/query-basic/query-basic.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/query-editor/query-editor.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/query-settings/query-settings.view.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/location/base.line.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/utils/validation/index.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/utils/validation/validation.tsx
Rebased @hayleynorton 's PR: 
https://github.com/codice/ddf/pull/5636
__________________
ABBREVIATED REVIEW
Link to original PR: #5594
~~Note: only review the last commit; this PR is built off #5609~~ #5609 has been merged, so only one commit in this PR
This PR provides the user with an error message containing guidance for the correct geo string format and prevents the search from being run or saved until corrected. It also changes the value passed to the buffer input to a string to prevent a large console error due to prop types not matching.
@andrewzimmer
@zta6
@codice/ui
@bdeining
@Bdthomson
Open the dev …
=> DDF-5593 prevent a query from running when geo string is in wrong format

ui/packages/catalog-ui-search/src/main/webapp/component/query-advanced/query-advanced.view.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/filter/filter.js
Sorts dropdowns containing facet attributes alphabetically, rather than by their count. 
@bennuttle 
@nsuvarna 
@lavoywj 
@leo-sakh 
@bdeining 
@samuelechu 
@bdeining 
@codice/ui 
@jrnorth
Full build, and check that any faceted attributes are sorted alphabetically
Fixes: #5711  …
=> [2.19.x] DDF-5711 Sort Facet Dropdown Results

catalog/plugin/catalog-plugin-facet-attribute-access/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/plugin/catalog-plugin-facet-attribute-access/src/main/resources/OSGI-INF/metatype/metatype.xml, catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.xml, distribution/docs/src/main/resources/content/_reference/_tables/catalog.ui.adoc, ui/packages/catalog-ui-search/src/main/webapp/component/query-basic/query-basic.view.js
Use a faceted query on the configured `Basic Search Match Type Attribute` to determine the options presented in the basic search form's `Match Types` dropdown.
@willwill96 
@aj-brooks 
@bennuttle 
@leo-sakh 
@nsuvarna 
@lavoywj 
@BernardIgiri 
@codice/ui 
@djblue
1. Ingest a large number of metacards.
2. In the `Catalog UI Search` config, set `Basic Search Match Type Metacard Attribute` to any attribute present on your metacards. Make sure to add the attribute to the `Facet Attribute Whitelist`.
3. In Intrigue, open the basic search form. Under `Match Types`, click `Specific` then open the dropdown and verify the options are all valid values of the specified attribute that appear in the metacards you ingested. Also verify the options are sorted in case-insensitive …
=> [2.19.x] DDF-5724 G-2115 Fill the match types dropdown with known values of the basic search match type attribute

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/security/app/UserApplication.java, platform/persistence/platform-persistence-core-api/src/main/java/org/codice/ddf/persistence/PersistentStore.java, ui/packages/catalog-ui-search/src/main/webapp/component/alert-item/alert-item.hbs, ui/packages/catalog-ui-search/src/main/webapp/component/alert-item/alert-item.less, ui/packages/catalog-ui-search/src/main/webapp/component/alert-item/alert-item.view.js
This is a 2.19.x backport of #5735. It enables scheduled query notifications to display an accurate count of the number of results it received, and notifies the user if they were truncated. 
@nsuvarna 
@bennuttle 
@lavoywj 
@leo-sakh 
@jrnorth 
@bdeining 
@codice/solr 
@codice/ui 
@bdeining
@jrnorth
See testing instructions in #5735 
Fixes: #5734, G-3176 …
=> [2.19.x] DDF-5374 Allow notifications to specify the number of results they found

catalog/plugin/catalog-plugin-facet-attribute-access/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/plugin/catalog-plugin-facet-attribute-access/src/main/resources/OSGI-INF/metatype/metatype.xml, catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.xml, distribution/docs/src/main/resources/content/_reference/_tables/catalog.ui.adoc, ui/packages/catalog-ui-search/src/main/webapp/component/query-basic/query-basic.view.js
Use a faceted query on the configured `Basic Search Match Type Attribute` to determine the options presented in the basic search form's `Match Types` dropdown.
@willwill96 
@aj-brooks 
@bennuttle 
@leo-sakh 
@nsuvarna 
@lavoywj 
@BernardIgiri 
@codice/ui 
@djblue
@andrewkfiedler  
1. Ingest a large number of metacards.
2. In the `Catalog UI Search` config, set `Basic Search Match Type Metacard Attribute` to any attribute present on your metacards. Make sure to add the attribute to the `Facet Attribute Whitelist`.
3. In Intrigue, open the basic search form. Under `Match Types`, click `Specific` then open the dropdown and verify the options are all valid values of the specified attribute that appear in the metacards you ingested. Also verify the options are sorted in case-insensitive …
=> DDF-5724 G-2115 Fill the match types dropdown with known values of the basic search match type attribute

catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/data/impl/AttributeImpl.java, catalog/plugin/catalog-plugin-metacard-validation/src/main/java/ddf/catalog/metacard/validation/MetacardValidityMarkerPlugin.java, catalog/plugin/catalog-plugin-metacard-validation/src/test/java/ddf/catalog/metacard/validation/MetacardValidityMarkerPluginTest.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/associations/Associated.java, catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/util/EndpointUtilTest.java
Makes `AttributeImpl`'s multi-value constructor accept lists of any type that implements `Serializable`. This will allow developers to write code like the following:
```java
List<String> values = ...
Attribute attribute = new AttributeImpl("myAttribute", values);
```
@leo-sakh 
@bennuttle 
@nsuvarna 
@aj-brooks 
@lavoywj 
@rzwiefel 
@Lambeaux 
Full build.
Fixes: #5542 …
=> DDF-5542 Make AttributeImpl accept lists of any type that implements Serializable

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/security/app/UserApplication.java, platform/persistence/platform-persistence-core-api/src/main/java/org/codice/ddf/persistence/PersistentStore.java, ui/packages/catalog-ui-search/src/main/webapp/component/alert-item/alert-item.hbs, ui/packages/catalog-ui-search/src/main/webapp/component/alert-item/alert-item.less, ui/packages/catalog-ui-search/src/main/webapp/component/alert-item/alert-item.view.js
Checks for a count property on an alert. If it exists and is greater than negative 1, it will use that property instead of count the number of associated metacards. If `count` is more than 1000, it will tell the user their results have been truncated. 
Also, it enables deleting from the `result-cache` core. 
@nsuvarna 
@bennuttle 
@lavoywj 
@jrnorth 
@leo-sakh 
@jrnorth
Ensure notifications work in DDF as expected. DDF does not specify the count property, so this should not affect how scheduled queries behave. 
1. Build DDF and install the standard profile
2. Ingest some data, and scheduled a query one it
3. Check that you can view the results of the query
4. Verify that you can delete the query
Fixes: #5734 
G-3176 …
=> DDF-5734 Allow notifications to specify the number of results they found

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/suggestion/UtmUpsCoordinateProcessor.java, catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/query/suggestion/UtmUpsCoordinateProcessorTest.java
When a user enters a UTM coordinate in the gazetteer search box with no latitude band, `N` is used as the default. This behavior makes is appear as if we support specifying the Northern or Southern hemisphere in place of the latitude band since the gazetteer correctly pans to the Northern hemisphere point. However, this is only a side-effect of how we are parsing the coordinates. In reality, `N` does not directly correspond to the Northern hemisphere. Instead, if the latitude band does not actually correspond with the northing value, then the invalid latitude band is used to *indirectly* determine which hemisphere to use with C-M latitude bands corresponding to the Southern hemisphere and N-X latitude bands corresponding the the Northern hemisphere. As a result, the default behavior of …
=> DDF-5716 G-7628 Add support for specifying UTM coords with the hemisphere notation in the gazetteer 

ui/packages/catalog-ui-search/src/main/webapp/component/singletons/metacard-definitions.js
Fixed Result Forms from hiding temporal attributes.  
@cassandrabailey293 @andrewzimmer 
@bdthomson
Build / Install / Verify that temporal attributes are present in the result forms dropdown and verify basic search forms still work as expected.
Fixes: #____ …
=> [2.19.x] Fixed Result Forms from hiding temporal attributes

ui/packages/catalog-ui-search/src/main/webapp/component/singletons/metacard-definitions.js
Fixed Result Forms from hiding temporal attributes.  
@cassandrabailey293 @andrewzimmer 
@bdthomson
Build / Install / Verify that temporal attributes are present in the result forms dropdown and verify basic search forms still work as expected.
Fixes: #____ …
=> Fixed Result Forms from hiding temporal attributes

catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/validation/impl/report/AttributeValidationReportImpl.java, catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/MigrateCommand.java, catalog/core/catalog-core-eventcommands/src/main/java/org/codice/ddf/catalog/pubsub/command/DeleteCommand.java, catalog/core/catalog-core-impl/filter-proxy/src/main/java/ddf/catalog/filter/proxy/adapter/GeotoolsFilterAdapterImpl.java, catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/SolrFilterDelegate.java, catalog/core/catalog-core-validator/src/main/java/ddf/catalog/validation/impl/ReportingMetacardValidatorImpl.java, catalog/core/catalog-core-validator/src/main/java/ddf/catalog/validation/impl/validator/RequiredAttributesMetacardValidator.java, catalog/security/catalog-security-filter/src/main/java/ddf/catalog/security/filter/plugin/FilterPlugin.java, catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/transformer/TransformerManager.java, catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java, catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswQueryFactory.java, catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/transformer/GmdTransformer.java, catalog/spatial/wfs/1.0.0/spatial-wfs-v1_0_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v1_0_0/catalog/source/WfsResponseExceptionMapper.java, catalog/transformer/catalog-transformer-pdf/src/main/java/ddf/catalog/transformer/input/pdf/GeoPdfParserImpl.java, catalog/transformer/catalog-transformer-xml/src/main/java/ddf/catalog/transformer/xml/MetacardMarshallerImpl.java, platform/landing-page/src/main/java/org/codice/ddf/landing/LandingPage.java, platform/metrics/platform-metrics-reporting/src/main/java/ddf/metrics/reporting/internal/rrd4j/RrdMetricsRetriever.java, platform/security/certificate/security-certificate-keystoreeditor/src/main/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditor.java, platform/security/expansion/security-expansion-impl/src/main/java/ddf/security/expansion/impl/AbstractExpansion.java, platform/security/rest/security-rest-cxfwrapper/src/main/java/org/codice/ddf/cxf/paos/PaosOutInterceptor.java
This PR aims to fix issues from SonarQube rule [Collection.isEmpty() should be used to test for emptiness](https://rules.sonarsource.com/java/RSPEC-1155)
SonarQube states that calling `Collection.isEmpty()` is:
- more readable than `Collection.size()`
- can be more performant
- some Collections implementation have a cost of O(n) when calling `size()`
Sorry, I don't know who I should tag.
I asked whether PRs tackling SonarQube issues were welcome on [google groups](https://groups.google.com/forum/?fromgroups#!topic/ddf-developers/Ovdj2lohGow).
For Jira:
For GH Issues:
Fixes: #4909 (partially) …
=> DDF-04909 Replacing calls to Collection.size() with Collection.isEmpty()

ui/packages/catalog-ui-search/src/main/webapp/component/query-advanced/query-advanced.view.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/filter/filter.js
Sorts dropdowns containing facet attributes alphabetically, rather than by their count.
@nsuvarna 
@bennuttle 
@lavoywj 
@AzGoalie 
@leo-sakh 
@codice/ui 
@jrnorth 
@bdeining 
Full build, and check that all faceted attributes in a query dropdown are sorted alphabetically
Forwardport of: https://github.com/codice/ddf/pull/5712
Fixes: #5711 …
=> DDF-5711 Sort dropdown attributes

ui/packages/catalog-ui-search/src/main/webapp/react-component/location/base.line.js
Link to 2.19.x PR: https://github.com/codice/ddf/pull/5611 
___________________________________________________
Converts WKT strings to the correct format automatically instead of relying on error messages to inform the user of the correct format and making them convert it themselves.
@zta6 @cassandrabailey293 
@codice/ui 
@bdeining
@Bdthomson 
Copy and paste WKT strings into the Polygon and Line geo filter fields. Verify that they're being immediately converted into the correct format, the shapes are still showing up on the map and you can successfully execute the search without any error messages.
Note about multipolygons: each polygon in a multipolygon must have at least 4 coordinate pairs (first and last should be the same). Test with multipolygons where at least one polygon isn't …
=> DDF-5610 Automatically convert WKT strings into the correct format

ui/packages/catalog-ui-search/src/main/webapp/react-component/location/base.line.js
Adds support for negative values when automatically converting WKT strings to the correct format in search geos
@bdeining
@Bdthomson 
Copy and paste WKT strings with negative coordinate values into the Polygon and Line geo filter fields. Verify that they're being immediately converted into the correct format.
Example polygon: 
`POLYGON ((-45.69035002266293 -20.676851, -45.6903113 20.6255905, 45.623261 -20.625589597640413, 45.623261 20.676851, 45.69035002266293 20.676851))`
Example line:
`LINESTRING (45.4806 20.644323,45.620127 20.727819)`
- ✏️ (Pencil) …
=> [2.19.x] DDF-5610 Added support for negative coordinate values in WKT conversion

ui/packages/catalog-ui-search/src/main/webapp/js/controllers/ol.layerCollection.controller.js
Includes credentials for WMTS GetCapabilities requests on the 2D map when `withCredentials` is enabled for the layer.
@leo-sakh 
@bennuttle 
@lavoywj 
@aj-brooks 
@nsuvarna 
@AzGoalie 
@codice/ogc 
@codice/ui 
@bdeining
@djblue
Create a WMTS layer with the URL https://mrdata.usgs.gov/mapcache/wmts?SERVICE=WMTS&REQUEST=GetCapabilities.
The layer configuration should look like the following:
```javascript
{
"matrixSet": "WGS84",
"parameters": {
"transparent": false,
"format": ""
},
"name": "sgmc",
"order": 0,
"url": "https://mrdata.usgs.gov/mapcache/wmts?SERVICE=WMTS&REQUEST=GetCapabilities",
"layer": "sgmc",
"proxyEnabled": false,
"tileHeight": 256,
"withCredentials": true,
"format": "image/jpeg",
"tileWidth": 256,
"type": "WMT",
"show": true,
"alpha": 1
}
```
Open Intrigue then open your …
=> [2.19.x] DDF-5771 Include credentials for WMTS GetCapabilities requests on the 2D map

catalog/catalog-app/pom.xml, catalog/catalog-app/src/main/resources/features.xml, catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/validation/impl/violation/QueryValidationViolationImpl.java, catalog/core/catalog-core-api/src/main/java/ddf/catalog/validation/QueryValidator.java, catalog/core/catalog-core-api/src/main/java/ddf/catalog/validation/violation/QueryValidationViolation.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/QueryApplication.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/validate/CqlRequestParser.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/validate/CqlValidationHandler.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/validate/QueryValidators.java, catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/query/validate/CqlValidationHandlerTest.java, catalog/ui/search-ui-app/src/main/resources/etc/IntrigueBundle.properties, catalog/validator/catalog-validator-unsupportedattributes/pom.xml, catalog/validator/catalog-validator-unsupportedattributes/src/main/java/org/codice/ddf/validator/query/unsupportedattributes/AttributeExtractor.java, catalog/validator/catalog-validator-unsupportedattributes/src/main/java/org/codice/ddf/validator/query/unsupportedattributes/MessageFormatSupplier.java, catalog/validator/catalog-validator-unsupportedattributes/src/main/java/org/codice/ddf/validator/query/unsupportedattributes/UnsupportedAttributeQueryValidator.java, catalog/validator/catalog-validator-unsupportedattributes/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/validator/catalog-validator-unsupportedattributes/src/test/java/org/codice/ddf/validator/query/unsupportedattributes/AttributeExtractorTest.java, catalog/validator/catalog-validator-unsupportedattributes/src/test/java/org/codice/ddf/validator/query/unsupportedattributes/UnsupportedAttributeQueryValidatorTest.java, catalog/validator/pom.xml, distribution/ddf-common/src/main/resources/security/default.policy
Adds a new framework for validating queries **before they are ran**. The idea is that as a user creates/modifies a query in the UI, it will be sent to the backend for validation in real-time.
It works by exposing a new `cql/validator/:id` POST endpoint that accepts a CQL query body just like the `/cql` endpoint. The `:id` parameter is the id of the validator that you want to run. The response contains a set of validation warnings or errors.
New validators are added by implementing the `QueryValidator` interface. Currently, the only validator in the system is the `UnsupportedAttributesQueryValidator` with id `unsupportedAttribute`. This validator aggregates all instances of the `SourceAttributeRestriction` interface and uses them to determine if there are any attributes in the query that …
=> [2.19.x] DDF-5627 G-7443 Add an endpoint to validate different aspects of a query

catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsFilterDelegate.java, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsSource.java, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/resources/OSGI-INF/metatype/metatype.xml, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsFilterDelegateTest.java, catalog/spatial/wfs/spatial-wfs-common/src/main/java/org/codice/ddf/spatial/ogc/wfs/catalog/common/WfsConstants.java
Allows the WFS 1.1.0 source to customize the `wildCard`, `singleChar`, and `escapeChar` characters used for `PropertyIsLike` queries.
@leo-sakh 
@bennuttle 
@lavoywj 
@nsuvarna 
@aj-brooks 
@AzGoalie 
@codice/ogc 
@bdeining
@millerw8
1. Create a WFS 1.1.0 source with the URL http://services.azgs.az.gov/ArcGIS/services/aasggeothermal/CAWellLogs/MapServer/WFSServer
2. Change the `Wildcard Character`, `Single-Character Wildcard Character`, and `Escape Character` from their default values.
3. `log:set info org.apache.cxf` (so you can see the outgoing WFS queries)
4. Open Intrigue and run some queries using the wildcard character `*`, the single-character wildcard character `?` and the escape character `\` (these are the special characters Intrigue understands and will be translated to the …
=> [2.19.x] DDF-5674 G-5334 Enable PropertyIsLike special character customization for the WFS 1.1.0 source

catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsFilterDelegate.java, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsSource.java, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/resources/OSGI-INF/metatype/metatype.xml, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsFilterDelegateTest.java, catalog/spatial/wfs/spatial-wfs-common/src/main/java/org/codice/ddf/spatial/ogc/wfs/catalog/common/WfsConstants.java
Allows the WFS 1.1.0 source to customize the `wildCard`, `singleChar`, and `escapeChar` characters used for `PropertyIsLike` queries.
@leo-sakh 
@bennuttle 
@lavoywj 
@nsuvarna 
@aj-brooks 
@AzGoalie 
@codice/ogc 
@bdeining
@millerw8
1. Create a WFS 1.1.0 source with the URL http://services.azgs.az.gov/ArcGIS/services/aasggeothermal/CAWellLogs/MapServer/WFSServer
2. Change the `Wildcard Character`, `Single-Character Wildcard Character`, and `Escape Character` from their default values.
3. `log:set info org.apache.cxf` (so you can see the outgoing WFS queries)
4. Open Intrigue and run some queries using the wildcard character `*`, the single-character wildcard character `?` and the escape character `\` (these are the special characters Intrigue understands and will be translated to the …
=> DDF-5674 G-5334 Enable PropertyIsLike special character customization for the WFS 1.1.0 source

ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-old.js
Before, a console error was making it so that each number had to be typed twice in order for it to show up in the field when manually inputting USNG coordinates for a bounding box. This PR fixes that
@bdeining 
@shaundmorris
Create an advanced search with an anyGeo Bounding Box filter. Switch to USNG/MGRS coordinates and try to manually input a value number-by-number (i.e. 22R CA 75963 20865). Verify that you don't have to enter each number twice in order for it to show up in the field
Fixes: codice/ddf-ui#73 …
=> [2.19.x] DDF-73 Fixed having to type numbers in twice when manually inputting USNG coordinates for bounding box

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/config/ConfigurationApplication.java, catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.xml, catalog/ui/search-ui-app/src/main/resources/etc/org.codice.ddf.catalog.ui.config, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/cesium/map.cesium.js, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/geometry.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/map.model.js, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/openlayers/map.openlayers.js
Backport of #5638 and #5768 
Adds an option and input field to the Search UI preferences to enable "custom text notation". Custom text notation allows for a user to enter a metacard attribute to display as a text label next to metacard map markers in Intrigue. title is the default attribute used.
@aaronilovici 
@mdang8 
@codice/ui 
@vinamartin 
1. Open the Admin console and navigate to `Search UI -> Configuration -> Catalog UI Search`
2. Scroll down to `Show Custom Text Notations` and click the checkbox to enable it
3. Ingest some metacards in Intrigue, ensuring there are metacards that overlap with different titles
4. Open the 2D map and run a * search
5. Verify the metacard map markers have a label next to each one and that there are no overlapping …
=> [2.21.x] DDF-5572 Render map marker labels with custom text notation on 2D and 3D maps

catalog/core/catalog-core-solrcommands/pom.xml, catalog/core/catalog-core-solrcommands/src/main/java/org/codice/ddf/commands/solr/ReindexCommand.java, catalog/core/catalog-core-solrcommands/src/main/java/org/codice/ddf/commands/solr/SolrCommands.java, catalog/core/catalog-core-solrcommands/src/test/java/org/codice/ddf/commands/solr/ReindexCommandTest.java
karaf command to initiate a reindex of record.
criteria can be specified for which segment of the data to be reindexed
A threadpool is established to query and reingest all the records. 
Reindex query data from the given specified collection and always ingest via the catalog framework which default to `catalog` collection
This uses the solr cloud setting provided in custom.system.properties file. 
@pklinef 
@pklinef
@millerw8 
@bdeining 
start solr cloud in distribution/docker/solrcloud
docker-compose up
run DDF
profile:install standard
`http://localhost:8994/solr/catalog/select?fl=metacard.modified_tdt&q=*:*`
note the metacard.modified_tdt
reindex -c catalog -a 2019-11-01T00:00:00Z 
verify metacard.modified_tdt has been updated to now
Fixes: #5546 ____
- [ x] Update / Add Unit Tests …
=> DDF-5546 karaf reindex command

ui/packages/catalog-ui-search/src/main/webapp/component/result-form/result-forms.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/search-form-interactions/search-form-interactions.less, ui/packages/catalog-ui-search/src/main/webapp/component/search-form/search-form.view.js
Hides result form actions (vertical ellipsis) when no actions are present
re adds edit as a result form action
@zta6 @hayleynorton @cassandrabailey293 
@codice/ui
@bdeining
@bdthomson
- ingest system search form, verify there are no actions available
- verify edit action is available for editable result forms
Fixes: #5815  …
=> [2.19.x] DDF-5815 fix result form action dropdown

ui/packages/catalog-ui-search/src/main/webapp/js/cql.js
Fixes a parsing error that occurs when running relative time queries that are not wrapped in parentheses. Wrapping does not appear to be necessary: https://docs.geoserver.org/latest/en/user/filter/ecql_reference.html#filter-ecql-reference
DDF UI master pr: https://github.com/codice/ddf-ui/pull/94
@aj-brooks 
@bennuttle 
@AzGoalie 
@lavoywj 
@leo-sakh 
@codice/ui 
@bdeining
@millerw8
Run a relative time query and ensure it works.
Fixes: https://github.com/codice/ddf-ui/issues/92 …
=> [2.19.x] DDF-92 Fix parsing of relative time queries

distribution/test/itests/test-itests-ddf-core/pom.xml, distribution/test/itests/test-itests-ddf/pom.xml
…. this was causing `mvn clean` to download a large number of dependencies
fixes #4883 
@ahoffer 
@bdeining 
@codice/build 
@AzGoalie
@bdeining
`mvn clean`
`mvn clean install` ensure solr is stopped after execution
it may be worth trying `mvn install` and `mvn clean install` with a running solr to see how it breaks
Fixes: #____ …
=> DDF-4883 removes ensure-solr-is-stopped executions

catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/DynamicSchemaResolver.java, catalog/solr/catalog-solr-provider/pom.xml, catalog/solr/catalog-solr-provider/src/main/java/ddf/catalog/solr/provider/InjectedAttributeListener.java, catalog/solr/catalog-solr-provider/src/main/resources/OSGI-INF/blueprint/blueprint.xml
PR #5536 improved the DynamicSchemaResolver so that it pre-populates its cache with all metacard types. However, if an attribute was injected into a metacard type the DynamicSchemaResolver would fail if that injected attribute was queried on.  This PR adds a listener for InjectableAttributes and adds them to the DynamicSchemaResolver.
@pklinef
@rzwiefel
@glenhein 
@codice/solr
@jlcsmith
The original problem can be reproduced by first installing a master build. Add a json definition file to `etc/definitions` that will inject an attribute into any/all metacard types (e.g. `ext.alt-source`).  Then, using the karaf console, run `catalog:search --cql '"ext.alt-source" IS NULL'`. You should see an exception in the logs with the message `Anonymous Field Property does not exist. …
=> DDF-5538 - Add InjectedAttributes to DynamicSchemaResolver field cache

catalog/core/catalog-core-api/pom.xml, catalog/core/catalog-core-api/src/main/java/ddf/catalog/plugin/OAuthPluginException.java, catalog/core/catalog-core-urlresourcereader/pom.xml, catalog/core/catalog-core-urlresourcereader/src/main/java/ddf/catalog/resource/impl/URLResourceReader.java, catalog/core/catalog-core-urlresourcereader/src/test/java/ddf/catalog/resource/impl/URLResourceReaderTest.java, catalog/opensearch/catalog-opensearch-source/src/main/java/org/codice/ddf/opensearch/source/OpenSearchSource.java, catalog/plugin/catalog-plugin-oauth/src/main/java/org/codice/ddf/catalog/plugin/oauth/OAuthPlugin.java, catalog/plugin/catalog-plugin-oauth/src/test/java/org/codice/ddf/catalog/plugin/oauth/OAuthPluginTest.java, catalog/rest/catalog-rest-endpoint/pom.xml, catalog/rest/catalog-rest-endpoint/src/main/java/org/codice/ddf/endpoints/rest/RESTEndpoint.java, catalog/rest/catalog-rest-service/pom.xml, catalog/rest/catalog-rest-service/src/main/java/org/codice/ddf/rest/service/AbstractCatalogService.java, catalog/spatial/csw/spatial-csw-source-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/AbstractCswSource.java, platform/security/rest/security-rest-clientapi/src/main/java/org/codice/ddf/cxf/client/SecureCxfClientFactory.java, platform/security/rest/security-rest-cxfwrapper/src/main/java/org/codice/ddf/cxf/client/impl/SecureCxfClientFactoryImpl.java, platform/security/rest/security-rest-cxfwrapper/src/main/java/org/codice/ddf/cxf/oauth/OAuthOutInterceptor.java, platform/security/rest/security-rest-cxfwrapper/src/main/java/org/codice/ddf/cxf/oauth/OAuthSecurityImpl.java
Needs: https://github.com/codice/ddf-ui/pull/83
Adds the ability to go through OAuth to download a resource.
@SmithJosh @bakejeyner 
@stustison
- Verify downloading a resource from an OAuth protected source works. Download using
- the download button
- the inspector tab
- the action tab
- Delete the user's tokens and try downloading a resource (should be prompted to log in).
- Verify querying with OAuth still works
#5360  …
=> DDF-5360 Adds the ability to go through OAuth to download a resource

catalog/core/catalog-core-definitionparser/src/main/java/ddf/catalog/definition/impl/DefinitionParser.java, catalog/core/catalog-core-definitionparser/src/test/groovy/ddf/catalog/definition/impl/DefinitionParserSpec.groovy, distribution/docs/src/main/resources/content/_developing/_devComponents/json-definition-files.adoc, distribution/docs/src/main/resources/content/_developing/_devComponents/metacard-type.adoc, distribution/docs/src/main/resources/content/_developing/_devComponents/metacard-validators.adoc
* Fixes the `DefinitionParser` so that the required attributes metacard validators it generates have the correct metacard type names.
* Re-adds the metacard validators section to the JSON definition file section of the documentation.
@bennuttle 
@leo-sakh 
@nsuvarna 
@aj-brooks 
@lavoywj 
@bdeining
@rzwiefel
1. Create a definition JSON file containing a `requiredattributes` validator in the `metacardvalidators` section.
2. Drop the file into `etc/definitions`.
3. Ingest an _invalid_ metacard of the type the validator is configured for (i.e. the metacard should be missing at least one of the attributes required by the validator).
4. Verify the metacard is marked as invalid and that the validation errors say it is missing required attributes.
Fixes: #5757
Please see …
=> DDF-5757 Fix the DefinitionParser-generated required attributes metacard validators

ui/packages/catalog-ui-search/src/main/webapp/component/announcement/actions.js, ui/packages/catalog-ui-search/src/main/webapp/component/content/content.js, ui/packages/catalog-ui-search/src/main/webapp/component/location-new/geo-components/coordinates.js, ui/packages/catalog-ui-search/src/main/webapp/component/location-new/inputs/masked-text-field.js, ui/packages/catalog-ui-search/src/main/webapp/component/location-new/models/usng-model.js, ui/packages/catalog-ui-search/src/main/webapp/component/location-new/utils/dms-utils.js, ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-old.js, ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-old.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-serialization.js, ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-serialization.spec.js, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/openlayers/map.openlayers.js, ui/packages/catalog-ui-search/src/main/webapp/js/CQLUtils.js, ui/packages/catalog-ui-search/src/main/webapp/js/CQLUtils.spec.js, ui/packages/catalog-ui-search/src/main/webapp/js/DistanceUtils.js, ui/packages/catalog-ui-search/src/main/webapp/js/widgets/cesium.line.js, ui/packages/catalog-ui-search/src/main/webapp/js/widgets/cesium.polygon.js, ui/packages/catalog-ui-search/src/main/webapp/js/widgets/openlayers.line.js, ui/packages/catalog-ui-search/src/main/webapp/js/widgets/openlayers.polygon.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/filter/filter-input/filter-location-input.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/location/base.line.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/location/bounding-box.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/location/gazetteer.spec.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/location/keyword.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/location/keyword.spec.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/location/location.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/location/point-radius.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/utils/validation/index.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/utils/validation/validation.tsx, ui/packages/catalog-ui-search/src/main/webapp/test/mock-api/config.json
This PR improves the validation/error handling/error displaying for anyGeo searches - specifically Line, Point-Radius, and Bounding Box.
For details on how the behavior has changed, please see this document:
[UX-changes_updated.pdf](https://github.com/codice/ddf/files/4246059/UX-changes_2_24.pdf)
It also refactors the way in which the state is set when values are changed by the user, and eliminates the `cursor` function from `location.js` entirely. This refactor involved moving the error components and their validation into each separate component (pulling shared logic into the `validation.tsx` file) rather than using the cursor function and the `LocationInput` component for most of the error handling. Generic validation logic that existed in `base.line.js` and 'location.js' were moved …
=> [2.19.x] DDF-5793 anyGeo search validation refactor and UX improvements

Jenkinsfile, pom.xml
Removes `mvn install` from the Sonar Cloud stage, mainly leaving `sonar:sonar`
@TonyMorrison 
@LinkMJB 
@codice/build 
@bdeining 
@oconnormi
Sonar cloud runs at least 30 minutes faster
Fixes: #5596 
- ❗ …
=> DDF-5596 removed mvn install from Sonarcloud command

ui/packages/catalog-ui-search/src/main/webapp/component/query-basic/query-basic.view.js
Fixes issue with basic search form when there are no facets
Build / Install / Configure the Catalog UI to use a facet that will return nothing and verify one can still issue a query from the basic search form
Fixes: #____ …
=> [2.19.x] DDF-5724 G-2115 fixes issue with basic search form when there are no facets

ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/cesium/map.cesium.js, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/map.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/openlayers/map.openlayers.js, ui/packages/catalog-ui-search/src/main/webapp/js/controllers/cesium.layerCollection.controller.js, ui/packages/catalog-ui-search/src/main/webapp/js/controllers/ol.layerCollection.controller.js, ui/packages/catalog-ui-search/src/main/webapp/plugins/map.view.tsx
Adds ability to extend map (Cesium and OpenLayers) config functionality by downstream projects via 'plugin'
@nsuvarna
@bennuttle 
@aj-brooks 
@AzGoalie 
@rymach 
@lavoywj 
@codice/ui 
@AzGoalie
@bdeining
Interact with both 2D and 3D maps in the UI to verify no regressions have been introduced.
Fixes: #5829
=> [2.19.x] DDF-5829: Added plugin support to map.view; fixed OpenLayers minZoom

ui/packages/catalog-ui-search/src/main/webapp/component/result-form/result-form.view.js
Selects the first attribute as the default when creating a new result form. 
@bennuttle 
@leo-sakh 
@nsuvarna 
@lavoywj 
@AzGoalie 
@maryformanek 
@codice/ui 
@lambeaux
1. Start DDF, and install the standard profile
2. Create a new result form. Check that there is an attribute selected by default
3. Check that you can change the attribute, and successfully save the form.
Fixes: #https://github.com/codice/ddf-ui/issues/96 …
=> [2.19.x] DDF-96 Start with default value in result forms

ui/packages/catalog-ui-search/src/main/webapp/component/filter-builder/filter-builder.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/filter/filter.collection.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/filter/filter.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/query-advanced/query-advanced.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/query-settings/query-settings.view.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/filter/filter-attribute.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/filter/filter.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/inputs/enum-input/enum-input.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/menu/index.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/menu/menu.tsx
Disables attributes from the dropdown when a source with supportedAttributes is selected. Display a warning below the dropdown that the currently selected attribute is not available to be selected in the dropdown
@codice/ui 
TBD
TBD
These changes were done in catalog-ui-search which is now removed from master a forward port to ddf-ui will be necessary
Fixes: #____
TBD …
=> [2.19.x] Disable attributes that are not supported by selected sources

catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/DumpCommand.java, catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/ExportCommand.java, catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/IngestCommand.java
fixes commands that use Security interface
anyone
Ensure catalog commands that use security work (eg, ingest)
`@Reference` fields are not actually injected until _after_ object construction , so attempting to use them in the constructor means they will be null still. You must use them after object is init'ed.
Fixes: #5893 …
=> DDF-5893 Fixes commands attempting to use references in their constructor

ui/packages/catalog-ui-search/src/main/webapp/component/metacard-overwrite/metacard-overwrite.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/tabs/metacard/tabs-metacard.js
Port of https://github.com/codice/ddf-ui/pull/91
Updates metacard overwrite to use selection interface, allowing this to be reused downstream or in other routes
@willwill96 @Bdthomson @andrewkfiedler 
Test metacard overwrite, see that it still works as expected 
Fixes: #5881  …
=> [2.20.x] Use SelectionInterface in metacardOverwrite

Jenkinsfile
Prevents the entire build from being failed if the SonarCloud is the only stage failing since the the actual build and deploy would have already completed
@shaundmorris 
@bdeining 
created a test on Jenkins which I forced an error trapped by the catchError and the subsequent stage completed successfully as well as the entire build (as desired)
http://jenkins.phx.connexta.com/service/jenkins/job/W.I.P./job/DDF/job/master/3/
Fixes: ___ …
=> BR-101 Add error trapping for SonarCloud stage

platform/security/handler/security-handler-api/src/main/java/org/codice/ddf/security/handler/api/OidcHandlerConfiguration.java, platform/security/handler/security-handler-oidc/src/main/java/org/codice/ddf/security/handler/oidc/OidcHandlerConfigurationImpl.java, platform/security/handler/security-handler-oidc/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/security/handler/security-handler-oidc/src/main/resources/OSGI-INF/metatype/metatype.xml, platform/security/realm/security-realm-oidc/src/main/java/org/codice/ddf/security/oidc/realm/OidcRealm.java, platform/security/security-oidc-bundle/pom.xml, platform/security/security-oidc-bundle/src/main/java/org/codice/ddf/security/oidc/resolver/OidcCredentialsResolver.java
Make the OIDC token server connect and read timeouts admin configurable. A downstream project is operating in an environment where the default timeouts were too short.
The connect and read timeouts are configured separately. But let me know if it would be preferred to have a single "network timeout" that is used for both connecting and reading.
There is a static method (getOidcTokens) that is being used by downstream projects. In order to not break those projects, I left a deprecated version of the method that uses the original timeout values. 
@rzwiefel 
@pklinef 
@codice/ui (because ddf-ui uses the deprecrated method)
@jrnorth
@bdthomson
I don't have a good way to simulate the slow network environment from the downstream project. My idea is to set a breakpoint in …
=> DDF-5849 make oidc token server connect and read timeouts configurable

catalog/core/catalog-core-versioning/versioning-api/src/main/java/ddf/catalog/core/versioning/DeletedMetacard.java, catalog/core/catalog-core-versioning/versioning-common/src/main/java/ddf/catalog/core/versioning/impl/DeletedMetacardImpl.java, catalog/core/catalog-core-versioning/versioning-common/src/test/groovy/ddf/catalog/core/versioning/impl/DeletedMetacardImplSpec.groovy
- You can now search for deleted metacards original tags by querying the field
Ensure nothing breaks, ensure you can query on DeletedMetacards original tags field `metacard.deleted.tags`
- This is functionality that its sibling class (MetacardVersionImpl) has but this class never got for some reason. So this is something that probably should have been there but wasn't before. No hard schema changes so upgrade can be done with no migrations to continue working. 
Fixes: #5875 
- only adding additional metadata about what the original metacard was (eg, a workspace) no resource metadata is exposed. …
=> DDF-5875 Adds original tags to DeletedMetacard

ui/packages/catalog-ui-search/src/main/webapp/component/property/property.js
Fixes the `isBlank()` method in `property.js` to correctly check for empty numeric fields.
Fixes: #____
=> [2.19.x] DDF-5902 G8098 UI Property fails when checking numeric fields

platform/security/handler/security-handler-api/src/main/java/org/codice/ddf/security/handler/api/OidcHandlerConfiguration.java, platform/security/handler/security-handler-oidc/src/main/java/org/codice/ddf/security/handler/oidc/OidcHandlerConfigurationImpl.java, platform/security/handler/security-handler-oidc/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/security/handler/security-handler-oidc/src/main/resources/OSGI-INF/metatype/metatype.xml, platform/security/security-oidc-realm/src/main/java/org/codice/ddf/security/oidc/realm/OidcCredentialsResolver.java, platform/security/security-oidc-realm/src/main/java/org/codice/ddf/security/oidc/realm/OidcRealm.java
Abbreviated review of https://github.com/codice/ddf/pull/5858
Make the OIDC token server connect and read timeouts admin configurable. A downstream project is operating in an environment where the default timeouts were too short.
The connect and read timeouts are configured separately. But let me know if it would be preferred to have a single "network timeout" that is used for both connecting and reading.
There is a static method (getOidcTokens) that is being used by downstream projects. In order to not break those projects, I left a deprecated version of the method that uses the original timeout values. 
@rzwiefel 
@pklinef 
@codice/ui (because ddf-ui uses the deprecrated method)
@jrnorth
@bdthomson
I don't have a good way to simulate the slow network environment from …
=> [2.20.x] DDF-5849 make oidc token server connect and read timeouts configurable

catalog/security/catalog-security-policyplugin/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/security/catalog-security-policyplugin/src/main/resources/OSGI-INF/metatype/metatype.xml, catalog/security/catalog-security-resourceplugin/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/security/catalog-security-resourceplugin/src/main/resources/OSGI-INF/metatype/metatype.xml, catalog/spatial/registry/registry-policy-plugin/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/spatial/registry/registry-policy-plugin/src/main/resources/OSGI-INF/metatype/metatype.xml, platform/security/pep/security-pep-interceptor/src/main/java/ddf/security/pep/interceptor/PEPAuthorizingInterceptor.java, platform/security/pep/security-pep-interceptor/src/test/java/ddf/security/pep/interceptor/PepInterceptorActionsTest.java, platform/security/pep/security-pep-interceptor/src/test/java/ddf/security/pep/interceptor/PepInterceptorValidSubjectTest.java
This PR removes the requirement for a guest user to be able to do CRUD operations, as well as changes to the PEPAuthInterceptor that allow for SessionToken creation for requests that do not have an authentication token.
@rfding 
@mdang8 
@clockard
@stustison
Fixes: #____ …
=> [2.21.x] Update policies and interceptors

ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/geometry.view.js, ui/packages/catalog-ui-search/src/main/webapp/js/widgets/openlayers.line.js, ui/packages/catalog-ui-search/src/main/webapp/js/widgets/openlayers.polygon.js
Before, if you drew a geometry over the anti-meridian (180 degrees longitude) on the 2D map, the query would return the correct results (within the originally drawn geometry) but the map would show a geometry that would fit within the constraints of the map (see "before" gifs below). This did not happen on the 3D map.
Also, results whose location geometries were over the anti-meridian would render within the constraints of the map as well.
@codice/ui 
@bdeining 
@millerw8
See gifs below, verify you see the behavior from the "after" gif for drawn geometries
For result geometries, edit the location attribute with WKTs that cross the antimeridian. Verify that they rendering correctly on the 2D map
Fixes: #codice/ddf-ui#111
G-1595
Bounding Box before …
=> [2.19.x] DDF-UI-111 Fixed drawn geometries and result geometries over anti-meridian

catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/DynamicSchemaResolver.java, catalog/solr/catalog-solr-provider/pom.xml, catalog/solr/catalog-solr-provider/src/main/java/ddf/catalog/solr/provider/InjectedAttributeListener.java, catalog/solr/catalog-solr-provider/src/main/resources/OSGI-INF/blueprint/blueprint.xml
ABBREVIATED REVIEW 
Back port PR for DDF-5538 into 2.20.x
Original PR: #5807 
@glenhein 
@rzwiefel 
@pklinef 
@codice/solr 
@jlcsmith 
The original problem can be reproduced by first installing a master build. Add a json definition file to `etc/definitions` that will inject an attribute into any/all metacard types (e.g. `ext.alt-source`). Then, using the karaf console, run `catalog:search --cql '"ext.alt-source" IS NULL'`. You should see an exception in the logs with the message `Anonymous Field Property does not exist. ext.alt-source`.
With this PR, you should no longer see the exception.
This is affecting downstream projects. Part of the issue was solved with #5536
This was fixed in the master branch but needs to be back ported to 2.20.x
Fixes: #5538 
Please see [Notes …
=> [2.20.x] DDF-5538 - Add InjectedAttributes to DynamicSchemaResolver field cache

catalog/opensearch/catalog-opensearch-source/src/main/java/org/codice/ddf/opensearch/source/OpenSearchFilterVisitor.java
Backend portion of the 2.23.x Forward-port of https://github.com/codice/ddf/pull/5889
_____________________________________________________________________
Allows a line to have a zero-buffer. Solves https://github.com/codice/ddf-ui/issues/112
@codice/ui 
@bdeining 
- Advanced search - anyGeo
- Select Line
- Draw a line and verify that it doesn't automatically change the buffer width to 1
- Verify that you can search with nothing (and/or 0) in the buffer width input, and that the outgoing cql uses INTERSECTS instead of DWITHIN
- Verify that searching with a buffer width greater than 1 meter is allowed and that the outgoing cql uses DWITHIN
- Verify that searching with a buffer width of greater than 0 but less than 1 meter displays an inline error message …
=> [2.23.x] DDF-UI-112 allow intersects query for line

ui/packages/catalog-ui-search/src/main/webapp/component/query-basic/query-basic.view.js
Clears drawings from a basic location search when toggling from "Somewhere Specific" to "Anywhere" location filters.
@jordanwilking @andrewkfiedler @jlcsmith @vinamartin 
@vinamartin
On the Basic Search menu, click the "Somewhere Specific" location filter. 
Draw any geo on a map visual.
Switch back to the "Anywhere" filter. The drawing should be cleared.
Fixes: #5909 
After toggling back to "Anywhere" …
=> [2.20.x] DDF-5909 Clear geo search drawing correctly when using query-basic form

catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/SolrMetacardClientImpl.java
Fixes the bug where enabling spellcheck causes a NullPointerException due to missing spellcheck response in the modified query.
@bellcc 
@pklinef 
@codice/solr 
@jlcsmith 
1. After full build and install, enable spellcheck in the admin console
2. Build the spellcheck dictionary index in Solr
3. Upload some data
4. Create a search that enables spellcheck and search for an incorrectly spelled word
5. Assuming the misspelled word provides a spellcheck hit:
a) In the logs, there should no longer be a NullPointerException
b) The "Did you mean" and "Showing results for" capability on the UI will be populated
Fixes: #5907  …
=> [2.20.x] DDF-5907 - Fix Spellcheck Showing Results For capability

platform/persistence/platform-persistence-commands/src/main/java/org/codice/ddf/persistence/commands/AbstractStoreCommand.java, platform/persistence/platform-persistence-core-api/src/main/java/org/codice/ddf/persistence/PersistentStore.java
Addressing issue https://github.com/codice/ddf/issues/5924
This persistence type check is a self inflicting restriction. The PersistentStoreImpl allows any type to establish a new solr core/collection.
For import, if persistence core is not found, create a new core and store result
For export, if persistence core is not found, return empty result
able to import/export any persistence core
@millerw8 
@bdeining 
@codice/solr 
build profile:install standard
store:list -t metacard_cache
results found: xx (before this PR, this will fail)
store:list -t alerts
result found: xx
store:list -t abc
results found: 0
Fixes: #____ …
=> DDF-5924 remove persistence type enforcement

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/MetacardApplication.java, ui/packages/catalog-ui-search/src/main/webapp/component/annotation/annotation.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/editor/editor.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/search-form/search-form.js, ui/packages/catalog-ui-search/src/main/webapp/component/tabs/search-form/tabs.search-form.js, ui/packages/catalog-ui-search/src/main/webapp/js/ApplicationStart.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/sharing/presentation.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/utils/security/security.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/workspace-interactions/presentation.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/workspaces-items/container.tsx
Removes all hardcoded uses of email as the subject identity. Now Intrigue uses the attribute set in the Subject Identity configuration.
@stustison @brendan-hofmann @beyelerb 
1. Create two non-admin accounts in DDF
2. Change the Subject Identity config in the Admin UI to use the `http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier` attribute instead of email.
3. Restart DDF
4. Verify the following:
* Metacard security attributes (the security.access-* attributes) use the name identifier instead of email.
* The workspaces page use the name identifier to indicate workspace ownership
* Workspace filtering works (Owned by Me, Not Owned by Me)
* Workspace sharing works
* Search form sharing works (top left hamburger > Search Forms)
* On load, Intrigue opens an existing …
=> [2.21.x] DDF-5946 Update Intrigue to respect Subject Identity configuration

catalog/core/catalog-core-versioning/versioning-common/src/main/java/ddf/catalog/core/versioning/impl/MetacardVersionImpl.java
Adds in a null check that breaks if a metacard isn't a resource (for example: it's a workspace)
@rzwiefel @andrewkfiedler 
Verify that reverting resource metacards still work.
Fixes: #5920  …
=> DDF-5920 Allows non-resource metacards to be restored

ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/openlayers/map.openlayers.js, ui/packages/catalog-ui-search/src/main/webapp/plugins/map.openlayers.js
This PR adds an `extension` argument to `OpenlayersMap` to allow for customization of how the 2D map pans to results. The `extension` argument is utilized in `panToExtent` if it exists and is a function. In the plugin, `null` is passed as the argument so that the `extent`, and therefore the way the 2D map pans to results is unaffected.
Thanks @leo-sakh for helping with this!
@andrewzimmer @cassandrabailey293 @leo-sakh @zta6 
@bdeining 
@millerw8 
@shaundmorris 
- Upload a couple images and edit their locations so that they're on the edges of the map (i.e. one in Russia, one in Alaska)
- Open the 2D map
- Select each result in the results panel and verify that the way the map pans to each result has not changed and that at no point does it pan off of the singular map image
Fixes: …
=> [2.19.x] DDF-UI-131 allow for customization of how 2D map pans to results

catalog/core/catalog-core-versioning/versioning-common/src/main/java/ddf/catalog/core/versioning/impl/MetacardVersionImpl.java
Backport of: https://github.com/codice/ddf/pull/5921
@andrewkfiedler @rzwiefel 
@jordanwilking @stevenmalmgren
=> [2.23.x] DDF-5920 Allows non-resource metacards to be restored

catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/SolrMetacardClientImpl.java
Fixes the bug where enabling spellcheck causes a NullPointerException due to missing spellcheck response in the modified query.
@cantstoptheunk
@bellcc
@pklinef
@codice/solr 
@jlcsmith
1. After full build and install, enable spellcheck in the admin console
2. Build the spellcheck dictionary index in Solr
3. Upload some data
4. Create a search that enables spellcheck and search for an incorrectly spelled word
5. Assuming the misspelled word provides a spellcheck hit:
a) In the logs, there should no longer be a NullPointerException 
b) The "Did you mean" and "Showing results for" capability on the UI will be populated
Fixes: #5907  …
=> DDF-5907 - Fix spellcheck Showing Results For

ui/packages/catalog-ui-search/src/main/webapp/js/model/List.js
Fixes an issue where federated source results do not show up in workspace lists. The problem is that a filter for the `metacard-tags` field is being added to the query to retrieve list items; this fails in federated sources that do not recognize this attribute.
@bennuttle 
@lavoywj 
@leo-sakh 
@frnkshin 
@codice/ui 
@bdeining
Verify that records can still be added and removed from lists
Fixes: https://github.com/codice/ddf-ui/issues/122 …
=> [2.19.x] DDF-UI-122 Fixing add to list for federated sources

platform/security/core/security-core-impl/src/main/java/ddf/security/impl/SubjectUtils.java, platform/security/servlet/security-servlet-whoami/src/main/java/org/codice/ddf/security/servlet/whoami/WhoAmI.java
The whoami endpoint grabs the attributes off of an assertion similar to how the `SubjectUtils` class does it. [The `SubjectUtils` class was updated with null checking](https://github.com/codice/ddf/pull/5161), so this logic should be updated as well (or else null pointers can happen when attempting to access the whoami endpoint).
@blen-desta 
@stustison 
1. Build, run, and install DDF with debugging enabled.
2. Put a breakpoint at line 114 of `WhoAmI.java`.
3. Log into DDF and attempt to access `<fqdn>/whoami`.
4. (Feel free to message me about clarifying this one) Modify the assertion object so on of its attributes contains a list containing only `null`.
5. Step over line 114. It should not error out. …
=> DDF-5212 Add null checking to whoami endpoint

catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/SolrFilterDelegate.java, catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/provider/SolrProviderQuery.java
Adds support to query quoted phrases with Solr.  See #5962 for more details.
@bellcc 
@derekwilhelm 
@codice/solr 
@Bdthomson 
@rzwiefel
Ingest a record with a field that contains spaces and/or punctuation. If you had a title like `This is the title`, you should be able to search on title and anyText and match with `"is the"`, `"*the title"`, and `"This is*"`.
Fixes: #5962 …
=> DDF-5962 Support querying quoted phrases with Solr

Jenkinsfile, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/forms/data/QueryTemplateMetacard.java, ui/packages/catalog-ui-search/src/main/webapp/component/query-add/query-add.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/query-editor/query-editor.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/query-settings/query-settings.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/search-form-interactions/search-form-interactions.less, ui/packages/catalog-ui-search/src/main/webapp/component/search-form-interactions/search-form-interactions.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/search-form/search-form.view.js, ui/packages/catalog-ui-search/src/main/webapp/js/model/QuerySettings.js
Adds the ability to set a default result form. 
Setting a result form as default means that it will show up automatically in these cases:
1. When you create a basic or advanced search in your workspace
2. When you create a new search form in the search form editor
If you set a result form to default, but you already have a default search form that does not have that result form, you will NOT see the default result form when you search. You will see the result form associated with your default search form. 
@andrewzimmer @hayleynorton @zta6 
@codice/ui 
1. build/profile install
2. create two result forms if you don't already have them
3. Verify that the dropdown has the "Set Default" option
4. Set one as the default
5. Verify that the result form you set as default appears in the basic and …
=> [2.19.x] DDF-UI-145 default result form

ui/packages/catalog-ui-search/src/main/webapp/react-component/filter/filter-input/filter-text-inputs/filter-text-input.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/filter/filter-input/filter-text-inputs/textFilterHelper.js
Fixes an error where if an 'is empty' search was run and then the search is edited such that the field is changed back to 'anytext' an error was thrown in the console and the field was deleted. 
@hayleynorton 
@andrewzimmer 
@codice/ui 
@bdeining
Build, profile install
Run an 'IS EMPTY' query for any attribute. 
Edit the search and change the query attribute to 'anyText' 
verify that there is no console error and that the 'anyText' field is not deleted from the query editor. 
Run a 'contains' query with any attribute and value. Edit the search to change the attribute
Verify that the query is still a 'contains' query and still has the same value as before. 
Fixes: #5988  …
=> [2.19.x] DDF-5988 Fix 'IS EMPTY' search error

platform/solr/solr-schema/src/main/resources/solr/conf/schema.xml
Running a DWITHIN query (i.e., a buffered geometry) near the antimeridian often results in a Solr error because the resulting geometry contains points outside the valid longitude range of [-180,180]. The SolrFilterDelegate uses JTS to calculate the buffered geometry but does not enforce the longitude range on the result so it is passed to Solr with out-of-range values. Enabling normWrapLongitude means that Solr will wrap longitudes outside of the range into it.
@codice/solr 
@bdthomson
@pklinef
1. Ingest the following GeoJSON files:
`alaska1.json`
```javascript
{
"type": "Feature",
"geometry": {
"type": "Point",
"coordinates": [179.980009, 51.602957]
},
"properties": {
"title": "Alaska 1"
}
}
```
`alaska2.json`
```javascript
{
"type": "Feature",
"geometry": {
"type": "Point", …
```
=> Enable longitude wrapping on the indexed Solr geo field

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/MetacardApplication.java, platform/security/core/security-core-services/pom.xml, platform/security/core/security-core-services/src/main/java/ddf/security/impl/SubjectIdentityImpl.java, platform/security/core/security-core-services/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/security/core/security-core-services/src/test/java/ddf/security/impl/SubjectIdentityTest.java, platform/security/sts/security-sts-guestclaimshandler/pom.xml, platform/security/sts/security-sts-guestclaimshandler/src/main/java/org/codice/ddf/security/claims/guest/GuestClaimsConfig.java, platform/security/sts/security-sts-guestclaimshandler/src/main/java/org/codice/ddf/security/claims/guest/GuestClaimsHandler.java, platform/security/sts/security-sts-guestclaimshandler/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/security/sts/security-sts-guestclaimshandler/src/test/java/org/codice/ddf/security/claims/guest/GuestClaimsHandlerTest.java, ui/packages/catalog-ui-search/src/main/webapp/component/annotation/annotation.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/editor/editor.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/search-form/search-form.js, ui/packages/catalog-ui-search/src/main/webapp/component/tabs/search-form/tabs.search-form.js, ui/packages/catalog-ui-search/src/main/webapp/js/ApplicationStart.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/container/workspaces-items-container/workspaces-items-container.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/sharing/sharing.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/workspace-interactions/workspace-interactions.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/utils/security/security.tsx
Updates the UI to respect the Subject Identity configuration, rather than always using the email as the subject identity. It also updates the subject identity code to ignore guest claims if the user is logged in, so that they are not used as the subject identifier.
@stustison @bakejeyner @blen-desta @garrettfreibott 
1. Create two non-admin accounts in DDF
2. Change the Subject Identity config in the Admin UI to use the `http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier` attribute instead of email.
3. Restart DDF
4. Verify the following:
* Metacard security attributes (the security.access-* attributes) use the name identifier instead of email.
* The workspaces page use the name identifier to indicate workspace ownership
* Workspace filtering works (Owned by Me, Not …
=> [2.16.x] DDF-5946 Subject identity fix

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/SortedQueryMonitor.java, catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/cache/solr/impl/SortedQueryMonitorTest.java
Adds logic to send any source exceptions contained in processing details back to the client
@derekwilhelm 
@pklinef 
@glenhein 
Fixes: #____ …
=> DDF-5649 G-6176 routes exceptions back to client

platform/platform-paxweb-jettyconfig/pom.xml, platform/platform-paxweb-jettyconfig/src/main/java/org/codice/ddf/pax/web/jetty/ClientInfoFilter.java, platform/platform-paxweb-jettyconfig/src/test/java/org/codice/ddf/pax/web/jetty/ClientInfoFilterTest.java
- Adds proxy forwarded information to the client-info property, which will expose this information to the catalog framework through request properties.
@figliold @mcalcote 
@figliold
@paouelle
1. Turn logging to DEBUG on `org.codice.ddf.pax.web.jetty`
2. Send CSW (or any other endpoint) containing with the new forwarded headers
3. Check logs for the map produced
This change will allow a source to be created which can decide which host to federate too based on the original host the request was sent to. …
=> [2.21.x] Add forwarded information to client-info

distribution/ddf-common/src/main/resources/etc/web-context-policy-config.properties, distribution/ddf-common/src/main/resources/security/default.policy, distribution/docs/src/main/resources/content/_developing/_devComponents/managed-service-factories.adoc, distribution/docs/src/main/resources/content/_managing/_configuring/configuring-oidc.adoc, distribution/docs/src/main/resources/content/_managing/_configuring/no-idp.adoc, distribution/docs/src/main/resources/content/_managing/_configuring/securing-admin-console.adoc, distribution/docs/src/main/resources/content/_managing/_configuring/securing-idp-sp.adoc, distribution/docs/src/main/resources/content/_managing/_configuring/web-context-policy-manager.adoc, distribution/docs/src/main/resources/content/_managing/_securing/disallowing-login-wo-certs.adoc, distribution/docs/src/main/resources/content/_managing/_securing/managing-crl.adoc, distribution/docs/src/main/resources/content/_reference/_tables/PolicyManager.adoc, distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/AbstractIntegrationTest.java, distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/security/SecurityPolicyConfigurator.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFederation.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestOidc.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestSecurity.java, platform/security/policy/security-policy-context/pom.xml, platform/security/policy/security-policy-context/src/main/java/org/codice/ddf/security/policy/context/impl/PolicyManager.java, platform/security/policy/security-policy-context/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/security/policy/security-policy-context/src/main/resources/OSGI-INF/metatype/metatype.xml, platform/security/policy/security-policy-context/src/test/java/org/codice/ddf/security/policy/context/PolicyManagerTest.java, platform/security/policy/security-policy-context/src/test/resources/web-context-policy-config.properties
Simplifies the Web Context Policy Manager's authentication type configuration by:
- Removing the authentication type configuration per context
- Adding a single auth type config for all web pages  
- Adding another auth type config for all endpoints
- Keeping the option to configure multiple auth types per context as a file-based configuration
@bakejeyner
@ricklarsen 
@SmithJosh 
@stustison 
- Test that changes to the web and endpoint authentication types works as expected
- Test the current (soon to be old) was of configuring auth types is still supported and works
To see how to do these and test the documentation see the docs on how to accomplish ☝️ 
Fixes: #5996  …
=> DDF-5996 Simplifies the Web Context Policy Manager's authentication type configuration

ui/packages/catalog-ui-search/src/main/webapp/component/query-settings/query-settings.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/result-form/result-form.collection.js, ui/packages/catalog-ui-search/src/main/webapp/component/result-form/result-form.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/table/row.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/table/table-viz.view.js
Fixes the following issues with result forms:
- Newly created result forms were not able to be used in queries until after a refresh.
- While editing existing forms, the attributes were not being populated correctly.
- The table visualization would throw an error if the `thumbnail` attribute was not included in the attributes of the result form
@brianfelix 
@Lambeaux 
@brhumphe 
@bdeining
1. Go to `Result Forms` page in Intrigue
2. Create a new result form
3. Navigate to the `Workspaces` page from the hamburger menu without refreshing the page
4. Create a new query and open the `Result Forms` dropdown
5. Notice the new result form is available in the list without a refresh
1. Go to `Result Forms` page in Intrigue
2. Create a new result form with some …
=> [2.19.x] DDF-6035 G-8076 Fix result forms

catalog/catalog-app/pom.xml, catalog/catalog-app/src/main/resources/features.xml, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/CachePutPlugin.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/CacheBulkProcessor.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/CacheCommitPhaser.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/CachingFederationStrategy.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/SolrCache.java, catalog/core/catalog-core-standardframework/src/main/resources/OSGI-INF/blueprint/fedstrategy.xml, catalog/core/catalog-core-standardframework/src/main/resources/OSGI-INF/blueprint/plugins.xml, catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/cache/solr/impl/CacheBulkProcessorTest.java, catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/cache/solr/impl/CachingFederationStrategyTest.java, catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/cache/solr/impl/SolrCacheTest.java, catalog/plugin/cache-plugin-defaultmetacardtags/pom.xml, catalog/plugin/cache-plugin-defaultmetacardtags/src/main/java/org/codice/ddf/cache/plugin/metacardtags/DefaultMetacardTagsPlugin.java, catalog/plugin/cache-plugin-defaultmetacardtags/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/plugin/cache-plugin-defaultmetacardtags/src/test/java/org/codice/ddf/cache/plugin/metacardtags/DefaultMetacardTagsPluginTest.java, catalog/plugin/pom.xml
Backport of https://github.com/codice/ddf/pull/5615/
Adds a CachePutPlugin and updates SolrCache to utilize the plugin. This plugin is called for every metacard being put into the solr cache. The plugin provides the opportunity to modify metacards before being put into the cache, or to indicate that the metacard should not be put into the cache.
This PR also provides an implementation of the CachePutPlugin that sets metacard tags attribute to "resource" if the metacard does not have a metacard tags.
@pklinef
@jlcsmith
@jrnorth
@codice/data
@codice/solr
@bdeining
@Bdthomson
Follow steps in original PR.
Fixes: #____ …
=> [2.20.x] DDF-5614 create CachePutPlugin interface and update SolrCache to call registered plugins

features/security/src/main/feature/feature.xml, platform/security/servlet/pom.xml, platform/security/servlet/security-servlet-web-socket/pom.xml, platform/security/servlet/security-servlet-web-socket/src/main/java/org/codice/ddf/security/servlet/web/socket/SecureWebSocketServlet.java, platform/security/servlet/security-servlet-web-socket/src/main/java/org/codice/ddf/security/servlet/web/socket/WebSocket.java, platform/security/servlet/security-servlet-web-socket/src/main/java/org/codice/ddf/security/servlet/web/socket/WebSocketAuthenticationException.java
[DDF-UI Pull Request](https://github.com/codice/ddf-ui/pull/219)
Moves the `SecureWebSocketServlet` into DDF and changes the way the web sockets checks to see if a user is logged in. The web sockets now store a reference to the http session (which contains the login information), and when that session is invalid it means the user has logged out.
@SmithJosh 
@blen-desta 
@stustison 
Feel free to contact me with any questions.
Setup:
1. Install the standard profile.
1. Build and install [this DDF-UI](https://github.com/codice/ddf-ui/pull/219). **Make sure that ddf.version in the DDF-UI root pom matches this version of DDF.**
Test w/ Basic:
1. Login to the admin console with basic credentials.
1. Navigate to `System -> Configuration -> Catalog UI Search` and check `Enable …
=> DDF-6049 Move SecureWebSocketServlet into DDF

catalog/security/catalog-security-logging/src/main/java/org/codice/ddf/catalog/security/logging/SecurityLoggingPlugin.java
@bakejeyner
@SmithJosh 
@stustison 
Fixes: #6074 …
=> DDF-6074 Fixes query request filters not showing up in the security audit log

catalog/security/catalog-security-logging/src/main/java/org/codice/ddf/catalog/security/logging/SecurityLoggingPlugin.java
@bakejeyner
@SmithJosh 
@stustison 
This branch will be compatible with `ddf-ui 3.5.x`
Fixes: #6074 …
=> [2.24.x] DDF-6074 Fixes query request filters not showing up in the security audit log

catalog/security/catalog-security-logging/src/main/java/org/codice/ddf/catalog/security/logging/SecurityLoggingPlugin.java
@bakejeyner
@SmithJosh 
@stustison 
This branch will be compatible with `ddf-ui 3.4.x`
Fixes: #6074 …
=> [2.23.x] DDF-6074 Fixes query request filters not showing up in the security audit log

catalog/security/catalog-security-logging/src/main/java/org/codice/ddf/catalog/security/logging/SecurityLoggingPlugin.java
@bakejeyner
@SmithJosh 
@stustison 
This branch will be compatible with `ddf-ui 3.1.x`
Fixes: #6074 …
=> [2.22.x] DDF-6074 Fixes query request filters not showing up in the security audit log

catalog/security/catalog-security-logging/src/main/java/org/codice/ddf/catalog/security/logging/SecurityLoggingPlugin.java
@bakejeyner
@SmithJosh 
@stustison 
This branch does not need ddf-ui
Fixes: #6074 …
=> [2.21.x] DDF-6074 Fixes query request filters not showing up in the security audit log

catalog/security/catalog-security-logging/src/main/java/org/codice/ddf/catalog/security/logging/SecurityLoggingPlugin.java
@bakejeyner
@SmithJosh 
@stustison 
This branch does not need ddf-ui
Fixes: #6074 …
=> [2.19.x] DDF-6074 Fixes query request filters not showing up in the security audit log

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/config/ConfigurationApplication.java, catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.xml, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/table/table-visibility.view.js, ui/packages/catalog-ui-search/src/main/webapp/js/model/User.js
This is the ddf part of the table column default.
Notes:
- Decided to make a new config, so there's no conflict with the results config.
- Had to add a way to determine whether the user had chosen to hide an attributes. An empty columnHide could mean that the user wants to see all attributes.
- Couldn't add the defaults directly to the user prefs, because we need to know what attributes are available before before we can negate them.
=> Add admin-configurable default table columns

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/CachingFederationStrategy.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/SortedQueryMonitor.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/QueryOperations.java, catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/cache/solr/impl/CachingFederationStrategyTest.java, catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/cache/solr/impl/SortedQueryMonitorTest.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/cql/Status.java, ui/packages/catalog-ui-search/src/main/webapp/component/dropdown/query-src/dropdown.query-src.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/query-status/query-status-row.hbs, ui/packages/catalog-ui-search/src/main/webapp/component/query-status/query-status-row.less, ui/packages/catalog-ui-search/src/main/webapp/js/model/Query.js, ui/packages/catalog-ui-search/src/main/webapp/js/model/QueryResponseSourceStatus.js
**Backend**
- Pass a synchronized hashmap for properties to the QueryResponse that accumulates results in the `OffsetResultHandler` so that they are not thrown away.
- Allow `PostFederatedQueryPlugin`s that were ran after a Source Error occured to still return an updated QueryResponse.
- Move the calculation/aggregation of hits per source, properties, and processing details to after any `PostFederatedQueryPlugin`s are ran so that even those ran after a Source Error are included.
- Pass `ProcessingDetails` from the `SourceResponse` to each invocation of a `PreFederatedQueryPlugin`.
- Remove where the ProcessingDetails from the `SourceResponse` were being copied into the final QueryResponse. This is done so that if you have a `PostFederatedQueryPlugin` that wants to mutate/remove any of …
=> [2.20.x-perf] DDF-6097 Update PreFederatedQueryPlugin logic to maintain context

catalog/security/catalog-security-logging/src/main/java/org/codice/ddf/catalog/security/logging/SecurityLoggingPlugin.java
@bakejeyner
@SmithJosh 
@stustison 
This branch does not need ddf-ui
Fixes: #6074 …
=> [2.20.x] DDF-6074 Fixes query request filters not showing up in the security audit log

ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/cesium/map.cesium.js, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/openlayers/map.openlayers.js, ui/packages/catalog-ui-search/src/main/webapp/js/model/MetacardProperties.js
___________
This PR explicitly passes the `'location'` attribute to the `getPoints` function when panning to a result on the 2D and 3D maps
@bdeining 
@shaundmorris 
Fixes: codice/ddf-ui#216
G-8307 …
=> [2.19.x] DDF-UI-216 G-8307 Pan explicitly to location attribute

ui/packages/catalog-ui-search/src/main/webapp/react-component/utils/validation/validation.tsx
________________________
This PR adds inline and pop-up error messages when there's a negative value in the buffer field for polygon and line geo searches
@bdeining 
@shaundmorris 
Enter a negative value in for buffer (both line and polygon) and verify that you see the inline error message pictured below (first screenshot) when you click out of the field. Also verify that if you try to execute the search, you see the pop-up error message pictured below (second screenshot) that prevents the search. Delete the negative buffer (or replace it with a valid value) and click out. Verify the inline message disappears and you are able to execute the search
Fixes: codice/ddf-ui#224
G-8398 …
=> [2.19.x] DDF-UI-224 G-8398 Added error messaging for negative buffer values

catalog/admin/module/catalog-admin-module-maplayers/src/main/java/org/codice/ddf/catalog/admin/plugin/MaplayersPlugin.java, distribution/docs/src/main/resources/content/_managing/_configuring/map-layers-intrigue.adoc
__________
This PR moves the Map Layers tab from the Catalog app into the Search UI app
@bdeining 
@millerw8
@shaundmorris
Open the admin console and verify that the Map Layers tab is under the Search UI app and not the Catalog app
Fixes: #6076
G-2260 …
=> [2.19.x] DDF-6076 G-2260 Moved Map Layers to Search UI app

catalog/admin/module/catalog-admin-module-maplayers/src/main/java/org/codice/ddf/catalog/admin/plugin/MaplayersPlugin.java
__________
This PR moves the Map Layers tab from the Catalog app into the Search UI app
@bdeining 
@millerw8
@shaundmorris
Open the admin console and verify that the Map Layers tab is under the Search UI app and not the Catalog app
Fixes: #6076
G-2260 …
=> [2.23.x] DDF-6076 G-2260 Moved Map Layers to Search UI app

catalog/admin/module/catalog-admin-module-maplayers/src/main/java/org/codice/ddf/catalog/admin/plugin/MaplayersPlugin.java
__________
This PR moves the Map Layers tab from the Catalog app into the Search UI app
@bdeining 
@millerw8
@shaundmorris
Open the admin console and verify that the Map Layers tab is under the Search UI app and not the Catalog app
Fixes: #6076
G-2260 …
=> DDF-6076 G-2260 moved Map Layers to Search UI app

catalog/core/catalog-core-api/src/main/java/ddf/catalog/Constants.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/AbstractDurableFileConsumer.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/AsyncFileAlterationObserver.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/ContentDirectoryMonitor.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/DurableFileAlterationListener.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/DurableFileEndpoint.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/DurableFileSystemFileConsumer.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/DurableWebDavFileConsumer.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/FileSystemPersistenceProvider.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/JsonPersistantStore.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/synchronizations/CompletionSynchronization.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/synchronizations/DeletionSynchronization.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/synchronizations/FileDeletionSynchronization.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/synchronizations/LoggingSynchronization.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/watcher/FileWatcher.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/watcher/FilesWatcher.java, distribution/ddf-common/src/main/resources/etc/log4j2.xml, distribution/ddf-common/src/main/resources/etc/org.ops4j.pax.logging.cfg, distribution/docs/src/main/resources/content/_managing/_configuring/content-directory-monitor.adoc
Improves logging in the **catalog-core-directorymonitor** bundle:
- CDM now has its own log in **data/logs**
- Concurrent set keeps track of files still being processed in **AsyncFileAlterationObserver**
- Additional Logging information in cdm classes
@mcalcote 
@aaronilovici 
@clockard
@paouelle
1. Pull and build this branch
2. Set up DDF with a normal profile and set cdmLogging to TRACE
3. Create a directory of files to use for the cdm. There should be 20 or more files in this directory. Duplicate all of the files to a subdirectory within the first directory.
3a. Add permissions for the directory in **security/configurations.policy**. Message me for details 
4. Set up a "Monitor in place" CDM in the admin console by going to **Catalog -> Configuration -> Catalog …
=> DDF-6408 Improve Logging for CDM 

catalog/core/catalog-core-api/src/main/java/ddf/catalog/Constants.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/AbstractDurableFileConsumer.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/AsyncFileAlterationObserver.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/ContentDirectoryMonitor.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/DurableFileAlterationListener.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/DurableFileEndpoint.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/DurableFileSystemFileConsumer.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/DurableWebDavFileConsumer.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/FileSystemPersistenceProvider.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/JsonPersistantStore.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/synchronizations/CompletionSynchronization.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/synchronizations/DeletionSynchronization.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/synchronizations/FileDeletionSynchronization.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/synchronizations/LoggingSynchronization.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/watcher/FileWatcher.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/watcher/FilesWatcher.java, distribution/ddf-common/src/main/resources/etc/log4j2.xml, distribution/ddf-common/src/main/resources/etc/org.ops4j.pax.logging.cfg, distribution/docs/src/main/resources/content/_managing/_configuring/content-directory-monitor.adoc
Improves logging in the **catalog-core-directorymonitor** bundle:
- CDM now has its own log in **data/logs**
- Concurrent set keeps track of files still being processed in **AsyncFileAlterationObserver**
- Additional Logging information in cdm classes
@mdang8  
@cjlange 
@clockard 
1. Pull and build this branch
2. Set up DDF with a normal profile and set cdmLogging to TRACE
3. Create a directory of files to use for the cdm. There should be 20 or more files in this directory. Duplicate all of the files to a subdirectory within the first directory.
3a. Add permissions for the directory in **security/configurations.policy**. Message me for details 
4. Set up a "Monitor in place" CDM in the admin console by going to **Catalog -> Configuration -> Catalog Content Directory …
=> DDF-6408 Improve Logging for CDM  [2.21.x]

ui/packages/catalog-ui-search/src/main/webapp/component/search-form-interactions/search-form-interactions.view.js
Form item dropdown switches order when form is made default
@andrewzimmer 
@hayleynorton
@bdeining
1. Click three-dot menu for search or result form
2. Notice that "Make Default Form" is first 
3. Select "Make Default Form"
4. Click the three-dot menu again
5. Ensure that "Clear Default Form" is the first item
codice/ddf-ui#242 …
=> [2.19.x] DDF-UI-242 Form item dropdown switches order when form is made default

ui/packages/catalog-ui-search/src/main/webapp/component/search-form-editor/search-form-editor.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/search-form/search-form.collection.view.js
1. When a user creates a search form, and there's already at least one search form in the list, the search form will show existing form twice, rather than the one you just provided in the editor. 
2. When a user makes a search form as default, it show a star icon on top right. When that form is edited and saved, the star icon is no longer displayed.
@andrewzimmer 
@hayleynorton
@zta6 
@bdeining
Issue 1 (Search form duplication):
1. Create a search form titled "test1" or other name
2. Create another search form titled "test 1" or other name
3. Save "test 1" and Ensure both "test1" and "test 1" are both displayed properly
4.Try to edit search field and make as default etc. and ensure only the one working with is effected and not both
Issue 2 (Make …
=> [2.19.x] DDF-UI-245 Search form duplication and Make Default star icon missing

ui/packages/catalog-ui-search/src/main/webapp/component/visualization/table/row.less
modifies row.less by changing white-space field of td to normal from nowrap
@leo-sakh  
@lavoywj  
@bennuttle  
@rymach  
@bdeining
@codice/ui 
@bdeining 
@rzwiefel
1. Search content stores
2. Go to table view of results
3. Look for text long enough to wrap around to a second line in it's cell
Issue discovered in a downstream project.
Fixes: [#DDF-6131](https://github.com/codice/ddf/issues/6131)
Before:
After:
- ❓ …
=> [2.19.x] DDF-6131 Change style to allow text wrapping

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/federation/impl/SortedFederationStrategy.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/federation/impl/SortedQueryMonitor.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/QueryOperations.java, catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/federation/impl/SortedQueryMonitorTest.java
Forward port of updates in 2.20.x (parts of https://github.com/codice/ddf/pull/6096 and parts of https://github.com/codice/ddf/pull/6103):
- Calculate startindex from statusBySource
- Allow PostFederatedQueryPlugins to return query responses
- Allow PostFederatedQueryPlugins to be ran on sources that are "unavailable"
- Fixes other issues with post federated
Fixes: #____ …
=> Update PreFederatedQueryPlugin logic to maintain context and post query plugins

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/federation/impl/SortedQueryMonitor.java, catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/federation/impl/SortedQueryMonitorTest.java
When sorting on an attribute where some of the results do not have that attribute it can cause issues with paging.  The reason is because the sorting mechanism in DDF for ascending sort order sorts nulls first.  Solr, on the other hand, always sorts nulls last regardless of the sort order.  Therefore, when paging through results if a result with a null attribute that is being sorted on shows up in a later page it will get sorted to the beginning of the list inside DDF and skipped in the returned result list.  This also has the effect of a result page containing a duplicate entry from the previous page.  This PR changes the DDF sort to match Solr where nulls are always last.
@pklinef 
@bdeining 
@codice/data  
@codice/solr 
@codice/ui 
@jlcsmith
1. Add a …
=> DDF-6146 - Change null sort to match solr

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/SortedQueryMonitor.java, catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/cache/solr/impl/SortedQueryMonitorTest.java, catalog/ui/catalog-ui-search/pom.xml
Back port of PR #6147 
When sorting on an attribute where some of the results do not have that attribute it can cause issues with paging. The reason is because the sorting mechanism in DDF for ascending sort order sorts nulls first. Solr, on the other hand, always sorts nulls last regardless of the sort order. Therefore, when paging through results if a result with a null attribute that is being sorted on shows up in a later page it will get sorted to the beginning of the list inside DDF and skipped in the returned result list. This also has the effect of a result page containing a duplicate entry from the previous page. This PR changes the DDF sort to match Solr where nulls are always last.
@pklinef
@bdeining
@codice/data
@codice/solr
@codice/ui …
=> [2.20.x] DDF-6146 - Change null sort to match solr

catalog/core/catalog-core-versioning/versioning-api/src/main/java/ddf/catalog/core/versioning/DeletedMetacard.java, catalog/core/catalog-core-versioning/versioning-common/src/main/java/ddf/catalog/core/versioning/impl/DeletedMetacardImpl.java
Stores the date that the metacard was deleted on deleted metacards.
@rececoffin 
@astagg 
@codice/data 
@jlcsmith 
@pklinef 
1. Create a metacard within DDF. 
2. Delete that metacard. 
3. Find that deleted metacard within solr. 
4. Verify that the deleted metacard contains the date it was deleted on. 
None
Fixes: #6058 
None …
=> DDF-6058 Store date that metacard was deleted

catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsSource.java, catalog/spatial/wfs/spatial-wfs-metacardtype-registry-api/src/main/java/org/codice/ddf/spatial/ogc/wfs/catalog/metacardtype/registry/WfsMetacardTypeRegistry.java, catalog/spatial/wfs/spatial-wfs-metacardtype-registry/src/main/java/org/codice/ddf/spatial/ogc/wfs/catalog/metacardtype/registry/impl/WfsMetacardTypeRegistryImpl.java, catalog/spatial/wfs/spatial-wfs-metacardtype-registry/src/test/java/org/codice/ddf/spatial/ogc/wfs/catalog/metacardtype/registry/impl/WfsMetacardTypeRegistryTest.java
Fixes the WFS 1.1.0 Source and Wfs Metacard Feature Type Registry to support multiple active sources.
Note - this does include an API change, but the API is marked experimental.
@jrnorth 
@bdeining 
@rzwiefel 
@jrnorth 
@bdeining 
@rzwiefel 
1. Configure 2 WFS 1.1.0 Federated Sources
2. Optional: disable the cache to eliminate this from the test (Catalog Federated Strategy -> Query Result Cache Strategy=None
3. Query both and verify results come back from each
4. Disable and then re-enable each source
5. Re-verify that a query against both sources work
Fixes: #6169 
- ✏️ …
=> DDF-6169 fixes support for multiple wfs 1.1.0 sources

ui/packages/catalog-ui-search/src/main/webapp/component/search-form-interactions/search-form-interactions.view.js
fixes error that occurs when deleting a default search form
@zta6 @hayleynorton @cassandrabailey293 @abel-connexta 
@bdeining
- build / run
- create new search from, set as default
- delete the form and verify no error is seen in the console
- create another search form and use it in a search
- delete the form and verify no error is seen in the console
Fixes: codice/ddf-ui#276 …
=> [2.19.x] DDF-UI-276 fix error when deleting a default search form

ui/packages/catalog-ui-search/src/main/webapp/component/golden-layout/golden-layout.less, ui/packages/catalog-ui-search/src/main/webapp/component/golden-layout/golden-layout.view.js
When changing theme setting 'Zoom Percentage' to a value greater than 100%, can no longer see some of the control tools, such as the horizontal scroll bar, the 'Add Visual' etc., unless page is refreshed after the theme is updated.
@andrewzimmer 
@hayleynorton
@zta6 
@bdeining
1. Go to Workspace
2. Create new workspace
3. Upload some content
4. Search for items
5. Add Visual (2D Map, Table etc.)
6. Click on the setting wheel and go to theme
7. Update Zoom Percentage and Spacing and ensure everything looks good and nothing is out of place. Ensure you don't lose the control tools such as the 'Add Visual Button', zoom in and out button in 2d map, the horizontal scroll bar in Table etc. 
**Note:** for 2D map the 'Add visual' button might be covering the …
=> [2.19.x] DDF-UI-262 Workspace loosing tools when Theme Zoom Percentage greater than 100%

ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-old.js
__________
This PR removes the condition that prevented the map state variables (those that update the map while drawing) from being set while in USNG/MGRS (it did not affect UTM/UPS because for some reason the `locationType` is changed from `utm` to `latlon` while drawing in UTM/UPS then switches back when drawing ends). This PR also removes an unused function.
@bdeining 
@shaundmorris 
Verify that the map changes _while drawing_ in USNG/MGRS like in the below gif 
Fixes: codice/ddf-ui#269
G-8544 …
=> [2.19.x] DDF-UI-269 G-8544 Update map for USNG shortest distance while drawing

ui/packages/catalog-ui-search/src/main/webapp/component/query-editor/query-editor.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/query-settings/query-settings.view.js
Fixes a bug where users were able to get select an invalid result form and get into a bad state if they did not explicitly click "Search" or "Save" before running an Advanced search.
@Lambeaux 
@brhumphe 
@brianfelix 
@bdeining
@millerw8
**NOTE: To fully test the fix, you should build the latest 2.19.x branch and run the PR fix along side it with the dev server (see testing instructions)**
1. Checkout the latest 2.19.x code WITHOUT THIS PR and build / start DDF
2. Open Intrigue
3. Create a new result form
4. Go to the workspaces page, create a new Advanced Search (all defaults are ok), and click "Search"
5. Re-open the query by clicking the Pencil icon and then click the Save icon to save the workspace
6. Refresh the page
7. Open the query one more time with the Pencil …
=> [2.19.x] G-8304 Fix intermediate result form dropdown state

ui/packages/catalog-ui-search/src/main/webapp/react-component/filter/filter-attribute.js
Uses attribute alias for the read-only filters when using a search form
@bdeining 
@shaundmorris 
Create a search form and create a query using that search form
Verify that the attribute aliases are displayed instead of the raw attribute names
Fixes: codice/ddf-ui#286
G-8697 …
=> [2.19.x] DDF-UI-286 G-8697 Utilized attribute alias in read-only filters

ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/map.view.js
UI failing to pan to initial result when 2D is Opened. Result must be selected before 2D map visual opened.
Expectation - 2D Map pan to selected result
Actual - 2D Map stays at home location
@andrewzimmer
@hayleynorton
@zta6
@bdeining
1. Upload items (Click on Navigation icon on upper left corner)
2. Open a new workspace and search for uploaded items
3. Add locations attributes to items, so that icon is displayed on 2D map.
a. Items can be added via the Inspector Visual. Example locations bellow:
i.  POLYGON ((32.896 -22.1266, 32.896 -34.8398, 16.458 -34.8398, 16.458 -22.1266, 32.896 -22.1266)))
ii. POLYGON ((137.1736 45.8825, 137.1736 45.7598, 136.9888 45.7598, 136.9888 45.8825, 137.1736 45.8825))
4. Close 2D Map, select an item and reopen 2D Map
5. …
=> [2.19.x] DDF-UI-283 UI failing to pan to initial result when 2D is Opened

ui/packages/catalog-ui-search/src/main/webapp/component/filter-builder/filter-builder.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/search-form-editor/search-form-editor.view.js
Allows creation of search forms to include all Boolean logical filters as the advanced query builder does.
@bennuttle 
@leo-sakh 
@jMoneee
@frnkshin 
1. Build / run DDF and install 
2. Navigate to search forms, create a new form, verify you can use all Boolean logical operators as expected, and form saves / can be used as expected
3. Try to create another search for that has invalid boolean logic (i.e. 'OR' with only one field, etc), verify error is caught and form isn't created
Fixes: #6183 
-See issue for before screenshot
-After: 
- ✏️ (Pencil) This comment is a nitpick or style suggestion, …
=> [2.19.x] DDF-6183  G-2068 Allow search forms to fully leverage boolean logic

ui/packages/catalog-ui-search/src/main/webapp/react-component/location/point-radius.js
____________
Changes the keys of utm/ups easting, northing, zone and hemisphere when calling validateGeo in point-radius in order to match the changes made in https://github.com/codice/ddf/pull/5958
@abel-connexta @andrewkfiedler @cassandrabailey293 @zta6 
@bdeining 
Verify that you can enter values into all fields under anyGeo > Point Radius > UTM/UPS
Fixes: codice/ddf-ui#287
G-8723
- ❓ (Question …
=> [2.19.x] DDF-UI-287 G-8723 Fixed point radius UTM/UPS error

distribution/docs/src/main/resources/content/_introduction/_coreConcepts/high-availability-supported-capabilities.adoc, distribution/docs/src/main/resources/content/_managing/_datamanagement/attributes-added-by-input-transformers.adoc, distribution/docs/src/main/resources/content/_reference/_appReferences/mg-spatial.adoc
removes unneeded references to Intrigue UI in the DDF documentation.
@codice/docs 
@ahoffer
@clockard
@mcalcote
@paouelle
@shaundmorris
@stustison
=> DDF-2749 removed references to intrigue from docs

ui/packages/catalog-ui-search/src/main/webapp/component/filter-builder/filter-builder.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-old.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/result-filter/result-filter.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/result-selector/result-selector.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/map.view.js, ui/packages/catalog-ui-search/src/main/webapp/js/filter.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/filter/filter-input/filter-location-input.js
Fixes bug where user is unable to access the result filter after saving an anygeo filter
fixes bug where keyword/bbox geos are converted to polygons when the user reopens the result filter
backport of https://github.com/codice/ddf/pull/5436
@hayleynorton @cassandrabailey293 @zta6 @abel-connexta 
@bdeining
- ingest records with location data or edit records to include a location
- search for all records
- use filter button to add an anygeo filter
- verify the results are filtered correclty and the result filter and be reopened and edited
- refreshed and verify user can edit
- save a keyword or bbox geometry filter, reopen and verify the value are as you enter them
- attempt to save an invalid geo and verify that its prevented 
codice/ddf-ui#294
G-8763 …
=> [2.19.x] DDF-UI-294 G-8763 G-8787 fix Unable to remove results filters

ui/packages/catalog-ui-search/src/main/webapp/js/model/Workspace.js
Addresses #6199 by adding a few calls to update the workspace's modified attribute when the workspace is modified.
@leo-sakh 
@frnkshin 
@lavoywj 
@jMoneee 
@bdeining 
@codice/ui 
See steps to reproduce in #6199 and verify the behavior is working as listed as expected there
Fixes: #6199 
See the before and after. Workspace 1 is edited but not saved in each image.
Before:
After: …
=> [2.19.x] DDF-6199 Update workspace's modified attribute prior to manual saving

distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/SystemStateManager.java
The `--cache` option was removed from the `catalog:removeall` command in https://github.com/codice/ddf/pull/6117, so the itests has been logging `Error resetting system` configuration errors. This PR removes that step in the itests.
@stustison @bakejeyner @blen-desta 
CI. No hero is needed.
The `solr:cache --clear -f` command could be used instead, but it looks like this step is unnecessary because the itests have been executing without it since https://github.com/codice/ddf/pull/6117 was merged.
https://github.com/codice/ddf/issues/6229
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Gui …
=> [2.25.x] DDF-6229 Remove clearCache in itests

platform/security/handler/security-handler-oidc/src/main/java/org/codice/ddf/security/handler/oidc/OidcHandlerConfigurationImpl.java
This warnings appear in the itests. It's misleading that it's logged at WARN because it's expected that OIDC isn't configured.
@blen-desta @bakejeyner @stustison
CI. No hero is needed.
https://github.com/codice/ddf/issues/6227 …
=> [2.25.x] DDF-6227 Update OidcHandlerConfiguration initialization failure logs from WARN to DEBUG

distribution/ddf-common/src/main/resources/security/default.policy, platform/parser/xml/src/main/java/org/codice/ddf/parser/xml/XmlParser.java
Addresses an `AccessControlException` in `XmlParser`, and cleans up the related permission
Note: might be easier to review if you ignore whitespace
@blen-desta @bakejeyner @stustison
Confirm that the `AccessControlException` no longer occurs in the downstream project itest. Ping me for testing instructions.
The XML input transformer is tested in itests, so there's no need to manually test that.
I don't know why this doesn't fail in DDF itests because there are itests that use the XML input transformer. I don't know how to reproduce this issue in DDF. 🤷
Fixes: https://github.com/codice/ddf/issues/6239
This is the `context` that was failing the permission check …
=> [2.25.x] DDF-6239 Wrap XmlParser marshall and unmarshall in doPrivileged blocks

ui/packages/catalog-ui-search/src/main/webapp/js/widgets/openlayers.bbox.js
3.4.x https://github.com/codice/ddf-ui/pull/320
master https://github.com/codice/ddf-ui/pull/321
___________________________________
Bounding boxes drawn over the anti-meridian were disappearing from the map because the call to `validateGeo` registers an error when the east/west values are outside of [-180, 180]. This PR moves `validateGeo` so that it's called before the anti-meridian adjustment of east/west values. This PR also explicitly removes bounding boxes from the map if any values are `NaN` or the south value is greater than or equal to the north value.
@bdeining
Verify that bounding boxes drawn over the anti-meridian do not disappear after drawing is complete
Fixes: G-8544 …
=> [2.19.x] G-8544 Fixed bounding box disappearing over anti-meridian

catalog/ui/search-ui/search-redirect/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/ui/search-ui/search-redirect/src/main/resources/OSGI-INF/metatype/metatype.xml, catalog/ui/search-ui/search-redirect/src/test/groovy/org/codice/ddf/ui/searchui/filter/RedirectServletSpec.groovy, distribution/ddf-common/src/main/resources-filtered/etc/application-definitions/search-ui.json, distribution/docs/src/main/resources/content/_reference/_tables/RedirectServlet.adoc
- Removes catalog-ui features from `etc/application-definitions/search-ui.json`
- Updates the default search redirect to `/search/simple`
master PR: https://github.com/codice/ddf/pull/6247
@garrettfreibott @blen-desta @bakejeyner @stustison 
catalog-ui was moved to it's own repo and is not included in DDF anymore. The only search ui that exists in DDF now is the Simple Search UI.
#6245 …
=> [2.25.x] DDF-6245 Remove catalog-ui features from etc/application-definitions/search-ui.json and update the default search redirect to /search/simple

ui/packages/catalog-ui-search/src/main/webapp/component/dropdown/hover-preview/dropdown.hover-preview.view.js, ui/packages/catalog-ui-search/src/main/webapp/plugins/dropdown.hover-preview.view.js
https://github.com/codice/ddf-ui/pull/300
https://github.com/codice/ddf-ui/pull/301
____________________
Adds a plugin for dropdown.hover-preview.view.js that wraps the `openThumbnailInNewWindow` function to allow for a different url to be opened in a new window
@codice/ui 
@bdeining 
@shaundmorris 
Upload a result that has a thumbnail and ensure that clicking on the thumbnail image opens a new window that displays the image (basically, verify no regression in this feature)
Fixes: codice/ddf-ui#299
G-8412
- ✏️ (Pencil) …
=> [2.19.x] DDF-UI-299 G-8412 Extended thumbnail onClick to allow for different url

catalog/ui/search-ui/search-redirect/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/ui/search-ui/search-redirect/src/main/resources/OSGI-INF/metatype/metatype.xml, catalog/ui/search-ui/search-redirect/src/test/groovy/org/codice/ddf/ui/searchui/filter/RedirectServletSpec.groovy, distribution/ddf-common/src/main/resources-filtered/etc/application-definitions/search-ui.json, distribution/docs/src/main/resources/content/_reference/_tables/RedirectServlet.adoc
- Removes catalog-ui features from `etc/application-definitions/search-ui.json`
- Updates the default search redirect to `/search/simple`
2.25.x PR: https://github.com/codice/ddf/pull/6246
@garrettfreibott @blen-desta @bakejeyner @stustison 
catalog-ui was moved to it's own repo and is not included in DDF anymore. The only search ui that exists in DDF now is the Simple Search UI.
Fixes: #6245 …
=> DDF-6245 Remove catalog-ui features from etc/application-definitions/search-ui.json and update the default search redirect to /search/simple

ui/packages/catalog-ui-search/src/main/webapp/component/filter-builder/filter-builder.view.js
Currently for search forms, only the `AND` & `NOT` operators have support implemented for them but `NOT AND` & `NOT OR` still show up as options in the selection dropdown, causing errors when trying to save forms that include those operators. This PR hides the operators that have no support implemented for them so they can't be selected for use on a search form.
@bennuttle @leo-sakh @jMoneee @frnkshin 
1. Build / run DDF, install profile, and navigate to Search Forms
2. Create a new search form, verify the filter options dropdown only includes `AND` & `OR` options
3. Navigate to Intrigue, create a new advanced query, verify the filter options dropdown includes `AND`, `OR`, `NOT AND`, &`NOT OR` options
Support for `NOT AND` / `NOT OR` in search forms could be implemented later on, this …
=> [2.19.x] DDF-6254 Hide filters in search forms with no support

platform/security/servlet/security-servlet-logout/pom.xml, platform/security/servlet/security-servlet-logout/src/main/java/org/codice/ddf/security/servlet/logout/LocalLogoutServlet.java, platform/security/servlet/security-servlet-logout/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/security/servlet/security-servlet-logout/src/test/java/org/codice/ddf/security/servlet/logout/LogoutServletTest.java, ui/packages/security-logout/src/main/webapp/js/main.js
Enables downstream projects to add a custom logout redirect url that users will be directed to upon logging out.
@brhumphe 
@Lambeaux 
@lambeaux
Since there is no way to configure the redirectUri in DDF, we just want to make sure nothing has changed regarding logout from a DDF perspective. Install DDF and logout to ensure logout directs users to the same logout page as before these changes were implemented.
Fixes: #6223
=> [2.19.x] DDF-6223 Added Logout Redirect

distribution/ddf-common/src/main/resources-filtered/etc/application-definitions/security-services.json
Moves the Guest Claims Configuration under the Security App
@bakejeyner
@emmberk
@stustison
Verify that the `Guest Claims Configuration` and `OIDC Configuration Settings` are under the Security App in the Admin UI
Fixes: #6277 
- ❗ …
=> DDF-6277 Moves the Guest Claims Configuration under the Security App

catalog/rest/catalog-rest-endpoint/pom.xml
Attempts to fixes a jacoco build failure (EOFException) in the catalog-rest-endpoint. This attempt is done by using a different jacoco.exec file for integration tests. Not sure if this is the best workaround so looking for feedback.
@TonyMorrison 
@LinkMJB 
@codice/build 
@codice/test 
Fixes: #____ …
=> Fix jacoco EOFException in catalog-rest-endpoint module

catalog/solr/catalog-solr-core/src/main/java/ddf/catalog/source/solr/SolrMetacardClientImpl.java, catalog/solr/catalog-solr-core/src/test/java/ddf/catalog/source/solr/SolrMetacardClientImplTest.java
- Allows the `solr.query.timeAllowed` system property to set a time
allowed to do a Solr query.  This is not a hard limit.
- Time allowed is not enabled by default.
@codice/solr 
- Install standard profile and ingest data
- `log:set DEBUG ddf.catalog.source.solr`
- Find (`list | grep -i provider`) and restart Solr provider bundle
- `search test` or other search terms for your data that have not been queried and cached yet
- Verify logs contain details about partial results being returned
```
15:28:44,012 | DEBUG | StrategyThread 1 | talog.source.solr.SolrMetacardClientImpl  334 | atalog-solr-provider | Found 0 partial results for query [ ( (point-of-contact_txt_tokenized:"test" ... location.crs-code_txt_tokenized:"test") AND metacard-tags_txt_tokenized:"resource" ) ] that took 8ms.
```
- …
=> Make Solr query time allowed configurable

platform/security/handler/security-handler-oidc/src/main/java/org/codice/ddf/security/handler/oidc/OidcLogoutActionProvider.java, platform/security/handler/security-handler-oidc/src/test/java/org/codice/ddf/security/handler/oidc/OidcLogoutActionProviderTest.java
Fixes the OIDC logout action provider so it process the prevurl query parameter in the Referer header correctly.
@blen-desta @bakejeyner @emmberk @garrettfreibott @stustison 
Tagging @jlcsmith for visibility
The easy way:
1. Install DDF and configure OIDC authentication (https://octoconsulting.atlassian.net/wiki/spaces/DDF/pages/702939155/Connect+Keycloak+to+DDF+using+OIDC may help)
2. Sign in to an OIDC-protected web context
3. Browse to `https://localhost:8993/logout?service=https%3A%2F%2Flocalhost%3A8993%2Fsearch%2Fsimple`
4. Click the "sign in again" link on the logout landing page. Verify you can sign back in as you would expect (no 404 response)
The hard way:
1. Install DDF, and install [Intrigue](https://github.com/codice/ddf-ui/) on top of it.
2. Configure OIDC …
=> [2.25.x] DDF-6308 Fix handling of encoded urls in OIDC logout action provider

features/utilities/src/main/feature/feature.xml, platform/mime/core/platform-mime-core-configurableresolver/pom.xml, platform/mime/core/platform-mime-core-configurableresolver/src/main/resources/default-mimetype-csv.config
Adds CSV mime type mapping to account for cases where CSV files come across with application/octet-stream
@a-asaad @jordanwilking 
@bdeining
The mime type issue is relegated to only certain Windows clients without Excel installed.  Likely difficult to test in a dev env.  Recommend successful CI being sufficient.
Fixes: #____ …
=> DDF-6329 adds csv mime type mapping

ui/packages/catalog-ui-search/src/main/webapp/react-component/workspace-interactions/container.tsx
Makes 'run all searches' interaction open the workspace when used from the 'workspaces' page
Makes 'run all searches' open the first query in the workspace and display it's results
@codice/ui 
@andrewzimmer 
@hayleynorton 
@bdeining
Ingest some data so that you will get search results
Create a workspace with multiple queries, a single query, and no queries. 
From the workspaces page click the ellipsis on the workspace with multiple queries
Click 'run all searches' in the dropdown
Verify: 
The workspace opens
The first query in the workspace is selected and its results are shown
Upon selecting the other queries in the workspace their results are already loaded
Repeat for the workspace with a single query
Repeat for the workspace with no …
=> [2.19.x] G-8998 Run all searches not working

catalog/solr/catalog-solr-core/src/main/java/ddf/catalog/source/solr/DynamicSchemaResolver.java, catalog/solr/catalog-solr-core/src/test/java/ddf/catalog/source/solr/SolrProviderTest.java, catalog/solr/catalog-solr-core/src/test/java/ddf/catalog/source/solr/provider/SolrProviderSorting.java, distribution/ddf-common/src/main/resources-filtered/etc/custom.system.properties, platform/solr/solr-schema/src/main/resources/solr/conf/schema.xml
Creates a new copy field in the solr schema to allow for case-insensitive text field sorting.  Also adds a configuration item to allow the sorting to be reverted to the existing, case-sensitive sorting.
@pklinef 
@bdeining
@codice/solr 
@jlcsmith
1. Perform a full build
2. Install DDF and DDF-UI
3. Upload/ingest several documents with sortable names
- For example: apple.txt, apricot.txt, banana.txt, blackberry.txt, blueberry.txt, broccoli.txt, carrot.txt, cherry.txt, tangerine.txt
4. Edit some of the titles in the metacards to contain uppercase letters
- For example: Apricot.txt, Broccoli.txt, Cherry.txt, Tangerine.txt
5. Set the page size in the search settings to 5
6. In the karaf console, ensure that the `solr.query.sort.caseInsensitive` property is set to `true`
- To …
=> DDF-6319 - Enable case-insensitive sorting of solr text fields

platform/solr/solr-factory-impl/pom.xml, platform/solr/solr-factory-impl/src/main/java/org/codice/solr/factory/impl/Configsets.java, platform/solr/solr-factory-impl/src/test/java/org/codice/solr/factory/impl/ConfigsetsTest.java
Previously when specifying config in etc/solr/conf you had to supply every file or solr would error out when using the partial config. The behavior now supplies any files that were not included for you automatically. 
still to do:
@codice/solr 
@pklinef 
@lamhuy 
<ol>
<li>Build and unzip the distribution -- <b>do not start it yet</b> </li>
<li>Remove all data from solr by navigating to <code>distribution/docker/solrcloud</code> and performing the steps in the readme</li>
<li>
<table>
<tr>
<td style="vertical-align:bottom"> navigate to  <code>&lt;ddf_home&gt;/etc/solr/solrconfig</code>. You will see two folders, <code>default</code> and <code>catalog</code>.</td>
<td><img src="https://user-images.githubusercontent.com/9013416/90187331-7490a900-dd6e-11ea-8efb-7ddd4ad853b4.png" …
=> Makes solr config auto include required files if not specified

Jenkinsfile
Reverts the skipITs introduced due to failing Integration tests
@shaundmorris 
@bdeining 
@LinkMJB 
@codice/build 
Fixes: BR-102 Revert skipIT changes to DDF …
=> BR-102 Revert skipIT changes to DDF

ui/packages/catalog-ui-search/src/main/webapp/behaviors/selection.behavior.js, ui/packages/catalog-ui-search/src/main/webapp/component/result-selector/result-selector.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/selection-checkbox/item-checkbox.tsx, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/table/tbody.view.js
_______________________
Allows the user to select multiple results using the checkbox without holding down the Ctrl button in both the results list and the table view. 
@codice/ui 
@bdeining 
Upload multiple results (3 or more)
Verify that you're able to select multiple results via checkboxes without holding down the Ctrl button in the results list
Do the same as above in the table view
Fixes: G-8889 …
=> [2.19.x] G-8889 Allow multi-select without holding down Ctrl button

ui/packages/catalog-ui-search/src/main/webapp/react-component/filter/filter-input/filter-location-input.js
non polygon geometries were failing to show up in search form editor after creation. Only an issue if the user creates the search form then opens it without refreshing
@cassandrabailey293 @hayleynorton @zta6 @abel-connexta 
@bdeining
- navigate to search forms page and create a new form with a bbox geo 
- without refreshing open the newly created search form and verify the geo is displayed
- repeat for point radius
- test with other shapes and verify they are displayed correctly
Fixes: #____ …
=> [2.19.x] G-9033 fix Saved search form fails to display Geometry

ui/packages/catalog-ui-search/src/main/webapp/component/result-form/result-form.view.js
Improves result form UX by only showing input validation errors when the user tries to click Save
@kentmorrissey @brhumphe @brianfelix
@lambeaux
@millerw8
1. Open the `Result Form` page in Intrigue
2. Click `+ New Result Form`
3. Verify no validation errors are shown
4. Click `Save` without entering any values
5. Verify validation errors for Title and Attributes are now shown
6. Play around with modifying existing result forms to test for regressions
Fixes: #____ …
=> [2.19.x] G-7920 Improve Result Form UX

ui/packages/catalog-ui-search/src/main/webapp/js/CQLUtils.js
fixes search form editor failing to save a linestring geo without a buffer.
removes `distance` attribute when no buffer applied
@cassandrabailey293 @hayleynorton @zta6 @abel-connexta 
@lambeaux
- build / run / install
- create new search form in editor with linestring geo without buffer
- verify form saves correctly
- verify linestring geos with buffers as well and any other geo combination
Fixes: #____ …
=> [2.19.x] G-9209 fix search form fails to save linestring

ui/packages/catalog-ui-search/src/main/webapp/component/location-new/inputs/masked-text-field.js
This PR fixes an issue where the anyGeo component was jumping off the search form in a specific version of Firefox. The problem was the usage of `event` in the `padEndWithZeros` method, which was being called many times by the pipe function. I removed the pipe function since we only want to call `padEndWIthZeros` when switching to the DMS tab from other tabs.
@hayleynorton @andrewzimmer @zta6 @abel-connexta 
@codice/ui 
0. build, profile/install
1. Verify no regression with DMS coordinate entry/switching tabs
2. Download Firefox 60 ESR: https://ftp.mozilla.org/pub/firefox/releases/60.0esr/mac/en-US/
3. Go to the UI and Advanced Search -> anyGeo
4. Select Bounding Box
5. Switch to the DMS tab
6. Verify that there is no `event is not defined` error in the console and that the component …
=> [2.19.x] G-8885; Use window.event instead of event

ui/packages/catalog-ui-search/src/main/webapp/component/query-add/query-add.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/query-settings/query-settings.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/search-form-interactions/search-form-interactions.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/search-form/search-form.view.js, ui/packages/catalog-ui-search/src/main/webapp/js/model/Query.js, ui/packages/catalog-ui-search/src/main/webapp/js/model/QuerySettings.js
ddf-ui PRs:
3.4.x codice/ddf-ui#398
Issue 1 - Unable to clear default Result Form if tried to switch Workspace Search Forms (works after refresh) 
Issue 2 - Unable to clear default Result Form if tried to select User custom Search Forms (still issue even after refresh)
Issue 3 - Deleted Result Form is still selected when Updating a custom Search Forms if selected prior to its deletion
Issue 4 - Deleted Result Form still appears in dropdown in Workspace Search 
Issue 5 - Exception is thrown when deleting a non-default Search Form
Issue 6 - Updated Search form that saved “All Field” in Search Form for Result form, gets overridden to existing default Result Form
Issue 7 - “Use Another Search Form” in workspace do not show correct selected Search Form for dropdown
Issue …
=> [2.19.x] DDF-UI-396 Result Form shows 'Make Default Form' even though already default

features/security/src/main/feature/feature.xml
Deletes reference from the security features descriptor to the old wrapped opensaml bundle. It no longer exists
@shaundmorris 
@codice/build 
CI without cached m2
Fixes: #6360 …
=> DDF-6360 Remove reference to deleted libs-bundles-opensaml artifact

ui/packages/catalog-ui-search/src/main/webapp/component/search-form-editor/search-form-editor.view.js
prevents search form editor title from retaining the changes after the user cancels the edit
@abel-connexta @zta6 @cassandrabailey293 @hayleynorton 
@lambeaux
- open search form editor and save a new search form with title and some attributes
- open again to edit and make some changes
- cancel the edit and verify that none of the changes were persisted
Fixes: #____
- ❓ …
=> [2.19.x] G-9203 fix search form editor title changes after cancel

ui/packages/catalog-ui-search/src/main/webapp/component/result-filter/result-filter.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/map.view.js, ui/packages/catalog-ui-search/src/main/webapp/js/model/User.js
ddf-ui PRs:
3.4.x codice/ddf-ui#428
Resolved following List issues:
Issue 1 - Error when saving "NOT AND" or "NOT OR" filters.
Issue 2 - Error when remove all fields in filter and saving.
@andrewzimmer 
@hayleynorton
@zta6 
@Lambeaux 
**Issue 1 - Error when saving "NOT AND" or "NOT OR" filters.**
1. Go to Workspaces, open or click create a New Workspace
2. Perform any type of Search that returns results
3. Click on "Filter" Result menu icon 
4.  Select "NOT AND" or "NOT OR"
5.  Open console log
6. Add some fields and click "Save Filter"
7. Ensure no error occurs
8. Ensure the Result menu icons are still there and able to edit filter created
9. Refresh page and ensure no error occurs and Result menu icons are still there and able to edit filter …
=> [2.19.x] G-9247 Loosing Result Selector Menu

catalog/core/catalog-core-api/src/main/java/ddf/catalog/data/MetacardType.java, catalog/transformer/catalog-transformer-csv-common/pom.xml, catalog/transformer/catalog-transformer-csv-common/src/main/java/ddf/catalog/transformer/csv/common/MetacardIterator.java, catalog/transformer/catalog-transformer-csv-common/src/test/java/ddf/catalog/transformer/csv/common/MetacardIteratorTest.java, catalog/transformer/catalog-transformer-csv-queryresponse/pom.xml, catalog/transformer/catalog-transformer-csv-queryresponse/src/main/java/ddf/catalog/transformer/csv/CsvMetacardTransformer.java, catalog/transformer/catalog-transformer-geojson-input/src/main/java/ddf/catalog/transformer/input/geojson/GeoJsonInputTransformer.java, catalog/transformer/catalog-transformer-geojson-metacard/src/main/java/ddf/catalog/transformer/metacard/geojson/GeoJsonMetacardTransformer.java, catalog/transformer/catalog-transformer-geojson-metacard/src/test/java/ddf/catalog/transformer/metacard/geojson/GeoJsonMetacardTransformerTest.java, catalog/transformer/catalog-transformer-propertyjson-metacard/src/main/java/ddf/catalog/transformer/metacard/propertyjson/PropertyJsonMetacardTransformer.java
Downstream projects need to create CSV exports that include the source identifier and metacard type name. The current code only supports exporting data that is contained in a metacard attribute. However, the source identifier and metacard type name are stored separately from the attributes.
This PR also creates a constant in MetacardType for the string "metacard-type", which was being defined multiple times in DDF and in downstream projects.
@pklinef 
@derekwilhelm 
@codice/data 
@bdthomson
@jlcsmith
Build with a downstream project that provides a UI capable of creating a CSV export. The export should include the source id and metacard type. Make sure that the exported data includes the correct values for these fields.
Fixes: #6386  …
=> [2.26.x] DDF-6386 Add support for source id and metacard type for csv metacard  transforms

features/security/src/main/feature/feature.xml
Deletes reference from the security features descriptor to the old wrapped opensaml bundle. It no longer exists
@shaundmorris 
@codice/build 
CI without cached m2
Fixes: #6360 …
=> [2.26.x] DDF-6360 Remove reference to deleted libs-bundles-opensaml artifact

catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsFilterDelegate.java, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsSource.java, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/resources/OSGI-INF/metatype/metatype.xml, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsFilterDelegateTest.java, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsSourceTest.java, catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/source/WfsFilterDelegate.java, catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/source/WfsSource.java, catalog/spatial/wfs/spatial-wfs-common/pom.xml, catalog/spatial/wfs/spatial-wfs-common/src/main/java/org/codice/ddf/spatial/ogc/wfs/catalog/common/AbstractWfsSource.java, catalog/spatial/wfs/spatial-wfs-common/src/test/java/org/codice/ddf/spatial/ogc/wfs/catalog/common/AbstractWfsSourceTest.java
Ports & refactors the WFS 2.0 sorting functionality into the WFS 1.1.0 source. Adds flag to enable/disable sorting (default to disable).  Adds mapping of DDF sort attributes to WFS attributes.
@millerw8 
@jrnorth 
@glenhein 
@derekwilhelm 
@codice/data 
@jrnorth 
@emmberk 
1) build / install DDF
2) build DDF UI master (update ddf.version to 2.26.1-SNAPSHOT)
3) install DDF UI features into DDF per the README https://github.com/codice/ddf-ui/blob/master/README.md
4) Verify Intrigue UI is accessible
5) start up GeoServer
6) configure a Metacard to WFS Feature Map 
```
Feature type = {http://www.openplans.org/topp}states
Metacard title to feature property mapping = STATE_NAME
```
Save the config
7) configure a new WFS v1.1.0 Federated Source
```
WFS URL = http://<host>:<port>/geoserver/ows …
```
=> [2.26.x] DDF-4729 adds WFS 1.1.0 sorting

catalog/solr/catalog-solr-core/src/main/java/ddf/catalog/source/solr/PropertyExistsDelegate.java, catalog/solr/catalog-solr-core/src/main/java/ddf/catalog/source/solr/ResultHighlighter.java, catalog/solr/catalog-solr-core/src/main/java/ddf/catalog/source/solr/SolrMetacardClientImpl.java, distribution/ddf-common/src/main/resources-filtered/etc/custom.system.properties, distribution/ddf-common/src/main/resources/security/default.policy
Allows solr highlighter parameters to be configurable in the system.
@pklinef 
@jlcsmith 
@codice/solr 
@vinamartin
1. Perform a full build
2. Unzip/install DDF
3. Create the file `<ddf_home>/etc/solr-highlighter.properties`
4. Add various highlighter settings to this file
- Some examples: `hl.fl=title_txt`, `hl.requireFieldMatch=false`
5. Enable solr highlighting via the `custom.system.properties` file: set `solr.highlight.enabled=true`
6. Start DDF
7. Perform a search
8. Verify (via debugging DDF or via Solr logs) that the highlight parameters as specified in the config file are applied to the query
Fixes: #6421  …
=> [2.26.x] DDF-6421 - Enable configuration of solr highlight parameters

ui/packages/catalog-ui-search/src/main/webapp/component/list-editor/list-editor.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/result-filter/list/result-filter.list.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/result-filter/result-filter.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/search-form-editor/search-form-editor.view.js, ui/packages/catalog-ui-search/src/main/webapp/js/filter.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/group/index.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/location/base.line.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/location/keyword.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/location/location.less, ui/packages/catalog-ui-search/src/main/webapp/react-component/text-field/text-field.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/utils/validation/validation.tsx
ddf-ui PRs:
3.4.x codice/ddf-ui#451
- Prevents the user from saving and/or executing any location (e.g. 'anyGeo', 'location', 'center point' ) that is empty ('no keyword is selected').
- Also made keyword shape read only (can still copy and paste the geometry)
- Fix issue when a buffer is inputed for multiPolygon Keyword, error occurs
@andrewzimmer 
@hayleynorton
@zta6 
@Lambeaux 
• Ingest gazetteer data keywords
https://github.com/codice/ddf/blob/master/distribution/ddf-common/src/main/resources/data/countries.geo.json
`>gazetteer:update /..<path of file>../countries.geo.json`
https://download.geonames.org/export/dump/
`>gazetteer:update /..<path of file>../VA.zip` …
=> [2.19.x] G-9315 Prevent Save/Search of empty Location Keyword

Jenkinsfile
Upgrades Sonar Analysis to use JDK 11. Java 8 is no longer supported as of next month.
@TonyMorrison 
@LinkMJB 
@codice/build 
@Lambeaux 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codice/ddf/ …
=> Upgraded Sonar analysis to use JDK 11

catalog/core/catalog-core-commands/pom.xml, catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/RangeCommand.java, catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/SubjectCommands.java, catalog/core/catalog-core-commands/src/test/java/org/codice/ddf/commands/catalog/SubjectCommandsTest.java
- Fixes the error message printed out to the Karaf console when `executeWithSubject` throws an `Exception` in any class that implements `SubjectCommands`
- Update `catalog:range` command to only print table header row when there are no errors
Before:
```
admin@root()> catalog:range name ___ ___
null
```
After:
```
admin@root()> catalog:range name ___ ___
Could not parse date parameters.
```
Verify that both checked and unchecked exceptions are handled (log and karaf console output) correctly for comands that extend `SubjectCommands`. I tested with `catalog:range`. Here are the commands that I used:
|                        | run with username                                           | run without username                           | …
=> [2.26.x] Fix printErrorMessage when executeWithSubject fails in SubjectCommands

catalog/solr/catalog-solr-core/src/main/java/ddf/catalog/source/solr/SolrFilterDelegate.java, catalog/solr/catalog-solr-core/src/test/java/ddf/catalog/source/solr/provider/SolrProviderQuery.java
The NOT operator in queries are translating to invalid solr queries.  This PR changes the translation to be `(*:* NOT <query>)` instead of `NOT <query>` so that the solr query is generated properly.
@pklinef 
@codice/solr 
@jlcsmith
@vinamartin
1. Ingest a document with title `test.txt`
2. Perform a cql search: `((NOT (("title" ILIKE 'something'))) OR ("title" ILIKE 'test'))`
3. Verify that the `test.txt` document is returned in the results
Fixes: #6437  …
=> [2.26.x] DDF-6437 - Correctly translate NOT query operator

ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-old.js, ui/packages/catalog-ui-search/src/main/webapp/js/widgets/openlayers.bbox.js
_____________________________________________________
This PR removes the 180 degree width restraint on bounding boxes by checking whether or not it crosses the antimeridian using the conditional of not drawing and `east < west` instead of `east - west > 180 || east - west < -180` 
@abel-connexta @andrewzimmer @zta6 
Verify that you can draw bounding boxes that cross the prime meridian and the antimeridian
Fixes: G-8544 …
=> [2.19.x] G-8544 Removed 180 degree width constraint on bounding boxes

catalog/solr/catalog-solr-commands/pom.xml, catalog/solr/catalog-solr-core/pom.xml, features/solr/src/main/feature/feature.xml, platform/solr/solr-dependencies/pom.xml, pom.xml
As of version 8.x, Solrj depends on Jetty. The solr-dependencies bundle was missing the Jetty imports, and it was causing an issue when trying to configure the Solr client to use basic auth. This PR adds them.
@pklinef @derekwilhelm 
@codice/solr 
1. Start a Solr server and configure it to use basic auth. You can do that by overwriting the `security.json` file with 
```
{
"authentication":{
"class":"solr.BasicAuthPlugin",
"credentials":{"solr":"IV0EHq1OnNrj6gvRCwvFwTrZ1+z1oBbnQdiVC3otuq0= Ndd7LKvVBAaZIF0QAVi1ekCfAJXr1GGfLtRUXhgrF8c="},
"blockUnknown": true
},
"authorization":{
"class":"solr.RuleBasedAuthorizationPlugin",
"user-role":{"solr":"admin"},
"permissions":[{"name":"all",
"role":"admin"}]
}
}
```
2. Build and unzip DDF
3. Configure the Solr client in DDF to use basic auth to …
=> [2.26.x] Add missing Jetty imports to solr-dependencies

catalog/spatial/kml/spatial-kml-util/pom.xml, catalog/spatial/kml/spatial-kml-util/src/main/java/org/codice/ddf/spatial/kml/converter/MetacardToKml.java, catalog/spatial/kml/spatial-kml-util/src/test/java/org/codice/ddf/spatial/kml/converter/MetacardToKmlTest.java
ddf PRs:
2.23.x codice/ddf#6459
master codice/ddf#6458
kml not exporting InnerBoundary, witch causes issue of being unable to import Multipolygon with holes, and causes issues upstream.
@andrewzimmer
@hayleynorton
@zta6
1. Go to Workspace and Create/Update new workspace
2. Upload some content (Click on Navigation icon on upper left corner)
3. Search for uploaded items
4. Add or update "locations" attributes to a Shape with hole(s). Added shape should be displayed on 2D map.
a. Items can be added via the Inspector Visual. Example locations bellow (for other example look at bottom):
MULTIPOLYGON (((30 20, 45 40, 10 40, 30 20), (15 5, 40 10, 10 20, 15 5)))
5. Click on ellipses to the bottom right of …
=> [2.19.x] G-9476 kml not exporting InnerBoundary

ui/packages/catalog-ui-search/src/main/webapp/react-component/filter/filter-input/filter-boolean-input.js
This PR alters the validation of data received from the server such
that when a user saves a Search Form which contains a boolean value of
`true`, that value will remain as `true` even after the user reloads the
relevant data from the server.
@Lambeaux 
@brhumphe 
@brianfelix 
@Lambeaux 
1. Build this branch
2. `profile:install standard`
3. Open the UI
4. Create a Search Form with the attribute 'spellcheck' set to `true`
5. Save th**e**~is~ ~s~**S**earch ~f~**F**orm
6. Refresh the webpage
7. Verify that the Search Form still has the attribute 'spellcheck' set to `true`
8. Clear the browser's cache
9. Verify that the Search Form still has the attribute 'spellcheck' set to `true`
10. Create another Search Form with the attribute 'spellcheck' set to …
=> [2.19.x] G-9570 Retain boolean value after reload

platform/security/core/security-core-impl/pom.xml, platform/security/core/security-core-impl/src/main/java/ddf/security/assertion/impl/DefaultSecurityAssertionBuilder.java, platform/security/core/security-core-impl/src/test/java/ddf/security/assertion/impl/DefaultSecurityAssertionBuilderTest.java
Requires a user principal to be provided when building a SecurityAssertionDefault. The builder as-is allows assertions to be created without one, even though DDF assumes that a principal will be present.
@vinamartin @jlcsmith @andrewkfiedler @jordanwilking 
CI 
We found a case where invalid security assertions were being created with the default security assertion builder. This should prevent that in the future.
Fixes: #____ …
=> [2.26.x] Require userPrincipal for DefaultSecurityAssertion

catalog/solr/catalog-solr-core/src/main/java/ddf/catalog/source/solr/SolrFilterDelegate.java, catalog/solr/catalog-solr-core/src/test/java/ddf/catalog/source/solr/provider/SolrProviderQuery.java
The NOT operator in queries are translating to invalid solr queries. This PR changes the translation to be `(*:* NOT <query>)`  instead of `NOT <query>` so that the solr query is generated properly.
@pklinef
@codice/solr 
@jlcsmith
@vinamartin
1. Ingest a document with title `test.txt`
2. Perform a cql search: `((NOT (("title" ILIKE 'something'))) OR ("title" ILIKE 'test'))`
3. Verify that the `test.txt` document is returned in the results
Fixes: #6437  …
=> DDF-6437 - Correctly translate NOT query operator

platform/security/core/security-core-impl/pom.xml, platform/security/core/security-core-impl/src/main/java/ddf/security/assertion/impl/DefaultSecurityAssertionBuilder.java, platform/security/core/security-core-impl/src/test/java/ddf/security/assertion/impl/DefaultSecurityAssertionBuilderTest.java
Forward port of https://github.com/codice/ddf/pull/6486. Changes the DefaultSecurityAssertionBuilder to require a userPrincipal, as all assertions should have one.
@vinamartin @jlcsmith @andrewkfiedler @jordanwilking
CI 
Fixes: #____
- ❗ …
=> Require userPrincipal for DefaultSecurityAssertion

catalog/spatial/kml/spatial-kml-util/pom.xml, catalog/spatial/kml/spatial-kml-util/src/main/java/org/codice/ddf/spatial/kml/converter/MetacardToKml.java, catalog/spatial/kml/spatial-kml-util/src/test/java/org/codice/ddf/spatial/kml/converter/MetacardToKmlTest.java
ddf PRs:
2.19.x codice/ddf#6457
master codice/ddf#6458
kml not exporting InnerBoundary, witch causes issue of being unable to import Multipolygon with holes, and causes issues upstream.
@andrewzimmer
@hayleynorton
@zta6
1. Go to Workspace and Create/Update new workspace
2. Upload some content (Click on Navigation icon on upper left corner)
3. Search for uploaded items
4. Add or update "locations" attributes to a Shape with hole(s). Added shape should be displayed on 2D map.
a. Items can be added via the Inspector Visual. Example locations bellow (for other example look at bottom):
MULTIPOLYGON (((30 20, 45 40, 10 40, 30 20), (15 5, 40 10, 10 20, 15 5)))
5. Click on ellipses to the bottom right of …
=> [2.23.x] G-9476 kml not exporting InnerBoundary

catalog/spatial/kml/spatial-kml-util/pom.xml, catalog/spatial/kml/spatial-kml-util/src/main/java/org/codice/ddf/spatial/kml/converter/MetacardToKml.java, catalog/spatial/kml/spatial-kml-util/src/test/java/org/codice/ddf/spatial/kml/converter/MetacardToKmlTest.java
ddf PRs:
2.19.x codice/ddf#6457
2.23.x codice/ddf#6459
kml not exporting InnerBoundary, witch causes issue of being unable to import Multipolygon with holes, and causes issues upstream.
@andrewzimmer
@hayleynorton
@zta6
1. Go to Workspace and Create/Update new workspace
2. Upload some content (Click on Navigation icon on upper left corner)
3. Search for uploaded items
4. Add or update "locations" attributes to a Shape with hole(s). Added shape should be displayed on 2D map.
a. Items can be added via the Inspector Visual. Example locations bellow (for other example look at bottom):
MULTIPOLYGON (((30 20, 45 40, 10 40, 30 20), (15 5, 40 10, 10 20, 15 5)))
5. Click on ellipses to the bottom right of …
=> G-9476 kml not exporting InnerBoundary

catalog/solr/catalog-solr-core/src/main/java/ddf/catalog/source/solr/PropertyExistsDelegate.java, catalog/solr/catalog-solr-core/src/main/java/ddf/catalog/source/solr/ResultHighlighter.java, catalog/solr/catalog-solr-core/src/main/java/ddf/catalog/source/solr/SolrMetacardClientImpl.java, distribution/ddf-common/src/main/resources-filtered/etc/custom.system.properties, distribution/ddf-common/src/main/resources/security/default.policy
Forward port of PR #6422 
Allows solr highlighter parameters to be configurable in the system.
@pklinef
@jlcsmith
@codice/solr 
@vinamartin
1. Perform a full build
2. Unzip/install DDF
3. Create the file <ddf_home>/etc/solr-highlighter.properties
4. Add various highlighter settings to this file
- Some examples: hl.fl=title_txt, hl.requireFieldMatch=false
5. Enable solr highlighting via the custom.system.properties file: set solr.highlight.enabled=true
6. Start DDF
7. Perform a search
8. Verify (via debugging DDF or via Solr logs) that the highlight parameters as specified in the config file are applied to the query
Fixes: #6421 …
=> DDF-6421 - Enable configuration of solr highlight parameters

ui/packages/catalog-ui-search/src/main/webapp/behaviors/dropdown.behavior.utility.js, ui/packages/catalog-ui-search/src/main/webapp/component/search-form-editor/search-form-editor.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/map.view.js, ui/packages/catalog-ui-search/src/main/webapp/js/widgets/openlayers.line.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/filter/filter-input/filter-location-input.js
ddf-ui PRs:
3.4.x codice/ddf-ui#496
Solve following issues:
- Issue 1 - Line Location Buffer Error. Unpredictable behavior when negative value is inputted for line Buffer.
- Issue 2 - When a shape is drawn in workspace and then go to create a Search Form and select to draw a shape, the previously drawn shape from workspace is displayed on the map.
- Issue 3 - When user click on draw and drawing on 3D map tab for Lists and/or Result Filter, if user click outside of map area, user lose the "cancel draw", but user is still able to draw, and won't be able to get rid of that shape and it won't appear on the filter form (anyGeo etc.) to delete. 
- Issue 4 - Keyword location geometry does not get cleared on 3D map, when switching between keyword values (e.g. United State, …
=> [2.19.x] G-9627 Line Location Buffer Error & Map issues

catalog/core/catalog-core-validator/src/main/java/ddf/catalog/validation/impl/validator/MatchAnyValidator.java, catalog/core/catalog-core-validator/src/test/java/ddf/catalog/validation/impl/MatchAnyValidatorTest.java
Master Port of #6222
Adds `equals()` and `hashCode()` methods to `MatchAnyValidator` to not allow adding in multiple of the same `MatchAnyValidator`s if one already exists for an `attribute`.
@leo-sakh 
@bennuttle 
@jMoneee 
@bdeining
@millerw8
1. Build and install
2. Edit `/etc/definition/core-attributes-validator.json` file with the following contents
```
{
"validators": {
"datatype":
[
{
"validator": "enumerationignorecase",
"arguments": [
"Collection",
"Dataset",
"Event",
"Image",
"Interactive Resource",
"Moving Image",
"Physical Object",
"Service",
"Software",
"Sound",
"Still Image",
"Text"
]
}
],
"location.country-code":
[
{
"validator": "match_any",
"validators": [
{
"validator": "iso3_countryignorecase"
}
]
}
]
}
}
```
3. Run DDF
4. Check that the dropdown …
=> DDF-6221 Duplicate MatchAnyValidators get added to AttributeValidator Registry for an attribute

ui/packages/catalog-ui-search/src/main/webapp/component/search-form-editor/search-form-editor.view.js
Previously, when a user defined any geometries on their search form (i.e., anyGeo, location attribute searches), the search form editor was not panning to these geometries. This PR fixes this behavior by panning to the extent defined by the collection of coordinates of all of the geometries defined on the search form. In other words, it will now pan/zoom to show the geometries. 
@codice/ui 
1. build, profile:install
2. create a search form with an `anyGeo` attribute, draw the geo somewhere away from your Home view 
3. fill in other necessary fields and save the search form
4. open the search form back up and verify that the map shows the geometry you created in step 2
5. edit the search form by adding a `location` attribute and drawing a geo 
6. re-open the search form and verify that the …
=> [2.19.x] G-9036 pan to geos defined on search form

catalog/transformer/catalog-transformer-csv-queryresponse/src/main/java/ddf/catalog/transformer/csv/CsvMetacardTransformer.java, catalog/transformer/catalog-transformer-zip/src/main/java/org/codice/ddf/catalog/transformer/zip/ZipCompression.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/handlers/CqlTransformHandler.java, distribution/ddf-common/src/main/resources/security/default.policy, ui/packages/catalog-ui-search/src/main/webapp/react-component/results-export/container.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/utils/export/export.tsx
This pr fixes issues with the request body for zipped export that was causing the backend to throw exceptions and not export the result(s). Namely, the request requires a sort to be passed as one of the arguments. Previously, this was causing ALL export selected (Compressed) to fail. Nothing would happen when users clicked download, no indication of failure, for all formats. Adding the sort, as well as the following changes, fixed MOST of the export formats. 
In addition, `columnOrder` can be passed as either a comma-delimited string, or as a list of strings. Changes were made to accommodate this. 
Also, I made changes to pass the arguments along to the metacard transformer for the zipped (compressed) export for similar reasons. 
Another issue was that we were passing a URI-encoded value …
=> [2.19.x] G-9585 fix export result (compressed)

catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/util/impl/CaseInsensitiveIfStringComparator.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/federation/impl/SortedQueryMonitor.java, catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/federation/impl/SortedQueryMonitorTest.java
Adds a new comparator for doing case insensitive sort on string attributes.
Even though solr was returning the results with case insensitive sorting (https://github.com/codice/ddf/pull/6320), they were getting resorted in the incorrect order. 
@pklinef 
@derekwilhelm 
@jlcsmith 
1. Perform a full build
2. Install DDF and DDF-UI
3. Upload/ingest several documents with sortable names
4. For example: apple.txt, apricot.txt, banana.txt, blackberry.txt, blueberry.txt, broccoli.txt, carrot.txt, cherry.txt, tangerine.txt
5. Edit some of the titles in the metacards to contain uppercase letters 
6. Hit the cql endpoint or any other endpoint that allows for query and sort by title ascending
7. Verify the results are correctly sorted
8. Verify asc/desc order is …
=> [2.26.x] Updates SortedQueryMonitor to include a case insensitive sort

catalog/transformer/catalog-transformer-csv-common/pom.xml, catalog/transformer/catalog-transformer-csv-common/src/main/java/ddf/catalog/transformer/csv/common/MetacardIterator.java, catalog/transformer/catalog-transformer-csv-common/src/test/java/ddf/catalog/transformer/csv/common/MetacardIteratorTest.java
Normalizes any metacard date attributes to UTC when exporting to a CSV file.
@codice/io 
Export a metacard as a CSV file. Verify that the generated CSV uses UTC dates. For example:
Fixes: #____ …
=> [2.26.x] Use UTC dates when exporting metacards in CSV format

catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsFilterDelegate.java, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsSource.java, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/resources/OSGI-INF/metatype/metatype.xml, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsFilterDelegateTest.java, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsSourceTest.java, catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/source/WfsFilterDelegate.java, catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/source/WfsSource.java, catalog/spatial/wfs/spatial-wfs-common/pom.xml, catalog/spatial/wfs/spatial-wfs-common/src/main/java/org/codice/ddf/spatial/ogc/wfs/catalog/common/AbstractWfsSource.java, catalog/spatial/wfs/spatial-wfs-common/src/test/java/org/codice/ddf/spatial/ogc/wfs/catalog/common/AbstractWfsSourceTest.java
Forward port of #6419  
* DDF-4729 adds WFS 1.1.0 sorting
- adds flag to enable/disable sorting
- adds mapping of DDF sort attributes to WFS attributes
@millerw8
@jrnorth
@glenhein
@derekwilhelm
@codice/data
@jrnorth 
@millerw8 
See test instructions in #4729 
Fixes: #____ …
=> DDF-4729 adds WFS 1.1.0 sorting

catalog/transformer/catalog-transformer-csv-queryresponse/src/main/java/ddf/catalog/transformer/csv/CsvMetacardTransformer.java, catalog/transformer/catalog-transformer-zip/src/main/java/org/codice/ddf/catalog/transformer/zip/ZipCompression.java, distribution/ddf-common/src/main/resources/security/default.policy
backend portion of forward port of https://github.com/codice/ddf/pull/6496
should be built with 3.4.x DDF-UI pr https://github.com/codice/ddf-ui/pull/506
___________________________________________________________________
This pr fixes issues with the request body for zipped export that was causing the backend to throw exceptions and not export the result(s). Namely, the request requires a sort to be passed as one of the arguments. Previously, this was causing ALL export selected (Compressed) to fail. Nothing would happen when users clicked download, no indication of failure, for all formats. Adding the sort, as well as the following changes, fixed MOST of the export formats. 
In addition, `columnOrder` can be passed as either a comma-delimited string, or as a list of strings. Changes …
=>  [2.23.x] G-9585 fix export result (compressed)

catalog/transformer/catalog-transformer-csv-queryresponse/src/main/java/ddf/catalog/transformer/csv/CsvMetacardTransformer.java, catalog/transformer/catalog-transformer-zip/src/main/java/org/codice/ddf/catalog/transformer/zip/ZipCompression.java, distribution/ddf-common/src/main/resources/security/default.policy
backend portion of master port of https://github.com/codice/ddf/pull/6496
should be built with 3.4.x DDF-UI pr https://github.com/codice/ddf-ui/pull/506
___________________________________________________________________
This pr fixes issues with the request body for zipped export that was causing the backend to throw exceptions and not export the result(s). Namely, the request requires a sort to be passed as one of the arguments. Previously, this was causing ALL export selected (Compressed) to fail. Nothing would happen when users clicked download, no indication of failure, for all formats. Adding the sort, as well as the following changes, fixed MOST of the export formats. 
In addition, `columnOrder` can be passed as either a comma-delimited string, or as a list of strings. Changes were …
=> G-9585 fix export result (compressed)

ui/packages/catalog-ui-search/src/main/webapp/behaviors/dropdown.behavior.js, ui/packages/catalog-ui-search/src/main/webapp/behaviors/dropdown.behavior.utility.js, ui/packages/catalog-ui-search/src/main/webapp/component/dropdown/dropdown.companion.view.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/dropdown/dropdown.tsx
ddf-ui PRs:
3.4.x codice/ddf-ui#509
When user is working within a dropdown window (e.g. Search form, List, Result Filter etc.), when they receive an error banner and click to close it, the dropdown closes and lose whatever was being worked on.
@andrewzimmer 
@hayleynorton
@zta6 
@Lambeaux 
1. Go to a workspace
2. Create advanced search (Advanced Search)
3. Cause an error dialogue message to pop-up (e.g. select anyGeo and don't select any shape types and click "Search")
4. Try clicking on error dialogue and then try to close error dialogue
5. Ensure the Advanced search form you were working on before the error, is still displayed and did not close
6. Do steps 3 to 5 for other dropdown(s) such as …
=> [2.19.x] G-9774 Drop down window(s) closes and lose data when error banner is closed

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/forms/TemplateTransformer.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/forms/filter/FilterReader.java
Search form read operations for a single form take noticeably longer than other ops. There's a noticeable delay while debugging GET ops over lines that create `FilterReader` in `TemplateTransformer`. When this compounds for many search forms, the user will be left waiting. 
This PR fixes the issue, which is the creation of a `JAXBContext`, not per request, but **per form** being processed. This is causing redundant JAXB initialization processing of XML metadata that isn't necessary and now it only gets created once when the application starts: 
https://stackoverflow.com/a/7400735
This was missed the first time through because the javadocs made no mention of thread safety. 
https://docs.oracle.com/javase/8/docs/api/javax/xml/bind/JAXBContext.html
@brianfelix
@millerw8 …
=> [2.19.x] G-9824 Greatly speeds up search form GET requests by not creating a JAXBContext for each form being processed

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/forms/builder/AttributeValueNormalizer.java, catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/forms/builder/AttributeValueNormalizerTest.java
Relaxes attribute validation on search forms so that valid attributes do not keep a search form from getting saved. 
Forms XML structures in Solr have never had comprehensive validation to inform the UI when it's sending incompatible data. This means changes to the UI data structures were able to impact the persistence layer and potentially break the system when old data is read that no longer conformant to what the UI wants. 
Essentially, we had no systems to detect when we were putting ourselves in a migration situation (or near one), in particular for nested data (like forms XML) which get translated directly from UI data structures. 
In response, uni-directional validation was added to search forms which aggressively rejects bad data when persisting it, but provides a best effort …
=> [2.19.x] G-9826 Fix saving search forms by relaxing overly strict attribute name validation

distribution/ddf-common/src/main/resources/bin/setenv, distribution/ddf-common/src/main/resources/bin/setenv.bat
Enables java garbage collection logging to data/log/
**What log level should we set by default?** 
Available levels are the typical 'trace, debug, info, warning, error'
Currently set on *info*. 
Debug offers course grained info related to setup and a vague description of what garbage collection has occurred:
`[2021-02-25T16:16:25.549-0700][0.013s][debug][gc] Initialize mark stack with 4096 chunks, maximum 16384`
`[2021-02-25T16:17:49.941-0700][84.405s][debug][gc] GC(51) Reclaimed 601 empty regions`
Info offers some information as to what type of garbage collection is occurring: 
`[2021-02-25T16:17:50.089-0700][84.553s][info ][gc] GC(51) Concurrent Cycle 402.641ms`
`[2021-02-25T16:17:50.387-0700][84.850s][info ][gc] GC(52) Pause Young (Normal) (G1 Evacuation Pause) 510M->212M(2732M) …
=> Enable Java garbage collection logging

catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/ContentDirectoryMonitor.java, catalog/core/catalog-core-directorymonitor/src/test/java/org/codice/ddf/catalog/content/monitor/ContentDirectoryMonitorTest.java
Attache the system subject to the camel thread for CDM in a way that ensures it works regardless of the camel thread used to run the route.
@jrnorth 
@kcover 
@shaundmorris
Verify CDM still works
In downstream projects using the cdm it was found that the system subject wasn't being attached to the camel thread running the cdm route when the thread wasn't the one that had initialized the route.
=> CDM fix for binding system subject to thread

catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/pom.xml, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/ExtendedGetFeatureType.java, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/ExtendedWfs.java, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsSource.java, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/resources/OSGI-INF/metatype/metatype.xml, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsSourceTest.java
Adds configuration to enable `startIndex` and deep paging on `GetFeature` requests for WFS 1.1 servers that support it like Geoserver.
@derekwilhelm 
@jlcsmith 
- Setup Geoserver with test data with over 1000 results. 
- Configure a WFS 1.1.0 source for that Geoserver. 
- Set the `supportsStartIndex` config option. 
- Verify you can page past 1000 results.
- Disable the `supportsStartIndex` config option. 
- Verify you can page up to 1000 results but fails past 1000.
Fixes: n/a …
=> [2.26.x] Support startIndex in GetFeature requests on WFS 1.1.0

catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsSource.java, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsSourceTest.java
Fixes a off by one error when using start indexes on WFS 1.1 sources.
@derekwilhelm 
@jlcsmith
Add Geoserver with test data as a WFS 1.1 source. Enable start index support. Verify all results are returned on last page.
Fixes: n/a …
=> [2.26.x] Fix WFS 1.1 off by one error with start index

catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsSource.java, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsSourceTest.java
When the WFS Source receives a query with a null sort property ignore it and continue
@derekwilhelm @pklinef 
@derekwilhelm @pklinef 
Fixes: #____
=> [2.26.x] DDF-4729 Handles WFS sortBy null property

catalog/transformer/catalog-transformer-common/src/main/java/ddf/catalog/transformer/common/tika/MetacardCreator.java
Adds a null check for the attribute descriptor in case the configured attribute name is not found in the metacard type.
@pklinef 
@codice/data 
@jlcsmith 
See steps in #6569 
Fixes: #____ …
=> [2.26.x] DDF-6568 - Add null check for attribute descriptor

platform/security/core/security-core-services/pom.xml, platform/security/core/security-core-services/src/main/java/ddf/security/http/impl/HttpSessionFactory.java
Fixes the bug when multiple requests from the same user to the same context are received too close together for the first time that the context is accessed.  In this scenario, jetty cannot associate a session object to the request when they are received because one does not exist yet.  Since both requests are received at basically the same time, both (or more) requests are in the same state and will attempt to create a new session object.  Since the HttpSessionFactory is synchronized, whichever request is received first will create the session object.  Prior to this fix, the second request would then also attempt to create the session object but would fail.  This PR checks the jetty session cache to see if the session was already created and is valid.  If it was, it joins the request to …
=> [2.26.x] DDF-6587 - Manually associate cached jetty sessions

platform/security/core/security-core-services/src/main/java/ddf/security/http/impl/HttpSessionFactory.java
Fixes an issue with previous PR so that the security token is always checked and added even if the cached session is found.
@pklinef
@jlcsmith 
Same as PR #6588 
Fixes: #6587 …
=> [2.26.x] DDF-6587 - make sure security token is added

ui/packages/catalog-ui-search/src/main/webapp/react-component/alert-settings/presentation.tsx
Matches notification setting labels' font size to other user setting labels' font size.
Before:
After:
=> [2.19.x] Notification setting labels' font size is different from rest of settings

catalog/transformer/catalog-transformer-csv-queryresponse/pom.xml, catalog/transformer/catalog-transformer-csv-queryresponse/src/main/java/ddf/catalog/transformer/csv/CsvMetacardTransformer.java, catalog/transformer/catalog-transformer-csv-queryresponse/src/main/java/ddf/catalog/transformer/csv/CsvQueryResponseTransformer.java, catalog/transformer/catalog-transformer-csv-queryresponse/src/main/java/ddf/catalog/transformer/csv/CsvTransformerSupport.java, catalog/transformer/catalog-transformer-csv-queryresponse/src/test/java/ddf/catalog/transformer/csv/CsvMetacardTransformerTest.java
`CsvMetacardTransformer` now uses the same transformation logic as `CsvQueryResponseTransformer`, which correctly excludes binary and object attributes. `CsvMetacardTransformer` now also supports column sorting and hiding.
@kcwire 
@millerw8 
@shaundmorris 
@codice/io 
To test the binary attribute filtering:
Upload some records with thumbnails. Search for them in Intrigue, select one or more of them and do a compressed export with CSV.
Unzip the exported file and open the CSV file(s) inside. Verify there is no `thumbnail` column.
To test the column sorting and hiding:
Use a REST client (e.g., Postman) to create a POST to `/search/catalog/internal/cql/transform/zipCompression` with the following body:
```json
{
"searches": [
{
"srcs": [
"ddf.distribution"
],
"cql": …
```
=> [2.19.x] CsvMetacardTransformer excludes binary and object attributes

ui/packages/catalog-ui-search/src/main/webapp/extension-points/table-export/table-export.tsx
Downstream projects need the cacheId, since they may have sources that cache results by the ID.
@shaundmorris 
@samuelechu 
@kcwire 
@millerw8 
@codice/ui 
Will have to be tested downstream.
=> [2.19.x] G-9437 Include the cacheId for table exports

ui/packages/catalog-ui-search/src/main/webapp/react-component/results-export/container.tsx
* Simplifies the results export format filtering code.
* Updates the filtering behavior to handle zipped and unzipped exports differently. Zipped exports require only one result in the set to have the required attributes for that export type to be available. Unzipped exports require every result in the set to have the required attributes for that export type to be available.
@shaundmorris 
@kcwire 
@millerw8 
@samuelechu 
@codice/ui 
Should be tested downstream, I can provide instructions.
=> [2.19.x] Simplify the results export format filtering

catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsSource.java, catalog/spatial/wfs/spatial-wfs-featuretransformer-api/src/main/java/org/codice/ddf/spatial/ogc/wfs/featuretransformer/ExceptionReportException.java, catalog/spatial/wfs/spatial-wfs-featuretransformer/src/main/java/org/codice/ddf/spatial/ogc/wfs/featuretransformer/impl/WfsRouteBuilder.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestSpatial.java
Update the camel route used for WFS to detect the ExceptionReport and throw it so callers can handle it. Update WfsSource to catch the exception, log it, and set the hit count to -1 as per the SourceResponse API.
@jlcsmith 
@derekwilhelm 
@codice/ogc 
@pklinef
This can only be tested if you have a WFS server that returns an ExceptionReport for the hit count, but sends valid objects for the results query. I do not have a publicly available server for this. However, there is a mock server and test in TestSpatial that reproduces the scenario.
This affects a downstream project.
Fixes: #6599  …
=> [2.26.x] DDF-6599 detect a WFS ExceptionReport, log it, and set hit count to -1

catalog/core/catalog-core-solrcommands/src/test/resources/configset/schema.xml, platform/solr/solr-schema/src/main/resources/solr/conf/schema.xml
Solr 8.x will always populate the _root_ field with the unique key (which is id_txt for DDF), if that field is in the schema. When Solr 8.x detects the presence of the _root_ field in the schema, it will use that field to query for Lucene documents when making updates. Solr 7.x and earlier does not populate that field, so a Solr 7.x index will have the field in its schema but not in its Lucene index (assuming the nested documents feature is not being actively used, and DDF does not use it). This causes Solr 8.x to think the document does not exist, so it creates a new Lucene document with a different Lucene Doc ID but the same Solr ID. SolrCloud appears to de-duplicate by ID, so only the old stored document is returned when there is a match for either Lucene document.
This means that if …
=> [2.19.x] Remove _root_ field from Solr schema

catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsSource.java, catalog/spatial/wfs/spatial-wfs-featuretransformer-api/src/main/java/org/codice/ddf/spatial/ogc/wfs/featuretransformer/ExceptionReportException.java, catalog/spatial/wfs/spatial-wfs-featuretransformer/src/main/java/org/codice/ddf/spatial/ogc/wfs/featuretransformer/impl/WfsRouteBuilder.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestSpatial.java
Note: This PR is a redo of the origin PR https://github.com/codice/ddf/pull/6600, because the PR was accidentally merged prematurely. 
Update the camel route used for WFS to detect the ExceptionReport and throw it so callers can handle it. Update WfsSource to catch the exception, log it, and set the hit count to -1 as per the SourceResponse API.
@jlcsmith
@derekwilhelm
@codice/ogc
@pklinef
This can only be tested if you have a WFS server that returns an ExceptionReport for the hit count, but sends valid objects for the results query. I do not have a publicly available server for this. However, there is a mock …
=> [2.26.x] DDF-6599 detect an ExceptionReport, log it, and set hit count to -1

platform/security/claims/security-claims-ldap/src/main/java/ddf/security/sts/claimsHandler/ClaimsHandlerManager.java, platform/security/claims/security-claims-ldap/src/main/java/ddf/security/sts/claimsHandler/LdapClaimsHandler.java, platform/security/claims/security-claims-ldap/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/security/claims/security-claims-ldap/src/main/resources/OSGI-INF/metatype/metatype.xml, platform/security/claims/security-claims-ldap/src/test/java/ddf/security/sts/claimsHandler/ClaimsHandlerManagerTest.java, platform/security/claims/security-claims-ldap/src/test/java/ddf/security/sts/claimsHandler/LdapClaimsHandlerTest.java, pom.xml
After STS removal, LdapClaimsHandler was using null as the object class to do LDAP queries for people. Any additional claims on the person were missing from the subject due to this. Now it will send `people` as the object class in the LDAP query or the configured value.
@dcruver 
@mcalcote 
@stustison
- Configure DDF to an LDAP server with people objects with additional attributes
- Configure DDF to support those additional person attributes
- ddf.security.sts.attributequery config PID has `supportedClaims` value
- ddf.security.guest.realm config PID has `attributes` value
- etc/ws-security/attributeMap.properties needs a mapping for the new attribute
- Claims_Handler_Manager factory PID has `personObjectClass` if the person object needs a value other than `person`
- Log …
=> [2.25.x] Fix people claims lookup for LdapClaimsHandler

platform/security/claims/security-claims-ldap/src/main/java/ddf/security/sts/claimsHandler/ClaimsHandlerManager.java, platform/security/claims/security-claims-ldap/src/main/java/ddf/security/sts/claimsHandler/LdapClaimsHandler.java, platform/security/claims/security-claims-ldap/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/security/claims/security-claims-ldap/src/main/resources/OSGI-INF/metatype/metatype.xml, platform/security/claims/security-claims-ldap/src/test/java/ddf/security/sts/claimsHandler/ClaimsHandlerManagerTest.java, platform/security/claims/security-claims-ldap/src/test/java/ddf/security/sts/claimsHandler/LdapClaimsHandlerTest.java, pom.xml
Forward port of #6607.
After STS removal, LdapClaimsHandler was using null as the object class to do LDAP queries for people. Any additional claims on the person were missing from the subject due to this. Now it will send people as the object class in the LDAP query or the configured value.
@dcruver
@mcalcote
@stustison
- Configure DDF to an LDAP server with people objects with additional attributes
- Configure DDF to support those additional person attributes
- ddf.security.sts.attributequery config PID has `supportedClaims` value
- ddf.security.guest.realm config PID has `attributes` value
- etc/ws-security/attributeMap.properties needs a mapping for the new attribute
- Claims_Handler_Manager factory PID has `personObjectClass` if the person object needs a value other …
=> Fix people claims lookup for LdapClaimsHandler

catalog/solr/catalog-solr-commands/src/test/resources/configset/schema.xml, platform/solr/solr-schema/src/main/resources/solr/conf/schema.xml
Forward port of #6602
Solr 8.x will always populate the _root_ field with the unique key (which is id_txt for DDF), if that field is in the schema. When Solr 8.x detects the presence of the _root_ field in the schema, it will use that field to query for Lucene documents when making updates. Solr 7.x and earlier does not populate that field, so a Solr 7.x index will have the field in its schema but not in its Lucene index (assuming the nested documents feature is not being actively used, and DDF does not use it). This causes Solr 8.x to think the document does not exist, so it creates a new Lucene document with a different Lucene Doc ID but the same Solr ID. SolrCloud appears to de-duplicate by ID, so only the old stored document is returned when there is a match for either Lucene …
=> Remove _root_ field from Solr schema (#6602)

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/forms/builder/AttributeValueNormalizer.java, catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/forms/builder/AttributeValueNormalizerTest.java, ui/packages/catalog-ui-search/src/main/webapp/component/query-advanced/query-advanced.view.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/filter/filter-input/filter-input.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/filter/filter-input/filter-location-input.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/filter/filter-input/filterInputHelper.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/filter/filter.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/location/location.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/utils/validation/index.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/utils/validation/validation.tsx
This allows a search form to require a location without having to specify the location type, allowing the user to select their own when running a search.
@kcwire 
@jMoneee 
@codice/ui 
@andrewzimmer
@millerw8
Create a search form and add either the `anyGeo` or `location` field, or both. Do not select a location option. Verify no warnings are displayed and that you can save the search form.
Open a workspace and use the search form. Verify you can select a location option and that your search works as expected.
Use the advanced search and add either the `anyGeo` or `location` field, or both. Verify you are warned to select a location, and that you cannot run the search without selecting a location option.
https://user-images.githubusercontent.com/4495447/134585250-486cf8b5-ec0e-4c11-9d5b-9b7 …
=> [2.19.x] G-9945 Allow empty location in search forms

distribution/docs/src/main/resources/content/_architectures/_catalogFrameworks/catalog-api.adoc, distribution/docs/src/main/resources/content/_architectures/_catalogFrameworks/catalog-framework-intro.adoc, distribution/docs/src/main/resources/content/_architectures/_catalogFrameworks/standard-catalog-framework.adoc, distribution/docs/src/main/resources/content/_developing/_devComponents/custom-applications.adoc, distribution/docs/src/main/resources/content/_developing/_devComponents/global-attribute-validators.adoc, distribution/docs/src/main/resources/content/_developing/_devGuidelines/osgi-basics.adoc, distribution/docs/src/main/resources/content/_integrating/_endpoints/csw-endpoint.adoc, distribution/docs/src/main/resources/content/_integrating/_endpoints/endpoint-intro.adoc, distribution/docs/src/main/resources/content/_integrating/_eventing/subscriptions.adoc, distribution/docs/src/main/resources/content/_introduction/_coreConcepts/search-intro.adoc, distribution/docs/src/main/resources/content/_managing/_configuring/enforcing-errors.adoc, distribution/docs/src/main/resources/content/_managing/_configuring/http-port.adoc, distribution/docs/src/main/resources/content/_managing/_configuring/landing-page.adoc, distribution/docs/src/main/resources/content/_managing/_datamanagement/overriding-attributes.adoc, distribution/docs/src/main/resources/content/_managing/_running/directory-monitor-ingest.adoc, distribution/docs/src/main/resources/content/_managing/_running/ingest-command.adoc, distribution/docs/src/main/resources/content/_managing/_running/ingesting.adoc, distribution/docs/src/main/resources/content/_managing/_running/subscription-commands.adoc, distribution/docs/src/main/resources/content/_managing/_running/troubleshooting-ui.adoc, distribution/docs/src/main/resources/content/_managing/_running/validator-plugins.adoc, distribution/docs/src/main/resources/content/_managing/_securing/managing-crl.adoc, distribution/docs/src/main/resources/content/_metadataReference/contact-attributes-table.adoc, distribution/docs/src/main/resources/content/_metadataReference/core-attributes-table.adoc, distribution/docs/src/main/resources/content/_metadataReference/datetime-attributes-table.adoc, distribution/docs/src/main/resources/content/_quickstart/quickstart-certificates.adoc, distribution/docs/src/main/resources/content/_reference/_tables/Metacard_File_Storage_Route.adoc
**PORT to MASTER of #6643**
updates documentation to remove parens from optional plurals. 
Aligns with Google Developer documentation style guidance on [Optional Plurals](https://developers.google.com/style/plurals-parentheses?hl=en).
@shaundmorris 
@jaymcnallie 
@sgalla 
@rececoffin 
@codice/docs  …
=> Documentation edits to rephrase optional plurals (#6643)

distribution/docs/src/main/resources/content/_architectures/_catalogFrameworks/catalog-framework-intro.adoc, distribution/docs/src/main/resources/content/_architectures/_resources/resource-readers-intro.adoc, distribution/docs/src/main/resources/content/_architectures/_resources/url-resource-reader.adoc, distribution/docs/src/main/resources/content/_architectures/_securityFramework/realms.adoc, distribution/docs/src/main/resources/content/_architectures/_securityFramework/subject.adoc, distribution/docs/src/main/resources/content/_developing/_devComponents/custom-plugins.adoc, distribution/docs/src/main/resources/content/_developing/_devComponents/custom-sts-claims-handlers.adoc, distribution/docs/src/main/resources/content/_developing/_devComponents/custom-transformers-input.adoc, distribution/docs/src/main/resources/content/_developing/_devComponents/managed-service-factories.adoc, distribution/docs/src/main/resources/content/_integrating/_eventing/subscriptions.adoc, distribution/docs/src/main/resources/content/_managing/_configuring/content-directory-monitor.adoc, distribution/docs/src/main/resources/content/_managing/_running/catalog-commands.adoc, distribution/docs/src/main/resources/content/_managing/_running/validator-plugins.adoc, distribution/docs/src/main/resources/content/_reference/_tables/ContentDirectoryMonitor.adoc, distribution/docs/src/main/resources/content/_reference/_tables/Wfs_v2_0_0_Connected_Source.adoc, distribution/docs/src/main/resources/content/_reference/_tables/Wfs_v2_0_0_Federated_Source.adoc
**PORT to MASTER of #6639**
makes edits to documentation content to fix
- spacing after periods (one space is correct)
- set off package names with backticks for consistent formatting.
@jaymcnallie 
@shaundmorris 
@sgalla 
@rececoffin 
@codice/docs 
review content, builds successfully …
=> copy edits to fix spacing issues in docs (#6639)

distribution/ddf-common/src/main/resources-filtered/etc/org.apache.karaf.features.xml, distribution/ddf-common/src/main/resources-filtered/etc/startup.properties, distribution/ddf-common/src/main/resources/common-bin.xml, distribution/kernel/pom.xml, platform/security/platform-security-core-api/pom.xml, platform/solr/solr-logging/pom.xml, pom.xml
Upgrades pax-logging to 1.11.13 to resolve CVE-2021-44228 
Note - this does not resolve the vulnerable log4j jars bundled in Solr.  That will be addressed separately.
@millerw8 
@jrnorth 
@beyelerb 
@millerw8 
@jrnorth 
@beyelerb 
Run a vulnerability scanner against the exploded distro (eg, [lunasec log4shell scan](https://github.com/lunasec-io/lunasec/releases)).  The only log4j vulnerabilities identified should be coming from solr:
- solr/contrib/prometheus-exporter/lib/log4j-core-2.13.2.jar
- /solr/server/lib/ext/log4j-core-2.13.2.jar
Fixes: #6673  …
=> DDF-6673 / G-10028 upgrades pax-logging to 1.11.13

ui/packages/catalog-ui-search/src/main/webapp/js/model/User.js, ui/packages/catalog-ui-search/src/main/webapp/js/model/User.spec.js
The User.Preferences model will now convert old-style CQL result filters to filter trees on the fly.
@millerw8
@kcwire 
@shaundmorris 
1. Open the Solr Admin UI and query the `preferences` core.
2. Copy the `preferences_json_bin` for your user.
3. Base64 decode that string to a JSON file and create a `resultFilter` key with a CQL string value if no such key exists, or replace the existing value with a CQL string value.
a. The CQL string can be as simple as `(\"anyText\" ILIKE '')`, or it can be a more complex query.
4. Base64 encode that JSON file and update your user preferences via the `Documents` page in the Solr Admin UI, filling in the ID of your preferences and your base64-encoded JSON:
5. Open Intrigue, click on your result filter, and verify that the CQL you added in step 3 was …
=> [2.19.x] G-10041 Add support for old CQL result filters

catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsFilterDelegate.java, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsFilterDelegateTest.java
Normalize datetimes to UTC for all outgoing WFS queries 
@derekwilhelm 
@glenhein 
@codice/ogc 
@derekwilhelm 
@glenhein 
Some WFS services do not process timezones correctly and assume datetimes are in UTC.
Fixes: #____ …
=> Normalize WFS 1.1.0 query times to UTC

catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/SolrFilterDelegate.java, catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/SolrFilterDelegateTest.java, catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/provider/Library.java, catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/provider/SolrProviderSpatial.java, platform/solr/solr-schema/src/main/resources/solr/conf/schema.xml
- Enables `normWrapLongitude` in the Solr schema. Running a DWITHIN query (i.e., a buffered geometry) near the antimeridian often results in a Solr error because the resulting geometry contains points outside the valid longitude range of [-180,180]. The SolrFilterDelegate uses JTS to calculate the buffered geometry but does not enforce the longitude range on the result so it is passed to Solr with out-of-range values. Enabling `normWrapLongitude` means that Solr will wrap longitudes outside of the range into it.
- Removes holes from polygons and multipolygons that cross the antimeridian. When handling polygons that cross the antimeridian, spatial4j requires any interior rings to be subsets of the exterior ring, which seems wrong (see …
=> [2.19.x] G-10122 Fix buffering across the antimeridian

catalog/solr/catalog-solr-core/src/main/java/ddf/catalog/source/solr/SolrFilterDelegate.java, catalog/solr/catalog-solr-core/src/test/java/ddf/catalog/source/solr/SolrFilterDelegateTest.java, catalog/solr/catalog-solr-core/src/test/java/ddf/catalog/source/solr/provider/Library.java, catalog/solr/catalog-solr-core/src/test/java/ddf/catalog/source/solr/provider/SolrProviderSpatial.java
- `SolrFilterDelegate` will remove holes from polygons and multipolygons that cross the antimeridian. When handling polygons that cross the antimeridian, spatial4j requires any interior rings to be subsets of the exterior ring, which seems wrong (see https://github.com/locationtech/spatial4j/blob/2926812ae302c6e0f24fb5995b1fd24be7fe0b56/src/main/java/org/locationtech/spatial4j/shape/jts/JtsGeometry.java#L482). Removing any holes means this check won't fail.
- Enables `normWrapLongitude` in `SolrFilterDelegate`'s `SpatialContext`. If a shape near the antimeridian is buffered, then it may have points that end up outside the range [-180, 180]. Enabling this allows spatial4j to handle those points correctly.
- Enables `allowMultiOverlap` in `SolrFilterDelegate`'s `SpatialContext`. Sometimes, …
=> G-10122 Fix issues related to geometry buffering

catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsSource.java, catalog/spatial/wfs/spatial-wfs-featuretransformer-api/src/main/java/org/codice/ddf/spatial/ogc/wfs/featuretransformer/ExceptionReportException.java, catalog/spatial/wfs/spatial-wfs-featuretransformer/src/main/java/org/codice/ddf/spatial/ogc/wfs/featuretransformer/impl/WfsRouteBuilder.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestSpatial.java
This is a forward port of PR #6604
Update the camel route used for WFS to detect the ExceptionReport and throw it so callers can handle it. Update WfsSource to catch the exception, log it, and set the hit count to -1 as per the SourceResponse API.
@glenhein 
@jlcsmith 
@codice/ogc 
@clockard
This can only be tested if you have a WFS server that returns an ExceptionReport for the hit count, but sends valid objects for the results query. I do not have a publicly available server for this. However, there is a mock server and test in TestSpatial that reproduces the scenario.
Fixes: #6599 …
=> DDF-6599 detect an ExceptionReport, log it, and set hit count to -1

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/QueryOperations.java, catalog/solr/catalog-solr-core/src/main/java/ddf/catalog/source/solr/SolrMetacardClientImpl.java
Add detailed logging for the pre and post query plugins, and for the solr query code. 
Note: The original intent was to include the trace-id in the solr logging, however there is a problem in the code with the thread context getting passed through to the solr code. 
@jlcsmith 
@derekwilhelm 
@codice/io 
@codice/solr 
@clockard 
Enable trace logging:
log:set TRACE ddf.catalog.impl.operations
log:set TRACE ddf.catalog.source.solr
Perform a query in the UI. Check the DDF log file for the extra logging.
Fixes: #6704  …
=> [2.26.x] DDF-6704 improve query logging

catalog/spatial/csw/spatial-csw-source-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/CswJTSToGML311GeometryConverter.java, catalog/spatial/csw/spatial-csw-source-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/CswJTSToGML311LineStringConverter.java
Adds a converter for CSW getRecords requests to transform lineString queries to posList (in lieu of pos[])  when converted JTS to GML 3.1.1.  
@jrnorth 
@kcwire 
Set up a CSW federated Source, select usePosList true, execute a lineString query to that source, and confirm the outbound xml represents the LineString geometry as a posList instead of a pos[]... e.g.
```
<posList>1 2 3 4 5 6</posList>
```
instead of
```
<pos>1 2</pos>
<pos>3 4</pos>
<pos>5 6</pos>
```
There was already logic in place to do this for LinearRing and Polygons (which use LinearRings), but nothing that enforced this for LineString.  Adding this makes LineString behave consistently with the other shapes.
Fixes: #____
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+R …
=> [2.19.x] G-20606 Added a converter for lineString which supports posList over pos

catalog/core/catalog-core-api/src/main/java/ddf/catalog/data/MetacardType.java, catalog/transformer/catalog-transformer-csv-common/pom.xml, catalog/transformer/catalog-transformer-csv-common/src/main/java/ddf/catalog/transformer/csv/common/MetacardIterator.java, catalog/transformer/catalog-transformer-csv-common/src/test/java/ddf/catalog/transformer/csv/common/MetacardIteratorTest.java, catalog/transformer/catalog-transformer-csv-queryresponse/pom.xml, catalog/transformer/catalog-transformer-csv-queryresponse/src/main/java/ddf/catalog/transformer/csv/CsvTransformerSupport.java, catalog/transformer/catalog-transformer-csv-queryresponse/src/test/java/ddf/catalog/transformer/csv/CsvMetacardTransformerTest.java, catalog/transformer/catalog-transformer-csv-queryresponse/src/test/java/ddf/catalog/transformer/csv/CsvQueryResponseTransformerTest.java, catalog/transformer/catalog-transformer-geojson-input/src/main/java/ddf/catalog/transformer/input/geojson/GeoJsonInputTransformer.java, catalog/transformer/catalog-transformer-geojson-metacard/src/main/java/ddf/catalog/transformer/metacard/geojson/GeoJsonMetacardTransformer.java, catalog/transformer/catalog-transformer-geojson-metacard/src/test/java/ddf/catalog/transformer/metacard/geojson/GeoJsonMetacardTransformerTest.java, catalog/transformer/catalog-transformer-propertyjson-metacard/src/main/java/ddf/catalog/transformer/metacard/propertyjson/PropertyJsonMetacardTransformer.java
Forward port and conflict resolution of #6387 :
Downstream projects need to create CSV exports that include the source identifier and metacard type name. The current code only supports exporting data that is contained in a metacard attribute. However, the source identifier and metacard type name are stored separately from the attributes.
This PR also creates a constant in MetacardType for the string "metacard-type", which was being defined multiple times in DDF and in downstream projects.
This PR also includes a forward port of #6501 which adds UTC dates when exporting metacards in CSV format.
@glenhein 
@jlcsmith 
@jrnorth 
@codice/data 
@clockard
Build with a downstream project that provides a UI capable of creating a CSV export. The export should …
=> DDF-6386 Add support for source id and metacard type for csv metacard transforms

catalog/confluence/catalog-confluence-common/pom.xml, platform/pom.xml
The 2.26.x build is failing due to the build pulling in an incompatible version of the cxf-wadl2java-plugin library.  This PR specifies the correct cxf version for the plugin that is compatible with java 8.
@glenhein 
@pklinef 
@codice/build 
@glenhein 
@pklinef 
Fixes: #____ …
=> [2.26.x] Fixes build failures due to incompatible cxf-wadl2java-plugin version

catalog/transformer/catalog-transformer-tika-input/src/test/java/ddf/catalog/transformer/input/tika/TikaInputTransformerTest.java, pom.xml
This PR upgrades Tika from version 1.24 to version 1.26, in order to [addresses an inconsistency](https://issues.apache.org/jira/browse/TIKA-3318) regarding MP3 format duration units.
@alexabird 
@jrnorth
@jlcsmith
Verify that the metacard for any ingested MP3 file should have the duration in seconds and not in milliseconds. …
=> [2.26.x] Upgrade Tika to 1.26

catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/pom.xml, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsFilterDelegate.java, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsFilterDelegateTest.java, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsSourceTest.java
Now, the WfsFilterDelegate will return null when ANDing filters and at least one is null. This means any AND group will be dropped if it contains a feature property not understood by the source being queried. If this results in no filter for the query at all, then it will not be run against the source.
Also, note that test coverage did not actually decrease with this change. The instruction coverage was updated to reflect its true value; LenientLimit has prevented this from failing the build.
@derekwilhelm  
@alexabird 
@codice/ogc 
@glenhein  
@jlcsmith
Test in downstsream
- …
=> [2.26.x] Prevent AND queries containing invalid filters from running against WFS 1.1.0 sources

catalog/solr/catalog-solr-core/src/main/java/ddf/catalog/source/solr/SolrMetacardClientImpl.java
When issuing a query for IDs that exceed the requested page size, solr returns the full list of results rather than the requested page size.  This causes the catalog framework to throw away those results beyond the page size limit and give the impression to any calling code that the next page could be requested.  However, since ID queries are changed to solr real time get requests, requesting the next page doesn't work.  Solr ignores all of the paging parameters when utilizing the real time get handler.  This means that solr will again return the full list of documents and cause the catalog framework to return the same list of results it did for page 1 as page 2.  This PR works around this limitation such that if paging parameters are received it will not do a real time get request. …
=> [2.26.x] Support ID query paging

catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/pom.xml, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsFilterDelegate.java, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsFilterDelegateTest.java, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsSourceTest.java
Now, the WfsFilterDelegate will return null when ANDing filters and at least one is null. This means any AND group will be dropped if it contains a feature property not understood by the source being queried. If this results in no filter for the query at all, then it will not be run against the source.
Also, note that test coverage did not actually decrease with this change. The instruction coverage was updated to reflect its true value; LenientLimit has prevented this from failing the build.
@derekwilhelm  
@alexabird 
@codice/ogc 
@glenhein  
@jlcsmith
Test in downstsream
- …
=> Prevent AND queries containing invalid filters from running against WFS 1.1.0 sources

catalog/transformer/catalog-transformer-csv-common/src/main/java/ddf/catalog/transformer/csv/common/MetacardIterator.java, catalog/transformer/catalog-transformer-xlsx/pom.xml, catalog/transformer/catalog-transformer-xlsx/src/main/java/ddf/catalog/transformer/xlsx/XlsxMetacardUtility.java, catalog/transformer/catalog-transformer-xlsx/src/test/java/ddf/catalog/transformer/xlsx/XlsxMetacardUtilityTest.java
Makes the XLSX transformer filter out empty, null, object, and binary attributes from the resulting xlsx file.
@glenhein 
@jlcsmith
@jrnorth
Ingest some data, ideally of varying types. Export as xlsx via the rest endpoint:
https://localhost:8993/services/catalog/query?q=8&format=xlsx
This PR is to apply the same logic done for the CSV and RTF transformers. …
=> [2.26.x] Xlsx column filtering

catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-common/src/main/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/common/Wfs11Constants.java, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/pom.xml, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsSource.java, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/resources/OSGI-INF/metatype/metatype.xml, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsSourceTest.java
Support default sort parameters for WFS 1.1.0 sources.
@derekwilhelm 
@jlcsmith 
Configure a WFS source that does not support RELEVANCE. Leave the default sort property and default sort order blank in the config. Confirm that a search that sorts by RELEVANCE returns unsorted results. Change the config to use "name" and "ASCENDING" for the default property and order. Confirm that a search that sorts by RELEVANCE returns results sorted by name.
Fixes: #____ …
=> [2.26.x] Support default sort parameters for WFS 1.1.0 sources.

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/event/retrievestatus/DownloadStatusInfoImpl.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/resource/download/ReliableResourceDownloadManager.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/resource/download/ReliableResourceDownloader.java, catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/resource/download/ReliableResourceDownloaderTest.java
Removes entries from the `downloaders` map inside of `DownloadStatusInfoImple.java` in the `cleanupAfterDownload` method call from  `ReliableResourceDownloader`.
Whatever gets merged from this PR should go into release/2.15.x as well.  
@dcruver @pklinef @middlets719 @jhunzik @figliold @mcalcote
@rzwiefel  @stustison @kcwire @djblue @emmberk @mojogitoverhere @rodgersh @oconnormi @coyotesqrl @cmthom10 @lessarderic 
@pklinef
@figliold 
Contact me privately for steps for testing.
My project ran into a case where it was reported that the container running ddf would eventually crash due to the main process throwing an `OutOfMemoryError`. I was able to replicate the problem and upon inspecting the heap afterwards found that the entries `downloaders` map inside of `DownloadStatusInfoImple.java` …
=> 2.25.x address download status info memory leak

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/federation/impl/TimedSource.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/QueryOperations.java, catalog/solr/catalog-solr-core/src/main/java/ddf/catalog/source/solr/SolrCatalogProviderImpl.java, catalog/solr/catalog-solr-core/src/main/java/ddf/catalog/source/solr/SolrMetacardClientImpl.java
Updates the metrics for queries. Adds timing for the plugins, threads, and processing to the QueryRequest object. The resulting log statement prints out all the metrics. This log statement can then be extracted from the logs (grep for the word 'QueryMetrics') and converted to csv files for analysis in Excel.
The resulting log statement will include the following fields:
2023-08-08T08:47:17,949 | DEBUG | ... | QueryMetrics: trace-id: e67bee6eaaa3478a9d072f087099ab2f, qm.do-query.elapsed: 118220823, qm.postquery.AccessControlAccessPlugin.elapsed: 1022, qm.postquery.AccessControlPlugin.elapsed: 1656,  .... (another 70+ fields)
Each qm.XX.YYY field represents a specific plugin or span of code with the following value representing the elapsed execution time in nanoseconds for the corresponding …
=> [2.26.x] Added query metrics to the QueryRequest and converted to ns timing

catalog/rest/catalog-rest-service/src/main/java/org/codice/ddf/rest/service/AbstractCatalogService.java, distribution/docs/src/main/resources/content/_integrating/_endpoints/catalog-rest-endpoint.adoc, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFederation.java
When attempting to download a resource as part of a transform request, if the resource cannot be found or cannot be read for some reason, the transform endpoint will return a generic "Unable to transform Metacard. Try differen transformer" message.  While this message may be valid in some cases, the resource transformer and any other transformer that requires the file data could provide a much better message considering this message usually ends up back to the user.  In the case of a download from the UI, this is definitely true and shows within the browser window that opens.  This PR checks the transformers failure cause and provides a better message for when the resource file can either not be found or not be read.
@jlcsmith 
@codice/ui 
@glenhein …
=> [2.26.x] Provide better transform failure message

platform/security/security-jaas-ldap/src/main/java/ddf/ldap/ldaplogin/SslLdapLoginModule.java
The LDAP login module allows a password to be empty when attempting to authenticate a user.  This leaves the authentication decision up to the LDAP server as to how to process an empty password.  If the LDAP server allows unauthenticated bind operations, this will make the LDAP login module assume the password was correct and the user is authorized for login even though the password was not correct/supplied.  This means that any user would be able to login as another valid LDAP user without supplying a password.  While most LDAP servers should not be configured with this enabled, if it is enabled then this would be a security hole and DDF should not allow unauthenticated access.  Guest access should be utilized instead.
This PR changes the SslLdapLoginModule to short circuit the login …
=> [2.26.x] Disallow unauthenticated LDAP login attempts

catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/transformer/AbstractGmdTransformer.java, catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/transformer/GmdTransformer.java, catalog/spatial/csw/spatial-csw-transformer/src/main/resources/OSGI-INF/blueprint/blueprint.xml
Adds a QueryResponseTransformer implementation for GMD format.
@derekwilhelm 
@birda 
Fixes: #____
=> [2.26.x] Adds Gmd QueryResponseTransformer

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/federation/impl/SortedQueryMonitor.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/federation/impl/SortedQueryMonitorFactory.java, catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/federation/impl/SortedQueryMonitorTest.java
When performing a query, the QueryOperations hands off the source execution of the queries to the SortedFederationStrategy.  This class uses an ExecutorService to run the source queries in parallel within a thread pool where the results are gathered and processed with PostFederatedQueryPlugins in the SortedQueryMonitor class.  Since these run in separate threads, they don't share the same thread context as the original query.  This means that things like `trace-id` in the thread context are lost.  Furthermore, if any of the PostFederatedQueryPlugins perform an action that sets or binds a user subject to the thread, then the thread in the thread pool will now have that user defined in its thread context going forward, including when it gets reused.  This may easily happen if a …
=> [2.26.x] Ensure SortedQueryMonitor uses query ThreadContext

catalog/rest/catalog-rest-api/src/main/java/org/codice/ddf/rest/api/CatalogService.java, catalog/rest/catalog-rest-api/src/main/java/org/codice/ddf/rest/api/CatalogServiceException.java, catalog/rest/catalog-rest-endpoint/pom.xml, catalog/rest/catalog-rest-endpoint/src/main/java/org/codice/ddf/endpoints/rest/RESTEndpoint.java, catalog/rest/catalog-rest-endpoint/src/main/java/org/codice/ddf/endpoints/rest/RESTService.java, catalog/rest/catalog-rest-endpoint/src/test/java/org/codice/ddf/endpoints/rest/RESTEndpointTest.java, catalog/rest/catalog-rest-service-impl/src/main/java/org/codice/ddf/rest/service/impl/CatalogServiceImpl.java, catalog/rest/catalog-rest-service-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/rest/catalog-rest-service-impl/src/test/java/org/codice/ddf/rest/service/impl/CatalogServiceImplTest.java, catalog/rest/catalog-rest-service/src/main/java/org/codice/ddf/rest/service/AbstractCatalogService.java
Add endpoint to test for the downloadability of a local resource.
Upload two local products. For one of the products, manually delete the resource file in data/content. 
Using the following CURL as a guide (adjust for you installation), try hitting the endpoint for
each product. The product that was manually delete should return a 404. For the other product, the endpoint should return a 200.
```
curl \
--verbose \
--get \
--insecure "https://localhost:8993/services/catalog/doesExist/<metacardID>/<sourceID>"
``` 
Fixes: #____ …
=> [2.26.x] Add endpoint to test for the downloadability of a local resource

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/history/Historian.java, catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/history/HistorianTest.java, catalog/solr/catalog-solr-core/src/main/java/ddf/catalog/source/solr/SolrCatalogProviderImpl.java
Introduces system properties for skipping historian versioning on deletes and updates (both direct metacard updates and associated content updates). 
e.g.
`# Skip historian for the following types on updates`
`org.codice.ddf.history.update.blacklist.metacardTypes=query,workspace`
`# Skip historian for the following types on deletes`
`org.codice.ddf.history.deletes.blacklist.metacardTypes=workspace`
Additionally this copies the DeleteRequest properties onto the DeleteResponse. This was initially done to allow for the SKIP_VERSIONING property to be used with local deletes, but this also makes behavior more consistent across the Create, Update, and Delete requests on the Solr implementation of the CatalogProvider.
Fixes: #____ …
=> [2.26.x] Historian blacklist for updates and deletes

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/history/Historian.java, catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/history/HistorianTest.java
The Historian will not actually skip versioning for update or delete requests as it ignores the properties that would contain that flag. This corrects that to allow metacards to be deleted or updated and have no versions created. 
@jlcsmith 
@derekwilhelm 
@alexabird
=> [2.26.x] updated historian to check for the skip-versioning flag from the request properties instead of the response properties

catalog/core/catalog-core-metacardgroomerplugin/src/main/java/ddf/catalog/plugin/groomer/metacard/StandardMetacardGroomerPlugin.java, platform/preferences/preferences-impl/pom.xml, platform/preferences/preferences-impl/src/main/java/org/codice/ddf/preferences/impl/PreferencesImpl.java, platform/preferences/preferences-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/util/platform-util-uuidgenerator/util-uuidgenerator-api/src/main/java/org/codice/ddf/platform/util/uuidgenerator/UuidGenerator.java, platform/util/platform-util-uuidgenerator/util-uuidgenerator-impl/src/main/java/org/codice/ddf/platform/util/uuidgenerator/impl/UuidGeneratorImpl.java, platform/util/platform-util-uuidgenerator/util-uuidgenerator-impl/src/test/java/org/codice/ddf/platform/util/uuidgenerator/impl/UuidGeneratorImplTest.java
Adds a known UUID to preference metacards, in order to prevent multiple appearing in the system for the same user
@jlcsmith 
@glenhein 
@codice/solr 
@derekwilhelm 
@jlcsmith 
1. Sign in an check solr for a ddf-preference metacard being created
2. Not the ID of the preference metacard, remove it from solr using `catalog:remove`
3. Wait for another ddf-preference metacard to be created for the same user
4. Ensure the new metacard has the same ID as the previously removed one
Fixes: #____ …
=> [2.26.x] Added ability to generate known uuid

catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsFilterDelegate.java, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsFilterDelegateTest.java
For WFS 1.1.0, adjusts the coordinates in a wkt to conform to the range [-180, 180] before a filter is created. This is necessary because that's the range supported by WFS. 
@alexabird  
@malmgrens4  
@codice/ogc 
@jlcsmith 
@glenhein 
Ensure any outgoing WFS requests containing geo filters that overlap with the antimeridian are not outside the range [-180, 180], and that the request is successful.
Fixes: #____
- ❓ …
=> [2.26.x] Normalize Coordinates For WFS 1.1.0 Sources

distribution/ddf-common/src/main/resources-filtered/etc/org.apache.karaf.features.xml, distribution/ddf-common/src/main/resources/common-bin.xml, distribution/kernel/pom.xml, platform/security/platform-security-core-api/pom.xml, platform/solr/solr-logging/pom.xml, pom.xml
Upgrades pax-logging to 1.11.17 to resolve https://github.com/advisories/GHSA-jfh8-c2jp-5v3q
@derekwilhelm 
@derekwilhelm 
Run a vulnerability scanner against the exploded distro (eg, [lunasec log4shell scan](https://github.com/lunasec-io/lunasec/releases)).  …
=> [2.26.x] Update to pax logging 1.11.17

platform/platform-paxweb-jettyconfig/src/test/java/org/codice/ddf/pax/web/jetty/TraceContextFilterTest.java, platform/security/core/security-core-services/src/main/java/ddf/security/audit/impl/SecurityLoggerImpl.java, platform/security/core/security-core-services/src/main/java/ddf/security/audit/impl/TraceIdAuditPropertiesPlugin.java, platform/security/core/security-core-services/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/security/core/security-core-services/src/test/java/ddf/security/audit/impl/TraceIdAuditPropertiesPluginTest.java, platform/security/platform-security-core-api/pom.xml, platform/security/platform-security-core-api/src/main/java/ddf/security/audit/AuditPropertiesPlugin.java, platform/security/platform-security-core-api/src/main/java/org/codice/ddf/security/util/ThreadContextProperties.java, platform/security/servlet/security-servlet-web-socket-api/src/main/java/org/codice/ddf/security/servlet/web/socket/SecureWebSocketServlet.java
(cherry picked from commit 5c4cdd3ad54240de19a8ab0a25d3dbbdd4b40d69)
Improve audit logs for authentication and session events
https://github.com/codice/ddf/commit/4ff4c05242c8216a403d2899ef8d81c2181d23d3
https://github.com/codice/ddf/pull/6455
DDF-6609 corrects email audit logging
https://github.com/codice/ddf/commit/0c1b6fe57ba546c6c08066ebe340e33a93cc7a91)
https://github.com/codice/ddf/pull/6610
DDF-6626 Adds initial implementation of trace context
https://github.com/codice/ddf/commit/dc5367c48ffaa7f27680634c18c89e07423f9b1b)
https://github.com/codice/ddf/pull/6627
DDF-6636 adds IP and port to all audit events https://github.com/codice/ddf/commit/9cc7049a38507771539da689ac7707ab3faab7ac
https://github.com/codice/ddf/pull/6637
DDF-6636 adds support for proxied request audit logging …
=> [2.29.x] Forward Port Audit Logs from 2.26

catalog/transformer/catalog-transformer-csv-common/pom.xml, catalog/transformer/catalog-transformer-csv-common/src/main/java/ddf/catalog/transformer/csv/common/CsvTransformer.java, catalog/transformer/catalog-transformer-rtf/src/main/java/ddf/catalog/transformer/output/rtf/model/ExportCategory.java
To hot deploy these changes:
1. build `ddf/catalog/transformer/catalog-transformer-csv-common`
2. build `ddf/catalog/transformer/catalog-transformer-csv-queryresponse`
3. build `ddf/catalog/transformer/catalog-transformer-xlsx`
4. build `ddf/catalog/transformer/catalog-transformer-rtf`
5. copy the target jars from steps 2, 3 and 4 into the running instance's deploy dir
=> [2.29.x] Add null check before casting attribute value to string

catalog/core/catalog-core-standardframework/pom.xml, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/federation/impl/TimedSource.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/QueryOperations.java, catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/impl/operations/QueryOperationsTest.java
Adds a few additional metrics to the existing query metric functionality and defines process for logging these metrics. In order to enable metric logging, the `metrics-enabled` property must be set to `true` on the query's request or response properties. In addition, additional metrics can be added to the log statement by adding a map to request or response properties via `additional-query-metrics`.
Fixes: #____
- ❓ …
=> [2.29.x] Improve query metrics logging

catalog/rest/catalog-rest-endpoint/pom.xml, catalog/rest/catalog-rest-endpoint/src/test/java/org/codice/ddf/endpoints/rest/it/RestEndpointIT.java, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsFilterDelegateTest.java, catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/source/WfsFilterDelegateTest.java, distribution/ddf-common/src/main/resources-filtered/etc/startup.properties, distribution/ddf-common/src/main/resources/common-bin.xml, distribution/kernel/pom.xml, distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/AbstractIntegrationTest.java, features/branding/src/main/feature/feature.xml, features/utilities/src/main/feature/feature.xml, platform/platform-paxweb-jettyconfig/src/main/resources/jetty.xml, platform/platform-paxweb-jettyconfig/src/test/resources/jetty-session.xml, pom.xml
Upgrade gson/json/karaf and related libraries. I bug was found in jetty.xml that was causing the upgraded system to not start-up.
Fixes: #____
=> [2.29.x] Upgrade karaf to 4.3.10, and json/gson

catalog/core/catalog-core-camelcomponent/pom.xml, catalog/core/catalog-core-commons/pom.xml, catalog/core/catalog-core-impl/filter-proxy/pom.xml, catalog/core/catalog-core-impl/pubsub/pom.xml, catalog/core/catalog-core-resourcesizeplugin/pom.xml, catalog/core/catalog-core-resourcestatusplugin/pom.xml, catalog/opensearch/catalog-opensearch-source/pom.xml, catalog/pom.xml, catalog/spatial/csw/spatial-csw-endpoint/pom.xml, catalog/spatial/geocoding/spatial-geocoding-feature/pom.xml, catalog/spatial/geocoding/spatial-geocoding-geocoder/pom.xml, catalog/spatial/kml/spatial-kml-util/pom.xml, distribution/test/itests/test-itests-common/pom.xml, features/solr/pom.xml, features/utilities/pom.xml, features/utilities/src/main/feature/feature.xml, platform/platform-paxweb-jettyconfig/src/test/java/org/codice/ddf/security/session/JettySessionManagementTest.java, platform/security/claims/security-claims-ldap/pom.xml, platform/security/core/security-core-services/pom.xml, platform/security/handler/security-handler-oauth/pom.xml, platform/security/handler/security-handler-oidc/pom.xml, platform/security/realm/security-realm-oidc/pom.xml, platform/security/security-oidc-bundle/pom.xml, pom.xml
=> [2.29.x] More upgrades based on karaf upgrade

catalog/pom.xml, catalog/transformer/pom.xml
Removes mime4j 0.7.2 transitive dependency which causes CVE.
Run `mvn org.commonjava.maven.plugins:directory-maven-plugin:highest-basedir@directories dependency-check:aggregate -B -pl '!distribution/docs, !platform/admin/modules/admin-modules-docs' -P '!itests'` on project and ensure that mime4j 0.7.2 does not show up in CVE list. …
=> [2.29.x] Removed mime4j transitive dependency from abdera-extensions-geo to resolve CVEs

catalog/solr/catalog-solr-commands/pom.xml, catalog/solr/catalog-solr-commands/src/main/java/org/codice/ddf/commands/solr/BackupCommand.java, catalog/solr/catalog-solr-commands/src/main/java/org/codice/ddf/commands/solr/RestoreCommand.java, catalog/solr/catalog-solr-commands/src/test/java/org/codice/ddf/commands/solr/BackupCommandTest.java, catalog/solr/catalog-solr-commands/src/test/java/org/codice/ddf/commands/solr/RestoreCommandTest.java, catalog/solr/catalog-solr-commands/src/test/java/org/codice/ddf/commands/solr/SolrCommandTest.java, catalog/solr/catalog-solr-core/pom.xml, catalog/solr/catalog-solr-core/src/test/java/ddf/catalog/source/solr/SolrProviderRealTimeQueryTest.java, catalog/solr/catalog-solr-core/src/test/java/ddf/catalog/source/solr/SolrProviderTest.java, distribution/solr-distro/pom.xml, features/solr/src/main/feature/feature.xml, platform/admin/core/admin-core-appservice/pom.xml, platform/error/platform-error-impl/pom.xml, platform/error/platform-error-page-injector/pom.xml, platform/error/platform-error-servlet/pom.xml, platform/platform-paxweb-jettyconfig/pom.xml, platform/security/core/security-core-services/pom.xml, platform/security/filter/security-filter-csrf/pom.xml, platform/security/platform-security-core-api/pom.xml, platform/security/servlet/security-servlet-web-socket-api/pom.xml, platform/solr/solr-dependencies/pom.xml, pom.xml
Cherry-pick upgrade solr commits from the 3.x branch + upgrade to the latest zookeeper to resolve the zookeeper CVEs
Run `mvn org.commonjava.maven.plugins:directory-maven-plugin:highest-basedir@directories dependency-check:aggregate -B -pl '!distribution/docs, !platform/admin/modules/admin-modules-docs' -P '!itests'` on project and ensure that zookeeper does not show up in CVE list.
@zkirksey 
@glenhein 
@codice/solr 
@jlcsmith 
@derekwilhelm  …
=> [2.29.x] Upgrade Solr 9.2.1 & Zookeeper 3.8.4

features/utilities/src/main/feature/feature.xml
Xlsx tranformer was failing due to an missing/incorrect xmlbeans dependency.  The xmlbeans version was updated from 3.1.0 to 5.0.3 but the feature file containing the bundle version of xmlbeans was not updated accordingly.   
@codice/build 
@pklinef 
@derekwilhelm 
Fixes: #____ …
=> [2.29.x] Fixes failed xlsx transforms due to incorrect xml beans version

catalog/core/catalog-core-metacardgroomerplugin/src/main/java/ddf/catalog/plugin/groomer/metacard/StandardMetacardGroomerPlugin.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/history/Historian.java, catalog/core/catalog-core-standardframework/src/main/resources/OSGI-INF/metatype/metatype.xml, catalog/core/catalog-core-versioning/versioning-common/src/main/java/ddf/catalog/core/versioning/impl/MetacardVersionImpl.java
This PR changes how deleted metacard IDs are generated.  Since deleted metacards are meant to be singletons, the Historian has been changed to use a known ID (using the known ID function in the UuidGenerator api) for deleted metacards.  This ensures that the same ID is used for each and not allowing multiple deleted metacards to exist for the same metacard.  A configuration item was also added so that this capability could be turned off and the functionality returned to the way it has always been before if a deployment doesn't want to enable this capability.
@codice/data 
@glenhein 
@jlcsmith
1. Create a metacard of any type that is versioned
2. Delete the metacard and verify the deleted metacard is added to solr and note the metacard ID
3. Restore/revert the metacard and verify the …
=> [2.29.x] Change deleted metacards to use known IDs

catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsSource.java, catalog/transformer/catalog-transformer-overlay/src/main/java/ddf/catalog/transformer/OverlayActionProvider.java
Forward ports a missing line from this [PR](https://github.com/codice/ddf/pull/6751/files#diff-9d159d4abec701db1c9737de8745bf74ee320e17d84d8b638942c2ac47a9e736) which sets processing details when a WFS source has sorting disabled.
Also, the OverlayActionProvider was throwing an NPE when a metacard didn't have a WKT. I added a check for this.
@glenhein 
@alexabird 
@glenhein 
@alexabird 
Fixes: #____
- ❓ (Question …
=> [2.29.x] Set processing details when WFS sorting is disabled

platform/platform-paxweb-jettyconfig/src/main/java/org/codice/ddf/pax/web/jetty/ResponseFilter.java
Adds the Strict-Transport-Security response header.  See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security
Verified that the response header is showing up after this change when hitting the DDF REST endpoint:
@derekwilhelm 
@alexabird 
@derekwilhelm 
@alexabird 
Fixes: #____ …
=> [2.29.x] Adds strict transport security header to responses

distribution/ddf-common/src/main/resources/bin/ddf, distribution/ddf-common/src/main/resources/bin/ddf.bat, distribution/ddf-common/src/main/resources/bin/setenv, distribution/ddf-common/src/main/resources/bin/setenv.bat
Only specify garbage collection options when starting DDF
@derekwilhelm 
@zkirksey 
@jlcsmith 
@glenhein 
Verify starting DDF has the GC options, while just accessing the karaf client does not
Fixes: #____ …
=> [2.29.x] Only specify garbage collection options when starting DDF

distribution/ddf-common/src/main/resources/common-bin.xml
After starting DDF without an m2 repository, there was an `Error resolving artifact org.ops4j.pax.web:pax-web-tomcat-common:jar:8.0.24: [Could not find artifact org.ops4j.pax.web:pax-web-tomcat-common:jar:8.0.24]`
@derekwilhelm 
@codice/build 
@jlcsmith 
@derekwilhelm 
Start DDF without an m2
Fixes: #____ …
=> [2.29.x] Include tomcat in dist

catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-converter/src/main/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/converter/impl/AbstractFeatureConverterWfs11.java
Minor refactoring of the Abstract WFS 1.1.0 transformer to allow sub classes to override behavior as needed.
@derekwilhelm 
@glenhein 
@codice/data 
@derekwilhelm 
@glenhein 
Fixes: #____ …
=> [2.29.9.x] Refactors the WFS 1.1.0 transformer for extensibility

catalog/core/catalog-core-impl/filter-proxy/pom.xml, catalog/core/catalog-core-impl/filter-proxy/src/main/java/ddf/catalog/filter/proxy/GeotoolsPluginLoader.java, features/utilities/src/main/feature/feature.xml
In cases where geotools was asked to process shapefiles, the underlying data factory was not available leading to a a processing failure.  This PR adds the necessary factory to the GeotoolsPluginLoader
@glenhein 
@derekwilhelm 
@pklinef 
@glenhein 
@derekwilhelm 
@pklinef 
Fixes: #____ …
=> [2.29.9.x] Adds geotools support for shp files

distribution/ddf/pom.xml, features/solr/src/main/feature/feature.xml
The upgraded pax-web feature file is structured in a way that `spifly` and `asm` are no longer started with the `pax-web-core` or `pax-web-jetty`, instead 
@glenhein 
@codice/build 
@codice/solr 
@jlcsmith 
@derekwilhelm 
Fixes: #____
- …
=> [2.29.x] Include spifly with jetty-extras

distribution/test/itests/test-itests-common/pom.xml
Fixes an issue where downstream projects that use PaxExam and extend `AbstractIntegrationTest` will fail in the pax exam startup phase due to a `ClassNotFoundException` related to `ddf.security`.
This needs to be explicitly included in the `import-package` (**cannot** be optional) so the extended code has access to it otherwise pax blows up. 
@ahoffer
@glenhein 
@clockard 
@jrnorth  …
=> [2.29.x] Fix itests for downstream projects

platform/security/servlet/security-servlet-web-socket-api/src/main/java/org/codice/ddf/security/servlet/web/socket/SecureWebSocketServlet.java
The move to pax web 8.0.24 updated websocket use and registration. Unlike other servlets there is no direct whiteboard registration for websockets. While there are a couple ways to register a websocket between the java servlet specification, jetty, and pax web this approach uses the Java Servlet annotation @WebServlet which works with all three. 
Pax web requires a more complicated setup for websockets through other approaches but by using this annotation and registering the Websocket bundles as WABs it correctly configures the Servlet registration/ Websocket upgrade. 
SecureWebsocketServlet has been changed to a websocketCreator for use with the new WABs that must be deployed for websocket integration. 
1. Build ddf and install ddf-ui front and backend (with this PR: …
=> [2.29.x] Websocket updates

distribution/docker/solr-docker/src/main/docker/Dockerfile
Copies and sets the entrypoint script permissions to 755 so that the image can be started by the solr user
@lavoywj 
@jrnorth 
@codice/solr 
@clockard
@pklinef
Start the image as-is and verify that the container starts and solr is running as the solr user
Fixes: #____ …
=> [2.29.x] Fix solr image to allow startup as solr user

Jenkinsfile
The 2.29.x branch (not PR) Jenkins job has been failing for a long time due to the core tests stage failing. This is an attempt to get the job working again so we can enable nightly builds on the branch and deploy up-to-date snapshots.
=> Fix 2.29.x branch build
