ui/packages/catalog-ui-search/src/main/webapp/component/filter-builder/filter-serialization.js, ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-old.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/map.view.js, ui/packages/catalog-ui-search/src/main/webapp/js/CQLUtils.js, ui/packages/catalog-ui-search/src/main/webapp/js/CQLUtils.spec.js
Prevent a deeply nested structure representing a filter's attributes in Search Forms. This remedies an issue where the form fails to load after a few successive reloads.
@djblue 
@adimka 
@jrnorth 
@gjvera 
@BernardIgiri 
@leo-sakh 
@codice/ui
@adimka 
@bdeining 
1. Create a search form with a geography-based filter (`location` or `anyGeo` for example).
2. Draw an arbitrary shape on the map, save the form.
3. Navigate back to the 'Search Forms' view and re-load the form repeatedly.
4. Verify that the form continues to populate all fields appropriately.
5. Ensure other uses of search forms (workspace ad-hoc search) still work as intended.
Fixes: #4998 
**Before**
**After**
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guideline …
=> DDF-04998 Limit Filter Attribute Depth on Search Form Reloading

distribution/docs/src/main/resources/content/_managing/_securing/managing-keystores.adoc
Clarifies the Keystore and Truststore documentation.
@bakejeyner 
@brjeter 
@ricklarsen 
@stustison 
Related to https://github.com/codice/ddf/pull/4928 …
=> Clarified keystore and truststore documentation

catalog/core/catalog-core-solrcommands/pom.xml, features/admin/pom.xml, features/apps/pom.xml, features/install-profiles/pom.xml, platform/security/platform-security-core-api/pom.xml, platform/solr/solr-logging/pom.xml, pom.xml
Updated Log4j dependencies
@coyotesqrl
@stustison
Build / Install / Verify logging has not regressed
For Jira:
For GH Issues:
Fixes: #__4942__ …
=> DDF-04942 Updated Log4j dependencies

distribution/docs/src/main/resources/content/_integrating/_endpoints/catalog-rest-endpoint.adoc
Corrects documentation to rectify an incorrect URL for the RESTful `DELETE` endpoint.
@jrnorth @ricklarsen
@codice/docs
@jrnorth  
@ricklarsen 
Build Docs …
=> DDF-2824 Fix Path for RESTful Delete Endpoint

distribution/docs/src/main/resources/content/_managing/_configuring/hardening-solr.adoc, distribution/docs/src/main/resources/content/_managing/_configuring/solr-admin-ui.adoc
Corrects outdated documentation about Solr.
@brjeter  @tyler30clemens @austinsteffes @ricklarsen @clockard 
@codice/docs 
Proof read the changes.
Fixes: #5038 …
=> DDF-5038 Correct the Solr documentation

ui/packages/catalog-ui-search/src/main/webapp/behaviors/dropdown.behavior.utility.js
Fixes dropdown left/right calculation
@samuelechu
@Bdthomson 
@codice/ui
@adimka
@bdeining
Open dropdowns close to the sides of the window, verify they are completely visible.
Fixes: #5022 …
=> DDF-5022 Fix dropdown left/right calculation

ui/packages/catalog-ui-search/src/main/webapp/react-component/utils/fetch/fetch.tsx
Updates fetch to default to no caching
@Bdthomson 
@djblue 
@rzwiefel 
@djblue
@rzwiefel 
@Bdthomson Verify fetching response does not return cached response. 
Fixes: #5028 
- N/A
- N/A
- N/A
- N/A …
=> DDF-5028 Add no-cache default to fetch

ui/packages/catalog-ui-search/src/main/webapp/component/content/content.view.js
Add flexbox to get rid of empty space at the bottom of the visualizations pane (right hand side)
@djblue 
@samuelechu 
@adimka
@vinamartin
1. See that without multi select actions, visualizations height is correct.
2. See that with multi select actions, visualizations height is correct:
Add this to `ddf/ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/multi-select-actions/multi-select-actions.tsx` to simulate a multi select action.
```javascript
const TestMultiSelectButton = () => (
<MultiSelectButton buttonType={buttonTypeEnum.neutral}>
Flexbox is good
</MultiSelectButton>
)
const buttons = plugin([TestMultiSelectButton])
//const buttons = plugin([])
```
Fixes: #5007 
**Before**
**After** …
=> DDF-5007 Add flexbox to get rid of empty space

ui/packages/catalog-ui-search/src/main/webapp/dev/component/input-guide/input-guide.view.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/container/input-wrappers/autocomplete/autocomplete.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/container/input-wrappers/base/base.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/location/keyword.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/save-button/save-button.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/workspace-menu/workspace-menu.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/workspace-title/workspace-title.tsx
Improves the UI flow to create new search within a workspace. The main improvements are making the top search button have a background color and grouping the workspace related items together into one distinct section.
@adimka 
@TeresaHudson
@djblue 
Ensure that there are no regressions with performing workspace functions, opening up searches
Fixes: #4952  …
=> DDF-4952 Improve Search UI

catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/RealTimeGetDelegate.java, catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/SolrMetacardClientImpl.java, catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/RealTimeGetDelegateTest.java, catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/SolrMetacardClientImplTest.java, catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/SolrProviderRealTimeQueryTest.java
Backport of #5009 
@rymach @peterhuffer @paouelle
@codice/solr 
@clockard 
@pklinef 
=> [2.16.x] DDF-4983 Fix check for Solr RealTime Get

ui/README.md, ui/package.json, ui/packages/catalog-admin-module-layout/package.json, ui/packages/catalog-admin-module-maplayers/package.json, ui/packages/catalog-ui-search-e2e/README.md, ui/packages/catalog-ui-search-e2e/flow.svg, ui/packages/catalog-ui-search-e2e/package.json, ui/packages/catalog-ui-search-e2e/src/main/webapp/index.html, ui/packages/catalog-ui-search-e2e/src/main/webapp/index.js, ui/packages/catalog-ui-search-e2e/src/main/webapp/intrigue-basic-query.json, ui/packages/catalog-ui-search-e2e/src/main/webapp/intrigue.spec.js, ui/packages/catalog-ui-search-e2e/wait-for-intrigue.js, ui/packages/catalog-ui-search/package.json, ui/packages/catalog-ui-search/src/main/webapp/component/query-add/query-add.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/query-advanced/query-advanced.view.js, ui/packages/catalog-ui-search/src/main/webapp/extension-points/navigator/navigator.tsx, ui/packages/catalog-ui-search/src/main/webapp/js/ApplicationStart.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/dropdown/dropdown.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/navigation-left/navigation-left.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/workspace-interactions/workspace-interactions.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/workspace-item/workspace-item.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/workspace-menu/workspace-menu.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/workspaces-items/workspaces-items.tsx, ui/packages/imperio/driver.js, ui/packages/imperio/index.js, ui/packages/imperio/monitor.js, ui/packages/imperio/package.json, ui/pom.xml, ui/yarn.lock
DDF-04955 Implements initial API driven e2e testing
@adimka
@AzGoalie
@bdeining
@millerw8
@codice/test 
@codice/ui 
- CI build
- Exercise the UI via the API
Fixes: #4955 …
=> DDF-04955 Implements initial API driven e2e testing

catalog/transformer/catalog-transformer-xml/src/main/java/ddf/catalog/transformer/xml/adapter/GeometryAdapter.java, catalog/transformer/catalog-transformer-xml/src/test/java/ddf/catalog/transform/xml/XmlInputTransformerTest.java, catalog/transformer/catalog-transformer-xml/src/test/resources/metacard-emptygeo1.xml, catalog/transformer/catalog-transformer-xml/src/test/resources/metacard-emptygeo2.xml
Link to 2.16.x PR: #5025
@austinsteffes @tyler30clemens @Kjames5269 
@bdeining
@jlcsmith
Fixes: #5024
=> [2.16.x]DDF-5024 XML Transforms handles empty geos

ui/packages.xml
DDF-04955 Adds imperio to exported packages for downstream projects
@Bdthomson 
@leo-sakh 
@bdeining 
@samuelechu 
CI build
Fixes: #4955
=> DDF-04955 Adds imperio to exported packages for downstream projects

distribution/docs/src/main/resources/content/_managing/_running/available-console-commands.adoc, distribution/docs/src/main/resources/content/_managing/_running/catalog-commands.adoc, distribution/docs/src/main/resources/content/_managing/_running/migrate-commands.adoc, distribution/docs/src/main/resources/content/_managing/_running/platform-commands.adoc, distribution/docs/src/main/resources/content/_managing/_running/solr-commands.adoc, distribution/docs/src/main/resources/content/_managing/_running/store-commands.adoc, distribution/docs/src/main/resources/content/_managing/_running/subscription-commands.adoc
reorders catalog command docs for downstream
@ricklarsen  
@brjeter 
@Kjames5269 
quick build passes
Fixes: #5083 
=> DDF-5083 reorder catalog command docs

distribution/docs/src/main/resources/content/_managing/_running/available-console-commands.adoc, distribution/docs/src/main/resources/content/_managing/_running/catalog-commands.adoc, distribution/docs/src/main/resources/content/_managing/_running/migrate-commands.adoc, distribution/docs/src/main/resources/content/_managing/_running/platform-commands.adoc, distribution/docs/src/main/resources/content/_managing/_running/solr-commands.adoc, distribution/docs/src/main/resources/content/_managing/_running/store-commands.adoc, distribution/docs/src/main/resources/content/_managing/_running/subscription-commands.adoc
Port of https://github.com/codice/ddf/pull/5085
reorders catalog command docs for downstream
@ricklarsen
@brjeter
@Kjames5269
quick build passes
Fixes: #5083
Checklist:
[X] Documentation Updated
Update / Add Threat Dragon models
Please see Notes on Review Process for further guidance on requirements for merging and abbreviated reviews.
Review Comment Legend:
✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist.
❓ (Question Mark) …
=> [2.16.x] DDF-5083 reorder catalog command docs

ui/packages/catalog-ui-search/src/main/webapp/extension-points/extension-points.tsx, ui/packages/catalog-ui-search/src/main/webapp/extension-points/navigation-right/index.tsx, ui/packages/catalog-ui-search/src/main/webapp/extension-points/navigation-right/navigation-right.tsx, ui/packages/catalog-ui-search/src/main/webapp/js/Entry.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/navigation-right/buttons.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/navigation-right/index.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/navigation-right/navigation-right.tsx
Currently navigation-right is extensible via plugins (216036c), it would be nice to move to extension points without breaking code bases that use plugins
@Bdthomson @samuelechu 
@adimka
@djblue 
Add a plugin to override the navigation right functionality. 
Add an override for navigationRight in `index.tsx`'s  `Entry()`. 
Example: 
```
{
navigationRight: [() => <div>Some Text That Replaces Right Nav</div>],
}
```
This is already extensible via plugins (216036c)
Fixes: #5058 
_Navigation right_ …
=> DDF-05058 Refactors navigation-right to be extensible via extension points

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/query/data/metacard/QueryMetacardTypeImpl.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/query/data/model/QueryBasic.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/query/util/QueryAttributes.java
This PR adds the spellcheck and phonetics attributes to the Query metacard. The attributes indicate whether or not the spellcheck/phonetics filters were enabled for a given query.
@Bdthomson 
@bellcc 
@rzwiefel 
@Bdthomson 
@rzwiefel 
1. Integrate the changes made in the mvn:ddf.ui/catalog-ui-search module
2. Navigate to the Search UI settings -> configuration -> Catalog UI Search
3. Enable the "Enable Spellcheck" and "Enable Similar Word Matching" options -> Save Changes
4. Conduct a new search in the catalog with "Spellcheck" and "Similar Word Matching" set to "On"
5. Save the changes made to the workspace.
6. Once the changes are saved refresh the page and open the query filter options.
7. Validate that the options are both set to "On".
8. Steps 4 through 7 may be repeated with the …
=> DDF-05054 Adds spellcheck and phonetics to query metacard

catalog/transformer/catalog-transformer-geojson-input/src/test/java/ddf/catalog/transformer/input/geojson/GeoJsonExtensibleTest.java, catalog/transformer/catalog-transformer-geojson-input/src/test/java/ddf/catalog/transformer/input/geojson/GeoJsonInputTransformerTest.java, distribution/test/itests/test-itests-common/src/main/resources/json/record/SimpleGeoJsonWithMetadataRecord, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalog.java
Adds unit and integration tests for the GeoJson input transformer's capability for parsing metadata.
@cjlange
@codice/test 
@brjeter 
Integration tests can be run in `distribution/test/itests/test-itests-ddf` with `mvn clean verify -Dit.test=TestCatalog#testGeoJsonMetacardTransformersFromRest`
These are tests for the changes made in #4992.
Fixes: #5043  …
=> DDF-5043 Add tests for GeoJson input transformer

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/security/accesscontrol/AccessControlPreQueryPlugin.java
backward porting for https://github.com/codice/ddf/pull/5011
Fixes: https://github.com/codice/ddf/issues/5010 …
=> [2.16.x] DDF-5010 AccessControlPreQueryPlugin to copy all other query parameters

ui/package.json, ui/yarn.lock
Updates Ace Version so that `react-hot-loader` works properly with our most recent React upgrades
@hayleynorton 
@Bdthomson 
@andrewzimmer 
@zta6 
@djblue 
1. Build DDF
2. Run Dev Server
3. Verify from the dev server that you can open the gazetteer dropdown
4. Verify no relevant errors in console
Fixes: #5067  …
=> DDF-5067 Upgrade Ace Version for React Hooks

ui/packages/imperio/driver.js
Updates how imperio finds dom nodes to fix issues with functional components
@samuelechu 
@willwill96 
@gjvera 
@adimka 
- quickbuild
- yarn start
- ensure no errors in console related to refs
Fixes: #4955
=> DDF-04955 Update how imperio finds dom nodes to fix issues with functional components

catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/GetRecordsResponseConverter.java
It was discovered that a CSW federated query does not return any results when one of the results fail to transform. This PR will change it so that failed resources will be ignored which will improve the source to return as many results as it can.
@Kjames5269 
@codice/data 
@brjeter
@clockard 
@jlcsmith 
@bdeining 
1. Build and install DDF (standard, localhost) 
2. Setup federated CSW source (loop-back for this testing purpose)
3. Set federation caching configuration to none (to better see true results)
4. Ingest some records through command line 
5. Query local DDF source, and edit one of the results such that it would fail its own transform
6. Query the loop-back CSW source
7. Verify warn message in the logs, and that all other results but that result are returned
Work …
=> DDF-5111 Change CSW source to ignore results that fail to transform

platform/solr/solr-factory-impl/src/main/java/org/codice/solr/factory/impl/SolrCloudClientFactory.java, platform/solr/solr-factory-impl/src/test/groovy/org/codice/solr/factory/impl/SolrCloudClientFactorySpec.groovy
Fixes a problem where collection aliases weren't respected during the default collection creation process. This will cause a duplicate collection to be created for which an alias already exists.
@leo-sakh 
@lamhuy 
@codice/solr 
@bdeining 
@pklinef
Full Build with Tests.
Configure Solr
Create "catalog_test" collection
Create "catalog" alias for "catalog_test" collection
Restart DDF
Ensure that the default "catalog" collection has not been created.
Fixes: #5047  …
=> DDF-5047 Support for Solr catalog alias

catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/GetRecordsResponseConverter.java
Link to master PR: #5112 
It was discovered that a CSW federated query does not return any results when one of the results fail to transform. This PR will change it so that failed resources will be ignored which will improve the source to return as many results as it can.
@austinsteffes
@Kjames5269
@codice/data
@brjeter
@clockard
@jlcsmith
@bdeining
1. Build and install DDF (standard, localhost)
2. Setup federated CSW source (loop-back for this testing purpose)
3. Set federation caching configuration to none (to better see true results)
4. Ingest some records through command line
5. Query local DDF source, and edit one of the results such that it would fail its own transform
6. Query the loop-back CSW source
7. Verify warn message in the logs, and that all other results but that result …
=> [2.16.x] DDF-5111 Change CSW source to ignore results that fail to transform

ui/packages/catalog-ui-search/src/main/webapp/component/query-add/query-add.view.js
Addresses the bug described in [5113](https://github.com/codice/ddf/issues/5113)
@samuelechu @gjvera @leo-sakh @BernardIgiri @lavoywj
@codice/ui
@jrnorth @djblue @adimka 
See the steps to reproduce in [5113](https://github.com/codice/ddf/issues/5113)
Additionally, try to break the default form setting. Edit a form as default, switch the default from one to another without clearing it, delete a default form, try to set a shared form as default, etc.
There was a bit of discussion about the code this PR replaces [here](https://github.com/codice/ddf/pull/4819/files#r284337456). Note that I checked in with @samuelechu and he was unsure what at the time he was referring to with that comment.
Fixes: #5113
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/7194 …
=> DDF-05113 Bugfix Clearing User's Default Search Form

platform/security/servlet/security-servlet-logout/pom.xml, pom.xml
Ban duplicate dependencies in pom files
@codice/build 
@troymohl
@vinamartin
Fixes: #4748
=> DDF-04748 Ban duplicate dependencies in pom files

platform/security/handler/security-handler-oidc/pom.xml
This commit removes the duplicate declaration of dependency
ddf.action.core:action-core-impl from a pom file.
@bdeining
@stustison
@codice/security  
@bdeining
@stustison
Since this PR only exists to fix a broken master, full build should test sufficiently.
Master was broken on an error involving a duplicate declaration of a dependency. This should fix that.
N/A …
=> DDF-XXXX Remove duplicate declaration of dependency

ui/packages/catalog-ui-search/src/main/webapp/component/table/results/table-results.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/table/row.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/table/table-rearrange.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/table/table-visibility.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/table/table-viz.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/table/tbody.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/table/thead.view.js, ui/packages/catalog-ui-search/src/main/webapp/js/model/QueryResponse.js
Filters metacard attributes in views instead of at the query level. Doing the latter causes issues in views that want all available attributes rather than the set of filtered attributes generated when using result forms in a query.
@rymach 
@nsuvarna 
@Schachte 
@mcat97
@adimka 
@djblue
Verify that the table view can be filtered based on result form. Views like the histogram and inspector should be unaffected by queries using result forms.
Issue that resulted in creation of this ticket:
https://github.com/codice/ddf/issues/5079
Fixes: #5079  …
=> DDF-5079 Filter attributes in views instead of query

ui/packages/catalog-ui-search/src/main/webapp/plugins/user-settings.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/user-settings/extensions.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/user-settings/index.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/user-settings/user-settings.tsx
Allow for more types of components to be displayed in the user settings menu and for those components to have more control over their actions.
@willwill96 
@andrewzimmer 
@samuelechu 
@hayleynorton 
@codice/ui 
@adimka
@bdeining
Verify that all of the existing settings options have not regressed.
Fixes: #5102  …
=> DDF-5102 Allow more extension of user-settings. 

dependency-check-maven-config.xml
Removed suppressions that are no longer valid and grouped related suppressions.
Removed all suppressions and gradually added the ones that were needed.
@bakejeyner 
@brjeter
@stustison 
A successful CI
The goal is to only keep suppression’s that are still relevant.
Fixes: https://github.com/codice/ddf/issues/5135 …
=> DDF-5135 Removed suppressions that are no longer valid and grouped related suppressions

Documentation-versions.html, index.html
- adds links for 2.13.10 release docs
- reformats to library table
@codice/docs 
@brjeter
@lessarderic
@shaundmorris
verify content/formatting
#4759  …
=> DDF-04759 updated project site for 2.13.10 release

platform/security/security-guest-realm/src/test/java/org/codice/ddf/security/guest/realm/GuestRealmTest.java, ui/packages/catalog-ui-search/src/main/webapp/react-component/container/user/user.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/navigation-right/buttons.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/navigation-right/navigation-right.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/presentation/user/user.tsx
The only configuration that will allow guest access is:
1. `/=` with `Allow Guest Access` checked
2. `/=PKI` with `Allow Guest Access` checked
The other authentication types: `BASIC`, `OIDC` and `SAML` are terminating and don't allow guest access.
If `/=PKI` is configured the only solution is to close and reopen the browser.
If Guest access is the only one configured, there isn't a way to log in so we'll show:
@bakejeyner 
@SmithJosh 
@djblue 
@stustison 
Verify guest user behavior:
1. Change the authentication type to `/=` and check `Allow Guest Access`
2. Go to Intrigue, you should see `Guest` instead of `Sign In` in the top right corner
3. When clicking `Guest` you should not see a `Sign Out` button
Verify logged in user behavior:
1. Configure `SAML`, `OIDC`, and/or …
=> DDF-5136 Remove sign in for Guest users

platform/security/servlet/security-servlet-logout/pom.xml, platform/security/servlet/security-servlet-logout/src/main/java/org/codice/ddf/security/servlet/logout/LocalLogoutServlet.java, platform/security/servlet/security-servlet-logout/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/security/servlet/security-servlet-logout/src/test/java/org/codice/ddf/security/servlet/logout/LogoutServletTest.java, platform/security/session-management-impl/pom.xml, platform/security/session-management-impl/src/main/java/org/codice/ddf/security/session/management/impl/SessionManagementServiceImpl.java, platform/security/session-management-impl/src/test/java/org/codice/ddf/security/session/management/impl/SessionManagementServiceImplTest.java, ui/packages/catalog-ui-search/src/main/webapp/component/singletons/session-timeout.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/container/user/user.tsx, ui/packages/security-servlet-logout/src/main/resources/index.html, ui/packages/security-servlet-logout/src/main/webapp/js/main.js, ui/packages/ui/src/main/webapp/js/application.js, ui/packages/ui/src/main/webapp/js/models/SessionTimeout.js
Previously the UI used a JS component which handled logging the user
out. The "sign out" buttons throughout the UI called out to it to
handle logouts. This worked for frontend code, but there was no
way for the backend to use it.
This commit modifies the logout page to perform the same functions
as the JS component. Now, both the frontend and backend can use it
by redirecting the user to this page.
In particular, this fixes the session management service's
invalidate() method.
@brjeter @blen-desta @bakejeyner @stustison
Verify that the following all redirect to the logout page and that the user cannot access the UI again without authenticating once redirected
* The "sign out" buttons in both the Admin UI and Intrigue
* The session inactivity timeout in both the Admin UI …
=> [2.16.x] DDF-5132 Replace logout UI component with single logout page

dependency-check-maven-config.xml, distribution/solr-distro/assembly.xml, distribution/solr-distro/pom.xml, pom.xml
2.16.x port: https://github.com/codice/ddf/pull/5148
Reverts the suppression from https://github.com/codice/ddf/pull/5120 and upgrades the dependency instead. Most of the work for this was done on master as part of an unrelated PR: https://github.com/codice/ddf/pull/5105. This completes the work.
@tyler30clemens @Kjames5269 @austinsteffes 
@blen-desta 
@stustison
CI
Fixes: #5119  …
=> DDF-5119 Upgrade jackson-databind in transitive dependencies

dependency-check-maven-config.xml, distribution/solr-distro/assembly.xml, distribution/solr-distro/pom.xml, platform/security/platform-security-core-api/pom.xml, pom.xml
Master port: https://github.com/codice/ddf/pull/5151
Reverts the suppression from https://github.com/codice/ddf/pull/5120 and upgrades the dependency instead. Most of the work for this was done on master as part of an unrelated PR: https://github.com/codice/ddf/pull/5105.
@tyler30clemens @Kjames5269 @austinsteffes 
@blen-desta 
@stustison
CI
Fixes: #5119  …
=> [2.16.x]DDF-5119: Upgrade jackson-databind in transitive dependencies

ui/README.md, ui/path.sh
Updates path.sh to auto install local node/yarn
@Bdthomson 
@adimka 
@vinamartin 
- cd ui && rm node && source path.sh
=> DDF-04824 Updates path.sh to auto install local node/yarn

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/query/data/metacard/QueryMetacardTypeImpl.java
Added the metacard tags descriptor to the query metacard.
@bellcc 
@rzwiefel
Ingest a query metacard, and ensure that it has the correct metacard tags.
Fixes: #5165  …
=> DDF-5165 added metacard tags to query metacard

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/CreateOperations.java, catalog/plugin/catalog-plugin-metacard-validation/src/main/java/ddf/catalog/metacard/validation/MetacardValidityMarkerPlugin.java
Adds more robust ingest logging
@Kjames5269 
@brjeter
@clockard
Fixes: #5143 
=> DDF-5143 add more robust ingest logging

ui/pom.xml
Upgrades lodash to version 4.17.15
@bellcc 
@vinamartin 
@codice/ui 
@bdeining
@jlcsmith
Full build and verify UI functions normally
Fixes: # [5170](https://github.com/codice/ddf/issues/5170) …
=> DDF-5170 Update lodash version

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/CreateOperations.java, catalog/plugin/catalog-plugin-metacard-validation/src/main/java/ddf/catalog/metacard/validation/MetacardValidityMarkerPlugin.java, dependency-check-maven-config.xml
master PR here: https://github.com/codice/ddf/pull/5144
Adds more robust ingest logging
@Kjames5269
@brjeter
@clockard
Fixes: #5143
Screenshots
Checklist:
Update / Add Threat Dragon models
Please see Notes on Review Process for further guidance on requirements for merging and abbreviated reviews.
Review Comment Legend:
✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line …
=> [2.16.x] DDF-5143 add more robust ingest logging (#5144)

ui/packages/catalog-ui-search/src/main/webapp/js/model/User.js
User preferences does not save any preferences of nested objects. The lastSaved object is a shallow copy of the preferences object, and if any nested preferences are updated, it is updated as well. When the User.js file checks to see if the object has changed (in order to determine if it should be written), it fails and the user's preferences are never saved.
Updated preferences to a deepCopy for comparison to lastSaved
@Bdthomson 
@rymach 
@codice/ui 
@bdeining 
@djblue
For Jira:
For GH Issues:
Fixes: #04465
- ✏️ (Pencil) This comment is …
=> DDF-04465 Updated preferences to a deepCopy for comparison to lastSaved

ui/packages/catalog-ui-search/src/main/webapp/component/search-form/search-form.view.js
Makes it clear that clicking on a system search form isn't permitted.
@jlcsmith 
@codice/ui 
@djblue 
@vinamartin
1. Add system search form, following documentation http://artifacts.codice.org/service/local/repositories/snapshots/content/ddf/docs/2.17.0-SNAPSHOT/docs-2.17.0-20190813.190858-47-documentation.html#_creating_and_managing_system_search_forms_through_karaf
2. Try and click on a system search form and see the announcement.
Fixes: #5209 …
=> DDF-5209 Add error announcement when clicking system search form for editing

ui/packages/catalog-ui-search/exports/user.tsx
Adds User.tsx to the exports api so that it can be used downstream.
@djblue 
@codice/ui 
@adimka
@vinamartin
Jenkins
Fixes: #5162 
=> DDF-5162 Add User to catalog-ui-search/exports

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/query/data/model/QueryBasic.java, catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/metacard/query/data/model/QueryBasicTest.java
Changes how sorts attribute is stored in solr
@bellcc 
@jlcsmith 
Verify that workspaces still work as expected
Fixes: #5204  …
=> DDF-5204 changed how sort attributes are stored on metacards

features/security/pom.xml, features/security/src/main/feature/feature.xml
this dependency no longer exists.
therefore, begone dependency.
=> remove non-existent dependency

catalog/spatial/csw/spatial-csw-source/src/main/resources/OSGI-INF/metatype/metatype.xml
Added disable CN config to CSW Federated
@Schachte @hayleynorton 
@adimka
@jrnorth
Build / Install / Configure CSW Federated Profile / Verify as working
Fixes: #__5052__ …
=> DDF-05052 Added disable CN config to CSW Federated

ui/packages/catalog-ui-search/exports/metacard-interactions.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/metacard-interactions/index.tsx
Adds MetacardInteraction to the catalog-ui-search export list.
@samuelechu @Bdthomson @gordocanchola 
@djblue
@vinamartin
Fixes: #5162 
=> DDF-5162 Export MetacardInteraction

ui/packages/catalog-ui-search-e2e/package.json
=> DDF-04746 [minor] address yarn warning

ui/packages/catalog-ui-search/package.json, ui/packages/catalog-ui-search/src/main/webapp/react-component/dropdown/dropdown.js
Removes background color from dropdown components.
@rzwiefel 
@codice/ui 
@adimka
@vinamartin
Opening up dropdowns and making sure they weren't relying on this background color being set.
Fixes: #5219  …
=> DDF-5219 Remove background from dropdown elements

libs/gson-support/pom.xml, libs/gson-support/src/main/java/org/codice/gsonsupport/GsonTypeAdapters.java, libs/gson-support/src/test/java/org/codice/gsonsupport/GsonTypeAdaptersTest.java
Fixed GSON type adapter null handling
@bdeining 
@jrnorth 
@troymohl 
@rymach 
@codice/io 
@bdeining
@jrnorth
1. Create search and/or result form
2. Perform search using the form from 1.
3. Observe no NPE in karaf log output
4. Valid search results returned
Fixes: #5147 
=> DDF-05147: Fixed null date handling in `DateLongFormatTypeAdapter`

ui/packages/catalog-ui-search/src/main/webapp/component/visualization/table/row.view.js
Fixes Table view does not render correctly when paging through results with images
with the addition of filtered attributes to table view, thumbnail was still attempting to render even if the attribute was filtered resulting in an error.
@codice/ui 
@adimka 
@djblue 
- build / run / ingest image data
- set number of results to 2 in search options and open table visual 
- page through results and verify the table correctly renders
Fixes: #5241  …
=> DDF-5241 fix Table view does not render correctly when paging through results with images

distribution/docs/src/main/resources/content/_managing/_configuring/reusing-configurations.adoc
Improves upgrade docs:
issue 1: Document the Profile Install Command in the Reusing Configurations section (commit 1)
issue 2: Better clarify what the --profile option does in migration:import (commit 2)
@tyler30clemens @bakejeyner 
@codice/docs 
@brjeter
build, check docs and new hypertext link works
Fixes: #5236  …
=> [2.16.x] DDF-5236 Improve Upgrade Documentation

distribution/docs/src/main/resources/content/_managing/_configuring/reusing-configurations.adoc
Link to 2.13.x PR: #5240 
Improves upgrade docs:
issue 1: Document the Profile Install Command in the Reusing Configurations section (commit 1)
issue 2: Better clarify what the --profile option does in migration:import (commit 2)
@tyler30clemens @bakejeyner
@codice/docs
@brjeter
build, check docs and new hypertext link works
Fixes: #5236  …
=> DDF-5236 Improve Upgrade Documentation

ui/package.json, ui/yarn.lock
Revert ace to a previous version to fix ui dev build
@rymach 
@troymohl 
@adimka 
@Bdthomson 
- cd ui && yarn install && yarn build
=> DDF-04746 Revert ace to a previous version to fix ui dev build

ui/packages/catalog-ui-search/exports/metacard-interactions.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/metacard-interactions/index.tsx
Adds MetacardInteraction to the catalog-ui-search export list.
See https://github.com/codice/ddf/pull/5214
@samuelechu @Bdthomson @gordocanchola
@djblue
@vinamartin
Fixes: #5162
* ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist.
* ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
* ❗ (Exclamation Mark) This comment is critical and requires clarification or …
=> [2.17.x] DDF-5162 Export MetacardInteraction

ui/packages/catalog-ui-search/src/main/webapp/component/visualization/table/table-viz.view.js, ui/packages/catalog-ui-search/src/main/webapp/extension-points/extension-points.tsx, ui/packages/catalog-ui-search/src/main/webapp/extension-points/table-export/index.tsx, ui/packages/catalog-ui-search/src/main/webapp/extension-points/table-export/table-export.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/table-export/container.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/utils/export/export.tsx
Made an extension point for export functionality
@Schachte @Bdthomson 
@codice/ui 
@adimka
@djblue
Build / Install / Verify that export still works from the inspector and table view
Fixes: https://github.com/codice/ddf/issues/5140 …
=> DDF-05140 Made an extension point for export functionality

catalog/ui/catalog-ui-search/pom.xml, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/FeedbackApplication.java, platform/email/platform-email-api/pom.xml, platform/email/platform-email-impl/pom.xml, platform/email/platform-email-impl/src/main/java/org/codice/ddf/platform/email/impl/SmtpClientImpl.java, platform/email/platform-email-impl/src/test/java/org/codice/ddf/platform/email/impl/SmtpClientImplITCaseTest.java, ui/packages/catalog-ui-search/src/main/webapp/component/query-feedback/query-feedback.view.js
1. Fixes SmtpClientImpl so it can send emails again.
2. Fixes query feedback so users can submit feedback again.
@bakejeyner 
@glenhein 
@codice/ui 
@bdeining
@troymohl 
1. In the Admin UI, open the `Platform` app then click `Email Service` and set `Host` to `connexta-com.mail.protection.outlook.com`.
2. Open the `Search UI` app then click `Catalog UI Search` and select `Enable Query Feedback`, then set `Query Feedback Email Destination` to your email address.
3. Open Intrigue and run a query, then submit feedback.
4. Verify you receive an email containing the feedback.
a. If you do not receive an email, try adding `mail.mime.address.usecanonicalhostname=false` to `etc/custom.system.properties` and restarting DDF. (I think this may have something to do with how Outlook …
=> DDF-5198 DDF-5201 Fix SMTP client and query feedback

catalog/core/catalog-core-api/src/main/java/ddf/catalog/source/SourceAttributeRestriction.java
See https://github.com/codice/ddf/issues/5218 - just adds a new interface.
@brianfelix 
@brhumphe 
@bdeining 
@troymohl
See https://github.com/codice/ddf/issues/5218. 
Fixes: #5218  …
=> DDF-5218 Sources should be able to optionally express their supported attributes

ui/packages/catalog-ui-search/src/main/webapp/react-component/menu/menu.tsx
Increases the maximum height of the `Menu` component
@codice/ui 
@adimka
@vinamartin
Look at the before and after.
Fixes: #5292 
Before
After
=> DDF-5292 Increasing max height of Menu

ui/package.json, ui/packages/catalog-ui-search/src/main/webapp/component/details-interactions/details-interactions.less, ui/packages/catalog-ui-search/src/main/webapp/component/details-interactions/details-interactions.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/editor/editor.hbs, ui/packages/catalog-ui-search/src/main/webapp/component/editor/editor.less, ui/packages/catalog-ui-search/src/main/webapp/component/editor/editor.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/metacard-associations/metacard-associations.hbs, ui/packages/catalog-ui-search/src/main/webapp/component/metacard-associations/metacard-associations.less, ui/packages/catalog-ui-search/src/main/webapp/component/metacard-associations/metacard-associations.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/tabs/metacard/tabs-metacard.less, ui/packages/catalog-ui-search/src/main/webapp/component/tabs/metacard/tabs-metacard.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/tabs/metacards/tabs-metacards.less, ui/packages/catalog-ui-search/src/main/webapp/component/tabs/metacards/tabs-metacards.view.js, ui/packages/catalog-ui-search/src/main/webapp/js/model/MetacardProperties.js, ui/packages/catalog-ui-search/src/main/webapp/js/model/QueryResult.collection.js, ui/packages/catalog-ui-search/src/main/webapp/js/model/QueryResult.js, ui/packages/catalog-ui-search/src/main/webapp/js/model/User.js, ui/packages/catalog-ui-search/src/main/webapp/js/model/Workspace.js, ui/packages/catalog-ui-search/src/main/webapp/js/properties.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/metacard-history/container.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/metacard-history/presentation.tsx, ui/packages/catalog-ui-search/src/main/webapp/test/mock-api/mock-properties.js
=> Revert "DDF-5260 Updates editing restrictions to take into account write access"

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/QueryMetacardApplication.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/RetreiveAllQueryRequests.java
Refactored query API get request for retrieving all searches
@rececoffin 
@bellcc 
@rzwiefel
Downstream queries function as intended
Fixes: #5258  …
=> DDF-5258 refactored query for all searches into wrapper

ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/geometry.view.js
Fixes https://github.com/codice/ddf/issues/5328
@bdeining 
@millerw8 
@codice/ui 
@bdeining 
@millerw8
As described in: https://github.com/codice/ddf/issues/5328
Here: https://github.com/codice/ddf/issues/5328
Fixes: #5328 …
=> DDF-05328: Fixes mixed, multi-valued geometry parse

.github/PULL_REQUEST_TEMPLATE
Adds @Bdthomson to PR template.
@rzwiefel 
@djblue 
N/A
@bdeining
@vinamartin
N/A
N/A
N/A
- [N/A ] Update / Add Threat Dragon models
- [N/A ] Update / Add Integration Tests …
=> Add bdthomson to PR Template

ui/packages/catalog-ui-search/src/main/webapp/react-component/source-item/source-item.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/sources/container.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/sources/presentation.tsx
Passes a callback to the models fetch method to the view, allowing the view to refresh itself
@Schachte 
@djblue 
@codice/ui 
@adimka
Full build should be enough, it just adds framework extensibility options without an impl
Fixes: https://github.com/codice/ddf/issues/5318 …
=> DDF-05318 Pass fetch method to source-item and call it on close

distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/AbstractIntegrationTest.java
Fixes warning during itests 
see #5334 for details
@bennuttle 
@rymach 
@leo-sakh 
@bdeining 
@stustison 
Fixes: #5334 
=> DDF-05334 Adding ids to maven repo

catalog/core/catalog-core-directorymonitor/pom.xml, features/cxf/pom.xml, libs/test-common/pom.xml
Added missing dependencies to test-commons module
@bdthomson
@stustison
Build.  
From a new M2 that is not hooked up to the local mirror, the build will fail to resolve these artifacts when building.
Fixes: #____ …
=> DDF-5168 Added missing dependencies to test-commons module

dependency-check-maven-config.xml, distribution/docs/src/main/resources/content/_managing/_configuring/reusing-configurations.adoc, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/admin/ConfigurationAdminMigratable.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/admin/ImportMigrationConfigurationAdminContext.java, platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/admin/ImportMigrationConfigurationAdminEntry.java, platform/migration/platform-migration/src/test/java/org/codice/ddf/configuration/admin/ConfigurationAdminMigratableTest.java
DO NOT SQUASH!!! 
Adds support for upgrading `Web Context Policy Manger`, `STS Guest Claims Handler`, `STS Server`, and `Session` security configurations with migration across versions.
@ahoffer 
@brjeter
@paouelle 
1. Install an old release version of DDF that is in the list of "supported versions" and create `Web Context Policy Manger`, `STS Guest Claims Handler`, `STS Server`, and `Session` configurations under the Security App
2. Run migration:export, which creates 3 files under the `etc/exported` directory
3. Shutdown
4. Start up a DDF built on this PR's changes
5. Install with `profile:install standard`
6. Copy all 3 files from step 2 into this newly installed DDF under /exported.
7. Run `migration:import -f`
8. After the system automatically …
=> [2.16.x] DDF-5311 Added support for upgrading some security configs with migration

dependency-check-maven-config.xml
adds above CVE suppressions
@tyler30clemens @bakejeyner 
@brjeter
@mcalcote
Fixes: #5369 
=> DDF-5369 suppress CVE-2019-16335 and CVE-2019-14540

distribution/docs/src/main/resources/content/_managing/_installing/configure-single-sign-on.adoc
updates installation instructions to include SSO configuration
@codice/docs 
@blen-desta
@brjeter
@clockard
@lessarderic
verify content
Fixes: #5348  …
=> DDF-5349 added Configure SSO instructions to admin docs

ui/packages/catalog-ui-search/src/main/webapp/react-component/navigation-right/buttons.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/navigation-right/presentation.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/workspace-menu/presentation.tsx
Adjusts spacing/styling for the Search button and the User section. Corrects uneven spacing around the Search button text, and allows for correct spacing and text overflow behavior in the User icon. 
@TeresaHudson @samuelechu @gordocanchola 
@djblue
@vinamartin
UI build, open UI and ensure Search button spacing and User icon spacing is correct.
Part of: #5269 …
=> DDF-5269 Improve styling and layout for Search Button and User

catalog/core/catalog-core-sourcemetricsplugin/src/main/java/ddf/catalog/metrics/source/SourceMetricsImpl.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/CachingFederationStrategy.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/SortedQueryMonitor.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/TimedSource.java, catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/cache/solr/impl/CachingFederationStrategyTest.java
Adds metrics and logging to track latency per source query.
@coyotesqrl
@lamhuy 
@troymohl
@rzwiefel
Use Intrigue or Simple UI to query the system.  Navigate to Admin UI > Platform > Metrics.  Verify `Source Ddf Distribution Queries Latency` exists.  See screenshot for example.
Fixes: #5347  …
=> DDF-5347 Add per source latency metric

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/config/ConfigurationApplication.java, catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.xml, distribution/docs/src/main/resources/content/_managing/_configuring/default-layout-intrigue.adoc, distribution/docs/src/main/resources/content/_reference/_tables/catalog.ui.adoc, ui/packages/catalog-admin-module-layout/package.json, ui/packages/catalog-admin-module-layout/src/main/webapp/default-layout/index.js, ui/packages/catalog-admin-module-layout/src/main/webapp/default-layout/reducer.js, ui/pom.xml, ui/yarn.lock
Allow admin layout to support custom visualizations
@codice/ui 
@bdeining
@djblue 
-->
Open `$DDF_DIST/ddf-2.19.0-SNAPSHOT/etc/org.codice.ddf.catalog.ui.config` and add a config for visualizations like this:
```
"[{\"name\":\"openlayers\",\"title\":\"2D Map\",\"icon\":\"map\"},{\"name\":\"cesium\",\"title\":\"3D Map\",\"icon\":\"globe\"},{\"name\":\"inspector\",\"title\":\"Inspector\",\"icon\":\"info\"},{\"name\":\"histogram\",\"title\":\"Histogram\",\"icon\":\"bar-chart\"},{\"name\":\"table\",\"title\":\"Table\",\"icon\":\"table\"},{\"name\":\"timeline\",\"title\":\"Timeline\",\"icon\":\"hourglass\"},{\"name\":\"results\",\"title\":\"Results\",\"icon\":\"list\"}]"
```
The list structure is `component,componentName,font-awesome4.7.0-icon-name`
Then verify …
=> DDF-5381 Allow admin layout to override visualizations

distribution/docs/src/main/resources/content/_integrating/_endpoints/opensearch-endpoint.adoc, distribution/docs/src/main/resources/content/_using/accessing-intrigue.adoc, distribution/docs/src/main/resources/content/_using/attribute-editor.adoc, distribution/docs/src/main/resources/content/_using/create-a-search.adoc, distribution/docs/src/main/resources/content/_using/editing-searches.adoc, distribution/docs/src/main/resources/content/_using/lists.adoc, distribution/docs/src/main/resources/content/_using/map-tools.adoc, distribution/docs/src/main/resources/content/_using/result-forms.adoc, distribution/docs/src/main/resources/content/_using/search-forms.adoc, distribution/docs/src/main/resources/content/_using/sources-ui.adoc, distribution/docs/src/main/resources/content/_using/using-intrigue-intro.adoc, distribution/docs/src/main/resources/content/_using/viewing-results.adoc, distribution/docs/src/main/resources/content/_using/workspaces.adoc, distribution/docs/src/main/resources/templates/documentation.ftl, distribution/docs/src/main/resources/templates/using.ftl
updates User guide documentation to include a glossary of UI terminology
@codice/docs 
@codice/ui 
@djblue
@lessarderic
@mcalcote
@shaundmorris
Verify content. 
Feel free to suggest other relevant concepts to include.
Fixes: #5033  …
=> DDF-5033 added glossary to user docs

pom.xml
=> DDF-04342 Release of DDF Parent

js/script.js
tweak to script.js to fix the "News and Events" pane on the home page.
@codice/docs 
@bdeining
@jrnorth
@lessarderic
@mcalcote
@shaundmorris
"News and Events" section loads latest releases
The script was checking for `index` to appear in the URL, this does not work if redirected / linked to the homepage without "index"
#4759  …
=> DDF-04759 updated gh-pages script for site index

ui/.eslintignore
anyone who hasn’t cleaned out .gitignored files after a27766313e51f4d8a852563d77659b5d1dd8f7fb will probably have a broken build
this pr will fix that
=> DDF-04746 repeat builds are failing b/c this old dir is not ignored

ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-old.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/location/bounding-box.js
Updates MGRS bounding box to use two points vs a single block
@samuelechu 
@adimka
@bdeining
@millerw8 
Try using the new upper left and lower right inputs for specifying the usng bounding box.
Fixes: #5306  …
=> DDF-05306 Updates MGRS bounding box to use two points vs a single block

Documentation-versions.html, index.html, js/script.js
- fix for "latest version" script to normalize tag names to valid version numbers.
- (Added some reformatting to the `Documentation-versions` page as well)
- (Added `documentation.html` (complete documentation) to library.
@codice/docs 
@brjeter
@clockard
@jrnorth
@lessarderic
@pklinef
@shaundmorris
load page & check links
#4759  …
=> DDF-04759 edits to Documentation-version page and copy edits

ui/packages/catalog-ui-search/src/main/webapp/react-component/location/keyword.js
Makes keyword.js more configurable. Also replaced the component ternaries with ||s
@codice/ui
@bdthomson
@vinamartin 
1. Pull and (use dev server or quick build)
1. Configure offline gazetteer
1. Admin UI -> System -> Catalog-UI-Search (image below)
1. Unselect "Use Online Gazetteer"
1. Import gazetteer data by running `gazetteer:update "$ddf.data/countries.geo.json"` in the karaf console
1. Navigate to the anyGeo keyword filter (Search DDF Intrigue -> switch to advanced search -> select anyGeo from the dropdown -> choose keyword from the geometry dropdown). You'll see something that looks similar to the gazetteer (image below). That's the component we're using to test.
1. Make sure it works normally (see first image below) (e.g. has the normal …
=> DDF-5398 Update keyword to be more configurable

catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/ExportCommand.java, distribution/docs/src/main/resources/content/_managing/_running/catalog-commands.adoc, distribution/docs/src/main/resources/content/_managing/_running/data-migration-intro.adoc
=> Updates catalog:export description

ui/packages/catalog-ui-search/src/main/webapp/component/filter-builder/filter-builder.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/query-advanced/query-advanced.view.js, ui/packages/catalog-ui-search/src/main/webapp/js/cql.js, ui/packages/catalog-ui-search/src/main/webapp/js/model/Workspace.collection.js
anyText ILIKE '%', and anyText ILIKE '*' are used in several places as defaults/fallbacks. This PR makes constants for those strings and uses those constants in a few places across the codebase. This constants will also be of use downstream.
@andrewzimmer 
@hayleynorton 
@willwill96 
@codice/ui 
Fixes: #5423  …
=> DDF-5423 make and use constants for common cql strings

distribution/ddf-common/src/main/resources/security/default.policy
Updated policy for jetty; failures were observed when using the CSW endpoint
Fixes: #__04342__
=> [2.19.x] DDF-04342 Updated policy for jetty

catalog/core/catalog-core-directorymonitor/pom.xml, features/cxf/pom.xml, libs/test-common/pom.xml
backport of https://github.com/codice/ddf/pull/5342
@bdeining 
Fixes: #____
=> [2.18.x] DDF-5168 Added missing dependencies to test-commons module (#5342)

ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-old.js, ui/packages/catalog-ui-search/src/main/webapp/js/widgets/cesium.circle.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/location/point-radius.js
Currently you cannot enter a latitude or longitude that starts with 0 (positive or negative) or even 0 itself. point-radius.js sets the field's value to '' if the actual input value is 0 so as soon as you
enter 0 or a value that resolves to 0 (like -0), it is erased. That solution was implemented to fix a bug that caused the fields to display 0 whenever the input was fully erased. The root cause is that the Math.max()/Math.min() operations performed on the input value to fit it in the valid latitude or longitude range return 0 for '' (the value of a fully-erased input field) which results in the field being set to 0 even if you erase the whole thing. This solution simply adds a check for the empty string before attempting to fit the value to the valid range which removes the need to check …
=> [2.18.x] DDF-5432 Fix point-radius lat/lon input validation

ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-old.js, ui/packages/catalog-ui-search/src/main/webapp/js/widgets/cesium.circle.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/location/point-radius.js
Currently you cannot enter a latitude or longitude that starts with 0 (positive or negative) or even 0 itself. point-radius.js sets the field's value to '' if the actual input value is 0 so as soon as you
enter 0 or a value that resolves to 0 (like -0), it is erased. That solution was implemented to fix a bug that caused the fields to display 0 whenever the input was fully erased. The root cause is that the Math.max()/Math.min() operations performed on the input value to fit it in the valid latitude or longitude range return 0 for '' (the value of a fully-erased input field) which results in the field being set to 0 even if you erase the whole thing. This solution simply adds a check for the empty string before attempting to fit the value to the valid range which removes the need to check …
=> [2.19.x] DDF-5432 Fix point-radius lat/lon input validation

ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-old.js, ui/packages/catalog-ui-search/src/main/webapp/js/widgets/cesium.circle.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/location/point-radius.js
Currently you cannot enter a latitude or longitude that starts with 0 (positive or negative) or even 0 itself. point-radius.js sets the field's value to '' if the actual input value is 0 so as soon as you
enter 0 or a value that resolves to 0 (like -0), it is erased. That solution was implemented to fix a bug that caused the fields to display 0 whenever the input was fully erased. The root cause is that the Math.max()/Math.min() operations performed on the input value to fit it in the valid latitude or longitude range return 0 for '' (the value of a fully-erased input field) which results in the field being set to 0 even if you erase the whole thing. This solution simply adds a check for the empty string before attempting to fit the value to the valid range which removes the need to check …
=> DDF-5432 Fix point-radius lat/lon input validation

ui/packages/catalog-ui-search/src/main/webapp/component/query-add/query-add.view.js
Backport of https://github.com/codice/ddf/compare/2.19.x...Schachte:2.19x-double-query?expand=1
=> [2.19.x] DDF-5834 Fixed double invocation of query (#5385) (#5412)

dependency-check-maven-config.xml
Suppresses false positives, please see notes on the file to see you agree with the findings.
@codice/solr 
@vinamartin 
@jrnorth 
Build passes
The suppression file has a note on why these are suppressed
Fixes: #5458  …
=> DDF-5458 suppressed OWASP false positivies

ui/packages/catalog-ui-search/src/main/webapp/react-component/enum/enum.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/map-settings/container.tsx
Fixes #5424  
@bennuttle 
@BernardIgiri 
@jrnorth 
@djblue 
@gjvera 
@lavoywj 
@codice/ui 
@bdeining
@jrnorth
Please see #5424 
Fixes: #5424 
=> DDF-05424: Enum marionette view forced re-render

ui/packages/catalog-ui-search/src/main/webapp/react-component/enum/enum.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/map-settings/container.tsx
Please see #5424 
@bdeining 
@gjvera 
@bennuttle 
@lavoywj 
@jrnorth 
@codice/ui
@bdeining
@jrnorth
Same as: https://github.com/codice/ddf/pull/5429
Here: https://github.com/codice/ddf/pull/5429
Fixes: #5424  …
=> DDF-05424: [2.19.x] Enum marionette view forced re-render

platform/admin/admin-configuration-configupdater/src/main/java/org/codice/ddf/admin/configuration/ConfigurationUpdater.java, platform/solr/solr-factory-impl/src/main/java/org/codice/solr/factory/impl/HttpClientBuilder.java
Makes `HttpClientBuilder.get()` and `ConfigurationUpdater.handleDelete(String)` final.
@blen-desta
Full CI build should be sufficient.
Fixes: #5477  …
=> [MASTER] DDF-5477 Makes methods that invoke privileged code final.

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/transformer/TransformerDescriptorApplication.java
Applies correct locale when calling toLowerCase before comparison of transformer type.
@blen-desta @bakejeyner 
@brjeter
Full CI build should be sufficient.
Fixes: #5479  …
=> [MASTER] DDF-5479 Ensure correct locale is used when calling toLowerCase before comparison

platform/admin/admin-configuration-configupdater/src/main/java/org/codice/ddf/admin/configuration/ConfigurationUpdater.java, platform/solr/solr-factory-impl/src/main/java/org/codice/solr/factory/impl/HttpClientBuilder.java
Cherry pick of #5478 
@blen-desta
Cherry-pick; CI is sufficient.
Fixes: #5477 
=> [2.19.x] DDF-5477 Makes methods that invoke privileged code final. (#5478)

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/transformer/TransformerDescriptorApplication.java
Cherry pick of #5480 
@blen-desta @bakejeyner 
@brjeter
Cherry pick; CI build is sufficient.
Fixes: #5479 
=> [2.19.x] DDF-5479 Ensure correct locale is used when calling toLowerCase before comparison

platform/admin/admin-configuration-configupdater/src/main/java/org/codice/ddf/admin/configuration/ConfigurationUpdater.java, platform/solr/solr-factory-impl/src/main/java/org/codice/solr/factory/impl/HttpClientBuilder.java
Cherry pick of #5478 
@blen-desta
Cherry-pick; CI is sufficient.
Fixes: #5477 
=> [2.16.x] DDF-5477 Makes methods that invoke privileged code final. (#5478)

platform/admin/admin-configuration-configupdater/src/main/java/org/codice/ddf/admin/configuration/ConfigurationUpdater.java, platform/solr/solr-factory-impl/src/main/java/org/codice/solr/factory/impl/HttpClientBuilder.java
Cherry pick of #5478 
@blen-desta
Cherry-pick; CI is sufficient.
Fixes: #5477 
=> [2.17.x] DDF-5477 Makes methods that invoke privileged code final. (#5478)

platform/admin/admin-configuration-configupdater/src/main/java/org/codice/ddf/admin/configuration/ConfigurationUpdater.java, platform/solr/solr-factory-impl/src/main/java/org/codice/solr/factory/impl/HttpClientBuilder.java
Cherry pick of #5478 
@blen-desta
Cherry-pick; CI is sufficient.
Fixes: #5477 
=> [2.18.x] DDF-5477 Makes methods that invoke privileged code final. (#5478)

ui/packages/catalog-ui-search/src/main/webapp/js/filter.js
Fixes anyText filtering of query results 
@andrewzimmer 
@hayleynorton 
@codice/ui 
@bdeining
@djblue
Run a query that returns multiple results
Apply an anyText filter to the search results
Verify that the filter is applied correctly and the results are narrowed down according to the filter 
(previously, all the results would be hidden regardless of what the anyText filter is)
Fixes: #5471  …
=> DDF-5471 fix anyText filtering

ui/packages/catalog-ui-search/src/main/webapp/js/filter.js
Fixes anyText filtering of query results. Previously an anyText filter would hide all the query results, even if some of them did match the anyText condition. 
@andrewzimmer 
@hayleynorton 
@codice/ui 
@bdeining
@djblue
Execute a query that returns multiple results
Apply an anyText filter that will narrow down the number of search results
Verify that the proper results are shown. (Previously all results would be hidden regardless of the condition in the anyText filter))
Fixes: #5471  …
=> [2.19.x] DDF-5471 Fix anyText filtering of query results

distribution/ddf-common/src/main/resources/security/default.policy
Updated policy for jetty; failures were observed when using the CSW endpoint
Fixes: #__04342__
=> DDF-04342 Updated policy (#5437)

catalog/core/catalog-core-directorymonitor/pom.xml, catalog/core/catalog-core-directorymonitor/src/test/java/org/codice/ddf/catalog/content/monitor/ContentDirectoryMonitorIT.java, catalog/core/catalog-core-directorymonitor/src/test/java/org/codice/ddf/catalog/content/monitor/features/SecurityFeatures.java, catalog/rest/catalog-rest-endpoint/pom.xml, catalog/rest/catalog-rest-endpoint/src/test/java/org/codice/ddf/endpoints/rest/RestEndpointIT.java, distribution/ddf-common/src/main/resources-filtered/etc/custom.properties, features/camel/src/main/feature/feature.xml, features/cxf/pom.xml, features/cxf/src/main/feature/feature.xml, features/pom.xml, features/security/pom.xml, features/security/src/main/feature/feature.xml, libs/bundles/libs-bundles-opensaml/pom.xml, libs/bundles/pom.xml, libs/pom.xml, platform/security/platform-security-core-api/pom.xml, platform/security/pom.xml, pom.xml
See https://github.com/codice/ddf/pull/5379
@brianfelix 
@bdeining
@stustison
=> [18.x] DDF-5324 Upgrades Guava to 25.1 and forces opensaml to use the same version

features/camel/src/main/feature/feature.xml, pom.xml
This PR updates the version of Apache Camel dependency, which will help reduce the amount of high severity vulnerabilities.
@mdang8
@rfding
@josephthweatt
@bakejeyner
@codice/build 
@brjeter
@oconnormi
@stustison
This should be non-invasive and does not add any functionality to test. This branch can be checked out, and built using 'mvn clean install' to ensure that it passes all current compilation, unit test, and integration test steps.
Fixes: #5502 …
=> DDF-5502 Upgrading Apache Camel to 2.24.2

dependency-check-maven-config.xml, platform/security/handler/security-handler-oidc/pom.xml, platform/security/handler/security-handler-oidc/src/main/java/org/codice/ddf/security/handler/oidc/OidcHandlerConfigurationImpl.java, platform/security/security-oidc-realm/src/main/java/org/codice/ddf/security/oidc/realm/OidcTokenValidator.java, pom.xml
This PR updates the version of pac4j dependency, which will help reduce the amount of high severity vulnerabilities. 
@mdang8 
@rfding
@bakejeyner 
@oconnormi 
@brjeter 
@stustison
@ricklarsen 
This should be non-invasive and does not add any functionality to test. This branch can be checked out, and built using 'mvn clean install' to ensure that it passes all current compilation, unit test, and integration test steps.
Fixes: DDF-5431 …
=> DDF-5431 Upgrading pac4j to version 3.8.2

Jenkinsfile, pom.xml
Upgraded depdency-check from 3.1.1 to 5.2.2
Updated dependency-check stage to be more efficient. Instead of using Maven verify phase, directly call dependency-check. 
Re-adds dependency-check into the build with the -POwasp profile
The build does not fail on CVEs currently, instead it enables reporting to take place. Need to consider our process improvements for those cases. It seems most PRs will be unrelated to the CVE that was reported yesterday.
Also switches to the JSON feed rather than the removed XML feed that was causing builds to fail 
@bakejeyner 
@LinkMJB 
@stustison 
@codice/build 
@bdeining 
@jlcsmith
Build passes locally (try with internal database) with the -POwasp profile
Fixes: #5504  …
=> DDF-5504 Upgraded to DDF-Parent 1.0.8 and Dependency-Check 5.2.2

catalog/core/catalog-core-directorymonitor/pom.xml, catalog/core/catalog-core-directorymonitor/src/test/java/org/codice/ddf/catalog/content/monitor/ContentDirectoryMonitorIT.java, catalog/core/catalog-core-directorymonitor/src/test/java/org/codice/ddf/catalog/content/monitor/features/SecurityFeatures.java, catalog/rest/catalog-rest-endpoint/pom.xml, catalog/rest/catalog-rest-endpoint/src/test/java/org/codice/ddf/endpoints/rest/RestEndpointIT.java, distribution/ddf-common/src/main/resources-filtered/etc/custom.properties, features/camel/src/main/feature/feature.xml, features/cxf/pom.xml, features/cxf/src/main/feature/feature.xml, features/pom.xml, features/security/pom.xml, features/security/src/main/feature/feature.xml, libs/bundles/libs-bundles-opensaml/pom.xml, libs/bundles/pom.xml, libs/pom.xml, platform/security/platform-security-core-api/pom.xml, platform/security/pom.xml, pom.xml
See https://github.com/codice/ddf/pull/5379
@brianfelix 
@bdeining
@stustison
=> [19.x] DDF-5324 Upgrades Guava to 25.1 and forces opensaml to use the same version

catalog/ui/catalog-ui-search/README.md, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/forms/builder/AttributeValueNormalizer.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/forms/builder/JsonModelBuilder.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/forms/builder/XmlModelBuilder.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/forms/filter/VisitableJsonElementImpl.java, catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/forms/builder/AttributeValueNormalizerTest.java, ui/packages/catalog-ui-search/src/main/webapp/component/filter-builder/filter-serialization.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/filter/filter-input/filter-date-inputs/filter-between-time-input/betweenDateHelper.js
Allows users to save between filters on search forms.
@Lambeaux 
@rzwiefel 
@Bdthomson 
@codice/ui 
@Lambeaux 
@vinamartin 
Create a search form with a between date range filter on a date attribute.
Save the form with both fields, only one field, and no fields. 
Access the form in your saved forms and be sure to refresh after each access to make sure the data for the view is being fetched from SOLR. 
You may also access the form from searches as well to ensure the expected values are present. 
Fixes: #05450 …
=> DDF-5450 Adds date ranges (during) to the AttributeNormalizer for search forms

ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-serialization.js, ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-serialization.spec.js
Forward port of: https://github.com/codice/ddf/pull/5531
@andrewzimmer
@hayleynorton 
@willwill96 
@codice/ui 
@bdeining
@bdthomson
Follow test procedure on: 
https://github.com/codice/ddf/pull/5531
Fixes: #5513  …
=> [2.19.x] DDF-5513 Fix anyGeo bounding box not updating correctly

catalog/ui/catalog-ui-search/pom.xml, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/api/EndpointUtility.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/util/EndpointUtil.java, catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/blueprint/provides.xml, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/table/table-viz.view.js, ui/packages/catalog-ui-search/src/main/webapp/extension-points/table-export/index.tsx, ui/packages/catalog-ui-search/src/main/webapp/extension-points/table-export/table-export.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/table-export/container.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/utils/export/export.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/utils/export/index.tsx
Extends Table Export to allow downstream projects to set separate behavior
@hayleynorton @zta6 @willwill96 
@codice/ui 
@bdeining
@djblue
- verify no regression in exporting results from the table view
Fixes: #5495  …
=> [2.19.x] DDF-5495 Provide an extension for Table Export behavior

ui/packages/catalog-ui-search/src/main/webapp/component/map-context-menu/map-context-menu.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/cesium/map.cesium.js, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/map.model.js, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/map.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/openlayers/map.openlayers.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/map-context-menu/index.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/select-coordinates/index.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/select-coordinates/select-coordinates.tsx
Adds the full implementation for the Intrigue ruler feature brought up during the UC Hackathon. A new menu action is added to the right-click context menu that contains options for using the ruler on both the 2D and 3D Map. Coordinates can be selected as start/end points for the ruler and the distance between them is calculated. Map markers are placed at the selected coordinates and a line is drawn between them to show the distance that is being measured. The map markers and line are able to be cleared through a menu option or when new coordinates are selected after a distance has been calculated for the previous set.
@rfding 
@aaronilovici
@brjeter 
@pvargas 
@codice/ui 
@djblue 
1. Open the Intrigue UI and go to the 3D Map view.
2. Right-click anywhere on …
=> DDF-5430 Add ruler capabilites to right-click context menu on map

ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-serialization.js, ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-serialization.spec.js
Forward port of https://github.com/codice/ddf/pull/5531
@andrewzimmer 
@hayleynorton 
@willwill96 
@codice/ui 
@bdeining
@bdthomson
Follow test steps on: https://github.com/codice/ddf/pull/5531
Fixes: #5513  …
=> DDF-5513 Fix anyGeo bounding box not updating correctly

Documentation-versions.html
fixes mis-capitalized target in link to Managing documentation.
@codice/docs 
@brjeter
@clockard
@lessarderic
check link to pdf
nah.
#4759  …
=> DDF-04759 fixed typo in docs link

ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-old.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/location/point-radius.js
Changing the validation logic to no longer clear the value
Changing the validation logic to default lat/lon to 0 instead of undefined
Adding a Warning to the user when an invalid MGRS coordinate is entered
Changing the logic that converts from Lat/Lon to USNG to run after drawing is complete
Fixes: #____ …
=> Edit Point Radius MGRS coordinates

pom.xml
@codice/build 
(please choose ONLY two committers from below)
@brjeter
@clockard
Build with -Powasp
Fixes: #5510  …
=> DDF-5504 setFailOnError to false for dependency-check

catalog/rest/catalog-rest-endpoint/pom.xml, catalog/ui/catalog-ui-search/pom.xml, distribution/test/itests/test-itests-ddf/pom.xml, distribution/test/itests/test-itests-kernel/pom.xml, features/pom.xml, libs/test-common/pom.xml, pom.xml
Upgrades the maven-failsafe-plugin and enables fast fail.
@codice/test 
@pklinef @brjeter @paouelle 
Fixes: #5446 
=> DDF-5446 Upgraded maven-failsafe-plugin and added fast fail

ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-old.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/location/point-radius.js
Changing the validation logic to no longer clear the value
Changing the validation logic to default lat/lon to 0 instead of undefined
Adding a Warning to the user when an invalid MGRS coordinate is entered
Changing the logic that converts from Lat/Lon to USNG to run after drawing is complete
Fixes: #____ …
=> [2.20.x] Edit Point Radius MGRS coordinates (#227) (#236) (#5498)

ui/packages/catalog-ui-search/src/main/webapp/react-component/time-settings/container.tsx
Change the import statement for `moment` in time-settings. This is so that downstream projects have import compatibility for `moment`
@jlcsmith 
@rececoffin 
@vinamartin 
@vinamartin
Make sure the Time Setting has no regressions.
Fixes: #____ …
=> DDF-127 Import change for downstream import compilation compatibility

ui/packages/catalog-ui-search/src/main/webapp/component/alert/alert.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/multi-select-actions/container.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/multi-select-actions/presentation.tsx
We pass the selection interface as a prop to the multi select component, so it can access whatever the current selection interface is in a given environment. Also, it adds the function required to select all alert results. 
@codice/ui 
@djblue
1. Change `polling` at https://github.com/codice/ddf/blob/6ab4217216b20f2157a0797b7c0571ffe1c55de6/ui/packages/catalog-ui-search/src/main/webapp/js/QueryPolling.js#L248 to be 30000 (The shortest interval you can schedule a query for is 30 minutes, so you can set it to 30 seconds to speed this up. You don't have to do this, but you will need to keep DDF active for 30 minutes if you don't)
2. Build DDF
3. Ingest some data
4. Schedule a query and view the results
5. Click the top checkbox to select all, and see that all results are …
=> [2.19.x] [DDF-5567] Enable ability to select all results in the alert view

Jenkinsfile
Saves a redundant `mvn clean install` command which can easily take over an hour. 
The Codecov stage is updated to be more sufficient.
@TonyMorrison  
@oconnormi 
@LinkMJB 
@codice/build 
@brjeter
@clockard 
Master build passes
Fixes: #5578  …
=> DDF-5578 updated Codecov stage

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/api/EndpointUtility.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/forms/SearchFormsLoader.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/forms/commands/SearchFormsLoaderCommand.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/util/EndpointUtil.java
This PR fixes the Search Forms Loader, which was failing to load the EndpointUtil class from the BundleContext
Build / Install / run forms:load
Fixes: #____ …
=> [2.19.x] Fixed forms loader

ui/packages/catalog-ui-search/src/main/webapp/component/visualization/table/row.view.js
This PR fixes the number formatting issue in the Table View. Now, the large number will display as expected rather than in scientific notation in the Table View. 
@hayleynorton @andrewzimmer 
@codice/ui 
@bdeining 
1. Perform a search
2. Select a result with an attribute with a large number (i.e. File Size)
3. Open Table View and search for the column with the large number and see that it is no longer in scientific notation
4. Compare to the value shown in the Details of the Inspector. It should match.
Fixes: #5583  …
=> [2.19.x] DDF-5583 Fix issue where tables display large numbers in incorrect format

features/cxf/src/main/feature/feature.xml, pom.xml
This upgrades CXF to 3.2.11, an October 2019 release. 
@mdang8
@rfding
@josephthweatt
@clockard 
@stustison 
Checkout, run mvn clean install, verify compatibility. 
Fixes: #5443  …
=> DDF-5443 Upgrading CXF to 3.2.11

distribution/docs/src/main/resources/content/_architectures/_resources/retrieving-resources.adoc, distribution/docs/src/main/resources/content/_metadataReference/core-attributes-table.adoc
Updates descriptions in developer documentation to differentiate `resource-uri` & `resource-derived-uri` from `resource-download-url` & `resource-derived-download-url`.
@codice/data 
@codice/docs 
@ahoffer
@clockard
@lessarderic
@pklinef
review content changes
Fixes: #5569  …
=> DDF-5569 updated resource attribute descriptions to clarify purpose

ui/packages/catalog-ui-search/src/main/webapp/component/visualization/table/row.view.js
Link to 2.19.x PR : #5584 
____
This PR fixes the number formatting issue in the Table View. Now, the large number will display as expected rather than in scientific notation in the Table View. 
@hayleynorton @andrewzimmer 
@codice/ui 
@bdeining 
1. Perform a search
2. Select a result with an attribute with a large number (i.e. File Size)
3. Open Table View and search for the column with the large number and see that it is no longer in scientific notation
4. Compare to the value shown in the Details of the Inspector. It should match.
Fixes: #5583  …
=> DDF 5583 tableview number incorrect format fwdport

distribution/docs/src/main/resources/content/_managing/_configuring/map-layers-intrigue.adoc
Fixes a typo in the map layers documentation.
@codice/docs 
@shaundmorris
=> DDF-2824 Fix typo in map layers documentation

distribution/docs/src/main/resources/content/_managing/_running/troubleshooting.adoc, distribution/docs/src/main/resources/content/_managing/_securing/managing-keystores.adoc, distribution/docs/src/main/resources/content/_quickstart/quickstart-certificates.adoc
Adds some troubleshooting steps to the documentation for configuring certificates
@codice/docs 
@ahoffer
@brjeter
@clockard
@lessarderic
review content changes
Fixes: #5586  …
=> DDF-5586 updated troubleshooting section for common cert issues

distribution/test/itests/test-itests-ddf/pom.xml
Removes obsolete registry dependency from itests, which is currently breaking the DDF Release
@codice/build 
@codice/test 
@ahoffer
@clockard 
@mcalcote 
Build and release of DDF
Fixes: #5541  …
=> DDF-5541 remove obsolete registry dependency from itests

platform/email/platform-email-impl/pom.xml, platform/email/platform-email-impl/src/test/java/org/codice/ddf/platform/email/impl/SmtpClientImplITCaseTest.java, pom.xml
Upgrades dumbster (SMTP client) to a new version. The previous version may have been the cause of occasional builds hanging in CI. 
@glenhein 
@brjeter 
@codice/test 
@AzGoalie
@jrnorth 
Build platform-email-impl
Fixes: #5573  …
=> DDF-5573 Upgraded dumbster to 1.7.1

ui/packages/catalog-ui-search/src/main/webapp/component/list-editor/list-editor.view.js
This PR hides the Template section in Lists when no system defined filters exist
@hayleynorton @zta6 
@codice/ui
@bdeining 
1. Select list tab
2. create a new lists
3. Verify that if there are no system defined filters, the templates view is gone. 
**Note**: It should also be gone for this case when editing a list.
Fixes: #5602  …
=> [2.19.x] DDF-5602 hide templates dropdown in Lists when none are defined

ui/packages/catalog-ui-search/src/main/webapp/component/query-add/query-add.view.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/location/base.line.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/utils/validation/index.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/utils/validation/validation.tsx
This PR provides the user with an error message containing guidance for the correct geo string format and prevents the search from being run or saved until corrected. It also changes the value passed to the buffer input to a string to prevent a large console error due to prop types not matching. 
@andrewzimmer 
@zta6 
@codice/ui 
@bdeining 
@Bdthomson 
1. Open the dev console
2. Start an `anyGeo` Advanced Search and select `Line` or `Polygon`
3. Verify that you no longer see the error pictured in the first screenshot below in the console
4. Paste a WKT string (or any string not in the correct format; could also leave blank) into the geo field
5. Click `Search` twice
6. Verify that you see the error pictured in the second (if searching with Polygon) or third (if …
=> [2.19.x] DDF-5593 Prevent a query from running when geo string is incorrectly formatted

catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/SolrMetacardClientImpl.java
Prevents the spell corrected query from performing spellcheck because it has already been spellchecked
@derekwilhelm 
@jzstern 
@bellcc 
@jlcsmith 
@jlcsmith
Make sure query.get("spellcheck") is false or look at the decompiled files of the solr spellcheck code.
Fixes: #5625  …
=> DDF-5625 Optimized Collation Requery to not spellcheck

catalog/ui/catalog-ui-search/pom.xml, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/alias/AttributeAliases.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/alias/AttributeAliasesImpl.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/config/ConfigurationApplication.java, catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/blueprint/provides.xml, catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.attribute.aliases.xml, catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.attribute.xml, catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/alias/AttributeAliasesImplTest.java, catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/config/ConfigurationApplicationTest.java
Creates a new `AttributeAlias` interface with an impl for mapping attributes to their aliases.
@brianfelix 
@Lambeaux 
@brhumphe 
@bdeining
@millerw8
Install the `standard` profile. Copy the following snippet into `etc/org.codice.ddf.catalog.ui.attribute.aliases.config`. Verify that `Title` (capitalized) is available in the attribute dropdown while creating a new query.
```
attributeAliases=[ \
"title\=Title", \
]
```
Fixes: #5590  …
=> [2.19.x] DDF-5590 Refactor attribute aliases as a standalone service

catalog/catalog-app/src/main/resources/features.xml, catalog/core/catalog-core-directorymonitor/pom.xml, catalog/core/catalog-core-solr/pom.xml, catalog/spatial/spatial-app/src/main/resources/features.xml, dependency-check-maven-config.xml, distribution/solr-distro/pom.xml, features/camel/src/main/feature/feature.xml, features/cxf/src/main/feature/feature.xml, features/pom.xml, features/security/src/main/feature/feature.xml, platform/security/platform-security-core-api/pom.xml, pom.xml
@mdang8 
@clockard
@emmberk
Build this branch of thirdparty:
https://github.com/aaronilovici/thirdparty/tree/upgradeJacksonVersion
Build this branch of DDF:
https://github.com/aaronilovici/ddf/tree/upgradeJackson2.21.x
Run DDF, ingest a document, check that there are no errors.
Fixes: #5642 …
=> [2.21.x] DDF-5642 Upgrading versions for Jackson, Shiro, and thirdparty

catalog/catalog-app/src/main/resources/features.xml, catalog/core/catalog-core-directorymonitor/pom.xml, catalog/core/catalog-core-solr/pom.xml, catalog/spatial/spatial-app/src/main/resources/features.xml, dependency-check-maven-config.xml, distribution/solr-distro/pom.xml, features/camel/src/main/feature/feature.xml, features/cxf/src/main/feature/feature.xml, features/pom.xml, features/security/src/main/feature/feature.xml, platform/security/platform-security-core-api/pom.xml, pom.xml
This PR updates the versions DDF uses for Jackson, Shiro, and the thirdparty library.
@mdang8
@josephthweatt
@rfding
@emmberk 
@clockard 
Build this branch of DDF:
https://github.com/aaronilovici/ddf/tree/upgradeJacksonMaster
Run DDF, ingest a document, check that there are no errors.
Fixes: #5642
2.21.x PR: https://github.com/codice/ddf/pull/5644 …
=> DDF-5642 Upgrading versions for Jackson, Shiro, and thirdparty

ui/packages/catalog-ui-search/src/main/webapp/component/list-editor/list-editor.view.js
Link to 2.19.x PR : #5603 
_____
This PR hides the Template section in Lists when no system defined filters exist
@hayleynorton @zta6 
@codice/ui
@bdeining 
1. Select list tab
2. create a new lists
3. Verify that if there are no system defined filters, the templates view is gone. 
**Note**: It should also be gone for this case when editing a list.
Fixes: #5602  …
=> DDF-5602 hide templates dropdown in Lists when none are defined

catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/pom.xml, catalog/transformer/catalog-transformer-streaming-impl/pom.xml, catalog/transformer/catalog-transformer-xml/pom.xml
This PR updates the jaxb2 runtime to 0.10.0 in some areas of the baseline
Build / Install / Configure WFS and verify it is still working
Fixes: #____
=> [2.19.x] Bump jaxb2 0.6.0 to 0.10.0

catalog/catalog-app/src/main/resources/features.xml, catalog/opensearch/catalog-opensearch-source/pom.xml
This PR uses JDOM service mix instead of embedding jdom2 to fix classpath issues in downstream projects.
@bdthomson
@millerw8
Build / Install / Configure OpenSearch Loopback and verify results are still shown
Fixes: #____ …
=> [2.19.x] Use JDOM service mix

Jenkinsfile
Increases timeout to prevent build abortion (needs RCA)
@TonyMorrison 
@shaundmorris 
@codice/build 
@mcalcote
@shaundmorris
N/A
=> Increased timeout to prevent build abortion (needs RCA)

distribution/docs/src/main/resources/content/_managing/_installing/installing-from-the-command-line.adoc
removes subsection headings from installation directions
@codice/docs 
@ahoffer
@lessarderic
@mcalcote
@shaundmorris
Duplicate section headers can cause links to not link to the expected section. Removed headers from two sections that only exist to direct users to another process instruction. …
=> DDF-2824 formatting fix for installation docs on guest claim attributes

distribution/ddf-common/src/main/resources/bin/setenv, distribution/ddf-common/src/main/resources/bin/setenv.bat
https://github.com/codice/ddf/pull/4953
@brjeter
@beyelerb
=> [2.15.X] DDF-04953 Update setenv script to not override EXTRA_JAVA_OPTS if it already contains a value

distribution/ddf-common/src/main/resources/bin/setenv, distribution/ddf-common/src/main/resources/bin/setenv.bat
https://github.com/codice/ddf/pull/4953
@beyelerb 
@brjeter
=> [2.14.X] DDF-04953 Update setenv script to not override EXTRA_JAVA_OPTS if it already contains a value

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/util/EndpointUtil.java
This PR aims to fix an issue from SonarQube rule ["entrySet()" should be iterated when both the key and value are needed](https://rules.sonarsource.com/java/RSPEC-2864)
"Iterating on a Map using `entrySet()`, when both key and value are needed, is more performant."
Sorry, I don't know who I should tag.
I asked whether PRs tackling SonarQube issues were welcome on [google groups](https://groups.google.com/forum/?fromgroups#!topic/ddf-developers/Ovdj2lohGow).
For Jira:
For GH Issues:
Fixes: #4909 (partially) …
=> DDF-04909 entrySet() instead of keySet() when key and value are needed

catalog/catalog-app/src/main/resources/features.xml, catalog/opensearch/catalog-opensearch-source/pom.xml
This PR uses JDOM service mix instead of embedding jdom2 to fix classpath issues in downstream projects.
@bdthomson
@millerw8
Build / Install / Configure OpenSearch Loopback and verify results are still shown
Fixes: #____ …
=> Use JDOM service mix

platform/platform-paxweb-jettyconfig/src/main/java/org/codice/ddf/security/session/AttributeSharingHashSessionIdManager.java, platform/platform-paxweb-jettyconfig/src/main/java/org/codice/ddf/security/session/AttributeSharingSessionDataStore.java, platform/platform-paxweb-jettyconfig/src/main/resources/jetty.xml
@bdeining
@blen-desta
@pklinef
@rzwiefel
@stustison
@troymohl
For Jira:
For GH Issues:
Fixes: #____ …
=> [2.14.x] DDF-4709 fixed session memory cleanup

catalog/ui/catalog-ui-search/pom.xml, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/alias/AttributeAliases.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/alias/AttributeAliasesImpl.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/config/ConfigurationApplication.java, catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/blueprint/provides.xml, catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.attribute.aliases.xml, catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.attribute.xml, catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/alias/AttributeAliasesImplTest.java, catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/config/ConfigurationApplicationTest.java
Forward port of #5591 
Creates a new `AttributeAlias` interface with an impl for mapping attributes to their aliases.
@brianfelix 
@Lambeaux 
@brhumphe 
@bdeining
@millerw8
Install the `standard` profile. Copy the following snippet into `etc/org.codice.ddf.catalog.ui.attribute.aliases.config`. Verify that `Title` (capitalized) is available in the attribute dropdown while creating a new query.
```
attributeAliases=[ \
"title\=Title", \
]
```
Fixes: #5590  …
=> DDF-5590 Refactor attribute aliases as a standalone service 

catalog/catalog-app/pom.xml, catalog/spatial/ogc/spatial-ogc-urlresourcereader/pom.xml, catalog/transformer/catalog-transformer-pptx/src/test/java/ddf/catalog/transformer/input/pptx/PptxInputTransformerTest.java, catalog/transformer/catalog-transformer-tika-input/pom.xml, catalog/transformer/catalog-transformer-video-input/pom.xml, platform/metrics/platform-metrics-reporting/pom.xml, platform/metrics/platform-metrics-reporting/src/main/java/ddf/metrics/reporting/internal/rrd4j/RrdMetricsRetriever.java, pom.xml
Upgrades Tika to 1.22
Only introduce after adding in the thirdparty change:
https://github.com/codice/thirdparty/pull/39
@aaronilovici 
@rfding 
@bdeining
@oconnormi
Build this branch and test it by ingesting a visio file to ensure that the metadata was extracted.
Fixes: #DDF-5618 …
=> DDF-5618 upgrade tika to version 1.22

Jenkinsfile, pom.xml
Chery-pick of upgrading ddf-parent and dependency-check, which is causing 2.16.x to fail currently.
@bakejeyner
@AdamBurstynski
@LinkMJB
@stustison
@codice/build
@codice/continuous-integration
@bdeining 
@brjeter
@clockard
@ricklarsen 
Build passes (doesn't fail on dependency-check)
Fixes: #5510  …
=> DDF-5504 Upgraded to DDF-Parent 1.0.8 and Dependency-Check 5.2.2 #5510

catalog/catalog-app/pom.xml, catalog/spatial/ogc/spatial-ogc-urlresourcereader/pom.xml, catalog/transformer/catalog-transformer-pptx/src/test/java/ddf/catalog/transformer/input/pptx/PptxInputTransformerTest.java, catalog/transformer/catalog-transformer-tika-input/pom.xml, catalog/transformer/catalog-transformer-video-input/pom.xml, platform/metrics/platform-metrics-reporting/pom.xml, platform/metrics/platform-metrics-reporting/src/main/java/ddf/metrics/reporting/internal/rrd4j/RrdMetricsRetriever.java, pom.xml
This PR applies the upgrades from master to the 2.21.x branch. 
The PR for master can be seen here: https://github.com/codice/ddf/pull/5619
@mdang8 
@rfding 
@brjeter
@oconnormi
Build this branch and test it by ingesting a visio file to ensure that the metadata was extracted.
Fixes: #5618  …
=> [2.21.x] Upgrading Tika and ThirdParty versions

platform/security/rest/security-rest-clientapi/src/main/java/org/codice/ddf/cxf/client/ClientFactoryFactory.java, platform/security/rest/security-rest-cxfwrapper/pom.xml, platform/security/rest/security-rest-cxfwrapper/src/main/java/org/codice/ddf/cxf/client/impl/ClientFactoryFactoryImpl.java, platform/security/rest/security-rest-cxfwrapper/src/main/java/org/codice/ddf/cxf/client/impl/SecureCxfClientFactoryImpl.java, platform/security/rest/security-rest-cxfwrapper/src/main/java/org/codice/ddf/cxf/oauth/OAuthSecurity.java, platform/security/rest/security-rest-cxfwrapper/src/main/java/org/codice/ddf/cxf/oauth/OAuthSecurityImpl.java, platform/security/rest/security-rest-cxfwrapper/src/test/java/org/codice/ddf/cxf/oauth/OAuthSecurityImplTest.java
Adds support for the OAuth Resource Owner Password Credentials Grant
@KalCramer 
@ronipolus
@ryeats
@stustison
Change a source to make a call to the new cxf client methods and ensure that a valid access token is attached to the client.
Fixes: #5360 (continued) …
=> DDF-5360 Added support for the OAuth Resource Owner Password Credentials Grant

Jenkinsfile
@codice/build 
@TonyMorrison 
@shaundmorris 
@LinkMJB 
Fixes: #5665 …
=> #5665 PR builds using Jenkinsfile

Jenkinsfile
Back port of changes to get the Jenkinsfile to where master is. 
@codice/build 
@TonyMorrison 
@shaundmorris 
@LinkMJB 
Fixes: #5665
Backport of: #5666 …
=> Backport 5666 to 2.21.x

Jenkinsfile
Backports #5666 to 2.16.x
@codice/build 
@TonyMorrison 
@shaundmorris 
@LinkMJB 
Fixes: #5665 …
=> Backport 5666 to 2.16.x

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/session/SessionManagementApplication.java, platform/security/servlet/security-servlet-session-expiry/src/main/java/org/codice/ddf/security/servlet/expiry/SessionManagementEndpoint.java, platform/security/session-management-impl/src/main/java/org/codice/ddf/security/session/management/impl/SessionManagementServiceImpl.java, platform/security/session-management-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/security/session-management-impl/src/test/java/org/codice/ddf/security/session/management/impl/SessionManagementServiceImplTest.java, platform/security/session-management-service/src/main/java/org/codice/ddf/security/session/management/service/SessionManagementService.java, ui/packages/catalog-ui-search/src/main/webapp/component/singletons/session-auto-renew.js, ui/packages/ui/src/main/webapp/js/util/SessionRefresherUtil.js
remove the renewal logic from the SessionManagementService
@SmithJosh @bakejeyner 
@blen-desta
Fixes: #____
=> DDF-5681 remove the renewal logic from the SessionManagementService

Jenkinsfile, pom.xml
Backports #5666 to 2.13.x. This had to be done manually instead of cherrypicking because the pom change significantly sometime after 2.13.x was cut. 
@codice/build 
@TonyMorrison 
@shaundmorris 
@LinkMJB 
Fixes: #5665 …
=> Backport 5666 to 2.13.x

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/config/ConfigurationApplication.java, catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.xml, catalog/ui/catalog-ui-search/src/test/resources/config.json, catalog/ui/search-ui-app/src/main/resources/etc/org.codice.ddf.catalog.ui.config, distribution/docs/src/main/resources/content/_managing/_configuring/securing-idp-sp.adoc, distribution/docs/src/main/resources/content/_reference/_tables/catalog.ui.adoc, ui/packages/catalog-admin-module-layout/src/main/webapp/default-layout/test-data/config.json, ui/packages/catalog-ui-search/src/main/webapp/test/mock-api/config.json
Removes the unused External Authentication configuration
@SmithJosh @bakejeyner 
@stustison
Itests pass
=> Remove the External Authentication configuration

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/config/ConfigurationApplication.java, catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.xml, catalog/ui/search-ui-app/src/main/resources/etc/org.codice.ddf.catalog.ui.config, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/cesium/map.cesium.js, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/geometry.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/map.model.js, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/openlayers/map.openlayers.js
Adds an option and input field to the Search UI preferences to enable "custom text notation". Custom text notation allows for a user to enter a metacard attribute to display as a text label next to metacard map markers in Intrigue. `title` is the default attribute used.
@aaronilovici 
@rfding 
@codice/ui 
-->
@djblue 
@vinamartin  
1. Open the Admin console and navigate to `Search UI -> Configuration -> Catalog UI Search`
2. Scroll down to `Show Custom Text Notations` and click the checkbox to enable it
3. Ingest some metacards in Intrigue
4. Open the 2D map and run a `*` search
5. Verify the metacard map markers have a label next to each one
6. Scroll in and out to change appearances of labels
6. Repeat steps 4-6 in the 3D map
Fixes: #5572 and #5508  …
=> DDF-5572 Render map marker labels with custom text notation on 2D and 3D maps

Jenkinsfile, pom.xml
Backports #5666 to 2.15.x
@codice/build 
@TonyMorrison 
@shaundmorris 
@LinkMJB 
Fixes: #5665 …
=> Backport 5666 to 2.15.x

Jenkinsfile, pom.xml
Backports #5666 to 2.20.x
@codice/build 
@TonyMorrison 
@shaundmorris 
@LinkMJB 
Fixes: #5665 …
=> Backport 5666 to 2.20.x

Documentation-versions.html, js/script.js
removes or hides links to inactive repository
@codice/docs 
@ahoffer
@brjeter
@clockard
@jrnorth
@lessarderic …
=> DDF-4759 edits to documentation versions page on product site

ui/packages/catalog-ui-search/src/main/webapp/react-component/workspace-menu/presentation.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/workspace-title/workspace-title.tsx
Link to original PR: #5690 
____________________________________________
Limits the size of the input box for the workspace title so that the search button doesn't get squished
@hayleynorton @zta6 
@codice/ui 
@bdeining 
1. Open search ui
2. Type a long string into the workspace title
3. Verify that the search button doesn't get squished
4. Verify for all of the theme settings (cozy, comfortable, compact)
Fixes: #5689 
Before:
After: …
=> [2.19.x] DDF-5689 limit the size of the workspace title

Jenkinsfile, pom.xml
Backports #5666 to 2.17.x
@codice/build 
@TonyMorrison 
@shaundmorris 
@LinkMJB 
Fixes: #5665 …
=> Backport 5666 to 2.17.x

ui/packages/catalog-ui-search/src/main/webapp/react-component/table-export/container.tsx
Adds the word "Rows" to the options in the export dropdown to specify that export applies to rows, not columns
@codice/ui 
* Conduct any search that returns 1 or more results
* Go to Table Inspector
* Click Export
* In the popup, click the dropdown under "Export"
* Verify that all the options now specify "rows"
Fixes: #5730 
Before
After
@maryformanek Can you verify that this wording change is satisfactory? Any recommendations/changes? …
=> [2.19.x] DDF-5730 edit wording of dropdown options to specify rows

distribution/solr-distro/pom.xml, pom.xml
Adds a new property for Solr Download URLs
@LinkMJB 
@jrnorth 
@pklinef
@AzGoalie 
Full build passes
Fixes: #5743 
---
This change …
=> DDF-5743 Added new property for solr downloads

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/forms/model/pojo/CommonTemplate.java, catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/forms/SearchFormsSymbolsIT.java
Corrects attribute being grabbed for search forms application
@andrewzimmer 
@hayleynorton 
@zta6 
@bdeining 
@djblue 
1. Create a few search forms
2. Modify one of the search forms
3. Refresh search forms page and verify that the modified date of that search form is updated
Fixes: #5727  …
=> DDF-5727 Grab Correct Modified Attribute for Search Forms

ui/packages/catalog-ui-search/src/main/webapp/react-component/workspace-menu/presentation.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/workspace-title/workspace-title.tsx
Limits the size of the input box for the workspace title so that the search button doesn't get squished
@hayleynorton @zta6 
@codice/ui 
@bdeining 
1. Open search ui
2. Type a long string into the workspace title
3. Verify that the search button doesn't get squished
4. Verify for all of the theme settings (cozy, comfortable, compact)
Fixes: #5689 
Before:
After: …
=> DDF-5689 limit the size of the workspace title

ui/packages/catalog-ui-search/src/main/webapp/react-component/table-export/container.tsx
ABBREVIATED REVIEW - 
12.19.x PR - #5731 
______________________________________________________________________
Adds the word "Results" to the options in the export dropdown to specify that export applies to rows, not columns
@codice/ui 
* Conduct any search that returns 1 or more results
* Go to Table Inspector
* Click Export
* In the popup, click the dropdown under "Export"
* Verify that all the options now specify "rows"
Fixes: #5730 
Before
After
~~@maryformanek Can you verify that this wording change is satisfactory? Any recommendations/changes?~~ UX Approved in 2.19.x PR : #5731 
- ✏️ …
=> DDF-5730 export wording master

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/forms/data/QueryTemplateMetacard.java, ui/packages/catalog-ui-search/src/main/webapp/component/search-form/search-form.js
Adds facets to query template metacard and search form model
@bdeining
@Bdthomson 
Verify no regression in source selection on search forms 
Fixes: #5751 
G-7563 …
=> [2.19.x] DDF-5751 Added facets to query template metacard and search form model

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/forms/data/QueryTemplateMetacard.java, ui/packages/catalog-ui-search/src/main/webapp/component/search-form/search-form.js
Link to 2.19.x PR: https://github.com/codice/ddf/pull/5752
_____________________________________________________________________________________________________
Adds facets to query template metacard and search form model
@bdeining
@Bdthomson 
Verify no regression in source selection on search forms 
Fixes: #5751 
G-7563 …
=> DDF-5751 Added facets to query template metacard and search form model

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/security/accesscontrol/AccessControlPreQueryPlugin.java
backward porting for https://github.com/codice/ddf/pull/5011
Fixes: https://github.com/codice/ddf/issues/5010
=> [2.15.x] DDF-5010 AccessControlPreQueryPlugin omit query parameters

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/suggestion/UtmUpsCoordinateProcessor.java, catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/query/suggestion/UtmUpsCoordinateProcessorTest.java
When a user enters a UTM coordinate in the gazetteer search box with no latitude band, `N` is used as the default. This behavior makes is appear as if we support specifying the Northern or Southern hemisphere in place of the latitude band since the gazetteer correctly pans to the Northern hemisphere point. However, this is only a side-effect of how we are parsing the coordinates. In reality, `N` does not directly correspond to the Northern hemisphere. Instead, if the latitude band does not actually correspond with the northing value, then the invalid latitude band is used to *indirectly* determine which hemisphere to use with C-M latitude bands corresponding to the Southern hemisphere and N-X latitude bands corresponding the the Northern hemisphere. As a result, the default behavior of …
=> [2.19.x] DDF-5716 G-7628 Add support for specifying UTM coords with the hemisphere notation in the gazetteer

distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/AbstractIntegrationTest.java
Update itest references to https for the maven repos. Really need to just update maven central but trying them all initially while I'm here.
@codice/build 
@codice/test 
Maven Central only supports https effective on January 15, 2020
https://blog.sonatype.com/central-repository-moving-to-https
Fixes: #5777  …
=> DDF-5777 updated repo references to use https

Support.html
removes video carousel from Support page of product site
@codice/docs 
@brjeter
@jrnorth
@lessarderic
@shaundmorris …
=> DDF-2824 removed outdated videos from support page on product site.

ui/packages/catalog-ui-search/src/main/webapp/extension-points/table-export/table-export.tsx
Fixes table export - Exact Amount to output correct results to export 
@andrewzimmer @zta6 
@codice/ui 
@bdeining 
1. Run a query with > 200 search results
2. Go to table view
3. Select Export -> Exact Amount -> Enter the value "150" as "preview HTML"
4. Select "Download"
5. Open the downloaded HTML and see that it has the 150 entries
Fixes: #5687  …
=> [2.19.x] DDF-5687 Fix table export Exact Amount

Jenkinsfile
Should skip component tests in the right phases but run still run itests.
@TonyMorrison 
@codice/build 
@codice/test 
Build passes
Fixes: #5777  …
=> DDF-5777 skipITs due to http mvn central issue

ui/packages/catalog-ui-search/package.json, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/cesium/cesium.hbs, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/cesium/map.cesium.js, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/map.hbs, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/map.model.js, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/map.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/openlayers/map.openlayers.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/distance-info/distance-info.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/distance-info/index.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/distance-info/presentation.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/map-context-menu/index.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/map-info/container.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/map-info/presentation.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/select-coordinates/select-coordinates.tsx, ui/yarn.lock
The Ruler on Map feature should show the distance between points via the MapInfo component on the bottom right of the screen and next to the mouse. That should also calculate the distance between the start point and the mouse when in the "START" state.
Other changes include:
- Fix to explicitly render points and lines when those functions are called
- Color changes to the line and points
- Removing the toast upon creating a line
- Ruler is dynamically drawing between starting point and the mouse
@rfding 
@mdang8 
@aaronilovici 
@codice/ui 
@brjeter
1. pull and build changes.
2. Open up the Search UI and add a tab for the 3D map and the 2D map.
3. Start with the 3D map. Select a point on the globe, right click and go to **Calculate Distance -> Select Start Point**. 
4. …
=> DDF-5581 Cosmetic Changes to Ruler on Map

ui/packages/catalog-ui-search/src/main/webapp/component/table/query-status/table-query-status.view.js, ui/packages/catalog-ui-search/src/main/webapp/plugins/query-status.js
Make query-status extensible for downstream projects
@zta6 @hayleynorton @cassandrabailey293 
@codice/ui 
@bdeining
@bdthomson
- run query 
- verify no regression in query status (heart beat icon)
Fixes: #5763  …
=> [2.19.x] DDF-5763 Make query-status extensible for downstream projects

Jenkinsfile, distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/AbstractIntegrationTest.java
Skips component tests, but still runs unit and itests. 
@TonyMorrison 
@codice/build 
@codice/test 
@bdeining 
@pklinef 
Build passes
Fixes: #5778  …
=> [2.19.x] DDF-5777 skipITs due to http mvn central issue (#5788)

Jenkinsfile, distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/AbstractIntegrationTest.java
Updates itests to use https in repo URLs. Backport of #5778 
@codice/build 
@codice/test 
Maven Central only supports https
Fixes: #5778  …
=> [2.15.x] DDF-5777 updated repo references to use https (#5778)

ui/packages/catalog-ui-search/src/main/webapp/react-component/dropdown/dropdown.js
Fixes dropdowns on Microsoft Edge versions <= 44.18362.449.0
@bdeining 
@djblue 
Open the UI on an affected version of Microsoft Edge and verify that dropdowns open when you click them (i.e. pan/zoom dropdown on map, location mode selection on anyGeo search) 
Fixes: #5796 
G-7751 …
=> [2.19.x] DDF-5796 Fixed dropdowns not opening on Microsoft Edge

Jenkinsfile, distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/AbstractIntegrationTest.java
Fixes itests using http reference. Backport of #5778 
@codice/build 
@codice/test 
Maven Central stopped supporting http
Fixes: #5777  …
=> [2.21.x] DDF-5777 updated repo references to use https

Jenkinsfile, distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/AbstractIntegrationTest.java
Updates the repo references to use HTTPs
@LinkMJB 
@TonyMorrison 
@codice/build 
@codice/test 
@jrnorth 
Build passes
Fixes: #5777  …
=> [2.20.x] DDF-5777 updated repo references to use HTTPs and skipITs  

catalog/catalog-app/pom.xml, catalog/catalog-app/src/main/resources/features.xml, catalog/transformer/catalog-transformer-xlsx/pom.xml, catalog/transformer/catalog-transformer-xlsx/src/main/java/ddf/catalog/transformer/xlsx/XlsxMetacardTransformer.java, catalog/transformer/catalog-transformer-xlsx/src/main/java/ddf/catalog/transformer/xlsx/XlsxMetacardUtility.java, catalog/transformer/catalog-transformer-xlsx/src/main/java/ddf/catalog/transformer/xlsx/XlsxQueryResponseTransformer.java, catalog/transformer/catalog-transformer-xlsx/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/transformer/catalog-transformer-xlsx/src/test/java/ddf/catalog/transformer/xlsx/XlsxMetacardTransformerTest.java, catalog/transformer/catalog-transformer-xlsx/src/test/java/ddf/catalog/transformer/xlsx/XlsxMetacardUtilityTest.java, catalog/transformer/catalog-transformer-xlsx/src/test/java/ddf/catalog/transformer/xlsx/XlsxQueryResponseTransformerTest.java, catalog/transformer/pom.xml, pom.xml
This PR adds a MetacardTransformer and QueryResponseTransformer for exporting as XLSX format.
@rececoffin 
@bellcc 
@jzstern
@rececoffin 
@bellcc 
Export the results of a search and verify the XLSX option is available and verify the spreadsheet can be opened.   
Fixes: #5721  …
=> DDF-5721 - Add the ability to export as XLSX format

catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/operation/impl/ProcessingDetailsImpl.java, catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/operation/impl/QueryResponseImpl.java, catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/operation/impl/SourceProcessingDetailsImpl.java, catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/operation/impl/SourceResponseImpl.java, catalog/core/catalog-core-api-impl/src/test/java/ddf/catalog/operation/ProcessingDetailsImplTest.java, catalog/core/catalog-core-api-impl/src/test/java/ddf/catalog/operation/SourceProcessingDetailsImplTest.java, catalog/core/catalog-core-api-impl/src/test/java/ddf/catalog/operation/SourceResponseImplTest.java, catalog/core/catalog-core-api/src/main/java/ddf/catalog/security/SourceWarningsFilter.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/CachingFederationStrategy.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/SortedQueryMonitor.java, catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/cache/solr/impl/CachingFederationStrategyTest.java, catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/cache/solr/impl/SortedQueryMonitorTest.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/QueryApplication.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/cql/CqlQueryResponse.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/cql/SourceWarningsFilterManager.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/util/EndpointUtil.java, catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/query/cql/CqlQueryResponseTest.java, catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/query/cql/SourceWarningsFilterManagerTest.java
This PR provides infrastructure to allow sources to add details about a query's operation to the relevant response, and to allow the application to filter details in a response for user-friendliness and provide a list of filtered details to the UI.
@brianfelix 
@Lambeaux 
@brhumphe 
@mazarag2 
@codice/ui 
@jrnorth
@lambeaux
(will complete soon)
(might add later)
Fixes: #5649 
- ❓ …
=> [2.19.x] DDF-5649 G-6176 Allow sources to notify the UI of issues with a query

ui/packages/ui/src/main/webapp/js/application.js
Updates the link to the new admin UI from the admin console
@djblue 
@rzwiefel 
Verify that the link to the new admin UI from the admin console works …
=> DDF-5786 Updates the link to the new admin UI from the admin console

distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/ContainerPerSuiteItestSuite.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestOidc.java
Re -adds OIDC Itests
@blen-desta 
Ensure Itests run 
They were removed because they used Catalog UI. Now they have arisen, free from the catalog-ui that burdened them. 
Fixes: #5705 …
=> DDF-5705 Readd testoidc

catalog/plugin/catalog-plugin-videothumbnail/pom.xml, catalog/plugin/catalog-plugin-videothumbnail/src/main/java/org/codice/ddf/catalog/content/plugin/video/VideoThumbnailPlugin.java, catalog/plugin/catalog-plugin-videothumbnail/src/test/java/org/codice/ddf/catalog/content/plugin/video/VideoThumbnailPluginTest.java
Upgrades FFmpeg from 4.0.2 to 4.2.2
Fixes build issue on Mac (64-bit). 
@codice/build 
@codice/test 
@coyotesqrl 
@jlcsmith 
Build/test pass
Fixes: #5809  …
=> DDF-5809 Upgrade FFmpeg to 4.2.2

platform/solr/solr-dependencies/pom.xml, pom.xml
fixing https://github.com/codice/ddf/issues/5824
@pklinef 
@stustison 
Install standard profile
Ingest some record. verify query
Fixes: #____
=> DDF-5824 remove duplicate export

catalog/solr/catalog-solr-app/pom.xml, catalog/solr/catalog-solr-app/src/main/resources/features.xml, catalog/solr/pom.xml, distribution/ddf-common/src/main/resources-filtered/etc/application-definitions/solr.json, distribution/docs/src/main/resources/content/_reference/_appReferences/mg-solr.adoc, distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/AbstractIntegrationTest.java, features/apps/pom.xml, features/apps/src/main/feature/feature.xml, features/install-profiles/src/main/feature/feature.xml, features/solr/src/main/feature/feature.xml, platform/admin/modules/admin-modules-application/src/test/resources/application-service-array.json, platform/admin/modules/admin-modules-application/src/test/resources/application-service.json, platform/admin/modules/admin-modules-configuration/src/test/resources/application-service.json, platform/admin/modules/admin-modules-installer/src/test/resources/application-service.json, platform/admin/modules/admin-modules-installer/src/test/resources/start-application.json, platform/solr/solr-dependencies/pom.xml
Rename solr-app module to catalog-solr-app
Rename duplicate solr-app features to catalog-solr-app and platform-solr-app
adding solr-dependencies to export org.locationtech.spatial4j
@codice/solr 
@pklinef 
@stustison 
install standard profile
verify ingest and query
Fixes: https://github.com/codice/ddf/issues/5833 …
=> DDF-5833 rename dup feature, add export back

catalog/core/catalog-core-camelcomponent/pom.xml, catalog/core/catalog-core-commands/pom.xml, catalog/core/catalog-core-resourcesizeplugin/pom.xml, catalog/core/catalog-core-resourcestatusplugin/pom.xml, catalog/core/catalog-core-solrcommands/pom.xml, catalog/core/catalog-core-standardframework/pom.xml, catalog/resourcemanagement/resourcemanagement-querymonitor-plugin/pom.xml, catalog/solr/catalog-solr-provider/pom.xml, catalog/transformer/catalog-transformer-pdf/pom.xml, catalog/transformer/catalog-transformer-zip/pom.xml, distribution/solr-distro/pom.xml, distribution/test/itests/test-itests-common/pom.xml, features/pom.xml, platform/admin/core/admin-core-impl/src/main/java/org/codice/ddf/admin/core/impl/module/Decorator.java, platform/admin/core/admin-core-jolokia/pom.xml, platform/platform-scheduler/pom.xml, platform/security/claims/security-claims-ldap/pom.xml, platform/security/security-jaas-ldap/pom.xml, pom.xml
Upgrades almost all of the plugins used in DDF
@SmithJosh @bakejeyner 
@blen-desta
@pklinef
@shaundmorris
@stustison
Fixes: #____
=> DDF-5834 update plugins in DDF

dependency-check-maven-config.xml, pom.xml
This PR updates the version of CXF, downgrades the equinox version to take care of a Karaf+Equinox R7 issue, and adds an exclusion for a CVE that does not affect us.
@mdang8 
@rfding 
@oconnormi 
@clockard
@stustison
Fixes: #____ …
=> Updating dependency versions

dependency-check-maven-config.xml, pom.xml
This PR updates the version of CXF, downgrades the equinox version to take care of a Karaf+Equinox R7 issue, and adds an exclusion for a CVE that does not affect us.
@mdang8 
@rfding 
@clockard
@stustison
Fixes: #____
- …
=> [2.21.x] Updating dependency versions

.github/PULL_REQUEST_TEMPLATE
Adds David Morales to the Pull Request Template as a committer
@Lambeaux
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codice/ddf/5852)
=> Added David Morales to PULL_REQUEST_TEMPLATE

ui/packages/catalog-ui-search/package.json, ui/packages/catalog-ui-search/src/main/webapp/react-component/map-settings/example-coordinates.tsx, ui/yarn.lock
Bumps the version of usng.js to 0.4.2 to 0.4.3
@bdeining 
@shaundmorris 
Change the map's tooltip to UTM/UPS and verify that the zone now appears with a hemisphere (N or S)
Fixes: codice/ddf-ui#102
- ❗ …
=> [2.19.x] DDF-102 Bumped usng.js version to 0.4.3

catalog/plugin/catalog-plugin-oauth/pom.xml, catalog/plugin/catalog-plugin-oauth/src/main/java/org/codice/ddf/catalog/plugin/oauth/OAuthPlugin.java, catalog/plugin/catalog-plugin-oauth/src/test/java/org/codice/ddf/catalog/plugin/oauth/OAuthPluginTest.java, features/security/src/main/feature/feature.xml, platform/security/core/security-core-services/src/main/java/ddf/security/service/impl/SecurityManagerImpl.java, platform/security/filter/security-filter-web-sso/src/main/java/org/codice/ddf/security/filter/websso/WebSSOFilter.java, platform/security/handler/security-handler-api/src/main/java/org/codice/ddf/security/handler/api/SessionToken.java, platform/security/handler/security-handler-saml/src/main/java/org/codice/ddf/security/idp/client/LogoutRequestService.java, platform/security/rest/security-rest-cxfwrapper/src/main/java/org/codice/ddf/cxf/oauth/OAuthOutInterceptor.java, platform/security/rest/security-rest-cxfwrapper/src/main/java/org/codice/ddf/cxf/oauth/OAuthSecurity.java, platform/security/rest/security-rest-cxfwrapper/src/main/java/org/codice/ddf/cxf/oauth/OAuthSecurityImpl.java, platform/security/rest/security-rest-cxfwrapper/src/test/java/org/codice/ddf/cxf/oauth/OAuthSecurityImplTest.java, platform/security/security-token-storage/token-storage-api/src/main/java/org/codice/ddf/security/token/storage/api/TokenInformation.java, platform/security/security-token-storage/token-storage-api/src/main/java/org/codice/ddf/security/token/storage/api/TokenInformationImpl.java, platform/security/security-token-storage/token-storage-api/src/main/java/org/codice/ddf/security/token/storage/api/TokenStorage.java, platform/security/security-token-storage/token-storage-impl/pom.xml, platform/security/security-token-storage/token-storage-impl/src/main/java/org/codice/ddf/security/file/token/storage/FileSystemTokenStorage.java, platform/security/security-token-storage/token-storage-impl/src/main/java/org/codice/ddf/security/file/token/storage/TokenInformationUtil.java, platform/security/security-token-storage/token-storage-impl/src/test/java/org/codice/ddf/security/file/token/storage/FileSystemTokenStorageTest.java, platform/security/servlet/security-servlet-logout/pom.xml, platform/security/servlet/security-servlet-logout/src/main/java/org/codice/ddf/security/servlet/logout/LocalLogoutServlet.java, platform/security/servlet/security-servlet-logout/src/main/java/org/codice/ddf/security/servlet/logout/LogoutServiceImpl.java, platform/security/servlet/security-servlet-logout/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/security/servlet/security-servlet-logout/src/test/java/org/codice/ddf/security/servlet/logout/LogoutServletTest.java
Previously, the user's email address or username (if an email address is not present) was used to store users' OAuth tokens. This would cause problems for guest users. To solve that, we're switching to store tokens based on session IDs.
@bakejeyner @SmithJosh 
@stustison 
Needs: https://github.com/codice/ddf-ui/pull/74
Create two sources (CSW and OpenSearch) to use OAuth (don't forget to add `/services=OIDC` to the webcontext policy manager and to configure the OIDC Handler)
- Should get a notification to log in
- Sign in and re-query
- Query should succeed with no errors
- Should get a notification to **authorize the source**
- Authorize and re-query
- Query should succeed with no errors
- After logging in and querying successfully, sign out of DDF and …
=> DDF-5360 Changed user ID based OAuth token storage to session ID to better handle the guest user.

ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-serialization.js, ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-serialization.spec.js
* DDF-5513 Fix anyGeo bounding box not updating correctly
* remove unused var
Forward port of #5531 
@bellcc 
@astagg 
@codice/ui 
(please choose ONLY two committers from below)
@jlcsmith
Follow steps on #5531
Fixes: #5513 
- ❗ …
=> [2.20.x] DDF-5513 Fix anyGeo bounding box not updating correctly (#5533)

catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/operation/impl/ProcessingDetailsImpl.java, catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/operation/impl/QueryResponseImpl.java, catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/operation/impl/SourceProcessingDetailsImpl.java, catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/operation/impl/SourceResponseImpl.java, catalog/core/catalog-core-api-impl/src/test/java/ddf/catalog/operation/ProcessingDetailsImplTest.java, catalog/core/catalog-core-api-impl/src/test/java/ddf/catalog/operation/SourceProcessingDetailsImplTest.java, catalog/core/catalog-core-api-impl/src/test/java/ddf/catalog/operation/SourceResponseImplTest.java, catalog/core/catalog-core-api/src/main/java/ddf/catalog/security/SourceWarningsFilter.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/CachingFederationStrategy.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/SortedQueryMonitor.java, catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/cache/solr/impl/CachingFederationStrategyTest.java, catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/cache/solr/impl/SortedQueryMonitorTest.java
In response to a malfunction of a query which the user runs, the user
would like a message which describes or explains the malfunction so that
the user can more easily resolve the malfunction. This PR supports
the user's aforementioned desire in that it:
- adds an interface—SourceWarningsFilter—which allows that a Source
which implements it filter the warnings of ProcessingDetails of a
SourceResponse which the Source may receive from the execution of a
query and, thereby, produce new ProcessingDetails whose warnings
contain only each warning of the original ProcessingDetails which
describes or explains a malfunction which occurred in the execution
of the query
- ensures that the implementations of SourceResponse not return null
from getProcessingDetails(), in accordance with the dictate …
=> DDF-5649 G-6176 Add interface to filter warnings

distribution/docs/src/main/resources/content/_using/create-a-search.adoc
Updates the documentation to be more specific as to how the between operator actually works. 
@rececoffin 
@a-asaad 
@codice/docs 
@codice/ui 
@jlcsmith
@ricklarsen
@vinamartin
Full build should be sufficient
None
Fixes: #5869 
None …
=> [2.20.x] DDF-5869 Specify inclusive and exlusive bounds on between operator

catalog/plugin/catalog-plugin-videothumbnail/pom.xml, platform/solr/solr-schema/src/main/resources/solr/conf/schema.xml
Indexes geo fields to improve search experience when searching on 
@bellcc 
@derekwilhelm 
@codice/ui 
@jlcsmith
@vinamartin
-->
Upload data that has geo location associated with it. Run a search for `location is empty` and ensure that the data does not come back. Then change the query to `location is NOT empty` and make sure the expected data comes back.
Fixes: #5877  …
=> [2.20.x] DDF-5877 Make geo attributes indexed in solr

ui/packages/catalog-ui-search/src/main/webapp/js/widgets/openlayers.polygon.js
Fixed #5850 
@bennuttle 
@aj-brooks 
@lavoywj 
@AzGoalie 
@codice/ui 
@AzGoalie
@bdeining
See #5850 reproduce steps. These would be the same to verify fix.
Fixes: #5850  …
=> [2.19.x] DDF-5850: Fixed small polygon buffer width exception

platform/solr/solr-schema/src/main/resources/solr/conf/schema.xml
Forward port of #5878 
@bellcc 
@astagg 
@codice/ui 
@jlcsmith 
@vinamartin
Follow steps on #5878 
Fixes: #5877 
=> DDF-5877 index geo attributes in solr

.github/PULL_REQUEST_TEMPLATE
Adds Glen Hein to committer list.
anyone
anyone
Fixes: #____
=> Adds Glen Hein as committer

ui/packages/catalog-ui-search/src/main/webapp/component/visualization/table/row.less, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/table/row.view.js
Fixes https://github.com/codice/ddf-ui/issues/115
@andrewzimmer @hayleynorton @zta6 
@codice/ui 
Fixes: https://github.com/codice/ddf-ui/issues/115
=> [2.19.x] DDF-UI-115 show inspector thumbnail in table

catalog/opensearch/catalog-opensearch-source/src/main/java/org/codice/ddf/opensearch/source/OpenSearchFilterVisitor.java, ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-serialization.js, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/map.view.js, ui/packages/catalog-ui-search/src/main/webapp/js/CQLUtils.js, ui/packages/catalog-ui-search/src/main/webapp/js/filter.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/filter/filter-input/filter-location-input.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/location/base.line.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/utils/validation/validation.tsx
Allows a line to have a zero-buffer. Solves https://github.com/codice/ddf-ui/issues/112
@codice/ui 
@bdeining 
- Advanced search - anyGeo
- Select Line
- Draw a line and verify that it doesn't automatically change the buffer width to 1
- Verify that you can search with nothing (and/or 0) in the buffer width input, and that the outgoing cql uses INTERSECTS instead of DWITHIN
- Verify that searching with a buffer width greater than 1 meter is allowed and that the outgoing cql uses DWITHIN
- Verify that searching with a buffer width of greater than 0 but less than 1 meter displays an inline error message "Buffer width must be 0 or at least 1 meter".  similar message should display when clicking search (the search should be prevented). Error message should …
=> [2.19.x] DDF-UI-112 allow intersects query for line

distribution/docs/src/main/resources/content/_architectures/_plugins/post-ingest-intro.adoc, distribution/docs/src/main/resources/content/_architectures/_plugins/pre-ingest-intro.adoc
Removes redundant diagrams from plugin documentation
@codice/docs 
@ahoffer
@pklinef
=> DDF-2824 removed diagrams from plugin docs

.github/stale.yml
Adds Stalebot to this repository to automatically close stale issues and pull requests. 
@codice/ddf-contributors 
@Lambeaux 
Just to need to verify existing stale issues, pull requests for the warning comment (after this is merged)
Issues and pull requests can get stale and abandoned over time. This will help with efficiently pinging people for updates before closing.
Fixes: #5911 
- ❓ (Question …
=> DDF-5911 Adding Stalebot config

pom.xml
* DDF-5597 updated dependency-check properties
* DDF-5597 added back dependency-check maven version
Backport to 2.21.x
@TonyMorrison 
@LinkMJB 
@codice/build 
@brjeter
@oconnormi 
Build passes and uses local NVD with the owasp profile
Fixes: #5597  …
=> [2.21.x] DDF-5597 updated dependency-check properties for local NVD (#5654)

ui/packages/catalog-ui-search/src/main/webapp/behaviors/dropdown.behavior.utility.js, ui/packages/catalog-ui-search/src/main/webapp/component/content/content.js, ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-old.js, ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-old.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/singletons/drawing.tsx, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/cesium/map.cesium.js, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/cluster.collection.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/geometry.collection.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/map.view.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/filter/filter-input/filter-location-input.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/location/base.line.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/location/conversion.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/navigation/container.tsx
- Adds a read only popup translation of USNG / MGRS to Lines and Polygons.  Similar with DMS.
- In the future, we'll support the ability to enter coordinates in this format as well, but for now users at least need the ability to see what the translation from decimal degrees to these formats is.
@jlcsmith 
@lifenouveau 
@vinamartin 
Go to the basic search form and select somewhere specific.  Draw a line or polygon.  Verify that you can then click DMS or USNG and see the translation of the coordinates.  Verify that it handles incorrect inputs correctly (displays "cannot translate, please enter valid coordinates").
Do the same thing with advanced search form.
For now the translation is read only.  In the future, we want to provide an actual editor that supports these …
=> [2.20.x] DDF-5904 Adds readonly translation for USNG / DMS to Lines / Polygons

Jenkinsfile, distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/AbstractIntegrationTest.java
skips failing component tests and updates AbstractIntegrationTest to use HTTPs URL for Maven Central/Oss
@TonyMorrison 
@codice/build 
@codice/test 
@jrnorth
@clockard 
Maven central stopped supporting HTTP URL
Fixes: #5777  …
=> [2.16.x] DDF-5777 updated references to use HTTPs

ui/packages/catalog-ui-search/package.json, ui/yarn.lock
Updates `usng.js` to 0.4.4 version of the library. 
@bdeining 
@jlcsmith 
@codice/ui 
@glenhein 
- Verify drawing a bounding boxes in DDF works for all coordinate systems.
- Verify other map drawing options still work correctly. 
- ❗ …
=> [2.20.x] 5935 - Update DDF to use usng.js version 0.4.4

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/query/data/model/QueryBasic.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/workspace/transformer/impl/SrcToQuerySources.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalogSearchUi.java, ui/packages/catalog-ui-search/src/main/webapp/component/query-settings/query-settings.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/search-form/search-form.js, ui/packages/catalog-ui-search/src/main/webapp/js/QueryPolling.js, ui/packages/catalog-ui-search/src/main/webapp/js/model/Query.js, ui/packages/catalog-ui-search/src/main/webapp/js/model/QuerySettings.js
The front end stores the sources on a query metacard in a property called src. When submitting with an RPC request the src property will be ignored as it doesn't match the "sources" definition on the metacard. 
@rzwiefel
@bellcc 
Fixes: #____ …
=> [2.20.x] DDF-5928 Renames "src" to "sources" so RPC doesn't fail

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/handlers/CqlTransformHandler.java, catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/query/handlers/CqlTransformHandlerTest.java, ui/packages/catalog-ui-search/src/main/webapp/extension-points/table-export/index.tsx, ui/packages/catalog-ui-search/src/main/webapp/extension-points/table-export/table-export.tsx, ui/packages/catalog-ui-search/src/main/webapp/js/model/Query.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/results-export/container.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/utils/export/export.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/utils/export/index.tsx
Export Visible always exports the first page of results, this updates table export to use the correct starting index for visible
@hayleynorton @cassandrabailey293 @zta6 @willwill96 
@bdeining
@bdthomson
- ingest data and search for it
- export results via the table
- export Visible results on multiple different pages and verify correct results are present
- hide a result and verify it is not present when exporting visible results
- verify no other regression in exporting
Fixes: #5867  …
=> [2.19.x] DDF-5867 fix table export Visible

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/forms/SearchFormsApplication.java
Adds an id based endpoint for query forms to allow skipping the soft commit delay. 
@bdthomson
Create a form. 
Access the newly created record in solr to view its id. 
Using that id, hit the new endpoint `internal/forms/query/<id>` with a tool like Postman.
Ensure the expected template form is returned.
Fixes: #5925 …
=> [2.20.x] DDF-5925 Adds query form id endpoint 

catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/ConfigurationStore.java, catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/DynamicSchemaResolver.java, catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/RemoteSolrCatalogProvider.java, catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/DynamicSchemaResolverTest.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/SolrCache.java, catalog/core/catalog-core-standardframework/src/main/resources/OSGI-INF/blueprint/fedstrategy.xml, catalog/core/catalog-core-standardframework/src/main/resources/OSGI-INF/metatype/metatype.xml, catalog/solr/catalog-solr-provider/src/main/resources/OSGI-INF/metatype/metatype.xml
Adds the ability to provide a whitelist or blacklist for text fields that are included in an anyText query.
@bdeining 
@pklinef 
@codice/solr 
@jlcsmith
1. Build and do a standard profile install
2. Ingest some data
3. Perform an anyText query that will find the data
4. In the admin console, select the `Solr Catalog` application
5. Edit the `Solr Catalog Provider` configuration
6. Add new whitelist or blacklist entries
- entries can be the field name as seen by DDF OR Solr (i.e. `id` or `id_txt`)
- entries can be regular expressions (i.e. to ignore all security fields use `security.*`)
7. In the admin console, select the `Catalog` application and choose `Configuration`
8. Edit the `Solr Cache Provider` configuration
9. Add the same configuration here as in the `Solr …
=> [2.20.x] DDF-5940 - Add anyText expansion whitelist / blacklist capability

ui/package.json, ui/yarn.lock
Update ace version to b8a981b
@ryeats 
@codice/ui 
@coyotesqrl 
Fixes: #5927
=> DDF-5927 Update ace version to b8a981b

catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/operation/impl/ProcessingDetailsImpl.java, catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/operation/impl/QueryResponseImpl.java, catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/operation/impl/SourceProcessingDetailsImpl.java, catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/operation/impl/SourceResponseImpl.java, catalog/core/catalog-core-api-impl/src/test/java/ddf/catalog/operation/ProcessingDetailsImplTest.java, catalog/core/catalog-core-api-impl/src/test/java/ddf/catalog/operation/SourceProcessingDetailsImplTest.java, catalog/core/catalog-core-api-impl/src/test/java/ddf/catalog/operation/SourceResponseImplTest.java, catalog/core/catalog-core-api/src/main/java/ddf/catalog/security/SourceWarningsFilter.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/CachingFederationStrategy.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/SortedQueryMonitor.java, catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/cache/solr/impl/CachingFederationStrategyTest.java, catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/cache/solr/impl/SortedQueryMonitorTest.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/util/EndpointUtil.java
Abbreviated Review
Backport of https://github.com/codice/ddf/pull/5843
Note the second commit was an addition to the original PR to route processing details all the way back to the UI.
@derekwilhelm 
@bdeining 
@pklinef  
Fixes: #____
- ❗ …
=> [2.20.x] DDF-5649 G-6176 Add interface to filter warnings (#5843)

catalog/core/catalog-core-solr/pom.xml, catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/SolrCatalogProvider.java, catalog/core/catalog-core-solrcommands/pom.xml, catalog/core/catalog-core-solrcommands/src/test/java/org/codice/ddf/commands/solr/SolrCommandTest.java, catalog/core/catalog-core-solrcommands/src/test/resources/simplelogger.properties, catalog/core/catalog-core-standardframework/pom.xml, catalog/rest/catalog-rest-endpoint/pom.xml, catalog/rest/catalog-rest-endpoint/src/test/java/org/codice/ddf/endpoints/rest/it/RestEndpointIT.java, catalog/solr/catalog-solr-provider/pom.xml, catalog/spatial/geocoding/spatial-geocoding-offline-catalog/pom.xml, distribution/docker/solr-docker/src/main/docker/Dockerfile, distribution/docker/solrcloud/docker-compose.yml, distribution/docs/src/main/resources/content/_reference/_dependencyList/ddf-dependency-list.adoc, distribution/solr-distro/pom.xml, distribution/solr-distro/src/main/resources/bin/solr.in.cmd, distribution/solr-distro/src/main/resources/bin/solr.in.sh, platform/solr/solr-dependencies/pom.xml, platform/solr/solr-factory-impl/src/main/java/org/codice/solr/factory/impl/PingAwareSolrClientProxy.java, platform/solr/solr-factory-impl/src/main/java/org/codice/solr/factory/impl/SolrClientAdapter.java, platform/solr/solr-factory-impl/src/main/java/org/codice/solr/factory/impl/SolrClientProxy.java, platform/solr/solr-factory-impl/src/main/java/org/codice/solr/factory/impl/SolrCloudClientFactory.java, platform/solr/solr-factory/src/main/java/org/codice/solr/client/solrj/SolrClient.java, platform/solr/solr-schema/src/main/resources/solr/conf/solrconfig.xml, pom.xml
Upgrades to Solr 8.5.0
@lamhuy 
@rymach 
@codice/solr 
@rzwiefel 
@paouelle
Verify you can ingest and query data
Fixes: #5960 …
=> Upgrade to Solr 8.5

catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/ConfigurationListener.java, catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/ConfigurationStore.java, catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/DynamicSchemaResolver.java, catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/RemoteSolrCatalogProvider.java, catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/DynamicSchemaResolverTest.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/SolrCache.java, catalog/core/catalog-core-standardframework/src/main/resources/OSGI-INF/blueprint/fedstrategy.xml, catalog/core/catalog-core-standardframework/src/main/resources/OSGI-INF/metatype/metatype.xml, catalog/solr/catalog-solr-provider/src/main/resources/OSGI-INF/metatype/metatype.xml
Adds the ability to provide a whitelist or blacklist for text fields that are included in an anyText query.
@bdeining
@pklinef
@codice/solr 
@jlcsmith
1. Build and do a standard profile install
2. Ingest some data
3. Perform an anyText query that will find the data
4. In the admin console, select the `Solr Catalog` application
5. Edit the `Solr Catalog Provider` configuration
6. Add new whitelist or blacklist entries
- entries can be the field name as seen by DDF OR Solr (i.e. `id` or `id_txt`)
- entries can be regular expressions (i.e. to ignore all security fields use `security.*`)
7. In the admin console, select the `Catalog` application and choose Configuration
8. Edit the `Solr Cache Provider` configuration
9. Add the same configuration here as in the `Solr Catalog …
=> DDF-5940 - Add anyText expansion whitelist and blacklist

ui/packages/catalog-ui-search/package.json, ui/yarn.lock
=> [2.19.x] DDF-5936 G-3094 Bump USNG

ui/packages/catalog-ui-search/src/main/webapp/component/query-add/query-add.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/search-form-interactions/search-form-interactions.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/search-form-list/search-form-list.js, ui/packages/catalog-ui-search/src/main/webapp/component/search-form/search-form.js, ui/packages/catalog-ui-search/src/main/webapp/component/search-form/search-form.view.js, ui/packages/catalog-ui-search/src/main/webapp/extension-points/search-interactions/search-interactions.container.tsx, ui/packages/catalog-ui-search/src/main/webapp/extension-points/search-interactions/search-interactions.presentation.tsx, ui/packages/catalog-ui-search/src/main/webapp/extension-points/search-interactions/search-interactions.tsx, ui/packages/catalog-ui-search/src/main/webapp/js/model/QuerySettings.js
- adds a check next to the selected search form so a user can easily identify which form is selected
- selected user forms will now stay selected after search/refresh if user does not have a default form
@hayleynorton @zta6 @cassandrabailey293 
@bdeining
@bdthomson
- build / run
- create search forms
- open a new search and switch between forms, verify correct form is checked
- make one of the search forms default
- open a new search, verify correct form is checked
- switch search form and run, open a new search and verify default form is showing and checked
Fixes: #codice/ddf-ui#140
- ✏️ …
=> [2.19.x] DDF-UI-140 add check to selected search form

catalog/transformer/catalog-transformer-csv-queryresponse/src/main/java/ddf/catalog/transformer/csv/CsvMetacardTransformer.java, catalog/transformer/catalog-transformer-csv-queryresponse/src/test/java/ddf/catalog/transformer/csv/CsvMetacardTransformerTest.java
Backend portion of the Forward port of #5931 
_____________________________________________________________________________
This PR fixes the single result export so that only the attributes that exist on that particular record will show up as columns in the .csv 
@codice/ui 
@bdeining 
- build/install
- add some records
- search for records and click the ellipsis menu on the bottom right corner of the result
- select "Export as"
- choose csv and download
- verify that the blank attributes are filtered out
Fixes: https://github.com/codice/ddf-ui/issues/135
- ✏️ …
=> [2.23.x] DDF-UI-135 filter blank attributes from CSV export result

platform/security/rest/security-rest-clientapi/src/main/java/org/codice/ddf/cxf/client/ClientFactoryFactory.java, platform/security/rest/security-rest-cxfwrapper/src/main/java/org/codice/ddf/cxf/client/impl/ClientFactoryFactoryImpl.java, platform/security/rest/security-rest-cxfwrapper/src/main/java/org/codice/ddf/cxf/client/impl/SecureCxfClientFactoryImpl.java
Backport of #5949 
@bennuttle @leo-sakh @frnkshin @nsuvarna
=> [2.23.x] DDF-5948 Add constructor to Client Factory

Documentation-versions.html
Adds links to the 2.21.6 version of the DDF documentation. Also archives that version on the site.
@codice/docs 
@clockard
@jrnorth
@lessarderic
@mcalcote
@shaundmorris
verify version numbers …
=> DDF-4759 added v2.21.6 to documentation archive on product site

ui/packages/catalog-ui-search/src/main/webapp/js/Common.js
adds preceding 0 to hours 1-9 to correct 12 Hour Standard format, hour place required to be 2 digits 
@hayleynorton @cassandrabailey293 @zta6 
@bdeining
@bdthomson
- In user settings change time format to 12 Hour Standard
- verify a leading 0 for hours 1-9
Fixes: #____ …
=> [2.19.x] DDF-UI-155 fix 12 Hour Standard format

catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/SolrProviderRealTimeQueryTest.java, catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/SolrProviderTest.java, distribution/ddf-common/src/main/resources/common-bin.xml, distribution/ddf-common/src/main/resources/security/default.policy, distribution/kernel/pom.xml, platform/solr/solr-factory-impl/src/main/java/org/codice/solr/factory/impl/Configsets.java, platform/solr/solr-factory-impl/src/main/java/org/codice/solr/factory/impl/SolrCloudClientFactory.java, platform/solr/solr-factory-impl/src/test/groovy/org/codice/solr/factory/impl/SolrCloudClientFactorySpec.groovy, platform/solr/solr-factory-impl/src/test/java/org/codice/solr/factory/impl/ConfigsetsTest.java
Provides a way to override the default configuration for all collections and a way to override individual collections from the `etc` directory.
@lamhuy 
@derekwilhelm 
@codice/solr 
@rzwiefel
@bdeining
Unzip the DDF build.  Copy `etc/solr/configsets/_default` to `etc/solr/configsets/catalog`.  Add different words to `conf/protwords.txt` under each directory.  Start DDF with a clean SolrCloud.  Verify `catalog` has its given word and that all other collections have the `_default` given word.
http://localhost:8994/solr/#/catalog/files?file=protwords.txt
http://localhost:8994/solr/#/alerts/files?file=protwords.txt
Fixes #5984 …
=> DDF-5984 Support overriding default Solr configsets from etc

catalog/transformer/catalog-transformer-csv-queryresponse/src/main/java/ddf/catalog/transformer/csv/CsvMetacardTransformer.java, catalog/transformer/catalog-transformer-csv-queryresponse/src/test/java/ddf/catalog/transformer/csv/CsvMetacardTransformerTest.java, ui/packages/catalog-ui-search/src/main/webapp/react-component/results-export/container.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/utils/export/export.tsx
This PR fixes the single result export so that only the attributes that exist on that particular record will show up as columns in the .csv 
@codice/ui 
@bdeining 
- build/install
- add some records
- search for records and click the ellipsis menu on the bottom right corner of the result
- select "Export as"
- choose csv and download
- verify that the blank attributes are filtered out
Fixes: https://github.com/codice/ddf-ui/issues/135 …
=> [2.19.x] DDF-UI-135 filter blank attributes from CSV export result

ui/packages/catalog-ui-search/src/main/webapp/react-component/dropdown/dropdown.js
Allows the dropdown's CSS `overflow` property to be manually set so the dropdown component can be implemented in different styles.
@bennuttle @frnkshin @leo-sakh 
Passing build should be sufficient as no real testing is necessary, the changes just allow for different uses of the dropdown if desired.
Fixes: #5972  …
=> [2.19.x] DDF-5972 Allow dropdown overflow property to be set manually

pom.xml
Removes the mvn site plugin for a small build speed boost (see screenshot of what was being printed on every module. More time is saved on a clean repo build. I also ran 
> mvn site:site 
That still works if anybody needs to actually run the site plugin. Just would grab the latest version.
@ricklarsen 
@TonyMorrison 
@LinkMJB 
@codice/build 
@pklinef 
@ricklarsen 
Build passes
Fixes: #5977  …
=> DDF-5977 remove unused mvn site-plugin

ui/packages/catalog-ui-search/src/main/webapp/component/result-form/result-form.hbs, ui/packages/catalog-ui-search/src/main/webapp/component/result-form/result-form.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/result-form/result-forms.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/search-form/search-form.view.js, ui/packages/catalog-ui-search/src/main/webapp/js/model/User.js
Creates consistent behavior for read only result forms.
System result forms and result forms shared to a user with only read permission will now allow you to click to open them, but all sections will be read-only and unmodifiable. 
@hayleynorton @zta6 @andrewzimmer 
@codice/ui 
1. build/profile install/ load system result forms (add forms to etc/forms folder and run `forms:load` command)
2. Share a result form with your user and make it read only
3. verify that for both the system result form and the shared result form, you can open the result form and see its details, but not modify them, and no error toast messages pop up.
Fixes: https://github.com/codice/ddf-ui/issues/153
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidel …
=> [2.19.x] DDF-UI-153 readonly result forms

Jenkinsfile, pom.xml
- changed Docker container from linux-large to linux-large-ddf which contains the maven dependency cache which can reduce time for the build stage.
- upgraded maven version to maven-latest as well as the version of the release plugin
- upgraded checkout to include shallow clone and increase timeout to 30 mins
- added error trapping to cleanup code in the post section  
- upgraded the ddf-parent version 1.0.10 which has the correct release-plugin version for the new maven version 
@LinkMJB 
@bdeining 
@shaundmorris 
@bdeining
@shaundmorris
Ran the pipeline in a test job
http://jenkins.phx.connexta.com/service/jenkins/job/W.I.P./job/DDF_TM/job/master/
Fixes: #BR-93
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+G …
=> BR-93 Implement Maven Repository Caching for DDF

ui/packages/catalog-ui-search/src/main/webapp/component/location-new/geo-components/coordinates.js, ui/packages/catalog-ui-search/src/main/webapp/component/location-new/utils/dd-utils.js, ui/packages/catalog-ui-search/src/main/webapp/component/location-new/utils/dms-utils.js, ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-old.js, ui/packages/catalog-ui-search/src/main/webapp/js/widgets/cesium.bbox.js, ui/packages/catalog-ui-search/src/main/webapp/js/widgets/openlayers.bbox.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/location/bounding-box.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/utils/validation/validation.tsx
This PR adds inline and pop-up error messaging for when a bounding box's south value is greater than or equal to the north value. It prevents the invalid bounding box from rendering on both maps and prevents the user from executing the search until the error is resolved.
This PR also refactors some of the validation functions in dms-utils and dd-utils
@codice/ui 
@bdeining
@shaundmorris 
- Create an anyGeo search with a bounding box 
- Enter south values that are less than or equal to a north value
- Verify that you see the inline error message (first screenshot below)
- Switch to different coordinate systems and verify the message persists (USNG and UTM messages will be worded differently; see second screenshot below)
- Verify that nothing is …
=> [2.19.x] DDF-UI-146 Add error messaging for when bounding box south >= north

ui/packages/catalog-ui-search/src/main/webapp/component/location-new/inputs/masked-text-field.js, ui/packages/catalog-ui-search/src/main/webapp/component/location-new/utils/dms-utils.js, ui/packages/catalog-ui-search/src/main/webapp/component/location-old/location-old.js
This PR fixes three issues:
- codice/ddf-ui#157 UTM/UPS coordinates were being automatically cleared if an invalid value was entered
- codice/ddf-ui#160 DMS coordinate fields were not populating on draw
- codice/ddf-ui#161 DMS underscore placeholders were present if there was less than 3-decimal-point precision 
@andrewzimmer @cassandrabailey293 @gjvera @willwill96 @zta6 
@codice/ui 
@bdeining 
@shaundmorris 
Fixes: codice/ddf-ui#157
Fixes: codice/ddf-ui#160
Fixes: codice/ddf-ui#161 …
=> [2.19.x] DDF-UI-157-160-161 DMS geo search bug fixes

catalog/core/catalog-core-impl/filter-proxy/pom.xml
Made filter-proxy use osgi friendly geotools suite
@pklinef
@millerw8
Fixes: #____
=> [2.19.x] DDF-5994 G-8222 filter proxy to use geotools suite

Jenkinsfile, pom.xml
Upgrades GIB to see if we get some performance improvements
@LinkMJB 
@TonyMorrison 
@brhumphe 
@codice/build 
@mcalcote 
@rzwiefel 
Fixes: #5998  …
=> DDF-5998 Upgraded to GIB 3.10.0

ui/packages/catalog-ui-search/src/main/webapp/js/widgets/openlayers.polygon.js
Fixes a bug introduced by #5851 
@bdeining 
@millerw8 
@bennuttle 
@frnkshin 
@nsuvarna 
@lavoywj 
@codice/ui 
@bdeining
@millerw8
Same as #5801 
See #5851 
Fixes: #5897  …
=> [2.19.x] DDF-5897: Fixed drawing polygons without buffers

distribution/ddf-common/src/main/resources/security/default.policy, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestOidc.java, features/security/src/main/feature/feature.xml, platform/security/core/security-core-services/src/main/java/org/codice/ddf/security/jaxrs/impl/RestSecurity.java, platform/security/handler/security-handler-oidc/pom.xml, platform/security/handler/security-handler-oidc/src/main/java/org/codice/ddf/security/handler/oidc/OidcCallbackEndpoint.java, platform/security/handler/security-handler-oidc/src/main/java/org/codice/ddf/security/handler/oidc/OidcLogoutActionProvider.java, platform/security/handler/security-handler-oidc/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/security/handler/security-handler-oidc/src/test/java/org/codice/ddf/security/handler/oidc/OidcCallbackEndpointTest.java, platform/security/handler/security-handler-oidc/src/test/java/org/codice/ddf/security/handler/oidc/OidcLogoutActionProviderTest.java, platform/security/realm/security-realm-guest/src/main/java/org/codice/ddf/security/guest/realm/GuestRealm.java, platform/security/realm/security-realm-pki/src/main/java/org/codice/ddf/security/pki/realm/PKIRealm.java, platform/security/realm/security-realm-userpass/src/main/java/org/codice/ddf/security/userpass/realm/UsernamePasswordRealm.java, platform/security/servlet/security-servlet-default-logout/pom.xml, platform/security/servlet/security-servlet-default-logout/src/main/java/org/codice/ddf/security/servlet/local/logout/DefaultLogoutAction.java, platform/security/servlet/security-servlet-logout/pom.xml, platform/security/servlet/security-servlet-logout/src/main/java/org/codice/ddf/security/servlet/logout/LocalLogoutServlet.java, platform/security/servlet/security-servlet-logout/src/main/java/org/codice/ddf/security/servlet/logout/LogoutServiceImpl.java, platform/security/servlet/security-servlet-logout/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/security/servlet/security-servlet-logout/src/test/java/org/codice/ddf/security/servlet/logout/LogoutServiceImplTest.java, platform/security/servlet/security-servlet-logout/src/test/java/org/codice/ddf/security/servlet/logout/LogoutServletTest.java, ui/packages/security-logout/src/main/resources/index.html, ui/packages/security-logout/src/main/resources/logout-response.html, ui/packages/security-logout/src/main/webapp/js/logout-response.js, ui/packages/security-logout/src/main/webapp/js/main.js
Simplifies logout such that we attempt to log out from a single URL. This will allow us to remove the use of iframes when logging out of external IdPs and appropriately propagate logout errors to the user.
@bakejeyner 
@SmithJosh 
@stustison
- On logout, you should see a message to close your browser for both auth types
- On logout, you should see a message that you are logged out with a link to sign back in
- On logout, you should see the logout page of the SAML provider
- To get the 403 error page, log in to Intrigue using OIDC auth then navigate to the admin page
- On logout, you should see a message that you are logged out with a link to sign back in. The link should take you to the admin page
Fixes: #5974 …
=> DDF-5974 Simplifies logout such that we attempt to log out from a single url

pom.xml
Upgrades jRuby dependency for documentation module
@codice/build 
@codice/docs 
@clockard
@mcalcote
@shaundmorris
Documentation module builds as expected …
=> DDF-2409 upgraded Jruby version used by docs module

catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/DynamicSchemaResolver.java, catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/provider/SolrProviderSpatial.java
Fixes a Solr create error when the generated centroid of the location used for sorting is out of spatial bounds.
@derekwilhelm 
@lamhuy 
@codice/solr 
@bdeining
@millerw8
Verify a metacard with a location like `LINESTRING (-180 -63.0065, -180 -90, -180 -63.0065)` is successfully created. 
Fixes: n/a
- ❓ …
=> Fix Solr create error when sort geo is out of bounds

ui/packages/catalog-ui-search/src/main/webapp/component/select/select.collection.view.js
This PR adds a null check for empty collections to ensure that no errors are thrown
@bdeining 
@shaundmorris 
Verify no regression in drop-down menus
Fixes: codice/ddf-ui#179
G-8210 …
=> [2.19.x] DDF-UI-179 Added null check for empty collections

platform/security/rest/security-rest-cxfwrapper/src/main/java/org/codice/ddf/cxf/oauth/OAuthSecurityImpl.java
When the status is not okay for getting access token, sanitize the password field before logging request and response information in trace logs.
Also, log if the password was being sent over encrypted, which it should not be.
@blen-desta 
@ryeats 
@coyotesqrl 
@stustison
Fixes: #6000  …
=> DDF-6000 Add additional logging with getting an AccessToken

ui/packages/beta-admin-ui/package.json, ui/packages/beta-admin-ui/src/main/webapp/components/entry/entry.tsx, ui/yarn.lock
- Includes fix for namespaced local storage
=> Upgrade to latest Kanri

catalog/core/catalog-core-impl/filter-proxy/pom.xml
Made filter-proxy use osgi friendly geotools suite
@pklinef
@millerw8
Fixes: #____
=> [2.23.x] DDF-5994 G-8222 filter proxy to use geotools suite (#5995)

catalog/core/catalog-core-impl/filter-proxy/pom.xml
Made filter-proxy use osgi friendly geotools suite
@pklinef
@millerw8
Fixes: #____
=> DDF-5994 G-8222 filter proxy to use geotools suite (#5995)

distribution/docs/src/main/resources/content/_managing/_running/ddf-service.adoc
See title.
@mdang8 
@cjlange
@clockard 
@mcalcote 
@codice/docs 
@ricklarsen 
@clockard
@mcalcote
=> Updating documentation with a warning to reflect a corner case during installation

ui/packages/catalog-ui-search/src/main/webapp/js/widgets/cesium.bbox.js, ui/packages/catalog-ui-search/src/main/webapp/js/widgets/cesium.circle.js, ui/packages/catalog-ui-search/src/main/webapp/js/widgets/cesium.line.js, ui/packages/catalog-ui-search/src/main/webapp/js/widgets/cesium.polygon.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/filter/filter-input/filter-location-input.js
This PR does two things:
1. Fixes the keyword issue, where geometries remained drawn on the map even after searching a new keyword. 
2. If the user causes a currently valid geometry to be invalid (e.g., deleting a value), that geometry is now removed from the map. 
@hayleynorton @zta6 @andrewzimmer 
@codice/ui 
Testing keyword:
1. Open an anyGeo search and select keyword
2. Search for a region 
3. See that the geo for that region pops up
4. Search another region in the same anyGeo Keyword search
5. See the new region pop up and the old one go away
Testing invalid geos:
1. Open an anyGeo search and select one of the geometries
2. Draw the geo and notice the drawn geo displays on the map
3. Delete part of the input for the geo to make it invalid
4. Verify that the geo disappears from the …
=> [2.19.x] DDF-UI-184 G-4697 removal of old/invalid 3-D map geometries 

distribution/test/itests/test-itests-ddf/pom.xml, features/apps/pom.xml, features/camel/pom.xml, features/camel/src/main/feature/feature.xml, features/security/pom.xml
Finishes removing references to deleted code (custom Karaf feature and FTP) 
@ryeats 
@peterhuffer 
@codice/build 
Nightly release job has been failing since April due to not catching this earlier.
Fixes: #5854 
- ❗ …
=> DDF-5854 fixed release issues with deleted code

ui/packages/catalog-ui-search/src/main/webapp/react-component/filter/filter-input/filter-text-inputs/filter-near-input/nearFilterHelper.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/filter/filter-input/filter-text-inputs/filter-near-input/nearFilterHelper.spec.js
2.19.x port of https://github.com/codice/ddf-ui/pull/200
Fixes a silent error that was causing 'near' queries to fail to return results. 
@hayleynorton @cassandrabailey293  @andrewzimmer
@bdeining 
@Bdthomson 
Build, profile:install
Ingest some metacards
Run some 'near' queries and verify that the proper results are returned. 
Fixes: DDF-UI-198
Screenshots
Checklist:
Update / Add Threat Dragon models
Please see Notes on Review Process for further guidance …
=> DDF-UI-198 Fix near queries not returning results

catalog/core/catalog-core-api/src/main/java/ddf/catalog/operation/ResourceRequest.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/ResourceOperations.java, platform/security/handler/security-handler-pki/pom.xml
Enhances the resource operations to handle a special case where a qualifier is present on the request to reference a specific derived resource to retrieve instead of the main resource.
@mcalcote 
@peterhuffer 
@figliold
@pklinef
@stustison
- ingest something that will generate derived resources
- send a REST request for a retrieving a resource for the metacard and add `&QUALIFIER=xxx` to the URL (e.g. `/services/catalog/{id}?QUALIFIER=xxx`). Where xxx represents the qualifier of a derived resource
- The derived resource should be returned instead of the main resource
Fixes: #____
- ✏️ (Pencil) …
=> [2.21.x] Enhanced catalog framework to support retrieval of derived resources

platform/platform-paxweb-jettyconfig/src/main/java/org/codice/ddf/pax/web/jetty/ClientInfoFilter.java, platform/platform-paxweb-jettyconfig/src/test/java/org/codice/ddf/pax/web/jetty/ClientInfoFilterTest.java
Adds additional headers to the client info map to help determine how to re-write catalog requests and responses.
@mcalcote 
@figliold @paouelle 
Fixes: #____ …
=> [2.21.x] Add headers to help determine how to rewrite catalog responses

platform/security/rest/security-rest-clientapi/src/main/java/org/codice/ddf/cxf/client/ClientFactoryFactory.java, platform/security/rest/security-rest-cxfwrapper/src/main/java/org/codice/ddf/cxf/client/impl/ClientFactoryFactoryImpl.java, platform/security/rest/security-rest-cxfwrapper/src/main/java/org/codice/ddf/cxf/client/impl/SecureCxfClientFactoryImpl.java
Adds a constructor to Client Factory to allow OAuth flow along with REST security for a downstream project.
@nsuvarna @bennuttle @leo-sakh @frnkshin 
@bdeining @blen-desta
Full build should be sufficient, this change just adds a constructor to be used by a downstream project.
Fixes: #5948  …
=> DDF-5948 Add constructor to Client Factory

platform/security/rest/security-rest-cxfwrapper/src/main/java/org/codice/ddf/cxf/client/impl/ClientFactoryFactoryImpl.java, platform/security/rest/security-rest-cxfwrapper/src/main/java/org/codice/ddf/cxf/client/impl/SecureCxfClientFactoryImpl.java
https://github.com/codice/ddf/pull/5949 was merged before a necessary rebase / refactor could take place, this fixes the issues.
@leo-sakh @bdeining @bennuttle 
Fixes: #5948  …
=> DDF-5948 Fix ClientFactory constructor

distribution/docs/src/main/resources/content/_integrating/_endpoints/catalog-rest-endpoint.adoc
Updates the example in the Catalog REST Update Operation Examples section with a properly formed URL.
@josephthweatt
@mdang8
@cjlange
@codice/docs 
@clockard
@ricklarsen …
=> Updating DDF Rest Update Example documentation

dependency-check-maven-config.xml, distribution/docs/src/main/resources/content/_integrating/_endpoints/catalog-rest-endpoint.adoc
Updates the example in the Catalog REST Update Operation Examples section with a properly formed URL.
@josephthweatt
@mdang8
@cjlange
@codice/docs
@clockard
@ricklarsen …
=> [2.21.x] Updating DDF Rest Update Example documentation

distribution/ddf-common/src/main/resources/etc/solr/configsets/catalog/collection.properties, distribution/ddf-common/src/main/resources/etc/solr/configsets/default/collection.properties, distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/AbstractIntegrationTest.java, distribution/test/itests/test-itests-common/src/main/resources/collection.properties, platform/solr/solr-factory-impl/src/main/java/org/codice/solr/factory/impl/CollectionConfig.java, platform/solr/solr-factory-impl/src/main/java/org/codice/solr/factory/impl/SolrCloudClientFactory.java, platform/solr/solr-factory-impl/src/test/java/org/codice/solr/factory/impl/CollectionConfigTest.java, platform/solr/solr-factory-impl/src/test/java/org/codice/solr/factory/impl/ConfigsetsTest.java, platform/solr/solr-factory-impl/src/test/resources/configsets/default/collection.properties, platform/solr/solr-factory-impl/src/test/resources/configsets/test/collection.properties
Makes it possible to override per collection or by default the number of shards, replication factor, and allowed shards per node when collections are created.  The number of shards for the catalog collection is now 6 shards instead of 2 shards.  All other collections still have 2 shards by default.
@lamhuy 
@derekwilhelm 
@codice/solr 
@rzwiefel
@bdeining
Go to http://localhost:8994/solr/#/catalog/collection-overview
Verify that the catalog collection has 6 shards.
Go to http://localhost:8994/solr/#/alerts/collection-overview
Verify that the alerts collection has 2 shards.
You can verify the values under `etc/solr/configsets/default/collection.properties` and `etc/solr/configsets/catalog/collection.properties`.
Fixes: n/a
- [ n/a ] Update / Add Threat …
=> Support per collection properties with Solr

pom.xml
Upgrades to the released version of DDF Admin UI
This also will fix the release
@blen-desta 
@codice/build 
@codice/ui 
Fixes: #6012  …
=> DDF-6012 upgraded to Admin-UI 2.25.0

ui/packages/catalog-ui-search/src/main/webapp/react-component/location/bounding-box.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/utils/validation/validation.tsx
This PR adds an inline error message for when the west coordinate equals the east coordinate in a bounding box geo filter. It also prevents the search from executing and triggers a pop-up error message
@andrewzimmer @cassandrabailey293 @maryformanek @TeresaHudson @zta6 
@bdeining 
@shaundmorris 
Verify you see an inline error message when east = west in all coordinate systems. Verify that drawing a new shape makes the error message disappear in all coordinate systems. Also verify that there's no regression with the south >= north messaging or any other inline error messages. 
Fixes: codice/ddf-ui#199 …
=> [2.19.x] DDF-UI-199 Added error messaging for west = east

ui/packages/catalog-ui-search/src/main/webapp/component/metacard/metacard.js, ui/packages/catalog-ui-search/src/main/webapp/extension-points/routes/definitions/base.tsx, ui/packages/catalog-ui-search/src/main/webapp/extension-points/routes/definitions/base/openDetails.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/workspace-interactions/container.tsx
Fixes the 'view details' action for workspaces. 
@andrewzimmer 
@hayleynorton 
codice/ui 
@bdeining
@bdthomson
Build, profile:install
Create a few workspaces
From the 'workspaces' screen click the ellipsis menu and then the 'view details' action
verify that the 2D Map and Table view appear, with the details of the workspace metacard being displayed in the table view. 
Repeat for multiple workspaces
Move into one of the workspaces and trigger the 'view details' action from the ellipsis menu within the workspace, verify that this functions the same as above. 
Fixes: #6056 G-4800 …
=> DDF-6056 G-4800 Fix view details action

ui/packages/catalog-ui-search/src/main/webapp/component/paging/paging.view.js
Clears the selected result from the inspector view when a new query is run
@hayleynorton 
@andrewzimmer 
@bdeining
@bdthomson
Run a query
select a result to display it in the inspector view
run a new query
verify that the selected result is cleared from the inspector view.
Fixes: #6086  …
=> [2.19.x] DDF-6086 G-8302 Clear inspector view when new query is run

ui/packages/catalog-ui-search/src/main/webapp/component/visualization/table/table-rearrange.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/table/table-visibility.view.js, ui/packages/catalog-ui-search/src/main/webapp/extension-points/table-export/table-export.tsx, ui/packages/catalog-ui-search/src/main/webapp/js/model/LazyQueryResult/LazyQueryResult.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/table-export/container.tsx
Updates the table column order, column visibility, and export actions with the new LazyQueryResult formats.
=> Table column order, column visibility, and export fixes

ui/packages/catalog-ui-search/src/main/webapp/component/visualization/table/table-rearrange.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/table/table-visibility.view.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/result-sort/container.tsx
Keeps result sort dropdown in sync with sorts triggered from table columns.
=> Table sorting updates

features/cxf/src/main/feature/feature.xml, pom.xml
Dependency upgrades for:
Upgrades to dependencies in the root pom, including:
xerces
netty/netty-codec
Upgrade to snakeyaml in cxf's features.xml
@aaronilovici 
@mdang8 
@stustison 
Fixes: #6087  …
=> DDF-6075 Dependency Upgrades [2.21.x]

ui/packages/catalog-ui-search/src/main/webapp/js/filter.js
Addresses https://github.com/codice/ddf/issues/6037 by appending wildcards to the filter to properly handle CONTAINS operations and changes the matching to consider the entire string rather than addressing each token individually.
@leo-sakh 
@lavoywj 
@frnkshin 
@codice/ui 
@bdeining
See steps to reproduce in https://github.com/codice/ddf/issues/6037
Fixes: #6037 …
=> [2.19.x] DDF-6037 G-1625 Fix CONTAINS Filter Behavior with Multi-word Filters

platform/security/policy/security-policy-context/pom.xml, platform/security/policy/security-policy-context/src/main/java/org/codice/ddf/security/policy/context/impl/PolicyManager.java, platform/security/policy/security-policy-context/src/test/java/org/codice/ddf/security/policy/context/PolicyManagerTest.java
also fixed the tests in the unit test to put actual and expected in the right place of the assertions
@bakejeyner @SmithJosh 
@blen-desta
@jlcsmith
@stustison 
Fixes: #____ …
=> DDF-6066 added the ability to configure the file for the policy manager without restarting the bundle/system

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/CachingFederationStrategy.java
Forward part of https://github.com/codice/ddf/pull/6106
@derekwilhelm 
@pklinef 
@rzwiefel 
Verify prequery plugins have access to source IDs in the query request
Fixes: #6104  …
=> DDF-6104 maintain source IDs in CachingFederationStrategy

catalog/core/catalog-core-directorymonitor/pom.xml, catalog/core/catalog-core-solr/pom.xml, distribution/solr-distro/pom.xml, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestOidc.java, features/camel/src/main/feature/feature.xml, features/cxf/src/main/feature/feature.xml, features/pom.xml, features/security/src/main/feature/feature.xml, platform/admin/core/admin-core-impl/src/test/java/org/codice/ddf/admin/core/impl/AdminConsoleServiceTest.java, platform/security/core/security-core-impl/pom.xml, platform/security/handler/security-handler-api/src/main/java/org/codice/ddf/security/handler/api/OidcHandlerConfiguration.java, platform/security/handler/security-handler-oauth/src/main/java/org/codice/ddf/security/handler/oauth/CustomOAuthCredentialsExtractor.java, platform/security/handler/security-handler-oauth/src/main/java/org/codice/ddf/security/handler/oauth/OAuthHandler.java, platform/security/handler/security-handler-oauth/src/test/java/org/codice/ddf/security/handler/oauth/CustomOAuthCredentialsExtractorTest.java, platform/security/handler/security-handler-oidc/src/main/java/org/codice/ddf/security/handler/oidc/OidcCallbackEndpoint.java, platform/security/handler/security-handler-oidc/src/main/java/org/codice/ddf/security/handler/oidc/OidcHandler.java, platform/security/handler/security-handler-oidc/src/main/java/org/codice/ddf/security/handler/oidc/OidcLogoutActionProvider.java, platform/security/handler/security-handler-oidc/src/test/java/org/codice/ddf/security/handler/oidc/OidcHandlerTest.java, platform/security/handler/security-handler-oidc/src/test/java/org/codice/ddf/security/handler/oidc/OidcLogoutActionProviderTest.java, platform/security/handler/security-handler-oidc/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker, platform/security/realm/security-realm-oidc/src/main/java/org/codice/ddf/security/oidc/realm/CustomOidcProfileCreator.java, platform/security/realm/security-realm-oidc/src/main/java/org/codice/ddf/security/oidc/realm/OidcRealm.java, platform/security/realm/security-realm-oidc/src/test/java/org/codice/ddf/security/oidc/realm/OidcRealmTest.java, platform/security/security-oidc-bundle/src/main/java/org/codice/ddf/security/oidc/resolver/OidcCredentialsResolver.java, platform/security/security-oidc-bundle/src/main/java/org/codice/ddf/security/oidc/validator/OidcTokenValidator.java, platform/security/security-oidc-bundle/src/test/java/org/codice/ddf/security/oidc/validator/OidcTokenValidatorTest.java, pom.xml
Upgrades dependencies to address CVEs. The focus for this PR was on the handler bundles and security-core-impl. The following were updated:
PAC4J -> 4.0.1
Jackson -> 2.10.4
Shiro -> 1.5.3
This PR depends on https://github.com/codice/ddf/pull/6062. Ignore those commits.
@bakejeyner @blen-desta @garrettfreibott @stustison 
Full build and verify OIDC login/logout
This is part of an ongoing effort to reduce the CVE level in DDF
Fixes: #____ …
=> DDF-6069 Address security module CVEs

distribution/docs/src/main/resources/content/_integrating/_endpoints/csw-endpoint.adoc, distribution/docs/src/main/resources/content/_managing/_configuring/_sources/confluence-federated-source.adoc, distribution/docs/src/main/resources/content/_managing/_securing/managing-keystores.adoc, pom.xml
Upgrades Asciidoctorj dependency from 1.5.6 to 1.6.2. 
@codice/docs 
@clockard
@mcalcote
@shaundmorris
builds successfully
Added formatting changes to some section titles to address implementation changes of auto-generated links.  …
=> DDF-2824 upgraded asciidoctor and jruby dependencies

catalog/rest/catalog-rest-endpoint/src/test/java/org/codice/ddf/endpoints/rest/it/RestEndpointIT.java, libs/httpproxy/pom.xml, libs/test-common/pom.xml, libs/test-common/src/main/java/org/codice/ddf/test/common/AbstractComponentTest.java, pom.xml
Adds byte-buddy dependencies to the list of test dependencies that get installed during component tests. They are required by Mockito.
@stustison @pklinef @bakejeyner @blen-desta @garrettfreibott 
@codice/test 
Full build (don't use -DskipITs flag!)
This is a follow on to https://github.com/codice/ddf/pull/6062 because it left some stuff broken
Fixes: https://github.com/codice/ddf/issues/6061 …
=> Install byte-buddy dependencies for component tests

catalog/solr/catalog-solr-defaultmetacardtagscacheplugin/pom.xml
Fix incorrect parent pom coordinates after moving module.  Currently fails with a clean maven cache.
Builds we a clean .m2 directory.
Fixes: #____
=> Fix parent pom coordinates

platform/security/filter/security-filter-csrf/pom.xml
Changes the version of the CSRF filter module
@bdeining 
@bakejeyner 
- Should get a 403 when hitting jolokia endpoints and the system doesn't change because of that request
- Hitting endpoints under `/search/catalog/internal` from non-browser user-agents will be forbidden unless specific headers are present or are whitelisted contexts
- Hitting endpoints under `/services` from the browser will be forbidden unless they are whitelisted
Fixes: #6111 …
=> [2.19.x] DDF-6111 Changed the version of the CSRF filter module

catalog/solr/catalog-solr-app/pom.xml, catalog/solr/catalog-solr-app/src/main/resources/features.xml
Fixes the release build by updating a couple of mvn group ids. Need to verify if this is the appropriate fix. 
@codice/solr 
@pklinef 
Build and release build pass
I verified the release build was fine locally …
=> Fix Release Build 

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/security/accesscontrol/AccessControlAccessPlugin.java, catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/blueprint/provides.xml, catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/metatype/org.codice.ddf.catalog.ui.security.accesscontrol.xml, catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/security/accesscontrol/AccessControlAccessPluginTest.java, ui/packages/catalog-ui-search/exports/sharing.tsx
backport of https://github.com/codice/ddf-ui/pull/187
adds configuration for additional metacard tags to comply with catalogue's access control
@bdeining
@Lambeaux 
- build / unzip
- before starting ddf go into /etc/ directory, update user.attributes file to include
```
"test" : {
"http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress":"test@localhost.local",
"http://schemas.xmlsoap.org/ws/2005/05/identity/claims/role": ["manager","viewer","systembundles"]
}
```
and in user.properties files add 
```
test=test,group,manager,viewer,systembundles,ssh
``` 
- login with the admin user
- create new Workspace and share with other user test@localhost.local (read/write/share)
- verify with other user (test as user/password) that worskspace is shared and that operations outside the …
=> [2.19.x] DDF-UI-185 Add metacard tag configuration for enforcing access controls

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/CachingFederationStrategy.java, catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/cache/solr/impl/CachingFederationStrategyTest.java
Properties should be present in queryResponse for queryRequests containing multiple sources and an offset.
@AzGoalie 
@pklinef 
@bdeining
Fixes: #____ …
=> [2.19.x] Update CachingFederationStrategy

catalog/catalog-app/pom.xml, catalog/catalog-app/src/main/resources/features.xml, catalog/core/catalog-core-camelcomponent/pom.xml, catalog/core/catalog-core-standardframework/pom.xml, catalog/core/catalog-core-urlresourcereader/pom.xml, catalog/core/pom.xml, catalog/opensearch/catalog-opensearch-endpoint/pom.xml, catalog/pom.xml, catalog/spatial/ogc/spatial-ogc-urlresourcereader/pom.xml, catalog/transformer/catalog-transformer-common/pom.xml, catalog/transformer/catalog-transformer-pptx/pom.xml, catalog/transformer/catalog-transformer-tika-input/pom.xml, catalog/transformer/catalog-transformer-tika-input/src/test/java/ddf/catalog/transformer/input/tika/TikaInputTransformerTest.java, catalog/transformer/catalog-transformer-video-input/pom.xml, catalog/transformer/pom.xml, dependency-check-maven-config.xml, distribution/test/itests/pom.xml, features/admin/src/main/feature/feature.xml, features/kernel/src/main/feature/feature.xml, features/security/src/main/feature/feature.xml, features/solr/src/main/feature/feature.xml, features/test-utilities/src/main/feature/feature.xml, features/utilities/pom.xml, features/utilities/src/main/feature/feature.xml, libs/klv/pom.xml, platform/metrics/platform-metrics-reporting/pom.xml, platform/metrics/platform-metrics-reporting/src/main/java/ddf/metrics/reporting/internal/rrd4j/RrdMetricsRetriever.java, platform/pom.xml, pom.xml
Tika and its dependencies have a few CVEs reported against them. This PR upgrades to the latest Tika version to fix them. Also, upgrades POI and other transitive Tika dependencies to match the version that Tika uses.
This PR depends on https://github.com/codice/thirdparty/pull/86 
@blen-desta @garrettfreibott @bakejeyner @stustison 
@codice/io 
1. Build https://github.com/codice/thirdparty/pull/86
2. Build this PR branch and run DDF
3. Download this set of assorted file types: https://github.com/codice/ddf/tree/master/catalog/transformer/catalog-transformer-tika-input/src/test/resources. 
4. Test the Tika input transformer by ingesting those files from the Karaf shell.
```
admin@root()> catalog:ingest -t tika "/path/to/test/resources"
```
5. Test the video input …
=> DDF-6137 Upgrade Tika to 1.24.1

README.md
Update the README.md to mention / link to the release documentation
=> Updates README.md to mention / link to release doc

catalog/opensearch/catalog-opensearch-source/src/main/java/org/codice/ddf/opensearch/source/BoundingBoxUtils.java, catalog/opensearch/catalog-opensearch-source/src/main/java/org/codice/ddf/opensearch/source/OpenSearchSource.java
Added types to lists in opensearch source.
Fixes: #____
=> Added types to lists in opensearch source

catalog/opensearch/catalog-opensearch-source/src/main/java/org/codice/ddf/opensearch/source/BoundingBoxUtils.java, catalog/opensearch/catalog-opensearch-source/src/main/java/org/codice/ddf/opensearch/source/OpenSearchSource.java
Added types to lists in opensearch source
Fixes: #____
=> [2.23.x]. Added types to lists in opensearch source

catalog/opensearch/catalog-opensearch-source/src/main/java/org/codice/ddf/opensearch/source/BoundingBoxUtils.java, catalog/opensearch/catalog-opensearch-source/src/main/java/org/codice/ddf/opensearch/source/OpenSearchSource.java
Added types to lists in opensearch source
Fixes: #____
=> [2.19.x] Added types to lists in opensearch source

distribution/docs/src/main/resources/content/_integrating/_endpoints/query-endpoints.adoc
edits the header of the content for the Queries endpoint to place it in the appropriate subsection.
@codice/docs 
@ahoffer
@pklinef
=> DDF-2824 fixed header in queries endpoint docs

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/SortedQueryMonitor.java, catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/cache/solr/impl/SortedQueryMonitorTest.java
Back port of PR #6147 
When sorting on an attribute where some of the results do not have that attribute it can cause issues with paging. The reason is because the sorting mechanism in DDF for ascending sort order sorts nulls first. Solr, on the other hand, always sorts nulls last regardless of the sort order. Therefore, when paging through results if a result with a null attribute that is being sorted on shows up in a later page it will get sorted to the beginning of the list inside DDF and skipped in the returned result list. This also has the effect of a result page containing a duplicate entry from the previous page. This PR changes the DDF sort to match Solr where nulls are always last.
@pklinef
@bdeining
@codice/data
@codice/solr
@codice/ui …
=> [2.24.x] DDF-6146 - Change null sort to match solr

ui/packages/catalog-ui-search/src/main/webapp/styles/components/base.less
Changes the color of placeholder text to adapt to the user selected theme. This was done by adding the ::placeholder field to base.less, setting it to inherit the regular text color and setting the opacity to 0.5 to make it appear lighter than regular text.
@leo-sakh
@lavoywj
@bennuttle
@rymach
@bdeining
@bdeining
@rzwiefel
1. Build, Install and start DDF
2. Click Search DDF Intrigue
3. Observe the placeholder test in the text input boxes
Fixes: #6159
Before:
After: …
=> [2.19.x] DDF-6159 Made Textbox Placeholder text more visible

ui/packages/catalog-ui-search/src/main/webapp/component/visualization/table/thead.view.js
Removes id if label is present for table headers.
Fixes: #____
=> 2.19.x Repeat label on table headers.

distribution/docs/src/main/resources/content/_managing/_running/validator-plugins.adoc
DDF-6177 adding ID of Metacard Validators to docs
@aaronilovici 
@ricklarsen 
@codice/docs 
Fixes: #DDF-6177 …
=> [2.21.x] DDF-6177

distribution/ddf-common/src/main/resources/security/default.policy
Add security policies to allow Admin UI to load applications 
@SmithJosh 
@derekwilhelm 
@pklinef 
Install DDF
Verify the Admin UI displays application configurations
Fixes: #____ …
=> [2.25.x] DDF-6185 correct security policies for Admin UI

distribution/ddf-common/src/main/resources/security/default.policy
Fixes policy violations coming from he Admin UI due to the metrics-servlet-filter. 
@pklinef 
@pklinef 
Fixes: #____
=> [2.25.x] DDF-6185 additional policies for Admin UI

distribution/docs/src/main/resources/content/_managing/_running/validator-plugins.adoc
DDF-6177 adding ID of Metacard Validators to docs
@aaronilovici 
@ricklarsen 
@codice/docs 
Fixes: #DDF-6177 …
=> DDF-6177 adding ID of Metacard Validators to docs

distribution/ddf-common/src/main/resources/security/default.policy, platform/platform-paxweb-jettyconfig/src/main/java/org/codice/ddf/pax/web/jetty/DoPrivilegedFilter.java, platform/platform-paxweb-jettyconfig/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/platform-paxweb-jettyconfig/src/test/java/org/codice/ddf/pax/web/jetty/DoPrivilegedFilterTest.java
Added doPrivileged call as last injected servlet filter to separate execution thread of endpoints from injected servlet filters.
@derekwilhelm 
@stustison
@jlcsmith
Verify you can go through all steps of the installer and reach all endpoints without policy violations.
Fixes: n/a …
=> Decouple injected servlet filters from security policy of endpoints

ui/packages/catalog-ui-search/src/main/webapp/component/lightbox/result/lightbox.result.less, ui/packages/catalog-ui-search/src/main/webapp/component/search-form-editor/search-form-editor.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/tabs/tabs.less
Issues:
1. Search Forms - Title input form partially hidden
2. Result Forms - Attributes Title goes underneath its form
3. For both Result and Search Form - When have multiple items and zoomed percentage is higher than 150%, no way to get to other items, since can't scroll down
@andrewzimmer 
@hayleynorton
@zta6 
@bdeining
Issue 1:
1. Go to Search Forms
2. Click on "+ Search Forms" to add new search form
3. Change Theme Zoom Percentage and Spacing to various settings
4. Ensure the " Search Name" input field is fully visible, no matter the theme settings.
Issue 2:
1. Go to Result Forms
2. Change Theme Zoom Percentage and Spacing to various settings 
3. Click on "New Result Forms" to add new result form
4. Ensure the "Attributes" input field label is …
=> [2.19.x] DDF-UI-273 Theme Zoom Percentage Formatting Issues

platform/security/filter/security-filter-web-sso/src/main/java/org/codice/ddf/security/filter/websso/WebSSOFilter.java
Lowers logging.  Too much spam
@stustison
Fixes: #____
=> [2.19.x] Lowered logging to prevent log spam

catalog/core/catalog-core-urlresourcereader/src/test/java/ddf/catalog/resource/impl/URLResourceReaderTest.java, catalog/opensearch/catalog-opensearch-source/src/test/java/org/codice/ddf/opensearch/source/OpenSearchSourceTest.java, catalog/solr/catalog-solr-solrclient/src/test/java/ddf/catalog/source/solr/rest/SolrRestTest.java, catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswSubscriptionEndpoint.java, catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/event/CswSubscription.java, catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/event/SendEvent.java, catalog/spatial/csw/spatial-csw-endpoint/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/spatial/csw/spatial-csw-endpoint/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswSubscriptionEndpointTest.java, catalog/spatial/csw/spatial-csw-source-common/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/CswSourceTest.java, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsSourceTest.java, catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/source/WfsSourceTest.java, platform/security/certificate/security-crl-generator/src/test/java/org/codice/ddf/security/crl/generator/CrlGeneratorTest.java, platform/security/certificate/security-ocsp-checker/src/test/java/org/codice/ddf/security/ocsp/checker/OcspCheckerTest.java, platform/security/rest/security-rest-clientapi/src/main/java/org/codice/ddf/cxf/client/ClientBuilder.java, platform/security/rest/security-rest-cxfwrapper/pom.xml, platform/security/rest/security-rest-cxfwrapper/src/main/java/org/codice/ddf/cxf/client/impl/ClientBuilderFactoryImpl.java, platform/security/rest/security-rest-cxfwrapper/src/main/java/org/codice/ddf/cxf/client/impl/ClientBuilderImpl.java, platform/security/rest/security-rest-cxfwrapper/src/main/java/org/codice/ddf/cxf/client/impl/SecureCxfClientFactoryImpl.java, platform/security/rest/security-rest-cxfwrapper/src/main/java/org/codice/ddf/cxf/client/interceptor/SubjectRetrievalInterceptor.java, platform/security/rest/security-rest-cxfwrapper/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/security/rest/security-rest-cxfwrapper/src/test/java/org/codice/ddf/cxf/SecureCxfClientFactoryTest.java
Renames the `OutgoingSubjectRetrievalInterceptor` to `SubjectRetrievalInterceptor`, moves it into the custom CXF client code, and adds a parameter to the CXF builder to enable the `SubjectRetrievalInterceptor`.
@blen-desta  
@SmithJosh  
@stustison 
T.B.D
Fixes: #6182  …
=> [2.25.x] DDF-6182 Move OutgoingSubjectRetrievalInterceptor into custom CXF client code

ui/packages/catalog-ui-search/src/main/webapp/component/dropdown/visualization-selector/dropdown.visualization-selector.hbs, ui/packages/catalog-ui-search/src/main/webapp/component/golden-layout/golden-layout.hbs, ui/packages/catalog-ui-search/src/main/webapp/component/golden-layout/golden-layout.less, ui/packages/catalog-ui-search/src/main/webapp/component/golden-layout/golden-layout.view.js
Add control to add a new visual tab from the tabs similar to a browser
@abel-connexta @cassandrabailey293 @hayleynorton @maryformanek 
@bdeining
- build / run
- create / delete visualization tabs, verify everything is working as expected
codice/ddf-ui#261 …
=> [2.19.x] DDF-UI-261 Add control to add a new visual tab from the tabs similar to a browser

ui/packages/catalog-ui-search/src/main/webapp/component/dropdown/visualization-selector/dropdown.visualization-selector.hbs, ui/packages/catalog-ui-search/src/main/webapp/component/golden-layout/golden-layout.hbs, ui/packages/catalog-ui-search/src/main/webapp/component/golden-layout/golden-layout.less, ui/packages/catalog-ui-search/src/main/webapp/component/golden-layout/golden-layout.view.js
Reverts codice/ddf#6162.  Needs to be blocked
https://github.com/codice/ddf/pull/6162
=> Revert "[2.19.x] DDF-UI-261 Add control to add a new visual tab from the tabs similar to a browser"

ui/packages/catalog-ui-search/src/main/webapp/react-component/time-settings/presentation.tsx
=> [2.19.x] G-1385 Change some verbiage with example label

libs/common-system/src/main/java/org/codice/ddf/configuration/PropertyResolver.java, libs/common-system/src/test/java/org/codice/ddf/configuration/PropertyResolverTest.java, libs/common-system/src/test/resources/properties.txt, platform/security/claims/security-claims-attributequery/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/security/claims/security-claims-attributequerycommon/pom.xml, platform/security/claims/security-claims-attributequerycommon/src/main/java/org/codice/ddf/security/claims/attributequery/common/AttributeQueryClaimsHandler.java, platform/security/claims/security-claims-attributequerycommon/src/test/java/org/codice/ddf/security/claims/attributequery/common/AttributeQueryClaimsHandlerTest.java, platform/security/core/security-core-impl/pom.xml, platform/security/core/security-core-services/pom.xml
Remove usage of PropertiesWrapper from AttributeQueryClaimsHandler
Add file reading logic to PropertyResolver
Lower unit test log levels on some security bundles
@blen-desta 
@emmberk 
@SmithJosh 
@stustison  
TBD
Fixes: #6218 
- ❗ …
=> [2.25.x] DDF-6218 Remove usage of PropertiesWrapper from AttributeQueryClaimsHandler

platform/platform-scheduler/src/main/java/ddf/platform/scheduler/CommandJob.java, platform/platform-scheduler/src/main/java/ddf/platform/scheduler/ScheduledCommandTask.java, platform/platform-scheduler/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/platform-scheduler/src/test/java/ddf/platform/scheduler/CommandJobTest.java, platform/platform-scheduler/src/test/java/ddf/platform/scheduler/ScheduledCommandTaskTest.java, platform/platform-scheduler/src/test/java/ddf/platform/scheduler/ServiceStoreTest.java
...to take in a Quartz Job instance instead of a Quartz Job class
Changes the `ScheduledCommandTask` constructor to take in a Quartz `Job` instance instead of a Quartz `Job` class, since thats how it is instantiated in blueprint.
@blen-desta 
@emmberk 
@SmithJosh 
@stustison 
Pass CI.
Fixes: #6224  …
=> [2.25.x] DDF-6224 Change ScheduledCommandTask constructor

catalog/solr/catalog-solr-offline-gazetteer/src/main/java/ddf/catalog/solr/offlinegazetteer/BuildGazetteerSuggesterIndexCommand.java, catalog/solr/catalog-solr-offline-gazetteer/src/main/java/ddf/catalog/solr/offlinegazetteer/CatalogGazetteerForwardingPlugin.java, catalog/solr/catalog-solr-offline-gazetteer/src/main/java/ddf/catalog/solr/offlinegazetteer/GazetteerQueryOfflineSolr.java, catalog/solr/catalog-solr-offline-gazetteer/src/main/java/ddf/catalog/solr/offlinegazetteer/RemoveAllOfflineSolrGazetteerCommand.java, catalog/solr/catalog-solr-offline-gazetteer/src/main/java/ddf/catalog/solr/offlinegazetteer/SyncCatalogCommand.java
=> Fixes format issues

catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/transformer/TransformerManager.java, catalog/spatial/csw/spatial-csw-common/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/common/transformer/TransformerManagerTest.java, catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java, catalog/spatial/csw/spatial-csw-endpoint/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpointTest.java, catalog/spatial/csw/spatial-csw-transformer/src/main/resources/OSGI-INF/blueprint/blueprint.xml
CSW DescribeRecord does not show all the schemas that getCapabilities enumerates.
This is due to content being hardcoded and not dynamically retrieved.
@andrewzimmer 
@hayleynorton
@zta6 
@bdeining
- Build and install
- Perform and verify following request(s)
**Request Type - GET:**
- Request All available item(s)
`https://localhost:8993/services/csw?version=2.0.2&service=CSW&request=describeRecord`
Should return all available schema(s) (2)
- Request Single item
`https://localhost:8993/services/csw?version=2.0.2&service=CSW&request=describeRecord&namespace=xmlns(gmd=http://www.isotc211.org/2005/gmd)&typeName=gmd:MD_Metadata`
Should return requested item schema(s) (1)
- Request multiple items
`https://localhost:8993/services/csw?version=2.0.2&service=CS …
=> [2.19.x] DDF-6209 CSW DescribeRecord does not show all the schemas that getCapabilities enumerates

ui/packages/catalog-ui-search/src/main/webapp/react-component/enum/enum.tsx
Fixed #6204 
@bennuttle 
@lavoywj 
@jMoneee 
@frnkshin 
@codice/ui 
@bdeining
@millerw8
See #6204 for steps to reproduce, these should be used to verify
Fixes: #6204 …
=> [2.19.x] DDF-6204: Enum forced re-render is now selective

ui/packages/catalog-ui-search/src/main/webapp/component/query-editor/query-editor.view.js
Resolves #6237 by ensuring `startSearchFromFirstPage` is used.
@leo-sakh 
@frnkshin 
@lavoywj 
@jMoneee 
@bdeining 
@millerw8 
See steps in #6237
Fixes: #6237 …
=> [2.19.x] DDF-6237 Ensure First Page of Results are Displayed

ui/packages/catalog-ui-search/src/main/webapp/component/result-form/result-form.view.js
ddf-ui PRs:
3.4.x codice/ddf-ui#310
Issue 1 - Result form collection creates empty items when it shouldn't for Guest
Issue 2 - Not able to set default a Result form item (already fixed in 2.19.x)
@andrewzimmer 
@hayleynorton
@zta6 
@bdeining
Issue 1:
You should be logged in as Guest (Confirm by checking on upper right corner)
1. Go to Result Forms
2. Click on "New Result Forms" to add new result form
3. Ensure you get two error pop up messages, and ensure no Result From Box are created
Issue 2:
1. Log in as admin (Confirm by checking on upper right corner)
2. Ensure in Search form no default is selected for existing Search forms, or make sure no Search forms are created
3. Go to Result form
4. Click on "New Result Forms" to add …
=> [2.19.x] DDF-UI-309 Result form collection creates empty items

distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/SystemStateManager.java
Port of https://github.com/codice/ddf/pull/6230
@stustison @bakejeyner @blen-desta @garrettfreibott
@codice/test 
CI. No hero is needed.
See https://github.com/codice/ddf/pull/6230.
Fixes: #6229 …
=> DDF-6229 Remove clearCache in itests

platform/security/handler/security-handler-oidc/src/main/java/org/codice/ddf/security/handler/oidc/OidcHandlerConfigurationImpl.java
Port of https://github.com/codice/ddf/pull/6228
@blen-desta @bakejeyner @stustison @garrettfreibott 
CI. No hero is needed.
See https://github.com/codice/ddf/pull/6228
Fixes: #6227 …
=> DDF-6227 Update OidcHandlerConfiguration initialization failure logs from WARN to DEBUG

ui/packages/catalog-ui-search/src/main/webapp/react-component/filter/filter-input/filter-date-inputs/filter-relative-time-input/filter-relative-time-input.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/filter/filter-input/filter-date-inputs/filter-relative-time-input/relativeTimeHelper.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/inputs/relative-time-input/relative-time-input.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/utils/validation/validation.tsx
add validation for relative time input, a value that is too large will break the query
@cassandrabailey293 @hayleynorton @zta6 @abel-connexta 
@bdeining 
- attempt to enter a large value in the relative time search, verify inline error message appears
- attempt search with invalid value, verify search is blocked and a relevant message appears …
=> [2.19.x] DDF-UI-318 add validation for relative time input

ui/packages/catalog-ui-search/src/main/webapp/component/search-form-editor/search-form-editor.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/map.view.js
Removes the result filter geometry from the map when it's not supposed to be there (i.e., in the search form editor). 
@andrewzimmer @abel-connexta @hayleynorton @zta6 
@codice/ui 
1. Go into a workspace and create a result filter
2. Add an anyGeo to the result filter and draw a Polygon on the map
3. Go to search forms and create a new search form
4. verify that the geometry from your result filter isn't showing up on the map
Fixes: https://github.com/codice/ddf-ui/issues/296 …
=> [2.19.x] DDF-UI-296 G-8772 Remove result filter geometry from map

platform/email/platform-email-impl/pom.xml, platform/email/platform-email-impl/src/main/java/org/codice/ddf/platform/email/impl/SmtpClientImpl.java, platform/email/platform-email-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/email/platform-email-impl/src/test/java/org/codice/ddf/platform/email/impl/SmtpClientImplITCaseTest.java
If a SmtpClientImpl config file is provided a bug occurs where the password parameter is sent to the smtp server still encrypted. Note: if no configuration file is provided and the configuration is instead performed through the admin ui - everything works properly. This change decrypts the password parameter in SmtpClientImpl when necessary. 
- create config file: org.codice.ddf.platform.email.impl.SmtpClientImpl.config 
with a smtp server url, port, username, and password 
- cause ddf to send an email. one way to do this is to check "Enable Query Feedback" in Admin UI > Catalog UI > Catalog UI Search; and supply a "Query Feedback Email Destination"
Fixes: #6232 …
=> [2.19.x] DDF-6232 decrypt password parameter in SmtpClientImpl

ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/cesium/map.cesium.js
This PR removes the result filter geo from the map when the user deletes it. The issue before was that for the 3D map case, the map wasn't re-rendering after deletion. So to solve this i'm requesting render after the delete. 
@zta6 @hayleynorton @abel-connexta @andrewzimmer 
@codice/ui 
@bdeining 
1. build and profile/install
2. Go into workspaces and execute a search (it doesn't need to return anything)
3. click on the filter icon in the left pane to add a result filter
4. select anyGeo and draw a polygon on the map
5. save the result filter
6. go back into the result filter and click the red "delete filter" button
7. verify that the polygon is removed from the map
Fixes: #____
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Gu …
=> [2.19.x] G-8807 Remove result filter geometry on delete

catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/transformer/TransformerManager.java, catalog/spatial/csw/spatial-csw-common/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/common/transformer/TransformerManagerTest.java, catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java, catalog/spatial/csw/spatial-csw-endpoint/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpointTest.java, catalog/spatial/csw/spatial-csw-transformer/src/main/resources/OSGI-INF/blueprint/blueprint.xml
ddf PRs:
2.19.x codice/ddf#6210
2.23.x codice/ddf#6211
---------------
CSW DescribeRecord does not show all the schemas that getCapabilities enumerates.
This is due to content being hardcoded and not dynamically retrieved.
@andrewzimmer 
@hayleynorton
@zta6 
@bdeining
- Build and install
- Perform and verify following request(s)
**Request Type - GET:**
- Request All available item(s)
`https://localhost:8993/services/csw?version=2.0.2&service=CSW&request=describeRecord`
Should return all available schema(s) (2)
- Request Single item
`https://localhost:8993/services/csw?version=2.0.2&service=CSW&request=describeRecord&namespace=xmlns(gmd=http://www.isotc211.org/2005/gmd)&typeName=gmd:MD_Metadata`
Should return requested item schema(s) (1)
- Request …
=> DDF-6209 CSW DescribeRecord does not show all the schemas that getCapabilities enumerates

catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/transformer/TransformerManager.java, catalog/spatial/csw/spatial-csw-common/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/common/transformer/TransformerManagerTest.java, catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java, catalog/spatial/csw/spatial-csw-endpoint/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpointTest.java, catalog/spatial/csw/spatial-csw-transformer/src/main/resources/OSGI-INF/blueprint/blueprint.xml
ddf PRs:
2.19.x codice/ddf#6210
master codice/ddf#6212
---------------
CSW DescribeRecord does not show all the schemas that getCapabilities enumerates.
This is due to content being hardcoded and not dynamically retrieved.
@andrewzimmer 
@hayleynorton
@zta6 
@bdeining
- Build and install
- Perform and verify following request(s)
**Request Type - GET:**
- Request All available item(s)
`https://localhost:8993/services/csw?version=2.0.2&service=CSW&request=describeRecord`
Should return all available schema(s) (2)
- Request Single item
`https://localhost:8993/services/csw?version=2.0.2&service=CSW&request=describeRecord&namespace=xmlns(gmd=http://www.isotc211.org/2005/gmd)&typeName=gmd:MD_Metadata`
Should return requested item schema(s) (1)
- Request …
=> [2.23.x] DDF-6209 CSW DescribeRecord does not show all the schemas that getCapabilities enumerates

catalog/transformer/catalog-transformer-csv-queryresponse/src/main/java/ddf/catalog/transformer/csv/CsvMetacardTransformer.java, catalog/transformer/catalog-transformer-csv-queryresponse/src/test/java/ddf/catalog/transformer/csv/CsvMetacardTransformerTest.java
Backend portion of the Forward port of #5931 
_____________________________________________________________________________
This PR fixes the single result export so that only the attributes that exist on that particular record will show up as columns in the .csv 
@codice/ui 
@bdeining 
- build/install
- add some records
- search for records and click the ellipsis menu on the bottom right corner of the result
- select "Export as"
- choose csv and download
- verify that the blank attributes are filtered out
Fixes: https://github.com/codice/ddf-ui/issues/135
- ✏️ …
=> DDF-UI-135 filter blank attributes from CSV export result

catalog/spatial/geocoding/spatial-geocoding-offline-index/pom.xml
Fixes `feature:install offline-gazetteer-index`
@stustison @garrettfreibott @blen-desta @bakejeyner 
1.  Confirm `feature:install offline-gazetteer-index` succeeds.
2. Confirm the offline gazetteer works with the indexed data.
1. Disconnect from the internet to prevent use of online gazetteer.
2. Ingest a record with a location. You can unzip and ingest the record in [test_record.zip](https://github.com/codice/ddf/files/5126910/test_record.zip) using `catalog:ingest -t xml <unzipped file path>`.
3. Confirm that the `location.country-code` attribute was populated in the metacard. You can use `catalog:inspect 0c46d0594efd46f1a3959939f39b8a50` for the attached test record. The `GeoCoder Plugin` needs a gazetteer for this to work, so this indicates that the offline gazetteer is working and …
=> [2.25.x] DDF-6265 Fix feature:install offline-gazetteer-index

distribution/ddf-common/src/main/resources/security/default.policy, platform/branding-registry-impl/pom.xml, platform/branding-registry-impl/src/main/java/org/codice/ddf/branding/impl/BrandingRegistryImpl.java, platform/branding-registry-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/branding-registry-impl/src/test/java/org/codice/ddf/branding/impl/test/BrandingRegistryTest.java
@bakejeyner 
@blen-desta
@emmberk
@stustison
See https://github.com/codice/ddf/issues/6269
#6269
=> [2.25.x] DDF-6269 fixed branding registry by removing SortedServiceList usage and doing direct OSGi calls

catalog/solr/catalog-solr-commands/pom.xml, catalog/ui/search-ui-app/pom.xml, catalog/ui/search-ui/simple/pom.xml, catalog/ui/search-ui/simple/src/main/webapp/WEB-INF/web.xml, dependency-check-maven-config.xml, features/camel/src/main/feature/feature.xml, features/pom.xml, libs/bundles/libs-bundles-opensaml/pom.xml, platform/admin/modules/admin-modules-docs/src/main/java/org/codice/ui/admin/docs/SparkServlet.java, platform/osgi/platform-osgi-configadmin/pom.xml, platform/platform-paxweb-jettyconfig/src/main/resources/jetty.xml, platform/platform-scheduler/pom.xml, platform/platform-scheduler/src/main/java/ddf/platform/scheduler/CommandJobFactory.java, platform/platform-scheduler/src/main/java/ddf/platform/scheduler/ScheduledCommandTask.java, platform/platform-scheduler/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/platform-scheduler/src/test/java/ddf/platform/scheduler/ScheduledCommandTaskTest.java, platform/security/claims/security-claims-attributequerycommon/pom.xml, platform/security/claims/security-claims-ldap/pom.xml, platform/security/encryption/platform-security-encryption-crypter/pom.xml, platform/security/security-token-storage/token-storage-impl/pom.xml, platform/solr/solr-dependencies/pom.xml, platform/solr/solr-query/pom.xml, pom.xml
Addresses OWASP findings by upgrading vulnerable dependencies and cleans up outdated OWASP suppressions.
It also enables the Jetty GzipHandler so all webapps now get gzip compression for free.
@blen-desta @bakejeyner @garrettfreibott @stustison @emmberk 
@codice/security   
Verify:
* The crypter library still works (Tink upgrade): Upload and download a resource
* The platform scheduler still works (Quartz upgrade):
- From the Admin UI, navigate to Platform > Configuration > Platform Command Scheduler
- Set a command, (e.g. "echo hello") and a short interval (e.g. 1 second)
- Check the logs. The command should start running after a minute's delay
* You can load the documentation in the admin UI (Spark upgrade)
* Gzip compression is applied to all webapps. Check the Content-Encoding in the …
=> DDF-6256 Upgrade vulnerable dependencies

catalog/confluence/catalog-confluence-source/src/main/java/org/codice/ddf/confluence/source/ConfluenceSource.java, catalog/core/catalog-core-urlresourcereader/src/main/java/ddf/catalog/resource/impl/URLResourceReader.java, catalog/opensearch/catalog-opensearch-source/src/main/java/org/codice/ddf/opensearch/source/OpenSearchSource.java, catalog/solr/catalog-solr-solrclient/src/main/java/ddf/catalog/source/solr/rest/SolrRest.java, catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/event/SendEvent.java, catalog/spatial/csw/spatial-csw-source-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/AbstractCswSource.java, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsSource.java, catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/source/WfsSource.java, platform/security/certificate/security-crl-generator/src/main/java/org/codice/ddf/security/crl/generator/CrlGenerator.java, platform/security/certificate/security-ocsp-checker/src/main/java/org/codice/ddf/security/ocsp/checker/OcspChecker.java, platform/security/certificate/security-ocsp-checker/src/test/java/org/codice/ddf/security/ocsp/checker/OcspCheckerTest.java, platform/security/rest/security-rest-clientapi/src/main/java/org/codice/ddf/cxf/client/ClientBuilder.java, platform/security/rest/security-rest-cxfwrapper/src/main/java/org/codice/ddf/cxf/client/impl/ClientBuilderImpl.java, platform/security/rest/security-rest-cxfwrapper/src/main/java/org/codice/ddf/cxf/client/impl/ClientFactoryFactoryImpl.java, platform/security/rest/security-rest-cxfwrapper/src/main/java/org/codice/ddf/cxf/client/impl/SecureCxfClientFactoryImpl.java, platform/security/rest/security-rest-cxfwrapper/src/test/java/org/codice/ddf/cxf/SecureCxfClientFactoryTest.java
Fixes the issue of property replacement not working when creating a source
@bakejeyner 
@emmberk
@stustison
- Create a CSW and Open Search source with system properties in the URL
- Make sure these sources are available
- Verify that querying from these sources succeeds
#6262  …
=> [2.25.x] DDF-6262 Fixes the issue of property replacement not working when creating a source

catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/event/OutgoingSubjectRetrievalInterceptor.java
Master port of https://github.com/codice/ddf/pull/6260
@stustison @blen-desta @bakejeyner @garrettfreibott
CI can confirm that this update doesn't cause any regressions.
This fixes downstream itests.
Fixes: #6259 …
=> DDF-6259 Add setAllowGuest in SubjectRetrievalInterceptor

ui/packages/catalog-ui-search/src/main/webapp/component/query-item/query-item.view.js, ui/packages/catalog-ui-search/src/main/webapp/plugins/query-item.view.js
__________________
Adds a plugin for query-item.view for extensibility
@bdeining 
Verify no regression in query items
Fixes: G-8793 …
=> [2.19.x] G-8793 Added query-item.view plugin

catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/operation/impl/QueryImpl.java, catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/operation/impl/QueryResponseImpl.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/federation/impl/SortedFederationStrategy.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/CreateOperations.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/DeleteOperations.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/QueryOperations.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/UpdateOperations.java, catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/federation/impl/SortedFederationStrategyTest.java, catalog/opensearch/catalog-opensearch-source/src/test/groovy/org/codice/ddf/opensearch/source/OpenSearchSourceSpec.groovy
- Added a future monitor to SortedFederationStrategy to watch for
unhandled exceptions while monitoring source responses or offsetting
results to log, close the queue, and add processing details
- Added additional logging in catalog framework to log unhandled
exceptions and query processing details
- Fixed a bug where QueryResponseImpl would set its timeout to 0 from
the QueryImpl default value which for Query means no timeout but in
QueryResponseImpl would disable blocking for all take/poll methods
@derekwilhelm 
@rzwiefel
@stustison
@coyotesqrl
Make a `PostFederatedQueryPlugin` throw a runtime exception and verify the query returns with processing details about the exception.
Fixes: n/a
- [ n/a ] Update / Add …
=> Log unhandled exceptions during federation strategy future execution

distribution/docs/src/main/resources/content/_managing/_configuring/web-context-policy-manager.adoc, distribution/docs/src/main/resources/content/_managing/_securing/disallowing-login-wo-certs.adoc
Updates documentation concerning the web context policy authentication type configuration
@bakejeyner 
@emmberk
@ricklarsen 
@stustison 
CI
Related to: #5996 …
=> [2.25.x] DDF-5996 Updates documentation concerning the web context policy authentication type configuration

libs/test-common/src/main/java/org/codice/ddf/test/common/configurators/KarafOptions.java, libs/test-common/src/main/java/org/codice/ddf/test/common/options/DistributionOptions.java, libs/test-common/src/test/java/ddf/common/test/PaxExamRuleIT.java
Update Maven Central URLs to use HTTPS instead of HTTP in the test-common module.
@codice/test 
@shaundmorris
Build test common with a clean local m2 repository.
Fixes: n/a …
=> Fix test common build with clean local m2 repository

catalog/confluence/catalog-confluence-source/src/main/java/org/codice/ddf/confluence/source/ConfluenceSource.java, catalog/core/catalog-core-urlresourcereader/src/main/java/ddf/catalog/resource/impl/URLResourceReader.java, catalog/opensearch/catalog-opensearch-source/src/main/java/org/codice/ddf/opensearch/source/OpenSearchSource.java, catalog/solr/catalog-solr-solrclient/src/main/java/ddf/catalog/source/solr/rest/SolrRest.java, catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/event/SendEvent.java, catalog/spatial/csw/spatial-csw-source-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/AbstractCswSource.java, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsSource.java, catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/source/WfsSource.java, platform/security/certificate/security-crl-generator/src/main/java/org/codice/ddf/security/crl/generator/CrlGenerator.java, platform/security/certificate/security-ocsp-checker/src/main/java/org/codice/ddf/security/ocsp/checker/OcspChecker.java, platform/security/certificate/security-ocsp-checker/src/test/java/org/codice/ddf/security/ocsp/checker/OcspCheckerTest.java, platform/security/rest/security-rest-clientapi/src/main/java/org/codice/ddf/cxf/client/ClientBuilder.java, platform/security/rest/security-rest-cxfwrapper/src/main/java/org/codice/ddf/cxf/client/impl/ClientBuilderImpl.java, platform/security/rest/security-rest-cxfwrapper/src/main/java/org/codice/ddf/cxf/client/impl/ClientFactoryFactoryImpl.java, platform/security/rest/security-rest-cxfwrapper/src/main/java/org/codice/ddf/cxf/client/impl/SecureCxfClientFactoryImpl.java, platform/security/rest/security-rest-cxfwrapper/src/test/java/org/codice/ddf/cxf/SecureCxfClientFactoryTest.java
Fixes the issue of property replacement not working when creating a source
Forward port of https://github.com/codice/ddf/pull/6263
@bakejeyner 
@emmberk
@stustison
- Create a CSW and Open Search source with system properties in the URL
- Make sure these sources are available
- Verify that querying from these sources succeeds
#6262
=> DDF-6262 Fixes the issue of property replacement not working when creating a source

pom.xml
Uses the latest version of country code
Fixes: #____
=> [2.19.x] G-8407 Update country converter version

catalog/admin/catalog-admin-poller-service/src/main/java/org/codice/ddf/catalog/admin/poller/AdminPollerServiceBean.java, catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/IngestCommand.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/synchronizations/CompletionSynchronization.java, catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/GetRecordsRequest.java, catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java, catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/event/CswSubscriptionConfigFactory.java, catalog/spatial/csw/spatial-csw-source-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/AbstractCswSource.java, catalog/spatial/csw/spatial-csw-source-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/CswAbstractFilterDelegate.java, catalog/spatial/csw/spatial-csw-source-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/CswResponseExceptionMapper.java, catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/CswUnmarshallHelper.java, catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/XStreamAttributeCopier.java, catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/transformer/CswQueryResponseTransformer.java, catalog/spatial/kml/spatial-kml-util/src/main/java/org/codice/ddf/spatial/kml/converter/KmlToMetacard.java, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-converter/src/main/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/converter/impl/GenericFeatureConverterWfs11.java, catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-converter/src/main/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/converter/impl/GenericFeatureConverterWfs20.java, catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/source/WfsResponseExceptionMapper.java, catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/source/reader/FeatureCollectionMessageBodyReaderWfs20.java, catalog/spatial/wfs/spatial-wfs-converter/src/main/java/org/codice/ddf/spatial/ogc/wfs/catalog/converter/impl/GenericFeatureConverter.java, platform/admin/core/admin-core-impl/src/main/java/org/codice/ddf/admin/core/impl/AdminConsoleService.java, platform/osgi/platform-osgi-configadmin/src/main/java/org/codice/felix/cm/file/ConfigurationContextImpl.java, platform/security/certificate/security-crl-generator/src/main/java/org/codice/ddf/security/crl/generator/CrlGenerator.java, platform/security/filter/security-filter-authorization/src/main/java/org/codice/ddf/security/filter/authorization/AuthorizationFilter.java, platform/security/filter/security-filter-csrf/src/main/java/org/codice/ddf/security/filter/csrf/CsrfFilter.java, platform/security/handler/security-handler-basic/src/main/java/org/codice/ddf/security/handler/basic/BasicAuthenticationHandler.java, platform/security/handler/security-handler-saml/src/main/java/org/codice/ddf/security/idp/client/IdpHandler.java
Addresses 31 "Not enough arguments" SonarQube findings
@stustison 
@blen-desta 
@bakejeyner 
CI
https://github.com/codice/ddf/issues/6284 …
=> [2.25.x] DDF-6284 Address "Not enough arguments" SonarQube findings

catalog/admin/catalog-admin-poller-service/src/main/java/org/codice/ddf/catalog/admin/poller/AdminPollerServiceBean.java, catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/IngestCommand.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/synchronizations/CompletionSynchronization.java, catalog/core/catalog-core-standardframework/src/main/java/org/codice/ddf/catalog/sourcepoller/SourcePollerRunner.java, catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/GetRecordsRequest.java, catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java, catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/event/CswSubscriptionConfigFactory.java, catalog/spatial/csw/spatial-csw-source-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/AbstractCswSource.java, catalog/spatial/csw/spatial-csw-source-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/CswAbstractFilterDelegate.java, catalog/spatial/csw/spatial-csw-source-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/CswResponseExceptionMapper.java, catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/CswUnmarshallHelper.java, catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/XStreamAttributeCopier.java, catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/transformer/CswQueryResponseTransformer.java, catalog/spatial/kml/spatial-kml-util/src/main/java/org/codice/ddf/spatial/kml/converter/KmlToMetacard.java, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-converter/src/main/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/converter/impl/GenericFeatureConverterWfs11.java, catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-converter/src/main/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/converter/impl/GenericFeatureConverterWfs20.java, catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/source/WfsResponseExceptionMapper.java, catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/source/reader/FeatureCollectionMessageBodyReaderWfs20.java, catalog/spatial/wfs/spatial-wfs-converter/src/main/java/org/codice/ddf/spatial/ogc/wfs/catalog/converter/impl/GenericFeatureConverter.java, distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/ServiceManagerImpl.java, platform/admin/core/admin-core-impl/src/main/java/org/codice/ddf/admin/core/impl/AdminConsoleService.java, platform/osgi/platform-osgi-configadmin/src/main/java/org/codice/felix/cm/file/ConfigurationContextImpl.java, platform/security/certificate/security-crl-generator/src/main/java/org/codice/ddf/security/crl/generator/CrlGenerator.java, platform/security/filter/security-filter-authorization/src/main/java/org/codice/ddf/security/filter/authorization/AuthorizationFilter.java, platform/security/filter/security-filter-csrf/src/main/java/org/codice/ddf/security/filter/csrf/CsrfFilter.java, platform/security/handler/security-handler-basic/src/main/java/org/codice/ddf/security/handler/basic/BasicAuthenticationHandler.java, platform/security/handler/security-handler-saml/src/main/java/org/codice/ddf/security/idp/client/IdpHandler.java
Port of https://github.com/codice/ddf/pull/6285 plus 2 more small fixes (see latest commit)
@stustison 
@blen-desta 
@bakejeyner 
CI
Fixes: #6284 …
=> DDF-6284 Address "Not enough arguments" SonarQube findings

catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-common/src/main/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/common/Wfs20Constants.java, catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/source/WfsFilterDelegate.java, catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/source/WfsFilterDelegateTest.java, libs/klv/src/main/java/org/codice/ddf/libs/klv/data/Klv.java, libs/klv/src/test/java/org/codice/ddf/libs/klv/KlvContextTest.java, libs/klv/src/test/java/org/codice/ddf/libs/klv/KlvDecoderTest.java, libs/klv/src/test/java/org/codice/ddf/libs/klv/KlvEncodingDetectedStringTest.java
Addresses 63 critical SonarQube code smells: https://sonarcloud.io/project/issues?id=ddf&resolved=false&rules=java%3AS115
@blen-desta 
@stustison 
@bakejeyner 
CI
#6302 …
=> DDF-6302 Address "Constant names should comply with a naming convention" SonarQube code smells

catalog/solr/catalog-solr-commands/src/main/java/org/codice/ddf/commands/solr/SolrCommands.java
@stustison 
@blen-desta 
@bakejeyner 
CI
Fixes: #6295 …
=> DDF-6295 Address "Child class fields should not shadow parent class fields" SonarQube code smell

platform/security/filter/security-filter-web-sso/src/main/java/org/codice/ddf/security/filter/websso/WebSSOFilter.java
Lowers logging.  Too much spam
@stustison
Fixes: #____
=> [2.23.x] Lowered wordy logging to prevent log spam

platform/security/filter/security-filter-web-sso/src/main/java/org/codice/ddf/security/filter/websso/WebSSOFilter.java
Lowers logging.  Too much spam
@stustison
Fixes: #____
=> Lowered wordy logging to prevent log spam

catalog/solr/catalog-solr-commands/src/main/java/org/codice/ddf/commands/solr/SolrCommands.java
@stustison 
@blen-desta 
@bakejeyner 
CI
#6295 …
=> [2.25.x] DDF-6295 Address "Child class fields should not shadow parent class fields" SonarQube code smell

platform/security/servlet/security-servlet-logout/pom.xml, platform/security/servlet/security-servlet-logout/src/main/java/org/codice/ddf/security/servlet/logout/LocalLogoutServlet.java, platform/security/servlet/security-servlet-logout/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/security/servlet/security-servlet-logout/src/test/java/org/codice/ddf/security/servlet/logout/LogoutServletTest.java, platform/security/servlet/security-servlet-whoami/pom.xml, platform/security/servlet/security-servlet-whoami/src/main/java/org/codice/ddf/security/servlet/whoami/WhoAmIServlet.java, platform/security/servlet/security-servlet-whoami/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/security/servlet/security-servlet-whoami/src/test/groovy/org/codice/ddf/security/servlet/whoami/WhoAmIServletSpec.groovy
@stustison 
@blen-desta 
@SmithJosh 
@bakejeyner 
- Confirm /logout and /logout/local endpoints still work
- Confirm /whoami endpoint still works
#6316 …
=> [2.25.x] DDF-6316 Address "Servlets should not have mutable instance fields" SonarQube bugs

platform/security/servlet/security-servlet-logout/pom.xml, platform/security/servlet/security-servlet-logout/src/main/java/org/codice/ddf/security/servlet/logout/LocalLogoutServlet.java, platform/security/servlet/security-servlet-logout/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/security/servlet/security-servlet-logout/src/test/java/org/codice/ddf/security/servlet/logout/LogoutServletTest.java, platform/security/servlet/security-servlet-whoami/pom.xml, platform/security/servlet/security-servlet-whoami/src/main/java/org/codice/ddf/security/servlet/whoami/WhoAmIServlet.java, platform/security/servlet/security-servlet-whoami/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/security/servlet/security-servlet-whoami/src/test/groovy/org/codice/ddf/security/servlet/whoami/WhoAmIServletSpec.groovy
Clean port of https://github.com/codice/ddf/pull/6317
@stustison 
@blen-desta 
@SmithJosh 
@bakejeyner 
- Confirm /logout and /logout/local endpoints still work
- Confirm /whoami endpoint still works
Fixes: #6316 …
=> DDF-6316 Address "Servlets should not have mutable instance fields" SonarQube bugs

distribution/ddf-common/src/main/resources/bin/setenv-windows-wrapper.conf, distribution/docs/src/main/resources/content/_managing/_running/ddf-service.adoc
Allows for sshing into the service and updates documentation with warnings when installing.
@blen-desta 
@emmberk 
@SmithJosh 
@stustison 
Follow the documentation on starting DDF as a windows service (make sure to adhere to the warnings). Should run like a normal DDF instance, including the ability to ssh into the karaf console.
Fixes: #6305 …
=> [2.25.x] DDF-6305 Fix running DDF as a windows service

distribution/ddf-common/src/main/resources/bin/setenv-windows-wrapper.conf, distribution/docs/src/main/resources/content/_managing/_running/ddf-service.adoc
Allows for sshing into the service and updates documentation with warnings when installing.
@blen-desta 
@emmberk 
@SmithJosh 
@stustison 
Follow the documentation on starting DDF as a windows service (make sure to adhere to the warnings). Should run like a normal DDF instance, including the ability to ssh into the karaf console.
Fixes: #6305 …
=> DDF-6305 Fix running DDF as a windows service

libs/common-system/src/main/java/org/codice/ddf/configuration/PropertyResolver.java, libs/common-system/src/test/java/org/codice/ddf/configuration/PropertyResolverTest.java, libs/common-system/src/test/resources/properties.txt, platform/security/claims/security-claims-attributequery/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/security/claims/security-claims-attributequerycommon/pom.xml, platform/security/claims/security-claims-attributequerycommon/src/main/java/org/codice/ddf/security/claims/attributequery/common/AttributeQueryClaimsHandler.java, platform/security/claims/security-claims-attributequerycommon/src/test/java/org/codice/ddf/security/claims/attributequery/common/AttributeQueryClaimsHandlerTest.java, platform/security/core/security-core-impl/pom.xml, platform/security/core/security-core-services/pom.xml
Remove usage of PropertiesWrapper from AttributeQueryClaimsHandler
Add file reading logic to PropertyResolver
Lower unit test log levels on some security bundles
@blen-desta 
@emmberk 
@SmithJosh 
@stustison  
Full build passes.
Fixes: #6218  …
=> DDF-6218 Remove usage of PropertiesWrapper from AttributeQueryClaimsHandler

catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-common/src/main/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/common/Wfs20Constants.java, catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/source/WfsFilterDelegate.java, catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/source/WfsFilterDelegateTest.java, libs/klv/src/main/java/org/codice/ddf/libs/klv/data/Klv.java, libs/klv/src/test/java/org/codice/ddf/libs/klv/KlvContextTest.java, libs/klv/src/test/java/org/codice/ddf/libs/klv/KlvDecoderTest.java, libs/klv/src/test/java/org/codice/ddf/libs/klv/KlvEncodingDetectedStringTest.java
Port of https://github.com/codice/ddf/pull/6303
@blen-desta 
@stustison 
@bakejeyner 
CI
Fixes: #6302 …
=> [2.25.x] DDF-6302 Address "Constant names should comply with a naming convention" SonarQube code smells

platform/security/handler/security-handler-saml/pom.xml, platform/security/handler/security-handler-saml/src/main/java/org/codice/ddf/security/idp/client/LogoutRequestService.java, platform/security/handler/security-handler-saml/src/test/java/org/codice/ddf/security/idp/client/LogoutRequestServiceTest.java
Addresses SonarQube findings in `LogoutRequestService`. See #6313.
@blen-desta @garrettfreibott @bakejeyner @stustison @SmithJosh 
CI
#6313 …
=> [2.25.x] DDF-6313 Address SonarQube findings in LogoutRequestService

platform/security/handler/security-handler-oidc/src/main/java/org/codice/ddf/security/handler/oidc/OidcLogoutActionProvider.java, platform/security/handler/security-handler-oidc/src/test/java/org/codice/ddf/security/handler/oidc/OidcLogoutActionProviderTest.java
Fixes the OIDC logout action provider so it process the prevurl query parameter in the Referer header correctly.
@blen-desta @bakejeyner @emmberk @garrettfreibott @stustison 
Tagging @jlcsmith for visibility
The easy way:
1. Install DDF and configure OIDC authentication (https://octoconsulting.atlassian.net/wiki/spaces/DDF/pages/702939155/Connect+Keycloak+to+DDF+using+OIDC may help)
2. Sign in to an OIDC-protected web context
3. Browse to `https://localhost:8993/logout?service=https%3A%2F%2Flocalhost%3A8993%2Fsearch%2Fsimple`
4. Click the "sign in again" link on the logout landing page. Verify you can sign back in as you would expect (no 404 response)
The hard way:
1. Install DDF, and install [Intrigue](https://github.com/codice/ddf-ui/) on top of it.
2. Configure OIDC …
=> DDF-6308 Fix handling of encoded urls in OIDC logout action provider

distribution/ddf-common/src/main/resources/security/default.policy, platform/branding-registry-impl/pom.xml, platform/branding-registry-impl/src/main/java/org/codice/ddf/branding/impl/BrandingRegistryImpl.java, platform/branding-registry-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/branding-registry-impl/src/test/java/org/codice/ddf/branding/impl/test/BrandingRegistryTest.java
@bakejeyner @SmithJosh 
@blen-desta
@emmberk
@stustison
Fixes: #6269 
=> DDF-6269 fixed branding registry by removing SortedServiceList usage and doing direct OSGi calls

platform/security/handler/security-handler-saml/pom.xml, platform/security/handler/security-handler-saml/src/main/java/org/codice/ddf/security/idp/client/LogoutRequestService.java, platform/security/handler/security-handler-saml/src/test/java/org/codice/ddf/security/idp/client/LogoutRequestServiceTest.java
Clean port of https://github.com/codice/ddf/pull/6314
https://sonarcloud.io/project/issues?fileUuids=AW7-TRp-3eRe9HKsTMzE&id=ddf&resolved=false
@blen-desta @garrettfreibott @bakejeyner @stustison @SmithJosh
CI
Fixes: #6313 …
=> DDF-6313 Address SonarQube findings in LogoutRequestService

catalog/solr/catalog-solr-cache/src/main/java/org/codice/ddf/catalog/solr/cache/impl/SolrCache.java, catalog/solr/catalog-solr-cache/src/main/resources/OSGI-INF/metatype/SolrCache.xml, catalog/solr/catalog-solr-core/src/main/java/ddf/catalog/source/solr/ConfigurationStore.java, catalog/solr/catalog-solr-core/src/main/java/ddf/catalog/source/solr/DynamicSchemaResolver.java, catalog/solr/catalog-solr-core/src/main/java/ddf/catalog/source/solr/RemoteSolrCatalogProvider.java, catalog/solr/catalog-solr-core/src/main/java/ddf/catalog/source/solr/SolrMetacardClientImpl.java, catalog/solr/catalog-solr-core/src/test/java/ddf/catalog/source/solr/DynamicSchemaResolverTest.java, catalog/solr/catalog-solr-core/src/test/java/ddf/catalog/source/solr/provider/SolrProviderQuery.java, catalog/solr/catalog-solr-provider/src/main/resources/OSGI-INF/metatype/metatype.xml, distribution/ddf-common/src/main/resources-filtered/etc/custom.system.properties, distribution/test/itests/test-itests-common/src/main/resources/TestSpatial/csw/request/query/CswCompoundNot.xml, distribution/test/itests/test-itests-common/src/main/resources/TestSpatial/csw/request/query/CswEqualToTextQuery.xml
Reduces AnyText query parameters from 3200 characters down to 200 characters.  Now by default, only the metadata, title, description fields will be queried for AnyText queries.  This can be configured with the `solr.query.anytext.fields` system property to add more fields based on user needs.
- Removes the dynamic generation of AnyText fields. This creates poor
query performance when expanding to hundreds of fields.
- Removes filtered attribute feature that generated large field lists
but failed to significantly reduce query time for majority of queries.
- Removes spellcheck parameter if spell check is not enabled for the query.
- Removes score from field list if not sorting by relevance.
@codice/solr 
Ingest data and perform AnyText queries for tokens in the metadata, title, description …
=> Reduce average query size sent to Solr

ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/openlayers/openlayers.less
Fixes #6332 
@bennuttle 
@frnkshin 
@lavoywj 
@jMoneee 
@codice/ui 
@bdeining
@millerw8
Please see #6332 
Fixes: #6332 
Broken:
Unbroken:
=> [2.19.x] DDF-6332: Added CSS to fix 2D zoom overlay bleed

ui/packages/catalog-ui-search/src/main/webapp/component/notification-group/notification-group.view.js
Sorts alerts so the most recent alert is at the top of the alerts pane.
@codice/ui 
Fixes: #____
=> [2.19.x] G-9102 Sort alerts by most recent

catalog/pom.xml, distribution/ddf-common/src/main/resources/security/default.policy, libs/test-common/src/main/java/org/codice/ddf/test/common/options/PortOptions.java, libs/test-common/src/main/java/org/codice/ddf/test/common/options/SystemProperties.java, pom.xml
I noticed that there was some leftover ftp code even though the FTP endpoint was removed in #5854.
@shaundmorris @blen-desta @SmithJosh @bakejeyner @stustison 
@codice/io 
@codice/test 
CI
Related to #5854 …
=> Remove some unnecessary code that was missed when the FTP endpoint was removed

platform/email/platform-email-impl/pom.xml, platform/email/platform-email-impl/src/main/java/org/codice/ddf/platform/email/impl/SmtpClientImpl.java, platform/email/platform-email-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/email/platform-email-impl/src/test/java/org/codice/ddf/platform/email/impl/SmtpClientImplITCaseTest.java
forwardport: decrypt password parameter in SmtpClientImpl
https://github.com/codice/ddf/pull/6231
@AzGoalie
@bdeining
@bdthomson
Fixes: #____
=> DDF-6232 forwardport: decrypt password parameter in SmtpClientImpl

catalog/core/catalog-core-camelcomponent/pom.xml, catalog/core/catalog-core-camelcomponent/src/main/java/ddf/camel/component/catalog/CatalogComponent.java, catalog/core/catalog-core-camelcomponent/src/main/java/ddf/camel/component/catalog/CatalogEndpoint.java, catalog/core/catalog-core-camelcomponent/src/main/java/ddf/camel/component/catalog/framework/FrameworkProducer.java, catalog/core/catalog-core-camelcomponent/src/main/java/ddf/camel/component/catalog/framework/IngestTimeoutException.java, catalog/core/catalog-core-camelcomponent/src/main/java/ddf/camel/component/catalog/transformer/TransformerProducer.java, catalog/core/catalog-core-camelcomponent/src/main/java/ddf/camel/component/catalog/transformer/TransformerTimeoutException.java, catalog/core/catalog-core-camelcomponent/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/core/catalog-core-camelcomponent/src/test/java/ddf/camel/component/catalog/framework/FrameworkProducerTest.java, catalog/core/catalog-core-camelcomponent/src/test/java/ddf/camel/component/catalog/inputtransformer/InputTransformerProducerTest.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/AsyncFileAlterationObserver.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/ContentDirectoryMonitor.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/DurableFileAlterationListener.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/DurableFileSystemFileConsumer.java, catalog/core/catalog-core-directorymonitor/src/test/java/org/codice/ddf/catalog/content/monitor/AsyncFileAlterationObserverTest.java, catalog/core/catalog-core-directorymonitor/src/test/java/org/codice/ddf/catalog/content/monitor/ContentDirectoryMonitorIT.java, catalog/core/catalog-core-directorymonitor/src/test/java/org/codice/ddf/catalog/content/monitor/ContentDirectoryMonitorTest.java
Adds timeout capablity to the custom camel components FrameworkProducer and TransformerProducer.
Utilizes the timeout ability in CDM
@aaronilovici 
Fixes: #____ …
=> CDM timeout update

catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/DynamicSchemaResolver.java, catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/SolrMetacardClientImpl.java, catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/DynamicSchemaResolverTest.java, catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/SolrProviderTest.java, catalog/core/catalog-core-solr/src/test/java/ddf/catalog/source/solr/provider/SolrProviderQuery.java, distribution/ddf-common/src/main/resources-filtered/etc/custom.system.properties, distribution/test/itests/test-itests-common/src/main/resources/TestSpatial/csw/request/query/CswCompoundNot.xml, distribution/test/itests/test-itests-common/src/main/resources/TestSpatial/csw/request/query/CswEqualToTextQuery.xml
Backport of #6331 except excluded fields is disabled by default instead of removed.
@lamhuy 
@millerw8 
@bdeining 
Fixes: #____
=> [2.19.x] Reduce average query size sent to Solr

pom.xml
Upgrade to ddf-parent 1.0.11 dependency-check 6.0.2
@TonyMorrison 
@SmithJosh 
@TonyMorrison 
@LinkMJB 
@bakejeyner 
@codice/build 
Passing dependency-check build. This was successful on my laptop …
=> Upgrade to ddf-parent 1.0.11, dependency-check 6.0.2

catalog/solr/catalog-solr-offline-gazetteer/pom.xml, catalog/solr/catalog-solr-offline-gazetteer/src/main/java/ddf/catalog/solr/offlinegazetteer/AbstractSolrClientCommand.java, catalog/solr/catalog-solr-offline-gazetteer/src/main/java/ddf/catalog/solr/offlinegazetteer/BuildGazetteerSuggesterIndexCommand.java, catalog/solr/catalog-solr-offline-gazetteer/src/main/java/ddf/catalog/solr/offlinegazetteer/RemoveAllOfflineSolrGazetteerCommand.java, catalog/solr/catalog-solr-offline-gazetteer/src/main/java/ddf/catalog/solr/offlinegazetteer/SyncCatalogCommand.java, catalog/solr/catalog-solr-offline-gazetteer/src/test/groovy/ddf/catalog/solr/offlinegazetteer/AbstractSolrClientCommandSpec.groovy, catalog/solr/catalog-solr-offline-gazetteer/src/test/groovy/ddf/catalog/solr/offlinegazetteer/BuildGazetteerSuggesterIndexCommandSpec.groovy, catalog/solr/catalog-solr-offline-gazetteer/src/test/groovy/ddf/catalog/solr/offlinegazetteer/CatalogGazetteerForwardingPluginSpec.groovy, catalog/solr/catalog-solr-offline-gazetteer/src/test/groovy/ddf/catalog/solr/offlinegazetteer/GazetteerQueryOfflineSolrSpec.groovy, catalog/solr/catalog-solr-offline-gazetteer/src/test/groovy/ddf/catalog/solr/offlinegazetteer/RemoveAllOfflineSolrGazetteerCommandSpec.groovy, catalog/solr/catalog-solr-offline-gazetteer/src/test/groovy/ddf/catalog/solr/offlinegazetteer/SyncCatalogCommandSpec.groovy
Addresses SonarQube findings in BuildGazetteerSuggesterIndexCommand
https://sonarcloud.io/project/issues?id=ddf&issues=AXPkHocw60FsyeUshtpL&open=AXPkHocw60FsyeUshtpL
@rzwiefel @blen-desta @garrettfreibott @SmithJosh @bakejeyner @stustison 
Confirm that the `offline-solr-gazetteer` commands still work
- see the `Standalone Solr Offline Gazetteer Feature` section in the docs
- see https://github.com/codice/ddf/pull/6153 …
=> Address some SonarQube findings and missing unit tests in catalog-solr-offline-gazetteer

ui/packages/catalog-ui-search/src/main/webapp/component/visualization/maps/map.view.js
ddf-ui PRs:
3.4.x codice/ddf-ui#400
When try to save or perform a search with anyGeo that has no location selected, an exception occurs.
@andrewzimmer 
@hayleynorton
@zta6 
@bdeining 
- Build/install
1.	Open 'Workspaces' via the main menu ('hamburger') button
2.	Open Existing Workspace or click ‘New Workspace’
3.	Click on 'Search DDF Intrigue' or 'Create a Search'
4.	Click ellipse menu and click on 'Advanced Search'
5.	Select the 'anyGeo' (note - Do not select any locations, should have 'Select Location Option' already selected)
6.	Pull up and clear inspector console log
7.	Click Search
8.	Ensure there is no exception in console log
9.	Click on the "Filter" under result returned
10.	Follow steps 5 to 8 
11.	Open 'Search Forms' …
=> [2.19.x] DDF-UI-399 Exception occur for anyGeo Search with no Location selected

catalog/plugin/catalog-plugin-checksum/src/main/java/org/codice/ddf/catalog/content/plugin/checksum/Checksum.java, catalog/plugin/catalog-plugin-checksum/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/plugin/catalog-plugin-checksum/src/main/resources/OSGI-INF/metatype/metatype.xml, catalog/plugin/catalog-plugin-checksum/src/test/java/org/codice/ddf/catalog/content/plugin/checksum/ChecksumTest.java, distribution/ddf-common/src/main/resources/security/default.policy, libs/checksum/pom.xml, libs/checksum/src/main/java/org/codice/ddf/checksum/impl/Sha256ChecksumProvider.java, libs/checksum/src/test/java/org/codice/ddf/checksum/Sha256ChecksumProviderTest.java
Adds SHA 256 Checksum Provider
@lamhuy 
@Lambeaux 
Build / Install / Ingest / Verify checksum works 
Fixes: #__6156__
=> [2.19.x] DDF-6156 G-8624 SHA 256 Checksum Provider

distribution/docker/pom.xml, distribution/docker/solrcloud/pom.xml
Adds the solrcloud module to it's parent so it's version can be bumped on release like the others
Anyone
@pklinef
@shaundmorris
Fixes: #____
=> Fix solrcloud poms

catalog/core/catalog-core-camelcomponent/pom.xml, catalog/core/catalog-core-camelcomponent/src/main/java/ddf/camel/component/catalog/CatalogEndpoint.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/AsyncFileEntry.java, catalog/core/catalog-core-validator/src/main/java/ddf/catalog/validation/impl/validator/RangeValidator.java, catalog/spatial/wfs/spatial-wfs-common/pom.xml, catalog/spatial/wfs/spatial-wfs-common/src/main/java/org/codice/ddf/spatial/ogc/wfs/catalog/common/FeatureMetacardType.java, libs/gson-support/src/main/java/org/codice/gsonsupport/GsonTypeAdapters.java, platform/admin/core/admin-core-insecuredefaults/src/main/java/org/codice/ddf/admin/insecure/defaults/service/InsecureDefaultsCollector.java, platform/admin/core/admin-core-insecuredefaults/src/main/java/org/codice/ddf/admin/insecure/defaults/service/KeystoreValidator.java, platform/security/handler/security-handler-oidc/pom.xml, platform/security/handler/security-handler-oidc/src/main/java/org/codice/ddf/security/handler/oidc/OidcHandler.java
Addresses some miscellaneous SonarQube findings
@blen-desta @garrettfreibott @bakejeyner @SmithJosh @stustison 
CI
https://sonarcloud.io/project/issues?id=ddf&resolved=false …
=> Address some miscellaneous SonarQube findings

dependency-check-maven-config.xml, distribution/ddf-catalog/pom.xml, distribution/ddf-common/src/main/resources/common-bin.xml, distribution/ddf-common/src/main/resources/security/default.policy, distribution/ddf/pom.xml, distribution/kernel/pom.xml, distribution/kernel/src/main/descriptors/bin.xml, features/apps/src/main/feature/feature.xml, features/camel/src/main/feature/feature.xml, features/kernel/src/main/feature/feature.xml, features/utilities/src/main/feature/feature.xml, platform/security/policy/security-policy-context/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/security/policy/security-policy-context/src/main/resources/OSGI-INF/metatype/metatype.xml, pom.xml
This is a backport of https://github.com/codice/ddf/pull/6370
DDF uses a few third party feature repositories where only a few of the features are needed, and a couple where none of the features are used at all. However, it currently pulls in bundles for all those unused features, bloating the distribution and introducing a bunch of spurious CVEs.
This PR cuts out a bunch of those unused features. Here's the difference in distribution size before and after:
DDF -> 791M to 626M
Kernel -> 120MB to 89MB
Also, adds some false positives to the OWASP suppressions file.
CI
The fabric8 features repo was originally added to provide health and readiness endpoints for DDF: #3155
But later the features were turned off by default. Apparently there were issues with system startup when …
=> [2.26.x] DDF-6342 Remove vulnerable features from distribution

dependency-check-maven-config.xml, distribution/ddf-catalog/pom.xml, distribution/ddf-common/src/main/resources/common-bin.xml, distribution/ddf-common/src/main/resources/security/default.policy, distribution/ddf/pom.xml, distribution/kernel/pom.xml, distribution/kernel/src/main/descriptors/bin.xml, features/apps/src/main/feature/feature.xml, features/camel/src/main/feature/feature.xml, features/kernel/src/main/feature/feature.xml, features/utilities/src/main/feature/feature.xml, platform/security/policy/security-policy-context/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/security/policy/security-policy-context/src/main/resources/OSGI-INF/metatype/metatype.xml, pom.xml
DDF uses a few third party feature repositories where only a few of the features are needed, and a couple where none of the features are used at all. However, it currently pulls in bundles for all those unused features, bloating the distribution and introducing a bunch of spurious CVEs.
This PR cuts out a bunch of those unused features. Here's the difference in distribution size before and after:
DDF -> 791M to 626M 
Kernel -> 120MB to 89MB
Also, adds some false positives to the OWASP suppressions file.
CI
The fabric8 features repo was originally added to provide health and readiness endpoints for DDF: #3155
But later the features were turned off by default. Apparently there were issues with system startup when they were turned on: #3302
Fixes: …
=> DDF-6342 Remove vulnerable dependencies from distribution

catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/metacard/workspace/ListMetacardTypeImpl.java, ui/packages/catalog-ui-search/src/main/webapp/component/list-editor/list-editor.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/result-add/result-add.view.js, ui/packages/catalog-ui-search/src/main/webapp/js/model/List.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/list-create/list-create.js
ddf-ui PRs:
3.4.x codice/ddf-ui#411
Resolved following List issues:
Issue 1 - When create empty list with filter(s) from List view when go to Search view and try to add result to list, get error
Issue 2 - When save workspace after creating a list with filter(s), if open to edit filter(s), filter is reset to default and does not contain changes previously made.
Issue 3 - Not able to create new list (custom) with filter from Search view
Issue 4 - Not able to create new list with template that has geometry filter(s) from Search view
Issue 5 - The Plus icon is too close to word e.g. "+Create New List" and "+Create New List with Result(s)"
@andrewzimmer 
@hayleynorton
@zta6 
@Lambeaux
- build / run / install / upload sample datas
- …
=> [2.19.x] DDF-UI-409 Unable to create new List with filter

catalog/plugin/catalog-plugin-videothumbnail/pom.xml, catalog/plugin/catalog-plugin-videothumbnail/src/main/java/org/codice/ddf/catalog/content/plugin/video/VideoThumbnailPlugin.java, catalog/plugin/catalog-plugin-videothumbnail/src/test/java/org/codice/ddf/catalog/content/plugin/video/VideoThumbnailPluginTest.java
Upgrades the ffmpeg binaries used by the video thumbnail plugin
@shaundmorris 
@jlcsmith 
CI
Fixes: #____
=> [2.26.x] Upgrade to ffmpeg 4.3.1

catalog/plugin/catalog-plugin-videothumbnail/pom.xml, catalog/plugin/catalog-plugin-videothumbnail/src/main/java/org/codice/ddf/catalog/content/plugin/video/VideoThumbnailPlugin.java, catalog/plugin/catalog-plugin-videothumbnail/src/test/java/org/codice/ddf/catalog/content/plugin/video/VideoThumbnailPluginTest.java
Upgrades the ffmpeg binaries used by the video thumbnail plugin
@shaundmorris 
@jlcsmith 
CI
Fixes: #____
=> Upgrade to ffmpeg 4.3.1

ui/packages/catalog-ui-search/src/main/webapp/react-component/location/location.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/utils/validation/validation.tsx
Prevents the user from executing an anyGeo search if location option is not selected. It also adds an inline error for this case. 
@andrewzimmer @hayleynorton @zta6 @abel-connexta 
@codice/ui 
1. build, profile install
2. make an advanced search and select anyGeo. DO NOT select a location option
3. Verify that the inline error pops up
4. Try to search and verify that your search is prevented with a toast message 
5. Go back and select a Location Option
6. Verify that the inline error goes away and you can search
Fixes: #____ …
=> [2.19.x] G-9224 prevent search when location input is not selected

ui/packages/catalog-ui-search/src/main/webapp/component/query-add/query-add.view.js
ddf-ui PRs:
3.4.x codice/ddf-ui#446
Search Forms used in a query does not retain facets attribute, which ends up causing issues upstream.
@andrewzimmer 
@hayleynorton
@zta6 
@Lambeaux 
1. Create a Search Form, modify some of the fields (e.g. 'Sources', 'Sort', etc.)
2. Use created Search form in workspace query
3. Ensure all fields looks correct before and after query is ran.
4. Save workspace and refresh, ensure no regression for Search Form used in Query
5. This also need to be tested upstream, contact me for more information.
Fixes: #____ …
=> [2.19.x] G-9317 Search Forms does not retain selected facets after a query is run

.github/PULL_REQUEST_TEMPLATE
Update PR template to have new committers
@andrewzimmer 
@SmithJosh
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codice/ddf/6417)
=> Adding new committers to PR template

catalog/transformer/catalog-transformer-pptx/pom.xml, catalog/ui/search-ui/simple/pom.xml, dependency-check-maven-config.xml, features/pom.xml, platform/admin/core/admin-core-appservice/pom.xml, platform/admin/core/admin-core-jolokia/pom.xml, platform/error/platform-error-impl/pom.xml, platform/platform-paxweb-jettyconfig/pom.xml, platform/pom.xml, platform/security/filter/security-filter-csrf/pom.xml, platform/security/servlet/security-servlet-web-socket-api/pom.xml, pom.xml
Backport of https://github.com/codice/ddf/pull/6414
Upgrades Jolokia to 1.6.2, Hazelcast to 3.12.10, suppresses a false positive, and switches to jetty-bom to force the jetty version.
Fixes: #____ …
=> [2.26.x] Address OWASP findings

platform/email/platform-email-impl/pom.xml, platform/email/platform-email-impl/src/main/java/org/codice/ddf/platform/email/impl/SmtpClientImpl.java
This is a quick fix for the email client to prevent scenarios where the email session initialization fails due to OSGi classloader weirdness. 
@vinamartin @astagg @jlcsmith
Fixes: #____ …
=> [2.26.x] Fix email client not finding IMAPProvider

catalog/core/catalog-core-definitionparser/src/main/java/ddf/catalog/definition/impl/DefinitionParser.java, catalog/core/catalog-core-definitionparser/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/core/catalog-core-definitionparser/src/test/groovy/ddf/catalog/definition/impl/DefinitionParserSpec.groovy
Adds DDF to register external attribute validators via Definition Parser
@leo-sakh 
@bennuttle 
@lavoywj 
@jMoneee 
@rzwiefel
@jrnorth
1. Create a new AttributeValidator service from a downstream project
2. Update the json file read by DDF. Update an attribute to include a custom validator like below:
```
"anAttribute": [
{
"validator": "custom",
"validators": [
{
"validator": "service_id_for_your_new_validator_service_from_step_1"
}
]
}
]
```
3. Check and see if `DefinitionParser` correctly registers the validator for attribute (An easier way would be to attach a debugger)
This allows downstream projects to define custom validator mapping to the json file, and allows to use downstream-specific validator.
Fixes: #6043  …
=> [2.19.x] DDF-6043 Allow DDF to register external attribute validators

ui/packages/catalog-ui-search/src/main/webapp/component/result-selector/result-selector.view.js
Allow query results to be cleared
@cassandrabailey293 @hayleynorton @zta6 @abel-connexta 
- build / install / verify no regression with query results
Fixes: #____ …
=> [2.19.x] G-9207 allow query results to be cleared

ui/packages/catalog-ui-search/src/main/webapp/react-component/location/point-radius.js
ddf-ui PRs:
3.4.x codice/ddf-ui#447
The user cannot manually enter numbers into the buffer field for MGRS Point Radius. User also cannot edit numbers that have been input into the MGRS Point Radius buffer that have been entered by drawing the geometry on the map.
@andrewzimmer 
@hayleynorton
@zta6 
@Lambeaux 
Method 1
1. From any of these geometry field types (anyGeo, location, center), select Point Radius.
2. Select the MGRS coordinate format
3. Place cursor in Radius value box and enter a number from buffer radius
4. Ensure no error occurs and able to enter radius number
Method 2
1. From any of these geometry field types (anyGeo, location, center), select Point Radius.
2. Select the MGRS …
=> [2.19.x] G-9380 Unable to Edit a Buffer for MGRS Point Radius Search

ui/packages/catalog-ui-search/src/main/webapp/component/query-editor/query-editor.view.js, ui/packages/catalog-ui-search/src/main/webapp/component/query-title/query-title.view.js, ui/packages/catalog-ui-search/src/main/webapp/js/model/Query.js
Adds a method to sanitize CQL queries for use in downstream projects as well as ported changes from https://github.com/codice/ddf/pull/6433 which solves a related issue.
@leo-sakh
@jMoneee
@frnkshin
build / run, verify no regression when building searches without titles and default titles are getting set /saved correctly, verify when editing a query by removing it's title that saving / running the query produces the correct default title.
Fixes: #____ …
=> [2.19.x] G-9453 Added CQL Sanitizing method for Search Save and Query Titles

ui/packages/catalog-ui-search/src/main/webapp/component/query-add/query-add.view.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/workspace-item/container.tsx
Adds functionality that triggers the reset of the search creation panel when a workspace is selected from the workspace menu.
@leo-sakh
@frnkshin
@lavoywj
@codice/ui 
@millerw8
@leo-sakh
1. Build and set up DDF
2. Create some additional workspaces
3. Open one of the workspaces and create a search with any anyGeo field and draw a polygon (or anything else)
4. Do not start the search, click off the search and then open another workspace
5. Verify that the polygon drawn on the other workspace does not appear
Fixes: #6204 …
=> [2.19.x] DDF-6204 Reset Search window on Workspace change

ui/packages/catalog-ui-search/src/main/webapp/extension-points/extension-points.tsx, ui/packages/catalog-ui-search/src/main/webapp/extension-points/sharing-aliases/index.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/sharing/presentation.tsx
Allows aliases for sharing groups
@abel-connexta @cassandrabailey293 @hayleynorton @zta6 
- build /install / run
- verify no regression with sharing modal
Fixes: #____ …
=> [2.19.x] G-9513 allow aliases for sharing groups

distribution/pom.xml
Disables docker modules on 2.19.x 
@codice/build 
@andrewzimmer
@TonyMorrison
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codice/ddf/6451)
=> disabling docker modules due to known issue

distribution/solr-distro/pom.xml, platform/solr/solr-schema/src/main/resources/solr/conf/solrconfig.xml, pom.xml
Upgrades Solr to 8.7.0. Resolves CVE-2020-13957.
https://lucene.apache.org/solr/8_7_0/changes/Changes.html
https://lucene.apache.org/solr/security.html#cve-2020-13957-the-checks-added-to-unauthenticated-configset-uploads-in-apache-solr-can-be-circumvented
https://lucene.apache.org/solr/guide/8_7/solr-upgrade-notes.html#solr-8-7
@derekwilhelm 
@codice/solr 
@jlcsmith 
@rzwiefel
@ryeats
Start SolrCloud docker compose. Verify version.  Index data and verify can search.
Fixes: n/a …
=> Upgrade to Solr 8.7.0

distribution/ddf/pom.xml
https://github.com/codice/ddf/pull/6371 was supposed to remove only unused features from DDF, but it also removed a few that were used, causing installation to fail with a clean m2. This PR adds the missing features
@codice/build 
Build and run these changes. Verify the standard profile can be installed with a clean .m2 repo. 
Fixes: #____ …
=> [2.26.x] Add missing features to the distribution

catalog/core/catalog-core-commands/pom.xml, catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/RangeCommand.java, catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/SubjectCommands.java, catalog/core/catalog-core-commands/src/test/java/org/codice/ddf/commands/catalog/SubjectCommandsTest.java
Clean master port of https://github.com/codice/ddf/pull/6461
The Smiths
No hero is needed. Nothing has changed in these files between 2.26.x and master.
=> Fix printErrorMessage when executeWithSubject fails in SubjectCommands

ui/packages/catalog-ui-search/src/main/webapp/component/query-title/query-title.view.js
Fixes some logic introduced in #6445 that causes issues when saving query titles, particularly when using search forms, and caused iTest failure in a downstream project.
@leo-sakh 
@frnkshin 
@jMoneee 
Fixes: #____ …
=> [2.19.x] G-9453 Fix query title updating

distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestSecurity.java
Fixes a race condition in TestSecurity#testBasicFederatedAuth where a CSW source under test wasn't being created in time.
@codice/test 
CI
Fixes: #____ …
=> [2.26.x] Fix TestSecurity#testBasicFederatedAuth

catalog/core/catalog-core-definitionparser/src/main/java/ddf/catalog/definition/impl/DefinitionParser.java, catalog/core/catalog-core-definitionparser/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/core/catalog-core-definitionparser/src/test/groovy/ddf/catalog/definition/impl/DefinitionParserSpec.groovy
Reverts changes made in [DDF-6043](https://github.com/codice/ddf/issues/6043) and [PR-6399](https://github.com/codice/ddf/pull/6399)
@leo-sakh 
@lavoywj 
@jMoneee
@rzwiefel
@jrnorth
Fixes: #6469  …
=> [2.19.x] DDF-6469 Revert changes made in DDF-6043/PR-6399

platform/email/platform-email-impl/pom.xml, platform/email/platform-email-impl/src/main/java/org/codice/ddf/platform/email/impl/SmtpClientImpl.java, platform/email/platform-email-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/email/platform-email-impl/src/test/java/org/codice/ddf/platform/email/impl/SmtpClientImplITCaseTest.java
Ports decrypt password for emails to 2.26.x
@jlcsmith @SmithJosh @emmberk @a-asaad
=> [2.26.x] DDF-6232 decrypt password parameter in SmtpClientImpl 

catalog/core/catalog-core-commons/src/main/java/ddf/catalog/filter/delegate/TagsFilterDelegate.java, catalog/core/catalog-core-impl/filter-proxy/src/test/java/ddf/catalog/filter/delegate/TagsFilterDelegateTest.java
Duplicate of https://github.com/codice/ddf/pull/6435 but rebased
=> [2.26.x] Match on any OR for TagsFilterDelegate

ui/packages/catalog-ui-search/src/main/webapp/js/CQLUtils.js
fixes bug search form editor fails to save form with a 0 buffer for linestring or polygon
@abel-connexta @zta6 @hayleynorton 
- Go to search form editor and verify search forms can be saved with linestrings/polygons geos with a 0 buffer
- attempt other buffer values such as a blank value and verify the form saves
Fixes: #____ …
=> [2.19.x] G-9209 fix Search form editor fails to save form with linestring geo

distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestSecurity.java
Forward port of https://github.com/codice/ddf/pull/6475. That fixed the TestSecurity#testBasicFederatedAuth itest on the 2.26.x branch; it's been passing consistently since that was merged.
@shaundmorris 
@codice/test
@codice/continuous-integration
CI
The previous attempt to fix this did not work https://github.com/codice/ddf/pull/6404
Fixes: #____ …
=> Fix TestSecurity#testBasicFederatedAuth

dependency-check-maven-config.xml
Suppresses false positives reported by the dependency-check plugin
CI
Fixes: #____
=> Suppress false positives reported by dependency-check plugin

catalog/transformer/catalog-transformer-pptx/pom.xml, catalog/ui/search-ui/simple/pom.xml, dependency-check-maven-config.xml, features/pom.xml, platform/admin/core/admin-core-appservice/pom.xml, platform/admin/core/admin-core-jolokia/pom.xml, platform/error/platform-error-impl/pom.xml, platform/platform-paxweb-jettyconfig/pom.xml, platform/pom.xml, platform/security/filter/security-filter-csrf/pom.xml, platform/security/servlet/security-servlet-web-socket-api/pom.xml, pom.xml
Upgrades Jolokia to 1.6.2, Hazelcast to 3.12.10, suppresses a false positive, and switches to jetty-bom to force the jetty version.
CI
Fixes: #____ …
=> Address OWASP findings

catalog/solr/catalog-solr-commands/pom.xml, catalog/solr/catalog-solr-core/pom.xml, features/solr/src/main/feature/feature.xml, platform/solr/solr-dependencies/pom.xml, pom.xml
Forward port of https://github.com/codice/ddf/pull/6466
N/a. These changes have been tested already on the 2.26.x branch and there is minimal divergence between 2.26.x and master.
Fixes: #____ …
=> Add missing Jetty imports to solr-dependencies

distribution/ddf/pom.xml
#6370 was supposed to remove only unused features from DDF, but it also removed a few that were used, causing installation to fail with a clean m2. This PR adds the missing features
@codice/build
N/a. These changes have been tested already on the 2.26.x branch and there is minimal divergence between 2.26.x and master.
Fixes: #____ …
=> Add missing features to the distribution

platform/email/platform-email-impl/src/main/java/org/codice/ddf/platform/email/impl/SmtpClientImpl.java
Forward port of https://github.com/codice/ddf/pull/6427
N/a. These changes have been tested already on the 2.26.x branch and there is minimal divergence between 2.26.x and master (no divergence at all in the file touched by this PR).
Fixes: #____
- ❗ …
=> Fix email client not finding IMAPProvider

ui/packages/catalog-ui-search/src/main/webapp/dev/component/input-guide/input-guide.view.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/input-wrappers/autocomplete/autocomplete.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/input-wrappers/base/base.tsx, ui/packages/catalog-ui-search/src/main/webapp/react-component/location/keyword.js
backport of https://github.com/codice/ddf-ui/pull/70
Fixes: #____
=> [2.19.x] G-7486 Change gazetteer placeholder text to "Pan to a city, country, or coordinate"

catalog/transformer/catalog-transformer-csv-queryresponse/src/main/java/ddf/catalog/transformer/csv/CsvMetacardTransformer.java, catalog/transformer/catalog-transformer-csv-queryresponse/src/test/java/ddf/catalog/transformer/csv/CsvMetacardTransformerTest.java
Unable to export via Inspector tab, Action subtab for CSV type.
@andrewzimmer 
@hayleynorton
@zta6 
@Lambeaux 
• Execute a search with returned results.
1.   Select 1 Result and go to Inspector tab
2.  Click on Actions subtab and click on export type "CSV"
3.  Ensure able to export and exported file shows all attributes (Note-it shows all metacard labels and some might be empty if not present in exported result)
Fixes: #____ …
=> [2.19.x] CSV unable to export in Inspector Action

ui/packages/catalog-ui-search/src/main/webapp/component/property/property.view.js
ddf-ui PRs:
3.4.x codice/ddf-ui#507
Error on console when user click on reset of export/as format for table export.
@andrewzimmer 
@hayleynorton
@zta6 
@Lambeaux 
1. Go to Table export and click the "Export" button top far right of table tab.
2. Select the 2 different drop downs ("Export" and "as" drop down forms)
3. When select other items beside default ("All Results" and "CSV") should get a reset icon button
4. Open console log, and Click on reset icon
5. Ensure no error is displayed, and item are reset back to default. Ensure no regression to table export.
Fixes: #____ …
=> [2.19.x] G-9771 Table export reset form field causes error

catalog/transformer/catalog-transformer-csv-queryresponse/src/main/java/ddf/catalog/transformer/csv/CsvMetacardTransformer.java, catalog/transformer/catalog-transformer-csv-queryresponse/src/test/java/ddf/catalog/transformer/csv/CsvMetacardTransformerTest.java
ddf PRs:
2.19.x codice/ddf#6503
2.23.x codice/ddf#6510
-------------------
Unable to export via Inspector tab, Action subtab for CSV type.
@andrewzimmer 
@hayleynorton
@zta6 
@Lambeaux 
• Execute a search with returned results.
1.   Select 1 Result and go to Inspector tab
2.  Click on Actions subtab and click on export type "CSV"
3.  Ensure able to export and exported file shows all attributes (Note-it shows all metacard labels and some might be empty if not present in exported result)
Fixes: #____
- ✏️ …
=> CSV unable to export in Inspector Action

catalog/transformer/catalog-transformer-csv-queryresponse/src/main/java/ddf/catalog/transformer/csv/CsvMetacardTransformer.java, catalog/transformer/catalog-transformer-csv-queryresponse/src/test/java/ddf/catalog/transformer/csv/CsvMetacardTransformerTest.java
ddf PRs:
2.19.x codice/ddf#6503
master codice/ddf#6513
-------------------
Unable to export via Inspector tab, Action subtab for CSV type.
@andrewzimmer 
@hayleynorton
@zta6 
@Lambeaux 
• Execute a search with returned results.
1.   Select 1 Result and go to Inspector tab
2.  Click on Actions subtab and click on export type "CSV"
3.  Ensure able to export and exported file shows all attributes (Note-it shows all metacard labels and some might be empty if not present in exported result)
Fixes: #____
- ✏️ …
=> [2.23.x] CSV unable to export in Inspector Action

ui/packages/catalog-ui-search/src/main/webapp/component/search-form-editor/search-form-editor.view.js
fixes an issue introduced by https://github.com/codice/ddf/pull/6483 , where if the coordinates are empty/undefined, the `zoomToExtent` fails (visible in the dev console) and breaks tests. 
@codice/ui 
1. create a search form without a geometry and another attribute
2. save and exit the editor
3. select the newly created search form
4. verify that you do not see this error in the dev console:
Fixes: #____
- ❓ …
=> [2.19.x] G-9786 do not pan to empty/undefined coordinates

catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/DurableFileEndpoint.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/DurableWebDavFileConsumer.java, catalog/core/catalog-core-impl/pubsub/src/main/java/ddf/catalog/pubsub/criteria/contextual/ContextualEvaluationCriteriaImpl.java, catalog/core/catalog-core-impl/pubsub/src/main/java/ddf/catalog/pubsub/criteria/contextual/ContextualEvaluator.java, catalog/transformer/catalog-transformer-zip/src/main/java/org/codice/ddf/catalog/transformer/zip/ZipDecompression.java, libs/common-system/src/main/java/org/codice/ddf/configuration/PropertyResolver.java, libs/httpproxy/proxy-camel-route/src/main/java/org/codice/proxy/http/HttpProxyServiceImpl.java, platform/metrics/metrics-system-reporter/src/main/java/org/codice/ddf/metrics/SystemMetricsReporter.java, platform/security/certificate/security-crl-generator/src/main/java/org/codice/ddf/security/crl/generator/CrlGenerator.java
Fixes issues identified by SonarCloud here https://sonarcloud.io/project/issues?id=ddf&open=AXW1U0BdtOJ4nXCiOnvL&resolved=false&severities=BLOCKER&types=BUG
@lavoywj 
@frnkshin 
@hayleynorton 
@shaundmorris 
Full build should be suffiecient
Fixes: #____ …
=> SonarCloud Code Cleanup

catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/IngestCommand.java, catalog/solr/catalog-solr-core/src/main/java/ddf/catalog/source/solr/SolrMetacardClientImpl.java, libs/gson-support/src/main/java/org/codice/gsonsupport/GsonTypes.java, platform/admin/core/admin-core-impl/src/main/java/org/codice/ddf/admin/core/impl/module/Decorator.java
Fixes issues identified by SonarCloud here 
https://sonarcloud.io/project/issues?id=ddf&resolved=false&severities=MAJOR&types=BUG
and here https://sonarcloud.io/project/issues?id=ddf&resolved=false&severities=MINOR&types=BUG
Also fixed some other SonarCloud small findings in the classes changed.
@kentmorrissey
@lavoywj
@frnkshin
@hayleynorton
@jMoneee
@shaundmorris
@zta6 
Full build should be sufficient
Fixes: #____
- …
=> SonarCloud Code Cleanup Major Bugs findings 3

Jenkinsfile
Remove the iTests stage from the DDF build. The iTests will be moved to a new repo and also a new build
@shaundmorris 
@pklinef 
@codice/build 
@pklinef
@shaundmorris
Fixes: #____ …
=> BR-163 Remove Itests from DDF builds

catalog/transformer/catalog-transformer-metadata/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/transformer/catalog-transformer-overlay/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/transformer/catalog-transformer-thumbnail/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/transformer/catalog-transformer-zip/src/main/java/org/codice/ddf/catalog/transformer/zip/ZipCompression.java, catalog/transformer/catalog-transformer-zip/src/test/java/org/codice/ddf/catalog/transformer/zip/ZipCompressionTest.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/query/handlers/CqlTransformHandler.java, catalog/ui/catalog-ui-search/src/test/java/org/codice/ddf/catalog/ui/query/handlers/CqlTransformHandlerTest.java, ui/packages/catalog-ui-search/src/main/webapp/react-component/results-export/container.tsx
fixes compressed export for following types: csv, gmd metadata, kml, kmz, metadata xml, overlay thumbnail, preview and thumbnail
kml, kmz and overlay thumbnail now require a location attribute to be selected
overlay thumbnail and thumbnail require the thumbnail attribute to be selected
@cassandrabailey293 @mojogitoverhere @Lambeaux @brianfelix 
- ingest data, some with location attributes
- search for all data and select result(s) with checkboxes
- open compressed export by clicking vertical ellipsis on query
- verify export types listed above are exporting correctly 
Fixes: #____ …
=> [2.19.x] G-9780 Export selected (Compressed) export blank content for some formats

catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/util/impl/CaseInsensitiveIfStringComparator.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/federation/impl/SortedQueryMonitor.java, catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/federation/impl/SortedQueryMonitorTest.java
Port of https://github.com/codice/ddf/pull/6500
@SmithJosh @jlcsmith @derekwilhelm @stevenmalmgren
=> Updates SortedQueryMonitor to include a case insensitive sort

ui/packages/catalog-ui-search/src/main/webapp/react-component/filter/filter-input/filter-location-input.js
adds listener for rendering shapes downstream
- verify no regression drawing shapes on map
Fixes: #____
=> [2.19.x] G-9823 add listener for rendering shapes downstream

pom.xml
Upgrades DDF to consume new ddf-parent version and upgrade Xstream dependency
@pklinef
@shaundmorris
Completed a build consuming `ddf-parent` 1.0.12  with tests and dependency check enabled
Fixes: #____ …
=> upgrade to consume new ddf-parent version and xstream upgrade

features/test-utilities/src/main/feature/feature.xml, platform/platform-paxweb-jettyconfig/pom.xml, platform/security/security-jaas-ldap/pom.xml, pom.xml
Upgrades various dependencies to resolve security issues found by Snyk. https://app.snyk.io/org/codice/project/8b79555b-a0a4-4916-922d-adb3dc5e97d5/
Not all of the severe issues are covered in this PR as some are related to other upgrade efforts in progress.
@kentmorrissey
@lavoywj
@frnkshin
@hayleynorton
@jMoneee
@shaundmorris
@zta6
Full build should suffice
Additionally, tester could run snyk tests locally and confirm that the fixed dependencies are not still producing issues.
Fixes: #____ …
=> Upgrade Dependencies to resolve Snyk Issues

catalog/core/catalog-core-camelcomponent/src/main/java/ddf/camel/component/catalog/queryresponsetransformer/QueryResponseTransformerConsumer.java, catalog/core/catalog-core-camelcomponent/src/main/java/ddf/camel/component/catalog/transformer/TransformerConsumer.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/synchronizations/DeletionSynchronization.java, catalog/core/catalog-core-impl/pubsub-tracker/src/main/java/ddf/catalog/pubsub/tracker/SubscriptionTracker.java, catalog/core/catalog-core-impl/pubsub/src/main/java/ddf/catalog/pubsub/predicate/ContentTypePredicate.java, catalog/core/catalog-core-localstorageprovider/src/main/java/org/codice/ddf/catalog/content/impl/FileSystemStorageProvider.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/event/retrievestatus/DownloadsStatusEventPublisher.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/DeleteOperations.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/QueryOperations.java, catalog/core/catalog-core-standardframework/src/main/java/org/codice/ddf/catalog/sourcepoller/PollerRunner.java, catalog/opensearch/catalog-opensearch-endpoint/src/main/java/org/codice/ddf/opensearch/endpoint/OpenSearchEndpoint.java, catalog/plugin/catalog-plugin-metacard-validation/src/main/java/ddf/catalog/metacard/validation/MetacardValidityMarkerPlugin.java, catalog/plugin/catalog-plugin-metacardbackup-storage-common/src/main/java/org/codice/ddf/catalog/plugin/metacard/backup/common/MetacardStorageRoute.java, catalog/solr/catalog-solr-offline-gazetteer/src/main/java/ddf/catalog/solr/offlinegazetteer/GazetteerQueryOfflineSolr.java, catalog/spatial/csw/spatial-csw-source-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/AbstractCswSource.java, catalog/spatial/wfs/spatial-wfs-featuretransformer-handlebars/src/main/java/org/codice/ddf/spatial/ogc/wfs/transformer/handlebars/FeatureAttributeEntry.java, distribution/ddf-branding-plugin/src/main/java/org/codice/ddf/branding/impl/DdfBrandingPlugin.java, libs/activities/src/main/java/org/codice/ddf/activities/ActivityEvent.java, libs/httpproxy/proxy-camel-servlet/src/main/java/org/codice/proxy/http/HttpProxyCamelHttpTransportServlet.java, platform/mime/core/platform-mime-core-impl/src/main/java/ddf/mime/mapper/MimeTypeMapperImpl.java, platform/platform-logging/src/main/java/org/codice/ddf/platform/logging/LoggingService.java, platform/security/certificate/security-certificate-generator/src/main/java/org/codice/ddf/security/certificate/generator/CertificateGenerator.java, platform/security/certificate/security-certificate-keystoreeditor/src/main/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditor.java, platform/security/core/security-core-impl/src/main/java/ddf/security/samlp/impl/MetadataConfigurationParser.java, platform/security/core/security-core-services/src/main/java/ddf/security/service/impl/SubjectUtils.java, platform/solr/solr-factory-impl/src/main/java/org/codice/solr/factory/impl/SolrCloudClientFactory.java
Address sonar issues from https://sonarcloud.io/project/issues?id=ddf&resolved=false&rules=java%3AS3457&severities=MAJOR
@pklinef
@shaundmorris
Fixes: #____ …
=> Sonar-fixes for String formatting

distribution/solr-distro/pom.xml, platform/solr/solr-dependencies/pom.xml, platform/solr/solr-schema/src/main/resources/solr/conf/solrconfig.xml, pom.xml
Upgrades to Solr 8.8.1
@jMoneee
@shaundmorris
@abel-connexta
@kentmorrissey
@lavoywj
@frnkshin
@codice/solr 
@pklinef
@lambeaux
```
1.  Run SolrCloud docker image as directed by https://github.com/codice/ddf/blob/master/distribution/docker/solrcloud/README.md
2. Verify version by going into Solr admin console
3. Index data and verify search works
```
Upgrade Solr to 8.8.1
https://lucene.apache.org/solr/8_8_1/changes/Changes.html
Fixes: #n/a …
=> Upgrade to Solr 8.8.1

pom.xml
Upgrades Apache Shiro from 1.6.0 to 1.7.1
@kentmorrissey
@lavoywj
@frnkshin
@hayleynorton
@jMoneee
@shaundmorris
@zta6
Full Build should Suffice
Fixes: #____ …
=> Upgrade Apache Shiro to 1.7.1

catalog/core/catalog-core-commons/src/main/java/ddf/util/XSLTUtil.java, catalog/core/catalog-core-localstorageprovider/src/main/java/org/codice/ddf/catalog/content/impl/FileSystemStorageProvider.java, catalog/security/catalog-security-xmlattributeplugin/src/main/java/org/codice/ddf/catalog/security/policy/xml/XmlAttributeSecurityPolicyPlugin.java, catalog/spatial/csw/spatial-csw-source-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/reader/GetRecordsMessageBodyReader.java, catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/CswTransformProvider.java, catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/source/reader/FeatureCollectionMessageBodyReaderWfs20.java, platform/security/claims/security-claims-ldap/src/main/java/ddf/security/sts/claimsHandler/ClaimsHandlerManager.java, platform/security/pdp/security-pdp-authzrealm/src/main/java/ddf/security/pdp/realm/xacml/processor/XacmlClient.java
Addresses SonarCloud findings https://sonarcloud.io/project/issues?id=ddf&resolved=false&rules=java%3AS2093&severities=CRITICAL
@kentmorrissey
@lavoywj
@frnkshin
@hayleynorton
@jMoneee
@shaundmorris
@zta6
Full build and testing should be sufficient
Fixes: https://octoconsulting.atlassian.net/wiki/spaces/ARCH/pages/1783169029/Tech+Debt …
=> Addressing SonarCloud Findings

features/cxf/src/main/feature/feature.xml, features/pom.xml, pom.xml
Upgrades to CXF 3.4.2, and along with it upgraded Lucene dependency
@kentmorrissey
@lavoywj
@frnkshin
@hayleynorton
@jMoneee
@shaundmorris
@zta6
@jlcsmith 
Note - When was building, occasionally had itest failure for `ddf.test.itests.core.DdfCoreIT.testCswUpdateByFilterConstraint(DdfCoreIT.java:216)`
Error
`Expected: an XML document with XPath //TransactionResponse/TransactionSummary/totalUpdated is "2"`
This was also occurring for the base master, so believe it is not related to this upgrade.
- build / run / profile install
1. Configure a loopback CSW source and make sure it goes to “available”
- Config Loopback via Admin console -> System -> Configuration -> "CSW Federation Profile Source" . Can create using all defaults
- Check CSW source status is "available" via hitting sources …
=> Upgrade to CXF 3.4.2

distribution/docker/ddf-docker/pom.xml, distribution/docker/ddf-docker/src/main/docker/Dockerfile
Pulls from ddf-base 2.27-alpine which includes upgrade to java 11.
@lavoywj 
@shaundmorris 
@jMoneee 
@zta6 
@oconnormi
@shaundmorris
1. Build DDF
2. Build ddf-docker in /distribution/docker/ddf-docker
3. Run ddf-docker image
4. Log into the karaf shell and verify that DDF is working by installing `standard` profile. **(Make sure to increase RAM to somewhere around 6GB, I had personally set it to 6GB)**
Fixes: #N/A. …
=> Upgrade to Java 11 for ddf-docker

catalog/core/catalog-core-solr/pom.xml, catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/SolrCatalogProvider.java, catalog/core/catalog-core-solrcommands/pom.xml, catalog/core/catalog-core-solrcommands/src/test/java/org/codice/ddf/commands/solr/SolrCommandTest.java, catalog/core/catalog-core-solrcommands/src/test/resources/simplelogger.properties, catalog/core/catalog-core-standardframework/pom.xml, catalog/solr/catalog-solr-provider/pom.xml, catalog/solr/catalog-solr-solrclient/pom.xml, catalog/spatial/geocoding/spatial-geocoding-offline-catalog/pom.xml, distribution/docs/src/main/resources/content/_reference/_dependencyList/ddf-dependency-list.adoc, distribution/solr-distro/pom.xml, platform/solr/solr-dependencies/pom.xml, platform/solr/solr-factory-impl/src/main/java/org/codice/solr/factory/impl/PingAwareSolrClientProxy.java, platform/solr/solr-factory-impl/src/main/java/org/codice/solr/factory/impl/SolrClientAdapter.java, platform/solr/solr-factory-impl/src/main/java/org/codice/solr/factory/impl/SolrClientProxy.java, platform/solr/solr-factory-impl/src/main/java/org/codice/solr/factory/impl/SolrCloudClientFactory.java, platform/solr/solr-factory/src/main/java/org/codice/solr/client/solrj/SolrClient.java, platform/solr/solr-schema/src/main/resources/solr/conf/solrconfig.xml, pom.xml
Upgrades DDF to use Solr 8.8.1.
@millerw8 
@pklinef 
@andrewzimmer 
@Lambeaux 
@codice/solr 
@andrewzimmer
Build and run DDF as usual. Ingest, update, delete sample data.
Fixes: #____ …
=> [2.19.x] Upgrading to Solr 8.8.1

catalog/solr/catalog-solr-offline-gazetteer/pom.xml, catalog/solr/catalog-solr-offline-gazetteer/src/main/java/ddf/catalog/solr/offlinegazetteer/BuildGazetteerSuggesterIndexCommand.java, catalog/solr/catalog-solr-offline-gazetteer/src/main/java/ddf/catalog/solr/offlinegazetteer/CatalogGazetteerForwardingPlugin.java, catalog/solr/catalog-solr-offline-gazetteer/src/main/java/ddf/catalog/solr/offlinegazetteer/GazetteerConstants.java, catalog/solr/catalog-solr-offline-gazetteer/src/main/java/ddf/catalog/solr/offlinegazetteer/GazetteerQueryOfflineSolr.java, catalog/solr/catalog-solr-offline-gazetteer/src/main/java/ddf/catalog/solr/offlinegazetteer/RemoveAllOfflineSolrGazetteerCommand.java, catalog/solr/catalog-solr-offline-gazetteer/src/main/java/ddf/catalog/solr/offlinegazetteer/SyncCatalogCommand.java, catalog/solr/catalog-solr-offline-gazetteer/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/solr/catalog-solr-offline-gazetteer/src/test/groovy/ddf/catalog/solr/offlinegazetteer/CatalogGazetteerForwardingPluginSpec.groovy, catalog/solr/catalog-solr-offline-gazetteer/src/test/groovy/ddf/catalog/solr/offlinegazetteer/GazetteerQueryOfflineSolrSpec.groovy, catalog/solr/catalog-solr-offline-gazetteer/src/test/groovy/ddf/catalog/solr/offlinegazetteer/RemoveAllOfflineSolrGazetteerCommandSpec.groovy, catalog/solr/catalog-solr-offline-gazetteer/src/test/groovy/ddf/catalog/solr/offlinegazetteer/SyncCatalogCommandSpec.groovy, catalog/solr/pom.xml, catalog/solr/solr-app/pom.xml, catalog/solr/solr-app/src/main/resources/features.xml, catalog/spatial/geocoding/spatial-geocoding-api/src/main/java/org/codice/ddf/spatial/geocoding/GeoEntry.java, distribution/ddf-common/src/main/resources/security/default.policy, distribution/docs/src/main/resources/content/_reference/_appReferences/mg-spatial.adoc, platform/solr/solr-schema/src/main/resources/solr/conf/solrconfig.xml
Backport of #6153 
This adds a new gazetteer feature that copies all gazetteer data into a separate solr core called `gazetteer`. This allows the index to be updated without the overhead of all other items in the catalog.
- Stop the `DDF :: Spatial :: Geocoding :: Plugin` bundle
- Install the Solr Gazetteer feature `feature:install -r catalog-solr-offline-gazetteer`
- Ingest a record with the `gazetteer` metacard tag
- Verify the document is eventually created at https://localhost:8994/solr/#/gazetteer/query
- Verify the DDF UI location lookup can find the record
Fixes: n/a
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+ …
=> [2.19.x] DDF-6152 Added standalone Solr gazetteer 

catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/IngestCommand.java
Unable to ingest data via karaf, due to changes here https://github.com/codice/ddf/commit/19ffa80139cadbd40b80c5b6ab6d30caaa3f2084#diff-3f93d97685e6f7dffa215903b08f8f3d67f1f40c3d8e08486fa5bea159b0b97fR495
@kentmorrissey
@shaundmorris
@zta6 
- Build and install
- Download this set of assorted file types: https://github.com/codice/ddf/tree/master/catalog/transformer/catalog-transformer-tika-input/src/test/resources.
- Ingest data via different methods e.g. :
1. `admin@root()> catalog:ingest -t tika "/path/to/test/resources"`
2. `admin@root()> catalog:ingest -t pdf "/path/to/test/resources/testPDF.pdf"`
3. File ingest e.g. `curl -k -X POST -i -H "Content-Type: multipart/mixed" -basic --user admin:admin -F upload=@IMG_3808.png https://localhost:8993/services/catalog`
Fixes: #____
Please see …
=> Ingest Stream Error

ui/packages/catalog-ui-search/src/main/webapp/component/query-add/query-add.view.js, ui/packages/catalog-ui-search/src/main/webapp/js/store.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/workspace-item/container.tsx
clears search form when user navigates to new workspace
- build / run
- open workspace and edit search form with geos/attributes, do not save or run
- switch to a new workspace and verify the search form is cleared and the previously drawn geos do not appear 
Fixes: #____ …
=> [2.19.x] G-9391 clear search form when user navigates to new workspace

pom.xml
Upgrades to Bouncy Castle 1.68
@kentmorrissey
@shaundmorris
@zta6
@SmithJosh
@codice/io
1. Build and install DDF.
2. Log into the admin console.
i. Logout.
3. Log into Intrigue.
i. Ingest a resource.
ii. Query for that resource.
iii. Verify the resource looks correct.
4. In the Karaf console, run `security:encrypt <value>` where `<value>` is an arbitrary string of your choice. Verify that the value is encrypted.
5. Restart DDF and verify that there are no startup issues.
Fixes: #____ …
=> Upgrade Bouncy Castle to 1.68

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/ResourceOperations.java, catalog/rest/catalog-rest-endpoint/src/main/java/org/codice/ddf/endpoints/rest/RESTEndpoint.java, catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/CswConstants.java, catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/CswMarshallHelper.java, catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/source/WfsSource.java, libs/klv/src/main/java/org/codice/ddf/libs/klv/data/Klv.java, platform/security/pdp/security-pdp-authzrealm/src/main/java/ddf/security/pdp/realm/xacml/XacmlPdp.java
Fixes issues identified by SonarCloud here 
https://sonarcloud.io/project/issues?id=ddf&resolved=false&rules=java%3AS1192&severities=CRITICAL
@kentmorrissey
@shaundmorris
@zta6 
Full build should be sufficient
Fixes: #____ …
=> SonarCloud findings 13 - create constants for repeated string literals

features/solr/pom.xml, pom.xml
Address Snyk 'HIGH' findings for ddf solr
Overrides versions for solr dependencies/transitive dependencies to address security vulnerabilities. 
@shaundmorris 
@jMoneee 
@lavoywj 
@pklinef
@stustison
Build, profile:install, test basic functionality to verify no regressions
Fixes: #____ …
=> Address Snyk 'HIGH' findings for ddf solr

catalog/core/catalog-core-camelcomponent/src/main/java/ddf/camel/component/catalog/CatalogEndpoint.java, catalog/core/catalog-core-camelcomponent/src/main/java/ddf/camel/component/catalog/content/ContentEndpoint.java, features/camel/src/main/feature/feature.xml, features/pom.xml, libs/httpproxy/proxy-camel-servlet/pom.xml, platform/admin/core/admin-core-impl/src/main/java/org/codice/ddf/admin/core/impl/AdminConsoleService.java, pom.xml
Upgrades to Camel 3.8.0 to continue receiving security updates. Also fixed issue for Admin Console, when creating a "WFS v1.1.0 Federated Source" configuration, you are left with loading spinning wheel icon and an json parsing exception in console.  
@kentmorrissey
@shaundmorris
@zta6
@SmithJosh
@codice/io
Test the http proxy and all the camel routes
F.Y.I - Also you will probably get a 403 response, that is ok, because that's the old url for the Cesium tile assets. They no longer allow public access anymore so you get that 403 response. In production that would be changed to point to a real tile server, but for now it’s enough just to verify that the proxy url is forwarding the request and getting the same 403 response.
Note - Unable to test this, since don't have a …
=> Upgrade to Camel 3.8.0

pom.xml
Upgrade Apache Tika to 1.26 and upgraded depencies to be in sync with what Tika uses.
This PR depends on https://github.com/codice/thirdparty/pull/131
@kentmorrissey
@shaundmorris
@zta6
@SmithJosh
1. Build https://github.com/codice/thirdparty/pull/131
2. Build this PR branch and run DDF
3. Download this set of assorted file types: https://github.com/codice/ddf/tree/master/catalog/transformer/catalog-transformer-tika-input/src/test/resources.
4. Test the Tika input transformer by ingesting those files from the Karaf shell.
`admin@root()> catalog:ingest -t tika "/path/to/test/resources"`
5. Test the video input transformer
`admin@root()> catalog:ingest -t video "/path/to/test/resources/testMP4.m4a"`
6. Test the pdf input transformer
`admin@root()> catalog:ingest -t pdf …
=> Upgrade Tika to 1.26

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/federation/impl/SortedQueryMonitor.java, catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/federation/impl/SortedQueryMonitorTest.java
Source response properties can collide for a given key. For example this can happen with highlights from the Solr provider. Now it also makes a copy of the original source properties to a new property keyed by source ID which can be used in case of collisions.
@derekwilhelm
@jlcsmith
Use a debugger to verify that source response properties from a catalog framework query are copied into a new `originalSourceProperties` response property.
Fixes: n/a …
=> [2.26.x] Fix source property collision

catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsFilterDelegate.java, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsFilterDelegateTest.java
Adds support for multipolygon WKT to the WFS 1.1.0 Source. There is a fallback if multipolygon is not supported but polygon is which is true for Geoserver.
@jMoneee 
@jlcsmith
- Create a WFS 1.1 source to Geoserver with test data loaded
- Install DDF UI backend
```
feature:repo-add mvn:org.codice.ddf.search/intrigue-ui-app/5.0.1-SNAPSHOT/xml/features
feature:install catalog-ui-app
```
- Post requests to `https://localhost:8993/search/catalog/internal/cql`
- Query with a multipolygon
```JSON
{"start":1,"count":250,"cql":"(INTERSECTS(\"anyGeo\", MULTIPOLYGON(((-123.575001 45.851013,-120.148311 34.000377,-97.732049 27.575334,-98.017606 45.708234,-123.575001 45.851013)),((-97.58927 27.718113,-98.160385 45.851013,-65.892389 46.13657,-80.027485 24.862538,-97.58927 …
```
=> [2.26.x] Support multipolygon WKT for WFS 1.1.0 Source

catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsSource.java, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsSourceTest.java
forward port of https://github.com/codice/ddf/pull/6574
@derekwilhelm @pklinef 
@derekwilhelm @pklinef 
Fixes: #____
=> DDF-4729 handles WFS null sortBy property (#6574)

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/federation/impl/SortedQueryMonitor.java, catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/federation/impl/SortedQueryMonitorTest.java
Forward port of #6560
@derekwilhelm 
@glenhein 
@jlcsmith
Use a debugger to verify that source response properties from a catalog framework query are copied into a new `originalSourceProperties` response property.
Fixes: n/a …
=> Fix source property collision

catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsFilterDelegate.java, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsFilterDelegateTest.java
Forward port of #6570
@jMoneee 
@jlcsmith
See #6570
Fixes: n/a
=> Support multipolygon WKT for WFS 1.1.0 Source

catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/pom.xml, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/ExtendedGetFeatureType.java, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/ExtendedWfs.java, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsSource.java, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/resources/OSGI-INF/metatype/metatype.xml, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsSourceTest.java
Forward port of #6564 and #6571
@derekwilhelm 
@jlcsmith
- Setup Geoserver with test data with over 1000 results.
-  Configure a WFS 1.1.0 source for that Geoserver.
-  Set the supportsStartIndex config option.
-  Verify you can page past 1000 results.
-  Disable the supportsStartIndex config option.
-  Verify you can page up to 1000 results but fails past 1000.
Fixes: n/a …
=> Support startIndex in GetFeature requests on WFS 1.1.0

ui/packages/catalog-ui-search/src/main/webapp/component/query-advanced/query-advanced.hbs, ui/packages/catalog-ui-search/src/main/webapp/component/query-advanced/query-advanced.less, ui/packages/catalog-ui-search/src/main/webapp/component/result-form/result-form.hbs, ui/packages/catalog-ui-search/src/main/webapp/component/result-form/result-form.less
Updates styling of save/cancel buttons in search and result forms to match styling of other save/cancel buttons downstream.
- Verify that styling for adding and editing an advanced search within a workspace has not changed (these two components utilize the same styling file used by the search form creation component).
- Bring these changes to the downstream project and verify that the save/cancel buttons are unified across the app
Fixes: #____ …
=> [2.19.x] Update styling for save/cancel buttons in search and result forms

platform/email/platform-email-impl/src/main/java/org/codice/ddf/platform/email/impl/SmtpClientImpl.java
Moves the audit logging for emails outside of the thread that sends the email.  This avoids any issues with the wrong subject being logged inadvertently.
@pklinef @derekwilhelm 
@pklinef @derekwilhelm 
Fixes: #____ …
=> [2.26.x] DDF-6609 corrects email audit logging

distribution/solr-distro/pom.xml, platform/solr/solr-schema/src/main/resources/solr/conf/solrconfig.xml, pom.xml
Upgrades Solr to 8.9.0.
@codice/solr 
@jlcsmith
@shaundmorris
Verify CI build passes
Fixes: n/a
=> Upgrade to Solr 8.9.0

catalog/transformer/catalog-transformer-geojson-input/src/main/java/ddf/catalog/transformer/input/geojson/GeoJsonInputTransformer.java, catalog/transformer/catalog-transformer-geojson-input/src/test/java/ddf/catalog/transformer/input/geojson/GeoJsonExtensibleTest.java, catalog/transformer/catalog-transformer-geojson-input/src/test/java/ddf/catalog/transformer/input/geojson/GeoJsonInputTransformerTest.java
Back port of #6614
@jhunzik
@mcalcote
Verify updated unit tests pass CI.
Fixes: #____
=> [2.25.x] Improve GeoJSON input transformer ISO date handling

catalog/transformer/catalog-transformer-geojson-input/src/main/java/ddf/catalog/transformer/input/geojson/GeoJsonInputTransformer.java, catalog/transformer/catalog-transformer-geojson-input/src/test/java/ddf/catalog/transformer/input/geojson/GeoJsonExtensibleTest.java, catalog/transformer/catalog-transformer-geojson-input/src/test/java/ddf/catalog/transformer/input/geojson/GeoJsonInputTransformerTest.java
Add handling of "+HH:MM" and "Z" offsets to the already supported "+HHMM" offset.
@jhunzik 
@derekwilhelm 
@mcalcote
Verify updated unit tests pass CI.
Fixes: #____ …
=> Improve GeoJSON input transformer handling of ISO 8601 dates

distribution/docker/solrcloud/pom.xml
Fixes the ddf-solrcloud parent version
@mcalcote
Verify CI build passes.
Fixes: #____
=> [2.25] Fix ddf-solrcloud parent version

platform/email/platform-email-impl/src/main/java/org/codice/ddf/platform/email/impl/SmtpClientImpl.java
Forward port of #6610 
@pklinef @derekwilhelm 
@pklinef @derekwilhelm 
Fixes: #6609 
=> DDF-6609 corrects email audit logging (#6610)

distribution/docs/src/main/resources/templates/architectures.ftl, distribution/docs/src/main/resources/templates/developing.ftl, distribution/docs/src/main/resources/templates/documentation.ftl, distribution/docs/src/main/resources/templates/integrating.ftl, distribution/docs/src/main/resources/templates/managing.ftl, distribution/docs/src/main/resources/templates/metadata.ftl, distribution/docs/src/main/resources/templates/overview.ftl, distribution/docs/src/main/resources/templates/quickstart.ftl, distribution/docs/src/main/resources/templates/reference.ftl, distribution/docs/src/main/resources/templates/using.ftl
updates the documentation ftl templates for consistency on `:title:` fields to enable use in custom pdf templates
@codice/docs 
builds successfully, changes won't be apparent in pdfs at this stage …
=> updated documentation template files title fields

distribution/docs/src/main/resources/content/_managing/_configuring/restricting-app-access.adoc, distribution/docs/src/main/resources/content/_managing/_securing/hardening-checklist.adoc, distribution/docs/src/main/resources/content/_quickstart/quickstart-adding-roles.adoc, distribution/docs/src/main/resources/content/_quickstart/quickstart-installing.adoc, distribution/docs/src/main/resources/content/_reference/_tables/ContentDirectoryMonitor.adoc
adds instructions for add new user roles into users.properties
@shaundmorris 
@clockard 
@sgalla 
@rececoffin 
@jaymcnallie 
@zach3904 
@codice/docs 
review content for clarity and accuracy …
=> added instructions to docs for adding custom user roles (#6652)

distribution/docs/README.md
updates readme for documentation module
@codice/docs 
@clockard
@smithjosh
@stustison
@jaymcnallie 
=> Updated docs module README

distribution/docs/README.md
**Forward port of #6655**
updates readme for documentation module
@codice/docs 
@clockard
@smithjosh
@stustison
@jaymcnallie 
=> Updated README for docs module

features/utilities/pom.xml, features/utilities/src/main/feature/feature.xml, platform/metrics/opentelemetry-api-bundle/pom.xml, platform/metrics/pom.xml, pom.xml
Upgrades to Micrometer 1.8 and Prometheus client 0.12.0. Also added OpenTelemetry API bundle for Prometheus
@ahoffer
@ryeats
Unzip and run. Make sure https://localhost:8993/metrics works.
Fixes: n/a …
=> Upgrade Micrometer and Prometheus Client

catalog/transformer/catalog-transformer-tika-input/src/test/java/ddf/catalog/transformer/input/tika/TikaInputTransformerTest.java, features/cxf/src/main/feature/feature.xml, features/pom.xml, pom.xml
Upgraded CXF and related transitive dependencies. Tika was also upgraded which changed its default MP4 parser which impacted some unit tests.
@ahoffer
@andrewzimmer
@ryeats
Unzip, run, install the standard profile, ingest common images, and then verify you can search the catalog.
Fixes: n/a
- ❓ …
=> Upgrade to CXF 3.4.5

catalog/rest/catalog-rest-endpoint/src/test/resources/custom.properties, catalog/solr/catalog-solr-commands/pom.xml, catalog/solr/catalog-solr-solrclient/pom.xml, distribution/ddf-common/src/main/resources-filtered/etc/startup.properties, platform/security/platform-security-core-api/pom.xml, platform/solr/solr-logging/pom.xml, pom.xml
Upgrades to Karaf 4.3.4. 
This upgrades Pax Logging which resolves Log4j CVE CVE-2021-44228 without configuration changes. Log4j configuration can be used to mitigate this CVE without this upgrade.
https://blog.cloudflare.com/inside-the-log4j2-vulnerability-cve-2021-44228/
Unzip, run, ingest data, and search.
Fixes: n/a …
=> Upgrade to Karaf 4.3.4

catalog/core/catalog-core-camelcomponent/src/main/java/ddf/camel/component/catalog/converter/BinaryContentStringTypeConverter.java, catalog/core/catalog-core-camelcomponent/src/main/java/ddf/camel/component/catalog/metacardtransformer/MetacardTransformerProducer.java, catalog/core/catalog-core-camelcomponent/src/main/java/ddf/camel/component/catalog/transformer/TransformerConsumer.java, catalog/core/catalog-core-camelcomponent/src/test/java/ddf/camel/component/catalog/PostIngestConsumerTest.java, catalog/core/catalog-core-camelcomponent/src/test/java/ddf/camel/component/catalog/metacardtransformer/MetacardTransformerProducerTest.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/AbstractDurableFileConsumer.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/DurableFileAlterationListener.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/DurableFileComponent.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/DurableFileEndpoint.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/DurableFileSystemFileConsumer.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/DurableWebDavFileConsumer.java, catalog/plugin/catalog-plugin-metacardbackup-s3storage/pom.xml, catalog/plugin/catalog-plugin-metacardbackup-s3storage/src/main/java/org/codice/ddf/catalog/plugin/metacard/backup/storage/s3storage/DeleteBean.java, catalog/plugin/catalog-plugin-metacardbackup-s3storage/src/main/java/org/codice/ddf/catalog/plugin/metacard/backup/storage/s3storage/MetacardS3StorageRoute.java, catalog/plugin/catalog-plugin-metacardbackup-s3storage/src/test/java/org/codice/ddf/catalog/plugin/metacard/backup/storage/s3storage/MetacardBackupS3StorageTest.java, features/camel/src/main/feature/feature.xml, features/pom.xml, pom.xml
Upgrades to Camel 3.14. Upgrading Camel also required moving from AWS Java SDK 1.11.x to AWS Java SDK 2.17.x.
@ahoffer
@andrewzimmer
@ryeats
Verify CI build passes. Unzip, run, install the standard profile, ingest files, and query. Verify you can install the `catalog-metacard-backup-s3storage` feature.
Fixes: n/a …
=> Upgrade to Camel 3.14.0

distribution/solr-distro/pom.xml, platform/solr/solr-schema/src/main/resources/solr/conf/solrconfig.xml, pom.xml
Upgrades to Solr 8.11.1
@codice/solr 
@ryeats
@ahoffer
Verify that CI passes
Fixes: n/a
=> Upgrade to Solr 8.11.1

platform/branding-registry-impl/src/main/java/org/codice/ddf/branding/impl/BrandingRegistryImpl.java
Fixes an exception that happens if a BrandingPlugin is unregistered from the BrandingRegistry.
```
branding-registry-impl [org.osgi.framework.FrameworkEvent] ERROR : FrameworkEvent ERROR
java.lang.ClassCastException: class org.codice.ddf.branding.impl.DdfBrandingPlugin cannot be cast to class org.osgi.framework.ServiceReference (org.codice.ddf.branding.impl.DdfBrandingPlugin is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @ae9129f; org.osgi.framework.ServiceReference is in unnamed module of loader 'app')
at org.codice.ddf.branding.impl.BrandingRegistryImpl$1.compare(BrandingRegistryImpl.java:44)
at java.base/java.util.TreeMap.getEntryUsingComparator(TreeMap.java:374)
at java.base/java.util.TreeMap.getEntry(TreeMap.java:343)
at …
```
=> Fix unregistering a BrandingPlugin from BrandingRegistry

catalog/transformer/catalog-transformer-pptx/pom.xml, distribution/solr-distro/assembly.xml, distribution/solr-distro/pom.xml, platform/solr/solr-schema/src/main/resources/solr/conf/solrconfig.xml, pom.xml
Upgrades DDF to use Solr 8.11.1.  Also replaces the packaged log4j jars with the latest version to resolve CVE-2021-44228.
@jrnorth @pklinef 
@codice/solr 
@jrnorth @pklinef 
Fixes: #____ …
=> [2.19.x] Upgrade to Solr 8.11.1

distribution/ddf-common/src/main/resources-filtered/etc/application-definitions/geowebcache.json
Removes left over GeoWebCache file
@jlcsmith 
@jrnorth 
Originally removed on https://github.com/codice/ddf/pull/6677
=> DDF-5820 removed remaining gwc file

ui/packages/catalog-ui-search/src/main/webapp/js/extensions/backbone.partialAssociatedModel.js, ui/packages/catalog-ui-search/src/main/webapp/js/extensions/backbone.partialAssociatedModel.spec.js, ui/packages/catalog-ui-search/src/main/webapp/js/model/Workspace.collection.js, ui/packages/catalog-ui-search/src/main/webapp/react-component/workspace-interactions/container.tsx
Performs a partial fetch (fetching the target workspace's queries) before duplicating the workspace so the new workspace will have the expected queries.
@maiiiiiiii 
@kcwire 
@jlcsmith 
Follow the steps in the ticket and verify queries are now correctly copied to the new workspace. …
=> [2.19.x] G-10049 Fix workspace duplication issue

catalog/ui/catalog-ui-search/pom.xml, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/security/app/UserApplication.java, catalog/ui/catalog-ui-search/src/main/java/org/codice/ddf/catalog/ui/security/user/AttributesModifier.java, catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/ui/catalog-ui-search/src/main/resources/OSGI-INF/blueprint/consumes.xml
=> [2.19.x] G-10142 Make user attributes endpoint extensible

catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsFilterDelegate.java, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsFilterDelegateTest.java
Forward port of #6685 
@glenhein 
@derekwilhelm 
@codice/ogc 
@glenhein 
@derekwilhelm 
Fixes: #____
=> Normalize WFS 1.1.0 query times to UTC (#6685)

distribution/ddf-common/src/main/resources-filtered/etc/startup.properties, distribution/ddf-common/src/main/resources/bin/setenv, libs/test-common/src/main/java/org/codice/ddf/test/common/options/VmOptions.java, pom.xml
Upgrades to Karaf 4.3.7
@ryeats
@jrnorth
Make sure DDF starts and works correctly.
Fixes: n/a
=> Upgrade to Karaf 4.3.7

pom.xml
Upgrades CXF to 3.4.8
@ahoffer
@andrewzimmer
@ryeats
Verify CI passes.
Fixes: #____
=> Upgrade to CXF 3.4.8

pom.xml
Upgrades `commons-lang3` to 3.12.0
@kcwire 
@jlcsmith
@millerw8 
Full build is sufficient.
=> [2.19.x] G-20545 Upgrade commons-lang3 to 3.12.0

catalog/catalog-app/src/main/resources/features.xml, catalog/core/catalog-core-camelcomponent/pom.xml, catalog/core/catalog-core-downloadaction/pom.xml, catalog/opensearch/catalog-opensearch-source/pom.xml, catalog/plugin/catalog-plugin-metacardbackup-filestorage/pom.xml, catalog/plugin/catalog-plugin-metacardbackup-s3storage/pom.xml, catalog/plugin/catalog-plugin-metacardbackup-storage-common/pom.xml, catalog/plugin/catalog-plugin-oauth/pom.xml, catalog/pom.xml, catalog/spatial/kml/spatial-kml-networklinkendpoint/pom.xml, catalog/spatial/kml/spatial-kml-transformer/pom.xml, catalog/spatial/wfs/spatial-wfs-featuretransformer-handlebars/pom.xml, catalog/transformer/catalog-transformer-html/pom.xml, catalog/transformer/catalog-transformer-html/src/main/java/ddf/catalog/transformer/html/HtmlMetacardUtility.java, catalog/transformer/catalog-transformer-pptx/pom.xml, catalog/transformer/catalog-transformer-service-atom/pom.xml, catalog/transformer/catalog-transformer-xlsx/pom.xml, catalog/ui/search-ui/simple/src/main/java/org/codice/ddf/ui/searchui/simple/properties/UiConfigurationProperties.java, features/security/pom.xml, features/security/src/main/feature/feature.xml, features/utilities/pom.xml, features/utilities/src/main/feature/feature.xml, platform/landing-page/src/main/java/org/codice/ddf/landing/LandingPage.java, platform/security/core/security-core-services/pom.xml, platform/security/handler/security-handler-oauth/pom.xml, platform/security/handler/security-handler-oidc/pom.xml, platform/security/realm/security-realm-oidc/pom.xml, platform/security/security-oidc-bundle/pom.xml, pom.xml
Upgrades dependencies included in the distribution.
@ahoffer
@andrewzimmer
@ryeats
Verify CI passes.
Fixes: n/a
=> Upgrade dependencies included in distribution

catalog/transformer/catalog-transformer-overlay/src/main/java/ddf/catalog/transformer/GeometryUtils.java, catalog/transformer/catalog-transformer-overlay/src/main/java/ddf/catalog/transformer/OverlayMetacardTransformer.java, catalog/transformer/catalog-transformer-overlay/src/test/java/ddf/catalog/transformer/OverlayMetacardTransformerTest.java, catalog/transformer/catalog-transformer-overlay/src/test/java/ddf/catalog/transformer/PolygonNormalizationTest.java
Updates the overlay metacard transformer so it will reverse counterclockwise coordinates to clockwise before manipulating the image. This is necessary because the image manipulation code assumes the coordinates are clockwise.
@millerw8 
@maiiiiiiii 
@kcwire
@jlcsmith 
Ingest the following metacard:
```xml
<metacard xmlns="urn:catalog:metacard">
<type>ddf.metacard</type>
<source>ddf.distribution</source>
<dateTime name="metacard.created">
<value>2021-10-18T20:49:38.028+00:00</value>
</dateTime>
<dateTime name="metacard.modified">
<value>2021-10-18T20:49:38.028+00:00</value>
</dateTime>
<dateTime name="effective">
<value>2021-10-18T20:49:38.028+00:00</value>
</dateTime>
<dateTime name="created">
<value>1987-10-19T11:07:27.064+00:00</value>
</dateTime>
<dateTime name="modified"> …
```
=> [2.19.x] Always set coordinates to clockwise for overlays

platform/platform-paxweb-jettyconfig/pom.xml, platform/platform-paxweb-jettyconfig/src/main/java/org/codice/ddf/pax/web/jetty/ClientInfoFilter.java, platform/platform-paxweb-jettyconfig/src/main/java/org/codice/ddf/pax/web/jetty/TraceContextFilter.java, platform/platform-paxweb-jettyconfig/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/platform-paxweb-jettyconfig/src/test/java/org/codice/ddf/pax/web/jetty/ClientInfoFilterTest.java, platform/security/core/security-core-services/src/main/java/ddf/security/audit/impl/SecurityLoggerImpl.java, platform/security/platform-security-core-api/pom.xml, platform/security/platform-security-core-api/src/main/java/org/codice/ddf/security/util/ThreadContextProperties.java, platform/security/platform-security-core-api/src/test/java/org/codice/ddf/security/util/ThreadContextPropertiesTest.java, platform/security/servlet/security-servlet-web-socket-api/pom.xml, platform/security/servlet/security-servlet-web-socket-api/src/main/java/org/codice/ddf/security/servlet/web/socket/SecureWebSocketServlet.java
Forward port of https://github.com/codice/ddf/pull/6637 and https://github.com/codice/ddf/pull/6641
@derekwilhelm @pklinef 
@derekwilhelm @pklinef 
See test steps in https://github.com/codice/ddf/pull/6637
See https://github.com/codice/ddf/pull/6637 and https://github.com/codice/ddf/pull/6641
Fixes: #6636  …
=> DDF-6636 adds IP and port to all audit events

platform/security/servlet/security-servlet-web-socket-api/src/main/java/org/codice/ddf/security/servlet/web/socket/SecureWebSocketServlet.java, platform/security/servlet/security-servlet-web-socket-api/src/main/java/org/codice/ddf/security/servlet/web/socket/SessionPlugin.java
Add plugin support to websockets so downstream projects inject special processing logic for web socket connections.
@rececoffin 
@jlcsmith 
@derekwilhelm 
Build, install, and make sure existing web socket behavior functions as expected.
Fixes: #6714 
- ❗ …
=> [2.26.x] DDF-6714 add plugin support to websockets

platform/security/servlet/security-servlet-web-socket-api/src/main/java/org/codice/ddf/security/servlet/web/socket/SecureWebSocketServlet.java, platform/security/servlet/security-servlet-web-socket-api/src/main/java/org/codice/ddf/security/servlet/web/socket/SessionPlugin.java
Forward port of https://github.com/codice/ddf/pull/6715
Add plugin support to websockets so downstream projects inject special processing logic for web socket connections.
@clockard 
@derekwilhelm 
@jlcsmith 
Fixes: https://github.com/codice/ddf/issues/6714 …
=> DDF-6714 add plugin support to websockets (#6715)

pom.xml
Upgraded apache shiro to 1.10.1
=> [2.19.x] G-20680 - upgraded apache shiro

catalog/rest/catalog-rest-endpoint/pom.xml, catalog/rest/catalog-rest-endpoint/src/test/java/org/codice/ddf/endpoints/rest/it/RestEndpointIT.java, features/admin/pom.xml
Replaces old DDF CXF feature file with official CXF feature file.
@ryeats
Successful CI build.
Fixes: #____
=> Fix DDF CXF features being used instead of CXF official features

Jenkinsfile, catalog/solr/catalog-solr-commands/pom.xml, catalog/solr/catalog-solr-commands/src/test/java/org/codice/ddf/commands/solr/RestoreCommandTest.java, catalog/solr/catalog-solr-commands/src/test/java/org/codice/ddf/commands/solr/SolrCommandTest.java, catalog/solr/catalog-solr-commands/src/test/resources/log4j2-test.xml, catalog/solr/catalog-solr-commands/src/test/resources/logback-test.xml, catalog/solr/catalog-solr-core/pom.xml, catalog/solr/catalog-solr-core/src/test/resources/log4j2-test.xml, catalog/solr/catalog-solr-core/src/test/resources/logback-test.xml, pom.xml
Fixes CI build. Reduces the logging level and provide additional logback configuration. 
@ahoffer
@ryeats
Verify CI passes.
Fixes: #____
=> Fix CI build

catalog/solr/catalog-solr-commands/pom.xml, distribution/solr-distro/pom.xml, pom.xml
Upgrades to Solr 9.1.1.
@codice/solr 
@ahoffer
@ryeats
Verify CI build passes.
Fixes: N/A
=> Upgrade to Solr 9.1.1

catalog/core/catalog-core-standardframework/pom.xml, catalog/solr/catalog-solr-commands/pom.xml, catalog/solr/catalog-solr-commands/src/test/java/org/codice/ddf/commands/solr/BackupCommandTest.java, catalog/solr/catalog-solr-commands/src/test/java/org/codice/ddf/commands/solr/SolrCommandTest.java, catalog/spatial/csw/spatial-csw-endpoint/pom.xml, features/utilities/pom.xml, pom.xml
Upgrades to Karaf 4.4.3.
@ahoffer
@ryeats
Verify CI build passes.
Fixes: n/a
=> Upgrade to Karaf 4.4.3

Jenkinsfile
Removed CMSClassUnloadingEnabled from the maven options.  This doesn't appear to be needed and is causing issues with downstream projects.
@rececoffin @derekwilhelm 
@codice/build 
@rececoffin @derekwilhelm 
Fixes: #____
- ❗ …
=> [2.26.x] Removed CMSClassUnloadingEnabled flag from Jenksfile

catalog/core/catalog-core-api/src/main/java/ddf/catalog/plugin/SourcePlugin.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/FrameworkProperties.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/SourceOperations.java, catalog/core/catalog-core-standardframework/src/main/resources/OSGI-INF/blueprint/frameworkprops.xml, catalog/core/catalog-core-standardframework/src/main/resources/OSGI-INF/blueprint/plugins.xml
Adds a plugin point for sources return from the framework. Will let downstream projects apply needed filtering.
@glenhein 
@derekwilhelm 
@jlcsmith 
Good CI build
Will need to be tested in downstream projects.
Fixes: #____ …
=> [2.26.x] Add a plugin point for framework sources

catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/CqlCommands.java
Improve cql examples for catalog:remove and catalog:search
Fixes: #____
=> Improve cql examples for catalog:remove and catalog:search

catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/CqlCommands.java
Improve cql examples for catalog:remove and catalog:search
Fixes: #____
=> [2.26.x] Improve cql examples for catalog:remove and catalog:search

catalog/solr/catalog-solr-commands/pom.xml, catalog/solr/catalog-solr-core/pom.xml, catalog/solr/catalog-solr-core/src/test/java/ddf/catalog/source/solr/SolrProviderTest.java, distribution/solr-distro/pom.xml, features/solr/src/main/feature/feature.xml, platform/solr/solr-dependencies/pom.xml, pom.xml
Upgrades Solr and Geotools.
Verify build passes.
Fixes: #____
=> [3.x] Upgrade Solr and Geotools

catalog/transformer/catalog-transformer-rtf/pom.xml, catalog/transformer/catalog-transformer-rtf/src/main/java/ddf/catalog/transformer/output/rtf/model/ExportCategory.java
=> [2.26.x] fix npe in rtf

catalog/ui/search-ui/simple/pom.xml
After upgrading several development related packages on my system, I had to bump the yui compressor version for the build to pass. This behavior was confirmed and solved by @pklinef. 
@pklinef 
@derekwilhelm 
Fixes: #____ …
=> [2.26.x] Bump yuicompressor-maven-plugin version

catalog/ui/search-ui/simple/pom.xml
After upgrading several development related packages on my system, I had to bump the yui compressor version for the build to pass. This behavior was confirmed and solved by @pklinef.
@pklinef
@derekwilhelm
Fixes: #____
- ❗ …
=> Bump yuicompressor-maven-plugin version

catalog/catalog-app/pom.xml, catalog/catalog-app/src/main/resources/features.xml, distribution/ddf-common/src/main/resources-filtered/etc/custom.system.properties, features/solr/pom.xml, features/solr/src/main/feature/feature.xml, platform/pom.xml, platform/preferences/pom.xml, platform/preferences/preferences-api/pom.xml, platform/preferences/preferences-api/src/main/java/org/codice/ddf/preferences/DefaultPreferencesSupplier.java, platform/preferences/preferences-api/src/main/java/org/codice/ddf/preferences/PostRetrievalPlugin.java, platform/preferences/preferences-api/src/main/java/org/codice/ddf/preferences/Preferences.java, platform/preferences/preferences-api/src/main/java/org/codice/ddf/preferences/PreferencesException.java, platform/preferences/preferences-impl/pom.xml, platform/preferences/preferences-impl/src/main/java/org/codice/ddf/preferences/impl/PreferencesImpl.java, platform/preferences/preferences-impl/src/main/java/org/codice/ddf/preferences/impl/PreferencesMetacardType.java, platform/preferences/preferences-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml
Creates a new solution for storing user preferences in a metacard in the main catalog. It also allows downstream projects add new preference settings with the ability to supply defaults and modify the preferences returned by the catalog with a plugin.
It should be fine to merge this prior to modifying downstream projects since it adds a new service, but does to remove the original functionality.
Fixes: #____
- ❓ …
=> [2.26.x] New preferences storage solution

catalog/rest/catalog-rest-endpoint/src/main/java/org/codice/ddf/endpoints/rest/CatalogService.java, catalog/rest/catalog-rest-endpoint/src/main/java/org/codice/ddf/endpoints/rest/RESTEndpoint.java, catalog/rest/catalog-rest-endpoint/src/test/java/org/codice/ddf/rest/service/impl/CatalogServiceTest.java
Fixes a bug where doing a POST or PUT on the REST endpoint sends a closed stream to the catalog framework if the file is larger than 10k bytes. Reduced the number of `ServletFileUpload` objects created by the REST endpoint.
Fixes: #____ …
=> [3.x] Fix REST endpoint file upload using a closed stream

catalog/catalog-app/pom.xml, catalog/catalog-app/src/main/resources/features.xml
Add back metacard validation and definition parser to catalog features.
Fixes: #____
=> [3.x] Fix metacard validation and defintion parser features

catalog/solr/catalog-solr-core/src/main/java/ddf/catalog/source/solr/ConfigurationStore.java, distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/AbstractIntegrationTest.java, platform/solr/solr-factory-impl/src/main/java/org/codice/solr/factory/impl/ConfigurationStore.java
Fixed core itest failing due to a race when reading Solr force commit configuration on startup.
Fixes: #____
=> [3.x] Fix itest force solr commit race

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/DeleteOperations.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/UpdateOperations.java
Pass operation properties to populateMetacards
Make sure system behavior seems OK. There isn't a specific test.
Fixes: #____
=> [2.26.x] Pass operation properties to populateMetacards

platform/solr/solr-query/src/main/java/org/codice/solr/query/SolrQueryFilterVisitor.java
Adds a filter visitor to handle a null filter in the persistent store.
@derekwilhelm 
@jlcsmith 
@glenhein 
@jlcsmith
Fixes: #____
=> [2.26.x] Add null filter visitor

catalog/transformer/catalog-transformer-rtf/src/main/java/ddf/catalog/transformer/output/rtf/model/ExportCategory.java, catalog/transformer/catalog-transformer-rtf/src/test/java/ddf/catalog/transformer/output/rtf/BaseTestConfiguration.java
backport PR: https://github.com/codice/ddf/pull/6767
=> [2.26.30.x] Backport RTF multivalue fix

catalog/rest/catalog-rest-service/src/main/java/org/codice/ddf/rest/service/AbstractCatalogService.java, distribution/docs/src/main/resources/content/_integrating/_endpoints/catalog-rest-endpoint.adoc, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFederation.java
Backport of PR #6771 
@jlcsmith
@codice/ui 
@glenhein
@jlcsmith
See steps in PR #6771 
Fixes: #____
=> [2.26.30.x] Provide better transform failure message

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/QueryOperations.java, catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/impl/operations/QueryOperationsTest.java
Fixes an issue in the solr query logging statements. If the trace id was null, it would throw a null pointer exception while logging and bail from the query. Only happened when trace level executed the logging statements (DEBUG or TRACE).
@jlcsmith 
@glenhein 
@jlcsmith
@glenhein 
Junit tests added
- Start up ddf
- set logging level to TRACE for ddf.catalog.impl.operations
- log in the karaf console
- execute the "catalog:latest" command
- observer that trace-id has been set to a NIL UUID (all zeroes), trace metrics are generated, and no null ptr exception is thrown
Fixes: #____
- ✏️ (Pencil) …
=> [2.26.x] Fix null ptr issue with query logging

platform/preferences/preferences-impl/src/main/java/org/codice/ddf/preferences/impl/PreferencesImpl.java
To increase visibility into ddf-preferences metacard creation/ updates.
Fixes: #____
=> [2.26.x] Log ddf-preferences metacard create and update

distribution/docker/solr-docker/README.md, platform/persistence/platform-persistence-commands/src/main/java/org/codice/ddf/persistence/commands/AbstractStoreCommand.java, platform/persistence/platform-persistence-core-api/src/main/java/org/codice/ddf/persistence/PersistentStore.java
Remove old preference store.
Build with a downstream project and make sure everything starts up as expected.
Fixes: #____
=> [2.26.x] Remove traces of old preference store

catalog/solr/catalog-solr-core/src/main/java/ddf/catalog/source/solr/SolrMetacardClientImpl.java
Adds an option to skip a real time get. 
If you've attempted to do a faceted query and the query qualifies for a real time get, you don't receive a facet based response but just the respective documents (from the update log). https://solr.apache.org/guide/7_2/realtime-get.html
This prevents real time for faceted and allows the user to opt out of real time get with a property. 
@derekwilhelm 
@pvargas 
@alexabird 
Fixes: #____ …
=> [2.26.x] Skip real time get option for faceted queries

catalog/solr/catalog-solr-core/src/main/java/ddf/catalog/source/solr/DynamicSchemaResolver.java, catalog/solr/catalog-solr-core/src/main/java/ddf/catalog/source/solr/SolrFilterDelegate.java, catalog/solr/catalog-solr-core/src/test/java/ddf/catalog/source/solr/DynamicSchemaResolverTest.java, catalog/solr/catalog-solr-core/src/test/java/ddf/catalog/source/solr/provider/SolrProviderSpatial.java
Make anyGeo configurable.
Note: @pklinef thought there might be other areas of the code that needed to be changed, but was not specific. If you think of something, please let me know.
Build with a downstream project that adds a geometry attribute.
After unzip, add the following to etc/custom.system.properties after adjusting it for the name of the geometry attribute:
solr.query.anygeo.fields=location,new.geometry.attribute
Finish installing.
Using the UI, test every type of geo query. You will need to ingest an item and change its geometry attribute values to test every possible geo query.
Fixes: #____ …
=> [2.26.x] Make anyGeo configurable

platform/security/security-jaas-ldap/src/main/java/ddf/ldap/ldaplogin/SslLdapLoginModule.java
Audit logs successful LDAP authentication
@alexabird 
@rececoffin 
@glenhein 
Fixes: #____
=> [2.26.x] Audit log successful LDAP authentication

catalog/core/catalog-core-api/src/main/java/ddf/catalog/Constants.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/federation/impl/TimedSource.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/QueryOperations.java, catalog/solr/catalog-solr-core/src/main/java/ddf/catalog/source/solr/SolrCatalogProviderImpl.java, distribution/ddf-common/src/main/resources/etc/log4j2.xml, distribution/ddf-common/src/main/resources/etc/org.ops4j.pax.logging.cfg
Separates query metrics into own log file and removes a few redundant logs. This new log file will be `query_metrics.log`.
@jlcsmith
@codice/solr
@jlcsmith 
1. Start DDF
2. Run `log:set DEBUG queryLogger`
3. Run a few queries
4. Verify the query metrics were logged in `query_metrics.log` and not in `ddf.log`
Refer to #6763 for original metrics changes.
Fixes: #____ …
=> [2.26.x] Query metrics update

platform/persistence/platform-persistence-core-impl/src/test/java/org/codice/ddf/persistence/internal/PersistentStoreImplTest.java, platform/solr/solr-query/pom.xml, platform/solr/solr-query/src/main/java/org/codice/solr/query/SolrQueryFilterVisitor.java, platform/solr/solr-query/src/test/java/org/codice/solr/query/SolrQueryFilterVisitorTest.java
Add LIKE support to SolrQueryFilterVisitor.
There is no direct way in DDF to test. However, there is a downstream project that will use this. That project can be used for testing.
Fixes: #____ …
=> [2.26.x] Add LIKE support to SolrQueryFilterVisitor

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/federation/impl/SortedFederationStrategy.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/federation/impl/TimedSource.java
Similar to #6784, when performing a query, the QueryOperations hands off the source execution of the queries to the SortedFederationStrategy. This class uses an ExecutorService to run the source queries in parallel within a thread pool in the SortedQueryMonitor class using the TimedSource class. Since these run in separate threads, they don't share the same thread context as the original query. This means that things like trace-id in the thread context are lost. Furthermore, if any of the Source implementations perform an action that sets or binds a user subject to the thread, then the thread in the thread pool will now have that user defined in its thread context going forward, including when it gets reused. If the source is simply trying to perform a user validation, then it could fail …
=> [2.26.x] Ensure TimedSource uses query ThreadContext

catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/util/impl/ResultIterable.java, catalog/core/catalog-core-impl/pubsub/pom.xml, catalog/core/catalog-core-urlresourcereader/pom.xml, catalog/spatial/ogc/spatial-ogc-urlresourcereader/pom.xml, catalog/transformer/catalog-transformer-resource/pom.xml, catalog/transformer/catalog-transformer-xml/pom.xml
ResultIterable can return inconsistent results when paging through Solr results and the sort-by is  not used or when the sort-by field contains identical values. This PR sets the default sort-by to be by the metacard ID.
Fixes: #____ …
=> [2.26.x] Add default sort-by for ResultIterable

catalog/catalog-app/pom.xml, catalog/catalog-app/src/main/resources/features.xml, catalog/core/catalog-core-api/src/main/java/ddf/catalog/data/RequiredAttributes.java, catalog/core/catalog-core-api/src/main/java/ddf/catalog/data/RequiredAttributesRegistry.java, catalog/core/catalog-core-definitionparser/src/main/java/ddf/catalog/definition/impl/DefinitionParser.java, catalog/core/catalog-core-definitionparser/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/core/catalog-core-definitionparser/src/test/groovy/ddf/catalog/definition/impl/DefinitionParserSpec.groovy, catalog/core/catalog-core-requiredattributes/pom.xml, catalog/core/catalog-core-requiredattributes/src/main/java/ddf/catalog/data/requiredattributes/RequiredAttributesRegistryImpl.java, catalog/core/catalog-core-requiredattributes/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/core/catalog-core-requiredattributes/src/test/java/ddf/catalog/data/requiredattributes/RequiredAttributesRegistryTest.java, catalog/core/catalog-core-validator/src/main/java/ddf/catalog/validation/impl/validator/RequiredAttributesMetacardValidator.java, catalog/core/pom.xml
Adds RequiredAttributesRegistry, which contains a map of metacard types to a list of the attributes that are required for that type.
Fixes: #____
=> [2.26.x] Add support for required attributes

Jenkinsfile, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/ContentDirectoryMonitor.java, catalog/opensearch/catalog-opensearch-endpoint/pom.xml, catalog/opensearch/catalog-opensearch-endpoint/src/test/groovy/org/codice/ddf/opensearch/endpoint/OpenSearchEndpointSpec.groovy, catalog/schematron/catalog-schematron-plugin/src/test/java/ddf/services/schematron/SchematronValidationServiceTest.java, catalog/solr/catalog-solr-commands/src/test/java/org/codice/ddf/commands/solr/CacheCommandTest.java, catalog/solr/catalog-solr-commands/src/test/java/org/codice/ddf/commands/solr/ReindexCommandTest.java, catalog/solr/catalog-solr-commands/src/test/java/org/codice/ddf/commands/solr/SolrCommandTest.java, catalog/spatial/geocoding/spatial-geocoding-plugin/pom.xml, distribution/ddf-common/src/main/resources-filtered/etc/custom.properties, distribution/ddf-common/src/main/resources/etc/org.apache.karaf.log.cfg, distribution/docker/ddf-docker/pom.xml, distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/catalog/CatalogTestCommons.java, distribution/test/itests/test-itests-ddf/pom.xml, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestCatalog.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestFederation.java, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/catalog/TestSpatial.java, platform/admin/core/admin-core-appservice/src/test/java/org/codice/ddf/admin/application/service/command/AbstractProfileCommandTest.java, platform/admin/core/admin-core-appservice/src/test/java/org/codice/ddf/admin/application/service/command/ProfileInstallCommandTest.java, platform/admin/core/admin-core-appservice/src/test/java/org/codice/ddf/admin/application/service/command/ProfileListCommandTest.java, platform/resource-bundle-locator/src/test/java/ddf/platform/resource/bundle/locator/ResourceBundleLocatorImplTest.java, platform/security/core/security-core-impl/src/test/java/ddf/security/samlp/impl/SPMetadataParserTest.java, platform/security/handler/security-handler-oauth/pom.xml, platform/security/handler/security-handler-oidc/pom.xml, platform/security/handler/security-handler-pki/pom.xml, platform/security/handler/security-handler-saml/src/test/java/org/codice/ddf/security/idp/client/AssertionConsumerServiceTest.java, platform/security/handler/security-handler-saml/src/test/java/org/codice/ddf/security/idp/client/IdpHandlerTest.java, platform/security/handler/security-handler-saml/src/test/java/org/codice/ddf/security/idp/client/IdpMetadataTest.java, platform/security/security-oidc-bundle/pom.xml, pom.xml
Updates the camel version to fix CDM. 
Fixed several of the csw itests that were broken on the 2.29.x branch and ignored ones not easily fixed. Follow up ticket is https://github.com/codice/ddf/issues/6798
Updated java version to 17
Depends on https://github.com/codice/docker-ddf-base/pull/4
Good build …
=> Java 17 and Camel Update

catalog/rest/catalog-rest-api/src/main/java/org/codice/ddf/rest/api/CatalogService.java, catalog/rest/catalog-rest-service/src/main/java/org/codice/ddf/rest/service/AbstractCatalogService.java, platform/security/filter/security-filter-csrf/src/main/resources/OSGI-INF/blueprint/blueprint.xml
Adds a properties parameter to catalog service updates. 
Exposes `services/internal/catalog/?$=PUT` for CSRF (not ideal solution but quite a bit of refactoring needs to be done to move the endpoint/catalog service away from jaxrs) for updates. 
Fixes: #____ …
=> [2.26.x] Add properties parameter for updates

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/UpdateOperations.java, distribution/ddf-common/src/main/resources/etc/forms/readme.md
=> [2.26.x] Use new properties object so version flag isn't set on response 

catalog/core/catalog-core-api/src/main/java/ddf/catalog/Constants.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/federation/impl/SortedFederationStrategy.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/federation/impl/TimedSource.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/QueryOperations.java, catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/impl/CatalogFrameworkImplTest.java, catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/impl/operations/QueryOperationsTest.java, catalog/solr/catalog-solr-core/src/main/java/ddf/catalog/source/solr/DynamicSchemaResolver.java, catalog/solr/catalog-solr-core/src/main/java/ddf/catalog/source/solr/SolrCatalogProviderImpl.java, catalog/solr/catalog-solr-core/src/main/java/ddf/catalog/source/solr/SolrFilterDelegate.java, catalog/solr/catalog-solr-core/src/main/java/ddf/catalog/source/solr/SolrMetacardClientImpl.java, catalog/solr/catalog-solr-core/src/test/java/ddf/catalog/source/solr/DynamicSchemaResolverTest.java, catalog/solr/catalog-solr-core/src/test/java/ddf/catalog/source/solr/provider/SolrProviderSpatial.java, distribution/ddf-common/src/main/resources/etc/log4j2.xml, distribution/ddf-common/src/main/resources/etc/org.ops4j.pax.logging.cfg, platform/persistence/platform-persistence-core-impl/src/test/java/org/codice/ddf/persistence/internal/PersistentStoreImplTest.java, platform/solr/solr-query/pom.xml, platform/solr/solr-query/src/main/java/org/codice/solr/query/SolrQueryFilterVisitor.java, platform/solr/solr-query/src/test/java/org/codice/solr/query/SolrQueryFilterVisitorTest.java
Solr and query logging related PRs forward port from 2.26.x
DDF-6437 - Correctly translate NOT query operator https://github.com/codice/ddf/commit/afce6a65ceead5cbd6542b57a1d3e73d13a9f125
https://github.com/codice/ddf/pull/6438
Revert "Make anyGeo configurable https://github.com/codice/ddf/commit/c9b77e8561f1fe65d0dbc15c1dfe06ad90613e0d
https://github.com/codice/ddf/pull/6780[)"]
Revert "Add null filter visitor 
https://github.com/codice/ddf/commit/13aed1e3ec952e1f6ec43ff3a3aba4be40744da3
https://github.com/codice/ddf/pull/6768
Revert "DDF-6421 - Enable configuration of solr highlight parameters
https://github.com/codice/ddf/commit/60a75dc1bb95e7a3a0dd2c3c8227f7815260b54a
https://github.com/codice/ddf/pull/6422
Revert "Add missing Jetty imports to solr-dependencies …
=> [2.29.x] Forward port SOLR 2.26.x changes to 2.29.x

catalog/common/catalog-common-video-thumbnail/pom.xml, catalog/core/catalog-core-api/src/main/java/ddf/catalog/plugin/SourcePlugin.java, catalog/core/catalog-core-metacardgroomerplugin/src/main/java/ddf/catalog/plugin/groomer/metacard/StandardMetacardGroomerPlugin.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/FrameworkProperties.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/SourceOperations.java, catalog/core/catalog-core-standardframework/src/main/resources/OSGI-INF/blueprint/frameworkprops.xml, catalog/core/catalog-core-standardframework/src/main/resources/OSGI-INF/blueprint/plugins.xml, catalog/rest/catalog-rest-api/src/main/java/org/codice/ddf/rest/api/CatalogService.java, catalog/rest/catalog-rest-api/src/main/java/org/codice/ddf/rest/api/CatalogServiceException.java, catalog/rest/catalog-rest-endpoint/pom.xml, catalog/rest/catalog-rest-endpoint/src/main/java/org/codice/ddf/endpoints/rest/RESTEndpoint.java, catalog/rest/catalog-rest-endpoint/src/main/java/org/codice/ddf/endpoints/rest/RESTService.java, catalog/rest/catalog-rest-endpoint/src/test/java/org/codice/ddf/endpoints/rest/RESTEndpointTest.java, catalog/rest/catalog-rest-endpoint/src/test/java/org/codice/ddf/endpoints/rest/it/RestEndpointIT.java, catalog/rest/catalog-rest-service-impl/src/main/java/org/codice/ddf/rest/service/impl/CatalogServiceImpl.java, catalog/rest/catalog-rest-service-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/rest/catalog-rest-service-impl/src/test/java/org/codice/ddf/rest/service/impl/CatalogServiceImplTest.java, catalog/rest/catalog-rest-service/pom.xml, catalog/rest/catalog-rest-service/src/main/java/org/codice/ddf/rest/service/AbstractCatalogService.java, platform/preferences/preferences-impl/src/main/java/org/codice/ddf/preferences/impl/PreferencesImpl.java, platform/preferences/preferences-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml, platform/util/platform-util-uuidgenerator/util-uuidgenerator-api/src/main/java/org/codice/ddf/platform/util/uuidgenerator/UuidGenerator.java, platform/util/platform-util-uuidgenerator/util-uuidgenerator-impl/src/main/java/org/codice/ddf/platform/util/uuidgenerator/impl/UuidGeneratorImpl.java, platform/util/platform-util-uuidgenerator/util-uuidgenerator-impl/src/test/java/org/codice/ddf/platform/util/uuidgenerator/impl/UuidGeneratorImplTest.java
(cherry picked from commit 3e6ac7a0c9a9f6e7ae41f988fdc0471a02a57c41)
Fixes: #____
=> [2.29.x] Forward port new services from 2.26.x

catalog/transformer/catalog-transformer-tika-input/src/test/java/ddf/catalog/transformer/input/tika/TikaInputTransformerTest.java
DDF-6554 Handles epoch dates in tika transformer
https://github.com/codice/ddf/commit/f2bc29dadb98acc4c60b51627ccf753c840a1d49
https://github.com/codice/ddf/pull/6555
DDF-6568 - Add Exiftool and configurable mappings to Tika InputTransformer
https://github.com/codice/ddf/commit/d6a687536bb03c40805a5149cba74fcac8ee163b
https://github.com/codice/ddf/pull/6569
Add null check for attribute descriptor
https://github.com/codice/ddf/commit/c72889b2fcbf09668ea664ec58afd73b8c5f945b
https://github.com/codice/ddf/pull/6579
Upgrade Tika to 1.26
https://github.com/codice/ddf/commit/ac2a302ab2469b6535e3f3c7f3d37d134374abf4
https://github.com/codice/ddf/pull/6730
Fixes: #____ …
=> [2.29.x] Forward ports 2.26 tika changes

catalog/catalog-app/pom.xml, catalog/catalog-app/src/main/resources/features.xml, catalog/core/catalog-core-standardframework/pom.xml, distribution/ddf-common/src/main/resources-filtered/etc/custom.system.properties, distribution/docker/solr-docker/README.md, features/solr/pom.xml, features/solr/src/main/feature/feature.xml, platform/persistence/platform-persistence-commands/src/main/java/org/codice/ddf/persistence/commands/AbstractStoreCommand.java, platform/persistence/platform-persistence-core-api/src/main/java/org/codice/ddf/persistence/PersistentStore.java, platform/pom.xml, platform/preferences/pom.xml, platform/preferences/preferences-api/pom.xml, platform/preferences/preferences-api/src/main/java/org/codice/ddf/preferences/DefaultPreferencesSupplier.java, platform/preferences/preferences-api/src/main/java/org/codice/ddf/preferences/PostRetrievalPlugin.java, platform/preferences/preferences-api/src/main/java/org/codice/ddf/preferences/Preferences.java, platform/preferences/preferences-api/src/main/java/org/codice/ddf/preferences/PreferencesException.java, platform/preferences/preferences-impl/pom.xml, platform/preferences/preferences-impl/src/main/java/org/codice/ddf/preferences/impl/PreferencesMetacardType.java
Remove traces of old preference store 
https://github.com/codice/ddf/commit/60dfd8779899fc2511128787f5e5dc88a367da5e
https://github.com/codice/ddf/pull/6776
New preferences storage solution 
https://github.com/codice/ddf/commit/0deef5b6d9e0ba2428c1b037d469ae766425837f
https://github.com/codice/ddf/pull/6732
Log ddf-preferences metacard create and update
https://github.com/codice/ddf/commit/4f334e34ed48889c137950e1d88351f4cac9a17a
https://github.com/codice/ddf/pull/6773
Fixes: #____ …
=> [2.29.x] Forward port 2.26 Preferences

catalog/core/catalog-core-camelcomponent/pom.xml, catalog/core/catalog-core-camelcomponent/src/main/java/ddf/camel/component/catalog/CatalogComponent.java, catalog/core/catalog-core-camelcomponent/src/main/java/ddf/camel/component/catalog/CatalogEndpoint.java, catalog/core/catalog-core-camelcomponent/src/main/java/ddf/camel/component/catalog/framework/FrameworkProducer.java, catalog/core/catalog-core-camelcomponent/src/main/java/ddf/camel/component/catalog/framework/IngestTimeoutException.java, catalog/core/catalog-core-camelcomponent/src/main/java/ddf/camel/component/catalog/transformer/TransformerProducer.java, catalog/core/catalog-core-camelcomponent/src/main/java/ddf/camel/component/catalog/transformer/TransformerTimeoutException.java, catalog/core/catalog-core-camelcomponent/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/core/catalog-core-camelcomponent/src/test/java/ddf/camel/component/catalog/framework/FrameworkProducerTest.java, catalog/core/catalog-core-camelcomponent/src/test/java/ddf/camel/component/catalog/inputtransformer/InputTransformerProducerTest.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/AsyncFileAlterationObserver.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/ContentDirectoryMonitor.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/DurableFileAlterationListener.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/DurableFileSystemFileConsumer.java, catalog/core/catalog-core-directorymonitor/src/main/java/org/codice/ddf/catalog/content/monitor/synchronizations/CompletionSynchronization.java, catalog/core/catalog-core-directorymonitor/src/test/java/org/codice/ddf/catalog/content/monitor/AsyncFileAlterationObserverTest.java, catalog/core/catalog-core-directorymonitor/src/test/java/org/codice/ddf/catalog/content/monitor/ContentDirectoryMonitorTest.java, distribution/ddf-common/src/main/resources/security/configurations.policy
Port CDM updates to 2.26.x branch
https://github.com/codice/ddf/commit/9dddd93d0cb7c9692f99ea6d098235ea12c3a724
https://github.com/codice/ddf/pull/6434
CDM fix for binding system subject to thread
https://github.com/codice/ddf/commit/d1da443675cd6ccbab44b429d1757c6889c26edb
https://github.com/codice/ddf/pull/6547
Fixes: #____ …
=> [2.29.x] Forward ports from 2.26 for content directory monitor

catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/pom.xml, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsFilterDelegate.java, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsSource.java, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/resources/OSGI-INF/metatype/metatype.xml, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsFilterDelegateTest.java, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsSourceTest.java, catalog/spatial/wfs/spatial-wfs-common/pom.xml, catalog/spatial/wfs/spatial-wfs-common/src/main/java/org/codice/ddf/spatial/ogc/wfs/catalog/common/AbstractWfsSource.java
=> [2.29.x] Forward Port WFS 2.26.x changes

catalog/core/catalog-core-api-impl/src/main/java/ddf/catalog/util/impl/ResultIterable.java, catalog/core/catalog-core-commands/pom.xml, catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/CqlCommands.java, catalog/core/catalog-core-commons/src/main/java/ddf/catalog/filter/delegate/TagsFilterDelegate.java, catalog/core/catalog-core-impl/filter-proxy/src/test/java/ddf/catalog/filter/delegate/TagsFilterDelegateTest.java, catalog/core/catalog-core-impl/pubsub/pom.xml, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/federation/impl/SortedQueryMonitor.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/federation/impl/SortedQueryMonitorFactory.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/DeleteOperations.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/UpdateOperations.java, catalog/core/catalog-core-standardframework/src/test/java/ddf/catalog/federation/impl/SortedQueryMonitorTest.java, catalog/core/catalog-core-urlresourcereader/pom.xml, catalog/spatial/ogc/spatial-ogc-urlresourcereader/pom.xml, catalog/transformer/catalog-transformer-resource/pom.xml, catalog/transformer/catalog-transformer-xml/pom.xml, distribution/ddf/pom.xml, distribution/pom.xml
(cherry picked from commit d2cb53dcb7863057a99a8654ee5b644710cee4c9)
"DDF-6360 Remove reference to deleted libs-bundles-opensaml artifact https://github.com/codice/ddf/commit/2f2d2b9aa81f5e20995810925d71215f392c6659
https://github.com/codice/ddf/pull/6403
"Fix email client not finding IMAPProvider (]https://github.com/codice/ddf/commit/c380ef9734342e567b631650d0d17d02f299ad96)
https://github.com/codice/ddf/pull/6427
"commenting out docker project for release"https://github.com/codice/ddf/commit/85a740c6fd77d636571e5329c0a553e14be9cb3d)
"Add missing features to the distribution https://github.com/codice/ddf/commit/5ea99d2c7f5d9aa5885331345e765c9462c0da69)
https://github.com/codice/ddf/pull/6431
"Fix printErrorMessage when executeWithSubject fails in SubjectCommands …
=> [2.29.x] Forward ports from 2.26 (miscellaneous) 

catalog/catalog-app/pom.xml, catalog/catalog-app/src/main/resources/features.xml, catalog/core/catalog-core-api/src/main/java/ddf/catalog/data/RequiredAttributes.java, catalog/core/catalog-core-api/src/main/java/ddf/catalog/data/RequiredAttributesRegistry.java, catalog/core/catalog-core-commons/NOTICE, catalog/core/catalog-core-commons/src/main/java/ddf/util/Antimeridian.java, catalog/core/catalog-core-commons/src/test/java/ddf/util/AntimeridianTest.java, catalog/core/catalog-core-definitionparser/src/main/java/ddf/catalog/definition/impl/DefinitionParser.java, catalog/core/catalog-core-definitionparser/src/test/groovy/ddf/catalog/definition/impl/DefinitionParserSpec.groovy, catalog/core/catalog-core-impl/filter-proxy/src/main/java/ddf/catalog/filter/proxy/adapter/GeotoolsFilterAdapterImpl.java, catalog/core/catalog-core-requiredattributes/pom.xml, catalog/core/catalog-core-requiredattributes/src/main/java/ddf/catalog/data/requiredattributes/RequiredAttributesRegistryImpl.java, catalog/core/catalog-core-requiredattributes/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/core/catalog-core-requiredattributes/src/test/java/ddf/catalog/data/requiredattributes/RequiredAttributesRegistryTest.java, catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/UpdateOperations.java, catalog/core/catalog-core-validator/src/main/java/ddf/catalog/validation/impl/validator/RequiredAttributesMetacardValidator.java, catalog/core/pom.xml, catalog/rest/catalog-rest-api/src/main/java/org/codice/ddf/rest/api/CatalogService.java, catalog/rest/catalog-rest-service/src/main/java/org/codice/ddf/rest/service/AbstractCatalogService.java, catalog/solr/catalog-solr-core/src/main/java/ddf/catalog/source/solr/SolrFilterDelegate.java, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/pom.xml, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsFilterDelegate.java, catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v110/catalog/source/WfsFilterDelegateTest.java, platform/security/filter/security-filter-csrf/src/main/resources/OSGI-INF/blueprint/blueprint.xml, pom.xml
Use new properties object so version flag isn't set on response (https://github.com/codice/ddf/pull/6799[)](https://github.com/codice/ddf/commit/d2db3e478e37b92b6da75bc66392c44f70d18c92)
Split Geo Shapes That Cross The Antimeridian (https://github.com/codice/ddf/pull/6800[)](https://github.com/codice/ddf/commit/25a8eb9f7c2d1637d40985fdc4250c7df4adabb7)
Add properties parameter for updates (https://github.com/codice/ddf/pull/6796[)](https://github.com/codice/ddf/commit/6236c077e86bc5db2c2324d1d46119a7f61ce973)
[Add support for required attributes (](https://github.com/codice/ddf/commit/be5e3cd2d00cd4b06accb3859dde358bb7f4d01e)https://github.com/codice/ddf/pull/6794[)](https://github.com/codice/ddf/commit/be5e3cd2d00cd4b06accb3859dde358bb7f4d01e)
Fixes: #____ …
=> [2.29.x] More 2.26.x forward ports 

catalog/plugin/catalog-plugin-metacardbackup-filestorage/pom.xml, catalog/plugin/catalog-plugin-metacardbackup-s3storage/pom.xml, libs/klv/pom.xml, pom.xml
See title
@birda 
@derekwilhelm 
@glenhein 
@derekwilhelm 
@glenhein 
=> Upgrades handlebars, commons-text, and commons-lang3

pom.xml, thirdparty/restito/pom.xml
Upgrades restito to most recent version.  Also some minor version bumps of other libraries.
@alexabird @glenhein 
@alexabird @glenhein 
Fixes: #____ …
=> [2.29.x] Upgrade restito library

catalog/pom.xml, platform/security/pom.xml, platform/security/servlet/security-servlet-web-socket-api/pom.xml, pom.xml
Upgrades xalan and websockets dependencies
@glenhein @derekwilhelm  
@glenhein @derekwilhelm 
Fixes: #____
=> [2.29.x] Upgrade xalan and websockets

pom.xml
Upgrades Guava to 33.4 (latest)
@glenhein @alexabird 
@glenhein @alexabird 
Passing CI
Fixes: #____
=> [2.29.x] Upgrades Guava to 33.4 (latest)

dependency-check-maven-config.xml
=> Suppress CVEs for mxparser as false positives

catalog/core/catalog-core-camelcomponent/src/test/java/ddf/camel/component/catalog/CatalogComponentFrameworkTest.java, catalog/security/catalog-security-policyplugin/src/test/java/org/codice/ddf/catalog/security/CatalogPolicyTest.java, platform/security/claims/security-claims-ldap/pom.xml, pom.xml
upgrade spring core to 6.1.14 and ldap to 3.2.8
Fixes: #____
=> [2.29.x] upgrade spring core to 6.1.14 and ldap to 3.2.8

catalog/core/catalog-core-directorymonitor/pom.xml, catalog/rest/catalog-rest-endpoint/pom.xml, distribution/ddf-catalog/pom.xml, distribution/ddf/pom.xml, features/admin/pom.xml, features/apps/pom.xml, features/security/pom.xml, features/utilities/pom.xml
exclude activemq broker to eliminate a cve
FYI: I built and installed via the admin ui without any issues.
Fixes: #____
=> [2.29.x] exclude activemq broker to eliminate a cve

dependency-check-maven-config.xml
suppress false postives for CVE-2017-5929 (logback-json-core, logback-jackson, ...).
Fixes: #____
=> [2.29.x] suppress false postives for CVE-2017-5929

catalog/plugin/catalog-plugin-oauth/pom.xml, distribution/test/itests/test-itests-ddf/src/test/java/ddf/test/itests/platform/TestOidc.java, platform/security/handler/security-handler-api/src/main/java/org/codice/ddf/security/handler/api/OidcHandlerConfiguration.java, platform/security/handler/security-handler-oauth/src/main/java/org/codice/ddf/security/handler/oauth/OAuthHandler.java, platform/security/handler/security-handler-oidc/src/main/java/org/codice/ddf/security/handler/oidc/OidcCallbackEndpoint.java, platform/security/handler/security-handler-oidc/src/main/java/org/codice/ddf/security/handler/oidc/OidcHandler.java, platform/security/handler/security-handler-oidc/src/main/java/org/codice/ddf/security/handler/oidc/OidcHandlerConfigurationImpl.java, platform/security/handler/security-handler-oidc/src/main/java/org/codice/ddf/security/handler/oidc/OidcLogoutActionProvider.java, platform/security/handler/security-handler-oidc/src/test/java/org/codice/ddf/security/handler/oidc/OidcCallbackEndpointTest.java, platform/security/handler/security-handler-oidc/src/test/java/org/codice/ddf/security/handler/oidc/OidcHandlerConfigurationImplTest.java, platform/security/handler/security-handler-oidc/src/test/java/org/codice/ddf/security/handler/oidc/OidcHandlerTest.java, platform/security/handler/security-handler-oidc/src/test/java/org/codice/ddf/security/handler/oidc/OidcLogoutActionProviderTest.java, platform/security/realm/security-realm-oidc/src/main/java/org/codice/ddf/security/oidc/realm/CustomOidcProfileCreator.java, platform/security/realm/security-realm-oidc/src/main/java/org/codice/ddf/security/oidc/realm/OidcRealm.java, platform/security/realm/security-realm-oidc/src/test/java/org/codice/ddf/security/oidc/realm/OidcRealmTest.java, platform/security/security-oidc-bundle/pom.xml, platform/security/security-oidc-bundle/src/main/java/org/codice/ddf/security/oidc/validator/OidcTokenValidator.java, platform/security/security-oidc-bundle/src/test/java/org/codice/ddf/security/oidc/validator/OidcTokenValidatorTest.java, pom.xml
upgrade pac4j to 5.0.0
Fixes: #____
=> [2.29.x] upgrade pac4j to 5.0.0

distribution/ddf-catalog/pom.xml, distribution/kernel/pom.xml, platform/osgi/platform-osgi-configadmin/pom.xml, pom.xml
Upgrade tink and protobuf
Fixes: #____
=> [2.29.x] Upgrade tink and protobuf

catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/operations/QueryOperations.java
=> Fixed HTML escaping issue when converting query metrics to json object

dependency-check-maven-config.xml, platform/security/claims/security-claims-ldap/pom.xml
bump spring-ldap-core and suppress false positive cves
Fixes: #____
=> [2.29.x] bump spring-ldap-core and suppress false positive cves

catalog/solr/catalog-solr-commands/pom.xml, catalog/solr/catalog-solr-commands/src/main/java/org/codice/ddf/commands/solr/BackupCommand.java, catalog/solr/catalog-solr-commands/src/main/java/org/codice/ddf/commands/solr/RestoreCommand.java, catalog/solr/catalog-solr-commands/src/test/java/org/codice/ddf/commands/solr/RestoreCommandTest.java, distribution/solr-distro/pom.xml, pom.xml
Make necessary upgrades for Solr 9.3.0. 
Note: Solr's processAsync Response doesn't have the requestid attached to it (although the API says it should). Generated the UUID to submit with the request instead.
@zkirksey  
@glenhein 
@codice/solr 
@jlcsmith 
@derekwilhelm 
Fixes: #____ …
=> [2.29.x] Upgrade to Solr 9.3.0

catalog/common/catalog-common-video-thumbnail-impl/pom.xml, catalog/common/catalog-common-video-thumbnail/pom.xml, platform/osgi/platform-osgi-conditions/pom.xml, platform/osgi/platform-osgi-condpermadmin/pom.xml, platform/osgi/platform-osgi-configadmin/pom.xml, platform/osgi/platform-osgi-internal-api/pom.xml, pom.xml
upgrade osgi to 7.0.0
Fixes: #____
=> [2.29.x] upgrade osgi to 7.0.0

catalog/solr/catalog-solr-commands/src/test/java/org/codice/ddf/commands/solr/BackupCommandTest.java, catalog/solr/catalog-solr-commands/src/test/java/org/codice/ddf/commands/solr/RestoreCommandTest.java, catalog/solr/catalog-solr-commands/src/test/java/org/codice/ddf/commands/solr/SolrCommandTest.java
Fixes an issue with CI where tests can run in a different order that fails.
@middlets719 
@codice/solr 
Fixes: #____
=> Fix Solr command tests

catalog/catalog-app/src/main/resources/features.xml, catalog/core/catalog-core-directorymonitor/pom.xml, platform/security/pom.xml, pom.xml
Upgrade to apache CXF 3.5.10
@derekwilhelm 
@zkirksey 
@glenhein 
@jlcsmith 
Fixes: #____
=> Upgrade to apache CXF 3.5.10

catalog/solr/catalog-solr-commands/src/test/java/org/codice/ddf/commands/solr/BackupCommandTest.java, catalog/solr/catalog-solr-commands/src/test/java/org/codice/ddf/commands/solr/RestoreCommandTest.java, catalog/solr/catalog-solr-commands/src/test/java/org/codice/ddf/commands/solr/SolrCommandTest.java
Backport of
- https://github.com/codice/ddf/pull/6862
=> [2.29.x] Fix Solr command tests

pom.xml
see title
@derekwilhelm 
@alexabird 
@derekwilhelm 
@alexabird 
Fixes: #____
=> Reverts 2.29.x branch to j17 compiler target version

catalog/plugin/catalog-plugin-oauth/pom.xml, dependency-check-maven-config.xml, platform/security/core/security-core-impl/pom.xml, platform/security/core/security-core-services/pom.xml, platform/security/handler/security-handler-api/pom.xml, platform/security/handler/security-handler-impl/pom.xml, platform/security/handler/security-handler-oauth/pom.xml, platform/security/handler/security-handler-oidc/pom.xml, platform/security/realm/security-realm-oidc/pom.xml, platform/security/security-oidc-bundle/pom.xml
=> [2.29.x] Suppressing CVEs caused by smart library

dependency-check-maven-config.xml
Suppress Apache Johnzon related CVEs
Fixes: #____
=> [2.29.x] Suppress Apache Johnzon related CVEs

dependency-check-maven-config.xml
Suppress quartz CVE. 
Fixes: #____
=> [2.29.x] Suppress quartz CVE

distribution/ddf-common/src/main/resources/bin/ddf, distribution/ddf-common/src/main/resources/bin/ddf.bat
Ensure extra_java_opts preserved for downstream projects
Fixes: #____
=> [2.29.x] Preserve java exports

distribution/ddf-common/src/main/resources/bin/ddf, distribution/ddf-common/src/main/resources/bin/ddf.bat
Backport 
- https://github.com/codice/ddf/pull/6882
=> [2.29.9.x] Preserve java opts

catalog/core/catalog-core-impl/filter-proxy/pom.xml, catalog/core/catalog-core-impl/filter-proxy/src/main/java/ddf/catalog/filter/proxy/GeotoolsPluginLoader.java
Forward port of https://github.com/codice/ddf/pull/6886
@alexabird 
@derekwilhelm 
@codice/data 
@alexabird 
@derekwilhelm 
Fixes: #____
=> [2.29.x] Adds geotools support for csv and shp files

catalog/core/catalog-core-impl/filter-proxy/src/main/java/ddf/catalog/filter/proxy/GeotoolsPluginLoader.java
The previous PR (https://github.com/codice/ddf/pull/6886) fixed issues with reading shapefiles.  This PR fixes the writing of shapefiles.
@glenhein 
@derekwilhelm 
@codice/data 
@glenhein 
@derekwilhelm 
Fixes: #____ …
=> Fixes writing of shp files

catalog/core/catalog-core-impl/filter-proxy/src/main/java/ddf/catalog/filter/proxy/GeotoolsPluginLoader.java
Forward port of https://github.com/codice/ddf/pull/6888
@derekwilhelm 
@codice/data 
@derekwilhelm 
Fixes: #____
=> [2.29.x] Fixes writing of shp files (#6888)

catalog/catalog-app/pom.xml, catalog/catalog-app/src/main/resources/features.xml, distribution/test/itests/test-itests-common/src/main/java/org/codice/ddf/itests/common/AbstractIntegrationTest.java, pom.xml
This was previously upgraded in 
- https://github.com/codice/ddf/pull/6837
But was reverted during the CXF upgraded because the xalan 2.7.3 bundle did not have it's dependencies embedded, and would fail itests.
- https://github.com/codice/ddf/pull/6864
Fixes: #____ …
=> [2.29.x] Xalan upgrade

dependency-check-maven-config.xml
=> [2.29.x] Suppress spring framework CVEs

dependency-check-maven-config.xml, pom.xml
=> [2.29.x] Upgrade commons-fileupload and surpress quartz CVE

catalog/core/catalog-core-camelcomponent/pom.xml, catalog/transformer/catalog-transformer-tika-input/pom.xml, dependency-check-maven-config.xml, features/utilities/pom.xml, pom.xml
Removes bad versions of mime4j libraries causing CVEs and suppresses false positive CVEs for newer versions of mime4j.
Fixes: #____
=> [2.29.x] Removing and suppressing false positive CVEs caused by mime4j

catalog/core/catalog-core-impl/filter-proxy/pom.xml, catalog/core/catalog-core-impl/filter-proxy/src/main/java/ddf/catalog/filter/proxy/GeotoolsPluginLoader.java, catalog/spatial/csw/spatial-csw-source-common/pom.xml, catalog/spatial/csw/spatial-csw-source-common/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/CswCqlFilterTest.java, features/utilities/pom.xml, features/utilities/src/main/feature/feature.xml, pom.xml
Update geotools to handle GML files.
For testing, try to verify that other things that use geotools are not broken.
Fixes: #____
=> [2.29.x] Fix geotools to handle GML files.

dependency-check-maven-config.xml, platform/solr/solr-dependencies/pom.xml, pom.xml
- [Suppress cxf-rt-bindings-soap CVE](https://github.com/codice/ddf/commit/d3d37ec1ae15a22d9c821613b6eecd5cd976a577)
- [Remove emdedded http2-client from solr-dependencies since it can be i…](https://github.com/codice/ddf/commit/fd32cf18fb95b618a1bac7c3f6326b98ebb57bd7) 
- [Fix quartz supression](https://github.com/codice/ddf/commit/3480cd7b0d1d8ac4b0ba8421784822831a207908)
- [Upgrade logback-core](https://github.com/codice/ddf/commit/2c559e620878ef7c13211e083a214c35893fffd7)
@glenhein 
@derekwilhelm 
@jlcsmith 
Fixes: #____ …
=> [2.29.x] CVE resolutions

distribution/ddf-common/src/main/resources/etc/org.ops4j.pax.web.cfg, distribution/docs/src/main/resources/content/_managing/_configuring/environment-hardening.adoc, platform/admin/core/admin-core-insecuredefaults/src/test/resources/org.ops4j.pax.web.cfg, platform/admin/core/admin-core-insecuredefaults/src/test/resources/org.ops4j.pax.web.http.disabled.cfg, platform/admin/modules/admin-modules-application/src/test/resources/services.json, platform/admin/modules/admin-modules-configuration/src/test/resources/services.json, platform/admin/modules/admin-modules-installer/src/test/resources/services.json
This configuration has been renamed 
org.ops4j.pax.web.ssl.clientauthwanted to org.ops4j.pax.web.ssl.clientauth.wanted
Fixes: #____
=> [2.29.x] Pax config 2.29

platform/security/filter/security-filter-web-sso/src/main/java/org/codice/ddf/security/filter/websso/Activator.java
Fix for websocket issues. Looks like the .name=* context selection filter to apply out JettyAuthenticator wasn't applying it to our WABs as they never have the osgi.http.whiteboard.context.name value set. Which meant the websocket could be created (the upgrade handling is done on the default context) but subsequent calls wouldn't have an associated Authenticator and would set the session to null on the websockets when handling the request. 
Fixes: #____ …
=> [2.29.x] Context Select Pattern

catalog/rest/catalog-rest-endpoint/pom.xml, catalog/rest/catalog-rest-endpoint/src/test/java/org/codice/ddf/endpoints/rest/it/RestEndpointIT.java, distribution/ddf-catalog/pom.xml, distribution/ddf-common/src/main/resources-filtered/etc/startup.properties, distribution/ddf-common/src/main/resources/common-bin.xml, distribution/ddf/pom.xml, distribution/kernel/pom.xml, features/camel-karaf/pom.xml, features/security/src/main/feature/feature.xml, features/solr/src/main/feature/feature.xml, features/utilities/src/main/feature/feature.xml, pom.xml
Upgrades Karaf to version 4.4.7.  This also upgrades Jetty to 9.4.57.v20241219 and pax-web to 8.0.30
@alexabird 
@jlcsmith
Fixes: #____ …
=> [2.29.x] Upgrade to Karaf 4.4.7

Jenkinsfile, catalog/core/catalog-core-definitionparser/src/test/groovy/ddf/catalog/definition/impl/DefinitionParserSpec.groovy, catalog/core/catalog-core-standardframework/src/test/groovy/ddf/catalog/impl/operations/MetacardFactorySpec.groovy, catalog/core/catalog-core-urlresourcereader/src/test/java/ddf/catalog/resource/impl/URLResourceReaderTest.java, catalog/opensearch/catalog-opensearch-endpoint/pom.xml, catalog/solr/catalog-solr-commands/src/main/java/org/codice/ddf/commands/solr/BackupCommand.java, catalog/solr/catalog-solr-commands/src/main/java/org/codice/ddf/commands/solr/RestoreCommand.java, catalog/solr/catalog-solr-commands/src/test/java/org/codice/ddf/commands/solr/RestoreCommandTest.java, catalog/transformer/catalog-transformer-xml/src/test/java/ddf/catalog/transform/xml/XmlInputTransformerTest.java, dependency-check-maven-config.xml, distribution/solr-distro/pom.xml, distribution/test/itests/test-itests-common/pom.xml, distribution/test/itests/test-itests-dependencies-app/src/main/filtered-resources/features.xml, distribution/test/itests/test-itests-kernel/src/test/java/org/codice/ddf/itests/kernel/ITSynchronizedInstaller.java, features/test-utilities/src/main/feature/feature.xml, pom.xml, thirdparty/pom.xml
Update the DDF 3.x branch java and solr dependencies. 
@middlets719 
@jhunzik 
@figliold
@pklinef
Build
=> [3.x] Upgrade to Java 21 and Solr 9.3.0

catalog/core/catalog-core-impl/filter-proxy/src/main/java/ddf/catalog/filter/proxy/GeotoolsPluginLoader.java, features/utilities/src/main/feature/feature.xml
=> [2.29.x] Add default CRS classloaders for geotools

catalog/rest/catalog-rest-endpoint/src/test/java/org/codice/ddf/endpoints/rest/RESTEndpointTest.java, catalog/rest/catalog-rest-service-impl/src/main/java/org/codice/ddf/rest/service/impl/CatalogServiceImpl.java, catalog/rest/catalog-rest-service-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml, catalog/rest/catalog-rest-service-impl/src/test/java/org/codice/ddf/rest/service/impl/CatalogServiceImplTest.java, catalog/rest/catalog-rest-service/src/main/java/org/codice/ddf/rest/service/AbstractCatalogService.java
=> [2.29.x] Properly handle multiple checksum providers

catalog/core/catalog-core-impl/filter-proxy/pom.xml, catalog/core/catalog-core-impl/filter-proxy/src/main/java/ddf/catalog/filter/proxy/GeotoolsPluginLoader.java, catalog/spatial/csw/spatial-csw-source-common/pom.xml, catalog/spatial/csw/spatial-csw-source-common/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/common/source/CswCqlFilterTest.java, features/utilities/pom.xml, features/utilities/src/main/feature/feature.xml, pom.xml
backport of:
- https://github.com/codice/ddf/pull/6895
=> [2.29.9.x] Fix geotools to handle GML files. (#6895)

catalog/solr/catalog-solr-commands/pom.xml, catalog/solr/catalog-solr-core/pom.xml, distribution/solr-distro/pom.xml, pom.xml
This upgrades the solr base image to the latest version 9.8.1. 
@clockard @ahoffer @lavoywj @vinamartin 
Verify everything builds and runs normally.
=> [2.29.x] Upgrading solr to version 9.8.1

pom.xml
Upgrade codice country code converter in order to resolve a CVE in apache commons-io. 
Fixes: #____
=> [2.29.x] Upgrade codice country code converter

pom.xml
Update Apache POI to resolve a CVE in apache commons-io
A full build CI should suffice. You could also try building with a downstream project.
Fixes: #____ …
=> [2.29.x] Update Apache POI

catalog/core/catalog-core-impl/filter-proxy/pom.xml, catalog/measure/catalog-measure-api/pom.xml, distribution/test/itests/test-itests-ddf-core/pom.xml, features/utilities/pom.xml, features/utilities/src/main/feature/feature.xml, lib/geospatial/pom.xml, pom.xml
Upgrades Geotools to 29.6.
Fixes: #____
=> [3.x] Upgrade to Geotools 29.6

distribution/ddf-common/src/main/resources-filtered/etc/custom.system.properties, distribution/ddf-common/src/main/resources/bin/ddf
* Update the xml transformer factory
* fix minor syntax error in DDF script
@jlcsmith
@derekwilhelm 
Build with a downstream project and verify that metacards can be exported as XLSX. Also, try other XML formats that may use the xalan libraries. 
Fixes: #6923  …
=> 6923 Update the xml transformer factory
